### ISSUE TITLE
Image viewers like viu and chafa shows blurry images 

### ISSUE THREAD

**Issue by TroySigX** [neovim/neovim#22231] opened 2023-02-12 03:45 UTC
### Describe the bug

When using viu or chafa in neovim terminal, the image shown is very blurry, like this:
![image](https://user-images.githubusercontent.com/88051085/218291800-024b0899-99c2-42e5-9498-04c3558a23cf.png)

### Steps to reproduce

1. :new | term
2.  viu (chafa) "image-path"

### Expected behavior

Image shown should be clear, like this:
![image](https://user-images.githubusercontent.com/88051085/218291849-03442778-a993-4207-9db4-3652c00d72ed.png)

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

I dont use Vim

### Operating system/version

Endeavour OS 6.1.11-arch1

### Terminal name/version

yakuake 22.12.2

### $TERM environment variable

xterm-256color

### Installation

Arch pacman

**Comment by zeertzjq** [comment] 2023-02-12 03:53
Duplicate of #4349

**Closed by zeertzjq** 2023-02-12 03:53 UTC
Labels: bug
