### ISSUE TITLE
Support lsp completion snippet suggestions

### ISSUE THREAD

**Issue by urandom** [neovim/neovim#11982] opened 2020-03-05 08:23 UTC
I'm currently using a language server (gopls) that has started using snippets for some types of important completions. However, it appears that those are not even visible as a choice when using the built-in lsp support via omnifunc. Would it be possible to add such support, even rudimentary one for a start?

- `nvim --version`:
<pre>
NVIM v0.5.0-b353a5c
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200217-43799-1f6xoye/build/config -I/tmp/neovim-20200217-43799-1f6xoye/src -I/usr/local/include -I/tmp/neovim-20200217-43799-1f6xoye/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200217-43799-1f6xoye/build/src/nvim/auto -I/tmp/neovim-20200217-43799-1f6xoye/build/include
Compiled by viktor.kojouharov@Viktors-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-b353a5c/share/nvim"

Run :checkhealth for more info
</pre>

**Comment by mfussenegger** [comment] 2020-03-09 18:42
This is partially addressed by the [PR here](https://github.com/neovim/neovim/pull/11949) which allows plugins to take care of the snippet expansion.

**Comment by urandom** [comment] 2020-03-10 22:17
I was hoping that since neovim now provides both a completion method (omnifunc) and lsp support, there should be some support for the snippets provided by lsp via omnifunc, as they can be integral

**Closed** 2020-05-28 12:31 UTC
Labels: enhancement

**Comment by runiq** [comment] 2020-07-30 23:31
I can't get this to work with either rust-analyzer or sumneko's Lua langserver. Here's how to reproduce with rust-analyzer:

1. Have rust-analyzer in your PATH
1. Run this in a new directory:

    ```sh
    #!/bin/sh

    # Create minimal init.vim
    cat << 'EOF' > init.vim
    set omnifunc=v:lua.vim.lsp.omnifunc
    set completeopt-=preview
    set signcolumn=no
    set packpath^=$PWD
    packadd nvim-lsp
    lua << END
    require'nvim_lsp'.rust_analyzer.setup{}
    require'nvim_lsp'.sumneko_lua.setup{
      cmd = {
        "/home/ajaam/.local/opt/lua-language-server/bin/Linux/lua-language-server",
        "-E",
        "/home/ajaam/.local/opt/lua-language-server/main.lua"
      },
    }
    END
    EOF

    # Clone nvim-lsp plugin
    git clone https://github.com/neovim/nvim-lsp packages/start/nvim-lsp

    # Create rust project that exhibits the issue
    cargo new --lib foo
    cat << 'EOF' > foo/src/main.rs
    trait Foo {
      fn bar(&self, x: u64) -> f32;
    }
    struct S;
    impl Foo for S {
        // (type bar here)
    }
    EOF

    # Start nvim and place cursor at position that exhibits the issue
    nvim -u init.vim --noplugin +'call feedkeys("6Gccfn")' foo/src/main.rs
    ```

    It will place you in a minimally configured neovim instance, in insert mode, at the correct point in the file.
1. Press `<c-x><c-o>` (probably twice, don't know why) to trigger omni completion, and `<c-n>` to select the snippet
1. Observe (virtual text omitted for clarity, `|` is the cursor position):

    ```rust
    struct S;
    impl Foo for S {
        fn bar(&self, x: u64) -> f32 {^@     |
    }
    ```

The `^@` is a single null byte, and the closing brace is missing. I have to admit I have no idea what's going on here.

---

I can also reproduce with sumneko's Lua language server when completing the `for` keyword:

1. Have sumneko's langserver in your PATH
2. Use the init.vim from above
3. `nvim -u init.vim --noplugin test.lua`
4. Type `for`, invoke omni completion
5. Observe:

```lua
for key, value in pairs(t) do^@    ^@end
```

Again, the `^@` are null bytes.

**Comment by kdheepak** [comment] 2020-07-31 00:30
I'm pretty sure that is snippet autocompleted returned by the LSP server that is not being parsed correctly by the neovim lsp client.

**Comment by runiq** [comment] 2020-07-31 22:23
Sure, but I'd rather fix this than use a workaround :)

Should I file a new bug, or is re-opening this one better?

**Comment by Shougo** [comment] 2020-07-31 22:59
Hm.  Snippet parser seems implemented, but it is not perfect.
You can fix the problem.
Because it is open source project.

**Comment by urandom** [comment] 2020-08-01 07:40
@runiq 
Would it be possible to provide the raw output for that completion item from the language server?

**Comment by archseer** [comment] 2020-08-01 08:18
It's already exposed: https://github.com/neovim/neovim/pull/12204

I have a patch for it to work with ncm2/ultisnips it just wasn't merged yet

**Comment by runiq** [comment] 2020-08-23 18:04
There's now a [PR for integrating completion-nvim with snippets.nvim](https://github.com/nvim-lua/completion-nvim/pull/172). Note that there have been a lot of changes to snippets.nvim since I posted that PR, and I haven't yet had the chance to see if they break the PR.
