### ISSUE TITLE
inoremap <C-space> not work

### ISSUE THREAD

**Issue by xyz1001** [neovim/neovim#16642] opened 2021-12-14 08:32 UTC
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

no, vim 8.2 1-2824

### Operating system/version

Windows

### Terminal name/version

Windows Terminal 1.11.2921.0 + powershell 7.2 or cmd

### $TERM environment variable

screen-256color

### Installation

scoop

### How to reproduce the issue

```
nvim --clean
:inoremap <expr> <C-space> line(".")
i
<C-space>
```

### Expected behavior

insert line number when press `<C-space>` in insert mode

### Actual behavior

nothing happened

**Comment by xyz1001** [comment] 2021-12-14 08:35
Windows Terminal + WSL2(manjaro) + neovim 0.6 is ok.

**Comment by zeertzjq** [comment] 2021-12-14 08:38
May be a duplicate of #8435

**Comment by zeertzjq** [comment] 2021-12-14 08:39
Are you sure nothing happened? It doesn't even insert a space?

**Comment by xyz1001** [comment] 2021-12-14 08:43
Yes, nothing happened.

**Closed** 2021-12-14 15:16 UTC
Labels: bug, platform:windows, tui, input, closed:duplicate
