### ISSUE TITLE
Windows console TUI

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#3902] opened 2015-12-26 22:03 UTC
Redirecting from https://github.com/neovim/neovim/pull/810#issuecomment-167358288.

The purpose of this issue is to track the development of neovim TUI for Windows, so neovim can become a self-dependent, standalone and embedable console application (compiled with both MinGW and VS2015).

Currently, Windows bits are missing from https://github.com/neovim/neovim/blob/33eb33b/src/nvim/tui/.

> I found dotnet CoreCLR implementation of [console](https://github.com/dotnet/coreclr/blob/bc146608854d1db9cdbcc0b08029a87754e12b49/src/classlibnative/bcltype/console.cpp), which may provide some kind of relevance/gotchas.

Inviting @jaredpar (vsvim), @lodejard (KestrelHttpServer/libuv) and @pgavlin (coreclr) from dotnet team for comments and help. :)

cc @equalsraf

**Comment by justinmk** [comment] 2015-12-26 23:14
To be clear, it already is embeddable on Windows (for purposes like e.g. VsVim and Neovim-Qt).

**Comment by jaredpar** [comment] 2015-12-27 00:14
@justinmk is the embeddable API documented anywhere that I could take a look at?

**Comment by ZyX-I** [comment] 2015-12-27 00:23
@jaredpar API functions themselves live in src/nvim/api, documentation is compiled by doxygen and posted to https://neovim.io/doc/dev/, but you, of course, can look there directly. Also see `:h msgpack_rpc.txt`.

**Comment by justinmk** [comment] 2015-12-27 01:33
@jaredpar As @ZyX-I implied there is no formal documentation yet. 

If I were developing any sort of API-consuming application I would start with the [python client tests](https://github.com/neovim/python-client/tree/master/test) as a guide and reference. There are many [experimental applications](https://github.com/neovim/neovim/wiki/Related-projects#api-clients) built with the API already, but I am not sure how mature the [C# client](https://github.com/Pireax/neovim.cs) is.

Everything is experimental probably for the next

**Comment by jasonwilliams200OK** [comment] 2016-01-24 13:21
Seems like develop branch of C# client https://github.com/Pireax/neovim.cs/tree/develop is regularly updating. @Pireax can probably comment further. Separately, any chance we can get C# client under neovim org https://github.com/neovim, to get it first class citizenship like many others? :)

**Comment by Pireax** [comment] 2016-01-24 15:27
It currently only supports embedded neovim, not any other ways of connecting. I've been working mostly on the ui for the last few days as it was tediously slow before, I don't know yet if it's going to be just a showcase for the client or not.

**Comment by jasonwilliams200OK** [comment] 2016-04-15 20:35
@tarruda, @equalsraf, following this announcement about Ubuntu user-mode cooked into windows by Cannonical and Microsoft: https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/, would it somehow help `neovim running natively on Windows version > next_update_version`? At this point, the upcoming windows update is available for Windows Insider program (beta testing) which can be tried out in a VM.
Ideally, neovim's TUI living its own life would be the most masterful solution.

**Comment by justinmk** [comment] 2016-04-15 21:12
@jasonwilliams200OK It seems like ubuntu-on-Windows can't invoke win32 processes, so that's not going to satisfy this ticket. 

However if winpty can bring the Windows console into a Neovim GUI `:terminal`, there is no technical reason why anyone should want Neovim running in the Windows console, and I would recommend tagging this as `wontfix`.

**Comment by jasonwilliams200OK** [comment] 2016-04-16 08:45
@justinmk, thanks. I didn't knew about winpty and how it fits in with neovim. Just saw @equalsraf has recently added some commits for winpty in #810. Does this mean we don't need neovim-qt either?

>  I would recommend tagging this as `wontfix`.

I haven't checked out winpty TUI yet, but if it is already bringing Windows console to neovim, then lets close this ticket.

**Comment by justinmk** [comment] 2016-04-17 19:16
> Does this mean we don't need neovim-qt either?

We still need neovim-qt in a big way. But winpty allows `:terminal` to work in neovim-qt (or any other GUI). This is a big deal, not other Vim GUI offers this.

**Comment by bgshacklett** [comment] 2017-03-05 06:34
I'll be the first to admit that I'm not your average Windows user, but I usually have about 6-8 terminal windows open running PowerShell at any given time. I use terminal-based Vim as my editor and it's a setup that works great for me, allowing for a lot of flexibility and efficiency.

The above recommendation of running my terminals inside of my editor instead of the other way around strikes me as a very subpar solution. I've certainly never seen anyone do this on a Linux workstation. In fact, I can remember some jokes about Emacs being a lousy editor but a decent shell. Is this really the direction that NeoVim should take?

I've been very excited about this project since shortly after it was started, but I'm afraid I'll never get a chance to use it as long as I decide to remain on Windows.

**Comment by justinmk** [comment] 2017-03-05 09:06
@bgshacklett Can you explain the functional difference between using cmd.exe to run many vims vs using a single nvim to running many powershells? 

> I can remember some jokes about Emacs being a lousy editor but a decent shell. Is this really the direction that NeoVim should take?

That's the typical cliche´, but it's thoughtless. The amount of code implementing `:terminal` is comparable to the already-extant code in Vim needed to run `:shell` (which was removed from Nvim). `:terminal` is not bloat, it works well. It uses a real vterm library, not something written in VimL or elisp.

**Comment by bgshacklett** [comment] 2017-03-06 22:50
Well, to start, that essentially requires me to use nvim as my terminal emulator. I'm quite happy with ConEmu, right now and I've gotten it fairly well customized to my workflow. I can split and manage windows/tabs in it exactly the way I need, I've got all of the keyboard shortcuts configured as necessary. ConEmu is built to be a terminal emulator; can the same be said of nvim?
* Will a bug in a function/feature related to terminal emulation will be treated with the same seriousness that it would be in a project dedicated to terminal emulation?
* Would you expect that nvim would have feature parity with a dedicated terminal emulator?
* Does this project really want to take on that responsibility?
* Would you ever consider asking Linux users to use nvim as their terminal emulator instead of Terminator, Konsole, etc.?

Again, I understand that I'm not your typical Windows user, but I'd actually guess that most users who want to use nvim on Windows might fall into a similar bucket. Windows is heading more and more towards Command Line usage. In fact, Windows Nano doesn't even have a GUI, so the current plan will actually prevent nvim from ever existing in that environment.

**Comment by justinmk** [comment] 2017-03-06 23:15
> Does this project really want to take on that responsibility?

Terminal emulation is not the bugbear it's made out to be. Terminals are a commodity, an essential resource, like a pipe or a file. Mature libraries like libvterm exist.

> Would you ever consider asking Linux users to use nvim as their terminal emulator instead of Terminator, Konsole, etc.?

There's no question that it's a flaw, a regression, in Nvim, that it doesn't run in cmd.exe. I wouldn't dispute that even a little bit. 

In the meantime we need to weigh the cost of that regression vs the cost of implementing a cmd.exe TUI. And we can mitigate the cost of the regression by using `:term`, to buy time.

>  I'd actually guess that most users who want to use nvim on Windows might fall into a similar bucket.

As a long-time Windows user, I tried ConEmu many times and frankly I would be happy to use `:term` as an alternative.

> In fact, Windows Nano doesn't even have a GUI, so the current plan will actually prevent nvim from ever existing in that environment.

Nano is definitely a significant use-case.

**Comment by bgshacklett** [comment] 2017-03-07 00:26
Justin, thanks for taking the time to review my comments. I understand that time is limited and that each feature needs to be weighed against the others. That being the case, if there's anything I can do to help facilitate this one which doesn't require C or knowledge of the Console API (documentation or testing, for example, or even upping my funding contribution to the project) I'd be happy to be involved.

**Comment by justinmk** [comment] 2017-03-07 00:37
Thanks for the support. Implementing a cmd.exe TUI is a matter of adding a layer to libvterm. It's really just a matter of someone having the time and motivation. Hopefully when we announce Windows support (shouldn't be long), we'll get some more energy there.

**Comment by fischmax** [comment] 2017-03-17 16:59
Just to add another vote to the cause: I too would love to be able to run nvim on Windows in any type of terminal emulator, be it cmd.exe, mintty or even putty. Anything which also supports tmux would do!
While I know C, I'm very tight on time right now, so I'm afraid I cannot pick this one up myself. At least not for a while.

**Comment by equalsraf** [comment] 2017-03-19 01:12
In a nutshell the following points must be addressed to move this forward, or alternatives must be found:

- [ ] For the most part the TUI code is platform independent, its main dependencies are libtermkey and unibilium - but some bits like SIGSTP need to be implemented for Windows 
  - [ ] test unibilium in Windows - I've pushed a [patch](https://github.com/mauke/unibilium/pull/18) upstream so it builds with MinGW-w64, and a package into the MSYS2 MinGW packages
  - [ ] Likewise for libtermkey (I have a port [here](https://github.com/equalsraf/libtermkey)) - but check the [limitations](https://github.com/equalsraf/libtermkey/commit/b9317d6473b7a598359ebdfae5fd228bc159d0de)
- [ ] It is unclear to me what consoles would work, or if we need some helper like winpty.exe

These days I dont have much time available, but I've picked up some one of my old topic branches on this subject in case someone wants to give it a spin. It builds but I have not conducted any testing - its the [windows-tui](https://github.com/equalsraf/neovim/tree/windows-tui) branch in my personal repo.

My branch already grabs my libtermkey port, and uses the unibilium pkg from MSYS2 for the CI builds. Appveyor link [here](https://ci.appveyor.com/project/equalsraf/neovim/build/1435/job/shoxlii78lbl57kj/artifacts). I just did a quick test and it seems to produce output, but input seems broken which complicates further testing (a good way to test the output is to attach the GUI for input).

![](http://i.imgur.com/qMMSLd3.png)

**Comment by equalsraf** [comment] 2017-03-19 12:42
Followup in #6315

**Closed** 2017-05-03 10:49 UTC
Labels: platform:windows, tui
