### ISSUE TITLE
Neovim freezes while browsing SCSS file

### ISSUE THREAD

**Issue by scribu** [neovim/neovim#5252] opened 2016-08-25 15:05 UTC
- `nvim --version`:

```
NVIM v0.1.6-6-g4d253b4
Build type: Dev
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160825-74534-1h50srf/build/config -I/tmp/neovim-20160825-74534-1h50srf/src -I/tmp/neovim-20160825-74534-1h50srf/deps-build/usr/include -I/tmp/neovim-20160825-74534-1h50srf/deps-build/usr/include -I/tmp/neovim-20160825-74534-1h50srf/deps-build/usr/include -I/tmp/neovim-20160825-74534-1h50srf/deps-build/usr/include -I/tmp/neovim-20160825-74534-1h50srf/deps-build/usr/include -I/tmp/neovim-20160825-74534-1h50srf/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160825-74534-1h50srf/build/src/nvim/auto -I/tmp/neovim-20160825-74534-1h50srf/build/include
Compiled by scribu@imac

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-4d253b4/share/nvim"
```
- Vim (version: 7.4) behaves differently?

Same freezing behaviour.
- Operating system/version:

OSX El Capitan 10.11.6
- Terminal name/version:

Using iTerm2 3.0.5 (`$TERM` is set to `xterm`)
### Actual behaviour

The UI becomes unresponsive to any keypress. I have to KILL it.
### Expected behaviour

I can browse the file.
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC main.scss
/gly
```

main.scss source: https://gist.github.com/scribu/a3b44c7b23b773f25777364b99c05f3c

**Comment by justinmk** [comment] 2016-08-26 03:49
Happens with Vim 7.4.2253 as well. Looks like 7.4.2219 is the culprit. cc @chrisbra

**Comment by justinmk** [comment] 2016-08-26 04:28
I can reproduce this on Vim as far back as 7.4.1. @scribu did you test with `:syntax enable`, with a valid `$VIMRUNTIME` ?

**Comment by chrisbra** [comment] 2016-08-26 08:55
> Happens with Vim 7.4.2253 as well. Looks like 7.4.2219 is the culprit. cc @chrisbra

7.4.2219? I don't see how this is related.

Looks like a problem of the syntax file, according to `:syntime report`
cc @tpope as maintainer of the sass files

This seems to be caused by the inline 'background:url(' part of the file.

This patch fixes it for me:
```patch
diff --git a/runtime/syntax/sass.vim b/runtime/syntax/sass.vim
index 2ea0722..29ce0a9 100644
--- a/runtime/syntax/sass.vim
+++ b/runtime/syntax/sass.vim
@@ -17,7 +17,7 @@ syn cluster sassCssAttributes contains=css.*Attr,scssComment,cssValue.*,cssColor

 syn region sassDefinition matchgroup=cssBraces start="{" end="}" contains=TOP

-syn match sassProperty "\%([{};]\s*\|^\)\@<=\%([[:alnum:]-]\|#{[^{}]*}\)\+\s*:" contains=css.*Prop skipwhite nextgroup=sassCssAttribute contained containedin=sassDefinition
+syn match sassProperty "\%([{};]\s*\|^\)\zs\%([[:alnum:]-]\|#{[^{}]*}\)\+\s*:" contains=css.*Prop skipwhite nextgroup=sassCssAttribute contained containedin=sassDefinition
 syn match sassProperty "^\s*\zs\s\%(\%([[:alnum:]-]\|#{[^{}]*}\)\+\s*:\|:[[:alnum:]-]\+\)"hs=s+1 contains=css.*Prop skipwhite nextgroup=sassCssAttribute
 syn match sassProperty "^\s*\zs\s\%(:\=[[:alnum:]-]\+\s*=\)"hs=s+1 contains=css.*Prop skipwhite nextgroup=sassCssAttribute
 syn match sassCssAttribute +\%("\%([^"]\|\\"\)*"\|'\%([^']\|\\'\)*'\|#{[^{}]*}\|[^{};]\)*+ contained contains=@sassCssAttributes,sassVariable,sassFunction,sassInterpolation
```

(in other words, replace \@<= by \zs)


Best,
Christian
-- 
Man sollte immer so lange optimistisch bleiben, bis die Amerikaner von
jeder Tierart ein Paar nach Cape Canaveral treiben.

**Comment by scribu** [comment] 2016-08-26 14:24
@justinmk Yeah, I can reproduce it in Vim too now. Updated issue description.

**Comment by scribu** [comment] 2016-12-19 16:10
For the record, https://github.com/cakebaker/scss-syntax.vim does not exhibit this issue.

**Comment by mhinz** [comment] 2021-05-05 09:41
I can't seem to be able reproduce this with neither v0.4.4 nor master, so I consider this fixed unless someone says otherwise.

(I checked that the line in the syntax file didn't change as suggested by @chrisbra, but maybe it was fixed in the regexp engine itself along the way.)

**Closed by mhinz** 2021-05-05 09:41 UTC
Labels: 0.kind: bug-vim, runtime, syntax
