### ISSUE TITLE
:help text on latest master misaligned with treesitter config applied

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#20435] opened 2022-10-02 01:19 UTC
### Neovim version (nvim -v)

NVIM v0.9.0-dev-8-g01721aaa6

### Vim (not Nvim) behaves the same?

No

### Operating system/version

macOS 12.5.1

### Terminal name/version

on both iTerm2 and nvim-qt built from source

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

nvim --clean
:help cindent()

Everything looks fine. I've bisected my init.lua until discovered it was something about my treesitter config:

```lua
local configs = require('nvim-treesitter.configs')
configs.setup({
  sync_install = false,
  highlight = { enable = true },
  textobjects = {
    select = {
      enable = true,
      lookahead = true, -- jump ahead like targets.vim did
      keymaps = {
        ['af'] = '@function.outer',
        ['if'] = '@function.inner',
        ['ac'] = '@class.outer',
        ['ic'] = '@class.inner',
      },
    },
  },
  move = {
    enable = true,
    set_jumps = false, -- whether to add jump to jumplist (:jumps)
    goto_next_start = {
      [']m'] = '@function.outer',
      [']]'] = '@class.outer',
    },
    goto_next_end = {
      [']M'] = '@function.outer',
      [']['] = '@class.outer',
    },
    goto_previous_start = {
      ['[m'] = '@function.outer',
      ['[['] = '@class.outer',
    },
    goto_previous_end = {
      ['[M'] = '@function.outer',
      ['[]'] = '@class.outer',
    },
  },
  indent = { enable = true },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = '<CR>',
      node_incremental = '<CR>',
      scope_incremental = '<M-CR>',
      node_decremental = '<BS>',
    },
  },
  context_commentstring = { -- comment.nvim plugin module
    enable = true,
    enable_autocmd = false,
  },
})
```

Results in some help links getting smushed against nearby text, see image:
<img width="813" alt="Screen Shot 2022-10-01 at 8 59 16 PM" src="https://user-images.githubusercontent.com/7416158/193433866-92736aa0-f6b1-44f5-8dc7-41bd327c4825.png">

### Expected behavior

No smush. There wasn't a problem until I rebuild nvim from HEAD. It was working fine on a build from about 2 weeks ago. Any other info needed?

### Actual behavior

Smush.

**Comment by zeertzjq** [comment] 2022-10-02 01:25
Duplicate of https://github.com/neovim/tree-sitter-vimdoc/issues/23

**Closed by zeertzjq** 2022-10-02 01:25 UTC
Labels: bug
