### ISSUE TITLE
TUI/powershell: function keys F1-F5 are broken

### ISSUE THREAD

**Issue by habamax** [neovim/neovim#11773] opened 2020-01-27 06:23 UTC
- `nvim --version`:
```
NVIM v0.5.0-330-g71ee46acc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 .../projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: all of them) behaves differently? *Yes*
- Operating system/version: Win10
- Terminal name/version: Powershell

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:map <F3> :echo "hello"<CR>
<F3>
```

### Actual behaviour
Insert `C` letter

### Expected behaviour
echo `hello`

![neovim-powershell](https://user-images.githubusercontent.com/234774/73153902-85394480-40e6-11ea-9057-a51e0b1f94dd.gif)

PS, it works ok in `cmd.exe`.

**Comment by justinmk** [comment] 2020-01-27 08:12
Confirmed on win10 with 0.5 d3a9d75 , although cmd.exe also has the symptom for me.

- F1-F5 input A-E, respectively.
- F6-F12 work correctly.

Could be just a matter of tweaking [scripts/windows.ti](https://github.com/neovim/neovim/blob/master/scripts/windows.ti) which is used by [update_terminfo.sh](https://github.com/neovim/neovim/blob/master/scripts/update_terminfo.sh) 
 to generate [tui/terminfo_defs.h](https://github.com/neovim/neovim/blob/master/src/nvim/tui/terminfo_defs.h).

Needs a hero.

**Comment by erw7** [comment] 2020-01-28 06:15
> Could be just a matter of tweaking scripts/windows.ti which is used by update_terminfo.sh
to generate tui/terminfo_defs.h.

This problem occurs because `unibilium` cannot use built-in `terminfo` of `neovim`. Therefore, it cannot be solved by modifying `windows.ti`.

There are several ways to solve this problem:

1. Modify `libuv` to generate the same sequence as xterm. Specifically, fix [libuv/src/win/tty.c#L655-L659]( https://github.com/libuv/libuv/blob/1ff84206613e17e4d2242b96e3b6be7288840043/src/win/tty.c#L655-L659).
1. Change `unibilium` to use built-in `terminfo` of `neovim`.
1. Modify `driver-csi.c` of `libtermkey` to handle sequences generated by `libuv`.
1. Change `neovim` to use [`ENABLE_VIRTUAL_TERMINAL_INPUT`](https://docs.microsoft.com/en-us/windows/console/setconsolemode) instead of `TTY` emulation of `libuv`.
1. Prepare `terminfo`.

The implementation of `1.` is very simple, but I didn't do it because there is no chance of being merged upstream.

For `2.` I had previously implemented in #9094. However, they are unlikely to be incorporated due to differences in opinion with committers on how to implement. If someone implements the following https://github.com/neovim/neovim/pull/9094#discussion_r312457100, it could be merged.

I think it is difficult to implement `3.` because the generated sequence has no regularity.

I haven't tried it yet, but I think `4.` will eventually solve this problem.

Use `5.` as a workaround until one of the above solutions resolves this issue.

Specifically:

<ol>
<li>You can use <code>WSL</code>, <code>MSYS2</code> or <code>Git Bash</code>, so prepare a <code>tic</code> command anyway.
<pre>
> tic -x -o ~/.terminfo NVIM_SRC_ROOT/script/windows.ti
</pre>
</li>
<li>Set the <code>TEMINFO</code> environment variable to the directory where you output <code>terminfo</code> earlier (ex. <code>C:\MSYS64\home\erw7\.terminfo</code>).</li>
<li>Set the <code>TERM</code> environment variable to <code>vtpcon</code>.</li>
</ol>

**Comment by erw7** [comment] 2020-01-28 06:48
Incidentally, I think this is a duplicate of #8965.

**Comment by justinmk** [comment] 2020-01-28 09:49
> For `2.` I had previously implemented in #9094

sorry about the delay there. I had planned to try the unibilium patch myself, but got sidetracked...

**Comment by retzzz** [comment] 2020-03-06 06:52
NVIM v0.5.0-404-g49cd750d6 still has same issue. F1-F5 mapped to A-E in terminal nvim. My OS is win10.

**Comment by PhilT** [comment] 2020-04-13 16:28
Incidentally, I also get this problem in `cmd.exe` running with `nvim -u NORC` (Neovim 0.4.3)

**Closed** 2020-05-26 09:03 UTC
Labels: bug, input, platform:windows, tui

**Comment by yan12125** [comment] 2020-12-19 10:06
> Set the `TEMINFO` environment variable to the directory

Thanks for the instructions! Here is a typo - `TEMINFO` should be `TERMINFO`.

Looking towards to 0.5, by the way :)
