### ISSUE TITLE
Nvim don't merge file history properly if multiple instances get killed immediately

### ISSUE THREAD

**Issue by imcaizheng** [neovim/neovim#10461] opened 2019-07-09 17:52 UTC
- `nvim --version`: v0.4.0-dev
- `vim -u DEFAULTS` (version: ) behaves differently? No, it's the same.
- Operating system/version: Xubuntu 18.04.2 LTS
- Terminal name/version: fish, version 3.0.2
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`
1. Create multiple empty files and open each file with nvim in different terminals.
``` fish
for file in /tmp/file_{01,02,03}.txt
  touch $file
  xfce4-terminal --tab -x nvim -u NORC $file
end
```
2. After every nvim instance is ready, quit them all by sending SIGTERM.
``` fish
killall nvim
```
3. Open nvim and run the following vim command to check old files.
``` nvim
echo v:oldfiles
```

### Actual behaviour
Only one of the files is insert into the `v:oldfiles` list.
### Expected behaviour
Every opened files get updated in the `v:oldfiles` list, that is, when multiple instances are killed immediately nvim will merge the file history.

### Background
I use nvim for software development and often work on multiple projects. Each project is in its own terminal. And I usually poweroff my computer directly.
Currecty I have to quit each nvim instance one by one before I shutdown the machine to make sure file history get updated properly.

I use FZF plugin to search history a lot. I often found myself remember what files I edited but nvim don't.

**Comment by justinmk** [comment] 2019-07-09 18:04
Known issue, explicitly mentioned in `shada.c` source.

**Comment by glacambre** [comment] 2021-06-06 07:48
Closing as a duplicate of https://github.com/neovim/neovim/issues/10461 :).

**Closed by glacambre** 2021-06-06 07:48 UTC
Labels: bug
