### ISSUE TITLE
API for fetching history, :history items are truncated

### ISSUE THREAD

**Issue by siadat** [neovim/neovim#28034] opened 2024-03-25 23:13 UTC
### Problem

The result of :history cmd is truncated to Columns-10 as seen in https://github.com/neovim/neovim/blob/8744ee8783a8597f9fce4a573ae05aca2f412120/src/nvim/cmdhist.c#L668-L670

The :history command is used by [Telescope's command_history function](https://github.com/nvim-telescope/telescope.nvim/blob/6312868392331c9c0f22725041f1ec2bef57c751/lua/telescope/builtin/__internal.lua#L566-L567).

I encountered this issue while working on a plugin for running shell commands. The steps to reproduce the issue are outlined in https://github.com/shellpad/shellpad.nvim/issues/1

### Expected behavior

While it is nice that :history is truncating its output to look nice, it would be amazing if there was a Lua api for fetching history items, without having to parse the output of :history.

**Comment by zeertzjq** [comment] 2024-03-25 23:18
Duplicate of #23667

**Closed by zeertzjq** 2024-03-25 23:18 UTC
Labels: enhancement, api
