### ISSUE TITLE
Neovim doesn't apply colors from Airline custom themes.

### ISSUE THREAD

**Issue by ahmedelgabri** [neovim/neovim#4164] opened 2016-02-04 11:01 UTC
Some themes comes with their own airline themes like [gruvbox](https://github.com/morhetz/gruvbox), but the colors of that airline theme is not applied. This is how it looks like.

<img width="839" alt="screen shot 2016-02-04 at 10 54 32" src="https://cloud.githubusercontent.com/assets/63876/12811639/1414be2e-cb2e-11e5-814a-4c36e65a28b8.png">

And here is after applying the default airline theme `:AirlineTheme dark`

<img width="843" alt="screen shot 2016-02-04 at 10 55 12" src="https://cloud.githubusercontent.com/assets/63876/12811638/14119d3e-cb2e-11e5-859b-47a0dafe6dd3.png">

I tried also with [one-dark](https://github.com/geoffharcourt/one-dark.vim) and it still having the same problem, the theme colors were not applied.

It works in vim though so it doesn't look like an Airline issue though https://github.com/vim-airline/vim-airline/issues/989

Here is my neovim version
```
NVIM v0.1.2-462-gadd02b6
Build type: Dev
```

It's a minor thing for me, but I thought it's better to report it.

**Comment by wsdjeg** [comment] 2016-02-04 11:07
@ahmedelgabri I also encount this issue in ubuntu 14.04 gnome-terminal ,but fixed by update to gnome-terminal 3.16.2;
and what is the output in terminal
`tput colors`?

**Comment by ahmedelgabri** [comment] 2016-02-04 11:12
@wsdjeg I'm on OSX and I'm not sure if `set t_Co=256` will fix it or not while having true color enabled in neovim and tmux?

`tput colors` output is 256

**Comment by wsdjeg** [comment] 2016-02-04 11:33
maybe your terminal do not support true color?
which terminal do you use?

**Comment by ahmedelgabri** [comment] 2016-02-04 11:37
Last time I checked it was supporting and working properly with true color, and that was yesterday :) but the only thing changed today is the I updated neovim.

I'm using iTerm2 nightly `Build 2.9.20160131-nightly`

**Comment by ahmedelgabri** [comment] 2016-02-04 11:39
Here is a proof, using code from this gist https://gist.github.com/XVilka/8346728

<img width="564" alt="screen shot 2016-02-04 at 12 38 26" src="https://cloud.githubusercontent.com/assets/63876/12814031/3d8e798a-cb3c-11e5-8f37-71723a1b7e71.png">

**Comment by wsdjeg** [comment] 2016-02-04 11:39
oh my god! I just update neovim ,maybe I also has this issue,let me have a try.
I know yesterday,neovim merged a PR about has("gui_runing")

**Comment by wsdjeg** [comment] 2016-02-04 11:42
you see,mey neovim works well with true color;
version is neovim-0.1.1ubuntu1+git201602031640+2227+16~ubuntu15.10.1
![2016-02-04 19-41-06](https://cloud.githubusercontent.com/assets/13142418/12814087/676c5fb6-cb77-11e5-93bb-3fce18a20cfa.png)

**Comment by ahmedelgabri** [comment] 2016-02-04 12:02
The weird part is that in vim colors are shown _ignore the odd colors_, while in neovim it doesn't.
<img width="835" alt="screen shot 2016-02-04 at 11 43 14" src="https://cloud.githubusercontent.com/assets/63876/12812830/a5485166-cb34-11e5-9de5-f7a856609474.png">

**Comment by wsdjeg** [comment] 2016-02-04 12:08
in vim it is not true color.and it is not same as in neovim, and can you test with minivimrc,
```vim
if has('nvim')
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
end
set t_Co=256
colorscheme gruvbox
```

**Comment by ahmedelgabri** [comment] 2016-02-04 12:13
I know that it's not true color, what I meant is that it shows some colors. While in neovim nothing is shown.

My `.vimrc/init.vim` file has the exact same lines as you posted without `set t_Co=256` because I don't use vim

**Comment by wsdjeg** [comment] 2016-02-04 12:18
sorry ,I can not point out where the issue is.

**Comment by ahmedelgabri** [comment] 2016-02-04 12:56
No worries, thanks for trying :)

**Comment by justinmk** [comment] 2016-02-04 14:33
Please see https://github.com/neovim/neovim/wiki/Following-HEAD#20160204

**Closed by justinmk** 2016-02-04 14:33 UTC

**Comment by ahmedelgabri** [comment] 2016-02-04 14:40
Thanks @justinmk

**Comment by wsdjeg** [comment] 2016-02-05 12:39
@ahmedelgabri after update neovim ,I got the same issue,can you fix it?
![2016-02-05 20-37-43](https://cloud.githubusercontent.com/assets/13142418/12846613/667250a8-cc48-11e5-8423-04c85dd7cf06.png)

**Comment by ahmedelgabri** [comment] 2016-02-05 12:57
@wsdjeg Update Airline the issue was fixed today https://github.com/vim-airline/vim-airline/issues/989#issuecomment-180289312

**Comment by wsdjeg** [comment] 2016-02-05 13:04
thanks,I got it
