### ISSUE TITLE
Multihead

### ISSUE THREAD

**Issue by kovasap** [neovim/neovim#19502] opened 2022-07-25 17:50 UTC
### Feature already in Vim?

No

### Feature description

Allow multiple terminals to connect to a single nvim process, each acting as a "window".  This is primarily so that I can use my OS window system instead of neovim's builtin one.  

https://github.com/neovim/neovim/wiki/GSoC-2019-Ideas#tui-terminal-ui-remote-attachment-done seems related, but I can't find any docs for the finished feature (how to use it).  

See this thread for (I think) the same FR: https://www.reddit.com/r/neovim/comments/b6pnf7/any_way_to_share_the_same_session_between/

**Comment by justinmk** [comment] 2022-08-01 13:26
WIP at https://github.com/neovim/neovim/pull/18375

**Comment by glacambre** [comment] 2023-02-17 16:36
This is a duplicate of https://github.com/neovim/neovim/issues/2161 . The PR closest to implementing this feature is https://github.com/neovim/neovim/pull/13504 .

**Closed** 2023-02-18 13:57 UTC
Labels: enhancement, ui, tui

**Comment by neovim-discourse** [comment] 2023-12-22 17:27
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/status-of-multihead-multiple-independent-uis-attached-to-a-single-neovim-instance/4547/1

**Comment by neovim-discourse** [comment] 2023-12-22 20:01
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/status-of-multihead-multiple-independent-uis-attached-to-a-single-neovim-instance/4547/2
