### ISSUE TITLE
Bold terminal colors wrongly(?) mapped to "intense" color in 256-color terms

### ISSUE THREAD

**Issue by sscherfke** [neovim/neovim#11190] opened 2019-10-09 19:42 UTC
I am using a base16-like color theme for my terminal:

<img width="300" src="https://user-images.githubusercontent.com/511179/66513219-e22ed180-eada-11e9-96a0-1cd2ae0e8c67.png">

My Bash prompt is colored and uses a bold font for username (`[01;32m`) and hostname (`[01;34m`):

<img width="222" src="https://user-images.githubusercontent.com/511179/66513200-d5aa7900-eada-11e9-97ed-e2bff8618c59.png">

This works mostly well ([except in Konsole](https://bugs.kde.org/show_bug.cgi?id=405345), which has a problem similar to this issue).

It also worked well in neovim < 0.4 and stopped working well since neovim 0.4. :)

- `nvim --version`: 0.4.2
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: macOS 10.14, Fedora 29
- Terminal name/version: Terminal.app, iTerm, Konsole
- `$TERM`: xterm-256color
- `:set termguicolors?`: `notermguicolors`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
:term<CR>
```

### Actual behaviour

<img width="227" src="https://user-images.githubusercontent.com/511179/66513212-d9d69680-eada-11e9-97b3-d62f34bddc8b.png">

Neovim no longer uses the green/blue colors and sets the font in bold, but uses the "bright green/blue" colors (which is beige in my case).

### Expected behaviour

<img width="222" src="https://user-images.githubusercontent.com/511179/66513200-d5aa7900-eada-11e9-97ed-e2bff8618c59.png">

Use green/blue colors in bold variant (codes `1;32`/`1;34`) instead of the bright variant (codes `92`/`94`).

**Comment by sscherfke** [comment] 2019-10-09 21:04
Hm. iTerm has a similar “problem”: an (IMHO) non-sensical option “draw bold text in bold font” and uses ASCII 94 for bold 34 (blue) ... 🤔

**Comment by blueyed** [comment] 2019-10-10 00:10
> It also worked well in neovim < 0.4 and stopped working well since neovim 0.4. :)

Can you git-bisect it?

**Comment by blueyed** [comment] 2019-10-10 00:15
I can confirm this however (on master).
It appears to not use colors 16-21 altogether also.

![2019-10-10-021218_298x299_escrotum](https://user-images.githubusercontent.com/9766/66529373-7876ed80-eb03-11e9-9c19-4ab5cd4c553e.png)
![2019-10-10-021232_267x300_escrotum](https://user-images.githubusercontent.com/9766/66529409-a1977e00-eb03-11e9-8471-79c67c1584ae.png)

**Comment by blueyed** [comment] 2019-10-10 00:28
See https://github.com/neovim/neovim/issues/4696 and https://github.com/neovim/neovim/pull/10994.

**Comment by sscherfke** [comment] 2019-10-10 13:53
To me it doesn't look like these issues are related to this one:

- It worked for me in nvim 0.3.8 and stopped working in 0.4.0. Issue #4696 predates this.
- Issue #10994 handles an issue that occurs when `termguicolors` is enabled but this issue occurs when `termguicolor` is *disabled*.

Please correct me if I’m wrong.  I will test the nightly built, nonetheless, when #10994 is merged. :-)

**Comment by taylorskalyo** [comment] 2019-10-10 16:32
I also have this problem and agree that the linked issues are not related. This has to do with the way the Neovim terminal displays bold text and has nothing to do with the palette colors.

This was previously fixed (https://github.com/neovim/neovim/issues/2453), but the problem has resurfaced. Here's the commit where I believe the change happened: https://github.com/neovim/neovim/commit/e11dd1110fd018d9bd6d42460186ed69037f8651#diff-1246a4074910f78dd90d8c62350086b0L236-L240. The removal of the true color check means that `vterm_state_set_bold_highbright(state, true);` is now being called, where previously it wasn't.

**Comment by blueyed** [comment] 2019-10-10 17:47
Thanks for the input!
IIRC I've tested this with 0.3.4 and saw no difference/regression, but those are good hints for looking into it later again.

**Comment by bfredl** [comment] 2019-10-10 19:56
>  The removal of the true color check means that vterm_state_set_bold_highbright(state, true); is now being called, where previously it wasn't.

With #10994 nvim will support host terminal palette unconditionally, so we can just reflect the host terminal behavior always. So we should just remove this unconditionally (but it is not excepted behaviour for GUI either, so I don't know why it was added in the first place). I will remove it in #10994.

**Comment by bfredl** [comment] 2019-10-10 20:00
Though we could just remove `vterm_state_set_bold_highbright(state, true);` directly for 0.4.3, if it breaks expected behavior (though as I said, not sure what it was good for in the first place).

**Comment by blueyed** [comment] 2019-10-10 20:21
It is a bit older already (via https://github.com/neovim/neovim/pull/4274). /cc @DarkDefender 

As for me it still makes no difference - apparently since the 3rd step (get it from the VTerm instance) is not done (https://github.com/neovim/neovim/blob/6768c43e2129af85923ed0b4ed9f6f47be42b4fb/src/nvim/terminal.c#L225-L229), and I do not have `g:/b:terminal_color_X` defined.

**Comment by bfredl** [comment] 2019-10-10 20:27
I can only observe the issue in certain terminals. I think `pangoterm` has given me the expected colors always, even with the "highbright" thing enabled. But with gnome-terminal was broken (noticed this while testing an earlier version of #10994) and fixed with last push of #10994.

**Comment by bfredl** [comment] 2019-10-10 20:30
@blueyed the comment is a bit misleading, we always "get" the color from vterm, with the option thing we change vterm's interal table, so that vterm gives that color back.

**Comment by blueyed** [comment] 2019-10-10 20:40
My issue's root cause is that I have `TERM=xterm-256colo` in nvim's `:term`, which is wrong - it works when setting it to `TERM=tmux-256color`.  That's apparently the forced default for the terminal (https://github.com/neovim/neovim/blob/6768c43e2129af85923ed0b4ed9f6f47be42b4fb/src/nvim/eval.c#L18241).

**Comment by blueyed** [comment] 2019-10-10 20:44
My `colors-table` script is using `tput setaf` and that results in different output based on `$TERM`, but  apparently libvterm only understands one of it correctly then?
```
% (TERM=tmux-256color; tput setaf 7; echo white; tput setaf 15; echo bright-white) | cat -A
^[[37mwhite$
^[[97mbright-white$

% (TERM=xterm-256color; tput setaf 7; echo white; tput setaf 15; echo bright-white) | cat -A
^[[37mwhite$
^[[315mbright-white$
```

**Comment by bfredl** [comment] 2019-10-10 20:45
@blueyed but the terminal child process is interacting with nvim/libvterm, which aims at implementing xterm behavior, the "outer" terminal is irrelevant here (and could not exist, if you run :term inside GUI nvim). Though perhaps it should be just "xterm", both xterm and pangoterm on my system uses just "xterm" even if it supports 256 colors (and truecolors).

**Comment by blueyed** [comment] 2019-10-10 20:50
@bfredl 
Ok, then it's a matter of xterm also not displaying "tput setaf 15" as bright white, but having to use bold white there.  Kitty distinguishes between color 15 (bright white), and bold itself.
I guess the libvterm switch then only translates 7+bold => bright white, but still does not handle 15 as a color itself.

**Comment by blueyed** [comment] 2019-10-10 20:51
Using "bold" to mean "bright" is actually a (common) misuse.  See https://github.com/kovidgoyal/kitty/issues/197.

**Comment by bfredl** [comment] 2019-10-10 21:05
> Using "bold" to mean "bright" is actually a (common) misuse.

With #10994 we punt on that decision to host terminal when TUI is used. The remaining question (terminfo issue is separate issue) is if someone expects this behavior in GUI, i e specifically when using 16-color program inside `:term` in GUI. My suggestion is to remove it (as follows from the TUI fix) and see later if someone complains loudly enough.

**Comment by blueyed** [comment] 2019-10-10 21:07
So I guess libvterm should handle `38 - 315` also for color 8-15 (according to "its" TERM/infocmp).
But 38 gets handled as "Foreground colour alternative palette" already, which I cannot find in the xterm's infocmp output.  Also 39 gets handled as "// Foreground colour default".
According to the info from TERM everything starting with X and ending in a number should be handled to set the fg color.  This also includes colors over 15.  /cc @leonerd 

Removing `vterm_state_set_bold_highbright(state, true);` certainly makes sense (or setting it to false explicitly).

**Comment by blueyed** [comment] 2019-10-10 21:21
Oh sorry.. I've had some borked (outdated? / from experimenting) xterm-256color terminfo file in `~/.terminfo`:
```
 λ m@o¹✗❯❯ TERM=xterm-256color infocmp -A ~/.terminfo.out -B /usr/share/terminfo -d                                                                        🐍? (neovim@3.7.4)
comparing xterm-256color to xterm-256color.
    comparing booleans.
        ccc: F:T.
    comparing numbers.
        colors: 8, 256.
        pairs: 64, 65536.
    comparing strings.
        initc: NULL, '\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\'.
        ka1: '\EOw', NULL.
        ka3: '\EOy', NULL.
        kb2: '\EOu', '\EOE'.
        kc1: '\EOq', NULL.
        kc3: '\EOs', NULL.
        mgc: '\E[?69l', NULL.
        oc: NULL, '\E]104\007'.
        rs1: '\Ec', '\Ec\E]104\007'.
        setab: '\E[4%p1%dm', '\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m'.
        setaf: '\E[3%p1%dm', '\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m'.
        setb: '\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m', NULL.
        setf: '\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m', NULL.
        smglr: '\E[?69h\E[%i%p1%d;%p2%ds', NULL.
```
As you can see `setaf` is different there, and it works as expected now.

I can confirm that removing `vterm_state_set_bold_highbright(state, true);` works as expected also: i.e. it uses color 7 in bold, not color 15.

**Comment by blueyed** [comment] 2019-10-10 21:36
@bfredl 
> Though perhaps it should be just "xterm", both xterm and pangoterm on my system uses just "xterm" even if it supports 256 colors (and truecolors).

Just for completeness: apparently not: I was using a TERM=xterm terminfo file above (see my update at the end).

**Closed** 2019-10-10 22:00 UTC
Labels: bug, tui

**Comment by sscherfke** [comment] 2019-10-11 20:55
I have just tried the latest nightly and the issue seems to be solved. Thanks a lot for the quick fix! :-)
