### ISSUE TITLE
Install failed by chocolate "the remote server returned an error : (404) Not Found"

### ISSUE THREAD

**Issue by mu-yu** [neovim/neovim#7652] opened 2017-11-29 02:40 UTC
- `nvim --version`:
- Vim (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
choco install neovim -y
```

### Actual behaviour
install failed with logs below:
```ps
Attempt to get headers for https://github.com/neovim/neovim/releases/download/v0.2.1/nvim-win64.zip failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/neovim/neovim/relea
ses/download/v0.2.1/nvim-win64.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned a
n error: (404) Not Found."
Downloading neovim 64 bit
  from 'https://github.com/neovim/neovim/releases/download/v0.2.1/nvim-win64.zip'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/neovim/neovim/
releases/download/v0.2.1/nvim-win64.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server retur
ned an error: (404) Not Found."
The install of neovim was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\neovim\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
```

### Expected behaviour

update install info in chocolate since 0.2.2 has been released so many days.

**Comment by jamessan** [comment] 2017-11-29 02:59
Duplicate of #7635

**Closed by jamessan** 2017-11-29 02:59 UTC
