### ISSUE TITLE
bring back :hardcopy and print options

### ISSUE THREAD

**Issue by michael-odonovan** [neovim/neovim#23103] opened 2023-04-15 09:18 UTC
### Problem

This is my main way of printing for myself and for some people I am sharing code with for teaching purposes. I have the options setup to easily print files with line numbers, straight from vim.
Why was this feature removed?
I use this daily and am very disappointed with this change.
Could you please reconsider?

### Expected behavior

bring back :hardcopy and print options

**Comment by clason** [comment] 2023-04-15 09:22
Duplicate of #21629

**Closed by clason** 2023-04-15 09:22 UTC
Labels: enhancement

**Comment by lewis6991** [comment] 2023-04-15 09:36
>  Why was this feature removed?

- We don't want this feature in core, it is only something we inherited from Vim.
- It was completely broken on Windows (#10244)
- It did not work with Treesitter or extmarks (only legacy `:syntax`)
- It consisted of roughly 9k LOC that nobody wanted to, or has, maintained

**Comment by pkail** [comment] 2024-05-28 18:18
It worked perfectly and was extremely useful.  There are workarounds, but they don't as well.
