### ISSUE TITLE
TUI: corrupt display after resize + termguicolors, sign column, colorscheme

### ISSUE THREAD

**Issue by alexozer** [neovim/neovim#7861] opened 2018-01-16 06:37 UTC
- `nvim --version`: NVIM v0.2.3-448-gc06995b34
- Vim (version: 8.0) does not appear to have this problem.
- Operating system/version: Arch Linux
- Terminal name/version: Gnome terminal 3.26.2 (also occurs on termite and urxvt)
- `$TERM`: xterm-256color

### Steps to reproduce:

To summarize, I believe this only occurs when all four of these conditions are met:

* Truecolor is enabled
* A colorscheme is set
* The sign column is showing (sample vimrc shows a dummy one, I also reproduced with gitgutter and ale)
* Commands are loaded from file (won't work if entered in command mode manually)
* Window resized

In detail:

1) Write this to a separate vimrc named `bug-vimrc` or something:

```vim
set termguicolors
colorscheme desert
sign define dummy
execute 'sign place 9999 line=1 name=dummy buffer=' . bufnr('')
```

2) Open it with `nvim -u bug-vimrc --noplugin`
3) Enter the following into the buffer:

```
short line

loooooooooong line
```

4) Place your cursor on the middle line
5) Shrink the size of the terminal horizontally (perhaps by opening a window on the right if you use a tiling WM)
6) Watch the first line in the buffer become corrupted

### Expected behaviour
First line stays the same.

**Comment by justinmk** [comment] 2018-01-16 08:30
> Shrink the size of the terminal horizontally

Just a guess, maybe https://github.com/neovim/neovim/pull/7862 fixes it?

**Comment by justinmk** [comment] 2018-01-16 08:33
Repro'd. CTRL-L is a workaround.

**Comment by alexozer** [comment] 2018-01-16 09:09
To better describe the "corruption", it appears to be the result of rendering the line in the buffer below the cursor as the first visible line of the display, and then rendering the first line of the buffer on top of it. Therefore, it wouldn't be visible if the line below the cursor was shorter than the first line of the display.

For example:

```
AAAA
_
BBBBBBBB
```

Should produce:

```
AAAABBBB
_
BBBBBBBB
```

**Comment by davidgranstrom** [comment] 2018-01-16 11:33
I have also experienced this issue, and here is what I think is another way to reproduce it. It seems to be significant that something is occupying some columns on the left side of the editor screen (like the signcolumn in the original bug report).

Save this content as bug-vimrc or similar

```
set termguicolors
colorscheme desert
```

Open nvim and type the following commands. 

```
nvim -u bug-vimrc --noplugin

:help | only | set number
10G
```

Then resize the terminal to see the corruption on the first/top line of the terminal screen.


I'm using iTerm 3.0.15, NVIM v0.2.3-414-g9ddeb6e18

**Comment by alexozer** [comment] 2018-01-16 19:32
@davidgranstrom I was able to reproduce your steps on my setup too.

So, it seems like line numbers can stand in place of the sign column to reproduce. Loading this vimrc alone will cause corruption:

```vim
set termguicolors
colorscheme desert
set number
```

**Comment by sim590** [comment] 2018-01-29 23:40
I have been having this issue for a while. I can confirm that the following minimal vimrc triggers the problem.

```vim
set termguicolors
colorscheme desert
set number
```

My nvim version is v0.2.2 (debian buster (testing) branch package).

**Comment by bennyyip** [comment] 2018-02-06 14:38
To be more accurate, the first line of the buffer is replaced by the next line when window resized.  

Take the following file as an example, line 1 becomes "daa" if cursor is on line 2, and becomes "dbbbb" if cursor is on line 3.
```
d

aaa
bbbbb
ccccc
```

**Comment by justinmk** [comment] 2018-02-06 14:41
We have clear steps to repro. Don't need more confirmations, just someone to spend their time fixing the bug.

**Comment by bennyyip** [comment] 2018-02-06 14:47
I am trying to fix this, as my first issue.

**Comment by bennyyip** [comment] 2018-02-07 19:15
I figured out the what cause this bug. In the `cursor_goto` function of https://github.com/neovim/neovim/blob/master/src/nvim/tui/tui.c#L578, an optimization makes this happen. When I commented the two lines in the if branch, the bug got fixed.  

Since I don't understand exactly how this optimaztion works, idk how to fix it properly. Or should I simply remove the optimized code?

```C
if (0 == col ? col != grid->col :
      row != grid->row ? false :
      1 == col ? 2 < grid->col && cheap_to_print(ui, grid->row, 0, col) :
      2 == col ? 5 < grid->col && cheap_to_print(ui, grid->row, 0, col) :
      false) {
    // Motion to left margin from anywhere else, or CR + printing chars is
    // even less expensive than using BSes or CUB.

    // THIS BRANCH CAUSES THE BUG
    unibi_out(ui, unibi_carriage_return);
    ugrid_goto(grid, grid->row, 0);


  } else if (col > grid->col) {
      int n = col - grid->col;
      if (n <= (row == grid->row ? 4 : 2)
          && cheap_to_print(ui, grid->row, grid->col, n)) {
        UGRID_FOREACH_CELL(grid, grid->row, grid->row,
                           grid->col, col - 1, {
          print_cell(ui, cell);
        });
      }
}
```

**Comment by justinmk** [comment] 2018-02-07 23:55
@bennyyip Great! Note that on latest HEAD you can `:set writedelay=1` to observe redraw behavior.

> Or should I simply remove the optimized code?

No, at least we could check if sign column is showing in the `if` condition, or something like that. But it would be best to understand the condition (maybe rewrite it: it's hard to read) and fix it.

**Comment by frangio** [comment] 2018-04-11 19:25
Any progress on this?

**Comment by justinmk** [comment] 2018-04-11 19:26
see https://github.com/neovim/neovim/pull/7985#issuecomment-366831770

Need someone to take over that PR, it seems to have stalled. I'm not going to spend my time on it.

**Comment by antonstakhouski** [comment] 2018-07-31 16:40
This bug is still present in 0.3.1 version. This bug was fixed by1adb01c120d04bdbf25cd4ea6151ecd5f2de3a72 commit and it doesn't appear in the master anymore. So i think, that issue can be closed.
Ping @justinmk .

**Comment by bfredl** [comment] 2018-07-31 17:34
I'm not sure it is fixed, I can still reproduce with https://github.com/neovim/neovim/commit/1adb01c120d04bdbf25cd4ea6151ecd5f2de3a72 (which  doesn't really change TUI impl, only the way screen.c communicates with tui.c), when the terminal is increased in size vertically to the extent that the topline changes.

**Comment by bfredl** [comment] 2018-07-31 18:04
I'm pretty sure the problem is with clear, rather than anything with cursor position. Because when `Normal` group is reset, cl is used to clear the entire screen and it works as expected (and is also much smoother), but with `hi Normal guibg=...` tui.c doesn't actually clear the screen, it first rather painstakingly puts a space character in every screen cell (or it _should_, but probably misses the first row if tui.c idea of number of rows is out of sync with the terminals idea), and then immediately afterwards redraws every text cell with actual contents.

For a non-bce terminal (and we assume bce is broken unless `$XTERM_VERSION`) we should instead do as such: when screen is cleared turn off drawing. Then on the next flush: repaint the entire screen, with both "cleared" and "content" cells at once, with no cursor movement at all (unless for ambiwidth).

Alternatively: just stop clearing the grid on resize, it serves no purpose. Instead actually _define_ what happens with the grid when it is resized, and add scrolls as needed. (so that either top-line or bottom-line can be preserved, whatever we want).

**Closed** 2018-08-15 11:02 UTC
Labels: +workaround, bug, complexity:low, display, good first issue, help wanted, tui
