### ISSUE TITLE
Neovim does not resize itself when launched as initial command for terminal.

### ISSUE THREAD

**Issue by rojoxiw** [neovim/neovim#11330] opened 2019-11-03 17:19 UTC
- `nvim --version`: 0.4.2
- Operating system/version: Void Linux 5.3.8
- Terminal name/version: Alacritty 0.3.3

### Steps to reproduce:
1) Launch Alacritty, then type `nvim`, hit Return;
2) Launch Alacritty, enter command `alacritty --command nvim`, hit Return;

### Actual behaviour
In first case nvim is sized correctly.
In second case nvim has default size, which is independent of Alacritty window size.

### Expected behaviour
Neovim expected to be sized incorrectly in second case.

**Comment by KillTheMule** [comment] 2019-11-03 17:24
2. is what I do with xterm and st  (don't have the versions handy), and it works, so I'd assume it's a problem with alacritty. Not sure how to diagnose, though...

**Comment by justinmk** [comment] 2019-11-04 02:06
Terminal needs to send SIGWINCH

**Comment by kchibisov** [comment] 2019-11-08 07:18
FWIW `alacritty` sends `SIGWINCH` on resize through `ioctl` (`TIOCSWINSZ`). The one thing we noticed is that when `neovim` has long startup time (like 100+ ms on my system, due to the amount of plugins) it fails to resize correctly, however if we wait a bit (e.g. untill window is mapped) before sending resize events - everything is fine. In case `neovim` has low startup time everything is also fine (e.g. `nvim -u NONE`).

If we need some additional steps or we're doing it wrong then let us know about it, however the only app which has such problem is `vim`/`neovim`, and it was also reported that folks can repro the exact same bug in other terminal emulators like urxvt. I personally can repro it with `kitty` and `termite`. Our original bug for this problem https://github.com/jwilm/alacritty/issues/2817.

**Comment by henrik-farre** [comment] 2019-11-09 09:36
Sounds like it might be related to https://github.com/neovim/neovim/issues/11066 ?

**Comment by kchibisov** [comment] 2019-11-09 10:04
I'm not sure about it. The root cause could the fact, that `alacritty` has a bunch of resizes during startup. So this is the winsizes we're setting through ioctl during startup. `neovim` stucks to a first value, and others seems to be completely ignored.
```
WIN SIZE: winsize { ws_row: 54, ws_col: 145, ws_xpixel: 1600, ws_ypixel: 1200 }
WIN SIZE: winsize { ws_row: 96, ws_col: 174, ws_xpixel: 1916, ws_ypixel: 2121 }
WIN SIZE: winsize { ws_row: 96, ws_col: 174, ws_xpixel: 1916, ws_ypixel: 2121 }
```

**Comment by justinmk** [comment] 2019-11-10 01:48
> `neovim` stucks to a first value, and others seems to be completely ignored.

That's necessary to avoid hysteresis, or at least it used to be. Maybe since 533d4a36ec03 we don't need to worry about that now.

**Comment by lifranc** [comment] 2020-01-24 07:34
> That's necessary to avoid hysteresis, or at least it used to be. Maybe since [533d4a3](https://github.com/neovim/neovim/commit/533d4a36ec03626e9d796ef7e2a9aa3c0e1ce7bf) we don't need to worry about that now.

Where should I look to give that a try?

**Comment by justinmk** [comment] 2020-01-26 02:23
> Where should I look to give that a try?

https://github.com/neovim/neovim/commit/533d4a36ec03626e9d796ef7e2a9aa3c0e1ce7bf should be a big hint.

**Comment by jonhoo** [comment] 2020-03-11 16:13
I think there's a more general issue around resizing here, as I sometimes see neovim get confused about the terminal size if I open/close other windows in a tiling window manager, even if it's been running just fine for a while.

**Comment by jonhoo** [comment] 2020-03-11 16:16
Over in https://github.com/tmux/tmux/issues/2064#issuecomment-597726208, a tmux dev theorized that maybe neovim is installing its `SIGWINCH` handler too late at startup — could that be the source of this?

**Comment by jonhoo** [comment] 2020-03-11 17:48
Digging some more, it appears that neovim sometimes gets confused if the number of rows changes by a small amount and then back again. In particular, this came up for me because my status bar ([polybar](https://github.com/polybar/polybar/)) seems to take a short amount of time before it "registers" its height when moving between virtual desktops. When switching between virtual desktops, this causes a stream of `SIGWINCH` like:
```
2020-03-11 13:39:51 signal: 53 213
2020-03-11 13:39:52 signal: 51 213
2020-03-11 13:39:53 signal: 53 213
2020-03-11 13:39:53 signal: 51 213
```
The "true" size here is 51x213, but should neovim miss or suppress any of these, it could easily end up with the wrong size. This sounds a lot like the "hysteris prevention" @justinmk refers to above.

**Comment by matheusqueirozzabin** [comment] 2020-04-29 11:48
Anyone have some temporary workaround for this? I'm tired of have to resize manually every time I open a screen.

**Comment by helmecke** [comment] 2020-04-29 12:22
> Anyone have some temporary workaround for this? I'm tired of have to resize manually every time I open a screen.

Using `mhinz/neovim-remote` and starting neovim with `nvr` fixes the issue for me.

**Comment by andrewferrier** [comment] 2020-11-08 20:06
I have found that if one runs `kill SIGWINCH <pid_of_nvim_session>`, that fixes a NeoVim instance which has opened up as the wrong size. Presumably it might be possible to write an autocmd for NeoVim itself which runs this against the same instance, but I haven't tried this yet.

**Comment by ByteHamster** [comment] 2020-11-08 21:18
Nice idea @andrewferrier! Adding the following to my `init.vim` fixed the issue:

```
autocmd VimEnter * :silent exec "!kill -s SIGWINCH $PPID"
```

**Comment by andrewferrier** [comment] 2020-11-09 17:23
@ByteHamster great, good job. Worth noting this only works once neovim has loaded, so it looks a little flickery as the resize happens, and if anything blocks NeoVim loading (e.g. a prompt), it's "smaller" at that stage; but this is a good enough workaround for me for now. Thanks.

**Comment by trooms** [comment] 2020-11-30 06:08
> 
> 
> Nice idea @andrewferrier! Adding the following to my `init.vim` fixed the issue:
> 
> ```
> autocmd VimEnter * :silent exec "!kill -s SIGWINCH $PPID"
> ```

After adding this to my init.vim I get

Error detected while processing VimEnter Autocommands for "*"
E488 : trailing characters

**Comment by drasill** [comment] 2020-11-30 08:01
Thank @ByteHamster , it's working well.

I was also using `alacritty -e sh -c "sleep 0.1 && nvim"` as a workaround.

**Comment by maisiliym** [comment] 2020-12-19 06:13
> ```
> autocmd VimEnter * :silent exec "!kill -s SIGWINCH $PPID"
> ```

 This hack helps, but the bug is still apparent *sometimes*. There seem to be a timing issue at play. setup: Termite + sway + master-nvim

**Comment by camoz** [comment] 2021-07-04 19:10
Just for the record, after updating from 0.4.4 to 0.5 this has gotten worse for me. Neovim almost always has the wrong size when starting directly in a terminal emulator like `termite -e nvim`. Before it was more like only 1% of the time.

**Comment by pavanbhat1999** [comment] 2021-07-13 02:29
@camoz Exactly I am also facing the same issue even if I had put 
` autocmd VimEnter * :silent exec "!kill -s SIGWINCH $PPID" `
This in my init.vim

**Comment by figsoda** [comment] 2021-07-13 02:33
@pavanbhat1999 `autocmd VimEnter * silent exec "!kill -s SIGWINCH" getpid()` has been working for me

**Comment by pavanbhat1999** [comment] 2021-07-13 03:25
@figsoda both the command works but not all the times.Approximately 70% of the time it works.But its reall annoying sometimes.

**Comment by zdmgmail** [comment] 2021-07-18 03:10
@figsoda  @pavanbhat1999 

I tried 
```
autocmd VimEnter * :silent exec "!kill -s SIGWINCH $PPID"
or
autocmd VimEnter * silent exec "!kill -s SIGWINCH" getpid()
```

I problem is 
```
export MANPAGER='nvim +Man!'
alacritty -e man "libcurl-tutorial(3)"
```
I use `nnoremap yp :let @+ = expand("%:p:~")<cr>` to copy file path, 
if  `man "libcurl-tutorial(3)"` then copy path, get `man://libcurl-tutorial(3)`, 
if  `alacritty -e man "libcurl-tutorial(3)"` , then copy path, get `man://libcurl-tutlibcurl)`

sometime I resize terminal and want to use `:e` refresh, then `man://libcurl-tutlibcurl)` will casue problem

**Comment by camoz** [comment] 2021-08-17 10:50
I can confirm that
`autocmd VimEnter * :silent exec "!kill -s SIGWINCH $PPID"`
only fixes the issue (for me) in 50-70% of the cases.

If it's a timing issue it might also be hardware dependent (I'm on a rather old laptop).

**Comment by camoz** [comment] 2021-08-17 11:09
Quick followup: Adding a small timeout in neovim before sending `SIGWINCH` seems to work around the issue 100% of the time. For me even 20 ms are enough:
```
autocmd VimEnter * :sleep 20m
autocmd VimEnter * :silent exec "!kill -s SIGWINCH $PPID"
```
@maisiliym @pavanbhat1999 You might find this interesting.

**Comment by glyh** [comment] 2021-08-17 12:13
Same issue

**Comment by reportaman** [comment] 2021-11-30 00:28
Seems like this could be related to https://github.com/tmux/tmux/issues/2981#issuecomment-981545602

**Comment by glyh** [comment] 2021-11-30 01:01
@reportaman , I don't use tmux and have the same issue (alacritty, sway,arch)

**Comment by neovim-discourse** [comment] 2022-03-27 16:54
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/neovim-doesnt-open-fullscreen/2221/2

**Comment by erw7** [comment] 2022-04-02 11:11
There are probably two bugs.

The first bug is that the following code, no longer needed by 402b4e8fbe32c2ee1de0c39ab84c43b600db0495, remains.

https://github.com/neovim/neovim/blob/af1b61f342618aa8d27c6e1dcbb0e360920ca89e/src/nvim/tui/tui.c#L1481-L1489

The second bug is that `tui_grid_resize` may change the size of the host terminal when multiple `SIGWINCH` occur. I have confirmed that this actually happens in the following way using nvim with `DLOG` added.

```vim
nvim --clean
:lua vim.loop.fs_write(2, '\27[8;40;150t\27[8;35;140t', -1, nil) vim.loop.sleep(500) vim.loop.fs_write(2, '\27[8;30;130t', -1, nil)
:set columns? lines?  
  columns=140                                                                                                                     
  lines=35
Press ENTER or type command to continue
```

The logs were as follows.

```
DEBUG 2022-03-28T12:11:37.688 5899  sigwinch_cb:508: call sigwinch_cb
DEBUG 2022-03-28T12:11:37.695 5899  sigwinch_cb:508: call sigwinch_cb
DEBUG 2022-03-28T12:11:38.190 5899  tui_grid_resize:948: call tui_grid_resize, got_winch: true, width: 140, height: 35
DEBUG 2022-03-28T12:11:38.191 5899  tui_grid_resize:948: call tui_grid_resize, got_winch: false, width: 140, height: 35
DEBUG 2022-03-28T12:11:38.191 5899  sigwinch_cb:508: call sigwinch_cb
DEBUG 2022-03-28T12:11:38.191 5899  tui_grid_resize:948: call tui_grid_resize, got_winch: true, width: 130, height: 30
DEBUG 2022-03-28T12:11:38.199 5899  sigwinch_cb:508: call sigwinch_cb
DEBUG 2022-03-28T12:11:38.199 5899  tui_grid_resize:948: call tui_grid_resize, got_winch: true, width: 140, height: 35
```

The first bug can be fixed by simply removing the corresponding code. I think the easiest way to fix the second bug would be to change `got_winch` from a boolean to an integer and make it a counter.

**Comment by isak102** [comment] 2022-04-25 22:16
> Quick followup: Adding a small timeout in neovim before sending `SIGWINCH` seems to work around the issue 100% of the time. For me even 20 ms are enough:
> 
> ```
> autocmd VimEnter * :sleep 20m
> autocmd VimEnter * :silent exec "!kill -s SIGWINCH $PPID"
> ```
> 
> @maisiliym @pavanbhat1999 You might find this interesting.


This one is even better:
```
autocmd VimEnter * call timer_start(20, { tid -> execute(':silent exec "!kill -s SIGWINCH $PPID"')})
```
The reason this is better is because this creates a timer for the event in the background, so it doesn't halt the rest of the startup for 20ms. This way you don't affect the startup time whatsoever, if you dont use the timer function then you add +20ms to every startup

**Comment by potamides** [comment] 2022-04-26 13:30
If you want to use the new lua api for autocmds you can do it like this. This also has the (probably negligible) benefit of not having to rely on external processes:

```lua
vim.api.nvim_create_autocmd({"VimEnter"}, {
  callback = function()
    local pid, WINCH = vim.fn.getpid(), vim.loop.constants.SIGWINCH
    vim.defer_fn(function() vim.loop.kill(pid, WINCH) end, 20)
  end
})
```

**Closed** 2022-07-04 20:09 UTC
Labels: bug, tui, status:has-plan, startup
