### ISSUE TITLE
LSP[rust_analyzer] received `end` message with no corresponding `begin`

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/neovim#19157] opened 2022-06-29 20:52 UTC
### Neovim version (nvim -v)

v0.8.0-dev+1976-g6f6286e4f

### Language server name/version

rust-analyzer 0.0.0 (b74e96f50 2022-06-26)

### Operating system/version

macOS Monterey v12.4

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
vim.cmd('syntax off')
vim.cmd('filetype off')
vim.cmd('filetype plugin indent off')

local cache_dir = vim.env.HOME .. '/.cache'
local dein_dir = cache_dir .. '/dein'
local dein_repo_dir = dein_dir .. '/repos/github.com/Shougo/dein.vim'

if not string.match(vim.o.runtimepath, '/dein.vim') then
	if vim.fn.isdirectory(dein_repo_dir) ~= 1 then
		os.execute('git clone https://github.com/Shougo/dein.vim ' .. dein_repo_dir)
	end
	vim.o.runtimepath = dein_repo_dir .. ',' .. vim.o.runtimepath 
end

if vim.call('dein#min#load_state', dein_dir) ~= 1 then
    return
end

vim.call('dein#begin', dein_dir)

vim.call('dein#add', 'rust-lang/rust.vim')
vim.call('dein#add', 'neovim/nvim-lspconfig')
vim.call('dein#add', 'hrsh7th/nvim-cmp')
vim.call('dein#add', 'hrsh7th/cmp-nvim-lsp')

vim.call('dein#end')
vim.call('dein#save_state')


require'lspconfig'.rust_analyzer.setup {}

local cmp = require('cmp')

cmp.setup {

  mapping = {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({
      select = true,
    }),
  },

  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
  }),
}

vim.cmd('syntax on')
vim.cmd('filetype on')
vim.cmd('filetype plugin indent on')
```

### Expected behavior

The following procedure should not cause LSP[rust_analyzer] received `end` message with no corresponding `begin`.

1. `$ cargo new sample`
2. `$ cd sample`
3. `$ nvim`
4. Run `:call dein#update()` command.
5. Close neovim.
6. `$ nvim src/main.rs`

### Actual behavior

LSP[rust_analyzer] received `end` message with no corresponding `begin` will occur.

### Screen shot

![スクリーンショット 2022-06-30 6 38 46](https://user-images.githubusercontent.com/3197942/176549738-abd22e42-972c-41dd-96d4-0e57d6b90921.png)

**Comment by justinmk** [comment] 2022-06-29 21:35
Related? https://github.com/neovim/neovim/issues/15844

**Comment by nabezokodaikon** [comment] 2022-06-29 21:38
Hmmm... I am not sure.

**Comment by nabezokodaikon** [comment] 2022-06-29 21:41
However, it is certain that it occurs even in the latest version of rust-analyzer.

**Comment by justinmk** [comment] 2022-06-29 22:27
The error message seems clear. What leads you to believe this is a Nvim bug and not a bug in the lsp server?

**Comment by nabezokodaikon** [comment] 2022-06-30 03:08
I didn't think that far, are you saying it could be a bug in nvim-lspconfig?

**Comment by VeroAsghar** [comment] 2022-06-30 11:13
I rolled back rust-analyzer to the 5-30 release and the error message no longer shows. One of the releases between now and then would have caused the error to show up.

**Comment by amahmod** [comment] 2022-06-30 15:22
> I rolled back rust-analyzer to the 5-30 release and the error message no longer shows. One of the releases between now and then would have caused the error to show up.

This solved the issue for me too

**Comment by nabezokodaikon** [comment] 2022-07-01 00:43
Since https://github.com/rust-lang/rust-analyzer/tree/5bb123d97000a85c7a909fe1ab0b981d54c967f2 occurred and https://github.com/rust-lang/rust-analyzer/tree/401a71d1d7e99cd5563253da77d4b293de9b6731 did not, it looks like something happened with https://github.com/rust-lang/rust-analyzer/tree/5bb123d97000a85c7a909fe1ab0b981d54c967f2 commit.

**Comment by seandewar** [comment] 2022-07-01 10:10
Looks to be fixed now since https://github.com/rust-lang/rust-analyzer/pull/12660

**Closed by seandewar** 2022-07-01 10:10 UTC
Labels: bug, status:blocked-external, lsp

**Comment by nabezokodaikon** [comment] 2022-07-01 10:55
Confirmed. Thanks for letting me know.

**Comment by winkee01** [comment] 2022-07-01 12:56
Same issue

**Comment by OliverAThunes** [comment] 2022-07-02 23:23
I am also getting this issue now.
