### ISSUE TITLE
Neovim writes filename to screen

### ISSUE THREAD

**Issue by matthiasbeyer** [neovim/neovim#19372] opened 2022-07-15 07:06 UTC
### Neovim version (nvim -v)

0.6.1, 0.7.x

### Vim (not Nvim) behaves the same?

didn't check, do not have vim installed

### Operating system/version

NixOS 22.05.git.9e96b1562d6 (Quokka)

### Terminal name/version

konsole 22.04.1

### $TERM environment variable

xterm-256color

### Installation

system package manager

### How to reproduce the issue

`:w` in neovim, writes the path to the current file to the screen.

### Expected behavior

Normal screen visible.

### Actual behavior

![simplescreenrecorder-2022-07-15_08 57 55](https://user-images.githubusercontent.com/427866/179169811-a241432f-47a9-4c46-8e84-df5aad0a89e1.gif)

This happens in zellij, tmux and without any of these.
I just happened to have zellij open when recording above screen.

---

I also want to say that I'm not 100% sure whether this an issue with neovim or something else, but I have to start somewhere, right? And because it happens without tmux and zellij, I think those are not an issue here.

I quickly tested it in xterm as well and also got some screen artifacts. Not as many as in Konsole (as in the screenshot), but some. So I'm not 100% sure whether xterm has the same issue here or not, but I guess it has.

Maybe someone knows something or a way to debug this further.

**Comment by nullchilly** [comment] 2022-07-15 07:11
Did you check `:autocmd BufWritePost`?

**Comment by zeertzjq** [comment] 2022-07-15 07:16
Does this issue have if you `set notitle`?

**Comment by matthiasbeyer** [comment] 2022-07-15 07:18
> Does this issue have if you set notitle?

It seems that the issue vanishes if I `:set notitle`!

**Comment by justinmk** [comment] 2022-07-15 12:28
duplicate of https://github.com/neovim/neovim/issues/18573

**Closed by justinmk** 2022-07-15 12:28 UTC
Labels: bug, environment, tui, display
