### ISSUE TITLE
Disabling treesitter doesn't restore the proper syntax value

### ISSUE THREAD

**Issue by michelesr** [neovim/neovim#21836] opened 2023-01-16 13:30 UTC
### Describe the bug

When treesitter gets disabled, you end up with no syntax highlighting at all -> `:set syntax?` returns `syntax=on` rather then e.g. `syntax=c` for a C file.

### Steps to reproduce

- run `nvim --clean a.c`
- check that `:set syntax?` returns `syntax=c`
- run `:lua vim.treesitter.stop()`
- check that `:set syntax?` returns `syntax=on`

### Expected behavior

The value of syntax should be restored to the proper syntax for the filetype, e.g. `syntax=c` for a C file.

### Neovim version (nvim -v)

NVIM v0.8.2

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

ArchLinux

### Terminal name/version

alacritty with tmux

### $TERM environment variable

tmux-256color

### Installation

Arch Linux community package

**Comment by lewis6991** [comment] 2023-01-16 13:36
This is already fixed in v9.0-dev and backported to 0.8.x (#21358)

**Comment by clason** [comment] 2023-01-16 13:36
Not for me it isn't.

**Comment by lewis6991** [comment] 2023-01-16 13:36
I can't reproduce.

**Comment by lewis6991** [comment] 2023-01-16 13:38
Since you can produce the issue, are you able to debug?

**Comment by clason** [comment] 2023-01-16 13:38
Not yet.

**Comment by lewis6991** [comment] 2023-01-16 14:23
So with this init.lua:

```lua
vim.api.nvim_create_autocmd('FileType', {
  callback = function()
    print('DEBUG g:syntax_on=', vim.g.syntax_on)
    print('DEBUG syntax=', vim.bo.syntax)
    vim.treesitter.start()
  end
})
```

Which prints:
```
DEBUG g:syntax_on= 1
DEBUG syntax=
```

So with this, it appears `syntax` never gets set, and hence `vim.treesitter.stop()` does the correct thing and restores `syntax= `.

**Comment by clason** [comment] 2023-01-16 15:20
Thank you, that is exactly the situation we are looking at -- which I believe should work without explicit `syntax on`.

**Comment by lewis6991** [comment] 2023-01-16 17:11
> which I believe should work

What exactly should work? Can you provide an exact test vector for me to work towards?

If the user never set `syntax on`, why should `vim.treesitter.stop()` then set it.

**Comment by clason** [comment] 2023-01-16 17:19
> What exactly should work? Can you provide an exact test vector for me to work towards?

Exactly your example: enabling treesitter via a filetype autocommand, then manually disabling it.


> If the user never set syntax on, why should vim.treesitter.stop() then set it.

If the user never set `syntax on`, Neovim will still do it for them during initialization. I would expect to be in the same state regardless of whether I
1. do nothing;
2. start then stop `vim.treesitter`.


Basically, this line here:
https://github.com/neovim/neovim/blob/ef89f9fd46ab591183b7f59f31f5a2e55f7a526b/runtime/lua/vim/treesitter/highlighter.lua#L91

doesn't do what it is meant to do without manually setting `syntax on` (which is discouraged since Neovim enables syntax automatically). I don't know a better approach yet, though.

**Comment by michelesr** [comment] 2023-01-16 18:05
Just found out that `on` should be capitalized to be used as special flag for syntax, so e.g. `:set syntax=ON` (from `:h 'syntax'), setting that to `on` seems to set the wrong syntax for the file. This is probably irrelevant since you're aiming at restoring the original syntax string anyway.

**Closed** 2023-01-17 16:56 UTC
Labels: bug, syntax, highlight, treesitter
