### ISSUE TITLE
Win 32/x64 installation

### ISSUE THREAD

**Issue by TarunavBA** [neovim/neovim#15760] opened 2021-09-23 08:50 UTC
### Feature already in Vim?

No 

### Feature description

@nono it would be nice if `neovim`. Installation is more easier.

**Comment by TarunavBA** [comment] 2021-09-23 08:59
> ### Feature already in Vim?
> No
> 
> ### Feature description
> @nono it would be nice if `neovim`. Installation is more easier.

Probably a `msi` installer?

**Comment by justinmk** [comment] 2021-09-23 12:56
@TarunavBA you've now made two low-effort requests. This wastes our time.

Duplicate of https://github.com/neovim/neovim/issues/6649

**Closed by justinmk** 2021-09-23 12:56 UTC
Labels: enhancement, platform:windows

**Comment by itsmeboy0** [comment] 2022-04-09 03:36
@TarunavBA as of #17390, this has been fulfilled.
