### ISSUE TITLE
autocmd terminal insert freezing

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#4100] opened 2016-01-25 23:00 UTC
https://youtu.be/OdC3SCMhwFc

Let me know if the quality sucks but essentially these autocmd commands cause freezes when exiting a terminal and issuing a command. I think its a bug because I neovim freezes but not sure.

``` vim
autocmd BufWinEnter,WinEnter term://* startinsert
autocmd BufLeave term://* stopinsert
```

**Comment by justinmk** [comment] 2016-01-26 03:03
From the video I didn't see where the issue happened. Also can't reproduce locally. We need minimal steps to reproduce using `nvim -u NONE` (without plugins). Otherwise it's just guesswork or very time-consuming.

**Comment by nhooyr** [comment] 2016-01-26 03:20
Add those autocmds. Then create vertical splits and try closing them really fast by pressing x and then enter. It should start freezing.

**Comment by nhooyr** [comment] 2016-01-26 03:24
Never mind I figured it out, nothing wrong with neovim. That binding is wrong and for some reason the error wasn't coming up with my plugins and stuff enabled.

**Comment by nhooyr** [comment] 2016-01-26 03:38
Sigh, auto correct was too strong for me. I had the mapping above written wrong because my macbook autocorrected `stopinsert` to `stop insert`. I thought the mapping was wrong and that was the problem but nope. So as I said open a bunch of vertical split terminals. And start spamming x/enter. It'll start freezing.

**Comment by justinmk** [comment] 2019-04-08 23:17
closed by
https://github.com/neovim/neovim/issues/7807 
https://github.com/neovim/neovim/issues/7254

**Closed by justinmk** 2019-04-08 23:17 UTC
Labels: :terminal, performance
