### ISSUE TITLE
Fix bdelete

### ISSUE THREAD

**Issue by aditya-sadawarte** [neovim/neovim#11754] opened 2020-01-24 14:33 UTC
It's an old problem since vim,
buffers deleted with :bdelete refreshes the window and removes split screens which is really annoying.
the solution to this is having a plugin (like vim-bbye). can this be built-in to neovim for convenience?

**Comment by envp** [comment] 2020-01-24 17:34
To kick off some discussion, lets come up with some consistent expected behaviour, or some option that specifies which file to fall back to. Some things to consider:

- The most recently used (but hidden) buffer
- Run a function to pick a file (Eg, if for some reason I want to run Ctrl-P or FZF after every `:bdelete`)
- What if the buffer loaded points to resource that no longer exists?

**Comment by aditya-sadawarte** [comment] 2020-01-24 18:00
The usual default behaviour for single-window is to jump to the previous buffer, for multiple windows, it sounds logical to follow the same pattern.
* the whole layout should be preserved. unless the user specifically quits a window, it shouldn't be deleted.
* if no previous file is found, the usual [no name] empty buffer should be used.
* since buffers are not specific to a window, I don't actually think it's possible to keep track of the buffers for a particular window, hence, jumping to the previous buffer sounds like the next logical step.

I would like to hear your thoughts about this.

**Comment by sudo-nice** [comment] 2020-01-25 04:46
I like the way [Sayonara] handles this:

    * mark current buffer
    * current window is the only window in current tabpage?
      true  => is there only one tabpage?
               true  => are there any other active buffers?
                        true  => switch to most recently used active buffer
                        false => Is g:sayonara_confirm_quit set?
                                 true  => confirm whether to quit Vim
                                 false => quit Vim
               false => close tabpage
      false => close window
    * delete marked buffer unless it is shown in any other window

[Sayonara]: https://github.com/mhinz/vim-sayonara

**Comment by justinmk** [comment] 2020-01-25 23:02
Duplicate of https://github.com/neovim/neovim/issues/2434

Do not leave comments there without first reading and understanding the entire discussion .

**Closed by justinmk** 2020-01-25 23:02 UTC
Labels: enhancement
