### ISSUE TITLE
Quickfix list size increases when splitting

### ISSUE THREAD

**Issue by Tranquility** [neovim/neovim#3608] opened 2015-11-05 20:37 UTC
This only happens if vertical splits are used.

Steps to reproduce:
- `start nvim`
- `:vsp`
- `:copen`
-  `execute 'bot split'`
-  `:q`
- `execute 'bot split'`
- `:q`

Everytime you split the quickfix list gets bigger.

**Comment by mhinz** [comment] 2015-11-05 21:22
For what it's worth, the behaviour is the same with Vim. The problem seems to be how `:copen` is handled, because just using `:split` seems to work as intended.

**Comment by justinmk** [comment] 2018-09-05 21:17
> Everytime you split the quickfix list gets bigger.

The quickfix _window_ "stays" bigger after the first `:q`, but thereafter alternating `:bot split` and `:q` don't seem to change the window. 

The layout behavior that I observe is just Vim's standard window layout logic (cursor placement affects it as well).

    NVIM v0.3.2-376-g4c65f355d7fd

**Comment by rf-** [comment] 2018-09-06 05:57
@justinmk Thanks for looking into this ticket! I'm confused by what you mean here:

> The quickfix window "stays" bigger after the first :q, but thereafter alternating :bot split and :q don't seem to change the window.

Here's a recording of what I see when I follow the repro steps in the ticket: https://asciinema.org/a/BF8YXy8IGitHJqz6LQS9AQ61A

Is that different from what you're seeing?

**Comment by rf-** [comment] 2018-09-06 06:04
For comparison, here's what happens using `sp` instead of `copen` as suggested by @mhinz:

https://asciinema.org/a/bALwTLxPIYtf8GBuBn81PV13H

This seems like the behavior I'd expect from the quickfix window too.

**Comment by justinmk** [comment] 2018-09-07 06:06
It happens because the quickfix window has `winfixheight` set. If you `:set nowinfixheight` immediately after the `:copen` step, the window height only "grows" once. Alternatively the behavior can be simulated with a regular `:split` by first setting `winfixheight` in that window.

**Comment by rf-** [comment] 2018-09-07 20:34
I see, thanks for the context. I can see why opening the split again "grows" the quickfix window if it has `winfixheight`, but it seems like the buggy/surprising part is what happens when the bottom split closes. If the quickfix window has `winfixheight` set, shouldn't it stay the same height instead of growing downward to fill the gap left by the bottom split closing?

**Comment by justinmk** [comment] 2018-09-07 21:04
That's how it works with a 2-horizontal-split layout (as mentioned in the original report here), but not vertical. 

I don't know if it's intentional, but it should be reported to https://github.com/vim/vim/ .

**Comment by hiberabyss** [comment] 2019-02-19 07:50
This issue has already been reported in https://github.com/vim/vim/issues/2998

**Closed** 2019-03-30 21:20 UTC
Labels: bug-vim, vim-patch
