### ISSUE TITLE
:belowright terminal not honoring buffer split (v0.5.0-dev+1428-g997a9c879)

### ISSUE THREAD

**Issue by mrkz** [neovim/neovim#14875] opened 2021-06-21 21:14 UTC
**Nvim version**
```
$ nvim --version
NVIM v0.5.0-dev+1428-g997a9c879
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.5.0~dev.1428.g997a9c879/x86_64-redhat-linux-gnu/config -I/builddir/build/BUILD/neovim-0.5.0~dev.1428.g997a9c879/src -I/usr/include -I/usr/include/lua-5.1 -I/builddir/build/BUILD/neovim-0.5.0~dev.1428.g997a9c879/x86_64-redhat-linux-gnu/src/nvim/auto -I/builddir/build/BUILD/neovim-0.5.0~dev.1428.g997a9c879/x86_64-redhat-linux-gnu/include
Compiled by mockbuild

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```
**Operating system/version**
```
 $ cat /etc/os-release
NAME=Fedora
VERSION="34 (Workstation Edition)"
```
**Terminal name/version**
```
gnome-terminal Version 3.40.2 for GNOME 40
$ zsh --version
zsh 5.8 (x86_64-redhat-linux-gnu)
```
**$TERM**
```
 $ echo $TERM
xterm-256color
```

[x] `vim -u DEFAULTS` (version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 10 2021 00:00:00)
Included patches: 1-2956) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

:belowright terminal
```

### Actual behaviour
`:belowright terminal` does not honor the horizontal split between the current buffer and open terminal
[![asciicast](https://asciinema.org/a/IOo9mpbHcCTGBB6nva6EXmazD.svg)](https://asciinema.org/a/IOo9mpbHcCTGBB6nva6EXmazD)

### Expected behaviour
`:belowright terminal` to create a horizontal split placing the terminal on the buffer below.
[![asciicast](https://asciinema.org/a/1WKPaERapUiLS2ffbg0AFoiKo.svg)](https://asciinema.org/a/1WKPaERapUiLS2ffbg0AFoiKo)

**Comment by seandewar** [comment] 2021-06-21 23:09
This isn't a bug.
`:belowright` only takes effect if the command it's being used on opens a new split.
Nvim's `:terminal` implementation differs from (and even pre-dates) Vim's and does not split by default.

You can instead use a command like `:bel sp +te` instead.

**Comment by glacambre** [comment] 2021-06-26 11:29
Yep, not a bug, let's close this :)

**Closed by glacambre** 2021-06-26 11:29 UTC
Labels: bug
