### ISSUE TITLE
Terminal will be stuck when quit with a background nvim

### ISSUE THREAD

**Issue by SolaWing** [neovim/neovim#11629] opened 2019-12-29 03:19 UTC
- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/config -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/include
编译者 brew@Mojave.local

Features: +acl +iconv +tui
See ":help feature-compile"
```
- `vim -u DEFAULTS` (version: ) behaves differently? NO
- Operating system/version: mac 10.15.2 (19C57)
- Terminal name/version: terminal
- `$TERM`: login with fish or default bash

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
<ctrl-z> to background
<cmd-w> or <cmd-q> to quit terminal
terminal wil be stuck, or be stuck when next open.
open Activity, nvim is still exist with parent process is (null)

```

### Expected behaviour
nvim exits normally.

### Other Tip:
system vim is ok.
macvim is ok.
<ctrl-d> to exit is ok.
when in fish, enter bash and nvim, quit and kill both bash and nvim is ok

**Comment by justinmk** [comment] 2019-12-29 12:21
Sounds like a duplicate of https://github.com/neovim/neovim/issues/8075

**Closed by justinmk** 2019-12-29 12:21 UTC
Labels: bug

**Comment by svenper** [comment] 2020-01-29 14:36
I think this might be different (likely related) because it happens for me on linux, not just macos.

```
alacritty -e nvim
```
Press Ctrl+Z

Original vim avoids this problem by disabling the Ctrl-Z shortcut in this scenario.
