### ISSUE TITLE
macOs Catalina: Neovim from homebrew fails to start

### ISSUE THREAD

**Issue by ludbek** [neovim/neovim#11411] opened 2019-11-17 08:24 UTC
- `nvim --version`:

```
NVIM v0.4.3
Build type: Release
/Users/user
Vim: Finished.
E970: Failed to initialize lua interpreter
```

- `vim -u DEFAULTS` (version: ) behaves differently?
It opens without issues.

- Operating system/version: macOs Catalina, 10.15.1 (19B88)

- Terminal name/version: iterm2 build: 3.3.6

- `$TERM`: -bash: xterm-256color: command not found

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
Above command works without any issue.



```

### Actual behaviour
Neovim opens and quits promptly.
It can briefly see "Vim Finished"

### Expected behaviour
Neovim should have  stayed open.

**Comment by clason** [comment] 2019-11-17 11:54
Works for me (downloaded release as well as built HEAD via homebrew). How did you install?

**Comment by h-michael** [comment] 2019-11-17 13:04
It may be a LuaJIT or clang or gcc problem because lua interpreter initialization failed.

**Comment by clason** [comment] 2019-11-17 13:31
Good point: is a lua(jit) interpreter installed (e.g., `brew install luajit`)?

**Comment by clason** [comment] 2019-11-17 13:43
Interesting. After de- and then reinstalling `luajit` via homebrew, I can reproduce this. It seems to be an upstream problem with the `luajit` formula from homebrew (possibly due to https://github.com/Homebrew/homebrew-core/commit/fb3befb4f211debc5911be8c91712313c605bbd0).

**Comment by clason** [comment] 2019-11-17 16:05
Upstream issue: https://github.com/LuaJIT/LuaJIT/issues/521 

The problem is that the latest stable version 2.0.5 does not work on Catalina -- 2.1.0-beta3, which is bundled with neovim, works. However, homebrew does not provide builds of beta versions, and changes the neovim build to use system libraries. You can either

1. wait until the patch is backported (or applied by homebrew) and a new bottle is released;
2. `brew install luajit --HEAD` (linking `/usr/local/bin/luajit-2.1.0-beta3` to `luajit` somewhere in your path) and ` brew install neovim -s` (or `--HEAD`).

**Comment by ludbek** [comment] 2019-11-19 00:07
Unlinking `luajit` and installing it from head solves the problem. Thank you all.

Not sure if I should close this issue.

**Comment by clason** [comment] 2019-11-19 14:41
@ludbek I'm currently working with the maintainer to backport the fix from 2.1 beta to the 2.0.5 formula (the fix works locally, just has to be tested and committed to homebrew-core). I'd suggest waiting until that is merged before closing so people hitting the same issue see what's happening.

**Comment by clason** [comment] 2019-11-21 11:05
@ludbek The updated bottle just got added to homebrew; if you `brew reinstall luajit`, it should work now out of the box.

**Closed** 2019-11-21 16:42 UTC
Labels: platform:macos, waiting-on-external

**Comment by comatory** [comment] 2021-01-08 08:29
I am installing `neovim` on Catalina using `--fetch-HEAD` via `brew` and unfortunately this broke for me. Even removing `luajit` and installing `brew install luajit --fetch-HEAD` ends up with this error.

**Comment by comatory** [comment] 2021-01-08 08:32
OK apologies, I have followed this advice https://github.com/neovim/neovim/issues/13529#issuecomment-744275940 and it worked for me. I forgot to unlink the `luajit` dependency.
