### ISSUE TITLE
Syntax highlight fails when code is not loaded on screen

### ISSUE THREAD

**Issue by anhangaba** [neovim/neovim#12438] opened 2020-06-04 16:12 UTC
- `nvim --version`: NVIM v0.5.0-545-g6f4f38cd5
- `vim -u DEFAULTS` (version: 8.2) behaves differently? Yes
- Operating system/version: Arch Linux
- Terminal name/versioxterm-kittyn: kitty 0.17.4
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

New file with vim `syntax=vim`
```vim
augroup group1
augroup END

augroup group2
augroup END

"
" Add padding larger than window size
"
```
Scroll until only the second `augroup END` in on screen:
![2020-06-04-130751_659x272_scrot](https://user-images.githubusercontent.com/12538856/83780804-093aa480-a664-11ea-86cb-41b958106587.png)

Ask to redraw with CTRL-L:
![2020-06-04-130754_659x272_scrot](https://user-images.githubusercontent.com/12538856/83780821-0d66c200-a664-11ea-9f53-2f8d46f587b8.png)

Note: The command were run with `vim -u NORC`. The colorscheme is `default`, the non standard colors was configured in the terminal.

### Expected behaviour
To behave like vim.

**Comment by glacambre** [comment] 2020-06-04 16:30
Might be a duplicate of https://github.com/neovim/neovim/issues/12274 ? 
Could you try to reproduce this with `:syntax sync fromstart`?

**Closed** 2020-06-04 16:36 UTC
Labels: bug
