### ISSUE TITLE
'import type' messes up highlighting

### ISSUE THREAD

**Issue by champignoom** [neovim/neovim#13135] opened 2020-10-22 14:04 UTC
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: Manjaro 20.1.2
- Terminal name/version: xfce4-terminal 0.8.9.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC whatever.ts
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

Input the following code:
```typescript
import type { f } from "g";
let x;
1;
"abc";
```

### Actual behaviour
Everything after `{ f }` until the end of file is rendered in the same color (blue here).
### Expected behaviour
The highlighting should be normal.

**Comment by erw7** [comment] 2020-10-24 04:50
I can't reproduce it. Is it correctly highlighted for `import type`? Also, is it normal to highlight non-Typescript file types?

**Comment by champignoom** [comment] 2020-10-24 09:35
![Untitled](https://user-images.githubusercontent.com/66909116/97078236-fa409880-15ea-11eb-9a16-fcb104ffc476.png)
Until you said you couldn't reproduce it, I've thought this was somewhat expected since the [syntax file](https://github.com/neovim/neovim/blob/master/runtime/syntax/typescriptcommon.vim#L4) was last modified in nov 2019, 3 months before [typescript 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html) was released where `import type` was first introduced.

Neovim 0.5.0 AppImage behaves the same here. Other filetypes are highlighted normally.

**Comment by erw7** [comment] 2020-10-25 01:24
Sorry. I was mistaken because the actual and expected behavior is reversed. I can reproduce it in my environment. Normally, neovim does not make any changes to the runtime files on its own. The original file seems to have come from https://github.com/HerringtonDarkholme/yats.vim, so why not report the problem to the upstream issue tracker?

Ref vim/vim#4864.

**Comment by champignoom** [comment] 2020-10-25 10:18
Thanks for the pointer, but still it seems that the problem has already been [solved](https://github.com/HerringtonDarkholme/yats.vim/commit/976d10ee24ce4d8790bcd80b3f7c6b8bbc9ec76d) in the upstream. It's just not synchronized by either vim or neovim.

**Comment by erw7** [comment] 2020-10-26 04:27
The `runtime/syntax/README.txt` contains the following

> If you are the maintainer of a syntax file and make improvements, send the new version to Bram@vim.org.

So you'll need to have the upstream maintainer send the changes to Bram@vim.org. However, the Maintainer of `runtime/syntax/typescript.vim` is Bram Moolenaar, Herrington Darkholme, so he may update it.

CC @brammool, @HerringtonDarkholme

**Comment by champignoom** [comment] 2020-10-26 06:04
I've created [an issue](https://github.com/HerringtonDarkholme/yats.vim/issues/210#issue-729267011) in the upstream repo.
Thanks for the information.

**Comment by brammool** [comment] 2020-10-26 17:22
Let me know if a new flat-file version of the syntax was made, then I'll include it with Vim.

**Comment by HerringtonDarkholme** [comment] 2020-10-27 06:05
I have updated the merged syntax file in https://github.com/HerringtonDarkholme/yats.vim/commit/0635a855ff1c56073d5e372001a3843e15c8aedb

**Comment by chrisbra** [comment] 2020-10-27 09:46
@HerringtonDarkholme  please send the new syntax files to Bram (or create a PR).

**Comment by brammool** [comment] 2020-10-27 18:15
> I have updated the merged syntax file in https://github.com/HerringtonDarkholme/yats.vim/commit/0635a855ff1c56073d5e372001a3843e15c8aedb

Thanks, I'll take over the changes in the typescriptcommon.vim file.
I'll update the date in the header.

This is still setting 'iskeyword', it might work better to use
":syn iskeyword".

I changed the HiLink command to use "hi def link".

-- 
hundred-and-one symptoms of being an internet addict:
137. You decide to stay in college for an additional year or two,
     just so you can have the free Internet access.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mhinz** [comment] 2021-05-05 11:00
Fixed on master (probably due to https://github.com/neovim/neovim/pull/14424)

**Closed by mhinz** 2021-05-05 11:00 UTC
Labels: bug, runtime, syntax
