### ISSUE TITLE
vim.opt.cmdheight = 0 breaks move line(s)

### ISSUE THREAD

**Issue by Skeeledon** [neovim/neovim#30890] opened 2024-10-21 16:46 UTC
### Problem

Platform: Windows 11
Nvim Version: 0.10.2 - Commit: 8b98642
Plugins: None (Disabled all to test)
Mappings: 
`vim.keymap.set('v', 'J', [[:m '>+1<CR>gv]])
vim.keymap.set('v', 'K', [[:m '<-2<CR>gv]])`

Settings:
`vim.opt.cmdheight = 0`

Video: https://gyazo.com/4de3b54135acfbb8785f215704e97b9d

### Steps to reproduce

1. Install Neovim.
2. Add init.lua and include the following three lines
`vim.keymap.set('v', 'J', [[:m '>+1<CR>gv]])
vim.keymap.set('v', 'K', [[:m '<-2<CR>gv]])
vim.opt.cmdheight = 0`
3. Reload config
4. Attempt to highlight multiple lines and move

Notes:
- Doing the actions manually seem to not replicate the bug
- Even just binding and performing ':m '<-2<CR>' causes the selected history to be removed. Manually performing gv fails to select anything.
- Removing the cmdheight being 0 fixes the problem

### Expected behavior

Binding and using ':m '<-2<CR>' should not destroy select history

### Nvim version (nvim -v)

0.10.2 commit 8b98642

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 11 Build 22631.4317

### Terminal name/version

Powershell 7.4.5

### $TERM environment variable

undefined

### Installation

Choco

**Comment by zeertzjq** [comment] 2024-10-21 22:48
Duplicate of #20635

**Closed by zeertzjq** 2024-10-21 22:48 UTC
Labels: bug
