### ISSUE TITLE
A better default colorscheme :D

### ISSUE THREAD

**Issue by sp1n0r** [neovim/neovim#13722] opened 2021-01-09 01:34 UTC
Vim/Neovim's default scheme has a weird choice of colors... If for the sake of tradition default's colorscheme must not be changed then maybe create something like `modern_default` colorscheme

**Comment by adrian5** [comment] 2021-01-11 00:39
I think there was some kind of (possibly stagnant) brainstorming effort by a few (n)vim developers to standardize and modernize the colorscheme situation. It's a git repo, but I can't remember its name right now.

I definitely agree that there should be a better default. Something like Monokai would be a typical default. I do think such a default theme should be maximally compatible though, and look OK on 16-color terminals.

**Comment by sp1n0r** [comment] 2021-01-11 12:04
Well if you remember it again, don't forget to mention it here :)

Yeah it could be Monokai or something new as long as it works well on every terminal even those with 16 colors. Ideally I would like a brand new colorscheme, something that people would see and say, that's neovim :D

**Comment by clason** [comment] 2021-01-11 12:36
Summarizing comments on Gitter:

* It's not clear what the benefit is of putting effort into changing the default color scheme that virtually nobody uses. (As far as I see it, the main purpose of the default color scheme is to have something that's guaranteed to work on any supported platform, no matter how ancient.)
* "Weird" is very much in the eye of the beholder.
* It's a bit iffy to promote an existing color scheme to default over the heads of others. Why this and not one of the many other, equally good, ones?

That being said, 0.5 could be an opportunity to modernize the color scheme by either adding tree-sitter highlight groups as first-class citizens or by using @bfredl's temas. (At the same time, colors can be changed, of course, if there is consensus on improvement.) The main benefit wouldn't be prettier out-of-the-box look, but a template for other color schemes to use the new neovim features.

**Comment by sp1n0r** [comment] 2021-01-11 12:40
Any improvement on the default colorscheme sounds good to me

**Comment by chrisbra** [comment] 2021-01-11 13:24
> I think there was some kind of (possibly stagnant) brainstorming effort by a few (n)vim developers to standardize and modernize the colorscheme situation. It's a git repo, but I can't remember its name right now.

Better default colorschemes has been a long standing issue for Vim. Currently, some people are concentrating efforts here: 
https://github.com/vim/colorschemes

I am pretty sure, any support is appreciated.

**Comment by adrian5** [comment] 2021-01-11 18:46
Yes, that's the one I was thinking about.

**Comment by glacambre** [comment] 2021-01-19 17:05
I think this issue is a duplicate of https://github.com/neovim/neovim/issues/793 .

**Comment by teto** [comment] 2021-01-30 13:51
Indeed going to close this as a duplicate. Let's see what https://github.com/vim/colorschemes comes up with.

**Closed by teto** 2021-01-30 13:51 UTC
Labels: 2.status: waiting-on-vim, enhancement
