### ISSUE TITLE
Certain symbols not being accessible on a fresh install of macOS Sonoma

### ISSUE THREAD

**Issue by enidisepic** [neovim/neovim#25487] opened 2023-10-03 09:50 UTC
### Problem

I recently upgraded from my M1 MacBook Air to an M2 Pro MacBook Pro. Before setting all my tooling up I upgraded to macOS sonoma.

However, when cloning my config and running NeoVim I get this error when using `noice.nvim`:
```
dlsym(RTLD_DEFAULT, syn_attr2entry): symbol not found
```

I do think this is an issue with NeoVim itself as this seems to be related to a LuaJIT issue rather than how the plugin does things.

Versions between the M1 MacBook and M2 Pro one match fully within homebrew.

I do apologize if I falsely opened this report and it is not related to NeoVim or a classic user error. I do hope to get pointers in the right direction nonetheless. :)

### Steps to reproduce

```bash
# Start with a fresh install of macOS Sonoma
# Install homebrew
brew install neovim
# Create minimal config that uses Packer and noice.nvim (or any other script that tries running the aforementioned FFI call)
nvim
```

### Expected behavior

It should not throw any errors.

### Neovim version (nvim -v)

0.9.2 Release (LuaJIT 2.1.0-beta3)

### Vim (not Nvim) behaves the same?

no, vim 9.0 (the one Mac comes with)

### Operating system/version

macOS 14 Sonoma

### Terminal name/version

iterm2 3.4.20

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment] 2023-10-03 09:58
Duplicate of #25295

**Comment by dundargoc** [comment] 2023-10-03 09:59
I think this has been fixed on master: https://github.com/neovim/neovim/pull/25274

I don't think there's much we can do except to wait for neovim v0.10/v0.9.3.

**Closed by zeertzjq** 2023-10-03 09:58 UTC
Labels: bug

**Comment by enidisepic** [comment] 2023-10-03 10:11
@dundargoc thanks a lot! I'll give that a try and follow up :)

**Comment by enidisepic** [comment] 2023-10-03 10:44
Update: it works with the 0.10.0 pre-release binary 😄 
Thank you a lot for pointing me in the right direction!
