### ISSUE TITLE
With `:set cursorline` enabled, some lines are displayed incorrectly when editing files containing characters from a lot of different languages.

### ISSUE THREAD

**Issue by 1sixth** [neovim/neovim#16010] opened 2021-10-13 09:17 UTC
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

no, `vim/8.2.3441`

### Operating system/version

Arch Linux

### Terminal name/version

`alacritty/0.9.0`, `gnome-terminal/3.40.3`, `konsole/21.08.2`, `rxvt-unicode/9.26`, `xfce4-terminal/0.8.10`

### $TERM environment variable

`alacritty`, `xterm-256color`, `xterm-256color`, `rxvt-unicode-256color`, `xterm-256color`

### Installation

system package manager (pacman)

### How to reproduce the issue

1. `nvim --clean /usr/share/applications/chromium.desktop`[^1].
2. Use `j/k` to navigate, everything seems normal.
3. Type `:set cursorline`, then use `j/k` to navigate again.
4. When going up with `k`, some lines are rendered incorrectly

![2021-10-13_17:05:54](https://user-images.githubusercontent.com/67363572/137103806-1585f262-2def-4836-813b-c84884a3e746.png)

[^1]: This file is also available at <https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/installer/linux/common/desktop.template>

### Expected behavior

All lines looks correct.

![2021-10-13_17:16:23](https://user-images.githubusercontent.com/67363572/137104453-47579b97-3dbc-4042-885e-eefc89df380b.png)

### Actual behavior

Some lines looks wrong.

`kitty/0.23.1` is the only terminal eumlator I tried that renders correctly. So I think this is more like a `neovim` issue rather than any `terminal emulator` issue.

**Comment by zeertzjq** [comment] 2023-07-22 03:39
Duplicate of #12364

**Closed by zeertzjq** 2023-07-22 03:39 UTC
Labels: bug, tui, display
