### ISSUE TITLE
drawing issue

### ISSUE THREAD

**Issue by xiyaowong** [neovim/neovim#17648] opened 2022-03-08 10:08 UTC
### Neovim version (nvim -v)

NVIM v0.7.0-dev+nightly-119-g24d56116f-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

wsl

### Terminal name/version

alacritty 0.10.1 (2844606)

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

```ex
:set statusline=
```

### Expected behavior

NVIM v0.7.0-dev+nightly-118-g80e6f8186
![ok](https://user-images.githubusercontent.com/47070852/157214184-1c55b94f-9bd3-4427-b9d0-382d8d1333cf.jpg)
![ok](https://user-images.githubusercontent.com/47070852/157214368-5e051e60-1369-43ce-9edd-8d525c771de8.gif)

### Actual behavior

NVIM v0.7.0-dev+nightly-119-g24d56116f-dirty
![bad](https://user-images.githubusercontent.com/47070852/157214247-3214b1f4-13f7-48a9-8300-86040e677b22.jpg)
![bad](https://user-images.githubusercontent.com/47070852/157214264-ca11fb8c-57c5-424a-b158-23db5dc733cc.gif)

**Comment by zeertzjq** [comment] 2022-03-08 10:19
Duplicate of #17638

**Closed by zeertzjq** 2022-03-08 10:19 UTC
Labels: bug
