### ISSUE TITLE
`:syn`-based highlight and extmark-based highlight mixed up when `spell` is on

### ISSUE THREAD

**Issue by tomtomjhj** [neovim/neovim#23153] opened 2023-04-17 10:41 UTC
### Problem

When `:syn`-based highlight and extmark-based highlight overlap and spellchecking is on, the resulting highlight can be very broken.

This bug was introduced somewhere between 0.7.2 and 0.8.0.

### Steps to reproduce

`repro.vim`
```vim
insert
01234 6789
.
set spell
syn match Gray "^.*$"
hi Gray ctermfg=246
hi BoldPink cterm=bold ctermfg=199
call nvim_buf_add_highlight(0, -1, 'BoldPink', 0, 2, 8)
```

Run
```
nvim --clean -c 'so repro.vim'
```

Result:
![image](https://user-images.githubusercontent.com/19489738/232460925-51a10151-3bc7-412a-a0da-5e03c222fc61.png)
`BoldPink` is not fully applied to `6`: it is expected to be bold and pink, but it's bold and gray.

### Expected behavior

![image](https://user-images.githubusercontent.com/19489738/232461143-7fbde39a-f097-4a68-a296-a0ce6529ebac.png)

### Neovim version (nvim -v)

0.10.0~ubuntu1+git202304162017-55d346fc2-9b397864c

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

ubuntu 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

tmux-256color

### Installation

ubuntu ppa

**Comment by clason** [comment] 2023-04-17 10:45
Works for me. Please test with a manual build from the repo (or the nightly appimage).

**Comment by clason** [comment] 2023-04-17 10:47
Looks to be a duplicate of https://github.com/neovim/neovim/issues/20864

**Comment by tomtomjhj** [comment] 2023-04-17 10:53
> Works with nvim --clean -u test.vim, so there must be some race condition. :Inspect shows that both highlights are in fact applied.

with `-u`, `Gray` isn't applied at all (both visually and by `:Inspect`)

**Comment by clason** [comment] 2023-04-17 11:00
Similar results with
```vim
let ns = nvim_create_namespace('test')
call nvim_buf_set_extmark(0, ns, 0, 2, {'end_col': 8, 'hl_group': 'BoldPink', 'priority': 1000})
```
so not a priority issue.

**Comment by tomtomjhj** [comment] 2023-04-17 11:03
Also note that there is similar issue when `diff` is on (and `nospell`). I don't have minimal reproducer for that, but it suggests that this bug could be related to something that handles additional highlights for spellchecker and diff.

**Comment by tomtomjhj** [comment] 2023-04-19 03:45
Bisected to 75adfefc85bcf0d62d2c0f51a951e6003b595cea.

**Closed** 2023-05-22 09:07 UTC
Labels: bug-regression, has:bisected, highlight, spell
