### ISSUE TITLE
pythonAttribute highlight group does not apply

### ISSUE THREAD

**Issue by mangelozzi** [neovim/neovim#12732] opened 2020-08-08 15:16 UTC
Hopefully tree sitter makes this issue not significant. Really looking forward to tree sitter.

- `nvim --version`:
```
:ver
NVIM v0.5.0-563-ge628a05b5
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict
-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto
-DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/b
uild/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/bu
ild/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/n
eovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-c5758e75-4445-4564-8946-810c98499a51
```
- Operating system/version: Windows 10 running WSL2 Ubuntu 20.04
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Make `pythonAttribute` group very visible: `:hi pythonAttribute ctermfg=1 ctermbg=11 guifg=Red guibg=Yellow`
2. Check the `pythonAttribute` group is set to be very noticable with `:hi`
3. `:new temp.py`
4. Type in `"foo".upper()`
5. Can see the `pythonString` group highlighted `"foo"`.
6. Place the cursor over `upper` and run `:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')`
  Should print the group as `pythonAttribute`
7. Look at the colour of `upper`.

### Expected behaviour
`upper` to be highlighted with the `pythonAttribute` goup.

### Actual behaviour
`upper` is NOT highlighted.

**Comment by erw7** [comment] 2020-08-24 18:08
From the comments below, this seems to be the intended behavior.

https://github.com/neovim/neovim/blob/8c49e3d50959e24dadd688f56a18f104bd5fd934/runtime/syntax/python.vim#L220-L224

If you think this should be fixed, please follow the following description in `runtime/syntax/README.txt`. Normally we do not modify files under runtime in neovim. It merges when it is taken in upstream.

https://github.com/neovim/neovim/blob/8c49e3d50959e24dadd688f56a18f104bd5fd934/runtime/syntax/README.txt#L32-L33

**Closed** 2020-08-30 07:04 UTC
Labels: runtime
