### ISSUE TITLE
Build fails on dependency of "busted".

### ISSUE THREAD

**Issue by exhuma** [neovim/neovim#2482] opened 2015-04-22 14:17 UTC
This is based on 84891f2802a0db1a25

What sticks out to me is:

      Failed downloading  ... Operation already in progress.

Thoughts?

Detailed error message:

    Warning: falling back to curl - install luasec to get native HTTPS support                                                                                                                                                   

    Missing dependencies for busted:
    penlight >= 1.3.2-2
    lua_cliargs >= 2.5-0

    Using https://rocks.moonscript.org/penlight-1.3.2-2.rockspec... switching to 'build' mode

    Error: Failed installing dependency: https://rocks.moonscript.org/penlight-1.3.2-2.rockspec - Error fetching file: Failed downloading http://stevedonovan.github.io/files/penlight-1.3.2-core.zip - Operation already in progress
    make[3]: *** [usr/bin/busted] Error 1
    make[3]: Leaving directory `/tmp/neovim/.deps'
    make[2]: *** [CMakeFiles/busted.dir/all] Error 2
    make[2]: Leaving directory `/tmp/neovim/.deps'
    make[1]: *** [all] Error 2
    make[1]: Leaving directory `/tmp/neovim/.deps'
    make: *** [deps] Error 2

**Comment by Pyrohh** [comment] 2015-04-22 16:10
I assume you have `unzip` installed? I'm not sure if there actually is an operation already in progress, but I can't reproduce this locally. I'm guessing the server hosting that rockspec was temporarily down, not sure.

**Comment by exhuma** [comment] 2015-04-22 16:35
Yes. Unzip is installed. I can reproduce this without fail every time. So I'm not sure if it's a remote server issue. I just tried again. Same error.

For what it's worth, it seems that the process hangs on

    Using https://rocks.moonscript.org/penlight-1.3.2-2.rockspec... switching to 'build' mode

Might be a timeout?

Note that this is behind a corporate proxy. However, manually running

    curl https://rocks.moonscript.org/penlight-1.3.2-2.rockspec

works. So the proxy allows this connection. Is it possible that something behind the scenes is ignoring the `https_proxy` environment variable?

**Comment by AntoineD** [comment] 2015-04-22 18:38
Same situation and issue here.

**Comment by srang** [comment] 2015-04-22 20:16
I've had issues installing busted on corporate network and had it work fine when tethering on phone.

**Comment by exhuma** [comment] 2015-04-23 06:49
Unfortunately, tethering is not an option here. But this again makes me think that maybe something internally is ignoring the proxy environment variables.

**Comment by brettanomyces** [comment] 2015-04-23 22:01
I'm getting a similar error, also behind a corporate proxy.

```
[ 98%] Generating usr/bin/busted
Warning: falling back to curl - install luasec to get native HTTPS support

Missing dependencies for busted:
penlight >= 1.3.2-2
luassert >= 1.7.6-0

Using https://rocks.moonscript.org/penlight-1.3.2-2.rockspec... switching to 'build' mode

Error: Failed installing dependency: https://rocks.moonscript.org/penlight-1.3.2-2.rockspec - E
rror fetching file: Failed downloading http://stevedonovan.github.io/files/penlight-1.3.2-core.
zip - connection refused
make[3]: *** [usr/bin/busted] Error 1
make[3]: Leaving directory `/home/yukichb/git/neovim/.deps'
make[2]: *** [CMakeFiles/busted.dir/all] Error 2
make[2]: Leaving directory `/home/yukichb/git/neovim/.deps'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/yukichb/git/neovim/.deps'
make: *** [deps] Error 2
```

**Comment by luizribeiro** [comment] 2015-05-04 00:46
I was being affected by this today while upgrading neovim and spent some time debugging it. The problem here is that luarocks doesn't read from the `http_proxy` environment variable when downloading , but rather from its own `config.lua` file. See [luarocks/src/luarocks/fs/lua.lua](https://github.com/keplerproject/luarocks/blob/57c838ec4d0a6dbd75ffe93b9bbf9679f52ed4d2/src/luarocks/fs/lua.lua#L548).

So, I thought the solution would be to simply create a `~/.luarocks/config.lua` file and set `proxy = "myproxy.com:8080"`, but turns out that doesn't work - because neovim is building luarocks with `--force-config`.

I see two solutions for this:

1. Getting rid of `--force-config` from [third-party/cmake/BuildLuarocks.cmake](https://github.com/neovim/neovim/blob/master/third-party/cmake/BuildLuarocks.cmake#L22)
2. Make luarocks read from the `http_proxy` environment variable by default.

**Comment by luizribeiro** [comment] 2015-05-04 00:49
Btw, if you're building neovim from [Homebrew](http://brew.sh/) or [Linuxbrew](http://brew.sh/linuxbrew/), you can `brew edit neovim` and add the following to the neovim formula:

```ruby
  patch do
    url "https://gist.githubusercontent.com/luizribeiro/9f4f01a0b539b039e0a7/raw/087f40122187093c06f68f309ea7eb76c58d93a1/gistfile1.diff"
    sha256 "0ac3c910f505a3af99dc95a5f50b19877a62233f70a4fe8dd764870399449093"
  end

**Comment by justinmk** [comment] 2015-05-04 01:34
@luizribeiro thanks for debugging that. Is there a way to do the right thing with the proxy setting with a flag, which can be set here: https://github.com/neovim/neovim/blob/master/third-party/cmake/BuildLuarocks.cmake#L4 ?

(I don't know what this http_proxy environment variable is. Is it a shell variable? Is it a luarocks user config thing?)

**Comment by luizribeiro** [comment] 2015-05-04 03:23
@justinmk, yeah. `http_proxy` is a shell variable. You set it with `export http_proxy="http://myproxy.com:8080` and then `curl` and `wget` will use that as a HTTP proxy by default (hence why folks behind corporate networks who need proxy setups are experiencing this).

I don't think there's anything we could do on `BuildLuarocks.cmake` other than removing `--force-config` and having people setup their own `config.lua` files for proxying. I feel like the optimal solution here would be for luarocks to obey whatever is set on the `http_proxy` env variable, but no idea if the luarocks folks would be open to it... That would probably be a one-liner pull-request, so maybe I should just try it?

**Comment by luizribeiro** [comment] 2015-05-04 03:25
Sounds like there's someone looking into it already: keplerproject/luarocks#337

**Comment by nemith** [comment] 2015-05-05 05:08
Even with the patch and ~/.luarocks/config.lua I still cannot seem to get past downloading penlight.

Error: Failed installing dependency: https://rocks.moonscript.org/penlight-1.3.2-2.rockspec - Error fetching file: Failed downloading http://stevedonovan.github.io/files/penlight-1.3.2-core.zip - closed

**Comment by AntoineD** [comment] 2015-05-05 16:54
The patch worked for me.

**Comment by luizribeiro** [comment] 2015-05-16 04:49
I was just able to build neovim without the patch I mentioned before. Maybe we can close this? Anyone else experiencing this issue?

**Comment by exhuma** [comment] 2015-05-16 07:59
I will give it a try next week once I'm back at the office.

**Comment by exhuma** [comment] 2015-05-18 15:03
I'm still getting an error. After running `make clean` and `make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/opt/neovim"` I get the following message:

    [... snip ...]
    make[3]: Leaving directory `/tmp/neovim/.deps'
    make[3]: Entering directory `/tmp/neovim/.deps'
    [ 95%] Generating usr/bin/busted
    Warning: falling back to curl - install luasec to get native HTTPS support

    Missing dependencies for busted:
    penlight >= 1.3.2-2
    lua_cliargs >= 2.5-0

    Using https://rocks.moonscript.org/penlight-1.3.2-2.rockspec... switching to 'build' mode

    Error: Failed installing dependency: https://rocks.moonscript.org/penlight-1.3.2-2.rockspec - Error fetching file: Failed downloading http://stevedonovan.github.io/files/penlight-1.3.2-core.zip - timeout
    make[3]: *** [usr/bin/busted] Error 1
    [... snip ...]


So the error still persists.

Note: I cannot follow the `install luasec` recommendation as it is currently against local policy to install a package into the system (i.e. without `prefix`) which is not available as default system package. `luasec` falls into that category.

If there is a way to install it with a prefix *and* use it while compiling neovim, I could try that, but I don't know how I would make it available to the build-process, as it won't be "findable"  on normal system paths.

**Comment by Shougo** [comment] 2015-05-19 01:23
@exhuma I got same error yesterday.

https://gist.github.com/luizribeiro/9f4f01a0b539b039e0a7

You should remove `--force-config` arguments in the makefile.
And set proxy config for curl.
You don't have to install luasec.

@justinmk Why the `--force-config` is needed in the makefile?
This problem is really wired in proxy environment.

**Comment by justinmk** [comment] 2015-05-25 16:29
As of https://github.com/keplerproject/luarocks/pull/371 luarocks supports  `http_proxy`, `https_proxy`, and `no_proxy` env vars. I'll post a PR to update luarocks.

**Comment by Shougo** [comment] 2015-05-25 22:41
Thanks.   It is so good.  I think the problem is explained in Wiki build section.

**Closed** 2015-05-28 03:21 UTC
Labels: buildsystem

**Comment by exhuma** [comment] 2015-05-28 07:55
I can confirm that I managed to successfully build the project after pulling in the changes.

Note though that a simple `make clean` was insufficient. I had to run `make distclean` to make it work!

**Comment by Shougo** [comment] 2015-05-28 07:57
Thank you for the information.
