### ISSUE TITLE
Interpret colon in path as line number specifier

### ISSUE THREAD

**Issue by giuscri** [neovim/neovim#8099] opened 2018-03-04 15:42 UTC
grep outputs matches in format `name:n`.

I'd find useful to pass neovim `name:n:` and opening `name` at line `n`.

```
$ git grep -n insert
.editorconfig:7:insert_final_newline = true
contrib/uncrustify.cfg:1472:# The number of spaces to insert at the start of subsequent comment lines
contrib/uncrustify.cfg:1475:# The number of spaces to insert after the star on subsequent comment lines
...
$ nvim contrib/uncrustify.cfg:1472:
```

Are people interested in this feature? Or it's something specific to my workflow?

**Comment by justinmk** [comment] 2018-03-04 17:30
duplicate of #1281 (I renamed the title so it is easier to find)

**Closed by justinmk** 2018-03-04 17:30 UTC
