### ISSUE TITLE
Problems with inserting some non-ASCII characters

### ISSUE THREAD

**Issue by frangio** [neovim/neovim#2777] opened 2015-05-31 20:45 UTC
Inserting some non-ASCII characters is not working. To reproduce type in an accented capital A (U+00C1). (In an Apple computer with US keyboard layout this is done by pressing option+e and then shift+a.) This results in two separate characters being inserted: U+00C3, U+0081.

This happens only with some non-ASCII characters, for example it doesn't happen with a lowercase accented a (U+00E1).

It should be noted too that reading files that already have these problematic characters works fine.

Running on iTerm2, OS X Mavericks 10.9.5. Neovim installed via Homebrew, version:
NVIM 0.0.0-alpha+201505311247
Commit: 7dc241ac782e3a469d73d5f9a7baeba4e6107333

**Comment by brcolow** [comment] 2015-05-31 20:49
Can not reproduce. Typing option+e and then shift-a results in an accented capital A being inserted.

NVIM 0.0.0-alpha+201505260107 (compiled May 26 2015 22:05:42)
Commit: 5a9ad68b258f33ebd7fa0a5da47b308f50f1e5e7

On Mac OS X (iTerm2, zsh). Yosemite 10.10.3 (14D136)

**Comment by frangio** [comment] 2015-06-01 00:59
Did you build manually? I edited the issue and added more details about my installation. It may be related to installing via Homebrew.

**Comment by brcolow** [comment] 2015-06-01 01:01
I installed via homebrew.

**Comment by Shougo** [comment] 2015-06-01 01:02
Related issue.   https://github.com/neovim/neovim/issues/2752

**Comment by frangio** [comment] 2015-06-01 01:10
Tried building manually and the bug persists.

**Comment by Shougo** [comment] 2015-06-01 01:25
https://github.com/neovim/neovim/issues/2752#issuecomment-106270746

> OK, it turns out i should comment out this setting -- which is copying from my old vim setting:

```
try
  lang zh_TW
catch
endtry
```

> Now the Chinese characters works.

**Comment by frangio** [comment] 2015-06-01 01:29
It still happens with an empty nvimrc.

**Comment by bantana** [comment] 2015-06-02 12:37
https://github.com/neovim/neovim/issues/2752#issuecomment-107917012
export LANG="en_US.UTF-8"
can fix it.

**Comment by frangio** [comment] 2015-06-03 06:37
Indeed. Is this expected behaviour? It seems odd to me.

**Comment by Shougo** [comment] 2015-06-03 06:43
I think it is intended behavior.
If you don't set `LANG` correctly, multibyte characters behavior is undefined.

**Comment by bfredl** [comment] 2015-06-13 18:00
This might be fixed with #2469. Even without setting LANG it should work now. (Previously the settings was read in wrong order)

**Comment by justinmk** [comment] 2015-06-13 18:36
Please re-open if the issue still exists on latest master.

**Closed by justinmk** 2015-06-13 18:36 UTC
Labels: encoding, terminal

**Comment by frangio** [comment] 2015-06-13 19:05
I can confrm it's fixed.
