### ISSUE TITLE
(winbar): setting a winbar inside an autocmd create an E315 error.

### ISSUE THREAD

**Issue by vzytoi** [neovim/neovim#19585] opened 2022-07-31 00:53 UTC
### Neovim version (nvim -v)

NVIM v0.8.0-dev-nightly-6-ged6bbc03a

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.5

### Terminal name/version

iTerm

### $TERM environment variable

xterm-256color

### Installation

brew install --HEAD neovim

### How to reproduce the issue

I have not yet tried to reproduce the error with a minimal configuration. Could you try to add the code snippet given below and open some plugins similar to the ones I mentioned (Telescope, Diffview, harpoon, toggle-term...). If the problem doesn't appear on your configuration then I would try to do a minimal configuration. 

### Expected behavior

I would like to have 'ok' displayed in the winbar of each of my splits without errors being displayed.

### Actual behavior

**I have this autocmd inside my configuration :**

```lua
if vim.fn.has "nvim-0.8" == 1 then
    vim.api.nvim_create_autocmd("BufEnter", {
        callback = function()
            vim.opt_local.winbar = 'ok'
        end
    })
end
```

**It create a bunch of errors.**
- When opening Telescope:
```
E5108: Error executing lua: ...ack/packer/start/plenary.nvim/lua/plenary/popup/init.lua:408: Vim(append):Error executing lua callback: vim/_meta.lua:0: Vim:E36: Pas assez de place
stack traceback:
	[C]: in function 'nvim_set_option_value'
	vim/_meta.lua: in function '_set'
	vim/_meta.lua: in function '__newindex'
	/Users/cyprien/.config/nvim/lua/autocmds.lua:132: in function </Users/cyprien/.config/nvim/lua/autocmds.lua:131>
	[C]: in function 'nvim_set_current_win'
	...ack/packer/start/plenary.nvim/lua/plenary/popup/init.lua:408: in function 'create'
	...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:327: in function '_create_window'
	...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:397: in function 'find'
	...ker/opt/telescope.nvim/lua/telescope/builtin/__files.lua:305: in function 'v'
	...ker/opt/telescope.nvim/lua/telescope/builtin/__files.lua:529: in function 'v'
	...packer/opt/telescope.nvim/lua/telescope/builtin/init.lua:515: in function 'find_files'
	/Users/cyprien/.config/nvim/lua/plugins/telescope.lua:16: in function </Users/cyprien/.config/nvim/lua/plugins/telescope.lua:14>
stack traceback:
	[C]: in function 'nvim_set_current_win'
	...ack/packer/start/plenary.nvim/lua/plenary/popup/init.lua:408: in function 'create'
	...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:327: in function '_create_window'
	...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:397: in function 'find'
	...ker/opt/telescope.nvim/lua/telescope/builtin/__files.lua:305: in function 'v'
	...ker/opt/telescope.nvim/lua/telescope/builtin/__files.lua:529: in function 'v'
	...packer/opt/telescope.nvim/lua/telescope/builtin/init.lua:515: in function 'find_files'
	/Users/cyprien/.config/nvim/lua/plugins/telescope.lua:16: in function </Users/cyprien/.config/nvim/lua/plugins/telescope.lua:14>
```

- When trying to open Diffview:
```
E5108: Error executing lua: /Users/cyprien/.config/nvim/lua/fn.lua:41: Vim(lua):E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Il manque " à la fin de "Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:83: Vim:Error executing Lua callback: ...cker/opt/diffview.nvim/lua/diffview/views/file_entry.lua:446: Vim:E315: ml_get: invalid lnum: 136
stack traceback:
	[C]: in function 'cmd'
	...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:161>
	[string ":lua"]:1: in main chunk
	[C]: in function 'nvim_command'
	/Users/cyprien/.config/nvim/lua/fn.lua:41: in function 'toggle'
	/Users/cyprien/.config/nvim/lua/keymaps.lua:129: in function </Users/cyprien/.config/nvim/lua/keymaps.lua:128>
stack traceback:
	[C]: in function 'nvim_command'
	/Users/cyprien/.config/nvim/lua/fn.lua:41: in function 'toggle'
	/Users/cyprien/.config/nvim/lua/keymaps.lua:129: in function </Users/cyprien/.config/nvim/lua/keymaps.lua:128>
```

- When trying to open toggle-term:
```
E5108: Error executing lua: /Users/cyprien/.config/nvim/lua/fn.lua:41: Vim(lua):E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Il manque " à la fin de "Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:83: Vim:Error executing Lua callback: ...cker/opt/diffview.nvim/lua/diffview/views/file_entry.lua:446: Vim:E315: ml_get: invalid lnum: 136
stack traceback:
	[C]: in function 'cmd'
	...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:161>
	[string ":lua"]:1: in main chunk
	[C]: in function 'nvim_command'
	/Users/cyprien/.config/nvim/lua/fn.lua:41: in function 'toggle'
	/Users/cyprien/.config/nvim/lua/keymaps.lua:129: in function </Users/cyprien/.config/nvim/lua/keymaps.lua:128>
stack traceback:
	[C]: in function 'nvim_command'
	/Users/cyprien/.config/nvim/lua/fn.lua:41: in function 'toggle'
	/Users/cyprien/.config/nvim/lua/keymaps.lua:129: in function </Users/cyprien/.config/nvim/lua/keymaps.lua:128>
```

And I found 3 or 4 more plugins that cause this error.

**Things I tried:**

- Removing theses lines
=> Solve every error I mentioned.
- Changing the event (FileType...)
=> Does nothing

Est-ce qu'il y a quelque chose que j'ai mal comprit, si non , devrais-je me référés aux dépôt des plugins concernés? Merci beaucoup de votre assistance.

**Comment by zeertzjq** [comment] 2022-07-31 00:55
Duplicate of #19458

**Closed by zeertzjq** 2022-07-31 00:55 UTC
Labels: bug
