### ISSUE TITLE
noevim doesn't "paste" newlines in terminal buffer

### ISSUE THREAD

**Issue by Kreijstal** [neovim/neovim#17158] opened 2022-01-21 10:18 UTC
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

no vim 8.2

### Operating system/version

windows 10

### Terminal name/version

windows

### $TERM environment variable

not set (doesn't matter tried with ansi-256color and xterm-256color)

### Installation

scoop

### How to reproduce the issue

I have a file open with some code, and in normal mode I type 
```
:tabe whatever
:terminal
gT 
```
Then I go and yank 3 lines containing this
```
echo 1
echo 2
echo 3
```
I type `gtp` 
and I get this
```
Microsoft Windows [Version 10.0.19042.1466]
(c) Microsoft Corporation. All rights reserved.

C:\Users\k\ok>echo 1echo 2echo 3
```

![render1642758118045](https://user-images.githubusercontent.com/2415206/150509636-ed012e99-b868-4b63-801a-fad4f4305489.gif)

This happens whether you paste with neovim or paste from clipboard.

### Expected behavior

I expect every newline to be pasted into the terminal

### Actual behavior

I expect the newlines to not be lost, is this a bug? or something wrong with my vim knowledge?
all lines are concatenated in the terminal

**Comment by zeertzjq** [comment] 2022-01-23 04:50
Duplicate of #14621

**Closed by zeertzjq** 2022-01-23 04:50 UTC
Labels: bug, platform:windows, clipboard, terminal
