### ISSUE TITLE
Node provider doesn't work

### ISSUE THREAD

**Issue by duikboot** [neovim/neovim#7568] opened 2017-11-15 21:27 UTC
- `nvim --version`: NVIM v0.2.2-38-gf8d40e7d5
- Vim (version: ) behaves differently?
- Operating system/version: Fedora core 26
- Terminal name/version: GNOME Terminal/3.24.2
- `$TERM`: xterm-256color

### Actual behaviour
After installing node and npm,(v. 8.9.1), the latest HEAD of neovim v0.2.2-38-gf8d40e7d5 I ran:
:UpdateRemotePlugins
Which gave the following message
function remote#host#UpdateRemotePlugins[6]..<SNR>18_RegistrationCommands[13]..remote#host#RegisterPlugin, line 5     
Plugin "/home/arjen/config/dotfiles/_neovim/bundle/nvim-parinfer.js/rplugin/node/nvim-parinfer.js" is already registered
remote/host: python3 host registered plugins ['denite', 'deoplete']
remote/host: generated rplugin manifest: /home/arjen/.local/share/nvim/rplugin.vim

Running :CheckHealth gave me:

```
## Node provider (optional)
  - WARNING: `node` and `npm` must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` commands work.
```

```
$ which npm
~/bin/npm
```

```
$ which node
~/bin/node
```

### Expected behaviour

Node provider is available

**Comment by justinmk** [comment] 2017-11-15 21:34
`:checkhealth` has a bug, but the node host should still work. Are you saying nvim-parinfer plugin doesn't work? cc @billyvg

**Comment by duikboot** [comment] 2017-11-15 21:36
Correct. Do you need more information or is this a nvim-parinfer bug?

**Comment by billyvg** [comment] 2017-11-16 05:28
I believe the `:checkhealth` bug is just a red herring, let's try to address the bug in https://github.com/clojure-vim/nvim-parinfer.js/issues/32

**Comment by janlazo** [comment] 2017-11-16 06:45
It doesn't work in Windows as well. I installed yarn so `checkhealth` passes.
neovim-node-host is not written in Javascript so the batchfile shim that npm uses doesn't work.

**Comment by janlazo** [comment] 2017-11-17 03:16
`exepath('neovim-node-host')` returns `neovim-node-host` in Neovim and `neovim-node-host.cmd` in Vim.
Is that expected behaviour?

**Comment by justinmk** [comment] 2017-11-17 20:41
@duikboot 's report is addressed in https://github.com/clojure-vim/nvim-parinfer.js/issues/32#issuecomment-344820514 and https://github.com/neovim/node-client/issues/42 

@janlazo comment is addressed by https://github.com/neovim/neovim/pull/7577

**Closed by justinmk** 2017-11-17 20:41 UTC
Labels: bug, rplugin

**Comment by janlazo** [comment] 2017-11-17 23:59
`:checkhealth` works for me now as of the latest Appveyor build and `:UpdateRemotePlugins` registers nvim-parinfer.js with no errors. I cannot confirm for other OS.

**Comment by duikboot** [comment] 2017-11-19 20:37
It doesn't work yet on Fedora 26. CheckHealth still gives me:

```
## Node provider (optional)
  - WARNING: `node` and `npm` must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` commands work.
```
`which node` and `which npm` give me the correct path.

```
$ vim --version
NVIM v0.2.2-38-gf8d40e7d5
Build type: RelWithDebInfo
```

**Comment by justinmk** [comment] 2017-11-19 20:59
> NVIM v0.2.2-38-gf8d40e7d5

f8d40e7d5 is before the fix.

**Comment by duikboot** [comment] 2017-11-19 21:22
I'm sorry, thanks for your clarification.
