### ISSUE TITLE
TUI: distinguish Tab, ctrl-i (S8C1T mode)

### ISSUE THREAD

**Issue by RomanHargrave** [neovim/neovim#5916] opened 2017-01-08 19:01 UTC
### Actual behaviour

`C-i` is synonymous to `Tab`

### Expected behaviour

`C-i` is not synonymous to `Tab`

### Steps to reproduce using `nvim -u NORC`

Input `C-i`

My limited understanding of vim's input system is that certain non-alpha control keys are handled as chorded alpha/modifier keys, Tab being one. Since I use an odd keyboard layout, I would very much like to bind some certain keys to make things behave, unfortunately this isn't really an option seeing as I can either lose the ability to input Tab or lose the ability to comfortably navigate in insert mode.

I propose that, inline with nvim's (continued) refactoring and redesign of vim internals that input such as Tab not be handled as chords and rather its own input.

**Comment by justinmk** [comment] 2017-01-08 20:13
See http://www.leonerd.org.uk/hacks/fixterms/

We already use libtermkey internally. I believe the next step needed is for us to request [S8C1T mode](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-C1-_8-Bit_-Control-Characters) from the terminal. 

We currently don't request that mode but it's tentatively planned.

**Comment by roxma** [comment] 2017-03-04 11:19
Looking forward to this, `<c-h>` and `<backspace>`, `<c-m>` and `<Enter>`
I'm looking for keys for jumping by word in insert mode, but unfortunately there's too few key left available.

**Comment by justinmk** [comment] 2017-03-04 19:31
@roxma On master (0.2+) `<c-h>` and `<bs>` should already be distinguished, for mappings. See #5758

**Comment by sassanh** [comment] 2017-05-08 09:28
Is it possible to tell us what's the obstacles for requesting S8C1T mode right now? or maybe it's just too complicated?

**Comment by justinmk** [comment] 2017-05-08 09:35
There is no technical obstacle. Someone needs to spend the time to investigate it.

**Comment by sassanh** [comment] 2017-05-08 09:46
Isn't it like setting a config while loading libtermkey? Obviously I'm underestimating something, I just wanna know what it is if possible. The milestone set for this is too far (maybe around 2 years from now in my estimation based on how long it took for .2 to be released, correct me if I'm wrong.) Is it set for that milestone based on a logic you have for each milestone?

**Comment by sassanh** [comment] 2017-05-08 10:00
OK, for someone who reaches here: I found a detailed discussion about this issue here: https://github.com/neovim/neovim/issues/176

**Comment by sassanh** [comment] 2017-05-08 10:16
In iTerm I was able to configure the terminal so that it sends a custom escape code when `<c-i>` is pressed and nnoremap that code in neovim to `<tab>`. It can be a workaround if your terminal supports such intermediate mapping till neovim supports this distinction.

**Comment by justinmk** [comment] 2017-05-08 10:25
It's probably not very difficult. It might take a day or a week. If the task were precisely conceived, speaking only for myself, I would have done it already. Since I don't precisely know exactly what to do, it's like the other 600 unknown tasks waiting to be done: I work on whatever else is higher priority and/or more familiar by some measure greater than zero. For anyone who is not me, I don't know any better answer.

> In iTerm I was able to configure the terminal so that it sends a custom escape code when `<c-i>` is pressed and nnoremap that code in neovim to `<tab>`.

Yes, that's the typical workaround available in most terminals.

**Comment by sassanh** [comment] 2017-05-08 10:50
Thanks for info. I (like many others) am thankful for every minute you and other neovim developers spend on developing neovim and your quick responses.

**Comment by albertnetymk** [comment] 2017-05-17 01:30
> In iTerm I was able to configure the terminal so that it sends a custom escape code when <c-i> is pressed and nnoremap that code in neovim to <tab>.

@sassanh could you elaborate?

**Comment by sassanh** [comment] 2017-05-17 04:23
@albertnetymk 
Go to iTerm preferences => Keys. Press the `+` button. In keyboard shortcut press `ctrl-i`, in action select "Send Escape Sequence", and in `Esc+` enter `i`. Now whenever you hit `<c-i>`, `<a-i>` is sent to to applications in iTerm. So if you `noremap <a-i> <c-i>` you should be able to use `<c-i>` even though if you had already mapped `<tab>` to something else.

**Comment by albertnetymk** [comment] 2017-05-17 12:14
@sassanh Thank you very much. I get it to work for neovim. However, it doesn't work when I run neovim inside tmux. Worked around it by inputing `a` for `Esc+`. No idea why, though.

**Comment by neersighted** [comment] 2017-07-03 02:10
Just making a note for anyone who tries to implement this (maybe me, if I have time):

Request 8-bit (`S8C1T`) mode: `ESC SPACE G`, `\e G`
Request 7-bit (`S7C1T`) mode: `ESC SPACE F`, `\e F`

[DECRQSS](http://vt100.net/docs/vt510-rm/DECRQSS.html):

Device Control String (DCS): `ESC P`, `\eP`
Intermediate Characters: `DOLLAR Q`, `$q`
Final Characters: Varies
String Terminator (ST): `ESC BSLASH`, `\e\\`

The basic idea is to request 8-bit mode, and then use `DECRQSS` to determine what mode the terminal is in. If 8-bit characters are present in the response, then 8-bit mode is on.

It does occur to me however, it is likely easier to make the process more naive: request 8-bit mode at startup, and request 7-bit mode at shutdown. CSI-unaware terminals will ignore the escape sequences as junk, while CSI-aware terminals will switch to 8-bit mode and send CSI sequences. Since neovim can handle both at all times (or at least this is how I understand it from the prior discussion), there is no downside to this, and the `DECRQSS` should not be needed.

Any thoughts, @leonerd?

**Comment by leonerd** [comment] 2017-07-04 10:46
The point of setting S8C1T mode is that *if* the terminal has done that, then you know it will never send an ESC (0x1b) byte as the start of a longer control sequence, only as a real `<Escape>` key. This means that *if you know the terminal has done S8C1T mode correctly*, then when such a byte arrives you know it to be that Escape key and not a control sequence. But unless you know it understands S8C1T you can't make that inference, because it could be an older terminal that doesn't understand it, and it simply sending ESC-prefixed controls.

The `DECRQSS` part of the process is needed in order to find out if the terminal understood it; only if so can you remove the timing-related logic around handling ESC (0x1b) bytes.

**Comment by jonhoo** [comment] 2019-09-23 17:00
A related issue here is trying to map `<C-j>` to something like `<Esc>` in all modes. Works fine in insert mode, but not anywhere else it seems. In vim, you need to set the magical-looking property `BASH_Ctrl_j` to make this work, but that has no effect in neovim it seems.

**Comment by justinmk** [comment] 2019-09-23 17:09
Sounds like a config issue, off topic here.

**Comment by jonhoo** [comment] 2019-09-23 17:19
@justinmk I believe it is the same issue — `C-j` is mapped to newline somewhere deep in the stack, just like `C-i` is, and so can't easily be remapped to anything.

**Comment by justinmk** [comment] 2019-09-23 18:08
? I map ctrl-j in normal mode and it works just fine .

**Comment by jonhoo** [comment] 2019-09-23 18:17
If you remap `C-j` with, say
```vim
nmap <C-j> <Esc>
```
And then look at the output of `nmap`, you'll see that the mapping appears as
```
<NL>          <Esc>
```
Not as `C-j` as you'd expect (that is this issue). This is problematic in contexts such as `cmap`, where newline executes the command. I'm not entirely sure why it doesn't cause issues with `imap` (no newline is inserted), but that doesn't change that the root cause is that `C-j` is treated as a newline rather than as `C-j` (just like `C-i` is treated as tab).

**Comment by bfredl** [comment] 2019-09-23 18:23
Though it seems to work well with `:cmap` also. It might be displayed as `<nl>`, but nvim doesn't confuse it with `<cr>` fundamentally. What doesn't work in cmdline seems to be `wildchar=<c-j>` #11042 (and I guess other such special cases/misdesigns).

**Comment by jonhoo** [comment] 2019-09-23 18:44
@bfredl Hmm, if I do:
```
nvim -u NORC
```
then
```
:cmap <C-j> <Esc>
```
then
```
:abcdef<C-j>
```
I see
```
E492: Not an editor command: abcdef
```
Which implies that the `C-j` was indeed interpreted as a newline. Or am I missing something?

**Comment by bfredl** [comment] 2019-09-23 18:47
probably depends on terminal emulator then (which I alluded to in #11042, but wasn't sure of). Or at least we have the code for some terminals but not for others (I would have expected c-j to always be distinguishable from CR in raw mode, only c-m should need a special input mode).

**Comment by jonhoo** [comment] 2019-09-23 18:54
Ah, interesting. Should I file this as a separate issue then? Or as an issue with the emulator (Alacritty)? If the latter, what should I tell them to aid them in fixing the issue?

**Comment by bfredl** [comment] 2019-09-23 19:31
Let's try to fix it within nvim first. As long as the byte sent by c-j (in raw mode) is different from pressing the enter key, it should be possible. ( c-m should additionally work in a libtermkey-compatible terminal, so we should stop translating `<c-m>` to `<cr>` as well)

**Comment by llitz** [comment] 2020-02-05 07:12
This is a little bit old, but I don't think it is alacritty either, it is something else.

To test, open xev
press C-j you get 0x0a
press C-m you get 0x0d
press C-i you get 0x09

I don't see this behavior directly on the console though.

**Comment by hwalinga** [comment] 2020-07-29 17:39
Very late to the party, but the reason `:cmap <C-j> <Esc>` executes the command and not leaves it, is because mapping <Esc> in command mode will actually execute the command (for the documentation on this, see `:h c_Esc`, the mapping is considered a macro). So this is indeed off-topic in the C-j discussion. Binding any other key other than C-j will have the same effect. 

@jonhoo If you want to have the desired behavior you will need to map like this `:cmap <C-j> <C-c>`

**Comment by hasufell** [comment] 2021-07-11 08:44
(g)vim is able to distinguish ctrl-i and tab since some time, so it appears neovim is far behind here and I can't figure out from this discussion whether someone is working on it or what the proposed course is. I feel this has stalled, because the scope is too wide.

Not everyone uses terminal, but even GUI users can't have this feature atm, so apart from all the terminal foo, I'd consider this a bug, not an enhancement.

**Comment by bfredl** [comment] 2021-07-11 09:29
@hasufell as I said, let's fix it in core first. Somehere there's a rule that `<tab>` and `<c-i>` is considered the same key w.r.t internal functions such as `map <c-i>`, we need to change it to be have like `<bs>` and `<c-h>` (which can be mapped independently, regardless if the latter is transformed into the former). 

> (g)vim is able to distinguish ctrl-i and tab since some time, so it appears neovim is far behind here and I can't figure out from this discussion

So there likely is a vim-patch for the core part. I can't find it immediately, what is the time scale of "some time"?

**Comment by hasufell** [comment] 2021-07-11 09:54
> 
> So there likely is a vim-patch for the core part. I can't find it immediately, what is the time scale of "some time"?

https://github.com/vim/vim/issues/6338#issuecomment-649789502

I wonder if it's just this: https://github.com/vim/vim/commit/fd615a3c901f59abddca27c6a09940be552c0f4d

**Comment by bfredl** [comment] 2021-07-11 09:58
Hmm, that one only modifies specific gui code. This has some changes to getchar.c but not sure it is that one either https://github.com/vim/vim/commit/6a0299d8f4c7a64c64d60a6bb39cfe6eaf892247

**Comment by bfredl** [comment] 2021-07-11 10:08
could also be this one https://github.com/vim/vim/commit/459fd785e4 . The description mentions only Ctrl-H but the additional logic around "simplify" might also prevent `<c-i>` to be simplified into `key=0x09` (TAB).

**Comment by zeertzjq** [comment] 2021-10-02 01:00
Maybe these lines are also related?
<https://github.com/neovim/neovim/blob/dc4670038e0441dfda7ba11c519b834624a1f6fd/src/nvim/keymap.c#L748-L755>

**Comment by neovim-discourse** [comment] 2021-12-04 19:04
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/nitty-gritty-questions-on-terminal-nvim-and-keyboard-events/1624/1

**Comment by hasufell** [comment] 2022-01-26 17:55
Happy 5th anniversary!

**Comment by gpanders** [comment] 2022-03-19 01:24
https://github.com/neovim/neovim/issues/15352 is a related (possibly) duplicate issue.

My understanding is that this is separate from S8C1T mode: S8C1T solves the problem of disambiguating Alt keymaps from Esc keymaps (rendering `'ttimeout'` and `'ttimeoutlen'` obsolete). What's needed to distinguish `<C-I>` from `<Tab>` is instead @leonerd's "fixterms" proposal, known also as `CSI u`.

Neovim can already correctly interpret CSI u codes via its use of libtermkey; however, Neovim must explicitly request the terminal emulator to send these codes by sending the `Eneks` termcap string `\x1b[>4;1m`, as @gnachman mentioned in #15352.

Vim controls this setting via the `t_TI` and `t_TE` variables, which Neovim does not have. Instead, we will likely need to introduce a new option for this.

**Comment by gnachman** [comment] 2022-03-19 05:23
I don't believe that libtermkey parses keystrokes from modifyOtherKeys mode 1; it's a separate protocol that happens to share some codes in common. IMO modifyOtherKeys mode 1 is superior and much more well defined. It would also match vim's behavior to use modifyOtherKeys 1 or 2.

**Comment by justinmk** [comment] 2022-03-19 07:35
> Vim controls this setting via the `t_TI` and `t_TE` variables, which Neovim does not have. Instead, we will likely need to introduce a new option for this.

Can we do it opportunistically / by default, instead of introducing an option?

**Comment by gpanders** [comment] 2022-03-19 15:33
> I don't believe that libtermkey parses keystrokes from modifyOtherKeys mode 1; it's a separate protocol that happens to share some codes in common. IMO modifyOtherKeys mode 1 is superior and much more well defined. It would also match vim's behavior to use modifyOtherKeys 1 or 2.

Yes I think this is correct; however, we are already using `libtermkey` to parse keyboard input so I think the ship has sailed as far as what encoding scheme Neovim uses. Xterm can support the CSI u scheme with the [`formatOtherKeys`](https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:formatOtherKeys) option, so Xterm users are not left in the dust here.

**Comment by gnachman** [comment] 2022-03-28 00:22
> > I don't believe that libtermkey parses keystrokes from modifyOtherKeys mode 1; it's a separate protocol that happens to share some codes in common. IMO modifyOtherKeys mode 1 is superior and much more well defined. It would also match vim's behavior to use modifyOtherKeys 1 or 2.
> 
> Yes I think this is correct; however, we are already using `libtermkey` to parse keyboard input so I think the ship has sailed as far as what encoding scheme Neovim uses. Xterm can support the CSI u scheme with the [`formatOtherKeys`](https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:formatOtherKeys) option, so Xterm users are not left in the dust here.

There is no control sequence to set formatOtherKey. I think it would be worth considering supporting modifyOtherKeys in addition to CSI u. Because CSI u can't be enabled by a control sequence, it may as well not be there for the vast majority of your users. Furthermore, most terminal emulators don't support CSI u. I believe that CSI u was designed so as to coexist with modifyOtherKeys, so your existing CSI u support wouldn't need to break if you enable modifyOtherKeys=1.

**Comment by GustavoKatel** [comment] 2022-04-17 19:29
is this fixed by https://github.com/neovim/neovim/pull/17825 ?

**Comment by dundargoc** [comment] 2022-04-17 20:01
It seems so. Thanks.

**Closed by dundargoc** 2022-04-17 20:01 UTC
Labels: enhancement, tui, input

**Comment by 3rd** [comment] 2022-04-20 08:42
Just did a build using the [neovim-nightly-overlay](https://github.com/nix-community/neovim-nightly-overlay) on Nix, doesn't seem to work for me.

```
nvim -u NORC
nmap <tab> a
// both <tab> and <c-i> trigger the action
```

**Comment by zeertzjq** [comment] 2022-04-20 08:45
Your terminal needs to support it.

**Comment by 3rd** [comment] 2022-04-20 09:06
@zeertzjq Thanks for the reply!

I tried it with kitty, which seems to differentiate between <c-i> and <tab>.
https://asciinema.org/a/2awa507mbIR7DybOkY6fPcIPr

Looking at https://sw.kovidgoyal.net/kitty/keyboard-protocol/ to understand more, will report back hopefully with the needed steps to make it work with kitty.

**Comment by zeertzjq** [comment] 2022-04-20 09:14
Nvim doesn't enable kitty's keyboard protocol automatically. #18181 may enable it, or you try adding this to your config:

In Vim script:
```vim
if $TERM ==# 'xterm-kitty'
  autocmd UIEnter * if v:event.chan ==# 0 | call chansend(v:stderr, "\x1b[>1u") | endif
  autocmd UILeave * if v:event.chan ==# 0 | call chansend(v:stderr, "\x1b[<1u") | endif
endif
```

In Lua:
```lua
if vim.env.TERM == 'xterm-kitty' then
  vim.cmd([[autocmd UIEnter * if v:event.chan ==# 0 | call chansend(v:stderr, "\x1b[>1u") | endif]])
  vim.cmd([[autocmd UILeave * if v:event.chan ==# 0 | call chansend(v:stderr, "\x1b[<1u") | endif]])
end
```

**Comment by hasufell** [comment] 2022-04-25 16:26
> Your terminal needs to support it.

What does this mean? I looked at the PR and there is no documentation. I'm using alacritty.

**Comment by justinmk** [comment] 2022-04-25 16:42
> What does this mean? I looked at the PR and there is no documentation. I'm using alacritty.

    :help tui-input
