### ISSUE TITLE
"i CTRL-O u" does not immediately redraw

### ISSUE THREAD

**Issue by theowen** [neovim/neovim#7441] opened 2017-10-25 20:05 UTC
- `nvim --version`:
NVIM v0.2.1-1031-g91586d1ad
Build type: RelWithDebInfo

Features: +acl +iconv +jemalloc +tui 

- Vim (version: 8.0) behaves differently? yes
- Operating system/version: Arch Linux
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

-Inset text
-Press ^Ou

```
nvim -u NORC
isome text^Ou
```

### Actual behaviour

Text is still on screen until "1 line less; before #1  2 seconds ago" is deleted.

### Expected behaviour

Text is immediately deleted from screen when 'u' is pressed.

**Comment by bew** [comment] 2017-10-25 20:13
> Text is still on screen until `1 line less; before #1 2 seconds ago` is deleted.

Or until you press a key (which will be written like in insert mode).

**Comment by justinmk** [comment] 2017-10-25 20:33
Confirmed. Can someone check if this happened in 0.2, and if not, bisect to the problem commit?

**Comment by bew** [comment] 2017-10-25 21:19
It happens for me too, I'm on Arch, using the official neovim package which seems to be version 0.2.0.

**Comment by snoblenet** [comment] 2017-10-28 04:18
I have a problem which may be related.

Latest Neovim. Latest Mac OS X. Latest iTerm2.

On the Mac, pressing `option-e` enters the `´` character.

In my `init.vim` I have `nnoremap ´ <C-W>=`

After I press `option-e`, my split windows do not resize until after I have entered something else, such as `jk`.

BTW, hacks like `nnoremap ´ <C-W>=jk` or `nnoremap ´ <C-W>=:redraw<CR>` do not force the mapping to work.

I know the issue is with Neovim's handling of the option-key mapping as `nnoremap <C-E> <C-W>=` works just fine.

I've just checked Vim 8.0 and it has the same bug. However, I'm filing this here as I use Neovim fulltime.

**Comment by snoblenet** [comment] 2017-10-28 05:58
Update: `nnoremap <A-E> <C-W>=:redraw!` (with the `!`) works.

**Comment by justinmk** [comment] 2017-10-28 13:16
@snoblenet That's not the same issue,  `´` is waiting for a combining character. Even in Chrome option-e waits for a following character to be typed.

**Comment by glacambre** [comment] 2021-06-05 16:15
Can't reproduce on master anymore, so I'll close this issue :)

**Closed by glacambre** 2021-06-05 16:15 UTC
Labels: bug, display
