### ISSUE TITLE
[clipboard] terminal starts dancing when opening a directory in neovim :)

### ISSUE THREAD

**Issue by gaurav712** [neovim/neovim#9806] opened 2019-03-28 21:45 UTC
- `nvim --version`: NVIM v0.3.4
- Vim (version: ) behaves differently? yeah , it does. Version is : VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar  6 2019 21:38:32)
- Operating system/version: Arch Linux (up-to-date)
- Terminal name/version:tried it on latest st, termite and alacritty (it doesn't matter what terminal you are using)
- `$TERM`:st-256color(for st), xterm-termite(for termite) and xterm-256color(for alacritty)

### Steps to reproduce using  `nvim -u NORC`
It just behaves the same. No matter if I use config-file or not
I tried `nvim .scripts/` to open the directory specified ☝️

### Actual behaviour
It just goes crazy. Terminal window starts changing it's size like 20 times a second. I know I can't explain it better with words so, have a look at this :  https://github.com/neovim/neovim/issues/9847. If you want the directory I was trying, it here (named '.scripts') : https://github.com/gaurav712/dotfiles_sway.

### Expected behaviour
Well, you know how it should behave. Show the files. Don't do crap stuff.
The thing is, I like NEOVIM a lot and don't wanna keep vim installed just for some special task.

**Comment by KillTheMule** [comment] 2019-03-28 21:47
There's not video in that repository. Please also provide specific steps for reproduction, how exactly to you open a directory?

**Comment by gaurav712** [comment] 2019-03-28 21:53
Sorry, connection was slow then. It's there now. I didn't expect a reaction this quick.

**Comment by justinmk** [comment] 2019-03-28 22:06
Thanks for the report. https://github.com/neovim/neovim/pull/9645 probably fixes this. Can you try the development version (0.4.0)? 

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by gaurav712** [comment] 2019-03-28 22:11
Still no effect.

**Comment by justinmk** [comment] 2019-03-28 22:19
Never heard of this problem, so would need you to debug it. What happens if you remove `tui_guess_size` (and the calls to it)?

**Comment by gaurav712** [comment] 2019-03-28 22:35
An now it launches in a tiny part of the terminal. Something like 100*100pixels

**Comment by justinmk** [comment] 2019-03-28 22:44
You say this happens when opening any directory? Or a specific directory with specific contents? 

- Can you try commenting-out the four sections of `tui_guess_size` one-by-one, to see which section causes the issue?
- Can you try changing [this line](https://github.com/justinmk/neovim/blob/6753773408c9846d872fea0a99d232bf095b10a1/src/nvim/tui/tui.c#L893) to: 
  ```
  if (!got_winch && (!starting || did_user_set_dimensions)) {
  ```

**Comment by gaurav712** [comment] 2019-03-28 22:55
No effect!. Sorry for delayed replies. I cleared the compiled binaries. Had to compile again. God it's hell compiling it on a pentium. 
And yeah, the previous one was when I was opening files/directories.

**Comment by justinmk** [comment] 2019-03-28 23:16
Can you comment out these lines:

https://github.com/neovim/neovim/blob/a9fa3c3bdd2dd5ca6fe345182feab119185df24f/src/nvim/tui/tui.c#L896-L898                                                 


If that doesn't work, I'm out of ideas. And "visit a directory" isn't enough for anyone to attempt to fix this.

**Comment by gaurav712** [comment] 2019-03-28 23:17
That page says "Page not found"

**Comment by justinmk** [comment] 2019-03-28 23:35
@gaurav712 fixed the link

**Comment by gaurav712** [comment] 2019-03-29 03:35
Nothing! I can live without "opening the directory" feature though.

**Comment by justinmk** [comment] 2019-03-29 09:47
Try with TERM=ansi

**Comment by gaurav712** [comment] 2019-03-29 11:12
again nothing

**Comment by justinmk** [comment] 2019-04-05 20:56
Reopened since this seems to be affecting others. However if [this change](https://github.com/neovim/neovim/issues/9806#issuecomment-477805207) doesn't avoid the issue I don't know what to do. Can someone else confirm that change doesn't fix the issue?

**Comment by puresick** [comment] 2019-04-08 09:03
> Reopened since this seems to be affecting others. However if [this change](https://github.com/neovim/neovim/issues/9806#issuecomment-477805207) doesn't avoid the issue I don't know what to do. Can someone else confirm that change doesn't fix the issue?
> 
> And if that's confirmed, can someone bisect to the exact commit that caused this?

I did a quick package downgrade on arch linux and the problem started with the 0.3.2 release. 0.3.1 with netrw v156 works fine!
I'll try to run down to the exact commit this is happening.

**Comment by puresick** [comment] 2019-04-08 09:21
> Reopened since this seems to be affecting others. However if [this change](https://github.com/neovim/neovim/issues/9806#issuecomment-477805207) doesn't avoid the issue I don't know what to do. Can someone else confirm that change doesn't fix the issue?
> 
> And if that's confirmed, can someone bisect to the exact commit that caused this?

BTW, uncommenting the 3 LOC in `tui.c` does not solve the problem, BUT I observed that the length of the flickering may depend on the count of files and folders in the current directory being opened.
I opened a dir with just one binary (the built nvim) and it just flickered a couple of times. After that it was usable until the dir changed!

I applied this "patch" to master.

**Comment by puresick** [comment] 2019-04-08 09:51
@justinmk Ok I got the commit from which on this behaviour started: [05f9c7c](https://github.com/neovim/neovim/commit/05f9c7c2f7f52a5b4b1a72a49dab99dc21195c7d).

**Comment by justinmk** [comment] 2019-04-08 11:44
> @justinmk Ok I got the commit from which on this behaviour started: [05f9c7c](https://github.com/neovim/neovim/commit/05f9c7c2f7f52a5b4b1a72a49dab99dc21195c7d).

Interesting. @gaurav712 are you also using Wayland? As a workaround, trying forcing the clipboard provider to use something else, e.g. tmux:

```
    let g:clipboard = {
          \   'name': 'myClipboard',
          \   'copy': {
          \      '+': 'tmux load-buffer -',
          \      '*': 'tmux load-buffer -',
          \    },
          \   'paste': {
          \      '+': 'tmux save-buffer -',
          \      '*': 'tmux save-buffer -',
          \   },
          \   'cache_enabled': 1,
          \ }
```

Does that fix the behavior? 

This seems like a bug in wayland/sway, but maybe we can add some logic that prevents hysteresis.

**Comment by puresick** [comment] 2019-04-08 13:11
> Interesting. @gaurav712 are you also using Wayland? As a workaround, trying forcing the clipboard provider to use something else, e.g. tmux:
> 
> ```
>     let g:clipboard = {
>           \   'name': 'myClipboard',
>           \   'copy': {
>           \      '+': 'tmux load-buffer -',
>           \      '*': 'tmux load-buffer -',
>           \    },
>           \   'paste': {
>           \      '+': 'tmux save-buffer -',
>           \      '*': 'tmux save-buffer -',
>           \   },
>           \   'cache_enabled': 1,
>           \ }
> ```
> 
> Does that fix the behavior?
> 
> This seems like a bug in wayland/sway ( `wl-copy` or `wl-paste` provokes a resize?), but maybe we can add some logic that prevents hysteresis.

This fixed that behaviour for me!

**Comment by puresick** [comment] 2019-04-08 13:17
Running `wl-paste` manually in the terminal triggers some weird resize and returns to normal after it exits.

I'm not sure if this should be fixed here on neovims side. I think this might be a wl-paste (aka [wl-clipboard](https://github.com/bugaevc/wl-clipboard)) problem which needs to be adressed on their side.

**Comment by puresick** [comment] 2019-04-08 13:39
Ok one more little thing I noticed after using it for a few minutes with the updated `wl-clipboard`.
I still get weird glitches now (the cursor looks like it is redrawn really fast) and neovims cpu load rises to around 60% on one core (CPU: i7 7700HQ).

I now uninstalled `wl-clipboard` completely to prevent this.
Maybe there needs to be some workaround in neovim until `wl-clipboard` got this fixed.
I will open an issue on their side regarding this problem.

**Comment by gaurav712** [comment] 2019-04-10 15:55
> 
> Interesting. @gaurav712 are you also using Wayland?

Yeah, I am. Installing wl-clipboard-git from AUR as suggested by @puresick Solved it for me but he's right about cpu load so I uninstalled it as well.

One more thing. As it's not a neovim issue, should it be marked as **solved**?

**Comment by justinmk** [comment] 2019-04-10 16:00
> One more thing. As it's not a neovim issue, should it be marked as **solved**?

Yes, but I think we could avoid the issue by some sort of "debouncing" logic.

**Comment by Hello71** [comment] 2019-05-26 12:38
seems like neovim repeatedly executes and kills `wl-copy --foreground --primary`. this also has the side effect of leaving unlimited /tmp/wl-copy-buffer-* directories.

**Comment by justinmk** [comment] 2019-05-26 12:51
> seems like neovim repeatedly executes and kills `wl-copy --foreground --primary`. 

@Hello71 what does `:set clipboard?` say? If you have `clipboard=unnamed[plus]` then yes, the clipboard backend will be invoked on every yank because that's what you told it to do.

> his also has the side effect of leaving unlimited /tmp/wl-copy-buffer-* directories.

Are we invoking `wl-copy` incorrectly? Or what are you suggesting?

**Comment by Hello71** [comment] 2019-05-26 19:06
not "on every yank", a zillion times on start. seems like a race condition too, attaching gdb and breaking on fork/clone makes it stop.

**Comment by justinmk** [comment] 2019-05-26 19:24
@Hello71 isn't that  the same behavior as already discussed above?

**Comment by kovidgoyal** [comment] 2019-06-03 02:59
Just FYI you can use OSC 52 (terminal escape code) to interact with the clipboard without needing to rely on any third party tools. The only downside with OSC 52 is that it may or may not be available in all terminals and may or may not be turned on by default. For instance, in kitty, writing to the clipboard is enabled by default but reading is turned off for security reasons, the user has to enable it in kitty.conf.

It might be worth adding a "terminal" provider to the list of clipboard providers you already have. Note that the version of the OSC 52 protocol that kitty implements is slightly modified (in a way that has no bad side-effect in other terminals) to allow for copying arbitrary lengths of text https://sw.kovidgoyal.net/kitty/protocol-extensions.html#pasting-to-clipboard

**Comment by justinmk** [comment] 2019-08-02 17:31
@kovidgoyal thanks for the note. See also https://github.com/neovim/neovim/issues/3344

**Comment by NilsIrl** [comment] 2019-08-08 23:02
> @Hello71 isn't that the same behavior as already discussed above? [#9806 (comment)](https://github.com/neovim/neovim/issues/9806#issuecomment-480827573)

Yes, the artifacts are cause by `wl-paste`. However it seems that `nvim` is somehow calling `wl-paste` many times of unknown reasons. 

So even when `wl-paste` won't produce this problem there will still be the problem that `neovim` calls `wl-paste` repeatedly.

**Comment by justinmk** [comment] 2019-09-11 19:24
Can you be more specific?

**Comment by NilsIrl** [comment] 2019-09-11 22:36
Calling `wl-paste` causes the screen to flicker and artefacts appear (or whatever you want to call it, example can be found in #9847). This is caused by some strange stuff in `wl-paste` that resizes windows.

The thing is that

**Comment by justinmk** [comment] 2019-09-11 22:41
@NilsIrl that doesn't add any new information that wasn't already posted here. We have reports here that "aligning some wayland dependencies" solved the problem. So when you say "wl-copy is being invoked incorrectly", I need to know what's incorrect and how to correct it, rather than just guessing.

**Comment by NilsIrl** [comment] 2019-09-11 22:42
Sorry I didn't know what you wanted.

**Comment by NilsIrl** [comment] 2019-09-11 22:42
Also it's wl-paste not wl-copy.

**Comment by NilsIrl** [comment] 2019-09-11 22:44
Correct is: don't call `wl-paste` repeatedly for unknown reason

Incorrect: call it repeatedly (more than once per second)

**Comment by NilsIrl** [comment] 2019-09-11 22:45
I don't know anything about vim internals but the problem could also be present on xclip.

**Comment by justinmk** [comment] 2019-09-11 23:10
If you have `clipboard=unnamed[plus]`, then again, please review the above. That setting tells Nvim to invoke the clipboard whenever the editor yanks anything. netrw also may invoke the clipboard many times.  

"Invoking `wl-{paste,copy}` incorrectly" means "sending the wrong args". It does not mean "invoking the tool many times". 

We could potentially try to "defer" clipboard invocation to workaround this issue, but that doesn't explain why "terminal dances around" (which is the issue you are posting in, and is wayland-specific).

Please only post new, relevant information, to keep the ticket from getting filled with noise.

**Comment by Hello71** [comment] 2019-09-12 01:10
summary of the status as of a few months ago: under some circumstances, including at least some invocations of netrw, neovim will repeatedly call wl-copy, wl-paste, or both (not sure which). under wl-clipboard 1.0, each invocation of wl-copy or wl-paste (not sure which) causes a zero-sized window to pop up for a brief moment (a few milliseconds). by default under sway, this causes the current pane to be divided in half for the duration that the window is open. with wl-clipboard git, the window no longer appears due to the completion of bugaevc/wl-clipboard#31. however, wl-copy is still repeatedly called, at least in some invocations of netrw. this causes some unnecessary CPU load, as well as creating many copies of `/tmp/wl-copy-buffer-*`.

**Comment by justinmk** [comment] 2019-09-12 01:17
> as well as creating many copies of `/tmp/wl-copy-buffer-*`.

Won't that happen even if it is less frequent?

**Comment by Hello71** [comment] 2019-09-12 03:01
OK, since you insist, I did some more investigation. neovim repeatedly starts and then kills wl-copy with SIGTERM. this causes it to leave behind the wl-copy-buffer directory. I see two solutions: probably, wl-clipboard should support SIGINT or SIGTERM to cleanly remove the buffer directory and exit; also, neovim can stop passing -f and micromanaging the wl-copy instances and instead allow them to automatically terminate when another item is copied.

**Comment by justinmk** [comment] 2019-09-12 03:10
Sounds good. The code is in provider/clipboard.vim , it's just vimscript.

**Comment by djsavvy** [comment] 2020-02-16 03:56
I was having the same problem, also referenced in [#6695](https://github.com/neovim/neovim/issues/6695 )

I discovered the following workaround (to be put in `nvim.init`): 

```
" Enable system clipboard integration
set clipboard+=unnamedplus
" Workaround for neovim wl-clipboard and netrw interaction hang 
" (see: https://github.com/neovim/neovim/issues/6695 and
" https://github.com/neovim/neovim/issues/9806) 
let g:clipboard = {
      \   'name': 'myClipboard',
      \   'copy': {
      \      '+': 'wl-copy',
      \      '*': 'wl-copy',
      \    },
      \   'paste': {
      \      '+': 'wl-paste -o',
      \      '*': 'wl-paste -o',
      \   },
      \   'cache_enabled': 0,
      \ }
```

Essentially, it works by overriding the calls to `wl-copy` and `wl-paste` to avoid using the `-f` foreground flag, which is what causes the tiny window to pop up.

**Comment by NilsIrl** [comment] 2020-02-16 04:33
> I was having the same problem, also referenced in [#6695](https://github.com/neovim/neovim/issues/6695)

What version of `wl-clipboard` do you have?

**Comment by djsavvy** [comment] 2020-02-16 17:23
I am using the latest version of `wl-clipboard` in the Arch repositories:
2.0.0

Note that this is the same version provided by `wl-clipboard-git` in the
AUR.

**Comment by NilsIrl** [comment] 2020-02-16 17:33
Also what version of neovim?

**Comment by djsavvy** [comment] 2020-02-18 03:27
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
```

**Comment by NilsIrl** [comment] 2020-02-18 03:46
> NVIM v0.4.3
> wl-clipboard 2.0.0

This is very odd. Under this configuration I have no problems. I think switching to wl-clipboard 2.0.0 did fix the issue (though it didn't fix the underlying problem).

**Comment by the42** [comment] 2020-06-17 08:19
I am still affected by the bug and the workaround described in https://github.com/neovim/neovim/issues/9806#issuecomment-586666047 does not work for me.

I am using wl-clipboard 2.0.0,  wl-paste as in wl-clipboard 2.x has no flag -o
Besides that I am using the custom let g:clipboard from the mentioned proposed fix to prevent the --foreground flag of wl-copy (wl-paste has no --foreground  - flag)

Opening netrw still causes heavy spawning of wl-clipboard processes which still opens a window as the Gnome App title actively running flashes, until I have to kill nvim.

**Comment by djsavvy** [comment] 2020-06-17 19:18
I'm on a WSL2 system now, so I can't check for sure, but I think my workaround stopped working for me as well. Not sure what changed.

**Comment by the42** [comment] 2020-09-02 08:01
Any update on this? I am more than willing to provide further information, as I still have no workaround why constantly wl-clipboard process gets spawned when e.g. calling `:Lexplore`

Not using unnamedplus option

**Comment by the42** [comment] 2020-09-02 09:03
Update: If I get rid of all vim-specific fixes, NetRw works. Still doing some quick "dance" but after maybe half a second it stabilizes. I am willing to accept that this is a Wayland-Gnome issue outside the reach of NeoVim and should be fixes upstream:

https://gitlab.gnome.org/GNOME/gtk/-/issues/2307

**Comment by gaurav712** [comment] 2020-09-02 19:06
@the42 yeah of course the main problem is, all the projects neovim, wl-clipboard, and gnome aren't owned by any single authority. So its hard to make them all co-operate. For now I guess, all we can have are workarounds. Neovim itself works pretty well but it can't fix this issue solely.

**Comment by meldafert** [comment] 2021-05-05 16:49
This seems to be fixed in the 0.5.0 prerelease.
With 0.4.4, I run into this problem with Plasma Wayland 5.21.4 and wl-clipboard 2.0.0 (where NetRw repeatedly invokes wl-paste in an endless loop, which hangs kwin-wayland). With 0.5.0-dev (installed via snap or the PPA), wl-paste is no longer invoked by NetRw.

**Comment by maaattes** [comment] 2021-06-15 13:31
> This seems to be fixed in the 0.5.0 prerelease.
> With 0.4.4, I run into this problem with Plasma Wayland 5.21.4 and wl-clipboard 2.0.0 (where NetRw repeatedly invokes wl-paste in an endless loop, which hangs kwin-wayland). With 0.5.0-dev (installed via snap or the PPA), wl-paste is no longer invoked by NetRw.

Just a quick note:
I'm running NVIM v0.5.0-dev+1414-g8cdffd42d with wl-clipboard 2.0.0 and Gnome 40.2 Wayland and I can still reproduce the behaviour described above (flickering). Turns out, disabling [vim-vinegar](https://github.com/tpope/vim-vinegar) fixes this.
I guess [this](https://github.com/tpope/vim-vinegar/blob/b245f3ab4580eba27616a5ce06a56d5f791e67bd/plugin/vinegar.vim#L134) line of code could be responsible.

**Comment by justinmk** [comment] 2022-07-04 20:16
Assuming https://github.com/neovim/neovim/pull/17795 fixes this, leave a comment if not.

**Comment by maaattes** [comment] 2022-07-08 14:06
I can still reproduce this issue with NVIM v0.8.0-dev+578-gca64b589c

**Comment by MahdiAghaei1** [comment] 2023-04-25 06:45
I still encounter this problem with NVIM v0.10.0-dev and wl-clipboard 2.0.0-1

**Comment by sandorex** [comment] 2023-05-07 13:52
NVIM v0.9.0 (from bob-nvim)
wl-clipboard 2.0.0

It gets fixed when i disable clipboard in nvim

When if i first open a directory it works fine but when i change it, it starts flickering, video below and it does happen in another terminal as well so it's probably not related to WezTerm
![2023-05-07 15-32-55.webm](https://user-images.githubusercontent.com/18004075/236681618-921b31cf-06c8-443a-baf6-042222fa453d.webm)

**Comment by venthur** [comment] 2023-07-11 14:49
I think https://github.com/neovim/neovim/issues/23650 is related to this issue here.

**Comment by justinmk** [comment] 2024-09-26 23:30
> #23650 is related to this issue here.

Let's track there. I don't see anything actionable in this one. Resize issues were fixed AFAIK.

**Closed by justinmk** 2024-09-26 23:30 UTC
Labels: bug, clipboard, tui, netrw
