### ISSUE TITLE
statusline glitch for multiple window

### ISSUE THREAD

**Issue by liujoey** [neovim/neovim#13016] opened 2020-09-30 18:41 UTC
NVIM v0.5.0-nightly-177-gf520c1ef8
Build type: Release
LuaJIT 2.0.5

- `vim -u DEFAULTS` (version: ) behaves differently? Yes, vim 8.x works fine.
- Operating system/version: MacOS Catalina 10.15.6
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
I can only reproduce this when using plugin VimSpector. (I do notice this glitch in other scenario but for now I only remembered this way)
- nvim -u test.vim src/some.cpp
- Press F5 to start a debug session.
- look at the statusline of the right pane, it now has two statuslines stacking.
- move around in this right bottom buffer creates more problem of the statusline.
- the ghost statusline also blocks my input prompt, if press A in this prompt buffer, the cursor will be covered by the statusline.

The test.vim has nothing but only install the VimSpector plugin.

```test.vim
  call plug#begin('~/.config/nvim/plugged')
    Plug 'puremourning/vimspector' "{{{
      let g:vimspector_enable_mappings = 'HUMAN'
    "}}}
  call plug#end()
```

### Actual behaviour
![nvim](https://user-images.githubusercontent.com/123727/94725281-81228e00-0329-11eb-9a70-aa07891f1af7.gif)

### Expected behaviour
![vim](https://user-images.githubusercontent.com/123727/94725296-87b10580-0329-11eb-9e95-e5f9135cf215.gif)

### Where is the glitch
look at the right bottom pane, the "vimspector.console" buffer, in nvim, it has an ghost statusline below the buffer, which does not update at all. While the statusline of buffer "vimspector.console" shows a virtual statusline, when moving around, this statusline has some strange display problems.

In the vim, there will be no ghost statusline, no stacking statusline.

**Comment by erw7** [comment] 2020-10-14 04:50
Thanks for the report. But I think this is a duplicate of #12689.

**Closed** 2020-11-11 05:43 UTC
Labels: bug, duplicate

**Comment by puremourning** [comment] 2020-11-19 23:46
@liujoey FYI I worked around the neovim rendering bug in vimspector now https://github.com/puremourning/vimspector/pull/301

**Comment by liujoey** [comment] 2020-12-07 17:55
@puremourning That's fantastic, great work. I'm waiting for this fix from neovim side but it is great to hear from you that you found a work around. Thank you!

**Comment by jdknox** [comment] 2021-06-08 11:58
Can this be made into a feature to have a multiline `statusline`?
