### ISSUE TITLE
LSP: finding references "index out of range" with tsserver

### ISSUE THREAD

**Issue by zerochae** [neovim/neovim#21707] opened 2023-01-09 13:54 UTC
### Describe the bug

![error](https://user-images.githubusercontent.com/103923354/211321315-8d366e6a-6b86-4e32-bcef-16bf9c453d99.gif)
<img width="1282" alt="스크린샷 2023-01-09 22 41 50" src="https://user-images.githubusercontent.com/103923354/211321631-8d238d4a-7829-4ccc-9ad5-10e15af7751c.png">

An error occurs when I try to use the go to definition function(`vim.lsp.buf.definition()`) in a typescript React project.

```
Error executing vim.schedule lua callback: ...lar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/util.lua:1735: index out of range
stack traceback:
        [C]: in function '_str_byteindex_enc'
        ...lar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/util.lua:1735: in function 'locations_to_items'
        ...neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/handlers.lua:352: in function 'handler'
        ...l/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

it is same with https://github.com/neovim/neovim/issues/19237

Among the 4 components Header, Form, Footer, and Social, Header and Social can be moved to definition.

Header and Social do not use external package modules,
Form and Footer use an external package module (like jotai).

Form and Footer are recognized as @types/react in the path defined in the lsp saga.

![error3](https://user-images.githubusercontent.com/84373490/211330301-bafd3c30-c4bd-4236-8c83-dbf6e742968e.gif)

plz help me

### Steps to reproduce

1. Move the cursor over the functional component
2. run go to definition
3. error

### Expected behavior

go to definition without error

### Neovim version (nvim -v)

NVIM v0.8.2

### Vim (not Nvim) behaves the same?

do not test, sorry

### Operating system/version

macOS 13.1 22C65 x86_64

### Terminal name/version

iterm2 ver.3.4.19

### $TERM environment variable

screen-256color

### Installation

homebrew

**Comment by mfussenegger** [comment] 2023-01-09 19:07
Could you provide reproduction steps that one can follow to reproduce the issue?

**Comment by GrayKwon** [comment] 2023-01-19 07:47
fix with my plugins 

close this

**Closed** 2023-01-19 07:49 UTC
Labels: bug, needs:repro, lsp

**Comment by roschaefer** [comment] 2023-02-02 18:57
Maybe this helps other people: This error happens inside a project with [yarn berry](https://github.com/yarnpkg/berry).

In the project root, run the following:
```
yarn dlx @yarnpkg/sdks base
```
See here: https://yarnpkg.com/getting-started/editor-sdks#neovim-native-lsp

**Comment by meowmurai** [comment] 2023-08-16 03:24
I got extractly same issue when using nvim with nvchad, can u provide more details how to fix @GrayKwon ?

**Comment by raine** [comment] 2024-10-20 10:57
For me, this problem was caused by swap files after I renamed my imports from `.ts` to `.js` to make ESM work.

```
rm /Users/$USER/.local/state/nvim/swap/*
```
