### ISSUE TITLE
It suddenly crashed when I pressed the keybinding for :w!

### ISSUE THREAD

**Issue by printfdebugging** [neovim/neovim#28222] opened 2024-04-07 21:52 UTC
### Problem

So I was working in neovim (built from source), and when I saved the file using the keybinding <leader>w, I got this 

 COMMAND | 󰌶 5 | main.lua [+]                              utf-8 |  |  lua | 82% |  14:26
nvim: /home/printf/repos/neovim/src/nvim/marktree.c:375: unintersect_node: Assertion `seen' failed.
       %
[printf@arch] downloads $

### Steps to reproduce

I don't know if it's reproduceable, but have been through it 2 - 3 times atleast.

### Expected behavior

Should not happen

### Neovim version (nvim -v)

v0.10.0-dev-709834138

### Vim (not Nvim) behaves the same?

don't know

### Operating system/version

Arch

### Terminal name/version

st-256color

### $TERM environment variable

st-256color

### Installation

-

**Comment by zeertzjq** [comment] 2024-04-07 21:54
Duplicate of #27196

**Closed by zeertzjq** 2024-04-07 21:54 UTC
Labels: bug
