### ISSUE TITLE
Custom completion views falls back to native on imap events

### ISSUE THREAD

**Issue by arsham** [neovim/neovim#18303] opened 2022-04-29 11:10 UTC
### Neovim version (nvim -v)

v0.8.0-dev+74-g7029b4b44

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch linux

### Terminal name/version

Kitty 0.25.0-1

### $TERM environment variable

tmux-256color

### Installation

AUR

### How to reproduce the issue

Build neovim at 7029b4b44a1cea58af3f54a4d62757b29a8e6aeb
Install [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) plugin with the following setup:
```lua
cmp.setup({
  -- ...
  mapping = cmp.mapping.preset.insert({
    -- ...
    ["<C-j>"] = cmp.mapping.select_next_item({
      behavior = cmp.SelectBehavior.Select,
    }),
    ["<C-k>"] = cmp.mapping.select_prev_item({
      behavior = cmp.SelectBehavior.Select,
    }),
    -- ...
  }),
  window = {
    completion = cmp.config.window.bordered(),
    documentation = cmp.config.window.bordered(),
  },
  -- ...
})
```
Invoke the completion in insert mode, use `<C-j>` to go to the next item.

### Expected behavior

This is the behaviour at 68ddbdd03b0d5884261ab3a7b624195a4a77bd8d 
![1](https://user-images.githubusercontent.com/428611/165933265-f47eadbd-7ff8-4e3c-805e-27e7cb5cfe67.gif)

### Actual behavior

![2](https://user-images.githubusercontent.com/428611/165933408-8d7004c6-62f8-41ef-976a-3fcc584ab762.gif)

**Comment by zeertzjq** [comment] 2022-04-29 11:17
Do this bug exist on latest HEAD?

**Comment by arsham** [comment] 2022-04-29 11:40
Current HEAD is 8c548c9e5416b4e25b51c018ceaa433756ee99b1 and yes, the bug persists. 7029b4b44a1cea58af3f54a4d62757b29a8e6aeb is the commit that introduces this bug.

**Comment by zeertzjq** [comment] 2022-04-29 11:47
Oh, I think I know what the problem is.

**Comment by arsham** [comment] 2022-04-29 13:35
It fixes the issue, thanks!

**Comment by zeertzjq** [comment] 2022-05-13 02:58
The fix can cause more problems than it solves. I'm considering reverting it.

**Comment by hrsh7th** [comment] 2022-05-13 10:18
I've merged the fixing PR thank you!

**Closed** 2022-05-13 10:25 UTC
Labels: input, bug-regression, mappings
