### ISSUE TITLE
window size  can't auto resize with tmux

### ISSUE THREAD

**Issue by rockagen** [neovim/neovim#8803] opened 2018-07-31 09:21 UTC
Open neovim based tmux, neovim window size can't auto resize.

version: NVIM v0.3.2-69-ga2253744c

[![asciicast](https://asciinema.org/a/YgfR2mPGQrAIKKvpy3pRauczv.png)](https://asciinema.org/a/YgfR2mPGQrAIKKvpy3pRauczv)

**Comment by bitraid** [comment] 2018-07-31 10:00
It works fine with me.
Have you tried with `nvim -u NONE`?

**Comment by rockagen** [comment] 2018-07-31 10:10
I run `nvim -u NONE` is works fine.
but,I set `set lines=32 columns=104` in .vimrc, vim works fine, neovim can't auto resize the window size, i suggest neovim like vim auto resize windows will be better.

**Comment by bitraid** [comment] 2018-07-31 10:20
What's the point of setting these values?
As the help points out:
>Normally you don't need to set this.  It is done automatically by the terminal initialization code.

**Comment by justinmk** [comment] 2018-08-01 18:07
duplicate of https://github.com/neovim/neovim/issues/2403

**Closed by justinmk** 2018-08-01 18:07 UTC
