### ISSUE TITLE
Numpad arrow keys not working on kitty

### ISSUE THREAD

**Issue by NOTMASTER09** [neovim/neovim#19143] opened 2022-06-28 21:24 UTC
### Neovim version (nvim -v)

nvim 0.7.2

### Vim (not Nvim) behaves the same?

no, vim 8.2.5046

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

community repo through pacman

### How to reproduce the issue

use kitty, works as expected on other terminals
nvim --clean
enter insert mode
type anything
make sure numlock is disabled
try to move around with numpad

### Expected behavior

The cursor moves

### Actual behavior

Some kinda escape sequence is written, and the cursor does not move (ee 81 8a 0a for the numpad right/6 key)

**Comment by clason** [comment] 2022-06-28 21:27
Duplicate of #18991

**Comment by zeertzjq** [comment] 2022-06-28 21:41
Are you using X11 or Wayland?

**Comment by NOTMASTER09** [comment] 2022-06-28 21:42
> Are you using X11 or Wayland?

X11

**Comment by zeertzjq** [comment] 2022-06-28 22:32
Tracked in #14400
> Recognize keys in private use area

**Closed by zeertzjq** 2022-06-28 22:32 UTC
Labels: bug
