### ISSUE TITLE
system('cd "C:\Program Files"') fails with The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by christianrondeau** [neovim/neovim#6329] opened 2017-03-21 19:55 UTC
- `nvim --version`: `0.2.0.908` (appveyor build [11874](https://ci.appveyor.com/project/neovim/neovim/build/11874/job/vr7yhqd945cdqv25/artifacts))
- Vim (version: ) behaves differently? Yes, it works :)
- Operating system/version: Windows 10 64 bit
- Terminal name/version: nvim-qt 0.2.6
- `$TERM`: empty

### Actual behaviour

`system('cd "C:\Program Files"')` returns `The filename, directory name, or volume label syntax is incorrect`

### Expected behaviour

I would expect no output.

A better test might be: `system('cd "C:\Program Files"') && dir` which shows some output in vim, but fails with the same error in nvim.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
echom system('cd "C:\Program Files"')

```

There was a related issue: https://github.com/neovim/neovim/pull/5280#issue-174549578 but it is closed and I did not see anything specifically related to that issue.

Note that the problem is related to quotes, because this: `echom system('cd C:\Program Files && dir')` works perfectly.

**Comment by justinmk** [comment] 2017-03-21 20:15
https://github.com/neovim/neovim/pull/5280#issue-174549578 was related but not quite the same. But yes, this is an important issue.

**Comment by janlazo** [comment] 2017-03-22 03:10
I get no output for the following commands.

- system('cd C:\Program Files')    (no double quotes)
- system(['cd "C:\Program Files"']) (has double quotes)

**Comment by equalsraf** [comment] 2017-03-22 11:10
Yes quoting when using `system(string)` is broken in Windows:

- The string argument is converted according to options like `shell`, `shellcmdflag`, `sxq` and `sxe`. The current defaults for windows seem wrong, but this does not explain the current issue. `shell_build_argv()` builds the actual argv, e.g. for 'system('cd "c:\Windows"')' it uses `['cmd.exe', '/c', 'cd "c:\Windows"']`
- After this conversion argv is passed on to do_os_system() that calls libuv to spawn the process. Libuv does its own quoting at this point.

> system(['cd "C:\Program Files"']) (has double quotes)

@janlazo  this case was not supposed to work anyway. The `[arg0, arg1, ...]` expects arg0 to be an executable, but `cd` is a shell command.

Some relevant references on these issues

- https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/
- https://technet.microsoft.com/en-us/library/bb490880.aspx#EBAA

**Comment by justinmk** [comment] 2017-03-22 11:16
> this case was not supposed to work anyway. The [arg0, arg1, ...] expects arg0 to be an executable, but cd is a shell command.

In fact arg0 in the above case is `cd "C:\Program Files"`, which of course is not an executable.

**Comment by equalsraf** [comment] 2017-03-22 11:49
One more case that looks wrong is `echo system('echo ""')`

```
\"\"
```

But where did the slash come from?

**Comment by christianrondeau** [comment] 2017-03-22 11:53
@equalsraf this is exactly the test I was doing just now :) The interesting thing is that when I type `cd "\C:\"` in `cmd.exe`, I get `The filename, directory name, or volume label syntax is incorrect.` so we're on something :)

**Comment by equalsraf** [comment] 2017-03-22 12:08
@christianrondeau there are couple other tricks that help testing

- If we assume that the error is not in the construction of the shell command, then calling something like `system(['cmd.exe', '/c', '...quoted shell command'])` should be equivalent to `system(cmd)`
- if you are building Neovim from source there is a test binary `printargs-test.exe` that will print outs its arguments when called (this is not shipped with the builds)

**Comment by justinmk** [comment] 2017-03-23 18:47
`os_win32.c` in Vim has `unescape_shellxquote()`, used by `mch_call_shell()` and `mch_system_piped()`. That's at least part of the puzzle.

**Comment by justinmk** [comment] 2017-03-25 09:29
> But where did the slash come from?

@equalsraf The slashes are coming from libuv. With the `UV_PROCESS_WINDOWS_VERBATIM_ARGUMENTS` flag, the slashes are gone.

**Comment by janlazo** [comment] 2017-03-27 00:28
@equalsraf @justinmk
Does `shellslash` do anything for `system()` or `shellescape()` in Neovim?
I'm relying on it for the vim plugin of fzf and this PR, https://github.com/junegunn/fzf/pull/882
I'm using powershell to do what `shellescape()` should be doing for cmd but it has a longer startup than cmd and the output redirection uses utf16 encoding.

**Comment by equalsraf** [comment] 2017-03-27 00:48
In #6359 it does affect shellescape() for sure.

> should be doing for cmd but it has a longer startup than cmd and its output redirection uses utf16 encoding so I have run to powershell again to convert it to utf8

do you have an example for this? Are you getting utf16 in your vimscript?

**Comment by janlazo** [comment] 2017-03-27 00:58
https://github.com/janlazo/fzf/blob/5979c87e27058bb8721730fe7d1daa77b6510db8/plugin/fzf.vim#L655-L663
For the vim plugin of fzf, output redirection is used to send all selected entries to a temporary file via `tempname()`. The linked function is used to extract a list of lines from the temporary file. Problem is `readfile()` returns the lines as is, maintaining the utf16 encoding because of powershell. Outputting the list via `echom` and `join()` results in garbled text such that the main callback function in that vim plugin doesn't know what to do with the list.

**Comment by janlazo** [comment] 2017-03-27 01:04
I'm using the accepted answer from stackoverflow and making a new temporary file as storage for utf16-to-utf8 encoding conversion.

http://stackoverflow.com/questions/19388342/why-does-powershell-file-concatenation-convert-utf8-to-utf16

**Comment by equalsraf** [comment] 2017-03-27 10:26
My assumption would be that using system or jobstart instead of a temp file would yield the correct encoding into vim script - but I may be wrong here.

**Comment by justinmk** [comment] 2017-03-27 10:39
From `:help readfile()`:

> Also note that there is no recognition of encoding.  Read a
> file into a buffer if you need to.

**Comment by janlazo** [comment] 2017-03-27 11:35
Using system() resulted in strings with `^M`. I need a valid filepath for the entire line, not `^M C:\Program Files\^M`. Can jobstart handle different encodings?

**Comment by equalsraf** [comment] 2017-03-27 11:51
> Can jobstart() handle different encodings?

No but `^M` by itself is not an encoding issue, its a carriage return character seen in windows as a line ending. Altough that might be a bug in Neovim's side.

**Comment by bounceme** [comment] 2017-03-30 03:11
I think you might try `echom system('cd "\Program Files\"')` and some of the other hacks in #6387

**Comment by janlazo** [comment] 2017-03-30 10:12
@bounceme I tried all but `shellquote` because I want to stick with Vim defaults as much as possible.
Anything more will be Neovim-specific behaviour in Windows.

After reviewing my PR for fzf, I think I overdid the shellquoting because `:!` should be escaped Vim and the command passed to `:!` shouldn't have unescaped double quotes because of `set noshellslash`. To be compatible with `:!` in Vim and how fzf generates the final command via string concatenation, I plan on `jobstart(cmd, dict)`, where cmd is a string, once #6387 is merged.

**Comment by bounceme** [comment] 2017-03-30 19:10
just for clarification, `\` is not a special character in cmd.exe (not talking about shellslash, no idea there). so the addition of those is going to confuse things. You can use `^` as an escape for all the meta characters, or even just scape *everything* (except newlines) with `^`. this is the intention of `shellxescape` but it just does something incorrectly in vim/neovim. 

https://github.com/tpope/vim-dispatch/blob/master/autoload/dispatch/windows.vim#L8

**Comment by justinmk** [comment] 2017-04-11 12:45
I wonder if we can remove 'shellxescape' and 'shellxquote' entirely, now (silently ignore them), move their docs to `runtime/doc/deprecated.txt`.

**Closed** 2017-04-12 01:21 UTC
Labels: bug, platform:windows

**Comment by janlazo** [comment] 2017-04-12 04:54
Is shell redirection affected by #6497?

**Comment by equalsraf** [comment] 2017-04-12 09:11
@janlazo I would expect it to work fine. But I cannot test right now. Are you seeing any issue?

**Comment by justinmk** [comment] 2017-04-12 11:15
@janlazo that PR changed 'shellredir' default. If you change it back what happens?

**Comment by janlazo** [comment] 2017-04-15 13:21
Maybe it is shell quoting instead of shell redirection. `shellredir` didn't seem to have an effect and `system()` and `jobstart()` are behaving as intended anyway.
Before that PR, I can put a string, representing a command with shell redirection (e.g. fzf > path/to/tempfile), in a list which is then passed to `system()` or `jobstart()` such that, on exit, I get the output from tempfile.
After that PR, I have to escape that string to ensure that shell redirection stays within the scope of the command. I don't mind this change because this is expected from cmd anyway but I have to more creative on how to escape the command.

```dosbatch
> cmd /c start /WAIT cmd /c fzf > path/to/tempfile
> type path/to/tempfile

>
```
but
```dosbatch
> cmd /c start /WAIT cmd /c "fzf > path/to/tempfile"
> type path/to/tempfile
path/to/selectedfile_1
path/to/selectedfile_2
...
>
```
works because of the quoting on the command.
I'm using cmd here directly because this is what I expect when using lists for `system()` and `jobstart()`.

**Comment by justinmk** [comment] 2017-04-15 14:14
> representing a command with shell redirection (e.g. fzf > path/to/tempfile), in a list

A list? You didn't show an actual invocation. List form always is literal.

**Comment by janlazo** [comment] 2017-04-15 15:26
```viml
let command = 'fzf > path/to/tempfile'
call jobstart(['cmd', '/c', 'start', '/wait', 'cmd', '/c', command])
```
The redirection in the last list item worked as is before.

```viml
let command = 'fzf > path/to/tempfile'
call jobstart(['cmd', '/c', 'start', '/wait', 'cmd', '/c', '"'.command.'"'])
" OR
call jobstart('start /wait cmd /c '.'"'.command.'"')
```
I have to double quote now or do something else now.

**Comment by justinmk** [comment] 2017-04-15 18:53
If we make that work it breaks everything else. `:h jobstart()` mentions the special case of cmd.exe.

**Comment by equalsraf** [comment] 2017-04-15 19:04
> I'm using cmd here directly because this is what I expect when using lists for system() and jobstart().

While this is true, cmd.exe is a tricky case which was why we disabled quoting for it in that PR. I will agree that the behaviour of cmd.exe in system([...]) is broken which was why I added the note to the jobstart docs.

Its behaviour was also broken before, it just did not trigger this particular case.

> I have to double quote now or do something else now.

`shellescape()` should also work here.

For using cmd.exe with the list call the correct solution would be something like the plugin @bounceme created during our earlier discussions https://github.com/bounceme/windowsArgv.vim.

**Comment by janlazo** [comment] 2017-04-27 01:49
@equalsraf @justinmk What about `jobstart` for `:CheckHealth`?

**Comment by janlazo** [comment] 2017-04-27 02:16
https://github.com/neovim/neovim/blob/master/runtime/autoload/health/provider.vim#L449
Can that system call use string form instead?

**Comment by equalsraf** [comment] 2017-04-27 08:11
If gem is a .bat file then it would make sense that system([list]) fails in windows. We either

- use string form, but risk facing any issues with the user's shell settings
- use list form but call the shell for the windows case as ['cmd', '/c', 'gem ...']

**Comment by janlazo** [comment] 2017-04-28 04:21
2nd option with list form and ['cmd', '/c', 'gem', ... ] works for me
```viml
let latest_gem_cmd = (has('win32') ? 'cmd /c ' : '').'gem list -ra ^neovim$'
let latest_gem = s:system(split(latest_gem_cmd))
```
gem here is `gem.cmd`, batchfile from the Windows installter for ruby.
`:CheckHealth` worked for me with this change

**Comment by equalsraf** [comment] 2017-04-28 08:40
Neat, @janlazo can you start a PR?

**Comment by justinmk** [comment] 2017-04-28 14:37
Would the ^ need to be escaped for the win32 case? I.e. `^^neovim$`.

**Comment by janlazo** [comment] 2017-04-28 23:45
It has to for the regex to work as intended. Without escaping `^`, running that gem command directly can take 10 seconds or more. It's still fast enough to not cause the timeout though.

**Comment by bounceme** [comment] 2017-04-29 00:28
`cmd /c start /WAIT cmd /c fzf ^> path/to/tempfile`  can you try that ? i think since there are two cmd execs it needs to be escaped (guessing though)

**Comment by janlazo** [comment] 2017-04-29 01:07
@bounceme IIRC, Vim runs 2 cmds but Neovim runs one. The solution I and @junegunn used is to pass the command to a [batchfile](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L506-L522) and handle the shellescaping within the vim plugin for fzf such that it is compatible with both editors. We're using double quotes via [shellescape with substitute](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L48-L50). It's still lacking compared to your plugin but it does the job for now.

**Comment by bounceme** [comment] 2017-04-29 04:01
i never got to test that escaping plugin with neovim+windows haha. does it actually help with `system([])` ?

**Comment by janlazo** [comment] 2017-04-29 04:54
@bounceme It helps but I want to know how to combine both to make an escaped command. The following viml code works for me but I want do this in 2 commands at most (excluding `noshellslash`)

```viml
set noshellslash
let cmd = 'powershell -NoProfile -Command "Get-Item -Path $Env:APPDATA"'
let cmd_list = g:CommandLineToArgvW(cmd)
let cmd_arr_escaped = map(copy(cmd_list), 'g:Cmdexe(shellescape(v:val))')
let appdata = system(['cmd', '/c'] + cmd_arr_escaped)
```

**Comment by bounceme** [comment] 2017-04-29 05:13
it should be `system(['cmd', '/c'] + map(g:Command2ArgV(cmd),'g:Cmdexe(v:val)'))` according to https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/

**Comment by bounceme** [comment] 2017-04-29 05:31
it might be a problem that cmd isn't really acting interactively however.

**Comment by eramudeep** [comment] 2021-09-11 08:11
I am trying
`C:\\xampp\\mysql\\bin\\mysql.exe  -u admin -padmin123 -e"use my_db; select 'IMPORT_DONE' AS IMPORT_STATUS;"`
its working fine if i paste this command in CMD and run.

But not working when I am trying with node js child_precess
throwing error : **"The filename, directory name, or volume label syntax is incorrect.\r\n".**

Need help
