### ISSUE TITLE
:terminal : eliminate extra "filler" lines

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#9226] opened 2018-11-12 05:27 UTC
- `nvim --version`: v0.3.2
- Vim (version: ) behaves differently? Yes
- Operating system/version: Ubuntu
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
1. nvim -u NORC
2. :terminal
3. :set nu
```

### Actual behaviour
Extra line number as follow:
![image](https://user-images.githubusercontent.com/19503791/48328316-6fc13180-e67e-11e8-9645-401dd6b7b9b0.png)

### Expected behaviour
Consistent with other window:
![image](https://user-images.githubusercontent.com/19503791/48328225-135e1200-e67e-11e8-8ec6-dc331da9faf1.png)

**Comment by tweekmonster** [comment] 2018-11-12 07:33
This is just how the terminal emulator works.  All lines in the window are for rendering the terminal.  If you run `nvim` in the terminal and it renders taking up all of the window's rows, how should the line numbers appear when you exit out of the nested `nvim`?

I disable line numbers in the terminal because I don't find them useful there.

**Comment by zeertzjq** [comment] 2023-09-18 03:31
Duplicate of #8563

**Closed by zeertzjq** 2023-09-18 03:31 UTC
Labels: enhancement, terminal
