### ISSUE TITLE
Neovim 0.9.0 hi cursorline and hi cursorcolumn and statusline color go wrongs.

### ISSUE THREAD

**Issue by cklin731** [neovim/neovim#22976] opened 2023-04-09 15:28 UTC
### Problem

![Screenshot from 2023-04-09 22-30-05](https://user-images.githubusercontent.com/126345487/230781582-f56bee63-f953-4f3f-a4a1-ba93d6434272.png)
When I use nvim.
The hi cursorline and hi cursorcolumn become white and blue.
And the status  line lost its color.
But this thins just happen occasionally.

### Steps to reproduce

nvim .config/nvim/init.vim

### Expected behavior

Show the normal color.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

no, vim 8.2.2434

### Operating system/version

Debian 11

### Terminal name/version

GNOME terminal 3.38.3

### $TERM environment variable

xterm-256color

### Installation

source code

**Comment by clason** [comment] 2023-04-09 15:30
We need minimal repro steps, otherwise there's nothing we can do about it.

**Comment by cklin731** [comment] 2023-04-09 15:38
OK
I just update my report.

**Comment by clason** [comment] 2023-04-09 15:58
Nope, not good enough. We need something we can run with `nvim --clean -u test.lua` that shows the same issue.

**Comment by cklin731** [comment] 2023-04-09 16:06
![Screenshot from 2023-04-10 00-04-40](https://user-images.githubusercontent.com/126345487/230783603-0641b022-6412-4f42-adec-a6c129e96815.png)
@clason 
I am not share what you mean.
But I just open nvim 0.9.0 in Gnome Tremianl.
And it got wrong.

**Comment by luukvbaal** [comment] 2023-04-09 17:23
> nvim .config/nvim/init.vim

This is useless if we don't know the contents of your `init.vim`.

You should provide a minimal `init.vim` or `init.lua` that exhibits the behavior.

Only include options and commands that you think are necessary to break cursorline/column highlighting.

**Comment by cklin731** [comment] 2023-04-10 08:17
![Screenshot from 2023-04-10 16-15-32](https://user-images.githubusercontent.com/126345487/230859816-69689a7c-5358-4e5d-aae0-1ca0b84083ff.png)

**Comment by cklin731** [comment] 2023-04-10 08:18
I just set the mininal init.vim

**Comment by cklin731** [comment] 2023-04-10 08:24
file:///home/cklin/Pictures/Screenshot%20from%202023-04-10%2016-15-32.png
![Screenshot from 2023-04-10 16-24-02](https://user-images.githubusercontent.com/126345487/230862425-471e2343-6251-43dc-85a1-684f65dc75ef.png)

**Comment by cklin731** [comment] 2023-04-10 08:32
file:///home/cklin/Pictures/Screenshot%20from%202023-04-10%2016-15-16.png

**Comment by cklin731** [comment] 2023-04-10 08:32
![Screenshot from 2023-04-10 16-15-16](https://user-images.githubusercontent.com/126345487/230864947-072ebd26-42de-4916-930a-d6467a7001bb.png)

**Comment by shabahengam** [comment] 2023-04-10 16:15
I have this problem too.in my init file there is nothing related to colors except `set background=light`
but this is my statusline config (loading via source command in init file)
```
set noshowmode
highlight User1 ctermbg=4 ctermfg=15
highlight User2 ctermbg=7 ctermfg=15
highlight User3 ctermbg=2 ctermfg=15
highlight User4 ctermbg=0 ctermfg=6
highlight User5 ctermbg=5
highlight User6 ctermbg=3 ctermfg=15
highlight User7 ctermbg=1 ctermfg=15
highlight User8 ctermbg=249 ctermfg=15

let s:modes ={
    \ 'n'  : ['%3*', 'NORMAL'],
    \ 'i'  : ['%4*', 'INSERT'],
    \ 'v'  : ['%5*', 'VISUAL'],
    \ 'r'  : ['%6*', 'REPLACE'],
    \ 'c'  : ['%7*', 'COMMAND'],
    \ }

function! ModeColor() abort
  return get(s:modes, tolower(mode()), '%*')[0]
endfunction

function! CurrentMode() abort
  return ' ' . get(s:modes, tolower(mode()), '-')[1] . ' '
endfunction

function! Statusline()
  let status=""
  let status.=ModeColor()
  let status.=CurrentMode()
  let status.="%1* %.30f "
  let status.="%m"
  let status.="%8*"
  let status.="%= "

  let status.="%1*"
  let status.="\ %y"                                " filetype
  let status.="[%{strlen(&fenc)?&fenc:'none'},"     " file encoding
  let status.="%{&ff}]"                             " file format

  let status.="%1* %04.l-%02.c:%03.L "

  return status
endfunction

set statusline=%!Statusline()


```

**Comment by dundargoc** [comment] 2023-04-10 16:45
@cklin731 how are we supposed to test your configuration? You need to write it in text so that we can copy it.

**Comment by gaspargergo** [comment] 2023-04-11 09:51
I seem to have the same problem. The weird thing is that this only happens when I have `set background=light` in the config, with 'set background=dark', it works fine. Also, with the light background, when I manually do a `:source` command, the colors reappear.
Here are the relevant sections of my init.vim:
The statusline:
```
" --- Status line --- 
set laststatus=2
set statusline=
set statusline+=%#NormalColor#%{(mode()=='n')?'\ \ NORMAL\ ':''}
set statusline+=%#InsertColor#%{(mode()=='i')?'\ \ INSERT\ ':''}
set statusline+=%#CommandColor#%{(mode()=='c')?'\ \ COMMAND\ ':''}
set statusline+=%#VisualColor#%{(mode()=='v')?'\ \ VISUAL\ ':''}
set statusline+=%#FileNameColor#
set statusline+=\ 		" Separators
set statusline+=%f        " Path to the file
set statusline+=\ 				" Separator
set statusline+=%m				" Modified flag
set statusline+=%#StatusLineColor#
set statusline+=%=        " Switch to the right side
set statusline+=%y				" File type
set statusline+=\ 		" Separators
set statusline+=%#LineNumberColor#
set statusline+=\ \ %l:%c\ \       " Current line and coloumn
```
And the highlight groups and colorscheme:
```
" --- Theming ---
colorscheme gruvbox
let g:gruvbox_contrast_dark='hard'
set background=light
highlight Comment gui=italic
highlight StatusLineColor guifg=White guibg=#1d2021
highlight NormalColor guifg=Black guibg=#b8bb26 gui=bold
highlight InsertColor guifg=White guibg=#458588 gui=bold
highlight ReplaceColor guifg=Black guibg=maroon1 
highlight VisualColor guifg=White guibg=#b16286 gui=bold
highlight CommandColor guifg=White guibg=#427b58 gui=bold
highlight FileNameColor guifg=White guibg=#555555
highlight LineNumberColor guifg=Black guibg=#CCCCCC
```

Of course, I can provide the whole of my config file if necessary.

**Comment by cklin731** [comment] 2023-04-13 16:46
init.vim
----------------------------------------------
set t_Co=256
set termguicolors
colo cklin
set cursorline
set cursorcolumn
set hlsearch
hi CursorLine cterm=none ctermbg=Gray ctermfg=Black
hi CursorColumn cterm=none ctermbg=Gray ctermfg=Black
hi Search cterm=reverse ctermbg=none ctermfg=none
hi CursorLine gui=none guibg=#808080 guifg=#000000
hi CursorColumn gui=none guibg=#808080 guifg=#000000
hi Search gui=reverse guibg=none guifg=#ff0000
hi Pmenu guibg=#4e4e4e
hi PmenuSel guibg=#8babac

"------------------- statusline -------------------
set laststatus=2
set statusline=%#filepath#[%{expand('%:p')}]%#filetype#[%{strlen(&fenc)?&fenc:&enc},\ %{&ff},\ %{strlen(&filetype)?&filetype:'plain'}]%#filesize#%{FileSize()}%{IsBinary()}%=%#position#%c,%l/%L\ [%3p%%]
hi filepath cterm=none ctermbg=238 ctermfg=40
hi filetype cterm=none ctermbg=238 ctermfg=45
hi filesize cterm=none ctermbg=238 ctermfg=225
hi position cterm=none ctermbg=238 ctermfg=228
hi filepath gui=none guibg=#444444 guifg=#00d700
hi filetype gui=none guibg=#444444 guifg=#00d7ff
hi filesize gui=none guibg=#444444 guifg=#ffd7ff
hi position gui=none guibg=#444444 guifg=#ffff87

function IsBinary()
    if (&binary == 0)
        return ""
    else
        return "[Binary]"
    endif
endfunction
function FileSize()
    let bytes = getfsize(expand("%:p"))
    if bytes <= 0
        return "[Empty]"
    endif
    if bytes < 1024
        return "[" . bytes . "B]"
    elseif bytes < 1048576
        return "[" . (bytes / 1024) . "KB]"
    elseif bytes < 1073741824
        return "[" . (bytes / 1048576) . "MB]"
    else
        return "[" . (bytes / 1073741824) . "GB]"
    endif
endfunction

**Comment by cklin731** [comment] 2023-04-13 16:47
cklin.vim
----------------------------------------
"Vim color file
" Maintainer:   CKLIN
" Last Change:  2023 Mar 18

set background=dark
hi clear
if exists("syntax_on")
    syntax reset
endif
let g:colors_name = "cklin"

" GUI
highlight Normal    guifg=#ffffff   guibg=#171421
highlight Visual    guibg=#000000   gui=reverse
highlight StatusLine guifg=#2a7bde guibg=#ffffff
highlight LineNr guifg=#e9ad0c
highlight CursorLineNr guifg=#e9ad0c gui=none
highlight NonText guifg=#2a7bde

highlight Comment   guifg=#2a7bde
highlight Constant  guifg=#c061cb
highlight Identifier guifg=#33c7de gui=bold
highlight Statement guifg=#e9ad0c gui=none
highlight PreProc guifg=#5dd7ee
highlight Type guifg=#88feb0 gui=none
highlight Special   guifg=#af5f00

**Comment by zeertzjq** [comment] 2023-04-14 02:40
Duplicate of #22614

**Closed by zeertzjq** 2023-04-14 02:40 UTC
Labels: bug, needs:repro
