### ISSUE TITLE
add function that can add additional source to `<C-n> / <C-p>`

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#21153] opened 2022-11-22 11:12 UTC
### Feature already in Vim?

I guess no

### Feature description

```lua
            local lua_dict = {
                keyword = "~/.config/nvim/dict/lua/keyword.dic",
                func    = "~/.config/nvim/dict/lua/func.dic",
                vim     = "~/.config/nvim/dict/lua/vim.dic",
                vim_fn  = "~/.config/nvim/dict/lua/nvim-fn.dic",
                vim_api = "~/.config/nvim/dict/lua/nvim-api.dic",
            }

            vim.bo.dict = lua_dict.keyword .. "," .. lua_dict.func

            local special_map = {
                ["_"] = function ()
                    vim.bo.dict = lua_dict.vim_api .. "," .. lua_dict.func
                    return "_<C-x><C-z><C-n>"
                end,
                [":"] = function ()
                    vim.bo.dict = lua_dict.func
                    return ":<C-x><C-z><C-n>"
                end,
                ["."] = function ()
                    if utils.get_cursor_content(-4, -1) == ".api" then
                        vim.bo.dict = lua_dict.vim_api
                        return ".<C-x><C-k>"
                    elseif utils.get_cursor_content(-3, -1) == "vim" then
                        vim.bo.dict = lua_dict.vim
                        return ".<C-x><C-k>"
                    elseif utils.get_cursor_content(-3, -1) == ".fn" then
                        vim.bo.dict = lua_dict.vim_fn
                        return ".<C-x><C-k>"
                    end
                  
                    vim.bo.dict = lua_dict.func
                    return ".<C-x><C-z><C-n>"
                end,
            }
            
            for lhs, rhs in pairs(special_map) do
                vim.keymap.set("i", lhs, rhs, { expr = true })
            end
```
if neovim can have an API to add the additional sources using the table to built-in completion widow that would be great!

so we don't need to change `vim.bo.dict` to reach that :)

if neovim already has this feature, please tell me :)

**Comment by clason** [comment] 2022-11-22 11:15
Duplicate of #16488

**Closed by clason** 2022-11-22 11:15 UTC
Labels: enhancement

**Comment by dundargoc** [comment] 2022-11-22 11:58
What part of "Issues isn't the place for these, please ask in [neovim.discourse.group](https://neovim.discourse.group/) or [app.element.io/#/room/#neovim:matrix.org](https://app.element.io/#/room/#neovim:matrix.org)" in [my response](https://github.com/neovim/neovim/issues/21146#issuecomment-1322334755) did you not understand? Please ask usage questions there, we need GitHub Issues to only be about actual bugs or well-thought-out improvement suggestions.
