### ISSUE TITLE
Mapping <F1> - <F5> in terminal (windows)

### ISSUE THREAD

**Issue by wave-blessed** [neovim/neovim#10716] opened 2019-08-06 19:46 UTC
* Downloading clear nvim-win64.zip nightly build. Unpack it. Any custom configuration upsent yet.
* Run nvim.exe.
* Trying to map keys (on the fly for direct effect) `<F1>` - `<F12>` like `:map <F1> :echo 'F1'<CR>`
* Press any <F#> key.
* Keys from `<F6>` to `<F12>` work as expected.
* Keys from `<F1>` to `<F5>` make something strange like going to insert mode and spoil text.

I tried to mapping in different manner. I tried use config, tried use nmap/nnoremap etc. I tried to catch plugin which spoil it or wrong config. I tried look thrue help and google.
`:map`, `:checkhealth`, `:scriptnames` don't show anything strange.
Any soft catching keyboard.
What's wrong?

Nvim-qt works fine. Vim 8.1 works fine. Any other soft works fine.
Windows 7 x64.

**Comment by justinmk** [comment] 2019-08-06 19:55
What nvim version.

**Comment by wave-blessed** [comment] 2019-08-06 20:00
Latest nightly build from github now, but I have this behavior in number of nightly builds. I've been started to try learning vim/neovim about two weeks ago and updated neovim number of times.

**Comment by erw7** [comment] 2019-08-07 04:26
Duplicate of #8965.

**Closed** 2019-08-07 04:31 UTC
Labels: bug
