### ISSUE TITLE
neovim join (J) deletes character > if it's the first one on next line

### ISSUE THREAD

**Issue by eduardoarandah** [neovim/neovim#19729] opened 2022-08-12 00:49 UTC
### Neovim version (nvim -v)

v0.7.2

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.0

### Operating system/version

macOs 

### Terminal name/version

iterm2 3.4

### $TERM environment variable

screen-256color

### Installation

brew

### How to reproduce the issue

nvim -u NONE

insert 

```
<div>something<div
>
```

then join lines with `J`

### Expected behavior

`<div>something<div>`

### Actual behavior

destroys character `>`

`<div>something<div`

This is super weird. I started neovim with -u NONE. 
I've plugins installed with packer in its default location

https://user-images.githubusercontent.com/4065733/184265264-2901f1ef-7f2f-4678-9f1c-18a93f53c03e.mp4

**Comment by zeertzjq** [comment] 2022-08-12 00:51
Duplicate of #19729

**Comment by zeertzjq** [comment] 2022-08-12 00:52
Duplicate of #16017

**Closed** 2022-08-12 00:52 UTC
Labels: bug
