### ISSUE TITLE
:*explore from netrw creating duplicate panes

### ISSUE THREAD

**Issue by 73567876543783** [neovim/neovim#23489] opened 2023-05-05 14:36 UTC
### Problem

:Vexplore and related commands from netrw result in two panes with netrw, instead of creating a single new pane with netrw. This happens only on the unstable ppa the stable ppa doesn't exhibit the same behavior. 

### Steps to reproduce

touch script.lua
nvim --clean . 
(Open script.lua)
:Vexplore

### Expected behavior

A new pane with netrw opens and the current pane stays the same.

### Neovim version (nvim -v)

v0.10.0-dev

### Vim (not Nvim) behaves the same?

no, 8.2.4919

### Operating system/version

Pop!_OS 22.04 LTS

### Terminal name/version

GNOME Shell 42.5

### $TERM environment variable

xterm-256color

### Installation

ppa

**Comment by clason** [comment] 2023-05-05 14:38
Duplicate of https://github.com/vim/vim/issues/12304

**Closed by clason** 2023-05-05 14:38 UTC
Labels: runtime, bug-vim, netrw
