### ISSUE TITLE
Treesitter: segfault for long `->` chain in C

### ISSUE THREAD

**Issue by Eolien55** [neovim/neovim#17858] opened 2022-03-25 20:10 UTC
### Neovim version (nvim -v)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

I don't think vim supports treesitter.nvim

### Operating system/version

Linux 5.16.16-artix1-1

### Terminal name/version

st 0.8.5

### $TERM environment variable

st-256color

### Installation

Artix repos

### How to reproduce the issue

1. Open a C file with treesitter.nvim.
2. Write into it :
```
#include <stdio.h>

struct LinkedList {
	char info[50];
	struct LinkedList *next;
};

int main() {
	struct LinkedList head = {"heeyyyyyy", NULL};
	head.next = &head;

	puts(head.next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next-next->next->next->next->next->next->next->next->next->next-next->next->next->next->next->next->next->next->next->next-next->next->next->next->next->next->next->next->next->next->info);
}
```
3. Observe neovim segfaulting

### Expected behavior

NeoVim not segfaulting.

### Actual behavior

NeoVim segfaulting with `Thread 1 "v" received signal SIGSEGV, Segmentation fault. 0x00007ffff7eed03d in ts_query_cursor_next_capture () from /usr/lib/libtree-sitter.so.0`.

**Comment by madskjeldgaard** [comment] 2022-03-25 20:56
I suspect I am having a similar issue with the `supercollider` parser. It never segfaulted before  but something changed recently in nvim-treesitter that caused this I suspect. 

This is the top of the coredump from my situation:
```
Stack trace of thread 197222:
                                               #0  0x00007f961234dbc1 ts_parser_parse (libtree-sitter.so.0 + 0x10bc1)
                                               #1  0x000055a2e6baf011 n/a (nvim + 0x1d2011)
                                               #2  0x00007f96121c9f06 n/a (libluajit-5.1.so.2 + 0x9f06)
                                               #3  0x00007f96121dc73a lua_pcall (libluajit-5.1.so.2 + 0x1c73a)
                                               #4  0x000055a2e6ba01d1 n/a (nvim + 0x1c31d1)
                                               #5  0x000055a2e6bad341 nlua_call_ref (nvim + 0x1d0341)
                                               #6  0x000055a2e6d258b0 n/a (nvim + 0x3488b0)
                                               #7  0x000055a2e6c7a7b6 n/a (nvim + 0x29d7b6)
                                               #8  0x000055a2e6ad41fb n/a (nvim + 0xf71fb)
                                               #9  0x000055a2e6ac0369 n/a (nvim + 0xe3369)
                                               #10 0x000055a2e6cb5849 state_enter (nvim + 0x2d8849)
                                               #11 0x000055a2e6ac32fc edit (nvim + 0xe62fc)
                                               #12 0x000055a2e6bf816e n/a (nvim + 0x21b16e)
                                               #13 0x000055a2e6bef453 n/a (nvim + 0x212453)
                                               #14 0x000055a2e6cb589d state_enter (nvim + 0x2d889d)
                                               #15 0x000055a2e6beac20 normal_enter (nvim + 0x20dc20)
                                               #16 0x000055a2e6a58ff3 main (nvim + 0x7bff3)
                                               #17 0x00007f9611fe3310 __libc_start_call_main (libc.so.6 + 0x2d310)
                                               #18 0x00007f9611fe33c1 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d3c1)
                                               #19 0x000055a2e6a5a2fe _start (nvim + 0x7d2fe)
                                               
                                               Stack trace of thread 197223:
                                               #0  0x00007f96120c89ae epoll_wait (libc.so.6 + 0x1129ae)
                                               #1  0x00007f96123d40bd n/a (libuv.so.1 + 0x250bd)
                                               #2  0x00007f96123bd438 uv_run (libuv.so.1 + 0xe438)
                                               #3  0x000055a2e6cdfeef n/a (nvim + 0x302eef)
                                               #4  0x00007f96120435c2 start_thread (libc.so.6 + 0x8d5c2)
                                               #5  0x00007f96120c8584 __clone (libc.so.6 + 0x112584)
```

I'm running
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
```
on arch linux.
Latest nvim-treesitter.

**Comment by madskjeldgaard** [comment] 2022-03-25 21:01
and here's my `:checkhealth nvim_treesitter` output:

```

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.7.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - gowork         ✓ . . . ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - rst            ✓ ✓ . . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - perl           ✓ . ✓ . . 
  - ql             ✓ ✓ . ✓ ✓ 
  - http           ✓ . . . ✓ 
  - fish           x ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - jsdoc          ✓ . . . . 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - godot_resource ✓ ✓ ✓ . . 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - erlang         . . . . . 
  - dot            ✓ . . . ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - fusion         ✓ ✓ ✓ ✓ . 
  - gleam          ✓ ✓ ✓ ✓ ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - eex            ✓ . . . ✓ 
  - heex           ✓ ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - zig            ✓ . ✓ ✓ ✓ 
  - cooklang       ✓ . . . . 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - solidity       ✓ . . . . 
  - vala           ✓ . . . . 
  - ocamllex       ✓ . . . ✓ 
  - lalrpop        ✓ ✓ . . . 
  - norg           . . . . . 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - hocon          ✓ . . . ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - llvm           ✓ . . . . 
  - cmake          ✓ . ✓ . . 
  - make           ✓ . . . ✓ 
  - scala          ✓ . ✓ . ✓ 
  - pioasm         ✓ . . . ✓ 
  - prisma         ✓ . . . . 
  - json5          ✓ . . . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - rasi           ✓ ✓ ✓ ✓ . 
  - latex          ✓ . ✓ . ✓ 
  - r              ✓ ✓ . ✓ ✓ 
  - tlaplus        ✓ ✓ ✓ . ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - pascal         ✓ ✓ ✓ ✓ ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - gomod          ✓ . . . ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - pug            ✓ . . . ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - vue            ✓ . ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - yang           ✓ . ✓ . . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - glimmer        ✓ . . . . 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: fish(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 878
    fish(highlights) is concatenated from the following files:
    | [ERROR]:"/home/mads/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/fish/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 878
```

**Comment by zeertzjq** [comment] 2022-03-28 22:24
Duplicate of #14369

**Closed by zeertzjq** 2022-03-28 22:24 UTC
Labels: bug, bug-crash, treesitter
