### ISSUE TITLE
Should :keepjumps when switching between Terminal and Normal mode

### ISSUE THREAD

**Issue by bohrshaw** [neovim/neovim#3723] opened 2015-11-23 11:58 UTC
Both `<C-\><C-n>` from Terminal mode and `i` from Normal mode change the "jumplist".
I think this is not expected.

**Comment by doraemon96** [comment] 2018-01-17 18:38
Could this be caused because of the _setpcmark()_ call on [line 380 of src/nvim/terminal.c](https://github.com/neovim/neovim/blob/master/src/nvim/terminal.c#L380)?

Im new to neovim, I'm trying to locate where and how the char pressing events for the terminal are processed and where they invoke calls to the jumplist. I found that in the file _ex\_cmds2_ there are some _setmark()_ calls but I'm not sure if these functions are called during terminal mode.

**Comment by justinmk** [comment] 2018-01-17 21:03
@doraemon96 Thanks for the help! That could be it.

> where and how the char pressing events for the terminal are processed 

The entry point for `:terminal` input is `terminal_receive()`, which is hooked up to a stream (see `on_channel_output()`) and passively receives input.

If you have more questions feel free to ask in https://gitter.im/neovim/neovim .

**Comment by doraemon96** [comment] 2018-01-23 23:24
Just to keep record, whenever the user writes something in a terminal (without running it) and then does `<C-\><C-N>`, it creates a line in the jumplist in the form of: `user@host:~/path/to/neovim$ command` (at least for me).
And in closing the terminal window and inspecting the jumplist it reads `term://.//termnum:/bin/bash`.

Removing the lines 379 and 380 from src/vim/terminal.c (namely the calls to `checkpcmark()` and `setpcmark()` in the `terminal_enter()` function) does not change this behavior.

I'll keep looking. If someone could explain why those two lines of code are there I'd be thankful.

**Comment by doraemon96** [comment] 2018-02-02 14:33
@bohrshaw Could you explain what the problem is in more detail? I don't understand if the terminal should not modify the jumplist at all or if there's a :keepjupmps that isn't working.
The title of the issue is confusing (at least to me).

**Comment by bohrshaw** [comment] 2018-02-02 14:53
@doraemon96 Thanks for the "advice". I've reverted the title to the original one.

**Comment by doraemon96** [comment] 2018-02-02 18:10
@bohrshaw: Just to be clear, there are 3 cases (I've found) where the jumplist is modified by the terminal (This was tested by using `./build/bin/neovim`, I hope this is irrelevant)

1. You open a terminal and inmediately after close it. It creates something in the style of `term://.//termpid:/bin/bash` in the jumplist (where `termpid` is the pid of the terminal created).
2. You open a terminal and start editing. Without writing anything you enter Normal mode with `<C-\><C-n>`. It creates a `user@host:~/Path/To/neovim$` line in the jumplist.
3. You do as step 2, but write some command in the terminal (without pressing enter) and return to Normal mode. It creates a `user@host:~/Path/To/neovim$ command` entry in the jumplist.

Which of these are desired and which should not happen (or there should be no changes at all in the jumplist when working with the terminal?)

**Comment by bohrshaw** [comment] 2018-02-03 00:38
Basically my rationale is that, in terms of the jump list, the Terminal mode should be treated like Insert mode.

**Comment by justinmk** [comment] 2018-02-03 11:33
@bohrshaw the cursor behavior since this issue was first reported, has changed. It doesn't jump to the bottom of the buffer. Which of the above items listed in wrong?

Can you give specific steps that can be tested?

**Comment by justinmk** [comment] 2018-02-03 19:07
Writing tests is the first step. And I still don't see a minimal repro ...

**Comment by bohrshaw** [comment] 2018-02-04 14:32
After switching back and force between Terminal and Normal mode, the jump list contains new entries.
This could be tested by calculating the length of the jump list before and after it changes.

However, from a usage perspective, I seldom notice this misbehavior.

**Comment by justinmk** [comment] 2018-02-05 22:42
Not sure what's perfect, but the current behavior is probably not justified for the usual reasons: terminal buffers may have interactive processes, so cursor placement is arbitrary, and therefore tracking it in the jumplist is useless (at best). And (based on the docstring for `checkpcmark()`) it looks like we're calling `checkpcmark()` and `setpcmark()` in the wrong order.

see https://github.com/neovim/neovim/pull/7971

@doraemon96 Thanks for looking at this, your comments saved time. I think we can just remove the call from `terminal_enter()` entirely.

**Closed** 2018-02-07 00:52 UTC
Labels: :terminal, bug, complexity:low
