### ISSUE TITLE
:w !clear prints some weird characters

### ISSUE THREAD

**Issue by st203** [neovim/neovim#21840] opened 2023-01-16 16:49 UTC
### Describe the bug

In vim I normally use a command such as :w !clear; python to run a python script.

I use the clear command to clear the screen before seeing program output.

This does not work in Neovim, I get some weird characters (see screengrab).
<img width="815" alt="Screenshot 2023-01-16 at 16 46 12" src="https://user-images.githubusercontent.com/11555112/212729308-8a59f6d1-496a-4f48-929f-91dfdbd312e4.png">

### Steps to reproduce

:w !clear 

### Expected behavior

Clears the screen 

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

No 

### Operating system/version

Mac (M1) Ventura 13.1

### Terminal name/version

iterm2

### $TERM environment variable

bash: xterm-256color: command not found

### Installation

brew install neovim

**Comment by ii14** [comment] 2023-01-16 16:56
`:!` is not interactive in neovim, it can't understand escape sequences.

Duplicate of #1496

**Closed by ii14** 2023-01-16 16:56 UTC
Labels: bug
