### ISSUE TITLE
Bash syntax highlighting is broken

### ISSUE THREAD

**Issue by tupos** [neovim/neovim#22200] opened 2023-02-10 10:12 UTC
### Describe the bug

bash syntax highlighting is broken in comparison with vim

### Steps to reproduce

```bash
nvim --clean << EOF
#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
    exit 0
fi

export FOO="$1"
EOF
```

compare the same output with vim

If the first two lines are removed (i.e. the if is the first line) the syntax highlighting is restored.

### Expected behavior

The syntax highlighting should be correct

### Neovim version (nvim -v)

`NVIM v0.9.0-dev-912+gfe1e6b82f`

### Vim (not Nvim) behaves the same?

no, `VIM 9.0 Included patches: 1-962`

### Operating system/version

Linux SLES 15-SP1, 15.1

### Terminal name/version

tmux 3.3a

### $TERM environment variable

`screen-256color`

### Installation

build from repo

**Comment by zeertzjq** [comment] 2023-02-10 10:16
Duplicate of https://github.com/vim/vim/issues/11937

**Closed by zeertzjq** 2023-02-10 10:16 UTC
Labels: bug
