### ISSUE TITLE
cannot execute symlink to win32yank.exe in WSL

### ISSUE THREAD

**Issue by louisch** [neovim/neovim#12113] opened 2020-04-12 07:44 UTC
Following the instructions in the FAQ, I installed neovim on both WSL and Windows (using scoop), then symlinked win32yank to $PATH in WSL, specifically with
```
sudo ln -s /mnt/c/Users/<username>/scoop/apps/neovim/current/bin/win32yank.exe /usr/local/bin/win32yank.exe
```
I did confirm that this symlink does work by using it from shell, although it returns with an error and no output. I also tried symlinking it to `/usr/bin`, as well as symlinking from `/scoop/apps/neovim/0.4.3` instead of `current`. (`current` is a symlink to the latest installed version in scoop). I also tried creating an additional symlink called `win32yank` (to the same file) in addition to the `win32yank.exe` symlink.

Inside neovim itself on WSL, `:registers` shows `clipboard: error: 1` instead of any `*` or `+` register, and does not show the windows clipboard in any other register.

`:checkhealth` just says
```
- OK: Clipboard tool found: win32yank
```
(every other check also says OK except for Python2 and Perl which I did not do installation for)

This is under Ubuntu for WSL, the shell is zsh, and `$TERM` is `xterm-256color`.

My `nvim -v` for WSL is (I also tried using the stable ppa for neovim previously, which was at version 0.3.8)
```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-ftVHSM/neovim-0.5.0+ubuntu1+git202004082106-1f56f9a-00e710e=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-ftVHSM/neovim-0.5.0+ubuntu1+git202004082106-1f56f9a-00e710e/build/config -I/build/neovim-ftVHSM/neovim-0.5.0+ubuntu1+git202004082106-1f56f9a-00e710e/src -I/build/neovim-ftVHSM/neovim-0.5.0+ubuntu1+git202004082106-1f56f9a-00e710e/.deps/usr/include -I/usr/include -I/build/neovim-ftVHSM/neovim-0.5.0+ubuntu1+git202004082106-1f56f9a-00e710e/build/src/nvim/auto -I/build/neovim-ftVHSM/neovim-0.5.0+ubuntu1+git202004082106-1f56f9a-00e710e/build/include
Compiled by buildd@lcy01-amd64-021

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

For Windows is:
```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/H
ostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_
WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM
_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src
-IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/in
clude
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by louisch** [comment] 2020-04-13 06:36
followup on this issue:
I've noticed that if I go to the directory where win32yank.exe is, and execute win32yank.exe directly, then it produces output and seems to function correctly.
It's when I create the symlink to win32yank and try to execute the symlink that it produces no output and just errors.

**Comment by erw7** [comment] 2020-04-13 09:31
microsoft/WSL#3999 seems to be the cause of this problem. For now, you can use `win32yank` in the following way.

1. Create a shell script with the following contents in directory included in your `$PATH` as `win32yank.exe` and give it execute permission.

    ```sh
    #!/bin/sh
    
    exec "$NEOVIM_WIN_DIR/bin/win32yank.exe" ${@+"$@"}
    ```
2. Copy `win32yank.exe` to the directory that is part of your `$PATH`.

    ```sh
    cp "$NEOVIM_WIN_DIR/bin/win32yank.exe" "/usr/local/bin"
    ```

3. Add the following settings to your `init.vim`

    ```vim
    let s:win32yank = '$NEOVIM_WIN_DIR/bin/win32yank.exe'
    let g:clipboard = {
          \  'name' : 'wsl',
          \  'copy' : {
          \    '+' : s:win32yank..' -i --crlf',
          \    '*' : s:win32yank..' -i --crlf',
          \  },
          \  'paste' : {
          \    '+' : s:win32yank..' -o --lf',
          \    '*' : s:win32yank..' -o --lf',
          \  },
          \}
    unlet s:win32yank
    ```

4. Include `$NEOVIM_WIN_DIR/bin` at the end of your `$PATH`.

We need to rewrite the wiki, but which of the above methods is best? We can also change `:checkhelth` to warn if `win32yank.exe` is a symbolic link, or to use `resolve()` in the configuration if `win32yank.exe` is a symbolic link. I would like to know what the members think.

Note that this problem should probably be resolved in Windows10 20H1.

**Comment by louisch** [comment] 2020-04-14 13:59
Hi, I used method 1 and it did solve the issue. Should I close this issue now?

**Comment by erw7** [comment] 2020-04-15 08:53
I've added to the [FAQ](https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl) and created a pull request (#12124). I think this should be fine to keep open until the PR is merged.

**Closed** 2020-04-15 12:54 UTC
Labels: bug

**Comment by pxnditxyr** [comment] 2021-07-19 04:30
how i do this in init.lua?

**Comment by allworldg** [comment] 2022-07-15 23:57
@pxnditxyr add vim.cmd([[  ]]) around the code . E.g., vim.cmd([[ let s: xxx ]])

**Comment by jakelinnzy** [comment] 2022-07-27 05:17
If you're using WSL 2 with GUI apps support, win32yank.exe isn't needed anymore. Instead install `xclip` from `apt` and Neovim should automatically detect it just like in stock Linux. You can test that by trying:
```bash
# copy from wsl to windows clipboard
echo "test" | xclip -sel clip
# paste from windows clipboard
xclip -o -sel clip
```
