### ISSUE TITLE
concealcursor causes a redraw immediately after entering nightly Neovim

### ISSUE THREAD

**Issue by quinoa42** [neovim/neovim#9639] opened 2019-02-22 07:40 UTC
- `nvim --version`: 
```
NVIM v0.4.0-1354-g4f453830f
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190221-22553-1y99tg7/build/config -I/tmp/neovim-20190221-22553-1y99tg7/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20190221-22553-1y99tg7/build/src/nvim/auto -I/tmp/neovim-20190221-22553-1y99tg7/build/include
Compiled by quinoa42@HIDDEN

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-4f45383/share/nvim"

Run :checkhealth for more info
```
- Vim (version: `8.1.950`) behaves differently? yes
- `Neovim 0.3.4` also behaves differently.
- Operating system/version: `Mac OS 10.13.6`
- Terminal name/version: `Alacritty 0.2.4`
- `$TERM`: `xterm-256color-italic` / `tmux-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -c "set conceallevel=2 concealcursor=n"
```

### Actual behaviour

Welcome screen disappear immediately.

### Expected behaviour

Welcome screen should not disappear immediately.

**Comment by justinmk** [comment] 2019-02-22 10:30
Most likely this is because cursor modes are handled in the TUI as a UI event. Thus this is a duplicate of #3416 .

Generally the plan is the "collapse" redraws, not diligently avoid them. The intro screen is kind of a special case.

**Closed by justinmk** 2019-02-22 10:30 UTC
