### ISSUE TITLE
Error executing luv callback | `.config/nvim/vim/F.lua` - no such file or directory

### ISSUE THREAD

**Issue by vhyrro** [neovim/neovim#15524] opened 2021-08-30 13:29 UTC
### Neovim version (nvim -v)

0.6.0-dev+201-g215c9b579

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux/5.13.13

### Terminal name/version

Kitty/0.23.1

### $TERM environment variable

xterm-kitty

### Installation

AUR - `neovim-git`

### How to reproduce the issue

- Use any modern Neovim configuration (doom-nvim, glepnir's config, whatever. Will probably error out on your own configuration too)
- Launch Neovim
- Get ```Error executing luv callback:                                                                       
vim.lua:63: cannot open /home/xyz/.config/nvim/lua/vim/F.lua: No such file or directory"```

### Expected behavior

No error occurring. The F.lua file belongs in `/usr/share/nvim/runtime/lua/vim`, yet it is searched for in `.config/nvim/lua/vim` it seems.

### Actual behavior

Error occurs and prevents any further loading of the configuration, rendering the config unusable. I did a bisect and it seems the erroneous commit where this bug was introduced was in 6896d22b63ad12de4c4990d0eece4a9b6f9cd88f, aka `fix(lua): preserve argument lists which are not lists`.  After further testing I am certain that using a previous commit allows the configuration to load without problems.

`/usr/share/nvim/runtime` *is* present in my runtimepath, which is rather interesting. I guess that means it isn't getting caught properly?

**Comment by justinmk** [comment] 2021-08-30 13:49
> commit where this bug was introduced was in [6896d22](https://github.com/neovim/neovim/commit/6896d22b63ad12de4c4990d0eece4a9b6f9cd88f), aka `fix(lua): preserve argument lists which are not lists`.

if `src/nvim/lua/vim.lua` is dependent on `runtime/lua/vim/F.lua` then we need to move `runtime/lua/vim/F.lua` into core (`src/nvim/lua/vim.lua`) instead of runtime.

**Comment by clason** [comment] 2021-08-30 13:52
I cannot reproduce this, just for the record. It would be good to have a reproducing example.

**Comment by vhyrro** [comment] 2021-08-30 13:53
@justinmk $VIMRUNTIME returns `/usr/share/nvim/runtime`. The file `lua/vim/F.lua` exists there.
![runtime](https://user-images.githubusercontent.com/76052559/131350257-133633b7-0056-4fc2-b395-2254fd0e7f5f.png)

**Comment by vhyrro** [comment] 2021-08-30 13:58
> I cannot reproduce this, just for the record. It would be good to have a reproducing example (without any "frameworks" or "distributions").

@clason I've tested on all of those configurations + my own personal configuration. All are plagued with the same issue. This means that it should in theory break the same way on anyone else's config too. Also note: running `nvim -u NORC` and `nvim -u NONE` does not cause the issue to occur (? weird).

**Comment by clason** [comment] 2021-08-30 13:59
It does not break on my config (which includes telescope, LSP, gitsigns, luasnips, lualine -- so is a pretty solid exercise of the Lua API). It's not impossible that all your configs access neovim internals in an unsupported way.

**Comment by gpanders** [comment] 2021-08-30 14:00
I also cannot reproduce this.

**Comment by justinmk** [comment] 2021-08-30 14:03
see https://github.com/neovim/neovim/issues/15524#issuecomment-908358661

regardless of how the bug is triggered (calling `vim.schedule_wrap` somewhere), we should ask 

1. why `vim.F` is searching `~/.config/nvim` (and didn't find F.lua in VIMRUNTIME)?
2. `vim.schedule_wrap` is part of the core binary so it probably shouldn't depend on something in VIMRUNTIME

**Comment by clason** [comment] 2021-08-30 14:05
In particular, if there was a fundamental problem with this, the test added in the referenced commit -- which uses `F.lua` -- should fail, but it does not; neither on CI nor locally for me. (You can test with `TEST_FILE=test/functional/lua/vim_spec.lua make functionaltest`.)

**Comment by yutkat** [comment] 2021-08-30 14:21
I can reproduce this.
I'm thinking it's probably due to interference with galaxyline.


```vim
syntax enable
filetype plugin indent on

lua <<EOF
local execute = vim.api.nvim_command
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/opt/packer.nvim'

if fn.empty(fn.glob(install_path)) > 0 then
  execute('!git clone https://github.com/wbthomason/packer.nvim '..install_path)
end

vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function()
  use {'wbthomason/packer.nvim', opt = true}
  use {'glepnir/galaxyline.nvim'}
end)
EOF
```

**Comment by clason** [comment] 2021-08-30 14:23
Thank you for that! Alas, `galaxyline` is no longer maintained and has to be assumed to be broken... Would be interesting to trace where exactly it triggers the error, though.

**Comment by fdschmidt93** [comment] 2021-08-30 14:24
This is not an entirely isolated incident, as per [reddit]( https://www.reddit.com/r/neovim/comments/pe1ieq/error_executing_luv_callback_since_896d22b6/).

In my case, this is fixed by turning of galaxyline and blankline (or redefining `vim.F.if_nil` in my config), which both have in common to use `vim.loop.new_async` with `vim.schedule_wrap`. Could that be the perpetrator?

**Comment by vhyrro** [comment] 2021-08-30 14:28
My configuration does not use galaxyline nor indent-blankline.nvim (it uses no statusline for that matter lol), but it seems likely that there is a common plugin doing something janky and causing crashes.

**Comment by clason** [comment] 2021-08-30 14:34
@fdschmidt93 that's a decent guess -- can you make a minimal reproducing example based on https://raw.githubusercontent.com/clason/neovim/minit.lua/contrib/minimal.lua? I cannot reproduce it with just including `indent-blankline`.

**Comment by bfredl** [comment] 2021-08-30 15:15
Core already depends on runtime since 0.5, but I've been thinking of making embedding lua files more scalable so we can include `meta.lua` and `F.lua` into the binary if we want (so the boundary doesn't depend on shoving everything unnaturally in one huge `shared.lua` file)

**Comment by n3wborn** [comment] 2021-08-30 15:17
Hi o/

I'm the author of the mentioned [reddit post](https://www.reddit.com/r/neovim/comments/pe1ieq/error_executing_luv_callback_since_896d22b6/) . 

As I says in the post I was about to open an issue but at first I thought this was my fault as I couldn't reproduce this issue with   [default-nvim.lua](https://github.com/mjlbach/defaults.nvim) . 

Then I saw the "bad" commit was about scheduling and startup and as I saw this [PR](https://github.com/neovim/neovim/pull/15436)  was about this too and was already available using [impatient](https://github.com/lewis6991/impatient.nvim) so I tried it and the bug was "solved". 

As all this is about startup, could this be how some files or plugins are required inside our config or through config=...  in packer startup function ?  

I don't have galaxyline but lualine and the last is not correctly required since this commit. Not sure if it can help but in case you want to check [my config](https://github.com/n3wborn/nvim/tree/ad721b0620c75c08ed44ce79d509a31c3c2d9def) at that time (I wanted to keep the lewis plugin and keep followinf head but I finally removed it and checkout to the last good commit)

**Comment by Happy-Dude** [comment] 2021-08-30 15:37
I'm able to reproduce this;

```
❯ uname -a
Darwin C02YJ42EJHD2 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
❯ nvim --version
NVIM v0.6.0-dev+nightly-1054-gc52ec8f9e
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by schan@C02YJ42EJHD2

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-c52ec8f/share/nvim"

Run :checkhealth for more info
```

Several lua plugins cause this message to show up, including https://github.com/kristijanhusak/orgmode.nvim and https://github.com/nvim-treesitter/nvim-treesitter.

Regarding nvim-treesitter, I can get the message to occur with the following in my `.vimrc` :
```lua
lua <<EOF
  require('nvim-treesitter.configs').setup {
      ensure_installed = 'maintained',
  }
EOF
endif
```

**Comment by bfredl** [comment] 2021-08-30 15:38
would anyone having this issue mind testing https://github.com/neovim/neovim/pull/15526 ?

**Comment by vhyrro** [comment] 2021-08-30 15:49
Yup, upon checking out that PR things work nicely now at least on my end

**Comment by Happy-Dude** [comment] 2021-08-30 15:53
@bfredl I can confirm as well that the building PR #15526 fixes the issue 👍

**Closed** 2021-08-30 16:09 UTC
Labels: bug, lua, status:has-bisected
