### ISSUE TITLE
c266c2f36ea56220268d2b19364e28815e338c2f introduces a regression under tmux

### ISSUE THREAD

**Issue by ericonr** [neovim/neovim#14782] opened 2021-06-11 20:12 UTC
- `nvim --version`: v0.5.0-dev, built from a9b8c780fe3b74cec12747101e351ba7d13451f1
- Operating system/version: Void Linux musl
- Terminal name/version: alacritty 0.8.0, tmux 3.2
- `$TERM`: screen

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC any_file
```

### Actual behaviour

Commit c266c2f36ea56220268d2b19364e28815e338c2f broke neovim under tmux, where it creates some arbitrary input the moment neovim is launched, altering the content and putting things in the command buffer.

First is "rg", which changes the first character in the document to 'g', then it's ":eeee/eeee/eeee^G", which appears in the command buffer.

Can be seen in https://asciinema.org/a/adTZ5zJZwYnHSiNrFOl63ZWSU (pay attention to the bottom of the screen as well). The first word in that file was `octave`.

### Expected behaviour

Lauching neovim doesn't touch the buffer in any way or pre-input things in the command buffer. Reverting c266c2f36ea56220268d2b19364e28815e338c2f is enough to return to this behavior.

I could make a PR simply reverting it, but I don't want to throw away whatever it was that it fixed...

**Comment by mjlbach** [comment] 2021-06-11 20:16
Duplicate of https://github.com/neovim/neovim/issues/14298

**Closed by mjlbach** 2021-06-11 20:16 UTC
Labels: bug
