### ISSUE TITLE
Errors with vim-airline and ft= modeline in first arg

### ISSUE THREAD

**Issue by ncoop** [neovim/neovim#4471] opened 2016-03-18 21:10 UTC
- Neovim version: NVIM 0.1.3-dev (installed from [neovim-0.1.2-85.gite7a9c00.fc23.x86_64](https://copr.fedoraproject.org/coprs/dperson/neovim-head))
- Operating system: Fedora 23 (4.3.5-300.fc23.x86_64)
- Terminal emulator: problem happens on xfce4-terminal, rxvt-unicode, and also the linux console

### Actual behaviour
Errors similar to those [reported by wsdjeg at vim-airline](https://github.com/vim-airline/vim-airline/issues/1096)

This only seems to happen when there's a modeline specifying filetype in the args, and the file with modeline is the first arg.

### Steps to reproduce
Install neovim, and vim-airline (airline was installed with vim-plug)

```
# minimal init.vim

call g:plug#begin('$XDG_CONFIG_HOME/nvim/plugged')
  Plug 'vim-airline/vim-airline'
call g:plug#end()
```

From shell:

```
echo '# vim: tw=78' > file-vim-tw
echo '# vim: ft=sh' > file-vim-ft

# this is ok
nvim file-vim-tw file-vim-ft

# errors on startup
nvim file-vim-ft file-vim-tw
```

Problem does not occur in vim 7.4

**Comment by justinmk** [comment] 2016-03-18 22:17
Though I can't imagine how, I wonder if this is related to https://github.com/neovim/neovim/pull/4255.

Can you please try this _exact_ command:

    nvim --cmd 'filetype off' file-vim-ft file-vim-tw

Does that have errors on startup?

**Comment by ncoop** [comment] 2016-03-18 22:40
Yes, the errors are still there.

With `--cmd 'filetype off'` the output of `:filetype` is still `filetype detection:ON  plugin:ON  indent:ON`

And the output of `:scriptnames` is:
```
  1: /usr/share/nvim/runtime/ftoff.vim
  2: ~/.config/nvim/init.vim
  3: ~/.config/nvim/autoload/plug.vim
  4: /usr/share/nvim/runtime/filetype.vim
  5: /usr/share/nvim/runtime/ftplugin.vim
  6: /usr/share/nvim/runtime/indent.vim
  7: /usr/share/nvim/runtime/syntax/syntax.vim
  8: /usr/share/nvim/runtime/syntax/synload.vim
  9: /usr/share/nvim/runtime/syntax/syncolor.vim
 10: ~/.config/nvim/plugged/vim-airline/plugin/airline.vim
 11: ~/.config/nvim/plugged/vim-airline/autoload/airline.vim
 12: ~/.config/nvim/plugged/vim-airline/autoload/airline/init.vim
 13: ~/.config/nvim/plugged/vim-airline/autoload/airline/parts.vim
 14: /usr/share/nvim/runtime/plugin/gzip.vim
 15: /usr/share/nvim/runtime/plugin/man.vim
 16: /usr/share/nvim/runtime/plugin/matchit.vim
 17: /usr/share/nvim/runtime/plugin/matchparen.vim
 18: /usr/share/nvim/runtime/plugin/netrwPlugin.vim
 19: /usr/share/nvim/runtime/plugin/rplugin.vim
 20: /usr/share/nvim/runtime/plugin/rrhelper.vim
 21: /usr/share/nvim/runtime/plugin/shada.vim
 22: /usr/share/nvim/runtime/plugin/spellfile.vim
 23: /usr/share/nvim/runtime/plugin/tarPlugin.vim
 24: /usr/share/nvim/runtime/plugin/tohtml.vim
 25: /usr/share/nvim/runtime/plugin/tutor.vim
 26: /usr/share/nvim/runtime/plugin/vimballPlugin.vim
 27: /usr/share/nvim/runtime/plugin/zipPlugin.vim
 28: /usr/share/nvim/runtime/autoload/remote/host.vim
 29: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions.vim
 30: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/quickfix.vim
 31: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/netrw.vim
 32: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/whitespace.vim
 33: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/po.vim
 34: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/wordcount.vim
 35: ~/.config/nvim/plugged/vim-airline/autoload/airline/section.vim
 36: ~/.config/nvim/plugged/vim-airline/autoload/airline/highlighter.vim
 37: ~/.config/nvim/plugged/vim-airline/autoload/airline/themes/dark.vim
 38: ~/.config/nvim/plugged/vim-airline/autoload/airline/themes.vim
 39: ~/.config/nvim/plugged/vim-airline/autoload/airline/util.vim
 40: ~/.config/nvim/plugged/vim-airline/autoload/airline/builder.vim
 41: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/default.vim
 42: /usr/share/nvim/runtime/autoload/provider/clipboard.vim
```

**Comment by justinmk** [comment] 2016-03-18 23:03
> With --cmd 'filetype off' the output of :filetype is still filetype detection:ON plugin:ON indent:ON

That's expected, because your plugin manager is doing it. That's OK--I just wanted to make sure this wasn't an order-of-operations problem.

This means #4255 is not related.

**Comment by aignas** [comment] 2016-03-29 07:33
Just chipping in to say that I can reproduce the issue.

**Comment by trev** [comment] 2016-04-05 03:52
Samesies!

**Comment by rchady** [comment] 2016-04-17 04:35
Seeing the same behavior on NVIM v0.1.4-42-ga7a3605 as well.

**Comment by Streetwalrus** [comment] 2016-04-17 07:59
This issue is likely related to Plug, I can reproduce with it but not with the following:
```VimL
set rtp+=~/.nvim/bundle/vim-airline
```

**Comment by gwerbin** [comment] 2016-04-18 00:46
Just chiming in with the same issue, to confirm that removing the `filetype` modeline stops the wall of errors.

**Comment by justinmk** [comment] 2016-04-18 06:29
Closed by https://github.com/neovim/neovim/pull/4590

**Closed by justinmk** 2016-04-18 06:29 UTC

**Comment by ncoop** [comment] 2016-04-18 08:29
Built from HEAD; confirmed fixed :punch:

**Comment by arusahni** [comment] 2016-12-05 16:03
I've started seeing this error, using 0.1.7 stable.

**Comment by mhinz** [comment] 2016-12-05 16:24
@arusahni Any steps to reproduce it?

**Comment by arusahni** [comment] 2016-12-05 16:30
I'll try to narrow it down. Right now I'm only seeing the behavior on Git buffers.
