### ISSUE TITLE
Random SEGV signal

### ISSUE THREAD

**Issue by chimay** [neovim/neovim#5813] opened 2016-12-22 13:22 UTC
- `nvim --version`: v0.2.0-150-g33319b1
- Operating system/version: Linux 4.8.11 (Arch)
- Terminal name/version: mainly using nvim-qt and yakuake (derived from konsole)
- `$TERM`: screen-256color (in tmux)

### Actual behaviour

Crashes randomly, or after a period or inactivity, sometimes several times
a day.

Update all plugins doesn’t seem to solve it.

### Coredump

```
Signal: 11 (SEGV)

stack trace of thread 13314:

#0  0x000000000047ed31 set_ref_in_item (nvim)
#1  0x000000000047ec86 set_ref_in_list (nvim)
#2  0x000000000047ef39 set_ref_in_item (nvim)
#3  0x000000000047eba8 set_ref_in_ht (nvim)
#4  0x000000000047ddf6 garbage_collect (nvim)
#5  0x000000000050d84d before_blocking (nvim)
#6  0x000000000059726f os_inchar (nvim)
#7  0x0000000000621f58 state_enter (nvim)
#8  0x0000000000564468 normal_enter (nvim)
#9  0x0000000000528b39 main (nvim)
#10 0x00007fdecc7d2291 __libc_start_main (libc.so.6)
#11 0x000000000042f40a _start (nvim)
```

**Comment by jamessan** [comment] 2016-12-22 14:00
Closing as a duplicate of #3770.

**Closed by jamessan** 2016-12-22 14:00 UTC
Labels: duplicate
