### ISSUE TITLE
Following HEAD: breaking changes on master

### ISSUE THREAD

**Issue by teto** [neovim/neovim#14090] opened 2021-03-10 01:38 UTC
_Moved from https://github.com/neovim/neovim/wiki/Following-HEAD_

## Breaking changes are now tracked in `:help news`

- Breaking changes are now tracked in [:help news](https://neovim.io/doc/user/news.html#news-breaking)
- Where possible, breaking changes are also flagged with [vim.deprecate()](https://neovim.io/doc/user/lua.html#vim.deprecate())

---

- If you don't have Neovim, see [Building Neovim](https://github.com/neovim/neovim/wiki/Building-Neovim) or [Installing Neovim](https://github.com/neovim/neovim/wiki/Installing-Neovim).
- Use `:checkhealth` to detect and fix common problems.

---

### 2021/3/9

#13875 was merged which makes it an error to use vim.fn to call functions in vim.api. For example, before this PR it was possible to call either `vim.fn.nvim_get_current_buf()` or `vim.api.nvim_get_current_buf()` to get the current buffer; now, trying to call vim.fn.nvim_get_current_buf results in an error that says to use vim.api.nvim_get_current_buf instead. Any plugins that use vim.fn to call functions available in vim.api will therefore not work until updated to use vim.api.

### Older changes
<details><summary>Ye olde list of changes</summary>

### 2021/3/4

We have closed the github discussions in favour of our new forum https://neovim.discourse.group/. Please use that now. If there is some content from the github discussions you would like salvaged, contact us on gitter and we can restore it temporarily.

### 2021/3/3

Neovim 0.5 changed the undofile format compared to older versions ( #13973 ). New versions of neovim will not read undofiles written by nvim before #13973 (will show "incompatible version" error). Nvim 0.4 (or up to bda12927be84f0e0e05e885f9acb40a7ac2c5524 ) can be used to recover older undofiles, so if you worried about unsaved changes lurking around in undofiles it would make sense to keep such version around somewhere to recover them.

This change was necessary to keep tree-sitter and plugins dependent on byte-level buffer change events fully working with undo states from a undofile. 

### 2021/1/3

`:LspInstall` and `:LspInstallInfo` have been removed in lspconfig (in https://github.com/neovim/nvim-lspconfig/pull/498 as a follow up of https://github.com/neovim/nvim-lspconfig/issues/334). Refer to the server documentation to install them manually. Some servers may require cmd to be set to point at their previously installed location (elixir, sumneko, omnisharp).

#13739 Logs for both neovim and the language server client have been moved to `$XDG_CACHE_DIR/nvim`.

### 2020/11/23

We changed the way tree-sitter parsers are integrated in nvim. One major change is that the parser:parse() method changed to return a tree to a table of trees. Please expect the tree update callbacks to change soon.

### 2020/11/15

nvim_lsp has been renamed to lspconfig to make the goal of https://github.com/neovim/nvim-lspconfig/ clearer, i.e., it conveys only LSP server configurations. You should update your lua require calls as shown here https://github.com/neovim/nvim-lspconfig/pull/348.

### 2021/1/3

:LspInstall and :LspInstallInfo have been removed in lspconfig (in https://github.com/neovim/nvim-lspconfig/pull/498 as a follow up of https://github.com/neovim/nvim-lspconfig/issues/334). Refer to the server documentation to install them manually. Some servers may require cmd to be set to point at their previously installed location (elixir, sumneko, omnisharp).

#13739 Logs for both neovim and the language server client have been moved to $XDG_CACHE_DIR/nvim.

### 2020/11/23

We changed the way tree-sitter parsers are integrated in nvim. One major change is that the parser:parse() method changed to return a tree to a table of trees. Please expect the tree update callbacks to change soon.

### 2020/11/15

nvim_lsp has been renamed to lspconfig to make the goal of https://github.com/neovim/nvim-lspconfig/ clearer, i.e., it conveys only LSP server configurations. You should update your lua require calls as shown here https://github.com/neovim/nvim-lspconfig/pull/348.

### 2020/11/12

Large updates to vim.lsp.diagnostic. See https://github.com/neovim/neovim/pull/12655

### 2020/11/03

We moved tree-sitter as a dependency rather than vendoring the code. Thus there is now a new build dependency : libtree-sitter. At the time of writing, neovim is built against treesitter 0.17.3. Linux distributions and homebrew (already done) must update their package accordingly.

### 2020/09/24

We changed the behavior of folded lines so that it behaves more like regular lines (taking into account cursorline, as well as the column highlights such as LineNr) in https://github.com/neovim/neovim/pull/12515 . This departs from vim and may cause some issues so please bear with us as we fix them.

### 2020/09/09

PSA: Some larger changes to tree-sitter highlighting is planned to land on master very soon. Expect breakages for a little while. If you have a master working for your needs and want it to keep working, it might make sense to wait for a few days/weeks. But if you want to help with betatesting, please follow along. :] More updates will be posted here and on gitter.im/neovim/neovim regularly.

### 2020/03/03

#11716 foldcolumn changed from a number to a string to allow auto:X values. Also the limit was changed from 12 to 9.

### 2019/12/23

#11234 jobstart() or system() fail with error (instead of silently) if the command is not executable.

### 2019/12/04

#11135 sets nostartofline as a default. The cursor stays in the same column after gg or G for instance.

### 2019/07/07

Floating windows no longer implicitly disables the number column. Instead use style='minimal' argument to nvim_open_win() to disable UI features like number column, End-of-buffer lines etc.
2019/06/10

#10123 Nvim core requires libluv. This may require building with -DUSE_BUNDLED_LUV=ON if you were previously using -DUSE_BUNDLED_LUV=OFF. Previously luv was only needed for running tests; now nvim statically links libluv in order to provide the vim.loop Lua interface.

### 2019/03/31

#9819 MenuPopupChanged renamed to CompleteChanged.
2019/01/20

#9526: Neovim always uses the system allocator, instead of jemalloc.

### 2018/11/18

The Python package neovim was renamed to pynvim.

"Neovim" can mean a lot of things. It can relate to the editor, or the project, or (prior to this change) the Python module, or the Ruby gem, etc. Especially confusing was the fact that the Python side would refer to it as neovim whereas the Neovim side referred to it as python-client. Now, both sides call it pynvim for the greater good.

For the time being, neovim acts as a transitional package for the new pynvim. Unfortunately, due to limitations in pip, the neovim package cannot be safely upgraded with pip install --upgrade neovim on all systems.
Steps to update "pynvim" (formerly "neovim") Python package:

python -m pip uninstall neovim pynvim
python -m pip install pynvim

    After those steps, it is safe to pip install neovim again, if any third-party package has it as a formal dependency. Otherwise it shouldn't be necessary.
    import neovim is still supported, both in plugins and third-party software using it as a library. If import neovim fails, then the upgrade wasn't successful. Follow the instructions above.

### 2018/09/22

#9024: The meaning of the --embed and --headless flags changed to facilitate better startup behaviour with external UIs. UI embedders (any user of nvim_ui_attach) must start Nvim without --headless:

nvim --embed

Embedders not using the UI protocol must use:

nvim --embed --headless

In the "--embed only" case Nvim waits for nvim_ui_attach before continuing startup (user config, reading buffers) so that UIs can deterministically handle (display) early messages, dialogs, etc. The client can do other requests before nvim_ui_attach (e.g. nvim_get_api_info for feature-detection). During this pre-startup phase the user config is of course not available (similar to --cmd).

For most UI embedders this improves startup behavior automatically, by supporting startup messages and swapfile dialogs. For others it is potentially a breaking change, which can be easily avoided by specifying --headless (which is backwards-compatible for that use-case).

UIs that need additional initialization after init.vim can use this pattern:

    Before nvim_ui_attach send a single nvim_command request with the command "autocmd VimEnter * call rpcrequest(1, 'vimenter')".
    In the vimenter method handler the UI can then safely execute any requests.
    Nvim will only enter normal mode when the handler returns (because rpcrequest() is a blocking call).

### 2018/06/10

Changes from #7679:

    Nvim treats a stdin stream as text by default:

    echo foo | nvim

        To get the old behavior, pass stdin to -s:

        echo foo | nvim -s -

    Windows only: nvim *.txt (glob/wildcard expression) is treated literally. Use the :next (:n) command instead:

    nvim +"n *.txt"

### 2018/02/23

Default fillchars for 'vert' and 'sep' changed from respectively | and - to │ and · when the ambiwidth setting is different from double, else old defaults apply. #8035

### 2017/11/18

VimL (Vimscript) compatibility: count is no longer an alias to v:count. This helps avoid mistakes in scripts. #7407

### 2017/08/21

:terminal now starts in normal mode (#6808), like any other buffer, instead of terminal mode. This avoids the cursor getting "trapped" when a terminal is started.

### 2017/05/15

The highlight option is now read-only (#6737), so that the built-in highlight groups (and their behaviors) are predictable and can be used as keys for features like winhighlight.

### 2017/04/03

Default 'mouse' setting changed from mouse=a to mouse= (empty). This will change again in the future after mouse=a is improved. To continue using mouse, add this to your init.vim:

set mouse=a

### 2017/04/02

Support for $NVIM_TUI_ENABLE_CURSOR_SHAPE was removed. Use the guicursor option to control cursor styling. See FAQ.

    To disable cursor style changes, set guicursor to empty:

    :set guicursor=

    Note: guicursor is enabled by default only if Nvim is certain it won't cause problems on your terminal. If you know that cursor shaping works on your terminal, set guicursor in your init.vim:

    :set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor

### 2016/12/12

#5529 merged Vim's support for "partial functions" which made Nvim more strict about when the implicit self variable is available. Functions that reference self (which is common with job callbacks) must either be declared as dict functions:

function! s:on_stdout(id, data, event) dict abort

or as part of the job options dictionary:

let s:opts = { ... }
function! s:opts.on_stdout(id, data, event) abort

Job callbacks also must have at least 3 parameters now. See https://github.com/neovim/neovim/issues/5763#issuecomment-266722407

### 2016/11/05

'encoding' cannot be changed to a value other than "utf-8", even during initialization. #2905

(Background: [#2929][2929] restricted 'encoding' to be modifiable only during initialization. One year later, we've found no problems with UTF-8 as the internal encoding, and are now making this mandatory. This only affects the internals of Nvim, it doesn't affect file encodings or plugins.)

### 2016/02/14

:filetype plugin indent on and :syntax on are now executed by default after your vimrc.

    If your vimrc calls :filetype, Neovim will not change your preference.
    If your vimrc calls :filetype off or :syntax off, that will be respected.
    If filetype plugin indent on and/or syntax on is in your vimrc, you can delete those lines.

See :help startup for complete details.

### 2015/10/17

The 'viminfo' option is now an alias for 'shada'. 'viminfo' can no longer include n and it can no longer be shared with Vim.

See #3469 for more information.

### 2015/07/26

The behavior of the mkdir() function has changed:

    Assuming /tmp/foo does not exist and /tmp can be written to, mkdir('/tmp/foo/bar', 'p', 0700) will create both /tmp/foo and /tmp/foo/bar with the octal permissions 0700. Vim's mkdir() will create /tmp/foo with 0755.
    If you try to create an existing directory with 'p', such as with mkdir('/', 'p')), mkdir() will silently fail. In Vim this was an error.
    Upon failure, mkdir() related error messages now include strerror() text.

See #3041 for more information.

</details>

**Comment by bfredl** [comment] 2021-03-15 09:58
`nvim_set_hl_ns` was renamed to `nvim__set_hl_ns` to indicate the API is not yet stable (it is going to change after 0.5.0, #13457  )

**Comment by bfredl** [comment] 2021-03-15 17:10
Tree-sitter was bumped from 0.18 to 0.19. This breaks ABI compatibility with tree-sitter parsers compiled for 0.18. https://github.com/nvim-treesitter/nvim-treesitter/pull/1000 will be needed to stay compatible. if you use tree-sitter both neovim core and nvim-treesitter need to be updated together (after the PR in nvim-treesitter repo is merged, which should happen very soon).

**Comment by teto** [comment] 2021-03-16 17:52
`vim.TSHighlighter` will not work anymore starting from https://github.com/neovim/neovim/pull/14145 (it was deprecated months ago and should pose no issue).

**Comment by janlazo** [comment] 2021-05-08 03:00
`nvim_win_set_buf` does not block autocommands. https://github.com/neovim/neovim/pull/13664

**Comment by mjlbach** [comment] 2021-05-30 16:16
#14649 was merged which deprecated focusable_float, focusable_preview, and fancy_floating_markdown . Please use open_floating_preview directly.

**Comment by mjlbach** [comment] 2021-07-19 15:53
#15094:  

Right now, empty tables are treated as lists in the deep extend method, which means if you use force and have an empty table value in a table on the right, it will overwrite the existsing value.

vim.tbl_deep_extend("force", { ss = { a = 1 } }, { ss = {} }) ==> empty
vim.tbl_deep_extend("force", { ss = { a = 1 } }, { ss = { b = 1} }) => has both a and b

It also fixes an issue when merging values of a different type. This used to fail:
vim.tbl_deep_extend("force", {a=true}, {a={b= 1}})

**Comment by mjlbach** [comment] 2021-07-22 15:50
#14831 replaces opts.open_loclist with unified opts.open, which now works for both open_qflist and open_loclist

**Comment by justinmk** [comment] 2021-08-19 12:42
default mappings in 0.6:

- `Y => y$` : https://github.com/neovim/neovim/pull/13268

**Comment by mjlbach** [comment] 2021-09-05 17:55
https://github.com/neovim/neovim/pull/15504 was merged which changes the handler signature to 4 arguments instead of 6. See details in the commit message

https://github.com/neovim/neovim/commit/df17d7844ed7dedcb80f9405f7078a046a12524a was merged which 

Most plugins should already work transparently with these changes, as we warned authors ahead of time.

**Comment by justinmk** [comment] 2021-09-06 20:13
The legacy `MANPAGER="nvim -c 'set ft=man' -"` approach to configuring Nvim as your `man` pager is no longer supported. #15487 

Instead, use the approach documented in `:help :Man`:

    export MANPAGER='nvim +Man!'

**Comment by justinmk** [comment] 2021-09-09 13:56
Breaking changes to Lua modules:

- https://github.com/neovim/neovim/pull/15460

**Comment by clason** [comment] 2021-09-16 22:49
Breaking change in LSP diagnostics API:

- https://github.com/neovim/neovim/pull/15585

Specifically: 

* `vim.lsp.diagnostic` functions moved to `vim.diagnostic`,  see https://github.com/neovim/neovim/blob/c2a65921d762929a1b8e740aeb92c7970d025736/runtime/doc/deprecated.txt
* highlight groups renamed: `LspDiagnosticsDefaultWarning` to `DiagnosticWarn` etc., see https://github.com/neovim/neovim/blob/master/runtime/plugin/diagnostic.vim

**Comment by janlazo** [comment] 2021-09-17 01:16
Breaking changes from Neovim's implementation of Vim's blob feature
- Lua strings containing nulll bytes are converted to blob
  - https://github.com/neovim/neovim/commit/de9df825d5e38e6a9e5ba254d1d27cb3cfc9f557
  - https://github.com/neovim/neovim/issues/14801

**Comment by bfredl** [comment] 2021-09-18 15:19
Breaking change for packages: start packages are not visible in `&rtp` and `vim.o.rtp`. Use API functions `nvim_list_runtime_path()` and `nvim_get_rumtime_file()` instead. #15632

**Comment by clason** [comment] 2021-10-05 15:52
Breaking change in Windows builds: 

* https://github.com/neovim/neovim/pull/15889

Default build now uses LibUV 1.42.0 on all platforms, including Windows. This removes support for

* Windows 7
* mouse and alternate buffers in TUI for Windows 8 and 8.1

(Note that the minimum required version for LibUV remains 1.28.0, so distributions may build against older versions that retain support for earlier Windows versions.)

**Comment by justinmk** [comment] 2021-10-30 14:04
Renamed `vim.mpack` functions https://github.com/neovim/neovim/pull/16175
- `vim.mpack.unpack` => `vim.mpack.decode`
- `vim.mpack.pack` => `vim.mpack.encode`

**Comment by mjlbach** [comment] 2021-11-09 22:32
I'm going to merge a new change to the incremental sync implementation for the built-in language server client.

This should fix handling of unicode (utf-8, 16, and 32) encodings as well as handling newlines correctly for windows and (extremely old pre macos 9) macs (because, why not?).

The implementation should also be slightly faster, and is extremely commented to encourage external PRs. I also added test coverage for the most common failure cases.

To revert to sending full buffers, should you find an issue:

With lspconfig (or start_client for that matter), to disable incremental sync you can use the following.

```lua
require('lspconfig').pyright.setup {
  flags = {
    allow_incremental_sync = false
  }
}
```

Please file PRs with test scenarios (see `incremental_sync_spec.lua`) if you find a bug, otherwise it is extremely difficult for me to reproduce/debug for you. There is a known issue with `on_lines` which should not impact users.

I am merging this (and providing the long explanatory post) so we have time to fully test before 0.6 is released. I will revert if there are widespread regressions.

**Comment by jamessan** [comment] 2021-11-14 14:14
32-bit Windows/MinGW builds are no longer part of the nightly/release artifacts. #16317

**Comment by gpanders** [comment] 2021-11-16 15:50
https://github.com/neovim/neovim/pull/16328: The `show_header` option of `vim.diagnostic.open_float` has been renamed to simply `header` and has different semantics (you can now specify a custom header string and highlights). A value of `false` has the same meaning as before.

https://github.com/neovim/neovim/pull/16323: The `enable`, `disable`, `show`, and `hide` methods of `vim.diagnostic` now interpret a `nil` `bufnr` argument to mean "all buffers" rather than "current buffer". Use `0` for the current buffer.

**Comment by gpanders** [comment] 2021-11-25 18:55
https://github.com/neovim/neovim/pull/16098 removes the `LspDiagnosticsChanged` and `DiagnosticsChanged` user autocommands. Instead, use `DiagnosticChanged` (note the singular `Diagnostic`!) which is now a first-class autocommand.

**Before:**
```vim
autocmd User DiagnosticsChanged do_something
```

**After:**
```vim
autocmd DiagnosticChanged * do_something
```

The pattern of the `DiagnosticChanged` autocommand matches on the file name of the buffer for which diagnostics were updated. This means you can now do things like

```vim
autocmd DiagnosticChanged <buffer> do_something
```

to only trigger when diagnostics are changed for the current buffer.

**Comment by gpanders** [comment] 2021-12-15 15:21
https://github.com/neovim/neovim/pull/16557: `vim.lsp.util.close_preview_autocmd()` has been removed

**Comment by clason** [comment] 2021-12-19 09:47
#16684 changed `Q` to execute the last _recorded_ macro. To enter Ex mode, use `gQ` instead.

**Comment by gpanders** [comment] 2022-01-03 19:50
Many API functions that expect a number as their argument (e.g. `nvim_win_is_valid`, `nvim_buf_clear_namespace`) no longer implicitly convert `nil` to `0`. The fact that it did this before was a bug. Any usages of API functions that depended on this behavior will no longer work.

**Comment by mjlbach** [comment] 2022-01-13 10:34
https://github.com/neovim/neovim/pull/17049 made `offset_encoding` a non-optional parameter for the following functions:
* `vim.lsp.util.apply_text_edits(text_edits, bufnr, offset_encoding)`
* `vim.lsp.util.apply_text_document_edit(text_document_edit, index, offset_encoding)`
* `vim.lsp.util.apply_workspace_edit(workspace_edit, offset_encoding)`
* `vim.lsp.util.jump_to_location(location, offset_encoding)`
* `vim.lsp.util.buf_highlight_references(bufnr, references, offset_encoding)`
* `vim.lsp.util.character_offset(buf, row, col, offset_encoding)`

It is extremely important to consider character offset when working with the language-server-protocol, as servers can support utf-8, utf-16, or utf-32 encodings. Neovim provides support for all of these encodings, but we we occasionally lazily resolved these. Now, all utility functions that do *not* explicitly generate requests, or parameters for multiple clients, will consistently require an offset-encoding.

If you were affected by this in your plugin, **you will need to fetch the client.offset_encoding (available via ctx.client_id from most handlers)**. If you were using LSP functions for something *not* involving LSP, you should consider vendoring your own solution, although the default offset_encoding is most commonly "utf-16".

**Comment by gpanders** [comment] 2022-01-17 21:12
https://github.com/neovim/neovim/pull/17040 changes the order that the `:filetype plugin indent on` command is run relative to the user's `init.vim` or `init.lua` file (or just "init file", for short). See that PR for a more in-depth explanation of the reasoning/motivation behind this change.

**This should not be a breaking change for most users**. In fact, this should instead provide saner/more user friendly behavior by using a less surprising ordering for FileType autocommands. However, this PR will be a breaking change if any of the following apply to you:

1. **You set any variables in your init file that modify filetype loading, such as `g:did_load_filetypes` or `g:do_filetype_lua`**. These variables affect how filetype detection is loaded, but now that filetype detection loads before the init file, placing these variables in your init file will have no effect.

   **Solution:** Move these variable definitions to `~/.config/nvim/filetype.lua` (or `filetype.vim`, if you prefer).

2. **You use `filetype off` in your init file to block filetype detection loading.** This will still work as expected (filetype detection will be disabled), but you will now still pay the startuptime cost of loading filetype detection. We consider this an acceptable tradeoff given that disabling filetype detection is a much rarer use case than adding FileType autocommands to the init file.

3. **You do some kind of esoteric, unusual, or otherwise funky things with filetype detection**. In a system as complex as Neovim, we obviously cannot predict every possible consequence of even a simple change like this one. If you are doing something exotic involving filetype detection and it stops working, this may be why.

If you find that something no longer works as expected and none of the points above apply to you, we consider that a bug. Please open an issue.

**Comment by gpanders** [comment] 2022-01-18 19:45
https://github.com/neovim/neovim/pull/17129 invalidates points 1 and 2 in the comment above. You can now once again put `did_load_filetypes` and `do_filetype_lua` in your init file. Filetype detection can also once again be blocked with `:filetype off`.

**Comment by bfredl** [comment] 2022-01-29 19:22
python2 support was removed. #17222

**Comment by clason** [comment] 2022-02-21 20:23
#17462 changed the signature of `vim.highlight.region` to move optional arguments inside an `opts` table (a standard pattern throughout the Neovim API). The new signature is 
```lua
vim.highlight.range(bufnr, ns, hlgroup, start, finish, { regtype = regtype, inclusive = inclusive, priority = priority })
```

**Comment by gpanders** [comment] 2022-02-23 22:20
#17498 changes the semantics around negative line numbers used in `nvim_buf_set_text`. Previously, a value of `-2` meant "the last line", but this has been corrected so that `-1` refers to the last line and `-2` refers to the second to last line, etc. This is consistent with `nvim_buf_set_lines` and `nvim_buf_get_text`.

Any usages of `nvim_buf_set_text` that used negative line numbers should be adjusted accordingly.

**Comment by gpanders** [comment] 2022-03-01 17:47
#17566 causes `nvim --clean` to enable filetype detection and syntax highlighting by default. This closer emulates a "fresh install" of Neovim, which is the purported purpose of `--clean`.

**Comment by zeertzjq** [comment] 2022-03-24 11:55
Key notations `<Tab>`/`<C-I>`, `<CR>`/`<C-M>`, `<Esc>`/`<C-[>` are no longer treated as the same. #17825

**Comment by clason** [comment] 2022-03-26 14:35
#17854 has renamed `nvim_do_autocmd` to `nvim_exec_autocmd` (following established code standards, see `:h dev-api`).

**Comment by clason** [comment] 2022-03-31 22:50
Might as well rip the bandaid off now: #17938 has renamed
* `nvim_exec_autocmd` to `nvim_exec_autocmds`
* `nvim_clear_autocmd` to `nvim_clear_autocmds`
(as both of these may affect multiple autocommands per call).

**Comment by zeertzjq** [comment] 2022-04-11 02:34
Support for the undocumented `ESC NUL` forced escape sequence in TUI has been removed in #17198. `ESC NUL` is now usually recognized as `<M-C-Space>`, unless terminfo declares it to be something else.

Nvim already supports another unambiguous way to encode a `ESC` key through libtermkey: `ESC [ 2 7 u`, which is an "extended keys" (a.k.a. "modifyOtherKeys" or `CSI u`) sequence.

For example, if one previously used `tmux send-keys 'Escape' 'C-@' 'C-W' j` to leave Insert mode and go to the window below, that will no longer work, but they can still use `tmux send-keys 'Escape' [ 2 7 u 'C-W' j` to achieve that.

If one still wants to use `ESC NUL` as `ESC`, they can just map `<M-C-Space>` to `<Esc>`.

**Comment by gpanders** [comment] 2022-04-11 02:46
`nvim_add_user_command` and `nvim_buf_add_user_command` have been renamed to `nvim_create_user_command` and `nvim_buf_create_user_command` respectively in order to maximize consistency with other API functions.

**Comment by justinmk** [comment] 2022-04-27 04:18
#18252 Windows 10 is required for `:terminal`.

**Comment by mfussenegger** [comment] 2022-04-30 09:26
https://github.com/neovim/neovim/pull/17814

`resolved_capabilities` of the lsp-client is now deprecated. Accessing it will result in a warning. Users & plugins must migrate to use `server_capabilities` instead. An example how such a change may look like:

```patch
-  if client.resolved_capabilities['document_highlight'] then
+  if client.server_capabilities.documentHighlightProvider then
```

**Comment by gpanders** [comment] 2022-05-23 03:21
https://github.com/neovim/neovim/pull/18547 The `'insertmode'` option is removed in favor of a script that uses only existing Neovim features (see `:h 'insertmode'`).

**Comment by mfussenegger** [comment] 2022-05-25 17:38
https://github.com/neovim/neovim/pull/18458 the `filter` option on `vim.lsp.buf.format` is now a predicate: It takes a client as argument and must return a boolean.

**Comment by mfussenegger** [comment] 2022-05-26 10:29
https://github.com/neovim/neovim/pull/18745 the `filter` option of `vim.lsp.buf.rename` is now a predicate that takes a client as argument and must return a boolean.

**Comment by justinmk** [comment] 2022-05-31 18:11
#18720 The `health` Lua module was renamed to `vim.health`. Plugins using `require('health')` must be updated to use `vim.health`.

**Comment by clason** [comment] 2022-06-25 12:25
#19029 raised the minimum macOS version for the releases provided on https://github.com/neovim/neovim/releases to 11.0 in order to have universal builds for Intel and M1. 

(Note: This has no effect for builds from source or homebrew releases, which still support macOS 10.15, the minimum version supported by LibUV.)

**Comment by clason** [comment] 2022-06-26 16:44
#18895 refactored the `vim.filetype.match()` function to allow (limited) matching on filename or contents only. This required a breaking change in interface.

Instead of 
```lua
vim.filetype.match(name, bufnr)
``` 
use
```lua
vim.filetype.match({ buf = bufnr })
```

**Comment by zeertzjq** [comment] 2022-06-30 08:59
#19159 renamed these highlight attributes to match Vim:
- `underlineline` to `underdouble`
- `underdot` to `underdotted`
- `underdash` to `underdashed`

`underdouble` also now takes higher precedence than `undercurl`.

**Comment by zeertzjq** [comment] 2022-07-06 20:52
#19244 changed the error thrown when editing text/switching another window/editing another buffer from E523 to E565. Plugins may need to change what errors they catch.

**Comment by clason** [comment] 2022-07-07 16:59
#19216 switches to `filetype.lua` by default and deprecates the previous way of enabling it in favor of the legacy `filetype.vim` detection. This means

* users who want to use the **new** `filetype.lua` mechanism should **not set any variables** (and in particular `g:did_load_filetypes`, see below);
* users who want to use the **old** `filetype.vim` mechanism should `let g:do_legacy_filetype =1` (or any other value)
* users who want to **disable either** mechanism should `let g:did_load_filetypes =1` (or any other value).

**Comment by zeertzjq** [comment] 2022-07-14 06:51
#19357: `input()` and `inputdialog()` no longer convert the value of `cancelreturn` to a string if it is passed in an `opts` dictionary. It is still converted to a string if it is the third argument of `inputdialog()`

**Comment by zeertzjq** [comment] 2022-08-02 10:03
#19598 changed `vim.keymap.set()` to always replace keycodes in the result of `<expr>` mappings by default (previously this was only the default for Lua functions as RHS). Pass `replace_keycodes = false` in `opts` explicitly to disable this behavior.

**Comment by clason** [comment] 2022-08-11 08:19
#19693 changed the nightly (and release) builds and appimages to be built on Ubuntu 20.04 instead of Ubuntu 18.04, which is being deprecated by Github. Users that cannot upgrade from 18.04 need to [build from source](https://github.com/neovim/neovim/wiki/Building-Neovim#building) instead.

**Comment by bfredl** [comment] 2022-08-17 14:50
The 'winhighlight' feature was throughly reimplemented as window local highlight namespaces in #13457 . This is supposed to be fully backwards compatible while enabling many new usecases (like window local syntax highlighting). though if there unexpected changes to highlighting when updating master, this PR is likely the cause.

**Comment by clason** [comment] 2022-08-21 13:30
#19862 changed the behavior of `fargs` in Lua callbacks for `nvim_create_user_command` with `nargs='?'` to match the behavior of `nargs='*'` if no arguments were provided (`fargs = {}` instead of `fargs = { "" }`).

**Comment by zeertzjq** [comment] 2022-08-24 13:05
#19743 changed Vim functions `winheight()`, `winwidth()`, `getwininfo()` to return inner window width and height.

In non-multigrid UI the only change is that the returned height now excludes winbar, and this is compatible with Vim.

In multigrid UI this means the return value of these functions now reflect the space available for buffer lines in a window.

No change in `nvim_win_get_height` and `nvim_win_get_width`.

**Comment by bfredl** [comment] 2022-08-26 12:45
The rules for defining highlights in tree-sitter highlights.scm changed. #19931 

Previously the following two mechanisms were available

- use a capture name with initial uppercase. `@WarningMsg.foo` automatically mapped to highlight group `WarningMsg`
- (undocumented but often used) extend the `vim.treesitter.highlighter.hl_map` dict to translate lowercase groups.

**Both of these are now removed**. Instead capture names, _including_ the initial `@`, are now directly usable as highlight groups, both using ex commands and the api:

```
   :hi link @foo.bar MyHighlight
   :lua vim.api.nvim_set_hl(0, "@string.special", {fg="Green"})
```

There are no special behaviour for upper-case names (case-insensitive just like all highlight group names). The same fallback rule still applies: if a highlight is defined for `@foo` but not for `@foo.bar`, the former is used for `@foo.bar` captures.

**Comment by lewis6991** [comment] 2022-08-28 11:24
Previously if a highlight group with a name outside the regexp [a-zA-Z0-9_] was defined, Nvim would emit an invalid character warning message. This has now been promoted to an error with the code E1248 E5248.

Additionally the ASCII character period (`.`) and at-sign (`@`) has been added to the allowed list of characters of a highlight group name to support the application of defining hierarchical highlight groups, e.g. `@keyword`.

See #19830

**Comment by zeertzjq** [comment] 2022-08-31 13:15
#20020 introduced the following breaking changes:
- `nvim_get_keymap` now always returns a LuaRef object as `callback` for a
  Lua mapping regardless of how it is called. The LuaRef object can be
  called from Lua and Vim script, but is lost over RPC.
- `maparg()` now returns a Funcref instead of a ref number as `callback`
  for a Lua mapping. The Funcref can be called from Lua and Vim script,
  but is lost over RPC.

**Comment by clason** [comment] 2022-09-06 08:23
*Treesitter parsers and queries (#15391)*

Neovim now bundles parsers and highlight queries for Lua, Vimscript, and C; by default the former are installed in `/usr/local/lib/nvim/parsers`, the latter in `/usr/local/share/nvim/runtime/queries`. Parsers and queries from plugins and user configs should take precedence, but conflicts cannot be ruled out.

To enable treesitter highlighting for Lua, add `vim.g.ts_highlight_lua = true` to your `init.lua`. (Note that this disables regex syntax highlighting, which plugins may rely on for functionality. In this case, add `vim.bo.syntax = 'ON'` to `ftplugin/lua.lua` in your config.)

**Comment by bfredl** [comment] 2022-09-06 08:35
https://github.com/neovim/neovim/pull/20039 `nvim_parse_cmd()` now returns `tab = -1` instead of `tab = 0` when `:tab` modifier is absent. This makes it possible for `:[n]tab` to be properly forwarded to `nvim_cmd()` for all valid non-negative values.

**Comment by vigoux** [comment] 2022-09-08 07:52
__Treesitter runtime queries (https://github.com/neovim/neovim/pull/20105)__

The behavior of the runtime queries changed and now works as follows:
- The last query in the `rtp` without and `extends` modeline will be used as the base query
- All queries (without a specific order) with an `extends` modeline are concatenated with the base query

This has to be done to correctly handle different version of the queries, working with different parsers following #15391.

**Comment by zeertzjq** [comment] 2022-09-16 15:12
#20217 make Lua Funcrefs work as methods in Vim script. When using a Funcref converted from a Lua function as a method in Vim script, the result of the base expression is now passed as the first argument instead of being ignored.

**Comment by lewis6991** [comment] 2022-09-22 13:01
#20103: The methods `append`, `prepend`, `remove` in `vim.opt[_local]` no longer return a value and now act on the option object in-place.

**Comment by justinmk** [comment] 2022-09-25 12:36
- renamed `vim.treesitter.get_captures_at_position` => `vim.treesitter.get_captures_at_pos`
- renamed `vim.treesitter.get_node_at_position` => `vim.treesitter.get_node_at_pos`

https://github.com/neovim/neovim/pull/20331

**Comment by zeertzjq** [comment] 2022-09-25 23:16
#20344 changed `:undo!` to notify buffer update callbacks.

**Comment by zeertzjq** [comment] 2022-09-30 08:24
#20364 changed `nvim_parse_cmd` to omit `count`, `range`, `reg` fields for commands that do not support these fields, so that the result of `nvim_parse_cmd` can be used directly in `nvim_cmd` without causing an error.

**Comment by zeertzjq** [comment] 2022-09-30 08:26
#20387 changed `nvim_cmd` to use digits in the beginning of the first argument as count if the command supports a count.

**Comment by lewis6991** [comment] 2022-10-14 08:54
#20545: cscope has been removed

**Comment by clason** [comment] 2022-10-17 06:54
#20428 **removes `filetype.vim`** in favor of the now default `filetype.lua`.

The filetype detection _logic_ and tests still align with Vim, so additions or changes still need to be contributed there first and then ported to Neovim.

**Comment by lewis6991** [comment] 2023-01-03 10:08
#21472:  `:hardcopy` is now removed

  - Commands removed:
    - `:hardcopy`
  - Options removed:
    - `printdevice`
    - `printencoding`
    - `printexpr`
    - `printfont`
    - `printheader`
    - `printmbcharset`

**Comment by justinmk** [comment] 2023-01-07 02:34
https://github.com/neovim/neovim/pull/18706 `nvim -l` now invokes Lua scripts instead of setting the 'lisp' option. To set the 'lisp' option as `-l` formerly did, just set it like any other option:

    nvim -c "set lisp"

**Comment by zeertzjq** [comment] 2023-01-16 22:25
#21768: In 'statuscolumn' evaluation, `v:wrap` has been replaced by `v:virtnum`. `v:virtnum` is negative when drawing virtual lines, zero when drawing the actual buffer line, and positive when drawing the wrapped part of a buffer line.

**Comment by lewis6991** [comment] 2023-01-23 16:34
#21832: libiconv is now a required build dependency.

**Comment by dundargoc** [comment] 2023-01-30 18:07
https://github.com/neovim/neovim/pull/22060: `has("debug")` has been removed.

**Comment by zeertzjq** [comment] 2023-02-11 10:25
#22137: Unsaved changes are now preserved rather than discarded when stdio channel is closed.

**Comment by clason** [comment] 2023-02-15 08:59
#22257 removed the (undocumented) `vim.g.ts_highlight_lua` variable that enabled treesitter highlighting for Lua files. (This variable was only meant for easier testing during the last development cycle.)

To enable treesitter highlighting for Lua files (or any of the file types with a bundled parser), either put `vim.treesitter.start()` in a `.config/nvim/ftplugin/lua.lua` (and/or `help.lua`, `c.lua`, `vim.lua`) or in an autocommand like
```lua
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'lua', -- or { 'lua', 'help' },
  callback = function() vim.treesitter.start() end,
})
```

**Comment by justinmk** [comment] 2023-03-12 15:21
# Breaking changes are now tracked in `:help news`

- Breaking changes are now tracked in [:help news](https://neovim.io/doc/user/news.html#news-breaking)
- Where possible, breaking changes are also flagged with [vim.deprecate()](https://neovim.io/doc/user/lua.html#vim.deprecate())

**Closed by justinmk** 2023-03-12 15:21 UTC
Labels: enhancement, compatibility, project-management

**Comment by clason** [comment] 2023-03-12 18:51
You can also subscribe to all changes to `news.txt` with a RSS reader via [http://github.com/neovim/neovim/commits/master/runtime/doc/news.txt.atom](https://github.com/neovim/neovim/commits/master/runtime/doc/news.txt.atom)
