### ISSUE TITLE
screen redraw issue

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#20362] opened 2022-09-27 04:42 UTC
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1170-g63be76518

### Vim (not Nvim) behaves the same?

-

### Operating system/version

windows10

### Terminal name/version

-

### $TERM environment variable

-

### Installation

-

### How to reproduce the issue

1. nvim --clean
2. input  `100ojk<esc>ggu`
3. you will find screen redraw issue

### Expected behavior

-

### Actual behavior

-

**Comment by zeertzjq** [comment] 2022-09-27 05:01
Duplicate of #20332

**Closed by zeertzjq** 2022-09-27 05:01 UTC
Labels: bug
