### ISSUE TITLE
swap file fails to open with a UNC path on Windows

### ISSUE THREAD

**Issue by farnoy** [neovim/neovim#29528] opened 2024-07-01 08:07 UTC
### Problem

Trying to open a file with a UNC path: `$ nvim \\?\C:\some-file.txt` gives this message immediatlely: `E303: Unable to open swap file for "\\?\C:\some-file.txt", recovery impossible`. The usual version of this path would be `C:\some-file.txt` and that works just fine.

I also noticed this same issue with undofile when using with `jj commit` but I don't have an immediate reproducing example.

[Microsoft docs](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#fully-qualified-vs-relative-paths)

### Steps to reproduce

```
nvim \\?\C:\some-file.txt
```

### Expected behavior

I expected it to work without emitting warnings and to use the same swap & undo files as when it's opened with a relative path or the traditional `C:\some-file.txt`.

### Neovim version (nvim -v)

v0.11.0-dev-313+gfc9b70826

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Windows 11

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

n/a

### Installation

nightly zip

**Comment by lsvmello** [comment] 2024-10-04 17:12
Duplicate of #29495

**Closed** 2024-10-04 22:59 UTC
Labels: bug, platform:windows, filesystem
