### ISSUE TITLE
Weird behaviour when opening files from terminal file managers

### ISSUE THREAD

**Issue by n0ibe** [neovim/neovim#11816] opened 2020-02-04 12:52 UTC
- `nvim --version`:  NVIM v0.4.3
- Operating system/version: Mac OS 10.15.2

Approximately 3 out of 5 times when I open a text file from a terminal file manager like ranger, lf or vifm I get a very weird behaviour where nvim opens in command mode with some string in it. [Here](https://imgur.com/a/kGQh9pt) are all the different behaviours I get.

Like I said, this doesn't happen every single time, and I don't always get the same text in the command mode when it does.

This never happens when I open a file directly from the command line. Any ideas about what could be causing this?

**Comment by justinmk** [comment] 2020-02-05 09:03
Duplicate of https://github.com/neovim/neovim/issues/11393

**Closed by justinmk** 2020-02-05 09:03 UTC
Labels: bug
