### ISSUE TITLE
nvim_create_autocmd pattern does not expand environment variables

### ISSUE THREAD

**Issue by mardamkada** [neovim/neovim#20804] opened 2022-10-26 03:16 UTC
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

OpenSUSE Tumbleweed

### Terminal name/version

Kitty 0.26.3

### $TERM environment variable

xterm-kitty

### Installation

standard repo

### How to reproduce the issue

Open Neovim in home directory:
`nvim --clean`

Create autocmd with Lua using an environment variable in the pattern:
`:lua vim.api.nvim_create_autocmd("BufEnter", {pattern="$HOME/*", command='echo "hello world"'})`

Attempt to trigger the autocmd:
`:e somefile`

### Expected behavior

Autocmd gets triggered. 

### Actual behavior

Autocmd doesn't get triggered. Using the `~` alias for $HOME has the same unexpected behavior.

This is inconsistent with an autocmd created with the `au` command, (eg. `:au BufEnter $HOME/* echo "hello world"` works as expected), as well Lua autocmds without environment variables in the pattern (eg. `:lua vim.api.nvim_create_autocmd("BufEnter", {pattern="/home/user/*", command='echo "hello world"'})` also works as expected).

**Comment by zeertzjq** [comment] 2022-10-26 03:27
No, environment variables definitely should not be expanded, and changing this will break backward compatibility.

**Comment by mardamkada** [comment] 2022-10-26 03:33
If that's so, then it should be noted in the documentation. The help for nvim_create_autocmd() only mentions that patterns are matched against autocmd-pattern, which does expand environment variables

**Comment by clason** [comment] 2022-10-26 10:04
Duplicate of #17744

**Closed** 2022-10-26 10:04 UTC
Labels: documentation, api
