### ISSUE TITLE
`screenpos()` returns wrong result for some windows / tabs.

### ISSUE THREAD

**Issue by pbogut** [neovim/neovim#19606] opened 2022-08-01 10:01 UTC
### Neovim version (nvim -v)

NVIM v0.8.0-dev-nightly-2-gd529523027

### Vim (not Nvim) behaves the same?

Not sure, it happens randomly and I notice it only when using `nvim-cmp`

### Operating system/version

Linux / Arch Linux

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

xterm-256color

### Installation

AUR / neovim-git

### How to reproduce the issue

Happens randomly, was not able to reproduce it on demand yet, if I figure this out I will update isuue.

### Expected behavior

`screenpos()` to always return correct position.

### Actual behavior

When using `screenpos()` sometimes result is wrong:
```
{
  col = 0,
  curscol = 0,
  endcol = 0,
  row = 1
}
```

I've created a helper binding to test it:
```
:nmap <c-s> :lua print(vim.inspect(vim.fn.screenpos(0, vim.api.nvim_win_get_cursor(0)[1], vim.api.nvim_win_get_cursor(0)[2]+1)))<cr>

```
When I use `<c-s>` it sometimes returns this wrong data set. When it gets broken, it is broken for every window in given tab, if I open split, change buffer it is all broken. Same file in different tab will work all right.

I've also noticed that when I use `:set nowrap` it gets fixed and works with no issues (even when follow with `:set wrap` it still works till it gets broken again).

By default I have `wrap` enabled.

This affects `nvim-cmp` for me. When function doesn't work the completion window is rendered in left top corner no matter what my position in the window is.

In example below on both tabs I'm on the line 10 and using my helper mapping `<c-s>`:

Correct result:
![screenshot_from_2022-08-01_11-46-25](https://user-images.githubusercontent.com/1702152/182123551-7dfed7ec-22ab-4410-a1d7-4fe9b729e5bb.png)

Wrong result:
![screenshot_from_2022-08-01_11-46-34](https://user-images.githubusercontent.com/1702152/182123555-3994ef99-0a7d-4799-a051-5ca412649f3b.png)

**Comment by echasnovski** [comment] 2022-08-01 12:52
My guess is that it has something to do with [legacy `screenchar()` tests](https://github.com/neovim/neovim/blob/ece0850b7393114cac651cf9f43fc2c5e1b1cf50/src/nvim/eval.c#L5672-L5676) that are used to check command line output. It might be the "correct" result for message area. Maybe it is happening for when some messages are shown or Command mode is active?
Does using `<Cmd>` in mapping changes observations? So like this:
```
:nmap <c-s> <Cmd>lua print(vim.inspect(vim.fn.screenpos(0, vim.api.nvim_win_get_cursor(0)[1], vim.api.nvim_win_get_cursor(0)[2]+1)))<cr>
```

**Comment by pbogut** [comment] 2022-08-01 13:59
As far as I can tell there is no difference if i use `:lua ....` or `<cmd>lua ...`. Results are the same.

Also, another thing that is affected when bug happens is `Telescope`, I have shifted list when error is in place:

When all is all right:
![screenshot_from_2022-08-01_15-53-49](https://user-images.githubusercontent.com/1702152/182163798-0d697c7f-79d4-4868-8ea9-26072e2ae9be.png)

When bug occurs:
![screenshot_from_2022-08-01_15-53-40](https://user-images.githubusercontent.com/1702152/182163892-2592f1ef-c032-4d61-8809-6ecd933d3723.png)


I've also noticed that updating wrap in window helps even if its not changed:
`:lua vim.wo.wrap = vim.wo.wrap` maks this bug go away (for some time).

**Comment by echasnovski** [comment] 2022-08-01 14:58
@justinmk, other than that, I don't think these issues are related. `screenpos()` has different implementation than `screenattr()`, `screenchar()`, `screenchars()`, and `screenstring()`. It [uses `textpos2screenpos()`](https://github.com/neovim/neovim/blob/c6181a672a2fdb2cb89ddf85b5d6ab15b10a0996/src/nvim/eval/funcs.c#L7655) which indeed [has something to do with `wrap`](https://github.com/neovim/neovim/blob/c6181a672a2fdb2cb89ddf85b5d6ab15b10a0996/src/nvim/move.c#L1007-L1012). Maybe problem is there.

**Comment by pbogut** [comment] 2022-08-26 06:46
If it's any help at all I noticed it is only happening when I'm using vertical splits. Never happens without split being created first.

**Comment by johnwilmes** [comment] 2023-01-27 15:21
Not sure if this is related, but I can reliably get screenpos to give incorrect results when 'wrap' is on and I am querying a line that wraps past the end of the window.

Procedure:
Open new neovim session with single window/buffer, set wrap on
Make the first line of buffer short or empty, and the second line long enough that it can't display entirely in the window
Put the cursor on the first line and :echo screenpos(1000,2,1)

Expected behavior:
```
{
  col = something positive depending on size of number column/sign column/etc.,
  curscol = same,
  endcol = same,
  row = 2
}

```
Actual behavior
```
{
  col = 0,
  curscol = 0,
  endcol = 0,
  row = 57 (something like the number of lines on my screen?)
}
 
```

**Comment by zeertzjq** [comment] 2023-01-27 22:45
@johnwilmes This has already been fixed. Your version is too old.

**Comment by zeertzjq** [comment] 2023-08-19 00:36
Closing because nothing can be done without steps to reproduce.

**Closed by zeertzjq** 2023-08-19 00:36 UTC
Labels: bug, ui, needs:repro

**Comment by wincent** [comment] 2024-10-03 10:53
@pbogut did you ever get a reliable repro recipe for this one? I see the same thing (`screenpos` returns top-left coordinates, far away from where cursor actually is, causing `nvim-cmp` to draw its completion menu in the wrong place, up in the corner) from time to time, but it's so intermittent and unpredictable that I've never been able to boil it down to a set of concrete steps; days or even weeks can pass before I see it, but it's often enough that when I do see it drives me crazy 😬

**Comment by pbogut** [comment] 2024-10-04 07:06
@wincent Unfortunately no. I just learned to live with no wrap (`vim.o.wrap = false` / `:set nowrap`). This bug only happens when you use wraping.
