### ISSUE TITLE
search function

### ISSUE THREAD

**Issue by lasypig** [neovim/neovim#28686] opened 2024-05-10 03:50 UTC
### Problem

when I type ``:map`` to see the keybinds, the output has too much lines, This is annoying.

### Expected behavior

Add search function to the output of the commands like ``:map``, ``:highlight`` ...
such as type ``/keyword`` to jump to the postion that **contain** keyword

**Comment by wookayin** [comment] 2024-05-10 04:20
:help filter

e.g. `:filter Tab map`

would this suffice for you?

**Comment by zeertzjq** [comment] 2024-05-10 05:10
Duplicate of #5054

**Closed by zeertzjq** 2024-05-10 05:10 UTC
Labels: enhancement

**Comment by lasypig** [comment] 2024-05-11 06:36
`` :put =execute('map') ``
