### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by caseycronyn** [neovim/neovim#31750] opened 2024-12-28 02:35 UTC
### Problem

I believe there is an error in the Neovim documentation at [VIM.HL](https://neovim.io/doc/user/lua.html#vim.highlight).

The code block to make highlight on yank work within the init.vim file is: 
`autocmd TextYankPost * silent! lua vim.hl.on_yank {higroup='Visual', timeout=300}`
however I found this didn't work and it needs to be:
 `autocmd TextYankPost * silent! lua vim.highlight.on_yank{higroup='Visual', timeout=300}` 
to work (highlight in full and no space after yank).

### Steps to reproduce

nvim

### Expected behavior

Highlighting

### Nvim version (nvim -v)

0.10.3

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

macOS

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

Homebrew

**Comment by zeertzjq** [comment] 2024-12-28 02:49
Duplicate of https://github.com/neovim/neovim.github.io/issues/348

**Closed by zeertzjq** 2024-12-28 02:49 UTC
Labels: bug
