### ISSUE TITLE
Some settings like `relativenumber`, `cursorline`,  `conceallevel` cause slowness / lag when updating the buffer

### ISSUE THREAD

**Issue by asgeo1** [neovim/neovim#15005] opened 2021-07-06 09:29 UTC
- `nvim --version`: NVIM v0.5.0
- Operating system/version: OSX 10.15.7
- Terminal name/version: Kitty 0.21.1
- `$TERM`: `xterm-kitty`

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC /path/to/ruby/file.rb
```

STEPS:

1. Edit a Ruby file (at least 500 lines long) as above
2. Hold down the `x` (delete character) key for at least 5 seconds, and delete a stream of text
3. Hold down the `u` (undo) key for at least 5 seconds, and undo those deletions
4. Take careful note above how **_smooth_** these actions of deleting and restoring the text is. The buffer should be updated with no delay
5. `:set relativenumber`
6. Repeat steps 2-4

Notice that when `relativenumber` is on, the performance of holding down `x` and `u` is much worse. I can visibly see lag on my screen, it's very jittery. Whereas with it off, everything performs nice and smooth, instant.

I don't believe this was an issue with 0.4 Neovim.  Using Vim 8.1, I'm not seeing these issues either.

The same issue can happen with languages other than Ruby, but to a lesser extent. For example, Typescript seems to perform much better. (but there is still some lag)  I think it also depends on the size of the file, larger files it gets worse on.  Ruby is seems particularly bad on, and the lag is very noticeable for me.

The same lag issue also happens when turning on either `cursorline` or setting `conceallevel = 2`

Could be related to or the same issue reported [here](https://github.com/neovim/neovim/issues/14154), not sure.

**Comment by glacambre** [comment] 2021-07-06 13:25
If this didn't happen on Neovim 0.4, it would be very useful to bisect neovim to find out when this regression was introduced.

**Comment by justinmk** [comment] 2021-07-07 21:29
old, known vim issue. see https://github.com/neovim/neovim/issues/9984

duplicate of https://github.com/neovim/neovim/issues/4736

**Closed by justinmk** 2021-07-07 21:29 UTC
Labels: bug, performance
