### ISSUE TITLE
execute() call does not reset cmdline

### ISSUE THREAD

**Issue by liushapku** [neovim/neovim#9250] opened 2018-11-18 06:50 UTC
- `nvim --version`: 0.3.1
- Vim (version: ) behaves differently? YES
- Operating system/version: ubuntu 18.04
- Terminal name/version: gnome terminal
- `$TERM`:  xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

function! Test()
    let x = execute('echo 12345')
   echo '****'
endfunction
call Test()
```

### Actual behaviour
The echoed stars '****' will display from column 6

### Expected behaviour
The stars be displayed from column 1

### Other info
change 'echo 12345' to 'pwd' or other command that generates output will still has the error. However the following function behaves correctly
```
function! Test2()
    echo 'ABC'
    let x = execute('echo 12345')
    echo '****'
endfunction
```

It seems that `execute(xxx)` will only affect the cursor position if it is the first function to generate output.

Some guess:
- In `Test2`, `echo 'ABC'` will reset the terminal state so that `echo '****'` will be correct.
- In `Test1`, `echo '12345'` inside the `execute()` does not reset the terminal and the `echo '****'` is incorrect.

**Comment by justinmk** [comment] 2018-11-18 13:20
Duplicate of #6035

**Closed by justinmk** 2018-11-18 13:20 UTC

**Comment by liushapku** [comment] 2018-11-18 15:30
It is found that the starting column of the `echo` following the `execute()` equals the length of the last line of x (split at newline). Adding an `echon "\r"` after the execute can partially solve the problem in practice, except when you use `echon` after the `execute`, then the column is still wrong.

**Comment by justinmk** [comment] 2018-11-18 17:00
Send a PR?

**Comment by liushapku** [comment] 2018-11-19 14:17
I tried to build the binary from source code, but failed. Too many dependency fails and have no idea how to fix the dependencies. I use ubuntu 18.04. Is there a tutorial on how to install all the dependencies? Can I install the dependencies using conda?

**Comment by liushapku** [comment] 2018-11-19 14:33
Thanks, it works. I am actually a newbie here. Hope I can identify the code for echo

**Comment by liushapku** [comment] 2018-12-06 10:06
@justinmk I proposed a solution at [6035](https://github.com/neovim/neovim/issues/6035)
