### ISSUE TITLE
Lines disappear when moving with Hindi and 'cursorline' 

### ISSUE THREAD

**Issue by georg3tom** [neovim/neovim#9976] opened 2019-05-06 19:33 UTC
- `nvim --version`:NVIM v0.3.4
- Operating system/version:Fedora 30
- Terminal name/version:gnome-terminal

Lines disappear and reappear while moving around files containing characters of Malayalam or Hindi
Happens only when the cursor line is set.

### Steps to reproduce using `nvim -u NORC

````
nvim -u NORC
:set cursorline
````

sample text:
````
qwerty
txt="സംസ്ഥാനത്തെ പ്രമുഖ നഗരങ്ങളിൽ ചിത്രം റീലീസ് ചെയ്തിട്ടുണ്ട്."
ln=len(txt)
````

![ezgif com-gif-maker](https://user-images.githubusercontent.com/22193688/57248512-29162800-7060-11e9-9c9e-4942a3dad90d.gif)

**Comment by justinmk** [comment] 2019-05-06 19:36
Thanks for the report. Can you try the development version? 

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by georg3tom** [comment] 2019-05-06 19:48
Tried it with NVIM v0.4.0-713-g8a1880f04
Issue still persists.

**Comment by justinmk** [comment] 2019-05-06 20:05
Are those right-to-left languages?

**Comment by georg3tom** [comment] 2019-05-06 20:22
No. Left-to-right

**Comment by georg3tom** [comment] 2019-05-06 20:27
Also some of the characters appear when the terminal is opened while the other buffer is open.
![Screenshot from 2019-05-07 01-54-48](https://user-images.githubusercontent.com/22193688/57253000-44d2fb80-706b-11e9-9156-eeaa85b62120.png)

**Comment by justinmk** [comment] 2019-05-07 07:25
Vim 8.1.1005 has the same bug. cc @chrisbra

**Comment by chrisbra** [comment] 2019-05-07 08:24
works in gvim and putty. I think this is a rendering problem because the terminal and vim have different understanding of the width of certain chars, causing the cursorline rendering to continue at the next line. Might be caused by different unicode libraries.

**Comment by justinmk** [comment] 2019-05-07 08:30
Thanks @chrisbra . This is a duplicate of https://github.com/neovim/neovim/issues/7151

**Closed by justinmk** 2019-05-07 08:30 UTC
Labels: bug, bug-vim, display, encoding, help wanted, tui
