### ISSUE TITLE
module 'lpeg' not found when using bundled dependencies

### ISSUE THREAD

**Issue by danzimm** [neovim/neovim#12346] opened 2020-05-19 14:42 UTC
- Operating system/version: macOS 10.15.4
- Terminal name/version: Terminal (builtin), shell = fish
- `$TERM`: xterm-256color

### Steps to reproduce
- `git clone https://github.com/neovim/neovim.git`
- `make distclean`
- `make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=$HOME`

### Actual behaviour
The dependencies get installed (including lpeg) and then eventually the following error occurs:
```
-- Checking Lua interpreter: /path/redacted/neovim/.deps/usr/bin/luajit
/path/redacted/neovim/.deps/usr/bin/luajit: module 'lpeg' not found:
	no field package.preload['lpeg']
	no file './lpeg.lua'
	no file '/path/redacted/neovim/.deps/usr/share/luajit-2.1.0-beta3/lpeg.lua'
	no file '/usr/local/share/lua/5.1/lpeg.lua'
	no file '/usr/local/share/lua/5.1/lpeg/init.lua'
	no file '/path/redacted/neovim/.deps/usr/share/lua/5.1/lpeg.lua'
	no file '/path/redacted/neovim/.deps/usr/share/lua/5.1/lpeg/init.lua'
stack traceback:
	[C]: at 0x01021559b0
	[C]: at 0x01020e56d0
-- [/path/redacted/neovim/.deps/usr/bin/luajit] The 'lpeg' lua package is required for building Neovim
CMake Error at CMakeLists.txt:506 (message):
  Failed to find a Lua 5.1-compatible interpreter
```

### Expected behaviour
Build to succeed

**Comment by h-michael** [comment] 2020-05-19 14:49
If you also remove ./build, does the same occurs?

**Comment by clason** [comment] 2020-05-19 14:52
And `.deps`. (For what it's worth, `make` from a clean checkout works for me fine in macOS 10.15.4.)

**Comment by erw7** [comment] 2020-05-20 08:51
@danzimm Usually the error message should contain the following:

```
        no file './lpeg.so'
        no file '/usr/local/lib/lua/5.1/lpeg.so'
        no file '/path/redacted/neovim/.deps/usr/lib/lua/5.1/lpeg.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

But your error message doesn't try to search for `lpeg.so`. If `LUA_CPATH` is empty, it will not look for `lpeg.so` as well as your error message as shown below.

```
> ~/neovim/.deps/usr/bin/luajit -l 'lpeg' -e ''
> export LUA_CPATH=
> ~/neovim/.deps/usr/bin/luajit -l 'lpeg' -e ''
> /home/erw7/neovim/.deps/usr/bin/luajit: module 'lpeg' not found:
        no field package.preload['lpeg']
        no file './lpeg.lua'
        no file '/home/erw7/neovim/.deps/usr/share/luajit-2.1.0-beta3/lpeg.lua'
        no file '/usr/local/share/lua/5.1/lpeg.lua'
        no file '/usr/local/share/lua/5.1/lpeg/init.lua'
        no file '/home/erw7/neovim/.deps/usr/share/lua/5.1/lpeg.lua'
        no file '/home/erw7/neovim/.deps/usr/share/lua/5.1/lpeg/init.lua'
stack traceback:
        [C]: at 0x04d5b12360
        [C]: at 0x0100401b70
```

If you are setting environment variables such as `LUA_CPATH`, why don't you `unset` it and build it again?

**Comment by swarn** [comment] 2020-11-21 18:14
I'm also getting the same error, maybe with a different cause. Building from a clean checkout, I get `module 'lpeg' not found`, though it happily handles other third-party deps.


```
$ sw_vers
ProductName:    macOS
ProductVersion: 11.0.1
BuildVersion:   20B50

$ cc -v
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ /opt/local/bin/lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio

$ /opt/local/bin/luajit -v
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/

$ cd /Users/me/edit
$ git clone https://github.com/neovim/neovim.git
$ cd neovim
$ git log -1 --format="%H"
e192a4600af6db8c54f22c854cbabf0b071ca4bc

$ make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=~/.local/stow/neovim

[... trimmed ...]

-- Checking Lua interpreter: /Users/me/src/edit/neovim/.deps/usr/bin/luajit
/Users/me/src/edit/neovim/.deps/usr/bin/luajit: module 'lpeg' not found:
    no field package.preload['lpeg']
    no file '/Users/me/.luarocks/share/lua/5.3/lpeg.lua'
    no file '/Users/me/.luarocks/share/lua/5.3/lpeg/init.lua'
    no file '/opt/local/share/luarocks/share/lua/5.3/lpeg.lua'
    no file '/opt/local/share/luarocks/share/lua/5.3/lpeg/init.lua'
    no file '/opt/local/share/lua/5.3/lpeg.lua'
    no file '/opt/local/share/lua/5.3/lpeg/init.lua'
    no file '/opt/local/lib/lua/5.3/lpeg.lua'
    no file '/opt/local/lib/lua/5.3/lpeg/init.lua'
    no file './lpeg.lua'
    no file './lpeg/init.lua'
    no file '/Users/me/.luarocks/lib/lua/5.3/lpeg.so'
    no file '/opt/local/share/luarocks/lib/lua/5.3/lpeg.so'
    no file '/opt/local/lib/lua/5.3/lpeg.so'
    no file '/opt/local/lib/lua/5.3/loadall.so'
    no file './lpeg.so'
stack traceback:
    [C]: at 0x0104664af0
    [C]: at 0x01045f5270
-- [/Users/me/src/edit/neovim/.deps/usr/bin/luajit] The 'lpeg' lua package is required for building Neovim
-- Checking Lua interpreter: /opt/local/bin/lua
/opt/local/bin/lua: module 'lpeg' not found:
    no field package.preload['lpeg']
    no file '/Users/me/.luarocks/share/lua/5.3/lpeg.lua'
    no file '/Users/me/.luarocks/share/lua/5.3/lpeg/init.lua'
    no file '/opt/local/share/luarocks/share/lua/5.3/lpeg.lua'
    no file '/opt/local/share/luarocks/share/lua/5.3/lpeg/init.lua'
    no file '/opt/local/share/lua/5.3/lpeg.lua'
    no file '/opt/local/share/lua/5.3/lpeg/init.lua'
    no file '/opt/local/lib/lua/5.3/lpeg.lua'
    no file '/opt/local/lib/lua/5.3/lpeg/init.lua'
    no file './lpeg.lua'
    no file './lpeg/init.lua'
    no file '/Users/me/.luarocks/lib/lua/5.3/lpeg.so'
    no file '/opt/local/share/luarocks/lib/lua/5.3/lpeg.so'
    no file '/opt/local/lib/lua/5.3/lpeg.so'
    no file '/opt/local/lib/lua/5.3/loadall.so'
    no file './lpeg.so'
stack traceback:
    [C]: in function 'require'
    [C]: in ?
-- [/opt/local/bin/lua] The 'lpeg' lua package is required for building Neovim
CMake Error at CMakeLists.txt:509 (message):
  Failed to find a Lua 5.1-compatible interpreter
```

It definitely built `lpeg`, though:

```
$ ls -l .deps/usr/lib/lua/5.1/lpeg.so
-rwxr-xr-x  1 me  staff  109632 Nov 21 11:32 .deps/usr/lib/lua/5.1/lpeg.so
```

**Comment by yatli** [comment] 2021-10-09 05:56
got this, unset `LUA_PATH` and `LUA_CPATH`, builds fine now

**Comment by justinmk** [comment] 2023-03-08 17:08
The cmake project has been significantly simplified and improved, so I assume this is fixed.

Please confirm if or if not!

**Comment by swarn** [comment] 2023-03-08 17:28
The behavior has not changed for me: using commit ddd257f75301a50c177fc24a693d39a45b47a689, I still need to unset `LUA_PATH` and `LUA_CPATH` before building, or it won't use the bundled deps. I thought that was my user error, not a bug.

**Comment by dundargoc** [comment] 2023-03-08 17:43
> I thought that was my user error, not a bug.

Let's not get hasty ;)

Suffice to say I don't encounter this. Did you run "make distclean" beforehand? How are you installing it?

**Comment by swarn** [comment] 2023-03-08 18:04
```
$ sw_vers
ProductName:        macOS
ProductVersion:     13.2.1
BuildVersion:       22D68

$ cc -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ git clone git@github.com:neovim/neovim.git
$ cd neovim
$ git log -1 --format="%H"
276b647fdba07bf1762d8dd371c4b655b8a418df

$ echo $LUA_PATH
[... trimmed ...]

$ echo $LUA_CPATH
[... trimmed ...]

$ make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=~/.local/stow/neovim-master

[... trimmed ...]

-- Checking Lua interpreter: /Users/seth/src/edit/neovim/.deps/usr/bin/luajit
/Users/seth/src/edit/neovim/.deps/usr/bin/luajit: error loading module 'lpeg' from file '/opt/homebrew/lib/lua/5.4/lpeg.so':
    dlopen(/opt/homebrew/lib/lua/5.4/lpeg.so, 0x0006): symbol not found in flat namespace '_luaL_checkversion_'
stack traceback:
    [C]: at 0x0104ccb530
    [C]: at 0x0104ccb944
    [C]: at 0x0104c63640
-- [/Users/seth/src/edit/neovim/.deps/usr/bin/luajit] The 'lpeg' lua package is required for building Neovim
-- Checking Lua interpreter: /opt/homebrew/bin/lua
/opt/homebrew/bin/lua: module 'mpack' not found:
    no field package.preload['mpack']
    no file '/opt/homebrew/Cellar/luarocks/3.9.1/share/lua/5.4/mpack.lua'
    no file '/opt/homebrew/share/lua/5.4/mpack.lua'
    no file '/opt/homebrew/share/lua/5.4/mpack/init.lua'
    no file '/opt/homebrew/lib/lua/5.4/mpack.lua'
    no file '/opt/homebrew/lib/lua/5.4/mpack/init.lua'
    no file './mpack.lua'
    no file './mpack/init.lua'
    no file '/Users/seth/.luarocks/share/lua/5.4/mpack.lua'
    no file '/Users/seth/.luarocks/share/lua/5.4/mpack/init.lua'
    no file '/opt/homebrew/lib/lua/5.4/mpack.so'
    no file '/opt/homebrew/lib/lua/5.4/loadall.so'
    no file './mpack.so'
    no file '/Users/seth/.luarocks/lib/lua/5.4/mpack.so'
stack traceback:
    [C]: in function 'require'
    [C]: in ?
-- [/opt/homebrew/bin/lua] The 'mpack' lua package is required for building Neovim
CMake Error at CMakeLists.txt:185 (message):
  Failed to find a Lua 5.1-compatible interpreter
```

The `LUA_*` vars are set by `eval "$(luarocks path --bin)"` in my dotfiles. The build completes without them:
```
$ unset LUA_PATH && unset LUA_CPATH
$ make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=~/.local/stow/neovim-master
[... success ...]
```

**Comment by swarn** [comment] 2023-03-08 22:14
Yes, the lua interpreter it's seeing is the lua I have installed via homebrew:
```
$ which lua
/opt/homebrew/bin/lua
$ which luarocks
/opt/homebrew/bin/luarocks
$ lua -v
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
```
This is the default [lua in homebrew](https://formulae.brew.sh/formula/lua) is 5.4, which is also the default dependency for [homebrew's luarocks](https://formulae.brew.sh/formula/luarocks#default). Putting the `eval "$(luarocks path --bin)"` in .bashrc is mentioned [here](https://github.com/luarocks/luarocks/wiki/Using-LuaRocks#rocks-trees-and-the-lua-libraries-path). I mention all of this only to say I don't _think_ I have a bizarre lua setup.

Uninstalling the homebrew lua definitely fixes the problem: no lua -> no luarocks -> no `LUA_PATH` variable. Without `LUA_PATH`, the build process correctly uses the lua in `.deps/`; with `LUA_PATH`, it tries to use `/opt/homebrew/bin/lua`.
```
$ echo $LUA_PATH
/opt/homebrew/Cellar/luarocks/3.9.1/share/lua/5.4/?.lua;/opt/homebrew/share/lua/5.4/?.lua;/opt/homebrew/share/lua/5.4/?/init.lua;/opt/homebrew/lib/lua/5.4/?.lua;/opt/homebrew/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua;/Users/seth/.luarocks/share/lua/5.4/?.lua;/Users/seth/.luarocks/share/lua/5.4/?/init.lua
```

**Comment by dundargoc** [comment] 2023-03-08 22:25
No I don't think it's unreasonable setup you have. I just needed some kind of clue to figure out what is happening. I've tried to recreate this test by installing lua5.4 and building neovim but I cannot recreate this issue. I wonder if this is specific to homebrew+mac.

**Comment by swarn** [comment] 2023-03-08 23:10
Well, looking at the log, I see that it first checks the bundled lua `.deps/usr/bin/luajit`, but it fails to find lpeg because it's still looking in the system libraries `/opt/homebrew/lib/lua/5.4`.

Based on that, I checked and found that only `LUA_CPATH` is the problem. If you unset that, but leave `LUA_PATH` set, there's no issue.

The issue is occuring in LuaHelpers.cmake line 7. I can reproduce on the command line with
```
❯ echo $LUA_CPATH
/opt/homebrew/lib/lua/5.4/?.so;/opt/homebrew/lib/lua/5.4/loadall.so;./?.so;/Users/seth/.luarocks/lib/lua/5.4/?.so

❯ .deps/usr/bin/luajit -l "lpeg" -e ""
.deps/usr/bin/luajit: error loading module 'lpeg' from file '/opt/homebrew/lib/lua/5.4/lpeg.so':
	dlopen(/opt/homebrew/lib/lua/5.4/lpeg.so, 0x0006): symbol not found in flat namespace '_luaL_checkversion_'
stack traceback:
	[C]: at 0x01008c7530
	[C]: at 0x01008c7944
	[C]: at 0x010085f640

❯ unset LUA_CPATH

❯ .deps/usr/bin/luajit -l "lpeg" -e ""
[... success ...]
```

**Comment by swarn** [comment] 2023-03-08 23:42
As far as I can tell, this is all expected behavior. If you have a system install of luarocks, and you set `LUA_PATH`/`LUA_CPATH` based on the output of `luarocks path`, then _any_ lua binary will search only those paths.

I think, if the nvim build process wants to guarantee use of the bundled deps, then it has to set `LUA_CPATH`. If it wants to allow the use of non-bundled lua installs by setting environment variables, then users like me have to make sure that, if we have set environment variables, they point at compatible lua installs, or that we unset them before building.

I'm happy to run any other checks you can think of!

**Comment by dundargoc** [comment] 2023-03-09 22:11
lua is a disaster

**Comment by dundargoc** [comment] 2023-03-09 22:28
I have no idea how to solve this. Unsetting `LUA_CPATH` at the start of the cmake script still doesn't fix this scenario. I don't think lua/luajit/luarocks have the tools to handle this properly.

**Comment by swarn** [comment] 2023-03-10 15:28
You probably know this, but in case it's useful:

Using `set()` on env variables in cmake only sets those variables for the cmake process itself. You have  to use `cmake -E env` if you want to control the environment of tools that it calls. I've tripped on this one in the past.

You can use the `-E` flag to make `luajit` ignore environment variables:
```
❯ LUA_CPATH="/foo"

❯ .deps/usr/bin/luajit -l "lpeg" -e ""
[... error ...]

❯ .deps/usr/bin/luajit -E -l "lpeg" -e ""
[... success ...]
```

**Comment by dundargoc** [comment] 2023-03-10 16:35
Hmm, I tried that without success before, but I didn't do it thoroughly so I may have missed something. Still, thanks for the mention.

**Comment by jcabrerard** [comment] 2023-03-13 19:14
I resolved this after building the dependencies as described in https://github.com/neovim/neovim/wiki/Building-Neovim#third-party-dependencies

**Comment by luukvbaal** [comment] 2023-03-22 13:38
I'm getting a similar error when trying to build on windows with visual studio (first time building with MSVC in a freshly cloned repo):
```
1> [CMake] C:/Users/Luuk/source/repos/neovim/build/.deps/usr/bin/luajit.exe: module 'lpeg' not found:
1> [CMake] 	no field package.preload['lpeg']
1> [CMake] 	no file '.\lpeg.lua'
1> [CMake] 	no file 'C:\Users\Luuk\source\repos\neovim\build\.deps\usr\bin\lua\lpeg.lua'
1> [CMake] 	no file 'C:\Users\Luuk\source\repos\neovim\build\.deps\usr\bin\lua\lpeg\init.lua'
1> [CMake] 	no file '.\lpeg.dll'
1> [CMake] 	no file 'C:\Users\Luuk\source\repos\neovim\build\.deps\usr\bin\lpeg.dll'
1> [CMake] 	no file 'C:\Users\Luuk\source\repos\neovim\build\.deps\usr\bin\loadall.dll'
1> [CMake] stack traceback:
1> [CMake] 	[C]: at 0x7ff92ae59cf0
1> [CMake] 	[C]: at 0x7ff6cccc4830
1> [CMake] -- [C:/Users/Luuk/source/repos/neovim/build/.deps/usr/bin/luajit.exe] The 'lpeg' lua package is required for building Neovim
1> [CMake] CMake Error at C:\Users\Luuk\Source\Repos\neovim\CMakeLists.txt:187 (message):
1> [CMake]   Failed to find a Lua 5.1-compatible interpreter
```

It seems to originate here:
```
1> [CMake] [158/164] Generating usr/lib/luarocks/rocks-5.1/mpack
1> [CMake] FAILED: usr/lib/luarocks/rocks-5.1/mpack C:/Users/Luuk/source/repos/neovim/build/.deps/usr/lib/luarocks/rocks-5.1/mpack 
1> [CMake] cmd.exe /C "cd /D C:\Users\Luuk\source\repos\neovim\build\.deps && C:\Users\Luuk\source\repos\neovim\build\.deps\usr\luarocks\luarocks.bat build mpack 1.0.10-0"
1> [CMake] 'C:/Program' is not recognized as an internal or external command,
1> [CMake] operable program or batch file.
1> [CMake] 
1> [CMake] Error: Build error: Failed compiling object lmpack.obj
```

**Comment by dundargoc** [comment] 2023-03-22 14:10
@luukvbaal did you try running the cmake.deps/CMakeLists.txt first?

**Comment by jcabrerard** [comment] 2023-03-22 14:22
If you're running into issues related to lpeg.lua not found:
https://github.com/neovim/neovim/wiki/Building-Neovim#third-party-dependencies
...
To build the bundled dependencies using CMake:

mkdir .deps
cd .deps
cmake ../cmake.deps
make
By default the libraries and headers are placed in .deps/usr. Now you can build Neovim:

mkdir build
cd build
cmake ..
make

**Comment by dundargoc** [comment] 2023-03-27 05:42
@swarn lua 5.2 and later allows to setting versions specific lua paths with e.g. `LUA_PATH_5_4`. Can you try and see if that route works for you?

See also https://github.com/luarocks/luarocks/issues/1216#issuecomment-673249006

**Comment by swarn** [comment] 2023-03-27 15:15
I'm not sure what you're asking. Do you want me to unset `LUA_PATH`, then set `LUA_PATH_5_4`?

Let me emphasize that I'm happy to help, but this is not an ongoing issue for me. I am good with using `unset LUA_PATH && unset LUA_CPATH` before building neovim.

The bundled luajit binary reads the `LUA_*` environment variables during the build process. That's **not** macOS-specific, and it's not a Lua5.1 vs Lua5.4 thing. You can replicate it with a vanilla Ubuntu install:
```
$ sudo apt install build-essential gettext cmake git luarocks
$ eval "$(luarocks path)"
$ echo $LUA_PATH
./?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/lib/lua/5.1/?.lua;/usr/local/lib/lua/5.1/?/init.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;/home/test/.luarocks/share/lua/5.1/?.lua;/home/test/.luarocks/share/lua/5.1/?/init.lua
$ git clone https://github.com/neovim/neovim.git
$ cd neovim
$ make

[... cut ...]

-- Checking Lua interpreter: /home/test/neovim/.deps/usr/bin/luajit
/home/test/neovim/.deps/usr/bin/luajit: module 'lpeg' not found:
	no field package.preload['lpeg']
	no file './lpeg.lua'
	no file '/usr/local/share/lua/5.1/lpeg.lua'
	no file '/usr/local/share/lua/5.1/lpeg/init.lua'
	no file '/usr/local/lib/lua/5.1/lpeg.lua'
	no file '/usr/local/lib/lua/5.1/lpeg/init.lua'
	no file '/usr/share/lua/5.1/lpeg.lua'
	no file '/usr/share/lua/5.1/lpeg/init.lua'
	no file '/home/test/.luarocks/share/lua/5.1/lpeg.lua'
	no file '/home/test/.luarocks/share/lua/5.1/lpeg/init.lua'
	no file './lpeg.so'
	no file '/usr/local/lib/lua/5.1/lpeg.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lpeg.so'
	no file '/usr/lib/lua/5.1/lpeg.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/test/.luarocks/lib/lua/5.1/lpeg.so'
stack traceback:
	[C]: at 0x55cdd12d5910
	[C]: at 0x55cdd1281350
-- [/home/test/neovim/.deps/usr/bin/luajit] The 'lpeg' lua package is required for building Neovim

[... cut ...]

CMake Error at CMakeLists.txt:187 (message):
  Failed to find a Lua 5.1-compatible interpreter
```
That's the same error I get if I don't unset the `LUA_*` variables. During this check for a compatible interpreter, the _bundled_ luajit is invoked, but it's checking the _system_ Lua paths for the "lpeg" module and not finding it.

Line 168 in `CMakeLists.txt` is checking all found lua interpreters, _including_ the bundled `luajit`.  To see if they have the right libraries installed, it calls `check_lua_deps` in `cmake/LuaHelpers.cmake`, which respects the `LUA_*` varaibles. Is your intended behavior that the luajit in the bundled deps (and _only_ that lua binary, not any other discovered lua interpreter) should ignore environment variables in favor of the modules installed in deps? If so, then I think you need to special-case the bundled luajit during this search.

**Comment by swarn** [comment] 2023-05-07 17:12
I haven't bisected to find the specific commit, but one of them before 1cbfed0 fixed this issue for my setup. That is, I have `LUA_PATH` and `LUA_CPATH` variables, and they are pointing to a lua without `lpeg` and other required modules, but now I don't have to unset those variables before using `make` to build neovim. Props to @dundargoc!

**Comment by dundargoc** [comment] 2023-05-07 20:02
I forgot about this. Yeah, this is likely solved by https://github.com/neovim/neovim/pull/23216. I'm gonna go ahead and close this then.

**Closed by dundargoc** 2023-05-07 20:02 UTC
Labels: bug, build, documentation, lua
