### ISSUE TITLE
`nvim_cmd` does not fail when arguments are passed improperly

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#24127] opened 2023-06-23 02:15 UTC
### Problem

When `nvim_cmd` is used incorrectly by having an argument be passed in the `cmd` string, it returns the empty string instead of failing.

### Steps to reproduce

```lua
vim.api.nvim_cmd({ cmd = "echo", args={"'hi'"} }, { output = true }) -- succeeds and returns "hi"
vim.api.nvim_cmd({ cmd = "echo 'hi'" }, { output = true }) -- succeeds and returns the empty string
vim.api.nvim_cmd({ cmd = "echoz 'hi'" }, { output = true }) -- fails because echoz is not defined
```

### Expected behavior

Improper usage should fail.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

N/A

**Comment by zeertzjq** [comment] 2023-06-23 02:36
Duplicate of #20681

**Closed by zeertzjq** 2023-06-23 02:36 UTC
Labels: bug, api

**Comment by justinmk** [comment] 2023-06-23 09:12
For the case of `{ cmd = "echo 'hi'" }` at least, we could disallow whitespace and other special chars in the command name passed to `nvim_cmd`. That would mitigate a lot, but doesn't help https://github.com/neovim/neovim/issues/20681 where an underscore is treated as the start of "arguments".

**Comment by justinmk** [comment] 2023-06-27 22:55
https://github.com/neovim/neovim/pull/24181
