### ISSUE TITLE
Support OSC 52 remote copy in terminal buffer

### ISSUE THREAD

**Issue by tristone13th** [neovim/neovim#20672] opened 2022-10-15 12:16 UTC
### Feature description

OSC52 can let us copy text from a remote (e.g., ssh) machine to the local terminal (e.g., Windows Terminal), however, the terminal buffer in Neovim seems didn't support this feature. The behavior this issue wants to accomplish is to allow us to copy some text in the Neovim terminal, such as by executing the command like `printf "\E]52;c;%s\a"` in the terminal, and the result is copied to local.

**Comment by zeertzjq** [comment] 2022-10-15 12:28
Duplicate of #3344

**Comment by justinmk** [comment] 2024-05-03 11:18
OSC/DCS are now forwarded to the `TermRequest` autocmd event. However I think we don't have a default handler for `:terminal`.

We have a default handler for bg color: https://github.com/neovim/neovim/blob/cf9f002f31c8b4d9d42912a3f45f5d3db4462fd9/runtime/lua/vim/_defaults.lua#L256-L258

**Comment by farnoy** [comment] 2024-05-06 19:25
I'm using nvim `v0.10.0-dev-b5583ac` over SSH, from a Windows 11 & alacritty client, and while `:=require('vim.ui.clipboard.osc52').copy('+')({'asd', 'fasd'})` works fine to copy to system clipboard on the client, setting `vim.g.clipboard` as in [the docs](https://neovim.io/doc/user/provider.html#clipboard-osc52) doesn't actually work with something like `"+yy`. Is this a known issue, or should I create a new one for it?

**Comment by justinmk** [comment] 2024-05-06 20:05
> setting `vim.g.clipboard` as in [the docs](https://neovim.io/doc/user/provider.html#clipboard-osc52) doesn't actually work with something like `"+yy`. Is this a known issue, or should I create a new one for it?

not a known issue, yes please create one. is there an alternative config that works ?

**Comment by gpanders** [comment] 2024-05-06 20:39
Can you share exact reproduction steps? Setting `vim.g.clipboard` is exactly what Nvim itself is doing so we know that it _should_ work: https://github.com/neovim/neovim/blob/bb032d952bfc692062fceb764ff2742c5bdd3324/runtime/plugin/osc52.lua#L31-L43

**Comment by farnoy** [comment] 2024-05-06 21:44
Weird, I created a minimal repro, then it proceeded to alternate between working and not, in a non-deterministic way. Seems like a problem elsewhere with my systems and not with nvim. I'll experiment with a Linux client too to isolate the fault.

My repro and what I'm doing in my normal config is this:

```lua
-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE

vim.g.clipboard = {
  name = 'OSC 52',
  copy = {
    ['+'] = require('vim.ui.clipboard.osc52').copy('+'),
    ['*'] = require('vim.ui.clipboard.osc52').copy('*'),
  },
  paste = {
    ['+'] = require('vim.ui.clipboard.osc52').paste('+'),
    ['*'] = require('vim.ui.clipboard.osc52').paste('*'),
  },
}

vim.opt.clipboard:append 'unnamedplus'
```

**Comment by gpanders** [comment] 2024-06-01 12:14
https://github.com/neovim/neovim/pull/29117

**Closed** 2024-06-11 18:18 UTC
Labels: enhancement, clipboard, terminal, complexity:low, events
