### ISSUE TITLE
Issue with build-in omnifunc, a:base is 0.

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#7471] opened 2017-11-01 09:01 UTC
with this vim func 

```vim
func Omni(findstart, base)
    if a:findstart
        return 5
    else
        echom a:base
        return []
    endif
endf
```

reproduce step:

1. vim test.vim
2. `:so %`
3. set omni=Omni
4. normal `Gofind -<C-x><C-o>`
5. `:message` then you will see `0`, I think the a:base should be `-` instead. 

**NOTE** this issue can also be reproduced in vim8

**Comment by justinmk** [comment] 2017-11-01 19:14
Doesn't it depend on 'iskeyword' ?

**Comment by wsdjeg** [comment] 2017-11-01 23:42
I do not see it in help. it just show me a:base is the string from the pos to cursor poit. and the pos is the value omni-func returned.

**Comment by justinmk** [comment] 2017-11-02 09:57
If it doesn't use 'iskeyword', what do you expect? Only whitespace? That would be unusual.

**Comment by wsdjeg** [comment] 2017-11-02 10:38
I think the a:base should be `-`. but why it is 0？

**Comment by wsdjeg** [comment] 2017-11-02 10:44
please test  with

```vim
func Omni(findstart, base) 
     if a:findstart 
         return 5 
     else 
         echom a:base 
      return ['-help', '-v'] 
    endif 
endf
```

**Comment by chrisbra** [comment] 2017-11-02 11:07
sounds like a similar problem I fixed in Vim recently https://github.com/vim/vim/releases/tag/v8.0.1231
The cause is, that `vim_str2nr` is called on a string that starts with `-`. vim_str2nr assumes a negative number and since no number follows, it returns 0. So something like this patch is needed (patch is for Vim):
```patch
diff --git a/src/eval.c b/src/eval.c
index e8a1b0aa3..f45d54be1 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -1056,8 +1056,13 @@ call_vim_function(
        if (str_arg_only)
            len = 0;
        else
+       {
            /* Recognize a number argument, the others must be strings. */
            vim_str2nr(argv[i], NULL, &len, STR2NR_ALL, &n, NULL, 0);
+           if (len==1 && *argv[i] == '-')
+               /* no number, only '-' */
+               len = 0;
+       }
        if (len != 0 && len == (int)STRLEN(argv[i]))
        {
            argvars[i].v_type = VAR_NUMBER;
```
CC @brammool

**Comment by wsdjeg** [comment] 2017-11-02 12:14
Thanks for your information, @chrisbra

**Comment by brammool** [comment] 2017-11-02 14:44
Christian Brabandt wrote:

> sounds like a similar problem I fixed in Vim recently https://github.com/vim/vim/releases/tag/v8.0.1231
> The cause is, that `vim_str2nr` is called on a string that starts with `-`. vim_str2nr assumes a negative number and since no number follows, it returns 0. So something like this patch is needed (patch is for Vim):
> ```patch
> diff --git a/src/eval.c b/src/eval.c
> index e8a1b0aa3..f45d54be1 100644
> --- a/src/eval.c
> +++ b/src/eval.c
> @@ -1056,8 +1056,13 @@ call_vim_function(
>         if (str_arg_only)
>             len = 0;
>         else
> +       {
>             /* Recognize a number argument, the others must be strings. */
>             vim_str2nr(argv[i], NULL, &len, STR2NR_ALL, &n, NULL, 0);
> +           if (len==1 && *argv[i] == '-')
> +               /* no number, only '-' */
> +               len = 0;
> +       }
>         if (len != 0 && len == (int)STRLEN(argv[i]))
>         {
>             argvars[i].v_type = VAR_NUMBER;
> ```
> CC @brammool

Thanks, I'll also add a test from the example.

-- 
BRIDGEKEEPER: What is your favorite colour?
GAWAIN:       Blue ...  No yelloooooww!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment] 2017-11-02 14:49
relevant vim patch https://github.com/vim/vim/releases/tag/v8.0.1242

**Comment by glacambre** [comment] 2021-06-05 16:19
Can't reproduce on master, so the Vim patch most probably has been ported. Closing this issue :).

**Closed by glacambre** 2021-06-05 16:19 UTC
Labels: 0.kind: bug-vim, help wanted
