### ISSUE TITLE
Assertion failed (tui_raw_line)

### ISSUE THREAD

**Issue by imjasonmiller** [neovim/neovim#11019] opened 2019-09-14 13:27 UTC
- `nvim --version`: v0.4.0-2066-g3855204f5
- `vim` (version: `8.1`) behaves differently? Yes
- Operating system/version: Arch Linux x64
- Terminal name/version: [alacritty 0.3.3](https://github.com/jwilm/alacritty/tree/v0.3.3)
- `$TERM`: xterm-256color

### Steps to reproduce

Adding auto-paired braces (`{} () []`) after the `if` condition in `crash.ts`, pressing return, causes `nvim` to crash with the following error:
```
home/travis/build/neovim/bot-ci/build/neovim/src/nvim/tui/tui.c:1291: tui_raw_line: Assertion `(size_t)attrs[c-startcol] < kv_size(data->attrs)' failed.
```

This only seems to happen with the given amount of newlines in the file. Removing one causes it to somehow not crash.

I have removed all other plugins/settings from `init.vim` and `.vimrc` and found that the `auto-pairs` plugin seems to play a part, although it works fine in `vim`. 

#### Configuration
`~/.config/nvim/init.vim` with the latest [`jiangmiao/auto-pairs`](https://github.com/jiangmiao/auto-pairs/tree/39f06b873a8449af8ff6a3eee716d3da14d63a76). The plugin manager is [`vim-plug`](https://github.com/junegunn/vim-plug).
```vim
call plug#begin('~/.local/share/nvim/plugged')

Plug 'jiangmiao/auto-pairs'

call plug#end()
```
#### A copy of the file that causes the crash
```
curl https://gist.githubusercontent.com/imjasonmiller/37acdfca914458739b866d7725f279d0/raw/23b7c3b045ae2c885e9fa2b03245b7efa49b49c5/nvim-crash.ts -o crash.ts
```

### Actual behaviour
![crash-nvim](https://user-images.githubusercontent.com/12190184/64908507-6a4ed080-d701-11e9-9528-7ba3dd30f642.gif)

I had to remove a lot of code, but this seems to be the minimum working example that causes the crash on my system.

### Expected behaviour
![crash-vim](https://user-images.githubusercontent.com/12190184/64908517-94a08e00-d701-11e9-8641-62393c77f798.gif)

As shown above, it surprisingly seems to work in `vim` with the exact same plugin.

**Comment by bfredl** [comment] 2019-09-14 13:39
Cannot reproduce. If the exact number of lines is important, then terminal size is probably also important. What does `:set lines columns` say?

**Comment by imjasonmiller** [comment] 2019-09-14 13:43
> What does :set lines columns say?

**nvim**
```vim
lines=28
columns=212
```
**vim**
```vim
lines=28
columns=212
```

**Comment by imjasonmiller** [comment] 2019-09-14 14:09
I managed to reproduce it in Windows Subsystem for Linux (same system) with the same version (v0.4.0-2066-g3855204f5)

![image](https://user-images.githubusercontent.com/12190184/64909217-8191bc00-d709-11e9-85f7-de982dfcb4fc.png)

**Comment by bfredl** [comment] 2019-09-15 08:51
Thanks, I can reproduce now.

**Comment by bfredl** [comment] 2019-09-15 11:07
The issue is as follows. The plugin or something is also centering the newly inserted line, so that the entire buffer is also scrolled up (topline increased). So before drawing any line, `win_update()` is performing two `grid_scroll` operations.

```
===
A
B
C
D
E^
F
===
```
Consider that new line will be inserted after line E and screen also scrolled up to line C. First the topline will be adjusted (`x` is the scrolling region, `!` invalid/empty space created by the scroll):
```
===
C   x
D   x
E^  x
F   x
!   x
!   x
===
```
and then space is inserted for the new line
```
===
C
D
E^
!   x
F   x
!   x
===
```

The problem is that we are now assuming that any invalid area `!` created by a scroll is filled with actual contents (by `win_line` etc) before it is scrolled again. But in this case the last invalid line `!` gets scrolled. Ideally we should make `win_update` smarter and just scroll valid lines for the later scroll (it is just wasteful to scroll the larger area anyway), but for now (for the 0.4 release) I will just make the compositor ignore such an invalid line (as it will get overdrawn anyway later).

**Comment by imjasonmiller** [comment] 2019-09-15 11:34
I am glad to hear that it is something that can possibly be solved in the future. I will disable the plugin for now.

Lastly, thank you very much for the in-depth and clear explanation on what caused it. If there is anything I can help with, do let me know.

**Comment by bfredl** [comment] 2019-09-15 11:54
@imjasonmiller you could try if https://github.com/neovim/neovim/pull/11025 fixes the issue for you

**Closed** 2019-09-15 14:53 UTC
Labels: bug

**Comment by imjasonmiller** [comment] 2019-09-16 13:43
I just checked out that commit and it did! I am impressed! Many thanks for looking into this @bfredl.
