### ISSUE TITLE
set winminheight throwing error on startup

### ISSUE THREAD

**Issue by ricka** [neovim/neovim#2132] opened 2015-03-11 19:38 UTC
I cleared out my .nvimrc to make sure no plugins or anything else were causing this, as well as pulling the latest neovim via the brew instructions.  My .nvimrc is as follows:

```
set winheight=30
set winminheight=5
```

and that produces `E36: Not enough room` on startup.

**Comment by Pyrohh** [comment] 2015-03-12 00:08
```
nvim -u NONE -c 'set winheight=30' -c 'set winminheight=5'
```
and
```
vim -N -u NONE -c 'set winheight=30' -c 'set winminheight=5'
```
give me the same results.

Are you sure this is a bug? `:h winminheight` shows this at the bottom:
```
    ...

	This option is only checked when making a window smaller.  Don't use a
	large number, it will cause errors when opening more than a few
	windows.  A value of 0 to 3 is reasonable.

```

**Comment by justinmk** [comment] 2015-03-12 00:15
How many lines are available in your terminal window? 30 lines takes up more than half of a typical screen.

**Comment by ricka** [comment] 2015-03-12 00:33
Vim 7.4.258 did not throw an error with this config.  If newer versions of vim are throwing this error I apologize, but I expected that config to work since I've been using it for some time.

My terminal window has 59 lines.

I've just now tested and found I can use `set winheight=22` and not incur the error on startup.

**Comment by Pyrohh** [comment] 2015-03-12 00:35
Sorry, I had neglected to mention that I was using vim `7.4.617`.

**Comment by justinmk** [comment] 2015-03-12 00:36
Let's see what vim_dev has to say about it...

**Comment by ajiyakin** [comment] 2016-03-02 14:23
I have same issue here. I finally remove `set winminheight` and `set winminwidth`. I don't know what happen but this approach fix my problem. I leave `set winwidth` and `set winheight` in my `init.vim` configuration. Here is part of my `init.vim` configurations:

```
...
set winwidth=85
set winheight=30
" set winminwidth=0
" set winminheight=0
...

**Comment by wsdjeg** [comment] 2016-03-02 14:45
when full screen,the terminal max line number is 41, but the max number of winheight I can set is 34,when I set to 35,also get this errror

**Comment by glacambre** [comment] 2021-06-05 05:56
I can't reproduce this problem on master+kitty, so I'm going to close this issue. @ricka let me know if you can still reproduce this bug and I'll re-open :)

**Closed by glacambre** 2021-06-05 05:56 UTC
Labels: 0.kind: bug-vim

**Comment by ricka** [comment] 2021-06-06 16:46
@glacambre Looks fixed in both vim and neovim. Not sure when this happened, but thanks for the follow up!
