### ISSUE TITLE
CursorLine highlighting broken in diff without ctermfg

### ISSUE THREAD

**Issue by cprn** [neovim/neovim#16295] opened 2021-11-12 03:14 UTC
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

no, vim 8.2.344

### Operating system/version

Linux, 5.10.70-1-MANJARO

### Terminal name/version

urxvt, 9.22

### $TERM environment variable

screen-256color

### Installation

Arch User Repository (AUR)

### How to reproduce the issue

```sh
nvim --clean -d \
    +"windo set cul nu" \
    +"hi CursorLine term=none cterm=none ctermbg=blue" \
    <(echo -e "lorem\nipsum\ndolor sit\namet\n\n") \
    <(echo -e "lorem\nipsum\ndolor sores\nerratum\n\n")
```
1. notice how line `1` has background and no underline
1. go to line `3` or `4`
1. notice extra underline and ignored background setting
1. `:set nocul`
1. notice disabling cursor line hides underline in the left window
1. `:hi CursorLine ctermfg=white`
1. notice no underline and proper background in the right window (but no diff highlighting)
1. `:hi CursorLine ctermfg=none`
1. notice how cursor line in the right window is broken again (but diff is highlighted)

### Expected behavior

Cursor line in diff mode should adhere to `CursorLine` settings, i.e. have correct decorations and background even when foreground colour is not set (mind that difference between `sit` and `sores` in that line should be highlighted as well):
![2021-11-12-041341_455x246_scrot](https://user-images.githubusercontent.com/6132708/141402894-1c858139-0cb3-4e45-82d1-dd07699fd4fc.png)

### Actual behavior

Cursor line decorations and background colour settings overloaded when foreground colour is not set:
![2021-11-12-041354_455x246_scrot](https://user-images.githubusercontent.com/6132708/141402931-01498334-89d6-411c-a55d-59831462525d.png)

**Comment by zeertzjq** [comment] 2021-11-12 03:24
Well, I believe this is intentional?

**Comment by zeertzjq** [comment] 2021-11-12 03:28
Duplicate of #9800

**Closed by zeertzjq** 2021-11-12 03:28 UTC
Labels: bug, highlight
