### ISSUE TITLE
Trouble upgrading Neovim through Homebrew

### ISSUE THREAD

**Issue by retrone** [neovim/neovim#4491] opened 2016-03-23 20:28 UTC
Having trouble upgrading my previous Neovim to latest on Homebrew (0.1.2). A `brew upgrade` fails at the end - issue with doc/tags?

- Neovim version: 0.1.2
- Operating system: Mac OS 10.11.4 (latest command line tools and XCode)
- Terminal emulator: iTerm2 Build 2.9.20160206 and Zshell

### Actual behaviour
```
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/neovim/0.1.2
==> make VERBOSE=1 install
Last 15 lines from Library/Logs/Homebrew/neovim/04.make:
cd /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build && /usr/local/Cellar/cmake/3.5.0/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2 /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/runtime /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/runtime /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/runtime/CMakeFiles/runtime.dir/DependInfo.cmake --color=
Dependee "/tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/runtime/CMakeFiles/runtime.dir/DependInfo.cmake" is newer than depender "/tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/runtime/CMakeFiles/runtime.dir/depend.internal".
Dependee "/tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/runtime/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/runtime/CMakeFiles/runtime.dir/depend.internal".
Scanning dependencies of target runtime
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f runtime/CMakeFiles/runtime.dir/build.make runtime/CMakeFiles/runtime.dir/build
[ 96%] Generating syntax/vim/generated.vim
cd /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/runtime && ../../deps-build/usr/bin/luajit /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/scripts/genvimvim.lua /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/src/nvim /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/runtime/syntax/vim/generated.vim
[100%] Generating copy_docfiles
cd /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/runtime && /usr/local/Cellar/cmake/3.5.0/bin/cmake -E copy_directory /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/runtime/doc /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/runtime/doc
[100%] Generating doc/tags
cd /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/runtime/doc && /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/bin/nvim -u NONE -i NONE -es --headless -c helptags\ ++t\ . -c quit
/bin/sh: line 1: 65552 Abort trap: 6           /tmp/neovim20160323-40222-1yt1qkz/neovim-0.1.2/build/bin/nvim -u NONE -i NONE -es --headless -c helptags\ ++t\ . -c quit
make[2]: *** [runtime/doc/tags] Error 134
make[1]: *** [runtime/CMakeFiles/runtime.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by justinmk** [comment] 2016-03-23 21:26
Usually this happens because of https://github.com/neovim/neovim/issues/4183#issuecomment-180969619

Though I've not seen it on OSX.

**Comment by justinmk** [comment] 2016-03-23 21:27
Anyways, duplicate of https://github.com/neovim/neovim/issues/4485

**Closed by justinmk** 2016-03-23 21:27 UTC
