### ISSUE TITLE
Can't open multiple files in Windows using command line

### ISSUE THREAD

**Issue by comiluv** [neovim/neovim#15347] opened 2021-08-12 04:40 UTC
### Neovim Version

NVIM v0.6.0-dev+116-g35041432b

### Operating system/version:

Windows 10/21H1 build 19043.1110

### Terminal name/version:

Windows Terminal/1.9.1942.0

### TERM environment variable

blank

### Installation

chocolatey

### Steps to reproduce

1. Make multiple files in a directory (eg. a.txt, b.txt, c.txt, etc.)
2. ```nvim -u NORC *.txt``` 

### Vim

Vim can open all the *.txt files which can be checked using ```:ls```

### Expected behavior

Open every *.txt files in separate buffers

### Actual behavior

E303: Unable to open swap file for "*.txt", recovery impossible
Above is displayed and doesn't open any file.

**Comment by erw7** [comment] 2021-09-15 09:23
Unfortunately, this is not a bug, but a specification of neovim. See `:h vim-differences`.

Duplicate of #12089.

**Closed by erw7** 2021-09-15 09:23 UTC
Labels: bug, platform:windows
