### ISSUE TITLE
Viml Expression Parsing Assertion Fail From "Read Expression Register" Mode

### ISSUE THREAD

**Issue by jcorbin** [neovim/neovim#13832] opened 2021-01-26 19:45 UTC
- `nvim --version`:
```
NVIM v0.5.0-dev+1051-g4d1fc167a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/jcorbin/neovim/build/config -I/Users/jcorbin/neovim/src -I/Users/jcorbin/neovim/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/jcorbin/neovim/build/src/nvim/auto -I/Users/jcorbin/neovim/build/include
Compiled by jcorbin@anatta.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/jcorbin/.local/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: Mac Os 10.15.7
- Terminal name/version: kitty 0.18.3
- `TERM=xterm-kitty`

### Steps to reproduce using `nvim -u NORC`

Doing some quick maths from insert mode, with a stashed denominator, something like:
- populate register `d` with `/425.0`
- start out on a new line with number, like say `68`
- `^C<C-r>=<C-r>"<C-r>d` in other words:
  - correct until end of line 
  - read from expression register
  - read cut text we're correcting
  - read the stashed denominator

It doesn't always crash... in fact the crashes might correlate with fat fingering, or correcting typos, within the "read expr" command mode editor.

### Actual behaviour

Sometimes, but not always, crashes with an assertion fail:
```
Assertion failed: (bop_node_lvl != new_top_node_lvl || bop_node_ass == new_top_node_ass), function viml_pexpr_handle_bop, file ../src/nvim/viml/parser/expressions.c, line 1238.  
```

### Expected behaviour

Not to crash

**Comment by jamessan** [comment] 2021-01-26 20:28
Duplicate of #7889

**Closed by jamessan** 2021-01-26 20:28 UTC
Labels: bug
