### ISSUE TITLE
y/p multiple lines into a terminal buffer are joined together

### ISSUE THREAD

**Issue by svenXY** [neovim/neovim#13326] opened 2020-11-19 07:29 UTC
- `nvim --version`:

NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/config -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/include
Übersetzt von brew@Catalina

- `vim -u DEFAULTS` (version: ) behaves differently? has no terminal mode, thus: not applicable here
- Operating system/version: MacOS Catalina/10.15.7
- Terminal name/version: iterm2/3.4.1 (same happens in Terminal.app Version 2.10 (433))
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

* write some shell commands into a buffer, e.g.:
echo first line
echo second line
# some comment
echo third line

* make a visual selection of those lines and yank it
* change to the terminal buffer and press 'p'

Output:
$ echo first lineecho second line# some commentecho third line


```

### Actual behaviour
Terminal command line is populated with 
```
$ echo first lineecho second line# some commentecho third line
```

### Expected behaviour
Terminal command line is populated with 
```
echo first line
echo second line
# some comment
echo third line
```

**Comment by glacambre** [comment] 2020-11-19 08:14
I can't reproduce this on nvim v0.5+/bin/sh (symlinked to dash). I think your shell might be coalescing the lines as a way to prevent accidentally running pasted commands. You could either try using another shell, see if you can toggle this feature in your shell or use `:%!sh` instead of copy/pasting commands to a terminal instance.

**Comment by svenXY** [comment] 2020-11-19 08:22
the same happens with ordinary MacOS Terminal.app

**Comment by glacambre** [comment] 2020-11-19 10:29
I'm talking about shells, not terminals :). The shell is the thing that runs commands: dash, bash, zsh… The terminal is the thing that displays the shell and the commands' output: iterm2, terminal.app, neovim's terminal… If neovim is using zsh, try bash or plain /bin/sh (I think this should turn on posix sh compatibility and thus disable coalescing lines?).

**Comment by jamessan** [comment] 2020-11-19 12:14
Yeah, this is likely the shell supporting bracketed paste mode.

**Comment by svenXY** [comment] 2020-11-20 15:07
it is zsh

**Comment by glacambre** [comment] 2020-11-20 16:52
Running `unset zle_bracketed_paste` in zsh before pasting should fix this problem then :)

**Comment by svenXY** [comment] 2020-11-23 08:27
nope, unfortunately it doesn't, at least not with my zgen/oh-my-zsh setup. When starting another subshell with `zsh -f` within the neovim terminal, it works as expected.

**Comment by glacambre** [comment] 2020-11-23 13:14
I would recommend asking for help on zsh's support channels then (it has an IRC channel and a mailing list) :)

**Comment by glacambre** [comment] 2021-06-09 06:43
Closing as this is not a neovim issue but a zsh one :).

**Closed by glacambre** 2021-06-09 06:43 UTC
Labels: bug
