### ISSUE TITLE
CI: nightly release sometimes fails to upload

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#15709] opened 2021-09-18 13:26 UTC
## Note

- If the nightly release failed, you can download the Artifacts from https://github.com/neovim/neovim/actions/workflows/release.yml
    - Click on the latest build (even if it failed), then scroll to the "Artifacts" section.

## Problem

> Neovim occasionally fails to publish nightly releases: https://github.com/neovim/neovim/actions/workflows/release.yml
>
> example: https://github.com/neovim/neovim/runs/3530275099?check_suite_focus=true 

```
Upload Assets
Files to be uploaded to Github:
  nvim-linux64.tar.gz
  nvim-linux64.tar.gz.sha256sum
  nvim-macos.tar.gz
  ...
  {
    "message": "Not Found",
    "documentation_url": "https://docs.github.com/rest/reference/repos#delete-a-release-asset"
  }
  ...
  curl: (56) OpenSSL SSL_read: Connection reset by peer
```

Looks like an imperfection with https://github.com/meeDamian/github-release ? Maybe the retry logic?

upstream issue: https://github.com/meeDamian/github-release/issues/27

**Comment by clason** [comment] 2021-09-18 13:29
For the record (and anyone stumbling across this): in almost every case, it's the "publish" step that fails; the binaries are all built correctly. You can then always download them directly from https://github.com/neovim/neovim/actions/workflows/release.yml (click on the latest `Release` -- even if it's marked as failed -- and scroll down to the "Artifacts").

**Comment by ray-x** [comment] 2021-09-22 07:55
It also affect Appimage

https://github.com/neovim/neovim/runs/3671413821?check_suite_focus=true#step:5:1742

```
-- Deploying files into AppDir root directory -- 
Deploying files to AppDir root using desktop file: nvim.AppDir/usr/share/applications/nvim.desktop 
Deploying desktop file to AppDir root: nvim.AppDir/usr/share/applications/nvim.desktop 
Creating symlink for file nvim.AppDir/usr/share/applications/nvim.desktop in/as nvim.AppDir 
Deploying icon to AppDir root: nvim.AppDir/usr/share/icons/hicolor/128x128/apps/nvim.png 
Creating symlink for file nvim.AppDir/usr/share/icons/hicolor/128x128/apps/nvim.png in/as nvim.AppDir 
ERROR: Could not find suitable executable for Exec entry: nvim 
mv: cannot stat '/home/runner/work/neovim/neovim/build/nvim.appimage*': No such file or directory
genappimage.sh: finished

```

**Comment by nyuszika7h** [comment] 2021-09-25 12:18
This breaks https://nightly.link/ sometimes, because it always gets the latest successful build, which is from 2 days ago and somehow already expired?

**Comment by yashamon** [comment] 2021-09-25 21:18
Does this also affect nightly neovim snap? The edge snap right now is back to .5. It was at .6 a few days ago.

**Comment by rktjmp** [comment] 2021-10-06 12:06
Im trying to poke at this but it's hard to re-produce obviously. I do not believe the "failed to delete asset" is the cause of the bug, I have seen it regularly when working on the release workflow at other times and it's not been an issue.

From what I can tell looking at other issues, there may be an error being reported from GH, but without a proper SSL termination so the error doesn't get propagated?

Causes might be:

- malformed request somehow, though most of the content is pretty static besides some file names and sha's which shouldn't cause any obvious escape issues, etc.
  - Possibly the token is expiring or hitting a rate limit or just hitting an old node in some rolling internal update, again seems pretty unlikely.
  - Fix? Probably getting an actual error to read.
- CA cert issues
  - Dockerfile uses alpine 3.11, latest is 3.14 
  - alpine 3.11 uses 20191127-r2, the latest upstream is 20191127-**r6**, which is also flagged as [out of date](https://pkgs.alpinelinux.org/package/edge/main/x86/ca-certificates). 
  - I previously saw similar issues in workflows and had to manually force installing `ca-certificates`, but that was on deb/ubuntu and I can't say if it's the real issue yet. Failures might be dependent on what gateway/endpoint you get pushed through internally.
  - Fix? Bumping alpine version? Using debian image? The action doesn't really what platform its on, it just needs curl and jq.
- GH Issue?
  - It could just be that some internal servers aren't configured correctly, have some bug, whatever.

I am running the workflow with more verbosity on my fork but so far no luck in failing, so it's a bit of a waiting game.

**Comment by jamessan** [comment] 2021-10-06 12:24
FWIW, I'm planning on reimplementing this workflow to not rely on the third-party action, so we have more control over what happens.

**Comment by rktjmp** [comment] 2021-10-06 12:36
I did wonder about that since what we do isn't that complicated.

**Comment by rktjmp** [comment] 2021-10-18 00:29
Perhaps we can invert the problem.

Create a release "next-nightly", _if it succeeds_, add a step after it that deletes "nightly" and retags "next-nightly" &rarr; "nightly". (assuming you can retag/double-tag releases, rtm pending).

That would leave you with an always complete nightly, if potentially out of date (maybe 3-4 days max looking at the workflow history). (Assuming we can convince GH to accept one to start the chain! :godmode:)

Best solution? I will look into how feasible that is.

---

> Should be fine, since the old assets from the previous day will be there?

The current workflow clobbers previous nightlys before creating the new one. The other option is retagging the last nightly to "last-nightly" so it hangs around, but eventually that would be incomplete (night on night).

We can link people to https://github.com/neovim/neovim/actions/workflows/release.yml and tell them to poke around for a workflow containing their asset, not great though.

**Comment by justinmk** [comment] 2021-10-18 00:41
> We can link people to https://github.com/neovim/neovim/actions/workflows/release.yml and tell them to poke around for a workflow containing their asset, not great though.

Yeah but as long as nightly succeeds 65% of the time , it's ok. We should first do whatever stops the bleeding with minimal investment. Then see if we want to invest more later.

**Closed** 2021-10-30 20:07 UTC
Labels: distribution, ci

**Comment by ram02z** [comment] 2021-11-02 08:29
The nightly tag no longer points to the nightly git version. It has pointed to e921e98ce38a33a824a8b4efb376a9901a8191d7 for the last two days.

**Comment by zeertzjq** [comment] 2021-11-02 09:07
> The nightly tag no longer points to the nightly git version. It has pointed to [e921e98](https://github.com/neovim/neovim/commit/e921e98ce38a33a824a8b4efb376a9901a8191d7) for the last two days.

cc @jamessan

**Comment by jamessan** [comment] 2021-11-02 12:04
> > The nightly tag no longer points to the nightly git version. It has pointed to [e921e98](https://github.com/neovim/neovim/commit/e921e98ce38a33a824a8b4efb376a9901a8191d7) for the last two days.
> 
> cc @jamessan 

Fixed
