### ISSUE TITLE
TUI: rxvt with transparent background sends unexpected response

### ISSUE THREAD

**Issue by eichboson** [neovim/neovim#9991] opened 2019-05-09 16:05 UTC
- `nvim --version`:
```
NVIM v0.4.0-736-gbc395b4fd
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-par
ameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fal
lthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GE
NERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home
/lasse/neovim/build/config -I/home/lasse/neovim/src -I/home/lasse/neovim/.deps/usr/include -I/u
sr/include -I/home/lasse/neovim/build/src/nvim/auto -I/home/lasse/neovim/build/include
Compiled by lasse@lasse-pc

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```
- Vim (version: ) behaves differently?
bug is not happening, behaves normal
- Operating system/version:
Manjaro Linux
- Terminal name/version:
urxvt 9.22-7
- `$TERM`:
rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`

open .Xresources and edit urxvt background color to transparent (in angular brackets e.g. 50)
`URxvt.background:                 [50]#222D31`
```
xrdb .Xresources
urxvt
```
switch to newly opened urxvt terminal
```
nvim -u NORC
```

### Actual behaviour
nvim starts with an nonempty buffer, following is automatically inserted
`:21ff/2cff/30ff/800021ff/2cff/30ff/8000`

tested it in xterm and it didn't happen there

the same issue existed already some time ago i and was fixed shortly after in https://github.com/vim/vim/commit/46fd4df719b1c3f3d84474c71da8b10e17601ffc
https://bbs.archlinux.org/viewtopic.php?id=199362

### Expected behaviour
should open an empty buffer

**Comment by justinmk** [comment] 2019-05-09 17:08
vim patch 7.4.757: https://groups.google.com/forum/#!topic/vim_dev/LLGjKaEzNUY

> Problem:    Cannot detect the background color of a terminal. 

And you say:

> was fixed shortly after in patch 7.4.778

https://github.com/vim/vim/commit/ae2fe73abc954b8fd3dbd7994daa8e31e6690bd0

I don't see how they're related. 

My only guess is maybe https://github.com/neovim/neovim/pull/9509 is related. You could try [removing this line](https://github.com/justinmk/neovim/blob/d3dc94615523a71606edcbe6bf528f8b49a78c7d/src/nvim/tui/tui.c#L287).

**Comment by justinmk** [comment] 2019-05-09 17:12
Actually https://github.com/vim/vim/commit/46fd4df719b1c3f3d84474c71da8b10e17601ffc is the relevant Vim fix/patch.

**Comment by justinmk** [comment] 2019-05-09 17:15
If anyone wants to work on this, most likely [handle_background_color()](https://github.com/justinmk/neovim/blob/d3dc94615523a71606edcbe6bf528f8b49a78c7d/src/nvim/tui/input.c#L382) needs to be adjusted. Vim patch https://github.com/vim/vim/commit/46fd4df719b1c3f3d84474c71da8b10e17601ffc may provide a clue.

**Comment by eichboson** [comment] 2019-05-09 18:20
> My only guess is maybe #9509 is related. You could try [removing this line](https://github.com/justinmk/neovim/blob/d3dc94615523a71606edcbe6bf528f8b49a78c7d/src/nvim/tui/tui.c#L287).

I tried it and it works

**Comment by blueyed** [comment] 2019-09-20 19:03
@eichboson 
Could not reproduce it.

What do you see with `printf '\e]11;?\007'; read` (in a terminal)?
I get `^[]11;rgb:0000/2b2b/3636^G` normally, and `^[]11;rgba:feff/0000/0000/8000^G` with `URxvt.background:	[50]#ff0000` in xrdb.

"rgba:" prefix is handled since 424ddd01f.  So maybe it is fixed in 0.4.2 already after all?

**Comment by eichboson** [comment] 2019-09-23 12:44
@blueyed 
I get the same result like you with `printf '\e]11;?\007'; read` and I also don't get any weird sequences anymore.

**Comment by blueyed** [comment] 2019-09-23 13:34
@eichboson 
Great, thanks for the update.  Closing as fixed then.

**Closed by blueyed** 2019-09-23 13:34 UTC
Labels: +plan, bug, complexity:low, help wanted, tui
