### ISSUE TITLE
High CPU usage when vim.schedule inside statusline

### ISSUE THREAD

**Issue by kuznetsss** [neovim/neovim#17937] opened 2022-03-31 14:56 UTC
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

vim doesn't support lua

### Operating system/version

Arch linux

### Terminal name/version

alacritty 0.10.0-dev (f90dd12e)

### $TERM environment variable

xterm-256color

### Installation

System package manager

### How to reproduce the issue

Create file `example.lua` with config:
```lua
local line = nil
function _G.make_statusline()
    vim.schedule(function()
        line = 'some status line'
    end)
    return line
end
vim.cmd([[autocmd BufWinEnter,WinEnter * setlocal statusline=%!v:lua.make_statusline()]])
```
Run nvim with the config:
```bash
$ nvim -u example.lua
```

### Expected behavior

Almost zero CPU usage.

### Actual behavior

Got 100% of one CPU core usage.

**Comment by zeertzjq** [comment] 2022-03-31 15:00
Duplicate of #14303

**Comment by lewis6991** [comment] 2022-04-06 11:11
@zeertzjq, can you explain why you have marked this as a duplicate? The other issue is related to timers?

**Comment by zeertzjq** [comment] 2022-04-06 11:12
Both are `K_EVENT` key cause a redraw of statusline.

**Comment by lewis6991** [comment] 2022-04-06 11:16
Ok, thanks for clarifying. That wasn't clear.

What about the 100% CPU usage? The other issue just had the statusline update every 200ms. This issue seems a lot more severe.

**Comment by zeertzjq** [comment] 2022-04-06 11:18
I'll reopen this then.

**Comment by folke** [comment] 2022-10-28 06:47
Same issue when using Noice. We have a timer to update the UI, which trigger galaxyline redraws too frequently spiking CPU. Lualine doesn't have this problem, since they probably throttle statusline updates.

**Comment by msva** [comment] 2023-01-16 21:51
Hi there!

Can I ping someone with powerful anough C-foo and NVim code knowledge level ehough, to dig in this problem, as it makes NVim usage behaviour very annoying when using plugins like https://github.com/folke/noice.nvim or  even `nvim-notify`.
Using both of them makes nvim eat significant amount of CPU time (and even adds glitches because of constant redrawing) :cry:.

Unfortunately, my C-foo is not enough to handle such issues, so I can't make a PRs with fixes :cry: 

Although, I can't really distinguish, which issue have bigger effect: this or #14303, as by "syntetic" tests they both leads to high CPU usage (and, I guess, @folke, as author of `Noice` suggests this issue as a culprit of the linked issue in it's tracker), but in "real life" it is pretty hard to catch exact culprit :shrug:

**Comment by folke** [comment] 2023-01-16 22:44
As I mentioned before, this can easily be fixed in galaxyline or whatever statusline you're using. They should just debounce updates. I don't understand why they don't do that even without this issue. It makes no sense to potentially update the statusline a gazilian times per second.

Lualine for example does not have this issue since they properly debounce updates.

**Comment by msva** [comment] 2023-01-17 10:23
> They should just debounce updates.

Well, I'd personally prefer to fix that issue in nvim side, and not make all the authors of all the statusline plugins to implement special workaround kludges everywhere.

As I (and issue author) mentoned above, high CPU usage issue reproduces even with empty (default) statusline.

So, I can even not mention that, say, it also reproduces with non-plugin handmade statusline I used before, where I only assigned statusline function to just return some info I need, so CPU load goes high even there (I guess, because of spamming filesystem and git operations. At lease, strace looks like this).

Although, I can't distinguish which exact of that pair of issues makes bigger contribution on this behaviour :shrug: 



And, by the way, even when statuslines "debounces" updates, I still see tons of activity in `strace`, while, say, Bram's Vim's `strace` is silent in same situation.

So, I think, it'd be nice to fix that on nvim side and just stop irrelevant statusline spamming (and make it behave as the opposite to current state: let statusline plugins (or user, who writes the static function) decide how often they want to update statusline (with timers, or schedulers). IMHO.

**Closed** 2023-03-09 10:06 UTC
Labels: bug, performance, event-loop
