### ISSUE TITLE
neovim deletes file ACLs/extended file attributes when saving

### ISSUE THREAD

**Issue by velartrill** [neovim/neovim#11798] opened 2020-02-01 03:17 UTC
- `nvim --version`: v0.4.3
- Operating system/version: Arch Linux
- Terminal name/version: urxvt 9.22
- `$TERM`: fish

### Steps to reproduce using `nvim -u NORC`

```
$ touch temp
$ setfacl -m g:ftp:w temp
$ getfacl temp
$ nvim -u NORC temp
:wq
$ getfacl temp
```

### Actual behaviour
neovim attempts to save files atomically by creating a new file in a temporary directory, writing to that file, and then replacing the old file with the new one rather than write to the old one directly. unfortunately, neovim does not preserve extended file attributes such as ACLs when creating the new file. (`:set nowritebackup` produces the expected behavior.) this could be remedied by copying the existing file to a temporary location instead of just creating an empty new file when the buffer is written out.

### Expected behaviour
getfacl should produce the same output in both cases; neovim should not alter the extended file attributes of the file being saved.

**Comment by justinmk** [comment] 2020-02-03 08:22
https://github.com/neovim/neovim/pull/10379 should address this. If you can build it and try it out that will help!

> this could be remedied by copying the existing file to a temporary location instead of just creating an empty new file when the buffer is written out.

But then two writes would be needed. (Although on newer systems, copying a file is instantaneous thanks to `uv_fs_copyfile` :)

Duplicate of https://github.com/neovim/neovim/issues/1200

**Closed by justinmk** 2020-02-03 08:22 UTC
Labels: bug
