### ISSUE TITLE
nvim_chan_send can not be called from vimscript (only from lua)

### ISSUE THREAD

**Issue by lucc** [neovim/neovim#15453] opened 2021-08-22 09:29 UTC
### Neovim Version

0.5 on nixos and 0.6-dev (8331cd13c45fb75bff0cec328ccba79b3ae61fa5)

### Operating system/version:

NixOS 21.11.20210816.23485f2 (Porcupine)

### Terminal name/version:

termite v15

### TERM environment variable

xterm-termite

### Installation

nix shell github:nix-community/neovim-nightly-overlay#neovim

### Steps to reproduce

```
nvim --headless -u NONE -c 'lua vim.api.nvim_chan_send()' -c 'call nvim_chan_send()' -c 'qa!'
```

### Vim

N/A

### Expected behavior

Both errors should say "expected 2 arguments" or so. It should indicate that the function can be called from vimscript.

There is no comment in the docs saying that it can only be called from lua so I expect to be able to call it from vimcript as well.

### Actual behavior

E117 indicates that the function `nvim_chan_send` can not be called from vimscript.

**Comment by justinmk** [comment] 2021-08-22 16:03
There are a few such functions marked FUNC_API_LUA_ONLY: https://github.com/neovim/neovim/blob/4547137aaff32b20172870a549d3a28a3c7adf1c/src/nvim/api/window.c#L564

Could add handling to [gen_vimdoc.py](https://github.com/neovim/neovim/blob/649dbb3b15949aee9d9e25cd39cca1e3e3a4ee45/scripts/gen_vimdoc.py)

**Comment by bhaumikankan** [comment] 2021-09-02 11:10
@justinmk i am new in open source i want to contribute but can you explain it to me? with clearity

**Comment by lucc** [comment] 2021-09-02 12:15
@bhaumikankan the help file is automatically generated by the script that Justin linked above. So I assume you have to modify the script in two ways:
- parse the FUNC_API_LUA_ONLY marker from the source code
- add a note to the output for all functions that have this marker

**Comment by bhaumikankan** [comment] 2021-09-03 01:37
@lucc can you assign me for this task

**Comment by bhaumikankan** [comment] 2021-09-03 03:09
@justinmk  is there any other fun_api_lua_only function or its just which you mention?

**Comment by lucc** [comment] 2021-09-03 07:38
It looks like there are 5 functions using this marker: https://github.com/neovim/neovim/search?q=FUNC_API_LUA_ONLY&type=code
I think you only need to detect the occurences in the *.c files.  The other stuff looks like definitions and other code that also parses these markers to do other stuff.

Maybe you just have to add something here: https://github.com/neovim/neovim/blob/649dbb3b15949aee9d9e25cd39cca1e3e3a4ee45/scripts/gen_vimdoc.py#L238-L242 and see what happens

**Comment by justinmk** [comment] 2021-09-11 02:29
duplicate of https://github.com/neovim/neovim/issues/13963

work done in https://github.com/neovim/neovim/pull/13972

**Closed** 2021-09-11 02:33 UTC
Labels: documentation, good-first-issue, api, vimscript, complexity:low
