### ISSUE TITLE
Add `virt_text_pos = 'insert'`

### ISSUE THREAD

**Issue by hrsh7th** [neovim/neovim#15291] opened 2021-08-06 14:39 UTC
### Feature already in Vim?

No.

### Feature description

First, I can guess this request is very difficult (or impossible).

But it might be useful if we have the ability to locate the virtual text as the middle of the line and existing text will be shifted to the right.

The main purpose is completion preview like VSCode's GitHub copilot.
Currently, we can preview only if the cursor is the rightmost column.

If it is not a valid feature request, feel free to close it.

**Comment by clason** [comment] 2021-08-06 14:42
Duplicate of https://github.com/neovim/neovim/pull/9496 (which is in progress)

**Closed by clason** 2021-08-06 14:42 UTC
Labels: enhancement

**Comment by hrsh7th** [comment] 2021-08-06 14:58
Thank you for your quick reply. I'll follow it!
