### ISSUE TITLE
Splitting a fold by inserting line with less indent resets open/close state of inner folds, with foldmethod=indent

### ISSUE THREAD

**Issue by simmsbra** [neovim/neovim#24324] opened 2023-07-12 16:02 UTC
### Problem

![bugged](https://github.com/neovim/neovim/assets/34775764/f3619126-e3ac-41c0-8067-e06326ec64c4)
When you split a fold (that has a closed nested fold within it) by inserting (in the middle of the fold) a line with less indentation, the nested fold opens.

I could not successfully bisect because the old builds cannot be built, but I believe the regression happened when the optimization that I mention below was added.

### Steps to reproduce

nvim --clean [file.txt](https://github.com/neovim/neovim/files/12029406/file.txt)
1. Run ":set foldmethod=indent" and ":set sw=2".
2. Open the current fold by typing "zo".
3. Under the first line, insert a line with no indent by typing "o<BS>a<Esc>".
4. See that the inner fold opened even though it should have stayed closed.

I also wrote this test:
```diff
--- a/test/functional/editor/fold_spec.lua
+++ b/test/functional/editor/fold_spec.lua
@@ -7,6 +7,7 @@ local expect = helpers.expect
 local command = helpers.command
 local funcs = helpers.funcs
 local eq = helpers.eq
+local neq = helpers.neq
 
 describe('Folds', function()
   local tempfname = 'Xtest-fold.txt'
@@ -417,4 +418,32 @@ a]], '13m7')
     eq(1, funcs.foldlevel(1))
     eq(1, funcs.foldlevel(2))
   end)
+
+  it("doesn't open folds with indent method when inserting lower foldlevel line", function()
+    insert([[
+      insert under this line
+      keep the lines under this line folded
+        keep this line folded 1
+        keep this line folded 2
+    ]])
+    command('set foldmethod=indent shiftwidth=2')
+    eq(1, funcs.foldlevel(1))
+    eq(1, funcs.foldlevel(2))
+    eq(2, funcs.foldlevel(3))
+    eq(2, funcs.foldlevel(4))
+
+    feed('zo') -- open the outer fold
+
+    -- TODO it seems like the test behaves as if noautoindent is set, but if i
+    -- explicitly set it, the test behaves differently...
+    feed('gg0oa<Esc>') -- TODO
+    --funcs.append(1, 'a')
+
+    eq(1, funcs.foldlevel(1))
+    eq(0, funcs.foldlevel(2))
+    eq(1, funcs.foldlevel(3))
+    eq(2, funcs.foldlevel(4))
+    eq(2, funcs.foldlevel(5))
+    neq(-1, funcs.foldclosed(4)) -- make sure the inner fold is not open
+  end)
 end)
```

### Expected behavior

![expected](https://github.com/neovim/neovim/assets/34775764/c0b2714f-f4f9-4836-96eb-2d1337d5956b)
When you split a fold (that has a closed nested fold within it) by inserting (in the middle of the fold) a line with less indentation, the nested fold should not open.

I have found that removing the following optimization fixes the bug, but I'm not sure how important that optimization is.
```diff
--- a/src/nvim/fold.c
+++ b/src/nvim/fold.c
@@ -771,7 +771,7 @@ void clearFolding(win_T *win)
 /// The changes in lines from top to bot (inclusive).
 void foldUpdate(win_T *wp, linenr_T top, linenr_T bot)
 {
-  if (disable_fold_update || State & MODE_INSERT) {
+  if (disable_fold_update) {
     return;
   }
```

### Neovim version (nvim -v)

v0.10.0-dev-659+gbf5703042

### Vim (not Nvim) behaves the same?

No, vim 9.0.1677

### Operating system/version

Linux

### Terminal name/version

Konsole

### $TERM environment variable

xterm-256color

### Installation

Built from repo

**Comment by justinmk** [comment] 2023-07-12 16:46
Thanks for providing a failing test, that is very helpful. However this is an intentional performance decision, see 

- https://github.com/neovim/neovim/pull/5299
- https://github.com/neovim/neovim/issues/5055

The idea is that immediately-updated folds in insert-mode is not important enough to justify permanent, extremely slow, insert-mode typing. If that performance issue is no longer a problem we could revisit.

**Comment by simmsbra** [comment] 2023-07-12 20:09
I though of a potential second solution that doesn't involve removing the optimization:
```diff
--- a/src/nvim/edit.c
+++ b/src/nvim/edit.c
@@ -347,7 +347,7 @@ static void insert_enter(InsertState *s)
 
   pum_check_clear();
 
-  foldUpdateAfterInsert();
+  foldUpdate(curwin, (linenr_T)2, (linenr_T)2);
   // When CTRL-C was typed got_int will be set, with the result
   // that the autocommands won't be executed. When mapped got_int
   // is not set, but let's keep the behavior the same.
```
This fixes the test case from the manual reproduction steps, but it has hardcoded line numbers specific to that case. If somebody else who is more familiar with the source code could generalize the line numbers to the lines that the insertion effected, that would be amazing!

I had this idea because, during debugging, it seemed like vim always knew the specific line numbers that were changed and was able to call foldSplit() to neatly split the fold without resetting the open/close status of any of the folds. But neovim, instead, just updates the folds across the entire buffer after insertion, without passing any specific line numbers of which lines were effected. I think this loss of information is the cause of the bug.

@justinmk 
> However this is an intentional performance decision

I see. And thanks for giving background and links about the optimization. That helped me understand it better.
Removing the optimization was one quick solution I found to fix the bug, but I don't think that it is the only solution (see above), so I think it would be best to not have this bug marked as closed, at least until somebody continues looking into my second solution.
Thanks!!

**Comment by clason** [comment] 2023-07-12 20:19
You're very welcome to keep looking into your solution (and open a PR), even without an open issue. The point is just that nobody on the team is likely to work on this, because of different priorities. Closing the issue is one way of managing expectations here.

**Comment by simmsbra** [comment] 2023-07-12 20:21
Oh, I understand now. Thanks.

**Comment by simmsbra** [comment] 2023-07-18 14:38
I explored my second solution but it does not look feasible because I think you'd have to recreate too much logic for determining which line numbers to pass based on all the different line changes (line addition/deletion, single/multiple line(s)) that could have happened during Insert mode.

I briefly considered if it would be possible to fix the bug while keeping the logic that simply waits until Insert is over and then updates the folds across the entire buffer, but I do not think it's possible because when the outer fold is truncated (to the line that you inserted with a lower indentation amount), the open/close state of the inner folds below is forgetten because I think those inner folds will be recreated after a new outer fold (that they will now be in) is created below the original outer fold.

Therefore, removing the optimization is the only solution I see. So I wanted to run performance tests from the original discussion, but the history of this optimization is difficult to follow, and every page I read is lacking in exact reproduction files and steps (although there are performance results and some syntax highlighting rules). I could be missing something, of course, but I simply cannot find any tests to recreate to see if this buggy performance optimization is still making neovim significantly faster. Perhaps other changes made in the past ~7 years have rendered this optimization obsolete.

I know that probably nobody will work on this, but for the future: Does anybody know how to create a performance test that proves that this optimization is still needed? Thanks.

**Comment by justinmk** [comment] 2023-07-18 23:45
> Does anybody know how to create a performance test that proves that this optimization is still needed? 

We could revert it and see if people complain. What motivated it in the first place was that people were very sensitive to the slowness while using foldmethod=indent. Presumably if it's still an issue then we'll hear from those people.

**Comment by simmsbra** [comment] 2023-07-19 01:47
> We could revert it and see if people complain.

That is what I would do, but I didn't suggest it because I didn't know if you guys would be comfortable doing that.
If neovim becomes slower in this use case, it should not be any slower than vim anyway (unless there are other differences from vim that would make it so).

If you want to do this, I can write the pull request.

**Comment by justinmk** [comment] 2023-07-19 12:54
> If neovim becomes slower in this use case, it should not be any slower than vim anyway

The point is to be faster than vim.

**Comment by simmsbra** [comment] 2023-07-19 14:42
> It's a tradeoff. Yes, it makes folds temporarily inaccurate, but ESC updates the folds, right?

It's not that the folds are temporarily inaccurate (I have not noticed that) -- it's that when they are updated after ESC is pressed, they are not updated correctly; that is the bug. The bounds / line numbers of all the folds are correct, but the open/close states of some of them get reset. In practice, if you have a large file with lots of nested folds in particular open/close states, this bug can reset (open) tons of them, which is what would happen to me in my todo list file before I removed the optimization.

**Comment by lewis6991** [comment] 2023-07-19 15:40
The removing the optimisation is just a workaround for a deeper bug?

**Comment by lewis6991** [comment] 2023-07-19 15:57
> it's that when they are updated after ESC is pressed, they are not updated correctly; that is the bug.

So then we need to update them correctly? Removing the optimisation just seems like a workaround.

**Comment by simmsbra** [comment] 2023-07-19 16:32
> So then we need to update them correctly? Removing the optimisation just seems like a workaround.

I thought the same thing and have explored different solutions. If you read my previous comments, the closest non-workaround fix is what I was called the "second solution".

From my debugging, this is my conclusion: Vim works because it always knows and passes the exact line numbers for what is changing during Insert mode when it updates the folds. Neovim does not know the line numbers; it just updates folds for all lines after Insert mode is exited. This causes different functions to be run, which recreates some folds instead of splitting them (which would preserve the open/close states).
If you wanted to keep the optimization, you'd have to find all the spread-out logic that Vim uses to determine which line numbers to pass when updating the folds, depending on what happened (1 or >1 line added, 1 or >1 line deleted, etc) and recreate all of it where Insert mode ends in Neovim. I hoped that all this logic would be in one place, but if you start tracing where foldUpdate() gets called related to Insert mode in Vim, you will be lead to the calls to the functions changed_lines() and changed_bytes(), which seem to be called in so many different ways with different line number arguments. That's where I stopped.

So, yes, it's technically possible, but I don't think that the amount of work it would require would make much sense, especially since we don't know if this optimization is currently useful.

**Comment by lewis6991** [comment] 2023-07-19 16:59
I'm pretty confident this optimization is useful for `foldmethod=expr` which I think was the main motivation for the change.

As well as improving performance, it also stops folds changing whilst you are typing which is often distracting.

**Comment by simmsbra** [comment] 2023-07-19 17:38
> I'm pretty confident this optimization is useful for `foldmethod=expr` which I think was the main motivation for the change.
> 
> As well as improving performance, it also stops folds changing whilst you are typing which is often distracting.

So do you think it would be ok to make the optimization only happen when `foldmethod` does not equal `indent`? In other words, run the optimization (by skipping fold updating during insert mode) but not if `foldmethod` is `indent`.

**Comment by lewis6991** [comment] 2023-07-19 17:43
That might be a reasonable compromise.

**Comment by simmsbra** [comment] 2023-07-19 17:50
> We'll need a good test case added to justify this special casing though.

Can you explain what you mean? I already wrote a test for this bug. Do you mean some kind of additional performance test?

**Comment by lewis6991** [comment] 2023-07-19 18:47
Ah yes, that test should be fine.

**Comment by simmsbra** [comment] 2023-07-19 19:24
Ok, I'll start on a pull request.

**Closed** 2023-07-21 00:56 UTC
Labels: bug, performance, folds
