### ISSUE TITLE
LSP cannot find installed vimls and Lua error

### ISSUE THREAD

**Issue by 0xRainy** [neovim/neovim#12539] opened 2020-06-26 01:12 UTC
- `nvim --version`:

```
NVIM v0.5.0-574-g352831229
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
```

- language server name/version: vimls 1.9.0
- Operating system/version: Win10 Build 2004

<details>
<summary>nvim -c ":checkhealth nvim nvim_lsp"</summary>

```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: vimls: configuration checked.
```

</details>

<details>
<summary>lsp.log</summary>
Couldn't get markdown code block working, here's the log:
https://gist.github.com/0xRainy/400165568b3d1c8f0f211aa5997f64e3
</details>

### Steps to reproduce using `nvim -u smallinit.vim`
<details>
<summary>smallinit.vim</summary>
call plug#begin('~/.config/nvim/autoload/plugged')

Plug 'neovim/nvim-lsp'

call plug#end()

lua << END
require'nvim_lsp'.vimls.setup{}
END
</details>

`npm install --global vim-language-server`
Run `nvim -U smallinit.vim`
Open any .vim file
Get error:

```
Error detected while processing FileType Autocommands for "vim":
E5108: Error executing lua C:\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:268: attempt to index upvalue 'handle' (a nil value)
```

Run `:LspInstall vimls`
Returns: `vimls is already installed (not by Nvim)`
Run `:LspInstallInfo vimls`
Returns: 

```
{
  bin_dir = "C:\\Users\\rainy\\AppData\\Local\\Temp\\nvim\\nvim_lsp\\vimls\\node_modules\\.bin",
  binaries = {
    ["vim-language-server"] = "C:\\Users\\rainy\\AppData\\Local\\Temp\\nvim\\nvim_lsp\\vimls\\node_modules\\.bin\\vim-language-server"
  },
  install_dir = "C:\\Users\\rainy\\AppData\\Local\\Temp\\nvim\\nvim_lsp\\vimls",
  is_installed = false
}
```

### Actual behaviour
vimls does not work at all
### Expected behaviour
vimls works
### Notes
I have used the same config on linux and have no issues.
vim-language-server.exe is available through my PATH and is installed to `C:\Users\rainy\AppData\Roaming\npm`
Not sure if related but with nvim-lsp plugin enabled, getting lua error in vim-clap when searching text with grep function and trying to open the file. Disabling the nvim-lsp plugin resolves the error.

Requested tag: @tjdevries

**Comment by igrep** [comment] 2020-11-16 09:07
I guess this is caused by the same reason with https://github.com/neovim/nvim-lspconfig/issues/164.
and looks already fixed by https://github.com/neovim/nvim-lspconfig/commit/2ed101841142a3ac98fd3f5ef0d0dad73ddc0862

**Comment by mjlbach** [comment] 2021-01-19 00:03
We deprecated LspInstall, so I believe this is "fixed"

**Closed by mjlbach** 2021-01-19 00:03 UTC
Labels: bug, lsp
