### ISSUE TITLE
Neovim Crashes When Scrolling with Mouse or Keyboard

### ISSUE THREAD

**Issue by LSleutsky** [neovim/neovim#21785] opened 2023-01-13 17:27 UTC
### Describe the bug

For the last couple days, when I open a file in Neovim, and have to scroll down either with the mouse, or with `Ctrl-D` / `Ctrl-U` or `Ctrl-F` / `Ctrl-B`, the editor completely crashes and exits, and makes my iTerm unusable (_the UI gets disfigured, I can't `Ctrl-C` to get back to a reset state, and it just makes a constant bell sound_). I have to either open a new tab and close the current crashed one, or restart iTerm altogether.

I've made no recent config changes, and added no new plugins. Only thing I do is get the latest nightly version, and run a `PackerSync` after doing so, to update my existing plugins.

This came quite literally out of the clear blue sky, and I have no idea why or how! This is what my iTerm looks like after this "crash" happens:

![neovim-crash](https://user-images.githubusercontent.com/7631797/212380670-431c80d9-804f-44aa-a2a1-24348a8f44b6.png)

I'm completely at a loss, with no idea how to even debug something like this. I don't see this being mentioned anywhere recently, so _maybe_ it's just an isolated incident, but.... why!?

Any help or guidance or ideas would be greatly appreciated. Thank you!!

### Steps to reproduce

1. Open Neovim with the standard `nvim`.
2. Open a file (_ideally a large file that needs scrolling_) from the current working directory.
3. Scroll up and down with either the keyboard using the `Ctrl-D` / `Ctrl-U` and/or `Ctrl-F` / `Ctrl-B` keybindings, or just standard scrolling with the mouse.
4. Neovim crashes out, and makes iTerm instance unusable,

### Expected behavior

To be able to scroll large files up and down as needed, with either mouse or the keyboard/keybindings.

### Neovim version (nvim -v)

v0.9.0-dev-661+ga37c686d2

### Vim (not Nvim) behaves the same?

no, vim 9.0.217

### Operating system/version

macOS Monterey 12.6

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

Compile from source

**Comment by timbedard** [comment] 2023-01-13 17:34
Same. Kitty on macOS here.

**Comment by zeertzjq** [comment] 2023-01-13 20:44
Duplicate of #21299

**Closed by zeertzjq** 2023-01-13 20:44 UTC
Labels: bug
