### ISSUE TITLE
Question about line wrapping in the terminal.

### ISSUE THREAD

**Issue by ekiim** [neovim/neovim#14498] opened 2021-05-05 21:32 UTC
Why does the terminal break the lines from terminal mode to the _current window width_?

I haven't looked to the actual implementation, but this is something it's been bugging me for a while.

When ever you do a `system` call from vim script or even `systemlist` you get the proper output, but if you call a program the `terminal-buffer` you get line breaks where you shouldn't. 

I'm not talking about a _shell_ inside the terminal buffer necessarily, I'm talking about any kind of output you get through a terminal buffer, like running `:e term://printf '---- more dashes than window width-------`.

Can someone explain a little about this, and or point me to a direction where I can start inspecting?

**Comment by jamessan** [comment] 2021-05-05 22:23
Duplicate of #2514

**Closed by jamessan** 2021-05-05 22:23 UTC
