### ISSUE TITLE
Holding `x` to delete multiple characters doesn't work on GNOME-Wayland if `wl-clipboard` is installed

### ISSUE THREAD

**Issue by rxt30** [neovim/neovim#17919] opened 2022-03-30 09:38 UTC
### Neovim version (nvim -v)

v0.6.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux, Kernel Linux 5.17.1-arch

### Terminal name/version

foot 1.11.0

### $TERM environment variable

foot

### Installation

Arch Linux package

### How to reproduce the issue

Install the GNOME DE and install `wl-clipboard`.
Start a GNOME-Wayland session.
Enable the system clipboard integration with `set clipboard+=unnamedplus` or lua-style with `vim.opt.clipboard = "unnamedplus"`.

### Expected behavior

Delete multiple characters while holding `x` or delete multiple lines while holding `d`.

### Actual behavior

Only deletes one character or line and then stops.

**Comment by matveyt** [comment] 2022-03-30 11:48
Duplicate of #12622 and/or #11804

**Closed** 2022-03-30 11:52 UTC
Labels: bug, environment, clipboard
