### ISSUE TITLE
`ml_get` error when winbar is unset from winbar expression evaluation

### ISSUE THREAD

**Issue by rebelot** [neovim/neovim#19660] opened 2022-08-06 15:20 UTC
### Neovim version (nvim -v)

NVIM v0.8.0-dev-786-g5eb8119dc

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

macOS 12.5

### Terminal name/version

kitty 0.25.0

### $TERM environment variable

tmux-256color

### Installation

build

### How to reproduce the issue

This used to work before 9879fd5d087cc3939f91f4714b0f95f03a78c011
This hackish mechanism is used by my plugin https://github.com/rebelot/heirline.nvim (https://github.com/rebelot/heirline.nvim/issues/47) due to limitations in global/local winbar settings (see https://github.com/neovim/neovim/issues/18660#issue-1243265744)

minimal `init.lua`
```lua
function _G.WinBar()
    local ft = vim.bo.filetype
    if ft == "help" then
        vim.opt_local.winbar = nil
    else
        vim.opt_local.winbar = ft
    end
end

vim.api.nvim_create_autocmd({ "VimEnter", "BufWinEnter" }, {
    command = "setlocal winbar=%{%v:lua.WinBar()%}",
})
```

1) open a non-empty buffer
2) place cursor **after** the first line
3) `:h this`

### Expected behavior

winbar can be set/unset during winbar evaluation without messing screen lines

### Actual behavior

vim throws error
```
E315: ml_get: invalid lnum: ...
```

**Comment by zeertzjq** [comment] 2022-08-06 21:38
Duplicate of #19458

**Closed by zeertzjq** 2022-08-06 21:38 UTC
Labels: bug
