### ISSUE TITLE
[Snippets] Allow completion to not expand snippets on completion

### ISSUE THREAD

**Issue by ldelossa** [neovim/neovim#29695] opened 2024-07-13 22:58 UTC
### Problem

I really love the new builtin snippet + lsp completion. 
These native features simply Neovim usage and removes the needs for two plugins. 

However the usage could be just slightly improved by allowing lsp completion to **not** expand snippets, possibly via a additional argument to the completion commands. 

Why? Function pointers. 

Consider this scenario:

![image](https://github.com/user-attachments/assets/9298e9a3-a6c3-4357-b1cc-310d9cf24ad6)

In the image I'm trying to provide a pointer to a function to this structure via lsp completion. 
It gets really clumsy here. 

 I can complete the completion and be placed inside the first snippet, however pressing `backspace` here does not remove all arguments. Even if this did, we still need to remove the remaining parenthesis `()`. 

It would be nice to either
1. Allow a way to fill the completion without any snippets
or
2. When the snippet is 'active' provide a way to remove all arguments + '()'.

For 2. I could understand that removing the parenthesis maybe awkward. I think this could be optional since most individuals with pairs plugs will easily delete both parenths (when you delete the first one, the pairs plugin usually removes the other).

### Expected behavior

I wouldn't say I have an 'expected behavior'. As outlined above, I'm hoping that the suggestion for usability is agreed with. Its cool if the core team just doesn't agree with this, in which case feel free to close the feature request.

**Comment by clason** [comment] 2024-07-14 09:47
Neovim just implements the LSP specification in this regard and does exactly what the LSP server tells it to. You can disable snippets either through server configuration or by just setting the client snippet capability to `false`. The second ask is completely out of scope for the core implementation, but maybe a plugin can handle it.

(This is a general Neovim policy: core gives you a hackable implementation with reasonable (nonconfigurable) defaults; anything beyond that is the job of a plugin where a wide choice is usually available so everybody will find one that fits their needs.)

**Comment by ldelossa** [comment] 2024-07-14 13:37
Yup I can totally understand that. I can look into the completion and snippet code and see if a tiny plugin can be devised to do the want in this. Thanks for the quick response.

**Closed** 2024-07-15 18:05 UTC
Labels: enhancement, snippet

**Comment by mfussenegger** [comment] 2024-07-15 18:40
The snippet is only expanded if you accept a suggestion (`:h complete_CTRL-Y`)

If you only pre-select it (`i_CTRL-N`) it shouldn't expand the snippet and you can continue typing.


If the pre-selection already includes the parenthesis and arguments we may be able to tune things a bit depending on how the exact server response looks like. Similar to the cases in https://github.com/neovim/neovim/blob/45b7a2c50335e1943a36715101e40eda5a1423f3/test/functional/plugin/lsp/completion_spec.lua#L200-L278 

Could you share the payload the server is sending as response to a completion request or post a small reproduction?

**Comment by ldelossa** [comment] 2024-09-08 18:25
@mfussenegger 

Looks like for me, as soon as I hit `CTRL-N` the snippet text is included. 
But, maybe this is a Neovim setting I have that's doing this? 

I can reproduce with `clangd` and a super simple C file:

```
void f(int a);

int main(int argc, char *argv[]) {
   f()
}
```

For example:

https://github.com/user-attachments/assets/1dce1b09-c255-40b0-b6ed-b0a15e4b29df

I obviously have snippets enabled at the LSP, but if this is disabled, we get no templates to potentially expand at all. 

```
-- ripped from cmp.nvim
local default_capabilities = function(override)
	override = override or {}
	return {
		textDocument = {
			completion = {
				dynamicRegistration = true,
				completionItem = {
					snippetSupport = true,
					commitCharactersSupport = true,
					deprecatedSupport = true,
					preselectSupport = true,
					tagSupport = {
						valueSet = {
							1, -- Deprecated
						},
					},
					insertReplaceSupport = true,
					resolveSupport = {
						properties = {
							"documentation",
							"detail",
							"additionalTextEdits",
							"sortText",
							"filterText",
							"insertText",
							"textEdit",
							"insertTextFormat",
							"insertTextMode",
						},
					},
					insertTextModeSupport = {
						valueSet = {
							1, -- asIs
							2, -- adjustIndentation
						},
					},
					labelDetailsSupport = true,
				},
				contextSupport = true,
				insertTextMode = 1,
				completionList = {
					itemDefaults = {
						"commitCharacters",
						"editRange",
						"insertTextFormat",
						"insertTextMode",
						"data",
					},
				},
			},
		},
	}
end
```

Looking through my configs, I don't see anything.
The only `vim.snippet` functionality I have in my config is a super-tab implementation for moving thru the template elements:


```
_G.tab_action = function()
	if vim.fn.pumvisible() ~= 0 then
		return keys["ctrl-y"]
	elseif vim.snippet.active({ direction = 1 }) then
		return '<cmd>lua vim.snippet.jump(1)<cr>'
	else
		return keys["tab"]
	end
end
vim.keymap.set("i", "<Tab>", "v:lua._G.tab_action()", { expr = true })
```

**Comment by ldelossa** [comment] 2024-09-08 18:45
@mfussenegger - you are right. I was using a completion plugin that got in the way. 
Things work fine when I remove this plugin and use `noinsert, noselect` in compleopts
