### ISSUE TITLE
Closing parenthesis in Lua is highlighted as error

### ISSUE THREAD

**Issue by Mcbeany** [neovim/neovim#23460] opened 2023-05-03 11:38 UTC
### Problem

I got this error while writing Lua code in Vimscript and when opening documentation in Lua
It doesn't happen in regular `.lua` files
![image](https://user-images.githubusercontent.com/77101686/235904396-7d1c9238-aea3-4917-a1f3-fc53b277c809.png)

### Steps to reproduce

Install Neovim
Write some code in Lua

### Expected behavior

Highlight like normal Lua file

### Neovim version (nvim -v)

v0.10.0-dev

### Vim (not Nvim) behaves the same?

vim 8.2

### Operating system/version

Ubuntu 22.04

### Terminal name/version

Wezterm

### $TERM environment variable

xterm-256color

### Installation

system package manager (using PPA)

**Comment by zeertzjq** [comment] 2023-05-03 11:54
Duplicate of #20456

**Closed by zeertzjq** 2023-05-03 11:54 UTC
Labels: bug
