### ISSUE TITLE
Allow signcolumn on wrapped lines

### ISSUE THREAD

**Issue by famiu** [neovim/neovim#14431] opened 2021-04-23 16:37 UTC
It'd be nice if Neovim allowed sign column to be on wrapped lines. The main reason for me wanting this feature is because plugins like gitgutter or gitsigns.nvim look ugly due to the gutter sign not being in the wrapped line. Screenshot:
![image](https://user-images.githubusercontent.com/29580810/115902602-67db5d80-a484-11eb-9216-3b1d7d14d698.png)

**Comment by pwntester** [comment] 2021-04-28 08:03
Duplicate of #12866

**Closed** 2021-04-28 21:47 UTC
Labels: duplicate, enhancement
