### ISSUE TITLE
:file doesnt print current filename

### ISSUE THREAD

**Issue by hackaugusto** [neovim/neovim#8873] opened 2018-08-19 20:42 UTC
```
# nvim --version                                                                                                         17:37
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
Run :checkhealth for more info
```
- Vim behaves differently? Yes:
`vim test.py` followed by `:file` prints:
```
"test.py" --No lines in buffer--
```

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug  1 2018 12:30:25)
Included patches: 1-194
Compiled by Arch Linux
```
- Operating system/version: Arch Linux
- Terminal name/version: zsh 5.5.1 + tmux 2.7 + alacritty 0.1.0
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
touch test.py
nvim -u NORC test.py
type `:file`
```

### Actual behaviour

Nothing is printed

### Expected behaviour

The filename with the path relative to cwd should be printed

**Comment by justinmk** [comment] 2018-08-20 15:28
duplicate of #8817

you can:

- use `:file!`
- use `ctrl-g` 
- `:set shortmess+=F`

**Comment by justinmk** [comment] 2018-08-20 15:32
I can't think of a reason that `:file` should care about `shortmess-=F`. I suspect it might be unintentional, because the "F" flag of `shortmess` is somewhat new.

**Comment by janlazo** [comment] 2018-08-20 22:27
8.1.0110 doesn't resolve it?

**Comment by justinmk** [comment] 2018-08-21 06:52
@janlazo Thanks! Merged it in https://github.com/neovim/neovim/pull/8878

**Closed** 2018-08-21 07:25 UTC
Labels: compatibility, complexity:low, duplicate, good first issue, usage
