### ISSUE TITLE
vim.iter: flatten() non-list input

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#28448] opened 2024-04-21 23:11 UTC
### Problem

iter:flatten() currently fails ("flatten() requires a list-like table") on this code from gen_lsp.lua: https://github.com/neovim/neovim/blob/35e38833c54565b05a0c33ba44694fc1077dce97/scripts/gen_lsp.lua#L262-L265

    local anonym = vim.iter({ -- remove nil
      anonymous_num > 1 and '' or nil,
      '---@class ' .. anonymous_classname,
    }):flatten():totable()

### Expected behavior

`tbl_flatten` accepted array-like input and the above gen_lsp code leveraged that to drop nil items.

Can we enhance `Iter:flatten()` to work for arrays?

**Comment by clason** [comment] 2024-05-17 17:54
Duplicate of https://github.com/neovim/neovim/issues/28777 (which will be fixed by #28781)

**Closed by clason** 2024-05-17 17:54 UTC
Labels: enhancement, needs:discussion, complexity:low, lua
