### ISSUE TITLE
Resizing terminal window makes chars get chopped off

### ISSUE THREAD

**Issue by qwfy** [neovim/neovim#7303] opened 2017-09-22 10:45 UTC
```
$ nvim --version
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

$ uname -sr
Linux 4.12.13-1-ARCH

konsole: 17.08.1-1
bash: 4.4.012-2
```

### Steps to reproduce

(There is a [video](https://imgur.com/a/ayLiv) of the following procedure)
- `nvim -u NORC`
- split two windows: `:vnew`
- start a term: `:term`
- type some long garbage chars, like 'aaaaaaaa(...more a's omitted)' make sure it spans multiple lines
- reduce the windows size: `:vertical resize -20`
- recover the original windows size: `:vertical resize +20`

### Actual behaviour
The last 20 columns get chopped off, see the above video.

### Expected behaviour
The last 20 columns gets wrapped to the next line when reducing the window size, gets back to the original position when window is resized back.

**Comment by justinmk** [comment] 2017-09-23 04:12
duplicate of https://github.com/neovim/neovim/issues/5325

**Closed** 2017-09-23 04:12 UTC
Labels: :term, duplicate
