### ISSUE TITLE
Make leading space in line numbers use default highlight instead of LineNr

### ISSUE THREAD

**Issue by xtsm** [neovim/neovim#15900] opened 2021-10-04 15:42 UTC
### Feature description

I'm making this issue because I've found [this question](https://stackoverflow.com/questions/2531904/how-do-i-increase-the-spacing-of-the-line-number-margin-in-vim) on SO which claims that it is not currently customizable in Vim, which sucks. It also has a picture.

My description: the line numbers column has single whitespace character in the right to separate the column from the text. If you use the same background for line numbers and text, it looks okay, otherwise the text appears too close to the line numbers column, which looks ugly.

I said "make space use default highlight" but actually any solution that will make it not ugly will do, customizable or not. Fix pls

**Comment by gpanders** [comment] 2021-10-04 15:45
Duplicate of #6092.

> Fix pls

You're welcome to create the PR yourself.

**Closed by gpanders** 2021-10-04 15:45 UTC
Labels: enhancement
