### ISSUE TITLE
intemittent error: vim/shared.lua:0: attempt to index a nil value

### ISSUE THREAD

**Issue by etorth** [neovim/neovim#19700] opened 2022-08-10 07:51 UTC
### Neovim version (nvim -v)

NVIM v0.8.0-dev-805-g512e0441f

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

linux

### Terminal name/version

xterm

### $TERM environment variable

xterm

### Installation

https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage

### How to reproduce the issue

simple execute can reproduce intemittently:
```shell
vim
```
gives
```log
Error executing luv callback:
vim/shared.lua:0: attempt to index a nil value
stack traceback:
        vim/shared.lua: in function 'tbl_get'
        ...ount_nvim.a635ND7/usr/share/nvim/runtime/lua/vim/lsp.lua:403: in function 'get_group'
        ...ount_nvim.a635ND7/usr/share/nvim/runtime/lua/vim/lsp.lua:525: in function 'reset'
        ...ount_nvim.a635ND7/usr/share/nvim/runtime/lua/vim/lsp.lua:1151: in function 'on_exit'
        ..._nvim.a635ND7/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:329: in function <..._nvim.a635ND7/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:321>     
```

### Expected behavior

no error

### Actual behavior

error as above

**Comment by mfussenegger** [comment] 2022-08-10 10:55
Looks like a regression introduced by https://github.com/neovim/neovim/pull/19658 but your reproduction steps don't work for me and I don't understand how the lsp client can be nil in that scenario.

What kind of lsp plugins are you using?

**Comment by captainko** [comment] 2022-08-10 14:19
I'm using `rust-tools`

**Comment by etorth** [comment] 2022-08-10 17:49
> Looks like a regression introduced by #19658 but your reproduction steps don't work for me and I don't understand how the lsp client can be nil in that scenario.
> 
> What kind of lsp plugins are you using?

I don't have any lsp configured.
This is intemittent error, I can reproduce in chance like 50%

**Comment by mfussenegger** [comment] 2022-08-10 18:40
I don't see how you could see this error without using lsp, giving that the stacktrace suggests it happens when the lsp client exits.

In any case - this needs a minimal reproduction

**Comment by strayer** [comment] 2022-08-11 08:14
I'm experiencing the same issue on macOS with neovim built from git via homebrew. I can't yet reproduce it with a minimal example but can at least add that this only happens if the buffer has more than one lsp attached. In my case it is typescript with null-ls, eslint and tsserver. If I have all three enabled I get the error twice, with two enabled once and with only one enabled not at all. It doesn't seem to matter which ones are enabled and I can't seem to reproduce it with the same lsps in a simple reproduction repository where I only have one simple typescript file.

**Comment by zeertzjq** [comment] 2022-08-12 03:05
I found a way to reproduce the error:
```lua
local client_id = vim.lsp.start_client {
  cmd = {
    vim.v.progpath, '-es', '-u', 'NONE', '--headless'
  };
}

vim.lsp.stop_client(client_id)
```

**Comment by mfussenegger** [comment] 2022-08-12 08:16
Should be fixed with https://github.com/neovim/neovim/pull/19735

**Comment by zeertzjq** [comment] 2022-08-13 13:55
@etorth Can you confirm whether this has been fixed?

**Comment by etorth** [comment] 2022-08-13 19:38
I put a loop for the latest build:
```csh
while 1
    vim -c exit
end
```

looks I didn't see this error anymore.
I can not get the buggy appimage of version ```v0.8.0-dev-805-g512e0441f``` anymore.

**Closed** 2022-08-13 20:16 UTC
Labels: bug, lsp
