### ISSUE TITLE
Strange characters appear randomly after startup

### ISSUE THREAD

**Issue by lcdsmao** [neovim/neovim#11671] opened 2020-01-04 10:19 UTC
- `nvim --version`:
```
 NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
Behaves differently

- Operating system/version:
macOS 10.15.1 (19B88)

- Terminal name/version:
iTerm2 3.3.7

- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

Either `nvim -u NORC` or `env -i TERM=ansi-256color "$(which nvim)"` can reproduce this problem.

After starting nvim, some strange characters will appear:
<img width="598" alt="Screen Shot 2020-01-04 at 19 14 24" src="https://user-images.githubusercontent.com/13031690/71764075-75cf3d00-2f26-11ea-931e-1292cb2278ad.png">

This phenomenon appears randomly, and the characters will appear every time is the subsequence of `/26/31/37^G`, like `/31/37`.
 
### Actual behaviour
Like the above picture.

### Expected behaviour
No strange character after startup.
<img width="598" alt="Screen Shot 2020-01-04 at 19 15 17" src="https://user-images.githubusercontent.com/13031690/71764089-91d2de80-2f26-11ea-830f-9cf45f6f91b8.png">

**Comment by justinmk** [comment] 2020-01-04 20:42
Duplicate of https://github.com/neovim/neovim/issues/11393

**Closed by justinmk** 2020-01-04 20:42 UTC
Labels: bug
