### ISSUE TITLE
Quickly switching between terminal buffer will make bottom half of the screen not rendered

### ISSUE THREAD

**Issue by mars90226** [neovim/neovim#9935] opened 2019-04-23 09:18 UTC
- `nvim --version`: NVIM v0.4.0-614-g43356a43d
- Vim (version: ) behaves differently? Can't be sure
- Operating system/version: Ubuntu 18.04 Linux 4.18.20-041820-generic
- Terminal name/version: MobaXterm v11.1
- `$TERM`: xterm-256color. But in neovim, $TERM is screen-256color

### Steps to reproduce using `nvim -u NORC`
In order to "quickly switching between terminal buffer", I need to map keys in terminal mode.
```
$ cat ~/test_terminal_render_vimrc
tnoremap <F1> <C-\><C-N>gT
tnoremap <F2> <C-\><C-N>gt
```
And
```
nvim -u ~/test_terminal_render_vimrc -p2 +"tabdo terminal"
gTi
nvim -u ~/test_terminal_render_vimrc
<C-\><C-N>gti<F1>
```

### Actual behaviour
![neovim_terminal_render_wrong](https://user-images.githubusercontent.com/1523214/56569255-30165280-65eb-11e9-8171-adb33fe051b9.png)

### Expected behaviour
![neovim_terminal_render_normal](https://user-images.githubusercontent.com/1523214/56569666-027dd900-65ec-11e9-8bf3-b4c431d151e7.png)

As the images shown above, the bottom half of the screen is not rendered. This behavior is only happen when using mapping to "quickly switch" to other terminal buffer, and will not happen when using `<C-\><C-N>gt`. I've also using `git bisect` to find out [this commit](https://github.com/neovim/neovim/commit/f5d5da391715f3b1d4c3d36c522e39b94866b93f) that cause this behavior.

Since I can't make the mapping works in the vim 8, so I'm not sure if vim 8 will do the same. But I guess vim 8 probably don't have this problem.

**Comment by mars90226** [comment] 2019-04-23 10:43
After trying different program in the terminal buffer, I think only programs using ncurses is affected, e.g. `htop`, `ranger`. But programs like `less` is not affected.

**Comment by bfredl** [comment] 2019-04-23 10:52
Would you mind try if https://github.com/neovim/neovim/pull/9883 fixes the issue?

**Comment by mars90226** [comment] 2019-04-23 12:01
> 
> 
> Would you mind try if #9883 fixes the issue?

I just tried it, the issue is still there.

**Comment by mars90226** [comment] 2019-05-31 09:00
Well, I found that this issue doesn't appear in current neovim. And I've git bisect that [this commit](https://github.com/neovim/neovim/commit/5faed57ac70ef637a2bce25e03458e976f8c8969) fix the issue.

**Comment by mars90226** [comment] 2019-05-31 09:06
Well, I found that this issue does not appear in master branch of neovim. And I've git bisected to [this commit](https://github.com/neovim/neovim/commit/c08ca2964955290e1b69f3f8177517074c99a61e) that fix the issue.

**Comment by justinmk** [comment] 2019-05-31 18:32
Cannot reproduce. If you can't reproduce it either, let's close it.

**Closed by justinmk** 2019-05-31 18:32 UTC
Labels: +repro, :terminal, bug-regression, display
