### ISSUE TITLE
Ability to disable all the hit-enter propmts completely.

### ISSUE THREAD

**Issue by voronind-com** [neovim/neovim#31226] opened 2024-11-15 17:19 UTC
### Problem

I can't stand my work being interrupted by hit-enter, this is the single major annoyance I have with nvim. Right now I do something like this:
```lua
		bequiet = function(msg, log_level, opts)
			print(string.sub(tostring(msg), 1, vim.v.echospace))

			local log = io.popen("systemd-cat -t nvim", "w")
			log:write(tostring(msg))
			log:close()
		end

		vim.notify = bequiet
		vim.api.nvim_out_write = bequiet
		vim.api.nvim_err_write = bequiet
```
This redirects all the errors to system journal. But I still get popups occasionally, and it maddens me as I have no idea where else to look at to suppress it all.

Maybe there's a way to disable like all messages for good? I don't mind losing useful info just not to get hit-enter interrupted. Thanks!

### Expected behavior

Single entry-point to disable interruptions.

**Comment by clason** [comment] 2024-11-15 17:37
Duplicate of #22478

**Closed by clason** 2024-11-15 17:37 UTC
Labels: enhancement
