### ISSUE TITLE
E576: Failed to parse ShaDa file: incomplete msgpack string at position 85

### ISSUE THREAD

**Issue by mgraczyk** [neovim/neovim#4108] opened 2016-01-27 00:32 UTC
When I open neovim, I am met with the title error message. When I close neovim, I am met with a different error message claiming that "~/.local/share/nvim/shada/main.shada" is not a valid shada file.

The error occurs at the current head (9b0b3a0883ab6c9d9f57fcf65d5bc951f40dff3c) but not at revision (7f3999ac806daefa078b4db0781bfc1e190e135e).

It is consistent between builds, but does not happen the very first time I run nvim after the build:
$ git checkout master
$ git clean -xdf
$ rm -rf ~/.local/share/nvim
$ make -j CMAKE_BUILD_TYPE=Release install
$ nvim # No error
:q
$ nvim # error
E576: Failed to parse ShaDa file: incomplete msgpack string at position 85
Press ENTER or type command to continue

**Comment by justinmk** [comment] 2016-01-27 04:16
Possibly a permissions issue. Else we would need the exact contents of the file in order to debug this.

**Comment by mgraczyk** [comment] 2016-01-27 04:22
The file ~/.local/share/nvim/shada/main.shada contains the text "-1" and nothing else.

**Comment by justinmk** [comment] 2016-01-27 04:37
The contents are "-1" even before quitting, or did nvim somehow replace the contents with "-1"?

Are you able to reproduce with `nvim -u NONE` (i.e. without plugins and configuration)?

**Comment by mgraczyk** [comment] 2016-01-27 04:51
Ah I was confused about the contents of the file because I opened it with nvim, which knows how to interpret shada files and render them. The shada file appears to be fine, but neovim HEAD is not interpreting correctly and fills the buffer with "-1". The file's contents:

```
0000000: 01ce 56a8 4be4 2182 a776 6572 7369 6f6e  ..V.K.!..version
0000010: cd02 c0a9 6765 6e65 7261 746f 72c4 0973  ....generator..s
0000020: 6861 6461 2e76 696d 01ce 56a8 4b72 4b85  hada.vim..V.KrK.
0000030: a865 6e63 6f64 696e 67c4 0575 7466 2d38  .encoding..utf-8
0000040: a967 656e 6572 6174 6f72 c404 6e76 696d  .generator..nvim
0000050: a96d 6178 5f6b 6279 7465 0aa3 7069 64cd  .max_kbyte..pid.
0000060: 5a0e a776 6572 7369 6f6e c40e 4e56 494d  Z..version..NVIM
0000070: 2030 2e31 2e32 2d64 6576 0a               0.1.2-dev.
```

When I open with the older version of neovim, it renders correctly. When I open with HEAD, I get an error

```
E576: Failed to parse ShaDa file: incomplete msgpack string at position 91
Press ENTER or type command to continue
```

Running with `nvim -u NONE` gives the same error.

**Comment by justinmk** [comment] 2016-01-27 04:55
Oh. Would you be willing to bisect to find the commit that caused this? Or provide the shada file in a gist?

**Comment by mgraczyk** [comment] 2016-01-27 05:05
Okay, how about this command for bisect?
`./build/bin/nvim -e -s -c ":q"`

It looks like it correctly flags `$?==1` on failure. Does that sound right?

**Comment by justinmk** [comment] 2016-01-27 05:13
@mgraczyk Yes that works. Make things a little easier:

    nvim -u NONE -e -s -c ":q" ; echo $?

**Comment by mgraczyk** [comment] 2016-01-27 05:19
Using the following bisect script,

```
#!/bin/sh
git clean -xdf
make -j CMAKE_BUILD_TYPE=Release
./build/bin/nvim -u NONE -e -s -c ":q"
```

I got
```
feb70192a85d04343ecc383ea9a42aa8cd15e98d is the first bad commit
commit feb70192a85d04343ecc383ea9a42aa8cd15e98d
Author: James McCoy <jamessan@jamessan.com>
Date:   Fri Jan 22 14:37:19 2016 -0500

    cmake: Search for both libmsgpackc and libmsgpack #4075
    
    libmsgpack was the old C++ library provided by msgpack-c.  The C library
    is libmsgpackc.
    
    The C++ support became header-only, but there was a bug
    (msgpack/msgpack-c#395) wherein using msgpack-c's CMake build system
    would only install libmsgpack instead of libmsgpackc.
    
    Searching for both libraries, but preferring libmsgpackc, allows for
    building against older msgpack-c releases and prepares for the upcoming
    msgpack-c release which fixes the aforementioned issues.
    
    Signed-off-by: James McCoy <jamessan@jamessan.com>

:040000 040000 b1d6ac12ba1b74e304c96a25572c4d2b2156c7aa 463b90fc53cd4bf5167002b140a333c71e389261 M      cmake
bisect run success
```

**Comment by justinmk** [comment] 2016-01-27 05:32
@mgraczyk Nice, I did not know about that little feature of git bisect :) 

So, if you update to master and `git revert feb70192a85d04343ecc383ea9a42aa8cd15e98d` then build, everything's fine? 

`msgpackc` must have some sort of regression...

**Comment by justinmk** [comment] 2016-01-27 05:33
Can you find out the precise version of libmsgpackc on your system? We should require a minimum version, assuming the bug has been fixed in a later version. cc @jamessan @ZyX-I

**Comment by mgraczyk** [comment] 2016-01-27 08:13
Reverting the offending commit fixes the error for me.

I'm not sure how to check the msgpack version. Does neovim use the msgpack installed on my system or does it download its own? I am not running `make install` to reproduce this bug.

**Comment by justinmk** [comment] 2016-01-27 08:31
@mgraczyk It tries to find `libmsgpackc` (or `libmsgpack` if not available) on your system. You would need to find the package in your package manager, e.g. apt-get, to find the version.

**Comment by fwalch** [comment] 2016-01-27 10:17
@mgraczyk can you check the build output to see which msgpack (systemwide or bundled) is used? Should be something like "Found msgpack: . .". If after the commit it somehow picks up the systemwide version instead of the bundled one, we could provably avoid that by updating the bundled msgpack to 1.4.0.

**Comment by ZyX-I** [comment] 2016-01-27 14:19
> Ah I was confused about the contents of the file because I opened it with nvim, which knows how to interpret shada files and render them. The shada file appears to be fine, but neovim HEAD is not interpreting correctly and fills the buffer with "-1". The file's contents:

You have shown only the header here. If this is everything file contains it is *not* fine, file should contain something despite the header.

**Comment by mgraczyk** [comment] 2016-01-28 03:43
The "bad" version (HEAD) prints
```
-- Found Msgpack: /usr/lib/libmsgpackc.so  
```
which is a link to /usr/lib/libmsgpackc.so.2.0.0.

The "good" version (HEAD + revert feb701) prints
```
-- Found Msgpack: /<elided>/neovim/.deps/usr/lib/libmsgpack.a  
```

The full good and bad outputs are attached.

[good.txt](https://github.com/neovim/neovim/files/107660/good.txt)
[bad.txt](https://github.com/neovim/neovim/files/107659/bad.txt)

**Comment by jamessan** [comment] 2016-01-28 04:13
Try building with `make DEPS_CMAKE_FLAGS=-DUSE_BUNDLED_MSGPACK=OFF`.

**Comment by jamessan** [comment] 2016-01-28 04:32
The bundled msgpack is getting built and installed to `.deps`, since it wasn't requested not to.   The headers from that msgpack are picked up through `-isystem /path/to/neovim/.deps/usr/include`, but then the system libmsgpackc library is picked up and used to link nvim.

This doesn't look like a good combination.  If the third-party deps were each installed into their own tree (e.g., .deps/msgpack, .deps/jemalloc, etc.), then it'd be easy to exclude the msgpack tree if FindMsgpack.cmake finds something.  However, they're all installed into their own tree right now.

**Comment by jamessan** [comment] 2016-01-28 04:56
The buildsystem does try to avoid this problem by setting the .deps tree as the preferred place for pkg-config to find things.  Two things contribute to this not working in this specific scenario:

1. Up until 1.4.0, msgpack's CMake buildsystem wasn't installing libmsgpackc (c.f., msgpack/msgpack-c#395)
1. Relatedly, the pkgconfig file was pointing to the C++ library (which wasn't relevant anymore) instead of the C library.

So, the short term fix is probably just to bump the version of the bundled msgpack as @fwalch suggested earlier and decide later whether my suggestion to automatically give deference to system libraries is warranted.

**Comment by mgraczyk** [comment] 2016-01-28 05:36
Building with `DEPS_CMAKE_FLAGS=-DUSE_BUNDLED_MSGPACK=OFF` caused compiler errors, for example

```
../src/nvim/eval.c: In function ‘msgpack_to_vim’:
../src/nvim/eval.c:13185:10: error: ‘MSGPACK_OBJECT_FLOAT’ undeclared (first use in this function)
     case MSGPACK_OBJECT_FLOAT: {
          ^
../src/nvim/eval.c:13185:10: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by jszakmeister** [comment] 2016-01-28 11:02
> If the third-party deps were each installed into their own tree (e.g., .deps/msgpack, .deps/jemalloc, etc.), then it'd be easy to exclude the msgpack tree if FindMsgpack.cmake finds something.

I like that idea.

**Comment by jamessan** [comment] 2016-01-28 13:56
> ../src/nvim/eval.c:13185:10: error: ‘MSGPACK_OBJECT_FLOAT’ undeclared (first use in this function)

That looks either the build can't find the header files for your system msgpack or the system version of msgpack is pre-1.0.0 (which is when `MSGPACK_OBJECT_FLOAT` was added).

**Comment by jamessan** [comment] 2016-01-28 14:20
> or the system version of msgpack is pre-1.0.0

When #4119 is merged, this will be ruled out.  If you do have an old msgpack installed on your system, then the `-DUSE_BUNDLED_MSGPACK=OFF` build should fail and a normal build should use everything from the bundled msgpack.

Hopefully that fixes the issues you're hitting, or at least gives us better assurances about your environment.

**Comment by jamessan** [comment] 2016-01-29 01:27
@mgraczyk Can you try building the latest git to see if things work better now?

**Comment by mgraczyk** [comment] 2016-01-29 01:32
Building normally at `aa8b3b60ee03e4b6a5e664bc16f177893b2ba309` results in a binary with the same `E576` error. During the build, cmake still reports

```
Found Msgpack: /usr/lib/libmsgpackc.so
```

**Comment by myitcv** [comment] 2016-02-03 07:47
@jamessan as another reference point, on Ubuntu, removing the system-wide `libmsgpack*` allows 4f4b8ea4489b445d0f9e0b8e1b9885555d0d861f to build and run just fine... Which is I guess unsurprising given that the build is then using a locally downloaded dependency?

**Comment by jamessan** [comment] 2016-02-03 15:10
I have msgpack-c 1.4.0 installed system-wide and didn't disable the use of bundled deps.  CMake picked up the system install and used that to build nvim (@ 4f4b8ea).  I don't see the problem being reported.

nvim updates my shada file just fine and doesn't complain about anything when I restart it.

For people that are seeing this problem, we need to know what the version of the system msgpack libs are (`dpkg-query -l libmsgpack\*` for Debian/Ubuntu users and I'm sure there's some similar pacman invocation for Arch).

**Comment by fwalch** [comment] 2016-02-03 15:20
@jamessan It might be that even after #4119, an older systemwide msgpack version is still found. If `pkg_search_module` fails (i.e. `PC_*` variables are empty) the later `find_library` call should still pick up the systemwide, pre-1.0 `msgpackc` even with empty `HINTS`, as `LIMIT_SEARCH` is not set.

**Comment by jamessan** [comment] 2016-02-03 15:51
Right.  I'll do some more testing tonight.  I think I have a solution.

**Comment by myitcv** [comment] 2016-02-03 17:10
@jamessan details of my setup where `nvim` does _not_ work (i.e. I see the shada errors):

```
$ sb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
$ uname -s -r -p
Linux 4.2.0-27-generic x86_64
$ dpkg-query -l libmsgpack\*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                                                                 Version                                                 Architecture                                            Description
+++-====================================================================================================-=======================================================-=======================================================-=============================================================================================================================================================================================================
ii  libmsgpack-dev                                                                                       0.5.7-3ubuntu1                                          amd64                                                   binary-based efficient object serialization library
ii  libmsgpack3                                                                                          0.5.7-3ubuntu1                                          amd64                                                   binary-based efficient object serialization library
ii  libmsgpackc2                                                                                         0.5.7-3ubuntu1                                          amd64                                                   binary-based efficient object serialization library
```

**Comment by myitcv** [comment] 2016-02-03 17:56
I guess a separate question is how this didn't cause any tests to fail...

**Comment by jamessan** [comment] 2016-02-03 18:03
The CI builds aren't running with the system msgpack library/headers installed.  I was when I made the change, but mine is post-1.0 so it's fine.

**Comment by myitcv** [comment] 2016-02-03 18:08
> The CI builds aren't running with the system msgpack library/headers installed

Is this essentially a gap in the tests therefore? 

Difficult to cover all bases I realise...

**Comment by jamessan** [comment] 2016-02-03 18:12
> Not really related, but I just saw that the Neovim debian package depends on libmsgpackc2>=0.5.1, I guess it should be >=1.0.

Well, it Build-Depends `libmsgpack-dev (>= 1.0.0)` and then during the build we determine that Neovim is only using symbols from the library which require the library version >= 0.5.1.  That's fine.  It's the difference between API and ABI.

**Comment by jamessan** [comment] 2016-02-04 13:43
@fwalch The initial idea I had was just to call `find_library` twice, once with `NO_DEFAULT_PATH` and then again without.  If the first found the library, then the second is a no-op, but I think I like your idea better.

> We could read the detected msgpack's version from msgpack/version_master.h,

I'll work on a PR for that.

**Comment by justinmk** [comment] 2016-02-06 17:47
Should be fixed by https://github.com/neovim/neovim/pull/4174. Please `rm -rf build/ .deps/; make` to test.

**Closed by justinmk** 2016-02-06 17:47 UTC
Labels: bug, buildsystem

**Comment by myitcv** [comment] 2016-02-08 08:29
Just tested against 827e267800417b8fdd1340d54f5dc5fa9d81bb92 on the [same system referenced above](https://github.com/neovim/neovim/issues/4108#issuecomment-179351908)

All works well with/without `libmsgpack-dev` installed:

```
...
-- Found Msgpack: /home/myitcv/dev/neovim-editor/.deps/usr/lib/libmsgpack.a (found suitable version "1.0.0", minimum required is "1.0.0")
...
```

(i.e. it always detects the system-installed version is not recent enough and so reverts to the `.deps` install)

Thanks all!
