### ISSUE TITLE
segmentation fault combining nvim_open_term/jobstart with lots of output

### ISSUE THREAD

**Issue by mfussenegger** [neovim/neovim#19075] opened 2022-06-24 12:02 UTC
### Neovim version (nvim -v)

Both 0.7.0 but also on master NVIM v0.8.0-dev+476-g3a4fa22ba

### Vim (not Nvim) behaves the same?

Untested

### Operating system/version

Linux

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

pacman for stable, CMAKE_BUILD_TYPE=RelWithDebInfo make from source

### How to reproduce the issue

Create a `/tmp/foo.py` with:

```python
for i in range(200000):
    print("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
```

Create the following lua function somewhere:

```lua
local api = vim.api
local M = {}

function M.foo()
  vim.cmd('split')
  local win = api.nvim_get_current_win()
  local jobid
  local bufnr = api.nvim_get_current_buf()
  local chan = api.nvim_open_term(bufnr, {
    on_input = function(_, _, _, data)
      if jobid then
        pcall(api.nvim_chan_send, jobid, data)
      end
    end,
  })
  local opts = {
    height = api.nvim_win_get_height(win),
    width = api.nvim_win_get_width(win),
    pty = true,
    on_stdout = function(_, data)
      api.nvim_chan_send(chan, table.concat(data, "\n"))
    end,
    on_exit = function(_, exit_code)
      api.nvim_chan_send(chan, '\r\n[Process exited ' .. tostring(exit_code) .. ']')
      api.nvim_buf_set_keymap(bufnr, "t", "<CR>", "<cmd>bd!<CR>", { noremap = true, silent = true})
    end,
  }
  jobid = vim.fn.jobstart({'/usr/bin/python', '/tmp/foo.py'}, opts)
end

return M
```

Run the function via `:lua require('module_you_put_the_file').foo()`. This should cause a crash. Might take a bit, try switching the window if it doesn't.

(This snippet is extracted & adjusted from nvim-dap, see also https://github.com/mfussenegger/nvim-dap/issues/589). 

### Expected behavior

No crash

### Actual behavior

Segmentation fault

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000558915cdb244 in on_text (
    bytes=0x7f0faee3c010 "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut a"..., len=17695014, user=0x5589176b4c00) at src/state.c:255
255	  (*encoding->enc->decode)(encoding->enc, encoding->data,
[Current thread is 1 (Thread 0x7f0fba61ad00 (LWP 3140576))]
(gdb) l
250	    state->gsingle_set     ? &state->encoding[state->gsingle_set] :
251	    !(bytes[eaten] & 0x80) ? &state->encoding[state->gl_set] :
252	    state->vt->mode.utf8   ? &state->encoding_utf8 :
253	                             &state->encoding[state->gr_set];
254	
255	  (*encoding->enc->decode)(encoding->enc, encoding->data,
256	      codepoints, &npoints, state->gsingle_set ? 1 : len,
257	      bytes, &eaten, len);
258	
259	  /* There's a chance an encoding (e.g. UTF-8) hasn't found enough bytes yet
```

**Comment by erw7** [comment] 2022-06-25 08:56
Duplicate of #16040.

**Closed** 2022-06-25 08:56 UTC
Labels: terminal, bug-crash, closed:duplicate
