### ISSUE TITLE
improper setting of 'lines' when resizing horizontally

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#5866] opened 2017-01-03 12:22 UTC
- `nvim --version`: 0.1.7
- Vim (version: ) behaves differently? ~~No~~ yes it works as expected.
- Operating system/version: macOS 10.12.2
- Terminal name/version: iTerm2 3.0.13
- `$TERM`: xterm-256color

### Actual behaviour
I am not sure of the specific conditions that cause this, but I managed to produce with `nvim -u NORC`.

https://asciinema.org/a/83bo4h7bj6bmvyhvya24kwdb0 

### Expected behaviour
`'lines'` should stay the same when resizing horizontally.

**Comment by nhooyr** [comment] 2017-01-03 12:22
Hm, asciinema doesn't show resizing properly. I'll record with quicktime.

**Comment by nhooyr** [comment] 2017-01-03 12:26
See https://asciinema.org/a/83bo4h7bj6bmvyhvya24kwdb0

**Comment by kalkin** [comment] 2017-01-13 18:22
@nhooyr 
> Vim (version: ) behaves differently? No

Actually it does. It works as expected and has no resize issues at least here on GNU Linux.

**Comment by kalkin** [comment] 2017-01-13 18:22
BTW same issue on GNU Linux with nvim 1.0.7

**Comment by nhooyr** [comment] 2017-01-13 18:38
@kalkin sorry I meant that the problem does not occur, i'll edit.

**Comment by kalkin** [comment] 2017-01-18 12:37
This bug is really annoying. My C programming knowledge isn't great, but just steer me in the right direction and I will try to fix it or gather more debugging information.

**Comment by kalkin** [comment] 2017-08-07 14:44
The weird thing is I can't reproduce this error anymore. Not on Fedora 24, 25 or Arch. @nhooyr do you still experience it?

**Comment by nhooyr** [comment] 2017-08-07 14:45
I only use Neovim over ssh right now (been using gogland) so I haven't been using it much. So I don't experience it, but that's probably only because I don't use it enough.

**Comment by justinmk** [comment] 2017-08-14 00:00
This may have been resolved by https://github.com/neovim/neovim/pull/6202/commits/6777b6ecbc7e70d1002e8c0ce149924259613df2 .

**Closed by justinmk** 2017-08-14 00:00 UTC
Labels: bug, tui
