### ISSUE TITLE
colorscheme changes on nightly

### ISSUE THREAD

**Issue by ayroblu** [neovim/neovim#28119] opened 2024-03-31 00:11 UTC
### Problem

I use https://github.com/overcache/NeoSolarized
It's one of those vim color schemes that is very old that is a fork of a very very old colorscheme that should basically never change. However I was making a contribution to treesitter that required nightly and I noticed that the color scheeme is different in nightly

| Before | After |
| ------------- | ------------- |
| <img width="624" alt="image" src="https://github.com/neovim/neovim/assets/4915682/ace7ef96-b623-451a-ad80-5de697676878"> | <img width="619" alt="image" src="https://github.com/neovim/neovim/assets/4915682/6884f51b-56b2-4031-88cf-566704d5fce5"> |

### Steps to reproduce

Open a file with treesitter (probably optional?)

### Expected behavior

Colorscheme stays the same

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2754+g12240600f-Homebrew

### Vim (not Nvim) behaves the same?

No

### Operating system/version

macOS 14.3.1

### Terminal name/version

alacritty 0.13.1 (fe2a3c5)

### $TERM environment variable

xterm-256color

### Installation

brew install neovim --head

**Comment by zeertzjq** [comment] 2024-03-31 00:16
Duplicate of #26378

**Closed by zeertzjq** 2024-03-31 00:16 UTC
Labels: bug
