### ISSUE TITLE
Changing window position from an `<expr>` mapping raises `E523`

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#7773] opened 2017-12-27 23:52 UTC
- `nvim --version`:      NVIM `v0.2.3-313-gdee78a4` Build type: RelWithDebInfo
 - Vim (version: ) behaves differently?
   Vim `8.0.1427` doesn't raise any error.
 - Operating system:     Ubuntu `16.04.3` LTS
 - Terminal emulator:    rxvt-unicode `v9.22`
 - Terminal multiplexer: tmux `2.3`
 - `$TERM`:              screen-256color
 - Shell:                zsh `5.3.1`

If I define a mapping using the `<expr>` argument:

    nno  <expr>  cd  Func()

    fu! Func()
        wincmd H
        return ''
    endfu

Then split a window and use the mapping, Neovim raises the error E523. In Vim no error is raised, and the focused window is moved on the far left of the screen as intended.

Is it:

 - a bug in Vim which allows the window to be moved, while it should be blocked?
 - a bug in Neovim which forbids the window to be moved, while it shouldn't be blocked?
 - a known and accepted incompatibility between Neovim and Vim?
 - an undocumented incompatibility?

I've read `:h vim-differences`, `:h map-<expr>`, `:h E523` and searched the issue tracker for `E523` without finding any discussion which seemed relevant, but I may have missed one/them.

**Comment by justinmk** [comment] 2017-12-28 13:40
`:helpgrep E523` finds this note:

> Note: While completion is active Insert mode can't be used recursively. Mappings that somehow invoke ":normal i.." will generate an E523 error.  

Otherwise searching for `e_secure` in the Nvim source gives the impression that this error signals cases where "textlock" is in effect.

```c
  // Don't allow changes in the buffer while editing the cmdline.  The                                                                                      
  // caller of getcmdline() may get confused.                                                                                                               
  if (textlock != 0) {                                                                                                                                      
    EMSG(_(e_secure));                                                                                                                                      
    return false;                                                                                                                                           
  } 
```

> an undocumented incompatibility?

It's not intentional. Could be a bug, most likely it's a missing Vim patch.

**Comment by jamessan** [comment] 2018-01-02 04:05
> Could be a bug, most likely it's a missing Vim patch.

It's [v8.0.0704](https://github.com/vim/vim/releases/tag/v8.0.0704).

**Comment by glacambre** [comment] 2021-06-05 17:15
Can't reproduce on master and the patch isn't among the list of patches that need to be ported anymore, so let's close this :).

**Closed by glacambre** 2021-06-05 17:15 UTC
Labels: bug
