### ISSUE TITLE
Restore cursor no longer works. `Buffer 0 not found`

### ISSUE THREAD

**Issue by lmburns** [neovim/neovim#19196] opened 2022-07-01 19:35 UTC
### Neovim version (nvim -v)

NVIM v0.8.0-dev+532-g60604d6a9 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include Compiled by runner@fv-az124-413  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

No, VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 28 2022 16:22:51)

### Operating system/version

Linux archbox 5.18.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:01 +0000 x86_64 GNU/Linux

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

tmux-256color

### Installation

Use [`bob`](https://github.com/MordechaiHadad/bob) version manager

### How to reproduce the issue

If you create an `autocmd` to restore your cursor like such:

```lua
local group = vim.api.nvim_create_augroup("RestoreCursor", true)
vim.api.nvim_create_autocmd(
    "BufReadPost",
    {
        pattern = "*",
        group = group,
        callback = function()
            local row, col = unpack(vim.api.nvim_buf_get_mark(0, '"'))
            if {row, col} ~= {0, 0} and row <= vim.api.nvim_buf_line_count(0) then
                vim.api.nvim_win_set_cursor(0, {row, 0})
                if vim.fn.line("w$") ~= row then
                    vim.cmd("norm! zz")
                end
            end
        end
    }
)
```

Or even if you use the suggested `autocmd` for `restore-cursor`, like such:

```vim
autocmd BufRead * autocmd FileType <buffer> ++once
  \ if &ft !~# 'commit\|rebase' && line("'\"") > 1 && line("'\"") <= line("$") | exe 'normal! g`"' | endif
```

An error occurs.

### Expected behavior

The expected behavior is for the cursor position to be restored.

### Actual behavior

This is the error:

```
Error detected while processing BufReadPost Autocommands for "*":

Error executing lua callback: /home/lucas/.config/nvim/lua/autocmds.lua:301: Cursor position outside buffer
stack traceback:
        [C]: in function 'set_cursor'
        /home/lucas/.config/nvim/lua/autocmds.lua:301: in function </home/lucas/.config/nvim/lua/autocmds.lua:283>

Error executing lua callback: ...bob/nightly/nvim-linux64/share/nvim/runtime/filetype.lua:17: Vim(lua):E5108:
Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114:
Missing quote: "Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:155: Vim(append):
Error executing lua callback: /home/lucas/.config/nvim/lua/autocmds.lua:301: Cursor position out side buffer stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_buf_set_option'
        ...bob/nightly/nvim-linux64/share/nvim/runtime/filetype.lua:17: in function <...bob/nightly/nvim-linux64/share/nvim/runtime/filetype.lu
a:14>
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        ...bob/nightly/nvim-linux64/share/nvim/runtime/filetype.lua:17: in function <...bob/nightly/nvim-linux64/share/nvim/runtime/filetype.lu
a:14>
```

In Vim, using the following `autocmd` works just fine:

```vim
augroup jump_last_position
  autocmd!
  autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
augroup END
```

However, when trying to use this same `autocmd` in Neovim, it does not work.

This is the error for the last `autocmd`:

```
Error detected while processing BufReadPost Autocommands for "*":
E92: Buffer 0 not found
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:155: Vim(normal):E92: Buffer 0 not found
Please check your config for correctness
```

**Comment by seandewar** [comment] 2022-07-01 19:37
Duplicate of #19173

**Closed by seandewar** 2022-07-01 19:37 UTC
Labels: bug
