### ISSUE TITLE
0.10 colorscheme flickering

### ISSUE THREAD

**Issue by sarmong** [neovim/neovim#28667] opened 2024-05-08 11:39 UTC
### Problem

There are a few conditions when colorscheme flickers when launching neovim. By flickering I mean that it between changin background from terminal background to neovim background, there is a period of time when the background is black.

I think it is somewhat related to #19362 . These only reproduce on nightly, 0.9.5 is fine.

### Steps to reproduce

For any of this, run `nvim --clean -u minimal.lua` with the contents of `minimal.lua` described below.

#### termguicolors

After setting `termguicolor`, background switches to black before switching to the user-defined one. Run with `sleep` to pause on black background, or with some synchronous code to see flickering.

I know that `termguicolors` is enabled automatically in 0.10, however this causes 0.9 configs to flicker and people waste time debugging. Also, I don't know how this works under the hood, but automatic setting of `termguicolors` seems to happen after `init.lua` is loaded, because `vim.o.termguicolors` returns `false` if printed inside user config (when not set manually).

```lua
vim.opt.termguicolors = true
-- vim.cmd.sleep(1)
vim.fn.system("notify-send loading")

vim.cmd.colorscheme("blue")
```

#### VimEnter

If you have a VimEnter autocommand with any synchronous action, the same thing happens. There are 3 cases. 

If you run (1) - you will see the same effect as with `termguicolors` - background switches to black. 
If you run (2) - you may see very subtle flickering of the screen. I choose `fn.system` as a generic synchronous side-effect. The same happens with `system():wait`.
If you run (3) - no flickering. The same is described in https://github.com/neovim/neovim/issues/19362#issuecomment-1924993842

```lua
vim.api.nvim_create_autocmd("VimEnter", {
	callback = function()
		--[[ (1) ]] vim.cmd.sleep(1)
		--[[ (2) ]] vim.fn.system("notify-send vimenter")
		--[[ (3) ]] vim.print("asdf")
	end,
})
vim.cmd.colorscheme("blue")
```

#### unnamedplus

Same flickering, however you cannot pause on it by running `sleep`, maybe it happens at different point in time. But, if you run synchronous commands, then you can see the flickering.

```lua
vim.opt.clipboard = "unnamedplus"
vim.fn.system("notify-send loading")
vim.cmd.colorscheme("blue")
```

### Expected behavior

No flickering like on 0.9.5. 

### Neovim version (nvim -v)

0.10.0-dev-3097+g064f3e42e

### Operating system/version

Linux/X11

### Terminal name/version

Tested on: kitty + tmux; kitty; wezterm; alacritty

### $TERM environment variable

Respectively^: tmux-256color; xterm-kitty; xterm-256color; alacritty

### Installation

Build from repo

**Comment by gpanders** [comment] 2024-05-08 13:11
This looks similar to https://github.com/neovim/neovim/issues/26372 which was fixed in https://github.com/neovim/neovim/pull/26381. I can't reproduce this on https://github.com/neovim/neovim/commit/8bb5089974e14f043a0b0c17e4d38dbd0b9a9ab2 but I can on current master, so I think this might have regressed.

**Comment by gpanders** [comment] 2024-05-08 13:14
Bisected to 037ea6e786b5d05f4a8965e4c2ba6aa60ec7c01a. cc @luukvbaal

**Comment by zeertzjq** [comment] 2024-05-08 13:24
I don't think you are bisecting correctly. The previous commit have the same behavior.

**Comment by gpanders** [comment] 2024-05-08 13:26
> I don't think you are bisecting correctly. The previous commit has the same behavior.

I am bisecting correctly. Please read my edit.

**Comment by zeertzjq** [comment] 2024-05-08 13:28
I can't understand your edit. Are you using your own config for bisecting instead of the ones mentioned in this issue?

**Comment by gpanders** [comment] 2024-05-08 13:36
I've found a separate but similar issue, which I at first thought was the same. I'll open a separate issue for this.

**Closed** 2024-05-10 18:01 UTC
Labels: bug
