### ISSUE TITLE
Do not use statusline as horizontal split when laststatus=0 is used.

### ISSUE THREAD

**Issue by soupbowl** [neovim/neovim#20583] opened 2022-10-10 22:57 UTC
### Feature already in Vim?

No

### Feature description

Hello,

It would be nice if laststatus=0 used the nice horizontal split separator 
that laststatus=3 uses instead of using a statusline.

How to reproduce the issue
~~~
nvim -clean
:set laststatus=0
:h tab
~~~

![This is an image](https://i.imgur.com/sEuqeEW.png)

To see laststatus=3 behaviour
~~~
nvim -clean
:set laststatus=3
:h tab
~~~

![This is an image](https://i.imgur.com/U27HOsX.png)

Thanks for looking.

**Comment by zeertzjq** [comment] 2022-10-10 23:00
Duplicate of #20221

**Closed by zeertzjq** 2022-10-10 23:00 UTC
Labels: enhancement
