### ISSUE TITLE
nvim opens in command mode with random text

### ISSUE THREAD

**Issue by UtkarshKunwar** [neovim/neovim#14934] opened 2021-06-29 20:03 UTC
- `nvim --version`: v0.5.0-dev+1455-gf83c25942
- Operating system/version: ssh to Ubuntu 20.04 headless
- Terminal name/version: Konsole 17.12.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```

### Actual behaviour
`:2626/3232/3838^G` is printed in the command line whenever nvim is opened. The mode on opening is command mode and not the default normal mode. Same behaviour with own init.vim, with NORC and with NONE. With own init.vim, the message becomes `:.rgb:2626/3232/3838^G`. It's always the same string. This does not happen in `nvim stable 0.4.4`.

![Screenshot_20210629_225106](https://user-images.githubusercontent.com/14164924/123859572-7d11b400-d92d-11eb-94c5-001d0bbbd977.png)

### Expected behaviour
No text in command mode on opening nvim.

**Comment by justinmk** [comment] 2021-07-01 20:03
duplicate of https://github.com/neovim/neovim/issues/10131

**Closed by justinmk** 2021-07-01 20:03 UTC
Labels: bug
