### ISSUE TITLE
Port parts of #243 to allow using Lua code in core

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#3823] opened 2015-12-11 23:55 UTC
Wanted to log this separately, maybe someone wants to pick it up? I'm a bit hesitant to mark this as `entry-level`, though :grinning: 

From https://github.com/neovim/neovim/issues/1646#issuecomment-163359173:

> There is also an option to finally start using lua and port xxd to lua: parts of the #243 which execute lua code without parts that translate VimL may be ported for this purpose.

**Comment by ZyX-I** [comment] 2015-12-12 01:23
Specifically needed

1. src/nvim/viml/executor/converter.\*
2. src/nvim/viml/executor/executor.\* (basically everything from …/executor/*, except for …/executor/vim.lua)
3. src/nvim/viml/executor/luaapi.lua (missing: implementation of Vim lua API based on msgpack API which is available through `api` global)
4. scripts/msgpack-gen.lua (AFAIR it is some other generator script, renamed and extended to generate code which creates `api` global)
5. scripts/generate_vim_module.lua, modified to generate luaapi module in the same fashion. …/executor.c should be modified to use this generated module.
6. Changes to src/nvim/CMakeLists.txt regarding generators and executor.
7. Changes to ex_cmds.lua and some related files I do not know to recreate `lua*` commands family.
8. Changes to eval.c to recreate `luaeval()`.
9. Changes to documentation regarding incompatibilities or a few additions to executor code that will make `vim.eval` work as intended (note: `vim.eval` in lua is the same thing as `vim.bindeval` in Python. But `vim.bindeval` is no longer supported. And cannot be supported using only existing msgpack API.) (note2: `vim.eval` used to be basically the same thing as `vim.eval` in Python. But if_lua author cared about backwards compatibility less then I did, so we see `vim.eval` in lua being an equivalent of `vim.bindeval` and `vim.eval`+`vim.bindeval` pair in Python).

**Comment by justinmk** [comment] 2017-12-23 14:19
Addressed in #4411

**Closed by justinmk** 2017-12-23 14:19 UTC
Labels: enhancement
