### ISSUE TITLE
Setting cursorline on InsertEnter shifts cursor position by 1 after i_CTRL-O

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#5805] opened 2016-12-21 13:04 UTC
- `nvim --version`: v0.2.0-150-g33319b1b
- Vim (version: 8.0.86) behaves differently!

### Actual behaviour
When setting `cursorcolumn` or `cursorline` during `InsertEnter` `ifoo<c-o>:echo<cr>bar` inserts `fobaro`, but it should be `foobar`.

I've noticed this with the [cursorcross](https://github.com/mtth/cursorcross.vim) plugin, and vim-plugs lazy-loading (https://github.com/junegunn/vim-plug/issues/543#issuecomment-256075296).

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:autocmd InsertEnter * setlocal cursorcolumn
:call feedkeys("ifoo\<c-o>:echom 1\<cr>bar")
```

This works correctly in Vim.

**Comment by Shougo** [comment] 2016-12-21 21:53
Can you check the old Vim version?
It may be fixed in the Vim patches.

**Comment by blueyed** [comment] 2016-12-21 22:00
Not an issue with Vim 7.3.429.

**Comment by Shougo** [comment] 2016-12-21 22:03
It seems neovim related problem.

**Comment by brcolow** [comment] 2016-12-21 22:45
Is it possible that this failure is related to this issue?:

```
From test_alot.vim:
Found errors in Test_cursorhold_insert():
function RunTheTest[9]..Test_cursorhold_insert line 6: Expected 1 but got 0
```

**Comment by Shougo** [comment] 2016-12-21 22:50
I think it is related.

**Comment by brcolow** [comment] 2016-12-21 22:52
Interesting..so when did this test start breaking on master? Can anyone bisect?

**Comment by blueyed** [comment] 2016-12-22 19:14
> FWIW, I can reproduce with nocursorline as well, or number. But it doesn't work for all options.. weird bug.

Sounds a bit like https://github.com/vim/vim/issues/1297 then maybe?!

**Comment by mhinz** [comment] 2016-12-22 19:26
Hmm, no. That patch doesn't make a difference.

**Comment by blueyed** [comment] 2016-12-22 20:32
Yeah, I know (it is a recent one) - it sounds just like some options trigger different behavior internally - and therefore might be handled wrongly in Neovim?!

Is there a existing test for this?  Test_cursorhold_insert?
Then it would be trivial to find the problem using `git bisect run <cmd>...` (by moving this test into a separate file).

**Comment by mhinz** [comment] 2016-12-22 23:44
Amusingly you get the correct result when also using `set virtualedit+=onemore` with the test case mentioned above.

**Comment by justinmk** [comment] 2016-12-29 18:41
Should be fixed on master.

**Comment by mhinz** [comment] 2016-12-29 18:49
Nope, I'm still able to reproduce it with the steps given in the top post.

**Comment by glacambre** [comment] 2021-06-05 12:22
I can't reproduce this bug on master, so let's close this issue :)

**Closed by glacambre** 2021-06-05 12:22 UTC
Labels: bug
