### ISSUE TITLE
LSP: Omnisharp: Intellisense broken in Unity project when creating or renaming files 

### ISSUE THREAD

**Issue by Lap1n** [neovim/neovim#14042] opened 2021-03-02 03:59 UTC
- `nvim --version`: NVIM v0.5.0-dev+1115-gc1fbc2ddf
- What language server (If the problem is related to a specific language server): Omnisharp
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): It works in vscode
- Is the problem isolated to a particular language server: Not sure
- Operating system/version: Ubuntu 20.04

### How to reproduce the problem from neovim startup
- Create a new Unity project
- Open the project in Neovim
- Add or rename a file from Neovim

### Actual behaviour
Intellisense and completion is broken when creating or renaming files with Omnisharp (only in the new file) in the Unity project. For example, LSP won't recognise the "using UnityEngine" statement.

It will still work in other files in the project, but the LSP client won't recognise the new class added. The only way to fix this is to restart the language server.
I'm not sure is this bug is related to Unity or omnisharp, but it works fine in VS Code.

Note that in the case of a small dotnet CLI project, it seems to work.

### Expected behaviour
Intellisense and completion should continue to work when creating or renaming files with Omnisharp. 
### Minimal init.vim or init.lua and code sample
My config looks like this : 

```lua
nvim_lsp.omnisharp.setup {
    cmd = {omnisharp_bin, "--languageserver", "--hostPID", tostring(pid)},
}
```

**Comment by mjlbach** [comment] 2021-03-18 19:28
Try using the newly merged create/rename/delete functions in https://github.com/neovim/neovim/pull/14144

@mfussenegger Is there anything else we should be doing about this?

**Comment by mfussenegger** [comment] 2021-03-19 09:35
> Is there anything else we should be doing about this?

Maybe the [DidChangeWatchedFilesClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWatchedFiles) would be needed to improve this.

**Comment by mjlbach** [comment] 2021-03-19 09:58
That's a good idea, one nit is that it will require dynamicRegistration support, which I started and gave up on a couple months ago.

```
export interface DidChangeWatchedFilesClientCapabilities {
	/**
	 * Did change watched files notification supports dynamic registration.
	 * Please note that the current protocol doesn't support static
	 * configuration for file changes from the server side.
	 */
	dynamicRegistration?: boolean;
}
```

**Comment by dmbfm** [comment] 2021-06-15 01:21
> Try using the newly merged create/rename/delete functions in #14144
How do we use these functions?

**Comment by FTenner** [comment] 2021-08-02 10:42
> > Try using the newly merged create/rename/delete functions in #14144
> 
> How do we use these functions in this case?

I, too, am curious.

**Comment by mfussenegger** [comment] 2021-08-03 18:44
> > > Try using the newly merged create/rename/delete functions in #14144
> > 
> > 
> > How do we use these functions in this case?
> 
> I, too, am curious.


One example where Language servers like eclipse.jdt.ls use these extra create/rename/delete capabilities is if you use the `vim.lsp.buf.rename()` function on a class name. If you rename the class, the language server will also rename the file - because In Java top level class name and file name must match.

These functions can otherwise not be used directly by users, but are only there in case the language server wants to make changes to files. `rename` is one example. Code actions could be another case where a language server may use them.

**Comment by neovim-discourse** [comment] 2021-08-22 11:24
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/lsp-with-omnisharp-need-to-restart-neovim-when-adding-new-flies/603/2

**Comment by mjlbach** [comment] 2021-09-11 05:30
I need a step by step reproduction of the issue in order to debug this. Starting with preferably a non-unity project, but if that is absolutely necessary, steps from creating a unity project to reproducing OPs issue.

**Comment by cseickel** [comment] 2021-09-11 13:32
One problem I've had with omnisharp in the past which took me forever to figure out was that you need to be careful about dotnet sdk versions. If you have 5.0 installed on your path and you are working on a 3.1 project, you get a buggy LSP experience. That could explain why it worked with a quick cli project, you might likely generated a new project using a matching platform to what is installed.

There is a way to get at the omnisharp logs, which is likely crucial to diagnosing this problem. I think that's how I figured out my sdk version issue.

The problem is more likely to be with omnisharp than neovim. Omisharp is powerful but buggy, like everything else Microsoft makes. It's just as buggy on VS Code so it's not a (neo)vim issue.

**Closed** 2021-09-11 14:03 UTC
Labels: bug, lsp

**Comment by mjlbach** [comment] 2021-09-11 19:56
@cseickel in this case, I think that sending `textDocument/didOpen` is not sufficient for omnisharp to pick up a new project file, and we need to send an explicit didCreateFiles notification to the server https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#workspace_didCreateFiles

I pinged the omnisharp devs on slack, hoping to hear back.

**Comment by ChimpSpin** [comment] 2021-10-06 12:21
> One problem I've had with omnisharp in the past which took me forever to figure out was that you need to be careful about dotnet sdk versions. If you have 5.0 installed on your path and you are working on a 3.1 project, you get a buggy LSP experience. That could explain why it worked with a quick cli project, you might likely generated a new project using a matching platform to what is installed.
> 
> There is a way to get at the omnisharp logs, which is likely crucial to diagnosing this problem. I think that's how I figured out my sdk version issue.
> 
> The problem is more likely to be with omnisharp than neovim. Omisharp is powerful but buggy, like everything else Microsoft makes. It's just as buggy on VS Code so it's not a (neo)vim issue.

VS code works properly in this case. You can create new files and lsp works as expected without having to restart or even give unity focus.

**Comment by mjlbach** [comment] 2021-10-19 04:51
Hey! Just wanted to say I haven't forgotten about this, I filed an upstream issue with omnisharp-rosyln. https://github.com/OmniSharp/omnisharp-roslyn/issues/2250

**Comment by mjlbach** [comment] 2022-01-25 20:45
> Intellisense and completion is broken when creating or renaming files with Omnisharp (only in the new file) in the Unity project. For example, LSP won't recognise the "using UnityEngine" statement.

> It will still work in other files in the project, but the LSP client won't recognise the new class added. The only way to fix this is to restart the language server.
I'm not sure is this bug is related to Unity or omnisharp, but it works fine in VS Code.

I looked into this some more, you *always* need to regenerate your solution file from unity when you add a new file. VsCode appears to work correctly because it silences the error, but if you create a new *.cs file in a Unity project without regenerating the solution file, you will find that UnityEngine provides no completion results, hover, etc.

**Comment by dmbfm** [comment] 2022-01-25 20:49
> I looked into this some more, you _always_ need to regenerate your solution file from unity when you add a new file. VsCode appears to work correctly because it silences the error, but if you create a new *.cs file in a Unity project without regenerating the solution file, you will find that UnityEngine provides no completion results, hover, etc.

That is my experience as well. But after regenerating the solution I need to restart the LSP server as well. Maybe vscode does that automatically? And here I'm running into another issue as well. `LspRestart` does not seem to work correctly. In fact `LspStop` does not work, and every time I exit Neovim I have an orphan `mono` process open. What I am doing currently is to kill `mono` manually and then calling `LspStart`.

**Comment by mjlbach** [comment] 2022-01-25 20:57
> Maybe vscode does that automatically?

Based on the logs, I don't think so. I believe it is likely sending a `workspace/didChangedWatchedFiles` notification to inform the server that the solution file has changed. None of this is documented in omnisharp or the extension as far as I know, and it's unclear how to surface the RPC messages to see.

> ? And here I'm running into another issue as well. LspRestart does not seem to work correctly. In fact LspStop does not work, and every time I exit Neovim I have an orphan mono process open. What I am doing currently is to kill mono manually and then calling LspStart.

This is unrelated to this issue. `LspStart/Restart` are provided as conveniences via lspconfig (not here). LspStop merely asks the language server to shut down, if it refuses to self terminate that is a bug in the language server.

**Comment by Domeee** [comment] 2022-02-25 10:44
Hi @mjlbach

I'm working on https://github.com/Domeee/com.cloudedmountain.ide.neovim, a code editor integration for supporting neovim as code editor for unity.

Unity .NET based solution synchronization for vscode, rider, etc. is handled via unity packages. The project I'm working on does handle solution synchronization if you are working with neovim as unity code editor. E.g. ensuring `<Compile Include="{filename}" />` entries.

My current problem with my Unity/Neovim workflow is the exact same issue as described by you here https://github.com/OmniSharp/omnisharp-roslyn/issues/2250#issue-1029857334

Is there anything I can help with?

**Comment by niscolas** [comment] 2022-07-22 19:17
So, any updates on this?
I've researched the topic for a while now, but I still didn't find a solution for it

**Comment by dmbfm** [comment] 2022-07-23 00:43
> So, any updates on this? I've researched the topic for a while now, but I still didn't find a solution for it

Same here. From what I gather, a plugin inside Unity that talks to neovim/lsp is necessary to achieve this. All other editors in which this works, like visual studio, vscode and JetBrains Raider have a Unity plugin as well.

**Comment by niscolas** [comment] 2022-07-23 02:24
Even with a package in the Unity side like this: https://github.com/the-argus/com.unity.ide.neovim I wasn't able to make it work.
It basically functions automates the process of clicking in the "Regenerate project files" button, similar to the Rider package for instance (it was originally forked from it). 
It seems that something else is needed

**Comment by niscolas** [comment] 2022-07-23 02:31
I **think** that this is directly related to these other issues:
- https://github.com/neovim/neovim/issues/17808
- https://github.com/OmniSharp/omnisharp-roslyn/issues/2250

**Comment by remzisenel** [comment] 2024-01-03 11:28
I got frustrated enough with this feature created a workaround plugin for unity so it "regenerates project files" and then sends a :LspRestart command to Unity when the project files require an omnisharp restart: https://github.com/remzisenel/com.remzisenel.ide.neovim

You still need to focus Unity for the plugin to trigger the regeneration.

It is still quite frustrating as omnisharp takes 3 years to restart, but, hey - at least it is automated.

Feel free to customise the sent command from at `NeovimEditor/Editor/Integration/NvimIntegration.cs` if you have a different setup for LSP capabilities.

**Comment by apyra** [comment] 2025-04-22 13:08
The Ultimate, multiplatform solution, Use Neovim as Code Editor for unity [nvim-unity](https://github.com/apyra/nvim-unity.git) , sync the project files automaticaly: [nvim-unity-sync](https://github.com/apyra/nvim-unity-sync.git), Great workflow!
