### ISSUE TITLE
noexpandtab is not honored when filetype=python

### ISSUE THREAD

**Issue by giuscri** [neovim/neovim#8112] opened 2018-03-07 16:05 UTC
- `nvim --version`:
```
NVIM v0.2.3-788-g1d5eec2c6
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/g/hack/neovim/build/config -I/home/g/hack/neovim/src -I/home/g/hack/neovim/.deps/usr/include -I/usr/include -I/home/g/hack/neovim/build/src/nvim/auto -I/home/g/hack/neovim/build/include
Compiled by g@x220

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- Vim (version: `8.0`) behaves differently? yes, like the expected behaviour.
- Operating system/version: Arch Linux x86/64
- Terminal name/version: `GNOME Terminal 3.26.2 Using VTE version 0.50.3 +GNUTLS`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`
- `:set noet`
- insert tab

### Actual behaviour
4 spaces are inserted.

### Expected behaviour
1 tab is inserted

**Comment by jamessan** [comment] 2018-03-07 16:23
Duplicate of #3786.

`:help ft-python-plugin`

**Closed by jamessan** 2018-03-07 16:23 UTC
