### ISSUE TITLE
Exit when tab pressed after deleting already open completion list

### ISSUE THREAD

**Issue by theowen** [neovim/neovim#7289] opened 2017-09-18 18:35 UTC
- `nvim --version`:
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Vim (version: 8.0 ) behaves differently? yes
- Operating system/version: Arch Linux
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:a<tab>^W<tab>
```

### Actual behaviour

nvim exits with no output

### Expected behaviour

nothing happens

**Comment by jamessan** [comment] 2017-09-18 18:51
Duplicate of #6650

**Closed by jamessan** 2017-09-18 18:51 UTC
