### ISSUE TITLE
Put ( set clipboard=unnamed ) does not work well in Mac OS X (^_^;;

### ISSUE THREAD

**Issue by callmekohei** [neovim/neovim#8272] opened 2018-04-14 00:10 UTC
- `nvim --version`: NVIM v0.2.3-dev
- Vim (version: ) behaves differently?: Yes
- Operating system/version: Mac OS X / ProductVersion 10.13.4 ( BuildVersion 17E199 )
- Terminal name/version: Terminal / 2.8.2 ( 404 )
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
$ nvim -u NORC

: set clipboard=unnamed
```

yank ( -- VISUAL BLOCK -- ) at left of `baz space`
`<C-v> j j $ y`
```
 baz |
 --- |
 ccc |
```
put at right of `| foo | bar |`
```
| foo | bar |
| --- | --- |
| aaa | bbb |
```

### Actual behaviour
```
| foo | bar |
 baz |
 --- |
 ccc |
| --- | --- |
| aaa | bbb |
```

### Expected behaviour
```
| foo | bar | baz |
| --- | --- | --- |
| aaa | bbb | ccc |
```

**Comment by callmekohei** [comment] 2018-04-14 00:24
see also

https://github.com/neovim/neovim/issues/7815

**Comment by callmekohei** [comment] 2018-04-14 06:05
# workaround

put with unnamed registers `""`

```
""p
```

**Comment by callmekohei** [comment] 2018-04-14 06:43
see also

https://github.com/neovim/neovim/issues/1822#issuecomment-233152833

**Comment by justinmk** [comment] 2018-04-14 08:45
duplicate of #1822

**Closed by justinmk** 2018-04-14 08:45 UTC
