### ISSUE TITLE
:terminal image position is not bound by the Vim window 

### ISSUE THREAD

**Issue by htfy96** [neovim/neovim#4056] opened 2016-01-20 13:48 UTC
Steps:
1. Open nvim in gnome-terminal
2. `:T w3m http://www.baidu.com`

![2016-01-20 21-34-52](https://cloud.githubusercontent.com/assets/8121231/12450475/ec6a7640-bfbe-11e5-99bb-e4effb0d42b0.png)

The image should be displayed in the top-left corner of the right window instead of the whole terminal. I'm not sure whether this is a bug of gnome-terminal or Neovim.

Version:
```
NVIM v0.1.2-220-g3b94756
Build type: Dev
Compilation: /usr/lib/ccache/bin/cc -march=native -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/yaourt-tmp-lz/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-lz/aur-neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/yaourt-tmp-lz/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-lz/aur-neovim-git/src/neovim-git/build/include
Compiled by lz@lz

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by lucc** [comment] 2016-01-23 09:56
It's not limited to gnome terminal. I can reproduce on urxvtc and xterm. But for me the vertical position is correct. Only the horizontal position is messed up (like above).

**Comment by DarkDefender** [comment] 2016-02-26 15:38
I'm guessing it is like this because the image display hack doesn't know it is in a split or even inside neovim. So it tried to output the image as if it were running in a normal terminal window.

I'm guessing the same problem will happen if you run it inside tmux with splits and so on.

**Comment by justinmk** [comment] 2016-02-26 16:22
> I'm guessing the same problem will happen if you run it inside tmux with splits and so on.

I was about to ask the same thing, inspired by your comment :)

@htfy96 @lucc Does the image get positioned correctly while running in tmux (or GNU screen) split panes?

**Comment by fmoralesc** [comment] 2016-02-26 16:34
![captura de pantalla de 2016-02-26 17-34-00](https://cloud.githubusercontent.com/assets/221465/13358344/24f46bb2-dcaf-11e5-8f3b-0ae29b9e908a.png)

**Comment by DarkDefender** [comment] 2016-02-26 17:00
@fmoralesc thanks for the image, I did some quick GIMPing and it looks like I guessed correctly:
![24f46bb2-dcaf-11e5-8f3b-0ae29b9e908a](https://cloud.githubusercontent.com/assets/312503/13359128/dd472d28-dcb2-11e5-91da-f7555eeb38ce.png)

**Comment by fmoralesc** [comment] 2016-02-26 17:08
Yep: 
![captura de pantalla de 2016-02-26 18-08-39](https://cloud.githubusercontent.com/assets/221465/13359336/fc65f0b2-dcb3-11e5-96a7-3d24e339a867.png)

**Comment by lucc** [comment] 2016-02-27 00:02
urxvt + tmux = same problem

**Comment by justinmk** [comment] 2016-02-27 00:19
Thanks. It seems this is a limitation of w3m or whatever mechanism it uses internally. If there's something needed on our end, we can reopen this, but otherwise we can consider this out of scope.

**Closed by justinmk** 2016-02-27 00:19 UTC
Labels: :term, invalid

**Comment by wsdjeg** [comment] 2016-02-27 01:19
I can not see pic in terminal ,even if I use w3m http://www.baidu.com in gnome-terminal,I think it is a issue with my terminal

**Comment by lucc** [comment] 2016-02-27 06:34
@wsdjeg you can use xterm or urxvt. It should work there.

**Comment by wsdjeg** [comment] 2016-02-27 06:53
I am using ubuntu ,by default the termianl is gnome-terminal,I will have a try with these two app

**Comment by wsdjeg** [comment] 2016-02-27 06:54
xtem works well ,but in ubuntu xterm looks very ugly
