### ISSUE TITLE
lsp: synchronization bottleneck due to buf_get_lines (caused by line-by-line changes)

### ISSUE THREAD

**Issue by doubleloop** [neovim/neovim#11867] opened 2020-02-13 21:48 UTC
- `nvim --version`: v0.5.0-346-g406464fa6
- `vim -u DEFAULTS` (version: ) behaves differently? NA
- Operating system/version: Debian testing
- Terminal name/version: alacritty 0.4.2-dev
- `$TERM`: screen-256color
- clangd version 9.0.1-8

### Steps to reproduce
testinit.vim:
```vim
call plug#begin('~/.local/share/nvim/plugged')
  Plug 'neovim/nvim-lsp'
call plug#end()
lua require('nvim_lsp').clangd.setup{}
```
script.vim (parts from neoformat, 99-104 are some random lines):
```vim
function! s:deletelines(start, end) abort
    silent! execute a:start . ',' . a:end . 'delete _'
endfunction

let lines_after = getbufline(bufnr('%'), 104, '$')
let lines_before = getbufline(bufnr('%'), 1, 99)
let new_buffer = lines_before + ['whatever'] + lines_after
call s:deletelines(len(new_buffer), line('$'))
call setline(1, new_buffer)
```
run
```sh
$ build/bin/nvim -u testinit.vim src/nvim/eval.c # or other big c file (~10k lines)
```
then in vim:
```vim
:source script.vim
```

### Actual behaviour
Nvim freezes (100% cpu load) until finally
`PANIC: unprotected error in call to Lua API (not enough memory)` is returned. The issue does not occur when `lua require('nvim_lsp').clangd.setup{}` is not called

### Expected behaviour
Script finishes without vim crash

**Comment by justinmk** [comment] 2020-02-14 08:35
Maybe LSP needs to debounce (more)? cc @norcalli

**Comment by norcalli** [comment] 2020-02-14 09:16
Well this would probably be fixed by having proper incremental support. Right now we are sending the whole file due a bug in the on_line callback events. It was sending incorect information and I have a PR open for that which demonstrates a failing test case.

I imagine what's happening is that it's changing multiple times in quick succession and then getting the whole file each time for the textDocument notification.

We did consider debouncing as well, but punted it because it wasn't high priority at the time.

Good to know, though.

PS, clangd can do the formatting for you via the LSP, if you want a meantime solution. @doubleloop 
`vim.lsp.buf.formatting()`
Thanks for the detailed bug report.

**Comment by doubleloop** [comment] 2020-02-14 13:22
> PS, clangd can do the formatting for you via the LSP,

Nice, juste enabled it and it is really cool. 

Just as a side note (maybe will be helpful for someone), currently `range_formatting` is using `<` and `>` marks which points to previous selection (not current), so visual mapping should contain `<esc>`, for example:
```
vnoremap <leader>= <esc><cmd>lua vim.lsp.buf.range_formatting()<cr>
```

Otherwise:
```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/callbac
ks.lua:223: RPC UnknownErrorCode message =  "Line value can't be negative (-1)"
```

**Comment by supermarin** [comment] 2020-04-24 10:12
This also happens with `sourcekit-lsp` when editing even a small swift file.

**Comment by norcalli** [comment] 2020-08-11 15:31
I wrote a little debounce utility function and I'm trying to decide if I should add that to core first or release it on nvim-lsp. I'm leaning towards core first since there's no rush and people tend to update neovim master frequently-ish if they're using nvim-lsp anyway. Then I can make a follow up PR to add debounce to the LSP either as an option or as a built-in with a very very tiny timeout like 1ms.

**Comment by acomagu** [comment] 2020-09-06 10:03
Same error after editing for a minute.
(nvim v0.5.0-660-g2cea6ab01 with typescript-language-server)

https://imgur.com/a/2pznjGE

Same problem?

**Comment by bry-guy** [comment] 2020-09-16 05:34
I'm seeing this issue frequently while editing Ruby projects with Solargraph enabled via `nvim-lsp`. Not sure how I can best provide a more thorough bug report (gather logs/profiling, etc.), but happy to do so with any pointers. Thanks for your contributions :)

**Comment by pyrho** [comment] 2020-10-22 15:04
Same issue with NVIM v0.5.0-763-geaee3d929 and typescript-language-server.
The error is thrown from [here](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/rpc.lua#L561) with the message: 
```
Error executing luv callback:
~/.local/share/nvim/runtime/lua/vim/lsp/rpc.lua:561: not enough memory
```

Happy to help debug this, I tried with `nvim -V20vimlog` but the verbose file doesn't contain anything useful about the issue.

**Comment by acomagu** [comment] 2020-10-22 15:43
@pyrho Hi, I wrote a patch to improve the memory usage on receiving huge JSON from LSP server few days ago. Could you try to see if it solves your situation?

https://github.com/acomagu/neovim/commit/09c237c13c20f4df7b1a06f353574e910408da46

**Comment by pyrho** [comment] 2020-10-22 16:07
@acomagu On it thanks! will report in this comment.

**Comment by acomagu** [comment] 2020-11-06 10:31
@pyrho Oh, I have not noticed your edit. Thank you!

I'm glad to know the patch works well on other environment. I'll create a PR for it before long.

I leave this issue open because I'm not sure that it's also same problem.

**Comment by pyrho** [comment] 2020-11-17 10:14
ftr, I have not been using your patch lately and I don't seem to experience the issue anymore.

**Comment by acomagu** [comment] 2020-11-17 15:40
@pyrho Yeah I know it. It's good to know limiting completion results also solves this issue, without any lag, for everyone here(including me!) I didn't feel something bad and thank you for clarifying 👍

**Comment by mjlbach** [comment] 2021-03-10 06:08
@doubleloop is this still an issue if you use incremental sync? #14079 was just merged which you can try with:

```
nvim_lsp = require('lspconfig')
nvim_lsp.clangd.setup {
    on_init = function(client)
        client.config.flags = {}
        if client.config.flags then
          client.config.flags.allow_incremental_sync = true
        end
    end;
 }
```

**Comment by ibraheemdev** [comment] 2021-03-15 21:29
I am having the same issue with rust-analyzer.

**Comment by mjlbach** [comment] 2021-03-15 21:33
Can you all reliably reproduce this and provide an example file?

**Comment by ttys3** [comment] 2021-03-24 12:04
I encountered this too. but I do not know the re-produce steps.

with gopls enabled, I delete some chars sometime, got `PANIC: unprotected error in call to Lua API (bad callback)`


```shell
❯ nvim --version
NVIM v0.5.0-dev+1175-g1186f7dd9
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/ttys3/.config/nvim/neovim/build/config -I/home/ttys3/.config/nvim/neovim/src -I/home/ttys3/.config/nvim/neovim/.deps/usr/include -I/usr/include -I/home/ttys3/.config/nvim/neovim/build/src/nvim/auto -I/home/ttys3/.config/nvim/neovim/build/include
Compiled by ttys3@ttys3

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by roddyyaga** [comment] 2021-08-06 22:51
II'm also getting this problem with neoformat/ocamlformat on a large file (https://github.com/roddyyaga/xobl/blob/e7191dc147b4f14ff643a68dd423e0f78e71f5a6/generated/xcb.ml).

**Comment by mjlbach** [comment] 2021-08-06 23:36
@roddyyaga Did you try enabling debounce_text_changes as described in the lspconfig readme?

**Comment by roddyyaga** [comment] 2021-08-07 12:33
@mjlbach I have now, still get the error though. I'm running `NVIM v0.5.0-dev+1101-g1caf58578`.

**Comment by mjlbach** [comment] 2021-10-05 17:03
@roddyyaga Can you try building from master?

**Comment by doubleloop** [comment] 2021-10-06 00:05
>@doubleloop is this still an issue if you use incremental sync? #14079 was just merged (and is now enabled by default)

Sorry for late response. Just tested master ([neovim](https://github.com/neovim/neovim/commit/acd5e831b6294e54b12c09983bee3da89c0f183a) and [lspconfig](https://github.com/neovim/nvim-lspconfig/commit/66659884c36dadd1f445f9012fcf4e7600286d3e)) and the issue still exists (nvim becones not responsive, `<c-c>` does not work, 100% cpu load). Tested using exactly same procedure as originally described with slightly adjusted testinit.vim:
```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'neovim/nvim-lspconfig'
call plug#end()

lua << EOF
require('lspconfig').clangd.setup {
  cmd = { 'clangd-11', '--background-index' },
  flags = { debounce_text_changes = 150, }
}
EOF
```

**Comment by mjlbach** [comment] 2021-10-06 00:15
No worries, thanks for the update!  I tried reproducing, and although neovim hangs for a few seconds, it doesn't panic. 

github.com/mjlbach/minimal_repro_11867

Let me look into the hang to see if there is something obvious we can do to fix it.

**Comment by doubleloop** [comment] 2021-10-06 00:28
> although neovim hangs for a few seconds, it doesn't panic.

True, it doesn't panic any more, it just takes ~30 seconds on my machine to complete.

**Comment by mjlbach** [comment] 2021-10-06 00:30
> True, it doesn't panic any more, it just takes ~30 seconds on my machine to complete.

Still something we can fix. I think the general performance improvements I've made have just mitigated the issue (at least a step in the right direction for now).

**Comment by doubleloop** [comment] 2021-10-06 00:59
just a note: single run of this repro generates 3,7M of logs in ~/.cache/nvim/lsp.log (using default log lvl, WARN). It consists mainly from this 3 lines repeated:

```
[ERROR][2021-10-06 02:18:30] .../vim/lsp/rpc.lua:431	"rpc"	"clangd-11"	"stderr"	"E[02:18:30.100] Failed to update /home/doubleloop/src/neovim/src/nvim/eval.c: Change's rangeLength (62) doesn't match the computed range length (60).\nI[02:18:30.100] <-- textDocument/didChange\n"
[ERROR][2021-10-06 02:18:30] .../vim/lsp/rpc.lua:431	"rpc"	"clangd-11"	"stderr"	"E[02:18:30.100] Trying to remove file from TUScheduler that is not tracked: /home/doubleloop/src/neovim/src/nvim/eval.c\nE[02:18:30.100] Failed to update /home/doubleloop/src/neovim/src/nvim/eval.c: Trying to do incremental update on non-added document: /home/doubleloop/src/neovim/src/nvim/eval.c\nI[02:18:30.100] <-- textDocument/didChange\n"
[ERROR][2021-10-06 02:18:30] .../vim/lsp/rpc.lua:431	"rpc"	"clangd-11"	"stderr"	"I[02:18:30.100] <-- textDocument/didChange\nE[02:18:30.100] Trying to remove file from TUScheduler that is not tracked: /home/doubleloop/src/neovim/src/nvim/eval.c\nE[02:18:30.100] Failed to update /home/doubleloop/src/neovim/src/nvim/eval.c: Trying to do incremental update on non-added document: /home/doubleloop/src/neovim/src/nvim/eval.c\nI[02:18:30.100] <-- textDocument/didChange\nE[02:18:30.100] Trying to remove file from TUScheduler that is not tracked: /home/doubleloop/src/neovim/src/nvim/eval.c\nE[02:18:30.100] Failed to update /home/doubleloop/src/neovim/src/nvim/eval.c: Trying to do incremental update on non-added document: /home/doubleloop/src/neovim/src/nvim/eval.c\n"
```

**Comment by dmitmel** [comment] 2021-11-13 17:49
Minimal repro:

```vim
set rtp+=~/.config/nvim/plugged/nvim-lspconfig
lua <<EOF
require('lspconfig').clangd.setup({
  flags = { debounce_text_changes = 150 },
})
EOF

function! Test() abort
  let start = reltime()
  call setline(1, getline(1, '$'))
  echomsg reltimefloat(reltime(start))
endfunction
```

Edit `src/nvim/eval.c`, run `:call Test()`.

**Comment by mjlbach** [comment] 2022-01-16 21:07
Just to restate what the issue is:

The bottleneck for incremental sync is here: 
https://github.com/neovim/neovim/blob/09d270bcea5f81a0772e387244cc841e280a5339/runtime/lua/vim/lsp.lua#L368

The bottleneck for full sync is here: https://github.com/neovim/neovim/blob/09d270bcea5f81a0772e387244cc841e280a5339/runtime/lua/vim/lsp.lua#L377

Under normal circumstances, this is cheap/fast. When using a formatting option like rustformat (from rust.vim), or the example in the issue, changes are applied line by line. This fetches the entire buffer text on each iteration of on_lines, which causes the lag.

The solutions are:
1. Switch to on_bytes (not ready yet) which can provide the text of the last change directly
2. make buf_get_text faster
3. add an outer debounce (completely bypass getting the buffer text until the next debounce window storing first/lastline to keep the current change tracking logic intact)
4. optimize buf_get_text to only get the changed ranges (see https://github.com/neovim/neovim/pull/16277)

1 is currently blocked see https://github.com/neovim/neovim/issues/14093

I'm not sure if 2 is possible.

When I benchmarked it, 4 did not make that much of a difference using the reproduction in this thread.

That leaves us with 3, which IMO is the best solution.

**Comment by mjlbach** [comment] 2022-01-17 16:22
This was closed by @dmitmel in https://github.com/neovim/neovim/pull/17118

**Closed by mjlbach** 2022-01-17 16:22 UTC
Labels: bug, lsp
