### ISSUE TITLE
Some emojis aren't rendered with recent Kitty versions

### ISSUE THREAD

**Issue by xfzv** [neovim/neovim#28733] opened 2024-05-13 15:15 UTC
### Problem

Starting with Kitty 0.33.1 (I didn't try 0.33.0 because the ebuild is no longer available in Gentoo repositories but considering the [changelog](https://sw.kovidgoyal.net/kitty/changelog/), I guess it might have started with 0.33.0), some emojis are no longer rendered.

According to [Kitty maintainer](https://github.com/kovidgoyal/kitty/issues/7329#issuecomment-2046467830), this isn't an issue with Kitty but with Vim/Neovim. Downgrading Kitty to 0.32.1 solves the issue for me. I cannot reproduce with WezTerm (`x11-terms/wezterm-20240203.110809-r1` from Gentoo repositories).

[Equivalent bug report in Vim repository](https://github.com/vim/vim/issues/14590), although I couldn't reproduce with vim 9.0.2167 on my end.

Occurs with both 0.9.5 and 0.10 here, as long as I'm using Kitty >=0.32.1:

```console
% nvim -v
NVIM v0.9.5

% nvim -v
NVIM v0.10.0-dev-3121+ge3ec97432-dirty
```

### Steps to reproduce

1. Add some emojis to a text file:

```console
:arrow_up:
:arrow_left:
:arrow_down:
:arrow_right:
:arrow_up_small:
:arrow_double_up:
:arrow_up_down:
:arrow_forward:
:arrows_clockwise:
:arrow_down_small:
:arrow_double_down:
:arrow_backward:
:arrow_upper_left:
:arrow_lower_left:
:arrow_right_hook:
:arrow_heading_up:
:arrow_upper_right:
:arrow_lower_right:
:arrow_heading_down:

⬆️
⬅️
⬇️
➡️
🔼
⏫
↕️
▶️
🔃
🔽
⏬
◀️
↖️
↙️
↪️
⤴️
↗️
↘️
⤵️
```

2. Open the file with:

```console
% nvim --clean a.txt
```

- With Kitty 0.32.2, all emojis are rendered:
![kitty_0 32 2](https://github.com/neovim/neovim/assets/78810647/5dc09186-45b3-44cf-9d10-9cc855d3cc49)

- With Kitty 0.34.1, only some emojis aren't rendered:
![kitty_0 34 1](https://github.com/neovim/neovim/assets/78810647/e762ea6b-a0bb-4837-9f11-650693b475cc)

I used some emojis starting with "a" for demonstration purpose but many other emojis are not rendered with 0.34.1.

### Expected behavior

All emojis are rendered with Kitty >=0.32.1

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3121+ge3ec97432-dirty Build type: Release LuaJIT 2.1.0-beta3 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

no, 9.0.2167

### Operating system/version

Gentoo

### Terminal name/version

kitty 0.34.1

### $TERM environment variable

xterm-kitty

### Installation

from Gentoo repositories (`app-editors/neovim`)

**Comment by zeertzjq** [comment] 2024-05-13 15:23
Duplicate of #7151

**Closed by zeertzjq** 2024-05-13 15:23 UTC
Labels: bug
