### ISSUE TITLE
[crash] Assertion failed (ctx->parent_handle->poll_ctx == ctx), function timer_cb, file fs_poll.c, line 177. Abort trap: 6

### ISSUE THREAD

**Issue by mg979** [neovim/neovim#22424] opened 2023-02-27 00:02 UTC
### Problem

    Assertion failed (ctx->parent_handle->poll_ctx == ctx), function timer_cb, file fs_poll.c, line 177. 
    Abort trap: 6

I'm getting these consistently in this moment, because I was trying out stuff that caused an error at nvim start.
They seem to happen after a tabpage change, but not immediately (much less than a second anyway). I know it's vague.

![Schermata 2023-02-27 alle 00 51 35](https://user-images.githubusercontent.com/26169924/221445245-713bb5ff-2824-4180-9766-b0cb78b9666d.png)

I'm not sure it's related to this error, I saw this crash before in the last week, but now I can crash almost at will.

![Schermata 2023-02-27 alle 00 56 54](https://user-images.githubusercontent.com/26169924/221445311-95f2b5fa-afd3-483a-b9a2-82e43dcfff60.png)

### Steps to reproduce

I don't have a minimal reproducible case.

### Expected behavior

No crash.

### Neovim version (nvim -v)

0.8.3 (release)

### Vim (not Nvim) behaves the same?

I doubt it

### Operating system/version

macOS 12.6.3

### Terminal name/version

wezterm 20221119-145034-49b9839f

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by zeertzjq** [comment] 2023-02-27 00:08
Duplicate of #19731

**Closed by zeertzjq** 2023-02-27 00:08 UTC
Labels: needs:repro, bug-crash

**Comment by zeertzjq** [comment] 2023-02-27 00:09
Duplicate of #19371

**Comment by mg979** [comment] 2023-02-27 00:14
I also use gitsigns, if it matters.
