### ISSUE TITLE
:messages API

### ISSUE THREAD

**Issue by izelnakri** [neovim/neovim#29391] opened 2024-06-18 15:55 UTC
### Problem

As it stands today, `:messages` command output is hackable in lua, however there is *no way* to be able to obtain/hack the output of the **last command** in lua, **or any command for that matter**. I've read all the possible documentation on this subject, please let me know if there is a way to achieve this. One cannot associate a certain command that has been run in the past to certain output/historical message(s) neither, although neovim keeps such information under the hood without exposing it publicly. 

This significantly reduces the surface area of neovim customizability. Therefore, I think it is a bug rather than a feature request. We must have `:message` command available in Ex in addition to `:messages`. 

- There is *no way* to get the output of `g<` in a buffer with lua in neovim today.
- Today `:messages` command outputs all messages in history **with no separation**/indicator between outputs, for any developer to be able to determine what were the last messages of a certain command.
- In fact, today as it seems neovim doesn't expose this information publicly in the runtime. The data is hidden inside `void show_sb_text(void) {}` of `src/nvim/message.c`
- In functional tests of neovim this data is tested against a very custom/private/internal `Screen::assert()` test method. Example of its usage is in: `test/functional/ui/messages_spec.lua: < shows blank line from :echo properly'`

This limits the possibility to customize the UI of `g<` and developers cannot build advanced execution plugins/behavior like:
- Select only certain area of a lua file in existing buffer, run it and show the output on a vertical split.
- Show the last command output that I had run few seconds ago with `:`, show it on a separate window, without leaving my current buffer position, without using `g<`.

### Steps to reproduce

nvim file.txt

`:=vim.print({'a', 'b', 'c'})`

Hit enter.

No way to determine what was the last output of a command. `:messages` shows all the gathered messages without any proper separator to be able to obtain the last output(not the line, entire output) in lua.

### Expected behavior

`:message` command, that outputs `g<` so `vim.fn.execute`, `vim.api.exec2() ` can get this string output in lua.

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

Linux x1-carbon 6.9.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 20:17:17 +0000 x86_64 GNU/Linux

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

tmux-256color

### Installation

nixpkgs

**Comment by justinmk** [comment] 2024-06-18 22:46
I agree we need a structured API. But that seems to conflict with the request for a `:message` command specifically, since that's not really structured. Also, this request is too limited. We need something more general. The entire messages history should be available, plus timestamps, highlights, log-level, etc.

Partially related to https://github.com/neovim/neovim/pull/7062

**Comment by justinmk** [comment] 2024-06-18 22:56
Duplicate of https://github.com/neovim/neovim/issues/22478

**Closed by justinmk** 2024-06-18 22:56 UTC
Labels: enhancement, api, messages
