### ISSUE TITLE
messagepack socket in /run

### ISSUE THREAD

**Issue by Yamakaky** [neovim/neovim#2552] opened 2015-05-01 08:39 UTC
The /tmp/nvim* socket should be moved to $XDG_RUNTIME_DIR (/run/user/1000 for me).

**Comment by Pyrohh** [comment] 2015-05-01 18:39
I think this is tangentially related to #78, so should probably be mentioned there.

**Comment by Yamakaky** [comment] 2015-05-01 19:13
Oh yes, sorry.

**Comment by splinterofchaos** [comment] 2015-05-01 19:30
Is the issue that this should be the default location? After all, one can set `$NVIM_LISTEN_ADDRESS` to really anything.

The listen address defaults to a temp file, and all of vim's temp files go in that `/tmp/(n)vim*/` directory. Perhaps the issue is that vim's temp dir is `/tmp`, in which case #78 is definitely the issue to track.

**Comment by Pyrohh** [comment] 2015-05-01 19:41
> Perhaps the issue is that vim's temp dir is /tmp, in which case #78 is definitely the issue to track.

I believe that is it, as @Yamakaky just commented in #78. I'll close this.

**Closed by Pyrohh** 2015-05-01 19:41 UTC
