### ISSUE TITLE
macOS Catalina 10.15 search tag appear "E432: Tags file not sorted"

### ISSUE THREAD

**Issue by johnlamb** [neovim/neovim#11196] opened 2019-10-10 18:25 UTC
<img width="957" alt="Screenshot 2019-10-10 at 20 27 19" src="https://user-images.githubusercontent.com/8145875/66596042-714fee00-eb9c-11e9-92d3-44d493506fe6.png">

- `nvim --version`:
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
- `vim -u DEFAULTS` (version: ) behaves differently?
No
- Operating system/version:
macOS Cataline 10.15
- Terminal name/version:
iTerm 3.3.6 and macOS Terminal
- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
Use the built in help :h
EIther with or without a topic

```

### Actual behaviour
Gives:
E432: Tags file not sorted: /usr/local/Cellar/neovim/0.4.2/share/nvim/runtime/doc/tags
E432: Tags file not sorted: /usr/local/Cellar/neovim/0.4.2/share/nvim/runtime/pack/dist/opt/matchit/doc/tags
when a topic is supplied and
E432: Tags file not sorted: /usr/local/Cellar/neovim/0.4.2/share/nvim/runtime/doc/tags
when help is started without a topic.
### Expected behaviour
No errors.

### Notes
This is a marked issue in Vim (https://github.com/vim/vim/issues/5039) as well.
Same issue using macOS builtin ctags, homebrews ctags and homebrews universal-ctags.
Issue persist when --HEAD is installed.

**Comment by mhinz** [comment] 2019-10-10 19:03
FWIW, I can't reproduce it at all, no matter which ctags implementation is used. So, there's probably other conditions needed as well. 

I'm really just guessing here, but did you do the typical `xcode-select --install` after upgrading? Xcode often effects a lot of parts in magical ways and it's the only other thing I did after upgrading.

**Comment by dm1try** [comment] 2019-10-11 00:31
`echo "a\ta\ta\nb\tb\tb\nc\tc\tc\nd\td\td\n" > tags && nvim -c 'tag a'`
this onliner is minimal reproducible example on my side. I'm unable to debug atm.
<img width="445" alt="Screen Shot 2019-10-11 at 03 31 16" src="https://user-images.githubusercontent.com/486807/66615979-a0378580-ebd7-11e9-83fd-496e129c64d0.png">

**Comment by dm1try** [comment] 2019-10-11 00:33
reproducible example -> echo "a\ta\ta\nb\tb\tb\nc\tc\tc\nd\td\td\n" > tags && nvim -c 'tag a'

**Comment by mhinz** [comment] 2019-10-11 00:48
Hmm, that works for me, too. I just get the expected `E429: File "a" does not exist`.

**Comment by dm1try** [comment] 2019-10-11 00:52
@mhinz that's interesting)
<img width="894" alt="Screen Shot 2019-10-11 at 03 50 48" src="https://user-images.githubusercontent.com/486807/66616681-7764bf80-ebda-11e9-9627-274e7b93712c.png">

**Comment by mhinz** [comment] 2019-10-11 00:55
Correction: `echo "a\ta\ta\nb\tb\tb\nc\tc\tc\nd\td\td\n" > tags && nvim -u NORC -c 'tag a'` _does_ throw `E432: Tags file not sorted: tags` as well.

(But I still can't reproduce it with just `nvim -u NORC` after a fresh `brew install neovim`.)

**Comment by mhinz** [comment] 2019-10-11 00:58
Ah.. of course.. can't reproduce it with:

```
nvim -u NORC -c 'set ignorecase | tag a'
```

**Comment by dm1try** [comment] 2019-10-11 01:53
offset calculation in binary search algorithm is broken somehow
<img width="780" alt="Screen Shot 2019-10-11 at 04 50 11" src="https://user-images.githubusercontent.com/486807/66618706-d9c1be00-ebe2-11e9-8786-a3601a33fa52.png">

**Comment by griffinqiu** [comment] 2019-10-11 01:57
Vim has the same problem after upgrade to macOS 10.15

https://github.com/vim/vim/issues/5039

**Comment by dm1try** [comment] 2019-10-11 14:23
the problem is here, on Catalina the returned value is `-1`
https://github.com/neovim/neovim/blob/401398bc4b07301e8f7ad6c288dbc799624b1a2d/src/nvim/tag.c#L1378-L1380
<img width="681" alt="Screen Shot 2019-10-11 at 17 22 45" src="https://user-images.githubusercontent.com/486807/66659243-c860cc00-ec4b-11e9-8e2f-9acb95d5d05f.png">

**Comment by dm1try** [comment] 2019-10-11 15:24
ok guys,
something is going wrong in underlying FIO
this dirty patch works(re-open the tag file for reading), but I have no time; will continue tomorrow
```patch
diff --git a/src/nvim/tag.c b/src/nvim/tag.c
index 6fe3efbaa..39021fbf1 100644
--- a/src/nvim/tag.c
+++ b/src/nvim/tag.c
@@ -1372,6 +1372,7 @@ find_tags (
         if (state == TS_BINARY || state == TS_SKIP_BACK) {
           /* Adjust the search file offset to the correct position */
           search_info.curr_offset_used = search_info.curr_offset;
+          fp = freopen((char *)tag_fname, "r", fp);
           vim_fseek(fp, search_info.curr_offset, SEEK_SET);
           eof = vim_fgets(lbuf, LSIZE, fp);
           if (!eof && search_info.curr_offset != 0) {
```

**Comment by mhinz** [comment] 2019-10-11 15:56
What I don't get is why `vim_fseek(fp, 12, SEEK_SET)` (and thus `fseeko()`) returns `-1` at all. Errno gets set to _invalid argument_.

But as far as I see, all the arguments are valid. I checked the stream with `ferror()`/`feof()` and the tags file is certainly bigger than 12 bytes.

**Comment by dm1try** [comment] 2019-10-11 16:06
> Errno gets set to invalid argument.

@mhinz maybe `fp` is not "valid" anymore? I'm not sure how to properly check this, but it looks like re-opening the file helps.

**Comment by dm1try** [comment] 2019-10-11 20:19
I've made the minimal reproducible example outside Neovim codebase; see `fgets/lseek`
```c
#include <stdio.h>
#include <unistd.h>

int main(){
  char lbuf[256];

  FILE *p = fopen("/Users/dmitrydedov/projects/sandbox/tags", "r");
  // those calls lead to "broken"(?) file pointer
  fgets(lbuf,255, p);
  lseek(fileno(p), 0L, SEEK_SET);

  fseek(p, 10, SEEK_SET);

  int pos = ftell(p);
  printf("pos: %d\n", pos);
  return 0;
}
```
<img width="238" alt="Screen Shot 2019-10-11 at 23 17 24" src="https://user-images.githubusercontent.com/486807/66682258-51442b80-ec7d-11e9-822a-305af93e155e.png">

**Comment by dm1try** [comment] 2019-10-11 20:29
using `fseek` instead of `lseak` fixes the problem, btw
the new patch:
```patch
diff --git a/src/nvim/tag.c b/src/nvim/tag.c
index 6fe3efbaa..fd0a8e057 100644
--- a/src/nvim/tag.c
+++ b/src/nvim/tag.c
@@ -1512,7 +1512,7 @@ line_read_in:
             if ((filesize = vim_lseek(fileno(fp), (off_T)0L, SEEK_END)) <= 0) {
               state = TS_LINEAR;
             } else {
-              vim_lseek(fileno(fp), (off_T)0L, SEEK_SET);
+              vim_fseek(fp, 0, SEEK_SET);

               /* Calculate the first read offset in the file.  Start
                * the search in the middle of the file. */
```

**Comment by dm1try** [comment] 2019-10-12 22:09
I sent the bug report to Apple, though it's not clear when the bug will be fixed(it exits in 10.15.1 Beta too).

btw `fseek` works because it calls `__sflush` while doing its work, while `lseek` looks like more low-level thing.

so either `fseek` or `flush+lseek` will help. should I open a PR with that workaround for Catalina or we will wait for the action from Apple?

**Comment by mhinz** [comment] 2019-10-13 16:28
Catalina clearly has lots of issues around I/O. E.g. https://github.com/Homebrew/homebrew-core/pull/44715 or https://github.com/fink/fink/issues/197.

Why was `lseek()` instead of `fseek()` used in the first place? (aka. Why mixing standard I/O with file I/O?) I don't see much point in that opposed to other uses of `lseek()` in `fileio.c` or `memline.c`, which work on file descriptors anyway.

No matter how long Apple needs to fix their stuff, if there are no pressing arguments against replacing both `lseek()` in `tag.c` by `fseek()`, I'd go that route.

**Comment by mhinz** [comment] 2019-10-13 17:19
@dm1try 

Just make a PR for it. If Vim later decides to wait for Apple or goes another route, we can change it again to stay in sync.

It's an annoying bug that probably a lot of users experience at the moment, so let's just get that fix in now. Maybe we can even get it into the next 0.4.3 release, so it gets picked up by Homebrew as well.

**Closed** 2019-10-14 11:58 UTC
Labels: bug, bug-vim, platform:macos, vim-patch

**Comment by dm1try** [comment] 2019-12-18 01:41
FYI, I've received  the response from Apple
>Hi Dmitry,
>
>Buffered (fgets) and unbuffered fd operations should not be mixed unless `fflush` is called to >synchronise the `FILE *` state with the file pointer. `fseek` should have been used here, as >pointed out.

**Comment by andmarti1424** [comment] 2021-05-22 13:32
Hello. I am still getting this issue but im on Arch Linux. I get this error on nvim `NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser`
but it works OK on
`VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 16 2021 18:44:28)
Included patches: 1-2859`
btw my tags file is sorted. generated by `ctags --sort=foldcase -R`
thank you.

**Comment by jamessan** [comment] 2021-05-26 00:44
@andmarti1424 Since 0.4.4 contains the fix for this issue, it's likely a separate problem and will need to be debugged separately from this.  You should create a new issue with specific steps on how to reproduce the problem you're experiencing.
