### ISSUE TITLE
indent (php) dont correct indent php embedded in html code #neovim#nvim 

### ISSUE THREAD

**Issue by truongtd94** [neovim/neovim#23079] opened 2023-04-14 05:57 UTC
### Problem

when I put php opening tag in html code it automatically jumps to the beginning of the line, i want the php code to be at the same level as the html code.
Broblem Images:
https://github.com/truongtd94/errors/blob/master/2023-04-14_12-38.png
https://github.com/truongtd94/errors/blob/master/2023-04-14_12-39.png

### Steps to reproduce

Write php embedded in html tag
It automatically jumps to the beginning of the line
Finally, Format it with phpcsfixer, wrong indentation.

### Expected behavior

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.14.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Debian 10.2.1-6) 10.2.1 20210110
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "5.10.0-21-amd64",
  sysname = "Linux",
  version = "#1 SMP Debian 5.10.162-1 (2023-01-21)"
}

## Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - css                 ✓ . ✓ ✓ ✓
  - dart                ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - phpdoc              ✓ . . . .
  - query               ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - sql                 ✓ . . . ✓
  - vim                 ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

8.1

### Operating system/version

debian 11

### Terminal name/version

xfce4-terminal

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by lewis6991** [comment] 2023-04-14 12:35
Neovim core does not yet support or even implement treesitter indentation.

**Comment by lucario387** [comment] 2023-04-14 12:42
It's a duplicate of nvim-treesitter/nvim-treesitter#2565, so this can be closed

**Closed** 2023-04-14 13:57 UTC
Labels: bug
