### ISSUE TITLE
6x times slower startup than VIM on same config

### ISSUE THREAD

**Issue by petRUShka** [neovim/neovim#11143] opened 2019-10-02 21:44 UTC
[vim-orgmode](https://github.com/jceb/vim-orgmode) plugin works on Neovim 6x times slower than on Vim with exactly same config. Benchmarking via `--startuptime` option.

So bare nvim/vim sharing the config with each other consisting of only one plugin (and one dependency plugin). Opening with them same huge file (10000 lines) very different process in sense of speed.

- `nvim --version`:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
Features: +acl +iconv +tui
```
- `vim -u DEFAULTS` (version: ) behaves differently? Yes. It's 6x times faster.
- Operating system/version: Arch linux
- Terminal name/version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u vimrc_minimal`

vimrc_minimal:
```vim
set nocompatible
set runtimepath^=~/.vim runtimepath+=~/.vim/after
call plug#begin('~/.vim/plugged')
Plug 'jceb/vim-orgmode'
Plug 'tpope/vim-speeddating'
call plug#end()

set iskeyword+=:

filetype plugin indent on
syntax enable
```
File to open: 

test.org
```orgmode
* Tasks
** TODO My task number 1
** TODO My task number 1
** TODO My task number 1
...
```
So it is basically 10000 times repeated line `** TODO My task number 1`

### Actual behaviour
`nvim -u vimrc_minimal test.org --startuptime nvim.log`
nvim.log: http://dpaste.com/11M4AHP

Quotation from nvim.log:
```
...
122.485  000.004: editing files in windows
15381.376  15258.891: VimEnter autocommands
...
```

### Expected behaviour

`vim -u vimrc_minimal test.org --startuptime vim.log`
vim.log: http://dpaste.com/2MKVM5P

```
...
057.128  000.002: editing files in windows
2616.079  2558.951: VimEnter autocommands
...
```

**Comment by blueyed** [comment] 2019-10-03 05:09
Is vim-speeddating required to trigger it?

It would be better to have profiling output (see `:h :profile`), which would then show more information about where the time is spent.

**Comment by justinmk** [comment] 2019-10-03 05:37
vim-orgmode is written in python. Until proven otherwise, this is almost certainly a duplicate of #1898 / #7063.

see also

-  https://github.com/neovim/neovim/issues/4522#issuecomment-205013308
-  https://github.com/neovim/neovim/issues/8876#issuecomment-414357105
-  https://github.com/neovim/neovim/issues/9135#issuecomment-430585870

**Closed by justinmk** 2019-10-03 05:37 UTC
Labels: bug, performance

**Comment by petRUShka** [comment] 2019-10-03 06:52
You are right. It should be python.

Quotation from profile log:
```
FUNCTION  provider#python3#Call()
    Defined: /usr/share/nvim/runtime/autoload/provider/python3.vim line 26
Called 10007 times
Total time:  14.891349
 Self time:  14.840843
```

**Comment by justinmk** [comment] 2019-10-03 07:02
Note that vim-orgmode could probably fix this by simply getting buffer contents in a batch, doing its work, then sending the updates in a batch. Instead of going back-and-forth from Vim to Python.
