### ISSUE TITLE
nvim_win_get_option() returns invalid values for 'scrolloff' and 'sidescrolloff'

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#13964] opened 2021-02-17 22:24 UTC
- `nvim --version`: NVIM v0.5.0-dev+1093-g4bc74c243
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: Ubuntu 20.04.2
- Terminal name/version: Konsole 19.12.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```vim
nvim -u NORC

" command 1: check 'scrolloff' with nvim_win_get_option()
:echo nvim_win_get_option(0, 'scrolloff')

" command 2: check 'scrolloff' with :setl
:setl scrolloff?

" command 3: check 'sidescrolloff' with nvim_win_get_option()
:echo nvim_win_get_option(0, 'sidescrolloff')

" command 4: check 'sidescrolloff' with :setl
:setl sidescrolloff?

" command 5: set 'scrolloff' with nvim_win_set_option(), using output from nvim_win_get_option()
call nvim_win_set_option(0, 'scrolloff', nvim_win_get_option(0, 'scrolloff'))

" command 6: set 'sidescrolloff' with nvim_win_set_option(), using output from nvim_win_get_option()
call nvim_win_set_option(0, 'scrolloff', nvim_win_get_option(0, 'scrolloff'))

```

### Actual behaviour

Commands 1 and 3 output `140730054174776`.

Commands 2 and 4 output `-1`.

Commands 5 and 6 result in the following errors:

```
E5555: API call: Value for option 'scrolloff' is out of range
```
```
E5555: API call: Value for option 'sidescrolloff' is out of range
```

### Expected behaviour

Expected that command 1's output would match command 2's, and that command 3's output would match command 4's.

Expected that the output from `nvim_win_get_option` could be used as input for `nvim_win_set_option` for commands 5 and 6.

**Comment by dstein64** [comment] 2021-02-26 06:22
I checked which value is reported using `vim.wo.scrolloff` from Lua.

```
:lua print(vim.wo.scrolloff)
```

This outputs `5384718`, which matches neither `140730054174776` (from `nvim_win_get_option` above) nor `-1` (from `setl`).

I tried using `nvim_win_get_option` again, which this time reported a different output, `140729295266120`. I then confirmed that the outputs changes on each invocation of Neovim. However, `vim.wo.scrolloff` appears to remain fixed at `5384718`.

**Comment by dstein64** [comment] 2021-03-04 17:46
> "However, vim.wo.scrolloff appears to remain fixed at 5384718."

I've updated my Neovim to `v0.5.0-dev+1116-gbda12927b` since that last comment. When I just tried this again, the output was `5308061`, so the value is not fixed at `5384718`, as I had initially thought. However, it does appear to now remain fixed at `5308061`.

Calling `vim.api.nvim_win_get_option` from Lua results in the same value as `vim.wo.scrolloff`, as opposed to matching the correct `setlocal` value or the incorrect `nvim_win_get_option` value from outside the context of Lua.

**Comment by dstein64** [comment] 2021-06-23 20:15
As of 1a1fe58f7e947abb3c6389a98b17ad54f18c353f, `nvim_win_get_option(0, 'scrolloff')` and `nvim_win_get_option(0, 'sidescrolloff')` return 0. This differs from `140730054174776` reported above, but still does not match the expected value, `-1`.

`:lua print(vim.wo.scrolloff)` outputs `1.4041364345741e+14`.

**Comment by dstein64** [comment] 2021-06-23 22:28
The issue may have something to do with `global-local` options. For example, `lua print(vim.bo.undolevels)` outputs 1.3975481990029+14, in contrast to `-123456` for `setl undolevels?` (tested after first using `enew` to get to a buffer where `undolevels` was not yet set).

**Comment by gpanders** [comment] 2021-09-23 01:17
Duplicate of #14670.

**Closed by gpanders** 2021-09-23 01:17 UTC
Labels: bug

**Comment by mg979** [comment] 2022-02-20 20:09
vim.wo.scrolloff is still bugged (returns `94009804178418` to me).

**Comment by gpanders** [comment] 2022-02-20 20:51
Please open a new issue with a reproducible test case.
