### ISSUE TITLE
Visual asterisk doesn't work properly if text contains `/` char

### ISSUE THREAD

**Issue by onlyfortesting** [neovim/neovim#24406] opened 2023-07-20 07:57 UTC
### Problem

Visual asterisk doesn't work properly if text contains `/` char.

### Steps to reproduce

nvim --clean

On visual mode try selecting text that has `/` char, then press `*`

e.g. `border-t-black/10`

Resulting command is `/\Vborder-t-black/+10` which is not correct

### Expected behavior

Resulting command should be `/\Vborder-t-black\/10`

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

I believe vim doesn't have this feat

### Operating system/version

Archlinux

### Terminal name/version

rxvt-unicode (urxvt) v9.31 

### $TERM environment variable

tmux-256color

### Installation

pacman

**Comment by zeertzjq** [comment] 2023-07-20 08:45
Duplicate of #21676

**Closed by zeertzjq** 2023-07-20 08:45 UTC
Labels: bug
