### ISSUE TITLE
Ubuntu 17.10 wrong installation guide

### ISSUE THREAD

**Issue by flofriday** [neovim/neovim#7476] opened 2017-11-01 19:14 UTC
The description on how to install neovim on Ubuntu 17.10 does not work. 
The description tells to add a ppa, however the ppa does not work.
The solution is to skip the adding of the ppa since it seams to be already in the main repository of Ubuntu and just install it.

## Current (Wrong) Description
```
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
sudo apt-get install neovim
```
## Working Description
```
sudo apt-get install neovim
```
## Further Information
I am not sure if this is a Ubuntu 17.10 specific issue, but that ist the only version of Ubuntu I tried.

**Comment by justinmk** [comment] 2017-11-02 09:50
duplicate of https://github.com/neovim/neovim/issues/7418

**Closed by justinmk** 2017-11-02 09:50 UTC
