### ISSUE TITLE
Checkhealth  warns about colors not working properly when using tmux's new `terminal-features` option to set TC support

### ISSUE THREAD

**Issue by jjant** [neovim/neovim#21819] opened 2023-01-15 13:07 UTC
### Describe the bug

The [tmux faq says that we can now use `set-option -as terminal-features ",gnome*:RGB"` in your tmux config](https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-a-256-colour-terminal) to enable TrueColor support. 
However, if we use `terminal-features`, `:checkhealth nvim` reports that colors will not work correctly and says to use `set-option -ga terminal-overrides`.

### Steps to reproduce

Put this in your `tmux.conf` (assuming your `$TERM` outside is `xterm-256color`):
```tmux
set-option -ga terminal-overrides ",xterm-256color:RGB"
```

Then:
```bash
tmux
nvim
:Checkhealth nvim
```
See warning

### Expected behavior

- No warning is reported if using `terminal-features` (if things are working fine, which I suppose they are?)

### Neovim version (nvim -v)

NVIM v0.8.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by _nixbld1

### Vim (not Nvim) behaves the same?

No `:checkhealth` in vim

### Operating system/version

macOS 12.6.1

### Terminal name/version

alacritty 0.10

### $TERM environment variable

In tmux: `screen-256color`. Outside tmux: `xterm-256color`

### Installation

Nix (home-manager)

**Comment by seandewar** [comment] 2023-01-16 12:57
Duplicate of #16237

**Closed by seandewar** 2023-01-16 12:57 UTC
Labels: bug

**Comment by jjant** [comment] 2023-01-16 14:19
Thanks, I missed that one.
