### ISSUE TITLE
:terminal display glitches

### ISSUE THREAD

**Issue by Asheq** [neovim/neovim#8782] opened 2018-07-25 22:55 UTC
- `nvim --version`:
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/config -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"

Run :checkhealth for more info
```
- Vim  behaves differently? Yes
- `vim --version`
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 22 2018 05:24:30)
macOS version
Included patches: 1-202
Compiled by Homebrew
Huge version without GUI. ...
```

- Operating system/version: macOS 10.13.5
- Terminal name/version: kitty 0.11.3
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

There's this command-line application that I like to use as a sort of real-world test for terminals: https://github.com/p-e-w/ternimal

```
git clone https://github.com/p-e-w/ternimal.git
cd ternimal
rustc -O ternimal.rs
nvim -u NORC
:set termguicolors
:terminal
./ternimal length=20 thickness=70,15,0,1,0 padding=10 radius=5 gradient=0.03:#ffff00,0.15:#0000ff,0.3:#ff0000,0.5:#00ff00
```

### Actual behaviour
![nvim](https://user-images.githubusercontent.com/4657140/43231582-dde55f46-9021-11e8-87d1-9288697d2eca.gif)

### Expected behaviour
This is how it looks in kitty's raw terminal.
![terminal](https://user-images.githubusercontent.com/4657140/43231565-ccacbd8c-9021-11e8-85ae-8eee1dc060ff.gif)

This is how it looks in old-school Vim's :terminal. It's not as smooth as raw kitty, but still "accurate".
![vim](https://user-images.githubusercontent.com/4657140/43231604-eddf7a4e-9021-11e8-9b04-f10f4544ee3b.gif)

Thanks for looking into this! I wasn't sure what to title this issue, so please feel free to re-title.

**Comment by Asheq** [comment] 2018-07-25 22:58
Also, here's what it looks like **without `termguicolors` set**.

### In neovim
![nvim-notermguicolors](https://user-images.githubusercontent.com/4657140/43231934-5ceacdde-9023-11e8-99ea-8b9736e17600.gif)

### In vim
![vim-notermguicolors](https://user-images.githubusercontent.com/4657140/43231969-78fafe90-9023-11e8-842e-b6ddfdc76be0.gif)

**Comment by BurhanDanger** [comment] 2018-07-27 05:59
[Both show almost identical behaviour for me](https://ptpb.pw/Op03)

**Comment by justinmk** [comment] 2019-01-27 14:19
With current HEAD 7e6980a161011ab58c69ee67f35522fd86e6cb25 the steps provoke an assertion:

```
/nvim/tui/tui.c:1283: void tui_raw_line(UI *, Integer, Integer, Integer, Integer, Integer, Integer, Boolean, const schar_T *, const sattr_T *): Assertion `(size_t)attrs[c-startcol] < kv_size(data->attrs)' failed.
                                                        Aborted (core dumped)
```

**Comment by bfredl** [comment] 2019-01-27 14:33
Probably issue with the highlight table getting full, and not cleared properly. A simple program like this could be added as a fixture in the test suite, to test this case.

**Comment by justinmk** [comment] 2019-03-05 21:12
This behaves much better on current HEAD (e386e51d9e284ece5fe78a6dbcc0c8c4f166e48a), however: 

- The `tui_raw_line` crash mentioned above is still present.
- e386e51d9e284ece5fe78a6dbcc0c8c4f166e48a is not the cause of the improved behavior.

**Comment by blueyed** [comment] 2019-09-24 22:54
Just hit:

> src/nvim/tui/tui.c:1296: tui_raw_line: Assertion `(size_t)attrs[c-startcol] < kv_size(data->attrs)'

(NVIM v0.5.0-56-g0ab7da856)

```
Thread 2 (Thread 0xf7c0e980 (LWP 1534194)):
#0  get_func_line (c=58, cookie=0x58e99340, indent=2) at ../src/nvim/eval.c:23450
#1  0x566e2e01 in do_cmdline (cmdline=0x0, fgetline=0x566af4f2 <get_func_line>, cookie=0x58e99340, flags=7) at ../src/nvim/ex_docmd.c:512
#2  0x566ae6e2 in call_user_func (fp=0x58555470, argcount=2, argvars=0xffde25dc, rettv=0xffde2bd4, firstline=3277, lastline=3277, selfdict=0x0) at ../src/nvim/eval.c:23028
#3  0x56687b48 in call_func (funcname=0x58dd5050 "MyStatusLine", len=12, rettv=0xffde2bd4, argcount_in=2, argvars_in=0xffde25dc, argv_func=0x0, firstline=3277, lastline=3277, doesrange=0xffde2784, evaluate=true, partial=0x0, selfdict_in=0x0) at ../src/nvim/eval.c:6509
#4  0x566872d7 in get_func_tv (name=0x58dd5050 "MyStatusLine", len=12, rettv=0xffde2bd4, arg=0xffde2b94, firstline=3277, lastline=3277, doesrange=0xffde2784, evaluate=1, partial=0x0, selfdict=0x0) at ../src/nvim/eval.c:6267
#5  0x56682f7f in eval7 (arg=0xffde2b94, rettv=0xffde2bd4, evaluate=1, want_string=0) at ../src/nvim/eval.c:4369
#6  0x5668275e in eval6 (arg=0xffde2b94, rettv=0xffde2bd4, evaluate=1, want_string=0) at ../src/nvim/eval.c:4079
#7  0x566821fe in eval5 (arg=0xffde2b94, rettv=0xffde2bd4, evaluate=1) at ../src/nvim/eval.c:3927
#8  0x56681284 in eval4 (arg=0xffde2b94, rettv=0xffde2bd4, evaluate=1) at ../src/nvim/eval.c:3663
#9  0x566810b5 in eval3 (arg=0xffde2b94, rettv=0xffde2bd4, evaluate=1) at ../src/nvim/eval.c:3581
#10 0x56680f0f in eval2 (arg=0xffde2b94, rettv=0xffde2bd4, evaluate=1) at ../src/nvim/eval.c:3512
#11 0x56680d17 in eval1 (arg=0xffde2b94, rettv=0xffde2bd4, evaluate=1) at ../src/nvim/eval.c:3439
#12 0x56680c40 in eval0 (arg=0x58f7e502 "MyStatusLine(1, 0)", rettv=0xffde2bd4, nextcmd=0x0, evaluate=1) at ../src/nvim/eval.c:3399
#13 0x5667ba1f in eval_to_string (arg=0x58f7e502 "MyStatusLine(1, 0)", nextcmd=0x0, convert=0) at ../src/nvim/eval.c:1125
#14 0x5667bb91 in eval_to_string_safe (arg=0x58f7e502 "MyStatusLine(1, 0)", nextcmd=0x0, use_sandbox=0) at ../src/nvim/eval.c:1164
#15 0x5664ad0b in build_stl_str_hl (wp=0x58eea590, out=0xffde3f3c "\001\200\255\373\vA\336\377\vA\336\377\vA\336\377\vA\336\377\fA\336\377KA\336\377\vA\336\377KA\336\377", outlen=4096, fmt=0x58f7e500 "%!MyStatusLine(1, 0)", use_sandbox=0, fillchar=32 ' ', maxwidth=87, hltab=0xffde37bc, tabtab=0xffde3a3c) at ../src/nvim/buffer.c:3381
#16 0x568068b8 in win_redr_custom (wp=0x58eea590, draw_ruler=0) at ../src/nvim/screen.c:5177
#17 0x568062aa in redraw_custom_statusline (wp=0x58eea590) at ../src/nvim/screen.c:4994
#18 0x56805ddb in win_redr_status (wp=0x58eea590) at ../src/nvim/screen.c:4893
#19 0x567fa67e in update_screen (type=10) at ../src/nvim/screen.c:502
#20 0x56789317 in normal_redraw (s=0xffde50f8) at ../src/nvim/normal.c:1247
#21 0x56789544 in normal_check (state=0xffde50f8) at ../src/nvim/normal.c:1324
#22 0x56851bac in state_enter (s=0xffde50f8) at ../src/nvim/state.c:28
#23 0x56787259 in normal_enter (cmdwin=false, noexmode=false) at ../src/nvim/normal.c:463
#24 0x5674d32c in main (argc=5, argv=0xffde5384) at ../src/nvim/main.c:576

Thread 1 (Thread 0xf7740b40 (LWP 1534195)):
#0  0xf7f5ab29 in __kernel_vsyscall ()
#1  0xf7c43096 in raise () from /usr/lib32/libc.so.6
#2  0xf7c2d399 in abort () from /usr/lib32/libc.so.6
#3  0xf7c2d299 in __assert_fail_base.cold () from /usr/lib32/libc.so.6
#4  0xf7c3b0dd in __assert_fail () from /usr/lib32/libc.so.6
#5  0x56876682 in tui_raw_line (ui=0x582ee380, g=1, linerow=31, startcol=0, endcol=174, clearcol=174, clearattr=0, flags=2, chunk=0x58f58f20, attrs=0x58e52610) at ../src/nvim/tui/tui.c:1296
#6  0x5687f9de in ui_bridge_raw_line_event (argv=0xf773fee4) at ../src/nvim/ui_bridge.c:157
#7  0x566c7591 in multiqueue_process_events (this=0xf6e006d0) at ../src/nvim/event/multiqueue.c:157
#8  0x566c6ad1 in loop_poll_events (loop=0xf773ffe0, ms=-1) at ../src/nvim/event/loop.c:70
#9  0x5687391a in tui_main (bridge=0x582ee420, ui=0x582ee380) at ../src/nvim/tui/tui.c:437
#10 0x5687f5c6 in ui_thread_run (data=0x582ee420) at ../src/nvim/ui_bridge.c:104
#11 0xf7eec591 in start_thread () from /usr/lib32/libpthread.so.0
#12 0xf7d0f11a in clone () from /usr/lib32/libc.so.6
```
(FWIW it caused also zsh to crash right after?!)

**Comment by Asheq** [comment] 2020-09-22 22:55
@justinmk Tried this again recently and for whatever reason it works now (and it's beautiful).
Feel free to close this PR if it works for you too.

![8](https://user-images.githubusercontent.com/4657140/93945370-9f660980-fceb-11ea-8e37-ad32a88db7ac.gif)


# System Info
```
:version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototyp
es -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUD
E_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-17465-1c37yvx/neovim-0.4.4/build/config -
I/tmp/neovim-20200808-17465-1c37yvx/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-17465-1c37yvx/neovim-0.4.4/deps-build/include -I/Library/De
veloper/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-17465-1c37yvx/neovim-0.4.4/build/src/nvim/
auto -I/tmp/neovim-20200808-17465-1c37yvx/neovim-0.4.4/build/include
Compiled by brew@Mojave

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4/share/nvim"

Run :checkhealth for more info
Press ENTER or type command to continue
```

kitty version: version 0.18.3

**Comment by glacambre** [comment] 2021-06-05 20:07
Can confirm that this still works on master. Let's close this :).

**Closed by glacambre** 2021-06-05 20:07 UTC
Labels: bug, display, topic: :terminal
