### ISSUE TITLE
A virtual line is not displayed above the 1st line

### ISSUE THREAD

**Issue by rickhowe** [neovim/neovim#22167] opened 2023-02-08 10:13 UTC
### Describe the bug

A virtual line is not displayed above the 1st line

### Steps to reproduce

On the following window:

![11](https://user-images.githubusercontent.com/3096934/217498433-6a3ce16b-f2b4-49c4-a105-81cb9687d1e8.png)

Run this script to place a virtual line both above and below each line:

```
let vt = 'test'
let ns = nvim_create_namespace(vt)
for ln in range(1, line('$'))
  call nvim_buf_set_extmark(0, ns, ln - 1, 0,
    \{'virt_lines': [[['---', 'DiffChange']]], 'virt_lines_above': v:true})
  call nvim_buf_set_extmark(0, ns, ln - 1, 0,
    \{'virt_lines': [[['+++', 'DiffText']]], 'virt_lines_above': v:false})
endfor
```

![22](https://user-images.githubusercontent.com/3096934/217498961-921d049f-93a6-4e85-94d4-62c37d25f163.png)

A virtual line is not displayed above the 1st line.

### Expected behavior

A virtual line should be displayed above the 1st line.

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

No problem on vim 9.0

### Operating system/version

Windows 10

### Terminal name/version

Not on terminal but GUI

### $TERM environment variable

Not on terminal but GUI

### Installation

download zip file

**Comment by zeertzjq** [comment] 2023-02-08 10:27
Duplicate of #16166

**Closed by zeertzjq** 2023-02-08 10:27 UTC
Labels: bug
