### ISSUE TITLE
splitkeep causes issues when window height is set from an autocmd

### ISSUE THREAD

**Issue by folke** [neovim/neovim#23888] opened 2023-06-02 17:44 UTC
### Problem

When changing the height of a window that is not the current window with `splitkeep=screen`, and then moving the cursor to a location in the new window, the cursor will be moved by the splitkeep code to a wrong location instead.

### Steps to reproduce

The editor needs to be open in order to trigger the issue.

Save the file as `test.lua` and run `nvim -u NONE test.lua`.

Then inside Neovim, do `:luafile %`

```lua
vim.o.splitkeep = "screen"
vim.o.number = true

-- create test file
local lines = {}
for i = 1, 200, 1 do
	lines[#lines + 1] = i .. ""
end
local fd = assert(io.open("./foo.bar", "w+"))
fd:write(table.concat(lines, "\n"))
fd:close()

local win = vim.api.nvim_get_current_win()

-- create second window
vim.cmd([[vnew]])
local win2 = vim.api.nvim_get_current_win()
vim.api.nvim_buf_set_lines(0, 0, -1, false, { "Second Window" })

-- make the previous window active
vim.api.nvim_set_current_win(win)

vim.api.nvim_create_autocmd({ "WinResized" }, {
	callback = function()
		-- set to same height
		local height = vim.api.nvim_win_get_height(win2)
		-- commenting the line below, will make the issue go away
		vim.api.nvim_win_set_height(win2, height)
	end,
})

-- simulates vim.lsp.buf.jump_to_location()
local function go(line)
	local win = vim.api.nvim_get_current_win()
	local bufnr = vim.fn.bufadd("./foo.bar")
	vim.api.nvim_win_set_buf(win, bufnr)
	-- vim.api.nvim_set_current_win(win)
	vim.api.nvim_win_set_cursor(win, { line, 1 })
	vim.api.nvim_win_call(win, function()
		vim.cmd("normal! zv")
	end)
end

-- commenting the two lines below also don't trigger the issue
go(1)
vim.cmd([[bdelete]])

-- this will trigger the issue
-- instead of at line 100, you'll be at line roughly the same as the editor height
go(100)
``` 

### Expected behavior

spitkeep fix cursor should not be called for this case.

### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

didn't test

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-256-kitty

### Installation

bob

**Comment by luukvbaal** [comment] 2023-06-02 18:05
Closed by accident, I'll look into it thanks.

**Comment by luukvbaal** [comment] 2023-06-02 22:52
So it turns out `win_fix_cursor()` uses an invalid `w_botline` in this repro.
This patch fixes the issue:
```diff
diff --git a/src/nvim/window.c b/src/nvim/window.c
index ebfa538af..88c44b116 100644
--- a/src/nvim/window.c
+++ b/src/nvim/window.c
@@ -6483,6 +6483,7 @@ static void win_fix_cursor(int normal)
   cursor_down_inner(wp, so);
   linenr_T top = wp->w_cursor.lnum;

+  validate_botline(wp);
   wp->w_cursor.lnum = wp->w_botline - 1;
   cursor_up_inner(wp, so);
   linenr_T bot = wp->w_cursor.lnum;
```

Now to somehow convert this repro into an oldtest 😅

**Comment by folke** [comment] 2023-06-02 22:55
Wow, I would never have figured that one out :) Nice!

**Comment by luukvbaal** [comment] 2023-06-03 00:11
Actually, it is easy to write a test that exhibits wrong behavior similar to this issue:
```vim
set splitkeep=screen
call setline(1, range(1, 200))
func CursorResize()
  call cursor(100, 1)
  resize -1
endfunc
call CursorResize()
```

However in this case, both `w_topline` and `w_botline` are not yet updated so adding `validate_botline()` is not enough to fix this issue.
I'm not exactly sure how to fix this yet.

**Comment by luukvbaal** [comment] 2023-06-05 14:39
After some back and forth with Bram about this in https://github.com/vim/vim/pull/12488, I'm no longer sure what can be done about this. It's not clear what should happen when the cursor is moved and windows are resized before a redraw happens if 'splitkeep' != "cursor.

Although in my eyes the explicit cursor movement should trump the window resize. The problem is that it is hard to make this work without special-casing 'splitkeep' for each cursor movement which according to Bram is unrealistic, which I would agree with.

Using the `w_valid` flags or `w_valid_cursor` directly to determine whether the cursor should be adjusted in `win_fix_cursor()` seems like the right approach, but I haven't been able to make that work without breaking numerous 'splitkeep' tests.

**Comment by luukvbaal** [comment] 2023-08-24 22:02
Fixed in https://github.com/neovim/neovim/pull/24811

**Closed by luukvbaal** 2023-08-24 22:02 UTC
Labels: bug, bug-vim, needs:vim-patch
