### ISSUE TITLE
E903: Process failed to start: function not implemented: "C:\Windows\System32\cmd.exe"

### ISSUE THREAD

**Issue by ANP-Oxy** [neovim/neovim#23204] opened 2023-04-19 18:15 UTC
### Problem

I installed NeoVim today on windows 10. I'm a newbie to vim world so forgive me if I say something stupid the I'm having problem using it. I know this issue is duplicate but couldnt figure out what to do after looking at the original one. couldn't find a clear answer

### Steps to reproduce

choco install nvim
start nvim in cmd
type `:terminal`
it's giving this error
![image](https://user-images.githubusercontent.com/94713251/233161791-57634900-e3ce-4a7b-bbfc-f60ec498aeb7.png)

### Expected behavior

it should open a builtin terminal

### Neovim version (nvim -v)

0.8.9

### Vim (not Nvim) behaves the same?

no, vim

### Operating system/version

Windows 10

### Terminal name/version

don't kow what these two mean

### $TERM environment variable

---|---

### Installation

chocolatey

**Comment by dundargoc** [comment] 2023-04-19 20:50
Duplicate of https://github.com/neovim/neovim/issues/23204 I think

**Closed by dundargoc** 2023-04-19 20:50 UTC
Labels: bug, platform:windows

**Comment by ANP-Oxy** [comment] 2023-04-20 03:09
> Duplicate of #20458 I think

I already knew it was duplicate but I couldn't figure anything out because I'm pretty new to vim. Is this solvable or not cuz I can't find anything in the thread of original issue.

**Comment by dundargoc** [comment] 2023-04-20 07:00
Unfortunately not. To use the :terminal feature you need to upgrade to whatever windows version it says in the original issue.
