### ISSUE TITLE
Visual bracketed baste should replace the selected text instead of pasting at cursor position

### ISSUE THREAD

**Issue by chrischen** [neovim/neovim#12184] opened 2020-04-26 07:08 UTC
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: macOS Catalina
- Terminal name/version: iTerm2 and alacritty
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
Assuming clipboard contains the word `apple`

1. Type any word, such as `test`
2. Go to visual mode and select `test` from left to right
3. Paste using paste function of terminal (for example: CMD+V, or Ctrl+V, or Ctrl+Shift+V) that sends a bracketed paste.

### Actual behaviour
Paste results in `testapple`

### Expected behaviour
Just `apple`

Vim8 exhibits the correct expected behavior, even in the command-line version. Macvim, VimR (GUIs), do the same behavior. For anyone looking for a workaround: remap the key bindings for paste in your terminal, make a visual mode map to receive it, and make it do `"0p`.

**Comment by erw7** [comment] 2020-04-26 09:19
I tried it and it seems to have been fixed in the master. Please try [nightly](https://github.com/neovim/neovim/releases/tag/nightly).

**Comment by chrischen** [comment] 2020-04-26 09:46
It's mostly fixed, but still bugged. It seems to be failing if replacing a selection at the end of a line. The other problem is that it's yanking what was deleted, which is not consistent with behavior for this elsewhere.

Given this
<img width="124" alt="image" src="https://user-images.githubusercontent.com/109630/80303555-a279bf80-8776-11ea-9445-9488deae95e6.png">

Assuming "one" is in the clipboard:
### Expected Behavior

Pasting "one" over a selection of "six" should replace just the selected "six" in place.
<img width="108" alt="image" src="https://user-images.githubusercontent.com/109630/80303584-cd641380-8776-11ea-8bc7-d5903488655c.png">


### Actual Behavior

Pasting over "six" (at the end of the line) causes the paste to be inserted one character to the left.
<img width="124" alt="image" src="https://user-images.githubusercontent.com/109630/80303579-c5a46f00-8776-11ea-8fdc-e59155703aea.png">

If pasting before the end of the line then it works correctly and pastes exactly in place.

This seems to be caused by a delete happening before pasting.
`dP` - This delete and paste sequence seems to be consistent with the behavior right now. This works on any selection that isn't at the end of the line, and fails if it's at the end of the line.
`dp` - This works at the end of the line, but shifts the paste everywhere else.
`p` or `P` - This works in all cases
`"0P" or `"0p"` - This works in all cases AND prevents it from replacing clipboard.

**Comment by zeertzjq** [comment] 2022-01-14 09:43
That has the same root cause as #13431

**Closed** 2022-03-15 10:41 UTC
Labels: bug, clipboard
