### ISSUE TITLE
Remapping "_" (underscore) doesn't work when using XTerm

### ISSUE THREAD

**Issue by meribold** [neovim/neovim#21944] opened 2023-01-22 08:34 UTC
### Describe the bug

When I `:nnoremap _ k` (for example), the mapping is shown by `:map _`, but underscore retains its default behavior. Out of the terminals I tried (XTerm, Alacritty, Kitty, and `urxvt`), the only one exhibiting the incorrect behavior is XTerm. But Vim 9.0.1182 behaves correctly even when running inside XTerm.

https://user-images.githubusercontent.com/3041190/213906756-df1b8f7e-2b82-4be6-acd5-dd8864b3f2fc.mp4

### Steps to reproduce

* Use XTerm
* `nvim --clean`
* Insert some text
* `:nnoremap _ k`
* Try moving the cursor up by pressing `_`

### Expected behavior

Hitting `_` in Normal mode moves the cursor up after running `:nnoremap _ k`.

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

Vim 9.0.1182 isn't affected

### Operating system/version

Arch Linux

### Terminal name/version

XTerm 378

### $TERM environment variable

xterm-256color

### Installation

Official "community" repository of Arch Linux

**Comment by zeertzjq** [comment] 2023-01-22 08:36
Duplicate of #19042

**Closed by zeertzjq** 2023-01-22 08:36 UTC
Labels: bug
