### ISSUE TITLE
LSP: merge results of multiple LSP servers

### ISSUE THREAD

**Issue by pidgeon777** [neovim/neovim#17712] opened 2022-03-13 22:59 UTC
### Neovim version (nvim -v)

0.6.1

### Language server name/version

vhdl-tool, vhdl_ls

### Operating system/version

Windows 10 Pro

### Steps to reproduce using "nvim -u minimal_init.lua"

My minimal `init.lua`:

```lua
-- https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

-- Set runtimepath so that .lua files are found when required
vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'USERPROFILE'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local status_ok, nvim_lsp = pcall(require, "lspconfig")
  if not status_ok then
    return
  end
  local on_attach_key_opt = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  local lsp_configs = require "lspconfig.configs"

  -- -----------------------------
  -- LSP: vhdl-tool
  -- -----------------------------
  lsp_configs.vhdl_tool = {
    default_config = {
      -- Update the path to vhdl-tool
      cmd = { 'vhdl-tool', 'lsp' }, -- needed for elixirls, omnisharp, sumneko_lua
      filetypes = { "vhdl" },
      -- NOTE: For hdl_checker:
      root_dir = function(fname)
        local util = require "lspconfig.util"
        local root_files = {
          "vhdltool-config.yaml",
        }
        return util.root_pattern(unpack(root_files))(fname) or util.root_pattern ".git"(fname) or util.path.dirname(fname)
      end,
      settings = {},
    },
  }

  if nvim_lsp.vhdl_tool.setup then
    nvim_lsp.vhdl_tool.setup {
      on_attach = function(client, bufnr)
        on_attach_key_opt(client, bufnr)
      end,
    }
  end

  -- -----------------------------
  -- LSP: vhdl_ls
  -- -----------------------------
  lsp_configs.vhdl_ls = {
    default_config = {
      -- Update the path to vhdl_ls
      cmd = { 'vhdl_ls', 'enable_linter' }, -- needed for elixirls, omnisharp, sumneko_lua
      filetypes = { "vhdl" },
      -- NOTE: For hdl_checker:
      root_dir = function(fname)
        local util = require "lspconfig.util"
        local root_files = {
          "vhdl_ls.toml",
        }
        return util.root_pattern(unpack(root_files))(fname) or util.root_pattern ".git"(fname) or util.path.dirname(fname)
      end,
      settings = {},
    },
  }

  if nvim_lsp.vhdl_ls.setup then
    nvim_lsp.vhdl_ls.setup {
      on_attach = function(client, bufnr)
        on_attach_key_opt(client, bufnr)
      end,
    }
  end
  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### Expected behavior

When looking for references, I would not expect `vhdl_ls` LSP to overwrite the find references output of `vhdl-tool`.

### Actual behavior

When both `vhdl_ls` and `vhdl-tool` LSP are enabled, the find references outputs are not joined: `vhdl_ls` overwrites the ones of `vhdl-tool`.

### Log file

https://gist.github.com/pidgeon777/3390a8cec5236b673eebfb63ce267e06

**Comment by instingt** [comment] 2022-06-27 12:43
Hello!
I have same issue with tsserver and angularls

tsserver shows references in typescript files, and angularls additionally in angular templates. When I ran gr command I able to see list from angularls with html files and then tsserver overrides them and I can't see html files

Is there possible way to merge results from different lsp's?

**Comment by Matsuuu** [comment] 2023-02-06 20:27
+1:ing this.

I think this is something that needs to be looked at. Especially in the frontend development scene, there's multiple cases where results are fed from more than one language servers. 

I have a situations where I have my Custom Elements Language Server's response getting overridden by the TSServer ones on some cases, where the two LS's are returning input for the same request type

**Comment by justinmk** [comment] 2023-07-04 12:52
This is likely the root cause of https://github.com/neovim/neovim/issues/13766

**Comment by lewis6991** [comment] 2024-10-31 10:22
`vim.lsp.buf.references` is fixed in #30722 . General support for multiple clients is ongoing.

**Closed by lewis6991** 2024-10-31 10:22 UTC
Labels: enhancement, complexity:high, lsp
