### ISSUE TITLE
nvim changes font size in KDE Konsole

### ISSUE THREAD

**Issue by jhzab** [neovim/neovim#6798] opened 2017-05-23 14:05 UTC
- `nvim --version`:
nvim --version
NVIM v0.2.1-232-gc4a8950
- Vim (version: ) behaves differently?
Yes.
- Operating system/version:
Fedora 25
- Terminal name/version:
Konsole 16.12.3
- `$TERM`:
xterm-256color

### Actual behaviour

nvim changes font size in Konsole terminal if the current size is not the default configured in the settings.

### Expected behaviour

Font size should not change.

### Steps to reproduce using `nvim -u NORC`

Open Konsole, increase or decrease font size from default, start nvim with ``nvim -u NONE -i NONE`` and nvim changes the font size back to the default configured in Konsole settings.

Starting nvim via ``nvim -u nvim-no-cursor -i NONE`` where ``nvim-no-cursor`` contains only one line: ``set guicursor=`` doesn't exhibit this behaviour (font size doesn't change).

(It still changes with that config set when using CtrlP and probably other plugins, but that just might be related.)

**Comment by ZyX-I** [comment] 2017-05-23 14:41
Yet another reason to make guicursor empty by default.

About CtrlP: some plugins have a habit of temporary setting &guicursor for its own needs (most likely: simply temporary disable the cursor).

**Comment by justinmk** [comment] 2017-05-23 14:44
We use KONSOLE_PROFILE_NAME env var to detect konsole. Seems that konsole is broken enough that we should disable guicursor there. 

@jhzab what is `$KONSOLE_PROFILE_NAME` in your environment?

**Comment by jhzab** [comment] 2017-05-23 14:52
@justinmk 
``echo $KONSOLE_PROFILE_NAME`` prints: ``Profile 1``

Regarding CtrlP, I'll open an issue on their side (maybe with a potential fix) later.

**Comment by ZyX-I** [comment] 2017-05-23 14:59
Regarding CtrlP: as far as I know *we* should emit sequences which disable cursor when cursor highlight group is set to Normal or something similar (nonexistent highlight group, hl group linked to normal, etc).

**Comment by justinmk** [comment] 2017-05-23 15:23
@ZyX-I Yes, and @teto is working on that. But empty 'guicursor' should be considered as a hint to "leave cursor styling alone".

**Comment by ZyX-I** [comment] 2017-05-23 15:27
@justinmk Why? While changing shape may not work in many terminals, disabling it should work (almost?) everywhere.

**Comment by jdebp** [comment] 2017-05-24 21:29
I hope that I haven't affected this with the work for #6795.  Please check when I create the pull request.  Please note that I was unable to reproduce the described fault with the versions of Konsole that I have available.

**Comment by jhzab** [comment] 2017-05-26 16:10
@jdebp I'm not seeing any difference with your ``non-terminfo-tui`` branch. Also which Konsole version are you using?

Should I file a bug report upstream on the KDE side? And if so, is there some specific information that might help them? I know to little about terminal internals to make an informed decision about this.

I also didn't file anything on CtrlPs side, since as far as I understand it, it's already being worked on, but not by checking the current ``guicursor`` setting.

**Comment by jdebp** [comment] 2017-05-27 00:14
I have managed to replicate this; which made it possible to investigate.

It's a deficiency in Konsole; which does not support the DEC VT control sequence for changing the cursor.  If it did, nvim could use it instead of doing what it resorts to doing.  What it resorts to doing is causing this behaviour.

Konsole is one of only two (Linux/BSD) terminal emulators that I know of where changing the cursor shape is not done with a conventional control sequence named DECSCUSR.  The other is the terminal emulator built into the Linux kernel.  There is no simple control sequence for doing this on Konsole.  

Instead, a program such as nvim that wants to change the cursor shape has to perform a _fake profile update_, using a control sequence that first makes a nonce temporary profile with some of the settings changed from the real  profile, and that then causes that temporary profile to be applied.

It is the fact that this done by inventing a Konsole profile and applying it, on the fly, which is causing the effect that you are seeing; where the font size is set to the size specified in the profile.  Applying a nonce profile based upon the current one _will_ reset the font size back to what is in the current profile, by the very nature of the action.

Your local fix is to turn nvim's `guicursor` mechanism off when you are using nvim in Konsole.

A harder fix is getting Konsole to support DECSCUSR, and updating the terminfo `Ss` capability when Konsole is the terminal.

**Comment by ZyX-I** [comment] 2017-05-27 00:19
They actually could put the font size changes into the same temporary profile they are using for cursor shape changes.

**Comment by azrdev** [comment] 2017-06-09 12:52
FTR, there is a Konsole issue to implement "proper" cursor changing with DECSCUSR (instead of the temporary-profile hack): <https://bugs.kde.org/show_bug.cgi?id=347323>

**Comment by DonnieWest** [comment] 2017-06-12 16:11
I added support for DECSUSR to qtermwidget (a QT based Konsole fork) a while back. I can't imagine it would be hard to submit the patch upstream. Anyone here know someone on the Konsole team? I'd like to know they'd be interested before I put in the work to make them support it

**Comment by azrdev** [comment] 2017-06-13 08:32
@DonnieWest The [KonsoleDevelopment](https://userbase.kde.org/KonsoleDevelopment) page reads like you should just go forward and submit your patch. If still in doubt, there's a mail contact to ask, too.

**Comment by k1sul1** [comment] 2018-01-30 14:35
I didn't have this problem for months, but now it's happening again. 

Did Konsole break or did neovim break? :')

**Comment by undu** [comment] 2018-04-23 08:39
Problem should go away soon as support for DECSCUSR was merged recently into master: https://github.com/neovim/neovim/issues/8300

**Comment by prg318** [comment] 2018-08-22 15:07
It's unclear from the thread whether people are still experiencing this or not.. I am still experiencing the issue with neovim 0.3.1 and konsole 18.08.0

My TERM is properly set to konsole-256color

As a workaround, adding "set guicursor=" seems to prevent the issue from occuring

**Comment by justinmk** [comment] 2018-12-13 23:02
# Plan

As described in https://github.com/neovim/neovim/issues/8300#issuecomment-386803484 the next steps are to detect konsole version and use DECSCUSR if konsole version is 18.07.70 or newer.

**Closed** 2018-12-14 21:54 UTC
Labels: +plan, complexity:low, tui
