### ISSUE TITLE
remote plugins: deprecate :UpdateRemotePlugins

### ISSUE THREAD

**Issue by tweekmonster** [neovim/neovim#5532] opened 2016-10-25 16:33 UTC
I think `:UpdateRemotePlugins` should be deprecated.  The command is esoteric and generates issues that have little to do with runtime scripts and more to do with the user's environment.

This command literally generates vimscript that doesn't require special parsing and should be a responsibility left to the plugin developer.
## Proposal
- `:UpdateRemotePlugins` is turned into a `NOOP` (so that user configs aren't broken)
  - Optionally generate a manifest for plugins that _aren't_ manually registered.
  - Print a deprecation message after a couple releases.
- A helper function (e.g. `remote#host#pluginSpec()`) is available to devs to generate a spec string for use in the `remote#host#RegisterPlugin()` function.
  - ...or a separate SDK plugin that helps with generating the spec and provides simple debugging.
  - Optionally make this something that can be done from the command line to write a bootstrap script (e.g. `plugin/manifest.vim`).
- `remote#host#RegisterPlugin()` should be called by the plugin when it's loaded.
  - Changes to a plugin's API spec will always be up to date when the user updates the plugin.

Plugins manually registering themselves will effectively be backward compatible with older versions of nvim, [provided registration happens before a host starts](https://github.com/neovim/neovim/blob/714ec09c6d83295ef70becbbaf1c620761cbdac6/runtime/autoload/remote/host.vim#L86-L90).  Plugins may have to wrap it in a `try...endtry` [due to existing manifest files](https://github.com/neovim/neovim/blob/714ec09c6d83295ef70becbbaf1c620761cbdac6/runtime/autoload/remote/host.vim#L80-L84), but I think this is a small price to pay.
## Pros
- Users will have one less step for installing rplugins.
- Problems about an rplugin not working will most likely be due to the user not having a host program.  This can be dealt with `:CheckHealth`.
- Problems with registration are more likely to be reported by plugin devs who will have more specific information beyond "it doesn't work."
- The dev's environment will (or should) be already configured to generate the spec without fail.
- Devs will have a more reasonable issue scope:
  - Is the host program installed?
  - Is the host client up to date?
  - Is the plugin compatible with the host/client?
  - Mainly: "Did you run `:CheckHealth`?" without the followup questions.
## Cons
- ???

**Comment by bfredl** [comment] 2016-10-25 16:50
This has been discussed before. The question boils more or less down to: when should nvim asks a host and see if the registered commands have changed? Should nvim monitor the `rplugin/langX` directory and start up the host when a changed file is newer than the previous timestamp for that host?

**Comment by bfredl** [comment] 2016-10-25 16:54
> Plugins may have to wrap it in a try...endtry due to existing manifest files, but I think this is a small price to pay.

This is an annoying bug (I would call it a bug) with `:UpdateRemotePlugins` which in principle could be fixed without changing much else. I think the reason is because the plan is to get rid of UpdateRemotePlugins eventually, otherwise this would probably have been fixed much earlier.

**Comment by bfredl** [comment] 2016-10-25 17:00
ref #4438 #4439

**Comment by tweekmonster** [comment] 2016-10-25 19:19
> The question boils more or less down to: when should nvim asks a host and see if the registered commands have changed?

The moment a plugin developer decides to refresh *the plugin's* manifest file.  nvim shouldn't do anything else.  If errors are generated because of an out of date API spec, that's the plugin dev's fault without question.  As an example, @zchee generates the spec in [nvim-go][1] and as a result, `:UpdateRemotePlugins` isn't needed.  He used [go-client][2] to generate it.

> This is an annoying bug (I would call it a bug) with :UpdateRemotePlugins which in principle could be fixed without changing much else.

I agree.  I was only suggesting it because I'd like to see this be a backward compatible change.  Though, it might be cleaner to use a version check.

[1]: https://github.com/zchee/nvim-go/blob/aa6aaa92630dfff20a6da48ddf6709818a3f4a49/plugin/nvim-go.vim#L105-L140
[2]: https://github.com/neovim/go-client/blob/71e25ff7b5d1244a40237662a359bd9c5f24d72a/nvim/plugin/plugin.go#L430-L473

**Comment by bfredl** [comment] 2016-10-25 19:33
Moving the responsibility from the end user to the plugin author would be a step forward and a step backward. Seems better to go directly to a fully automated solution. At least, intervention should only be needed in edge cases, not in normal usage _nor_ in normal development.

We could already update the spec for one host more or less cost-free when the host is started anyway, when the user starts an existing plugin using an existing command, but this won't cover the situation when the host would be started by a new command, which includes the situation of the first plugin added... This would be simpler with a machine-readable and modifiable format for the spec. Best is probably shada as @justinmk suggested the linked issues, there might be logic we could reuse for instance to merge changes according to timestamps, i e if instance 1 updated the specs for host A and instance 2  updated the specs for host B.

**Comment by tweekmonster** [comment] 2016-10-26 00:08
I can't see the disadvantage of the spec being managed by the developer.  A plugin's spec might change after updating the plugin.  After plugins are updated, the most sane thing to do is restart nvim.  I'm not sure how being able to update the spec at runtime will change this unless it's a 100% pure remote plugin.  Even if it was, I would still restart either out of habit or because non-remote plugins were updated.

In the case for remote plugins that have no vimscript dependencies, I think it'd be great if they were able to auto-restart (and even auto-update) without user intervention.  However, what I mentioned in the proposal above could be achieved right now with minor modifications to the runtime scripts.  It shouldn't block future development into making this fully automated.  It also removes the user from a crucial step and shifts the burden to plugin developers who already have the burden of writing/maintaining the plugin in the first place.

If the time comes that the specs are auto-updated, manual plugin registration could be a noop in the case of irregularly maintained plugins.

**Comment by bfredl** [comment] 2016-10-26 06:55
The problem is that you suggest fixing the part of the system that is not broken. The rplugin host _already_ collects the (up-to-date) specs from the plugin sources every time the host starts, it must do this to be able to respond to rpc requests. Requiring any intervention here would purely be a step backwards.  The problem is that nvim just ignores this fresh information and insists on using an old cached copy that the user (sometimes the plugin manager) must update manually. It would likewise be a not too big change to update the manifest file when we have this opportunity to do so (when the host happen to be be started anyway), and also then using these fresh specs, this would greatly reduce the need for running `:UpdateRemotePlugins` if not completely eliminating it.

I'm not suggesting nvim should support updating running plugins at runtime, just basic things like this should work:

1. nvim is started (but plugin X is not loaded)
2. plugin X sources are changed
3. the user invokes plugin X in the same instance

This should work regardless if the relevant host was started in another instance or not, in the meanwhile. If the plugin already was started, the end user already expects to need to restart nvim.

**Comment by roxma** [comment] 2017-10-13 14:48
I have tried [nvim-ascript](https://github.com/roxma/nvim-ascript). But as mentioned in the warnings that doesn't look like a neat implementation.

My current attempt is [nvim-yarp](https://github.com/roxma/nvim-yarp). This looks more straitforward to me.

And if things goes well, it may be able to be run on vim8 after https://github.com/roxma/vim-hug-neovim-rpc/issues/4 is finished.

**Comment by justinmk** [comment] 2024-03-20 15:33
Alternative proposal/design:

- https://github.com/neovim/neovim/issues/27949

**Closed by justinmk** 2024-03-20 15:33 UTC
Labels: enhancement, plugin, rpc, remote-plugin
