### ISSUE TITLE
nvim closed on run :bd command

### ISSUE THREAD

**Issue by carlitux** [neovim/neovim#3087] opened 2015-07-23 13:26 UTC
Hi,

Some times when I run bd command closes nvim and sometimes just close the buffer.

**Comment by mhinz** [comment] 2015-07-23 15:18
`:bdelete` never closes nvim. Try reproducing it with `nvim -u NONE`.

It's probably a plugin doing magic on the `BufDelete` event. Check `:au BufDelete` for potential culprits.

**Comment by justinmk** [comment] 2015-07-28 18:59
Lacks details, can't reproduce. Closing.

**Closed by justinmk** 2015-07-28 18:59 UTC
