### ISSUE TITLE
can't run on ubuntu 18.04

### ISSUE THREAD

**Issue by lasypig** [neovim/neovim#20113] opened 2022-09-08 00:57 UTC
### Neovim version (nvim -v)

0.8 nightly release

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ubuntu 18.04

### Terminal name/version

--

### $TERM environment variable

--

### Installation

appimage

### How to reproduce the issue

```
./nvim.appimage
```

### Expected behavior

run without error

### Actual behavior

```
/tmp/.mount_nvim.aLnLzcF/usr/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_nvim.aLnLzcF/usr/bin/nvim)
/tmp/.mount_nvim.aLnLzcF/usr/bin/nvim: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_nvim.aLnLzcF/usr/bin/nvim)
```

**Comment by zeertzjq** [comment] 2022-09-08 00:58
Duplicate of #19711

**Closed by zeertzjq** 2022-09-08 00:58 UTC
Labels: closed:duplicate
