### ISSUE TITLE
Error when trying to get type definition with clangd

### ISSUE THREAD

**Issue by fenuks** [neovim/neovim#15825] opened 2021-09-28 14:33 UTC
### Neovim version (nvim -v)

0.6.0-dev+360-g9ca7b6b71

### Language server name/version

clangd version 12.0.1

### Operating system/version

Arch Linux

### :checkhealth

```markdown
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.
```

### Steps to reproduce using "nvim -u minimal_init.lua"

My minimal init.vim looks like that:

```viml
call plug#begin('~/.local/share/nvim/plugged/')
    Plug 'https://github.com/neovim/nvim-lspconfig'
        
call plug#end()
lua << EOF
    require'lspconfig'.clangd.setup{}
EOF
```

Test file:
```c
int test(void) {
    return 1;
}

int main() {
    return test();
}
```
Move cursor over test() invocation, run `:lua vim.lsp.buf.type_definition()`. Error will be presented.
```
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:486: bad argument #2 to 'format' (number expected, got nil)                            
```

### Expected behavior

No error is returned when server doesn't support textDocument/typeDefinition, as hinted in lsp.log.

```
[WARN][2021-09-28 16:18:23] .../lua/vim/lsp.lua:87	"method textDocument/typeDefinition is not supported by any of the servers registered for the current buffer"
```

### Actual behavior

It seems reason for the error is that ctx.client_id is nil, and neovim doesn't expect that.

**Comment by mfussenegger** [comment] 2021-09-28 15:41
This would be fixed by https://github.com/neovim/neovim/pull/15193

**Comment by fenuks** [comment] 2021-09-28 18:04
Thank you, I didn't find it searching for error message.

**Comment by mjlbach** [comment] 2021-09-28 21:47
Duplicate of #15174

**Closed by mjlbach** 2021-09-28 21:47 UTC
Labels: bug, lsp
