### ISSUE TITLE
Compilation fails when path contains space

### ISSUE THREAD

**Issue by themightyoarfish** [neovim/neovim#4912] opened 2016-06-12 18:22 UTC
- Operating system/version: OSX 10.10.5
- Terminal name/version: iTerm 2.9
- `$TERM`: xterm-256color

### Actual behaviour
```
mkdir .deps
cd .deps
cmake ../third-party
make
```

When building dependencies, cmake fails with
```
clang: error: no input files
clang: error: no such file or directory: 'HD/Users/Rasmus/Downloads/Sources/neovim/.deps/build/src/jemalloc/include'
clang: error: no such file or directory: 'HD/Users/Rasmus/Downloads/Sources/neovim/.deps/build/src/jemalloc/test/include'
```
### Expected behaviour
Compilation proceeds

**Comment by jamessan** [comment] 2016-06-12 18:44
Duplicate of #4621, also filed by you. :)

**Closed by jamessan** 2016-06-12 18:44 UTC

**Comment by themightyoarfish** [comment] 2016-06-12 22:12
Whoops, how silly. I thought i had reported this for some other project.
