### ISSUE TITLE
Terminal Insert Mode cursor is always block

### ISSUE THREAD

**Issue by ayroblu** [neovim/neovim#22730] opened 2023-03-19 17:37 UTC
### Problem

When I'm using terminal mode, my cursor is always a block. I even tried `set guicursor=a:ver25` but no change. I was reading from: https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-shape-in-the-terminal

| Actual | Expected |
|--------|--------|
| <img width="537" alt="image" src="https://user-images.githubusercontent.com/4915682/226195378-1b282eb5-46ce-4a7c-adea-7de5c15b347a.png"> | <img width="541" alt="image" src="https://user-images.githubusercontent.com/4915682/226195434-f48433d6-13b2-44d7-9eab-9212c3436d05.png"> | 

### Steps to reproduce

nvim -u NORC
run: :terminal
- press 'i' key

### Expected behavior

Cursor shape should be different depending on whether in terminal insert mode or terminal normal mode

### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

no, it's always a I bar?, 9.0.1000

### Operating system/version

macOS 13.1

### Terminal name/version

alacritty 0.11.0 (8dbaa0b)

### $TERM environment variable

screen-256color

### Installation

brew install neovim

**Comment by justinmk** [comment] 2023-03-19 18:33
Duplicate of : 

- https://github.com/neovim/neovim/issues/3681
- https://github.com/neovim/neovim/issues/17173

**Closed by justinmk** 2023-03-19 18:33 UTC
Labels: bug, terminal, closed:duplicate
