### ISSUE TITLE
lag: noticeable lag increase when opening `markdown` files (because of `filetype.lua` instead of `filetype.vim`)

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [neovim/neovim#17798] opened 2022-03-21 06:42 UTC
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1280-gf2e5f509d

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.1.1

### Terminal name/version

kitty 0.24.4

### $TERM environment variable

xterm-256color

### Installation

brew install neovim --head

### How to reproduce the issue

in basic config: 
``` lua
-- use filetype.lua instead of filetype.vim
vim.g.do_filetype_lua = 1
vim.g.did_load_filetypes = 0
```

then open any significant markdown file either directly, or through `find` cmd
``` 
nvim README.md
```

### Expected behavior / Actual Behavior

the startup time is noticeably larger when compared to doing the same on default `filetype.vim` plugin being loaded. this is not true for other files, and in general you can see huge decrease in startup time when using the `filetype.lua` plugin (built in on HEAD) instead.

I have only noticed this on `markdown` files, and it happens 100% on all markdown file launches on my system.
for reference, the link to this in my config: 
https://github.com/ViRu-ThE-ViRuS/configs/blob/efb8aca57d1413ffcb6f7025d4296dd2495e84ba/nvim/lua/settings.lua#L13

with `filetype.lua` enabled:
``` bash
$> time nvim +qall README.md 
________________________________________________________
Executed in  446.04 millis    fish           external
   usr time  236.40 millis    0.19 millis  236.21 millis
   sys time  182.84 millis    1.54 millis  181.30 millis

```

without `filetype.lua` enabled:
``` bash
$> time nvim +qall README.md 
______________________________________________________
Executed in  209.63 millis    fish           external
   usr time  129.48 millis    0.15 millis  129.33 millis
   sys time   83.98 millis    1.43 millis   82.56 millis

```

NOTE: using `README.md` from my config files (linked above), for this measurement

**Comment by clason** [comment] 2022-03-21 07:53
Please create a _minimal_ self-contained config and add it to the issue. Also, make sure that you are not using tree-sitter (otherwise this is a duplicate).

**Comment by ViRu-ThE-ViRuS** [comment] 2022-03-22 15:53
this behavior is exacerbated after `TSInstall markdown` (using treesitter), but its also there without it. I will shortly provide a minimal config file with timings from `nvim --startuptime`.

**Comment by clason** [comment] 2022-04-24 10:59
Closing this for now because there's not enough information to reproduce and investigate.

**Closed by clason** 2022-04-24 10:59 UTC
Labels: performance, status:needs-response, lua, filetype
