### ISSUE TITLE
Within Lua script this key command 'viwp' not work

### ISSUE THREAD

**Issue by abdulbadii** [neovim/neovim#30142] opened 2024-08-26 00:52 UTC
### Problem

Within a Lua's script this key command:
`viwp`
 ie. to visual select the word string then swap it to the " register, is not working by any of

```
vim.cmd "normal! viwp"
vim.cmd [[normal! viwp]]
vim.api.nvim_command( 'normal! viwp')
vim.api.nvim_exec([[normal! viwp]], false)

```
have spent a full day to work to succeed getting it to no avail 

### Steps to reproduce

let
`~\.config\nvim\init.lua 
`
have a code line
vim.api.nvim_command('normal! viwp')

so utilize it by, eg, put it in function then get key-binding
vim.api.nvim_set_keymap('n', '<Space>',  ':lua test()<CR>', {noremap=true})
 
 it doesn't accomplish its job, instead of swapping, it'll just yank/copy it to " register

### Expected behavior

 swapping the word string the cursor is on, to " register

### Neovim version (nvim -v)

$ nvim --version NVIM v0.9.5 Build type: Release LuaJIT 2.1.1713773202     system vimrc file: "$VIM\sysinit.vim"   fall-back for $VIM: "/ucrt64/share/nvim"

### Vim (not Nvim) behaves the same?

I can't afford as not having Vim, so please apologize

### Operating system/version

Msys2/Mingw64 on Windows

### Terminal name/version

mintty

### $TERM environment variable

xterm-256color

### Installation

Msys2 or Mingw64 or UCRT64  pacman

**Comment by zeertzjq** [comment] 2024-08-26 01:02
> :lua test<CR>

This will not execute anything. Do you mean to use `:lua test()<CR>`?

**Comment by abdulbadii** [comment] 2024-08-26 01:43
Of course
didn't read:

**eg.**

Why github issues full of ones spending others' time to everything annoying far-of-point things

**Comment by zeertzjq** [comment] 2024-08-26 02:00
Cannot reproduce. This works for me:
```lua
function test()
  vim.api.nvim_command('normal! viwp')
end
vim.api.nvim_set_keymap('n', '<Space>', ':lua test()<CR>', { noremap = true })
```
The let's close this issue and not spend more time on this :)

**Closed by zeertzjq** 2024-08-26 02:00 UTC
Labels: bug, needs:repro
