### ISSUE TITLE
WinEnter uses value from the previous window

### ISSUE THREAD

**Issue by mdumitru** [neovim/neovim#12781] opened 2020-08-20 15:13 UTC
I'm trying to make it so that every time I land into a terminal buffer I end up in insert mode; during this attempt, it appeared necessary to me to have an autocmd that monitors `WinEnter` and starts insert if it's a terminal buffer. However, it seems there is at least a situation of opening a file from the terminal buffer which ends up in a non-terminal buffer, but triggering said autocmd.

- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
```
- `vim -u DEFAULTS` (version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)) behaves differently?
It behaves differently, though still wrong (the autocmd is not triggered at all even when entering the terminal buffer).
- Operating system/version: Ubuntu 20.04.1 LTS (Focal Fossa)
- Terminal name/version: alacritty 0.4.0 (b115b90)
- `$TERM`: alacritty

### Steps to reproduce using `nvim -u NORC`

```
$ nvim -u NORC
:autocmd WinEnter * if &buftype == 'terminal' | startinsert | endif
:terminal
$ /etc/passwd    # simply write the file name or ls a directory, we need a name in the buffer
# exit terminal mode, place cursor on the file name
<c-w>f
```

### Actual behaviour
The file opens in an horizontal split in **insert** mode.

### Expected behaviour
The file opens in an horizontal split in **normal** mode.

My expectation is that the `if` in the autocmd is executed once we end up in the new split. From that split we can inspect `&buftype` and see that it indeed does not have a value of `'terminal'`, so I don't understand how the body of the `if` is executed (that is indeed why we end up in insert mode, I've tested with other actions in the if body).

With this use-case, `BufEnter` seems conceptually equivalent. However, replacing `WinEnter` with `BufEnter` in the mentioned aucmd works as expected, we end up in **normal** mode in the new split.

**Comment by justinmk** [comment] 2020-09-02 04:51
duplicate of https://github.com/neovim/neovim/issues/4977

**Closed by justinmk** 2020-09-02 04:51 UTC
Labels: :terminal, bug

**Comment by mdumitru** [comment] 2020-09-03 17:21
@justinmk After reading the linked issues, my conclusion is that it is impossible to end up in insert mode every time you switch to a terminal window; is that correct? `WinEnter` is triggered before any buf is potentially loaded, which is why my example doesn't work; but it is the only event triggered when going from a terminal split to another split with the same terminal buffer - a situation that I cannot determine through autocmd events to trigger startinsert?

**Comment by glacambre** [comment] 2020-09-04 04:08
On 2020-09-03 19:21, mdumitru wrote:
> @justinmk <https://github.com/justinmk> After reading the linked issues, 
> my conclusion is that it is impossible to end up in insert mode every 
> time you switch to a terminal window; is that correct?

Doesn't `:autocmd WinEnter * if nvim_buf_get_option(nvim_win_get_buf(0), 
"buftype") == "terminal" | startinsert | endif` work?

**Comment by mdumitru** [comment] 2020-09-04 12:41
>  `:autocmd TermOpen * startinsert | au BufEnter <buffer> startinsert` should do what you want though.

@glacambre If I understand this correctly, on launching a terminal, it sets up another autocmd for that terminal only, triggered on BufEnter; the problem however is that BufEnter isn't triggered when going to a split holding the same buffer; only WinEnter is, but the body of such autocmds can't seem to access information from the destination buf.
