### ISSUE TITLE
Error on Paste 

### ISSUE THREAD

**Issue by ggsalas** [neovim/neovim#8781] opened 2018-07-25 21:08 UTC
- `nvim --version`: NVIM v0.3.1
- Operating system/version: macos 10.13.6 (17G65)
- Terminal name/version: kitty 10.13.6 (17G65)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
insert mode
paste a big chunk of text with <command-v>
```

### Actual behaviour
`:checkhealth`
```
## Configuration
  - ERROR: 'paste' is enabled. This option is only for pasting text.
    It should not be set in your config.
    - ADVICE:
      - Remove `set paste` from your init.vim, if applicable.
      - Check `:verbose set paste?` to see if a plugin or script set the option.
```
### Expected behaviour
`:checkhealth`
```
## Configuration
  - OK: no issues found
```

**Comment by jamessan** [comment] 2018-07-25 21:22
Duplicate of #7994

**Closed by jamessan** 2018-07-25 21:22 UTC
