### ISSUE TITLE
Support iTerm2 proprietary ANSI codes in TUI nvim terminal

### ISSUE THREAD

**Issue by nall** [neovim/neovim#11282] opened 2019-10-24 16:10 UTC
iTerm2 supports a number of proprietary [ANSI codes](https://iterm2.com/documentation-escape-codes.html). When I run a terminal under (TUI) nvim, it seems that it filters these out instead of passing them through.

Is there a setting to allow unknown codes to pass through to the terminal emulator (iTerm2 in this case)?

```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` behaves the same
- Operating system/version: macOS 10.15
- Terminal name/version: iTerm2 Build 3.3.7beta1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:terminal
I
printf "\033]1337;SetUserVar=%s=%s\007" "foo" $(printf "%s" "bar" | base64 | tr -d '\n')
```

### Actual behaviour
iTerm2 does not receive the expected ANSI code.

### Expected behaviour
iTerm2 receives the ANSI code and updates any UI displaying the user variable `foo`. This happens as expected when running in outside of nvim.

**Comment by mhinz** [comment] 2019-10-24 17:18
How to retrieve the value afterwards? How to test this?

**Comment by nall** [comment] 2019-10-24 17:32
Oops. Forgot that part.

With iTerm2 installed, `Preferences` -> `Profiles`

Select the profile you're using and go to the `General` tab. In the `Badge` field type: `\(user.foo)`. Then create a new window with that profile. 

<img width="549" alt="screenshot_10" src="https://user-images.githubusercontent.com/72578/67510154-47410600-f649-11e9-8605-cb79fdc95029.png">

Now the printf should result in the string "bar" being displayed as in the screenshot below.

<img width="990" alt="screenshot_09" src="https://user-images.githubusercontent.com/72578/67510187-4f994100-f649-11e9-8820-a8d8160424a2.png">

**Comment by justinmk** [comment] 2019-10-25 03:17
Duplicate of https://github.com/neovim/neovim/issues/4349

**Closed by justinmk** 2019-10-25 03:17 UTC
Labels: enhancement
