### ISSUE TITLE
regression, clang-format is not working on nvim0.7

### ISSUE THREAD

**Issue by linjintao** [neovim/neovim#18588] opened 2022-05-16 01:20 UTC
### Neovim version (nvim -v)

0.7

### Vim (not Nvim) behaves the same?

no,vim7.3

### Operating system/version

redhat7

### Terminal name/version

csh

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

I have this configuration in my "init.vim" 
if has('python')
    map <C-I> :pyf /path/to/12.0.1_1/share/clang/clang-format.py<cr>
    imap <C-I> <c-o>:pyf /path/to/12.0.1_1/share/clang/clang-format.py<cr>
  elseif has('python3')
    map <C-I> :py3f /path/to/12.0.1_1/share/clang/clang-format.py<cr>
    imap <C-I> <c-o>:py3f /path/to/12.0.1_1/share/clang/clang-format.py<cr>
  endif

### Expected behavior

Use C-I will format the cpp code, and it does work in 0.6, not for 0.7

### Actual behavior

input C-I in visual mode, the command line does not showing ":py3f /path/to/12.0.1_1/share/clang/clang-format.py" link nvim0.6, still showing "--VISUAL-- "

**Comment by zeertzjq** [comment] 2022-05-16 01:24
Duplicate of #17867

**Closed by zeertzjq** 2022-05-16 01:24 UTC
Labels: bug
