### ISSUE TITLE
Crashed when pressing : directly after start

### ISSUE THREAD

**Issue by languitar** [neovim/neovim#8922] opened 2018-08-27 14:38 UTC
- `nvim --version`:

```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently?
- Operating system/version: archlinux64
- Terminal name/version: termite
- `$TERM`: `xterm-termite`

### Steps to reproduce using `nvim -u NORC`

Can't tell.

### Actual behaviour

```
           PID: 27508 (nvim)
           UID: 1000 (languitar)
           GID: 1000 (languitar)
        Signal: 11 (SEGV)
     Timestamp: Mon 2018-08-27 16:34:46 CEST (1min 35s ago)
  Command Line: nvim src/autosuspend/__init__.py
    Executable: /usr/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (languitar)
       Boot ID: 1d3f776e23874268868101280bf566dc
    Machine ID: 0fb6577e559143d0aa8bdc54f7bb4f7b
      Hostname: jaco
       Storage: /var/lib/systemd/coredump/core.nvim.1000.1d3f776e23874268868101280bf566dc.27508.1535380486000000.lz4
       Message: Process 27508 (nvim) of user 1000 dumped core.
                
                Stack trace of thread 27508:
                #0  0x00007fb879215bef __memmove_avx_unaligned_erms (libc.so.6)
                #1  0x000055f17db32e45 put_on_cmdline (nvim)
                #2  0x000055f17db3ad68 n/a (nvim)
                #3  0x000055f17dc3dc10 state_enter (nvim)
                #4  0x000055f17db37748 n/a (nvim)
                #5  0x000055f17db257a9 do_cmdline (nvim)
                #6  0x000055f17dba2208 n/a (nvim)
                #7  0x000055f17dbab377 n/a (nvim)
                #8  0x000055f17dc3dc10 state_enter (nvim)
                #9  0x000055f17dba278a normal_enter (nvim)
                #10 0x000055f17da815aa main (nvim)
                #11 0x00007fb8790da223 __libc_start_main (libc.so.6)
                #12 0x000055f17da8256a _start (nvim)
```

**Comment by justinmk** [comment] 2018-08-27 16:42
Duplicate of https://github.com/neovim/neovim/issues/8857

**Closed by justinmk** 2018-08-27 16:42 UTC
