### ISSUE TITLE
Vim syntax highlighting is broken when lua code blocks are used (regression since nvim 0.8.0)

### ISSUE THREAD

**Issue by doronbehar** [neovim/neovim#21025] opened 2022-11-11 18:41 UTC
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

NixOS/(unstable channel)

### Terminal name/version

Alacritty/0.11.0

### $TERM environment variable

tmux-256color

### Installation

Nix package manager

### How to reproduce the issue

Use and open this `init.vim`:

```nvim
lua << EOF
print("hello world!")
EOF
let g:vim_code_shows_good = 1
" TRY TO REMOVE this comment and play with adding more comments etc.
" Syntax highlighting is a mess from here on
" 
let g:vim_code_shows_good = 0
```

No need for plugins, I reproduce the issue with `env XDG_CONFIG_HOME=$PWD nvim nvim/init.vim`.

### Expected behavior

Syntax highlighting showing good, as in 0.7.2:

![image](https://user-images.githubusercontent.com/10998835/201409318-46e5f799-8244-447e-ba8e-1e0a9dacdfb5.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/10998835/201409346-672803ea-db81-48d5-a991-20049e838e29.png)

**Comment by clason** [comment] 2022-11-11 18:45
Duplicate of #20456

**Closed by clason** 2022-11-11 18:45 UTC
Labels: bug
