### ISSUE TITLE
`filetype` of symlink target file is not set

### ISSUE THREAD

**Issue by hexium310** [neovim/neovim#27914] opened 2024-03-18 16:44 UTC
### Problem

The filetype of a symlink target file whose path matches with `pattern` in filetype.lua isn't set. This issue occurs when a symlink **source file** path mismatches with `pattern`, and a **target file** path matches with it, and doesn't reproduce in Vim. 

The following table shows the difference in filetype between opening the source file and the opening target file of symlink when the source file path matches or mismatches.

in Neovim:
|| matching source path with `pattern` | NOT matching source path with `pattern` |
| --- | :---: | :---: |
| source file | set | not set |
| target file | set | **not set** |

in Vim:
|| matching source path with `pattern` | NOT matching source path with `pattern` |
| --- | :---: | :---: |
| source file | set | not set |
| target file | set | **set** |

### Steps to reproduce

1. `source setup.sh` for setup

`setup.sh`
```sh
export mismatched=$(mktemp -d)
export matched=$(mktemp -d)
mkdir -p config/git .config/git $mismatched/.config $matched/.config
touch config/git/config .config/git/config
ln -s $PWD/config/git $mismatched/.config/git
ln -s $PWD/.config/git $matched/.config/git
```

2. `nvim --clean -S minimal.vim`
  The first and second filetypes are `filetype=`, and the others are `filetype=gitconfig`.
3. `vim --clean -S minimal.vim`
  Only the first filetype is `filetype=`, and the others are `filtype=gitconfig`.

`minimal.vim`
```vim
" Makes Vim message format the same as Neovim message format
set shortmess=ltToOCF
filetype on

echo 'mismatched, actual file'
e config/git/config
set ft?
bw

echo 'mismatched, symlinked file'
e $mismatched/.config/git/config
set ft?
bw

echo 'matched, actual file'
e .config/git/config
set ft?
bw

echo 'matched, symlinked file'
e $matched/.config/git/config
set ft?
bw
```

### Expected behavior

The filetype of a symlink **target file** whose path matches with `pattern` when a **source file** path mismatches with `pattern` should be set the same as in Vim.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2632+ge3bd04f2a

### Vim (not Nvim) behaves the same?

no, Vim version 9.1.151

### Operating system/version

Arch Linux on WSL

### Terminal name/version

alacritty 0.13.1 (fe2a3c56)

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by clason** [comment] 2024-03-18 16:55
Must be Windows-specific (symlinks usually are...); seems to work fine in macOS (but not 100% sure since the expected description is a bit confusing to me -- can you just post the literal output? -- and I get `E79: Cannot expand wildcards`).

By the way, you should test with `nvim --clean`, not `-u NONE`.

**Comment by hexium310** [comment] 2024-03-18 18:11
I apologize for any confusion. I updated the steps to reproduce; the first step update is to use the `source` shell command and to stop using the `realpath` command; the second and third steps are to use `--clean` not `-u NONE`.

I can reproduce it in old macOS (12.7.2).

The outputs of the second and third steps are below.
in Neovim:
```
mismatched, actual file
  filetype=
mismatched, symlinked file
  filetype=
matched, actual file
  filetype=gitconfig
matched, symlinked file
  filetype=gitconfig
```

in Vim:
```
mismatched, actual file
  filetype=
mismatched, symlinked file
  filetype=gitconfig
matched, actual file
  filetype=gitconfig
matched, symlinked file
  filetype=gitconfig
```

This is a GIF in which I reproduced this issue.
![filetype](https://github.com/neovim/neovim/assets/10758173/31ac148a-ae9d-445b-9c96-821cf5c1aa6d)

**Comment by clason** [comment] 2024-03-18 18:15
Ok, with these steps I can reproduce. I'll have to investigate, but if this is indeed due to how libuv handles symlinks, I'm afraid this will be "wontfix" as the general benefits of the Lua implementation vastly outweigh this frankly niche-looking edge case.

**Comment by zeertzjq** [comment] 2024-03-18 23:09
I also found some other difference:
1. `nvim --clean "$mismatched/.config/git/config"` results in filename `config/git/config` and does not set filetype.
2. `nvim --clean +"edit $mismatched/.config/git/config"` results in filename `$mismatched/.config/git/config` and does not set filetype.
3. `vim --clean "$mismatched/.config/git/config"` results in filename `$mismatched/.config/git/config` and sets filetype to `gitconfig`.
4. `vim --clean +"edit $mismatched/.config/git/config"` results in filename `$mismatched/.config/git/config` sets filetype to `gitconfig`.

So there seem to be two problems here, one in startup arguments and one in filetype detection.

**Comment by zeertzjq** [comment] 2024-03-18 23:47
Related https://github.com/neovim/neovim/pull/19218#issuecomment-1173493550

Using `args.file` instead of `args.match` solves the problem with `:edit`.

**Comment by zeertzjq** [comment] 2024-03-18 23:56
>     1. `nvim --clean "$mismatched/.config/git/config"` results in filename `config/git/config` and does not set filetype.

It seems that the symlink is resolved when using an absolute path, but not a relative path.

**Comment by zeertzjq** [comment] 2024-03-19 12:13
Actually using `args.file` isn't the correct solution either, because it may be the resolved path if `expand('<afile>')` has been called previously. I think this requires a new feature.

**Closed** 2024-03-23 03:46 UTC
Labels: bug, filetype
