### ISSUE TITLE
Feature request: ability to map key-release.

### ISSUE THREAD

**Issue by sassanh** [neovim/neovim#5315] opened 2016-09-08 11:43 UTC
Every thread in internet talking about adding key-release to vim is terminated by "not all environments support it, and vim is supposed to run on many environments." But if that logic is true then we should drop features like cursor shapes, true color, etc. Lets just give the user the ability to have this feature and turn it off by default like other features that require terminal to support something.

**Comment by bfredl** [comment] 2016-09-08 12:33
Duplicate of #3253

I don't think anyone in the neovim dev community is strongly against it. What is needed is rather a more fleshed out proposal how this will be represented in the vim/neovim keymap "language", interact with "normal" keybindings and so forth, or maybe even a prototype implementation.

(personally I "gave up" on gvim ever implementing this two years ago, and instead implemented an "input method" that have the change of preproccesing any X11 keyboard event before they reach gvim (or terminal+nvim nowadays) so I can have proper key chord and all kinds of fancy stuff).

**Closed** 2016-09-08 12:36 UTC
Labels: enhancement, io
