### ISSUE TITLE
Increased segmentation faults as of late

### ISSUE THREAD

**Issue by stefanpenner** [neovim/neovim#2956] opened 2015-07-04 23:27 UTC
When using a terminal buffer with lots of output and some fuzzy finder (like control-p) im getting regular segfaults.

Please let me know how best to instrument, so I can provide a better bug report.

**Comment by tarruda** [comment] 2015-07-05 00:05
A backtrace of the core dump would be helpful, see [this](https://github.com/neovim/neovim/wiki/Development-tips#core-dumps) for more information.

Also, can you isolate a minimal nvimrc and set of plugins that cause the crash? I can dig the bug more quickly if I reproduce locally.

**Comment by stefanpenner** [comment] 2015-07-05 00:34
> Also, can you isolate a minimal nvimrc and set of plugins that cause the crash? I can dig the bug more quickly if I reproduce locally.

I'll start pruning it down. It doesn't happen all the time, maybe 3times/hour. So it'll be abit before i have a good reduced example for you.

**Comment by tarruda** [comment] 2015-07-05 00:35
Ok. Also enable core dumps so you can paste a backtrace next time a segfault happens

**Comment by Pyrohh** [comment] 2015-07-08 17:42
@stefanpenner I don't doubt nvim has been segfaulting for you, but since there's no specific details yet, I'll close this.

Please feel free to re-open this issue once you've encountered one, or can provide more information.

**Closed by Pyrohh** 2015-07-08 17:42 UTC

**Comment by stefanpenner** [comment] 2015-07-13 23:31
I just got the right GDB running on my mac, (silly apple for not upstreaming the patches). But now it appears the problem is gone, maybe https://github.com/neovim/neovim/commit/366aa8c1963fadabc164e823b6ba758759a30178 ?

**Comment by justinmk** [comment] 2015-07-14 01:15
@stefanpenner If you run OS X, usually the backtrace will be in Console.app, without having to enable core dumps.

**Comment by tarruda** [comment] 2015-07-14 01:16
> I just got the right GDB running on my mac, (silly apple for not upstreaming the patches). But now it appears the problem is gone, maybe 366aa8c ?

I don't think so, that commit only changes how nvim API handles out of bounds indexes, it shouldn't fix any crashes.

In any case you will be better equipped to paste the backtrace now that gdb is working, so feel free to reopen the issue when/if you encounter it again.
