### ISSUE TITLE
quitting out slow with packer.nvim

### ISSUE THREAD

**Issue by jamestrew** [neovim/neovim#18670] opened 2022-05-21 01:36 UTC
### Neovim version (nvim -v)

NVIM v0.8.0-dev+211-g4c7462fdb

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux 5.17.5-arch1-1

### Terminal name/version

kitty 0.25.0

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

I've git bisected to isolate the commit.
I've also come to find this issue exists when using `packer.nvim`. `nvim -u NONE` doesn't cause this issue but I figured this might be a nvim issue as opposed to a packer issue.

1. Get minimal_init.lua https://gist.github.com/jamestrew/7ba588b8c956db8c4829e6784b09f448
2. Check out neovim 4c7462fd and build/install
3. open nvim with `nvim -u minimal_init.lua`
4. Close out of nvim with `:q`

### Expected behavior

nvim promptly closes and can start typing in the terminal shell prompt almost immediately.

### Actual behavior

Terminal hangs for approximately 2-3 secs and typing immediately after hitting `:q` results in something like this: 
![image](https://user-images.githubusercontent.com/66286082/169629187-4152bfe8-2582-418f-b8db-505590cffa13.png)

It even shows a seg fault message occasionally after quitting.

**Comment by gpanders** [comment] 2022-05-21 01:39
This only happens in Debug builds, which are used for, well, debugging. If you’re building from source to actually *use* Neovim, then you should set the `CMAKE_BUILD_TYPE` variable to Release or RelWithDebInfo when you run `make`.

The cause of the hang is that there are active libuv handles not being closed correctly, so Neovim waits is waiting for them to close before force-closing them. The “fix” is to find the offending plugins and fix it there.

**Comment by gpanders** [comment] 2022-05-21 01:40
See https://github.com/neovim/neovim/pull/18582 for related discussion.

**Closed by gpanders** 2022-05-21 01:39 UTC
Labels: bug

**Comment by andmis** [comment] 2022-06-02 01:21
@justinmk was this pin deliberate?

**Comment by jamestrew** [comment] 2022-06-04 00:05
Personally, I had building using default options (`make && sudo make install`) for a while going off the build instructions in the [Building Neovim quick start](https://github.com/neovim/neovim/wiki/Building-Neovim#quick-start).

I frankly never even noticed I was running the debug build until I came across this issue. Even if I did, I don't know that I would've cared.

**Comment by CSpencerND** [comment] 2022-06-04 00:29
> Personally, I had building using default options (`make && sudo make install`) for a while going off the build instructions in the [Building Neovim quick start](https://github.com/neovim/neovim/wiki/Building-Neovim#quick-start).
> 
This.
I personally find the build instructions confusing, as there are something like 3 different pages explaining it slightly differently. Once you understand it, it's very easy, but when I was brand new to this I found it pretty overwhelming.

**Comment by Shougo** [comment] 2022-06-04 07:05
I have found `nvim-lspconfig` causes the problem in debug mode.

**Comment by lewis6991** [comment] 2022-08-31 15:39
Been looking into this a little bit. As mentioned, the issue is entirely due to plugins not closing uv handles. Many of these handles are intended to live as long as the Neovim process, so the only way to avoid the hang is to close them in a `VimLeavePre` autocmd.

Should we really be expecting plugins to close uv handles themselves, or should Neovim close all of them on exit?

**Comment by dundargoc** [comment] 2022-09-30 07:18
@nyuszika7h does it happen when you use `Release`  build type as well?

**Comment by justinmk** [comment] 2022-09-30 09:13
> Should we really be expecting plugins to close uv handles themselves, or should Neovim close all of them on exit?

Nvim should close them on exit.

**Comment by KillTheMule** [comment] 2022-09-30 09:32
Check out https://github.com/neovim/neovim/issues/12896#issuecomment-926760700, this has been a major source of slow exit and even indefinite hangs for me. Excluding the blasted NFS filesystems from shada fixed it all for me.

**Comment by lewis6991** [comment] 2022-09-30 10:15
#12896 is a different issue to the closing of uv handles. The latter is also only present on debug builds.

**Comment by KillTheMule** [comment] 2022-09-30 10:22
Sure, I just wanted to point that out to @nyuszika7h in case that's their problem :)

**Comment by JasonGrace2282** [comment] 2024-02-14 03:18
This happened to me after deleting my swap files at `~/.local/state/nvim/swap`. The easiest solution was (on archlinux at least) to just `rm -rf ~/.local/state/nvim ~/.local/share/nvim` and have neovim regenerate everything (I did have to reinstall my plugins though).
