### ISSUE TITLE
Regex substitution doesn't substitute newlines

### ISSUE THREAD

**Issue by ararslan** [neovim/neovim#4352] opened 2016-02-27 05:12 UTC
- Neovim version: 0.1.2
- Operating system: Mac OS X 10.10.5 Yosemite (independently reproduced on Debian Unstable Sid)
- Terminal emulator: Terminal.app

### Actual behaviour

`:%s/\n//` highlights newlines but doesn't replace them. See here:

![screen shot 2016-02-26 at 9 06 42 pm](https://cloud.githubusercontent.com/assets/6396159/13370907/0800647a-dccd-11e5-9606-85f26005c96f.png)

Oddly enough, it *does* work for spaces, i.e. `:%s/\s//`, but not for newlines.

### Expected behaviour

Newlines should be replaced, as is the case in Vim. See here:

![screen shot 2016-02-26 at 9 07 17 pm](https://cloud.githubusercontent.com/assets/6396159/13370910/1a81708a-dccd-11e5-86ef-6fe25ad0b9a2.png)

### Steps to reproduce

I open NeoVim, go to insert mode, enter some text with newlines, back to normal mode, `:%s/\n//`.

**Comment by KeyboardFire** [comment] 2016-02-27 05:14
Er, Bash isn't a terminal emulator, but it really isn't relevant here.

Other notes:

- `:%s/\n/anything` works, including replacing newline with spaces (i.e. imitating `:%j`).

- `:%s/\n//i` and `:%s/\n//I` **do** work, strangely enough.

**Comment by wsdjeg** [comment] 2016-02-27 07:13
@ararslan I can not reproduce it with latest version neovim,and I can hi newline with `:%s/\n// `
![2016-02-27 15-12-19](https://cloud.githubusercontent.com/assets/13142418/13371572/907b74d8-dd64-11e5-9527-ca04a4cce3f3.png)

**Comment by mhinz** [comment] 2016-02-27 11:57
Most probably because of a Vim patch that wasn't merged yet. Have no time to look through them right now, though.

**Comment by ararslan** [comment] 2016-02-27 22:47
Apologies for the title change. Clearly I can't be trusted to use correct spelling when submitting issues.

**Comment by mmcdole** [comment] 2016-02-29 20:26
Related vim issue: https://github.com/vim/vim/issues/287

**Comment by mhinz** [comment] 2016-03-01 01:20
@mmcdole Thanks for mentioning the Vim issue which lead me to patch 7.4.543 which helped finding the actual issue.

**Closed** 2016-03-01 11:36 UTC
Labels: bug
