### ISSUE TITLE
Windows: removes hardlink from $MYVIMRC file when saving

### ISSUE THREAD

**Issue by mac10688** [neovim/neovim#4525] opened 2016-04-03 19:56 UTC
- Neovim version: 0.1.3-dev
- Operating system: Windows
- Terminal emulator: Neovim-qt

### Actual behaviour
Neovim removes the hardlink from the $MYVIMRC file when saving

### Expected behaviour
Neovim does not remove the hardlink I created so I can share my VIMRC file between VIM and NeoVim.

### Steps to reproduce
Open windows.
Install vim.
Edit/Create the _vimrc file located in %userprofile%
Create a hardlink using command line prompt.

"mklink /H %userprofile%\AppData\Local\nvim\init.vim %userprofile%\_vimrc"

With the link created open the init.vim file with regular vim, edit it and save it. Both init.vim and _vimrc are synced.

Open the init.vim file with neovim, edit and save. The two files are no longer synced.

**Comment by JonathanDaSilva** [comment] 2016-04-12 16:45
What I have personally done is to create the init.vim and only put one line in it:
```vim
source "path/to/your/vimrc"
```

Hope that will help you :p

**Comment by ZyX-I** [comment] 2016-04-12 16:49
This should depend on `&backupcopy` setting. But I do not see its default changed compared to Vim.

**Comment by equalsraf** [comment] 2016-04-15 13:13
Confirmed here, happens with any hardlink. `set backupcopy=yes` avoids the issue. While @ZyX-I is right the default did not change, it seems the windows branch for checking this was removed, in [fileio.c](https://github.com/neovim/neovim/blob/master/src/nvim/fileio.c#L2701) there is only an UNIX check, in vim/vim there was a [windows specific check](https://github.com/vim/vim/blob/master/src/fileio.c#L3685).

The hardlink check should be portable though, I've removed the `UNIX` guard (04bbe73) and it seems to work as intended.

There are a few similar situation in fileio.c, some are [trivial :smirk:](https://github.com/neovim/neovim/blob/master/src/nvim/fileio.c#L184), others not so clear to me if they should run on Windows.

**Comment by equalsraf** [comment] 2016-04-17 21:03
@mac10688 I've added a fix for this in #810 can you check if it all works out for you?

**Comment by justinmk** [comment] 2016-04-29 02:38
Closed by https://github.com/neovim/neovim/pull/4670

**Closed by justinmk** 2016-04-29 02:38 UTC
Labels: bug, platform:windows
