### ISSUE TITLE
Screen tearing inside tmux inside Alacritty

### ISSUE THREAD

**Issue by nerosnm** [neovim/neovim#14760] opened 2021-06-09 21:00 UTC
- `nvim --version`: NVIM v0.5.0-dev
- Operating system/version: macOS 11.4
- Terminal name/version: alacritty 0.8.0 (a1b13e6)
- `$TERM`: tmux-256color
- `tmux -V`: tmux 3.2

### Steps to reproduce using `env -i TERM=ansi-256color "$(which nvim)"`

- open Alacritty
- run `tmux`
- run `env -i TERM=ansi-256color "$(which nvim)"`
- open a file that is at least a few screens long
- move down to the end of the file and then up again with `C-f` and `C-b`
- move the cursor down to the bottom of the file and up

### Actual behaviour

Screen tearing; lines are only refreshed when the cursor reaches them, resulting in duplicate lines that display in the wrong place. In my case, the lightline also disappears.

### Expected behaviour

No screen tearing. All lines refresh regardless of whether the cursor has reached them.

https://user-images.githubusercontent.com/13041332/121428821-26d4d500-c96e-11eb-9725-cba3038edf66.mov

**Comment by nerosnm** [comment] 2021-06-10 16:20
I've narrowed this down to a specific character in a specific file, which is the only file that actually triggers this. That file contains the following line:

```nix
          symbol = "❄️ ";
```

It's when and only when that line comes onto screen that the issue appears.

**Comment by rktjmp** [comment] 2021-06-27 17:10
Having a hard time reproing this but I have seen the same behaviour, a long time ago. I thought it was maybe related to undo/redoing.

- Do you see the same thing with say, `cat file | less`, etc?
- Do you see it with -u NORC?

**Comment by nerosnm** [comment] 2021-07-01 10:46
Interesting. No, neither of those things exhibits the issue.

**Comment by rktjmp** [comment] 2021-07-01 19:39
Maybe you could have a peek around your config.

I would start with no plugins to see if it's a settings issue then enable half of the plugins, see it it shows up, half again, etc etc.

**Comment by justinmk** [comment] 2021-07-03 14:10
duplicate of https://github.com/neovim/neovim/issues/14434

**Closed by justinmk** 2021-07-03 14:10 UTC
Labels: bug
