### ISSUE TITLE
SIGABRT: failed assertion blk_dlms.empty

### ISSUE THREAD

**Issue by sanga** [neovim/neovim#13122] opened 2020-10-20 07:07 UTC
- `nvim --version`: NVIM v0.5.0-762-g9817d9914
- `vim -u DEFAULTS` (version: ) behaves differently? (I presume this istreesitter related so I doubt it does)
- Operating system/version: ubuntu 20.04
- Terminal name/version: alacritty
- `$TERM`: alacritty

### Steps to reproduce

Open the following file in nvim and type `(` after `main` -> failed assertion

```python
def main():
    pass

if __name__ == '__main__':
    main
```

### Actual behaviour
```
src/scanner.cc.253: bool {anonymous}::Scanner::scan(TSLexer*, const bool*): Assertion `blk_dlma.empty()` failed
```
### Expected behaviour
Don't crash

**Comment by vigoux** [comment] 2020-10-20 07:11
Known bug with tree-sitter, duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/602, maybe we should keep the discussion there ?

**Comment by sanga** [comment] 2020-10-20 07:19
ah crap. I checked neovim's issues but not nvim-treesitter's - it's a bit hard to know where the responsibilities lie sometimes. Whatever is most convenient for you guys.

**Comment by vigoux** [comment] 2020-10-20 07:32
From what I know, this is caused by the nvim-treesitter / completion-nvim combination, putting the markdown parser on error.
Maybe concentrating all the information in the aforementioned issue is better, closing.

**Closed by vigoux** 2020-10-20 07:32 UTC
Labels: bug, treesitter

**Comment by ruifm** [comment] 2020-10-20 13:37
> Maybe concentrating all the information in the aforementioned issue is better, closing.

Should a plugin ever be allowed to cause a segfault? Seems like a neovim API issue to me :thinking:

**Comment by vigoux** [comment] 2020-10-20 13:52
For now there is no proof it is, as the segfault is actually happening _in_ the markdown parser.

**Comment by ruifm** [comment] 2020-10-20 13:56
> For now there is no proof it is, as the segfault is actually happening _in_ the markdown parser.

But shouldn't crashes in child processes/dynamic libraries be caught and handled by the parent process, produce and error message and life should go on without a neovim crash?

**Comment by vigoux** [comment] 2020-10-20 14:02
Unfortunately not, because nothing is made async, the way it works is by loaded the parsers binaries into nvim, an running it synchronously.
No master/child process then.
