### ISSUE TITLE
crash/render issues with 'termbidi', 'rightleft' after inputting hebrew

### ISSUE THREAD

**Issue by Kozova1** [neovim/neovim#11925] opened 2020-02-21 09:36 UTC
neovim crashes when termbidi is set after setting rightleft and then inputting hebrew

OS: Endeavour OS
## neovim version:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
I can't seem to find $NVIM_LOG_FILE

## Steps to reproduce:
1. `nvim -u NORC +"set rightleft"`
2. enter insert mode with `i`
3. type some hebrew characters
4. exit insert mode
5. `:set termbidi`
and then it crashes with a SIGSEGV

## Stacktrace:
```gdb

GNU gdb (GDB) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/nvim...
(No debugging symbols found in /usr/bin/nvim)
[New LWP 3464]
[New LWP 3465]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `nvim -u NORC'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000562846f3bbaf in ?? ()
[Current thread is 1 (Thread 0x7f911d4bacc0 (LWP 3464))]
(gdb) quit
           PID: 3464 (nvim)
           UID: 1000 (kozova1)
           GID: 1000 (kozova1)
        Signal: 11 (SEGV)
     Timestamp: Fri 2020-02-21 11:20:59 IST (4min 40s ago)
  Command Line: nvim -u NORC
    Executable: /usr/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (kozova1)
       Boot ID: 6848ff9de67f4ae6b0d18a32640e4160
    Machine ID: 7802cd5b0da44cc1bed7572eaf47feae
      Hostname: thinkpad
       Storage: /var/lib/systemd/coredump/core.nvim.1000.6848ff9de67f4ae6b0d18a32640e4160.3464.1582276859000000000000.lz4
       Message: Process 3464 (nvim) of user 1000 dumped core.
                
                Stack trace of thread 3464:
                #0  0x0000562846f3bbaf n/a (nvim + 0x9fbaf)
                #1  0x0000562846f3c583 n/a (nvim + 0xa0583)
                #2  0x0000562846fcbb80 n/a (nvim + 0x12fb80)
                #3  0x00005628470697e5 n/a (nvim + 0x1cd7e5)
                #4  0x0000562846f5d233 state_enter (nvim + 0xc1233)
                #5  0x000056284706c327 n/a (nvim + 0x1d0327)
                #6  0x0000562847060752 getcmdline (nvim + 0x1c4752)
                #7  0x000056284707e645 do_cmdline (nvim + 0x1e2645)
                #8  0x0000562846ff9774 n/a (nvim + 0x15d774)
                #9  0x0000562847000e1f n/a (nvim + 0x164e1f)
                #10 0x0000562846f5d233 state_enter (nvim + 0xc1233)
                #11 0x00005628470025dc normal_enter (nvim + 0x1665dc)
                #12 0x0000562846f03d37 main (nvim + 0x67d37)
                #13 0x00007f911d976023 __libc_start_main (libc.so.6 + 0x27023)
                #14 0x0000562846f04dce _start (nvim + 0x68dce)
                
                Stack trace of thread 3465:
                #0  0x00007f911da4e70e epoll_wait (libc.so.6 + 0xff70e)
                #1  0x00007f911d91736a uv__io_poll (libuv.so.1 + 0x2036a)
                #2  0x00007f911d906fc7 uv_run (libuv.so.1 + 0xffc7)
                #3  0x0000562847096226 loop_poll_events (nvim + 0x1fa226)
                #4  0x0000562846f4b59e n/a (nvim + 0xaf59e)
                #5  0x00007f911d8de46f start_thread (libpthread.so.0 + 0x946f)
                #6  0x00007f911da4e3d3 __clone (libc.so.6 + 0xff3d3)


```

**Comment by bfredl** [comment] 2020-02-21 19:47
Cannot reproduce, neither with 0.4.3 nor master. Perhaps it depends on the choice of text. Can you upload an example file which causes a crash?

**Comment by Kozova1** [comment] 2020-02-23 09:00
also crashes when setting rightleft and then opening a file with hebrew text in it.
sample text:
שדגשדגשדגשגד

**Comment by bfredl** [comment] 2020-02-23 10:07
I get render issues (chars added in the wrong place) but no crash.

**Comment by Kozova1** [comment] 2020-02-23 12:41
Interesting. I've just checked and it seems as if it crashes only in specific terminals (doesn't crash in xterm or kitty). I could only get it to crash in Konsole 19.12.2. didn't check other versions of konsole.

**Comment by bfredl** [comment] 2020-02-23 20:14
@Kozova1 but is it _nvim_ that is crashing and not Konsole?

**Comment by Kozova1** [comment] 2020-02-23 20:36
definitely nvim itself, konsole continues to work as expected and the crash dump is from neovim

**Comment by Kozova1** [comment] 2020-02-25 17:44
@bfredl what terminal do you use? Maybe it is dependant on the terminal.

**Comment by bfredl** [comment] 2020-02-25 18:30
I use `pangoterm` which identifies itself as `TERM=xterm`

**Comment by doronbehar** [comment] 2020-11-14 08:48
I am pretty sure this can be closed now with https://github.com/neovim/neovim/pull/12698 merged.

**Comment by glacambre** [comment] 2021-06-07 04:49
Yep, I can't reproduce on master, so let's close this. @Kozova1 let us know if you're still experiencing this issue on master/nightly and we'll reopen :).

**Closed by glacambre** 2021-06-07 04:49 UTC
Labels: 9.needs:repro, bug-crash, input

**Comment by Kozova1** [comment] 2021-06-07 06:12
Seems to no longer be an issue. Thanks!
