### ISSUE TITLE
Windows: backspace and shift issues

### ISSUE THREAD

**Issue by K1DV5** [neovim/neovim#11926] opened 2020-02-21 12:03 UTC
In the terminal, in normal and command modes (and maybe other modes other than insert) typing `<bs>` or using any mapping that uses shift does not work. But typing `<c-bs>` works as `<bs>`. Is windows console intercepting the keys? Is there a way to fix it?

EDIT: I solved the backspace issue by logging the keys with `nvim -w keys.txt` and looking up the character typed in `:digraphs`. What nvim actually receives when `<bs>` is pressed is the raw backspace character ^H (`<c-h>`) and this can be used to create a mapping.

The shift key is still problematic for me. It is not making any difference, `<tab>` and `<s-tab>` do the same thing.

**Comment by justinmk** [comment] 2020-02-21 22:06
Please don't ignore the issue template. The questions in it are almost always relevant.

**Comment by K1DV5** [comment] 2020-02-22 05:37
Sorry about the template, I didn't first think they were relevant. I don't have vim at the moment, never thought I'd need it. My nvim details are:

`nvim --version` : NVIM v0.5.0-378-gbb331a9b3
Operating system/version: Windows 10 1903
Terminal name/version: powershell
$TERM : [none]

To add to this, I've noticed this issue with all released versions before this and since about v0.3.4 (didn't test it before that). It also doesn't work with backspace and space.

**Comment by justinmk** [comment] 2020-02-22 21:44
> don't know what happened but shift now works with tab.

After upgrading Nvim, updating your system, or something else?

> It still doesn't work with backspace and space though.

You mean "shift + bs" and "shift + space" does not work? Not sure that ever worked anywhere, and the general topic is covered by https://github.com/neovim/neovim/issues/6279

 https://github.com/neovim/neovim/pull/11803 may improve some things, can you try it? Here's its zip artifact: https://ci.appveyor.com/api/buildjobs/ik3xxlhkdeyeu8xk/artifacts/build%2FNeovim.zip

**Comment by K1DV5** [comment] 2020-02-24 08:58
> After upgrading Nvim, updating your system, or something else?

Nothing, maybe I just assumed if it doesn't work with space, it will not work with tab, sorry.

> You mean "shift + bs" and "shift + space" does not work?

Yes.

I tried the artifact, apart from swapping `<bs>` and `<c-h>`, I didn't see any difference. 

If it doesn't work anywhere, it means its not a Windows only problem right? So maybe the title should be changed.

This issue does not affect Neovim-qt. Maybe there are some useful things there?

**Comment by justinmk** [comment] 2020-02-25 04:54
> If it doesn't work anywhere, it means its not a Windows only problem right? So maybe the title should be changed.

It means it is a duplicate of #6279 .

> This issue does not affect Neovim-qt

GUIs do not have this problem.

**Closed by justinmk** 2020-02-25 04:54 UTC
Labels: input, platform:windows, revisit-at-release, tui
