### ISSUE TITLE
suspend (ctrl-z) leaves terminal in strange state

### ISSUE THREAD

**Issue by phmarek** [neovim/neovim#5459] opened 2016-10-10 13:42 UTC
Debian package: neovim=0.1.5-6, Linux amd64

Starting nvim and suspending it via Ctrl-Z leaves the terminal
in a strange state.

With any of xterm, gnome-terminal, and konsole, but NOT the linux text 
console, some newlines before color codes are "eaten" at some layer.
("dmesg" for me)

It doesn't happen with the "old" vim.

So, to reproduce:

choose one of the terminal applications

```
# nvim -u NORC
<ctrl-Z>
# perl -e 'print "\33[32m[113916.534730] \33[0m\33[33musb 1-1.3.2\33[0m: SerialNumber=4\n" for 1 .. 300'
```

observe that some timestamps are at the end of the previous line
using "reset", or starting/suspending/stopping "vim" makes no difference

```
# fg
:q
```

now everything is back to normal.

The writing process (eg. "dmesg") sometimes also gets a write error on 
stdout.
Processes that don't send the whole line but individual blocks (eg. 
"colordiff" flushes after each color escape) are not affected.

This can also be observed from a ":terminal" window ;)

**Comment by phmarek** [comment] 2016-10-10 13:42
see also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840306

**Comment by justinmk** [comment] 2016-10-11 09:17
If someone wants to look at this, note that exiting `nvim` _does_ restore the terminal. So the fix could be narrowed down by comparing (bisecting) `suspend_event()` with  `mch_exit()` and/or other parts of nvim's exit/teardown routine.

> observe that some timestamps are at the end of the previous line

FWIW, I can't reproduce this with Terminal.app (macOS) nor iTerm2, connected to ubuntu VM. Each timestamp is on its own line.

**Comment by jagerman** [comment] 2016-10-31 22:54
I'm fairly sure I'm seeing the same issue: I also notice that if I background neovim, commands expecting input (like `git add -p` or `cp -i`) don't work.  It seems that attempts to read from STDIN from another program after suspending neovim result in a read error:

```
jagerman@betwixt:~$ perl -le 'my $str = <STDIN>; if (defined $str) { print "Read success: $str"; } else { print "Read error: " . int($!) . ": $!"; }'
Read error: 11: Resource temporarily unavailable
jagerman@betwixt:~$ 
```

while before launching neovim, or after quitting it instead of suspending it, I get:
```
jagerman@betwixt:~$ perl -le 'my $str = <STDIN>; if (defined $str) { print "Read success: $str"; } else { print "Read error: " . int($!) . ": $!"; }'
asdf
Read success: asdf

jagerman@betwixt:~$ 
```

One other curious observation: if I start one neovim, suspend it, then start another in that same terminal and quit it, input works again (while the first neovim is still suspended).

I see this same behaviour on the Linux console as well.

**Comment by jagerman** [comment] 2016-11-01 16:25
I investigated the STDIN read failure some more: it happens with bash 4.4, which landed in Debian unstable a bit more than a month ago.  It doesn't happen with 4.3.

@phmarek - I can't seem to reproduce your issue, specifically, but if it's still happening for you, can you try downgrading bash to 4.3 (I used the 4.3-14+b1 snapshot from http://snapshot.debian.org/package/bash/4.3-14/) and see if that resolves it?

**Comment by jagerman** [comment] 2016-11-01 16:28
I can also reproduce both @phmarek's and my issue on OS X under bash 4.4, but not under bash 4.3.

**Comment by jagerman** [comment] 2016-11-01 16:44
Here is another thing that breaks, in case this gives any clue:

```
perl -e 'print "1234567890123456789012345678901234567890123456789\n" x 500'
```
That should print 500 lines, but after suspending nvim under bash 4.4, it prints just the first 1024 bytes (i.e. 20 full lines plus the first 24 characters of the 21st line).  Similarly, in @phmarek 's example, the "eaten" characters are at 1024-byte intervals.

**Comment by justinmk** [comment] 2016-11-01 16:48
>  if I start one neovim, suspend it, then start another in that same terminal and quit it, input works again 

Yes, see note in https://github.com/neovim/neovim/issues/5459#issuecomment-252856688

@jagerman Can you build from source? If so, please try adding this to `suspend_event()` before SIGSTP:

    stream_set_blocking(input_global_fd(), true);

**Comment by jagerman** [comment] 2016-11-01 17:04
Yes, that appears to fix both issues! (Tested on Debian and OS X El Capitan, both under bash 4.4.)

**Comment by justinmk** [comment] 2016-11-02 00:23
Thanks @jagerman and @phmarek for the detailed reports.

**Closed** 2016-11-02 00:22 UTC
Labels: complexity:low, tui
