### ISSUE TITLE
No highlight when using 'global' command

### ISSUE THREAD

**Issue by linjiX** [neovim/neovim#11104] opened 2019-09-27 05:29 UTC
- `nvim --version`:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 18 2019 03:49:48)
macOS version
Included patches: 1-2050
Compiled by Homebrew
```
After 'set incsearch', vim will highlight the searching word when using 'global' command.
But not in Neovim.

- Operating system/version:
MacOS Mojave 10.16.6

- Terminal name/version:
iTerm2 3.3.4

- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:global/searching word/
```

### Actual behaviour
The searching word in `global` command will not be highlight.

### Expected behaviour
The searching word in `global` command should be highlight like using `:s` command

**Comment by justinmk** [comment] 2019-09-29 22:10
Nvim provides `:help 'inccommand'` which shows live updates of the `:s` command. We plan to support `:global` also. Patch welcome.

Duplicate of https://github.com/neovim/neovim/issues/7370

**Closed by justinmk** 2019-09-29 22:10 UTC
Labels: bug
