### ISSUE TITLE
} is replaced by ^_ when editing

### ISSUE THREAD

**Issue by nlguerra2003** [neovim/neovim#12207] opened 2020-04-29 10:47 UTC
In neovim 0.4.3 for Windows 10, whenever I type a } sign (curly brace closing), it inserts two chars: ^_ (a circunflex and an underscore) instead of inserting the desired symbol.
These two symbols can be deleted in a row (only one tap on the backspace symbol deletes all two chars, and even a _left arrow_ or _right arrow_ tap jumps directly to the opposite side), and are not saved as printable characters (both chars are saved only as **only one** hex 1F symbol, invisible to most text editors).

**Comment by glacambre** [comment] 2020-04-29 12:43
Can you reproduce this with neovim nightly?

If yes, what terminal/GUI are you running neovim in?

**Comment by Vyber90** [comment] 2020-04-29 14:33
@glacambre, nvim-qt.exe does not have this bug, as far as I am concerned.
As to nvim.exe, I tried to verify if this error happened in windows terminals. From the traditional Windows command line to Windows Powershell they both show this error.

**Comment by teto** [comment] 2020-04-29 14:56
Please try with nightly https://github.com/neovim/neovim/releases/tag/nightly ?

**Comment by Vyber90** [comment] 2020-04-29 15:06
It shows the bug as well (sorry, did not know what you meant by nightly).

**Comment by justinmk** [comment] 2020-04-29 15:44
related https://github.com/neovim/neovim/issues/11061?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDU4Nzc5ODcxMjoxMzU5NDIx&notifications_query=is%3Aunread#issuecomment-595620466

**Comment by erw7** [comment] 2020-07-20 14:59
@Vyber90 Try NVIM 0.5.0(nightly) on the following page.

https://github.com/neovim/neovim/releases

**Comment by dundargoc** [comment] 2021-11-12 23:50
I've tried neovim version 0.4.3 on windows with powershell and also had trouble inputting `{}`, while I had no problems on nvim-qt. Same for neovim version 0.4.4. I did not have same problem as @nlguerra2003 since the problem is dependent on keyboard language. I use Swedish which meant that `{ [ ] }` instead became `7 8 9 0` (aka the Alt Gr key didn't work). When I switched to English keyboard I could input `{ [ ] }` just fine. Had this issue not been almost 2 years old I'd have asked what keyboard language @nlguerra2003 is using :) . My keyboard problems went away after upgrading to neovim 0.5.0. While it's not an absolute guarantee that this is solved, it's very likely, especially considering the [many accounts of neovim input working after version 0.5.x](https://github.com/neovim/neovim/issues/11061). I will therefore elect to close this.

**Closed by dundargoc** 2021-11-12 23:50 UTC
Labels: bug, platform:windows, tui
