### ISSUE TITLE
if_ruby legacy compatibility

### ISSUE THREAD

**Issue by xanderdunn** [neovim/neovim#1770] opened 2015-01-04 04:33 UTC
Mac OSX 10.10.1.  

I have the plugin [vim-ios](https://github.com/eraserhd/vim-ios) installed via [Vundle](https://github.com/gmarik/Vundle.vim).  In vim 7.4.540, it works as expected.  I recall it also worked on stable vim: 7.4.488.  The plugin hasn't been updated in years.  However, in nvim, the commands don't seem to be found.  vim-ios registers commands like `:A` and `:Xbuild`.  Although they both work in vim,  they can't be found in nvim: `E492: Not an editor command: Xbuild`.

When I start up nvim I don't see any errors or warnings.  Looking at `:messages` doesn't show anything either.  

Let me know if there's anything I can do to help narrow it down.  Thanks!

nvim --version:
```
NVIM 0.0.0-alpha+201501031606 (compiled Jan  3 2015 16:39:59)
Commit: 10ff6ee0d7efedc4e3812b39dc8327b8aeef57a7
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-I2Cf5M/build/config -I/tmp/neovim-I2Cf5M/src -I/tmp/neovim-I2Cf5M/.deps/usr/include -I/tmp/neovim-I2Cf5M/.deps/usr/include -I/tmp/neovim-I2Cf5M/.deps/usr/include/luajit-2.0 -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-I2Cf5M/build/src/nvim/auto -I/tmp/neovim-I2Cf5M/build/include
Compiled by admin@Alex-Dunns-MacBook-Pro.local
  Features included (+) or not (-):
+acl             +farsi           -mouse_gpm       -tag_any_white
+arabic          +file_in_path    +mouse_netterm   +terminfo
+autocmd         +find_in_path    +mouse_sgr       +termresponse
-browse          +float           -mouse_sysmouse  +textobjects
+byte_offset     +folding         +mouse_urxvt     +title
+cindent         -footer          +mouse_xterm     -toolbar
-clipboard       +fork()          +multi_byte      +user_commands
+cmdline_compl   +gettext         +multi_lang      +vertsplit
+cmdline_hist    +iconv           +path_extra      +virtualedit
+cmdline_info    +insert_expand   +persistent_undo +visual
+comments        +jumplist        +postscript      +visualextra
+conceal         +keymap          +printer         +viminfo
+cscope          +langmap         +profile         +vreplace
+cursorbind      +libcall         +quickfix        +wildignore
+cursorshape     +linebreak       +reltime         +wildmenu
+dialog_con      +lispindent      +rightleft       +windows
+diff            +listcmds        +scrollbind      +writebackup
+digraphs        +localmap        +signs           -X11
-dnd             +menu            +smartindent     -xfontset
-ebcdic          +mksession       +startuptime     -xsmp
-emacs_tags      +modify_fname    +statusline      -xterm_clipboard
+eval            +mouse           +syntax          
+ex_extra        -mouseshape      +tag_binary      
+extra_search    +mouse_dec       +tag_old_static  
   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "$HOME/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"

```

**Comment by alexdunn** [comment] 2015-01-04 04:51
All of my other plugins and their commands are working as expected.

**Comment by fmoralesc** [comment] 2015-01-04 07:40
vim-ios requires ruby support, but neovim doesn't have it yet.

**Comment by alexdunn** [comment] 2015-01-04 09:15
Ahhhhhh, yes. Should have checked that. Thanks!  I wanted to close this as a dupe of an open issue, but I didn't find one. #852 and #718 cover this, but they're both closed.

**Comment by fwalch** [comment] 2015-01-06 14:08
Note that there is already a [ruby plugin for Neovim](https://github.com/alexgenco/neovim-ruby), which might provide Ruby support (`:ruby`, ...) at some point (as a "provider", see `:h nvim-provider`). Maybe file an issue there as well?

**Comment by hron84** [comment] 2015-06-30 14:01
@fwalch I do not understand one thing: that project says it's a ruby binding for NeoVim, I think it is for control NeoVim from outside. I do not read anything that refer it's a ruby "provider". It will be enough if I install that stuff to the global ruby interpreter? I want to use LustyExplorer plugin with NeoVim.

**Comment by Shougo** [comment] 2015-06-30 14:09
@hron84 Ruby binding is you can create remote Ruby plugins for neovim.
But it is not if_ruby program.
To support if_ruby probram, the ruby binding must support legacy ruby provider interface.
And the neovim-ruby project is not developed...

**Comment by fwalch** [comment] 2015-06-30 14:27
>  I do not read anything that refer it's a ruby "provider".

Yes, because it is not (yet?) a provider. That's why I said it might provide `+ruby` *at some point*. At the moment, there's no way you can get LustyExplorer to work with Neovim, sorry.

**Comment by hron84** [comment] 2015-07-01 10:06
@fwalch thanks for clarifying this. Then it seems like my change will be snoozed until if_ruby plugins get supported since I work with a lot of big codebases with Vim, and LustyExplorer makes handling multiple files easy - easier than I can achieve via commands with my current Vim knowledge.

**Comment by fwalch** [comment] 2015-07-01 10:18
@hron84 There's apparently a Python port of LustyExplorer: http://www.vim.org/scripts/script.php?script_id=3659

Otherwise, well, maybe plugin/provider development will speed up after the first release, so keep an eye on this issue :-)

**Comment by stephenprater** [comment] 2016-08-09 23:17
Neovim supports if_ruby in the latest builds.  Maybe give it a shot?

**Closed** 2016-08-09 23:55 UTC
Labels: compatibility

**Comment by sencer** [comment] 2016-08-13 23:07
I am trying to use notmuch's vim plugin, which is written mostly in ruby. It works with usual vim, but not with neovim (0.15).

> :CheckHealth
> 
> Checking: Ruby                                                                                                                                                 
>   Ruby Version: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]                                                                                                 
>   Host Executable: /usr/local/bin/neovim-ruby-host                                                                                                             
>   Host Version: 0.2.4

**Comment by Shougo** [comment] 2016-08-14 06:20
@sencer You should create new issue for it.
