### ISSUE TITLE
Malformatting with nvim-lsp / gopls on  buf_set_keymap("n", "ff", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)

### ISSUE THREAD

**Issue by sergii4** [neovim/neovim#14117] opened 2021-03-12 13:01 UTC
- `nvim --version`: NVIM v0.5.0-dev+nightly
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: macOS 11.1 (20C69)
- Terminal name/version: Alacritty
- `$TERM`: screen-256colo

### Actual behaviour
Malformat go code with 
```
buf_set_keymap("n", "ff", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
```
Format code
```
func DBConn(cfg Config) (*sql.DB, error) {

	psqlInfo := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable",
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
  db, err := sql.Open("postgres", psqlInfo)
  if err != nil {
	  return nil, errors.Wrap(err, "can't establish connection")
  }

  err = db.Ping()
  if err != nil {

	  return nil, errors.Wrap(err, "can't ping DB")
  }

  fmt.Println("Successfully connected!")
	return db, nil
}
```
to
```
func DBConn(cfg Config) (*sql.DB, error) {

	psqlInfo := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable",
		cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
  db, err := sql.Open("postgres", psqlInfo)
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
  if err != nil {
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
	  return nil, errors.Wrap(err, "can't establish connection")
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
  }
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)

	if err != nil {

		return nil, errors.Wrap(err, "can't ping DB")
	}
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
  }
	fmt.Println("Successfully connected!")
	return db, nil
}
```
but `go fmt ./...` works correct
### Expected behaviour
Formatting correct

<details>
 <summary>init.vim </summary>
call plug#begin()
Plug 'neovim/nvim-lspconfig'
Plug 'mileszs/ack.vim'
Plug 'justinmk/vim-dirvish'
Plug 'vim-airline/vim-airline'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'dracula/vim', { 'as': 'dracula' }
call plug#end()

lua <<EOF
local nvim_lsp = require('lspconfig')

local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }
  buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
  buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
  buf_set_keymap('n', 'ga', '<Cmd>lua vim.lsp.buf.code_action()<CR>', opts)
  buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
  buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
  buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
  buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
  buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
  buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
  buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
  buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
  buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
  buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
  buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)

  -- Set some keybinds conditional on server capabilities
  if client.resolved_capabilities.document_formatting then
    buf_set_keymap("n", "ff", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
  elseif client.resolved_capabilities.document_range_formatting then
    buf_set_keymap("n", "ff", "<cmd>lua vim.lsp.buf.range_formatting()<CR>", opts)
  end

  -- Set autocommands conditional on server_capabilities
  if client.resolved_capabilities.document_highlight then
    vim.api.nvim_exec([[
      hi LspReferenceRead cterm=bold ctermbg=red guibg=LightYellow
      hi LspReferenceText cterm=bold ctermbg=red guibg=LightYellow
      hi LspReferenceWrite cterm=bold ctermbg=red guibg=LightYellow
      augroup lsp_document_highlight
        autocmd! * <buffer>
        autocmd CursorHold <buffer> lua vim.lsp.buf.document_highlight()
        autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()
      augroup END
    ]], false)
  end
end

-- Use a loop to conveniently both setup defined servers 
-- and map buffer local keybindings when the language server attaches
nvim_lsp.gopls.setup{
	-- cmd = {'gopls', '-remote=auto', '-logfile=/tmp/gopls.log', '-rpc.trace'},
	cmd = {'gopls'},
	on_attach = on_attach
}

vim.lsp.set_log_level("debug")
EOF

"nnoremap <silent> ff    <cmd>lua vim.lsp.buf.formatting()<CR>
"autocmd BufWritePre *.go lua vim.lsp.buf.formatting()

" https://stackoverflow.com/questions/6991638/how-to-auto-save-a-file-every-1-second-in-vim
let g:autosave_time = 1

set ttyfast                     " Indicate fast terminal conn for faster redraw
colorscheme dracula

" Set leader shortcut to a comma ','. By default it's the backslash
let mapleader = ","

set number                      " Show line numbers

" Jump to next error with Ctrl-n and previous error with Ctrl-m. Close the
" quickfix window with <leader>a
map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>

</details>

**Comment by mjlbach** [comment] 2021-03-12 16:33
Duplicate of #14121. Please don't crosspost issues between nvim-lspconfig and nvim-lsp.

**Closed by mjlbach** 2021-03-12 16:33 UTC
Labels: bug
