### ISSUE TITLE
Saving large files is extremely slow when using nvim-lsp and rustfmt

### ISSUE THREAD

**Issue by nerosnm** [neovim/neovim#14205] opened 2021-03-24 11:31 UTC
- `nvim --version`:

    ```
    NVIM v0.5.0-dev+c1fbc2ddf
    Build type: Release
    LuaJIT 2.1.0-beta3
    Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210301-91403-1qxibkt/build/config -I/tmp/neovim-20210301-91403-1qxibkt/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210301-91403-1qxibkt/build/src/nvim/auto -I/tmp/neovim-20210301-91403-1qxibkt/build/include
    Compiled by soren@Rigel.local
    
    Features: +acl +iconv +tui
    See ":help feature-compile"

       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-c1fbc2d_1/share/nvim"

    Run :checkhealth for more info
    ```

- `vim -u DEFAULTS` (version: ) behaves differently? Yes, because this issue involves nvim-lsp
- Operating system/version: macOS 10.15.7 (19H114)
- Terminal name/version: alacritty 0.7.2 (5ac8060)
- `$TERM`: tmux-256color

### Steps to reproduce (not using `-u NORC` since this relies on nvim-lsp)

I filed this originally as rust-lang/rust.vim#438 and included reproduction steps there, but I'll put them here too:

- Install `nvim` from the tip of `master` (must be an 0.5 version)
- Install `rustup`
- Run `rustup toolchain install nightly-2021-03-01`
- Run `rustup component add rustfmt --toolchain nightly-2021-03-01`
- Install `rust-analyzer` (I'm on rust-analyzer 2021-02-15, installed via Nix unstable)
- Put the following minimal config in `~/.config/nvim/init.vim`:

    <details>
    
    ```vim
    set shell=/bin/bash
    
    " Install vim-plug if it isn't already
    if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
      silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      au VimEnter * PlugInstall --sync | source $MYVIMRC
    endif
    
    call plug#begin('~/.local/share/nvim/plugged')
    Plug 'neovim/nvim-lspconfig'
    Plug 'rust-lang/rust.vim'
    call plug#end()
    
    lua <<EOF
    require'lspconfig'.rust_analyzer.setup({})
    EOF
    
    let g:rustfmt_command = 'rustup run nightly-2021-03-01 rustfmt'
    let g:rustfmt_autosave = 1
    ```

    </details>
- Make sure `~/.local/share/nvim/site/autoload` and `~/.local/share/nvim/plugged` are empty or do not exist
- Open `nvim` once to allow the plugins to install, then close it
- Create a crate that contains a very long Rust file (in my case, the file is over 3000 lines long - the problem appears with shorter files but is less noticeable), and open that long file
- Verify the language server is running by (e.g.) putting the cursor over a documented type name and running `:lua vim.lsp.buf.hover()` (documentation info should appear)
- Insert some extra blank lines in the file, so that rustfmt will remove them when run
- Run `:w`

### Actual behaviour

The file saves quickly, with no noticeable delay, and the contents of the file are automatically formatted using rustfmt

### Expected behaviour

The file is formatted correctly, but takes more than 10 seconds to save, during which time the editor is completely frozen

Please note a few things:
- The issue also appears when running `:RustFmt` manually
- Saving the file becomes almost instantaneous if auto-formatting is disabled (but `:RustFmt` still hangs just as much)
- Saving the file and formatting it also becomes almost instantaneous (with auto-formatting enabled) if the language server is disabled (remove the Lua section in the config above), so **it appears to be the interaction between the two things that's the problem**.
- `cargo +nightly-2021-03-01 fmt` only takes about a second, at most, to run from outside `nvim`
- There has been some mention before of shells such as `fish` (which is my login shell) causing delays, and I do see additional delays if I remove `set shell=/bin/bash` from that config, but please note that that line means `fish` shouldn't be involved here. Changing my login shell to `bash` or `zsh` does not fix the problem.

**Comment by mfussenegger** [comment] 2021-03-30 17:49
Could be related to https://github.com/neovim/neovim/issues/14087 - in that the formatting is causing a storm of didChange events

**Comment by mjlbach** [comment] 2021-04-13 22:21
@nerosnm Can you try with #14087 and debouncing enabled? (Try 50 ms)

**Comment by nerosnm** [comment] 2021-04-21 13:10
@mjlbach It's definitely better than it was, but not completely fixed. It seems to freeze for less time (~5s vs. more than 10s), and I would say it's just about usable now, but there's still clearly something going wrong.

**Comment by mjlbach** [comment] 2021-10-05 17:01
@nerosnm Can you try again? I've made additional performance improvements over the last month. I would also try a higher debounce (150ms)

**Comment by dmitmel** [comment] 2021-11-13 18:11
Minimal reproduction:

```vim
call plug#begin(stdpath('config') . '/plugged')
Plug 'https://github.com/neovim/nvim-lspconfig'
Plug 'https://github.com/rust-lang/rust.vim'
call plug#end()

lua <<EOF
require('lspconfig').rust_analyzer.setup({
flags = { debounce_text_changes = 150 }
})
EOF

function! Test() abort
  let begin = reltime()
  RustFmt
  echomsg reltimefloat(reltime(begin))
endfunction
```

Edit a long Rust file, run `:call Test()`.

**Comment by mjlbach** [comment] 2022-01-16 20:59
Closing in favor of https://github.com/neovim/neovim/issues/11867 since it's the same issue.

**Closed by mjlbach** 2022-01-16 20:59 UTC
Labels: bug, status:needs-response, lsp
