### ISSUE TITLE
Scrolling viewport with two vertical splits corrupts the display

### ISSUE THREAD

**Issue by d86leader** [neovim/neovim#16300] opened 2021-11-13 07:11 UTC
### Neovim version (nvim -v)

0.5.1 commit 0159e4daaed1347db8719c27946fcfdc4e49e92d

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

opensuse tumbleweed 20211110

### Terminal name/version

konsole 21.08.3

### $TERM environment variable

xterm-256color

### Installation

Built from source at commit 0159e4daaed1347db8719c27946fcfdc4e49e92d, but same for one installed from package manager

### How to reproduce the issue

Running from neovim source tree having just built nvim: `./build/bin/nvim --clean` 
Edit a couple of files in vertical splits: `:e src/clint.py<CR>` `:vsplit src/Doxyfile<CR>`  
Scroll the viewport: `<c-d>`

### Expected behavior

The viewport scrolls half a screen like with vim:
![nvim-expected-1](https://user-images.githubusercontent.com/6142210/141609483-df749392-4862-4204-8ca1-d3e073cef4a8.png)
![nvim-expected-2](https://user-images.githubusercontent.com/6142210/141609488-764234c2-5beb-4707-bc9d-7c7723a9f2c8.png)

### Actual behavior

The viewport scrolls half a screen, but the viewport for the other window becomes corrupted and also kind-of-scrolls:
![nvim-got-1](https://user-images.githubusercontent.com/6142210/141609504-2633e760-5112-4fc9-8017-00841e9fa71d.png)
![nvim-got-2](https://user-images.githubusercontent.com/6142210/141609506-4dc0f2da-c760-478a-afaa-4066d256a0d5.png)

## Additional info
This problem is not present in xterm, or with the same vim version built on my mac, but it is also present in yakuake.

**Comment by zeertzjq** [comment] 2021-11-13 07:13
This is already been fixed in #16239.

**Closed by zeertzjq** 2021-11-13 07:13 UTC
Labels: bug

**Comment by zeertzjq** [comment] 2021-11-13 07:14
Duplicate of #16238

**Comment by d86leader** [comment] 2021-11-13 07:18
Can confirm, was fixed. Cool!
