### ISSUE TITLE
Using !start on windows (NvimQt) cause many strange behaviors

### ISSUE THREAD

**Issue by skywind3000** [neovim/neovim#5844] opened 2016-12-29 15:12 UTC
- `nvim --version`: NVIM v0.1.6-250-gc57a816  (download from from [wiki/Installing-Neovim](https://github.com/neovim/neovim/wiki/Installing-Neovim) )
- Vim (version: ) behaves differently? GVim 8.0.133
- Operating system/version: Windows 7 64 bits
- Terminal name/version: NvimQt  0.2.4
- `$TERM`:  NONE

### Actual behaviour

1. typing `:!start cmd.exe /C echo HAHAHA` in nvim, the nvim window scrolled up and down. (**bug1**)
2. typing `:!start cmd.exe /C echo HAHAHA & pause` in nvim, the following `pause` is ignored, cmd window shows up and flash away immediately. (**bug2**, in gvim, `& pause` will pause the cmd.exe).
3. typing `:silent !start cmd.exe /C echo HAHAHA & pause` in nvim, nvim displays some strange characters in the command line, and first line of my source file disappears. The cursor can't rewind to the first line by `gg`. unless I call `:redraw!` (**bug3**)

![nvim_nvim_start](https://cloud.githubusercontent.com/assets/3035071/21546207/1f74f8a4-ce18-11e6-97c0-f8cf76281d2d.gif)

### Expected behaviour
1. typing `:!start cmd.exe /C echo HAHAHA' in gvim, the gvim window will not scroll.
2. typing `:!start cmd.exe /C echo HAHAHA & pause` in gvim, the cmd.exe window shows up and stay until I press enter (the `PAUSE` command)
3. same as `:silent !start cmd.exe /C echo HAHAHAHA & pause`

![nvim_vim_start](https://cloud.githubusercontent.com/assets/3035071/21546211/261445ca-ce18-11e6-85a1-79f4e89b5ef8.gif)

### Sumary

I download nvim.exe from nvim wiki directly, it is not the latest nvim, because I don't know how to build it on windows, but I believe:

1. nvim has not implemented the `:!start` command on windows but gvim has (see `:h !start`), even through nvim's document has the description of `:h !start`.

2. append a `& pause` after `:!start .... ` or insert `silent` before it in nvim on windows will cause undefined action.

Since contributors develop & debug NeoVim on non-windows systems, the latest nvim.exe would have the same problem. 

`:!start cmd.exe /C ........ & pause` is a very useful command for windows users, it will open a cmd.exe window and execute your file and prompt you "press any key to continue" before exit.

This is the top 1 high frequence command in my workflow, I even bind it to F5 to run my current file easily.

I like NvimQt, and want to use it on my windows. But there are some most important bugs which may stop windows users switching to nvim.

Wish it could be fixed. 

and two more things:
1. can windows binary files from [wiki/Installing-Neovim](https://github.com/neovim/neovim/wiki/Installing-Neovim) be updated.

2. can has('gui_running') returns 1 when I am using NvimQt, a lot of settings (color schemes, key mapping etc) which are written for gvim could be reused.

**Comment by skywind3000** [comment] 2017-01-05 18:22
nobody saw this ?

**Comment by skywind3000** [comment] 2017-01-05 18:22
any solution ?

**Comment by mhinz** [comment] 2017-01-05 18:34
As you said, we simply lack Windows people. I have no idea how I could help with the `:!start` questions. It's still in the help, because we merge the runtime patches (including the documentation) from Vim.

Does `:echo has('gui_running')` also output 0? I think it's expected at start time (read: in your vimrc) due to technical details. If the command gives you 1, you could work around it in your vimrc by using:

```vim
autocmd VimEnter * call s:set_settings()

function! s:set_settings()
   " all your stuff
endfunction
```

**Comment by ZyX-I** [comment] 2017-01-05 18:44
Maybe this can be checked in wine? I used to successfully test my Vim plugins there.

**Comment by justinmk** [comment] 2017-01-05 20:19
There's several bug fixes for Windows. Please wait.

> can has('gui_running') returns 1 when I am using NvimQt, a lot of settings (color schemes, key mapping etc) which are written for gvim could be reused.

Those colorschemes are broken, and they won't work with `'termguicolors'` (in Vim nor Nvim). Colorschemes have no reason to check `has('gui_running')`. They should set `ctermfg/bg` _and_ `guifg/bg`.

**Comment by skywind3000** [comment] 2017-01-06 06:59
looking forward

**Comment by justinmk** [comment] 2017-01-11 05:05
> `2.` typing :!start cmd.exe /C echo HAHAHA & pause in nvim, the following pause is ignored, cmd window shows up and flash away immediately. (bug2, in gvim, & pause will pause the cmd.exe).

This is unlikely to get fixed; `:!` in Nvim does not support "interactive" commands. Instead `:terminal` should be used for that. (According to @brcolow, `:terminal` works in the Windows build from #810. I'm working on merging the rest of #810 to master, this week.)

**Comment by skywind3000** [comment] 2017-01-11 06:50
thanks I will try it and feed you back

**Comment by justinmk** [comment] 2017-01-11 12:59
Ah, good point.

**Comment by equalsraf** [comment] 2017-01-25 22:22
The original Vim code https://github.com/vim/vim/blob/972c3b8f1b50e2f887a397c324af99eb354aad0b/src/os_win32.c#L4679 it is built as a special case of '!'.

**Comment by janlazo** [comment] 2017-04-19 06:34
Update after #6497:

1. Would redirecting the "Press any key to continue" message to `NUL` fix the scroll up/down bug?
It happens without `& pause`.

2. `:!` is currently not escaped like in Vim so you have to quote the commands themselves.
    Using `:!start` won't block the UI though if that's what you want.
  ```viml
   :!start cmd /c ":!start cmd.exe /C echo HAHAHA & pause"
  ```
  Without the double quotes, the pause message appears along with other "Press any to continue" message from `#1` but both of them can't stop the `:!start` command from exiting within Neovim because `echo   HAHAHA` finished already.

3. Same shellescaping issue in `#2`. I cannot reproduce the redraw issues and strange characters in nvim-qt.exe

**Comment by justinmk** [comment] 2018-05-01 07:50
Tested on `NVIM v0.3.0-1184-g4744142fa` with `nvim-qt.exe -- -u NORC`.

> `1.` typing `:!start cmd.exe /C echo HAHAHA` in nvim, the nvim window scrolled up and down.

Nvim window does not scroll up/down. 

> `2.` typing `:!start cmd.exe /C echo HAHAHA & pause` in nvim, the following `pause` is ignored, cmd window shows up and flash away immediately.

Try this instead (with quotes as @janlazo [mentioned](https://github.com/neovim/neovim/issues/5844#issuecomment-295119927)):

    :!start cmd.exe /C "echo HAHAHA & pause"

> `3.` typing `:silent !start cmd.exe /C echo HAHAHA & pause` in nvim, nvim displays some strange characters in the command line, and first line of my source file disappears. The cursor can't rewind to the first line by `gg`. unless I call `:redraw!`

No strange display, `gg` works, and this works (with quotes):

    :silent !start cmd.exe /C "echo HAHAHA & pause"

> `:!start cmd.exe /C ........ & pause` is a very useful command for windows users, it will open a cmd.exe window and execute your file and prompt you "press any key to continue" before exit.

I think what you actually mean is:

    :!start cmd.exe /C "echo HAHAHA & pause"

Even in cmd.exe itself, `start cmd.exe /C echo HAHAHA & pause` doesn't do what you want, the popup shell closes immediately. The quotes are required.

> nvim's document has the description of `:h !start.`

Removed in #7783.

> can windows binary files from wiki/Installing-Neovim be updated

That's done (automatically), and the [releases page](https://github.com/neovim/neovim/releases) is automatically updated also.

> can has('gui_running') returns 1 when I am using NvimQt

As discussed in other issues, this can't be restored in Nvim because Nvim supports attachment of multiple UIs. 

Nvim 0.3 has a new API function `nvim_list_uis()` which includes an `rgb` key. However that doesn't help the case of these old colorschemes, which _should not_ check `has('gui_running')` in the first place. These colorschemes are just broken, they should _always_ `guifg/guibg` _and_ `ctermfg/ctermbg`, there is _zero reason_ for colorschemes to care about `has('gui_running')`.

**Closed by justinmk** 2018-05-01 07:50 UTC
Labels: platform:windows
