### ISSUE TITLE
vim.fn: returning funcref in list/table turns it into vim.NIL

### ISSUE THREAD

**Issue by nmattia** [neovim/neovim#17748] opened 2022-03-16 23:03 UTC
### Neovim version (nvim -v)

07.0-dev commit: 746a29c58041e0470a4e8f9446378caba32f037c

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.2.1

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

built from source

### How to reproduce the issue

Create the following file:

```lua
-- foo.lua
local func = function() end

vim.api.nvim_command([[
function! OkFunc(arg)
    return a:arg
endfunction

function! NilFunc(arg)
    return [ a:arg ]
endfunction
]])

-- <function 1>
print(vim.inspect(vim.fn["OkFunc"](func)))

-- { vim.NIL }
print(vim.inspect(vim.fn["NilFunc"](func)))
```

then source in nvim with `:luafile ./foo.lus`.

### Expected behavior

The `vim.fn` function should return a function wrapped in a table

```lua
-- { <function 1> }
print(vim.inspect(vim.fn["NilFunc"](func)))
```

### Actual behavior

The `vim.fn` function returns `vim.NIL` wrapped in a table

```lua
-- { vim.NIL }
print(vim.inspect(vim.fn["NilFunc"](func)))
```

**Comment by nmattia** [comment] 2022-03-16 23:04
NOTE: I got the faulty behavior on `OkFunc` as well in neovim 0.6.1, i.e. returning the funcref itself would transform it to `vim.NIL`.

**Comment by zeertzjq** [comment] 2022-03-16 23:08
Possible duplicate of #13436. That issue contains some outdate information though, so maybe it can be closed in favor of this one.

**Comment by bfredl** [comment] 2022-03-16 23:36
`nlua_push_typval` checks directly for `VAR_FUNC` in the top-most return value. This must rather be done in `TYPVAL_ENCODE_CONV_FUNC_START`, so it also applies recursively to nested typvals.

**Closed** 2022-03-17 19:21 UTC
Labels: bug, lua

**Comment by nmattia** [comment] 2022-03-17 19:52
Thanks!
