### ISSUE TITLE
Can't open file with .db extension

### ISSUE THREAD

**Issue by fancieux** [neovim/neovim#22001] opened 2023-01-26 01:04 UTC
### Describe the bug

Can't open any file with .db extension. Even if it is an empty file, even if all plugins have been removed.
Error message:
> Error detected while processing BufReadPost Autocommands for "*":
> Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:22: Error executing lua: /usr/share/nvim/runtime/filetype.lua:23: String command argument must have at leas
> t one non-whitespace character
> stack traceback:
>         [C]: in function 'nvim_cmd'
>         /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
>         [C]: in function 'nvim_buf_call'
>         /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
> stack traceback:
>         [C]: in function 'nvim_buf_call'
>         /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>

### Steps to reproduce

touch test.db # create a empty file with extension .db
nvim test.db  # open it

### Expected behavior

open and edit it normally

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

no, vim 9.0.1182

### Operating system/version

archlinux with all packages up to update

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

tmux-256color

### Installation

archlinux official repo

**Comment by zeertzjq** [comment] 2023-01-26 01:11
Duplicate of #20763

**Closed by zeertzjq** 2023-01-26 01:11 UTC
Labels: bug
