### ISSUE TITLE
Can not open nvim 0.9.0 on Debian 9

### ISSUE THREAD

**Issue by hanshanglin** [neovim/neovim#23463] opened 2023-05-04 02:20 UTC
### Problem

install nvim by [asdf-neovim](https://github.com/richin13/asdf-neovim), then fail to startup. 
```shell
❯ nvim
/home/hanshanglin.lol/.asdf/installs/neovim/0.9.0/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/hanshanglin.lol/.asdf/installs/neovim/0.9.0/bin/nvim)
/home/hanshanglin.lol/.asdf/installs/neovim/0.9.0/bin/nvim: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/hanshanglin.lol/.asdf/installs/neovim/0.9.0/bin/nvim)
```

### Steps to reproduce

```shell
# install asdf, ref https://asdf-vm.com/guide/getting-started.html

asdf plugin add neovim
asdf install neovim 0.9.0 
asdf global neovim 0.9.0

nvim 
# /home/hanshanglin.lol/.asdf/installs/neovim/0.9.0/bin/nvim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/hanshanglin.lol/.asdf/installs/neovim/0.9.0/bin/nvim)
# /home/hanshanglin.lol/.asdf/installs/neovim/0.9.0/bin/nvim: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/hanshanglin.lol/.asdf/installs/neovim/0.9.0/bin/nvim)
```

### Expected behavior

nvim startup as normal

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

no, vim 8.0

### Operating system/version

Debian GNU/Linux 9 (stretch)

### Terminal name/version

sshd

### $TERM environment variable

xterm-256color

### Installation

asdf, by tarball

**Comment by zeertzjq** [comment] 2023-05-04 03:13
Duplicate of #21261

**Closed by zeertzjq** 2023-05-04 03:13 UTC
Labels: bug

**Comment by dundargoc** [comment] 2023-05-04 07:12
@hanshanglin can you install latest/nightly neovim with asdf and try that?

**Comment by bfredl** [comment] 2023-05-04 09:14
> Debian 9.0 was initially released on June 17th, 2017

Our binaries don't support ancient versions of distros, sorry. your best bet is to build neovim from source.
