### ISSUE TITLE
:terminal : strange issue with Fish

### ISSUE THREAD

**Issue by asilvadesigns** [neovim/neovim#7300] opened 2017-09-21 15:15 UTC
**nvim --version**
v.0.2.0

**vim behaves differently**
Issue can only occur within neovim, due to Neovim Terminal

**OS**
Mac OS 10.11.6

**terminal**
Occurs within all terminals I have installed, namely: alacritty, iterm2, terminal.

**$TERM**
xterm-256color

### Steps to reproduce using `nvim -u NORC`
- assuming fish is your default shell with no fancy plugins or configs...
1. Launch a terminal emulator.
2. `nvim -u NORC`
3. `terminal`, run some commands, 
4. Quit the terminal emulator.
5. Reopen terminal emulator.
6. `nvim -u NORC`. - in my case, the prompt hangs here, and I have to kill the process.

### Actual Behaviour
Neovim hangs and does not open again, after having closed a previous neovim session with a terminal buffer with fish shell.

### Expected Behaviour
Neovim should work, as it always does with zsh, or bash.

**Comment by justinmk** [comment] 2017-09-21 17:45
Thanks for the report. I see you're using the release version, which is missing many changes. Can you try the development version? The [releases page](https://github.com/neovim/neovim/releases) has pre-built packages for Linux/Windows/macOS.

**Comment by asilvadesigns** [comment] 2017-09-21 17:49
@justinmk thanks for the quick reply.
Is it cool if I install with homebrew via `brew install --HEAD neovim`?

**Comment by justinmk** [comment] 2017-09-21 18:21
That's fine

**Comment by asilvadesigns** [comment] 2017-09-21 19:11
@justinmk noice!! seems to work. I'll keep testing it throughout the day, but seems legit!

**Comment by asilvadesigns** [comment] 2017-09-21 19:37
@justinmk unfortunately, the issue persists. I've noticed the following:

In addition to nvim not being to able to open again, but simply hanging, until I `ctrl-c`.

I'm also not able to enter zsh, or bash, or npm. They all simply hang, until I `ctrl-c`.

I'm wondering if issue is caused by my PATH in fish, but somehow is triggered through nvim?

**Comment by jamessan** [comment] 2017-09-21 19:48
I can't reproduce this on Linux, with either 0.2.0 or current master.

**Comment by justinmk** [comment] 2017-09-22 06:23
This sounds like a termios problem. @asilvadesigns does `reset` in your terminal fix the issue?

**Comment by asilvadesigns** [comment] 2017-09-22 13:47
@justinmk sorry that was unclear, when I'm referring to `terminal emulator` it always refer to my GUI terminal emulator such as iterm, terminal, or alacritty.

Using `reset` in the terminal does not fix it. : (

It may very well be a fish bug, I use Alacritty as my terminal, being that it's fairly new I started with an issue there, but later observed it happens in all terminal emulators, so my next step was to check if it may be neovim. 

I'm going to reinstall fish, and see if I notice any differences.

**Comment by mqudsi** [comment] 2017-10-08 01:31
Please try with fish 3.0 (you'll need to build from git), it may be related to fish attempting to take control of the tty at startup. You can refer to https://github.com/Microsoft/BashOnWindows/issues/1653 where I first experienced this case and patch https://github.com/fish-shell/fish-shell/commit/55b3c45f95ba09efa4b9eaad8ec49256a7435823 where I merged a fix upstream into fish.

Note that as far as we've been able to deduce, there's no bug in fish (it's trying to do something it doesn't need to do but shouldn't be prevented from doing). That's all presuming fish 3 takes care of your problem.

**Comment by justinmk** [comment] 2017-10-08 08:58
@mqudsi Thanks, that is valuable. fish dev has helped us figure out other low-level edge cases before: https://github.com/neovim/neovim/pull/2598

Any idea what we could be doing wrong? I can't imagine what state could hang around after the terminal emulator is killed, that would later affect startup of new `nvim` instances.

**Comment by mqudsi** [comment] 2017-10-08 10:11
@asilvadesigns what version of fish were you using?

@justinmk I can't imagine it's a neovim bug given the three layers being reset. strace would certainly help, but I can't reproduce this on my end.

**Comment by mqudsi** [comment] 2017-10-08 10:22
Wait, @asilvadesigns, how do you get neovim to load thereafter? You have to restart your PC?

**Comment by asilvadesigns** [comment] 2017-10-08 11:46
@mqudsi 2.6.0

I'll install version 3.

@mqudsi correct, I did have to restart my computer in order for Neovim to load afterwards. I need to take care of some things this morning, then I'll build fish v3, excited to try : ).

**Comment by asilvadesigns** [comment] 2017-10-10 13:42
@mqudsi is cool if I `brew install fish --HEAD`?

**Comment by mqudsi** [comment] 2017-10-10 15:31
@asilvadesigns sure, that should be fine.

**Comment by asilvadesigns** [comment] 2017-10-10 16:53
@mqudsi issue still occurs : (

**Comment by justinmk** [comment] 2018-06-24 22:56
@asilvadesigns Any improvement with Nvim 0.3.0? There were various job-control and channel changes since this was reported.

**Comment by mqudsi** [comment] 2018-10-31 22:40
A [complete overhaul of job control](https://github.com/fish-shell/fish-shell/pull/5219) in fish was also just merged into fish `master` last week, so definitely worth trying it out again with a newer neovim+fish combo.

**Comment by justinmk** [comment] 2018-12-20 21:14
Assuming this is fixed in latest version of fish/nvim.

**Closed** 2018-12-20 21:14 UTC
Labels: :terminal, bug, revisit-at-release, system, tui
