### ISSUE TITLE
Running ex commands from python much slower compared to vim

### ISSUE THREAD

**Issue by svermeulen** [neovim/neovim#9135] opened 2018-10-17 10:43 UTC
- `nvim --version`:  NVIM v0.3.2-707-g082e14557, LuaJIT 2.0.5
- Vim (version: ) 8.1
- Operating system/version: Windows 10

I sometimes run ex commands from python and have noticed that in some cases it is over 5x slower in neovim compared to vim.  Here's my testing setup:

Temp.vim

```viml
let s:scriptDir = expand('<sfile>:p:h')

exec 'py3file ' . s:scriptDir . '/Temp.py'

if has('nvim')
    exec 'luafile ' . s:scriptDir . '/TempNvim.lua'
else
    exec 'luafile ' . s:scriptDir . '/TempVim.lua'
endif

function! g:RunBindTest(type)
    let startTime = reltime()

    if a:type == 'python'
        exec "python3 AddTestBindings()"
    elseif a:type == 'lua'
        exec "lua AddTestBindings()"
    elseif a:type == 'vim'
        call s:AddTestBindings()
    endif

    return reltimefloat(reltime(startTime))
endfunction

function! g:RunAllTests()

    let numTimesEach = 5

    let sum = 0
    for i in range(0, numTimesEach)
        let sum += g:RunBindTest('vim')
    endfor
    let vimAverage = sum / numTimesEach

    let sum = 0
    for i in range(0, numTimesEach)
        let sum += g:RunBindTest('python')
    endfor
    let pythonAverage = sum / numTimesEach

    let sum = 0
    for i in range(0, numTimesEach)
        let sum += g:RunBindTest('lua')
    endfor
    let luaAverage = sum / numTimesEach

    echom "Vim " . string(vimAverage) . " seconds, python " . string(pythonAverage) . " seconds, lua " . string(luaAverage) . " seconds"
endfunction

function! s:AddTestBindings()
    for i in range(0, 4000)
        nnoremap <expr> <leader>ts ":echo 'vim " . i . "'<cr>"
    endfor
endfunction
```

Temp.py

```python
import vim

def AddTestBindings():
    for i in range(1, 4000):
        vim.command('nnoremap <leader>ts :echo "python ' + str(i) + '"<cr>')
```

TempNvim.lua

```lua
AddTestBindings = function()
    for i = 1, 4000 do
        vim.api.nvim_command('nnoremap <leader>ts :echo "lua ' .. i .. '"<cr>')
    end
end
```

TempVim.lua

```lua
AddTestBindings = function()
    for i = 1, 4000 do
        vim.command('nnoremap <leader>ts :echo "lua ' .. i .. '"<cr>')
    end
end
```

Results on my machine:

Neovim:
Vim 0.046622 seconds, python 0.571145 seconds, lua 0.098019 seconds

Vim
Vim 0.096171 seconds, python 0.099919 seconds, lua 0.092197 seconds

Vim vs Neovim
- 2.06x faster in vimscript
- 5.7x slower in python
- Roughly the same in lua (1.06x slower)

I understand that neovim is targetting Lua for first class support compared to python, but I'm wondering if a 5.7x loss of speed in python is expected?  If so please close this issue

I think these results suggest to me that lua should always be preferred when interacting through the vim api and also probably in general

**Comment by svermeulen** [comment] 2018-10-17 10:50
I should also mention I'm using python 3.7 for both neovim and vim, lua 5.1 on neovim, and lua 5.3 on vim

**Comment by justinmk** [comment] 2018-10-17 11:05
`vim.command` in a loop does 4000 RPC requests. Build the 4000-line script as a single `\n`-delimited string, then call `vim.command(script)` once.

Duplicate of #7063.
See also https://github.com/neovim/neovim/issues/1898 for some related discussion.

**Closed by justinmk** 2018-10-17 11:05 UTC
