### ISSUE TITLE
Query error at 42:2. Invalid node type "method_elem"

### ISSUE THREAD

**Issue by lougxing** [neovim/neovim#30167] opened 2024-08-28 08:42 UTC
### Problem

I edit golang file, but it error.

`
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 42:2. Invalid node type "method_elem":
(method_elem
 ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...m/0.10.1/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...ovim/0.10.1/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...ovim/0.10.1/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        ....1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ....1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:243: in function 'get_query'
        ....1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:191: in function 'fn'
        ...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        ....1/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:178: in function 'prepare_highlight_states'
        ....1/share/nvim/runtime/lua/vim/treesitter/highlight
`

my computer is macos(arm).  
 

Using plugin:

- Finishing ... Done!
- fzf: Already up to date.
- any-jump.vim: Already up to date.
- jsonc.vim: Already up to date.
- vim-which-key: Already up to date.
- fzf.vim: Already up to date.
- vim-json: Already up to date.
- nvim-treesitter:  create mode 100644 queries/diff/folds.scm
- vim-mundo: Already up to date.
- vim-beautify: Already up to date.
- goyo.vim: Already up to date.
- syntax-tree-surfer: Already up to date.
- wildfire.vim: Already up to date.
- vim-illuminate: Already up to date.
- vim-go: Already up to date.
- vim-indent-guides: Already up to date.
- molokai: Already up to date.
- tabular: Already up to date.
- vim-better-whitespace: Already up to date.
- vim-bufferline: Already up to date.
- tagbar: Already up to date.
- undotree: Already up to date.
- vim-easymotion: Already up to date.
- vim-hexokinase: Already up to date.
- LeaderF: Already up to date.
- vim-rooter: Already up to date.

### Steps to reproduce

nvim a.go

### Expected behavior

just nvim a.go 

### Neovim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

14.5

### Terminal name/version

iterm2

### $TERM environment variable

i don't known

### Installation

homebrew

**Comment by clason** [comment] 2024-08-28 08:44
Duplicate of #3092

**Closed by clason** 2024-08-28 08:44 UTC
Labels: bug
