### ISSUE TITLE
inccommand=nosplit changes the way of evaluation of line concatenation in Vim script

### ISSUE THREAD

**Issue by itchyny** [neovim/neovim#11818] opened 2020-02-05 04:42 UTC
- `nvim --version`: v0.5.0-nightly (`brew install --HEAD nvim` today)
- `vim -u DEFAULTS` (version: ) behaves differently?: There's no `inccommand` in Vim.
- Operating system/version: macOS 10.15.3
- Terminal name/version: iTerm2
- `$TERM`:xterm

### Steps to reproduce using `nvim -u NORC`
vimrc: This is a valid Vim script and `call F()` does not cause error.
```vim
set inccommand=nosplit

function! F(...) abort
  if 1 | return | endif
endfunction

call timer_start(100, 'F', {'repeat': -1})
```
```
nvim -u ./vimrc
:s/
```

### Actual behaviour
```
Error detected while processing function F:
line    1:
E171: Missing :endif
```
### Expected behaviour
Emits no error.

**Comment by justinmk** [comment] 2020-02-05 09:18
> inccommand=nosplit changes the way of evaluation of line concatenation in Vim script

Do you mean line continuation?

Duplicate of https://github.com/neovim/neovim/issues/8796 . There is a root cause there, if someone wants to work on it.

**Closed by justinmk** 2020-02-05 09:18 UTC
Labels: bug
