### ISSUE TITLE
gentoo build fails

### ISSUE THREAD

**Issue by foo-bar-baz** [neovim/neovim#1967] opened 2015-02-09 23:16 UTC
[100%] Building C object src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/channel.c.o
cd /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/src/nvim && /usr/bin/clang  -DHAVE_CONFIG_H -DINCLUDE_GENERATED_DECLARATIONS  -DNDEBUG -march=native -O3 -pipe -O3 -D_FORTIFY_SOURCE=1  -Wconversion -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/config -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src -isystem /usr/include/luajit-2.0 -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/include    -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -o CMakeFiles/nvim.dir/msgpack_rpc/channel.c.o -c /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/msgpack_rpc/channel.c
/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/msgpack_rpc/helpers.c:89:19: error: no member named 'dec' in 'msgpack_object_union'
  *arg = obj->via.dec;
         ~~~~~~~~ ^
/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/msgpack_rpc/helpers.c:90:23: error: use of undeclared identifier 'MSGPACK_OBJECT_DOUBLE'
  return obj->type == MSGPACK_OBJECT_DOUBLE;
                      ^
/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/msgpack_rpc/helpers.c:123:10: error: use of undeclared identifier 'MSGPACK_OBJECT_DOUBLE'
    case MSGPACK_OBJECT_DOUBLE:
         ^
3 errors generated.
src/nvim/CMakeFiles/nvim.dir/build.make:2844: recipe for target 'src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/helpers.c.o' failed
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/helpers.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/msgpack_rpc/channel.c:346:12: warning: unused variable 'channel' [-Wunused-variable]
  Channel *channel = job_data(data);
           ^
1 warning generated.
make[2]: Leaving directory '/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build'
CMakeFiles/Makefile2:113: recipe for target 'src/nvim/CMakeFiles/nvim.dir/all' failed
make[1]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build'
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
 * ERROR: app-editors/neovim-9999::lua failed (compile phase):
 *   emake failed
 *
 * If you need support, post the output of `emerge --info '=app-editors/neovim-9999::lua'`,
 * the complete build log and the output of `emerge -pqv '=app-editors/neovim-9999::lua'`.
 * The complete build log is located at '/var/tmp/portage/build/app-editors/neovim-9999:20150209-225021.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-editors/neovim-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build'
 * S: '/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999'

**Comment by Pyrohh** [comment] 2015-02-09 23:27
Your issue should be fixed if you build from #1900, and this looks like a duplicate of #1899.

**Closed** 2015-02-10 04:53 UTC
