### ISSUE TITLE
failed assert 'new_col >= 0'

### ISSUE THREAD

**Issue by pieterkockx** [neovim/neovim#4916] opened 2016-06-14 01:42 UTC
- `nvim --version`: 0.1.4
- Vim (version:7.4 ) behaves differently? yes
- Operating system/version:ARCH 4.6
- Terminal name/version: tty
- `$TERM`: linux

### Actual behaviour
failed assert 'new_col >= 0' in ui_cursor_left(), ui.c:461

### Expected behaviour
print empty line

### Steps to reproduce using `nvim -u NORC`

nvim -u NORC
:!echo ^H
_^H is a (backspace) character generated using CTRL-V CTRL-H_

**Comment by oni-link** [comment] 2016-06-14 11:33
Looks like a duplicate of #4142.

**Comment by mhinz** [comment] 2016-06-15 15:38
Yup, duplicate. Thanks for reporting anyway.

**Closed by mhinz** 2016-06-15 15:38 UTC

**Comment by justinmk** [comment] 2016-06-15 15:50
https://github.com/neovim/neovim/pull/4376 fixes this issue, I should break out the relevant commit to unblock that.
