### ISSUE TITLE
Restore cursor shape to default on exit

### ISSUE THREAD

**Issue by UtkarshVerma** [neovim/neovim#21701] opened 2023-01-09 05:46 UTC
### Problem

My default cursor shape is a blinking line. When I quit NVIM, my terminal cursor is set to a block instead.

### Expected behavior

I wish to configure NVIM so that the terminal cursor is restored to the default cursor. I read the [FAQ](https://github.com/neovim/neovim/wiki/FAQ#cursor-style-isnt-restored-after-exiting-or-suspending-and-resuming-nvim) and I don't prefer it as it hardcodes the cursor.

A better approach would be to utilize the ANSI escape sequence `\033[0 q` which restores the default cursor. It is supported by `xterm`. How do I configure NVIM to behave like this?

**Comment by zeertzjq** [comment] 2023-01-09 06:06
This doesn't seem currently used anywhere:
https://github.com/neovim/neovim/blob/c19bd47c0a2e3cc77d7f5e41ed184edb41685bd3/src/nvim/tui/tui.c#L1939-L1944

**Comment by UtkarshVerma** [comment] 2023-01-09 07:13
> This doesn't seem currently used anywhere:
> https://github.com/neovim/neovim/blob/c19bd47c0a2e3cc77d7f5e41ed184edb41685bd3/src/nvim/tui/tui.c#L1939-L1944

I'm sorry, could you please elaborate a bit?

**Comment by justinmk** [comment] 2023-01-09 12:26
duplicate of #4396 , which mentions a termcode that could be used to "reset cursor to terminal default".

**Closed by justinmk** 2023-01-09 12:26 UTC
Labels: enhancement, tui, complexity:low
