### ISSUE TITLE
Shift J deletes % character sometimes

### ISSUE THREAD

**Issue by daose** [neovim/neovim#8864] opened 2018-08-16 05:32 UTC
- `nvim --version`:
```
NVIM v0.3.1-1-g489d32f
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolcha
in/usr/bin/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LO
G_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -W
implicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GE
NERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -
I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim
/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/inclu
de -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/bu
ild/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/inc
lude
Compiled by travis@Traviss-Mac-1284.local

Features: +acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
- Vim (version: 8.0) behaves differently? **YES**
- Operating system/version:
```
Darwin STUDENTs-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:59:54 PDT 2018; root:xnu-4570.71.2~2/RELEASE_X86_64 x86_64
```
- Terminal name/version: Alacritty
- `$TERM`: `screen-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```
Hit the following keys (`i%<CR>%<ESC>k`) to create:
```
%
%
```

Now press `J` and observe that the second percentage sign disappears

### Actual behaviour (where `_` is a space)

The screen displays `%_`

### Expected behaviour (where `_` is a space)

The screen displays `%_%`

**Comment by chrisbra** [comment] 2018-08-16 05:34
duplicate of #8841

**Closed** 2018-08-16 05:43 UTC
