### ISSUE TITLE
Neovim LSP hangs when exiting large projects

### ISSUE THREAD

**Issue by ojroques** [neovim/neovim#23723] opened 2023-05-22 15:53 UTC
### Problem

When using [gopls](https://pkg.go.dev/golang.org/x/tools/gopls@v0.11.0), Neovim hangs when exiting in large Go projects. I don't think it comes from gopls since I've tried older versions and the issue persists. It used to work fine until recently.
*Edit*: I tested with Neovim 0.9 and everything works fine.

### Steps to reproduce

**Neovim minimal config**:
```lua
require 'paq' {
  {'neovim/nvim-lspconfig'},
}

require('lspconfig')['gopls'].setup {}
```
Go to a medium to large-sized Go project, for instance [pion/webrtc](https://github.com/pion/webrtc), open a file and exit with `:q`. Neovim hangs.

### Expected behavior

Neovim should exit immediately.

### Neovim version (nvim -v)

0.10.0~ubuntu1+git202305112018-e124672ce-9b397864c

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Ubuntu 22.04 

### Terminal name/version

Alacritty + Tmux

### $TERM environment variable

tmux-256color

### Installation

APT

**Comment by SaschaMendel** [comment] 2023-05-23 09:44
Having the same issue, tried using strace, only thing i see is epoll_wait & a read and then nothing.
Quiting using ZZ or ZQ produce same result.

**Comment by glepnir** [comment] 2023-05-23 10:18
relate watcher have a pr working on this https://github.com/neovim/neovim/pull/23500

**Comment by mfussenegger** [comment] 2023-05-23 11:00
This is likely either a duplicate of https://github.com/neovim/neovim/issues/23595 or https://github.com/neovim/neovim/issues/23291

**Closed by mfussenegger** 2023-05-23 11:00 UTC
Labels: bug, lsp
