### ISSUE TITLE
Pressing "d", then moving to a different workspace, results in "dd"

### ISSUE THREAD

**Issue by stefanmh** [neovim/neovim#6206] opened 2017-03-03 16:15 UTC
- `nvim --version`: v0.2.0-751-g8bbdef1 (latest master)
- Vim (version: 8.0) - doesn't have the bug 
- Operating system/version: Ubuntu, i3 window manager
- Terminal name/version: gnome terminal
- `$TERM`: zsh

### Actual behaviour
d<switch workspace or focus a different window> results in dd.

### Expected behaviour
Should wait for a second keystroke after the first "d"

### Steps to reproduce using `nvim -u NORC`
I'm using i3, but might be reproducible in other window managers as well.

Do: d + focus a different window

This also appears to happen if a remote plugin executes certain nvim commands, though I can't reproduce that very reliably.

My remote plugin makes this happen pretty frequently, which leads me to accidentally deleting 2 lines when I intended to delete one.

**Comment by stefanmh** [comment] 2017-03-03 16:24
Managed to repro with a remote plugin.

In first shell, run:
```
 NVIM_LISTEN_ADDRESS=/tmp/nvim ~/neovim/bin/nvim -u NORC ~/somefile
```

In the second, run this python script:

```python
import neovim
nvim = neovim.attach('socket', path='/tmp/nvim')
while True:
    nvim.current.buffer[:]
    time.sleep(0.1)
```

Go to nvim and press `d` once. A line will get deleted.

**Comment by stefanmh** [comment] 2017-03-03 16:35
Works with `nvim.call('getline', 1, 1)` as well.

**Comment by jamessan** [comment] 2017-03-03 16:45
Isn't this just a duplicate of #6166?

**Comment by justinmk** [comment] 2017-03-03 16:45
Thanks for the repro. This is a known issue that is very important, but no one is working on it yet. Help would be most welcome.

**Comment by sliceofcode** [comment] 2017-03-05 02:23
I can reproduce this issue under AwesomeWM.

**Comment by stefanmh** [comment] 2017-03-06 10:44
Had a look over the weekend, but couldn't quickly figure out a fix; the code is quite convoluted.

I assume what happens is the state machine sees d, followed by K_EVENT and then reinterprets the first d.

The logic for K_EVENT seems to have been sprinkled all over the place, though. Might have another look this weekend.

**Comment by justinmk** [comment] 2017-03-10 00:55
See also https://github.com/neovim/neovim/issues/3720#issuecomment-220702592 .

#6159 gave me more insight into this, hopefully I can find a fix after that.

Merging this with https://github.com/neovim/neovim/issues/6166

**Closed by justinmk** 2017-03-10 00:55 UTC
Labels: api, bug
