### ISSUE TITLE
Bultin terminal doesn't understand `modifyOtherKeys` escape sequences

### ISSUE THREAD

**Issue by ianliu** [neovim/neovim#21360] opened 2022-12-09 12:38 UTC
### Neovim version (nvim -v)

v0.8.1

### Vim (not Nvim) behaves the same?

yes, 9.0

### Operating system/version

Archlinux

### Terminal name/version

wezterm 20221119-145034-49b9839f

### $TERM environment variable

xterm-256color

### Installation

system package manager

### How to reproduce the issue

Wezterm seems to have added `modifyOtherKeys` escape sequences in this issue: https://github.com/wez/wezterm/issues/2527, and after I've updated wezterm, neovim's terminal started to print the character sequence `;2` when I press `<s-space>`.

By mapping `<s-space>` to `<space>` the issue is fixed, but it would be nice if the terminal was smart enough to ignore the escape codes if nothing is mapped to `<s-space>`.

### Expected behavior

I would expect to have a single `<space>` to be printed on the terminal when pressing `<s-space>`.

### Actual behavior

Pressing `<s-space>` in the terminal prints `;2` in the input line.

**Comment by zeertzjq** [comment] 2022-12-09 12:40
Duplicate of #18735

**Closed by zeertzjq** 2022-12-09 12:40 UTC
Labels: closed:duplicate
