### ISSUE TITLE
executing nvim command in term mode

### ISSUE THREAD

**Issue by wertasy** [neovim/neovim#17700] opened 2022-03-12 23:05 UTC
### Feature already in Vim?

No

### Feature description

When executing nvim command in term mode, open the file directly in the current nvim instance instead of starting a new process.

**Comment by zeertzjq** [comment] 2022-03-12 23:15
This is already achievable using something like `nvim --server $NVIM_LISTEN_ADDRESS --remote-tab {file}`, so the question is whether this should be the default behavior.

**Comment by jamessan** [comment] 2022-03-12 23:24
Duplicate of #1750

https://github.com/neovim/neovim/issues/1750#issuecomment-162002955

**Closed by jamessan** 2022-03-12 23:24 UTC
Labels: enhancement, defaults, status:needs-discussion, remote
