### ISSUE TITLE
colorscheme incorrectly highlighted

### ISSUE THREAD

**Issue by xian-wen** [neovim/neovim#30930] opened 2024-10-24 10:05 UTC
### Problem

colorscheme (no matter which builtin) is not correctly highlighted, including but not limited to:
* characters following ` (single backtick) in the same line are highlighted as code (motion.txt:932)
![Image](https://github.com/user-attachments/assets/4d0ad71e-f973-4932-b179-640d3e516023)

* Note, Todo, and Error are not highlighted (helphelp.txt:385)
![Image](https://github.com/user-attachments/assets/7acf408c-49cb-4ff3-94a4-4ece10a1750d)

### Steps to reproduce

nvim --clean
:h motion.txt
933G

:h helphelp.txt
G

### Expected behavior

* characters following ` (single backtick) should not be highlighted
![Image](https://github.com/user-attachments/assets/fc6fd307-5452-4184-8ab6-1322448c82b8)

* Note, Todo, and Error should be highlighted
![Image](https://github.com/user-attachments/assets/308d3e58-d391-4b70-af1a-804e14a464d0)

### Nvim version (nvim -v)

v0.10.2

### Vim (not Nvim) behaves the same?

no, vim 9.1.0754

### Operating system/version

Ubuntu/22.04.5 LTS

### Terminal name/version

Windows Terminal/1.21.2911.0

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment] 2024-10-24 10:09
Duplicate of #26650

**Closed by zeertzjq** 2024-10-24 10:09 UTC
Labels: bug

**Comment by xian-wen** [comment] 2024-10-24 11:42
@zeertzjq Sorry, I have just seen #26650 and did not find any solution for this problem. My Neovim was built with the latest stable version, which was released on just 3 weeks ago. While #26650 was closed in the last year, I think the problem should no longer exist in the latest version. Am I missing something? Thank you so much.
I think the right highlight should only happen when `` (double backtick) is found instead of like a comment highlight from the open backtick to the end of line.
![Image](https://github.com/user-attachments/assets/2d70a553-59ce-467c-9b75-52a841370807)

**Comment by justinmk** [comment] 2024-10-24 11:49
Those screenshots look like a potential issue with the treesitter parser. Please paste the sample code (not screenshots) in a new issue at https://github.com/neovim/tree-sitter-vimdoc (and link to this issue).
