### ISSUE TITLE
"inits 1" takes more time in all terminals comparing to Kitty on MacOS

### ISSUE THREAD

**Issue by ajukraine** [neovim/neovim#21989] opened 2023-01-24 21:55 UTC
### Describe the bug

I was profiling startup time of "--clean" Neovim istance on different terminals. I had suspicion there might be correlation between terminal and Neovim performance. And after many repeatable tests I've found out, that all terminal produce similar "vim-startuptime" timings, except Kitty. Which is faster. And I've found that the speed gain is at "inits 1" step (approximately ~11ms). So maybe you can help me out here to understand why is that?

Terminals in test:
 - Kitty
 - Alacritty
 - cool-retro-term
 - warp
 - Terminal.app
 - WezTerm
 - iTerm2

System info:
```
                ,xNMM.          ---------------------------------- 
               .OMMMMo           OS: macOS 13.1 22C65 x86_64 
               OMMM0,            Host: MacBookPro16,1 
     .;loddo:' loolloddol;.      Kernel: 22.2.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 18 days, 11 hours, 54 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 275 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: fish 3.6.0 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1920x1080@2x, 1792x1120@2x 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Amethyst 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: kitty 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   CPU: Intel i9-9880H (16) @ 2.30GHz 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   GPU: Intel UHD Graphics 630, AMD Radeon Pro 5500M 
    kMMMMMMMMMMMMMMMMMMMMMMd     Memory: 11052MiB / 16384MiB 
     ;KMMMMMMMWXXWMMMMMMMk.
```

Tests:
![vim startuptime on different terminals](https://user-images.githubusercontent.com/828545/214428054-d77486d2-b876-400a-a28d-1ab30215d663.png)

I was also able see the same problem with Vim ("inits 1" takes ~5ms longer on all terminals, comparing to Kitty):
![vim startuptime on different terminals](https://user-images.githubusercontent.com/828545/214428832-2531f9ae-e611-49c2-981e-86b82ae1cd98.png)

### Steps to reproduce

For Neovim:
` ❯ vim-startuptime -warmup 5 -count 50 -vimpath nvim -- --clean`

For Vim:
` ❯ vim-startuptime -warmup 5 -count 50 -vimpath vim -- -u NONE`

### Expected behavior

All terminals produce similar startup time

### Neovim version (nvim -v)

0.9.0-dev-1737+g23d8f5b87-dirty

### Vim (not Nvim) behaves the same?

yes, 9.0.0100

### Operating system/version

macOS 13.1

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Installation

Homebrew

**Comment by clason** [comment] 2023-01-24 21:57
Always test with `nvim --clean`. I cannot reproduce these timings on my macOS Intel machine.

**Comment by ajukraine** [comment] 2023-01-24 22:00
@clason thanks for fast reply! have you tried to compare Kitty with any other terminal?

**Comment by clason** [comment] 2023-01-24 22:03
In any case, this is clearly not an issue with Neovim, so I'm closing this -- usage questions should be asked on Matrix or StackOverflow.

**Closed by clason** 2023-01-24 22:03 UTC
Labels: closed:question

**Comment by ajukraine** [comment] 2023-01-24 22:05
@clason hm, yeah I see. I've just found, that if I start any terminal from within Kitty itself, it works as expected... maybe you someone knows what is happening during "inits 1" that may cause such behavior?

**Comment by ajukraine** [comment] 2023-01-24 22:13
Okay, I guess, I've found the reason. It seems that Kitty automatically turns on GPU accelaration, and other terminals don't (even if they have one). Maybe it will be usefull for others
