### ISSUE TITLE
Add support for workspaces

### ISSUE THREAD

**Issue by j-xella** [neovim/neovim#25683] opened 2023-10-17 11:07 UTC
### Problem

ATM, if you connect multiple GUI/TUI to the same nvim server, they will be like mirrors of each other, which is limiting.

I understand that there is a work underway #13504 to let a client have its own layout. However, this solution will not be persistent, correct? If the client is closed, the layout is gone.

### Expected behavior

This problem has already been faced by terminal multiplexers, and the solution was something like **sessions** in tmux. Another layer on top of the collection of tabs, so that if different clients are connected to different sessions, they can work without disturbing each other (visually at least). And the sessions persist, so that you can reconnect to a session later.

In vim/neovim, the term "session" is probably not a good idea, as it is already used for other things. I would use the term **workspace** - this is a [feature of wezterm](https://wezfurlong.org/wezterm/recipes/workspaces.html) that is similar to tmux sessions.

**Comment by zeertzjq** [comment] 2023-10-17 11:56
Duplicate of #2161

**Closed by zeertzjq** 2023-10-17 11:56 UTC
Labels: enhancement
