### ISSUE TITLE
terminal: black color is not handled properly with Solarized scheme

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#2323] opened 2015-03-31 23:43 UTC
In `:terminal` (left) the black color is not the same as in my normal terminal (right):
![selection_064](https://cloud.githubusercontent.com/assets/9766/6926866/9ee03c2e-d7e9-11e4-9490-45bc0922c16e.png)

I am using the Solarized theme in my terminal emulator (urxvt), via ~/.Xresources (https://github.com/solarized/xresources), which defines special color values for the first 16 colors.

This includes:

```
#define S_base02        #073642
...
*color0:                  S_base02
...
```

Vim's solarized theme is configured to use the 16 color palette then, specifically set up for it.

In `terminal_get_line_attributes:549` I see this (added via `ELOG`):

```
line: 1, col:0, attr_id:213, vt_fg_idx:233, vt_fg_rgb: 0
```

The problem seems to be that the RGB of that column gets reported as
0/0/0 via:

```
int vt_fg = RGB(cell.fg.red, cell.fg.green, cell.fg.blue)
```

And then this gets mapped to an existing "cterm-fg value" (233/232), which then does not get interpreted/translated by the real terminal emulator then anymore.

It turns out the problem is duplicate entries in the `color_indexes` map,
and `map_get` should probably return the first value from there..!

As a hack, I've changed `terminal_init`:

```
if (!map_get(int, int)(color_indexes,
    RGB(color.red, color.green, color.blue)))
    map_put(int, int)(color_indexes,
        RGB(color.red, color.green, color.blue), color_index + 1);
```

~~btw: I've also tried to set `let g:terminal_color_0 = '#ff0000'`, but this had not effect at all.  First, because of another index being used (233/232). But also after the hack from above, this won't get enforced.  Maybe in this case a new color index needs to be created and used, using some new color
number?~~ That's because this only works for true color terminals, with NVIM_TUI_ENABLE_TRUE_COLOR=1.

The colors-table script is available at: https://github.com/blueyed/dotfiles/blob/master/usr/bin/colors-table

**Comment by justinmk** [comment] 2016-02-04 06:54
@blueyed I didn't look closely at this, but is it covered by https://github.com/neovim/neovim/issues/3459 ?

**Comment by motdef** [comment] 2016-03-14 12:55
When colour 0 is used as a background colour in the Neovim terminal, it simply displays the background colour:
![screen shot 2016-03-14 at 12 47 24](https://cloud.githubusercontent.com/assets/12588098/13745020/a105b738-e9e3-11e5-989f-3e04b49c81f7.png)

#4350 fixes the issue:
![screen shot 2016-03-14 at 12 47 34](https://cloud.githubusercontent.com/assets/12588098/13745036/b7391bc6-e9e3-11e5-8bfc-9872cbe5e46f.png)

**Comment by blueyed** [comment] 2016-03-24 01:25
@motdef 
#4350 did not help in my case: I am still getting real black instead of the one for solarized.
This issue is not about the background.

I've also noticed that ctermfg=16 (used for Title and in the startifyHeader), which is red by default is black in Neovim's terminal (and therefore with nvim in nvim).
It (color16) displays fine with my colors-table script though?!  (while that's not the case for color0/color8).

**Comment by motdef** [comment] 2016-03-24 17:15
That's strange, as running your colour script with #4350 shows the correct colour for index 0:
![screen shot 2016-03-24 at 17 11 24](https://cloud.githubusercontent.com/assets/12588098/14025019/e3834d66-f1e3-11e5-813b-fdf50964ffc7.png)
(I forgot to enable bright colours for this screenshot but the point still stands)

ctermfg=16 does display as black for me though, with or without the aforementioned pull request.

**Comment by blueyed** [comment] 2016-03-24 19:26
@motdef 
I've just pushed an update to the `colors-table` script (for base16 support).
You need to run it with `-` instead of `8`.

**Comment by motdef** [comment] 2016-03-25 19:26
![screen shot 2016-03-24 at 19 41 51](https://cloud.githubusercontent.com/assets/12588098/14052072/4e05f6f8-f2bf-11e5-867e-088247f88a7e.png)
Seems fine to me? Matches the output in a regular terminal, anyway

**Comment by blueyed** [comment] 2016-05-10 20:52
@cztchoice 
#4350 helps a bit with that, but it moves the black color to color16 (0-index), which I'm using with the extended bas16 theme (which has 22 colors).

In urxvt directly:
![2016-05-10-224941_338x242_scrot](https://cloud.githubusercontent.com/assets/9766/15162133/bfdd7a74-1701-11e6-9df0-50db349fd459.png)

In Neovim `:term`:
![2016-05-10-225030_327x240_scrot](https://cloud.githubusercontent.com/assets/9766/15162134/bfdec2f8-1701-11e6-8492-1ba72b9854cb.png)

**Comment by blueyed** [comment] 2016-05-10 20:59
@justinmk 
#3459 might be related, but I do not fully understand it.

**Comment by DarkDefender** [comment] 2016-05-10 21:46
@blueyed I don't think the the extended base colors are reliable...

I didn't test it out inside neovim, but it looks like this in my urxvt terminal:
![test_color](https://cloud.githubusercontent.com/assets/312503/15163463/e919d9b2-1708-11e6-99bf-73392001d460.png)

As you can see it has black as the color nr 16. I'm guessing these colors are not used defined because I haven't seen anything to manually set them.

**Comment by justinmk** [comment] 2017-03-23 16:54
Guessing https://github.com/neovim/neovim/pull/6160 fixed this. Please try master and confirm or deny.

**Comment by blueyed** [comment] 2017-03-23 21:46
@justinmk 
I still get the same result as above, i.e. real black for `16:base16-16`.
I am using `colors-table -` (from https://github.com/blueyed/dotfiles/blob/01ce00e572eeac945d0004ddf4b44b3756335a0b/usr/bin/colors-table).

@DarkDefender 
I have not investigated or remember the details, but it works in urxvt by itself, and Neovim picks it up via `ctermfg=16`.

**Comment by blueyed** [comment] 2017-03-23 21:48
`tput setaf 16` is `^[[38;5;16m` normally, but `^[[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m` in Neovim's terminal.

**Comment by DarkDefender** [comment] 2017-03-24 18:16
To fix this we need to change neovim terminal lib (I don't remember the library name) to accept custom colors above 16. Currently it only allows the user to set the first 16. (We need to be able to change the colors to be able to figure out exactly what index they should have)

The problem is that the lib only is built to emulate 1-16 and 256 color terminals. The values for the colors above 16 will be wrong if the user changes any of the hardcoded color values (color 16-255).

When I first implemented the color fix for neovim, I had in mind that we should be able to handle all the 256 color values. But I ran into the library color restriction and settled to just be able to figure out the first 16 colors (because I think most people will only change those anyways).

**Comment by DarkDefender** [comment] 2017-03-29 12:19
@leonerd could the 16 custom color restriction be lifted from libvterm? Or perhaps you know of a less hacky way to get the color index from libvterm?

The idea is that we will set all the colors to their respective index to be able to figure out their true index (when not running in true color mode). So color index nr 1 will have rbg 0,0,1 and nr 32 0,0,32 etc.

**Comment by leonerd** [comment] 2017-03-29 12:24
This is already recorded as a feature request for libvterm:
  https://blueprints.launchpad.net/libvterm/+spec/palette-index
I'll get around to it sometime, or someone else can have a look at it and suggest me some code.

**Comment by justinmk** [comment] 2020-04-28 14:40
fixed by https://github.com/neovim/neovim/pull/10994

**Closed by justinmk** 2020-04-28 14:40 UTC
Labels: :terminal
