### ISSUE TITLE
Strange behavior around NetRW and tabs

### ISSUE THREAD

**Issue by tstirrat15** [neovim/neovim#9152] opened 2018-10-23 16:54 UTC
This issue just appeared in last night's build. Yesterday's build worked fine.

- `nvim --version`:
```
NVIM v0.3.2-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-ghCPJj/neovim-0.3.0~ubuntu1+git201810222021-6dae777-479a1d0=. -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-ghCPJj/neovim-0.3.0~ubuntu1+git201810222021-6dae777-479a1d0/build/config -I/build/neovim-ghCPJj/neovim-0.3.0~ubuntu1+git201810222021-6dae777-479a1d0/src -I/build/neovim-ghCPJj/neovim-0.3.0~ubuntu1+git201810222021-6dae777-479a1d0/.deps/usr/include -I/usr/include -I/build/neovim-ghCPJj/neovim-0.3.0~ubuntu1+git201810222021-6dae777-479a1d0/build/src/nvim/auto -I/build/neovim-ghCPJj/neovim-0.3.0~ubuntu1+git201810222021-6dae777-479a1d0/build/include
Compiled by buildd@lcy01-amd64-017
```
- Vim (version: ) behaves differently?
Not sure - I can't remember how to access system vim, as I've pointed all instances of vi/vim at nvim using `update-alternatives`.

- Operating system/version:
Ubuntu 18.10

- Terminal name/version:
GNOME Terminal 3.28.2

- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC .
# Press "i" 3 times to go to netrw tree mode
# Press "t" to open a file in a new tab
```

### Actual behaviour
* File opens in current screen, but tab indicator stays on the NetRW tab.
* `gT` changes the tab indicator but doesn't change the rendered file
* Switching workspaces (on Ubuntu: ctrl + alt + direction key) will cause the NetRW screen to render correctly, but it then sticks there

### Expected behaviour
* File opens in current screen and tab indicator points at file
* `gT` changes both active file and tab indicator
* Switching workspaces has no effect on active output

### Notes
* This seems to be specific to NetRW - if I `tabe <filename>`, it works just fine, and if I edit a single file, it also works just fine

**Comment by tstirrat15** [comment] 2018-10-23 17:29
I installed via the unstable PPA, and reverted to the stable branch to be able to keep getting work done. Would I have to clone and build to be able to do what you're describing?

**Comment by dm1try** [comment] 2018-10-23 22:30
> Yes. I can't reproduce the issue, so someone with GNOME Terminal needs to try reverting #9143 or bisecting.

reproducible on osx with alacritty and iTerm. Reverting helps.
`:redraw` or `:mode` works as temporary workaround, as mentioned above.

**Comment by tstirrat15** [comment] 2018-10-23 22:35
I got a local install going, and it does seem like #9143 is the issue. The commit just prior to that is fine, and that commit exhibits the behavior that I'm describing in the issue.

I'm not sure how to debug beyond that, though.

**Comment by cvlmtg** [comment] 2018-10-24 06:51
I'm having display issues too, and usually ctrl-l fixes everything. I'm not using netrw, it happens e.g. when closing or navigating tabs, but it doesn't happen always, so I still  haven't understood exactly why or when it happens.

I'm using kitty on macos and the problem appeared after I compiled nvim with #9143

**Comment by bfredl** [comment] 2018-10-24 06:54
Probably a `redraw_all_later(NOT_VALID)` is done somewhere in the context of the old tab which needs to be moved to the new tab. I'll look into it.

**Comment by tstirrat15** [comment] 2018-10-24 15:29
@bfredl I can't seem to make it happen with `-u NONE`. I was able to get it without NetRW, but that was with my full `nvimrc`. Would it help to have a paste of that? I use enough plugins that it might not be..

**Comment by cvlmtg** [comment] 2018-10-24 17:07
@bfredl I suspect it might be some sort of race condition with timers and / or jobs. I wasn't unable to reproduce it with `vim -u NONE`, but while using it normally a couple of times the screen was updated like a second later after closing the tab. this thing plus the randomness of the bug makes me think about something asynchronous.

btw the last time I saw the bug, the tab bar at the top and the status line at the bottom where updated correctly, it was just the content of the tabs / splits that wasn't updated at all

**Comment by tstirrat15** [comment] 2018-10-24 17:12
> btw the last time I saw the bug, the tab bar at the top and the status line at the bottom where updated correctly, it was just the content of the tabs / splits that wasn't updated at all

That's the same behavior I've been seeing.

**Comment by dm1try** [comment] 2018-10-24 17:15
>  Netrw is huge, and its behavior depends on external factors.

that's total true. it looks like it has some "manual" redraw logic(?).

anyway I found that it calls only single function on `WinEnter`
```
autocmd WinEnter

    *         if &ft == "netrw"|call s:NetrwInsureWinVars()|endif
```
which basically does not do anything if `netrw` uses list style
https://github.com/neovim/neovim/blob/5fbc2eeac596041569d3c50ec3d8dec2b23870ba/runtime/autoload/netrw.vim#L11421-L11422

so the dirty fix like with manual `redraw` works
```viml 
  ...
  else
    exe `:redraw`
  endif
```

> btw the last time I saw the bug, the tab bar at the top and the status line at the bottom where updated correctly, it was just the content of the tabs / splits that wasn't updated at all
>That's the same behavior I've been seeing.
  
btw, the cursor position is also updated)

**Comment by bfredl** [comment] 2018-10-24 21:12
Still cannot reproduce, but here's a patch maybe worth trying:
```diff
diff --git a/src/nvim/window.c b/src/nvim/window.c
index 56caf7a94..853ff09c1 100644
--- a/src/nvim/window.c
+++ b/src/nvim/window.c
@@ -3313,6 +3313,7 @@ static void enter_tabpage(tabpage_T *tp, buf_T *old_curbuf, int trigger_enter_au
 
   last_status(false);  // status line may appear or disappear
   (void)win_comp_pos();  // recompute w_winrow for all windows
+  redraw_all_later(NOT_VALID);  // need to redraw everything
   diff_need_scrollbind = true;
 
   /* The tabpage line may have appeared or disappeared, may need to resize
```

**Comment by dm1try** [comment] 2018-10-24 21:32
I can reproduce without switching to the tree view in `netrw`, somehow `newrw:LocalBrowseRefresh` leads to the behavior described above:
- open any file using `netrw`
- change the window focus somehow two times(switching workspaces or Alt+Tab)(`netrw` calls `s:LocalBrowseRefresh` on `FocusGained`)

see the demo
![demo](https://user-images.githubusercontent.com/486807/47462820-2bfcaa00-d7ed-11e8-8ea7-5ba4de6ff9a6.gif)

**Comment by dm1try** [comment] 2018-10-24 21:45
@bfredl 
> here's a patch maybe worth trying

no luck :(

**Comment by vsajko** [comment] 2018-10-24 23:29
I can reproduce it with session
```
NVIM v0.3.2-744-g6dae7776e                                                                                                                                                                                                                                         
Build type: Release
LuaJIT 2.0.5
```
term is xterm
```xterm-256color```

```
> echo x > x ; echo y > y
> nvim -u NONE -p x y
```

```
:mksession sess
:qa
```

```
> nvim -S sess -u NONE
```

Now when you do :tabnext, :tabprevious , you will see incorrect display of same file until :tabdo redraw

**Comment by dm1try** [comment] 2018-10-25 00:01
> I can reproduce it with session

I confirm(though I'm not sure if it is the same bug but the consequences are the same)
I've simplified the session example to onliner `nvim -u NONE -c 'edit x|tabedit y'`

**Comment by bfredl** [comment] 2018-10-25 15:53
> I've simplified the session example to onliner echo x > x ; nvim -u NONE -c 'tabedit x'

Thanks, it worked to reproduce. Please try #9155.

**Comment by dm1try** [comment] 2018-10-25 16:06
@bfredl thanks, #9155 fixes all!

**Closed** 2018-10-25 17:03 UTC
Labels: bug-regression, display

**Comment by tstirrat15** [comment] 2018-10-25 21:42
Awesome. Thank you, @bfredl!
