### ISSUE TITLE
E303 Unable to open swap file for "{filename}", recovery impossible

### ISSUE THREAD

**Issue by jiajunhuang** [neovim/neovim#3898] opened 2015-12-25 02:33 UTC
I'm using nvim compiled by myself, and when I open a file, I got this error.

it seems that the reason is `XDG_DATA_HOME` is not defined(I'm using it in my ubuntu 14.04 server), it's a sysvinit system. I've google for it, and I got this link: https://wiki.archlinux.org/index.php/XDG_Base_Directory_support

so I wonder is it possible to hard code the directory(or some better ways) to `.config/nvim/`?

ps: I guess `XDM_DATA_HOME` is not defined in osx, let alone windows.

**Comment by justinmk** [comment] 2015-12-25 13:08
> it seems that the reason is XDG_DATA_HOME is not defined

Most users do not have that defined. What is `:set directory?` ?

This is a configuration issue, so closing.

**Closed by justinmk** 2015-12-25 13:08 UTC

**Comment by jiajunhuang** [comment] 2015-12-26 09:40
it's `directory=~/.local/share/nvim/swap//`.

and I've disable $XDG_DATA_HOME , so I still got this error: `E303 Unable to open swap file for "{filename}", recovery impossible`, it will disappear if I export XDG_DATA_HOME variable:

```bash
export XDG_DATA_HOME="$HOME/.config/nvim"
```

and nvim version:

```bash
$ nvim --version
NVIM 0.1.1 (compiled Dec 23 2015 21:24:39)
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/build/config -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/src -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/.deps/usr/include -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/.deps/usr/include -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/.deps/usr/include -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/.deps/usr/include -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/build/include
Compiled by buildd@lgw01-26

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by ZyX-I** [comment] 2015-12-26 10:18
@jiajunhuang Since Neovim is creating directory for swap files, it is permission problems. Make sure that ~/.local/share/nvim/swap either exists, is a directory and can be written to or any of the /home, ~, ~/.local, ~/.local/share, ~/.local/share/nvim exist, is a directory and can be written to (for recursively creating ~/.local/share/nvim/swap).

Also it is not correct to set XDG_DATA_HOME to `$XDG_CONFIG_HOME/nvim`: 1. this variable is used not only by Neovim and 2. XDG_CONFIG_HOME is for configs and it is unexpected to share the same location with XDG_DATA_HOME.

**Comment by jiajunhuang** [comment] 2015-12-26 11:15
ok, thanks.

**Comment by bnjmn** [comment] 2016-06-07 13:32
Thought I would share my experience for clarity since the op did not specify what issue/solution was. Thanks to @ZyX-I for pointing me in the right direction.

I had a similar issue using Ubuntu 16.04 and neovim 0.1.5-dev installed using the neovim-ppa. Turns out `~/.local/share/nvim/swap` was owned by `root`; all the other directories under `~/.local` were owned by my user. After updating the ownership on this directory to my user and group, the problem was solved:


    sudo chown -R my_user:my_user ~/.local/share/nvim/swap

**Comment by jamessan** [comment] 2016-06-07 14:13
This sounds like the same root cause as #4551.  If the first time the user runs nvim is via sudo (and sudo uses the user's `$HOME`), then the directory tree will be created as root.

I highly recommend using `sudoedit` or `sudo -e` instead of actually running the editor under sudo.

**Comment by ianliu** [comment] 2018-03-13 20:39
@justinmk  I would like to revisit this issue, since I'm getting it and none of the comments here apply to my case. I've generated a [strace.log](https://github.com/neovim/neovim/files/1808572/strace.log) to see why NeoVim is not able to open the swap file (the swap file does not exists, by the way). If you go to the line number 557 to 560 you will see that several system calls failed with `ENAMETOOLONG`, and by looking at the file path being processed it is indeed very long.

Any help here?

**Comment by jamessan** [comment] 2018-03-13 22:02
@ianliu If your root cause is different, then you should open a new issue.
