### ISSUE TITLE
CTRL-h cannot be used in Neovim as mapping even when not in the console

### ISSUE THREAD

**Issue by SirVer** [neovim/neovim#2294] opened 2015-03-30 05:44 UTC
While using NeoVim with the promising new GUI project at https://github.com/rogual/neovim-dot-app I found out that `<ctrl-h>` is mapped to `<bs>`.

Mapped is probably the wrong word - this is an anachronism from terminal days where this byte combination meant backspace - but in modern GUI days, it feels wrong that `<ctrl-h>` cannot be used inside Vim as any other key combination. And in fact in gvim or macvim it can be used.

**Comment by ntnn** [comment] 2015-03-30 05:50
It does work, but not with `ctrl`, you have to use `c`: `map <c-h> :vertical res -5<CR>` (i.e.). Just as well you use `a` for meta (or alt, I'm not sure), `s` for shift, ...

**Comment by SirVer** [comment] 2015-03-30 06:03
@ntnn thanks for the comment. I realize my comment was not fully clear. Here is how to repro:

~~~
$ nvim # you need to start some gui client though, otherwise your terminal might already eat the <c-h>
:imap <c-h> blub
i<c-h>
~~~~

The i in the last line will be deleted. If you use something else for mapping (e.g. c-b), you will have iblub in your buffer instead.

**Comment by hendrikcech** [comment] 2015-03-30 08:02
@SirVer I have the same problem. [This workaround](https://github.com/neovim/neovim/issues/2048#issuecomment-78045837) solves the issue in my case.

**Comment by tarruda** [comment] 2015-03-30 10:32
@SirVer thats the GUI is sending `<c-h>` when backspace is pressed. cc @rogual

**Comment by rogual** [comment] 2015-03-30 11:45
I'm working on a key handling patch that should fix this as well as enable multiple modifiers. Should be ready real soon.

**Comment by schickling** [comment] 2015-04-16 10:47
+1

**Comment by rogual** [comment] 2015-04-16 10:50
This should be possible in Neovim.app now.

**Comment by schickling** [comment] 2015-04-16 10:51
I've built neovim yesterday and it doesn't seem to work by now (there are no new commits since two days, so I assume I have the newest version).

**Comment by rogual** [comment] 2015-04-16 10:53
Just to clarify, we're talking about the OSX GUI here. https://github.com/rogual/neovim-dot-app/

**Comment by schickling** [comment] 2015-04-16 10:57
My bad!

**Comment by spacepluk** [comment] 2015-04-16 11:05
I'm not sure it's related but I have the same problem in a terminal but only while it's running in tmux.

**Comment by badeip** [comment] 2015-04-18 07:46
This might be a duplicate of bug #2048

**Comment by splinterofchaos** [comment] 2015-04-18 16:15
Yes, there have been several duplicates of this issue, but #2048 takes precedence for both being first and having much more detailed information and discussion. Thank you for reporting.

**Closed by splinterofchaos** 2015-04-18 16:15 UTC
