### ISSUE TITLE
 mapping ctrl-c breaks noremap'd ctrl-c

### ISSUE THREAD

**Issue by sosmo** [neovim/neovim#15519] opened 2021-08-29 13:00 UTC
### Neovim version (nvim -v)

0.5

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Kubuntu 21.04

### Terminal name/version

Konsole

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

I have this mapping to make <c-c> close cmd windows immediately - usually you have to press <c-c> twice. The mapping is ugly but works on original vim.

First, copy the augroup mapping to system clipboard:
```
augroup dirty_cc_remap
	autocmd!
	autocmd CmdWinEnter * inoremap <c-c> <c-c><c-c>
	autocmd CmdWinEnter * noremap <c-c> <c-c><c-c>
	autocmd CmdWinLeave * inoremap <c-c> <c-c>
	autocmd CmdWinLeave * noremap <c-c> <c-c>
augroup END
```

Run:
```
nvim -u NONE
:@+
:while 1 | endwhile
<c-c>
```

### Expected behavior

Pressing `<c-c>` as the last action should break out of the loop.

### Actual behavior

Nvim hangs

**Comment by justinmk** [comment] 2021-08-29 14:39
7cd204dbfa9b was a partial attempt to fix this. 

duplicate of https://github.com/neovim/neovim/issues/15258

**Closed by justinmk** 2021-08-29 14:39 UTC
Labels: bug
