### ISSUE TITLE
`:help 'nobri'` not work

### ISSUE THREAD

**Issue by bottycode** [neovim/neovim#17964] opened 2022-04-02 11:19 UTC
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

no, vim 8.2.2783

### Operating system/version

Ubuntu 20.04

### Terminal name/version

Windows Terminal 1.11.3471.0

### $TERM environment variable

xterm-256color

### Installation

github release

### How to reproduce the issue

`:help 'nobri'`

### Expected behavior

Show the `breakindent` entry in `options.txt`

### Actual behavior

`E149: Sorry, no help for nobri`

**Comment by clason** [comment] 2022-04-02 11:24
Well, it looks like a vim-patch got lost somewhere...

Are there any other `'nofoo'` tags that are missing in `options.txt`? Might as well fix them all at once.

**Comment by zeertzjq** [comment] 2022-04-02 11:24
<https://github.com/vim/vim/commit/7c1c6dbb6817640fd3956a0d5417da23fde336d8>
<https://github.com/vim/vim/commit/7c1c6dbb6817640fd3956a0d5417da23fde336d8>

**Comment by clason** [comment] 2022-04-02 11:27
Yeah, looks like a regression (7.4.907 should already be merged).

**Comment by zeertzjq** [comment] 2022-04-02 11:29
Skipped by <https://github.com/neovim/neovim/commit/1fbb56795d16783f9a97e25e3b71ab3ac2a644dc>

**Closed** 2022-04-02 12:08 UTC
Labels: bug, documentation, status:has-vim-patch

**Comment by bottycode** [comment] 2022-04-02 13:07
Looks like there are more 'nofoo' tags missing:

```
grep -P "(?<=')\s+boolean\b" -B 1 runtime/doc/options.txt | grep "*'" | grep -v no
                                                *'breakindent'* *'bri'*
                                                *'emoji'* *'emo'*
                                                *'fsync'* *'fs'*
                                                *'termguicolors'* *'tgc'*
```

**Comment by clason** [comment] 2022-04-02 13:10
`'nobri'` and`'nofs'` were just added; the other two are Neovim-only, and I'll add them in a followup PR.

**Comment by zeertzjq** [comment] 2022-04-02 13:12
`'noemoji'` was skipped in <https://github.com/neovim/neovim/commit/e686b613ecd349265e17d9c1f481cafac4935aef>.
