### ISSUE TITLE
Package load order depends on location

### ISSUE THREAD

**Issue by timokau** [neovim/neovim#9390] opened 2018-12-22 21:40 UTC
- `nvim --version`: 0.3.1
- Vim (version: ) behaves differently? behaves the same
- Operating system/version: NixOS unstable
- Terminal name/version: kitty
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

I wasn't able to produce a minimal working example. I'm not sure what exactly causes the issue.

### Actual behaviour

Neovim loads the default `tex.vim` filetype before the one from the vimtex plugin (verified with `:scriptnames`). That is even though vimtex is in the `start` directory of `pack/mypack`.

This is similar to the issue reported [here](https://github.com/lervag/vimtex/issues/586) and [here](https://github.com/Vimjas/vim-python-pep8-indent/issues/67). I couldn't reproduce the issue with the setup reported there however (`~/.config/nvim` being a symlink). For me the issue occurs because of NixOS's non-standard filesystem layout. Here is the output of `:scriptnames` when opening a `tex` file (28 and 36 are in the wrong order):

```
  1: /nix/store/n95mndkpmqrph3zxv0p7lasl7k3cmzcw-vimrcg
  2: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/filetype.vimg
  3: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/ftplugin.vimg
  4: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/indent.vimg
  5: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/syntax/syntax.vimg
  6: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/syntax/synload.vimg
  7: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/syntax/syncolor.vimg
  8: /nix/store/6c5q1a82il9yn1a50gd5xp38m36klc7q-vimplugin-gruvbox-2018-02-25/share/vim-plugins/gruvbox/colors/gruvbox.vimg
  9: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/syntax/nosyntax.vimg
 10: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/gzip.vimg
 11: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/health.vimg
 12: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/man.vimg
 13: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/matchit.vimg
 14: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/matchparen.vimg
 15: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/netrwPlugin.vimg
 16: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/rplugin.vimg
 17: ~/.local/share/nvim/rplugin.vimg
 18: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/autoload/remote/host.vimg
 19: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/autoload/remote/define.vimg
 20: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/rrhelper.vimg
 21: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/shada.vimg
 22: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/spellfile.vimg
 23: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/tarPlugin.vimg
 24: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/tohtml.vimg
 25: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/tutor.vimg
 26: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/plugin/zipPlugin.vimg
 27: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/autoload/dist/ft.vimg
 28: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/ftplugin/tex.vimg
 29: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/ftplugin/plaintex.vimg
 30: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/ftplugin/initex.vimg
 31: /nix/store/jww45611n0ca5hfrgbsdrm1fdd4d8fi7-vimplugin-vimtex-2018-12-12/share/vim-plugins/vimtex/ftplugin/tex.vimg
 32: /nix/store/jww45611n0ca5hfrgbsdrm1fdd4d8fi7-vimplugin-vimtex-2018-12-12/share/vim-plugins/vimtex/after/ftplugin/tex.vimg
 33: /nix/store/jww45611n0ca5hfrgbsdrm1fdd4d8fi7-vimplugin-vimtex-2018-12-12/share/vim-plugins/vimtex/autoload/vimtex.vimg
 34: /nix/store/jww45611n0ca5hfrgbsdrm1fdd4d8fi7-vimplugin-vimtex-2018-12-12/share/vim-plugins/vimtex/autoload/vimtex/util.vimg
 35: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/indent/tex.vimg
 36: /nix/store/jww45611n0ca5hfrgbsdrm1fdd4d8fi7-vimplugin-vimtex-2018-12-12/share/vim-plugins/vimtex/indent/tex.vimg
 37: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/syntax/tex.vimg
 38: /nix/store/jww45611n0ca5hfrgbsdrm1fdd4d8fi7-vimplugin-vimtex-2018-12-12/share/vim-plugins/vimtex/after/syntax/tex.vimg
 39: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/syntax/dot.vimg
 40: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/syntax/lua.vimg
 41: /nix/store/imnf5g2gqpzyh2cyv1mbkir280iak7s9-neovim-unwrapped-0.3.1/share/nvim/runtime/syntax/gnuplot.vimg
 ```

### Expected behaviour

Explicitly loaded plugins are loaded first, as is the case with vim-plug etc.

I'm sorry that the issue descriptons is not entirely clear. I don't really understand the problem well enough. I'm happy to answer any followup questions.

**Comment by justinmk** [comment] 2018-12-23 12:11
Can you try the 0.3.2 prerelease https://github.com/neovim/neovim/releases

**Comment by timokau** [comment] 2018-12-23 13:01
I just did, it (current prerelease at commit 87b40f7445dce4477d575ac74b63132bade60a47) behaves the same as 3.1.

**Comment by justinmk** [comment] 2018-12-23 13:09
cc @brammool @chrisbra

**Comment by brammool** [comment] 2018-12-23 13:35
What is 'runtimepath' set to?
Perhaps patch 8.1.0353 matters?

**Comment by timokau** [comment] 2018-12-23 13:41
runtimepath is

```
~/.config/nvim
~/.nix-profile/etc/xdg/nvim
/nix/var/nix/profiles/default/etc/xdg/nvim
/run/current-system/sw/etc/xdg/nvim
/etc/profiles/per-user/timo/etc/xdg/nvim
~/.local/share/nvim/site
/run/opengl-driver/share/nvim/site
~/.nix-profile/share/nvim/site
/nix/var/nix/profiles/default/share/nvim/site
/run/current-system/sw/share/nvim/site
/etc/profiles/per-user/timo/share/nvim/site
/nix/store/as4y9knjyhws44k4w988mrq6apw4a68m-neovim-unwrapped-0.3.2-pre/share/nvim/runtime
/etc/profiles/per-user/timo/share/nvim/site/after
/run/current-system/sw/share/nvim/site/after
/nix/var/nix/profiles/default/share/nvim/site/after
~/.nix-profile/share/nvim/site/after
/run/opengl-driver/share/nvim/site/after
~/.local/share/nvim/site/after
/etc/profiles/per-user/timo/etc/xdg/nvim/after
/run/current-system/sw/etc/xdg/nvim/after
/nix/var/nix/profiles/default/etc/xdg/nvim/after
~/.nix-profile/etc/xdg/nvim/after
~/.config/nvim/after
/nix/store/mfj2safb59d3jbg1y29w8s3gl227r7vx-vim-pack-dir/pack/myVimPackage/start/base16-vim
/nix/store/mfj2safb59d3jbg1y29w8s3gl227r7vx-vim-pack-dir/pack/myVimPackage/start/gruvbox
/nix/store/mfj2safb59d3jbg1y29w8s3gl227r7vx-vim-pack-dir/pack/myVimPackage/start/vimtex
/nix/store/mfj2safb59d3jbg1y29w8s3gl227r7vx-vim-pack-dir/pack/myVimPackage/start/vimtex/after
```

Should I try to apply that patch? If so, where would I get the patch file?

**Comment by timokau** [comment] 2018-12-25 09:52
I am using the same setup, so it is probably the same issue. Thanks for providing additional context.

However I can *not* confirm that this has anything to do with `-u`. I tried copying the vimrc file to `~/.config/nvim/init.vim` instead of using `-u` and the same issue remains.

**Comment by timokau** [comment] 2018-12-25 09:57
The issue also occurs if I shorten the generated vimrc down to just

```
set packpath-=~/.vim/after
set packpath+=/nix/store/zxnn9043abc2z94xaygysz5pikgz7jnw-vim-pack-dir
set packpath+=~/.vim/after
```

Where the `vim-pack-dir` has `vimtex` in start.

**Comment by justinmk** [comment] 2018-12-27 18:33
we need these vim patches:

     8.1.0354: packadd test fails on MS-Windows (Bram Moolenaar)
     8.1.0353: an "after" directory of a package is appended to 'rtp' (Bram Moolenaar)
     8.0.1734: package directory not added to 'rtp' if prefix matches (Bram Moolenaar)
     8.0.1469: when package path is a symlink 'runtimepath' is wrong (Bram Moolenaar)

**Comment by timokau** [comment] 2018-12-27 18:56
The same issue exists with vim 8.1.0578 though.

**Comment by jamessan** [comment] 2018-12-29 15:34
> The issue also occurs if I shorten the generated vimrc down to just
> 
> ```
> set packpath-=~/.vim/after
> set packpath+=/nix/store/zxnn9043abc2z94xaygysz5pikgz7jnw-vim-pack-dir
> set packpath+=~/.vim/after
> ```
> 
> Where the `vim-pack-dir` has `vimtex` in start.

Why is `~/.vim/after` being added to `'packpath'`?  `~/.vim/after` is already part of the standard `'runtimepath'`.

**Comment by timokau** [comment] 2018-12-29 16:04
I don't know why it is done that way, good question. I have asked the author of the code that generated the vimrc: https://github.com/NixOS/nixpkgs/commit/7bb0611e2e27b3e5b7db7c93a3635fab5f7d3306#r31802229

It is not relevant for this issue however. An even more minimal vimrc that also reproduces the issue is just

```
set packpath+=/nix/store/zxnn9043abc2z94xaygysz5pikgz7jnw-vim-pack-dir
```

**Comment by jamessan** [comment] 2018-12-29 16:14
> we need these vim patches:
> 
> ```
>  8.1.0354: packadd test fails on MS-Windows (Bram Moolenaar)
>  8.1.0353: an "after" directory of a package is appended to 'rtp' (Bram Moolenaar)
>  8.0.1734: package directory not added to 'rtp' if prefix matches (Bram Moolenaar)
>  8.0.1469: when package path is a symlink 'runtimepath' is wrong (Bram Moolenaar)
> ```

Working on those in https://github.com/neovim/neovim/pull/9409.

**Comment by timokau** [comment] 2018-12-30 08:47
Still reproducible with the latest master (d442345729a497663b32ee0609c6b697567a4e10, including #9409).

**Comment by evanjs** [comment] 2019-09-29 18:50
Still reproducible on NixOS unstable `20.03pre194293.2436c27541b (Markhor)` running `NVIM v0.4.2`.
Here is my current [configuration](https://github.com/evanjs/nixos_cfg/blob/fcb2a685b4d1f990cadaaddeacd3e217927dd0a1/config/new-modules/vim/vim.nix).

Some things to note:
Package load order seemed to work fine when I used [VAM](https://nixos.wiki/wiki/Vim#Using_VAM_as_manager). 
[Here](https://github.com/evanjs/nixos_cfg/blob/ef3ddb47a6912027165ae90fed76ced7e0be2c8b/config/new-modules/vim/vim.nix) is what my config looked like around that time.

I eventually switched to using [home-manager](https://github.com/rycee/home-manager)'s [`neovim.plugins`](https://rycee.gitlab.io/home-manager/options.html#opt-programs.neovim.plugins)-based approach after https://github.com/rycee/home-manager/pull/793 was merged.

After this, some plugins seemed to function as intended (e.g. colorizer, vim-illumniate, etc), while other plugins functioned with varying levels of success.
For example, I can use `Latexmk` just fine, but no `Vimtex` commands are available.

Note that these commands do work fine after `:call vimtex#init()`.

Not sure how much of this is relevant, just wanted to share my findings, and am happy to dig further if it helps us get closer to solving this issue.

I tried just swapping out neovim for vim with my current config, and... yeah, doesn't quite work :upside_down_face:
And I'd rather contribute to fixing this issue than retrofitting my configuration for vim.

**Comment by tqbl** [comment] 2019-09-29 19:09
@evanjs, please see https://github.com/NixOS/nixpkgs/issues/39364#issuecomment-513800296. Basically, when packpath directories are appended to runtimepath, `$VIMRUNTIME` is already there, so it takes precedence. I'm not sure what the neovim developers will want to do about this as it's not really a bug. For NixOS users, two solutions are:

1. Directly modify the runtimepath (see the end of https://github.com/NixOS/nixpkgs/issues/39364#issuecomment-425536054)
2. Take advantage of the `--with-global-runtime` configure flag (e.g. tqbl/nixpkgs@eb474ed).

**Comment by evanjs** [comment] 2019-09-29 19:24
@tqbl Ah alright, I came here after seeing this [comment](https://github.com/rycee/home-manager/issues/815#issuecomment-536168793) and probably should've checked there first.

Woo! Looks one of those workarounds [works](https://github.com/evanjs/nixos_cfg/commit/75053dfedbe9d54e7bac4da23f44ad0604c50c2a), though I'll follow up with https://github.com/NixOS/nixpkgs/issues/39364 from now on in that case.

Lesson for the day: Read through _all_ of the threads in the comment before posting on any of them.

Thanks again!
(Probably going to apply your patch so I can keep my vim config clean, though...)

**Comment by tqbl** [comment] 2019-09-29 19:37
I can't blame you. Too many threads on this issue!

Thinking about it some more, I want to retract saying that this isn't an issue with vim/neovim. Perhaps packpath directories _should_ be added intelligently to runtimepath. After all, these are plugin directories specified by the user. At the very least, maybe document the current behaviour.

**Comment by jonringer** [comment] 2020-02-20 02:57
This might be solved for nixos users by https://github.com/NixOS/nixpkgs/pull/78385

**Comment by justinmk** [comment] 2021-09-19 16:09
> Perhaps packpath directories _should_ be added intelligently to runtimepath.

- related: https://github.com/neovim/neovim/pull/15632

**Comment by abitrolly** [comment] 2022-08-11 07:14
Is this issue still actual?

**Comment by clason** [comment] 2022-08-11 11:17
Not on a standard install (VimTeX is sourced before builtin; I just tested this).

**Closed by clason** 2022-08-11 11:17 UTC
Labels: status:has-vim-patch, bug-vim, status:has-workaround

**Comment by voidus** [comment] 2022-09-03 01:48
Just ran into this problem while trying to use `vim-javascript`. The nvim `syntax/javascript.vim` is sourced first instead of the one from the plugin
