### ISSUE TITLE
autoread doesn't work when returning from suspend

### ISSUE THREAD

**Issue by rcorre** [neovim/neovim#6042] opened 2017-02-01 20:07 UTC
- `nvim --version`: NVIM 0.1.7
- Vim (version: 8.0) behaves differently? yes. with `autoread` set, the file is
  loaded on returning from suspend
- Operating system/version:  Linux 4.8.13-1-ARCH x86_64 GNU/Linux
- Terminal name/version: st 20161214.f4b1a8f-1
- `$TERM`: st-256color

### Actual behaviour

neovim does not reload the modified file on resuming from suspend

### Expected behaviour

neovim does reload the modified file on resuming from suspend

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC file
<ctrl-z>
echo asdf >> file
fg
```

[this plugin](https://github.com/TheZoq2/neovim-auto-autoread) is a workaround, but shouldn't be necessary.

Related: #1936

**Comment by justinmk** [comment] 2017-02-01 23:38
I'll look at this as part of https://github.com/neovim/neovim/pull/5599.

**Comment by rcorre** [comment] 2017-02-02 17:09
Thanks. Give a shout if you need someone to test it on linux.

**Comment by justinmk** [comment] 2017-09-04 07:00
This is actually a duplicate of https://github.com/neovim/neovim/issues/2127

**Closed by justinmk** 2017-09-04 07:00 UTC
Labels: tui
