### ISSUE TITLE
segfault during insert expression register

### ISSUE THREAD

**Issue by mcastorina** [neovim/neovim#18214] opened 2022-04-22 03:57 UTC
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

No, vim 8.2.4651

### Operating system/version

Linux 5.17.3-arch1-1

### Terminal name/version

rxvt-unicode v9.26

### $TERM environment variable

rxvt-unicode-256color

### Installation

System package manager

### How to reproduce the issue

`nvim --clean`
`i<C-R>=]]`

### Expected behavior

Does not segfault

### Actual behavior

Segfaults

**Comment by zeertzjq** [comment] 2022-04-22 04:24
UBSAN stacktrace:
```
**/src/nvim/viml/parser/expressions.c:2001:5: runtime error: load of null pointer of type 'ExprASTNode *' (aka 'struct expr_ast_node *')
    #0 0x5577b0d16d47 in viml_pexpr_parse **/src/nvim/viml/parser/expressions.c:2001:5
    #1 0x5577affcba0a in color_expr_cmdline **/src/nvim/ex_getln.c:2705:18
    #2 0x5577affc50d6 in color_cmdline **/src/nvim/ex_getln.c:2820:5
    #3 0x5577aff69a99 in draw_cmdline **/src/nvim/ex_getln.c:2978:8
    #4 0x5577aff6e9a5 in put_on_cmdline **/src/nvim/ex_getln.c:3349:5
    #5 0x5577affb57d9 in command_line_handle_key **/src/nvim/ex_getln.c:2273:5
    #6 0x5577aff9e222 in command_line_execute **/src/nvim/ex_getln.c:1572:10
    #7 0x5577b0b278ce in state_enter **/src/nvim/state.c:89:26
    #8 0x5577aff5f89f in command_line_enter **/src/nvim/ex_getln.c:926:3
    #9 0x5577aff5b34c in getcmdline **/src/nvim/ex_getln.c:2422:10
    #10 0x5577b050c8fc in get_expr_register **/src/nvim/ops.c:730:14
    #11 0x5577afb3dffb in ins_reg **/src/nvim/edit.c:7831:15
    #12 0x5577afb3720d in insert_handle_key **/src/nvim/edit.c:963:5
    #13 0x5577afaf1d24 in insert_execute **/src/nvim/edit.c:840:10
    #14 0x5577b0b278ce in state_enter **/src/nvim/state.c:89:26
    #15 0x5577afaf91db in insert_enter **/src/nvim/edit.c:496:5
    #16 0x5577afaedf79 in edit **/src/nvim/edit.c:1472:3
    #17 0x5577b04e49be in invoke_edit **/src/nvim/normal.c:6883:7
    #18 0x5577b04b20e8 in nv_edit **/src/nvim/normal.c:6860:5
    #19 0x5577b049bb96 in normal_execute **/src/nvim/normal.c:1153:3
    #20 0x5577b0b278ce in state_enter **/src/nvim/state.c:89:26
    #21 0x5577b047312a in normal_enter **/src/nvim/normal.c:450:3
    #22 0x5577b01feaa3 in main **/src/nvim/main.c:574:3
    #23 0x7fc823b9a30f in __libc_start_call_main libc-start.c
    #24 0x7fc823b9a3c0 in __libc_start_main@GLIBC_2.2.5 (/usr/lib/libc.so.6+0x2d3c0)
    #25 0x5577af641dc4 in _start (**/build/bin/nvim+0xbdbdc4)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior **/src/nvim/viml/parser/expressions.c:2001:5 in 
```

**Comment by jamessan** [comment] 2022-04-22 11:51
Duplicate of #7889

**Closed by jamessan** 2022-04-22 11:51 UTC
Labels: vimscript, status:has-backtrace, bug-crash

**Comment by zeertzjq** [comment] 2022-04-22 11:55
Hmm, the backtrace is a bit different.
