### ISSUE TITLE
terminal mode hang at 100% CPU when interrupted with <C-c>

### ISSUE THREAD

**Issue by ibhagwan** [neovim/neovim#20726] opened 2022-10-18 20:40 UTC
### Neovim version (nvim -v)

NVIM v0.8.0

### Vim (not Nvim) behaves the same?

not using vim

### Operating system/version

Void Linux kernel 5.10.147

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

screen-256color

### Installation

Void Linux xbps package manager

### How to reproduce the issue

I am able to consistently get neovim to hang at 100% CPU when using [fzf-lua](https://github.com/ibhagwan/fzf-lua), opening any interface and quickly pressing `<C-c>`.
> Note that to rerproduce this consistently [this commit](https://github.com/ibhagwan/fzf-lua/commit/c90a88b354ae12736760f623000d91b438b04234) which maps `<C-c>` to `<Esc>` in termal mode, needs to be reverted or you can test with the [`trace` branch](https://github.com/ibhagwan/fzf-lua/tree/trace) which also contains trace logging to file.

What happens behind the scenes is fzf-lua opening a new window and running `termopen` with the fzf command and then waits for the job's `on_exit` callback.

While stuck I ran  `strace -s 99 -ffp <pid> ` on the neovim pid and it seems to be polling a no longer existing thread (not sure about that, but in the below pid `27433` no longer exists), the loop below continues endlessly:
```
[pid 27433] <... epoll_wait resumed>[{events=EPOLLIN, data={u32=18, u64=18}}], 1024, -1) = 1
[pid 27432] <... write resumed>)        = 8
[pid 27433] read(18, "\1\0\0\0\0\0\0\0", 1024) = 8
[pid 27432] epoll_wait(9,  <unfinished ...>
[pid 27433] epoll_wait(15,  <unfinished ...>
[pid 27432] <... epoll_wait resumed>[], 1024, 0) = 0
[pid 27432] epoll_wait(9, [], 1024, 0)  = 0
[pid 27432] epoll_wait(9, [], 1024, 0)  = 0
[pid 27432] epoll_wait(9, [], 1024, 0)  = 0
[pid 27432] write(32, "\3", 1)          = 1
[pid 27432] write(18, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
[pid 27433] <... epoll_wait resumed>[{events=EPOLLIN, data={u32=18, u64=18}}], 1024, -1) = 1
[pid 27432] <... write resumed>)        = 8
[pid 27433] read(18, "\1\0\0\0\0\0\0\0", 1024) = 8
[pid 27432] epoll_wait(9,  <unfinished ...>
[pid 27433] epoll_wait(15,  <unfinished ...>
[pid 27432] <... epoll_wait resumed>[], 1024, 0) = 0
[pid 27432] epoll_wait(9, [], 1024, 0)  = 0
[pid 27432] epoll_wait(9, [], 1024, 0)  = 0
[pid 27432] epoll_wait(9, [], 1024, 0)  = 0
[pid 27432] write(32, "\3", 1)          = 1
[pid 27432] write(18, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
```

In an effort to understand where this issue comes from I added trace logging to my plugin from the moment the `termopen` succeeds until `on_exit` is called, you can enable logging to file (only with the [`trace` branch](https://github.com/ibhagwan/fzf-lua/tree/trace)) with:
```lua
require'fzf-lua'.setup({ debug_tracelog = "~/neovim.log" })
```

With the above setup the file gets overwritten each time the fzf-lua interface is open, the results indicate neovim is stuck in an endless loop calling the `vim._on_key(char)` function within the runtime `runtime/lua/vim/_editor.lua:560`, relevant part of the log right before it gets stuck:
```
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:102 nil
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:79 finish
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:81 finish
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:82 finish
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:83 finish
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:85 finish
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/fzf.lua:104 nil
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/manager.lua:449 nil
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/manager.lua:450 nil
2022-10-18T13:26:32 @/home/bhagwan/.local/share/nvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/manager.lua:451 nil
2022-10-18T13:26:32 @/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:258 nil
2022-10-18T13:26:32 @/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:259 nil
2022-10-18T13:26:32 @/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:260 nil
2022-10-18T13:26:32 @vim/_editor.lua:561 nil  <= first line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:562 nil
2022-10-18T13:26:32 @vim/_editor.lua:563 nil
2022-10-18T13:26:32 @vim/_editor.lua:572 nil
2022-10-18T13:26:32 @vim/_editor.lua:581 nil
2022-10-18T13:26:32 @vim/_editor.lua:561 nil  <= first line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:562 nil  <= last line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:563 nil
2022-10-18T13:26:32 @vim/_editor.lua:572 nil
2022-10-18T13:26:32 @vim/_editor.lua:581 nil  <= last line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:561 nil  <= first line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:562 nil
2022-10-18T13:26:32 @vim/_editor.lua:563 nil
2022-10-18T13:26:32 @vim/_editor.lua:572 nil
2022-10-18T13:26:32 @vim/_editor.lua:581 nil  <= last line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:561 nil  <= first line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:562 nil
2022-10-18T13:26:32 @vim/_editor.lua:563 nil
2022-10-18T13:26:32 @vim/_editor.lua:572 nil
2022-10-18T13:26:32 @vim/_editor.lua:581 nil  <= last line of vim._on_key
2022-10-18T13:26:32 @vim/_editor.lua:561 nil  <= first line of vim._on_key
```

I think this might be related to neovim not yet interrupting lua code as explained in #6800?

@famiu, @ZyX-I, @justinmk, if my analysis is correct, do you have any idea why this happens? What part of the code causes this? Any workarounds I can apply before #19096 is merged (aside from remapping `<C-c>`)?

### Expected behavior

Neovim should be able to handle `<C-c>`.

### Actual behavior

Neovim will occasionally become unresponsive when pressing `<C-c>`.

**Comment by vhoyer** [comment] 2022-10-21 17:44
https://github.com/vim-airline/vim-airline/issues/2588 I can reproduce this freezing behavior with `vim-airline`

here is a reproduction repo: https://github.com/vhoyer-bug-reproductions/airline-freeze-on-C-c

**Comment by vhoyer** [comment] 2022-10-21 17:45
also this is happening with `NVIM v0.7.2`

**Comment by vhoyer** [comment] 2022-10-24 14:28
btw, vim-airline doesn't use lua, so I don't know if the labels are correctly applied, or maybe it's a different problem with the same behavior, should I open a new issue?

**Comment by jrahm** [comment] 2023-01-30 20:40
Not sure if this is the same bug or not, but it sounds similar, and I believe I found fairly minimal steps to reproduce:

1. Open neovim with `nvim -u NONE`
2. Open a terminal
3. Source a file with the following contents:

```lua
local vim = assert(vim)
local loop = vim.loop

local i = 0

local function do_cmd()
  i = i + 1
  print ("spawn: " .. i)
  loop.spawn('echo', {
    args = {'hi'}
  }, function () end)
end

local function start_polling()
  vim.defer_fn(function ()
    local j = 0
    while j < 100 do
      do_cmd()
      j = j + 1
    end
    start_polling()
  end, 100)
end

start_polling()
```
4. In the terminal (in INSERT mode) hold Ctrl-C. (In otherwords just send a bunch of Ctrl-C's to the terminal. For reference I have my keyboard rate set to `xset r rate 300 100`, so it repeats pretty fast).

After several seconds the terminal should hang and Neovim will lock up at 100% CPU. 

Obviously this example is pretty contrived, but the freeze happens often enough on my dev workflow to be annoying. (I have a plugin that periodically polls information by launching a bunch of commands). It appears to be a race conditions where if Ctrl-C is pressed at the exact wrong time during the job life cycle, it get's stuck in a loop.

Poking around in GDB indicates that Neovim thinks it's getting a constant stream of Ctrl-C's, so it appears that maybe `got_int` is not being cleared somewhere. Using gdb to manually `set got_int = 0` will break the loop.

To further add to the mystery, I replicated this on 3 different machines (All Linux-based, Arch and Debian), however, I could not get the bug to replicate on a Gentoo server I run. All versions of Neovim were built from source though, so it seems strange to have different behavior. Maybe the server hardware is beefy enough that it masks the issue.

I was also able to replicate this issue on the packaged release of Neovim in Arch linux:

**Comment by masaeedu** [comment] 2023-03-12 11:09
Anyone know of a workaround for getting out of this state once you're in it? For me the entire terminal is unresponsive, so I'm not sure what to do.

**Comment by vhoyer** [comment] 2023-03-12 11:29
Open another terminal, and kill the nvim process

**Comment by masaeedu** [comment] 2023-03-12 11:39
@vhoyer Yes, this is the "workaround" I've been using, but I'd prefer to keep my vim session if at all possible.

**Comment by AugustoDeveloper** [comment] 2023-05-19 21:07
In my computer, i'm getting a similar situation, when NeoVim attached to Omnisharp, the process hangs on 100% but i can use even hanging one of four cores. But, when i try exit from Neovim, the process stops to respond. 



To finish the process, i need execute `kill` command.
![image](https://github.com/neovim/neovim/assets/4335700/f9e9f409-088d-4166-ba0f-efee3b9a60ed)
![image](https://github.com/neovim/neovim/assets/4335700/8c6216cc-d04b-46ef-b093-a8f1d8e4671c)
![image](https://github.com/neovim/neovim/assets/4335700/0bf278ae-32bd-4002-8ba7-a02badbb5143)

**Comment by Kraust** [comment] 2023-05-26 18:40
I have been consistently running into this issue for months, the way I frequently run into it is by pressing C-c when there is a terminal buffer outputting a lot of text to the screen (e.g. from the output of a `tail -f`. I was able to reproduce the same EPOLLIN loop when attaching strace to the process.

**Comment by dispensable** [comment] 2023-05-31 04:16
Same issue here, nvim keep reading `^C` and the whole process use 100% cpu and memory until i killed it.

strace 

```
epoll_wait(9, [{events=EPOLLIN, data={u32=39, u64=39}}], 1024, 0) = 1
read(39, "^C", 3203)                    = 2
epoll_wait(9, [], 1024, 0)              = 0
write(38, "\3", 1)                      = 1
write(14, "\223\2\246redraw\334\0\2\334\0\2\260grid_cursor_goto"..., 47) = 47
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [{events=EPOLLIN, data={u32=39, u64=39}}], 1024, 0) = 1
read(39, "^C", 3201)                    = 2
epoll_wait(9, [], 1024, 0)              = 0
write(38, "\3", 1)                      = 1
write(14, "\223\2\246redraw\334\0\2\334\0\2\260grid_cursor_goto"..., 47) = 47
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [{events=EPOLLIN, data={u32=39, u64=39}}], 1024, 0) = 1
read(39, "^C", 3199)                    = 2
epoll_wait(9, [], 1024, 0)              = 0
write(38, "\3", 1)                      = 1
write(14, "\223\2\246redraw\334\0\2\334\0\2\260grid_cursor_goto"..., 47) = 47
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [{events=EPOLLIN, data={u32=39, u64=39}}], 1024, 0) = 1
read(39, "^C", 3197)                    = 2
epoll_wait(9, [], 1024, 0)              = 0
write(38, "\3", 1)                      = 1
write(14, "\223\2\246redraw\334\0\2\334\0\2\260grid_cursor_goto"..., 47) = 47
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [{events=EPOLLIN, data={u32=39, u64=39}}], 1024, 0) = 1
read(39, "^C", 3195)                    = 2
epoll_wait(9, [], 1024, 0)              = 0
write(38, "\3", 1)                      = 1
write(14, "\223\2\246redraw\334\0\2\334\0\2\260grid_cursor_goto"..., 47) = 47
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [{events=EPOLLIN, data={u32=39, u64=39}}], 1024, 0) = 1
read(39, "^C", 3193)                    = 2
epoll_wait(9, [], 1024, 0)              = 0
write(38, "\3", 1)                      = 1
write(14, "\223\2\246redraw\334\0\2\334\0\2\260grid_cursor_goto"..., 47) = 47
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [{events=EPOLLIN, data={u32=39, u64=39}}], 1024, 0) = 1
read(39, "^C", 3191)                    = 2
epoll_wait(9, [], 1024, 0)              = 0
write(38, "\3", 1)                      = 1
write(14, "\223\2\246redraw\334\0\2\334\0\2\260grid_cursor_goto"..., 47) = 47
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [], 1024, 0)              = 0
epoll_wait(9, [{events=EPOLLIN, data={u32=39, u64=39}}], 1024, 0) = 1
read(39, "^C", 3189)                    = 2
epoll_wait(9, [], 1024, 0)              = 0
write(38, "\3", 1)                      = 1
write(14, "\223\2\246redraw\334\0\2\334\0\2\260grid_cursor_goto"..., 47) = 47
epoll_wait(9, ^C[], 1024, 0)              = 0
strace: Process 1497024 detached

```

**Comment by justinmk** [comment] 2023-06-04 01:08
We have clear repro steps given above. So I've hidden redundant comments (though the hints are appreciated).

**Comment by xbreak** [comment] 2023-09-21 13:03
@ibhagwan: Is it possible to mitigate this in fzf-lua somehow? I appear to trigger this condition 100% of the time just by running FzfLua and previewing certain files (not all files exhibit this behaviour though).
```
$ strace -s 99 -ffp  1816172
... (opening preview) ...
[{events=EPOLLIN, data={u32=0, u64=0}}], 1024, -1, NULL, 8) = 1
[pid 1816172] read(0, "\33[I", 4095)    = 3
[pid 1816172] write(18, "\223\2\261nvim_ui_set_focus\221\303", 22) = 22
[pid 1816172] epoll_pwait(11, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, -1, NULL, 8) = 1
[pid 1816172] read(0, "\33OB", 4095)    = 3
[pid 1816172] write(18, "\223\2\252nvim_input\221\246<Down>", 21) = 21
[pid 1816172] epoll_pwait(11, [{events=EPOLLIN, data={u32=20, u64=20}}], 1024, -1, NULL, 8) = 1
[pid 1816172] read(20, "\223\2\246redraw\334\0\5\334\0\2\251grid_line\224\1\n \334\0\37\222\241 \315\1\202\222\241 \315\1\r\223\243\342\200\202\315\1\r\2\222\243\357\203\266\315\1\207\222\243\342\200\202\315\1\r\221\241c\221\241o\221\241n\221\241s\221\241o\221\241l\221\241e\221\241_\221\241l\221\241i"..., 65536) = 514
[pid 1816172] write(26, "\33[11;33H\33(B\33[m\33[38;2;88;110;117m\33[48;5;236m \33(B\33[m\33[38;2;88;110;117m\33[48;2;253;246;227m \342\200\202\342\200\202\33(B\33["..., 452) = 452
[pid 1816172] epoll_pwait(19, [], 1024, 0, NULL, 8) = 0
[pid 1816172] epoll_pwait(11, [{events=EPOLLIN, data={u32=20, u64=20}}], 1024, -1, NULL, 8) = 1
[pid 1816172] read(20, "\223\2\246redraw\334\0\2\334\0\30\251grid_line\224\1\4\314\270\334\0\1\223\243\342\224\200\315\1\r\n\224\1\5\315\1\0\334\0\1\222\243\342\224\202\315\1\r\224\1\6\315\1\0\334\0\1\222\243\342\224\202\315\1\r\224\1\7\315\1\0\334\0\1\222\243\342\224\202\315\1\r\224\1\10\315\1\0"..., 65536) = 426
[pid 1816172] write(26, "\33[5;185H\33(B\33[m\33[38;2;88;110;117m\33[48;2;253;246;227m\342\224\200\33[5;186H\342\224\200\33[5;187H\342\224\200\33[5;188H\342\224\200\33[5;189H\342\224\200\33"..., 420) = 420
[pid 1816172] epoll_pwait(19, [], 1024, 0, NULL, 8) = 0
[pid 1816172] epoll_pwait(11, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, -1, NULL, 8) = 1
[pid 1816172] read(0, "\33[O", 4095)    = 3
[pid 1816172] write(18, "\223\2\261nvim_ui_set_focus\221\302", 22) = 22
[pid 1816172] epoll_pwait(11, ^[[B
[{events=EPOLLIN, data={u32=0, u64=0}}], 1024, -1, NULL, 8) = 1
[pid 1816172] read(0, "\33[I", 4095)    = 3
[pid 1816172] write(18, "\223\2\261nvim_ui_set_focus\221\303", 22) = 22
[pid 1816172] epoll_pwait(11, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, -1, NULL, 8) = 1
[pid 1816172] read(0, "\33OB", 4095)    = 3
[pid 1816172] write(18, "\223\2\252nvim_input\221\246<Down>", 21) = 21
[pid 1816172] epoll_pwait(11, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, -1, NULL, 8) = 1
[pid 1816172] read(0, "\33OA", 4095)    = 3
[pid 1816172] write(18, "\223\2\252nvim_input\221\244<Up>", 19) = 19
[pid 1816172] epoll_pwait(11, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, -1, NULL, 8) = 1
[pid 1816172] read(0, "\33OA", 4095)    = 3
[pid 1816172] write(18, "\223\2\252nvim_input\221\244<Up>", 19) = 19
[pid 1816172] epoll_pwait(11, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, -1, NULL, 8) = 1
[pid 1816172] read(0, "\33[O", 4095)    = 3
[pid 1816172] write(18, "\223\2\261nvim_ui_set_focus\221\302", 22) = 22
[pid 1816172] epoll_pwait(11, 
```

**Comment by wookayin** [comment] 2023-10-12 02:54
@mattpallissard That's a great finding! I can also confirm that setting `foldexpr=0` for the terminal window prevents neovim from freezing, very *consistently*. A great repro. I also used the `cat /dev/urandom | base64` example to flood terminal outputs.

In your workaround you globally `set foldexpr&`, but it'd be even better if one can set this locally to the terminal windows: `setlocal foldexpr&` or `setlocal foldexpr=0` so that `foldexpr` can work for other buffers. Or simply `setlocal foldmethod=manual` (for the terminal buffer) also works by disabling the execution of foldexpr, hence another workaround:

```vim
  autocmd TermOpen * setlocal foldmethod=manual
```

I've made a more refined and clean version of the repro with minimal dependencies based on @mattpallissard's observation:

```lua
-- Run with: nvim --clean -u repro.lua, and hit <Ctrl-C>
vim.o.foldmethod = 'expr'
vim.o.foldexpr = 'MyFold()'

vim.cmd [[
  function! MyFold() abort
    " Do some expensive(?) computation inside foldexpr, to increase the chance of neovim freezing
    " Note: this function gets called **VERY OFTEN**, every single time terminal draws with a new character
    let i = 0 | while i <= 20 | let i += 1 | endwhile
    return 0
  endfunction
]]

vim.cmd [[ term base64 < /dev/urandom ]]
-- vim.cmd [[ setlocal foldmethod=manual ]] -- a workaround to prevent hanging (#20726)
vim.cmd [[ startinsert ]]
```

<details>
<summary>Some additional notes regarding the above repro</summary>

The following (lua function instead of vimscript foldexpr function) doesn't result in hanging. So it's probably related to vimscript execution?
```
vim.o.foldexpr = 'v:lua.MyFold()'
function _G.MyFold() return 0 end
```
</details>

With this reliable repo and playing around with gdb, it can be easily figured out that the infinite loop happens around:
- [`safe_vgetc()`](https://github.com/neovim/neovim/blob/v0.9.4/src/nvim/state.c#L62) which always returns 3 (`CTRL-C`), and
- [`s->execute(s, key)`](https://github.com/neovim/neovim/blob/v0.9.4/src/nvim/state.c) (i.e., [`terminal_execute`](https://github.com/neovim/neovim/blob/v0.9.4/src/nvim/terminal.c#L562)) always return 1 (FAIL).

**Comment by justinmk** [comment] 2023-10-12 13:24
Related? https://github.com/neovim/neovim/issues/6800

**Comment by chanha-park** [comment] 2023-11-28 05:55
I'm not sure if it's related or not, but I also have a `foldexpr` related issue. When I use a command like `yes` inside the nvim's built-in terminal, nvim just stucks.

After executing `yes` command, I cannot do anything.(none of `<ESC>`, `<C-c>`, `<C-\>`, `<C-\><C-n>` works)

Tested with minimal.lua below, with `nvim --clean -u minimal.lua`. Nvim version 0.9.4 on Linux Mint 21.

```lua
-- minimal.lua
for name, url in pairs({
    -- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
    -- some_plugin = 'https://github.com/author/plugin.nvim'
    ['nvim-treesitter'] = 'https://github.com/nvim-treesitter/nvim-treesitter',
}) do
    local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
    if vim.fn.isdirectory(install_path) == 0 then
        vim.fn.system({ 'git', 'clone', '--depth=1', url, install_path, })
    end
    vim.opt.runtimepath:append(install_path)
end

vim.opt.foldmethod = 'expr'
vim.opt.foldexpr = 'nvim_treesitter#foldexpr()'
```

**Comment by ibhagwan** [comment] 2024-04-01 06:02
May or may not be related, while attempting to debug this issue I've been using `fzf-lua` and spamming FzfLua + `<C-c>`, done enough times I would sometimes be able to hang neovim. However, doing so with `gdb` attached I am unable to get to the `got_int` loop described by both @jrahm in https://github.com/neovim/neovim/issues/20726#issuecomment-1409303471 and @wookayin in https://github.com/neovim/neovim/issues/20726#issuecomment-1758832263 but I do see the below in the gdb console every single time:
> Few examples below, each depicting a would-be hang?
```
Thread 1 "nvim" received signal SIGPIPE, Broken pipe.
0x00007fa66ba9d60f in __GI___libc_write (nbytes=4093, buf=0x557165339f40, fd=20) at ../sysdeps/unix/sysv/linux/write.c:26
26	in ../sysdeps/unix/sysv/linux/write.c

Thread 1 "nvim" received signal SIGPIPE, Broken pipe.
0x00007fa66ba9d60f in __GI___libc_write (nbytes=2174, buf=0x55716533af50, fd=20) at ../sysdeps/unix/sysv/linux/write.c:26
26	in ../sysdeps/unix/sysv/linux/write.c

Thread 1 "nvim" received signal SIGPIPE, Broken pipe.
0x00007fa66ba9d60f in __GI___libc_write (nbytes=164, buf=0x5571654bcf40, fd=21) at ../sysdeps/unix/sysv/linux/write.c:26
26	in ../sysdeps/unix/sysv/linux/write.c
```

Is it possible that somehow the combination of receing the `SIGPIPE` causes `got_int` to never get cleared and thus enter the infinite loop?

@justinmk, is it possible this issue is not related to lua code interruption or folds?

**Comment by amitlevy21** [comment] 2024-06-17 10:46
I'm having the same issue when using Neovim's builtin terminal, and pressing CTRL-C to terminate a program that runs within that terminal.
for example:
1. open terminal within neovim
2. run a waiting command such as `tail -f /dev/null`
3. press CTRL-C while being in terminal mode
4. neovim hangs

the thing is, it doesn't always happen. just from time to time

This makes terminal mode basically unusable for me

**Comment by justinmk** [comment] 2024-06-17 20:40
@amitlevy21 does it happen with `nvim --clean` ?

**Comment by amitlevy21** [comment] 2024-06-22 15:06
@justinmk it does not. how can I pinpoint the root cause of this? I tried using `:profile` (which I understand is for performance but tried nonetheless)
however, I could not find anything interesting there

**Comment by justinmk** [comment] 2024-06-24 13:50
@amitlevy21 you could narrow it to a specific plugin (`:help bisect`). Then the next step would be to see if that plugin is creating autocmds or other handlers that happen on TextChanged or similarly-frequent events.

**Comment by CertainLach** [comment] 2024-07-19 12:31
Yesterday, my neovim has freezed after <C-c>
I haven't closed it, and today I looked at it, and I saw
```
Messages: table overflow
```

After I have pressed enter in this window, for a split second I have seen the lua stack trace, where there was something containing "key", but I haven't remembered anything else distinct.
I'm not sure if it was the same error, but looks like the windows is not completely frozen at signal processing, but also evaluates some lua code?

**Comment by ibhagwan** [comment] 2024-08-11 03:19
> Yesterday, my neovim has freezed after I haven't closed it, and today I looked at it, and I saw
> 
> ```
> Messages: table overflow
> ```
> 
> After I have pressed enter in this window, for a split second I have seen the lua stack trace, where there was something containing "key", but I haven't remembered anything else distinct. I'm not sure if it was the same error, but looks like the windows is not completely frozen at signal processing, but also evaluates some lua code?
> 
> After a couple of hours, the same window unfreezed again, this time I was able to see the error message:
> 
> ```
> Error executing vim.on_key Lua callback: vim/_editor.lua:0: Error executing 'on_key' with ns_ids '17'
>     Messages: table overflow
> stack traceback:
>     [C]: in function 'error'
>     vim/_editor.lua: in function <vim/_editor.lua:0>
> ```
> 
> It is still consuming 100% of one core.

Great finds @CertainLach, this confirms my finding from the OP, the log generated by the lua debug hook shows it’s calling `on_key` in a loop.

**Comment by justinmk** [comment] 2024-08-11 14:19
> it’s calling `on_key` in a loop.

Do you have a config or plugin that is setting an `on_key` callback?

**Comment by ibhagwan** [comment] 2024-08-11 14:33
> > it’s calling `on_key` in a loop.
> 
> Do you have a config or plugin that is setting an `on_key` callback?

Nope, reading the code the lua `on_key` seems to be called (from the C code) regardless?

**Comment by CertainLach** [comment] 2024-08-11 14:37
> Do you have a config or plugin that is setting an on_key callback?

The problem is not the contents of on_key callback, the problem is that this callback is being called indefinitely after C-c is pressed sometimes.

**Comment by ibhagwan** [comment] 2024-08-15 03:43
@justinmk, I'm trying to debug this issue, would appreciate your insight in the matter.

As alredy noted in this thread, it seems that the issue stems from an endless loop inside the terminal's `state_enter` due to `got_int=true` which subsequently never gets cleared causing `safe_vgetc` to always return `3`.

Having explored the code a bit it is now my understanding that `got_int` should never be set while in terminal mode due to the below variables assignments in `terminal_enter` :
```c
  State = MODE_TERMINAL;           // 128
  mapped_ctrl_c |= MODE_TERMINAL;  // Always map CTRL-C to avoid interrupt.
```

Which then causes `os_inchar` to set `ctrl_c_interrupts=false`:
```c
  if ((mapped_ctrl_c | curbuf->b_mapped_ctrl_c) & get_real_state()) {
    ctrl_c_interrupts = false;
  }
```

Which then prevents `proces_ctrl_c` from ever setting `got_int`:
```c
static void process_ctrl_c(void)
{
  if (!ctrl_c_interrupts) {
    return;
  }
 ...
}
```

I manged to get neovim to freeze and attach a debugger, this the state while inside the endless loop:
![image](https://github.com/user-attachments/assets/2c5fe07a-9e7f-4984-9ef6-6563b1bceec4)

As you can see above both `State` and `mapped_ctrl_c` equal `128` (i.e. we're in a "terminal state"), the fact my debugger is stopped inside `terminal_execute` means we're still inside the `state_enter` loop called by `terminal_enter`.

My questions / thoughts:
 - Given `got_int=true` is set inside `process_ctrl_c`, any idea how could it be set while in terminal mode? Is there any other place that can set `got_int=true` while inside a terminal?
 - To trigger this bug I open a term and quickly spam `<C-c>`  - is it possible `got_int=true` is set right before the terminal process is open (still in "normal" mode) and then carries over to the terminal mode causing the infinite loop?
 - If the above is true it could explain opening a term and spamming `<C-c>` quickly to trigger the bug but I'm not sure if this can explain other issues described in this thread where this happens randomly long after the term is open while a lot of data is written to the term.

As an experiment I've added `got_int =false;` right below this block of code and I haven't been able to reproduce the bug but I'm still unsure if this can explain other issues in this thread.
https://github.com/neovim/neovim/blob/615f7bbff06c0585aacce542fac4bc823070ebee/src/nvim/terminal.c#L530-L534

**Comment by zeertzjq** [comment] 2024-08-15 04:35
The are some other places that can set `got_int`. For example, the hang can happen when calling `interrupt()` in Terminal mode too:
```
autocmd TermEnter * call timer_start(500, {-> interrupt()})
terminal
startinsert
```
So `got_int` needs to be cleared more often.

**Comment by ibhagwan** [comment] 2024-08-15 04:58
> So got_int needs to be cleared more often like in other modes. Maybe like this?

I thought about clearing `got_int` inside `terminal_execute` but wasn’t sure if was an overkill or other side effects I wasn’t aware of.

If your patch above is acceptable that would most likely fix this issue for all cases where `got_int` is inadvertently set inside terminal mode.

Let me know if you’d like me to submit a PR or if you’d rather commit this yourself?

**Comment by ibhagwan** [comment] 2024-08-15 05:23
@zeertzjq, https://github.com/neovim/neovim/pull/30056.

**Closed** 2024-08-19 22:23 UTC
Labels: bug, job-control, terminal, input
