### ISSUE TITLE
Seg Fault from opening nvim with "nvim ." on nvim nightly

### ISSUE THREAD

**Issue by Elaborate1100** [neovim/neovim#20338] opened 2022-09-25 05:33 UTC
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1162-g2a3cb0893-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 20.04.5

### Terminal name/version

xterm

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

note: 
* unable to replicate with nvim --clean for some reason (don't know if it is a problem with my config, which either way shouldn't cause a seg fault anyway)
* this was done in a gitpod workspace, so it may just be that

attempted replication:
install nvim with homebrew (nightly)
copy dotfiles for nvim from here to ~/.config/nvim: https://github.com/Elaborate1100/.dotfiles/tree/8c9ac0174a1c55dc458b0f0dec58178070a36515/.config/nvim
run "nvim ." in the terminal

### Expected behavior

nvim should execute with a file tree (netrw)

![Screenshot 2022-09-24 23 29 35](https://user-images.githubusercontent.com/86505727/192129745-14daa58a-a4dc-4838-aa3d-550b517e1207.png)

### Actual behavior

seg faults and exits

![Screenshot 2022-09-24 23 27 37](https://user-images.githubusercontent.com/86505727/192129734-914ad4ac-a326-4d1c-9e90-5f79caf2430d.png)

**Comment by zeertzjq** [comment] 2022-09-25 05:45
Duplicate of #20316

**Closed by zeertzjq** 2022-09-25 05:45 UTC
Labels: bug
