### ISSUE TITLE
Setting backupdir='$HOME/.config/nvim/cache' creates directory literally named $HOME

### ISSUE THREAD

**Issue by duynguyendu** [neovim/neovim#15777] opened 2021-09-24 13:59 UTC
### Neovim version (nvim -v)

NVIM v0.6.0-dev+331-gaba397991

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty/0.23.1

### $TERM environment variable

screen

### Installation

AUR

### How to reproduce the issue

Set these config using lua
`vim.opt.backupdir = '$HOME/.config/nvim/cache
vim.opt.directory = '$HOME/.config/nvim/tmp'`

### Expected behavior

Neovim will recognize and use home directory

### Actual behavior

A new folder literally named $HOME is created in current working directory

**Comment by seandewar** [comment] 2021-09-24 14:52
Yeah, I think this should work like `:h :set_env`.
For now, you can use `vim.opt.backupdir = os.getenv("HOME") .. "/.config/nvim/cache"`.

**Comment by gpanders** [comment] 2021-09-24 15:35
Closing as a duplicate of #15720.

**Closed** 2021-09-24 15:35 UTC
Labels: bug, lua
