### ISSUE TITLE
Latest neovim not working with ultisnips.

### ISSUE THREAD

**Issue by paulhybryant** [neovim/neovim#5373] opened 2016-09-22 06:46 UTC
- `nvim --version`: 
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160922-15632-1zpbhf/neovim-0.1.5/build/config -I/tmp/neovim-20160922-15632-1zpbhf/neovim-0.1.5/src -I/tmp/neovim-20160922-15632-1zpbhf/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160922-15632-1zpbhf/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160922-15632-1zpbhf/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160922-15632-1zpbhf/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160922-15632-1zpbhf/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160922-15632-1zpbhf/neovim-0.1.5/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim-20160922-15632-1zpbhf/neovim-0.1.5/build/src/nvim/auto -I/tmp/neovim-20160922-15632-1zpbhf/neovim-0.1.5/build/include
Compiled by yuhuang@yuhuang-macbookair.roam.corp.google.com

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.5/share/nvim"

- Vim (version: ) behaves differently?
- Operating system/version: OSX
- Terminal name/version: iTerm2
- `$TERM`: screen-256color

Error when using ultisnips.
Commenting out ultisnips nvim runs fine.

pip show neovim
---
Metadata-Version: 2.0
Name: neovim
Version: 0.1.9
Summary: Python client to neovim
Home-page: http://github.com/neovim/python-client
Author: Thiago de Arruda
Author-email: tpadilha84@gmail.com
Installer: pip
License: Apache
Location: /usr/local/lib/python2.7/site-packages
Requires: trollius, msgpack-python, greenlet
Classifiers:

YouCompleteMe is enabled and works fine.

Some errors:
line   92:
E121: Undefined variable: a:specs
E15: Invalid expression: a:specs
line  117:
E121: Undefined variable: plugins
E116: Invalid arguments for function add
line  118:
E48: Not allowed in sandbox: endfunction
line  122:
E48: Not allowed in sandbox: function! s:GetManifestPath() abort
line  126:
E133: :return not inside a function
line  137:
E48: Not allowed in sandbox

**Comment by Shougo** [comment] 2016-09-22 06:58
neovim 0.1.5 is not the latest version.
You should test neovim HEAD.

**Comment by paulhybryant** [comment] 2016-09-22 07:25
I can confirm the same issue happens with HEAD

**Comment by Shougo** [comment] 2016-09-22 07:26
Hm.  OK.  I will test it.
Please upload the minimal init.vim less than 50 lines and reproduce ways from neovim starting.

**Comment by justinmk** [comment] 2016-09-22 08:07
Why is it running in sandbox?

**Comment by paulhybryant** [comment] 2016-09-22 10:25
Minimal init.vim:

" vim: ft=vim sw=2 ts=2 sts=2 et tw=80 fdl=0 fdm=marker nospell
let s:bundle_base_path = expand('~/.config/nvim/bundle/')
execute 'set runtimepath+=' . s:bundle_base_path . 'neobundle.vim/'
call neobundle#begin(s:bundle_base_path)
NeoBundleFetch 'Shougo/neobundle.vim'                                         " Install NeoBundle itself
" NeoBundle 'SirVer/ultisnips', {'disabled' : !has('python')}                   " Define and insert snippets
call neobundle#end()
NeoBundleCheck

start nvim

It will run fine.

Uncomment the line with ultisnips, and we start to get errors.

**Comment by Shougo** [comment] 2016-09-22 10:30
OK.  I will check it.

**Comment by Eisfreak7** [comment] 2016-09-23 14:38
I have the same problem.

**Comment by Shougo** [comment] 2016-09-23 20:00
@paulhybryant I get the problem.  Your neobundle is old.
It is neobundle bug and it is fixed in June.

@Eisfreak7 Do you use neobundle as plugin manager?

**Closed** 2016-09-23 20:21 UTC

**Comment by Eisfreak7** [comment] 2016-09-24 12:56
No, I use vim-plug.
However, I can't reproduce the problem anymore. I don't know what it was, but it seems to have "fixed itself".

**Comment by paulhybryant** [comment] 2016-09-25 08:27
@Shougo 
My neobundle is the latest version. And I still run into the same issue.

**Comment by Shougo** [comment] 2016-09-26 12:38
@paulhybryant I have fixed the problem.
Please update neobundle again.

**Comment by paulhybryant** [comment] 2016-09-27 12:53
@Shougo Thank you. The error is fixed after the update.
