### ISSUE TITLE
bufwinid changes after CursorMoved

### ISSUE THREAD

**Issue by champignoom** [neovim/neovim#23710] opened 2023-05-22 05:33 UTC
### Problem

The window number of buffer changes after CursorMoved.

### Steps to reproduce

nvim --clean
:lua vim.api.nvim_create_autocmd({"cursormoved"}, {pattern="*", callback=function(ev)print(ev.buf, vim.fn.bufwinid(ev.buf))end})
:h
(now it prints "1 1001")
:echo bufwinid(1)
(now it prints "1000")

### Expected behavior

Both bufwinid should give the same result.

### Neovim version (nvim -v)

NVIM v0.9.0

### Vim (not Nvim) behaves the same?

irrelevant

### Operating system/version

macOS 13.2.1

### Terminal name/version

iTerm2 build 3.4.19

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment] 2023-05-22 05:53
When the `CursorMoved` autocommand is triggered, the buffer in the top window is still the same as the bottom one.

This does indicate an incompatibility with Vim though.

**Comment by champignoom** [comment] 2023-05-22 05:59
Then how can one refer to the bottom buffer?

**Comment by zeertzjq** [comment] 2023-05-22 06:34
Duplicate of #11878

**Closed by zeertzjq** 2023-05-22 06:34 UTC
Labels: bug, compatibility, events
