### ISSUE TITLE
Unable to remap default modifier + scrollwheel behaviour

### ISSUE THREAD

**Issue by prurigro** [neovim/neovim#14647] opened 2021-05-26 18:55 UTC
I took a look through the existing issues and wasn't able to find anything, though the list is long so apologies in advance if this is a duplicate. I thought I actually reported this back in 2016 or so but don't see any issues (open or closed) that I've been involved in so I must be remembering wrong.

- `nvim --version`: v0.4.4
- Operating system/version: Arch Linux
- Terminal name/version: xfce4-terminal, gnome-terminal, urxvt, xterm
- `$TERM`: xterm-256color, rxvt-unicode-256color, tmux-256color

[ ] `vim -u DEFAULTS` (version: ) 8.2.2859

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set nowrap
:set mouse=a
:nnoremap <C-ScrollWheelUp> 4zl
:nnoremap <C-ScrollWheelDown> 4zh
```

### Actual behaviour

Holding ctrl and scrolling up or down on a line that extends beyond the right side of the terminal both scrolls left or right and quickly up or down

### Expected behaviour

The original behaviour (scrolling quickly up or down) should have been unmapped and the content should have only scrolled left or right like in vim.

Thanks for your time!

**Comment by prurigro** [comment] 2022-01-04 02:17
Just updating that this bug is still happening on 0.6.1

**Comment by zeertzjq** [comment] 2022-01-26 00:48
It seems continuous scrolling is recognized as multiclick, which I'm not sure is a bug or not. A workaround is to define four mappings instead of one:
```vim
:nnoremap <C-ScrollWheelUp> 4zl
:nnoremap <C-ScrollWheelDown> 4zh
:nnoremap <C-2-ScrollWheelUp> 4zl
:nnoremap <C-2-ScrollWheelDown> 4zh
:nnoremap <C-3-ScrollWheelUp> 4zl
:nnoremap <C-3-ScrollWheelDown> 4zh
:nnoremap <C-4-ScrollWheelUp> 4zl
:nnoremap <C-4-ScrollWheelDown> 4zh
```

**Comment by zeertzjq** [comment] 2022-01-26 00:57
Duplicate of #6211

**Closed by zeertzjq** 2022-01-26 00:57 UTC
Labels: bug, input, status:has-workaround, mouse
