### ISSUE TITLE
segfault with multiple buffers open + control-p usage

### ISSUE THREAD

**Issue by stefanpenner** [neovim/neovim#3070] opened 2015-07-21 16:04 UTC
Although there exists at-least one other segfault report. The core dump appears different:

```
➜  ~ gdb -q -n -ex bt -batch nvim /cores/core.50018
Reading symbols for shared libraries ..... done
Reading symbols for shared libraries . done
Reading symbols for shared libraries ................................................ done
#0  0x00000001025b1f32 in utf_head_off ()
```

[crash report](https://gist.github.com/stefanpenner/307caaacb897c46d29da)

---

What I was doing:

multiple buffers open, including a terminal buffer then sometimes, when use [ctrlp](https://github.com/kien/ctrlp.vim) i get this failure.

**Comment by justinmk** [comment] 2015-07-21 16:30
What's the output of `:version`? A commit was pushed to master in the last 24 hours related to segfaults.

**Comment by stefanpenner** [comment] 2015-07-21 16:32
oops good call:

```
NVIM 0.0.0-alpha+201507112238 (compiled Jul 12 2015 18:23:47)
Commit: c80ebfff82d539d44815b1d36709ba573e4e38e8
```

Which is clearly older then last night, let me upgrade. If the segfault doesn't happen in the first hour or two of use. I'll circle back and close this issue.

**Comment by stefanpenner** [comment] 2015-07-21 16:47
oh oh, re-building via brew has left me with:

```
make[4]: *** [all] Error 2
make[3]: *** [build/src/msgpack-stamp/msgpack-build] Error 2
make[2]: *** [CMakeFiles/msgpack.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2
```

going to investigate further, if others have a recommendation that would be appreciated.

**Comment by justinmk** [comment] 2015-07-21 19:59
@stefanpenner  The build error may be due to https://github.com/neovim/neovim/issues/3071

**Comment by stefanpenner** [comment] 2015-07-21 20:15
superficial comparison suggests it may be different. I have opened a new issue: https://github.com/neovim/neovim/issues/3073

**Comment by justinmk** [comment] 2015-08-17 07:17
This is very similar to https://github.com/neovim/neovim/issues/3150

**Comment by tarruda** [comment] 2015-09-08 16:36
@justinmk I don't think it's the same, the crash happens at a different place

@stefan991 I want to reproduce this locally, which nvimrc did you use? Was it [this one](https://github.com/stefanpenner/dotfiles/blob/master/.nvimrc)? Also, could you give more hints about the state of the editor when this happens? Eg: how many buffers/terminals/tabs open, steps, etc. If you could record a video it would be perfect.

**Comment by justinmk** [comment] 2015-10-01 06:48
We don't have anything to work with here, so assume it was fixed by https://github.com/neovim/neovim/pull/3309 . Please report with the requested details if this is still an issue.

**Comment by stefanpenner** [comment] 2015-10-01 07:05
I'm still having this issue with latest. I'm about to head to sleep, but will provide more useful info in the AM.

**Comment by stefanpenner** [comment] 2015-10-08 18:40
just build latest, and can no longer reproduce. :+1:

**Closed** 2015-10-08 18:40 UTC
Labels: bug
