### ISSUE TITLE
Highlighting group affects statusline's width calculations

### ISSUE THREAD

**Issue by mkoskar** [neovim/neovim#7980] opened 2018-02-07 12:40 UTC
- `nvim --version`: `NVIM v0.2.3-dev` 538361955
- Vim (version: `8.0 1-1436`) behaves differently? yes

### Steps to reproduce using `nvim -u NORC`

```
$ vim/nvim -u NORC -c 'set laststatus=2 statusline=%(=%#ErrorMsg#%(%m%)%*%)%n'
```

### Actual behaviour

Nvim's statusline is `=1`.

### Expected behaviour

Nvim's statusline is `1`.

**Comment by justinmk** [comment] 2018-02-08 00:07
Wasn't there a Vim patch for this? Can you see if the problem exists in an older version of Vim 8?

**Comment by sunbenxin** [comment] 2018-02-08 06:29
why not $ vim/nvim -u NORC -c 'set laststatus=2 statusline=%(**%**=%#ErrorMsg#%(%m%)%*%)%n'

**Comment by sunbenxin** [comment] 2018-02-08 06:38
change 'set laststatus=2 statusline=%(=%#ErrorMsg#%(%m%)%*%)%n' 
to          'set laststatus=2 statusline=%(%=%#ErrorMsg#%(%m%)%*%)%n'
work fine~

**Comment by mkoskar** [comment] 2018-02-08 14:16
@sunbenxin `=` was just an example, I could have used `<space>` or something else. I wasn't trying to do `%=` which is a separation point. I.e., the `=` should be displayed only when `%m` is non empty so e.g., after doing `:set mod` it should look like `=[+]1`.

**Comment by mkoskar** [comment] 2018-02-08 14:24
@justinmk Good call! I was able to see the problem present in `1176` but fixed in `1272`.

**Comment by mkoskar** [comment] 2018-02-08 14:38
So it seems (at least by the commit message) this could be it https://github.com/vim/vim/commit/6b89dbb55f84c485310c8c9e094dbafe3ecbace6.

**Comment by jamessan** [comment] 2018-02-08 14:39
Looks like it 8.0.1164, 8.0.1208, and 8.0.1220 are related.

**Comment by glacambre** [comment] 2021-06-05 18:29
Can't reproduce on master, none of the three patches mentionned by jamessan are present of in the list of patches that need to be ported, there's a very high probability that this has been fixed. Closing this issue :).

**Closed by glacambre** 2021-06-05 18:29 UTC
Labels: 0.kind: bug-vim
