### ISSUE TITLE
A bug for CurorHoldI When use rpc channel

### ISSUE THREAD

**Issue by taigacute** [neovim/neovim#9647] opened 2019-02-25 11:54 UTC
- `nvim --version`:0.3.4
- Vim (version: ) behaves differently? N/A
- Operating system/version: mac os 10.13.6 
- Terminal name/version: iterm2
- `$TERM`:xterm-256colors

### Steps to reproduce using `nvim -u NORC`

N/A

### Actual behaviour
[problem](https://github.com/neoclide/coc.nvim/issues/414)
It's bug of neovim, when there is a job using `rpc`, the CursorHoldI event not triggered as expected.
### Expected behaviour
fixed

**Comment by justinmk** [comment] 2019-02-25 18:27
Thanks for reporting. We could use help investigating/debugging this.

Duplicate of #3757

**Closed by justinmk** 2019-02-25 18:27 UTC
