### ISSUE TITLE
multi-repeat hang neovim

### ISSUE THREAD

**Issue by jlneder** [neovim/neovim#2155] opened 2015-03-15 11:40 UTC
using :g or :v hangs neovim. Vim 7.4.617 handles it fine.

**Comment by tarruda** [comment] 2015-03-15 11:49
can you provide detailed steps on how to reproduce the problem?

**Comment by jlneder** [comment] 2015-03-15 20:57
correction, it doesn't hang, it just take too long with relatively long files.
Example: https://gist.github.com/jlneder/ed6193434a5c85edff37
Opening that file and doing ":v/org/d" takes too long. In vim is instantaneous.

**Comment by tarruda** [comment] 2015-03-16 18:09
Confirmed, this happens when `clipboard=unnamed` because for each execution of `d` there's an associated spawn of `xsel`.

**Comment by tarruda** [comment] 2015-03-16 23:59
@jlneder this patch is a bit hacky but should work around the issue:

```diff
diff --git a/src/nvim/ex_cmds.c b/src/nvim/ex_cmds.c
index fdbb613..c3bf5f9 100644
--- a/src/nvim/ex_cmds.c
+++ b/src/nvim/ex_cmds.c
@@ -4513,6 +4513,9 @@ void global_exe(char_u *cmd)
   global_need_beginline = FALSE;
   global_busy = 1;
   old_lcount = curbuf->b_ml.ml_line_count;
+  int save_cb_flags = cb_flags;
+
+  cb_flags = 0;
   while (!got_int && (lnum = ml_firstmarked()) != 0 && global_busy == 1) {
     curwin->w_cursor.lnum = lnum;
     curwin->w_cursor.col = 0;
@@ -4522,6 +4525,7 @@ void global_exe(char_u *cmd)
       do_cmdline(cmd, NULL, NULL, DOCMD_NOWAIT);
     os_breakcheck();
   }
+  cb_flags = save_cb_flags;

   global_busy = 0;
   if (global_need_beginline)
```

Can you try it before I open a PR? The only catch is that it will temporarily ignore `clipboard` while the global command is executing, but clipboard isn't very useful in this case anyway.

**Comment by justinmk** [comment] 2015-03-17 00:15
@tarruda  Even Vim had this problem until [7.4.396](https://code.google.com/p/vim/source/detail?r=v7-4-396). They added a `start_global_changes()` function which does something similar to your patch. 

Note that patch 396 suggests we should also make this change for `ex_listdo()` (which is not related to `global_exe`).

**Comment by tarruda** [comment] 2015-03-17 00:30
@justinmk nice to know there's a corresponding patch we can use for this. The above patch does not handle `:global/{pattern}/d +` which explicitly uses the clipboard register, so a `start_global_changes` function(which sets yet another global variable :cry: ) may be better because it can be handled in ops.c even when the clipboard register is used directly.

**Comment by chrisbra** [comment] 2015-03-17 07:44
Am 2015-03-17 01:15, schrieb Justin M. Keyes:
> @tarruda [1] Even Vim had this problem until 7.4.396 [2]. They added a
> start_global_changes() function which does something similar to your
> patch.

This was only a problem on Windows and only if the clipboard option was 
set to unnamedplus.
On Unix it worked well even before that patch.

Cheers,
Christian

**Comment by tarruda** [comment] 2015-03-17 11:03
@chrisbra this doesn't change the fact there's a lot of unnecessary copying to the clipboard. On unix it worked well because sending text to the clipboard is fast when you already have a connection to the x server.

**Comment by justinmk** [comment] 2015-08-31 04:36
Closed by https://github.com/neovim/neovim/pull/2809

**Closed by justinmk** 2015-08-31 04:36 UTC
Labels: bug, clipboard, performance
