### ISSUE TITLE
win32yank 'Unable to translate ....` error on WSL

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7021] opened 2017-07-14 16:07 UTC
If cwd is a WSL-specific path (i.e. not `/mnt/X/...`), attempting to run a Windows binary (such as win32yank.exe, the clipboard provider under WSL) throws the following to stderr:

`Unable to translate current working directory. Using C:\Users\USER`

This error is generated by the WSL subsystem when trying to map the current working directory to a win32-compatible value to execute the target application (again, here win32yank.exe) under.

Some relevant tickets:
* https://github.com/equalsraf/win32yank/issues/3
* https://github.com/Microsoft/BashOnWindows/issues/2011

Anyway, nvim should not launch win32yank.exe directly, instead it should use a wrapper script to swallow errors. 

Here's a generic wrapper script that works with any WSL binary (including win32yank.exe):

```
$ cat wslnoerr.sh
#!/bin/bash
app=$1
shift
$app "$@" 2> >(sed -e '1h;2,$H;$!d;g' -r -e 's/Unable to translate[^\n]*\n//' 1>&2)
```

nvim would then execute `wslnoerr.sh win32yank.exe ...` instead of `win32yank.exe ...`

**Comment by ZyX-I** [comment] 2017-07-14 23:22
I do not like the idea of filtering such error out, it should be possible to instead create a script which will `cd` to the directory which is known to be translatable should the current one be not translatable. Specifically for `win32yank` it may be logical just to always do `cd` because this utility should not need actual Neovim working directory.

**Comment by bfredl** [comment] 2017-07-15 06:25
Under neither circumstance should there be need to create a shell script, our job control handles both `pwd` and "filter stderr" just fine.

**Comment by mqudsi** [comment] 2017-07-15 16:37
@bfredl awesome. I've obviously not dug extensively into the neovim build system or code, I'm just reporting how WSL works.

fwiw, adding `pwd` to the `g:clipboard.copy.*` command fails miserably :)

**Comment by justinmk** [comment] 2017-07-15 16:57
@mqudsi Does this issue happen for copy _and_ paste, or _only_ paste? If it happens for both, can you check whether https://github.com/neovim/neovim/pull/7033 fixes the issue for copy (`"+y`)

**Comment by mqudsi** [comment] 2017-07-15 17:10
I'll test it now; it should happen on both copy and paste because that error comes from the WSL subsystem. However, on copy I don't think neovim shows the return value of the copy command, so it's possible that it happens but the user doesn't see it.

**Comment by bfredl** [comment] 2017-07-15 17:14
It is better to use `pwd` explicitly than `cd ...;`, but then one currently needs to use jobstart() | jobwait()` instead of systemlist. (Or course, we could add a form to `systemlist` replacing the _ad-hoc_ boolean flag with an options dictionary)

**Comment by mqudsi** [comment] 2017-07-15 17:27
@justinmk I made a PR against your branch, the uname text should be matched against "Microsoft", not "Windows".

However, in all cases this does not solve the problem.

Question: isn't a cleaner solution to paste only the stdout output of the command?

```
mqudsi@ZBook ~/r/neovim> win32yank.exe -o
Unable to translate current working directory. Using C:\Users\Mahmoud
Linux ZBook 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
mqudsi@ZBook ~/r/neovim> win32yank.exe -o 2>/dev/null
Linux ZBook 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
mqudsi@ZBook ~/r/neovim>
```

**Comment by mqudsi** [comment] 2017-07-15 17:30
I imagine the correct fix would be to `cd` to a different directory *and* send stderr output to `:messages` and only paste stdout to the buffer; it makes no sense intuitively to include the stderr output in the paste contents no matter what provider/circumstances.

**Comment by bfredl** [comment] 2017-07-15 18:05
Yep, seems a bug/design flaw with `systemlist()` if it mixes stderr in, or at least inconsistent with documentation: it mentions output will be returned, but not stderr. Could also be fixed with `options` argument.

**Comment by justinmk** [comment] 2017-07-15 18:43
> I imagine the correct fix would be to cd to a different directory and send stderr output to :messages and only paste stdout to the buffer; it makes no sense intuitively to include the stderr output in the paste contents no matter what provider/circumstances.

@mqudsi could you try https://github.com/neovim/neovim/pull/6684 ?

**Comment by mqudsi** [comment] 2017-07-15 21:19
Still broken in `NVIM v0.2.1-558-g4dee942` which should contain that fix.

**Comment by justinmk** [comment] 2017-07-15 21:33
What's still broken? https://github.com/neovim/neovim/pull/6684 only affects yank (copy).

**Comment by mqudsi** [comment] 2017-07-15 21:34
Oh, nevermind then. As I mentioned above, no issues with WSL copy (because stderr output isn't shown anywhere, anyway). Paste is still broken, but I guess that's to be expected.

**Comment by oblitum** [comment] 2017-08-19 21:46
Hey @mqudsi, just wanted to share that your script doesn't work for me, it doesn't remove that string, I'm currently fixing it by just redirecting `stderr` to `/dev/null`:

```bash
~ ❯❯❯ cat /bin/win32yank                                                                                                                                                                                                             windows ✱
#!/bin/bash
/mnt/c/Users/username/Documents/WSL-Terminal/bin/win32yank.exe "$@" 2>/dev/null
```

If you have any idea why it's not working I'd be glad to know.

**Comment by mqudsi** [comment] 2017-08-20 14:21
Oh gosh, I really can't remember the details of that script.

I'm just using a generic `noerr` prefix for my copy/paste commands, where `noerr` is the following:

```bash
#!/bin/bash
app=$1
shift
$app "$@" 2> /dev/null
```

**Comment by mqudsi** [comment] 2017-09-16 19:15
Unfortunately `f_systemlist` in `eval.c` uses the same calls as literally everything else that interacts with external processes, going first to `get_system_output_as_rettv` and ultimately ending up in `do_os_system` where both the stdout and stderr streams are munged into a single buffer (via rstream) without any interface for changing that behavior.

I highly doubt we want to prevent stderr coalescing everywhere, so it would be necessary to add either a second interface that stores stderr as a separate `typval_T` or just add a parameter to ignore stderr altogether to that call chain.

**Comment by bfredl** [comment] 2017-09-16 19:19
>  just add a parameter to ignore stderr altogether to that call chain.

Rather than "ignoring" stderr, the proper alternative (to "both streams joined") behavior should be to collect stdout and stderr separately.

**Comment by mqudsi** [comment] 2017-09-16 19:21
> Rather than "ignoring" stderr, the proper alternative (to "both streams joined") behavior controlled by) the parameter hould be to collect stdout and stderr separately

@bfredl That's exactly what the first suggestion in my comment was: 

> so it would be necessary to add either a second interface that stores stderr as a separate typval_T

**Comment by bfredl** [comment] 2017-09-16 19:23
There is no need for a "second" interface for that. Just preserve the old behavior if the stderr return parameter is NULL.

**Comment by mqudsi** [comment] 2017-09-16 19:24
I wasn't sure if the interface was supposed to remain stable for any reason or if we could add a parameter for stderr.

**Comment by bfredl** [comment] 2017-09-16 19:34
The _internal_ interface `do_os_system` and similar could be changed with no problem, but how to fix the _public_ interface `systemlist()` I'm not so sure. It already has a bool parameter to toggle between the correct and the vim compatible behavior, adding yet another flag `systemlist(cmd, input, 1, 1)` would be a bit messy, at that point we typically prefer to add an `options` dict form.

**Comment by mqudsi** [comment] 2017-09-16 19:39
Is neovim's custom overload of `systemlist` stable (i.e. can we drop that one)?

**Comment by bfredl** [comment] 2017-09-16 19:45
As stable as we want it to be. I also thought of `systemlist(cmd, input, 2)` but that's just horrible... 

An alternative is to use `jobstart()` + 'jobwait()`. The channels PR will allow
```
let dict = {'stdout_buffered': v:true, 'stderr_buffered': v:true`}
let job = jobstart(cmd, dict)
call chansend(job, data)
call jobwait(job)
" now dict has dict.stdout, dict.stderr
```
maybe we could make that slightly more comfortable, rather that making `systemlist()` more complicated.

**Comment by bfredl** [comment] 2017-09-17 17:28
The simplest might just to include a function in the runtime which does the above, and returns status+stdout+stderr, plus error handling.

**Comment by justinmk** [comment] 2017-09-17 17:54
I don't think the sample you wrote above is that painful. Let's wait on the sugar.

**Comment by bfredl** [comment] 2017-09-17 18:10
It looks un-painful because it ignores any hint of error handling, which the helper function also would do.

**Comment by 3N4N** [comment] 2023-03-22 15:00
Unrelated, but I want to leave it here in case it's useful for some.

I was using `xclip` in Linux, `win32yank` in Windows and WSL, `xclip` in ssh machine if it's installed.  It was a hassle.  Copy-paste shouldn't be a hassle.

Now I'm using [OSC52][1] for copying and Ctrl-Shift-V for pasting.  It doesn't matter what OS I'm on or if I'm working over SSH.  My terminal just needs to support OSC52 and that's it.  Freedom from `xclip`s and `xsel`s, `win32yank`s and `clip`s.  Maybe users having problem with clipboard would wanna consider this.

P.S.  You can use [OSC52 outside nvim][2], too.

[1]: https://github.com/ojroques/nvim-osc52
[2]: https://github.com/chromium/hterm/blob/master/etc/osc52.sh

**Comment by justinmk** [comment] 2023-03-23 11:39
Builtin OSC events discussed in: https://github.com/neovim/neovim/issues/4413

**Comment by 3N4N** [comment] 2023-05-13 06:44
This may have been fixed.  I'm not too sure I understand what the actual problem is, but the repro described in [a comment above][1] is not reproducible anymore.

The original repro was:
```
mqudsi@ZBook ~/r/neovim> win32yank.exe -o
Unable to translate current working directory. Using C:\Users\Mahmoud
Linux ZBook 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
mqudsi@ZBook ~/r/neovim> win32yank.exe -o 2>/dev/null
Linux ZBook 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
mqudsi@ZBook ~/r/neovim>
```

But in my system I get:
```
enan@DESKTOP-5F09VFS:~
$ echo 'foo' | win32yank.exe -i
enan@DESKTOP-5F09VFS:~
$ win32yank.exe -o
foo
```

My system specs are:
```
Neovim: NVIM v0.9.0-dev-1252+g5726f33e8caa
Terminal: Windows Terminal v1.18.1241.0
Shell: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
OS: Windows 11 Pro Version 22H2 Build 22621.1702
WSL: Ubuntu 20.04.6
```

The version of win32yank neovim ships has been bumped recently, which may be how this issue got fixed (assuming it was only with win32yank that this issue appeared, not all native-Windows binaries).

[1]: https://github.com/neovim/neovim/issues/7021#issuecomment-315549423

**Closed by 3N4N** 2023-05-13 06:44 UTC
Labels: platform:windows, job-control, clipboard
