### ISSUE TITLE
Invalid enums on window creation

### ISSUE THREAD

**Issue by Black-Sirius69** [neovim/neovim#19601] opened 2022-08-01 07:04 UTC
### Neovim version (nvim -v)

NVIM v0.8.0-dev-751-g8952def50

### Vim (not Nvim) behaves the same?

I do not have vim

### Operating system/version

Fedora 36 workstation

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

I do not know why I am getting this bug

### Expected behavior

I expect it to create the ui window/buffers. Currently I am trying it with nvim-dap and it gives me errors

### Actual behavior

Whenever trying to open dapui or dap repl I get the following errors. This is not just related to nvim-dap tho. I am getting it with other plugins like telescope, packer to name a few.
Here is a screenshot:
![image](https://user-images.githubusercontent.com/71623796/182091786-c4beffbf-331c-42d3-b3fc-c8dca1e6b2ec.png)

**Comment by zeertzjq** [comment] 2022-08-01 07:12
Duplicate of #19458

**Closed by zeertzjq** 2022-08-01 07:12 UTC
Labels: bug
