### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by datanoise** [neovim/neovim#21708] opened 2023-01-09 16:38 UTC
### Describe the bug

Crash with the following message:

```
Assertion failed: ((size_t)(buf->read_ptr - buf->write_ptr) == buf->size), function rbuffer_consumed_compact, file rbuffer.c, line 168
```

### Steps to reproduce

n/a

### Expected behavior

n/a

### Neovim version (nvim -v)

NVIM v0.9.0-dev-642+g50f03773f

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 16.2

### Terminal name/version

iTerm

### $TERM environment variable

xterm-color256

### Installation

n/a

**Comment by lewis6991** [comment] 2023-01-09 16:40
Duplicate of #21299

**Closed by lewis6991** 2023-01-09 16:40 UTC
Labels: bug
