### ISSUE TITLE
OSCYank broken after TUI as external process

### ISSUE THREAD

**Issue by hjanuschka** [neovim/neovim#21636] opened 2023-01-03 19:36 UTC
### Neovim version (nvim -v)

5eed3e741b39a7e52888b0400ba63a2ea70f4dac

### Vim (not Nvim) behaves the same?

no

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

xterm

### Installation

source

### How to reproduce the issue

git checkout master
make install
add the plugin: https://github.com/ojroques/vim-oscyank 
and try yanking something into osc 

### Expected behavior

https://github.com/ojroques/vim-oscyank - should copy into clipboard.

### Actual behavior

stopped working since the commit of: 24488169564c39a506c235bf6a33b8e23a8cb528

i guess the clipboard in the external process is not connected to the clipboard of the ui (or something like this)

**Comment by SanchayanMaity** [comment] 2023-01-08 05:25
See the same problem. Terminal is foot and inside tmux with `TERM` set to `tmux-256color`. neovim is on commit d89290b, latest as of this moment.

Tried moving to the commit before 2448816 but that did not fix it. Also tried the commit before this with Alacritty and outside of tmux, but did not help either.

My mappings are

```
remap('n', '<Leader>y', ':%y+<CR>', opts)
remap('n', '<Leader>Y', ':%y*<CR>', opts)
remap('v', '<Leader>y', '"+y'     , opts)
remap('v', '<Leader>Y', '"*y'     , opts)
```

I had to reintroduce this setting in my config which was not required after #20936 was merged.

```
vim.g.clipboard = {
  name = "tmux",
  copy = {
    ["+"] = "tmux load-buffer -w -",
    ["*"] = "tmux load-buffer -w -"
  },
  paste = {
    ["+"] = "tmux save-buffer -",
    ["*"] = "tmux save-buffer -"
  },
  cache_enabled = true
}
```
May be the above is a red herring and the problem is somewhere else but thought I did note down my observations if it helps.

**Comment by fsouza** [comment] 2023-01-08 15:28
Yeah I think the story with clipboard still needs to be revisited? Like the client should handle it, not the server?

**Comment by bfredl** [comment] 2023-01-12 15:01
Is this still an issue after https://github.com/neovim/neovim/pull/21675 ?

**Comment by SanchayanMaity** [comment] 2023-01-12 15:56
> Is this still an issue after #21675 ?

Does still seem to be an issue.

```
NVIM v0.9.0-dev-663+g2aabe9b85
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by zeertzjq** [comment] 2023-01-14 07:03
I cannot reproduce. It works for me.

**Comment by zeertzjq** [comment] 2023-01-14 09:12
It seems that the comments below may be a separate problem than the original one.

**Closed by zeertzjq** 2023-01-14 09:12 UTC
Labels: bug, needs:repro

**Comment by hjanuschka** [comment] 2023-01-14 20:08
❤️  can confirm, initial issue is solved!
