### ISSUE TITLE
Range not supported for :term

### ISSUE THREAD

**Issue by BreakTheBeta** [neovim/neovim#22157] opened 2023-02-07 15:11 UTC
### Describe the bug

Expected:
https://vimhelp.org/terminal.txt.html#terminal-function-details
Vim terminal should be able to accept a range of lines to execute
:[range]term

Current:
ERR: E481: No range allowed

### Steps to reproduce

1 - Select lines in visual mode
2 - Enter:
      :'<,'>term

Errors

### Expected behavior

Should execute range like in vim 8

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

no 

### Operating system/version

macOS 13.1

### Terminal name/version

zsh/tmux

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by glacambre** [comment] 2023-02-13 15:55
This is a duplicate of https://github.com/neovim/neovim/issues/6233 . It is almost equivalent to fixing https://github.com/neovim/neovim/issues/1496 / https://github.com/neovim/neovim/issues/12103 .

**Comment by zeertzjq** [comment] 2023-09-18 03:17
Duplicate of #6233

**Closed by zeertzjq** 2023-09-18 03:17 UTC
Labels: enhancement, terminal
