### ISSUE TITLE
yank creates flickering columns underneath in SecureShell

### ISSUE THREAD

**Issue by llpamies** [neovim/neovim#8545] opened 2018-06-13 16:21 UTC
I did not have this problem in v0.1.0, but I recently updated to v0.3.1-1-gfa2ad305e and I get this weird flickering column every time I yank a line. This is a video of the problem:

https://drive.google.com/file/d/1X7iKGrqBa_fZepbUdPaInw1UnaEGzfoG/view

This only seem to happen with SecureShell from Chrome, and it is not dependent of my current nvim configuration or TERM variable.

You can reproduce by installing bare v0.3.1-1, without plugins or config, connect via SecureShell and type "yy" to yank a line.

**Comment by mschilli87** [comment] 2018-06-13 16:28
duplicate of https://github.com/neovim/neovim/issues/8530?

**Comment by jamessan** [comment] 2018-06-13 16:33
Yes.  Filing the exact same issue again isn't going to help anything.  Just keep the discussion to the other issue.

**Closed by jamessan** 2018-06-13 16:33 UTC

**Comment by mschilli87** [comment] 2018-06-13 16:42
@jamessan: Maybe the original issue could be re-opened as the problem seems not solved for @llpamies?
