### ISSUE TITLE
"save changes to Untitled" doesn't work

### ISSUE THREAD

**Issue by gqqnbig** [neovim/neovim#23651] opened 2023-05-16 08:04 UTC
### Problem

Open Neovim-qt, insert some text, click the x button on the window.

Neovim asks Save changes to "Untitled"? I press Y.

Then, I expect Neovim to exit, but it doesn't.

If I click the x button again, Neovim shows the message again "Save changes to "Untitled"?".

Appearently Neovim does not save at all.

### Steps to reproduce

![neovim](https://github.com/neovim/neovim/assets/614159/b2f6355e-17d9-4d29-b009-2c7fb0e4f6c8)

In the recording, I pressed Y for Yes three times, but it seems neovim does nothing. I have to press N for No in order to exit.

### Expected behavior

After I press Y, neovim should exit.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Windows 10

### Terminal name/version

QT mode

### $TERM environment variable

no

### Installation

MSI install

**Comment by zeertzjq** [comment] 2023-05-16 08:24
`:confirm quit` in Vim behaves the same if Vim is built without FEAT_BROWSE

**Comment by zeertzjq** [comment] 2024-04-05 08:14
Duplicate of #21682

**Closed by zeertzjq** 2024-04-05 08:14 UTC
Labels: ux, ui-extensibility
