### ISSUE TITLE
`nvim_create_autocmd` pattern doesn't expand `~`

### ISSUE THREAD

**Issue by Syakhisk** [neovim/neovim#19720] opened 2022-08-11 16:27 UTC
### Neovim version (nvim -v)

NVIM v0.8.0-dev+789-gfea15adad

### Vim (not Nvim) behaves the same?

no, this is using lua api

### Operating system/version

Fedora Linux 36

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

tmux-256color

### Installation

copr (agriffis/neovim-nightly)

### How to reproduce the issue

```
nvim --clean ~/test.txt
:lua vim.api.nvim_create_autocmd("BufWritePost", {pattern = "~/*.txt", command = "echo 'foo'" })
:w
```

### Expected behavior
Autocommand triggered the same as to:
```
nvim --clean ~/test.txt
:autocmd bufwritepost ~/*.txt :echo 'foo'
:w
```
or
```
nvim --clean ~/test.txt
:lua vim.api.nvim_create_autocmd("BufWritePost", {pattern = "/home/username/*.txt", command = "echo 'foo'" })
:w
```

### Actual behavior

Autocommand not triggered

**Comment by clason** [comment] 2022-08-11 16:37
Duplicate of #17744

**Closed by clason** 2022-08-11 16:37 UTC
Labels: bug

**Comment by Syakhisk** [comment] 2022-08-11 16:43
Thanks! but I think it should be referenced at the docs at least.
