### ISSUE TITLE
Cannot cancel long lasting actions

### ISSUE THREAD

**Issue by eesdil** [neovim/neovim#3373] opened 2015-09-22 12:25 UTC
Cannot cancel actions which last long with ctrl-c.

![image](https://cloud.githubusercontent.com/assets/1408181/10018263/aaddf4be-6135-11e5-8b5c-4618d5d55320.png)

Clicking on it but nothing happens. So I have to close the nvim instance...

**Comment by justinmk** [comment] 2015-09-22 12:37
`:version` ?

**Comment by eesdil** [comment] 2015-09-22 12:40
Sorry, here:

NVIM 0.0.0-alpha+201509190915 (compiled Sep 20 2015 13:12:56)
Commit: 2417aeebbffe58eab6ac39feac0f64a27aafbee2
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_G
ENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150920-1195-7qm6lb/build/config -I/tmp/neovim20150920-1195-7qm6lb/src -I/tmp/neovim20150920-1195-7qm6lb/.deps/usr/include -I/tmp/neovim20150920-1195-7q
m6lb/.deps/usr/include -I/tmp/neovim20150920-1195-7qm6lb/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150920-1195-7qm6lb/.deps/usr/include -I/tmp/neovim20150920-1195-7qm6lb/.deps/usr/include -I/tmp/neovim2
0150920-1195-7qm6lb/.deps/usr/include -I/tmp/neovim20150920-1195-7qm6lb/.deps/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/usr/include -I/tmp/neovim20150920-1195-7qm6lb/build/src/nvim/auto
-I/tmp/neovim20150920-1195-7qm6lb/build/include
Compiled by kcs@magnetite

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"

**Comment by justinmk** [comment] 2015-09-22 13:54
This was fixed awhile ago, and it works for me. So we need  more explicit steps to reproduce.

**Comment by eesdil** [comment] 2015-09-22 14:03
So what can I post here? It is most visible for me with ctrlP but it is not working in general.

**Comment by Grimy** [comment] 2015-09-23 13:35
This is a duplicate of #1234 (see in particular https://github.com/neovim/neovim/issues/1234#issuecomment-130327842). I confirm that the latest master is still affected.

**Comment by justinmk** [comment] 2015-09-23 14:34
Thanks @Grimy !

**Closed by justinmk** 2015-09-23 14:34 UTC
Labels: unconfirmed

**Comment by eesdil** [comment] 2015-09-23 14:47
ok, but bit confused, as my c-c is not mapped, so I cannot unmap it...

**Comment by Grimy** [comment] 2015-09-23 14:57
In nvim, type `:verbose map <C-C>`. This will show you what <kbd><C-c></kbd> is mapped to, and what plugin created the mapping.

If it prints `No mapping found`, run `:!sleep 10` and mash  <kbd><C-c></kbd>. If that doesn’t interrupt the sleep, then you actually have a different bug than in #1234. Since I can’t reproduce this bug, it probably has something to do with your config.

**Comment by eesdil** [comment] 2015-09-23 15:02
So I have really no mappings. And I cannot cancel sleep with c-c.

But I have started nvim without plugins and c-c was working on sleep... so I will try to find out which plugin is the guilty. thank you

**Comment by tricqueb** [comment] 2015-10-07 12:20
Hi,
I'm having this bug as well. 
I have no trouble interrupting a sleep, however I can't interrupt Ctrl-P anymore...
I've tested with `:! find *` which cannot be interrupted either...

**Comment by fmoralesc** [comment] 2015-10-07 12:33
@tricqueb Your nvim version is old, there's been changes fixing this issue since then.

**Comment by tricqueb** [comment] 2015-10-07 13:37
Sorry for the old version but I just get my version updated and... the issue is still there:
`
NVIM 0.0.0-alpha+201510042257 (compiled Oct  7 2015 15:31:48)
Commit: 7be75a02917b40e5791e3f98d177f833a348df35
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/timothee/neovim/build/config -I/home/timothee/neovim/src -I/home/timothee/neovim/.deps/usr/include -I/home/timothee/neovim/.deps/usr/include -I/home/timothee/neovim/.deps/usr/include/luajit-2.0 -I/home/timothee/neovim/.deps/usr/include -I/home/timothee/neovim/.deps/usr/include -I/home/timothee/neovim/.deps/usr/include -I/home/timothee/neovim/.deps/usr/include -I/usr/include -I/home/timothee/neovim/build/src/nvim/auto -I/home/timothee/neovim/build/include
Compilé par timothee@timothee-Precision-M2800

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   fichier vimrc système : "$VIM/nvimrc"
     fichier vimrc utilisateur : "~/.nvimrc"
 2me fichier vimrc utilisateur : "~/.nvim/nvimrc"
      fichier exrc utilisateur : "~/.exrc"
  $VIM par défaut : "/home/timothee/Applications/neovim/share/nvim"
`

**Comment by tricqueb** [comment] 2015-10-07 13:40
I've no mapping on <C-c> and I commented my whole .vimrc file.

**Comment by fmoralesc** [comment] 2015-10-07 14:13
I can't reproduce, but it seems like this issue is being handled on #1234
