### ISSUE TITLE
Make popupmenu flicker free (once and for all)

### ISSUE THREAD

**Issue by purpleP** [neovim/neovim#8802] opened 2018-07-31 07:05 UTC
https://asciinema.org/a/ZkoZBJNjHg6USfMfK4YZE7mTA

Neovim version 0.3.1 vim behaves the same way.

As you can see updating completions causes flickering which could have been avoided. When backspace is pressed popup window is closed only to be opened again. In case when completions are narrowing popup windows is closed again only to be opened with new size.

From reading the code in screen.c it seems that someone (probably bram himself) took easier path of redrawing popup window by removing it and drawing it again. I get why this decision could have been needed when vim was developed, but this is clearly has to be reworked some day as it is annoying to the eye (a lot of flickering issues have been fixed, I don't see any reason why this flickering should stay).

I'm saying this because it seems like it wouldn't be that easy to fix, because it seems that a lot of knowledge of how vim works internally is needed (popup api, drawing etc).

**Comment by bfredl** [comment] 2018-07-31 07:37
> took easier path of redrawing popup window by removing it and drawing it again. 

The problem is that the basic window drawing code doesn't know about the popupmenu at all, so what vim does is to just redraw all windows (which will appear to clear the popupmenu), and after that it draws the popupmenu on top of that.

This is indeed something we plan to fix: #6619 introduces "first class" support for overlapping screen elements, so that when we draw split windows we can mask out the regions occupied by floating elements. Currently the branch only does floating buffer windows, but the pum could be refactored to use the same logic.

**Comment by justinmk** [comment] 2018-08-06 01:40
duplicate of https://github.com/neovim/neovim/issues/6115

**Closed by justinmk** 2018-08-06 01:40 UTC
