### ISSUE TITLE
"Press enter or type command" not skipped by :cq

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7183] opened 2017-08-18 15:59 UTC
- `nvim --version`: v0.2.1-696-gbdc72c7
- Vim (version: ) behaves differently? N/A
- Operating system/version: WSL
- Terminal name/version: conhost
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Do something that will trigger a stream of `:echoerr`, such as trying to copy a dozen lines to a non-existent `g:clipboard`
2. <ENTER>
3. `:` and very if that the prompt appears OK, else do whatever it takes to get the prompt to appear
4. `:cq`

While the prompt shows that the command went through (no hang, no errors, prompt cleared, etc), nvim does not exit until the error messages have all been printed.

**Comment by justinmk** [comment] 2017-08-20 14:55
Doesn't CTRL-C flush through the remaining errors? I can't reproduce this except by the degenerate case you mentioned, which should be resolved by #7193.

**Comment by mqudsi** [comment] 2017-08-20 17:16
I can retry with that branch and let you know?

**Closed** 2017-08-20 22:47 UTC
Labels: ux
