### ISSUE TITLE
no nvim-macos.tar.gz in current Pre-release 0.5.0

### ISSUE THREAD

**Issue by skrshe** [neovim/neovim#13186] opened 2020-10-29 04:49 UTC
nvim-macos.tar.gz is referenced on the releases page under NVIM 0.5.0
but theres no link in assets dropdown

**Comment by erw7** [comment] 2020-10-29 05:57
Duplicate of #13146. We know there is a problem, so please be patient for now. If you must have the package, try accessing it immediately after the nightly build job is finished. The package will probably be there for a few minutes before the package is erased by the Linux job.

**Closed by erw7** 2020-10-29 05:57 UTC
Labels: duplicate
