### ISSUE TITLE
signcolumn doesn't refresh in YCM after upgrading neovim (0.3.1-1 -> 0.4.2-2)

### ISSUE THREAD

**Issue by BBBob** [neovim/neovim#11484] opened 2019-11-30 06:46 UTC
- `nvim --version`: NVIM v0.4.2
- Operating system/version: Arch Linux x86_64
- Terminal name/version: xfce4-terminal 0.8.8
- `$TERM`: xterm-256color

### Actual behaviour
![nvim1](https://user-images.githubusercontent.com/22796642/69896951-f9be6400-137f-11ea-91ba-483c9b97bb28.png)

### Expected behaviour
![nvim2](https://user-images.githubusercontent.com/22796642/69896952-02169f00-1380-11ea-8a8a-561ebb9bf736.png)

**Comment by justinmk** [comment] 2019-11-30 07:53
Need a minimal repro. Don't  have time  to debug YCM.

**Comment by ysolis** [comment] 2020-01-09 05:29
the problem is similar in my case, i have **vim-gitgutter** plugin installed and ...  

> set signcolumn

 show **no** as result (my nvim config don't alter the default value.)

**Comment by teto** [comment] 2021-01-29 20:55
old and not reproducible, closing

**Closed by teto** 2021-01-29 20:55 UTC
Labels: 9.needs:repro
