### ISSUE TITLE
d deletes empty line after ui_attach

### ISSUE THREAD

**Issue by carlosdcastillo** [neovim/neovim#3720] opened 2015-11-23 01:50 UTC
I've upgraded to use Neovim 0.1.0 and I'm seeing a new problem when I run:

`NVIM_LISTEN_ADDRESS=/tmp/neovim/neovim /usr/local/bin/nvim`

I can hit d on an empty line and nothing happens until I hit  a second d (this is all on the neovim console window) which is the behavior I expect.

After my client ui_attaches to Neovim, now I hit d and it deletes an empty line, both in the neovim console window and in my client. 

Also hitting d$ on a line with text stops working after ui_attaching.

**Comment by tarruda** [comment] 2015-11-23 10:39
this should be fairly easy to reproduce in a test using `screen:expect`. @mhinz recently merged some commits that show how to do it: https://github.com/neovim/neovim/commit/ec847af48d0a12aa177c0f51cfc11be0ebac26e5

**Comment by carlosdcastillo** [comment] 2015-12-11 04:40
Here is an update. I learned something that may shed light on this bug and why (I think it only happens on my client).

I have a timer that every 150 ms performs a vim_eval &modified and vim_eval expand('%:p')

Those get called in between vim_input of what the user types.

I turn off the timer and everything works. I turn the timer on and then d starts deleting the line. Ctrl-N in insert mode gets stuck and only goes into the first auto complete option. Hit >> and two levels get indented. And a variety of other strange behavior.

**Comment by davecoates** [comment] 2016-05-20 19:34
You can replicate this with the python client by fetching a buffer or a window (I think any API call really):

```
>>> from neovim import attach
>>> nvim = attach('socket', path='/tmp/nvim')
>>> nvim.input('iline1<cr>line2<esc>gg')
22
>>> nvim.buffers[0].get_line_slice(0, len(nvim.buffers[0]), True, True)
['line1', 'line2']
>>> nvim.input('d')
1
>>> nvim.buffers[0].get_line_slice(0, len(nvim.buffers[0]), True, True)
['line2']
>>>
```

**Comment by bfredl** [comment] 2016-05-20 19:51
Hmm, I thought we didn't process events at all in operator-pending mode but here it looks like it treats K_EVENT as a line-wise motion (to the same line)

**Comment by justinmk** [comment] 2016-05-20 21:20
https://github.com/neovim/neovim/issues/4763 was a recent, confirmed report of this same issue. I merged it to https://github.com/neovim/neovim/issues/3416.

**Comment by justinmk** [comment] 2017-03-10 00:56
Merging this with #6166

**Closed by justinmk** 2017-03-10 00:56 UTC
Labels: api, bug
