### ISSUE TITLE
A terminal buffer printing output while user is entering an editing command causes premature execution of the command and other undesirable effects

### ISSUE THREAD

**Issue by rjmill** [neovim/neovim#4763] opened 2016-05-15 20:42 UTC
- Neovim version:
  - tested on 1.4 and a freshly built 1.5
- [ ] ~~Vim behaves differently? Vim version:~~
  - not applicable
- Operating system/version:
  - Fedora 23 and Arch Linux
- Terminal name/version:
  - GNOME terminal and rxvt unicode
- `$TERM`: xterm-256color

### Actual behaviour
_I've experienced this issue with `d`, `c`, `y`, `gw`, `>`, and `<`, but for simplicity's sake, I'll just use `d` in my examples._

There are three main cases I've noticed of this issue, but they all stem from a terminal buffer outputting text while the user is entering an editing command.

__Case 1:__ If a terminal buffer prints text between entering a command and a text object, the command will be run as if the command's key had been pressed twice.

_Example:_ `d`_[terminal output]_ Deletes the current line as if the user had entered `dd`

__Case 2:__ If terminal output happens while entering a text object or motion command (even if the text object or motion command is modifying an edit command), the terminal will wait until the command has been fully entered to print its text.

_Example:_ `di`_[terminal output]_ Causes the terminal to only print its output after the command is completed, e.g. `di`_[output printed to terminal but not displayed]_`w`_[terminal displays the output]_

__Case 3:__ If entering a number modifier before a command, the command will be run without applying the number to the command. It will, however, apply that number modifier to the next command you do.

_Example:_ `10d`_[terminal output]_ Deletes only the current line, and then the next command, e.g. `u` will have that number modifier applied to it (in this case, running undo 10 times).

NOTE: All this behavior still occurs when the terminal buffer is running in the background with `set hidden` activated.

### Expected behaviour
A terminal buffer printing text while user is entering a command has no influence on the behavior of the command.

### Steps to reproduce using `nvim -u NORC`

Open up neovim, and put some text in a blank file:
```
nvim -u NORC
i
foo
bar
baz
<esc>
```
Then open up a split and a terminal buffer in that split:
```
<C-W>v
:te
```
Run a command in the terminal to consistently output text:
```
while true; do
    echo foo
    sleep 5s
done
```
Navigate to the other split with the text in it and start entering an edit command:
```
<C-\><C-n>
<C-W>l
d
```
Wait until the terminal prints text again. The line under the cursor should get deleted.

The other cases can be reproduced with the same setup by executing the commands shown in each case's example.

**Comment by justinmk** [comment] 2016-05-15 21:24
Thanks for the detailed report. I believe this is a duplicate of https://github.com/neovim/neovim/issues/3416

If you think it is not please explain.

**Closed by justinmk** 2016-05-15 21:24 UTC
