### ISSUE TITLE
`vim.highlight_on_yank` can work in `set virtualedit=all`

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#21812] opened 2023-01-15 06:07 UTC
### Describe the bug

`vim.highlight_on_yank` cant work in `set virtualedit=all`, if our cursor is out of the EOL, then `highlight_on_yank` will get error

```
Error detected while processing TextYankPost Autocommands for "*":
Error executing lua callback: /usr/local/share/nvim/runtime/lua/vim/highlight.lua:66: end_col value outside range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        /usr/local/share/nvim/runtime/lua/vim/highlight.lua:66: in function 'range'
        /usr/local/share/nvim/runtime/lua/vim/highlight.lua:137: in function 'on_yank'
```

### Steps to reproduce

`set virtualedit = all`

```lua
api.nvim_create_autocmd("TextYankPost", {
    callback = function()
        vim.highlight.on_yank({ higroup = "IncSearch", timeout = 100 })
    end,
})
```

### Expected behavior

no error

### Neovim version (nvim -v)

NVIM v0.9.0-dev-663+g2aabe9b85

### Vim (not Nvim) behaves the same?

not test

### Operating system/version

Linux UNEXPECTED 6.0.8-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:22 +0000 x86_64 GNU/Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

compile manually

**Comment by clason** [comment] 2023-01-15 11:06
Duplicate of #21368

**Comment by clason** [comment] 2023-01-15 11:06
Please test https://github.com/neovim/neovim/pull/21370.

**Closed by clason** 2023-01-15 11:06 UTC
Labels: bug
