### ISSUE TITLE
Using with Python3

### ISSUE THREAD

**Issue by leebrooks0** [neovim/neovim#1829] opened 2015-01-16 12:30 UTC
I have a python project that is using python 3.4.2 and I am using pyenv.
I switched to python 2 (the system python on Linux Mint 17) and ran ```pip install neovim```.

Everything then works except Jedi-Vim requires Python 3 for Python 3 project support. So I used pyenv to switch back to Python 3.4.2 and then I get a whole lot of error messages.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/__init__.py", line 65, in start_host
    host.start(plugins)
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/plugin/host.py", line 45, in start
    lambda: self._load(plugins))
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/api/common.py", line 234, in run
    self._session.run(filter_request_cb, filter_notification_cb, setup_cb)
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 117, in run
    raise self._setup_exception
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 93, in on_se
tup
    setup_cb()
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/plugin/host.py", line 45, in <lambda>
    lambda: self._load(plugins))
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/plugin/host.py", line 90, in _load
    self._discover_classes(module, handlers, path)
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/plugin/host.py", line 114, in _discover_cl
asses
    plugin = cls(self._configure_nvim_for(cls))
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 38, in __init__
    encoding=nvim.options['encoding'].decode('ascii')))
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/api/common.py", line 39, in __getitem__
    return self._get(key)
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/api/common.py", line 255, in <lambda>
    return lambda *args: session.request(method, *args)
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/api/common.py", line 221, in request
    'out-request')
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/api/common.py", line 248, in walk
    return fn(obj, *args)
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/api/common.py", line 155, in <lambda>
    return lambda o, s, m, k: f1(f2(o, s, m, k), s, m, k)
  File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/site-packages/neovim/api/common.py", line 177, in _decode_if_by
tes
    return obj.decode(self.encoding, errors=self.encoding_errors)
TypeError: decode() argument 1 must be str, not bytes
Exception ignored in: <script_host.RedirectStream object at 0x7ff8e194a780>
AttributeError: 'RedirectStream' object has no attribute 'flush'
```

Is it possible to use Python 3?

**Comment by justinmk** [comment] 2015-01-16 13:47
Not yet.

**Comment by aktau** [comment] 2015-01-16 20:59
> Not yet.

For my personal edification, is that documented? Perhaps any tips for people willing to help out to fix our Python 3 support?

**Comment by Pyrohh** [comment] 2015-01-17 21:29
This should probably be explicitly stated in the python-client `README.md` for now.

**Comment by fwalch** [comment] 2015-01-17 21:46
I think this might just be an oversight because it was only tested with Python 2? The python plugin itself [works with Python 3](https://travis-ci.org/neovim/python-client) and the provider [also has Python 3-related code](https://github.com/neovim/neovim/blob/2c29b20af767bd7ebebeb41da14df4d66a19d5a0/runtime/autoload/provider/script_host.py#L15).

**Comment by justinmk** [comment] 2015-01-17 22:00
@tarruda @fmoralesc or @equalsraf would know for sure, I know this was discussed on the python-client repo, but I don't remember why the docs currently specify only 2.6. or 2.7.

**Comment by Pyrohh** [comment] 2015-01-17 22:02
Does it work for you? I'm using Arch Linux, which has `python3` symlinked to `python`, so the issue might be there. I just removed the `neovim` package installed via `pip2` (python 3's pip is just called `pip`), installed via `pip` instead, and when I launch neovim I get this:

```
No neovim module found for Python 2.7.9. Try installing it with 'pip install neovim' or see ':help nvim-python'.
In order to use pymatcher plugin, you need +python compiled vim
Floobits requires python in nvim, please read :he nvim-python
Press ENTER or type command to continue
```

I also get a traceback when I hit enter and enter the UI:
```

Error detected while processing /usr/share/nvim/runtime/ftoff.vim:
line   11:
E216: No such group or event: filetypedetect *
No neovim module found for Python 2.7.9. Try installing it with 'pip install neovim' or see ':help nvim-python'.
In order to use pymatcher plugin, you need +python compiled vim
Error detected while processing /home/michael/.nvim/plugged/vim-pseudocl/autoload/pseudocl.vim:
line   58:
E703: Using a Funcref as a Number
Error detected while processing /home/michael/.nvim/plugged/vim-pseudocl/autoload/pseudocl.vim:
line   58:
E15: Invalid expression: !s:default_opts.renderer
SignColumn     xxx ctermfg=12 ctermbg=8 guifg=Cyan guibg=Grey
Floobits requires python in nvim, please read :he nvim-python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/__init__.py", line 65, in start_host
    host.start(plugins)
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/plugin/host.py", line 45, in start
    lambda: self._load(plugins))
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/api/common.py", line 234, in run
    self._session.run(filter_request_cb, filter_notification_cb, setup_cb)
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 117, in run
    raise self._setup_exception
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 93, in on_setup
    setup_cb()
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/plugin/host.py", line 45, in <lambda>
    lambda: self._load(plugins))
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/plugin/host.py", line 90, in _load
    self._discover_classes(module, handlers, path)
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/plugin/host.py", line 114, in _discover_classes
    plugin = cls(self._configure_nvim_for(cls))
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 38, in __init__
    encoding=nvim.options['encoding'].decode('ascii')))
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/api/common.py", line 39, in __getitem__
    return self._get(key)
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/api/common.py", line 255, in <lambda>
    return lambda *args: session.request(method, *args)
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/api/common.py", line 221, in request
    'out-request')
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/api/common.py", line 248, in walk
    return fn(obj, *args)
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/api/common.py", line 155, in <lambda>
    return lambda o, s, m, k: f1(f2(o, s, m, k), s, m, k)
  File "/home/michael/.local/lib/python3.4/site-packages/neovim/api/common.py", line 177, in _decode_if_bytes
    return obj.decode(self.encoding, errors=self.encoding_errors)
TypeError: decode() argument 1 must be str, not bytes
Exception ignored in: <script_host.RedirectStream object at 0x7f1e47eada20>
AttributeError: 'RedirectStream' object has no attribute 'flush'
```

**Comment by fwalch** [comment] 2015-01-17 22:10
@Pyrohh: No, it doesn't, but looking at the error message, it seems to be an oversight because of Python 2/3 string differences. It will unfortunately always pick up the Python 3 version if it is installed, so to get it working again, `pip3 uninstall neovim` and install `python2-neovim` (or use pip).

**Comment by fmoralesc** [comment] 2015-01-17 22:13
@Pyrohh I get the same. I think @fwalch assesment is right, this must have been an oversight.

**Comment by equalsraf** [comment] 2015-01-17 22:58
It *should* support python3, but it is far less tested, and the api behaves differently (returns bytes instead of str).

I'm getting the same error. In the traceback it seems to be a simple matter of decoding self.encoding before using it. I think I  ran into a similar issue before, so maybe this is a regression. I'll start having a look into it in more detail.

This is the quick (and dirty) fix for that issue.
```diff
diff --git a/neovim/api/common.py b/neovim/api/common.py
index cc094d6..6050694 100644
--- a/neovim/api/common.py
+++ b/neovim/api/common.py
@@ -174,7 +174,7 @@ class DecodeHook(SessionHook):
 
     def _decode_if_bytes(self, obj, session, method, kind):
         if isinstance(obj, bytes):
-            return obj.decode(self.encoding, errors=self.encoding_errors)
+            return obj.decode(self.encoding.decode('ascii'), errors=self.encoding_errors)
         return obj
```

I have not looked at this in a while but the vim files that start the python host used to check for python2 only, so I find it a bit odd that it is actually starting python3 (not that I am complaining :D).

**Comment by Pyrohh** [comment] 2015-01-17 23:17
I'm admittedly not knowledgeable in python and its integration with neovim, but is there a particular reason(s) for not solely supporting python 3? Looking at neovim's dependencies, it looks like all of them support python 3, although I did find this:

http://click.pocoo.org/3/python3/#python3-limitations

I'm guessing it has something to do with supporting LTS systems, or the perceived deficiencies in string handling, but I'm not sure at all.

**Comment by equalsraf** [comment] 2015-01-17 23:49
@Pyrohh, I am all in favour of Python3 (specially because Python2 is no longer officially [maintained](https://www.python.org/dev/peps/pep-0404/#official-pronouncement)) having said that there a number of hindrances

- Python3 is not fully backwards compatible with Python2, string handling is the most obvious bit. In particular Vim is very tolerant about having binary strings going around, Python3 expects a string to be valid (under a certain encoding) - Vim does not guarantee this and the API can be a bit odd.
- Some Vim plugins don't work with Python3 (YCM is probably the main reason why I don't run nvim with Python3, all my other plugins worked a while back).
- To make things a bit worse, Vim has the :python and :python3 commands which make compatibility going forward even more confusing

It depends on what you are talking about. If we are talking about :python and **Vim compatible** plugins, it would be hard if not impossible to go python3 right now. If we are talking about plugins that only support Neovim we should support it. But we always end up testing against Python for compatibility anyway.

On another note, there seems to be a second issue going on, this time in the runtime script

```diff
diff --git a/runtime/autoload/provider/script_host.py b/runtime/autoload/provider/script_host.py
index 1420831..5159bfe 100644
--- a/runtime/autoload/provider/script_host.py
+++ b/runtime/autoload/provider/script_host.py
@@ -35,7 +35,7 @@ class ScriptHost(object):
         if IS_PYTHON3:
             self.legacy_vim = self.legacy_vim.with_hook(
                 neovim.DecodeHook(
-                    encoding=nvim.options['encoding'].decode('ascii')))
+                    encoding=nvim.options['encoding']))
         sys.modules['vim'] = self.legacy_vim
 
     def setup(self, nvim):
```

Even after this I still get `E117: Unknown function: provider#python#Call`. More important of a questions is why are the automated tests passing?

**Comment by Pyrohh** [comment] 2015-01-17 23:56
> If we are talking about :python and Vim compatible plugins, it would be hard if not impossible to go python3 right now. If we are talking about plugins that only support Neovim we should support it

Of course, my intent was only in terms of Neovim python plugins. Thanks for the detailed response.

**Comment by tarruda** [comment] 2015-01-18 11:59
> I'm admittedly not knowledgeable in python and its integration with neovim, but is there a particular reason(s) for not solely supporting python 3? Looking at neovim's dependencies, it looks like all of them support python 3, although I did find this:

The main reason is to be compatible with existing plugins, but as the python community migrates to python3 so will Neovim!

**Comment by Grimy** [comment] 2015-01-28 08:58
@equalsraf How is Python2 “no longer officially maintained”? There will be bugfix releases until 2020 for [Python 2.7](https://www.python.org/dev/peps/pep-0373/). Python 2.7.9 was release one month ago, and 2.7.10 is planned for June 2015.

**Comment by equalsraf** [comment] 2015-01-28 09:10
@Grimy I meant there will be no new major releases (2.8 etc)

**Comment by leebrooks0** [comment] 2015-02-10 12:18
I see the python-client now works on python3, i updated and everything is now working beautifully

**Comment by sscherfke** [comment] 2015-02-10 13:04
I still get *“Sorry, the command is not available in this version”* if I execute `:python3`. `:python` works.

I just installed the newest version (NVIM 0.0.0-alpha+201502100546 (compiled Feb 10 2015 13:34:49)) and have python-neovim==0.0.27 installed for both, python2 and python3.

**Comment by leebrooks0** [comment] 2015-02-10 13:18
I see I also get that error, my mistake, I thought things were all rosy now

**Comment by justinmk** [comment] 2015-02-10 18:51
If the python-client issues are fixed, it should be trivial to hook up `:python3` and friends.

**Comment by bsmith89** [comment] 2015-03-08 18:09
Hi.  Is `:python3` supposed to work now?  I'm running NVIM 0.0.0-alpha+201503071753 off of Homebrew.  When I run `:python3 print("hello")` I get "E319: Sorry, the command is not available in this version: python3".  I have installed the neovim package using pip, and have upgraded that since installing the latest version of neovim.

Am I missing something?  If py3 isn't implemented yet, when might it be?

**Comment by justinmk** [comment] 2015-03-08 18:28
Not yet. It's low priority right now.

**Comment by Shougo** [comment] 2015-03-20 14:43
I will work for the feature.

**Comment by Shougo** [comment] 2015-03-24 21:48
I Implemented the feature.  It seems working.
https://github.com/neovim/neovim/pull/2208

**Comment by SirVer** [comment] 2015-04-27 05:26
I think this is fixed through https://github.com/neovim/neovim/pull/2208 - can somebody close the issue?

**Closed** 2015-04-27 05:30 UTC
Labels: compatibility, provider

**Comment by tony** [comment] 2016-01-13 21:47
I'm experiencing a similar problem at https://github.com/davidhalter/jedi-vim/issues/523 when using Python 3.
