### ISSUE TITLE
E5113: Error while calling lua chunk

### ISSUE THREAD

**Issue by jsatk** [neovim/neovim#14703] opened 2021-06-02 03:34 UTC
- `nvim --version`: NVIM v0.5.0-dev+3fe7a0470 & LuaJIT 2.1.0-beta3
- Operating system/version: macOS Big Sur 11.4
- Terminal name/version: iTerm2 v3.4.6
- `$TERM`: `tmux-256color`

### Steps to reproduce using `nvim -u NORC`

It works fine with `nvim -u NORC`.

It looks like this commit broke something in my `init.lua` or in one of the plugins I use. But it's very hard to track down. This commit looks like the culprit: https://github.com/neovim/neovim/commit/43956dea55a49a847a0f2e5d9e0f48384cb34635

Error message:
```
E5113: Error while calling lua chunk: ...ovim/HEAD-3fe7a04_2/share/nvim/runtime/lua/vim/_meta.lua:21: attempt to index local 'info' (a nil value)
```

Is there any way using homebrew to downgrade to the nightly right before this commit? Or alternatively, what's the best way to figure out the issue? If it's in a plugin I use I'd be happy to patch it and open a PR.

**Comment by peppermilldetective** [comment] 2021-06-02 04:04
Can also confirm problem on different computer:

- `nvim --version`: NVIM v0.5.0-dev+1367-g27c616d68
- OS: Windows 10
- Terminal: Powershell, CMD, Git Bash

Same error message as reporter. More information from me is probably not possible because I don't want to update my main nvim version and I can't give more information on the system that is experiencing this problem. I can at least confirm it is not unique. Apologies.

**Comment by clason** [comment] 2021-06-02 06:58
This looks like essentially a duplicate of #14697

(Runtime file mismatch: You need to 1. regenerate the CMake cache files (`make cmake` or `make distclean`) before building and 2. install the updated runtime files (`make install` or adjusting the `VIMRUNTIME` environment variable.)

I don't know why homebrew doesn't pick up the new runtime file -- they make modifications to the build scripts, so it's a homebrew issue and should be reported there. (_After_ 0.5 is released, since they understandably don't promise support for HEAD builds.)

@carlocab ?

**Comment by carlocab** [comment] 2021-06-02 09:47
I doubt it's related to the modification we make, which is only [this](https://github.com/Homebrew/homebrew-core/blob/e4c818406256621d18460c759fbd1dbc161198e3/Formula/neovim.rb#L88):

```ruby
inreplace "config/auto/versiondef.h", /#{HOMEBREW_LIBRARY}[^ ]+/o, ENV.cc
```

This just removes text that says something like
```
/usr/local/Homebrew/Library/Homebrew/shims/super/clang
```
and replaces it with just `clang`.

@peppermilldetective's comment also suggests to me that this isn't a Homebrew issue.

>Is there any way using homebrew to downgrade to the nightly right before this commit?

Try this:

```diff
diff --git a/Formula/neovim.rb b/Formula/neovim.rb
index cc5ac3e183..92517a05ba 100644
--- a/Formula/neovim.rb
+++ b/Formula/neovim.rb
@@ -21,7 +21,8 @@ class Neovim < Formula
   end
 
   head do
-    url "https://github.com/neovim/neovim.git"
+    url "https://github.com/neovim/neovim.git",
+        revision: "full git commit hash here"
     depends_on "tree-sitter"
   end
 
```
Haven't tested that this works, but it should.

**Comment by carlocab** [comment] 2021-06-02 09:49
That said, I am running a nightly that has https://github.com/neovim/neovim/commit/43956dea55a49a847a0f2e5d9e0f48384cb34635 (NVIM v0.5.0-dev+1368-g2faa1c361), and I can't reproduce this.

So I think this is a config/plugin issue. Try bisecting your `init.{vim,lua}` to see if the problem lies somewhere there.

**Comment by clason** [comment] 2021-06-02 09:50
@carlocab I agree, my comment was before I finished my coffee. The file is there but it triggers an error somewhere. Without a minimal reproducing example, we can't do much more.

(Sorry for the annoying ping!)

**Comment by carlocab** [comment] 2021-06-02 13:16
No worries; feel free to ping me anytime for issues related to the Homebrew formula.

**Comment by ngxingyu** [comment] 2021-06-02 14:42
> That said, I am running a nightly that has [43956de](https://github.com/neovim/neovim/commit/43956dea55a49a847a0f2e5d9e0f48384cb34635) (NVIM v0.5.0-dev+1368-g2faa1c361), and I can't reproduce this.
> 
> So I think this is a config/plugin issue. Try bisecting your `init.{vim,lua}` to see if the problem lies somewhere there.

I had the same issue, it went away after i changed `vim.o.conceallevel = 1` to `vim.wo.conceallevel = 1` so it might be something similar to this.

**Comment by 06kellyjac** [comment] 2021-06-02 14:57
For me it was `vim.o.t_Co="256"` -> `vim.wo.t_Co="256"` that fixed it (not that t_xx options seem to do anything in neovim anyway `:h t_xx`)
I've still got `vim.o.conceallevel=0` with `.o.` and no error with my setup

**Comment by ngxingyu** [comment] 2021-06-02 15:03
> For me it was `vim.o.t_Co="256"` -> `vim.wo.t_Co="256"` that fixed it (not that t_xx options seem to do anything in neovim anyway `:h t_xx`)
> I've still got `vim.o.conceallevel=0` with `.o.` and no error with my setup

Eh actually mine's the same as yours, the conceallevel wasn't the problem, it was t_Co for me too.

**Comment by clason** [comment] 2021-06-02 15:21
So it's a duplicate of https://github.com/neovim/neovim/issues/14662

`t_Co` is in fact deprecated and shouldn't be set, period. (But it should still work with the "dumb" `vim.go.t_Co` accessor if you absolutely _have to_ keep it.)

**Closed by clason** 2021-06-02 15:21 UTC
Labels: 9.needs:repro, bug, lua

**Comment by peppermilldetective** [comment] 2021-06-02 15:40
For others that may find their way here, can confirm that it is _some setting_ causing this problem. Best resolution is to go through your settings file (probably init.lua, no confirmed issues from the init.vim crowd) and verify that each individual setting is using the correct call to be set by using `:h <setting>`. Any global setting uses `vim.o.<setting>`, any local to window setting uses `vim.w.<setting>`, and there are some options that are both global and local to window that use `vim.wo.<setting>`.

Common denominators are probably any of the `t_xx` settings (such as `t_Co`), `conceallevel`, `term` (was the one for me). It appears to be inconsistent as to which setting is the guilty one, so you'll just have to manually check them all. Personally, it gave me a reason to migrate away from a function to set parameters to the easier settings.

**Comment by clason** [comment] 2021-06-02 15:46
Yes, if you find a specific option that is giving you an error with `vim.o` or `vim.opt` (but is not `t_xx`, which haven't been supported for a long time), please post in the linked issue https://github.com/neovim/neovim/issues/14662

**Comment by jsatk** [comment] 2021-06-02 22:42
> For others that may find their way here, can confirm that it is _some setting_ causing this problem. Best resolution is to go through your settings file (probably init.lua, no confirmed issues from the init.vim crowd) and verify that each individual setting is using the correct call to be set by using `:h <setting>`. Any global setting uses `vim.o.<setting>`, any local to window setting uses `vim.w.<setting>`, and there are some options that are both global and local to window that use `vim.wo.<setting>`.
> 
> Common denominators are probably any of the `t_xx` settings (such as `t_Co`), `conceallevel`, `term` (was the one for me). It appears to be inconsistent as to which setting is the guilty one, so you'll just have to manually check them all. Personally, it gave me a reason to migrate away from a function to set parameters to the easier settings.

Thanks. Will attempt to do this when I have some time. I wish there was an easier way to revert back to what I had tho as this b0rked stuff at work for me and I don't want to lose a day debugging 😢 .

Thanks for the quick reply and solution all.

**Comment by jsatk** [comment] 2021-06-02 22:48
> vim.wo.t_Co="256"

It was `vim.o.t_Co="256" for me too. I'm wondering if I even need this option set in neovim. 🤔 

Thanks for quick replies again.
