### ISSUE TITLE
`set winhl=Normal:GroupWithFgColor` takes priority over syntax highlighting

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#7375] opened 2017-10-11 06:44 UTC
[This is a tracking issue for 0.2.1]

see https://github.com/neovim/neovim/pull/7082#issuecomment-335218075

**Comment by bfredl** [comment] 2017-10-11 08:09
I can't reproduce the regression. Maybe it only happens with specific color scheme or link structure?
Can someone produce minimal example with `nvim -u NONE` (+ colorscheme if it turns out to be neccessary), I would expect something like

```
hi link ... " if neccessary
set winhl=Normal:XXX,NormalNC:YYY
split
set winhl=Normal:ZZZ,NormalNC:WWW
```

**Comment by bfredl** [comment] 2017-10-11 08:10
Alternatively, just write a failing test like the winhl tests in `ui/highlight_spec.lua` : )

**Comment by justinmk** [comment] 2017-10-15 10:41
@blueyed does https://github.com/neovim/neovim/pull/7082#issuecomment-335218075 happen with any colorscheme? Or a specific one? If it's not much trouble, can you reproduce it with `nvim -u NORC` ?

**Comment by blueyed** [comment] 2017-10-15 10:53
I am using this colorscheme: https://github.com/blueyed/vim-colors-solarized
The problem seems to be only that the current window has no syntax highlighting.
The inactive window is dimmed, and has syntax highlighting, which the active one is not dimmed, but has no syntax highlighting.
I could not reproduce it using the "default" colorscheme.

**Comment by blueyed** [comment] 2017-10-15 10:54
@rafaeln
What colorscheme are you using?

**Comment by blueyed** [comment] 2017-10-15 11:06
The workaround in my case is to not override `Normal`, which is not really necessary:
```vim
if exists('+winhighlight')
  function! s:configure_winhighlight()
    let ft = &filetype
    let bt = &buftype
    " Check white/blacklist.
    if &diff || (index(['dirvish'], ft) == -1
          \ && (index(['nofile', 'nowrite', 'acwrite', 'quickfix', 'help'], bt) != -1
          \     || index(['startify'], ft) != -1))
      set winhighlight=NormalNC:MyNormalWin
    else
      set winhighlight=NormalNC:MyInactiveWin
    endif
  endfunction
  augroup inactive_win
    au!
    au ColorScheme * hi link MyInactiveWin ColorColumn
    au FileType,BufWinEnter * call s:configure_winhighlight()
    if exists('##OptionSet')
      " TODO: does not work with :Gdiff - diffsplit does not trigger it, too!
      au OptionSet diff call s:configure_winhighlight()
    endif
  augroup END
endif
```

**Comment by blueyed** [comment] 2017-10-15 11:23
This reproduces it:
```vim
hi! Normal ctermfg=8
hi link MyNormal Normal
set winhl=Normal:MyNormal,NormalNC:ColorColumn
split
```

**Comment by bfredl** [comment] 2017-10-16 06:04
I see no difference with `MyNormal` or not, both cases it looks like expected.

**Comment by rafaeln** [comment] 2017-10-16 16:04
@blueyed, I'm using base16. I keep changing the exact one, but I was able to reproduce the problem with all the ones I tried.

**Comment by justinmk** [comment] 2017-10-16 16:07
What terminal are you all using? Does using a different terminal change the behavior ?

If using VTE based terminal, try one that isn't. Or vice versa.

**Comment by rafaeln** [comment] 2017-10-16 16:24
@justinmk, I'm running the the latest version of nvim from the ppas, under tmux 2.3 in urxvt v9.21

**Comment by rafaeln** [comment] 2017-10-16 16:30
@blueyed, [the latest workaround you posted](https://github.com/neovim/neovim/issues/7375#issuecomment-336704099) works better for me. It's still a little buggy in comparison with [vim-diminactive](https://github.com/blueyed/vim-diminactive). With the workaround, I only get dimming among nvim-internal windows. That is to say, when I move out of nvim, the last window I was in still keeps its normal highlight. With vim-diminactive, on the other hand, when I move out of nvim, all windows become dimmed, as expected.

**Comment by justinmk** [comment] 2017-10-16 16:49
I think @blueyed runs rxvt also. Can you both try something else? This could narrow down the issue.

**Comment by rafaeln** [comment] 2017-10-16 19:18
I tried gnome-terminal and xterm, but both work terribly wrongly with tmux and the colorschemes from base16. I'll have to do something non-trivial to figure this out. But once I do, I'll post the result here.

**Comment by justinmk** [comment] 2017-10-20 23:38
Since 'winhl' is new, this isn't a regression, and not serious enough to block 0.2.1. Moving to next.

**Comment by bfredl** [comment] 2017-10-21 08:21
It is not a regression at all. Or at least, the only problem that I managed to reproduce is "set winhl=Normal:XXX has priority over syntax highlighting" (most obvious with `hi XXX ctermfg=4 guifg=blue` but it applies to all attributes) which has been since `winhl` was merged (I checked out the PR and tested) and thus no regression...

**Comment by justinmk** [comment] 2017-10-21 11:33
Ok. @blueyed does this match your understanding?

**Comment by blueyed** [comment] 2017-10-21 12:21
I still have to look into this in detail - e.g. with another terminal etc.
I agree that it should not block 0.2.1, but from my test case it certainly shows that there is an issue somewhere.

@bfredl 
As for me there is a behavior change from before and after https://github.com/neovim/neovim/commit/ba7277cfb4e2556f246446d06b53f3427f28130f.

**Comment by bfredl** [comment] 2017-10-21 12:27
@blueyed yes the semantics of `hi link MyNormal Normal` _changed_. One could argue whether that change was right or wrong, but that effects anything that would use `MyNormal`, it is not a "winhl regression". Fixing the winhl problem means fixing it for _both_ with and without `hi link Normal`.

**Comment by blueyed** [comment] 2017-10-22 00:40
So I have tried gnome-terminal now also, and without my Zsh config (also using base16 etc).
In both cases I could reproduce it from my comment above (which I have clarified).

@bfredl 
You've said that you see no difference between using `MyNormal` or not, but I cannot confirm.

When using just `set winhl=NormalNC:ColorColumn` it works as expected (i.e. there is syntax highlighting for the current window):
```
hi! Normal ctermfg=8
hi link MyNormal Normal
" set winhl=Normal:MyNormal,NormalNC:ColorColumn
set winhl=NormalNC:ColorColumn
split
```

I still think that https://github.com/neovim/neovim/commit/ba7277cfb4e2556f246446d06b53f3427f28130f accidentally caused a behavior change that is actually not what you would expect to happen.

**Comment by justinmk** [comment] 2017-10-22 08:23
So base16 is somehow required?

**Comment by bfredl** [comment] 2017-10-22 08:48
@blueyed I could see no difference because your reproduction instructions did not mention syntax highlighting before.

The behavior change is simply, in the past
`hi link MyNormal Normal`
more or less meant
`hi clear MyNormal`
but now it means
`hi MyNormal ctermfg=8`
(or whatever attributes specified in`hi Normal`). You can easily reproduce the bug before  ba7277c by using something like this directly. 

> When using just set winhl=NormalNC:ColorColumn it works as expected

Set `ctermfg` in ColorColumn and you get the same issue these.

> So base16 is somehow required?

Only accidentally by the reproduction instructions, just add `guifg=whatever` to get the same bug in rgb terminal/gui.

**Closed** 2018-04-02 12:21 UTC
Labels: help wanted, syntax
