### ISSUE TITLE
Folded hl group not applied on folded lines with spell enabled

### ISSUE THREAD

**Issue by lewis6991** [neovim/neovim#12982] opened 2020-09-25 15:12 UTC
Just a quick heads up, I'm pretty sure f8134f2fd1e2effe79d011b1ff12ebb8719c3ffe has stopped the `Folded` highlight group being applied to folded lines with `set spell` applied.

- `nvim --version`: f8134f2fd1e2effe79d011b1ff12ebb8719c3ffe
- Operating system/version: Redhat
- Terminal name/version: Iterm2
- `$TERM`: zsh

### Steps to reproduce using `nvim -u NORC`

Open this file: 
```
FOLDME {{{
a
b
c
d
e
}}}

vim: foldmethod=marker spell
```
Top: 0.4.4
Bottom: f8134f2fd1e2effe79d011b1ff12ebb8719c3ffe
![Screenshot 2020-09-25 at 16 10 23](https://user-images.githubusercontent.com/7904185/94284001-b3a74200-ff49-11ea-820e-9fae00e28f6f.png)

**Comment by teto** [comment] 2020-09-25 21:00
very possible since that bit was hackish. I have a few (less)hackish workarounds in mind but @bfredl is doing crazy luahl stuff so he may end up with a clean solution. Meanwhile you can use an older master or bear with it (it's master after all :) ).

**Comment by lewis6991** [comment] 2020-09-25 21:03
I'm sure I can just `set nospell` for a while 😉

**Comment by petobens** [comment] 2020-10-02 12:01
> I have a few (less)hackish workarounds in mind but @bfredl is doing crazy luahl stuff so he may end up with a clean solution

I'm seeing the same problem. This comment refers to this pr: https://github.com/neovim/neovim/pull/12963 ?

**Comment by lervag** [comment] 2020-10-03 09:01
I'm also seeing the same problem. But more: When my cursor is on a foldstart line, the highlighting changes, regardless of the `spell` option. Screens here:

![2020-10-03_11:00_screenshot](https://user-images.githubusercontent.com/998898/94987586-a4d31780-0567-11eb-9d61-070b7c6cdba6.png)
![2020-10-03_11:00_screenshot_000](https://user-images.githubusercontent.com/998898/94987588-a56bae00-0567-11eb-973a-6a5cdda4d506.png)

I can look into this in more detail (minimal vimrc and test), if it would be of help.

**Comment by sjl** [comment] 2020-10-13 15:37
I'm seeing the same thing as @lervag.  Folded lines aren't highlighted properly when `spell` is on and/or the cursor is on them.

**Comment by lervag** [comment] 2020-11-09 15:33
This issue is still present, and I have to admit it is quite annoying. I'm curious, is there any progress here?

**Comment by teto** [comment] 2020-11-09 15:41
I'll try something this week.

**Comment by teto** [comment] 2020-11-15 22:15
as a quickfix in screen.c 
```
@@ -2195,6 +2196,7 @@ static int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow,
     }
 
     if (wp->w_p_spell
+        && foldinfo.fi_lines == 0
         && *wp->w_s->b_p_spl != NUL
         && !GA_EMPTY(&wp->w_s->b_langp)
         && *(char **)(wp->w_s->b_langp.ga_data) != NULL) {
```
seems to fix it.
I would like to do some more work to prepare inline folds but if this quickfix works for you, I can commit it.

**Comment by lervag** [comment] 2020-11-15 23:44
For me, the problem persists even with this patch. Here are some screenshots that might help:

|  | Ok | Bad |
| --- | --- | --- |
| **Neovim** | ![nvim_before](https://user-images.githubusercontent.com/998898/99200236-6e163100-27a4-11eb-9b14-8ad44bf421a2.png) | ![nvim_after](https://user-images.githubusercontent.com/998898/99200234-6d7d9a80-27a4-11eb-8a16-b24a8db41052.png) |
| **Vim** | ![vim_before](https://user-images.githubusercontent.com/998898/99200224-5c348e00-27a4-11eb-9bb5-8ca3a5f28837.png) | ![vim_after](https://user-images.githubusercontent.com/998898/99200229-635b9c00-27a4-11eb-898a-d2e937129fd6.png) |

Notice that in nvim, there's a strange ellipsis symbol at the end of the foldlines/foldtexts, and that when the cursor is on top of a fold, the folded line highlighting "disappears". This is also visible in [my previous comment](https://github.com/neovim/neovim/issues/12982#issuecomment-703072303).

As before, I can try and make a minimal example if that can help you figure it out.

**Comment by lewis6991** [comment] 2020-11-16 12:31
The quickfix to screen.c works for me.

**Comment by teto** [comment] 2020-11-17 08:52
@lervag yes I am interested in a minimal example. It works here but that function is complex so I may have missed your case.

**Comment by lervag** [comment] 2020-11-17 08:57
Ok, I'll see if I can make it within a day or two.

**Comment by lervag** [comment] 2020-11-17 22:32
I made a minimal example:

```vim
syntax enable

set termguicolors
highlight Folded gui=bold guibg=white guifg=red
highlight MyWord gui=bold guibg=red   guifg=white

nnoremap q :qall!<cr>

silent edit test.txt
normal! zM
redraw!
sleep 1

normal! zR
redraw!
sleep 1

call matchadd('MyWord', '\V' . 'test', -1)
redraw!
sleep 1

normal! zM
```

where `text.txt` contains e.g. this:

```
{{{ test 1

}}}
{{{ test 2

}}}
{{{ test 3

}}}

# vim: fdm=marker
```

Now, with a recent neovim nightly, `nvim -u test.vim` should reproduce my issue.

**Comment by TonyWu20** [comment] 2020-11-23 09:27
The quickfix also works for me.

**Comment by teto** [comment] 2020-11-23 22:31
@lervag thanks for the MWE, I will add an additional test. I think that skipping `while (cur != NULL || shl_flag == FALSE) {` when `foldinfo.fi_lines == 0` could work but I am working towards a longer term fix (towards https://github.com/neovim/neovim/pull/12194).
The other quickfix will be merged with https://github.com/neovim/neovim/pull/13322 tomorrow.

**Comment by teto** [comment] 2020-11-27 00:25
the first quickfix was merged

@lervag I quickly hacked sthg today for your specific issue https://github.com/neovim/neovim/pull/13393 it seems to fix it, if you want to try

**Comment by lervag** [comment] 2020-11-27 08:24
Great, thanks. Let's continue the discussion in #13393, then? It seems the other matters in this issue are solved, so it can be closed?

**Closed** 2020-11-27 08:45 UTC
Labels: bug
