### ISSUE TITLE
Neovim exits when a new line is inserted in some files

### ISSUE THREAD

**Issue by aliasgar55** [neovim/neovim#24018] opened 2023-06-14 09:31 UTC
### Problem

The neovim program exists when a new line is inserted in a file, using `o` or enter or by pasting a newline
The problem occurs only for a specific file in the project

### Steps to reproduce

Not sure how to reporduce

### Expected behavior

A new line should be inserted in the file

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1073+g9a271f6af

### Vim (not Nvim) behaves the same?

no

### Operating system/version

NAME="Pop!_OS" VERSION="22.04 LTS" 

### Terminal name/version

tmux 3.2a

### $TERM environment variable

screen-256color

### Installation

Using apt

**Comment by zeertzjq** [comment] 2023-06-14 09:44
Can you obtain a backtrace? https://github.com/neovim/neovim/wiki/FAQ#backtrace-linux

**Comment by aliasgar55** [comment] 2023-06-14 18:55
I had to edit the file using another editor(vim) 
After that I was not able to recreate the issue
We can close the issue, as of now, will reopen if the issue reappears again

**Comment by aliasgar55** [comment] 2023-07-18 10:41
The issue has surfaced again
Here is the backtrace

**Comment by zeertzjq** [comment] 2023-07-18 10:48
Where?

**Comment by aliasgar55** [comment] 2023-07-18 10:51
Signal: 11 (SEGV)
    PID: 426585 (nvim)
    UID: 1000 (ali)
    GID: 1000 (ali)
    Timestamp: Tue 2023-07-18 15:51:17 IST (23min ago)
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-e4f5ca3b-c819-407b-ba2a-047746a5b21f.scope
          Unit: user@1000.service
     User Unit: vte-spawn-e4f5ca3b-c819-407b-ba2a-047746a5b21f.scope
         Slice: user-1000.slice
     Owner UID: 1000 (ali)
       Boot ID: 90470abde59d4a028c7612a6a37e68e1
    Machine ID: b12731022c42a5ce6d5755de63fe20df
      Hostname: pop-os
       Storage: /var/lib/systemd/coredump/core.nvim.1000.90470abde59d4a028c7612a6a37e68e1.426585.1689675677000000.zst (present)
     Disk Size: 5.2M
       Message: Process 426585 (nvim) of user 1000 dumped core.
                
                Found module /home/ali/neovim/bin/nvim with build-id: 2cc017c092d25d04b78aff8b3ff2af8e818daee2
                Found module /home/ali/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/python.so with build-id: 8bab87a2e8f76d4e20561c9913ec74b56ed09825
                Found module linux-vdso.so.1 with build-id: 7153558dee7a7d9a1444464f014de5d4ba5e5adf
                Found module libutil.so.1 with build-id: 2bac9e4cf30824d56388dc43b83a2ad87d1bd33d
                Found module ld-linux-x86-64.so.2 with build-id: 61ef896a699bb1c2e4e231642b2e1688b2f1a61e
                Found module libc.so.6 with build-id: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d
                Found module libgcc_s.so.1 with build-id: 09c4935b79388431a1248f6a98e00d7dc81b8513
                Found module libdl.so.2 with build-id: 952123c3bdce7c3370553717942b4878d1fad797
                Found module libpthread.so.0 with build-id: e62798b68557abb4bc5548aba2640cd5ab948f36
                Found module libm.so.6 with build-id: 27e82301dba6c3f644404d504e1bb1c97894b433
                Stack trace of thread 426585:
                #0  0x00005643d5b1306a n/a (/home/ali/neovim/bin/nvim + 0x33906a)

GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/ali/neovim/bin/nvim...
[New LWP 426585]
[New LWP 426586]
[New LWP 426587]
[New LWP 426589]
[New LWP 426588]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/ali/neovim/bin/nvim --embed .'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005643d5b1306a in ts_query_cursor_next_capture (self=self@entry=0x5643d7544e00, match=match@entry=0x7fff4d56bd30, 
    capture_index=capture_index@entry=0x7fff4d56bd28)
    at /home/runner/work/neovim/neovim/.deps/build/src/tree-sitter/lib/src/./query.c:4061
4061	/home/runner/work/neovim/neovim/.deps/build/src/tree-sitter/lib/src/./query.c: No such file or directory.
[Current thread is 1 (Thread 0x7f188aba1740 (LWP 426585))]
[?2004h(gdb) clear
[?2004l
No breakpoint at this line.
[?2004h(gdb) exit
[?2004l

**Comment by clason** [comment] 2023-07-18 10:57
External scanner crash. Are you sure that your nvim-treesitter is fully updated, especially the Python parser? If it is, can you share the file that led to the crash?

@amaanq

**Comment by aliasgar55** [comment] 2023-07-18 11:21
Tree sitter is updated
I cant share the file

**Comment by clason** [comment] 2023-07-18 11:27
Then there's not much we can do.

**Comment by clason** [comment] 2023-07-18 11:27
Closing since it's an upstream (tree-sitter-python) issue.

**Closed by clason** 2023-07-18 11:27 UTC
Labels: needs:repro, bug-crash, treesitter

**Comment by clason** [comment] 2023-07-18 11:38
Yeah, but that should not happen without something going wrong in the parser?

In any case, without minimal reproducing steps (even for a toy file), this is hard to investigate. I'm happy to reopen if someone can provide them and the issue looks actionable on our end.

**Comment by aliasgar55** [comment] 2023-07-31 10:42
This is happens mostly 
When I add a try except block in python
i.e: add a try statement, and indent the code block
And when trying to add a except statement the editor crashes
I tried to isolate the it in another file, but then it dosent work

**Comment by amaanq** [comment] 2023-07-31 10:45
If you can provide a minimal reproducer (file and exact point at which you add text, and what text you add, newline, tab, etc), then I can investigate what's going on/if it is a tree-sitter bug
