### ISSUE TITLE
Maps using <> notation print garbled preview

### ISSUE THREAD

**Issue by MithicSpirit** [neovim/neovim#23451] opened 2023-05-02 19:33 UTC
### Problem

When making a `:map` that uses <> notation in the lhs, the preview (in the bottom right corner; not sure what it's called) is garbled. Note that using the actual character rather than <> notation (inserted with `<C-V>`) does not cause this issue.

### Steps to reproduce

```
nvim --clean
<C-W>  (look in bottom right: displays `^W`)
<Esc>
:nmap <C-W>, <C-W><
<C-W>  (look in bottom right: displays <80>ü^DW)
```

### Expected behavior

Even when mapping to `<C-W>` the preview should still look normal, as it does in step 2.

### Neovim version (nvim -v)

v0.9.0

### Vim (not Nvim) behaves the same?

no, 9.0 (from Arch Linux repos)

### Operating system/version

Arch Linux (rolling)

### Terminal name/version

alacritty 0.12.0 (5a728195)

### $TERM environment variable

alacritty

### Installation

Arch Linux community repo (not AUR)

**Comment by zeertzjq** [comment] 2023-05-02 22:16
Duplicate of #20452

**Closed by zeertzjq** 2023-05-02 22:16 UTC
Labels: bug
