### ISSUE TITLE
lsp/rpc.lua:494: attempt to index local 'decoded' (a number value)

### ISSUE THREAD

**Issue by JonasUJ** [neovim/neovim#14246] opened 2021-03-29 21:09 UTC
- `nvim --version`:
```
NVIM v0.5.0-dev+aa6adac
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: gcc-10 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210329-28620-1yqmrkg/build/config -I/tmp/neovim-20210329-28620-1yqmrkg/src -I/home/linuxbrew/.linuxbrew/include -I/usr/include -I/tmp/neovim-20210329-28620-1yqmrkg/build/src/nvim/auto -I/tmp/neovim-20210329-28620-1yqmrkg/build/include
```
- language server name/version: Mainly tested with sumneko_lua and pyright installed with :LspInstall (idk which version but I assume latest of both)
- Operating system/version: Windows 10 Home 2004 running WSL 2

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: lua: configuration checked.
  - INFO: python: configuration checked.
</details>

<details>
<summary>lsp.log</summary>

Too big, my browser almost crashed.

I uploaded them as files instead.

This log is from after opening an empty python file
[before.log](https://github.com/neovim/neovim/files/6224392/before.log)

This is after following the instructions I've put below
[after.log](https://github.com/neovim/neovim/files/6224393/after.log)

I might have gotten these logs without using nvim -u NORC, but my init.lua was the same file I have you run in the steps to repro anyway.

</details>

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

Have packer.nvim install and open a file with the following:
```lua
require('lspinstall').setup()

-- :LspInstall python
local servers = require'lspinstall'.installed_servers()
for _, server in pairs(servers) do
  require'lspconfig'[server].setup{}
end

return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use 'neovim/nvim-lspconfig'
  use 'kabouzeid/nvim-lspinstall'
end)
```
Type `:luaf %` and `:PackerCompile`/`:PackerSync`/`:LspInstall python` and maybe `luaf %` again.

Open a python file in a git repo and type anything, e.g.
```py
import math
math.|
```
with the cursor as `|` in insert mode type `^N` a couple of times.

### Actual behaviour

It spews this error every other time:
```
Error executing vim.schedule lua callback: ...im/HEAD-aa6adac_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:494: attempt to index local 'decoded' (a number value)
```

The language server stops working after exiting and re-entering insert mode.

### Expected behaviour

No errors

### Additional information

I realise this might be an issue with the language servers, but it's nvim code that throws an error so I'm reporting it here. Additionally, I have no problem with either language server on my ubuntu laptop, which is using an nvim version from yesterday. 

I also had this issue with my nvim install from a week or two ago, before I decided to update to see if this was fixed.

I installed nvim with linuxbrew, following the install instructions for MacOS, even though I'm on WSL2. This was also how I installed it on my ubuntu laptop.

I've tried resetting my WSL user to clear all data in case something was corrupt.

I've also had other errors with a bit more of an elaborate init.lua setup using compe.nvim (but also all occured in nvim code). Some said 'decoded' was userdata or nil, another complains about encode_tv2json and a function reference.

I'm new to (neo)vim, coming from VSCode. I might not know all the technicalities and I hope this is just a matter of misconfiguration on my end, or maybe nvim 0.5 lsp just isn't meant for WSL yet?

**Comment by JonasUJ** [comment] 2021-03-30 16:31
Also worth noting is that my after.log contains enormous chunks of backslashes always followed by an escapable character (`"`, `n`, `r`, etc.). To me this suggests a faulty JSON serializer somewhere.

**Comment by mjlbach** [comment] 2021-03-30 22:02
I'm not able to reproduce this. I use neovim on wsl with sumneko (and rust-analyzer) without issues. Have you both reproduced with a minimal config, like https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua

**Comment by joshuachp** [comment] 2021-03-31 07:46
I finally got it in the minimal config 😄.
[lsp.log](https://github.com/neovim/neovim/files/6234709/lsp.log)
The strange part is that

**Comment by joshuachp** [comment] 2021-03-31 07:51
Correct me if I'm wrong, but It seems that  `json_decode` is returning a number instead of a Json wich is not suppoted by rpc.

The same error is int the log provided by JonasUJ
```log
1202 [ DEBUG ] 2021-03-29T22:11:09+0200 ] ...im/HEAD-aa6adac_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:492      ]  "decoded"       663
```

**Comment by mjlbach** [comment] 2021-03-31 08:11
Very strange. The implementation of json_decode is [here](https://github.com/mjlbach/neovim/blob/0cadab14123a492f6a02f9580315596d604f9a9d/src/nvim/eval/funcs.c#L5386-L5419). 

Try running with this patch and then post an error if it comes up:
```diff
diff --git a/runtime/lua/vim/lsp/rpc.lua b/runtime/lua/vim/lsp/rpc.lua
index 4e2dd7c8e..94a712b82 100644
--- a/runtime/lua/vim/lsp/rpc.lua
+++ b/runtime/lua/vim/lsp/rpc.lua
@@ -485,6 +485,9 @@ local function start(cmd, cmd_args, dispatchers, extra_spawn_params)
   --@private
   local function handle_body(body)
     local decoded, err = json_decode(body)
+    if type(decoded) == "number" or type(decoded) == "string" then
+      vim.notify(vim.inspect({body = body, decoded=decoded, err=err}))
+    end
     if not decoded then
       -- on_error(client_errors.INVALID_SERVER_JSON, err)
       return
```

Do you have a reliable reproduction?

**Comment by mjlbach** [comment] 2021-03-31 08:12
@JonasUJ The only faulty serialization could be on the server side, which seems unlikely if the issue is reproducible on rust-analyzer on a python language server (pyright? I'm assuming?). I guess deserialization could be failing, but it seems odd that it would be so hard to repro;

**Comment by joshuachp** [comment] 2021-03-31 08:14
```json
{
  body = '{"jsonrpc":"2.0","method":"$/progress","params":{"token":"rustAnalyzer/roots scanned","value":{"kind":"report","message":"90/232","percentage":38}}}',
  decoded = 43
}
```

**Comment by mjlbach** [comment] 2021-03-31 08:17
Weirder, `:lua print(vim.inspect(vim.fn.json_decode('{"jsonrpc":"2.0","method":"$/progress","params":{"token":"rustAnalyzer/roots scanned","value":{"kind":"report","message":"90/232","percent
age":38}}}')))` works fine for me.

**Comment by joshuachp** [comment] 2021-03-31 08:18
Tryed to run it and actually works for me too

**Comment by mjlbach** [comment] 2021-03-31 08:22
Can you add an additional entry in the table in vim.inspect to include decoded_json=vim.fn.json_decode(body)

**Comment by joshuachp** [comment] 2021-03-31 08:25
```lua
{
  body = '{"jsonrpc":"2.0","method":"$/progress","params":{"token":"rustAnalyzer/roots scanned","value":{"kind":"report","message":"64/232","percentage":27}}}',
  decoded = 43,
  decoded_json = {
    jsonrpc = "2.0",
    method = "$/progress",
    params = {
      token = "rustAnalyzer/roots scanned",
      value = {
        kind = "report",
        message = "64/232",
        percentage = 27
      }
    }
  }
}
```

**Comment by mjlbach** [comment] 2021-03-31 08:44
Hmm, can you try building directly from source and check ~/.cache/nvim/log right after the error? See if there is anything suspicious about deserialization

**Comment by joshuachp** [comment] 2021-03-31 08:47
Im following HEAD with `neovim-git`

```
NVIM v0.5.0-dev+1194-gc20ae3aad
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/gcc -D_FORTIFY_SOURCE=2 -march=native -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/joshuachp/.cache/paru/clone/neovim-git/src/build/config -I/home/joshuachp/.cache/paru/clone/neovim-git/src/neovim-git/src -I/usr/include -I/home/joshuachp/.cache/paru/clone/neovim-git/src/build/src/nvim/auto -I/home/joshuachp/.cache/paru/clone/neovim-git/src/build/include
Compiled by joshuachp@blackbox

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
[log.log](https://github.com/neovim/neovim/files/6235159/log.log)

**Comment by joshuachp** [comment] 2021-03-31 08:51
Yep `-DCMAKE_BUILD_TYPE=RelWithDebInfo`

The `log` file is empty. I tried rm it and when the error happens it is empty

**Comment by mjlbach** [comment] 2021-03-31 08:53
Right, RelWithDebInfo and Debug have different default log levels :) 

https://github.com/neovim/neovim/blob/1186f7dd96b054d6a653685089fc845a8f5d2f27/contrib/local.mk.example#L34-L36

**Comment by joshuachp** [comment] 2021-03-31 08:55
Il try building it with debug

**Comment by joshuachp** [comment] 2021-03-31 09:09
```
NVIM v0.5.0-dev+1194-gc20ae3aad
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/gcc -D_FORTIFY_SOURCE=2 -march=native -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/joshuachp/.cache/yay/neovim-git/src/build/config -I/home/joshuachp/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/joshuachp/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/joshuachp/.cache/yay/neovim-git/src/build/include
Compiled by joshuachp@blackbox

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

[log.log](https://github.com/neovim/neovim/files/6235347/log.log)
[lsp.log](https://github.com/neovim/neovim/files/6235348/lsp.log)

**Comment by JonasUJ** [comment] 2021-03-31 09:31
> @JonasUJ The only faulty serialization could be on the server side, which seems unlikely if the issue is reproducible on rust-analyzer on a python language server (pyright? I'm assuming?). I guess deserialization could be failing, but it seems odd that it would be so hard to repro.

I was thinking the same, and yes I was using pyright. Since it's not present in joshuachp's log, maybe it's an unrelated error. I'll test with the minimal config in the evening.

**Comment by mjlbach** [comment] 2021-03-31 17:29
This seems like a legitimate bug in json_decode. If either of you can provide the exact steps for reproduction that would be great :) I think I'm going to have to get gdb attached when json_decode is invoked on the erroring call to see what happened.

**Comment by joshuachp** [comment] 2021-03-31 17:37
That's hard to say XD, it's something out of control I usually open and close nvim until it happens or keeping saving a file. It's probably better to use rust analyzer since it sends the progress when you started for `cargo check`.

**Comment by mjlbach** [comment] 2021-03-31 19:16
> I was starting to bisect the commits and found that I can not reproduce the bug with the bundle version of LuaJIT Neovim

The bundled luajit should be 2.1.0-beta3 as well. Are you saying that you can not reproduce with the bundle 2.1.0-beta3?

We could look at linux brew and the AUR recipe to see if something is off.

**Comment by mjlbach** [comment] 2021-03-31 20:17
Also @joshuachp does the AUR version not use the bundled luajit? Looking at the pkg-build it was unclear to me.

**Comment by joshuachp** [comment] 2021-03-31 20:22
I believe it doesn't. It doesn't even use the make file, and it doesn't appear in the log. After rebuilding it with LuaJIT 2.0.5 
```
NVIM v0.5.0-dev+1196-gd55a69168
Build type: RelWithDebInfo
LuaJIT 2.0.5
```

**Comment by JonasUJ** [comment] 2021-03-31 21:20
> Just to confirm, @JonasUJ if you build from source (directly, not using linux brew) do you still see the issue?

No I don't :) Been testing for some 15 minutes with no problems yet, whereas before it took 15 seconds.
```
❯ nvim --version
NVIM v0.5.0-dev+1196-gd55a69168
Build type: RelWithBedInfo
LuaJIT 2.1.0-beta3
```

**Comment by joshuachp** [comment] 2021-03-31 21:24
FTR
```
a32aeadc6878305658fb3939830e6abaef587e40 is the first bad commit
commit a32aeadc6878305658fb3939830e6abaef587e40
Author: Mike Pall <mike>
Date:   Tue Mar 23 00:35:46 2021 +0100

    Handle on-trace OOM errors from helper functions.
```

**Comment by mjlbach** [comment] 2021-03-31 23:37
@joshuachp That's for your excellent bisect :) This seems to be a luajit issue, but I'll leave the issue open because we should collect additional reports, and hopefully someone can find a reproduction so we can file a bug upstream.

For others running into this issue, **if you clone and build neovim from master (not using an AUR helper, COPR, PPA), we vendor an earlier version of luajit which does not have this issue**

**Comment by joshuachp** [comment] 2021-04-01 06:12
That's great to hear, thank you for your time

**Comment by mattsacks** [comment] 2021-04-01 20:03
For anyone using Homebrew, I was able to solve this by doing the following:

```fish
cd (brew --repo homebrew/core)
nvim Formula/luajit.rb # you may need to use another editor if your neovim was broken like mine
```

On line 5, you should see:
```ruby
  head "https://luajit.org/git/luajit-2.0.git", branch: "v2.1"
```

You'll want to change that to:
```ruby
  head "https://luajit.org/git/luajit-2.0.git", tag: "v2.1.0-beta2"
```

Finally, run `brew uninstall --ignore-dependencies luajit; brew install luajit --HEAD`

**Comment by ahmedelgabri** [comment] 2021-05-29 20:03
I started to get this error today after I updated my flakes (_I'm using https://github.com/nix-community/neovim-nightly-overlay, which is apparently now pulling from the [`contrib/`](https://github.com/neovim/neovim/tree/master/contrib) here_) & so I was wondering if we can pin the luajit version inside of the overlay too?

**Comment by mjlbach** [comment] 2021-05-29 20:06
I'm guessing it was https://github.com/NixOS/nixpkgs/pull/124110

Happy to take a PR, otherwise I can get to it probably tomorrow. I think we should modify the contrib flake @teto 

side note, I talked to @bfredl about this and one solution on the docket is to switch to https://openresty.org/en/lua-cjson-library.html instead of json_encode/decode. I'm planning to do this, but I'm currently in the middle of conference season for school.

**Comment by atcol** [comment] 2021-05-29 22:21
> I started to get this error today after I updated my flakes (_I'm using https://github.com/nix-community/neovim-nightly-overlay, which is apparently now pulling from the [`contrib/`](https://github.com/neovim/neovim/tree/master/contrib) here_) & so I was wondering if we can pin the luajit version inside of the overlay too?

I also got this error today and have found using [this Neovim-Overlay commit](https://github.com/nix-community/neovim-nightly-overlay/commit/125b7af69ec99e79749877cd820d614f35a64a29) works for me.

**Comment by mjlbach** [comment] 2021-05-29 22:22
FYI this is why I designed the overlay the way it is, it bundles a nixpkgs checkout (by default, which you can override of course), so the behavior of  given overlay commit *should* always be the same. I recommend pinning the overlay until I override the luajit version.

**Comment by tstelzer** [comment] 2021-05-30 09:20
@atcol @mjlbach could you elaborate on how to pin the working commit in the overlay?

**Comment by lblasc** [comment] 2021-05-30 13:36
This looks like pcall stack corruption, I think it starts from [this line](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/rpc.lua#L27), upsteam issue: https://github.com/LuaJIT/LuaJIT/issues/704

It should be solved by luajit 2.1 HEAD
Fix for nixpkgs: https://github.com/NixOS/nixpkgs/pull/124959

**Comment by mjlbach** [comment] 2021-05-30 16:15
I'm going to close this then, as it's an upstream issue that has been fixed. Thanks for the info @lblasc!

**Closed by mjlbach** 2021-05-30 16:15 UTC
Labels: bug, lsp

**Comment by mjlbach** [comment] 2021-06-05 17:52
The fix is now in nixpkgs-unstable for those wondering:

https://nixpk.gs/pr-tracker.html?pr=124959
