### ISSUE TITLE
Syntax highlighting fails intermittently, but often, on large Jenkinsfiles

### ISSUE THREAD

**Issue by bgshacklett** [neovim/neovim#17147] opened 2022-01-20 14:25 UTC
### Neovim version (nvim -v)

NVIM v0.7.0-dev+716-g9a0196d24

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

macOS 10.15.7

### Terminal name/version

iterm2 Build 3.4.14

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

Open a large Jenkinsfile and navigate to the bottom:
```
nvim --clean
:e Jenkinsfile
:syntax on
<shift>+G
```

### Expected behavior

Syntax highlighting should be correct.

### Actual behavior

Intermittently (but often), syntax highlighting will default to that of a string or heredoc, effectively rendering it useless.

**Comment by bgshacklett** [comment] 2022-01-20 14:30
Hello all,

I'm aware that this description is a bit light on details due to the lack of a specific file to open. Unfortunately I cannot share the Jenkinsfile that is causing me the most difficulty, as it contains proprietary details. I'll be looking through publicly available files to find a specific file which demonstrates the same behavior.

**Comment by clason** [comment] 2022-01-20 14:34
If Vim behaves the same, that is probably an issue with the syntax file (`groovy.vim`, I believe). Once you have a minimal reproducing example, the right course of action would be to contact the maintainer, who is listed at the top of each syntax file:
```
" Maintainer:	Tobias Rapp <yahuxo+vim AT mailbox.org>
```

**Comment by bgshacklett** [comment] 2022-01-29 18:41
I got a response indicating that there's something of a known issue with long string syntax ranges in Vim, because it doesn't calculate syntax based on the entire file. A suggested workaround, which appears to do the job, is to set: `:syntax sync fromstart`.

I've added `autocmd BufEnter * :syntax sync fromstart` to my `$HOME/.config/nvim/after/ftplugin/groovy.vim` file and I have not been able to reproduce the problem since. I suspect there's a better way to handle this, but I'm not much of a vimscript expert.

One noted downside to the above is that it can cause some performance degradation, because Vim has to do more work to calculate syntax information. I haven't seen it as an issue so far, but I'll definitely be on the lookout for it.

Perhaps there's something of a middle ground between the current behavior and rendering the entire file. Maybe it could continue looking for an end to whatever syntax type/region is currently set if it's not found within the standard "window"?

**Comment by lewis6991** [comment] 2022-02-18 17:05
You may also want to check out https://github.com/martinda/Jenkinsfile-vim-syntax

> I've added autocmd BufEnter * :syntax sync fromstart to my $HOME/.config/nvim/after/ftplugin/groovy.vim file and I have not been able to reproduce the problem since. I suspect there's a better way to handle this, but I'm not much of a vimscript expert.

Almost all filetypes will experience this issue in some form if the buffer is large enough. It is a fundamental issue of vim syntax highlighting. This was one of the many reasons that lead to us adding support for treesitter highlighting that aims to be more accurate for larger files.

> Perhaps there's something of a middle ground between the current behavior and rendering the entire file. Maybe it could continue looking for an end to whatever syntax type/region is currently set if it's not found within the standard "window"?

Vim syntax highlighting has a feature for dealing with this, see `:help syn-sync`. `:syntax sync fromstart` is a brute force "sync everything", but it is possible to tune it to lower thresholds. With that said, there won't be an ideal solution. The default runtime files are probably tuned to 95% of use cases.

Because there is no real scope for a solution for this other than the workaround mentioned, or to add a groovy treesitter parser with query highlights, I'm going to close this.

**Closed by lewis6991** 2022-02-18 17:05 UTC
Labels: bug-vim, syntax
