### ISSUE TITLE
Nvim crashes when opening a file named in Chinese

### ISSUE THREAD

**Issue by SteveLauC** [neovim/neovim#21612] opened 2023-01-01 13:22 UTC
### Neovim version (nvim -v)

v0.8.1

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Fedora 36 (with kernel 6.0.15-200.fc36.x86_64）

### Terminal name/version

Alacritty 0.10.1 (I am running nvim inside tmux, if this matters)

### $TERM environment variable

tmux-256color

### Installation

system package manager

### How to reproduce the issue

1. Just execute 
   
    ```shell
    $ nvim ElasticSearch底层搜索引擎
    ```

2. Then you will get
    
    ```
    E325: ATTENTION
    Found a swap file by the name "~/.local/state/nvim/swap//%home%steve%Documents%Notes%database%lucene%articles%ElasticSearch底层搜索引擎.swp"
              owned by: steve   dated: Sun Jan 01 21:02:02 2023
             file name: ~steve/Documents/Notes/database/lucene/articles/ElasticSearch底层搜索引擎
              modified: no
             user name: steve   host name: fedora
            process ID: 68868
    While opening file "ElasticSearch底层搜索引擎"
          CANNOT BE FOUND
    (1) Another program may be editing the same file.  If this is the case,
        be careful not to end up with two different instances of the same
        file when making changes.  Quit, or continue with caution.
    (2) An edit session for this file crashed.
        If this is the case, use ":recover" or "vim -r ElasticSearch底层搜索引擎"
        to recover the changes (see ":help recovery").
        If you did this already, delete the swap file "/home/steve/.local/state/nvim/swap//%home%steve%Documents%Notes%database%lucene%articles%ElasticSearch底层搜索引擎.sw
    p"
        to avoid this message.
    
    Swap file "~/.local/state/nvim/swap//%home%steve%Documents%Notes%database%lucene%articles%ElasticSearch底层搜索引擎.swp" already exists!
    [O]pen Read-Only, (E)dit anyway, (R)ecover, (D)elete it, (Q)uit, (A)bort:
    ```

    I don't think it is the first case that there are mutliple processes editing this file

3. Input `D` to exit the above TUI interface, then it just crashes with the following error message:
    
     ```
    nvim: /builddir/build/BUILD/neovim-0.8.1/src/nvim/ui_compositor.c:582: ui_comp_raw_line: Assertion `attrs[i] >= 0' failed.
                           [1]    73660 IOT instruction (core dumped)  nvim ElasticSearch底层搜索引擎
     ```

   And it messed my terminal up:

   
   ![Screenshot from 2023-01-01 21-19-06](https://user-images.githubusercontent.com/96880612/210171960-bd99e92d-09ed-4b63-84e2-68c616ba5423.png)

### Expected behavior

No error should occur

### Actual behavior

It crashed...

**Comment by SteveLauC** [comment] 2023-01-01 13:24
Not quite sure if this issue is related to Chinese, maybe it is just these characters that are causing this problem.

Feel free to ask me to provide any information that may help the debugging! Thank you guys for this great editor:)

**Comment by zeertzjq** [comment] 2023-01-01 13:38
This is similar to #15024 #20272

And I cannot reproduce this one either

**Comment by justinmk** [comment] 2023-01-01 14:16
> v0.8.1
 
please try the latest stable version, and also the dev/nightly

**Comment by SteveLauC** [comment] 2023-01-02 01:28
Thanks for the quick response!

### NVIM v0.9.0-dev-590+g6ba34e21f
```shell
$ nvim --version|head -1
NVIM v0.9.0-dev-590+g6ba34e21f

$ nvim ElasticSearch底层搜索引擎

$ echo $?
134
```
It just panicked without any error message

### NVIM v0.8.2
```shell
$ bob use stable
Jan 02 09:19:55.913  INFO stable is already installed and used!

$ nvim --version|head -1
NVIM v0.8.2

$ nvim ElasticSearch底层搜索引擎
```
The editor interface was successfully loaded, but it looks a little bit weird:
![Screenshot from 2023-01-02 09-23-13](https://user-images.githubusercontent.com/96880612/210189562-1bafd6cd-2ea2-400f-a413-359051e8f63c.png)
I am using [barbar.nvim](https://github.com/romgrk/barbar.nvim), and the file name displayed by this plugin is 
```
ElasticSearch底层搜索引擎<e5><bc>
```
instead of just
```
ElasticSearch底层搜索引擎
```

**Comment by zeertzjq** [comment] 2023-01-02 03:46
I'm able reproduce this with `barbar.nvim` and `require('bufferline').setup({ maximum_length = 20 })
`.

I think this is a combination of incorrect truncation by `barbar.nvim` and #20272

Duplicate of #20272

**Comment by zeertzjq** [comment] 2023-01-02 03:46
Duplicate of

**Comment by zeertzjq** [comment] 2023-01-02 03:46
Duplicate of #20272

**Closed by zeertzjq** 2023-01-02 03:46 UTC
Labels: encoding, bug-crash, unicode  💩, statusline
