### ISSUE TITLE
plugin clearing/adding highlights crashs neovim

### ISSUE THREAD

**Issue by cenomla** [neovim/neovim#10410] opened 2019-07-03 17:26 UTC
I recently started experiencing a crash do to adding/removing buffer highlights via the functions `nvim_buf_add_highlight` and `nvim_buf_clear_highlight`. This issue is triggered with the LanguageClient plugin. I have included an archive: [rep.tar.gz](https://github.com/neovim/neovim/files/3356152/rep.tar.gz) containing a script that reproduces the environment which causes the crash. Once the local nvim is launched the crash can be reproduced by repeatedly formatting and undoing. The included bare bones `init.vim` contains a mapping to format the entire file via `\f`. If any other info is needed let me know. I was able to reproduce this crash on `0.3.7` and `master`.

- `nvim --version`: master - [`0dc73b8`](https://github.com/neovim/neovim/commit/0dc73b87f10b67f9a8648cbf8936ba5f76a41def)
- `vim -u DEFAULTS` (version: ) behaves differently? Idk
- Operating system/version: 5.1.15-arch1-1-ARCH
- Terminal name/version: termite v15
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
I am unsure on how to reproduce without a minimal config

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
Crashes :(

### Expected behaviour
Does not crash

**Comment by justinmk** [comment] 2019-07-03 17:44
Thanks. Need a backtrace.  See [here](https://github.com/neovim/neovim/wiki/Development-tips#backtrace-linux) and please use the gdb command `thread apply all bt full`. Use the `tee` trick mentioned there to save the log to a file.

**Comment by cenomla** [comment] 2019-07-03 17:52
[bt.txt](https://github.com/neovim/neovim/files/3356250/bt.txt) here you go.

**Comment by justinmk** [comment] 2019-07-03 18:12
> * `nvim --version`: master

Does that mean 0dc73b8? If so please note that in the issue.

**Comment by glacambre** [comment] 2021-06-06 07:43
@cenomla Are you still encountering these crashes?

**Comment by cenomla** [comment] 2021-06-06 22:55
@glacambre just tested the case where I previously encountered the crash and it seems to be working now.

**Comment by glacambre** [comment] 2021-06-07 04:16
@cenomla Great, thanks! Let's close this issue since there's no reproducer :).

**Closed** 2021-06-08 16:59 UTC
Labels: bug, has:backtrace
