### ISSUE TITLE
Neovim freezes with Ctrl-Z, instead it should get temporarily suspended

### ISSUE THREAD

**Issue by 17Swagat** [neovim/neovim#14811] opened 2021-06-14 17:07 UTC
- `nvim --version`: NVIM v0.4.4
- Operating system/version: Windows 10
- Terminal name/version: Command Prompt
- 

### Actual behaviour
Whenever I try to temporarily suspend a neovim file and go back to my terminal using <Ctrl> + z , the entire Command-Prompt and neovim window freezes. It takes no input, just stuck. 

### Expected behaviour
Whenever I use vim that comes pre-installed in git, On using <Ctrl> + z, I'm able to go back to my terminal and whenever I want to come back to my file I just type  "ff" on the terminal. 
I expect the same behaviour in my neovim (windows).

Thank you.

**Comment by glacambre** [comment] 2021-06-15 05:20
Can you reproduce this issue with master/neovim nightly? Does manually running `:suspend` work?

**Comment by JSchrtke** [comment] 2021-06-15 10:02
This issue already exists, #6660.

According to that, there isn't really a canonical way of unsuspending a process in windows.

A workaround to avoid accidentally freezing neovim forever would be this

```vim
" avoid freezing the vim process forever, see
" https://github.com/neovim/neovim/issues/6660
if has('win32')
    nmap <C-z> <Nop>
endif
```

**Comment by 17Swagat** [comment] 2021-06-15 16:38
> Can you reproduce this issue with master/neovim nightly? Does manually running `:suspend` work?

No it still freezes on using :suspend. Do you have any other suggestions

**Comment by glacambre** [comment] 2021-06-16 09:34
@JSchrtke thank you for pointing out that this is a duplicate. I'll close this issue since #6660 is older.

**Closed by glacambre** 2021-06-16 09:34 UTC
Labels: bug
