### ISSUE TITLE
Native DAP

### ISSUE THREAD

**Issue by S-Spektrum-M** [neovim/neovim#17240] opened 2022-01-29 18:09 UTC
### Feature already in Vim?

No

### Feature description

[nvim-dap](https://github.com/mfussenegger/nvim-dap) does a fantastic job of adding DAP to neovim but it is external. Are there any plans to add DAP natively?

**Comment by clason** [comment] 2022-01-29 18:13
Duplicate of #11732

(short answer: not for the moment; there's not a compelling enough argument why "external" is a drawback.)

**Closed by clason** 2022-01-29 18:13 UTC
Labels: enhancement
