### ISSUE TITLE
lazyredraw: cursor lags after input characters

### ISSUE THREAD

**Issue by sQVe** [neovim/neovim#9452] opened 2019-01-04 06:48 UTC
- `nvim --version`:
```
NVIM v0.3.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: ) behaves differently?
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Operating system/version:
```
OS: Arch Linux
Kernel: x86_64 Linux 4.20.0-arch1-1-ARCH
```
- Terminal name/version:
```
rxvt-unicode (urxvt) v9.22
```
- `$TERM`:
```
rxvt-unicode-256color
```

### Steps to reproduce using `nvim -u NORC`

Cannot reproduce by simply using `nvim -u NORC`.

### Actual behaviour

When quickly inputting characters in INSERT mode the cursor lags behind. This behavior was introduced `0.3.2`.

![lag](https://user-images.githubusercontent.com/2284724/50676471-d0247d80-0ff4-11e9-89b1-0f530ae5c3e3.gif)

### Expected behaviour

The cursor should always be behind the inputted character. This works fine in `0.3.1` and below.

![no-lag](https://user-images.githubusercontent.com/2284724/50676477-d9ade580-0ff4-11e9-983c-32e43ffbbd82.gif)

---------------

I'm running the following settings for nvim: https://github.com/sQVe/dotfiles/tree/kodama/config/nvim. It is worth noting that this issue is less noticible if I remove `Plug 'itchyny/lightline.vim'` or `Plug 'sirver/ultisnips'`. 

I'd love some help and suggestions on how to debug/fix this.

**Comment by bfredl** [comment] 2019-01-04 09:34
In 0.3.2 we did a best-effort separation between "drawing" cursor and "input" cursor, but it is not always perfect. Likely the batching logic in `edit.c` relied on drawing setting the cursor position while inside a batch, we need to look into that.

**Comment by bfredl** [comment] 2019-01-04 09:43
Though I can't reproduce the issue with my config nor with `-u NONE`, maybe it requires a `TextChangedI` autocmd or something that is slowing inserting down.

**Comment by sQVe** [comment] 2019-01-04 09:49
@bfredl It might be worth noting that I only see this issue when I run my laptop on battery (ie. slower performance). I have been able to replicate the issue with `alacritty` too, so it is not isolated to the `rxvt-unicode` terminal. 

All my settings & dotfiles are located in the above link, if they are of any help.

**Comment by bfredl** [comment] 2019-01-04 09:53
I can reproduce with `set lazyredraw` but not without.

**Comment by justinmk** [comment] 2019-03-13 23:08
@sQVe is this still an issue on the current 0.4.x development version? The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by sQVe** [comment] 2019-03-16 19:56
@justinmk Hey! Sorry for taking some time but I've been away on a holiday. I just tried building from `git` and `nvim -v` outputs:

```
NVIM v0.4.0-401-g5c836d2ef
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/builds/neovim-git/src/neovim-git/build/config -I/tmp/builds/neovim-git/src/neovim-git/src -I/usr/include -I/tmp/builds/neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/builds/neovim-git/src/neovim-git/build/include
```

**I still see this issue** with the above build and `lazyredraw` enabled.

**Comment by sQVe** [comment] 2019-04-17 06:39
I just tried, out of curiosity, to enable `lazyredraw` again and **I'm now not seeing this issue**. `nvim -v` gives me this: 

```
NVIM v0.4.0-582-g3b7a4f233
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/builds/neovim-git/src/neovim-git/build/config -I/tmp/builds/neovim-git/src/neovim-git/src -I/usr/include -I/tmp/builds/neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/builds/neovim-git/src/neovim-git/build/include
```

**Comment by justinmk** [comment] 2019-04-27 15:22
@sQVe If you have time, would be great if you could bisect to the commit that changed (fixed) the behavior. 

Meanwhile I guess we can close this. Thanks for the followup.

**Closed by justinmk** 2019-04-27 15:22 UTC
Labels: display, performance, ui
