### ISSUE TITLE
Lua access to the wasm library

### ISSUE THREAD

**Issue by leiserfg** [neovim/neovim#31025] opened 2024-11-01 09:02 UTC
### Problem

Now that wasm was added for tree-sitter, I think it will be beneficial to have it exposed to lua. Wiring all the nvim API to wasm is not needed, just the fundamental  [WebAssembly](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface) API. 

### Expected behavior

The intention is to allow many plugins that now ship c/rust code to use it so plugin devs don't need to build for a gazillion platforms /  users don't need to have compilers installed.

**Comment by clason** [comment] 2024-11-01 09:06
Duplicate of https://github.com/neovim/neovim/issues/23579

(TL;DR: No plans right now; this is several orders of magnitude more complex than just putting wasmtime where the tree-sitter lib can find it.)

**Closed by clason** 2024-11-01 09:06 UTC
Labels: enhancement
