### ISSUE TITLE
Nvim for terminal does not print AltGr symbols

### ISSUE THREAD

**Issue by Vyber90** [neovim/neovim#12494] opened 2020-06-16 14:36 UTC
- `Nvim v0.4.3`:
- Nvim for Windows
- Every terminal (cmd, powershell) with and without [Windows Terminal](https://github.com/microsoft/terminal). Nvim-qt does perform correctly

### Steps to reproduce

When in insert mode, press `AltGr+[any key of the number row]`

### Actual behaviour

- In Spanish keyboard layout, Nvim writes the pressed number in the terminal (pressing `AltGr+2` prints `2`).
- In English keyboard layout, Nvim writes `5` while pressing `AltGr+4`, and writes nothing in other numerical keys (`AltGr+º` works correctly).

### Expected behaviour

- For the spanish layout, it should write, not the number, but the symbol next to it (using the previous example and a Spanish keyboard layout, a `@` should be displayed instead of a `2`).
- For the english layout, it should return `€` as the result for the `AltGr+4` instead of `5`.

**Comment by erw7** [comment] 2020-06-16 16:18
Duplicate of #11061.

**Closed by erw7** 2020-06-16 16:18 UTC
Labels: bug, duplicate
