### ISSUE TITLE
E303 when file name over 43 characters

### ISSUE THREAD

**Issue by DIWesser** [neovim/neovim#8231] opened 2018-04-05 02:40 UTC
- `nvim --version`: 0.2.2 from the [Ubuntu repository](https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable).
- Vim (version: 7.4 ) does not have this problem
- Operating system/version: KDE Neon
- Terminal name/version: Konsole and URXVT
- `$TERM`:
  - Konsole -- `xterm-color: command not found`
  - URXVT -- Opens new URXVT instance

So this is a weird one.

I have a couple markdown files with file names over 43 characters (that's including the '.md'). When I try to open them in neovim, I get an E303 message (`E303 Unable to open swap file for "/full/file/path.md", recovery impossible`).

I can still open the file once clearing the error. If I trim down the file names to 43 characters or less, the error goes away.

Things I've tried so far:  

- `nvim -u NORC`
- `nvim-u NONE`
- Changing the file name, but keeping it the same length.

**Comment by jamessan** [comment] 2018-04-05 02:44
Sounds like it may be the same as https://github.com/neovim/neovim/issues/8137#issuecomment-373127706.

**Comment by DIWesser** [comment] 2018-04-05 03:43
I've just checked, the full path is only 156 characters.

**Comment by jamessan** [comment] 2018-04-05 03:53
And you're using eCryptfs (or maybe something similar)?

**Comment by DIWesser** [comment] 2018-04-05 03:59
I do have full disk encryption with LUKS.

**Comment by jamessan** [comment] 2018-04-05 04:12
Given that the error occurs for the exact same character length, I'm closing this as a duplicate of #8137.

You can give yourself some breathing room by changing where swap files are located by putting something like this in your init.vim -- `set directory^=$HOME/.vimswap//`.  The point is to use a directory that's not as deep as the default (`$HOME/.local/share/nvim/swap/`) so the expanded filenames run less risk of hitting the limit, while we figure out better permanent solution

**Closed by jamessan** 2018-04-05 04:12 UTC
