### ISSUE TITLE
Homebrew HEAD not compiling

### ISSUE THREAD

**Issue by djensenius** [neovim/neovim#13771] opened 2021-01-16 23:11 UTC
- Operating system/version: macOS 11.1
- Terminal name/version: iTerm2 3.4.3
- `$TERM`: tmux-256color

### Steps to reproduce

```
brew install neovim --HEAD
```

I have tried suggestions for removing, unlinking, rebuilding luajit as suggested here: https://github.com/neovim/neovim/issues/13529

### Actual behaviour
```
❯ brew install neovim --HEAD
==> Downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.8/libmpack-lua-1.0.8.tar.gz
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/4b91349796a66e38e93acd77e6ca14212c869090429fd88271def2be5293d83f--libmpack-lua-1.0.8.tar.gz
==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.2-1.src.rock
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/0bc17975f0cf3981083172aa7da329b874e5780fa81494f5dd07d0665fcec23b--lpeg-1.0.2-1.src.rock
==> Downloading https://luarocks.org/manifests/kikito/inspect-3.1.1-0.src.rock
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/ecc1fa84ce4c83c9406f6d1202d4a88c80ede4a0a2bfd8d8d2bd54fd042226bb--inspect-3.1.1-0.src.rock
==> Downloading https://github.com/keplerproject/lua-compat-5.3/archive/v0.7.tar.gz
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/5f4e552e95b9a6223a5e4fabb7f04bf4b886057024507c76b1d5b803218c9363--lua-compat-5.3-0.7.tar.gz
==> Downloading https://github.com/luvit/luv/releases/download/1.30.0-0/luv-1.30.0-0.tar.gz
Already downloaded: /Users/david/Library/Caches/Homebrew/downloads/a9ce5a949370965d8f0fe70a47e7d102a3b4b6b831dbd4d088a83bbe1c00a3a2--luv-1.30.0-0.tar.gz
==> Cloning https://github.com/neovim/neovim.git
Updating /Users/david/Library/Caches/Homebrew/neovim--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at abbfaf286 logs: make kXDGCacheHome if it doesn't exist (#13758)
==> luarocks make --lua-dir=/usr/local/opt/luajit --tree=/private/tmp/neovim-20210116-4155-1txrl6u/deps-build
==> luarocks make --lua-dir=/usr/local/opt/luajit --tree=/private/tmp/neovim-20210116-4155-1txrl6u/deps-build
==> luarocks make --lua-dir=/usr/local/opt/luajit --tree=/private/tmp/neovim-20210116-4155-1txrl6u/deps-build
==> cmake . -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_INSTALL_PREFIX=/private/tmp/neovim-20210116-4155-1txrl6u/deps-bu
==> make install
==> cmake .. -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DLIBLUV_INCLUDE_DIR=/private/tmp/neovim-20210116-4155-1txrl6u/deps-bui
==> make install
Last 15 lines from /Users/david/Library/Logs/Homebrew/neovim/07.make:
cd /tmp/neovim-20210116-4155-1txrl6u/build/runtime && /usr/local/bin/luajit /tmp/neovim-20210116-4155-1txrl6u/scripts/genvimvim.lua /tmp/neovim-20210116-4155-1txrl6u/src/nvim /tmp/neovim-20210116-4155-1txrl6u/build/runtime/syntax/vim/generated.vim /tmp/neovim-20210116-4155-1txrl6u/build/funcs_data.mpack
cd /tmp/neovim-20210116-4155-1txrl6u/build/runtime/pack/dist/opt/vimball && /usr/local/Cellar/cmake/3.19.3/bin/cmake -E copy_directory /tmp/neovim-20210116-4155-1txrl6u/runtime/pack/dist/opt/vimball /tmp/neovim-20210116-4155-1txrl6u/build/runtime/pack/dist/opt/vimball
[100%] Generating pack/dist/opt/matchit/doc/tags
cd /tmp/neovim-20210116-4155-1txrl6u/build/runtime/pack/dist/opt/matchit && /usr/local/Cellar/cmake/3.19.3/bin/cmake -E copy_directory /tmp/neovim-20210116-4155-1txrl6u/runtime/pack/dist/opt/matchit /tmp/neovim-20210116-4155-1txrl6u/build/runtime/pack/dist/opt/matchit
cd /tmp/neovim-20210116-4155-1txrl6u/build/runtime && /usr/local/Cellar/cmake/3.19.3/bin/cmake -E copy_directory /tmp/neovim-20210116-4155-1txrl6u/runtime/doc doc
cd /tmp/neovim-20210116-4155-1txrl6u/build/runtime/pack/dist/opt/matchit && /tmp/neovim-20210116-4155-1txrl6u/build/bin/nvim -u NONE -i NONE -e --headless -c helptags\ doc -c quit
cd /tmp/neovim-20210116-4155-1txrl6u/build/runtime/pack/dist/opt/vimball && /tmp/neovim-20210116-4155-1txrl6u/build/bin/nvim -u NONE -i NONE -e --headless -c helptags\ doc -c quit
cd /tmp/neovim-20210116-4155-1txrl6u/build/runtime && /tmp/neovim-20210116-4155-1txrl6u/build/bin/nvim -u NONE -i NONE -e --headless -c helptags\ ++t\ doc -c quit
E5010: Failed to create directory /privateE/tmp/neovim5010: Failed to create directory /private/tmp/neovim-20210116-4-155-1txrl2021016u/.brew16-4155-1txrl6u/.brew_home/.cache for writing logs: file already exists_home/.cache for writing logs: file already existsmake[2]: *** [runtime/pack/dist/opt/vimball/doc/tags] Error 1
make[2]: *** Deleting file `runtime/pack/dist/opt/vimball/doc/tags'
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [runtime/doc/tags] Error 1
make[2]: *** Deleting file `runtime/doc/tags'
make[1]: *** [runtime/CMakeFiles/runtime.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
```

### Expected behaviour

It installs.

**Comment by mjlbach** [comment] 2021-01-16 23:17
It's do to this PR. https://github.com/neovim/neovim/commit/abbfaf286f26989b18377d4238f3cea9dc281149 I'll fix it.

**Comment by mjlbach** [comment] 2021-01-16 23:23
@djensenius I'm a little confused, I just installed neovim --HEAD from homebrew without any issues.

**Comment by mjlbach** [comment] 2021-01-16 23:23
```
==> Summary
🍺  /usr/local/Cellar/neovim/HEAD-abbfaf2: 1,455 files, 21.3MB, built in 2 minutes 26 seconds

 ~                                                                                                                                                                          3m 34s
```

**Comment by djensenius** [comment] 2021-01-16 23:31
Huh. Any more system info I can provide? I just tried a restart to make sure nothing was hanging around that shouldn't be. 

Still getting the same thing... 

```
HEAD is now at abbfaf286 logs: make kXDGCacheHome if it doesn't exist (#13758)
...
E5010: Failed to create directory /privateE/tmp/neovim5010: Failed to create directory /private/tmp/neovim-20210116-4-155-1txrl2021016u/.brew16-4155-1txrl6u/.brew_home/.cache for writing logs: file already exists_home/.cache for writing logs: file already existsmake[2]: *** [runtime/pack/dist/opt/vimball/doc/tags] Error 1
make[2]: *** Deleting file `runtime/pack/dist/opt/vimball/doc/tags'
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [runtime/doc/tags] Error 1
make[2]: *** Deleting file `runtime/doc/tags'
make[1]: *** [runtime/CMakeFiles/runtime.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by djensenius** [comment] 2021-01-16 23:34
More system info:

```
❯ brew --version
Homebrew 2.7.5-10-g8869208
Homebrew/homebrew-core (git revision c91104; last commit 2021-01-16)
Homebrew/homebrew-cask (git revision 621a49; last commit 2021-01-16)

~ took 1s
❯ uname -a
Darwin judy.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

**Comment by mjlbach** [comment] 2021-01-16 23:48
I can reproduce it, it seems to only occur (for me) if I purge homebrew's cache. I'll work on a fix.

**Comment by mjlbach** [comment] 2021-01-17 00:32
Should be fixed by #13773

**Comment by smutch** [comment] 2021-01-17 00:46
I can confirm that the fix works for me to resolve the same issue. Thanks for the speedy resolution!

**Comment by mjlbach** [comment] 2021-01-17 00:48
Sorry for the hassle! Ironically I test on nix/macos, but because I built macos from source and manually set my HOME to a mutable directory with nix, I didn't catch this before we merged the last PR.

**Closed** 2021-01-17 04:40 UTC
Labels: bug
