### ISSUE TITLE
Wrapping comment lines (reStructuredText) not working correctly in Neovim

### ISSUE THREAD

**Issue by cpkio** [neovim/neovim#12793] opened 2020-08-26 13:52 UTC
- `nvim --version`: **NVIM v0.5.0-635-g8c49e3d50**
- `vim -u DEFAULTS` (version: ) behaves differently? **YES**
- Operating system/version: **Windows 10 x64**

NeoVim behaves differently with Vim. With https://github.com/gu-fan/riv.vim (reStructuredText plugin) installed, NeoVim does not wrap commented lines with `gwip` as expected. Vim in the same situation and same configuration wraps correctly.

The correct wrapping comes from RIV behaviour, standard `rst.vim` files do not provide this wrapping feature (tested — Vim without RIV does not wrap commented strings as expected, does not care about `comments=fb:..` in `ftplugin\rst.vim` and such).

### Actual behaviour (Neovim)

![2020-08-26_16-18-46](https://user-images.githubusercontent.com/1917113/91310054-10340780-e7ba-11ea-976f-afedb93c18d9.gif)

### Expected behaviour (Vim)

![2020-08-26_16-18-16](https://user-images.githubusercontent.com/1917113/91310039-0ca08080-e7ba-11ea-92c6-ae3ca2cc0b88.gif)

### Partial solution

Delete `neovim\share\nvim\runtime\ftplugin\rst.vim`, `neovim\share\nvim\runtime\indent\rst.vim`, `neovim\share\nvim\runtime\syntax\rst.vim`.

I suppose this is some kind of loaded options priority error: Vim with standard `rst.vim` plugins loads RIV and works fine, Neovim loads RIV but some options are not set correctly, resulting in erroneous working.

**Comment by erw7** [comment] 2020-08-26 16:10
@cpkio Those files in neovim's runtime(`runtime/{ftplugin,indent,syntax}.rst.vim`) seem to be old compared to the vim ones. Would replacing it with a vim file solve the problem?

**Comment by cpkio** [comment] 2020-08-27 07:16
The files that I delete from Neovim installation are not old; they are _identical_ to those you get from `vim82rt.zip` at `ftp://ftp.vim.org/pub/vim/pc/`. My point is that Neovim for some reason gives priority to these runtime files, not to plugin-loaded ones.

**Comment by chrisbra** [comment] 2020-08-27 07:20
you can clone the vim runtime files and set the $VIMRUNTIME environment variable to those from vim and see if those work better

**Comment by cpkio** [comment] 2020-08-27 14:48
Setting $VIMRUNTIME to Vim82 files and starting Neovim results in a clean run without any plugins and configs. `gwip` does not wrap comment block as wanted. The same situation happens with Vim. Therefore, both Vim and Neovim do not wrap comments blocks on standard `.vim` files. The question still is, why Vim uses the plugin wrapping properly, and Neovim does not.

**Comment by erw7** [comment] 2020-08-27 16:35
This is not a neovim bug. It's a problem with your `&rtp` configuration. The following steps were taken to verify that the wrapping command worked correctly.

```
git clone https://github.com/gu-fan/riv.vim
cp -r riv.vim/after ~/.config/nvim
cp -r riv.vim/autoload ~/.config/nvim
cp -r riv.vim/ftplugin ~/.config/nvim
cp -r riv.vim/indent ~/.config/nvim
cp -r riv.vim/plugin ~/.config/nvim
cp -r riv.vim/syntax ~/.config/nvim
nvim -u NORC
:e test.rst
i.. This is an reStructerdText long comment line, that shuld be wrapped correctly in both Vim and Neovim, but only Vim does it right.<ESC>gwip
```

Probably in your environment, `&rtp` has the standard runtime followed by the RIV installation location. That's why the standard rst.vim is used instead of the RIV rst.vim. Set the location of the RIV at the beginning of the `&rtp` as shown in the following example, or try to copy the entire directory(`after, autoload, ftplugin, indent, plugin, syntax`) contained in the RIV to ~/.config/nvim.

```
cd
git clone https://github.com/gu-fan/riv.vim
nvim -u NORC --cmd 'set rtp^=/home/erw7/riv.vim'
```

**Comment by cpkio** [comment] 2020-08-30 12:27
My environment is Windows 10 x64, portable Vim and Neovim working from a USB drive. Portable installs does not use any `~` folders. All plugins are in `/pack` folder for both in Vim and Neovim, and both Vim and Neovim worked fine until this issue. Removing one plugin from `\Neovim\share\nvim\runtime\pack\user\start` and moving its files from a dedicated  plugin folder to a config folder to get it working seems more like a workaround. As noted, Vim has no problem with RTP priority on the same system, so how that is not a Neovim specific behaviour?

**Comment by justinmk** [comment] 2020-08-30 17:30
> Portable installs does not use any `~` folders

`~` in the example @erw7  gave is just an example. what is listed in `:echo &rtp` ?

**Comment by cpkio** [comment] 2020-08-31 09:35
I've set VIMRUNTIME to Vim directory and started Vim and Neovim. The `echo &rtp` output for each is:

```
VIM                                                            NEOVIM
                                                               C:\Users\user\AppData\Local\nvim
C:\Users\user/vimfiles                                         C:\Users\user\AppData\Local\nvim-data\site
I:\ConEmu\vim/vimfiles                                         I:\ConEmu\vim
I:\ConEmu\vim\pack\username\start\wildfire.vim                 I:\ConEmu\vim\pack\username\start\wildfire.vim
I:\ConEmu\vim\pack\username\start\vimwiki                      I:\ConEmu\vim\pack\username\start\vimwiki
I:\ConEmu\vim\pack\username\start\vimproc.vim                  I:\ConEmu\vim\pack\username\start\vimproc.vim
I:\ConEmu\vim\pack\username\start\vim-which-key                I:\ConEmu\vim\pack\username\start\vim-which-key
I:\ConEmu\vim\pack\username\start\vim-unimpaired               I:\ConEmu\vim\pack\username\start\vim-unimpaired
I:\ConEmu\vim\pack\username\start\vim-textobj-user             I:\ConEmu\vim\pack\username\start\vim-textobj-user
I:\ConEmu\vim\pack\username\start\vim-textobj-quotes           I:\ConEmu\vim\pack\username\start\vim-textobj-quotes
I:\ConEmu\vim\pack\username\start\vim-textobj-lastpat          I:\ConEmu\vim\pack\username\start\vim-textobj-lastpat
I:\ConEmu\vim\pack\username\start\vim-textobj-indent           I:\ConEmu\vim\pack\username\start\vim-textobj-indent
I:\ConEmu\vim\pack\username\start\vim-textobj-function         I:\ConEmu\vim\pack\username\start\vim-textobj-function
I:\ConEmu\vim\pack\username\start\vim-system-copy              I:\ConEmu\vim\pack\username\start\vim-system-copy
I:\ConEmu\vim\pack\username\start\vim-surround                 I:\ConEmu\vim\pack\username\start\vim-surround
I:\ConEmu\vim\pack\username\start\vim-sort-motion              I:\ConEmu\vim\pack\username\start\vim-sort-motion
I:\ConEmu\vim\pack\username\start\vim-signature                I:\ConEmu\vim\pack\username\start\vim-signature
I:\ConEmu\vim\pack\username\start\vim-ps1                      I:\ConEmu\vim\pack\username\start\vim-ps1
I:\ConEmu\vim\pack\username\start\vim-pandoc-syntax            I:\ConEmu\vim\pack\username\start\vim-pandoc-syntax
I:\ConEmu\vim\pack\username\start\vim-matchup                  I:\ConEmu\vim\pack\username\start\vim-matchup
I:\ConEmu\vim\pack\username\start\vim-lua                      I:\ConEmu\vim\pack\username\start\vim-lua
I:\ConEmu\vim\pack\username\start\vim-ingo-library             I:\ConEmu\vim\pack\username\start\vim-ingo-library
I:\ConEmu\vim\pack\username\start\vim-indentwise               I:\ConEmu\vim\pack\username\start\vim-indentwise
I:\ConEmu\vim\pack\username\start\vim-fugitive                 I:\ConEmu\vim\pack\username\start\vim-fugitive
I:\ConEmu\vim\pack\username\start\vim-custom-surround          I:\ConEmu\vim\pack\username\start\vim-custom-surround
I:\ConEmu\vim\pack\username\start\vim-commentary               I:\ConEmu\vim\pack\username\start\vim-commentary
I:\ConEmu\vim\pack\username\start\vim-autoread                 I:\ConEmu\vim\pack\username\start\vim-autoread
I:\ConEmu\vim\pack\username\start\vim-autopep8                 I:\ConEmu\vim\pack\username\start\vim-autopep8
I:\ConEmu\vim\pack\username\start\vim-autoformat               I:\ConEmu\vim\pack\username\start\vim-autoformat
I:\ConEmu\vim\pack\username\start\vim-abolish                  I:\ConEmu\vim\pack\username\start\vim-abolish
I:\ConEmu\vim\pack\username\start\undotree-rel_5.0             I:\ConEmu\vim\pack\username\start\undotree-rel_5.0
I:\ConEmu\vim\pack\username\start\textobj-word-column.vim      I:\ConEmu\vim\pack\username\start\textobj-word-column.vim
I:\ConEmu\vim\pack\username\start\targets.vim                  I:\ConEmu\vim\pack\username\start\targets.vim
I:\ConEmu\vim\pack\username\start\tabular                      I:\ConEmu\vim\pack\username\start\tabular
I:\ConEmu\vim\pack\username\start\sqlutil                      I:\ConEmu\vim\pack\username\start\sqlutil
I:\ConEmu\vim\pack\username\start\riv                          I:\ConEmu\vim\pack\username\start\riv
I:\ConEmu\vim\pack\username\start\nerdtree-5.0.0               I:\ConEmu\vim\pack\username\start\nerdtree-5.0.0
I:\ConEmu\vim\pack\username\start\nerdcommenter-2.5.1          I:\ConEmu\vim\pack\username\start\nerdcommenter-2.5.1
I:\ConEmu\vim\pack\username\start\lightline.vim                I:\ConEmu\vim\pack\username\start\lightline.vim
I:\ConEmu\vim\pack\username\start\Ionide-vim                    
I:\ConEmu\vim\pack\username\start\indentLine                   I:\ConEmu\vim\pack\username\start\indentLine
I:\ConEmu\vim\pack\username\start\haskell-vim                  I:\ConEmu\vim\pack\username\start\haskell-vim
I:\ConEmu\vim\pack\username\start\ghci.vim                     I:\ConEmu\vim\pack\username\start\ghci.vim
I:\ConEmu\vim\pack\username\start\fzf.vim                      I:\ConEmu\vim\pack\username\start\fzf.vim
I:\ConEmu\vim\pack\username\start\fzf                          I:\ConEmu\vim\pack\username\start\fzf
I:\ConEmu\vim\pack\username\start\ctrlp.vim                    I:\ConEmu\vim\pack\username\start\ctrlp.vim
I:\ConEmu\vim\pack\username\start\CommentFrame.vim              
I:\ConEmu\vim\pack\username\start\coconut.vim                  I:\ConEmu\vim\pack\username\start\coconut.vim
I:\ConEmu\vim\pack\username\start\base16-vim                   I:\ConEmu\vim\pack\username\start\base16-vim
I:\ConEmu\vim\pack\username\start\ale                          I:\ConEmu\vim\pack\username\start\ale
                                                               I:\ConEmu\vim\pack\username\start\Ionide-vim
                                                               I:\ConEmu\vim\pack\username\start\CommentFrame.vim
I:\ConEmu\vim\pack\CSS3-Syntax\start\vim-css3-syntax           I:\ConEmu\vim\pack\CSS3-Syntax\start\vim-css3-syntax
I:\ConEmu\vim                                                  C:\Neovim\lib\nvim
I:\ConEmu\vim\pack\username\start\vim-textobj-function\after   I:\ConEmu\vim\pack\username\start\vim-textobj-function\after
I:\ConEmu\vim\pack\username\start\vim-signature\after          I:\ConEmu\vim\pack\username\start\vim-signature\after
I:\ConEmu\vim\pack\username\start\vim-matchup\after            I:\ConEmu\vim\pack\username\start\vim-matchup\after
I:\ConEmu\vim\pack\username\start\tabular\after                I:\ConEmu\vim\pack\username\start\tabular\after
I:\ConEmu\vim\pack\username\start\riv\after                    I:\ConEmu\vim\pack\username\start\riv\after
I:\ConEmu\vim\pack\username\start\indentLine\after             I:\ConEmu\vim\pack\username\start\indentLine\after
I:\ConEmu\vim\pack\username\start\haskell-vim\after            I:\ConEmu\vim\pack\username\start\haskell-vim\after
I:\ConEmu\vim\pack\CSS3-Syntax\start\vim-css3-syntax\after     I:\ConEmu\vim\pack\CSS3-Syntax\start\vim-css3-syntax\after
I:\ConEmu\vim/vimfiles/after                                   C:\Users\user\AppData\Local\nvim-data\site\after
C:\Users\user/vimfiles/after                                   C:\Users\user\AppData\Local\nvim\after
```

There is no `$APPDATA\Local\nvim` folder existing. `$APPDATA\Local\nvim-data` has only a shada file. Still, Vim wraps text as expected, and Neovim does not.

**Comment by justinmk** [comment] 2020-08-31 20:50
sounds like https://github.com/neovim/neovim/issues/9390#issuecomment-450503224 but that was merged to 0.5 (master branch)...

**Comment by erw7** [comment] 2020-08-31 21:26
The following patch seems to fix this behavior. 

```C
diff --git a/src/nvim/ex_cmds2.c b/src/nvim/ex_cmds2.c
index 7a06cb7ca..de1e50253 100644
--- a/src/nvim/ex_cmds2.c
+++ b/src/nvim/ex_cmds2.c
@@ -2614,8 +2614,8 @@ static int add_pack_dir_to_rtp(char_u *fname)
       bool match = path_fnamencmp(rtp_ffname, ffname, fname_len) == 0;
       xfree(rtp_ffname);
       if (match) {
-        // Insert "ffname" after this entry (and comma).
-        insp = entry;
+        // Insert "ffname" before this entry (and comma).
+        insp = cur_entry;
       }
     }
```

However, from the following sources, I believe the current behavior is the same as that of vim. In fact, in my environment, vim and neovim work the same way. The reason for the different behavior in environment of @cpkio is not known if there is some kind of patch applied or if it is configured in vimrc or something else.

https://github.com/vim/vim/blob/2f1228463aa9ff62814f9732561b1849e5f01f75/src/scriptfile.c#L529-L530

**Comment by justinmk** [comment] 2020-09-01 01:22
@jamessan any thoughts on the above patch?

**Comment by cpkio** [comment] 2020-09-01 08:52
I've tested this issue again with only RIV plugin in `$vimruntime/pack/user/start` folder, still the same. @erw7 there are no patches applied, `vim/default.vim` used as vimrc. No Vim- or Neovim-related variables are set in user or system space.

1) `set VIMRUNTIME=C:\Temp\vim`
2) `dir c:\Temp\vim\pack\user\start\`
```
01.09.2020  10:59    <DIR>          ..
01.09.2020  10:59    <DIR>          fzf
01.09.2020  10:59    <DIR>          fzf.vim
01.09.2020  10:52    <DIR>          riv
```
3) `cd \Neovim\bin`
4) `nvim -u c:\temp\vim\defaults.vim` -> **not working**
5) `cd \Temp\vim`
6) `vim -u defaults.vim` -> **working**

**Comment by erw7** [comment] 2020-09-01 17:40
After rereading the `:h rtp`, I've come to the conclusion that it's wrong to put a system-wide package in `$VIMRUNTIME/pack` that applies to the entire system, like in environment of @cpkio. I think you should set up `XDG_CONFIG_DIRS` and install it there. I created #12829 because the current master is having problems handling `XDG_CONFIG_DIRS` and `XDG_DATA_DIRS` in WIndows.

Considering the above and the compatibility with vim, I don't think we should use the patch for  https://github.com/neovim/neovim/issues/12793#issuecomment-684050317

**Comment by erw7** [comment] 2020-09-01 17:55
@cpkio Where do you get your vim from? And what is that version?

**Comment by cpkio** [comment] 2020-09-01 18:13
@erw7 
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 28 2020 13:59:40)
MS-Windows 64-bit GUI/console version with OLE support
Included patches: 1-464
Compiled by tux0r@ROSAELEFANTC33A
```
from https://tuxproject.de/projects/vim/

**Comment by jamessan** [comment] 2020-09-02 01:27
> After rereading the `:h rtp`, I've come to the conclusion that it's wrong to put a system-wide package in `$VIMRUNTIME/pack` that applies to the entire system

Are you referring just to a user doing this or also to the packages we ship with nvim?  If it's the former, I agree in general since anything they do will be overwritten when they update.

If it's the latter, I'd be interested in more details.

**Comment by erw7** [comment] 2020-09-02 17:49
> Are you referring just to a user doing this or also to the packages we ship with nvim?

The former, of course.

**Comment by erw7** [comment] 2020-09-02 18:11
@cpkio The vim published at [www.vim.org](https://www.vim.org/download.php) does not behave like your environment. I think the vim you are using is customized by the distributor. I don't know where the neovim you're using came from, but it doesn't behave like a customized vim.  If you want to use a portable installation, create the file `Neovim/share/nvim/sysinit.vim` and customize it yourself.

**Comment by cpkio** [comment] 2020-09-02 19:31
@erw7 
At my home PC now; Windows 10 x64 (1803). Downloaded `vim82rt.zip` and `vim82w32.zip` from `https://www.vim.org/download.php#pc`. Extracted both, copied `riv`, `fzf` and `fzf.vim` folders to `\vim82\pack\user\start`, `cd \vim82`, `vim`. Everything works in Vim as expected to work, and does not in Neovim (repeated the `VIMRUNTIME` routine). That's not proof enough?

**Comment by erw7** [comment] 2020-09-03 16:13
I found the cause. When I changed the name of the vim extraction destination from `vim82`, I got the same phenomenon as  environment of @cpkio. In that case, `$VIM` and `$VIMRUNTIME` will be the same, and this is what happens.

```
2. In a system-wide Vim directory, for preferences from the system administrator.
3. In $VIMRUNTIME, for files distributed with Vim.
```

I think `$VIMRUNTIME` should be kept as clean as possible, because as shown in `:h rtp` above, everything below `$VIMRUNTIME` is where the files distributed by vim (or neovim) are placed. IMO Therefore, you should not place user-installed packages to take advantage of the fact that this phenomenon causes package files to take precedence over files in `$VIMRUNTIME`.

**Comment by cpkio** [comment] 2020-09-04 13:35
I dont understand where you mean to put the user plugins… Could you show the directories structure and vimrc settings (if any)?

**Comment by erw7** [comment] 2020-09-04 16:50
> I dont understand where you mean to put the user plugins [for a portable install]… Could you show the directories structure and vimrc settings (if any)?

As an example.

```vim
let s:rtp = join(
  \  insert(
  \    split(&rtp, ','), fnamemodify($VIM, ':p:h:h') .. '\nvimfiles', 1), ',')
set rtp&
let &rtp = s:rtp
set pp&
let &pp = s:rtp
unlet s:rtp
```

Create a file `Neovim\share\nvim\sysinit.vim` as shown above. Install the package under `Neovim\share\nvimfiles\pack\username\start`.

In the case of vim, you can install the package under `$VIM\vimfiles\pack\username\start`. The `$VIM\vimrc` is not required.

**Closed** 2020-09-08 04:37 UTC
Labels: platform:windows, question, runtime
