### ISSUE TITLE
lsp: jump_to_location fails to switch to specified window

### ISSUE THREAD

**Issue by saahiluppal** [neovim/neovim#14163] opened 2021-03-19 10:57 UTC
Error come and go so fast, that im not even able to read or even copy (i guess error vanishes with another key press).
But today i got it

```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:881: Failed to switch to window 1002
```

I am not sure if error is same every time, but i can confirm this is related to ```vim.schedule lua callback```

I don't know how to deal with this.

**Comment by mjlbach** [comment] 2021-03-19 11:04
Can you try updating to the current master? based on the line numbering I'm guessing your build is out of date.

**Comment by saahiluppal** [comment] 2021-03-19 11:15
Updated to the current master.
Will let you know if the error pops again

**Comment by mjlbach** [comment] 2021-03-19 17:22
I'm confused because your commit is correct but the line number looks off in util.lua which is provided in the runtime directory. Some information that should be in your bug report (for now, and for future reference)

* How did you install nvim? Is there an old copy of neovim somewhere that could be colliding with your runtime path?
* Which language server are you running? This is an lsp error
* What file does this reproduce on
* What is your system configuration

**Comment by saahiluppal** [comment] 2021-03-19 17:55
nvim installation -> Built from source
language servers running -> pyright and gopls
reproduced on -> python file (.py)
Here is my <a href='https://github.com/saahiluppal/shellify/blob/master/init.vim'>init.vim</a>

**Comment by mjlbach** [comment] 2021-03-19 17:57
Well, it's not reproducible on any python file as I've never run into this issue :)

**Comment by saahiluppal** [comment] 2021-03-20 07:07
I've met this issue couple of times since past week.

**Comment by mjlbach** [comment] 2021-03-20 07:09
I'll need a reproduction in order to solve it. Can you elaborate on "built from source"? Did you run `make install` to ensure the latest lua files on on your runtime path?

**Comment by saahiluppal** [comment] 2021-03-20 07:22
```
$ git clone https://github.com/neovim/neovim
$ cd neovim
$ make CMAKE_BUILD_TYPE=RelWithDebInfo
$ sudo make install
```

Yes i did make install

**Comment by mjlbach** [comment] 2021-03-20 07:28
Ok, great. I'll revisit this issue once you post a minimal reproduction.

**Comment by timcole** [comment] 2021-03-27 11:49
Hello, Just jumping in here to say I'm experiencing the same issue.
Unfortunately, I can't really reproduce it myself if I try, it just happens at times while I type.
`NVIM v0.5.0-dev+9481310c2`

Installed from brew on macOS 11.2.3 20D91 x86_64: `brew upgrade neovim --fetch-HEAD`

![](https://t.pics/jxQQitaJJdM.png)

LSP Config
```vim
nnoremap gd :lua vim.lsp.buf.definition()<CR>
nnoremap rn :lua vim.lsp.buf.rename()<CR>
nnoremap <S-k> :lua vim.lsp.buf.hover()<CR>)

inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
set completeopt=menuone,noinsert
set shortmess+=c

let g:completion_matching_strategy_list = ['exact', 'substring', 'fuzzy']
let g:completion_trigger_on_delete = 1
lua require'lspconfig'.rls.setup{ on_attach=require'completion'.on_attach }
lua require'lspconfig'.tsserver.setup{ on_attach=require'completion'.on_attach }
```
Happens both in typescript and rust files.
Will keep trying to find reliable reproduction steps.

**Comment by mjlbach** [comment] 2021-03-27 15:31
Can you reproduce this without completion-nvim?

**Comment by timcole** [comment] 2021-03-29 05:45
Not a perfect demo or reproduction step but does appear to not happen the same way (if at all) when completion is disabled.
(Repo/file used in videos [timcole/thumb.yt](https://github.com/timcole/thumb.yt/blob/main/src/scrape.ts) file `src/scrape.ts`)

completion disabled

https://user-images.githubusercontent.com/6754577/112791586-db2db300-902f-11eb-9a7e-b853745b907f.mov

completion enabled

https://user-images.githubusercontent.com/6754577/112791601-e2ed5780-902f-11eb-86fd-e81347acacb4.mov

**Comment by mjlbach** [comment] 2021-03-29 05:47
@timcole Are you using compe or completion.nvim?

**Comment by timcole** [comment] 2021-03-29 05:49
I'm using nvim-lua/completion-nvim
[my init.vim](https://github.com/timcole/dotfiles/blob/%F0%9F%A6%84/nvim/init.vim#L15)

**Comment by mjlbach** [comment] 2021-03-29 05:50
Can you try using compe? completion-nvim has not seen updates in awhile.

**Comment by timcole** [comment] 2021-03-29 06:00
Quick initial testing with default config seems to be good! Will keep using it throughout the workday and report back to make sure. 🙂 Thanks for the quick help/suggestions!

**Comment by mjlbach** [comment] 2021-03-29 06:02
I'm closing as I believe this is an issue with completion-nvim, and not a bug in core. If this isn't the case, feel free to reopen or file another issue.

**Closed by mjlbach** 2021-03-29 06:02 UTC
Labels: bug, lsp

**Comment by saahiluppal** [comment] 2021-03-29 16:11
Hey @timcole,
I'm struggling dealing with nvim-compe,
Is this configuration right
https://gist.github.com/saahiluppal/241ba70a3f6cfaaa21420a9373fef757
