### ISSUE TITLE
":terminal foo" doesn't open terminal on the same active virtualenv

### ISSUE THREAD

**Issue by itsmenewbie03** [neovim/neovim#28990] opened 2024-05-25 00:40 UTC
### Problem

Before the 0.10 update, using toggleterm has no issues working with python's virtualenvs. Now it doesn't open on the same active `venv`. Running `:ter which pip` provides the expected output in which pip is under the venv subdirectory of the current directory. However running `:ter` and executing `which pip` inside, the output is `/bin/pip` which tells that the current terminal is not under the `venv`.

### Steps to reproduce

1. `mkdir venvtest`
2. `cd venvtest`
3.  copy minimal.lua
4. `python -m virtualenv venv`
5. `source venv/bin/activate`
6. `nvim --clean -u minimal.lua`
7. `:ter which pip`
8. `:ter`
9. inside the terminal execute `which pip`

### Expected behavior

`:ter` should be opened in the same virtualenv if neovim is ran on an active virtualenv

### Neovim version (nvim -v)

0.10

### Vim (not Nvim) behaves the same?

yes, vim 9.1

### Operating system/version

EndeavourOS

### Terminal name/version

kitty 0.33.1

### $TERM environment variable

xterm-kitty

### Installation

AUR

**Comment by zeertzjq** [comment] 2024-05-25 01:22
Cannot reproduce.

**Comment by itsmenewbie03** [comment] 2024-05-25 02:33
Here's exactly what I'm doing 

https://github.com/neovim/neovim/assets/89230263/c2112b4d-167c-437d-8375-bd260e67d979

**Comment by bluss** [comment] 2024-05-25 10:02
`:ter which pip`  runs which without a shell. `:ter` starts your shell (see `set shell?` for which shell it starts). I think the explanation will be in your shell configuration.

Suppose your shell is `bash`.
Experiment you can do in the same virtualenv:

1. quit neovim
2. which pip
3. bash -c "which pip" 
4. bash; which pip    # Nested shell, just like :ter starts a shell "nested"

and compare outputs.

**Comment by justinmk** [comment] 2024-05-25 10:49
> `:ter which pip` runs which without a shell. `:ter` starts your shell

Right.

**Closed by justinmk** 2024-05-25 10:49 UTC
Labels: bug, terminal, needs:repro

**Comment by wookayin** [comment] 2024-05-26 04:21
I'm also pretty sure this is a shell configuration problem specific to your setup. print `$PATH` in each of the shell. In your bashrc/zshrc, etc. (only executed for login shell or interactive shell) there might be a line which re-orders `$PATH`.

**Comment by itsmenewbie03** [comment] 2024-05-26 04:25
> I'm also pretty sure this is a shell configuration problem specific to your setup. print `$PATH` in each of the shell. In your bashrc/zshrc, etc. (only executed for login shell or interactive shell) there might be a line which re-orders `$PATH`.

this is the output of `echo $PATH`
```bash
/home/itsmenewbie03/.nvm/versions/node/v20.13.1/bin:/bin:/home/itsmenewbie03/Desktop/WareHouse/Python/Random/hot-ai/venv/bin:/home/itsmenewbie03/.nvm/versions/
node/v20.13.1/bin:/bin:/home/itsmenewbie03/.nvm/versions/node/v20.13.1/bin:/bin:/home/itsmenewbie03/.bun/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/andro
id-sdk/platform-tools:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/hom
e/itsmenewbie03/bin:/home/itsmenewbie03/.cargo/bin:/usr/local/java/jdk19/bin:/opt/android-sdk/platform-tools:/home/itsmenewbie03/.local/share/bin:/opt/nvim-lin
ux64/bin
```

**Comment by itsmenewbie03** [comment] 2024-05-31 03:41
> `:ter which pip` runs which without a shell. `:ter` starts your shell (see `set shell?` for which shell it starts). I think the explanation will be in your shell configuration.
> 
> Suppose your shell is `bash`. Experiment you can do in the same virtualenv:
> 
>     1. quit neovim
> 
>     2. which pip
> 
>     3. bash -c "which pip"
> 
>     4. bash; which pip    # Nested shell, just like :ter starts a shell "nested"
> 
> 
> and compare outputs.

No Luck

![image](https://github.com/neovim/neovim/assets/89230263/91d74c26-e8c5-4260-900e-c79f5606d7db)

Here's also my $PATH:
```bash
/home/itsmenewbie03/.nvm/versions/node/v20.13.1/bin:/bin:/home/itsmenewbie03/.bun/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/itsmenewbie03/bin:/home/itsmenewbie03/.cargo/bin:/usr/local/java/jdk19/bin:/opt/android-sdk/platform-tools:/home/itsmenewbie03/.local/share/bin
```

**Comment by lazyzyf** [comment] 2025-03-23 13:04
I have the same issue, please fix it.
Run `:term which python `returns `/usr/bin/python`

**Comment by lazyzyf** [comment] 2025-03-23 13:20
I installed `https://github.com/linux-cultist/venv-selector.nvim/tree/regexp` and added `require("venv-selector").python()` and `require("venv-selector").venv()` in my init.lua. now it works.
