### ISSUE TITLE
Error in remote#define#notify

### ISSUE THREAD

**Issue by Marwes** [neovim/neovim#7856] opened 2018-01-15 15:18 UTC
- `nvim --version`: Both 0.2.1 and 0.2.2
```
NVIM v0.2.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171109-46118-9kky38/neovim-0.2.1/build/config -I/tmp/neovim-20171109-46118-9kky38/neovim-0.2.1/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171109-46118-9kky38/neovim-0.2.1/build/src/nvim/auto -I/tmp/neovim-20171109-46118-9kky38/neovim-0.2.1/build/include
Kompilerad av brew@Sierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system-vimrc-fil: "$VIM/sysinit.vim"
  reserv för $VIM: "/usr/local/Cellar/neovim/0.2.1/share/nvim"
```
- Vim (version: ) behaves differently? Unknown
- Operating system/version: OSX/Windows 10
- Terminal name/version: zsh/fish/neovim-qt
- `$TERM`: screen-256color (OSX)

### Steps to reproduce using

This might not be because of a bug in nvim but might be in a plugin. Unfortunately I don't know how to find out which. It occurs randomly (as far as I can tell) after some time (usually several hours) and is likely due to use of channels in https://github.com/autozimu/LanguageClient-neovim or https://github.com/Shougo/deoplete.nvim but I don't know how to debug further. As soon as it starts happening the error gets displayed on any use of `hjkl` to move so neovim becomes unusable until restart.

### Actual behaviour

```
Fel upptäcktes vid bearbetning av function remote#define#notify:
rad    6:
E475: Ogiltigt argument: Channel doesn't exist
Tryck RETUR eller skriv kommando för att fortsätta
```
See https://github.com/neovim/neovim/blob/9ddeb6e187e6ef6045bf037e4225dc46c8efb693/runtime/autoload/remote/define.vim#L184

Translated to English
```
Error were discovered when processing the function remote#define#notify:
row    6:
E475: Invalid argument: Channel doesn't exist
Press RETUR or write command to continue
```

### Expected behaviour

No error. Currently I restart neovim and it goes away. Best guess is that the channel gets closed/crashes at some point and either neovim or one of the plugins don't know how to recover.

**Comment by justinmk** [comment] 2018-01-15 19:16
> Best guess is that the channel gets closed/crashes at some point

That's correct. Can't do anything with this report until steps are provided.

**Comment by Marwes** [comment] 2018-01-15 19:43
@justinmk  Is there any way to determine which plugin that has created this channel without disabling them one by one? It can take a long time to reproduce this otherwise.

This was written to `nvim-data/log`.

```
2018/01/15 20:37:00 ERROR 3244 call_set_error:842: RPC: ch 2: stream write failed. RPC canceled; closing channel
```

**Comment by justinmk** [comment] 2018-01-15 19:49
We are working on things like https://github.com/neovim/neovim/pull/6743 to help with that.

**Comment by wenxingxing** [comment] 2018-02-05 08:58
getting the same error on mac os

**Comment by NikosEfthias** [comment] 2018-02-09 22:07
same error on macosx

**Comment by justinmk** [comment] 2018-02-11 11:39
As mentioned above, the occurrence of this error doesn't tell us anything. And we don't need more confirmations of it, only someone to investigate it more deeply.

**Comment by justinmk** [comment] 2019-03-13 23:03
## Resolution/Summary

>  Is there any way to determine which plugin that has created this channel without disabling them one by one? 

- #6743 provides `nvim_list_chans()` function, so clients and remote plugins can be listed. 
- It is the responsibility of remote plugins to call `nvim_set_client_info()` to  identify themselves. Please contact the plugin maintainer to encourage this.

Duplicate of #4468

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._

**Closed by justinmk** 2019-03-13 23:03 UTC
Labels: rpc, waiting-for-repro
