### ISSUE TITLE
Highlighting for `incsearch` Disappears When Using `sign place` and `redraw` within `vim.loop`

### ISSUE THREAD

**Issue by gen740** [neovim/neovim#25722] opened 2023-10-20 02:19 UTC
### Problem

When calling `sign place` and `redraw` within `vim.loop` while searching for text, the highlighting disappears.

### Steps to reproduce

1. Create `reprorc.lua` with:
    ```lua
    vim.fn.sign_define('foo', { text = '>' })
    vim.loop.timer_start(
      vim.loop.new_timer(),
      0,
      100,
      vim.schedule_wrap(function()
        for i = vim.fn.line('.'), vim.fn.line('$'), 1 do
          vim.fn.sign_place(1, 'bar', 'foo', vim.fn.bufname(), { lnum = i })
        end
        vim.cmd('redraw')
      end)
    )
    ```
2. Create `test.txt` containing:
    ```txt
    abcdef
    abdefg
    ```
3. Launch Neovim: `nvim -u reprorc.lua test.txt`
4. Execute search: `/abd`

https://github.com/neovim/neovim/assets/54583542/db2be6d8-f163-48ea-b7c5-910bc630b720

### Expected behavior

Highlight the search text incrementally.

https://github.com/neovim/neovim/assets/54583542/ca9ffb95-224a-48fb-868c-f1ce7e0e8be3

### Neovim version (nvim -v)

v0.9.5-dev-9+gb20533675

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 14.0 and archlinux(docker)

### Terminal name/version

weztern

### $TERM environment variable

xterm-256color

### Installation

build from repo. (tag release-0.9)

**Comment by zeertzjq** [comment] 2023-10-20 02:42
Related #17810

**Comment by zeertzjq** [comment] 2023-10-20 02:45
Duplicate of #17810

**Closed by zeertzjq** 2023-10-20 02:45 UTC
Labels: bug, highlight
