### ISSUE TITLE
Not possible to execute commands as root from within neovim

### ISSUE THREAD

**Issue by sixtyfive** [neovim/neovim#9671] opened 2019-03-04 09:58 UTC
I'm aware of #8527 and #8678, but I don't see how either of these addresses the use case where you would like to do something like `:!bundler install` from within `nvim` and it's not working because it needs to ask you your password and has no way how to do so. Is that something that'll never work in Neovim or something that has a workaround (`suda.vim` isn't one here) or will get a fix eventually?

**Comment by KillTheMule** [comment] 2019-03-04 10:05
Workaround would be to open a terminal and run your commands there.

**Comment by justinmk** [comment] 2019-03-04 11:09
> Is that something that'll never work in Neovim or something that has a workaround (suda.vim isn't one here) or will get a fix eventually?

Eventually. Hopefully. No timeline. Meanwhile use `:te` as mentioned above.

Duplicate of https://github.com/neovim/neovim/issues/1496 , also mentioned in the [FAQ](https://github.com/neovim/neovim/wiki/FAQ).

**Closed by justinmk** 2019-03-04 11:09 UTC

**Comment by sixtyfive** [comment] 2019-03-04 14:29
@KillTheMule thanks for that!
