### ISSUE TITLE
Add UI protocol for cursorline

### ISSUE THREAD

**Issue by fredizzimo** [neovim/neovim#30584] opened 2024-09-29 19:38 UTC
### Problem

The cursorline is embedded in the Window grid, which causes problems when scrolling in an UI like Neovide. This can be seen here, with a video https://github.com/neovide/neovide/issues/2818

 

### Expected behavior

It should be possible to use a UI protocol, so that we can deal with the cursorline ourselves, and do our own animations, totally decoupled from the grid scrolling itself.

**Comment by justinmk** [comment] 2024-09-29 19:41
Duplicate of https://github.com/neovim/neovim/issues/6071 which has more info.

**Closed by justinmk** 2024-09-29 19:41 UTC
Labels: enhancement, ui, ui-extensibility
