### ISSUE TITLE
unnamed and unnamedplus causing problems with long-press delete actions

### ISSUE THREAD

**Issue by maztaim** [neovim/neovim#23748] opened 2023-05-25 02:27 UTC
### Problem

I occasionally like to delete characters or lines by long-pressing x or d.  Recently, I've not been able to do so.  After looking through everything, it appears that when `vim.o.clipboard = 'unnamedplus'`  or `vim.o.clipboard = 'unnamed'` is set in init.lua, I see an unexpected behavior where the long-press only deletes one character or line, then stops.

### Steps to reproduce

```
nvim --clean
:set clipboard=unnamedplus
```
or 
```
:set clipboard=unnamed
```

create some characters
hold down x to delete a random amount of characters.

create some lines
hold down d to delete some lines.

### Expected behavior

mash 'x' in normal mode and delete characters until I lift.

mash 'd' in normal mode and delete lines until I lift.

### Neovim version (nvim -v)

v0.10.0-dev-382+gebb10d624

### Vim (not Nvim) behaves the same?

no, vim-minimal-9.0.1562-1

### Operating system/version

fedora 38

### Terminal name/version

alacritty 0.12.0

### $TERM environment variable

alacritty

### Installation

build from repo

**Comment by zeertzjq** [comment] 2023-05-25 02:53
What unexpected behavior did you see?

**Comment by maztaim** [comment] 2023-05-25 02:59
It only deleted one character, or one line.

**Comment by maztaim** [comment] 2023-05-25 20:15
I also did a bit more testing, I updated the title and description to include unnamed as being a problem, though to be fair, I don't normally use unnamed, so I don't have a baseline for that.

**Comment by zeertzjq** [comment] 2023-05-25 23:08
Cannot reproduce using wl-copy 2.0.0 or 2.1.0 and tmux 3.3a

**Comment by maztaim** [comment] 2023-05-26 00:08
I thought maybe it's alacritty?  I tried with gnome-terminal, still experiencing the problem when clipboard is set to either unnamed.

**Comment by maztaim** [comment] 2023-05-26 01:39
This seems to be wayland, wl-copy, or my lack of understanding how to configure clipboard.  I switched to gnome on xorg and ran through the same steps.  I am now able to delete multiple characters and lines, but I get `clipboard: No provider. Try ":checkhealth" or ":h clipboard".` on my initial attempt, which I expect since I am now on x instead of wayland.

**Comment by maztaim** [comment] 2023-05-26 01:46
I am chalking this up to my lack of experience here.  My solution was to just let neovim pick it's clipboard tool.  I can't even remember why I was using unnamed(plus) with wl-copy hanging around...

**Comment by sktt** [comment] 2024-02-10 21:59
I am having this issue too. I use unnamedplus to use the same clipboard the rest of wayland.

**Comment by maztaim** [comment] 2024-03-05 22:17
I'm a little more confident, it doesn't matter what terminal I use, if I use any clipboard, the hold behavior goes away.

**Comment by sktt** [comment] 2024-03-06 11:09
As far as I understand the problem only happens on gnome in wayland.

i think it's related to that wl-copy is forced to create a fake window to copy, which loses focus of neovim and held down key stop being registered when it returns to neovim.

so maybe it's more related to how nvim spawns the wl-copy process..  I wonder why plain vim does not have this problem...

**Comment by sktt** [comment] 2024-03-06 13:49
Related:
https://github.com/neovim/neovim/issues/11804
https://github.com/neovim/neovim/issues/12622 ( nice example )
https://github.com/neovim/neovim/issues/17919
https://github.com/AstroNvim/AstroNvim/issues/806
https://github.com/neovim/neovim/issues/25180

**Comment by ArnaudD-FR** [comment] 2024-08-06 21:25
Hello, I encounter this issue on Ubuntu 24.04 with neovim 0.9.5 and neovim 0.10.1. I use terminator as terminal but I have the same issue with gnome terminal.

My clipboard is configured to unnamedplus, so accordingly to this [documentation](https://neovim.io/doc/user/provider.html#g%3Aclipboard) neovim should use wl-copy.

How can I be sure wl-copy is really used?

Sometimes I see my terminal window blinking when this issue occur, it might be related to what @sktt [mentionned](https://github.com/neovim/neovim/issues/23748#issuecomment-1980626397)

**Comment by ArnaudD-FR** [comment] 2024-08-06 21:34
Just answering to myself, removing wl-clipboard package generates a warning in neovim claming no clipboard provider is installed. So `wl-copy` is used too in my case.

**Comment by yellowhat** [comment] 2024-11-06 22:42
I am having a similar problem but only using the flatpak version:

```bash
flatpak install flathub io.neovim.nvim
flatpak run io.neovim.nvim --clean
# :set clipboard=unnamedplus
```

Instead if I use neovim that ships with fedora 41:

```bash
nvim --clean
# :set clipboard=unnamedplus
```

there is no flickering while doing copy/paste operation.

**Comment by coreyhuinker** [comment] 2024-11-06 22:47
My workaround, borrowed from i-forget-where, has been to add the following to `lua/config/options.lua`:

```
-- single character deletes don't go to clipboard
-- this enables key repeat
vim.keymap.set("n", "x", '"_x')
```

though my solution only works for 'x', you can extrapolate to make it work for 'd' deletes as well.

**Comment by yellowhat** [comment] 2024-11-07 12:23
Thanks for your suggestion.

It is useful to remove clipboard call but, for example, `dd` I would like to cut to clipboard.

**Comment by yellowhat** [comment] 2024-11-07 14:57
I found a workaround for sway:

From my understanding: `wl-clipboard` spawns a 1x1 window for a splitsecond, then relies on the compositor to give it focus automatically, and uses the standard Wayland clipboard protocol.

Therefore I added the following to my sway config:

```
for_window [title="wl-clipboard"] floating enable
```

**Comment by justinmk** [comment] 2024-11-16 03:05
As mentioned already above, this is a duplicate of https://github.com/neovim/neovim/issues/11804#issuecomment-1113927971

**Closed by justinmk** 2024-11-16 03:05 UTC
Labels: bug, performance, clipboard, closed:duplicate

**Comment by Rmano** [comment] 2025-03-14 11:43
@coreyhuinker Sorry to comment on a closed issue, but this workaround saved my day... Thanks (a pity that reactions on messages are not notified by GitHub)
