### ISSUE TITLE
Build: Can't generate docs properly with `make doc`

### ISSUE THREAD

**Issue by xvzc** [neovim/neovim#26821] opened 2023-12-31 12:12 UTC
### Problem

When i run `make doc` without any changes from the master branch, i get `lsp.txt`, `tresitter.txt` with tons of missing lines. Also, i get following warning messages while generating docs. 
```text
...
Setting log level to ERROR
    warning: empty docs, skipping (target=lsp): buf.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=lsp): diagnostic.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=lsp): codelens.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=lsp): inlay_hint.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=lsp): tagfunc.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=lsp): semantic_tokens.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=lsp): handlers.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=lsp): util.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=lsp): log.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=lsp): rpc.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=lsp): protocol.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=treesitter): language.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=treesitter): query.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=treesitter): highlighter.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=treesitter): languagetree.lua
        existing docs: dict_keys([])
    warning: empty docs, skipping (target=treesitter): dev.lua
        existing docs: dict_keys([])
...
```

I tried on both MacOS and Arch Linux.

**MacOS Sonoma** 14.0.0
- `doxygen` 1.10.0
- `GNU Make` 3.81
- `cmake` version 3.28.1
- `ninja` 1.11.1
- `Python` 3.11.6

**Arch Linux**
- `doxygen` 1.9.8
- `GNU Make` 4.4.1
- `cmake` version 3.28.1
- `ninja` 1.11.1
- `Python` 3.11.6

### Steps to reproduce

1. clone the repository
2. run `make doc`

### Expected behavior

`lsp.txt` and `tresitter.txt` shouldn't have any changes

### Neovim version (nvim -v)

N/A

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

MacOS, Arch Linux

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

Git

**Comment by clason** [comment] 2023-12-31 12:16
I cannot reproduce that. Do you have `luajit` installed (system-wide)?

**Comment by xvzc** [comment] 2023-12-31 12:21
Yeah, i do. system-wide

**Comment by wookayin** [comment] 2023-12-31 12:36
After successfully building nvim (`make`), try running `python scripts/gen_vimdoc.py` instead of `make doc`. It will print a few more useful messages.

**Comment by xvzc** [comment] 2023-12-31 12:59
Thank you for your instruction. I read little bit of the source coe in `gen_vimdoc.py`. and found that the target in the **CONFIG** having one of its "files" values as `DIR like strings` cause the problem. For examlpe,

- `runtime/lua/vim/treesitter/` 
- `runtime/lua/vim/lsp/` 

After i change them to file paths, it works fine. below is the example of `lsp` target.
```
        'files': [
            'runtime/lua/vim/lsp/buf.lua',
            'runtime/lua/vim/lsp/diagnostic.lua',
            'runtime/lua/vim/lsp/codelens.lua',
            'runtime/lua/vim/lsp/inlay_hint.lua',
            'runtime/lua/vim/lsp/tagfunc.lua',
            'runtime/lua/vim/lsp/semantic_tokens.lua',
            'runtime/lua/vim/lsp/handlers.lua',
            'runtime/lua/vim/lsp/util.lua',
            'runtime/lua/vim/lsp/log.lua',
            'runtime/lua/vim/lsp/rpc.lua',
            'runtime/lua/vim/lsp/protocol.lua',
            'runtime/lua/vim/lsp.lua',
        ],
```

**Comment by wookayin** [comment] 2023-12-31 13:14
`runtime/lua/vim/treesitter` `runtime/lua/vim/lsp` those arguments will be passed literally to doxygen. So if that's the case, it's your doxygen behaves differently than ours. Filesystem issue...?

For me I was using Doxygen 1.9.5 on macOS Sonoma. I also tried Doxygen 1.10 but it's the same.

**Comment by xvzc** [comment] 2023-12-31 13:31
It seems like there was an related issue with this. https://github.com/doxygen/doxygen/commit/e73e0f92124f47c77ea5b9d6d8c0dd49f6a7bbf1

They say it's been fixed on 1.10.0, but maybe it counldn't handle all cases.
And it would be very nice if we can listify the files in given directories before we pass the arguments to doxygen.

**Comment by wookayin** [comment] 2023-12-31 13:35
That would be an easy fix (after #26791 is merged).

**Comment by xvzc** [comment] 2023-12-31 13:39
Yeah i can wait. now i got a workaround anyway.

**Comment by justinmk** [comment] 2024-04-20 16:48
docs generator was rewritten

**Closed by justinmk** 2024-04-20 16:48 UTC
Labels: bug, build, needs:repro
