### ISSUE TITLE
nvim_set_hl() does not work as expected under some terminals after `highlight clear`

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#23589] opened 2023-05-11 13:27 UTC
### Problem

hi folks, i'm trying to create a hi group using nvim_set_hl(), but seems it does not work as expected. in my tests, running nvim in some terminal works, but in some others works not. to be specific, st, urxvt, xterm dont.

### Steps to reproduce

* open `st` or `urxvt` or `xterm`
* `$ mkdir test && cd test`
* `touch init.vim`
* `$ mkdir colors && touch colors/foobar.vim`
* `$ nvim --clean -u init.vim`
* `:hi Foobar`

the init.vim
```
set rtp+=.
colorscheme foobar

lua <<EOF
vim.api.nvim_set_hl(0, "Foobar", { ctermfg = 15, ctermbg = 8, cterm = { bold = true } })
EOF

" " this works not either
" hi Foobar ctermfg=15 ctermbg=8 cterm=bold
```

the colors/foobar.vim
```
highlight clear

let g:colors_name = 'foobar'
```

### Expected behavior

the Foobar hi group was set after the colorscheme, it should not be cleared.
while in the above test case, `:hi Foobar` shows `Foobar  xxx cleared`

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

system package manager

**Comment by clason** [comment] 2023-05-11 13:31
I don't see how the terminal should make difference here? (I cannot reproduce this on iTerm2.)

**Comment by haolian9** [comment] 2023-05-11 13:40
yeah thanks, i'll refine the reproducing steps. i was trying to restore my local env.

**Comment by zeertzjq** [comment] 2023-05-11 13:46
Possible duplicate of #22614

**Comment by haolian9** [comment] 2023-05-11 13:47
> I cannot reproduce this on iTerm2

yeah, I can not reproduce it in kitty, st+**tmux** either.

**Comment by zeertzjq** [comment] 2023-05-11 15:59
Duplicate of #22614

**Closed by zeertzjq** 2023-05-11 15:59 UTC
Labels: bug

**Comment by haolian9** [comment] 2023-05-11 23:40
in my tests, this can be a wrokaround (actually a proper solution to me)
```
  vim.api.nvim_create_autocmd("colorscheme", {
    callback = function() vim.api.nvim_set_hl(0, "Foobar", { ctermfg = 15, ctermbg = 8, cterm = { bold = true } }) end,
  })
```

**Comment by haolian9** [comment] 2023-05-16 10:24
for anyone interested a workaround, i finally settled down with this solution: use a custom namespace rather than the global one, `nvim_set_hl(ns)`, and wrap the code with `nvim_win_set_hl(ns)` and `nvim_win_set_hl(0)`
