### ISSUE TITLE
Netrw with default scp in Windows use Unix-like path style for destination

### ISSUE THREAD

**Issue by mattthhh** [neovim/neovim#29841] opened 2024-07-24 08:53 UTC
### Problem

When I want to open a remote file using the scp protocol by netrw, I can see that it uses for destination path  `/C/Users/...`. The command fails by printing "No such file or directory". When reading the doc,s I found the variable for netrw called  `g:netrw_cygwin` that maybe uses the Unix-like path style. Even if I set the variable to 0, it stills try use for destination `/C/Users/...`

### Steps to reproduce

(on Windows) : `nvim scp://user@hostname/file/to/edit`

### Expected behavior

Instead of setting the destination path `/C/Users`, getting something more like that `C:\Users\...`

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

same

### Operating system/version

Windows 10

### Terminal name/version

Powershell

### $TERM environment variable

?

### Installation

Binary from realease

**Comment by thirstyice** [comment] 2024-09-02 17:04
Duplicate of #29517

**Closed** 2024-09-02 18:50 UTC
Labels: bug, netrw, closed:duplicate
