### ISSUE TITLE
<C-i>zz does not work

### ISSUE THREAD

**Issue by hacker-DOM** [neovim/neovim#20192] opened 2022-09-13 16:56 UTC
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no, 8.2.2681

### Operating system/version

macOS 12.4

### Terminal name/version

Tabby 1.0.183

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

```
:nnoremap <C-i> <C-i>zz<CR>
:h<CR>
:only<CR>
/bars<CR>
CTRL-]
CTRL-o
CTRL-i
```

### Expected behavior

The line containing the definition of |bars| is centered. 

vim:
<img width="836" alt="Screenshot 2022-09-13 at 6 55 03 PM" src="https://user-images.githubusercontent.com/18601956/189961529-83c28348-59f2-4195-90cd-2e7fc8698c8f.png">

neovim:
<img width="793" alt="Screenshot 2022-09-13 at 6 55 19 PM" src="https://user-images.githubusercontent.com/18601956/189961500-419a665b-06ea-485c-a3c4-535555f9d42d.png">

### Actual behavior

The line is not centered.

**Comment by hacker-DOM** [comment] 2022-09-13 17:02
Also: https://old.reddit.com/r/neovim/comments/xdb111/cizz_not_working/

**Comment by zeertzjq** [comment] 2022-09-13 22:40
Duplicate of #17867

**Closed by zeertzjq** 2022-09-13 22:40 UTC
Labels: bug
