### ISSUE TITLE
Ctrl-o jumped back into terminal and fired termopen command

### ISSUE THREAD

**Issue by mtglsk** [neovim/neovim#4420] opened 2016-03-06 17:59 UTC
- Neovim version: 0.1.3
- Operating system: ubuntu
- Terminal emulator: xterm

### Actual behaviour

Terminal is shown in jumplists.

### Expected behaviour

Terminal shouldn't be in jumplists. I don't want to jump back and fire rm -rf on files or folders which no longer exists and possibly delete my data. This should be configurable at least.

**Comment by justinmk** [comment] 2016-03-06 19:38
What is `:set hidden?` ? Also please don't ignore the "steps to reproduce" section.

**Comment by justinmk** [comment] 2016-03-06 19:40
Even with `'nohidden'` I cannot reproduce this. Closing until repro steps are provided.

**Comment by mtglsk** [comment] 2016-03-06 20:04
Only this in init.vim

    if empty(glob('~/.config/nvim/testdir'))
        call termopen('echo Test')
    endif

Then create the testdir (example usage for this scenario - bootstraping a plugin like vim-plug).

Checking out the jumplist:

    4     2    8 call termopen('echo Test')
    3     1    0 term://.//10846:echo Test
    2    21    0 term://.//10846:echo Test
    1     1    0 if empty(glob('~/.config/nvim/testdir'))

Jumping back a few times will trigger the terminal and the command which were running.

**Comment by justinmk** [comment] 2016-03-06 20:15
I still can't reproduce. I see now by "file termopen command" you don't mean the `TermOpen` event. I guess you mean the `echo Test` command is executing? But I still can't reproduce using something like `call termopen('date')`: after it finishes, it reports `[Process exited 0]`, and jumping back to that buffer shows the exact same date stamp (which includes seconds).

Please provide steps with `nvim -u NONE` and instead of saying "jumping back", please provide the _exact commands_ you are using so that I don't have to guess.

**Comment by justinmk** [comment] 2016-03-06 20:18
By the way, the `:mksession` support for terminals depends on the `term://foo` URI executing `foo` when `term://foo` is first visited. And if you re-load the file named `term://echo Test` after it has be unloaded, then yes, it's going to execute `echo Test` again. It does not make sense to remove these from the jumplist, but we do need to answer some questions about what to do with `term://` buffers when `'nohidden'` is set. See https://github.com/neovim/neovim/issues/3340#issuecomment-192812245

**Comment by mtglsk** [comment] 2016-03-06 20:19
Try with something like `call termopen('yes')` so there is no ambiguity if the command is running (btw, i can't even stop this command inside nvims terminal).

I just use ^O a few times until i hit terminal and it starts running the command again.

**Comment by justinmk** [comment] 2016-03-06 20:23
`yes` _never ends_, so I have no idea what you mean now: navigating away from it will not end it, and jumping back to it will not execute it...

**Comment by justinmk** [comment] 2016-03-06 20:27
The point of providing steps with `nvim -u NONE` is to eliminate any plugins or vimrc you have so that we have clear baseline of how to reproduce. If you won't provide that then I can't help you.

**Comment by mtglsk** [comment] 2016-03-06 20:31
Ok, i removed ~/.local nvim stuff and removed init.vim. Starting with `nvim -u NONE`:

    :call termopen('yes')
    i ^C <enter>
    ^O

Looking at top in another terminal the ^C stops the process then when i jump back the yes command starts again.

**Comment by justinmk** [comment] 2016-03-06 20:51
Thanks. Can you provide the full text of `:version`? I still cannot reproduce with this version:

```
NVIM v0.1.3-301-gc6df1b3
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/vagrant/neovim2/build/config -I/home/vagrant/neovim2/src -I/home/vagrant/neovim2/.deps/usr/include -I/home/vagrant/neovim2/.deps/usr/include -I/home/vagrant/neovim2/.deps/usr/include/luajit-2.0 -I/home/vagrant/neovim2/.deps/usr/include -I/home/vagrant/neovim2/.deps/usr/include -I/home/vagrant/neovim2/.deps/usr/include -I/home/vagrant/neovim2/.deps/usr/include -I/usr/include -I/home/vagrant/neovim2/build/src/nvim/auto -I/home/vagrant/neovim2/build/include
Compiled by vagrant@vagrant-ubuntu-saucy-64

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences
```

 Using `nvim -u NONE -i NONE`, when I press `<enter>` in your second step, 

- the buffer is deleted,
- `ls!` shows only buffer 2 (a new, empty buffer)
- pressing ctrl-o (your third step) goes nowhere
    - I'm still in buffer 2 (the new, empty buffer) after pressing ctrl-o multiple times
    - `top` does not show `yes`
    - `ps aux|grep yes` returns nothing (except `grep`)

**Comment by mtglsk** [comment] 2016-03-06 20:54
```
NVIM 0.1.3-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong
-Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_
SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter
 -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostic
s-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE
 -I/build/neovim-nYO9mJ/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu1
6.04.1/build/config -I/build/neovim-nYO9mJ/neovim-0.1.2ubuntu1+git201603052
300+2355+17~ubuntu16.04.1/src -I/build/neovim-nYO9mJ/neovim-0.1.2ubuntu1+gi
t201603052300+2355+17~ubuntu16.04.1/.deps/usr/include -I/build/neovim-nYO9m
J/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu16.04.1/.deps/usr/inclu
de -I/usr/include/luajit-2.0 -I/build/neovim-nYO9mJ/neovim-0.1.2ubuntu1+git
201603052300+2355+17~ubuntu16.04.1/.deps/usr/include -I/build/neovim-nYO9mJ
/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu16.04.1/.deps/usr/includ
e -I/build/neovim-nYO9mJ/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu
16.04.1/.deps/usr/include -I/build/neovim-nYO9mJ/neovim-0.1.2ubuntu1+git201
603052300+2355+17~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/n
eovim-nYO9mJ/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu16.04.1/buil
d/src/nvim/auto -I/build/neovim-nYO9mJ/neovim-0.1.2ubuntu1+git201603052300+
2355+17~ubuntu16.04.1/build/include
Compiled by buildd@lgw01-51

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

This is the version from PPA if that matters.

**Comment by mtglsk** [comment] 2016-03-06 21:28
I cleaned whole ~/.config/nvim/. I got a whole slew of errors while trying to find what causes it:
```
E317: pointer block id wrong, E316: ml_get:
E575: Error while reading ShaDa file: mark entry at position 3196 has invalid line number
E575: Error while reading ShaDa file: mark entry at position 3233 has invalid line number
```
This is what i managed to catch.

I think that `call termopen()` only adds a jump to jumplist if run from init.vim. Although i'm not sure.

Edit:

Ok, this is how to reproduce it i think:

```
nvim -u NONE
:call termopen('echo test')
:q

nvim -u NONE
:call termopen('echo test2')
:jumps
 jump line  col file/text
   2     1    0 term://.//28304:echo test <-- wtf?
```

And then ^O will jump back to it.

**Comment by justinmk** [comment] 2016-03-06 21:44
Ok, so this is what I described in https://github.com/neovim/neovim/issues/4420#issuecomment-192981380.

Again, this is how `:mksession` is supported. It's also how `:e term://` works. 

>  This should be configurable at least.

You can delete the `term://` handler:

    au! BufReadCmd term://*

This means that `:edit term://` won't open a terminal. 

"Remove terminals from the jumplist", doesn't seem like a good idea, it would be an arbitrary inconsistency.

> I don't want to jump back and fire rm -rf

I'd say it's not a good practice to `:term rm -rf`. Do `:term`, then run `rm -rf` inside the shell.

We can't have it both ways: either we support `:term {cmd}` or we don't. Removing it from the jumplist and other random hacks isn't going to avoid all problems. Rather, user must use judgment for this feature.

Definitely open to better, generalized designs, but not open to arbitrary tweaks.

**Closed by justinmk** 2016-03-06 21:44 UTC
