### ISSUE TITLE
Feature: optional floating window borders

### ISSUE THREAD

**Issue by Avi-D-coder** [neovim/neovim#9718] opened 2019-03-12 05:17 UTC
#6619 Added floating windows, but no way to create a border.

Try to find where the float begins:
![Screenshot_20190312_011317](https://user-images.githubusercontent.com/29133776/54176216-5aa9b300-4464-11e9-8181-68400ed1bd68.png)

**Comment by Avi-D-coder** [comment] 2019-03-12 05:31
What would a good api look like for this?

**Comment by bfredl** [comment] 2019-03-12 07:28
@Avi-D-coder The solution so far has been to change background color using `'winhl'`. #9669 will add a default highlight for convenience.

**Comment by Avi-D-coder** [comment] 2019-03-12 08:22
@bfredl 
`set winhl=Normal:PMenu`
Produces hideous results:
![Screenshot_20190311_204133](https://user-images.githubusercontent.com/29133776/54166995-26230080-443e-11e9-8a3d-094aa6dcd9db.png)

**Comment by bfredl** [comment] 2019-03-12 08:39
@Avi-D-coder So don't use `PMenu` then. Define a `NormalFloat` group (which will the default very soon) with reasonable colors, or link some existing group to it. In this case the main issue seems to be use of `gui=reverse`.

**Comment by Avi-D-coder** [comment] 2019-03-13 01:19
@bfredl That statige does work, but it requires the user to pick between using their color scheme and the ability to pick out a floating window.

**Comment by justinmk** [comment] 2019-03-13 01:50
Duplicate of https://github.com/neovim/neovim/issues/6092 . 
See https://github.com/neovim/neovim/pull/6373 (stalled, someone needs to take ownership).

> it requires the user to pick between using their color scheme and the ability to pick out a floating window.

You are asking for theme-harmony, but you said your theme's `Pmenu` is "hideous". Not at all clear how to satisfy both.

**Closed by justinmk** 2019-03-13 01:50 UTC

**Comment by bfredl** [comment] 2019-03-13 12:08
> @bfredl That strategy does work, but it requires the user to pick between using their color scheme and the ability to pick out a floating window.

@Avi-D-coder If the expectation is that a freshly merged infrastructural feature works ideally with every user config unchanged, I'm afraid we cannot deliver that. `Pmenu` is meant as a "best guess" that at least work reasonable with _some_ color schemes. Do you have a suggestion for a better default link? For a theme that has a `Pmenu` that already is consistent with `Normal` in its color ordering, it works reasonable (like `gruvbox`). It is also possible for any color theme to define the `NormalFloat` group (without compat issues: defining a non-existing group is not an error). 

If/when we add a border, the situation would be the same for the hypothetical`FloatBorder` group.

**Comment by Avi-D-coder** [comment] 2019-03-13 12:24
I would suggest that the default be a `│` border (like splits). The border color would be the same as splits border. This would allow `NormalFloat` to use the primary color scheme. This is also how other editors like vscode behave:
![image](https://user-images.githubusercontent.com/29133776/54278645-4dc2b780-4569-11e9-84c6-8834cd28f371.png)

**Comment by bfredl** [comment] 2019-03-13 12:44
>  This would allow NormalFloat to use the primary color scheme. This is also how other editors like vscode behave

This is also how nvim behaves, not sure what the alternative would be. One just shouldn't expect every nvim color scheme out there to optimized for float usage when floats only have been on an unreleased dev version for a week.

**Comment by Avi-D-coder** [comment] 2019-03-13 13:16
@bfredl  Without border support neovim cannot behave as vscode does since the floating window would blend into the background. 

Isn't the default still `Pmenu`?
`Pmenu` is a contrasting color scheme not the primary color scheme. If the default was a border then themes that do not explicitly define `NormalFloat` would just work, by using the normal color scheme not `Pmenu`. 

An alternative option to make theming just work would be to set `NormalFloat`'s default background ~20% lighter than the themes background for `&background=="dark"` and darker for `&background=="light"`. 

VsCode uses both a border and lightning/darkening floating window background.

**Comment by bew** [comment] 2019-03-13 13:20
> Without border support neovim cannot behave as vscode does since the floating window would blend into the background

You should probably define a background color for this float, which is slightly lighter than the normal background color, this way you can distinguish the two.

**Comment by bfredl** [comment] 2019-03-13 13:40
> Pmenu is a contrasting color scheme not the primary color scheme. 

I'm sorry but this doesn't make any sense.

> Without border support neovim cannot behave as vscode does since the floating window would blend into the background.

The float clearly has a different background color in your vscode snapshot, which stands out a lot more than what the border does. I'm not sure the point of arguing this.

> An alternative option to make theming just work would be to set NormalFloat's default background ~20% lighter than the themes background for &background=="dark" and darker for &background=="light".

This could be part of a more generic blending infrastructure, but I'm not sure we want this for a default. Using "default link" with ability for themes to override is the standard way for introducing new highlight groups. Let's have some patience and see how the larger community deals with it before doing a special intervention.

**Comment by Avi-D-coder** [comment] 2019-03-13 14:06
@bfredl By "Pmenu is a contrasting color scheme" I mean the content of the floating window shown in https://github.com/neovim/neovim/issues/9718#issuecomment-471901289 contrasts with the primary solarized dark theme. With the current implementation this contrast is by design.

What I am advocating is that one or both of the two approaches used by vscode (color shifting or a border) be used. That way the default behavior will be inline with what other editors do. Themes and users could still override the default. All I am asking for is a default that unlike `Pmenu` does not break syntax highlighting in floating windows.

**Comment by sassanh** [comment] 2019-04-28 02:10
Currently I'm creating another bigger window behind the actual window just to render the border:
![image](https://user-images.githubusercontent.com/1270688/56857248-5ee05000-6980-11e9-89d8-cbd500a20ef7.png)

**Comment by stellarhoof** [comment] 2019-10-26 13:41
@sassanh Have you got a link to the code for that?

**Comment by alichtman** [comment] 2019-11-14 07:05
@stellarhoof Using your solution seems to make the background text bleed into the preview window. Any ideas as to why this could be happening?

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/20600565/68834213-847f3d80-06b5-11ea-8886-48853a334e3b.png">

**Comment by stellarhoof** [comment] 2019-11-14 14:51
Nope. That's outside of my knowledge unfortunately.

**Comment by alichtman** [comment] 2019-11-28 17:53
This works for me:

```vimL
function! CreateCenteredFloatingWindow()
    let width = min([&columns - 4, max([80, &columns - 20])])
    let height = min([&lines - 4, max([20, &lines - 10])])
    let top = ((&lines - height) / 2) - 1
    let left = (&columns - width) / 2
    let opts = {'relative': 'editor', 'row': top, 'col': left, 'width': width, 'height': height, 'style': 'minimal'}

    let top = "╭" . repeat("─", width - 2) . "╮"
    let mid = "│" . repeat(" ", width - 2) . "│"
    let bot = "╰" . repeat("─", width - 2) . "╯"
    let lines = [top] + repeat([mid], height - 2) + [bot]
    let s:buf = nvim_create_buf(v:false, v:true)
    call nvim_buf_set_lines(s:buf, 0, -1, v:true, lines)
    call nvim_open_win(s:buf, v:true, opts)
    set winhl=Normal:Floating
    let opts.row += 1
    let opts.height -= 2
    let opts.col += 2
    let opts.width -= 4
    call nvim_open_win(nvim_create_buf(v:false, v:true), v:true, opts)
    au BufWipeout <buffer> exe 'bw '.s:buf
endfunction

let g:fzf_layout = { 'window': 'call CreateCenteredFloatingWindow()' }
```

**Comment by sodiumjoe** [comment] 2019-12-29 21:37
@justinmk maybe I'm missing something, but this doesn't appear to be a duplicate of #6092, which is regarding a margin between the line number column and the first buffer column.

**Comment by delphinus** [comment] 2020-01-21 11:48
The border of floats is a desired feature, but it is annoying that several plugins are implementing with each own logic. I think this feature should be supported by Neovim natively.

**Comment by justinmk** [comment] 2020-01-21 17:35
Indeed, but someone needs to implement it.

**Comment by slavistan** [comment] 2020-07-24 09:28
Is there a final verdict with respect to this feature? I cannot see why this issue is closed as the feature has not been explicitly rejected nor has it been implemented. Are we just waiting for someone to do it?

**Comment by sassanh** [comment] 2020-07-26 06:35
This is closed as it is a duplicate of https://github.com/neovim/neovim/issues/6092

**Comment by kantord** [comment] 2020-11-14 08:49
@sassanh how is this a duplicate of #6092? That sounds like a completely different issue.

**Comment by sassanh** [comment] 2020-11-14 13:47
Take a look at this comment: https://github.com/neovim/neovim/issues/9718#issuecomment-472247870
And this PR: https://github.com/neovim/neovim/pull/6373
which unfortunately is closed now.
So even though https://github.com/neovim/neovim/issues/6092 looks like a different issue, it was going to be resolved in a way that it would resolve this issue too, if you can have margins from each edge of your window, then it would be the responsibility of the buffer renderer to render a border or whatever in that margin space.
These are all how I understand it, not that I have anything to do with the decision making about this stuff.

**Comment by bfredl** [comment] 2020-11-14 17:06
Yes, once we have margin the space could be reused by code that renders a fancy ascii or unicode border. If this will be `runtime/lua` code or `src/nvim` code remains to be seen, but I hope to get time to revisit this before Xmas :)

**Comment by GideonWolfe** [comment] 2021-02-10 17:31
Has anyone taken a look at this? Different plugins have managed to implement this, [example](https://github.com/katawful/Obli-Vim#window-options)
![image](https://user-images.githubusercontent.com/32942052/107547681-908cd000-6b82-11eb-8dfa-cb29d9cc26ee.png)

A native API would be nice so we wouldn't have to get a plugin just for the floating window border feature.

**Comment by MuhammedZakir** [comment] 2021-02-10 18:40
> Has anyone taken a look at this? Different plugins have managed to implement this, [example](https://github.com/katawful/Obli-Vim#window-options)
> ![image](https://user-images.githubusercontent.com/32942052/107547681-908cd000-6b82-11eb-8dfa-cb29d9cc26ee.png)
> 
> A native API would be nice so we wouldn't have to get a plugin just for the floating window border feature.

Open an issue here -- https://github.com/mjlbach/neovim-ui. See https://github.com/neovim/neovim/pull/13863 for more info.

**Comment by mjlbach** [comment] 2021-02-10 18:46
> Open an issue here -- https://github.com/mjlbach/neovim-ui. See #13863 for more info.

FYI we already implemented bordered floating windows in neovim-ui

**Comment by GideonWolfe** [comment] 2021-02-10 18:51
I didn't know this existed, thanks!

**Comment by mjlbach** [comment] 2021-02-10 18:52
don't use it, it's not stable and we will be changing the api frequently. It will eventually be upstreamed to core once things stabilize

**Comment by GideonWolfe** [comment] 2021-02-10 18:58
Well it's at least good to know people are active on the issue :) Can't wait to see it upstreamed

**Comment by MuhammedZakir** [comment] 2021-02-10 20:28
> > Open an issue here -- https://github.com/mjlbach/neovim-ui. See #13863 for more info.
> 
> FYI we already implemented bordered floating windows in neovim-ui

Didn't know about that. Thanks! If possible, can you please add a list of features in an issue or a file in that repo? Added, in-progress, to-do, etc. To get an overview of the work. :-)

**Comment by LeonGr** [comment] 2021-03-10 13:37
This also adds a border to the diagnostics window: https://gist.github.com/LeonGr/96c8fd89eb69328876e9a45300ad374b

**Comment by ray-x** [comment] 2021-05-31 13:22
I have a question.
Where is the color of border been defined?
NormalFloat seems only define the inner area of floating window, not border color. Some of the colorscheme I am using can not show the border or it is very hard to see the border.

**Comment by adigitoleo** [comment] 2022-02-05 00:12
Linking the PR would have been helpful:

https://github.com/neovim/neovim/pull/13998

Example use:

```
function! NewFloating() abort
    " Open a new floating window.
    let l:buf = nvim_create_buf(v:false, v:true)
    let l:row = &lines / 4
    let l:col = &columns / 4
    let l:height = &lines / 2
    let l:width = &columns / 2
    let l:win = nvim_open_win(
        \l:buf,
        \v:true,
        \{
        \   'relative': 'editor',
        \   'border': 'single',
        \   'row': l:row,
        \   'col': l:col,
        \   'width': l:width,
        \   'height': l:height
        \}
    \)
endfunction
```

Tried on neovim 0.6.1

Relevant highlight groups are `NormalFloat` and the undocumented `FloatBorder` as mentioned already.

**Comment by Yggdroot** [comment] 2022-04-05 01:54
There is a bug of `nvim_open_win`.
As the example mentioned by @adigitoleo :
```vim
function! NewFloating() abort
    " Open a new floating window.
    let l:buf = nvim_create_buf(v:false, v:true)
    let l:row = &lines / 4
    let l:col = &columns / 4
    let l:height = &lines / 4
    let l:width = &columns / 4
    let l:win = nvim_open_win(
        \l:buf,
        \v:true,
        \{
        \   'relative': 'editor',
        \   'border': 'single',
        \   'row': l:row,
        \   'col': l:col,
        \   'width': l:width,
        \   'height': l:height
        \}
    \)
endfunction

call NewFloating()
```

<img width="512" alt="Snipaste_2022-04-05_09-52-32" src="https://user-images.githubusercontent.com/2705841/161663703-d422a641-2596-4fe3-88a6-89f45ecf3f5f.png">

**Comment by zeertzjq** [comment] 2022-04-05 02:14
@Yggdroot Please open a new issue with steps to reproduce using `nvim --clean`

**Comment by Yggdroot** [comment] 2022-04-05 02:55
> @Yggdroot Please open a new issue with steps to reproduce using `nvim --clean`

I open a new issue: https://github.com/neovim/neovim/issues/17996
