### ISSUE TITLE
git stash -p not work

### ISSUE THREAD

**Issue by huangyingw** [neovim/neovim#7987] opened 2018-02-09 02:46 UTC
- `nvim --version`: NVIM v0.2.3-dev Build type: Debug
- Vim (version: ) behaves differently? 8.0
- Operating system/version: macOS
- Terminal name/version: iterm2 Build 3.1.5
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
I could not go into the interactive mode to answer Y/N at each hunk
Stash this hunk [y,n,q,a,d,/,e,?]?
No changes selected

shell returned 1

Press ENTER or type command to continue
### Expected behaviour
I should go into an interactive mode to select Y/N at each hunk.

**Comment by ZyX-I** [comment] 2018-02-09 09:10
You have not specified what do you do to try going into interactive mode, but it looks like duplicate of #1496.

**Closed by ZyX-I** 2018-02-09 09:10 UTC
