### ISSUE TITLE
-u loads all matching files

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#8277] opened 2018-04-14 20:59 UTC
- `nvim --version`: v0.2.3-992-g27e26b1
- Vim (version: 7.4) behaves differently? no
- Operating system/version: Linux/WSL
- Terminal name/version: conhost
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
wget https://raw.githubusercontent.com/Haron-Prime/evening_vim/master/colors/evening.vim
nvim --startuptime nvim_startup.log -u ./evening.vim
```

### Actual behaviour
As seen in `nvim_startup.log`:

```
000.060  000.060: --- NVIM STARTING ---
001.208  001.148: locale set
003.448  002.240: inits 1
003.507  000.059: window checked
004.082  000.575: parsing arguments
004.954  000.872: expanding arguments
005.144  000.190: inits 2
006.406  001.262: init highlight
011.388  000.906  000.906: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim
016.787  002.195  002.195: sourcing /usr/local/share/nvim/runtime/colors/evening.vim # <----- HERE
280.772  274.011  270.910: sourcing ./evening.vim # <----- HERE
280.851  000.434: sourcing vimrc file(s)
300.990  019.661  019.661: sourcing /usr/local/share/nvim/runtime/filetype.vim
302.243  000.281  000.281: sourcing /usr/local/share/nvim/runtime/ftplugin.vim
303.191  000.186  000.186: sourcing /usr/local/share/nvim/runtime/indent.vim
307.704  001.025  001.025: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim
311.520  000.833  000.833: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim
313.252  008.596  006.738: sourcing /usr/local/share/nvim/runtime/colors/evening.vim # <----- HERE
```

### Expected behaviour

1. `./evening.vim` does not match `/usr/local/share/nvim/runtime/colors/evening.vim`, so it shouldn't be loaded.
2. I think even `-u evening.vim` (without the leading `./`) should load the first matching file then stop, and `./` should be the first directory searched (before rtp).

**Comment by justinmk** [comment] 2018-04-14 21:59
If Vim works the same way there's not much for us to discuss.  If it's really a problem, it should be fixed upstream.

**Comment by glacambre** [comment] 2021-06-05 19:24
Can't reproduce on master :tada: .

**Closed by glacambre** 2021-06-05 19:24 UTC
Labels: 0.kind: bug-vim, startup

**Comment by mqudsi** [comment] 2021-06-07 18:52
@glacambre please reopen; I'm not sure how you tested this but it 100% reproduces for me under NVIM v0.5.0-dev+1385-g93f15db5d with the steps in the initial post.

@justinmk this does not reproduce under vim 8.0, which correctly sources only the `evening.vim` and `./evening.vim`

I've attached the startup logs from both nvim and vim, you can clearly see the difference between the two.
[nvim_startup.log](https://github.com/neovim/neovim/files/6611341/nvim_startup.log) 
[vim_startup.log](https://github.com/neovim/neovim/files/6611342/vim_startup.log)
