### ISSUE TITLE
Lua slowdown in v0.7.0

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#18644] opened 2022-05-19 20:11 UTC
### Neovim version (nvim -v)

v0.7.0

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Ubuntu 22.04

### Terminal name/version

21.12.3

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

Create a file `f.lua` with the following contents:

```lua
local tic = os.clock()
for i = 0, 10000 do
  local t = {'A', 'B', 'C'}
  local x = {t[math.random(#t)]}
  table.foreach(x, function(k, v) end)
end
local toc = os.clock()
print(toc - tic)
```

Execute the Lua code.

```
$ nvim --clean
:source f.lua
```

### Expected behavior

Execution time would be similar to Neovim v0.6.1: `0.003525`

### Actual behavior

Execution time is noticeably longer than Neovim v0.6.1: `0.076882`

**Comment by dstein64** [comment] 2022-05-19 20:14
The example above is intended as a minimal reproducible example. I had noticed the slowdown when using a plugin I wrote, [vim-menu](https://github.com/dstein64/vim-menu).

Using `git bisect` indicates that the slowdown started when updating Lua in this commit:
https://github.com/neovim/neovim/commit/d3603e157a2b58b6976ba616ed2920972f184d41

**Comment by zeertzjq** [comment] 2022-05-19 20:22
On Arch Linux with the same LuaJIT version v0.6.1 is as slow as v0.7.0 and v0.8.0-dev, so this is a LuaJIT problem.

**Comment by zeertzjq** [comment] 2022-05-19 20:25
With luajit-2.1.0.beta3.r395.ge2c312e0-1:
0.006703
With luajit-2.1.0.beta3.r397.g20aea939-1:
0.0978003

**Comment by dstein64** [comment] 2022-05-19 20:51
Thanks @zeertzjq! I've opened a LuaJIT issue here:
https://github.com/LuaJIT/LuaJIT/issues/844

**Comment by zbirenbaum** [comment] 2022-05-20 01:21
This is due to the `table.foreach` call in your code. I had a hint something was wrong when diagnostics reported that `table` has no such value `foreach`

The code you supplied executed on my laptop in about 1.3 seconds, abysmally slow. Editing the code to this equivalent code however, ran in .006587 seconds:

```
local tic = os.clock()

local foreach = function(t, fn)
  for k, v in pairs(t) do
    fn(k, v)
  end
end

for i = 0, 10000 do
  local t = {'A', 'B', 'C'}
  local x = {t[math.random(#t)]}
  foreach(x, function(k, v) end)
end
local toc = os.clock()
print(toc - tic)
```
Its likely that either foreach isn't supported by luajit or the issue is with resolving the function symbol rather than execution itself.

**Comment by dstein64** [comment] 2022-05-20 01:43
Thanks @zbirenbaum! I can switch away from using `table.foreach`.

Are you running Lua or LuaJIT? For me, the following code executes as expected from LuaJIT, but not Lua:

```
table.foreach({1, 2, 3}, function(k, v) print(v) end)
```

Switching away from `table.foreach` will be a minor change for my code, but presumably there could still be an issue with the update to LuaJIT that introduced the slowdown, especially if the slowdown could be avoided.

**Comment by zbirenbaum** [comment] 2022-05-20 02:15
> Thanks @zbirenbaum! I can switch away from using `table.foreach`.
> 
> Are you running Lua or LuaJIT? For me, the following code executes as expected from LuaJIT, but not Lua:
> 
> ```
> table.foreach({1, 2, 3}, function(k, v) print(v) end)

I'm a little confused here. It was my understanding that running lua from within neovim via `luafile` or `:source` would use the neovim lua, which is of course luajit. I made sure by running each command for a file containing `print(_VERSION)` and `print(jit.version)` which outputs `Lua 5.1` and `LuaJIT 2.1.0-beta3` as expected.

I'm not sure how it is you are running that code without luajit unless you are running it from cli via a different lua binary than that one neovim uses.

**Comment by dstein64** [comment] 2022-05-20 02:29
> "I'm a little confused here. It was my understanding that running lua from within neovim via luafile or :source would use the neovim lua, which is of course luajit."

I wasn't sure if you were running the code from Neovim or not (since the problem is not specific to Neovim).

I think LuaJIT is conventionally the built-in version, but it's also possible (at least in the past) to build Neovim with e.g., Lua 5.1. That's what was included when I installed Neovim v0.4.3 on Ubuntu 20.04 on an `aarch64` virtual machine.

**Comment by zbirenbaum** [comment] 2022-05-20 02:34
> > "I'm a little confused here. It was my understanding that running lua from within neovim via luafile or :source would use the neovim lua, which is of course luajit."
> 
> I wasn't sure if you were running the code from Neovim or not (since the problem is not specific to Neovim).
> 
> I think LuaJIT is conventionally the built-in version, but it's also possible (at least in the past) to build Neovim with e.g., Lua 5.1. That's what was included when I installed Neovim v0.4.3 on Ubuntu 20.04 on an `aarch64` virtual machine.

I don't believe this remains possible but you may want to ask a maintainer. I build from source weekly at a minimum and I've always seen it build from luajit directly. I would also highly recommend against assuming anything from 0.4 is necessarily the same as the current implementation, and instead take a look at the makefile or source itself for such info.

It may be useful in the future to use diagnostics as I did to see if luajit resolves the symbols you reference properly. If it doesn't, odds are your code will make JIT drop out, and cause the slowdown which appeared here.

**Comment by dstein64** [comment] 2022-05-20 03:18
> "I don't believe this remains possible but you may want to ask a maintainer."

It looks like there's a build option:
https://github.com/neovim/neovim/blob/eb0aa8bb0ebc3cc233af6a5281c553d14ee57183/CMakeLists.txt#L442

I just tried it and got a build error, so I'm not sure if my environment is properly set up or whether it's currently supported.

When you initially referred to diagnostics, I thought you were referring to a _runtime error_ that was reported. I now realize that I was probably mistaken. There does seem to be an inconsistency with what the diagnostics show and what's available (e.g., `:lua print(type(table.foreach))` outputs `function`).

I guess the slowdown could relate to the _no bytecode, not yet implemented for `ITERN`_ status reported [here](http://wiki.luajit.org/NYI#libraries_table-library) for `table.foreach`.

**Comment by zbirenbaum** [comment] 2022-05-20 03:22
> I guess the slowdown could relate to the no bytecode, not yet implemented for ITERN status reported [here](http://wiki.luajit.org/NYI#libraries_table-library) for table.foreach.

Yeah this means it's not implemented in luajit so including it in your code will cause such issues. And no, I was referring to lsp diagnostics. Sorry for the mixup.

I would say this post can be closed, since the behavior has nothing to do with neovim and the upstream repo explicitly states that it does not support this functionality yet.

**Comment by dstein64** [comment] 2022-05-20 03:49
Even without JIT support, I wouldn't expect such a time difference between the newer version and old, and relative to Lua 5.1.

| Context | Seconds |
| ------------- | ------------- |
| Nvim 0.7 | 0.076882 |
| Nvim 0.6.1 | 0.003525 |
| Lua 5.1 | 0.003986 |

I have no objection to closing this ticket. I'll leave it up to the maintainers, in case they want to keep it open.

**Closed** 2022-05-20 17:19 UTC
Labels: bug, performance, dependencies
