### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#5552] opened 2016-10-31 14:52 UTC
- `nvim --version`:master
[log.txt](https://github.com/neovim/neovim/files/562027/log.txt)

```
           PID: 10146 (nvim)
           UID: 1000 (wsdjeg)
           GID: 1000 (wsdjeg)
        Signal: 11 (SEGV)
     Timestamp: Sat 2016-10-22 16:06:41 CST (1 weeks 2 days ago)
  Command Line: nvim job.vim
    Executable: /usr/local/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (wsdjeg)
       Boot ID: 1b4742bf18c34252a97bfe4573dd80d1
    Machine ID: fccbdca365d94df09a3d54f740f081ee
      Hostname: archlinux
       Message: Process 10146 (nvim) of user 1000 dumped core.
                
                Stack trace of thread 10146:
                #0  0x00000000081fa131 in_id_list (nvim)
                #1  0x0000000008201d09 syn_current_attr (nvim)
                #2  0x0000000008203201 get_syntax_attr (nvim)
                #3  0x00000000081bf3b8 win_line (nvim)
                #4  0x00000000081c266f update_single_line (nvim)
                #5  0x000000000816ab96 normal_redraw (nvim)
                #6  0x00000000081f92f4 state_enter (nvim)
                #7  0x0000000008167eaa normal_enter (nvim)
                #8  0x00000000080717ba main (nvim)
                #9  0x00000000b7534196 __libc_start_main (libc.so.6)
                #10 0x0000000008072cc5 _start (nvim)

           PID: 4710 (nvim)
           UID: 1000 (wsdjeg)
           GID: 1000 (wsdjeg)
        Signal: 11 (SEGV)
     Timestamp: Thu 2016-10-27 19:33:17 CST (4 days ago)
  Command Line: nvim README.md
    Executable: /usr/local/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (wsdjeg)
       Boot ID: e88ae53ef57a4202a60ad3c4fb014575
    Machine ID: fccbdca365d94df09a3d54f740f081ee
      Hostname: archlinux
       Message: Process 4710 (nvim) of user 1000 dumped core.
                
                Stack trace of thread 4710:
                #0  0x00000000b75b8d49 __memmove_sse2_unaligned (libc.so.6)
                #1  0x00000000080cf53b do_string_sub (nvim)
                #2  0x00000000080cf746 f_substitute (nvim)
                #3  0x00000000080be8a0 call_func (nvim)
                #4  0x00000000080c511f get_func_tv (nvim)
                #5  0x00000000080c37ab eval7 (nvim)
                #6  0x00000000080c3a4c eval6 (nvim)
                #7  0x00000000080c3d58 eval5 (nvim)
                #8  0x00000000080c4afa eval4 (nvim)
                #9  0x00000000080c4c9a eval2 (nvim)
                #10 0x00000000080c5172 eval0 (nvim)
                #11 0x00000000080cd857 ex_let (nvim)
                #12 0x00000000080f7804 do_one_cmd (nvim)
                #13 0x00000000080bd5b2 call_user_func (nvim)
                #14 0x00000000080be585 call_func (nvim)
                #15 0x00000000080c511f get_func_tv (nvim)
                #16 0x00000000080c37ab eval7 (nvim)
                #17 0x00000000080c3a4c eval6 (nvim)
                #18 0x00000000080c3d58 eval5 (nvim)
                #19 0x00000000080c4afa eval4 (nvim)
                #20 0x00000000080c4c9a eval2 (nvim)
                #21 0x00000000080c5172 eval0 (nvim)
                #22 0x00000000080ce9d6 ex_return (nvim)
                #23 0x00000000080f7804 do_one_cmd (nvim)
                #24 0x00000000080bd5b2 call_user_func (nvim)
                #25 0x00000000080be585 call_func (nvim)
                #26 0x00000000080c511f get_func_tv (nvim)
                #27 0x00000000080c37ab eval7 (nvim)
                #28 0x00000000080c3a4c eval6 (nvim)
                #29 0x00000000080c3d58 eval5 (nvim)
                #30 0x00000000080c4afa eval4 (nvim)
                #31 0x00000000080c4c9a eval2 (nvim)
                #32 0x00000000080c5172 eval0 (nvim)
                #33 0x00000000080ce9d6 ex_return (nvim)
                #34 0x00000000080f7804 do_one_cmd (nvim)
                #35 0x00000000080bd5b2 call_user_func (nvim)
                #36 0x00000000080be585 call_func (nvim)
                #37 0x00000000080c511f get_func_tv (nvim)
                #38 0x00000000080c37ab eval7 (nvim)
                #39 0x00000000080c3a4c eval6 (nvim)
                #40 0x00000000080c3d58 eval5 (nvim)
                #41 0x00000000080c4afa eval4 (nvim)
                #42 0x00000000080c4c9a eval2 (nvim)
                #43 0x00000000080c5172 eval0 (nvim)
                #44 0x00000000080c603c eval_to_string (nvim)
                #45 0x00000000080c6487 eval_to_string_safe (nvim)
                #46 0x000000000808b4ff build_stl_str_hl (nvim)
                #47 0x00000000081ba7b9 win_redr_custom (nvim)
                #48 0x00000000081bc8a4 win_redr_custom (nvim)
                #49 0x00000000081c73c4 update_screen (nvim)
                #50 0x00000000080ee1f0 ex_redraw (nvim)
                #51 0x00000000080f7804 do_one_cmd (nvim)
                #52 0x00000000080bd5b2 call_user_func (nvim)
                #53 0x00000000080be585 call_func (nvim)
                #54 0x00000000080c511f get_func_tv (nvim)
                #55 0x00000000080cbc72 ex_call (nvim)
                #56 0x00000000080f7804 do_one_cmd (nvim)
                #57 0x00000000080bd5b2 call_user_func (nvim)
                #58 0x00000000080be585 call_func (nvim)
                #59 0x00000000080c511f get_func_tv (nvim)
                #60 0x00000000080cbc72 ex_call (nvim)
                #61 0x00000000080f7804 do_one_cmd (nvim)
                #62 0x0000000008167fd0 nv_colon (nvim)
                #63 0x00000000081713cc normal_execute (nvim)
                
                Stack trace of thread 4713:
                #0  0x00000000b7705ce5 __kernel_vsyscall (linux-gate.so.1)
                #1  0x00000000b7572af7 syscall (libc.so.6)
                #2  0x0000000008234779 uv__epoll_wait (nvim)
                #3  0x0000000008232b1a uv__io_poll (nvim)
                #4  0x0000000008224a38 uv_run (nvim)
                #5  0x00000000080d9923 loop_poll_events (nvim)
                #6  0x000000000821000b tui_main (nvim)
                #7  0x0000000008212711 ui_thread_run (nvim)
                #8  0x000000000822f505 uv__thread_start (nvim)
                #9  0x00000000b76c7301 start_thread (libpthread.so.0)
                #10 0x00000000b75770ae __clone (libc.so.6)

           PID: 18390 (nvim)
           UID: 1000 (wsdjeg)
           GID: 1000 (wsdjeg)
        Signal: 11 (SEGV)
     Timestamp: Fri 2016-10-28 19:44:00 CST (3 days ago)
  Command Line: nvim README.md
    Executable: /usr/local/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (wsdjeg)
       Boot ID: 95f98a335311405ca44f4ecce7c8e864
    Machine ID: fccbdca365d94df09a3d54f740f081ee
      Hostname: archlinux
      Coredump: /var/lib/systemd/coredump/core.nvim.1000.95f98a335311405ca44f4ecce7c8e864.18390.1477655040000000000000.lz4
       Message: Process 18390 (nvim) of user 1000 dumped core.
                
                Stack trace of thread 18390:
                #0  0x00000000081fa8a5 in_id_list (nvim)
                #1  0x00000000082024a9 syn_current_attr (nvim)
                #2  0x00000000082039a1 get_syntax_attr (nvim)
                #3  0x00000000081bfb58 win_line (nvim)
                #4  0x00000000081c2e0f update_single_line (nvim)
                #5  0x000000000816b2d6 normal_redraw (nvim)
                #6  0x00000000081f9a94 state_enter (nvim)
                #7  0x00000000081685fa normal_enter (nvim)
                #8  0x00000000080717ea main (nvim)
                #9  0x00000000b74e9196 __libc_start_main (libc.so.6)
                #10 0x0000000008072cf5 _start (nvim)

           PID: 5753 (nvim)
           UID: 1000 (wsdjeg)
           GID: 1000 (wsdjeg)
        Signal: 11 (SEGV)
     Timestamp: Mon 2016-10-31 22:20:26 CST (24min ago)
  Command Line: nvim README.md
    Executable: /usr/local/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (wsdjeg)
       Boot ID: b4bbf088cc3e41869c41caed79498da0
    Machine ID: fccbdca365d94df09a3d54f740f081ee
      Hostname: archlinux
      Coredump: /var/lib/systemd/coredump/core.nvim.1000.b4bbf088cc3e41869c41caed79498da0.5753.1477923626000000000000.lz4
       Message: Process 5753 (nvim) of user 1000 dumped core.
                
                Stack trace of thread 5753:
                #0  0x00000000081faa85 in_id_list (nvim)
                #1  0x0000000008202689 syn_current_attr (nvim)
                #2  0x0000000008203b81 get_syntax_attr (nvim)
                #3  0x00000000081bfd08 win_line (nvim)
                #4  0x00000000081c2fbf update_single_line (nvim)
                #5  0x000000000816b486 normal_redraw (nvim)
                #6  0x00000000081f9c74 state_enter (nvim)
                #7  0x00000000081687aa normal_enter (nvim)
                #8  0x000000000807186a main (nvim)
                #9  0x00000000b7507196 __libc_start_main (libc.so.6)
                #10 0x0000000008072d75 _start (nvim)

           PID: 6084 (nvim)
           UID: 1000 (wsdjeg)
           GID: 1000 (wsdjeg)
        Signal: 11 (SEGV)
     Timestamp: Mon 2016-10-31 22:23:23 CST (21min ago)
  Command Line: nvim README.md
    Executable: /usr/local/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (wsdjeg)
       Boot ID: b4bbf088cc3e41869c41caed79498da0
    Machine ID: fccbdca365d94df09a3d54f740f081ee
      Hostname: archlinux
      Coredump: /var/lib/systemd/coredump/core.nvim.1000.b4bbf088cc3e41869c41caed79498da0.6084.1477923803000000000000.lz4
       Message: Process 6084 (nvim) of user 1000 dumped core.
                
                Stack trace of thread 6084:
                #0  0x00000000081faa85 in_id_list (nvim)
                #1  0x0000000008202689 syn_current_attr (nvim)
                #2  0x0000000008203b81 get_syntax_attr (nvim)
                #3  0x00000000081bfd08 win_line (nvim)
                #4  0x00000000081c2fbf update_single_line (nvim)
                #5  0x000000000816b817 normal_redraw (nvim)
                #6  0x00000000081f9c74 state_enter (nvim)
                #7  0x00000000081687aa normal_enter (nvim)
                #8  0x000000000807186a main (nvim)
                #9  0x00000000b74f1196 __libc_start_main (libc.so.6)
                #10 0x0000000008072d75 _start (nvim)
```

this issue happed with i3 split layout.
in my func, I use `call jobstart(['feh','foo.png'])`, then use `q` close the feh windows. then the nvim segmentation fault.

**Comment by wsdjeg** [comment] 2016-10-31 14:55
coredumpctl list show me :
```log
TIME                            PID   UID   GID SIG PRESENT EXE
Sat 2016-10-22 16:06:42 CST   10146  1000  1000  11   /usr/local/bin/nvim
Thu 2016-10-27 19:34:15 CST    4710  1000  1000  11   /usr/local/bin/nvim
Fri 2016-10-28 19:44:01 CST   18390  1000  1000  11 * /usr/local/bin/nvim
Mon 2016-10-31 22:20:26 CST    5753  1000  1000  11 * /usr/local/bin/nvim
Mon 2016-10-31 22:23:23 CST    6084  1000  1000  11 * /usr/local/bin/nvim
```

**Comment by justinmk** [comment] 2016-10-31 15:37
So when you close the "feh" window, this resizes nvim?

**Comment by wsdjeg** [comment] 2016-10-31 23:29
yeah. sometimes it works well, but some times it crash.

**Comment by justinmk** [comment] 2016-11-02 01:12
Very similar to https://github.com/neovim/neovim/issues/4796.

**Comment by wsdjeg** [comment] 2017-01-08 02:26
```
wsdjeg:SpaceVim [ dev | ✔  ] ➭ coredumpctl -1 info
           PID: 1448 (nvim)
           UID: 1000 (wsdjeg)
           GID: 1000 (wsdjeg)
        Signal: 11 (SEGV)
     Timestamp: Sun 2017-01-08 10:18:18 CST (6min ago)
  Command Line: nvim
    Executable: /usr/local/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (wsdjeg)
       Boot ID: 79c83866c15c4eeca259e70ca5e9f662
    Machine ID: fccbdca365d94df09a3d54f740f081ee
      Hostname: archlinux
       Storage: /var/lib/systemd/coredump/core.nvim.1000.79c83866c15c4eeca259e70ca5e9f662.1448.1483841898000000000000.lz4
       Message: Process 1448 (nvim) of user 1000 dumped core.
                
                Stack trace of thread 1448:
                #0  0x00000000080b0020 set_ref_in_ht (nvim)
                #1  0x00000000080aff25 set_ref_in_item (nvim)
                #2  0x00000000080bc855 garbage_collect (nvim)
                #3  0x000000000818dbe9 os_inchar (nvim)
                #4  0x00000000081f5057 state_enter (nvim)
                #5  0x000000000816804a normal_enter (nvim)
                #6  0x00000000080716b3 main (nvim)
                #7  0x00000000b74e8196 __libc_start_main (libc.so.6)
                #8  0x0000000008072bc5 _start (nvim)
```

**Comment by justinmk** [comment] 2017-01-08 02:29
@wsdjeg Are you able to reproduce it frequently? This is very similar to other reports, we haven't yet found a way to reproduce it.

**Comment by wsdjeg** [comment] 2017-01-08 02:37
@justinmk I think maybe it is same as other reports, I want to close it, and keep watch on #4796

**Comment by justinmk** [comment] 2017-01-08 02:53
@wsdjeg What were you doing at the time of the most recent crash? Did it involve jobstart() like your first post?

**Comment by wsdjeg** [comment] 2017-01-08 04:45
no, it is when I open `tagbar`, I am not sure if `tagbar` use job feature in it.

**Comment by mhinz** [comment] 2017-01-08 13:10
I really wonder what it is. I use tagbar a few times a day and never had a segfault with master so far..

**Comment by justinmk** [comment] 2017-01-27 12:56
The `win_line` crash is likely the same root cause as #5692. The  `do_string_sub` crash is likely the same as #5406. The `set_ref_in_ht` crash is already reported elsewhere.

 Given that there's no additional info here, closing this in favor of the other related tickets.

**Closed by justinmk** 2017-01-27 12:56 UTC
Labels: bug-crash, duplicate

**Comment by wsdjeg** [comment] 2017-01-27 13:57
Thanks. will follow the link you show me.
