### ISSUE TITLE
Neovim ignores rc file unless speciic

### ISSUE THREAD

**Issue by stevendlander** [neovim/neovim#3533] opened 2015-10-27 19:24 UTC

**Comment by Pyrohh** [comment] 2015-10-27 19:34
I assume this is a dupe of #3530.
Please see https://github.com/neovim/neovim/wiki/Following-HEAD#20151026

**Closed by Pyrohh** 2015-10-27 19:34 UTC

**Comment by stevendlander** [comment] 2015-10-27 19:37
Shoot, yes it is, and I realized I added the issue before I could fill in the details.  Thanks!
