### ISSUE TITLE
nvim_set_option undofile true doesn't work (lua)

### ISSUE THREAD

**Issue by Eja26** [neovim/neovim#11993] opened 2020-03-07 22:14 UTC
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Android/Termux
- Terminal name/version: Termux
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:lua vim.api.nvim_set_option('undofile', true)
:set undofile?
```

### Actual behaviour

undofile remains as noundofile.

### Expected behaviour

undofile should be 'undofile'.

Apologies if its a user error 😟.

**Comment by justinmk** [comment] 2020-03-07 22:19
- 'undofile' option is buffer-local. Use `nvim_buf_set_option`.
- Nvim 0.5 (unreleased) Lua has `vim.bo` for buffer-local options so you can do `:lua vim.bo.undofile=true`

Duplicate of https://github.com/neovim/neovim/issues/11179

**Closed by justinmk** 2020-03-07 22:19 UTC
Labels: bug, lua

**Comment by dagadbm** [comment] 2022-12-31 15:33
This doesnt work for some reason.
I tried to do this inside a lua file:
`vim.bo.undofile = true`
and nothing happens.
Ended up having to do vim cmd 'set undofile' like so:
```
-- using vim.bo.undofile = true does not work for some reason
vim.cmd 'set undofile'
```

I am using latest nvim (from head/nightly)

**Comment by zeertzjq** [comment] 2022-12-31 15:38
Use `vim.o.undofile`
