### ISSUE TITLE
:terminal type-to-display latency

### ISSUE THREAD

**Issue by blahgeek** [neovim/neovim#8815] opened 2018-08-05 04:04 UTC
- `nvim --version`: 

```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/config -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"

Run :checkhealth for more info
```
- Vim (version: 8.1) behaves differently? Yes
- Operating system/version: macOS 10.13.6
- Terminal name/version: Terminal.app (Note that for macOS, Terminal.app is significant faster than iTerm2)
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

I use [Typometer](https://pavelfatin.com/typometer/) to test responsiveness (type-to-display latency) of the terminal.

```
nvim -u NORC
:terminal cat # enter terminal, run cat, so that there's no extra delay from shell
i # enter insert mode
```

It's simply `cat` running inside neovim terminal echoing typed chars. Now run Typometer to measure its latency. The test result is: **min 53ms, max 80ms, avg 62ms**.

The test result for terminal outside neovim is: **min 7ms, max 29ms, avg 13ms**. The test result for terminal inside vim 8.1 or terminal inside tmux is also around 10 to 30 ms.

I would say that I can also feel the latency of terminal inside neovim being higher than terminal inside vim, though it may be biased.

**Comment by justinmk** [comment] 2018-08-05 11:04
I don't see any delay, even when holding down a key. Does this patch make a difference in your tests?

```diff
index c91b959ce3d7..deb0ba415224 100644
--- a/src/nvim/terminal.c
+++ b/src/nvim/terminal.c
@@ -91,7 +91,7 @@ typedef struct terminal_state {
-
 // Delay for refreshing the terminal buffer after receiving updates from
 // libvterm. Improves performance when receiving large bursts of data.
-#define REFRESH_DELAY 10
+#define REFRESH_DELAY 1
-
 static TimeWatcher refresh_timer;
 static bool refresh_pending = false;
```

**Comment by blahgeek** [comment] 2018-08-11 08:00
Here's the full test result:

Min/Max/**Avg** (ms) | `cat` | Insert mode in neovim | `:terminal cat` in neovim |
---|----|----|----|
Kitty 0.11.3 | 15.5/23.5/**17.7** | 15.0/34.0/**20.6** | 25.9/34.5/**28.4** |
Terminal.app | 6.1/27.7/**11.5** | 8.1/27.6/**11.1** | 51.0/71.7/**55.5** _(HERE!)_ |
iTerm2 3.1, Metal renderer | 24.9/52.9/**34.7** | 25.5/44.8/**36.2** | 39.3/48.2/**44.0** |

Regards of type-to-display latency,
1. Outside of neovim, Terminal.app is faster than Kitty and Kitty is faster than iTerm2 (even if Metal renderer is enabled)
2. Typing in neovim insert mode almost does not introduce extra latency
3. Terminal mode in neovim introduce some latency, especially in Terminal.app for some reason

**Comment by justinmk** [comment] 2018-08-11 13:54
@blahgeek Thank you for gathering those notes! I assume your tests were with `nvim -u NORC`?

> Terminal mode in vim 8.1 almost does not introduce extra delay

Terminal-mode (`:term` insert-mode) in Vim supports fewer features, for example it doesn't have Vim-driven syntax highlighting (try `:set ft=sh`). It's basically a stock libvterm window. 

There's probably room for improvement, and the Terminal.app discrepancy is worth investigating.

**Comment by blahgeek** [comment] 2018-08-11 14:46
>  I assume your tests were with `nvim -u NORC`?
Yes.

**Comment by dm1try** [comment] 2019-01-11 00:45
FYI, `REFRESH_DELAY` makes difference for me but I tested the latency using different conditions.
I have very smooth experience using Neovim with alacritty, all rendering is done under ~16ms in my case.

setup:
 MBP 2015 (integrated video)
 Alacritty + [this tweak](https://github.com/jwilm/alacritty/issues/897#issuecomment-343837767)(for smoothness in fullscreen mode 😑  )
 Neovim with `lazyredraw`

Terminal.app was tested without `termguicolors` as it does not support true color.

conditions:
  fullscreen window, editing ruby file
<img width="774" alt="screen shot 2019-01-11 at 03 15 07" src="https://user-images.githubusercontent.com/486807/51005258-293d6580-154f-11e9-8d88-9aa08019ec4d.png">
 
conditions:
  fullscreen window, insert mode of Neovim terminal(default `REFRESH_DELAY`)
<img width="774" alt="screen shot 2019-01-11 at 03 25 53" src="https://user-images.githubusercontent.com/486807/51005614-9ef60100-1550-11e9-879f-3521a503195c.png">

conditions:
  fullscreen window, insert mode of Neovim terminal(`REFRESH_DELAY` is `1`)
<img width="1014" alt="screen shot 2019-01-11 at 03 36 20" src="https://user-images.githubusercontent.com/486807/51005973-18daba00-1552-11e9-9060-90bb3cf1ba62.png">


though, in windowed mode and without Neovim, Terminal.app always feels smoother than others indeed
<img width="1014" alt="screen shot 2019-01-11 at 03 43 56" src="https://user-images.githubusercontent.com/486807/51006188-280e3780-1553-11e9-8c9d-159d5da3c04f.png">

**Comment by justinmk** [comment] 2019-04-28 08:30
Assuming this is a duplicate of https://github.com/neovim/neovim/issues/9452 .

**Closed by justinmk** 2019-04-28 08:30 UTC
Labels: :terminal, display, help wanted, performance
