### ISSUE TITLE
Executing `:%bwipeout!` inside `nvim_win_call()` can crash Nvim

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#31680] opened 2024-12-22 14:40 UTC
### Problem

Executing `:%bwipeout!` inside `nvim_win_call()` with target window in different tabpage and current window is floating can crash Neovim.

### Steps to reproduce

1. Create the following 'crash.lua' file:
    ```lua
    -- Create floating window
    local buf_id = vim.api.nvim_create_buf(false, true)
    local win_config = { relative = 'editor', row = 1, col = 1, height = 10, width = 10 }
    local float_win_id = vim.api.nvim_open_win(buf_id, true, win_config)

    -- Create tabpage and focus on float
    vim.cmd('tabnew')
    local tabpage_win_id = vim.api.nvim_get_current_win()
    vim.api.nvim_set_current_win(float_win_id)

    -- Delay '%bwipeout!' execution for demonstration
    vim.defer_fn(function()
      vim.api.nvim_win_call(tabpage_win_id, function() vim.cmd('%bwipeout!') end)
    end, 1000)
    ```
2. `nvim --clean`
3. `:source crash.lua`. Wait for 1 second and see Neovim crash.

Notes:
- There is no crash if initially focused window is not floating. For example, with `local float_win_id = vim.api.nvim_get_current_win()` as first paragraph.
- There is also no crash if target window is in the same tabpage. So instead of `vim.cmd('tabnew')` there is `vim.cmd('vert split')`.

### Expected behavior

No crash and all buffers are removed properly.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1397+gfd05c7f19d

### Vim (not Nvim) behaves the same?

Didn't check, as there is no direct comparison

### Operating system/version

EndeavourOS Linux x86_64, 6.12.4-arch1-1

### Terminal name/version

Ghostty 0.1.0-main+50cee999

### $TERM environment variable

xterm-ghostty

### Installation

appimage

**Comment by zeertzjq** [comment] 2024-12-22 14:44
Duplicate of #21409

**Closed by zeertzjq** 2024-12-22 14:44 UTC
Labels: bug-crash, floatwin

**Comment by echasnovski** [comment] 2024-12-22 15:01
> Duplicate of [#21409](https://github.com/neovim/neovim/issues/21409)

This was not really searchable 😅 

Just FYI, that this repro is *slightly* different: here floating window is both current and in current tabpage, while [here](https://github.com/neovim/neovim/issues/21409#issuecomment-1351022340) it is not. But indeed looks very similar.
