### ISSUE TITLE
Pasting into the terminal emulator adds weird characters

### ISSUE THREAD

**Issue by OskarPersson** [neovim/neovim#4122] opened 2016-01-28 20:44 UTC
When pasting any text from the system clipboard into the terminal emulator I get weird characters both before and after the text. This only happens in the terminal emulator, not in any other mode and only when using the system shortcut (`CMD-v`). I'm on version v0.1.2-371-g1574c4a from Homebrew on OSX 10.11.2

![skarmavbild 2016-01-28 kl 21 38 59](https://cloud.githubusercontent.com/assets/935414/12658208/e7238b50-c607-11e5-9822-309701702317.png)

**Comment by ZyX-I** [comment] 2016-01-28 20:52
Duplicate of #3476

**Closed by ZyX-I** 2016-01-28 20:52 UTC
