### ISSUE TITLE
Better visual substitution

### ISSUE THREAD

**Issue by alexmozaidze** [neovim/neovim#23799] opened 2023-05-28 09:49 UTC
### Problem

I wanted to substitude in the visual selected region, but it spans throughout the entire line, substituting what shouldn't be substituted. The problem is resolved when using `\%V`, but it's very verbose and unintuitive. I've made a [keybind](https://vi.stackexchange.com/a/31149) in my `init.lua`, but it's quite inconvenient to use.

Same issue: https://vi.stackexchange.com/questions/1922/how-to-replace-only-within-visual-selection

### Expected behavior

*Visual* and *Block-Visual* modes only substitude in their selected region.

**Comment by ad-chaos** [comment] 2023-06-01 16:55
Possible Duplicate of #22297

**Comment by justinmk** [comment] 2023-06-02 12:09
Are you suggesting a default mapping...? Unless someone thinks of a really good one this is wontfix except for https://github.com/neovim/neovim/issues/22297 as mentioned.

**Closed by justinmk** 2023-06-02 12:09 UTC
Labels: enhancement, defaults
