### ISSUE TITLE
cursor overridden after quitting

### ISSUE THREAD

**Issue by daviehh** [neovim/neovim#24267] opened 2023-07-05 23:47 UTC
### Problem

I have set the cursor of my terminal to be a thin vertical line, but the cursor of the terminal after quitting nvim is block-type

### Steps to reproduce

```
nvim --clean
:q
```

### Expected behavior

System setting of cursor should be restored.

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 15 2023 04:26:46)

### Operating system/version

macOS 13.4.1 

### Terminal name/version

xterm

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by daviehh** [comment] 2023-07-05 23:50
screen capture:


https://github.com/neovim/neovim/assets/25255906/895b29e8-20c5-4661-a765-a2e041a8388b

**Comment by zeertzjq** [comment] 2023-07-05 23:51
Duplicate of #4396

**Closed by zeertzjq** 2023-07-05 23:51 UTC
Labels: bug
