### ISSUE TITLE
comment on non-linewise text objects

### ISSUE THREAD

**Issue by Konfekt** [neovim/neovim#30477] opened 2024-09-23 07:55 UTC
### Problem

Neither `gc$` nor a visual selection from the cursor to the end of the line and typing `gc` comments the intended part but the complete line

### Expected behavior

`gc` comments the given text-object

**Comment by justinmk** [comment] 2024-09-23 07:57
Duplicate of https://github.com/neovim/neovim/issues/29834

**Closed by justinmk** 2024-09-23 07:57 UTC
Labels: enhancement, comment
