### ISSUE TITLE
E363: pattern uses more memory than 'maxmempattern'

### ISSUE THREAD

**Issue by rbhanot4739** [neovim/neovim#12304] opened 2020-05-12 17:57 UTC
- `nvim --version`:0.4.3
- Operating system/version: MacOs Catalina 10.15.4 
- Terminal name/version: Iterm2 - zsh
- `$TERM`: screen-256color
- `FZF Version`: 0.21.1 (334a4fa)
- `fzf.vim`: 3925db8

### Actual behaviour
I am using FZF version inside of Neovim and when ever I try to launch it I get this error `E363: pattern uses more memory than 'maxmempattern'`. 

To fix this issue I set `mmp=2000` and now when I run `FZF`  again, the fzf window opens but it is really slow, takes around ~3 seconds to load, typing the fuzzy string is really laggy.

Here are some of the tests which shows this is a Neovim issue.

- On the command line running `fzf` or `ctrl-c` is instant and list all the files within a second.  
- I have tested same setup with Vim 8.1 and this issue does not seem to occure in Vim. 
- I tested same setup by installing Neovim on a Red Hat machine and same issue occurred on that machine as well.

Please let me know if more information is required in order to troubleshoot or debug this issue.

For reference`FZF_CTRL_T_COMMAND` is set to `fd --type file --hidden --follow .`

### Expected behaviour
FZF should launch within Neovim instantly just like it opens in Vim or on the shell.

**Comment by rbhanot4739** [comment] 2020-05-13 11:09
Any update on this ?

**Comment by rbhanot4739** [comment] 2020-05-13 14:47
Any update on this ?

**Comment by glacambre** [comment] 2020-05-13 17:23
On 2020-05-13 16:47, RohitB wrote:
> Any update on this ?

You should be the one providing updates on this, since you're the one 
who can reproduce this issue ;)

Can you reproduce this with neovim nightly? Does it still happen with an 
init.vim that does nothing except load FZF? From a brief look online it 
looks like MacOS has a tool named "Time Profiler" to measure the 
performance of programs, have you tried to use it to see where neovim is 
spending time?

**Comment by PanAeon** [comment] 2021-04-27 17:22
@rbhanot4739 I can reproduce this issue with the latest `vim-better-comments` plugin enabled.
Could you confirm it's the same for you?

**Comment by glacambre** [comment] 2021-06-08 16:07
No reproducer, no way to know if this is fixed or not, so I'll close this issue.
@rbhanot4739 if you are still experiencing this problem, let us know (with a reproducer ;) ) and we'll re-open.

**Comment by meredrica** [comment] 2021-08-02 10:02
I had the same issue. for anyone ending up here: better comments is to blame

**Comment by meredrica** [comment] 2021-08-02 10:09
Here's the bugreport for better comments.
https://github.com/jbgutierrez/vim-better-comments/issues/8
however @glacambre this does not happen in vim 8

**Comment by meredrica** [comment] 2021-08-03 07:12
@glacambre i don't have a repo without plugins but below is a minimal init.vim that will automatically download vimplug and the two addons (fzf needs to be installed first)
```vim
" automagically install plugin management and all plugins if they are not present
if empty(glob(stdpath('data') . '/site/autoload/plug.vim'))
	execute '!curl -fLo ' . stdpath('data') . '/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin(stdpath('data') . '/plugged')

" comment highlighting
Plug 'jbgutierrez/vim-better-comments'
Plug 'junegunn/fzf.vim'

call plug#end()
```

**Comment by justinmk** [comment] 2021-09-24 13:55
no repro provided. 

1. find the actual regex
2. test it in Vim (not Nvim)
3. explain why it's a bug rather than actually just an expensive regex

**Closed by justinmk** 2021-09-24 13:55 UTC
Labels: bug
