### ISSUE TITLE
scroll screen-lines (long/wrapped) instead of text lines

### ISSUE THREAD

**Issue by GianniGi** [neovim/neovim#8715] opened 2018-07-10 09:28 UTC
I've been using vim for years to write prose, books, letters, tex, and to write code, and now I'm considering neovim because of this.

I've been growing increasingly frustrated by the lack of a nice way to navigate through long lines. And yes, I've remapped j and k to gj and gk, but yet all the other nice ways to scroll and navigate through text remain absolutely unusable (c-e, c-y, mouse wheel scroll, c-d, c-u...). Through the years I've found a very big number of topics on this subject, and many users that have requested this function. Many of them tried hard to get into it but end up getting really frustrated by its scrolling behavior and then give up.

**Can we please add an option that makes vim consider equal the soft wrapped (visual) lines and the hard wrapped lines? This will make my job infinitely more easy and enjoyable too.**

some links:
http://vim.1045645.n5.nabble.com/Scrolling-Long-Lines-Revisited-Again-td5031203.html
2001 "scrolling long lines": http://marc.info/?l=vim&m=100485909423627&w=2
2002 "smooth scroll": http://marc.info/?l=vim&m=102468968303594&w=2
2005 "how to view a long line": http://marc.info/?l=vim&m=111466655128136&w=2
2009 "can vim jump line by screen-line": http://groups.google.com/group/vim_use/browse_thread/thread/85318546ec889513/73ac449d902662e6
2010 "long lines and scrolling": http://groups.google.com/group/vim_use/browse_thread/thread/ed77cb8d39ff1bbf/31d252de859a80d5
http://vim.1045645.n5.nabble.com/Long-lines-and-scrolling-td1183898.html
http://vim.1045645.n5.nabble.com/Scrolling-Long-Lines-Revisited-Again-td5031203.html
https://vi.stackexchange.com/questions/11315/visual-scrolling-visual-c-e-and-c-y-across-wrapped-lines/11383#11383
http://vim.1045645.n5.nabble.com/Scrolling-screen-lines-I-knew-it-s-impossible-td3358342.html
http://vim.1045645.n5.nabble.com/Feature-request-Display-partial-paragraph-at-the-top-of-the-window-td1166809.html
https://github.com/neovim/neovim/issues/7172
https://vi.stackexchange.com/questions/11315/visual-scrolling-visual-c-e-and-c-y-across-wrapped-lines/11383#11383
set display+=lastline

**Comment by justinmk** [comment] 2018-07-10 17:45
It's a bit weird to link to https://github.com/neovim/neovim/issues/7172 and then open a new issue here, but I'll close that one since this has more references.

Nothing is going to materialize for this, however, unless someone sends a pull request with test coverage.

**Comment by GianniGi** [comment] 2018-07-12 09:02
Thanks for taking this into consideration. I hope that someone notices this and suddenly feels the desire to write some useful code. 
I think that line wrapping is one of the biggest problems that keeps away the beginners from the neovim world.

**Comment by GianniGi** [comment] 2018-07-16 16:16
Is there something we can do to reach more developers or more users that may want the same feature?

**Comment by GianniGi** [comment] 2018-07-16 16:48
OMG sorry for clicking some decorative icons, what a big big mistake :-D

**Comment by GianniGi** [comment] 2018-07-16 16:49
I've added more upvotes. Seems good.

**Comment by zwegner** [comment] 2019-09-14 00:04
I've done some work on this, as it's pretty much required for terminals to behave sanely with reflowing. Lots of hairy code to deal with! It's likely this will be pretty slow for extremely long lines without some new data structures, but vim wasn't great at dealing with those anyways.

Branch with some initial work: https://github.com/zwegner/neovim/tree/rowwise

And some tasty initial results:
![nvim-scroll-demo](https://user-images.githubusercontent.com/3751892/64898871-7af23e80-d64e-11e9-951d-417641642271.gif)

**Comment by blueyed** [comment] 2019-09-14 00:06
> Branch with some initial work: https://github.com/zwegner/neovim/tree/rowwise

Feel free to create a PR already - you'll get results from CI and we can discuss on the code directlly.

**Comment by zwegner** [comment] 2019-09-14 00:13
OK cool, will do. I'm not gating any behavior behind a setting yet, so I'm sure it will break something...

**Comment by zwegner** [comment] 2019-09-14 00:34
https://github.com/neovim/neovim/pull/11014

**Comment by GianniGi** [comment] 2019-09-17 14:23
fantastic news, thank you very much

**Comment by FreddieOliveira** [comment] 2019-11-08 04:16
Out of curiosity, how's the progress on this?

**Comment by forgetmenotz** [comment] 2019-11-13 12:58
I recently started using vim (the original) but there seems to be more interest in this subject here. I came across this problem yesterday. The only solution I found online was to make the "textwidth" the same as the number of columns of characters in the insert window, in my case, :set textwidth 112 and reformat with the key sequence " gggqG " (without the quotes). Then it allows scrolling by row without jumping between paragraphs. But this screwed up if I resize the window for example, so I wrote a function to re-enable this upon 'VimResize':

function Getcolumns()
       let alines = line('$')
       let acolumns = &columns
       let lineslen = len('alines')
       let b:realcolumns = acolumns - lineslen
       echo b:realcolumns
       "set formatoptions+=t
      let &textwidth = b:realcolumns
      :execute "normal gggqGgg"
  endfunction

 autocmd VimResized * call Getcolumns()                                                                            
 autocmd VimEnter * call Getcolumns()

I don't have much coding experience, sorry about the bloatedness, style. It works for me in vim except sometimes I can't backspace and have to delete in normal mode. I can't understand why this happens. Hope to see the changes people mentioned above merged into nvim.

**Comment by FreddieOliveira** [comment] 2019-11-14 19:05
From what I understood you just stopped using soft line wrap and are using hard ones. This isn't the same as seen [here](https://github.com/neovim/neovim/issues/8715#issuecomment-531425987). What we are willing to have is a way to scroll the screen line by line with soft wraps instead of turning them into hard line breaks.

**Comment by resolritter** [comment] 2022-07-12 03:15
I've been mulling over the idea of row-wise scrolling from a similar use-case where it's necessary for me to know the bounds (column-wise start + end) of displayed physical lines. Perhaps the ideas could be applied for this as well.

From https://github.com/neovim/neovim/pull/11014 and this thread's discussions I understood that one of the reasons why row-wise scrolling is hard is due to Neovim's internal data structures not being primed for this use-case (https://github.com/neovim/neovim/pull/11014#issuecomment-536761143). It looks like the implementation of https://github.com/neovim/neovim/pull/11014 @ 7d333c6d297bf03b2cde77d4c54294bd587572d1 requires recomputing physical lines up to the cursor position and that would be slow for long lines.

What I've been thinking about revolves around computing displayed physical lines' bounds based on the amount of skipped **line buffer characters** from the top line (which is not `w_skipcol` since `w_skipcol` also counts virtual characters such as `showbreak`). Starting from that offset we'd continuously slice line fragments until the whole available text area for the current screen is filled, therefore knowing the displayed physical lines' bounds. Having this data could allow for a crude manner of userland row-wise scrolling, e.g. to scroll down (assumes `set scrolloff=0`):

```
If on the bottom physical line:
  Input "gj"
Otherwise:
  Save cursor position
  Go to the bottom physical line
  Input "gj", therefore making the window scroll
  Restore the cursor position
```

That being said, since the bottom physical line's bounds would be known, it should be possible to infer the next one's bounds without scrolling the screen.

I'm unsure if I'm missing or misunderstanding something which would make this idea unreasonable.

**Comment by zwegner** [comment] 2022-07-13 09:01
The issue with this is that current neo-/vim is not capable of showing more than one line on screen if the beginning of the first line is not shown (at least that's my recollection, it's been a while since I've played with this). If you were to input "gj" on the last row of a line that filled the whole screen, the entire line is scrolled off screen (and likewise with scrolling up). I'm not sure how you'd get a usable row-wise scrolling just from userspace modifications, but it'd be nice to be proven wrong! Or maybe for your use case the jumpiness doesn't matter?

According to the last comment I made on the pull request, this is apparently not too far from being mergeable as an experimental feature. I haven't had much time for open source work in a while, but maybe I can brush that code off sometime soon.

**Comment by resolritter** [comment] 2022-07-13 10:25
> The issue with this is that current neo-/vim is not capable of showing more than one line on screen if the beginning of the first line is not shown (at least that's my recollection, it's been a while since I've played with this). If you were to input "gj" on the last row of a line that filled the whole screen, the entire line is scrolled off screen (and likewise with scrolling up).

I was considering "row-wise scrolling" merely as the capability of shifting the text in terms of physical lines, without regards for how it was presented. I wasn't taking into consideration much of what you said there when it comes to look and feel, so apologies.

> Or maybe for your use case the jumpiness doesn't matter?

Yes, it wouldn't matter for me. What I described there is more like "text scrolling in terms of physical lines" rather than the "row-wise scrolling" being envisioned for that feature as I perceive it now.

> According to the last comment I made on the pull request, this is apparently not too far from being mergeable as an experimental feature. I haven't had much time for open source work in a while, but maybe I can brush that code off sometime soon.

I saw one of your mentions about how bothersome it is to grapple with some of the options. It definitely feels that way even from an outsider's perspective, but I hope it's not bad enough to discourage you from pursuing the idea. Best of luck with your PR. :-)

**Comment by resolritter** [comment] 2022-07-13 11:06
Just for curiosity's sake, here's one demonstration of the idea mentioned in https://github.com/neovim/neovim/issues/8715#issuecomment-1181266849. Disclaimer: The code was put together for the purposes of this demo only, it might be bugged and doesn't handle various cases since the point is just to show how it could be possible.

```vim
fun! CheckRescroll()
  let now = winsaveview()
  if g:start.lnum != now.lnum
    return
  endif
  if g:start.skipcol == now.skipcol
    call Scroll(v:false)
  else
    call cursor([g:start.lnum, g:start.col])
  endif
endfun
noremap <Plug>(CheckRescroll) <cmd>call CheckRescroll()<CR>

fun! Scroll(set_start)
  if a:set_start
    let g:start = winsaveview()
  endif
  call feedkeys("gj", "n")
  call feedkeys("\<Plug>(CheckRescroll)")
endfun
nnoremap <c-e> <cmd>call Scroll(v:true)<CR>
```


https://user-images.githubusercontent.com/17429390/178718526-799446e3-fb95-4ad3-823f-fb4a3a19bfa0.mp4

Since there's no API for computing bounds for physical lines, nor an API to scroll by line without `gj` that I know of, the approach there is to keep inputting `gj` until we detect that the screen has been scrolled, then restore the cursor after. Pretty ugly and hacky, but doable.

**Comment by Hi-Angel** [comment] 2022-12-03 12:09
FTR, the original vim project [claims to have added an option `smoothscroll`](https://github.com/vim/vim/issues/3188#issuecomment-1336132779) to solve that issue. So for compatibility purposes I think would be useful to have the option implementing that named similarly.

**Comment by chrismit3s** [comment] 2023-03-03 15:57
The `smoothscroll` option for vim works as intended, so are there any updates on this feature in Neovim?

**Comment by clason** [comment] 2023-03-03 15:58
Somebody needs to port the patches. Maybe you?

**Comment by ychin** [comment] 2023-03-03 18:45
If you want to port the Vim `smoothscroll` patches over, you may want to just gather the full list of commits first as a lower effort initial work just to gauge the scope, since there are quite a few over the months as the initial feature was quite buggy and could result in cursor flying off the window. I [had 5](https://github.com/vim/vim/issues?q=author%3Aychin+smoothscroll) myself, and there are quite a few other ones. It couldbe useful to look at them as a whole if you don't want to retrace the bug -> fix bugs commits.

**Closed** 2023-05-02 11:42 UTC
Labels: enhancement, has:vim-patch, core

**Comment by Ddystopia** [comment] 2025-05-31 15:55
To have it mentioned, https://github.com/neovim/neovim/pull/23320 is not handling `scrolloff` and it still jumps when scrolling with j/k in some circumstances. Should I open a separate issue?
