### ISSUE TITLE
Feature request: option for incresing spacing between LineNr and text

### ISSUE THREAD

**Issue by pedro-augusto-santana** [neovim/neovim#14458] opened 2021-04-29 21:04 UTC
First of all, awesome work from all contributors of the incredible text editor

Consider, the feasibility of adding an option for increasing the spacing between the line numbers and the text
Example 1: Sublime Text
![image](https://user-images.githubusercontent.com/48259258/116617839-abb2e480-a914-11eb-9b33-05fa1e8a6848.png)

Example 2: Vim
![image](https://user-images.githubusercontent.com/48259258/116617863-b40b1f80-a914-11eb-8865-ad78048229c3.png)

As can be seen in the examples, Sublime Text and other editors in general have the option to edit the width of the column
I am aware of the `numberwidth` option, although it only changes the left side of the column
![image](https://user-images.githubusercontent.com/48259258/116618117-08ae9a80-a915-11eb-97bf-ef9cf84228f4.png)

**Comment by bew** [comment] 2021-04-30 09:58
My 2c, I'd argue about adding more styling options like this. I think this can be solved more cleanly with a format string for the whole left side, giving options for signs, line-numbers, spacing, folds, ..

A simple example could be along the lines of `{signs:2}{numbers:2-}  `, this would give a sign column of 2, a number columns of at least 2, and some spaces before the text.
(to be developed of course to support more options in a generic way. Or we could also use a syntax similar to the statusline.

**Comment by teto** [comment] 2021-04-30 21:13
duplicate of https://github.com/neovim/neovim/issues/6092

I agree with @bew I've started tagging issues about columns with `topic:column` and there are just too many needs to cover it with options.

**Closed by teto** 2021-04-30 21:13 UTC
Labels: enhancement, topic:column

**Comment by teto** [comment] 2021-04-30 22:09
virtualtext support has regularly improved so maybe it will reach a point where someone can hack together columns based on virtualtext wirtten at the beginning of the line.

**Comment by bfredl** [comment] 2021-04-30 22:17
we probably want to 

> virtualtext support has regularly improved so maybe it will reach a point where someone can hack together columns based on virtualtext wirtten at the beginning of the line.

indeed this is the (not so) secret plan.
