### ISSUE TITLE
Overflow on status bar with 'wrap'

### ISSUE THREAD

**Issue by Yamakaky** [neovim/neovim#3876] opened 2015-12-21 10:54 UTC
1. open a thin neovim window
2. put your cursor on the last visible line (spam <SPACE>)
3. fill the line with text
4. when the line is filled, the cursor goes on the next visible line, which is... the status bar!
5. if you put an other character, the window scrolls as expected.

It's not a big bug, just a bit strange to see ^^

**Comment by alexozer** [comment] 2015-12-21 17:14
I've noticed this also occurs in vim, not just neovim.

**Comment by glacambre** [comment] 2021-06-05 08:55
@Yamakaky I can't reproduce this bug anymore on master+kitty, so I'll close this issue. Let me know if you can still reproduce it and I'll re-open :).

**Closed by glacambre** 2021-06-05 08:55 UTC
Labels: 0.kind: bug-vim
