### ISSUE TITLE
:terminal - soft-wrap long lines

### ISSUE THREAD

**Issue by firedev** [neovim/neovim#5506] opened 2016-10-19 10:26 UTC
### Actual behaviour

When the long line is wrapped in the terminal buffer linebreaks are inserted in the yanked text
### Expected behaviour

In the actual terminal you can copy long lines just fine
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:term
echo "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
<C-\><C-n>
ggV5jy
```

Paste somewhere and if the line of zeroes was long enough to wrap you will see that it is broken down into few lines.

http://vi.stackexchange.com/questions/9944/copy-from-neovims-terminal-without-linebreaks

**Comment by lahwran** [comment] 2016-10-19 18:19
I don't know if opinions on this have changed, but this was rejected by the libvterm author a while ago when I was asking him for it.

**Comment by justinmk** [comment] 2016-10-19 20:39
@lahwran Thanks for that valuable link, I hadn't seen that before.

> The scrollback history is, to a rough approximation, an array of unwrapped lines. 

FWIW, in https://github.com/neovim/neovim/pull/5485 I've removed all the hyperactive resizing of terminals (I'll add some optional auto-resizing later). This allows one to set a fixed terminal size:

    :call jobstart('bash -i', {'type':'term', 'width':999})

What's interesting is that Vim's `:set nowrap` seems to kinda work with this. ANSI colors get mis-aligned, but things like a `python` REPL wrap correctly. Then you can `y`ank any wrapped line.

Keeping this open in sight of a half-solution in this area.

**Comment by lahwran** [comment] 2016-10-19 22:48
that's a good solution for most scenarios. I don't think it's hopeless to implement but it would be a major change.

**Comment by techfishio** [comment] 2018-08-27 00:26
@lahwran Has anything changed regarding the hard-wrapped terminal lines? I am frequently copy/pasting from terminal, the line breaks are borderline depressing me. Love the embedded terminal, was using Tmux + Vim before and all it does is cause problems (especially with fonts).

Also I don't understand the "workaround". If I call that command it either starts a terminal with the hard breaks or takes over my whole nvim window with an ultra-wide terminal.

**Comment by paulreimer** [comment] 2019-02-28 17:18
I wish this worked -- without it, `tmux`/`screen` are still superior terminal managers. I'm not even resizing/reflowing the window, just a fixed, fullscreen column count.

If anyone has a working workaround (even hard-coding column numbers), that would be greatly appreciated.

**Comment by justinmk** [comment] 2019-08-28 00:57
Duplicate of #2514 (which is seeing progress recently).

**Closed by justinmk** 2019-08-28 00:57 UTC
Labels: :terminal, enhancement
