### ISSUE TITLE
LSP:  NixD throws 'semantic tokens' errors after update to 0.10.2

### ISSUE THREAD

**Issue by Sk7Str1pe** [neovim/neovim#30767] opened 2024-10-11 20:30 UTC
### Problem

Editing .nix files using nixd becomes impossible if file contains nerdfonts glyphs (not commented or included in function. 

Check nix-community/nixvim#2390

### Steps to reproduce using "nvim -u minimal_init.lua"

```Lua
local pattern = 'nix'
local cmd = {'nixd'}
-- Add files/folders here that indicate the root of a project
local root_markers = {'.git', '.editorconfig'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'nixd',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```
Tho I configured this via NixVim, its config:
```Nix
programs.nixvim = {
  enable = true;
  lsp = {
  enable = true;
  inlayHints = true;
  servers = {
    nixd = {
      enable = true;
    };
  };
}
```

### Expected behavior

No errors idk

### Nvim version (nvim -v)

0.10.2

### Language server name/version

latest idk

### Operating system/version

NixOS 24.11

### Log file

[START][2024-10-08 20:06:15] LSP logging initiated [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.636] 16509: <-- initialize(1)\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.636] 16509: --> reply:initialize(1)\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.637] 16509: --> call window/workDoneProgress/create(1)\nI[20:06:15.637] 16509: --> notify $/progress\nI[20:06:15.637] 16509: --> call attrset/evalExpr(1)\nI[20:06:15.637] 16509: --> call window/workDoneProgress/create(2)\nI[20:06:15.637] 16509: --> notify $/progress\nI[20:06:15.637] 16509: --> call attrset/evalExpr(1)\nI[20:06:15.637] 16509: --> call workspace/configuration(3)\nI[20:06:15.638] 16509: <-- initialized\nI[20:06:15.638] 16509: <-- textDocument/didOpen\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.639] 16509: --> notify textDocument/publishDiagnostics\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.639] 16509: <-- textDocument/inlayHint(2)\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.639] 16509: <-- textDocument/inlayHint(3)\nI[20:06:15.639] 16509: <-- reply(1)\nI[20:06:15.639] 16509: --> call attrset/attrpathInfo(2)\nI[20:06:15.639] 16509: --> call attrset/attrpathInfo(3)\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.639] 16509: <-- reply(2)\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.640] 16509: <-- reply(3)\nE[20:06:15.640] 16509: workspace/configuration: parse error expected object\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.640] 16509: <-- textDocument/semanticTokens/full(4)\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.643] 16509: --> reply:textDocument/semanticTokens/full(4)\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.793] " [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"16509: <-- reply(1)\nI[20:06:15.793] 16509: --> notify $/progress\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.794] 16509: <-- reply(2)\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.794] 16509: <-- reply(3)\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"20:06:15.794] 16509: --> reply:textDocument/inlayHint(2)\n" [ERROR][2024-10-08 20:06:15] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:15.794] 16509: --> reply:textDocument/inlayHint(3)\n" [ERROR][2024-10-08 20:06:16] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/2dx04iayp5nl6zwsa60dsm82c58ghwk7-nixd-2.4.0/bin/nixd"	"stderr"	"I[20:06:16.157] 16509: <-- reply(1)\nI[20:06:16.157] 16509: --> notify $/progress\n"

**Comment by eljamm** [comment] 2024-10-11 20:59
This is likely a duplicate of https://github.com/neovim/neovim/issues/30675

**Comment by glepnir** [comment] 2024-10-12 05:39
duplicate #30675

**Closed by glepnir** 2024-10-12 05:39 UTC
Labels: bug, lsp
