### ISSUE TITLE
Neovim crashes when doing a regex replace that involves using \

### ISSUE THREAD

**Issue by medwatt** [neovim/neovim#12942] opened 2020-09-20 02:30 UTC
- `nvim --version`: NVIM v0.5.0-704-g905c2eb35
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Windows 10
- Terminal name/version: nvim-qt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

Just try to do a regex replace such as:
```vim
:%s/\v(some_text)/\1
```
I also have `incsearch` turned on.

### Actual behaviour
As soon as the backslash (\\) is typed (before the 1 in the expression above), nvim crashes.

### Expected behaviour
Neovim shouldn't crash when you type \ while doing a regex replace.

Edit: I just tested an old version (0.5.0-627) which was compiled around August 13 and it does not have this issue.

**Comment by erw7** [comment] 2020-09-20 03:10
Duplicate of #12932.

**Closed by erw7** 2020-09-20 03:10 UTC
Labels: bug
