### ISSUE TITLE
Neovim segfault on exit with a specific viminfo

### ISSUE THREAD

**Issue by duongdominhchau** [neovim/neovim#12042] opened 2020-03-23 13:36 UTC
I am configuring neovim using the command `sudo vim /etc/xdg/nvim/sysinit.vim`, when I set `viminfo` to contain both `:0` and `/0` it crashes on exit with the message `zsh: segmentation fault (core dumped)  vim`. I have succesfully reproduced this problem with one-line config file containing only `set viminfo='100,:0,/0`.

- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system: ArchLinux
- Terminal name: Alacritty
- Shell: `zsh` version 5.8
- `$TERM`: `xterm-256color`

**Comment by lacygoill** [comment] 2020-03-24 01:08
Possible duplicate of https://github.com/neovim/neovim/issues/11497.

**Comment by glacambre** [comment] 2021-06-07 05:39
Can't reproduce on master and other issue has been closed, so this most probably has been fixed. Closing :).

**Closed by glacambre** 2021-06-07 05:39 UTC
Labels: bug
