### ISSUE TITLE
Joining multiple lines ending with `>` will collapse them

### ISSUE THREAD

**Issue by Nales0** [neovim/neovim#30114] opened 2024-08-21 19:39 UTC
### Problem

Joining multiple lines with each of them ending with `>` will join them and leave only one `>`.

### Steps to reproduce

Open neovim with the following command.

```
nvim -u NONE
```

Write the following:

```
>
>
>
```

Select all lines and join them by typing in normal mode `ggVGJ`. The file now contains:
```
>
```

### Expected behavior

After this command, the file should contain the three `>` in one line.

It should ever be like that if it follows the behaviour when joining `)`.

```
>>>
```

Or it should be like that if it follows the behaviour for other characters.

```
> > >
```

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

I did not test it.

### Operating system/version

Linux Mint 21.2

### Terminal name/version

Terminal MATE 1.26.0

### $TERM environment variable

xterm-256color

### Installation

Ubuntu packages maintained by Ubuntu Developers

**Comment by clason** [comment] 2024-08-21 19:43
> I did not test it. 

Then please test it. That field is there for a reason. 

(If the chevron is considered as a comment marker, this is expected default behavior and cam be controlled by options.)

**Comment by zeertzjq** [comment] 2024-08-21 21:27
Duplicate of #16017

**Closed by zeertzjq** 2024-08-21 21:27 UTC
Labels: bug

**Comment by Nales0** [comment] 2024-08-21 23:11
> Then please test it. That field is there for a reason.

The problem does not appear with this version.

```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 03 2024 02:37:51)
Included patches: 1-579, 1969, 580-1848, 4975, 5016, 5023, 5072, 2068, 1849-1854, 1857, 1855-1857, 1331, 1858, 1858-1859, 1873, 1860-1969, 1992, 1970-1992, 2010, 1993-2068, 2106, 2069-2106, 2108, 2107-2109, 2109-3995, 4563, 4646, 4774, 489
5, 4899, 4901, 4919, 213, 1840, 1846-1847, 2110-2112, 2121
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Small version without GUI.  Features included (+) or not (-):
+acl               -cindent           -cursorshape       -file_in_path      -job               -menu              -mouse_urxvt       -popupwin          -smartindent       -tcl               -vartabs           +writebackup
-arabic            -clientserver      -dialog            -find_in_path      +jumplist          -mksession         +mouse_xterm       -printer           -sodium            -termguicolors     +vertsplit         -X11
+autocmd           -clipboard         -diff              -float             -keymap            +modify_fname      +multi_byte        -profile           -sound             -terminal          +vim9script        +xfontset
-autochdir         +cmdline_compl     -digraphs          -folding           -lambda            +mouse             -multi_lang        -python            -spell             +terminfo          -viminfo           -xim
-autoservername    +cmdline_hist      -dnd               -footer            -langmap           -mouseshape        -mzscheme          -python3           -startuptime       +termresponse      +virtualedit       -xpm
-balloon_eval      -cmdline_info      -ebcdic            +fork()            -libcall           -mouse_dec         -netbeans_intg     -quickfix          -statusline        -textobjects       +visual            -xsmp
-balloon_eval_term +comments          -emacs_tags        -gettext           -linebreak         -mouse_gpm         +num64             -reltime           -sun_workshop      -textprop          +visualextra       -xterm_clipboard
-browse            -conceal           -eval              -hangul_input      -lispindent        -mouse_jsbterm     -packages          -rightleft         -syntax            -timers            +vreplace          -xterm_save
+builtin_terms     -cryptv            +ex_extra          +iconv             +listcmds          -mouse_netterm     -path_extra        -ruby              +tag_binary        +title             +wildignore
-byte_offset       -cscope            -extra_search      +insert_expand     +localmap          +mouse_sgr         -perl              +scrollbind        -tag_old_static    -toolbar           -wildmenu
-channel           +cursorbind        -farsi             -ipv6              -lua               -mouse_sysmouse    -persistent_undo   -signs             -tag_any_white     +user_commands     +windows
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -Wdate-time -g -O2 -ffile-prefix-map=/build/vim-PRQ88X/vim-8.2.3995=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -DTIN
Y_VIMRC -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux -lacl -lattr
```

The result is:

```
> > >
```

> Duplicate of #16017

I confirm that `>` is in `comments`.

```
comments=s1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:
```

Thanks both of you for your support.
