### ISSUE TITLE
Off-screen cursor

### ISSUE THREAD

**Issue by dimascyriaco** [neovim/neovim#14081] opened 2021-03-08 16:45 UTC
I'm aware of [this](https://github.com/neovim/neovim/issues/279) old issue on the theme, but with the new LSP and the `vim.lsp.buf.document_highlight` function, it would be very useful to keep the cursor position on scroll, so we can keep the correct word highlighted.

**Comment by teto** [comment] 2021-03-08 17:07
that would be cool indeed. we just need someone to do it :) closing as duplicate of https://github.com/neovim/neovim/issues/989

**Closed by teto** 2021-03-08 17:07 UTC
Labels: enhancement
