### ISSUE TITLE
cmdheight, when set to 0, resets to 1 when command line window opens

### ISSUE THREAD

**Issue by sassanh** [neovim/neovim#20054] opened 2022-09-02 10:16 UTC
### Neovim version (nvim -v)

v0.8.0-dev-2457-gc0050b71e

### Vim (not Nvim) behaves the same?

NA (vim doesn't support cmdheight=0)

### Operating system/version

macOS 13.0 beta

### Terminal name/version

iTerm2 3.4.16

### $TERM environment variable

xterm-256color

### Installation

brew install neovim --HEAD

### How to reproduce the issue

nvim --clean
:set cmdheight=0
q:

### Expected behavior

cmdheight to stay 0

### Actual behavior

cmdheight becomes 1

I can work around this by setting an auto command for `autocmd CmdwinEnter * set cmdheight=0`, but then it will cause an unpleasant blink.

**Comment by Shougo** [comment] 2022-09-02 11:32
Reproduced.  But it is difficult to fix.

`q:` means enter command line and move to the command line window.
It is just syntax sugar and the command line is needed for the feature.

**Comment by Shougo** [comment] 2022-09-02 11:34
If you really need the feature:

```vim
autocmd CmdWinEnter * set cmdheight=0
```

It works for me and it is better than change the source code.

**Comment by sassanh** [comment] 2022-09-02 11:49
> I can work around this by setting an auto command for `autocmd CmdwinEnter * set cmdheight=0`, but then it will cause an unpleasant blink.

Thanks for the quick response @Shougo . As I mentioned in my original post I'm aware of the `CmdwinEnter` solution, but unfortunately it causes a blink.
If fixing it in the codebase is hard, we can postpone it for far future. I think we probably need an option to avoid setting cmdheight to 1 even when user opens command line (not command line window). I have a feeling these things should be addressed with tui client using `ext_cmdline` so that I can custom render the command line (hide it altogether when command line window is open).

**Comment by Shougo** [comment] 2022-09-02 12:00
I think cmdline UI should be implemented by `ext_cmdline`.
current solution is very adhoc.

**Comment by Shougo** [comment] 2022-09-02 12:02
Related: https://github.com/neovim/neovim/pull/16396

**Comment by Shougo** [comment] 2022-09-14 01:39
Please test https://github.com/neovim/neovim/pull/20188.

**Comment by zeertzjq** [comment] 2022-09-16 08:19
Fixed by #20188

**Closed by zeertzjq** 2022-09-16 08:19 UTC
Labels: bug, ui
