### ISSUE TITLE
t_xx: Broken hide/show cursor (t_vi / t_ve)

### ISSUE THREAD

**Issue by amerlyq** [neovim/neovim#3688] opened 2015-11-17 12:29 UTC
Inablility to set `t_vi` and `t_ve` to anything beside empty string results in next issue:

```
https://github.com/haya14busa/incsearch.vim/issues/79
```

It's fatal for plugins with real-time search/substitution preview.

**Comment by blankname** [comment] 2016-09-09 01:14
Does anyone have the time and knowledge to describe how one should go about fixing this?

**Comment by justinmk** [comment] 2016-09-09 18:01
> It's fatal for plugins with real-time search/substitution preview.

Wouldn't that mean those plugins don't work in gvim? Over.vim works fine in Nvim. 

Also try https://github.com/neovim/neovim/pull/5226

**Comment by amerlyq** [comment] 2016-09-09 21:12
Suggested pull-request is complete alternative to `over.vim` and not the solution to current problem, which also involves other plugins. `Over.vim` works itself, of course. But that double-cursor effect keeps being strongly irritating anyway. So this functionality is still required to hide the original cursor in different pseudo-prompts.

**Comment by justinmk** [comment] 2016-09-10 08:53
@amerlyq does the cursor hiding work in gvim?

**Comment by amerlyq** [comment] 2016-09-12 12:27
@justinmk yes, cursor hiding works both in gvim and vim.

**Comment by rainerborene** [comment] 2016-10-01 17:29
@justinmk would be possible to support those options via unibilium?

**Comment by justinmk** [comment] 2016-10-01 20:11
@rainerborene The `t_*` options in Vim are a Vim convenience to avoid the need to configure one's terminfo; I wouldn't guess that unibilium needs any modification to restore that functionality. 

Translation of `t_xx` in Vim works like this, following `option.c:do_set()`:

1. `find_key_option()` maps a `t_xx` option name to a Vim-internal magic keycode
2. `TERMCAP2KEY('x', 'x')` returns a magic number from the `xx` part of `t_xx`
3. magic number is mapped to a Vim-internal "key name" by `KEY2TERMCAP0`, `KEY2TERMCAP1`
    - see [this gist](https://gist.github.com/justinmk/6fbf991a7f7312487110d11ade1d50e0) for a sample of these first 3 steps
4. `find_termcode()` maps the key name to a termcode 
5. `show_one_termcode()` fiddles around and finally prints (msg_outtrans(code)) the bytes to TTY

`find_termcode()` does the real work, that is, a lookup into Vim's `termcodes` table (which is initialized from the current terminfo by `term.c`). We don't need Vim's `termcodes` table since we should be able to get that information from unibilium. 

Restoring this functionality as described above is probably 20-30 lines of code. A working PR with good test coverage would be accepted. 

But I would discourage starting new work to restore `t_xx`. Instead let's support these `t_xx` behaviors as API calls. For example instead of `t_vi` and `t_ve` (cursor visibility) and `t_AB`/`t_AF` (bg/fg colors), we _already_ have UI events that perform these things; we could provide a way to broadcast UI requests.

---

Side note: using `infocmp -L|grep cursor` one can see the `cursor_invisible` and `cursor_normal` termcodes, and `printf "\e<termcode>"` works as expected (outside of `nvim`). However `system('printf... > /dev/pts/9'))` from within `nvim` doesn't work. (It works for  https://github.com/neovim/neovim/issues/4867#issuecomment-250911566 but I wonder if that is because nvim

**Comment by yevhen-m** [comment] 2017-02-22 11:46
Guys, I know you are busy, but I think lots of neovim users are waiting for this issue to be fixed )).

**Comment by justinmk** [comment] 2017-02-22 14:08
@yevhen-m can you try https://github.com/neovim/neovim/pull/6044 ? Should be able to set `'guicursor'` in a VimLeave autocmd:

    au VimLeave * set guicursor=...

If that doesn't work we may just need to adjust the order of the VimLeave command.

**Comment by yevhen-m** [comment] 2017-02-22 14:43
Thanks, @justinmk, I've tried to install this revision, but "double-cursor" is still there (easymotion for instance), and I get segmentation fault errors when I use it.
I used these instructions to install:
```
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
```
Maybe I just did something wrong, so I ask other participants of this thread to try this PR.

**Comment by justinmk** [comment] 2017-02-22 15:18
"doublecursor" is not going to be solved unless easymotion uses the 'guicursor' feature to temporarily hide the cursor. We aren't going to restore the `t_XX` options.

@yevhen-m segfaults are always bugs, can you mention what you did to cause the segfault?

**Comment by yevhen-m** [comment] 2017-02-22 18:09
1. I checkout out PR #6044 revision
2. built and installed neovim
3. started nevim with easymotion plugin installed
4. tried to jump to a match

```
" Easymotion settings {{{
nmap s <Plug>(easymotion-s2)
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1
let g:EasyMotion_verbose = 0
" }}}
```

**Comment by frangio** [comment] 2017-02-22 19:02
I'm getting a segfault too, when I try to start incsearch.

In `tui_cursor_style_set` at [`src/nvim/tui/tui.c:471`](https://github.com/teto/neovim/blob/5fc57a0523b20fc7602ba614491c0591f36435d4/src/nvim/tui/tui.c#L471).
```
char *mode_name = args.items[i].key.data;
```

**Comment by teto** [comment] 2017-02-22 23:56
Thanks for testing it, I will try to fix it asap.

**Comment by teto** [comment] 2017-02-25 12:23
I updated the PR with initial cursor color support (requires termguicolors, should work with VTE & xterm). The bug should still be there though since I haven't touched these parts. Yet I couldn't reproduce the crashes, @yevhen-m & @frangio could you post backtrackes or minimal ways to reproduce those please ?

**Comment by yevhen-m** [comment] 2017-02-25 12:34
@teto https://github.com/neovim/neovim/issues/3688#issuecomment-281752354

> requires termguicolors
Does this mean that your fix does not work without this option set?
Personally I can't set this options, cause it breaks other plugins I use.

**Comment by teto** [comment] 2017-02-25 12:43
termguicolors is just required to be able to change the cursor color so you should be able to reproduce the crash without it.

**Comment by teto** [comment] 2017-02-25 14:05
I managed to crash it so let me do another pass :)

**Comment by teto** [comment] 2017-02-28 21:47
Should be fixed, you can try again.

**Comment by frangio** [comment] 2017-03-01 15:14
I can confirm it no longer segfaults.

**Comment by yevhen-m** [comment] 2017-03-02 17:38
So what should be done to make this fix land in easymotion, incsearch and other great plugins? Should their maintainers be notified about it?

**Comment by frangio** [comment] 2017-03-14 05:15
Yeah this will require plugin authors to add code using the `guicursor` feature.

@justinmk Is there any way we can write some kind of plugin-level adapter to make that easier?

**Comment by frangio** [comment] 2017-03-14 05:26
Actually, incsearch.vim already seems to have [the necessary code](https://github.com/haya14busa/incsearch.vim/blob/161c5b66542e767962ca5f6998a22e984f8d8a60/autoload/vital/_incsearch/Over/Commandline/Base.vim#L328), but it's not working.

**Comment by yevhen-m** [comment] 2017-03-15 21:45
@frangio great, so all are waiting till this feature lands in neovim.

**Comment by Alok** [comment] 2017-04-03 17:35
Does #6423 fix this?

**Comment by frangio** [comment] 2017-04-03 18:04
No, setting the cursor highlight group (which would enable to hide it) hasn't been implemented yet. There is some discussion going on in #6428.

**Comment by Shougo** [comment] 2017-04-04 01:21
> No, setting the cursor highlight group (which would enable to hide it) hasn't been implemented yet. There is some discussion going on in #6428.

Yes, I also need the cursor hide feature for denite.nvim.

**Comment by justinmk** [comment] 2017-04-04 02:10
> No, setting the cursor highlight group (which would enable to hide it) hasn't been implemented yet. ... #6428.

Cursor color _can_ be set by setting 'guicursor' (assuming your terminal supports cursor color changes) and specifying in the value of 'guicursor' some higlight group(s). The issue mentioned in #6428 is specifically about changing the highlight group(s) _after_ setting 'guicursor'.

**Comment by Shougo** [comment] 2017-04-04 02:18
> Cursor color can be set by specifying higlight group(s) in :set guicursor=... (assuming your terminal supports cursor color changes). 

My terminal (st) does not support the feature...

**Comment by justinmk** [comment] 2018-06-24 23:43
Nvim 0.3.0 `chansend()` can be used to send raw bytes to the terminal:

    :call chansend(v:stderr, {string or array})

Revisiting https://github.com/neovim/neovim/issues/3688#issuecomment-250934766 , `infocmp -L|grep cursor` on my machine gives `cursor_invisible=\E[?25l`. So I can do this to hide the cursor:

    call timer_start(1000, {-> chansend(v:stderr, "\<esc>[?25l") })

(any user-input will cause Nvim to show the cursor again.)

This doesn't help plugins since they don't really know what termcodes to send. 

So to close this issue we really need 'guicursor' to support showing/hiding the cursor.

**Comment by teto** [comment] 2018-06-25 08:05
My idea was to first make highlight notifications available so that it makes guicursor changes easier to test (i.e., right now if you change the cursor highlight, the cursor color for example won't be updated). Hence https://github.com/neovim/neovim/pull/8006 but bfredl is doing some more exhaustive work in this area so it might be best to wait for highlight notifications to land.

**Comment by bfredl** [comment] 2018-06-25 11:14
There is also the option to just add the cterm and rgb bgcolor fields to the mode_info_set dict, maaybe it could be considered ugly that the client in the future then can access the same info also a more indirect (but more general) way, but if someone wants to fix this right now, I'm not the one to argue against a little practicality.

**Comment by chemzqm** [comment] 2019-07-04 08:45
Any progress on this? `chansend` can be used for hide cursor, but can be easily broken on user input.

**Comment by amiralies** [comment] 2019-10-05 11:04
This is really annoying, my use case is coc.nvim lists, would be awesome if someone work on this?

**Comment by teto** [comment] 2019-10-05 11:18
If no one fixes it by then, I plan to work on it in December (no free time before that :'( ).

**Comment by teto** [comment] 2020-01-14 22:08
this is now possible on master by adjusting the Cursor highlight blend parameter. See `:help tui-cursor-shape `

**Comment by justinmk** [comment] 2020-01-15 08:10
## Resolution/Summary

Nvim 0.5 has `:help highlight-blend` (requires 'termguicolors' to be set), which allows setting the blend level of a highlight. One can combine that capability with 'guicursor' to hide the cursor, because `blend=100` means "invisible".

Example:

```
set termguicolors
hi Cursor blend=100
set guicursor+=a:Cursor/lCursor
```

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._

**Closed** 2020-03-02 13:45 UTC
Labels: +plan, api, gui, tui
