### ISSUE TITLE
Bad indented closing brace when filetype=python

### ISSUE THREAD

**Issue by giuscri** [neovim/neovim#8111] opened 2018-03-07 15:58 UTC
- `nvim --version`:
```
NVIM v0.2.3-788-g1d5eec2c6
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/g/hack/neovim/build/config -I/home/g/hack/neovim/src -I/home/g/hack/neovim/.deps/usr/include -I/usr/include -I/home/g/hack/neovim/build/src/nvim/auto -I/home/g/hack/neovim/build/include
Compiled by g@x220

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- Vim (version: `8.0`) behaves differently? yes, like the expected behaviour.
- Operating system/version: Arch Linux x86/64
- Terminal name/version: `GNOME Terminal 3.26.2 Using VTE version 0.50.3 +GNUTLS`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`
Enter insert mode, press tab then `{}`, put cursor inside braces, insert newline.

### Actual behaviour
```
    {
            }
~                                                                                                                                                                                                 
~                                                                                                                                                                                                 
~                                                                                                                                                                                                 
~                                                                                                                                                                                                 
```
### Expected behaviour
```
    {
}
~                                                                                                                                                                                                 
~                                                                                                                                                                                                 
~                                                                                                                                                                                                 
~                                                                                                                                                                                                 
```

**Comment by jamessan** [comment] 2018-03-07 16:20
Testing with `nvim -u NORC foo.py` and `vim --clean foo.py`, I see the "actual" behavior in both. This is using 8.0.1453 and nvim 0.2.2.

You don't mention the specific version of Vim that you're using, but I don't see any differences in the Python runtime files between 8.0.1453 and current master.  The Python indent and syntax files haven't changed in a _long_ time, so I doubt the difference is related to that.

Also, according to the Python indent script, the "actual" behavior _is_ the expected behavior. https://github.com/neovim/neovim/blob/1d5eec2c626bd8125940c0425cc6f33213851781/runtime/indent/python.vim#L74-L100.

**Comment by giuscri** [comment] 2018-03-07 16:29
I did test vim with `-u NONE` or `-u NORC` option. With `--clean` I can't reproduce

**Comment by jamessan** [comment] 2018-03-07 16:31
With Vim, `-u NONE` and `-u NORC` don't enable filetype-specific indent scripts, but `--clean` does (because it loads `defaults.vim`).

With Neovim, `-u NORC` enables filetype-specific indent scripts because we consider that a better default.

The behavior is consistent when filetype-specific indent scripts are enabled, so I'm closing this.

**Closed by jamessan** 2018-03-07 16:31 UTC
