### ISSUE TITLE
Terminal content disappears when resizing windows

### ISSUE THREAD

**Issue by taraslis453** [neovim/neovim#17770] opened 2022-03-18 19:46 UTC
### Neovim version (nvim -v)

v0.7.0-dev+1277-g9e66d27d3

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

macOS 12.3

### Terminal name/version

Kitty

### $TERM environment variable

xterm-kitty

### Installation

homebrew -HEAD

### How to reproduce the issue

1. nvim
2. :terminal
3. Split vertical
4. :terminal
5. switch to left terminal end run command that write content to terminal
6. resize right window 

### Expected behavior

https://user-images.githubusercontent.com/48454662/159073088-7039450a-2efd-48de-a7e3-d9054c6bf46f.mov

### Actual behavior

https://user-images.githubusercontent.com/48454662/159073454-dcb9d16a-1e42-4e99-8fb4-f1404ac89d34.mov

**Comment by zeertzjq** [comment] 2022-03-18 21:24
Duplicate of #4997

**Closed by zeertzjq** 2022-03-18 21:24 UTC
Labels: bug, terminal

**Comment by tipa40** [comment] 2022-06-05 20:21
Hi! I still get this described issue in v0.8.0-dev+374. Text is not reflowed when resizing. Would be very glad to see it working.
