### ISSUE TITLE
Starting the terminal in insertion mode will cause the terminal to enter insertion mode

### ISSUE THREAD

**Issue by yyy33** [neovim/neovim#19664] opened 2022-08-06 17:30 UTC
### Neovim version (nvim -v)

NVIM v0.7.2 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Arch linux

### Terminal name/version

alacritty 0.10.1 ()

### $TERM environment variable

xterm-256color

### Installation

 system package manager

### How to reproduce the issue

1. run `nvim --clean` open nvim
2. add this map `lua vim.keymap.set({'', '!', 't'}, '<c-t>', [[<cmd>exe 'buffer!' '+terminal' nvim_create_buf(v:true, v:false)<cr>]])`
3. type `i` into insert mode
4. type `<c-t>`,At this point a terminal will be opened, but it will be in insert mode, not terminal mode

### Expected behavior

The new terminal opened should enter terminal mode

### Actual behavior

The open terminal goes into insert mode

**Comment by zeertzjq** [comment] 2022-08-06 21:43
Duplicate of #7164

**Closed by zeertzjq** 2022-08-06 21:43 UTC
Labels: bug
