### ISSUE TITLE
Segmentation Fault when closing buffer

### ISSUE THREAD

**Issue by francoisGuerret** [neovim/neovim#7776] opened 2017-12-28 17:22 UTC
- `nvim --version`: v0.2.1
- Vim (version: ) behaves differently? Non relevant
- Operating system/version: Fedora 17
- Terminal name/version: terminology 1.1.0
- `$TERM`: xterm

### Actual behaviour

1. open neovim
2. activate terminal mode (:terminal)
3. escape terminal mode and open a file in a new buffer (eg :vs hello.cpp)
4. close the opened buffer (:q)

Neovim crashes on a Segmentation Fault

### Expected behaviour

Just keep the terminal buffer open

**Comment by jamessan** [comment] 2017-12-28 19:01
0.2.2 was released a month and a half ago and contained various crash fixes.  If you can reproduce with that or current HEAD, please reopen.  This is likely a duplicate of #7538.

**Closed by jamessan** 2017-12-28 19:01 UTC
