### ISSUE TITLE
When $VIMRUNTIME is set, vim lua runtime gets messed up

### ISSUE THREAD

**Issue by wookayin** [neovim/neovim#22717] opened 2023-03-18 01:50 UTC
### Problem

When an environment variable `$VIMRUNTIME` is set, some errors would happen as the vim instance may not load runtimes and lua modules properly.

One should not have $VIMRUTNIME already set before running $VIM, but this can happen when one launches vim inside a terminal buffer.

### Steps to reproduce

1. Open a vimr or neovim with a different location/version (e.g. Vimr 0.8.2).
2. Launch a terminal (e.g. `:term` inside the vim)
3. Try launching neovim different location (e.g. `$ nvim` in a zsh/bash shell), where nvim is 0.9.0-nightly.

Or, one can simulate this by setting `$VIMRUTNIME` explicitly:

```
VIMRUNTIME=/Applications/VimR.app/Contents/Resources/NvimView_NvimView.bundle/Contents/Resources/runtime nvim --clean --headless -c 'echo $VIMRUNTIME' -c 'lua print(vim.version)' -c 'qa'
```

Error message:
```
/Applications/VimR.app/Contents/Resources/NvimView_NvimView.bundle/Contents/Resources/ru
Error detected while processing command line:                                           
E5108: Error executing lua vim/_init_packages.lua:0: module 'vim.version' not found:    
        no field package.preload['vim.version']                                         
        no file './vim/version.lua'                                                     
        no file '/opt/homebrew/share/luajit-2.1.0-beta3/vim/version.lua'                
        no file '/usr/local/share/lua/5.1/vim/version.lua'                              
        no file '/usr/local/share/lua/5.1/vim/version/init.lua'                         
...
        no file '/usr/local/lib/lua/5.1/loadall.so'         
stack traceback:                                            
        [C]: in function 'require'                          
        vim/_init_packages.lua: in function '__index'       
        [string ":lua"]:1: in main chunk%                   
```
This is probably the $VIMRUNTIME for another vim instance (e.g. VimR here) and the neovim running through terminal are not compatible and of different version.

Running with the same neovim itself (without vimr) where $VIMRUNTIME is compatible is fine, i.e., open a terminal inside vim, and launch neovim inside the shell:

```
❯❯❯ echo $VIMRUNTIME                     
/opt/homebrew/Cellar/neovim/HEAD-29a43ef/share/nvim/runtime

❯❯❯ nvim --clean --headless -c 'echo $VIMRUNTIME' -c 'lua print(vim.version)' -c 'qa'
/opt/homebrew/Cellar/neovim/HEAD-29a43ef/share/nvim/runtime
table: 0x01014d2130 
```

### Expected behavior

It should work without an error. `$VIMRUNTIME` should be overriden regardless of what was set externally.

This was working fine in some previous neovim version (at least 0.8.0 works fine), but started breaking since some version of 0.9-nightly.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-3857+g29a43ef8a-dirty

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

macOS 12

### Terminal name/version

iTerm2, Kitty, etc.

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment] 2023-03-18 01:58
Duplicate of #8696

**Closed by zeertzjq** 2023-03-18 01:58 UTC
Labels: bug

**Comment by wookayin** [comment] 2023-03-18 02:06
According to #8696 a workaround is to make sure both of `VIM` and `VIMRUNTIME` are not set, i.e.
```
VIM=''
VIMRUNTIME=''
```
on a terminal running inside (neo)vim.
