### ISSUE TITLE
`os.date` format returns incorrect string on Windows

### ISSUE THREAD

**Issue by doongjohn** [neovim/neovim#29952] opened 2024-08-02 07:31 UTC
### Problem

`os.date` format `%p`, `%a`, `%A`, `%X` returns incorrect string on Windows.

My Windows language is set to korean so it may be the issue with handling unicode.

### Steps to reproduce

nvim --clean
- Windows: `:=os.date("%p")`
  ![image](https://github.com/user-attachments/assets/ed3529e7-9074-4bae-9b5a-3ec82a3dfddf)
- Linux: `:=os.date("%p")`
  ![image](https://github.com/user-attachments/assets/c78ad895-bb71-4223-8a75-5b7b1501c70c)

### Expected behavior

Windows should print AM(오전) or PM(오후).

### Neovim version (nvim -v)

NVIM v0.10.1

### Vim (not Nvim) behaves the same?

vim does not have lua support

### Operating system/version

Windows 11

### Terminal name/version

wezterm, windows terminal

### $TERM environment variable

xterm-256color

### Installation

github release

**Comment by mike325** [comment] 2024-08-02 11:38
cannot reproduce with neither `0.10.1` nor `0.11-nightly` also on windows 11 with wezterm and powershell 5.1, all of the described format strings work for me

**Comment by doongjohn** [comment] 2024-08-02 18:33
I can confirm this is a language issue. It works properly if I change the Windows display language to English.

- English:
![Screenshot 2024-08-03 031002](https://github.com/user-attachments/assets/ff7f0068-47ee-4934-9ca2-a204d0f57cfe)
![Screenshot 2024-08-03 031103](https://github.com/user-attachments/assets/32df0653-17f8-4e64-ab70-e63ce8868b92)
- Korean:
![image](https://github.com/user-attachments/assets/3d00e5f6-3720-488e-8c93-964001702b94)
![image](https://github.com/user-attachments/assets/3e324964-769a-412d-a1ee-4bc315946ca3)

**Comment by clason** [comment] 2024-08-03 09:58
I believe this is a duplicate of #29963 (meaning the underlying issue is the same) so we don't need to track both.

**Closed by clason** 2024-08-03 09:58 UTC
Labels: bug, platform:windows, localization, unicode  💩
