### ISSUE TITLE
windwos use neovim  err

### ISSUE THREAD

**Issue by Hope2KZ** [neovim/neovim#22782] opened 2023-03-25 13:39 UTC
### Problem

Error executing Lua callback: C:\Program Files\Neovim\share\nvim\runtime/lua/man.lua:11: man.lua: "command timed out: man -w man"
stack traceback:
        [C]: in function 'error'
        C:\Program Files\Neovim\share\nvim\runtime/lua/man.lua:11: in function 'man_error'
        C:\Program Files\Neovim\share\nvim\runtime/lua/man.lua:61: in function 'man_system'
        C:\Program Files\Neovim\share\nvim\runtime/lua/man.lua:277: in function 'get_path'
        C:\Program Files\Neovim\share\nvim\runtime/lua/man.lua:745: in function 'init'
        C:\Program Files\Neovim\share\nvim\runtime/lua/man.lua:757: in main chunk
        [C]: in function 'require'
        C:\Program Files\Neovim\share\nvim\runtime\plugin\man.lua:7: in function <C:\Program Files\Neovim\share\nvim\runtime\plugin\man.lua:6>
Error executing Lua callback: C:\Program Files\Neovim\share\nvim\runtime\plugin\man.lua:7: loop or previous error loading module 'man'
stack traceback:
        [C]: in function 'require'
        C:\Program Files\Neovim\share\nvim\runtime\plugin\man.lua:7: in function <C:\Program Files\Neovim\share\nvim\runtime\plugin\man.lua:6>
Error executing Lua callback: C:\Program Files\Neovim\share\nvim\runtime\plugin\man.lua:7: loop or previous error loading module 'man'
stack traceback:
        [C]: in function 'require'
        C:\Program Files\Neovim\share\nvim\runtime\plugin\man.lua:7: in function <C:\Program Files\Neovim\share\nvim\runtime\plugin\man.lua:6>
Error executing Lua callback: C:\Program Files\Neovim\share\nvim\runtime\plugin\man.lua:7: loop or previous error loading module 'man'
stack traceback:
        [C]: in function 'require'
        C:\Program Files\Neovim\share\nvim\runtime\plugin\man.lua:7: in function <C:\Program Files\Neovim\share\nvim\runtime\plugin\man.lua:6>

### Steps to reproduce

null

### Expected behavior

看到的大哥帮忙看一下

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

dont know

### Operating system/version

windows10

### Terminal name/version

alacritty

### $TERM environment variable

none

### Installation

git clone

**Comment by zeertzjq** [comment] 2023-03-25 13:45
Duplicate of #21169

**Closed by zeertzjq** 2023-03-25 13:45 UTC
Labels: bug
