### ISSUE TITLE
`au FileType lua` is not executed during startup if there is `syntax on` before

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#31589] opened 2024-12-15 21:17 UTC
### Problem

`FileType lua` autocommand might not execute during startup with lua file as argument if prepended with `syntax on`. Other filetypes work.

### Steps to reproduce

1. Create the following 'init.nvim':
    ```vim
    syntax on
    autocmd FileType lua let g:hello=1
    ```
2. `nvim --clean -u init.vim -- test.lua`
3. `:echo g:hello` - shows `E121: Undefined variable: g:hello`

While `FileType vim` and `-- test.vim` result in `g:hello` defined and equal to 1. Also works if there is no `syntax on`.

This might be related to #7367, but the fact that it doesn't work *specifically* for `lua` pattern probably indicates some hard-coding issue.

### Expected behavior

`FileType` autocommand is executed during startup regardless of pattern it uses.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1354+g852b6a6bce

### Vim (not Nvim) behaves the same?

No, doesn't have this issue; works for any filetype pattern (9.1.866)

### Operating system/version

EndeavourOS Linux x86_64, 6.12.4-arch1-1

### Terminal name/version

Ghostty 0.1.0-main+3c637a27

### $TERM environment variable

xterm-ghostty

### Installation

appimage

**Comment by zeertzjq** [comment] 2024-12-15 23:12
Duplicate of #29265

**Closed by zeertzjq** 2024-12-15 23:12 UTC
Labels: bug

**Comment by echasnovski** [comment] 2024-12-16 06:58
> Duplicate of #29265

Hmm... Looks similar, but that has no info that this happens only for 'lua' pattern/filetype.
