### ISSUE TITLE
Latest development --HEAD does not install on Mojave 10.4.5

### ISSUE THREAD

**Issue by jorgeOmurillo** [neovim/neovim#10211] opened 2019-06-13 08:32 UTC
- `nvim --version`:
- Vim (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Expected behaviour

Brew logs says it's missing endian.h.
The latest 'command line tools' include the in /usr/include/machine/

**Comment by blueyed** [comment] 2019-06-13 10:48
Duplicate of https://github.com/neovim/neovim/issues/10181 ?

**Closed by blueyed** 2019-06-13 10:48 UTC
