### ISSUE TITLE
CheckHealth never ends.

### ISSUE THREAD

**Issue by yiliangt5** [neovim/neovim#5637] opened 2016-11-21 02:00 UTC
- `nvim --version`:
NVIM 0.1.6
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161120-41230-1j47k8i/neovim-0.1.6/build/config -I/tmp/neovim-20161120-41230-1j47k8i/neovim-0.1.6/src -I/tmp/neovim-20161120-41230-1j47k8i/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161120-41230-1j47k8i/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161120-41230-1j47k8i/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161120-41230-1j47k8i/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161120-41230-1j47k8i/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161120-41230-1j47k8i/neovim-0.1.6/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161120-41230-1j47k8i/neovim-0.1.6/build/src/nvim/auto -I/tmp/neovim-20161120-41230-1j47k8i/neovim-0.1.6/build/include
Compiled by my local machine

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.6/share/nvim"
- Vim (version: ) behaves differently?
ng
- Operating system/version:
macOS Sierra 10.12.1
- Terminal name/version:
iTerm2 Build 3.0.12
- `$TERM`:
xterm-256color

### Actual behaviour
healthcheck script stuck after displaying 
    ## terminfo
      - INFO: key_backspace terminfo entry: key_backspace=\177

"Running healthchecks... " displays in status bar and the health check never ends.

### Expected behaviour
health check ends normally.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:CheckHealth
```

**Comment by tweekmonster** [comment] 2016-11-21 04:17
If you're in China and have Ruby installed, the problem is fixed in #5565.  That only fixes it so it doesn't hang indefinitely, though.  You most likely will need to change your gem source, even with the fix.

**Comment by yiliangt5** [comment] 2016-11-21 06:12
@tweekmonster 
Thanks. Fixed by connecting VPN

**Closed** 2016-11-21 12:33 UTC
