### ISSUE TITLE
nvim unusable - panes are not redrawn

### ISSUE THREAD

**Issue by mseravalli** [neovim/neovim#16756] opened 2021-12-23 08:43 UTC
### Neovim version (nvim -v)

NVIM v0.5.1

### Vim (not Nvim) behaves the same?

no, vim 8.1.2269

### Operating system/version

macOS 12.0.1 -> ssh -> Debian 5.10.46

### Terminal name/version

terminal, iTerm, alacritty

### $TERM environment variable

xterm-256color

### Installation

system package manager

### How to reproduce the issue

The issue appears if I use different terminals, if I use tmux, if I use mosh. Basically all the time. In the video below I am using the simplest setup mac -> ssh-> debian.

```
nvim --clean
i
hello there
<Esc>
yy
200p
<C-w>v # vertical split
<C-w>v # vertical split
<C-d><C-d><C-d><C-d><C-d><C-d> # scroll down
<C-w>l # change pane
<C-d><C-d><C-d> # scroll down
<C-w>l
...
```

### Expected behavior

I can see the text in all the panes

### Actual behavior

Nvim in unusable: the text is not redrawn and the panes seem empty.
[alacritty_ssh_nvim.avi.zip](https://github.com/neovim/neovim/files/7767908/alacritty_ssh_nvim.avi.zip)

**Comment by zeertzjq** [comment] 2021-12-23 09:01
What's the ncurses version on your Debian server?

**Comment by mseravalli** [comment] 2021-12-23 09:03
```
$ dpkg -l '*ncurses*' | grep '^ii'
ii  libncurses-dev:amd64 6.3-1        amd64        developer's libraries for ncurses
ii  libncurses5:amd64    6.3-1        amd64        shared libraries for terminal handling (legacy version)
ii  libncurses6:amd64    6.3-1        amd64        shared libraries for terminal handling
ii  libncursesw6:amd64   6.3-1        amd64        shared libraries for terminal handling (wide character support)
ii  ncurses-base         6.3-1        all          basic terminal type definitions
ii  ncurses-bin          6.3-1        amd64        terminal-related programs and man pages
```

**Comment by zeertzjq** [comment] 2021-12-23 09:03
Duplicate of #16238

**Closed by zeertzjq** 2021-12-23 09:03 UTC
Labels: bug
