### ISSUE TITLE
environ() causes internal error : hash_add()

### ISSUE THREAD

**Issue by puremourning** [neovim/neovim#11881] opened 2020-02-16 19:30 UTC
- `nvim --version`: 

```
C:\Users\ben\vimfiles\bundle\vimspector-Clean>nvim --version
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

C:\Users\ben\vimfiles\bundle\vimspector-Clean>  
```

- `vim -u DEFAULTS` (version: 8.2.0259) behaves differently? Yes
- Operating system/version: Windows 10
- Terminal name/version: command prompt
- `$TERM`: unset

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:let x = environ()
```

### Actual behaviour

traceback: `E685: Internal Error: hash_add()`

### Expected behaviour

no traceback

## info

Using `<C-r>=string( environ() )` and ignoring the error, the following is printed:

```
{'': '', 'VIM': 'C:\Program Files\Neovim\share\nvim', 'HOMEPATH': '\Users\ben', 'LOGONSERVER': '\\DESKTOP-25J9QDQ', 'USERNAME': 'ben', 'ProgramW6432': 'C:\Program Files', 'CommonProgramW6432': 'C:\Program Files\Common Files', 'USERDOMAIN': 'DESKTOP-25J9QDQ', 'HOMEDRIVE': 'C:', 'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-25J9QDQ', 'LOCALAPPDATA': 'C:\Users\ben\AppData\Local', 'PROMPT': '$P$G', 'NUMBER_OF_PROCESSORS': '2', 'PROCESSOR_REVISION': '9e09', 'PROCESSOR_LEVEL': '6', 'ProgramFiles': 'C:\Program Files', 'Path': 'C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\Program Files (x86)\Parallels\Parallels Tools\Applications;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Vim\vim82;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Go\bin;C:\Program Files\dotnet\;C:\Users\ben\AppData\Local\Microsoft\WindowsApps;C:\Program Files\CMake\bin;C:\Users\ben\AppData\Roaming\npm;C:\Users\ben\go\bin;C:\Program Files\Neovim\bin;;C:\Program Files\Neovim\bin', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PUBLIC': 'C:\Users\Public', 'USERPROFILE': 'C:\Users\ben', 'NVIM_LISTEN_ADDRESS': '\\.\pipe\nvim-6336-0', 'APPDATA': 'C:\Users\ben\AppData\Roaming', 'TERM': 'vtpcon', 'SystemDrive': 'C:', 'PSModulePath': 'C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules', 'windir': 'C:\Windows', 'TEMP': 'C:\Users\ben\AppData\Local\Temp', 'ProgramData': 'C:\ProgramData', 'GOPATH': 'C:\Users\ben\go', 'ALLUSERSPROFILE': 'C:\ProgramData', 'OneDrive': 'C:\Users\ben\OneDrive', 'SESSIONNAME': 'Console', 'VIMRUNTIME': 'C:\Program Files\Neovim\share\nvim\runtime', 'MYVIMRC': 'C:\Users\ben\AppData\Local\nvim\init.vim', 'CommonProgramFiles(x86)': 'C:\Program Files (x86)\Common Files', 'COMPUTERNAME': 'DESKTOP-25J9QDQ', 'TMP': 'C:\Users\ben\AppData\Local\Temp', 'ComSpec': 'C:\Windows\system32\cmd.exe', 'SystemRoot': 'C:\Windows', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW', 'DriverData': 'C:\Windows\System32\Drivers\DriverData', 'CommonProgramFiles': 'C:\Program Files\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 158 Stepping 9, GenuineIntel', 'OS': 'Windows_NT', 'ProgramFiles(x86)': 'C:\Program Files (x86)', 'OneDriveConsumer': 'C:\Users\ben\OneDrive'}
```

Vim does not show this error.

**Comment by bfredl** [comment] 2020-02-16 19:33
`f_environ()` uses `tv_dict_add_str()` directly which doesn't handle duplicate keys. It would need to use the adequate method to check if the key already present and replace it then instead. (alternatively clean up the env on startup and remove duplicates, perhaps this is what vim is doing because the code looks like it could have the same issue).

**Comment by PurpleMyst** [comment] 2020-02-24 15:36
I'm interested in fixing this, however I'm unsure of what the correct behavior would be. Should the environment definitions that come later in order override the ones defined earlier? i.e. when adding an environment variable to the dict in `f_environ`, should I just remove any key that is already present?

**Comment by puremourning** [comment] 2020-02-24 18:56
The correct behaviour is what vim does

**Comment by PurpleMyst** [comment] 2020-02-24 19:13
And does vim do what I describe? As in, later definitions override previous ones?

**Comment by erw7** [comment] 2020-03-02 06:59
POSIX.1-2008 states that:

<blockquote>If more than one string in an environment of a process has the same name, the consequences are undefined.</blockquote>

Therefore, I think the program that passes environment blocks containing duplicate names when creating child processes should be modified.

**Comment by puremourning** [comment] 2020-03-02 08:04
Sure. If it were a POSIX OS. It was windows.

**Comment by erw7** [comment] 2020-03-02 09:45
Certainly, on Windows, I did not find a statement in the environment block that names must not be duplicated.

Ref. https://docs.microsoft.com/en-us/windows/win32/procthread/environment-variables
Ref. https://docs.microsoft.com/en-us/windows/win32/shell/user-environment-variables?redirectedfrom=MSDN
Ref. https://docs.microsoft.com/en-us/windows/win32/procthread/changing-environment-variables

However, I don't think it is allowed because `GetEnvironmentVariable` is not implemented to return multiple values. In the first place, I don't think there is a useful use case for passing environment variables with duplicate names.

**Comment by puremourning** [comment] 2020-03-02 10:13
I’m not sure what your getting at. Are you saying that neovim is correct to break in windows when this happens? This isn’t a theoretical case.. it actually happened on a users actual PC.

**Comment by erw7** [comment] 2020-03-02 10:55
The reason for this happening is that the `env` dict was passed to `jobstart` `{opts}`, and that dictionary contained an environment variable with a name that already exists in the environment block. Therefore, I say that instead of removing duplicates when calling `environ()`, we need to remove duplicates when merging `env` dict.

**Comment by puremourning** [comment] 2020-03-02 11:24
Eh? The repro above is nothing to do with jobstart? What am I missing?

**Comment by bfredl** [comment] 2020-03-02 11:37
@puremourning If you think "doing what vim does" is the correct choice, it would be useful if you would state what that behavior is. Is it using the last value, or the first one? (I tried to look in the code, but I couldn't see any difference from nvim w.r.t. this)

**Comment by erw7** [comment] 2020-03-02 11:58
> Eh? The repro above is nothing to do with jobstart? What am I missing?

I don't know any programs that pass environment variables with duplicate names other than `job_start()` or `jobstart()`. If there is a case where environment variables are duplicated when `nvim` is normally executed from `cmd.exe` etc., please show the procedure that can reproduce it.

As @bfredl said, the behavior of `vim` is not different from `neovim`. You can check that in the next step.

```
vim -u NORC -N
:let $A = "A"
:call term_start('cmd', {'env': {'A': 'B'}})
vim -u NORC -N
:let x = environ()
```

**Comment by bfredl** [comment] 2020-03-02 12:44
@erw7  No, I certainly _never_ said the behaivor is the same in vim as in neovim, I said the direct opposite. In @puremourning :s initial scenario there empirically IS a difference, and I asked him to state what the actual behavior of vim is (as it is quicker than me trying to recreate his scenario). 

You are introducing a completely _different_ scenario in your latest comment, one that I hadn't seen before, how can I ever had "said" anything about it? How does that prove that vim and neovim behaves the same in _every_ case? You have to defend your own claims you make yourself, and _never_ implicitly assume that I agree with something I haven't even seen before.

**Comment by PurpleMyst** [comment] 2020-03-02 15:19
As far as I can tell the bug, at least on my machine, happens even if you just type `:echo environ()`, no `jobstart()` involved. The bigger question in my opinion is where are these duplicates coming from?

**Comment by erw7** [comment] 2020-03-03 06:03
I was misunderstanding this problem. If you have an environment where you simply run `nvim -u NORC` and get an error with `:echo environ()`, you probably have a problem with the environment block returned by `GetEnvironmentStringW()`. To solve this problem, you need to look at the environment block returned by `GetEnvironmentStringsW()` in the environment where the problem occurs to determine which entry is causing the problem. If it contains an entry with a duplicate name, it is a problem in that environment and not a neovim bug.

Since the result of `environ()` contains `'': ''`, I think it may have some unexpected entries.

**Comment by erw7** [comment] 2020-03-03 06:14
@bfredl The difference between `vim` and `neovim` in this problem is probably due to the difference between `GetEnvironmentStringsW()` and `_wenviron` (In fact, the environment blocks returned by `GetEnvironmentStringsW()` include things that are not included in `_wenviron`, such as `=C:=C:\ Windows.`). Describing the correct behavior of vim does not help solve this problem.

**Comment by bfredl** [comment] 2020-03-03 07:17
>  include things that are not included in _wenviron, such as =C:=C:\ Windows). Describing the correct behavior of vim does not help solve this problem.

Knowing the behaviour of vim is definitely relevant when considering which solution to pick. If we at least know _some_ situations where vim is preferring the later value to the former (be it by code in vim itself or code in the kernel it uses) or vice versa, then this is better than just guessing and picking one at random (or giving up and do nothing).

**Comment by bfredl** [comment] 2020-03-03 07:21
> If it contains an entry with a duplicate name, it is a problem in that environment and not a neovim bug.

I strongly disagree with this. If the system interfaces of both win32 and POSIX allow duplicate entries (even if the semantics are unclear), then neovim __must__ be prepared to handle this situation. Throwing a weird internal error at an unsuspecting plugin just using `environ()` is not acceptable. If it is considered a problem, it should be shown to the user in a meaningful way (like `:checkhealth` ) not by randomly breaking plugins.

**Comment by puremourning** [comment] 2020-03-03 07:24
@bfredl you're completely correct IMO

I will try and repro and get the actual env CME.exe has. I thought I had included it in the OP but I only included the internal outputted dict.

**Comment by erw7** [comment] 2020-03-04 10:47
This issue has been fixed in the master with https://github.com/neovim/neovim/commit/39963c6a04afc417a821b2255a5caea4b7955d7d.

**Comment by bfredl** [comment] 2020-03-04 11:25
@puremourning Can you test with a master version to see if this is the case? (we have precompiled binaries like https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip )

**Comment by jcorbin** [comment] 2020-03-07 16:49
Fwiw, I too had this problem with v0.4.2, but the latest nightly ( v0.5.0-404-g49cd750d6  ) does not.

**Comment by teto** [comment] 2021-01-14 08:25
apparently it has been fixed so let's close and reopen if that reappears

**Closed by teto** 2021-01-14 08:25 UTC
Labels: 1.severity:blocker, bug
