### ISSUE TITLE
Neovim keeps running after I closed it in terminal

### ISSUE THREAD

**Issue by ranranking** [neovim/neovim#4242] opened 2016-02-12 00:24 UTC
After I hit :q in terminal neovim, even when I closed my terminal, in activity monitor, I can still see nvim is using 100% of my cpu. I am using iterm2. Mac 10.11. What is going on? 
<img width="313" alt="screen shot 2016-02-11 at 5 22 15 pm" src="https://cloud.githubusercontent.com/assets/7812475/12995398/3fc5b3e6-d0e4-11e5-847a-4830c4577c5a.png">

**Comment by justinmk** [comment] 2016-02-12 01:15
select nvim, click the gear icon, select "sample process". Then please paste the result here or in a gist.

**Comment by ranranking** [comment] 2016-02-12 03:21
I killed the process already. Let me try duplicate this situation again.

**Comment by justinnhli** [comment] 2016-02-22 01:58
I have run into this issue a couple times, and I think it tends to be after I've used the built-in terminal. Here's the output from sampling the process:

```stdout
Sampling process 1861 for 3 seconds with 1 millisecond of run time between samples
Sampling completed, processing symbols...
Analysis of sampling nvim (pid 1861) every 1 millisecond
Process:         nvim [1861]
Path:            /usr/local/Cellar/neovim/HEAD/bin/nvim
Load Address:    0x10a5ac000
Identifier:      nvim
Version:         0
Code Type:       X86-64
Parent Process:  bash [1758]

Date/Time:       2016-02-21 17:54:40.076 -0800
OS Version:      Mac OS X 10.10.5 (14F1605)
Report Version:  7
Analysis Tool:   /usr/bin/sample
----

Call graph:
    2549 Thread_35732   DispatchQueue_1: com.apple.main-thread  (serial)
      2549 start  (in libdyld.dylib) + 1  [0x7fff902685c9]
        2549 main  (in nvim) + 8619  [0x10a6519d6]
          2549 normal_enter  (in nvim) + 176  [0x10a674d82]
            2549 state_enter  (in nvim) + 164  [0x10a6ff2de]
              2549 normal_execute  (in nvim) + 4149  [0x10a67a379]
                2549 nv_colon  (in nvim) + 170  [0x10a67be4c]
                  2549 do_cmdline  (in nvim) + 7495  [0x10a6090d0]
                    2549 ex_quit_all  (in nvim) + 173  [0x10a614eda]
                      2549 mch_exit  (in nvim) + 46  [0x10a697528]
                        2549 event_teardown  (in nvim) + 55  [0x10a64f6f9]
                          2549 process_teardown  (in nvim) + 127  [0x10a73338d]
                            2549 loop_poll_events  (in nvim) + 103  [0x10a732c56]
                              2546 uv_run  (in nvim) + 321  [0x10a738957]
                              + 2535 kevent  (in libsystem_kernel.dylib) + 10  [0x7fff9b8cb21a]
                              + 11 uv__io_poll  (in nvim) + 749,729  [0x10a745829,0x10a745815]
                              3 uv_run  (in nvim) + 580  [0x10a738a5a]
                                2 uv__run_timers  (in nvim) + 38  [0x10a74213a]
                                ! 2 children_kill_cb  (in nvim) + 197  [0x10a733780]
                                !   2 do_log  (in nvim) + 134  [0x10a64f356]
                                !     2 open_log_file  (in nvim) + 80  [0x10a64f44c]
                                !       1 expand_env_esc  (in nvim) + 106  [0x10a722c7a]
                                !       : 1 skipwhite  (in nvim) + 12  [0x10a5bf041]
                                !       1 expand_env_esc  (in nvim) + 927  [0x10a722faf]
                                !         1 strcpy  (in libsystem_c.dylib) + 84  [0x7fff92256f34]
                                !           1 _platform_memmove$VARIANT$Nehalem  (in libsystem_platform.dylib) + 0  [0x7fff96d6c340]
                                1 uv__run_timers  (in nvim) + 32  [0x10a742134]
                                  1 uv_timer_again  (in nvim) + 66  [0x10a7420bd]
                                    1 uv_timer_start  (in nvim) + 128  [0x10a741dcd]

Total number in stack (recursive counted multiple, when >=5):

Sort by top of stack, same collapsed (when >= 5):
        kevent  (in libsystem_kernel.dylib)        2535
        uv__io_poll  (in nvim)        11

Binary Images:
       0x10a5ac000 -        0x10a7b4fff +nvim (0) <4FEB274F-2897-3156-9A53-1D1EEC7D29CC> /usr/local/bin/nvim
       0x10a830000 -        0x10a839fff +libintl.8.dylib (0) <1E7AEBB3-C07B-32B4-897F-8E256D3E64F4> /usr/local/opt/gettext/lib/libintl.8.dylib
    0x7fff6c415000 -     0x7fff6c44b887  dyld (0.0 - ???) <D9967621-6378-381B-A47B-5085EE476B62> /usr/lib/dyld
    0x7fff8e168000 -     0x7fff8e168ff7  libkeymgr.dylib (28) <77845842-DE70-3CC5-BD01-C3D14227CED5> /usr/lib/system/libkeymgr.dylib
    0x7fff8e74c000 -     0x7fff8e752ff7  libsystem_networkextension.dylib (167.40.3) <BA58B30B-8377-3B0A-8AE3-4F84021D9D4E> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff8e753000 -     0x7fff8e94d46f  libobjc.A.dylib (647) <759E155D-BC42-3D4E-869B-6F57D477177C> /usr/lib/libobjc.A.dylib
    0x7fff8efb8000 -     0x7fff8efbfff7  libcompiler_rt.dylib (35) <BF8FC133-EE10-3DA6-9B90-92039E28678F> /usr/lib/system/libcompiler_rt.dylib
    0x7fff8efdd000 -     0x7fff8f031fff  libc++.1.dylib (120) <1B9530FD-989B-3174-BB1C-BDC159501710> /usr/lib/libc++.1.dylib
    0x7fff8f087000 -     0x7fff8f088fff  libsystem_secinit.dylib (18) <581DAD0F-6B63-3A48-B63B-917AF799ABAA> /usr/lib/system/libsystem_secinit.dylib
    0x7fff8f87e000 -     0x7fff8f8c4ff7  libauto.dylib (186) <A260789B-D4D8-316A-9490-254767B8A5F1> /usr/lib/libauto.dylib
    0x7fff8f9e8000 -     0x7fff8f9eaff7  libsystem_coreservices.dylib (9) <41B7C578-5A53-31C8-A96F-C73E030B0938> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff8f9f4000 -     0x7fff8f9f5ff7  libsystem_blocks.dylib (65) <9615D10A-FCA7-3BE4-AA1A-1B195DACE1A1> /usr/lib/system/libsystem_blocks.dylib
    0x7fff90265000 -     0x7fff90268ff7  libdyld.dylib (353.2.3) <CFBBE540-D503-3AFC-B5D6-644F1E69949B> /usr/lib/system/libdyld.dylib
    0x7fff90269000 -     0x7fff9026bfff  libquarantine.dylib (76.20.1) <7AF90041-2768-378A-925A-D83161863642> /usr/lib/system/libquarantine.dylib
    0x7fff9026c000 -     0x7fff9026dfff  libDiagnosticMessagesClient.dylib (100) <2EE8E436-5CDC-34C5-9959-5BA218D507FB> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff91dde000 -     0x7fff91df4ff7  libsystem_asl.dylib (267) <F153AC5B-0542-356E-88C8-20A62CA704E2> /usr/lib/system/libsystem_asl.dylib
    0x7fff921de000 -     0x7fff921e0fff  libsystem_sandbox.dylib (358.20.5) <3F5E973F-C702-31AC-97BC-05F5C195683C> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff92256000 -     0x7fff922e2fff  libsystem_c.dylib (1044.40.2) <69158EFA-8270-30A1-BA02-4F74A4498147> /usr/lib/system/libsystem_c.dylib
    0x7fff935df000 -     0x7fff935e0ffb  libremovefile.dylib (35) <3485B5F4-6CE8-3C62-8DFD-8736ED6E8531> /usr/lib/system/libremovefile.dylib
    0x7fff935e1000 -     0x7fff935e1ff7  libunc.dylib (29) <5676F7EA-C1DF-329F-B006-D2C3022B7D70> /usr/lib/system/libunc.dylib
    0x7fff94189000 -     0x7fff9418aff3  libSystem.B.dylib (1213) <1866C519-C5F3-3D09-8C17-A8F703664521> /usr/lib/libSystem.B.dylib
    0x7fff9420d000 -     0x7fff94216ff7  libsystem_notify.dylib (133.1.1) <61147800-F320-3DAA-850C-BADF33855F29> /usr/lib/system/libsystem_notify.dylib
    0x7fff94401000 -     0x7fff9441dff7  libsystem_malloc.dylib (53.30.1) <DDA8928B-CC0D-3255-BD8A-3FEA0982B890> /usr/lib/system/libsystem_malloc.dylib
    0x7fff94455000 -     0x7fff94466ff7  libz.1.dylib (55) <88C7C7DE-04B8-316F-8B74-ACD9F3DE1AA1> /usr/lib/libz.1.dylib
    0x7fff9459a000 -     0x7fff94932ff7  com.apple.CoreFoundation (6.9 - 1153.18) <5C0892B8-9691-341F-9279-CA3A74D59AA0> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff9516a000 -     0x7fff95170fff  libsystem_trace.dylib (72.20.1) <840F5301-B55A-3078-90B9-FEFFD6CD741A> /usr/lib/system/libsystem_trace.dylib
    0x7fff959b1000 -     0x7fff959b6ff7  libunwind.dylib (35.3) <BE7E51A0-B6EA-3A54-9CCA-9D88F683A6D6> /usr/lib/system/libunwind.dylib
    0x7fff9676e000 -     0x7fff96772fff  libcache.dylib (69) <45E9A2E7-99C4-36B2-BEE3-0C4E11614AD1> /usr/lib/system/libcache.dylib
    0x7fff96d6b000 -     0x7fff96d73fff  libsystem_platform.dylib (63) <64E34079-D712-3D66-9CE2-418624A5C040> /usr/lib/system/libsystem_platform.dylib
    0x7fff97231000 -     0x7fff9723afff  libsystem_pthread.dylib (105.40.1) <ACE90967-ECD0-3251-AEEB-461E3C6414F7> /usr/lib/system/libsystem_pthread.dylib
    0x7fff97329000 -     0x7fff97361fff  libsystem_network.dylib (412.20.3) <6105C134-6722-3C0A-A4CE-5E1261E2E1CC> /usr/lib/system/libsystem_network.dylib
    0x7fff97362000 -     0x7fff97392fff  libsystem_m.dylib (3086.1) <1E12AB45-6D96-36D0-A226-F24D9FB0D9D6> /usr/lib/system/libsystem_m.dylib
    0x7fff97393000 -     0x7fff973bbfff  libsystem_info.dylib (459.40.1) <2E16C4B3-A327-3957-9C41-143911979A1E> /usr/lib/system/libsystem_info.dylib
    0x7fff990f9000 -     0x7fff990fbfff  libsystem_configuration.dylib (699.40.2) <56F94DCE-DBDE-3615-8F07-DE6270D9F8BE> /usr/lib/system/libsystem_configuration.dylib
    0x7fff9922d000 -     0x7fff99238fff  libcommonCrypto.dylib (60061.30.1) <E789748D-F9A7-3CFF-B317-90DF348B1E95> /usr/lib/system/libcommonCrypto.dylib
    0x7fff99f14000 -     0x7fff99f1cffb  libcopyfile.dylib (118.1.2) <0C68D3A6-ACDD-3EF3-991A-CC82C32AB836> /usr/lib/system/libcopyfile.dylib
    0x7fff9a08b000 -     0x7fff9a090fff  libsystem_stats.dylib (163.30.2) <D0E96837-3CF6-323D-B711-6DF6F660E530> /usr/lib/system/libsystem_stats.dylib
    0x7fff9a25a000 -     0x7fff9a43fff7  libicucore.A.dylib (531.50) <CAA7ACE0-4012-3A13-864D-2B56B4B072FD> /usr/lib/libicucore.A.dylib
    0x7fff9a85f000 -     0x7fff9a951ff7  libiconv.2.dylib (42) <2A06D02F-8B76-3864-8D96-64EF5B40BC6C> /usr/lib/libiconv.2.dylib
    0x7fff9b09d000 -     0x7fff9b09fff7  libutil.dylib (38) <471AD65E-B86E-3C4A-8ABD-B8665A2BCE3F> /usr/lib/libutil.dylib
    0x7fff9b8b3000 -     0x7fff9b8b3ff7  liblaunch.dylib (559.40.1) <4F81CA3A-D2CE-3030-A89D-42F3DAD7BA8F> /usr/lib/system/liblaunch.dylib
    0x7fff9b8b4000 -     0x7fff9b8d1fff  libsystem_kernel.dylib (2782.50.1) <1EE815DA-FF1B-3A53-AE9B-C98BD8177A9D> /usr/lib/system/libsystem_kernel.dylib
    0x7fff9ba2a000 -     0x7fff9baa3fe7  libcorecrypto.dylib (233.30.1) <5779FFA0-4D9A-3AD4-B7F2-618227621DC8> /usr/lib/system/libcorecrypto.dylib
    0x7fff9bc9c000 -     0x7fff9bcc7fff  libc++abi.dylib (125) <88A22A0F-87C6-3002-BFBA-AC0F2808B8B9> /usr/lib/libc++abi.dylib
    0x7fff9bcc8000 -     0x7fff9bcf2ff7  libdispatch.dylib (442.50.1) <A61E703C-784A-3698-B513-75DD12AAD6DC> /usr/lib/system/libdispatch.dylib
    0x7fff9c16a000 -     0x7fff9c16fff7  libmacho.dylib (862) <126CA2ED-DE91-308F-8881-B9DAEC3C63B6> /usr/lib/system/libmacho.dylib
    0x7fff9c80f000 -     0x7fff9c817fff  libsystem_dnssd.dylib (576.50.2) <9EC5AF92-D0D2-3BDE-92B6-D3730D3865C8> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff9c8f9000 -     0x7fff9c90aff3  libsystem_coretls.dylib (35.40.1) <155DA0A9-2046-332E-BFA3-D7974A51F731> /usr/lib/system/libsystem_coretls.dylib
    0x7fff9d1e3000 -     0x7fff9d20bfff  libxpc.dylib (559.40.1) <5C829202-962E-3744-8B50-00D38CC88E84> /usr/lib/system/libxpc.dylib
Sample analysis of process 1861 written to file /dev/stdout
```

**Comment by justinmk** [comment] 2016-02-22 02:16
Interesting, it is stuck in `process_teardown()`. @justinnhli what is `:version` ?

**Comment by justinnhli** [comment] 2016-02-22 02:19
```
NVIM v0.1.0-53-g4cfda1f (compiled Nov 13 2015 10:32:48)
Commit: 4cfda1ff7d1aa75b67aed5566f39a390939da3f6
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra
-pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-pro
tector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_C
ONFIG_H -I/tmp/neovim20151113-23481-jgfuiy/build/config -I/tmp/neovim20151113-23
481-jgfuiy/src -I/tmp/neovim20151113-23481-jgfuiy/deps-build/usr/include -I/tmp/
neovim20151113-23481-jgfuiy/deps-build/usr/include -I/tmp/neovim20151113-23481-j
gfuiy/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20151113-23481-jgfuiy/deps-
build/usr/include -I/tmp/neovim20151113-23481-jgfuiy/deps-build/usr/include -I/t
mp/neovim20151113-23481-jgfuiy/deps-build/usr/include -I/tmp/neovim20151113-2348
1-jgfuiy/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include
-I/tmp/neovim20151113-23481-jgfuiy/build/src/nvim/auto -I/tmp/neovim20151113-234
81-jgfuiy/build/include
Compiled by justinnhli@surnia-mbp.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
Press ENTER or type command to continue
```

**Comment by justinnhli** [comment] 2016-02-22 02:21
To be clear, my issue may be slightly different from that of @ranranking. I don't think nvim takes up 100% CPU in this state, but it does continue running in iTerm until I Crtl+C.

**Comment by justinmk** [comment] 2016-02-22 02:38
@justinnhli Does it ever complete if you wait a long time without ctrl-c?

**Comment by justinnhli** [comment] 2016-02-22 02:40
I got the sample around the 10min mark. I'll keep it running the next time it happens and report back.

**Comment by justinmk** [comment] 2016-02-22 02:47
Oh, 10min is long enough, don't trouble yourself :)

**Comment by ranranking** [comment] 2016-03-03 00:04
I finally got the same issue today, and this is my sample process

**Comment by ranranking** [comment] 2016-03-03 00:05
[Sample of nvim.txt](https://github.com/neovim/neovim/files/155931/Sample.of.nvim.txt)

**Comment by ranranking** [comment] 2016-03-03 00:06
And it's using over 100% of my cpu again

**Comment by ranranking** [comment] 2016-03-03 05:42
Today, I got this several times. Mostly are related to :terminal and :so ~/.vimrc. Both of these two commands, especially the second one which source the vimrc file, can trigger this problem. At first, nvim would crash, I can not make any movements anymore, then I can only close my terminal and nvim keeps running, using up 100% of my cpu and more. here is another sample file:
[Sample of nvim 2.txt](https://github.com/neovim/neovim/files/156217/Sample.of.nvim.2.txt)

**Comment by justinmk** [comment] 2016-03-03 06:09
@ranranking If you can provide a minimal vimrc that reproduces the issue, that would be really helpful. Also, what `:version` ?

**Comment by ranranking** [comment] 2016-03-03 06:12
OK! I will try to make it! My version is 0.1.2, homebrew installed.

**Comment by ranranking** [comment] 2016-03-03 21:21
I finally figured out how to reproduce this problem. This is my vimrc file:
```vim
  set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim

  call dein#begin(expand('~/.vim/dein'))

  call dein#add('Shougo/dein.vim', {'rtp':''})
  
  call dein#add('AndrewRadev/switch.vim', {'on_map':['<c-s>']})
  call dein#add('tomtom/tcomment_vim', {'on_map': ['g','v']})
  call dein#end()

  map <S-J> 10gj
  map <S-K> 10gk

  nnoremap <Leader>rl :so ~/.vimrc<CR>
```
To reproduce it, you use neovim to open this .vimrc file, create a new line, save the file, use `:so ~/.vimrc` to reload the file, and then you have to delete one blank line, save it, and source the file again. Then, when you hit `S-J` or `S-K` you will find the program crashed. I could only kill it from outside. The two packaged are necessary, the map `<leader>rl` is also nessary. Whether other package manager can lead to the same problem I don't know. The `<S-J>` and `<S-K>` are used to trigger the problem. In fact, when there are more plugins and more vim settings, I could get this problem simply by making any modifications to the file, save it and reload it, the program will crash. I didn't have to save and reload twice by creating and deleting a line. But this is the minimal .vimrc I could have. Although I use a more complicated way to trigger the crash, I think these crashes may lead to the same problem.

**Comment by oni-link** [comment] 2016-08-06 09:38
> To be clear, my issue may be slightly different from that of @ranranking. I don't think nvim takes up 100% CPU in this state, but it does continue running in iTerm until I Crtl+C.

@justinnhli, do you still have this problem when using a newer version of nvim?

**Comment by oni-link** [comment] 2016-08-06 09:54
@ranranking, I cannot reproduce a crash with the script you have given. Can you still reproduce this problem with a newer version of nvim?

**Comment by justinnhli** [comment] 2016-08-06 11:19
@oni-link I *think* it's still happening but, like before, it's intermittent. For the purpose of this issue, feel free to close it; I'll open a new issue if I can reproduce it reliably.

**Closed** 2016-08-06 20:16 UTC
Labels: bug
