### ISSUE TITLE
Nvim executing random keystrokes on startup (iTerm2 only?)

### ISSUE THREAD

**Issue by kylepollina** [neovim/neovim#11952] opened 2020-02-26 19:23 UTC
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: macOS
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
Open nvim without a file or with any file

### Actual behaviour

When starting nvim, strange commands are entered as keystrokes, sometimes editing files but usually just showing up in the COMMAND window. Images:
![Screen Shot 2020-02-26 at 1 10 49 PM](https://user-images.githubusercontent.com/13981456/75379465-0ed16300-589b-11ea-9a60-9de96e3b1ba1.png)
![Screen Shot 2020-02-26 at 1 14 51 PM](https://user-images.githubusercontent.com/13981456/75379473-11cc5380-589b-11ea-85cb-ea20576a4abd.png)

Sometimes it will replace a character with the letter 'g' wherever the cursor is. Maybe it is running the keystroke 'rg'? This only happens with iTerm2, I haven't found this happening using the default mac terminal or with hyperterm.

This only happens with neovim, I have not found this to happen with vim or vi

### Expected behaviour
Not to do this

**Comment by kylepollina** [comment] 2020-03-03 14:32
Another screenshot of what happens sometimes:
![Screen Shot 2020-03-03 at 8 29 29 AM](https://user-images.githubusercontent.com/13981456/75785525-7ec36b80-5d29-11ea-8a8c-c0c67ad0f09f.png)

**Comment by kylepollina** [comment] 2020-03-03 14:33
I wanted to update and say that this is NOT due to a plugin. I've already tried using a blank init.vim file and no autoload and this issue still exists.

**Comment by justinmk** [comment] 2020-03-03 17:44
duplicate of https://github.com/neovim/neovim/issues/11393 . If it's happening with iTerm2 then it's definitely a timing issue, not a terminal capabilities issue.

**Closed by justinmk** 2020-03-03 17:44 UTC
Labels: bug
