### ISSUE TITLE
VimResume becomes useless with external TUI

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#22041] opened 2023-01-29 04:39 UTC
### Problem

`VimResume` has become useless with external TUI as it is now always triggered immediately after `VimSuspend`.

### Possible Solution

Wait some time (how long?) for all UI clients to detach (#22040). If all UI clients have detached, don't trigger `VimResume` until a UI client attaches, otherwise trigger `VimResume`. This makes behavior more backward-compatible, but less consistent as it depends on timing.

**Comment by bfredl** [comment] 2023-02-01 09:44
after #22040 , perhaps fire VimResume when the first (any) ui client re-attaches.

**Comment by zeertzjq** [comment] 2023-02-01 09:48
UI clients are allowed to ignore suspend event, so what should happen if there is no TUI client and all UI clients ignore it?

**Comment by tmillr** [comment] 2023-03-11 10:31
hmmm I was wondering why `VimResume` had stopped working properly in my terminal all of a sudden. I'm not doing anything crazy in my personal setup (I don't think anyway), just running nvim directly in my terminal and I happen to suspend and resume nvim often (because it feels easier and quicker than having to switch windows/tabs, enter terminal mode, do a shell command, then exit terminal mode with 2 different `CTRL-*` keystrokes, and finally switch back to the previous window/tab).

I have a plugin currently that relies on `VimResume`, and relies on it firing upon resume and not suspend (mainly just in order to run `:checktime` and trigger `'autoread'` upon resume/re-entry so that I don't have to worry about having/editing outdated buffers - after a git checkout for example). What is meant by `external TUI`? Will `VimResume` ever be fixed, or restored to its previous behavior? Thanks 👍

**Comment by justinmk** [comment] 2023-03-11 18:23
> Will `VimResume` ever be fixed, or restored to its previous behavior?

This issue tracks the intention to fix it. Else it would be closed.

**Comment by paulroseau** [comment] 2023-06-28 16:12
I experienced the same problem as @tmillr. I set / unset some tmux options upon resuming and suspending  Nvim, which no longer works. This was pretty confusing to debug, this issue should get a `:bug-regression` tag in my opinion.

For what it's worth, here is a simple test case to illustrate the behaviour (this is how I realized that `VimResume` was fired when `nvim` is suspended):
```
# Download and extract neovim
cd $(mktemp -d)
curl -LO https://github.com/neovim/neovim/releases/download/v0.9.0/nvim-linux64.tar.gz
tar -zxf nvim-linux64.tar.gz
cd nvim-linux64/bin

# Write example config file
cat >example.lua <<EOF
writeEventToLog = function (args)
  os.execute("echo '" .. args.event .. "' >> ./log")
end

vim.api.nvim_create_autocmd({'VimEnter'}, {
  callback = writeEventToLog,
})

vim.api.nvim_create_autocmd({'VimResume'}, {
  callback = writeEventToLog,
})

vim.api.nvim_create_autocmd({'VimSuspend'}, {
  callback = writeEventToLog,
})

vim.api.nvim_create_autocmd({'VimLeave'}, {
  callback = writeEventToLog,
})
EOF

if [ -f ./log ] ; then rm ./log ; fi
./nvim -u example.lua
```

At this point press `Ctrl-Z` and `cat ./log` you will see:
```
tmp.aG0SQweSos/nvim-linux64/bin
❯ ./nvim -u example.lua


zsh: suspended  ./nvim -u example.lua

tmp.aG0SQweSos/nvim-linux64/bin
✦ ❯ cat log
VimEnter
VimSuspend
VimResume
```

In `nvim-0.8.3` the content of `./log` is as expected:
```
VimEnter
VimSuspend
```

**Comment by tmillr** [comment] 2023-06-29 12:22
@paulroseau As a regular plugin author/user, it is certainly an unexpected regression, and the `needs:discussion` label is ironic since I've noticed that half the time relevant, helpful, or related discussion gets outright silenced/hidden in this repo by being marked "off-topic". It's strange. These issues are often prioritized in search engine results when folks are seeking help and serve as a central location for users to obtain further information or temporary workarounds.

I received 0 help on this issue after my comment left months ago, so I will offer you my own 2 cents based on my own trial and error, because it does not appear that this will be fixed anytime soon. You can try using a `UIEnter` autocmd in place of `VimResume` for the time being, since this does seem to fire on resume. Apparently the current implementation disconnects (detaches) from the default TUI on suspend and then reconnects on resume IIRC (or something along those lines)...although I am not sure if using `UIEnter` like this will be as dependable or will work as well as VimResume (used to), plus it might not work as expected if you have multiple UI's or are using a gui nvim, etc. There's also the function `nvim_list_uis()` which may be of use to you as well (maybe to check which UI's are attached while in the autocmd, if needed).

I've tried a couple of other things, like trying to setup a signal handler via autocmds or libuv, but had no success. So this appears to be the only simple/straightforward workaround AFAIK.

**Comment by justinmk** [comment] 2023-06-29 14:16
> and the `needs:discussion` label is ironic since I've noticed that half the time relevant, helpful, or related discussion gets outright silenced/hidden in this repo by being marked "off-topic". It's strange.

@tmillr Let me clear up the confusion: passive-aggressive dramatic comments get deleted. So please avoid it. We don't have to explain why, but I'll do so anyway: we need to keep the signal-to-noise ratio high in the issues tracker.

**Comment by zeertzjq** [comment] 2023-06-29 14:21
The discussion needed here is what the correct behavior should be, not why the current behavior is problematic.

**Comment by zeertzjq** [comment] 2023-06-29 14:23
Ok, maybe `needs:design` is a better label.

**Comment by zeertzjq** [comment] 2023-07-15 07:38
The places where `last_ui` is set in #23441 may be a good place to trigger `VimResume`.

**Closed** 2023-07-22 23:16 UTC
Labels: bug, gui, tui, ui-ext, events
