### ISSUE TITLE
Float background color doesn't match terminal with termguicolors, guibg=none, and winblend > 0

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#24584] opened 2023-08-07 00:59 UTC
### Problem

Floating window background color doesn't match terminal with `termguicolors`, `guibg=none`, and `winblend` > 0.

To see this, the terminal color has to be set to non-white if `background=light` or non-black if `background=dark`.

This issue is not present when using `notermguicolors`.

I noticed this when investigating an issue reported for a scrollbar plugin I wrote:
https://github.com/dstein64/nvim-scrollview/issues/112

### Steps to reproduce

First change your terminal color to non-white if `background=light` or non-black if `background=dark`.

`nvim --clean`

```vim
" Set termguicolors
:set termguicolors

" Create a new tab
:tabe

" Create a floating window
:let opts = {
      \   'relative': 'editor',
      \   'width': 30,
      \   'height': 20,
      \   'col': 5,
      \   'row': 5,
      \   'zindex': 100,
      \   'border': 'single'
      \ }
:let bufnr = nvim_create_buf(v:false, v:true)
:let win = nvim_open_win(bufnr, 0, opts)

" Remove Normal's guibg and ctermbg, intended to match terminal background
:highlight normal guibg=none ctermbg=none

" Set floating window highlight to Normal
:call nvim_win_set_option(win, 'winhighlight', 'Normal:Normal')

" Set positive value for winblend
:call nvim_win_set_option(win, 'winblend', 50)
```

### Expected behavior

(expected behavior was generated by changing `set termguicolors` to `set notermguicolors` in the steps above)

| Actual | Expected |
| :-----:|:-------: |
| ![actual](https://github.com/neovim/neovim/assets/541289/d00460af-3f36-4f89-86f0-43072cd61a1d) | ![expected](https://github.com/neovim/neovim/assets/541289/f4a4e5fc-1d7b-4274-9f39-d06b41417815) |

### Neovim version (nvim -v)

v0.9.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Kubuntu 23.04

### Terminal name/version

Konsole 22.12.3

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by zeertzjq** [comment] 2023-08-07 01:08
Duplicate of #18576

**Closed by zeertzjq** 2023-08-07 01:08 UTC
Labels: bug
