### ISSUE TITLE
notmuch doesn't work on neovim

### ISSUE THREAD

**Issue by ryzokuken** [neovim/neovim#12082] opened 2020-04-03 22:36 UTC
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)) behaves differently? Yes
- Operating system/version: Linux 5.5.13-arch2-1 x86_64 GNU/Linux
- Terminal name/version: alacritty 0.4.2
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:source /path/to/notmuch.vim
:NotMuch
```

### Actual behaviour

NotMuch opens up and renders, but doesn't work as expected. In search view, for example, `enter` moves cursor to the next line, doesn't open up message. Pressing `c` doesn't open compose view, it does what pressing `c` would do on a normal buffer.

### Expected behaviour

NotMuch work as expected, like it does on vim.

`notmuch.vim` for reference: https://paste.rs/DIg

**Comment by justinmk** [comment] 2020-04-04 13:42
notmuch.vim looks like it's using system(). See  https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes

duplicate of https://github.com/neovim/neovim/issues/1496

**Closed by justinmk** 2020-04-04 13:42 UTC
Labels: bug
