### ISSUE TITLE
:terminal truncated after resize

### ISSUE THREAD

**Issue by chriad** [neovim/neovim#5325] opened 2016-09-11 08:50 UTC
![output](https://cloud.githubusercontent.com/assets/4353001/18416199/5baa6662-780d-11e6-814d-76ec560b18b1.gif)

I use the nvimR-plugin (https://github.com/jalvesaq/Nvim-R) which initiates R in a neovim terminal. Then I use ctrlSF (https://github.com/dyng/ctrlsf.vim) to search some files. It comes with a preview window functionality that opens a file in a preview. After closing this preview, the terminal window is not restored to its initial size.
- `nvim --version`: NVIM v0.1.5-623-g4d4c925
- Vim (version: ) behaves differently?
- Operating system/version: 2.6.32-642.3.1.el6.x86_64 #1 SMP Sun Jun 26 18:16:44 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
- Terminal name/version: Gnome-terminal 3.6.2
- `$TERM`:
### Actual behaviour

Terminal window gets resized to width one after closing a preview window
### Expected behaviour

Terminal window should be restored to size before opening preview window
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by justinmk** [comment] 2016-09-11 13:10
See https://github.com/neovim/neovim/pull/4929#issuecomment-227501548.

There's no much we can do about this unless/until libvterm changes its scrollback handling. The problem you're seeing is that the "scrollback" is being truncated because the window was made smaller. Then it's not restored when the window is enlarged--there is no "secondary" scrollback buffer which preserves potentially-needed lines.

This bothers me as well.

**Comment by mallochine** [comment] 2017-06-05 22:05
There's a hack I wrote in vimscript to work around this scrollback issue.

In the terminal buffer, open a new buffer, say $HOME/tmp/vim_empty_file
Then after the terminal window is resized, quit the buffer. The original buffer is pristine.

**Comment by mallochine** [comment] 2017-06-05 22:51
Although I just now realize that this "works", but probably only "well" for me. Since my intention is to "paper over" the termianl buffer completely, instead of viewing it partially (say, half the size?).

**Comment by justinmk** [comment] 2017-10-17 20:06
duplicate of https://github.com/neovim/neovim/issues/4997

**Closed by justinmk** 2017-10-17 20:06 UTC
Labels: :term, bug
