### ISSUE TITLE
All windows share one status bar like tmux

### ISSUE THREAD

**Issue by fgheng** [neovim/neovim#12094] opened 2020-04-09 04:17 UTC
Now, neovim support one window with one status but not support all windows with only one status at the bottom, would you liket to add this feature?

**Comment by liuhaowen478** [comment] 2020-04-10 00:44
I'm definitely happy to see that coming.

**Comment by fgheng** [comment] 2020-04-10 02:52
That will save a lot of space and show more info about current window.

**Comment by glacambre** [comment] 2021-06-08 05:48
This issue is a duplicate of #9342, so I'll close it :)

**Closed by glacambre** 2021-06-08 05:48 UTC
Labels: enhancement
