### ISSUE TITLE
Text misaligned and only partially translated in initial window with LANG set

### ISSUE THREAD

**Issue by stevecheckoway** [neovim/neovim#9357] opened 2018-12-12 14:23 UTC
- `nvim --version`:

```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -pipe -Os -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_UNIBI_HAS_VAR_FROM -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/config -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/neovim-0.3.1/src -I/opt/local/include -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/src/nvim/auto -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/include
Compiled by macports@mojave.internal.macports.net

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/local/share/nvim"

Run :checkhealth for more info
```
- Vim (version: 8.1.280) behaves differently? Partially
- Operating system/version: macOS 10.14.1
- Terminal name/version: iTerm2 3.2.6
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
LANG=it_IT.UTF-8 nvim -u NORC
```

### Actual behavior
```
~                                 NVIM v0.3.1
~
~                 Nvim is open source and freely distributable
~                         https://neovim.io/community
~
~                type  :help nvim<Enter>       if you are new!
~                type  :checkhealth<Enter>     to optimize Nvim
~          batti :q<Invio>               per uscire
~                type  :help<Enter>            for help
~
~                      Diventa un utente Vim registrato!
~               batti :help register<Invio>   per informazioni
```
### Expected behavior
I expect `type` to be `batti`, `<Enter>` to be `<Invio>`, the other strings to be translated, and the columns to be aligned.

VIM's behavior is slightly better, but not great:
```
~                      VIM - Vi IMproved (VI Migliorato)
~
~                               versione 8.1.280
~                           di Bram Moolenaar et al.
~           Vim è 'open source' e può essere distribuito liberamente
~
~                     Aiuta i bambini poveri dell'Uganda!
~          batti :help iccf<Invio>       per informazioni
~
~          batti :q<Invio>               per uscire
~          batti :help<Invio>  o  <F1>   per aiuto online
~          batti :help version8<Invio>   per informazioni su versione
~
~                      Eseguo in modalità compatibile Vi
~           batti :set nocp<Invio>        per valori predefiniti Vim
~              batti :help cp-default<Enter> per info al riguardo
```

**Comment by justinmk** [comment] 2018-12-12 14:30
Duplicate of https://github.com/neovim/neovim/issues/6036

It requires updating the `.po` files, I think. Patch welcome.

**Closed by justinmk** 2018-12-12 14:30 UTC

**Comment by stevecheckoway** [comment] 2018-12-12 14:32
Ah, sorry for the noise. I didn't see #6036 and just ran across the issue while trying to reproduce another locale bug.
