### ISSUE TITLE
neovim macos nightly builds missing

### ISSUE THREAD

**Issue by prabirshrestha** [neovim/neovim#13146] opened 2020-10-24 02:44 UTC
nightly builds for macos doesn't seem to be getting uploaded so most of my plugins that also tests against neovim nightly is failing.

**Comment by erw7** [comment] 2020-10-24 05:01
Looking at the CI logs below, it should be uploading successfully, but there are no MacOS packages on the release page for the last few days. Please leave this open until someone solves this problem.

https://travis-ci.org/github/neovim/bot-ci/jobs/738316308

Related #13133.

**Comment by erw7** [comment] 2020-10-25 01:31
It seems to be fixed for now, so I'll close this one. However, the cause of the disease remains unknown, so it may recur.

**Comment by clason** [comment] 2020-10-27 10:45
Seems like the package is gone again today. Maybe keep open and pin it?

**Comment by erw7** [comment] 2020-10-27 11:44
I already know what caused it and how to fix it. I'm waiting for a review by someone who is familiar with bot-ci, so please be patient for now.

Ref neovim/bot-ci#152.

**Closed** 2020-10-30 10:37 UTC
Labels: bug, ci
