### ISSUE TITLE
Weird characters appears in the terminal!

### ISSUE THREAD

**Issue by Wei-Mao** [neovim/neovim#19028] opened 2022-06-20 01:59 UTC
### Neovim version (nvim -v)

0.7.0 stable

### Vim (not Nvim) behaves the same?

no   7.4.1689 

### Operating system/version

ubuntu 16.04

### Terminal name/version

GNOME Terminal 3.18.3

### $TERM environment variable

xterm-256color

### Installation

repo

### How to reproduce the issue

type nvim and then quit it.
Weird characters are printed out in the terminal.
![image](https://user-images.githubusercontent.com/51208983/174512243-ddb53e93-4c0f-40e7-88f6-a979a352cc6b.png)

### Expected behavior

No weird characters

### Actual behavior

weird characters as follows:
![image](https://user-images.githubusercontent.com/51208983/174512289-e6acf721-456b-4576-af8f-f9a60a293956.png)

**Comment by zeertzjq** [comment] 2022-06-20 02:24
Duplicate of #17985

**Closed by zeertzjq** 2022-06-20 02:24 UTC
Labels: bug
