### ISSUE TITLE
clipboard content is lost when nvim exits

### ISSUE THREAD

**Issue by oren** [neovim/neovim#3895] opened 2015-12-23 05:46 UTC
I have an issue with copy pasting: yanking something doesn't let me paste it if I close nvim and try to paste it into the same terminal where nvim was running. If I open a new terminal I can paste with no issues. This issue doesn't happen with vim. only with nvim. 

I only have a single line in my .vimrc
```
set clipboard=unnamed
```
any clues?

**Comment by geoffharcourt** [comment] 2015-12-24 13:48
Hi @oren, what platform are you using, what's your terminal application, and what is your current build of nvim? I was unable to reproduce your problem on using OS X with iTerm 2 both with and without tmux.

**Comment by oren** [comment] 2015-12-24 18:01
platform
```
cat /etc/lsb-release

DISTRIB_DESCRIPTION="Ubuntu 15.04"
```

terminal
```
echo $TERM

xterm-256color
```

nvim
```
nvim --version

NVIM 0.1.0-dev (compiled Nov 28 2015 03:09:16)
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-DirHM8/neovim-0.1.0ubuntu1+git201511272306+2019+15~ubuntu15.04.1/build/config -I/build/neovim-DirHM8/neovim-0.1.0ubuntu1+git201511272306+2019+15~ubuntu15.04.1/src -I/build/neovim-DirHM8/neovim-0.1.0ubuntu1+git201511272306+2019+15~ubuntu15.04.1/.deps/usr/include -I/build/neovim-DirHM8/neovim-0.1.0ubuntu1+git201511272306+2019+15~ubuntu15.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-DirHM8/neovim-0.1.0ubuntu1+git201511272306+2019+15~ubuntu15.04.1/.deps/usr/include -I/build/neovim-DirHM8/neovim-0.1.0ubuntu1+git201511272306+2019+15~ubuntu15.04.1/.deps/usr/include -I/build/neovim-DirHM8/neovim-0.1.0ubuntu1+git201511272306+2019+15~ubuntu15.04.1/.deps/usr/include -I/build/neovim-DirHM8/neovim-0.1.0ubuntu1+git201511272306+2019+15~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-DirHM8/neovim-0.1.0ubuntu1+git201511272306+2019+15~ubuntu15.04.1/build/src/nvim/auto -I/build/neovim-DirHM8/neovim-0.1.0ubuntu1+git201511272306+2019+15~ubuntu15.04.1/build/include
Compiled by buildd@lcy01-35

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by wsdjeg** [comment] 2016-01-03 00:25
same issue with vim,i think it is feature

**Comment by wsdjeg** [comment] 2016-01-03 00:27
for example i select something type,"+y,then closs nvim ,i can not past to anywhere,not only terminal

**Comment by justinmk** [comment] 2016-01-03 00:57
@oren Do you have `xsel` or `xcopy` or both? Just a wild guess, can you check (e.g. `ps -e | grep -E 'xsel|xcopy'`) if you one of them is perhaps hanging around briefly when you close `nvim`?

@wsdjeg Sounds like you don't have clipboard support in Vim (or nvim)?

**Comment by ZyX-I** [comment] 2016-01-03 00:59
@wsdjeg It is not a feature, it is a consequence of how X11 clipboard is implemented: you do not tell X server “put X into the clipboard”, you tell it “I own the clipboard now”. Application you paste to will then negotiate with application owning the clipboard to get clipboard contents (this is used to paste in the specific format: e.g. gtk can do automatic conversion of the images AFAIR). To fix you need to use clipboard manager which will listen to clipboard owner changes, get clipboard contents and own it itself.

Some useful link: https://www.jwz.org/doc/x-cut-and-paste.html (you can get more by searching `X11 clipboard` in Google).

**Comment by ZyX-I** [comment] 2016-01-03 01:01
@justinmk What is xcopy and why it may be used? I see provider using only pbcopy (Mac OS), xclip or xsel, in order.

**Comment by justinmk** [comment] 2016-01-03 01:05
xclip.

**Comment by wsdjeg** [comment] 2016-01-03 01:12
i have  install xclip,and i can use "y+ or "y*,but when vim or neovim is clossed,then can not past,maybe i miss some config,thank you for show me the link @zyx-i

**Comment by ZyX-I** [comment] 2016-01-03 01:39
@wsdjeg I see it is explicitly configured in Neovim provider: both xclip and xsel are executed in foreground which means that they are killed once Neovim is killed, which means that clipboard disappears. Due to the way provider is written you cannot possibly configure anything, only replace current provider implementation with your (e.g. by copying existing clipboard provider and modifying it).

**Comment by ZyX-I** [comment] 2016-01-03 01:47
Given that by default both xclip and xsel detach from their parent and are not affected by its death this behaviour is *intentional*. Maybe because this is how Vim works, maybe because this is how any X application is actually supposed to work. In any case this is not an issue. Change was made in d133502 (#2703).

**Comment by wsdjeg** [comment] 2016-01-03 01:50
ok,got it,I think this issue should be how to change ubuntu os default  clipboard provider  to xclip  or any thing start up with os not neovim

**Comment by ZyX-I** [comment] 2016-01-03 02:04
@wsdjeg You missed everything.

1. Current clipboard provider *does* use xclip. Or xsel, but they are not different in this context. (`xclip` has preference.)
2. Xclip does not start with OS (does not need to).
3. Xclip in the current provider was explicitly configured so that it dies with Neovim: `xclip` waits until somebody reclaims clipboard ownership, but it does so in background.
4. Without specific arguments supplied to xclip (in this case it is `-quiet`) `xclip` daemonizes itself and waits until somebody reclaims clipboard ownership.
5. There are clipboard managers (xclip is *not* the one) which may copy clipboard contents to their memory and when previous owner dies reclaim ownership and provide their own copy instead.

**Comment by wsdjeg** [comment] 2016-01-03 02:26
i find same thing happened not only in neovim ,yark something from other apps,such as firefox,the close firefox,also can not past,thanks for show me so many infos
@zyx-i

**Comment by oren** [comment] 2016-01-03 02:58
small update: from some reason nvim doesn't let me paste into any terminal. not just the terminal that was running nvim. vim on the other hand works great. i can paste to any terminal after copying text.
and just to be clear, when I say copy i mean a simple `yy`.
btw, i have xsel installed.

what's the bottom line? how do I make nvim behave as vim?

**Comment by wsdjeg** [comment] 2016-01-03 03:06
you should use "+yy or "*yy

**Comment by oren** [comment] 2016-01-03 03:12
interesting! "*yy works on vim but not in nvim. but yy is so much easy to type. why would i use "*yy ?

anyway, the issue is still the same. `yy` let me copy paste to the same terminal in vim but not in nvim.

**Comment by justinmk** [comment] 2016-01-03 03:14
> and just to be clear, when I say copy i mean a simple yy.

Still wondering what you mean by "paste", actually. CTRL-V, shift-insert, middle-click, CMD-V, p, or what?

**Comment by oren** [comment] 2016-01-03 03:16
sorry for not being clear. i am talking about middle click (which i think is the same as shift-insert).

**Comment by justinmk** [comment] 2016-01-03 03:20
D'oh. That's the one clipboard feature we don't support yet: https://github.com/neovim/neovim/pull/3708

**Comment by justinmk** [comment] 2016-01-03 03:23
If you use the secondary clipboard (shift-insert) it should paste just fine in other terminals. Or how ever your terminal is configured to do a "normal paste". Middle-click is a totally separate "clipboard" (the `@*` register in Vim, not yet supported in Neovim).

see `:help 'clipboard'` .

**Comment by justinmk** [comment] 2016-01-03 03:30
Oh, also try CTRL-SHIFT-V or CTRL-SHIFT-INSERT. See http://unix.stackexchange.com/a/11890/14626

**Comment by wsdjeg** [comment] 2016-01-03 08:52
strange things , after sletect words in neovim ,type `"+y`, close neovim,then I can not use `ctrl + v` in other apps, or can not use` ctrl + shilf + v ` in terminal, but i can use `ctrl + ;` open the clipboard of fcitx which contains all the thing i just have yarked in to + or *



> i find same thing happened not only in neovim ,yark something from other apps,such as firefox,the close firefox,also can not past,thanks for show me so many infos
> @zyx-i

it is my fault , yark from other apps works ok even if the apps has been closed.

**Comment by oren** [comment] 2016-01-04 01:14
@justinmk both middle click and shift+inserts behave the same: 
In vim I am able to paste into the same terminal that vim was open but not in nvim.
Just to make sure I understand correctly, is this a know issue? is there a ticket I can track to follow up on this? That's the only reason I still use vim and not nvim.

Thanks!

**Comment by justinmk** [comment] 2016-01-04 01:34
> both middle click and shift+inserts behave the same: 

https://github.com/neovim/neovim/issues/3895#issuecomment-168456330

>  is this a know issue? 

https://github.com/neovim/neovim/issues/3895#issuecomment-168455969

**Comment by oren** [comment] 2016-01-04 01:42
thanks!

**Comment by bfredl** [comment] 2016-01-04 11:37
I won't say the change is #2703 was _intentional_ to to lose the clipboard on exit, that was just a consequence of the way caching is implemented. If there was a `jobdetach()` function this could be called by the provider on `VimLeave` to keep the `xclip` helper alive after exit.

**Comment by ZyX-I** [comment] 2016-01-04 12:01
@bfredl I have missed the whole point of this caching. You never reuse the existing instances of xclip or xsel, so I am unable to see why this is called “caching” and how this is supposed to improve performance. So the only reason for this change left is intentionally losing clipboard on exit.

**Comment by wsdjeg** [comment] 2016-01-04 13:01
hi @ZyX-I sorry for tack up any time ,but I can not paste in to other programes,
here is my step:
## success
1. open a file with neovim 
2. select some works,type "+y
3. open other app, such firfox, type Ctrl v, i can paste the works i just yarked from neovim 

### failed
1. open a file with neovim 
2. select some works ,type "+y , **close neovim**
3. open other app, such firfox, type Ctrl v, i **can not** paste the works i just yarked from neovim

`xsel --version` outputs `xsel version 1.2.0 by Conrad Parker <conrad@vergenet.net>`

how should I config my pc, so that I can paste the works even if I hava closed neovim

**Comment by bfredl** [comment] 2016-01-04 13:14
@ZyX-I  Not sure if "caching" is the best word, but what's cached is the _contents_ of the clipboard whenever nvim owns the clipboard, and to determine ownership we need to track the lifetime of the `xsel` provider. This is needed to fully support `cb=unnamed` as we haven't implemented VIMENC clipboard format. For instance, Before #2703 blockmode was broken whenever  `cb=unnamed` . (sorry for bad description in the PR, this was discussed in many different issues at that time)

**Comment by ZyX-I** [comment] 2016-01-04 15:04
@bfredl I now see what exactly you was caching. I would though do it differently: yank as before, but remember the contents. If it did not change (checked upon pasting), assume that type and width of the register also did not change.

**Comment by ZyX-I** [comment] 2016-01-04 15:09
@bfredl This variant is simple, works with pbpaste as well (I see that this is *still* broken on Mac OS X as I do not see type and width of register saved anywhere on Mac).

**Comment by bfredl** [comment] 2016-01-04 15:15
True, but that doesn't help with performance (yes, there were many performance complaints about copy/pasting locally when `cb=unnamed` was set, for instance when pasting in a loop or certain plugins which do multiple clipboard accesses, I want to remember `YankRing` the worst offender with 13 */+ accesses on a single (unnamed) `p` )

**Comment by bfredl** [comment] 2016-01-04 15:56
It looks simple enough to fix X11 case with `UV_PROCESS_DETACHED`. (uv should still monitor the process, but it won't die on exit) Though for OS X @ZyX-I solution is the correct one (until someone implements the VIMENC-equivalent for OS X ), as OS X doesn't has the concept of clipboard ownership.

**Comment by justinmk** [comment] 2016-01-04 16:02
Should we re-open this? What's a 1-sentence description?

**Comment by bfredl** [comment] 2016-01-04 16:04
"clipboard content is lost when nvim exits" ?

**Comment by bfredl** [comment] 2016-01-04 16:25
Please try PR #3944 for the "after nvim exits" issue. But  what did autoselect do with this? Is big problem as well, but is _different_ problem.

**Comment by justinmk** [comment] 2016-01-04 16:50
> But what did autoselect do with this

I think that was my misunderstanding.

**Comment by ZyX-I** [comment] 2016-01-04 17:24
I would actually more like the solution which will throw away clipboard provider and write everything back in C. Given how many problems this infrastructure has already collected and how many people are willing to write their own clipboard providers it is not worth the hassle.

With the current providers it makes sense to use +python or +python3 and if that fails, fall back to current solution.

**Comment by justinmk** [comment] 2016-01-04 17:39
> throw away clipboard provider and write everything back 

@ZyX-I You mean link to Xorg?

> Given how many problems this infrastructure has already collected

- Most problems have been addressed. 
- We've made monotonically-improving progress. 

Existence of problems initially is not by itself a reason to discard an approach. We are working out the rough edges of a new extension capability...

> With the current providers it makes sense to use +python or +python3 and if that fails, fall back to current solution.

Sure, seems reasonable.

**Comment by bfredl** [comment] 2016-01-04 17:39
If we use python the question is what toolkit (gtk,qt or something like xpyb/xcffib if we're on that mood) do we use.

I actually thought of writing a binary clipboard X11 provider earlier today (and many times before. It would be quite feasible if 1) the binary interface was just _slightly_ better than _libcall_ 2) one could register an `fd` reader callback from vimL or binary plugin.

**Comment by bfredl** [comment] 2016-01-04 17:46
(Wait a minute, does `libcall` modules have access to `vim_` API? Then it is already much more powerful than I thought)

**Comment by ZyX-I** [comment] 2016-01-04 17:52
@justinmk 

1. Current solution is still slower then the original.
2. Blockwise selections still are not exported as blockwise. Fixing this requires patching xclip or xsel and making users use the patched version (which will take a long time *even* if patches are merged upstream due to package stabilization policies).
3. Exporting selection (clipboard=autoselect) is still WIP.
4. Exporting selection *cannot* be even nearly as fast as the original variant can be made because originally you only need to tell X that you have the clipboard, text will be deduced on request.


Compared to original solution this is 1 linked library exchanged for an external application, and immunity to X server restarts. To address the first problem there is dlopen. To address the second one may code reconnecting to X server.

**Comment by ZyX-I** [comment] 2016-01-04 17:54
By the way, do Mac and Windows *Vim* users receive blockwise selections yanked to system clipboard as blockwise?

**Comment by bfredl** [comment] 2016-01-04 17:56
The OS X case is implemented in https://github.com/vim/vim/blob/master/src/os_macosx.m

**Comment by bfredl** [comment] 2016-01-04 18:02
The way I thought of C implementation would be to have a `nvim_X11_clipboard.so` that would be dependent on Xlib.so but could be `dlopen`ed from nvim (either by `libcall`, luajit cffi, or dedicated binary interface for clipboard provider). But we could also have it builtin in nvim, but dlopen pointer indirection for every X11 call.
(For OS X no dlopen indirection should be needed as `NSPasteboard` is a _system_ library.)

**Comment by justinmk** [comment] 2016-01-04 18:08
> By the way, do Mac and Windows Vim users receive blockwise selections yanked to system clipboard as blockwise?

Seems to work with gvim + Windows 7.

> Compared to original solution this is 1 linked library exchanged for an external application, and immunity to X server restarts. To address the first problem there is dlopen. To address the second one may code reconnecting to X server.

Fair enough.

> The way I thought of C implementation would be to have a nvim_X11_clipboard.so that would be dependent on Xlib.so but could be dlopened from nvim

As long as there is a way to avoid users having to check "which version of nvim do I want" from their distro package manager, my major objection is addressed. 

> For OS X no dlopen indirection should be needed as NSPasteboard is a system library

Same for the win32 clipboard API. The provider exercise has been entirely for the unix world, to help drive the design of providers.

**Comment by ZyX-I** [comment] 2016-01-04 19:03
Providers work good for interpreter support. But clipboard support fails.

**Comment by ZyX-I** [comment] 2016-01-04 19:07
I am also not sure what is the policy in different distributions regarding nvim_X11_clipboard: specifically can e.g. debian maintainers accept package which does not depend on X11, but which has source package that depends. Can say that in Gentoo you for sure can have package with USE=X which will enabling building nvim_X11_clipboard, and unsetting this will disable clipboard support regardless of X server presence.

**Comment by bfredl** [comment] 2016-01-04 19:13
In any cause there won't be "multiple versions of nvim" Either (I'm thinking binary distributions here, source distributions like Gentoo are naturally more flexible) 1) `nvim_X11_clipboard` will be shipped with the main `nvim` package (giving it what some distributions call an _optional_ dependency of libX11.so) or 2) there will be an addon package that depends on both nvim and libX11. (Like some distributions handle nvim-python already).

**Comment by bfredl** [comment] 2016-01-04 19:19
And  the usecase of ad-hoc providers like the one that implemented tmux cut buffer integration could probably be served by clipboard autocommands.

**Comment by justinmk** [comment] 2016-01-04 19:36
> Providers work good for foreign languages support. But clipboard support fails.

Why do we need providers at all? Why can't we have a `FunctionCall` event and a `v:event` dict which contains data of the current event? (In the case of `FunctionCall` event, `v:event` would contain a child "args" dict `{ "event" : { "args": { ... } }, ...} `).

**Comment by bfredl** [comment] 2016-01-04 19:54
we had that design a while ago, and then we decided `autoload` was better. Basically, the autocmd solution was not simpler, and also the `autoload` sematics is better: either there is _zero_ or _one_ implementation (ok, there could be more than one, but only the last one in `&rtp` is used), and it is easy to determine which (for `has('python')` etc). @tarruda might remember more.

**Comment by justinmk** [comment] 2016-01-04 21:02
Good points. `autoload` (lazy-load) is definitely useful (I'm the one who suggested we use it instead of inventing a new mechanism ;). I guess I am trying to figure out if we can remove any concepts though.

**Comment by ZyX-I** [comment] 2016-01-04 22:53
@bfredl To be honest, unlike nvim_X11_clipboard which makes very little sense without neovim, nvim-python does not have to depend on Neovim because Neovim can be run on another machine.

Also in case of autoload only the *first* one in &runtimepath is used, not the *last*.

**Comment by bfredl** [comment] 2016-01-04 23:13
True, but some distributions include it still, like arch.

**Comment by bfredl** [comment] 2016-01-20 11:38
The actual issue should be fixed on master, reopen if not. I hope to look into C implementation (for X11 case) soon.

**Closed by bfredl** 2016-01-20 11:38 UTC
Labels: clipboard

**Comment by wsdjeg** [comment] 2016-01-20 12:17
@bfredl just waitting for this PR

**Comment by wsdjeg** [comment] 2016-01-22 10:56
@artur-shaik
hi I think this feature is a great improvement , so we can copy something, close neovim ,and the text will not missing,it works very well in ubuntu 14.04 + gnome-terminal 3.12.3

**Comment by justinmk** [comment] 2016-01-22 19:36
Nice work @bfredl
