### ISSUE TITLE
:norm runs single threaded

### ISSUE THREAD

**Issue by Marc-Bender** [neovim/neovim#12172] opened 2020-04-22 22:02 UTC
### Actual behaviour
:norm works fine and successfully but slow on large datasets (in my case 12k lines with a simple insert to the beginning of the line...
### Requested behaviour
:norm runs optionally on multiple threads.

###Background
I know that there are special tools for finding duplicate files but i decided to do it in nvim. I run :!$find . -type f
followed by :%norm Isha257sum 
in order to hash all my files and find the dupes. that means in my case adding a string to the beginning of 12k lines and it takes forever to do that (adding the string not the actual hashing). 
interrestingly running :%s/257/256/g 
to correct my typo runs very fast while it essentially runs on a just as big dataset (and basically i could propably just replace the start of a line with the start of the line followed by sha256sum to begin with but thats a different story)

**Comment by glacambre** [comment] 2020-04-23 06:00
I think this might actually be the same issue as https://github.com/neovim/neovim/issues/3508.

**Comment by justinmk** [comment] 2020-04-27 01:02
Duplicate of #3508

**Closed by justinmk** 2020-04-27 01:02 UTC
Labels: enhancement
