### ISSUE TITLE
nvim fails to load on arch linux

### ISSUE THREAD

**Issue by muralikodali** [neovim/neovim#16648] opened 2021-12-14 15:47 UTC
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 02 2021 19:44:33)

### Operating system/version

arch linux

### Terminal name/version

alacritty 0.8.0-dev (9f560b3)

### $TERM environment variable

xterm-256color

### Installation

arch community repository

### How to reproduce the issue

nvim 

### Expected behavior

nvim should load sourcing configuration from my congiruation file located in ~/.config/nvim/init.vim

### Actual behavior

nvim fails to load and giving following errors : 

```
Error detected while processing /home/murali/.config/nvim/init.vim:
line   15:
E117: Unknown function: plug#begin
Error detected while processing /home/murali/.config/nvim/conf.d/00_editor.vim:
line    3:
E492: Not an editor command: Plug 'ctrlpvim/ctrlp.vim'
line   23:
E492: Not an editor command: Plug 'wincent/ferret'
line   27:
E492: Not an editor command: Plug 'tpope/vim-surround'
line   30:
E492: Not an editor command: Plug 'preservim/nerdcommenter'
line   36:
E492: Not an editor command: Plug 'terryma/vim-multiple-cursors'
line   43:
E492: Not an editor command: Plug 'editorconfig/editorconfig-vim'
line   44:
E492: Not an editor command: Plug 'tpope/vim-projectionist'
Error detected while processing /home/murali/.config/nvim/conf.d/01_statusline.vim:
line   20:
E492: Not an editor command: Plug 'vim-airline/vim-airline'
line   21:
E492: Not an editor command: Plug 'vim-airline/vim-airline-themes'
Error detected while processing /home/murali/.config/nvim/conf.d/02_colors.vim:
line    6:
E492: Not an editor command: Plug 'noahfrederick/vim-hemisu'
line    7:
E492: Not an editor command: Plug 'lsdr/vim-hemisu-airline'
line    8:
E492: Not an editor command: Plug 'dracula/vim', { 'as': 'dracula' }
line    9:
E492: Not an editor command: Plug 'vim-airline/vim-airline-themes'
Error detected while processing /home/murali/.config/nvim/conf.d/03_autocomplete.vim:
line    3:
E492: Not an editor command: Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
line   10:
E492: Not an editor command: Plug 'Shougo/neco-vim'
Error detected while processing /home/murali/.config/nvim/conf.d/04_lang_support.vim:
line    4:
E492: Not an editor command: Plug 'sheerun/vim-polyglot'
Error detected while processing /home/murali/.config/nvim/conf.d/05_test_runners.vim:
line    3:
E492: Not an editor command: Plug 'janko-m/vim-test'
Error detected while processing /home/murali/.config/nvim/conf.d/06_linters.vim:
line    3:
E492: Not an editor command: Plug 'dense-analysis/ale'
Error detected while processing /home/murali/.config/nvim/conf.d/07_numbers.vim:
line    1:
E492: Not an editor command: Plug 'myusuf3/numbers.vim'
Error detected while processing /home/murali/.config/nvim/conf.d/08_ledger.vim:
line    1:
E492: Not an editor command: Plug 'ledger/vim-ledger'
Error detected while processing /home/murali/.config/nvim/conf.d/10_easyalign.vim:
line    1:
E492: Not an editor command: Plug 'junegunn/vim-easy-align'
```

**Comment by zeertzjq** [comment] 2021-12-14 15:49
Can you provide your config then?

**Comment by zeertzjq** [comment] 2021-12-14 15:52
Where did you put `vim-plug`'s `plug.vim`? I think need to put it in `~/.config/nvim/plugin/`

**Comment by zeertzjq** [comment] 2021-12-14 15:54
Did you follow `vim-plug`'s install steps for Neovim? <https://github.com/junegunn/vim-plug#neovim>

**Comment by teto** [comment] 2021-12-14 15:57
not a neovim problem, neovim just doesn't see vimplug.

**Comment by muralikodali** [comment] 2021-12-14 16:29
I am using nvim for the past 10 months with same configuration (source: https://github.com/lsdr/nvim) .

I am seeing this problem for the past two days.
I am attaching my nvim configuration file for your reference.

[init.vim.txt](https://github.com/neovim/neovim/files/7713136/init.vim.txt)

thanks any way for giving your help.

**Comment by zeertzjq** [comment] 2021-12-14 22:29
The only possible reason I can see is that you didn't follow `vim-plug`'s install steps.

**Comment by TomSchammo** [comment] 2021-12-15 09:03
This happened to me as well after upgrading to neovim 0.6.
So I just downgraded for the time because I was to busy to deal with it, works fine with 0.5, so I don't what went wrong or on whose part, but I don't think it's just because OP didn't follow the installation instructions, unless he is expected to reinstall it after the update.

**Comment by zeertzjq** [comment] 2021-12-15 09:20
How did you install `vim-plug`?

**Comment by TomSchammo** [comment] 2021-12-15 09:47
Not sure, it has been a while, but I think I just pasted the code for 'Linux, Unix' in the neovim section into my terminal and ran it (not the Flatpack one).

I used the following code in my init.vim:

```
call plug#begin('~/.config/nvim/autoload/plug.vim')
" Plugins
call plug#end()
```

I played around for a bit just now, and updated again (to get back to 0.6) and I now get a lightly different error.
If I remove the autoload directory, everything is fine.

If I then PlugInstall again, it naturally get created. Sourcing the init.vim still works fine for some reason, but when I close neovim and open it again it complains that it '`Cannot source a directory: "/home/tom/.config/nvim/autoload/plug.vim"`'

Removing the directory and restarting it and it all works fine again, until I PlugInstall as well as close and open neovim again.

**Comment by TomSchammo** [comment] 2021-12-15 09:49
And I obviously had my plugins instead of the `" Plugins` comment. It was just meant as a placeholder.

**Comment by zeertzjq** [comment] 2021-12-15 09:56
Don't use a path ending with `plug.vim`, it will cause conflict.

**Comment by zeertzjq** [comment] 2021-12-15 09:57
Don't use a path under `autoload` directory. It will cause conflicts.

**Comment by TomSchammo** [comment] 2021-12-15 09:59
Yeah, that makes sense, renaming it seems to have fixed it for me at least.
Just out of curiosity, why did it work prior to 0.6?

**Comment by clason** [comment] 2021-12-15 10:01
There were (significant) changes under the hood how runtime files are loaded (to fully support Lua runtime files); not quite sure how that would impact this specific scenario, but it is related.

**Comment by TomSchammo** [comment] 2021-12-15 10:02
I see, thanks.

**Comment by zeertzjq** [comment] 2021-12-15 10:07
@muralikodali What does `:scriptnames` print in your Nvim?

**Comment by muralikodali** [comment] 2021-12-15 12:56
nvim is hanging with cpu rise.
bottom of the terminal is showing message "[deoplete] function deoplete#enable[9]..deoplete#initialize[1]..deoplete#init#_initialize[15]..deoplete#init#_channel, line 31"

i have to kill the nvim process every time i start nvim.

neovim-qt is not showing any problem. it is loading plugins as well.

**Comment by matveyt** [comment] 2021-12-15 13:45
@muralikodali  [Here](https://github.com/lsdr/nvim/blob/2356c3fc437010dd15aa216a6ef1c899972d9615/Makefile#L33) is the typo: `CURL` instead of `$(CURL)`. After you've failed to download `plug.vim` nothing is working, of course.

**Comment by clason** [comment] 2021-12-15 13:47
The linked issue strongly means that you're using a broken framework, so this is _not_ a bug in Neovim (until proven otherwise).

I'm closing this issue and will reopen if you can reproduce this with a _minimal_ config (that you can share) without such frameworks.

**Closed by clason** 2021-12-15 13:47 UTC
Labels: status:needs-repro
