### ISSUE TITLE
Code folding with foldexpr works in vim but not nvim

### ISSUE THREAD

**Issue by sdondley** [neovim/neovim#21300] opened 2022-12-05 19:48 UTC
### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

no, vim 9.0.820

### Operating system/version

Alpine Linux v3.17

### Terminal name/version

iterm 3.4.18

### $TERM environment variable

tmux-256color

### Installation

package manager

### How to reproduce the issue

1) In init.vim, add following code:

```
set nocompatible
filetype plugin on
syntax on

set nocompatible
set mouse=a
let g:vimwiki_fold_blank_lines = 0   "set to 1 to fold blank lines
let g:vimwiki_header_type = '#'      "set to '=' for wiki syntax
set foldenable
set foldlevel=0
set foldmethod=expr
set foldexpr=Fold(v:lnum)

function! Fold(lnum)
   let fold_level = strlen(matchstr(getline(a:lnum), '^' . g:vimwiki_header_type . '\+'))
   echom fold_level
   if (fold_level)
     return '>' . fold_level  " start a fold level
   endif
   if getline(a:lnum) =~? '\v^\s*$'
     if (strlen(matchstr(getline(a:lnum + 1), '^' . g:vimwiki_header_type . '\+')) > 0 && !g:vimwiki_fold_blank_lines)
       return '-1' " don't fold last blank line before header
     endif
   endif
   return '=' " return previous fold level
endfunction
```

Open a markdown file and create a file:

```
# Title
* bullet

## Header
* bullet

### subeheader
* bullet

## Header
```

When folding on a header with `za`, folding does not work as expected. 

### Expected behavior

![vim-working](https://user-images.githubusercontent.com/2506364/205729287-9bc9a502-9bdd-4ac4-8a65-7e0693786ba7.gif)

### Actual behavior

![notworking](https://user-images.githubusercontent.com/2506364/205729353-32d304df-cb38-4f6f-8850-266093303dd7.gif)

If folds are manually recalculated with `zx`, folding will work as expected in the file until new markdown code is added and `zx` has to be typed again to get the new markdown code to fold properly.

**Comment by sdondley** [comment] 2022-12-06 04:59
As best I can tell, vim updates the fold level for every line in the file after every keystroke in insert mode. This behavior appears to differ from nvim which appear to only update folds after entering insert mode using the `o` key and even then, it does not appear to check every line.

**Comment by zeertzjq** [comment] 2022-12-06 05:05
Duplicate of #18479

**Closed by zeertzjq** 2022-12-06 05:05 UTC
Labels: bug, folds
