### ISSUE TITLE
Neovim window stuck at 24x80 lines/columns

### ISSUE THREAD

**Issue by zoqaeski** [neovim/neovim#11066] opened 2019-09-20 11:02 UTC
- `nvim --version`: 0.4.2 and up
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Arch Linux
- Terminal name/version: Tilix 1.9.3 and GNOME Terminal 3.34 (vte3 0.58)
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

Can't be reproduced with `nvim -u NORC`. Can be reproduced with a minimal configuration file, as outlined in the section below.

### Actual behaviour
When neovim starts up, the lines and columns are restricted to 24×80. It doesn't do this if you start with `nvim -u NORC`. I've been trying to figure out _why_ this is happening, and have disabled all plugins and reduced my configuration down to this:

    if &compatible
    	set nocompatible
    endif
    if has('vim_starting')
    	set all&
    endif

    augroup vimrc
    	au!
    augroup END

    let g:mapleader = '\'
    let g:maplocalleader = '\'

    let g:loaded_netrw = 1
    let g:loaded_netrwPlugin = 1
    let g:loaded_netrwFileHandlers = 1
    let g:loaded_netrwSettings = 1
    let g:loaded_vimball = 1
    let g:loaded_vimballPlugin = 1
    let g:loaded_zip = 1
    let g:loaded_zipPlugin = 1
    let g:loaded_tutor_mode_plugin = 1
    let g:loaded_2html_plugin = 1

    set nowrap
    set linebreak
    set breakat=\ \	;:,!?
    set nostartofline
    set whichwrap+=h,l,<,>,[,],~
    set splitbelow splitright
    set switchbuf=useopen,usetab
    set switchbuf+=vsplit
    set backspace=indent,eol,start
    set diffopt=filler,iwhite
    set tags=.git/tags,tags
    set showfulltag
    set complete=.
    set completeopt=menuone
    set completeopt+=noselect
    set virtualedit=block
    "set report=0
    set magic
    set modeline
    "set modelines=5
    set mouse=a
    set mousehide
    set hidden
    set autoread
    set fileformats+=unix,dos,mac
    set nrformats=octal,hex,alpha
    set noerrorbells
    set novisualbell
    "set textwidth=0
    "set tabstop=4
    "set softtabstop=4
    "set shiftwidth=4
    set smarttab
    set autoindent
    set smartindent
    set noexpandtab
    set shiftround
    set nolist
    set timeout ttimeout
    "set timeoutlen=1000
    "set updatetime=1000
    "set ttimeoutlen=-1
    set hlsearch
    set incsearch
    set ignorecase
    set smartcase
    set wrapscan
    set showmatch
    set matchpairs+=<:>
    "set matchtime=1
    set cpoptions-=m
    if has('wildmenu')
    	set wildmenu
    	set wildmode=list:longest,full
    	set wildoptions=tagfile
    	set wildignorecase
    	set wildignore+=.hg,.git,.svn
    	set wildignore+=*.aux,*.out
    	set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg
    	set wildignore+=*.o,*.obj,*.exe,*.dll,*.manifest
    	set wildignore+=*.spl
    	set wildignore+=*.sw?
    	set wildignore+=.DS_Store
    	set wildignore+=*.luac
    	set wildignore+=*.pyc
    endif
    set sessionoptions-=blank
    set sessionoptions-=options
    set sessionoptions-=globals
    set sessionoptions-=help
    set sessionoptions+=tabpages
    set viewoptions-=options
    set viewoptions-=unix,slash

The offending lines (that I've been able to find through a process of elimination) are commented out above. Why any of those lines should cause this weird issue is beyond me, as they're perfectly normal options to set.

![Screenshot from 2019-09-20 20-32-12](https://user-images.githubusercontent.com/172912/65321736-549d4780-dbe8-11e9-9a16-eab2f7c03c1c.png)

There's probably a whole lot more. My configuration, including plugins, is rather complex, and I keep discovering new ones as I add lines into the test init.vim I've been building up.

### Expected behaviour
Neovim should fill the terminal window.

**Comment by Boodleboy** [comment] 2019-09-20 16:32
Appears to be a regression. Can't replicate in my 0.3.8 release version. but can in current patch. Having build troubles with git bisect though, so I don't know the exact patch.

**Comment by Boodleboy** [comment] 2019-09-20 17:13
Git-bisect gives me aa28e070e9f953c26405d765addd9f780ede2c5a as the first bad patch. However, I'm not sure this is accurate. On a separate note, resizing the window fixes the issue.

**Comment by blueyed** [comment] 2019-09-20 18:38
> However, I'm not sure this is accurate

To be sure just do a clean build (after `make distclean`) before this commit, and with this commit.
Thanks for bisecting already!

**Comment by blueyed** [comment] 2019-09-20 18:39
@Boodleboy 
What terminal are you using?

**Comment by Boodleboy** [comment] 2019-09-21 16:52
I'm using xterm. I'll be able to retry the git-bisect in a few days, unless there's a way for me to easily build neovim on a musl-based system

**Comment by dtcyganok** [comment] 2019-09-21 19:26
Also actual for the gnome-terminal

**Comment by blueyed** [comment] 2019-09-21 19:51
Might be more related to the window manager than the terminal maybe.

Results of git-bisect would be very helpful, @dtcyganok.

**Comment by dtcyganok** [comment] 2019-09-22 11:12
Yes, it's related to the window manager. Running terminal with flag `--maximize` triggers WM animation. After the animation is completed, the nvim has a size equal to the initial size of the terminal. It seems that nvim completes initialization before the animation of WM is completed.

Note: not reproducing with kitty terminal.

**Comment by bfredl** [comment] 2019-09-22 11:35
Can reproduce. It used to be worse though, before #10959 nvim would get stuck with the old size if it was resized while a message (like swap dialog) was shown (even after the message was dismissed). With master I can reproduce it using `nvim --cmd "lua os.execute('sleep 3')"` (and resize before 3 seconds), as a proxy for anything that blocks CPU without processing events. The resize event should only be delayed in this case, not dropped entirely.

**Comment by Boodleboy** [comment] 2019-09-23 17:16
Tested again (after make distclean) and confirmed aa28e070e9f953c26405d765addd9f780ede2c5a is the first bad patch

**Comment by nilsboy** [comment] 2020-04-02 13:13
FYI - I could fix this by removing this from my init.vim:
`set all&`
Which I added to reset all options when reloading the init.vim.

**Comment by zoqaeski** [comment] 2020-06-14 13:14
> FYI - I could fix this by removing this from my init.vim:
> `set all&`
> Which I added to reset all options when reloading the init.vim.

Confirmed this works for me as well. But why though? Why does resetting the options cause this bug?

**Comment by jamessan** [comment] 2020-06-14 14:22
> But why though? Why does resetting the options cause this bug?

Because `'lines'` and `'columns'` are options, which default to 24 and 80, respectively.

**Comment by glacambre** [comment] 2021-06-06 08:59
This will be fixed when https://github.com/neovim/neovim/issues/5783 is fixed I think.

**Comment by justinmk** [comment] 2023-07-15 18:43
There were some SIGWINCH improvements:

- https://github.com/neovim/neovim/pull/23415
- https://github.com/neovim/neovim/pull/17795

> I could fix this by removing this from my init.vim: `set all&`

Zero reason for that to be in your config. As mentioned it sets `'lines'` and `'columns'` to their default of 24 and 80.

**Closed by justinmk** 2023-07-15 18:43 UTC
Labels: bug, ui, has:repro
