### ISSUE TITLE
TUI: no cursor highlight (with termguicolors) in lxterminal

### ISSUE THREAD

**Issue by Iron-E** [neovim/neovim#12796] opened 2020-08-27 17:12 UTC
- `nvim --version`: v0.5.0-638-g91109ffda
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Linux version 5.4.60-1-lts (linux-lts@archlinux)
- Terminal name/version: `lxterminal` 0.3.2-2
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

1. Execute `set termguicolor`
2. Attempt to `highlight` the `Cursor` group with `guifg`, `guibg`, or `gui`.
3. See that it does not change.

### Actual behaviour

The cursor color/attributes do not change, and sometimes are not restored as per lambdalisue/fern.vim#177. Colorschemes such as junegunn/seoul256.vim#41 and Iron-E/nvim-highlite#2 are also affected.

### Expected behaviour

The `Cursor` highlight group can be highlighted like the other groups.

**Comment by erw7** [comment] 2020-08-27 17:51
Please read the following FAQ.

https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-color-in-the-terminal

**Comment by Iron-E** [comment] 2020-08-27 18:22
Thank you for the fast response!

`set guicursor` is also ignored for me, as per the issues linked (lambdalissue/fern.vim#177 is the most relevant).

**Comment by erw7** [comment] 2020-08-27 19:40
@Iron-E Please be specific about all the commands you actually executed in item 2 of "Steps to reproduce using `nvim -u NORC`". In my environment, I can change the color of the cursor on LXTerminal without any problems using the FAQ procedure.

Just to be sure, does the color of the cursor change when you run the following command on the shell?

```
printf "\x1b]12;rgb:ffff/0000/0000\x1b\\"
```

**Comment by Iron-E** [comment] 2020-08-27 19:50
The `printf` command does change the color of my cursor.

I used the FAQ procedure and no colors change. No combination of `:set guicursor`, `:highlight Cursor`, or `:highlight Cursor2` changes the color of the cursor (although the FAQ example _did_ change the shape).

**Comment by erw7** [comment] 2020-08-28 14:28
@Iron-E Can you tell me the results of the following commands? If your problem is different from #12800 and `set termguicolors | hi Cursor guifg=green guibg=green | set guicursor+=a:Cursor` doesn't change the color of the cursor, the only reason I can think of is that there is a problem with the `VTE_VERSION` environment variable.

```
nvim -u NORC -V3log
:q
egrep 'ext.(re)*set_cursor_color' log
echo $VTE_VERSION
```

**Comment by Iron-E** [comment] 2020-08-28 17:06
Here is the output of `egrep`:

```
ext.set_cursor_color      = <Esc>]12;#%p1%06x<C-G>
ext.reset_cursor_color    = <Esc>]112<C-G>
```

My `$VTE_VERSION` is `6003`.

I think this issue may be related to #12800, although I don't know enough to tell for sure if it's caused by something different. I use `fern.vim` and _also_ experience that issue. _This_ issue could be a symptom of _that_ issue, but _that_ issue could be a symptom of _this_ issue… 

I experience both this and #12800's described behaviors. I neither can restore a cursor once it has been set to be invisible, nor set a cursor's color with `highlight` groups and `guicursor`.

**Comment by erw7** [comment] 2020-08-30 15:39
Hmm. There seems to be no problem with `VTE_VERSION`. Also, `ext.set_cursor_color` and `ext.reset_cursor_color` are properly set. I installed Arch Linux and tried it and had no problems. And the lxterminal does not have a color setting for cursor that can cause problems. Sorry, I can't help you.

**Comment by justinmk** [comment] 2020-08-30 18:33
cursor highlighting in general is best-effort, because terminal support is not very widespread.

Given that it works on VTE on some systems and we don't have a repro, closing

**Closed by justinmk** 2020-08-30 18:33 UTC
Labels: bug, highlight, needs-repro, tui
