### ISSUE TITLE
gx broken

### ISSUE THREAD

**Issue by swalladge** [neovim/neovim#10935] opened 2019-09-04 08:23 UTC
A similar issue to #7536 . 

git bisect determined the first commit to present this issue was 7c19a4e51881294adc8d174c5be7f546a052c989

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

2. type a url in the buffer
3. move the cursor over the url and type `gx`

### Actual behaviour

On latest master, `gx` appears to show curl downloading something, and then a new split opens with a different buffer. Very weird.

### Expected behaviour

`gx` should open the url under the cursor in the browser.

**Comment by blueyed** [comment] 2019-09-04 08:34
This also happens with Vim for me.

**Comment by blueyed** [comment] 2019-09-04 09:00
Closing as duplicate of https://github.com/vim/vim/issues/4738.

**Closed by blueyed** 2019-09-04 09:00 UTC
Labels: bug
