### ISSUE TITLE
E576: Failed to parse ShaDa file: incomplete msgpack string at position 95

### ISSUE THREAD

**Issue by teamblubee** [neovim/neovim#4169] opened 2016-02-04 21:29 UTC
just built neovim and started getting these errors, that one in the title pops up when I launch neovim.

when I try to quit, this one pops up.

```bash
E576: Failed to parse ShaDa file: incomplete msgpack string at position 95
E136: Did not rename /home/.local/share/nvim/shada/main.shada.tmp.b because /home/.local/share/nvim/shada/main.shada does not looks like a ShaDa file
E136: Do not forget to remove /home/.local/share/nvim/shada/main.shada.tmp.b or rename it manually to /home/.local/share/nvim/shada/main.shada.
Press ENTER or type command to continue
```

now if I go and delete all the files in the ```bash /.local/share/nvim/shada folder``` then the errors go away but as soon as I open a new terminal the errors come back again. What is going on with these errors?

**Comment by teamblubee** [comment] 2016-02-04 21:32
in the past, nvim config was put in ```bash ~/.config/nvim/....``` but now it seems to have shifted to that ```bash /.local/share/nvim folder``` . Is that something new?

**Comment by ZyX-I** [comment] 2016-02-04 21:37
ShaDa file is not a configuration file. It is a replacement for viminfo file from Vim (which also was not a configuration file). Most likely your issue is duplicate of #4108.

**Comment by ZyX-I** [comment] 2016-02-04 21:38
If it is not a duplicate report here, I will reopen.

**Closed** 2016-02-04 21:37 UTC
Labels: duplicate
