### ISSUE TITLE
Ability to create virtual spaces (indentation)

### ISSUE THREAD

**Issue by IllustratedMan-code** [neovim/neovim#20622] opened 2022-10-12 15:16 UTC
### Feature already in Vim?

no

### Feature description

Add ability to set  extmarks at the beginning of a line while offsetting existing text. Something like:
```lua
vim.api.nvim_buf_set_extmark(0, 1, 0, 0, {virt_text = {{"  ", "none"}}, virt_lines_pos="bol"})
```
would change this:
```
** my heading
other text
```
to this:
```org
  ** my heading
other text
```
This would make implementing things like [`org-indent-mode`](https://github.com/nvim-orgmode/orgmode/issues/422) possible.

**Comment by clason** [comment] 2022-10-12 15:21
Duplicate of https://github.com/neovim/neovim/pull/9496

**Closed by clason** 2022-10-12 15:21 UTC
Labels: enhancement
