### ISSUE TITLE
neovim terminal emulator

### ISSUE THREAD

**Issue by teamblubee** [neovim/neovim#3894] opened 2015-12-23 05:29 UTC
When I open up neovim session and type :term to launch the built in terminal I get this error:

```bash
shell-init: error retrieving current directory: getcwd: cannot access parent directories:
 No such file or directory
```
and trying to change directory or doing anything related to directory like cd

```bash
chdir: error retrieving current directory: getcwd: cannot access parent directories: No s
uch file or directory
```
This just started to happen recently.

I have installed
NVIM v0.1.118-g91b8ab3

built from source.

**Comment by Pyrohh** [comment] 2015-12-23 09:19
That error happens when nvim's working directory is deleted while it is running; I can reproduce it by doing the following:

```
$ mkdir test
$ cd test
$ nvim -u NONE -c '!rm -r ../test' -c term
```

ksh and rc-shell behaves in a similar manner to bash.  I don't think this is related to anything in Neovim.

**Comment by ZyX-I** [comment] 2015-12-23 09:29
@Pyrohh This is rather strange behaviour for a shell: I am using zsh and have the following code run before each command (actually in accept-line hook, though it is better suited for precmd): `cd $PWD || cd` (if `cd` fails, switch to the home directory) which works fine when current directory was deleted. I.e. zsh still allows to change directories even if working directory was deleted.

**Comment by Pyrohh** [comment] 2015-12-23 19:50
@ZyX-I csh does something similar when getcwd fails at startup time:
```
csh: No such file or directory
csh: Trying to start from "/home/michael"
```
But I don't use `cd $PWD || cd` because mistyping a directory name would return me to home, which I'd prefer to avoid.

**Comment by Pyrohh** [comment] 2015-12-23 19:54
Anyway I'll close this as it's not certain the issue is related to Neovim, but please reopen if that's shown to be wrong.

**Closed by Pyrohh** 2015-12-23 19:54 UTC

**Comment by ZyX-I** [comment] 2015-12-23 21:11
@Pyrohh I am wondering how mistyping of directory name will return you to home with this code? Mistyping a name *fails cd command*, so $PWD stays the same.

**Comment by Pyrohh** [comment] 2015-12-23 23:43
@ZyX-I I misinterpreted what you said as aliasing `cd` to `cd $PWD || cd`, which makes no sense now that I think about it.
