### ISSUE TITLE
Documentation for vim.opt_local suggests behavior that matches setlocal, which is not the case for window-local options

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#15531] opened 2021-08-30 23:30 UTC
### Neovim version (nvim -v)

NVIM v0.5.0

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Ubuntu 21.04

### Terminal name/version

Konsole 20.12.3

### $TERM environment variable

xterm-256color

### Installation

appimage

### Description

> "In any of the above examples, to replicate the behavior `setlocal`, use
`vim.opt_local`. Additionally, to replicate the behavior of `setglobal`, use
`vim.opt_global`.

The documentation for `:help lua-vim-optlocal` suggests that `vim.opt_local` can be used similarly as `:setlocal`. As shown below, this is not the case for window-local options.

```vim
nvim -u NORC
:setglobal nonumber
:lua vim.opt_local.number = true
:setglobal number?
```

In that example, using `vim.opt_local` results in a change in value for both the local and global setting of `number`. This is not the case when using `:setlocal`.

If the current behavior is intentional (see https://github.com/neovim/neovim/issues/15529), the documentation does not accurately describe the behavior.

**Comment by gpanders** [comment] 2021-08-31 01:02
`vim.opt_local` uses `nvim_win_set_option` under the hood, so I'll close this as a duplicate of #15529 to consolidate the discussion in one place.

**Comment by gpanders** [comment] 2021-08-31 01:54
See discussion [here](https://github.com/neovim/neovim/issues/15529). Re-opening and re-classifying this as a documentation issue.

@dstein64 Can you update the issue title to reflect this?

**Comment by gpanders** [comment] 2021-08-31 02:01
Oh and by the way, please feel free to open a PR with a documentation change. Improved clarity in documentation is always welcome :)

**Comment by dstein64** [comment] 2021-08-31 02:21
> "Can you update the issue title to reflect this?"

Sure. I just updated the title and description.

> "Oh and by the way, please feel free to open a PR with a documentation change."

It's unclear to me whether the behavior is intended in this case. Here are some related issues/PR: #14670, #13479, #14620

This issue might duplicate #14670.

**Closed** 2021-08-31 02:22 UTC
Labels: documentation
