### ISSUE TITLE
`nvim-qt` ignores certain keys when using Bépo keyboard layout on Windows

### ISSUE THREAD

**Issue by gropax** [neovim/neovim#7084] opened 2017-07-27 13:47 UTC
- `nvim --version`: v0.2.1-25-g2e3b78d1
- Operating system/version: Windows 10

Hello. I'm using the Bépo french keyboard layout available [on this site](https://bepo.fr/wiki/Windows) (`bepo-azerty.exe`) on Windows 10. The program `nvim-qt.exe` totally ignores certain keys such as `.` (corresponding to QWERTY `v` key) while `nvim.exe` run in `cmd` terminal detects them correctly. The ignored keys are ignored in every editing mode and in writing commands too.

**Comment by jamessan** [comment] 2017-07-27 13:52
This isn't the neovim-qt repository.  This is likely a duplicate of https://github.com/equalsraf/neovim-qt/issues/270.

**Closed by jamessan** 2017-07-27 13:52 UTC
