### ISSUE TITLE
Clipboard paste iTerm2 Character Displacement

### ISSUE THREAD

**Issue by chriskisskiss** [neovim/neovim#16326] opened 2021-11-15 13:01 UTC
### Neovim version (nvim -v)

0.6.0-dev+360-g9ca7b6b71

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.0.1

### Terminal name/version

iTerm2 3.4.12

### $TERM environment variable

xterm-256color

### Installation

brew

### How to reproduce the issue

- start nvim -u NONE in iTerm2
- paste a text of at least 764 characters from clipboard, then the 763th character will be missing and appended to the very ending of the pasted text.

does not happen in terminal, just iTerm2.
does not happen with vim in iTerm2.

### Expected behavior

dont mix up characters

### Actual behavior

mixes up character

**Comment by zeertzjq** [comment] 2021-11-15 13:09
Duplicate of #13431

**Closed by zeertzjq** 2021-11-15 13:09 UTC
Labels: bug, clipboard, tui
