### ISSUE TITLE
exists('$VAR') returns 0 for existing, but empty variable

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#3266] opened 2015-08-29 19:03 UTC
Some programs behave differently with empty, but existing variable and such exists() behaviour + #3265 makes it impossible to save and restore environment variables correctly. This issue was hit with `$TZ` variable, in Vim:

```
let saved_tz = $TZ
let $TZ = 'UTC'
echo strftime('%H', 0)
let $TZ = saved_tz
echo strftime('%H', 0)
```

will echo `00` two times instead of `00` and `03`. (In NeoVim it will always echo 03 because of #3264, but this code will change behaviour of `system('date')`.)

**Comment by tarruda** [comment] 2015-09-30 13:06
This should be the same issue as #3265

**Comment by tarruda** [comment] 2015-09-30 13:08
Actually this is the root cause of #3264, #3265 is another issue

**Comment by blueyed** [comment] 2019-07-30 09:22
This was done in https://github.com/neovim/neovim/commit/412d246be71bd99cb4edde4e6f984b0b0d91bcd9 / https://github.com/neovim/neovim/pull/2574.

**Comment by blueyed** [comment] 2019-07-30 09:32
It was labeled "bug-vim", but in Vim it actually works (at least by now).

**Comment by blueyed** [comment] 2019-07-30 11:06
https://github.com/neovim/neovim/pull/10657 fixes `exists()`, but that does not appear to be the described issue here really - which appears to be about https://github.com/neovim/neovim/issues/3264 mostly.

Given t.vim:

```vim
echo 'TZ='.$TZ
let saved_tz = $TZ
echo strftime('%H', 0)
echo system('date')

let $TZ = 'UTC'
echo 'TZ='.$TZ
echo strftime('%H', 0)
echo system('date')

let $TZ = saved_tz
echo 'TZ='.$TZ
echo strftime('%H', 0)
echo system('date')
```

I see this in Neovim (master, and with #10657), using `TZ=CEST nvim -u t.vim`:
```
TZ=CEST  
00
Tue 30 Jul 2019 11:01:33 AM CEST
TZ=UTC
00
Tue 30 Jul 2019 11:01:33 AM UTC
TZ=CEST
00
Tue 30 Jul 2019 11:01:33 AM CEST
```

Vim:
```
TZ=CEST 
00
Tue 30 Jul 2019 11:02:17 AM CEST
TZ=UTC
00
Tue 30 Jul 2019 11:02:17 AM UTC
TZ=CEST
00
Tue 30 Jul 2019 11:02:17 AM CEST
```

So Vim and Neovim are behaving in the same way here.

Not sure about https://github.com/neovim/neovim/issues/3264 / the real issue described here, but it appears like #10657 is irrelevant for it.

**Comment by blueyed** [comment] 2019-07-30 11:08
Let's take this issue by its subject only, which is fixed in https://github.com/neovim/neovim/pull/10657.

**Closed** 2019-08-09 21:43 UTC
Labels: bug, bug-vim, viml
