### ISSUE TITLE
Pressing and holding j/k to move cursor in tagbar is lag when tags items in tagbar is a little many and nvim set cursorline.

### ISSUE THREAD

**Issue by gngshn** [neovim/neovim#5084] opened 2016-07-18 03:45 UTC
- `nvim --version`:

```
NVIM v0.1.5-494-g65af001
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/grant_shen/backup/neovim/build/config -I/home/grant_shen/backup/neovim/src -I/home/grant_shen/backup/neovim/.deps/usr/include -I/home/grant_shen/backup/neovim/.deps/usr/include -I/home/grant_shen/backup/neovim/.deps/usr/include -I/home/grant_shen/backup/neovim/.deps/usr/include -I/home/grant_shen/backup/neovim/.deps/usr/include -I/home/grant_shen/backup/neovim/.deps/usr/include -I/usr/include -I/home/grant_shen/backup/neovim/build/src/nvim/auto -I/home/grant_shen/backup/neovim/build/include
Compiled by grant_shen@grant-pc

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```
- Vim (version: ) behaves differently?

Vim is not lagging.
- Operating system/version:

Ubuntu 14.04 lts
- Terminal name/version:

GNOME Terminal 3.12.3
- `$TERM`:

xterm-256color
### Actual behaviour

hold j/k in tagbar, the cursor is lag
### Expected behaviour

the cursor is not lag
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
# **The cause is `set cursorline`**, when I `set nocursorline` in tagbar, cursor will not lag. vim didn't have this problem

**Comment by justinmk** [comment] 2016-07-18 12:29
Which version of Vim are you comparing?

**Comment by gngshn** [comment] 2016-07-18 12:41
vim7.4

**Comment by justinmk** [comment] 2016-07-18 12:42
vim 7.4 has over 2000 patches. We need to know the patch level.

**Comment by gngshn** [comment] 2016-07-18 12:48
sry, tomorrow I will check. it is installed  by  apt in Ubuntu.

**Comment by gngshn** [comment] 2016-07-19 01:26
```
$ vim.gtk --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:59)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     +tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    +xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/tcl8.6  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1  
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib   
```

**Comment by gngshn** [comment] 2016-07-20 13:37
I tested gvim on my fedora, too.
Gvim don't lag when move cursor by holding j/k in tagbar. VIM version is
```
gvim --version                                                                                                                !900
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  2 2016 10:01:33)
Included patches: 1-1868
```

**Comment by justinmk** [comment] 2016-07-20 13:59
Possibly caused by the `win_line` changes in https://github.com/neovim/neovim/pull/4744.

**Comment by justinmk** [comment] 2017-12-23 14:31
Try `:set noshowcmd` . Otherwise this is a duplicate of https://github.com/neovim/neovim/issues/4736

**Closed by justinmk** 2017-12-23 14:31 UTC
Labels: performance
