### ISSUE TITLE
Full screen refreshed when :terminal window resized

### ISSUE THREAD

**Issue by whitecolor** [neovim/neovim#6040] opened 2017-02-01 16:08 UTC
- `nvim --version`: 0.1.7
- Operating system/version: Windows 10
- Terminal name/version: Mintty Ubuntu bash for windows 10
- `$TERM`: xterm-256color 

### Actual behaviour
Full screen refresh when terminal emulator window is resized.

I usually experience this behaviour if terminal window is visible on the screen and new window is added (esp. it is noticeable when using Ctrl+P/FZF temporary search windows which appear at the bottom of the screen) all windows are blinking. Аnd if there is no terminal windows among open windows (only text buffers) reaction on new opened search windows are much smoother (nothing blinks).

### Expected behaviour

No full screen refresh.

**Comment by whitecolor** [comment] 2017-02-02 16:34
On `todo` milestone: this really gives very unpleasant visual experience. I believe many people experience it but even don't understand why they see this flaw behavior. Hope to see this fixed soon.

**Comment by justinmk** [comment] 2017-02-02 19:32
It's unlikely to be fixed "soon". It's not a trivial problem, and I'm not sure how common it is. I certainly haven't noticed it (though I recall seeing a comment in the code saying why it happens).

**Comment by whitecolor** [comment] 2017-02-02 20:40
I think full refresh happens always when term is resized, it is quite noticeable when you have multiple windows filled with code and resizing terminal also using some advanced color themes.

**Comment by justinmk** [comment] 2018-08-26 21:07
Tested with `NVIM v0.3.1-130-gef9ef75a7` using `set writedelay=1`.

It depends on where your cursor is. E.g., if your cursor is at the top of the window (so it won't be "covered" by the new, temporary window created for example by FZF), usually the upper windows won't need to be redrawn.

The "full redraw" is because of Vim's tendency to re-center the viewport around where your cursor was in the most-recent window. 

IOW the "full refresh" happens because the viewports of all windows were shifted. `:terminal` tends to place the cursor at the _bottom_ of the buffer, so that's likely why it was correlated. (If you observe differently, I can't reproduce it. [Try the latest pre-release](https://github.com/neovim/neovim/releases)).

Related: https://github.com/neovim/neovim/pull/8088 introduced `:set display=msgsep` to avoid the "viewport bump" for the pager (e.g. `:messages`). Some have asked for a similar behavior to avoid the viewport-shift when a new window is created. 

To avoid viewport-shift when a new window is created, I can think of two feasible approaches: 

- Move the cursor in the window(s) as necessary. ...and un-move it if the layout is restored.
- Don't move the cursor, but next time the window is focused, shift the viewport.
    - In fact, sometimes this already is the case. The rules are inscrutable. (Vim is the same way.)

The original report here lacks clear steps to reproduce, and there isn't a precise goal, and "make redraw better" is something that's generally being worked upon. So, closing.

**Closed by justinmk** 2018-08-26 21:07 UTC
Labels: :terminal, complexity:medium, performance, ui, ux
