### ISSUE TITLE
error in lsp diagnostics 

### ISSUE THREAD

**Issue by dimbleby** [neovim/neovim#15697] opened 2021-09-17 15:03 UTC
### Neovim version (nvim -v)

NVIM v0.6.0-dev+289-g1ec3d3719

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

ubuntu 20.04

### Terminal name/version

wsltty

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

I'm using the terraform-ls language server, and hit this when I open a terraform file with no errors in it.

### Expected behavior

No errors

### Actual behavior

```
Error executing vim.schedule lua callback: vim/shared.lua:64: s: expected string, got nil
stack traceback:
        vim/shared.lua:64: in function 'gsplit'
        vim/shared.lua:111: in function 'split'
        ...local/nvim/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:76: in function 'get_buf_lines'
        ...local/nvim/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:83: in function 'diagnostic_lsp_to_vim'
        ...local/nvim/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:201: in function 'handler'
        /home/dch/.local/nvim/share/nvim/runtime/lua/vim/lsp.lua:681: in function 'cb'
        vim.lua:281: in function <vim.lua:281>
```

**Comment by dimbleby** [comment] 2021-09-17 15:03
`git bisect` points at a5bbb932f9094098bd656d3f6be3c58344576709, which I guess isn't all that helpful: except to say that the error is new.

**Comment by gpanders** [comment] 2021-09-17 15:07
Hmm, not sure why that is happening. Can you share (via a paste or gist) the file you're working on?

**Comment by dimbleby** [comment] 2021-09-17 15:09
I can't: but if it's not obvious what the problem is then I can try a bit harder to come up with a reproducible example that I can share.

**Comment by dimbleby** [comment] 2021-09-17 15:10
Alright, even this almost-nothing is enough:
```terraform
terraform {
  required_version = "~> 1.0"
    local = {
      source  = "hashicorp/local"
      version = "~> 2.1"
    }
  }
}
```

**Comment by gpanders** [comment] 2021-09-17 15:12
Thanks, I can reproduce. Looking into it now.

**Comment by davidgp1701** [comment] 2021-09-17 15:25
Yep, just updated to the latest nightly and I have been hit also with the same issue when trying to modify any Terraform file. Same exactly error. Even with the error it is showing suggestions: 
![image](https://user-images.githubusercontent.com/7021193/133808667-86a67d14-850b-4b86-85ed-f5a9582b13cb.png)

Disabling Terraform LS meanwhile. Let me know if you need help debugging something.

**Comment by gpanders** [comment] 2021-09-17 15:30
Please try #15696.

**Comment by dimbleby** [comment] 2021-09-17 15:38
That works for me!

**Comment by davidgp1701** [comment] 2021-09-17 15:49
It also fixes the issue for me!

**Comment by mjlbach** [comment] 2021-09-17 18:32
Closed by #15696

**Closed by mjlbach** 2021-09-17 18:32 UTC
Labels: bug, diagnostic

**Comment by fenuks** [comment] 2021-09-23 22:35
I don't know if I should post it in separate issue, but I have similar error while performing code action with rust_analyzer on NVIM v0.6.0-dev+335-gbe9382164 (built just before reporting this issue).

```
Code actions:                                                                                                                                                     
1. Remove `mut` keyword
Type number and <Enter> or click with the mouse (q or empty cancels): 1Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:502: command:
 expected string, got nil
stack traceback:
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:502: in function 'execute_command'
        /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:151: in function </usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:113>
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:465: in function 'callback'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1325: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:899: in function 'cb'
        vim.lua:281: in function <vim.lua:281>
```

Minimal init.vim:
```vim
call plug#begin('~/.local/share/nvim/plugged/')
    Plug 'https://github.com/neovim/nvim-lspconfig'
        
call plug#end()
lua << EOF
    require'lspconfig'.rust_analyzer.setup{}
EOF
```

Example code to trigger this problem:
```rust
fn main() {
    let mut a = 1;
}
```
After putting cursor at `mut` keyword, executing `:lua vim.lsp.buf.code_action()`, and executing action triggers error. It seems that it occurs on every code action from rust_analyzer.

**Comment by gpanders** [comment] 2021-09-24 15:54
@fenuks I cannot reproduce your issue with the example you provided. If you can still reproduce it with a minimal `init.lua` and Rust source file, please open a new issue.

**Comment by fenuks** [comment] 2021-09-24 16:03
I just rebuilt nvim, and on the latest master problem is gone now.
