### ISSUE TITLE
nvim 0.8.3-1 crash

### ISSUE THREAD

**Issue by yimingwangdell** [neovim/neovim#22989] opened 2023-04-10 07:23 UTC
### Problem

use "gd" command (jump defination) in CoC, after jump to new file, neovim crashed.

### Steps to reproduce

use "gd" command (jump defination) in CoC with any go project.

### Expected behavior

no crash.

### Neovim version (nvim -v)

0.8.3-1

### Vim (not Nvim) behaves the same?

don't know

### Operating system/version

manjaro

### Terminal name/version

kitty

### $TERM environment variable

256color

### Installation

pacman

**Comment by yimingwangdell** [comment] 2023-04-10 07:26
![image](https://user-images.githubusercontent.com/121928908/230850181-07c24c14-ee16-4421-8474-a12687e52e2b.png)

**Comment by yimingwangdell** [comment] 2023-04-10 07:27
![image](https://user-images.githubusercontent.com/121928908/230850303-ec7d98f7-8924-4e6d-bd1c-d0c3a717c175.png)
type "gd" (go to defination) here

**Comment by yimingwangdell** [comment] 2023-04-10 07:28
![image](https://user-images.githubusercontent.com/121928908/230850486-051af564-55fc-472e-8110-57d947982b0c.png)
neovim unexpectedly quit

**Comment by zeertzjq** [comment] 2023-04-10 08:16
Duplicate of #16287

**Closed by zeertzjq** 2023-04-10 08:16 UTC
Labels: bug
