### ISSUE TITLE
Treesitter indentation broken for filetype 'help'

### ISSUE THREAD

**Issue by SyedFasiuddin** [neovim/neovim#20461] opened 2022-10-03 04:22 UTC
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

Don't know

### Operating system/version

macOS 12.6

### Terminal name/version

Alacritty

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

```lua
require("nvim-treesitter.configs").setup {
    ensure_installed = all,
    indent = { enable = false },
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
}
```
And open any help file `:h treesitter`
I don't think this issue is related to `nvim-treesitter` plugin, as the parser for filetype `help` are built into neovim (I got to know this because I tried to uninstall and reinstall the parser, and it complained that file is still there and is not installed by it)

Facing this issue since 4 days, so it is not related (may be) to 0.8 release.

### Expected behavior

When highlights from Treesitter are disabled then things look as expected.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/66054777/193500673-267f894c-afd7-42ad-a0ee-8b79b5c7e520.png">

### Actual behavior

The indentation (if that what it is called) is broken when highlights are enabled

<img width="605" alt="image" src="https://user-images.githubusercontent.com/66054777/193500709-17e0c08f-4a2b-4fe2-9add-71990deb792c.png">

**Comment by zeertzjq** [comment] 2022-10-03 04:36
Duplicate of https://github.com/neovim/tree-sitter-vimdoc/issues/23

**Closed by zeertzjq** 2022-10-03 04:36 UTC
Labels: bug

**Comment by justinmk** [comment] 2022-10-03 19:26
If I use `:TSPlayground` to view the syntax tree, the node ranges look correct. Anyone see differently?

**Comment by clason** [comment] 2022-10-04 16:13
Yes. The `tag` node contains all leading whitespace; the anonymous `"*"` node and the `text` field are correct.
