### ISSUE TITLE
Diagnostics not updated

### ISSUE THREAD

**Issue by BigfootN** [neovim/neovim#14074] opened 2021-03-07 09:16 UTC
- `nvim --version`:
```
NVIM v0.5.0-dev+1123-g3fbff98cf
Build type: RelWithDebInfo
LuaJIT 2.0.5
```

- language server name/version:`clangd version 11.1.0`

- Operating system/version:`Linux 5.10.16-arch1-1`

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.
  - INFO: sumneko_lua: configuration checked.

</details>

<details>
<summary>lsp.log</summary>

### Logs before the problem

[Logs before the problem](https://gist.github.com/BigfootN/11c4174a22e602c975c6e11e86efcb86)

### Logs after the problem

I didn't find any. I cleared the log file before reproducing the problem. I reproduced the reproduced the problem and tried to refresh the log file, but I didn't find any.

</details>

### Steps to reproduce using minimal `init.lua`

1. Create a file named test.cpp
2. Only add this in the `init.lua`
`require('lspconfig').clangd.setup{}`
3. Write for example: `some error line`
4. One can see in the statusline that there is at least one error, but the virtual text isn't displayed

### A concrete example

I opened a `cpp` file containing some errors. I starting adding to the file a wrong line. In my case it was `var.sakdfhadf()`. But, despite my `:w` or buffer change, nothing happened. The only action that could take into account the problem was `:e`.

### Expected behaviour

I wished that the diagnostics were automatically refreshed, even when only refreshing the buffer. I wish to say that it happens sometimes, but it only *seems* on small or new files.

### Further information

The example I described was in a `C++` project with a `compile_commands.json`.

Thank you very much in advance for any help hoping I was clear enough.

**Comment by mjlbach** [comment] 2021-03-07 09:18
Not enough info. I need a minimal init.vim/init.lua and an example repo for a project in which this can be reliably reproduced.

**Comment by BigfootN** [comment] 2021-03-07 09:37
I updated it hoping it's enough.

Thank you for your help.

**Comment by mjlbach** [comment] 2021-03-13 18:49
It's not, I don't get this error so I'll need the exact commit of neovim/nvim-lspconfig/clangd you're using, and an example repo that reproduces the issue.

**Comment by mjlbach** [comment] 2021-03-18 19:29
Any update? :)

**Comment by BigfootN** [comment] 2021-03-20 11:33
Sorry, I am unable to work on this during the week, only the week-end, when I have time.

I'll keep you updated.

**Comment by BigfootN** [comment] 2021-03-28 13:41
Sorry for keeping you waiting for so long, but I tried to reproduce the problem in other contexts, but I was unable to. The problem is that it's quite hard to reproduce, it seems "random". Unfortunately, I wasn't able to "detect" any pattern.

So if anyone has a better example for reproduction, please feel free. Sorry for not being able to be of any more help.

**Comment by mjlbach** [comment] 2021-03-28 20:14
Have you tried with a recent commit? It may have been due to utf-8 vs. utf-16 errors in clangd, which will be further addressed by https://github.com/neovim/neovim/pull/14233

**Comment by mjlbach** [comment] 2021-04-13 22:57
Closing, but if you can find a reproduction, feel free to open the issue.

**Closed by mjlbach** 2021-04-13 22:57 UTC
Labels: bug, lsp
