### ISSUE TITLE
nvim -r outputs partial list and hangs

### ISSUE THREAD

**Issue by themadsens** [neovim/neovim#12025] opened 2020-03-18 23:25 UTC
- `nvim --version`:
NVIM v0.4.3

- `vim -u DEFAULTS` (version: ) behaves differently?
N/A
- Operating system/version:
macOS Mojave 10.14.6

- Terminal name/version:
iTerm2

- `$TERM`:
xterm

### Steps to reproduce using `nvim -u NORC`
` nvim -u NONE --cmd 'setglobal directory=/var/preserve/' -r`

### Actual behaviour
Outputs partial list and hangs
```
Swap files found:
   In directory /var/preserve/:
1.    %Users%fm%.vimrc.swp
          owned by: fm   dated: Wed Mar 18 23:54:54 2020
         file name: ~fm/.vimrc
          modified: YES
         user name: fm   host name: fmmbp.lan
        process ID: 3422 (STILL RUNNING)
2.    %Users%fm%repos%CheckMark%www%js%app.js.swp
          owned by: fm   dated: Wed Mar 18 09:15:36 2020
         file name: ~fm/repos/CheckMark/www/js/app.js
          modified: no
         user name: fm   host name: fmmbp.lan
        process ID: 89594 (STILL RUNNING)
3.    %Users%fm%repos%CheckMark%www%js%controllers.js.swp
          owned by: fm   dated: Wed Mar 18 09:33:24 2020
         file name: ~fm/repos/CheckMark/www/js/controllers.js
          modified: no
         user name: fm   host name: fmmbp.lan
        process ID: 89594 (STILL RUNNING)
4.    %Users%fm%repos%CheckMark%www%js%model.js.swp
          owned by: fm   dated: Wed Mar 18 10:07:51 2020
         file name: ~fm/repos/CheckMark/www/js/model.js
          modified:
```

### Expected behaviour
Output full list. Vim will output the full list:
```
Swap files found:
   In directory /var/preserve//:
1.    %Users%fm%.vimrc.swp
          owned by: fm   dated: Wed Mar 18 23:54:54 2020
         file name: ~fm/.vimrc
          modified: YES
         user name: fm   host name: fmmbp.lan
        process ID: 3422 (STILL RUNNING)
2.    %Users%fm%repos%CheckMark%www%js%app.js.swp
          owned by: fm   dated: Wed Mar 18 09:15:36 2020
         file name: ~fm/repos/CheckMark/www/js/app.js
          modified: no
         user name: fm   host name: fmmbp.lan
        process ID: 89594 (STILL RUNNING)
3.    %Users%fm%repos%CheckMark%www%js%controllers.js.swp
          owned by: fm   dated: Wed Mar 18 09:33:24 2020
         file name: ~fm/repos/CheckMark/www/js/controllers.js
          modified: no
         user name: fm   host name: fmmbp.lan
        process ID: 89594 (STILL RUNNING)
4.    %Users%fm%repos%CheckMark%www%js%model.js.swp
          owned by: fm   dated: Wed Mar 18 10:07:51 2020
         file name: ~fm/repos/CheckMark/www/js/model.js
          modified: no
         user name: fm   host name: fmmbp.lan
        process ID: 89594 (STILL RUNNING)
5.    %Users%fm%repos%CheckMark%www%js%types.js.swp
          owned by: fm   dated: Wed Mar 18 09:33:24 2020
         file name: ~fm/repos/CheckMark/www/js/types.js
          modified: no
         user name: fm   host name: fmmbp.lan
        process ID: 89594 (STILL RUNNING)
6.    %Users%fm%repos%CheckMark%www%templates%stucksetuplist.html.swp
          owned by: fm   dated: Wed Mar 18 09:15:36 2020
         file name: ~fm/repos/CheckMark/www/templates/stucksetuplist.html
          modified: no
         user name: fm   host name: fmmbp.lan
        process ID: 89594 (STILL RUNNING)
7.    %Users%fm%repos%embgit%arm9%agentframework%agents%checkmark%CheckMark.lua.swp
          owned by: fm   dated: Wed Mar 18 23:52:28 2020
         file name: ~fm/repos/embgit/arm9/agentframework/agents/checkmark/CheckMark.lua
          modified: YES
         user name: fm   host name: fmmbp.lan
        process ID: 3422 (STILL RUNNING)
8.    %Users%fm%repos%epgit%ampep%Install%scripts%shellcmd.js.swp
          owned by: fm   dated: Mon Mar 16 16:15:20 2020
         file name: ~fm/repos/epgit/ampep/Install/scripts/shellcmd.js
          modified: no
         user name: fm   host name: fmmbp.lan
        process ID: 43207 (STILL RUNNING)
9.    %Users%fm%repos%modules%lora-gridlight%main%lg-app.c.swp
          owned by: fm   dated: Mon Mar 02 15:10:11 2020
         file name: ~fm/repos/modules/lora-gridlight/main/lg-app.c
          modified: no
         user name: fm   host name: fmmbp.amplexfil.dk
        process ID: 55669 (STILL RUNNING)
```

### Supplemental info from Activity Monitor dump
```
Sampling process 3558 for 3 seconds with 1 millisecond of run time between samples
Sampling completed, processing symbols...
Analysis of sampling nvim (pid 3558) every 1 millisecond
Process:         nvim [3558]
Path:            /usr/local/Cellar/neovim/0.4.3/bin/nvim
Load Address:    0xd104000
Identifier:      nvim
Version:         0
Code Type:       X86-64
Parent Process:  bash [1128]

Date/Time:       2020-03-19 00:14:36.300 +0100
Launch Time:     2020-03-19 00:13:21.396 +0100
OS Version:      Mac OS X 10.14.6 (18G3020)
Report Version:  7
Analysis Tool:   /usr/bin/sample

Physical footprint:         4736K
Physical footprint (peak):  4744K
----

Call graph:
    2867 Thread_15409132   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2867 start  (in libdyld.dylib) + 1  [0x7fff6077d3d5]
    +   2867 main  (in nvim) + 11156  [0x10d1fcc0e]
    +     2867 recover_names  (in nvim) + 1495  [0x10d20abcf]
    +       2867 swapfile_info  (in nvim) + 773  [0x10d20b3ca]
    +         2867 msg_puts_attr_len  (in nvim) + 672  [0x10d214ced]
    +           2867 msg_puts_display  (in nvim) + 875  [0x10d215ac7]
    +             2867 do_more_prompt.llvm.2223702587072919974  (in nvim) + 225  [0x10d213deb]
    +               2867 get_keystroke  (in nvim) + 353  [0x10d2187a6]
    +                 2867 os_inchar  (in nvim) + 294  [0x10d24d844]
    +                   2867 inbuf_poll.llvm.10449417788153045410  (in nvim) + 394  [0x10d24daac]
    +                     2867 loop_poll_events  (in nvim) + 138  [0x10d19116a]
    +                       2867 uv_run  (in libuv.1.dylib) + 359  [0x10d405a3e]
    +                         2867 uv__io_poll  (in libuv.1.dylib) + 846  [0x10d41476d]
    +                           2867 kevent  (in libsystem_kernel.dylib) + 10  [0x7fff608b878a]
    2867 Thread_15409133
      2867 start_wqthread  (in libsystem_pthread.dylib) + 13  [0x7fff609703fd]
        2867 _pthread_wqthread  (in libsystem_pthread.dylib) + 458  [0x7fff60970636]
          2867 __workq_kernreturn  (in libsystem_kernel.dylib) + 10  [0x7fff608b3bfa]

Total number in stack (recursive counted multiple, when >=5):

Sort by top of stack, same collapsed (when >= 5):
        __workq_kernreturn  (in libsystem_kernel.dylib)        2867
        kevent  (in libsystem_kernel.dylib)        2867

Binary Images:
       0x10d0f4000 -        0x10d349fff +nvim (0) <C13934C3-0AAF-3816-B046-4D6C2F8C4ED3> /usr/local/bin/nvim
       0x10d3f2000 -        0x10d3faffb +libintl.8.dylib (0) <CD236902-DB50-39BB-86BB-E9F0D22E5649> /usr/local/opt/gettext/lib/libintl.8.dylib
       0x10d3ff000 -        0x10d419fff +libuv.1.dylib (0) <CC244463-5FC3-3184-A888-1B4314857D77> /usr/local/opt/libuv/lib/libuv.1.dylib
       0x10d42c000 -        0x10d430fff +libmsgpackc.2.dylib (0) <96F48F32-F34F-3103-A21E-D6D9E903F121> /usr/local/opt/msgpack/lib/libmsgpackc.2.dylib
       0x10d437000 -        0x10d440fff +libvterm.0.dylib (0) <2B983607-6B65-3AE4-A36F-7BA2E8321130> /usr/local/opt/libvterm/lib/libvterm.0.dylib
       0x10d447000 -        0x10d44cffb +libtermkey.1.dylib (0) <F4D448A7-58DF-3771-B560-3C6E5177A1F6> /usr/local/opt/libtermkey/lib/libtermkey.1.dylib
       0x10d454000 -        0x10d45bfff +libunibilium.4.dylib (0) <696AD650-DAC4-3C62-A298-6A5D04EA3061> /usr/local/opt/unibilium/lib/libunibilium.4.dylib
       0x10d468000 -        0x10d4e9ff7 +libluajit-5.1.2.dylib (0) <071439AC-F0B9-34C7-982A-950DC06765F6> /usr/local/opt/luajit/lib/libluajit-5.1.2.dylib
       0x119938000 -        0x1199a270f  dyld (655.1.1) <1605ACFC-49C3-33AF-B319-5BE41FC6E208> /usr/lib/dyld
    0x7fff347dc000 -     0x7fff34c21fef  com.apple.CoreFoundation (6.9 - 1575.23) <91D1D63A-9417-376D-801A-9ABDE4879F48> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff5d321000 -     0x7fff5d322ffb  libDiagnosticMessagesClient.dylib (107) <A14D0819-0970-34CD-8680-80E4D7FE8C2C> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff5d761000 -     0x7fff5d762ffb  libSystem.B.dylib (1252.250.1) <53C66B05-7254-344C-BC66-7BD2EE41F4E5> /usr/lib/libSystem.B.dylib
    0x7fff5d9a6000 -     0x7fff5d9f9ff7  libc++.1.dylib (400.9.4) <9A60A190-6C34-339F-BB3D-AACE942009A4> /usr/lib/libc++.1.dylib
    0x7fff5d9fa000 -     0x7fff5da0fff7  libc++abi.dylib (400.17) <38C09CED-9090-3719-90F3-04A2749F5428> /usr/lib/libc++abi.dylib
    0x7fff5da10000 -     0x7fff5da10ff3  libcharset.1.dylib (51.200.6) <2A27E064-314C-359C-93FC-8A9B06206174> /usr/lib/libcharset.1.dylib
    0x7fff5e365000 -     0x7fff5e455fff  libiconv.2.dylib (51.200.6) <2047C9B7-3F74-3A95-810D-2ED8F0475A99> /usr/lib/libiconv.2.dylib
    0x7fff5e456000 -     0x7fff5e6b7ffb  libicucore.A.dylib (62141.0.1) <A0D63918-76E9-3C1B-B255-46F4C1DA7FE8> /usr/lib/libicucore.A.dylib
    0x7fff5ef9a000 -     0x7fff5f71ffdf  libobjc.A.dylib (756.2) <7C312627-43CB-3234-9324-4DEA92D59F50> /usr/lib/libobjc.A.dylib
    0x7fff5fce7000 -     0x7fff5fceaff7  libutil.dylib (51.200.4) <CE9B18C9-66ED-32D4-9D29-01F8FCB467B0> /usr/lib/libutil.dylib
    0x7fff5fe0a000 -     0x7fff5fe1cff7  libz.1.dylib (70.200.4) <B048FC1F-058F-3A08-A1FE-81D5308CB3E6> /usr/lib/libz.1.dylib
    0x7fff60600000 -     0x7fff60604ff3  libcache.dylib (81) <1987D1E1-DB11-3291-B12A-EBD55848E02D> /usr/lib/system/libcache.dylib
    0x7fff60605000 -     0x7fff6060fff3  libcommonCrypto.dylib (60118.250.2) <1765BB6E-6784-3653-B16B-CB839721DC9A> /usr/lib/system/libcommonCrypto.dylib
    0x7fff60610000 -     0x7fff60617ff7  libcompiler_rt.dylib (63.4) <5212BA7B-B7EA-37B4-AF6E-AC4F507EDFB8> /usr/lib/system/libcompiler_rt.dylib
    0x7fff60618000 -     0x7fff60621ff7  libcopyfile.dylib (146.250.1) <98CD00CD-9B91-3B5C-A9DB-842638050FA8> /usr/lib/system/libcopyfile.dylib
    0x7fff60622000 -     0x7fff606a6fc3  libcorecrypto.dylib (602.260.2) <01464D24-570C-3B83-9D18-467769E0FCDD> /usr/lib/system/libcorecrypto.dylib
    0x7fff6072d000 -     0x7fff60766ff7  libdispatch.dylib (1008.270.1) <97273678-E94C-3C8C-89F6-2E2020F4B43B> /usr/lib/system/libdispatch.dylib
    0x7fff60767000 -     0x7fff60793ff7  libdyld.dylib (655.1.1) <002418CC-AD11-3D10-865B-015591D24E6C> /usr/lib/system/libdyld.dylib
    0x7fff60794000 -     0x7fff60794ffb  libkeymgr.dylib (30) <0D0F9CA2-8D5A-3273-8723-59987B5827F2> /usr/lib/system/libkeymgr.dylib
    0x7fff607a2000 -     0x7fff607a2ff7  liblaunch.dylib (1336.261.4) <3E0F9DEC-BCD8-37AE-BF51-C9E8C4184B04> /usr/lib/system/liblaunch.dylib
    0x7fff607a3000 -     0x7fff607a8fff  libmacho.dylib (927.0.3) <A377D608-77AB-3F6E-90F0-B4F251A5C12F> /usr/lib/system/libmacho.dylib
    0x7fff607a9000 -     0x7fff607abff7  libquarantine.dylib (86.270.1) <3F36A3D6-9606-3D90-B520-809BAEF981C3> /usr/lib/system/libquarantine.dylib
    0x7fff607ac000 -     0x7fff607adff7  libremovefile.dylib (45.200.2) <9FBEB2FF-EEBE-31BC-BCFC-C71F8D0E99B6> /usr/lib/system/libremovefile.dylib
    0x7fff607ae000 -     0x7fff607c5ff3  libsystem_asl.dylib (356.200.4) <A62A7249-38B8-33FA-9875-F1852590796C> /usr/lib/system/libsystem_asl.dylib
    0x7fff607c6000 -     0x7fff607c6ff7  libsystem_blocks.dylib (73) <A453E8EE-860D-3CED-B5DC-BE54E9DB4348> /usr/lib/system/libsystem_blocks.dylib
    0x7fff607c7000 -     0x7fff6084efff  libsystem_c.dylib (1272.250.1) <7EDACF78-2FA3-35B8-B051-D70475A35117> /usr/lib/system/libsystem_c.dylib
    0x7fff6084f000 -     0x7fff60852ffb  libsystem_configuration.dylib (963.270.3) <2B4A836D-68A4-33E6-8D48-CD4486B03387> /usr/lib/system/libsystem_configuration.dylib
    0x7fff60853000 -     0x7fff60856ff7  libsystem_coreservices.dylib (66) <719F75A4-74C5-3BA6-A09E-0C5A3E5889D7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff60857000 -     0x7fff6085dfff  libsystem_darwin.dylib (1272.250.1) <EC9B39A5-9592-3577-8997-7DC721D20D8C> /usr/lib/system/libsystem_darwin.dylib
    0x7fff6085e000 -     0x7fff60864ffb  libsystem_dnssd.dylib (878.270.3) <D5352ABD-0311-3327-8E64-93F29EB19BF1> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff60865000 -     0x7fff608b0ffb  libsystem_info.dylib (517.200.9) <D09D5AE0-2FDC-3A6D-93EC-729F931B1457> /usr/lib/system/libsystem_info.dylib
    0x7fff608b1000 -     0x7fff608d9ff7  libsystem_kernel.dylib (4903.278.25) <A85A66F0-DBA2-3773-9798-8EC9C0BE3B4B> /usr/lib/system/libsystem_kernel.dylib
    0x7fff608da000 -     0x7fff60925ff7  libsystem_m.dylib (3158.200.7) <F19B6DB7-014F-3820-831F-389CCDA06EF6> /usr/lib/system/libsystem_m.dylib
    0x7fff60926000 -     0x7fff60950fff  libsystem_malloc.dylib (166.270.1) <011F3AD0-8E6A-3A89-AE64-6E5F6840F30A> /usr/lib/system/libsystem_malloc.dylib
    0x7fff60951000 -     0x7fff6095bff7  libsystem_networkextension.dylib (767.250.2) <FF06F13A-AEFE-3A27-A073-910EF78AEA36> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff6095c000 -     0x7fff60963fff  libsystem_notify.dylib (172.200.21) <145B5CFC-CF73-33CE-BD3D-E8DDE268FFDE> /usr/lib/system/libsystem_notify.dylib
    0x7fff60964000 -     0x7fff6096dfef  libsystem_platform.dylib (177.270.1) <9D1FE5E4-EB7D-3B3F-A8D1-A96D9CF1348C> /usr/lib/system/libsystem_platform.dylib
    0x7fff6096e000 -     0x7fff60978ff7  libsystem_pthread.dylib (330.250.2) <2D5C08FF-484F-3D59-9132-CE1DCB3F76D7> /usr/lib/system/libsystem_pthread.dylib
    0x7fff60979000 -     0x7fff6097cff7  libsystem_sandbox.dylib (851.270.1) <9494594B-5199-3186-82AB-5FF8BED6EE16> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff6097d000 -     0x7fff6097fff3  libsystem_secinit.dylib (30.260.2) <EF1EA47B-7B22-35E8-BD9B-F7003DCB96AE> /usr/lib/system/libsystem_secinit.dylib
    0x7fff60980000 -     0x7fff60987ff3  libsystem_symptoms.dylib (820.267.1) <03F1C2DD-0F5A-3D9D-88F6-B26C0F94EB52> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff60988000 -     0x7fff6099dff7  libsystem_trace.dylib (906.260.2) <12C1B9A2-39D6-3428-AE60-2303BD201A57> /usr/lib/system/libsystem_trace.dylib
    0x7fff6099f000 -     0x7fff609a4ffb  libunwind.dylib (35.4) <24A97A67-F017-3CFC-B0D0-6BD0224B1336> /usr/lib/system/libunwind.dylib
    0x7fff609a5000 -     0x7fff609d4fff  libxpc.dylib (1336.261.4) <F01E4F2D-64B0-3678-8A3A-387299E965FE> /usr/lib/system/libxpc.dylib
Sample analysis of process 3558 written to file /dev/stdout
```

**Comment by glacambre** [comment] 2020-03-19 11:49
This looks like a duplicate of https://github.com/neovim/neovim/issues/11386.

**Comment by themadsens** [comment] 2020-03-19 13:21
It does indeed. Sorry for missing this one (too)

**Comment by jamessan** [comment] 2020-03-27 15:59
Duplicate of #11386

**Closed by jamessan** 2020-03-27 15:59 UTC
Labels: bug
