### ISSUE TITLE
AltGr+5 does not output the "[" character on Windows terminal

### ISSUE THREAD

**Issue by fxthomas** [neovim/neovim#11061] opened 2019-09-19 10:04 UTC
Hello,

When run directly in a terminal window (launched using `nvim.exe`), typing AltGr+5 on my French keyboard outputs "5" and not "[" as I expect it to. Typing AltGr+° does output "]" correctly, and the issue does not appear when using `nvim-qt.exe`. Other console programs don't suffer from this (and, in particular, Vim 8.1.1777).

I've been having this issue for a while (dating back from one of the 0.3.x versions, still occurring on the latest development build), and it still occurs with no `init.vim` so my plugins/settings are not the cause.

Is there anything I can do to fix that?

Environment: Windows 10, ConEmu/Cmder 1.3.12, appears with Powershell or cmd.exe.

**Comment by erw7** [comment] 2019-09-20 05:23
@fxthomas I built `nvim` with debug output in CI.

- [64bit](https://ci.appveyor.com/project/neovim/neovim/builds/27541438/job/692nw7o2i4j1ganu/artifacts)
- [32bit](https://ci.appveyor.com/project/neovim/neovim/builds/27541438/job/2kg2cjdfcfmie59g)

Can you show me the `key.log` created by the next operation using this `nvim`?

```
nvim -u NORC 2> key.log
i
ArtGr+5
Esc
:q!
```

**Comment by justinmk** [comment] 2019-09-21 20:27
@fxthomas can you try one of the artifacts linked by @erw7 above, and give the requested info?

**Comment by fxthomas** [comment] 2019-09-21 20:53
Of course, and thanks a lot for the help! I will do that on Monday at work, I need access to my computer there.

**Comment by erw7** [comment] 2019-09-22 03:04
After that, when I examined it, there was information that `AltGr` generates the key code of `Alt`+`Ctrl`. I changed the keyboard layout to French and confirmed that `[` was entered with `Alt`+`Ctrl`+`5`, so the following artifact should have fixed the problem:

- [64bit](https://ci.appveyor.com/project/neovim/neovim/builds/27575561/job/r85oqk88yiccp328/artifacts)
- [32bit](https://ci.appveyor.com/project/neovim/neovim/builds/27575561/job/lf8yc5i2842spf1x/artifacts)

@fxthomas I didn't actually use the AZERTY keyboard, so can you check it?

**Comment by fxthomas** [comment] 2019-09-23 08:15
The last build works, thanks a lot! That's a whole lot of code in `libuv` to fix this though, Windows terminal handling seems... hard? 😉 

I also noticed while testing that the two dead keys ~ and \` (AltGr+2 and AltGr+7 respectively) also don't work if there is a quick solution.

**Comment by erw7** [comment] 2019-09-24 04:54
> I also noticed while testing that the two dead keys ~ and ` (AltGr+2 and AltGr+7 respectively) also don't work if there is a quick solution.

Can you show me by creating key.log when pressing `AltGr`+`2` and `AltGr`+`7` with this https://github.com/neovim/neovim/issues/11061#issuecomment-533410292 method?

By the way, when I pressed `Alt`+`Ctlr`+`2` and `Alt`+`Cltr`+`7` with French keyboard layout in my environment, I got the following `KEY_EVENT_RECORD`.

**Alt+Ctrl+2**
```
bKeyDown:          true
wVirtualKeyCode:   0x00000032
wVirtualScanCode:  0x00000003
UnicodeChar:       0x00000000
dwControlKeyState: 0x0000000a
bKeyDown:          true
wVirtualKeyCode:   0x00000032
wVirtualScanCode:  0x00000000
UnicodeChar:       0x0000007e
dwControlKeyState: 0x0000000a
bKeyDown:          true
wVirtualKeyCode:   0x00000032
wVirtualScanCode:  0x00000003
UnicodeChar:       0x0000007e
dwControlKeyState: 0x0000000a
bKeyDown:          false
wVirtualKeyCode:   0x00000032
wVirtualScanCode:  0x00000003
UnicodeChar:       0x00000000
dwControlKeyState: 0x0000000a
```

**Alt+Ctrl+7**
```
bKeyDown:          true
wVirtualKeyCode:   0x00000037
wVirtualScanCode:  0x00000008
UnicodeChar:       0x00000000
dwControlKeyState: 0x0000000a
bKeyDown:          false
wVirtualKeyCode:   0x00000037
wVirtualScanCode:  0x00000000
UnicodeChar:       0x00000060
dwControlKeyState: 0x0000000a
bKeyDown:          false
wVirtualKeyCode:   0x00000037
wVirtualScanCode:  0x00000008
UnicodeChar:       0x00000060
dwControlKeyState: 0x0000000a
```

As far as you can see,` UnicodeChar` is 0 when the key is pressed. When I tried with Notepad or `cmd.exe`, `~` and `` ` `` seem to be entered when the next key is pressed. As mentioned above, these two behave specially, so it seems difficult to respond immediately.

For your information, `vim` also can't handle these two correctly.

**Comment by erw7** [comment] 2019-09-26 05:59
@fxthomas Can you check that the dead keys issue should be fixed in the next artifacts.

- [64bit](https://ci.appveyor.com/project/neovim/neovim/builds/27677371/job/yvi30rvsmk4p43ey/artifacts)
- [32bit](https://ci.appveyor.com/project/neovim/neovim/builds/27677371/job/txcpt6d10wanqfg5/artifacts)

**Comment by fxthomas** [comment] 2019-09-26 17:26
Thank you! The new build exits insert mode without writing anything when typing either AltGr+2 or +7, so I guess it doesn't actually type ~ or `.

I can't actually see any output from nvim.exe in the console, nor redirect it to a file. No meaningful output with the `-V` switch either.

Does something like https://github.com/springcomp/optimized-azerty-win help? It's **not** the correct layout, the ~ and ` dead keys are inverted in the real AZERTY keyboard, but maybe the configuration files include correct info for these keys?

**Comment by erw7** [comment] 2019-09-27 04:00
> The new build exits insert mode without writing anything when typing either AltGr+2 or +7, so I guess it doesn't actually type ~ or `.

Since keys that should be skipped are not skipped, it seems that `Esc`+`2` or` Esc`+`7` is read by nvim and the insert mode is exited.

Can you use the compiler on a PC that has a keyboard attached? Please tell me what the next program displays if possible.

```C
#include <stdio.h>
#include <windows.h>

int main(void)
{
  char buf[KL_NAMELENGTH];
  HMODULE hmd = LoadLibrary("kernel32.dll");
  typedef BOOL (*FUNC)(LPSTR);
  FUNC func = (FUNC)GetProcAddress(hmd, "GetConsoleKeyboardLayoutNameA");
  if (func && func(buf)) {
    printf("%s\n", buf);
  }
  return 0;
}
```

From your key.log, `AltGr`+`2` and `AltGr`+`7` generate the following `KEY_EVNENT_RECORD`.

```
bKeyDown:          true
wVirtualKeyCode:   0x00000032
wVirtualScanCode:  0x00000003
UnicodeChar:       0x00000000
dwControlKeyState: 0x00000029

bKeyDown:          true
wVirtualKeyCode:   0x00000037
wVirtualScanCode:  0x00000008
UnicodeChar:       0x00000000
dwControlKeyState: 0x00000029
```

`LEFT_CTRL_PRESSED` is `0x0008` and `RIGHT_ALT_PRESSED` is `0x0001`. Therefore, it is expected that this key will be skipped according to the condition of [libuv/src/tty.c#L1150-L1157](https://github.com/erw7/libuv/blob/725a582aa29e2ae707e42b52b77fe560a652f541/src/win/tty.c#L1150-L1157)
, but it does not seem to be skipped. The result of `GetConsoleKeyboardLayoutNameA()` may not be the expected "0C".

```C
if (!!(KEV.dwControlKeyState & (LEFT_ALT_PRESSED | RIGHT_ALT_PRESSED))
    && !!(KEV.dwControlKeyState & (LEFT_CTRL_PRESSED | RIGHT_CTRL_PRESSED))
    && (KEV.wVirtualKeyCode == 0x32 || KEV.wVirtualKeyCode == 0x37)) {
  if (pGetConsoleKeyboardLayoutNameA(buf)
      && buf[6] == '0' && buf[7] == 'C') {
    continue;
  }
}
```

Ref. https://docs.microsoft.com/en-us/windows/console/key-event-record-str
Ref. https://msdn.microsoft.com/en-us/windows/ms646305(v=vs.80)
Ref. https://msdn.microsoft.com/en-us/windows/dd318693(v=vs.80)

If the above conditions are not met, the code of [libuv/win/src/tty.c#L1159-L1185](https://github.com/erw7/libuv/blob/725a582aa29e2ae707e42b52b77fe560a652f541/src/win/tty.c#L1159-L1185) will be executed and nvim will read `Esc`+`2` or `Esc`+`7`.

**Comment by fxthomas** [comment] 2019-10-09 09:26
Hello,

Sorry for leaving this hanging. I compiled your test program with MSVC 2015 with the following command:

```
cl.exe test.cpp
```

The result was:

```
PS> .\test.exe
The call to GetConsoleKeyboardLayoutNameA failed.
```

I added a call to `GetLastError` to figure out what happened, which helpfully returned 16385, if that helps?

**Comment by erw7** [comment] 2019-10-10 05:10
> I added a call to GetLastError to figure out what happened, which helpfully returned 16385, if that helps?

@fxthomas Thank. It seems that `GetConsoleKeyboardLayoutNameA()` is not implemented. In that case, it changed to use `GetKeyboardLayoutNameA()`. Please try the following artifacts:

- [64bit](https://ci.appveyor.com/project/neovim/neovim/builds/28006770/job/eyyursuhb76ekv0x/artifacts)
- [32bit](https://ci.appveyor.com/project/neovim/neovim/builds/28006770/job/2n0wkt186vaw4ghn/artifacts)

If that doesn't work, try changing the Default Keyboard Input Language to French.

**Comment by rehnarama** [comment] 2019-11-23 12:03
> 
> 
> > I added a call to GetLastError to figure out what happened, which helpfully returned 16385, if that helps?
> 
> @fxthomas Thank. It seems that `GetConsoleKeyboardLayoutNameA()` is not implemented. In that case, it changed to use `GetKeyboardLayoutNameA()`. Please try the following artifacts:
> 
>     * [64bit](https://ci.appveyor.com/project/neovim/neovim/builds/28006770/job/eyyursuhb76ekv0x/artifacts)
> 
>     * [32bit](https://ci.appveyor.com/project/neovim/neovim/builds/28006770/job/2n0wkt186vaw4ghn/artifacts)
> 
> 
> If that doesn't work, try changing the Default Keyboard Input Language to French.

I've had the same problem with all keyboard shortcuts involving AltGr on a Swedish layout. 
I can at least confirm that these artifacts seemed to solve all key combinations with AltGr I could think of on a Swedish layout

**Comment by Whatnever** [comment] 2019-11-28 00:19
Dunno if it is helping, but i can add that I had the same issue with the following keys on a german (qwertz) keyboard:
"{" (Altgr+7), "[ "(Altgr+8),"]" (Altgr+9), "}" (Altgr+0), but not with other altgr mod inputs like "|","@","€","\","~"

**Comment by quickstar** [comment] 2019-12-16 16:26
Tnx for the effort so far, unfortunately the same issue with Altgr keys on a swiss german (qwertz) keyboard.

**Comment by rapus95** [comment] 2020-03-06 06:25
are there any news on this/will this make it into the official release?

**Comment by erw7** [comment] 2020-03-07 06:53
> are there any news on this/will this make it into the official release?

I have reverted the offending change in neovim/libuv#11. The issue has been remedied as follows in the #11803 artifacts that incorporates the change:

- Dead key by `AltGr+2`, `AltGr+7` of French keyboard works without any problem.
- The problem of `AltGr+5` etc on French keyboard and `AltGr+7` etc  on German keyboard can be solved by the following settings.
  + `:inoremap <M-#> #` AltGr+3 on French
  + `:inoremap <M-}> }` AltGr+4 on French, AltGr+9 on German 
  + `:inoremap <M-[> [` AltGr+5 on French, AltGr+8 on German
  + `:inoremap <M-Bar> \|` AltGr+6 on French
  + `:inoremap <M-{> {` AltGr+7 on German
  + `:inoremap <M-Bslash> \` AltGr+8 on French 
  + `:inoremap <M-^> ^` AltGr+9 on French
  + `:inoremap <M-@> @` AltGr+0 on French
  + `:inoremap <M-]> ]` AltGr+ ° on French, AltGr+0 on German
  + `:inoremap <M-}> }` AltGr+ + on French

It should also solve the problem of not being able to enter dot '.' on the #11255 Italian keyboard.

I'm only checking with on-screen keyboards, so I'd like people who have real keyboards to try the [artifacts of #11803](https://ci.appveyor.com/project/neovim/neovim/builds/30742167/job/ik3xxlhkdeyeu8xk/artifacts).

**Comment by erw7** [comment] 2020-03-07 07:07
> @erw7 Any plans to make an official PR in the libuv repo to address this issue?

@quickstar Sorry for the late reply. I seem to have overlooked your comment. There are no plans to create a PR in libuv, as this problem is caused by a change in libuv that was forked by neovim. I have reverted the change that caused the problem in neovim/libuv#11.

**Comment by R-Michelsen** [comment] 2020-04-13 20:29
@erw7 Im still having the issues discussed in this issue, are they supposed to be fixed yet or is this still a WIP?

**Comment by erw7** [comment] 2020-04-15 10:10
#11803 is waiting to be merged into the master branch. Rebased #11803 to the latest master. I don't know how much demand there is, but if you're in trouble, you should try using that artifacts.

**Comment by R-Michelsen** [comment] 2020-04-15 14:22
Thank you! I'll keep a lookout for the eventual merge

**Comment by vhanla** [comment] 2020-04-17 15:23
Tried last NVIM v0.5.0-437-..... on Windows Terminal, AltGr+[number] is not working.

**Comment by shyney7** [comment] 2020-04-29 11:21
I'm using the latest release version v0.5.0-476-ge9cc38361 and this issue is still not fixed. I cant use the [Alt Gr]-Key in Neovim. so brackets like [] and {} are not possible.

**Comment by CodingJinxx** [comment] 2020-05-06 16:01
Has anyone found a fix yet, its still not working.
Ive got a german Keyboard and {, [, ], } are not working.

**Comment by mborejdo** [comment] 2020-05-07 16:23
Using the provided artifacts solve the problem for now for me on windows-terminal

**Comment by janorn** [comment] 2020-05-15 16:52
Need this fix for Swedish keyboards as well.

**Comment by Marc-Bender** [comment] 2020-05-16 14:25
this is very much an issue still. using the standard german qwertz layout aswell.
i cant type { and } (im doing c stuff so its essential!).

the qt version is doing it just fine though it just takes way longer to open up!

**Comment by Marc-Bender** [comment] 2020-05-16 14:32
propably related ctrl + > (ie. shift plus <|> button) does not indent the current line in either the normal or qt executable

**Comment by alchexmist** [comment] 2020-05-19 13:24
:wave:

* Locale: es-ES
* Spanish QWERTY keyboard layout.
* (nvim.exe) NVIM v0.5.0-508-gc37d9fa3d
* Windows Terminal Version: 0.11.1333.0
* alacritty 0.4.2 (f68de37)
* OS: Windows 10 (18363.836)

Modifier key | Key1          | Key2  | creates  | works
------------ | ------------- | ----- | -------- | ------
|            | º             |       | º        | yes
Shift        | º             |       | ª        | yes
AltGr        | º             |       | \        | yes
Shift        | 1             |       | !        | yes
AltGr        | 1             |       | \|       | no
Shift        | 2             |       | "        | yes
AltGr        | 2             |       | @        | no
Shift        | 3             |       | ·        | yes
AltGr        | 3             |       | #        | no
Shift        | 4             |       | $        | yes
AltGr        | 4             | \<SPC>| ~        | no
Shift         | 6             |       | &        | yes
AltGr        | 6             |       | ¬        | no
|            | ç             |       | ç        | yes
AltGr        | ç             |       | }        | no
|            | ´             | \<SPC>| ´        | yes
Shift        | ´             | \<SPC>| ¨        | yes
AltGr        | ´             |       | {        | yes
|            | \`            | \<SPC>| `        | yes
Shift        | `             | \<SPC>| ^        | yes
AltGr        | `             |       | [        | yes
|            | +             |       | +        | yes
Shift        | +             |       | *        | yes
AltGr        | +             |       | ]        | yes
AltGr        | e             |       | €        | no

nvim-qt.exe: Dead keys are broken in Windows for some keyboard layouts [\#270](https://github.com/equalsraf/neovim-qt/issues/270)

**Comment by ShinduHub** [comment] 2020-05-26 11:02
Just built the latest commit. It finally works!
https://github.com/ShinduHub/neovim/releases/tag/nightly

**Comment by quickstar** [comment] 2020-05-26 11:51
> 
> Now you can also use the AppVeyor artifacts:
> https://ci.appveyor.com/project/neovim/neovim/branch/master/job/fmjor6c3l1sowmg4/artifacts

I can confirm that those artifacts also resolve all the issues with a Swiss German keyboard :raised_hands:

**Comment by alchexmist** [comment] 2020-05-28 14:54
- Spanish QWERTY keyboard layout.
- NVIM v0.5.0-530-g618e9a769
- Windows Terminal 1.0.1401.0

It finally works! 🥳🎉

**Comment by corynz** [comment] 2020-10-09 12:54
Looks like NVIM v0.5.x fixes this!

**Comment by heyn0r** [comment] 2021-04-21 14:21
AltGr is working for v0.5.0-beta with German QWERTZ.

CTRL+ALT {Number} is not working. Is there anything i missed?

**Closed** 2022-04-25 08:47 UTC
Labels: platform:windows, input, status:has-plan
