### ISSUE TITLE
Slow Ex command in diffmode

### ISSUE THREAD

**Issue by f380cedric** [neovim/neovim#14055] opened 2021-03-04 16:38 UTC
- `nvim --version`:

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-eK2ojg/neovim-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-eK2ojg/neovim-0.4.4/build/config -I/build/neovim-eK2ojg/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-eK2ojg/neovim-0.4.4/build/src/nvim/auto -I/build/neovim-eK2ojg/neovim-0.4.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently? Yes

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 31 2021 04:47:07)
Included patches: 1-2434
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         -python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             +sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -Wdate-time -g -O2 -ffile-prefix-map=/build/vim-0zRpH4/vim-8.2.2434=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lm -ltinfo -lselinux -lcanberra -lacl -lattr -lgpm -ldl
```

- Operating system/version: Debian/testing
- Terminal name/version: alacritty 0.6.0
- `$TERM`: alacritty

### Steps to reproduce using `nvim -u NORC`

```
base64 /dev/urandom | head -c 2000000 | fold -b > 1.txt
base64 /dev/urandom | head -c 2000000 | fold -b > 2.txt
nvim -u NORC -d 1.txt 2.txt
:v/tt/d
```

### Actual behaviour

Neovim takes an enormous time to execute `:v` (100% CPU usage for 3-4 min).
Same to undo it.
It is "instantaneous" using external command (eg: `:%! sed '/tt/\!d'`).
It is "instantaneous" outside of diffmode (eg: `:diffoff<enter> :v/tt/d<enter> :diffthis<enter>`, but not with `:diffoff | v:/tt/d | diffthis`).
VIM is not affected.

### Expected behaviour

Neovim takes approximately the same time with and without diffmode to execute `:v`.

**Comment by glacambre** [comment] 2021-06-10 06:41
Can't reproduce on master/nightly - @f380cedric are you still experiencing this bug?

**Comment by f380cedric** [comment] 2021-06-10 17:20
@glacambre, yes I still do.
But note that my neovim version has not changed since my first report.
Debian testing is following stable releases, and last neovim stable release was 0.4.4 on 2020/08/07.
I have not tried out nightly builds.

**Comment by glacambre** [comment] 2021-06-11 05:21
@f380cedric Could you try the nightly release available here? https://github.com/neovim/neovim/releases
The appimage is very easy to try - you just download it and make it executable with `chmod +x nvim.Appimage`.

**Comment by f380cedric** [comment] 2021-06-11 16:56
Yeah, nightly build worked.
After bisecting, bug is older than v0.3.0 (building before that tag is painful).
However, 7274f5c177d49660ed8c06998da402a09f5f31c6 fixed it (quite obvious when you find it -_- )

**Comment by f380cedric** [comment] 2021-06-11 17:05
Btw, cherry-picking it on top of v0.4.4 fix the issue

**Comment by glacambre** [comment] 2021-06-11 18:15
Nice, I'll close this issue then :). There won't be a v0.4.5 - neovim will soon enter feature freeze and v0.5.0 will be released (hopefully) shortly after that.

**Closed by glacambre** 2021-06-11 18:15 UTC
Labels: bug
