### ISSUE TITLE
`nvim_set_decoration_provider` with inline virt-text doesn't work

### ISSUE THREAD

**Issue by max397574** [neovim/neovim#29687] opened 2024-07-13 14:57 UTC
### Problem

I tried creating a decoration provider which sets ephermar inline extmarks. This didn't work though. It just displayed nothing.

### Steps to reproduce

1. nvim --clean repro.lua
2. `:so`
```lua
-- repro.lua
local ns = vim.api.nvim_create_namespace("test")
local i = 0
local cursor
vim.api.nvim_set_decoration_provider(ns, {
    on_win = function(_, win)
        if win ~= vim.api.nvim_get_current_win() then
            return false
        end
	return true
    end,
    on_line = function(_, _, bufnr, line)
        local cursor = vim.api.nvim_win_get_cursor(0)
        if line == cursor[1] - 1 then
            i = i + 1
            vim.api.nvim_buf_set_extmark(bufnr, ns, line, cursor[2], {
                virt_text = { { i .. "x", "IncSearch" } },
                virt_text_pos = "inline",
                ephemeral = true,
            })
        end
    end,
})
```

### Expected behavior

I expect virtual text to show next to the cursor when the screen is being redrawn as it is the case with this
```lua
local ns = vim.api.nvim_create_namespace("test")
local i = 0
local cursor
vim.api.nvim_set_decoration_provider(ns, {
    on_win = function(_, win)
        if win ~= vim.api.nvim_get_current_win() then
            return false
        end
	return true
    end,
    on_line = function(_, _, bufnr, line)
        local cursor = vim.api.nvim_win_get_cursor(0)
        if line == cursor[1] - 1 then
            i = i + 1
            vim.api.nvim_buf_set_extmark(bufnr, ns, line, cursor[2], {
                virt_text = { { i .. "x", "IncSearch" } },
                virt_text_pos = "eol",
                ephemeral = true,
            })
        end
    end,
})
```

### Neovim version (nvim -v)

NVIM v0.10.0, Build type: Release

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

macOS 14.4

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

bob

**Comment by zeertzjq** [comment] 2024-07-13 15:00
Duplicate of #24797

**Closed by zeertzjq** 2024-07-13 15:00 UTC
Labels: bug
