### ISSUE TITLE
right button of mouse or `print screen` will close the error windows.

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#3969] opened 2016-01-09 07:56 UTC
My os is ubuntu ,I start nvm by `nvim -u NONE`

then echo g:test
will show me error message ,I want use mouse selete the message ,and type right button open the menu,then copy the message,it works well in vim .but in neovim  if I type right button of the mouse ,the error windows will be closed!
here is some pic for this issue
in vim 
![2016-01-09 15-49-54](https://cloud.githubusercontent.com/assets/13142418/12215093/ac605b02-b6e8-11e5-93f6-d9e4536e3473.png)
then I have select this message ,I can type right button of mouse to copy this message ,or can use print screen to make pic like above,
but in nvim if i type right button or `print screen` the message will gone only can catch this picture
![2016-01-09 15-53-01](https://cloud.githubusercontent.com/assets/13142418/12215104/1488a252-b6e9-11e5-96ed-ac73488697f8.png)

I think it is due to how to delimit the other command
because the below the error mesage shows `press Enter or type command to continue`

sorry for my pool english,I hope any one can understand

**Comment by justinmk** [comment] 2016-01-09 17:35
We have a bunch of issues which all are attributable to (probably) the same root cause. Tossing this in with  https://github.com/neovim/neovim/issues/3168

**Comment by wsdjeg** [comment] 2016-01-09 17:42
@justinmk sorry ,I am not typping into any char, are you sure it is the same issue?

**Comment by justinmk** [comment] 2016-01-09 17:48
Mouse actions are sent as char sequences

**Comment by wsdjeg** [comment] 2016-01-09 17:49
you see in vim ,I can open the menu of the terminal ,can open the search windows of terminal,but in neovim ,the popup menu will be closed

![2016-01-10 01-43-23](https://cloud.githubusercontent.com/assets/13142418/12217450/d136d692-b73b-11e5-8b9d-b192444fa2e0.png)
![2016-01-10 01-44-17](https://cloud.githubusercontent.com/assets/13142418/12217451/d138f206-b73b-11e5-87da-29dd9d4fbbc6.png)

**Comment by wsdjeg** [comment] 2016-01-09 17:55
@justinmk also type `Alt` get the same issue,the completion will be done,just like type `esc`

**Comment by justinmk** [comment] 2016-01-09 18:13
Again, this is most likely the same root cause (maybe related to setting the high bit). See also https://github.com/neovim/neovim/issues/3094

**Comment by wsdjeg** [comment] 2016-01-09 18:16
yes ,everything look like the same ,also `Alt+tab` get the same issue

**Comment by ZyX-I** [comment] 2016-01-09 19:36
I cannot reproduce this in konsole (yakuake), v0.1.2-190-g50db031.

**Comment by wsdjeg** [comment] 2016-01-10 00:15
@ZyX-I you means you use different terminal with me ?

**Comment by ZyX-I** [comment] 2016-01-10 00:17
@wsdjeg Yes. I would also check whether you can reproduce this in Vim, but before trying set `mouse=a` (just as well it is not reproducible here on my machine).

**Comment by wsdjeg** [comment] 2016-01-10 00:21
@ZyX-I in gnomer-terminal I hava test vim ,by default ,it do not set `mouse=a`,and everything works well,vim will reproduce this by set `mouse=a`,and neovim reproduce this in gnome-terminal both set `mouse=a` or not.

**Comment by justinmk** [comment] 2016-01-10 00:47
I really think we should revert the mouse=a default.

**Comment by ZyX-I** [comment] 2016-01-10 00:58
@wsdjeg For Neovim you should check with `set mouse=` and nothing because `set mouse=a` is the *default* and checking with nothing or `set mouse=a` is *meaningless.

**Comment by ZyX-I** [comment] 2016-01-10 01:01
@justinmk I would rather say that TUI should ignore mouse clicks (drags, whatever) done on messages area, statuslines and tab line (latter should be ignored only if tabline does not do mouse clicks processing). Given the behaviour of Vim in konsole I observe I actually thought that this was already done.

**Comment by wsdjeg** [comment] 2016-01-10 01:30
thanks for reopen this issue,I hope I can show you  all the repoduce way,but now I only find these;

* mouse clicks on message area
* open menu of terminal
* press `print screen`
* type Alt
* type Shilf + Ctrl + f,  it is hot key of terminal
* type Alt+tab to switch to other program

and if I found new way,I will update this message,thanks a lot

**Comment by wsdjeg** [comment] 2016-01-10 01:33
@justinmk @ZyX-I  set mouse=a as default I think it is good idea,there is no need to change same as vim ,but even if set mouse=a  in vim ,I also get some defferent behavior in neovim .

**Comment by ZyX-I** [comment] 2016-01-10 02:41
Typing alt is a different thing, I do not know why it triggers the thing, but if `alt` switches to terminal menu then it is probably FocusLost, same for `<C-S-f>`, `<A-tab>`.

By the way, can you define

    autocmd FocusLost * :let g:cnt=get(g:, 'cnt', 0) + 1 | echomsg 'FocusLost' g:cnt

and repeat all of the checks (check `:messages` before reporting in case you have missed something)?

**Comment by wsdjeg** [comment] 2016-01-10 03:02
ok I will do it, has add `autocmd FocusLost * :let g:cnt=get(g:, 'cnt', 0) + 1 | echomsg 'FocusLost' g:cnt`into vimrc
1. nvim test.js
2. type into `windows.`
3. type Ctrl+x Ctrl+y
4. type Alt+tab
5. `:mes`

I can not use right button of mouse copy the message,so i take a photograph

![aa](https://pbs.twimg.com/media/CYU7ZFQWcAAKiVa.jpg)

**Comment by wsdjeg** [comment] 2016-01-10 03:21
I think maybe it is the problem with my terminal

**Comment by ZyX-I** [comment] 2016-01-10 03:54
@wsdjeg Do not use right button, there is `:redir @+ | messages | redir END`. Why did you type `<C-x><C-y>` and `windows.` if your report was regarding `<A-Tab>`, `<PrintScreen>`, `<A->`, `<C-S-f>` and opening terminal menu? Also you do not need to open popup menu, this does not change when FocusLost event is sent by terminal emulator. Actually you have wasted a lot of time on checking that FocusLost is received when popup menu is active when you press `<A-Tab>` which is useless because FocusLost event is not and should not be prevented by popup menu presence (though it is subjectable whether it should close popup menu or not) and `<A-Tab>` is the *only* expected way to invoke this event among listed.

**Comment by ZyX-I** [comment] 2016-01-10 03:57
@wsdjeg Do not use right button, there is `:redir @+ | messages | redir END`.

Your report was regarding `<A-Tab>`, `<PrintScreen>`, `<A->`, `<C-S-f>` and opening terminal right click menu, why did you check only `<A-Tab>`? Also you do not need to open popup menu, this does not change when FocusLost event is sent by terminal emulator. Actually you have wasted a lot of time on checking that FocusLost is received when popup menu is active when you press `<A-Tab>` which is useless because FocusLost event is not and should not be prevented by popup menu presence (though it is subjectable whether it should close popup menu or not) and `<A-Tab>` is the *only* expected way to invoke this event among listed.

**Comment by ZyX-I** [comment] 2016-01-10 03:57
(Also you need to report first two errors you see to vim-javascript maintainers.)

**Comment by wsdjeg** [comment] 2016-01-10 04:12
ok I think I should show you some pictures,
first I open two terminals, one in on the right and the other is on the left
then ,I open a java file ,and open popupmenu,like below
![2016-01-10 12-04-43](https://cloud.githubusercontent.com/assets/13142418/12219916/e0f17220-b792-11e5-8dab-e9ddeb3066e0.png)
then I can use Alt +tab  switch between these two terminals, and the popupmenu will not be closed.
![2016-01-10 12-04-40](https://cloud.githubusercontent.com/assets/13142418/12219909/980ab602-b792-11e5-9a96-a743c30377c9.png)
also the error message area will not be closed,you see I am now in the left terminal and the right terminal's message area will not be closed
![2016-01-10 12-10-48](https://cloud.githubusercontent.com/assets/13142418/12219929/352bebc2-b793-11e5-94d3-4de5ff295218.png)
 
but in neovim ,the popupmenu will be closed ,when I type Alt+tab ,also the message area will be closed too

**Comment by ZyX-I** [comment] 2016-01-10 04:50
@wsdjeg Vim does not support FocusLost events in terminal AFAIK (even though there is a patch for this). If you need to compare the behaviour with Vim, compare it with *GUI* Vim (though I should say I do not see messages closed by loosing focus with gtk Vim GUI).

Also I *did not* ask about `<A-Tab>`, there are other things you reported to close messages and popup which may be *not* a result of FocusLost. And the question was whether FocusLost *may be* responsible for closing popups at right click menu, printscreen or other your actions you reported to close it.

SO STOP TALKING ABOUT `<A-TAB>`.

Cause for the closing in case of `<A-Tab>` was already suggested and last your comment has absolutely no value. If other ways to close popup window you reported run FocusLost then there are good chances that there is only one error, connected to FocusLost (i.e. to processing escape sequences terminal sends in this case).

**Comment by justinmk** [comment] 2016-01-10 04:57
> messages closed by loosing focus

Sounds like https://github.com/neovim/neovim/issues/3416. Closing as dup.

**Closed by justinmk** 2016-01-10 04:57 UTC
Labels: bug-vim, input

**Comment by ZyX-I** [comment] 2016-01-10 04:59
@justinmk Yeah, #3416 is more likely to be the same issues then https://github.com/neovim/neovim/issues/3094.

**Comment by wsdjeg** [comment] 2016-01-10 12:13
@ZyX-I @justinmk Hi I do not know why everything works well now,I just update my system,everything works well ,and I can type `alt` `print screen`
you see 
![2016-01-10 20-09-55](https://cloud.githubusercontent.com/assets/13142418/12221442/3637d1a0-b7d6-11e5-99f8-e40dbb8a0e03.png)
and if I set `mouse=` everything  works better because mouse movement will close popupmenu,I am using Touch Pad

**Comment by wsdjeg** [comment] 2016-01-10 12:16
this pic is for open java file type into `this.` the popupmenu auto open ,then move mouse by touch pad
![2016-01-10 20-14-46](https://cloud.githubusercontent.com/assets/13142418/12221464/fa928464-b7d6-11e5-8fb6-ce2c2396d027.png)

**Comment by wsdjeg** [comment] 2016-01-11 13:06
this issue appear again,really do not know why?
