### ISSUE TITLE
Allow indicating that virtual text  may be wrapped

### ISSUE THREAD

**Issue by WhyNotHugo** [neovim/neovim#26882] opened 2024-01-04 14:35 UTC
### Problem

For lsp_lines.nvim, some users want error diagnostics to be wrapped ([related issue](https://todo.sr.ht/~whynothugo/lsp_lines.nvim/46))

The current virtual text API does not allow for me to indicate "this text may be wrapped". Given that the virtual text is per-buffer, manually wrapping the text would produce awkward results. In particular, wrapping could be wrong for one split if the same buffer is shown on two vertical splits of different width.

### Expected behavior

I would like an API to either:

- Indicate that virtual text can be wrapped, or
- Indicate that virtual text may wrap if wrapping is enabled for a given buffer.

**Comment by Notarin** [comment] 2024-01-05 05:09
I would like to add that what cued me to originally make the issue was irl social interactions, I have been asked about this missing feature several times.
I as well would personally like to see this.

**Comment by zeertzjq** [comment] 2024-01-05 06:14
Duplicate of #18282

**Closed by zeertzjq** 2024-01-05 06:14 UTC
Labels: enhancement, extmarks
