### ISSUE TITLE
Failure to run interactive Python apps under Neovim

### ISSUE THREAD

**Issue by techtonik** [neovim/neovim#8633] opened 2018-06-24 04:37 UTC
- `nvim --version`: v3.0.0
- Vim (version: 8.1.055) behaves differently? Yes
- Operating system/version: Fedora 28
- Terminal name/version: Tilix 1.8.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
```
$ nvim -u NORC notfar.py
```
Inside:
```
:!./notfar.py
```

```
#!/usr/bin/env python3

import os

from prompt_toolkit import prompt

import sys

print(sys.stdin.isatty())
print(sys.stdout.isatty())

text = prompt(os.getcwd() + ">")
print("[debug] " + text)
```

### Actual behaviour
```
:!./notfar.py
False
False
Traceback (most recent call last):
  File "./notfar.py", line 12, in <module>
    text = prompt(os.getcwd() + ">")
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/shortcuts.py", line 548, in p
rompt
    eventloop=eventloop)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/shortcuts.py", line 576, in r
un_application
    output=create_output(true_color=true_color))
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/shortcuts.py", line 126, in c
reate_output
    ansi_colors_only=ansi_colors_only, term=term)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/terminal/vt100_output.py", li
ne 424, in from_pty
    assert stdout.isatty()
AssertionError

shell returned 1
```

### Expected behaviour
```
True
True
/home/user/p/notfar>
```
and waiting for input.

See https://github.com/jonathanslenders/python-prompt-toolkit/issues/648

**Comment by justinmk** [comment] 2018-06-24 08:30
This is addressed in the FAQ https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes

and is a duplicate of https://github.com/neovim/neovim/issues/1496

**Closed by justinmk** 2018-06-24 08:30 UTC
