### ISSUE TITLE
Windows: 'wildignorecase' behaves incorrectly

### ISSUE THREAD

**Issue by RedX2501** [neovim/neovim#2755] opened 2015-05-28 12:08 UTC
Using neovim (https://github.com/equalsraf/neovim/commit/80745009aa1ac8ef7323643ba3c059fa9e437798) from AppVeyor with neovim-qt (https://github.com/equalsraf/neovim-qt/commit/211cc4f7cf05f19a0f2d9a6f3d0c7c0f9f8cf9c6) I see an odd behaviour behind `wildignore`

If i do `set wildignorecase` then not only is the case not ignored but the completion list does not show any possible matches at all.

![vim_wildignore](https://cloud.githubusercontent.com/assets/929932/7859633/fe25d3fc-0542-11e5-9e16-fcbf131d65e2.png)
![vim_wildignore2](https://cloud.githubusercontent.com/assets/929932/7859636/feb438d6-0542-11e5-8cd0-fa3bcc9ea1fb.png)
![vim_wildignore3](https://cloud.githubusercontent.com/assets/929932/7859635/feb1eed2-0542-11e5-848d-67638cfb073f.png)
![vim_wildignore4](https://cloud.githubusercontent.com/assets/929932/7859634/feb084e8-0542-11e5-9c77-8a7d77116e12.png)

**Comment by equalsraf** [comment] 2015-05-28 21:46
Confirmed here. Pushed a quick fix to #810. Our `do_path_expand()` function is mostly the `unix_expandpath()` and it was checking for wildignorecase + fileignore case when it shouldn't.

**Comment by rajkumarananthu** [comment] 2020-09-02 15:44
Hi,

I am interested to work on this. I am a beginner in contributing. 
Can I get some help or pointers to understand the flow.
Where can I start to learn.

Thank you.

**Comment by equalsraf** [comment] 2020-09-02 21:08
Ufff its been a while (5 years :D).

It seems like the past me was looking into the `do_path_expand()` function. Check its use in path.c. You might also want to look into how the same function behaves in Vim.

**Comment by trunghung03** [comment] 2022-01-06 12:10
Hope I'm not mistaken somewhere, this issue seems to be fixed by the latest dev build (NVIM v0.7.0-dev+839-g09d270bce).
![setwildignorecase](https://user-images.githubusercontent.com/61304518/148380864-ad12ad63-92f1-4341-bbb2-e074a99e0bc2.png)
![setwildignorecase (2)](https://user-images.githubusercontent.com/61304518/148380872-ecd30d01-c6fd-4a5a-9ade-e8582e59e74e.png)
.

**Comment by 3N4N** [comment] 2023-03-19 02:37
Any reason it's not closed yet?  @trunghung03 is right: the bug's been fixed already.

**Closed** 2023-03-19 02:40 UTC
Labels: platform:windows, complexity:low
