### ISSUE TITLE
can not redirect to `/dev/stderr` using `:!cmd`

### ISSUE THREAD

**Issue by 22mahmoud** [neovim/neovim#22034] opened 2023-01-28 11:35 UTC
### Describe the bug

When using `:!cmd` to execute `curl` command with dumb the headers into `stderr` `-D /dev/stderr` I got this error

```zsh
Warning: Failed to open /dev/stderr
curl: (23) Failed writing received data to disk/application

shell returned 23
```

that's happen on my arch Linux machine, but it works on macOS without any errors as expected

### Steps to reproduce

nvim --clean
:!curl https://jsonplaceholder.typicode.com/todos/1 -D /dev/stderr

### Expected behavior

run `curl` command without errors and redirect both `stderr` and `stdout`

### Neovim version (nvim -v)

v0.9.0-dev-832+g881d4adb59

### Vim (not Nvim) behaves the same?

no vim works fine,  9.0

### Operating system/version

Linux 6.1.8-arch x86_64 GNU/Linux

### Terminal name/version

st

### $TERM environment variable

st-256color

### Installation

build from repo

**Comment by lorlouis** [comment] 2023-02-03 18:03
I was able to confirm the bug is also present in 0.8.2. It seems to be related to libuv as node.js [also has the same problem](https://stackoverflow.com/questions/40301841/cannot-create-dev-stdout-no-such-device-or-address). I'm not super familiar with libuv so there might be an option I haven't found that would solve the problem, but it seems to be a libuv/linux problem at first glance.

**Comment by lorlouis** [comment] 2023-02-03 20:42
I wrote [a minimal example](https://gist.github.com/lorlouis/1d84d694296d90421ac5699b3a36090a) that behaves the same as neovim. I tested it on both macos and linux and the bug is only present on linux so it looks like it's not a neovim bug.

**Comment by lorlouis** [comment] 2023-02-03 23:13
I looked through libuv's source code and as far as I can tell this is intended behaviour.
[this is the line that makes it impossible to open /dev/stderr in the subprocess](https://github.com/libuv/libuv/blob/be2ddacb906939d989a422e5b44f121bcf720f0d/src/unix/process.c#L359)

`dup2(old_fd, new_fd)` closes old_fd and sets the value of old_fd to new_fd. In our case that means closing 2 which is stderr. Linux (and Macos) do not support re-opening stdin/err/out after closing them. The reason why macos does not behave the same as linux is because [it use a different code path](https://github.com/libuv/libuv/blob/be2ddacb906939d989a422e5b44f121bcf720f0d/src/unix/process.c#L879) and it makes use of a macos extension. Sadly I think the only thing you can do is `!curl https://jsonplaceholder.typicode.com/todos/1 >&2`


```c
/* closing and then opening stderr example */
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>

#define STDERR_F "/dev/stderr"

int main(int argc, char **argv) {
    close(2); // comment this line and now everything works
    FILE *f;
    f =  fopen(STDERR_F, "a");
    if(!f) {
        printf("unable to open "STDERR_F": %s\n", strerror(errno));
        return -1;
    }

    fprintf(f, "this is a line of text\n");
    fclose(f);
    return 0;
}
```

**Comment by erw7** [comment] 2023-02-23 12:43
#14049 is about `/dev/stdin`, but the cause is the same. Thus, this is a duplication.

**Closed by erw7** 2023-02-23 12:43 UTC
Labels: bug, job-control
