### ISSUE TITLE
:redraw! flicker with `:hi Normal ctermbg=...`

### ISSUE THREAD

**Issue by mkoskar** [neovim/neovim#4210] opened 2016-02-09 16:03 UTC
I was trying to make `nvim` flicker-less on my `urxvt` and during the process I've done some testing across different terminals comparing `vim` and `nvim`.

Running `vim` and `nvim` like this:

```
$ (n)vim -u ~/.config/nvim/init.vim
```

where `~/.config/nvim/init.vim` is:

``` viml
set nocompatible
set noloadplugins

let mapleader = ','

set laststatus=2
set shortmess+=I

if !has('nvim')
    set t_ut=
endif

colorscheme default

tabnew

function! Test() abort
    let themes = [ 'default', 'desert', 'blue', 'evening']
    let l = len(themes)
    for theme in themes
        exec 'colorscheme '.theme
        let c = 0
        while c < 30
            redraw!
            sleep 100 m
            let c += 1
        endwhile
    endfor
    echomsg 'Test: finished - '.(has('nvim') ? 'NVIM' : 'VIM')
endfunction

nnoremap <silent> <Leader>tt :call Test()<CR>
nnoremap <silent> Q :qa!<CR>

autocmd! VimEnter * call Test()
```

I did that in `urxvt`, `st`, `termite`, and `xterm` and in each one inside `tmux` too.

Here are the results (columns are themes: `default`, `desert`, `blue`, `evening`):

```
$ echo $LINES:$COLUMNS
68:239

Legend:

* Ys - flickers (content + statusbar)
* Yt - flickers (content + tabbar)
* Yst - flickers (content + statusbar + tabbar)
* N - doesn't flicker
* Ys*, Yst* - doing `set t_ut=` fixes flickering in VIM

urxvt (bce) : rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
----------------------------------------
vim:            Yst     Yst     Yst*    Yst*
nvim:           Ys      Ys      N       N

vim+tmux:       N       N       N       N
nvim+tmux:      N       N       Ys      Ys

st (bce) : st 0.6 (c) 2010-2016 st engineers
----------------------------------------
vim:            Ys      Ys      Ys*     Ys*
nvim:           Ys      Ys      Yt      Yt

vim+tmux:       Ys      Ys      N       N
nvim+tmux:      Ys      Ys      Yt      Yt

termite (bce) : termite v10
----------------------------------------
N

xterm (bce) : XTerm(322)
----------------------------------------
vim:            N       N       N       N
nvim:           N       N       N       N

vim+tmux:       Ys      Ys      N       N
nvim+tmux:      Ys      Ys      Yt      Yt
```

Based on that I've managed to find a workaround for `urxvt`. Basically when running outside of `tmux` make sure your theme has `ctermbg` set (e.g., in my case `ctermbg=16`, when running inside `tmux` set it to `NONE`). On top of that `set noshowcmd` is needed to get rid of flickering completely inside `tmux`.

Status as of 26.05.2017
----

```
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23 (ArchLinux aur/rxvt-unicode-patched)
--------------------------------------------------------------------------------------
vim:            Yst     Yst     Yst*    Yst*
nvim:           Ys      Ys      N       N

vim+tmux:
nvim+tmux:      N

st 0.7 (c) 2010-2016 st engineers (ArchLinux community/0.7-1)
-------------------------------------------------------------
vim:
vim+tmux:       Ys      Ys      N       N

nvim:
nvim+tmux:      Ys      Ys      Yt      Yt

* cursor flickers in all cases

termite v12 (ArchLinux community/12-2)
--------------------------------------
N

XTerm(327) (ArchLinux extra/327-1)
----------------------------------
N
```

So for `urxvt+tmux` no workarounds are necessary anymore. Under `urxvt` itself you need theme that sets some `ctermbg` other than `NONE`.

**Comment by justinmk** [comment] 2016-02-09 16:12
Nice report, thanks. Seems ilke it's yet another case caused by the fact that we don't yet support setting termcap options via `t_*`. If you set the "ut" option via some other means (edit the termcap entry), I assume the problem will be fixed. Can you try that?

**Comment by mkoskar** [comment] 2016-02-09 16:39
@justinmk I've tried that with `urxvt` (removed `bce` terminfo entry) but not even `vim` picked it up. I mean `:set t_ut?` returns `t_ut=y` not sure why. It behaves exactly same. As far as `tmux` goes it doesn't do BCE nor it is in its terminfo.

**Comment by joshuarubin** [comment] 2017-02-24 02:29
Just to add to this, I've been using neovim with [Alacritty](https://github.com/jwilm/alacritty) and had `~100ms` `redraw!` time. Setting `hi Normal ctermbg=NONE guibg=NONE` helped a lot, but there is still definite flicker. Had to clear `guibg` since I have `termguicolors` enabled.

**Comment by geraldspreer** [comment] 2017-08-12 11:14
I can confirm this issue. I happens also on tmux 2.3. Also I have noticed that even after leaving neovim, the cursor flickers inside tmux. 
To clarify: I open two tmux panes. One with vim and another with some scrolling output like a tail -f or something. neovim in it's pane flickers the cursor. Then after I close neovim the cursor still flickers in that pane. It seems to me that neovim somehow changes settings to the cursor as well but I am not too sure on how would work.

**Comment by justinmk** [comment] 2017-11-23 01:32
@mkoskar Since https://github.com/neovim/neovim/pull/6799/commits/133ae5eeeff3b83e1a3e6da35b57dcdfb92287b0 (Nvim 0.2.1+) Nvim uses the BCE entry found in terminfo, if any. Can you confirm?

**Comment by mkoskar** [comment] 2017-11-23 16:50
@justinmk I've retested with d9b3ebfede6439aab4148c4bbf117b8950ed6aa0 with practically same results as my last update.

```
Legend:

* Ytcs - flickers (tabbar, content, statusbar)
* N - doesn't flicker

rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
(ArchLinux aur/rxvt-unicode-patched 9.22-10) - rxvt-unicode-256color (BCE)
----------------------------------------
vim:            Ytcs    Ytcs    Ytcs    Ytcs
vim+t_ut=y      Ytcs    Ytcs    N       N
nvim:           Ycs     Ycs     N       N

vim+tmux:       N
nvim+tmux:      N

st 0.7 (c) 2010-2016 st engineers
(ArchLinux aur/st 0.7-1) - st-256color (BCE)
----------------------------------------

I'll write "N" here, but st has some performance issues I think because on the
same machine and same window size sometimes just bottom half of the screen was
flickering. When making smaller window VIM was "N", but NVIM had top half of the
screen flickering but only for "blue" and "evening" regadless of tmux or not.
Also cursor was flickering almost all the time.

termite v12
(ArchLinux community/12-2) - xterm-termite (BCE)
----------------------------------------
N

XTerm(330)
(ArchLinux extra/330-1) - xterm-256color (BCE)
----------------------------------------
N
```

So:

1) we're good on `termite` and `xterm`
2) on `urxvt` we're flickering only on themes that **don't** have `ctermbg` for `Normal` highlight group
3) on `st` the case of themes that **do** have `ctermbg` set is quite strange

I wonder what is it with `urxvt` vs. `xterm` or `termite`. Hmm

**Comment by justinmk** [comment] 2017-11-23 20:36
@mkoskar Many thanks, that's really helpful. Why is (BCE) listed by st? AFAIK st doesn't support BCE without a custom patch.

I've updated https://github.com/neovim/neovim/pull/7624 to _always_ disable BCE (except for true xterm). If you can try one more time with that I hope we can finally reach a conclusion.

**Comment by mkoskar** [comment] 2017-11-23 23:12
@justinmk So I've messed up before, I tested HEAD and missed that PR.

Now I've tested with #7624 as before the 2nd commit and then also with it (`tui: Disable BCE almost always.`). In both cases I don't see any difference relative to my report above.

As for the BCE there, it signifies that BCE is present in terminfo. I don't know if `st` really implements BCE or not, the version I have doesn't have any custom patches (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=st), terminfo itself is provided by `ncurses 6.0+20170902`.

Is there a way to tell if `nvim` has BCE enabled or not? Just that I can double check.

**Comment by justinmk** [comment] 2017-11-24 07:55
> Is there a way to tell if nvim has BCE enabled or not?

Not yet. With #7624 it is always disabled unless XTERM_VERSION env var is defined. 

Seems that BCE is not the cause of this issue.

BTW does st performance improve if you `:set noshowcmd noruler` ?

**Comment by mkoskar** [comment] 2017-11-24 11:48
`st`

* I tested with simple `tput` and `printf` and it indeed **does** BCE
* `:set noshowcmd noruler` doesn't make a difference
* my test script is doing `redraw!` and `sleep 100 m` in a cycle, but surprisingly mapping `:nmap <C-L> :redraw!<CR>` and then pressing it few times in a row doesn't produce same flickering, but `:sleep 100 m | redraw! | sleep 100 m | redraw! | sleep 100 m | redraw!` **does** indeed flickers 3 times
* [here's](https://ptpb.pw/kZAc.webm) how it looks recorded with `blue` and then `evening` flickering much but only first few lines (first in `st` then in `st+tmux`)

`urxvt`

* `:set noshowcmd noruler` doesn't make a difference
* overwriting default `clear=\E[H\E[2J` to `clear=\E[H\E[J` helps a bit in a sense that with `\E[2J` whole screen flickers with `\E[J` only content and statusbar flickers (Ycs) in above report; I was actually testing with it before and I do this in my terminfo otherwise I get flicker of cursor when I do "clear" in shell

In case of `urxvt` it's weird and I'm leaning towards blaming its broken?/not-optimal terminfo.

**Comment by justinmk** [comment] 2017-11-24 12:12
Why _wouldn't_ `:redraw!` in a loop cause screen flicker? That tells vim to forcibly redraw the entire screen. Even `vim -N -u NORC` flickers in that case.

**Comment by mkoskar** [comment] 2017-11-24 13:49
Well, I get your point. IIRC I was doing `gt` before in my manual testing, and then went with `:redraw!` because when that one flickered `gt` would too. I don't remember honestly. Point is that doing `:redraw!` was/is producing inconsistent behaviour among `vim` vs. `nvim` and few terminals that I use interchangeably. I concede that logic of it dictates one should see the flicker yet mostly (as demostrated) it doesn't. I don't know why that is really.

I've changed my script now such that I do `tabnext` followed by `redraw` in cycle (so to follow the real use-case, should have done it this way from the beginning). Tested it, and the report is practically the same. Actually for `st` it's even more prominent.

```vim
" vim: ft=vim fdm=marker

set nocompatible
set noloadplugins

let mapleader = ','

set laststatus=2
set noruler
set noshowcmd
set shortmess+=I
set signcolumn=yes
set viminfo=

"if !has('nvim')
"    set t_ut=
"endif

colorscheme default

tabnew

function! Test() abort
    let themes = ['default', 'desert', 'blue', 'evening']
    let l = len(themes)
    for theme in themes
        exec 'colorscheme '.theme
        let c = 0
        while c < 30
            tabnext
            redraw
            sleep 200 m
            let c += 1
        endwhile
    endfor
    echomsg 'Test: finished - '.(has('nvim') ? 'NVIM' : 'VIM')
endfunction

nnoremap <silent> <Leader>tt :call Test()<CR>
nnoremap <silent> <C-L> :redraw<CR>
nnoremap <silent> Q :qa!<CR>

autocmd! VimEnter * call Test()
```

```bash
#!/usr/bin/env bash

set -eu

prgname=${0##*/}

cd ~/tmp

config="$HOME/.config/nvim/init-test.vim"

vim -u "$config"
tmux -L "$prgname" new "vim -u '$config'"

nvim -u "$config"
tmux -L "$prgname" new "nvim -u '$config'"
```

**Comment by damage220** [comment] 2018-02-07 12:48
mkoskar, thank you a lot for sharing a fix to this issue. It was the main reason why I did not use this terminal.

**Comment by justinmk** [comment] 2018-12-13 23:54
I don't think this is actionable beyond what @bfredl has done recently (0.3.2).

**Closed by justinmk** 2018-12-13 23:54 UTC
Labels: bug, display, tui, ui, ux
