### ISSUE TITLE
Flake fails to build

### ISSUE THREAD

**Issue by happenslol** [neovim/neovim#22961] opened 2023-04-08 13:31 UTC
### Problem

The flake currently fails to build due to a missing treesitter function. I've narrowed the commit that introduced it down to `090ade4af`, where the function `tree_get_ranges` was included, which calls `ts_tree_included_ranges`. This function can not be found and that results in the following build error:

```
error: builder for '/nix/store/nwybmmj9ddhxgp7gw950lhznk5j1zjfc-neovim-unwrapped-090ade4.drv' failed with exit code 2;
       last 10 log lines:
       > [ 95%] Building C object src/nvim/CMakeFiles/nvim.dir/__/xdiff/xpatience.c.o
       > [ 95%] Building C object src/nvim/CMakeFiles/nvim.dir/__/xdiff/xprepare.c.o
       > [ 95%] Building C object src/nvim/CMakeFiles/nvim.dir/__/xdiff/xutils.c.o
       > [ 95%] Linking C executable ../../bin/nvim
       > /nix/store/frh9l9nrdysasdi2gs7i241s241ngjw2-binutils-2.39/bin/ld: CMakeFiles/nvim.dir/lua/treesitter.c.o: in function `tree_get_ranges':
       > treesitter.c:(.text+0x1766): undefined reference to `ts_tree_included_ranges'
       > clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
       > make[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:4641: bin/nvim] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:529: src/nvim/CMakeFiles/nvim.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/nwybmmj9ddhxgp7gw950lhznk5j1zjfc-neovim-unwrapped-090ade4.drv'.
```

### Steps to reproduce

```bash
git checkout 090ade4af
cd contrib
nix build .#neovim
```

### Expected behavior

The build should produce a neovim binary. I suspect the newest treesitter version has to be included in the flake, since the offending commit also changed the following:

```
-find_package(Treesitter REQUIRED)
+find_package(Treesitter 0.20.8 REQUIRED)
```

There is no corresponding flake update though.

### Neovim version (nvim -v)

0.9.0-dev commit 090ade4af

### Vim (not Nvim) behaves the same?

no

### Operating system/version

NixOS 23.05.20230326.5f9d1bb

### Terminal name/version

wezterm 20221119-145034-49b9839f

### $TERM environment variable

xterm-256color

### Installation

Flake

**Comment by zeertzjq** [comment] 2023-04-08 13:34
Duplicate of #22921

**Closed by zeertzjq** 2023-04-08 13:34 UTC
Labels: bug
