### ISSUE TITLE
API: Uncertain cursor behavior when using nvim_buf_set_lines

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#10880] opened 2019-08-29 11:28 UTC
- `nvim --version`: NVIM v0.4.0-1856-g82d52b229
- Operating system/version: macos
- Terminal: alacritty
### Steps to reproduce using `nvim -u NORC`
1. nvim -u NONE
2. input and move cursor as follow
![image](https://user-images.githubusercontent.com/19503791/63936339-29fd1a80-ca92-11e9-8d09-66af21c6358f.png)
3. `:call nvim_buf_set_lines(0,0,-1,v:true,['aaa','bbbbb','ccccccc'])`
4. Actual: The cursor goes to line 1
4. Expected: The cursor should retain its position when possible

**Comment by justinmk** [comment] 2019-08-30 05:48
FYI: a new API function `nvim_put()` was recently added to Nvim master.

> The cursor should retain its position when possible

Duplicate of https://github.com/neovim/neovim/issues/10096

from https://github.com/neovim/neovim/issues/7756#issuecomment-496834966 : 

>The semantics of`nvim_buf_set_lines` is that it removes the entire line range and then adds new lines that have no relation to the old ones, it is not the "same" line anymore. For the behavior you want what is needed is some new API function that can make changes within lines, for instance replace the text between two arbitrary marks. This would preserve cursor positions and marks in untouched parts of the line, including just after a NL char if it is not replaced.

Thus a new API function like `nvim_buf_set_region` is planned.

**Closed by justinmk** 2019-08-30 05:48 UTC
Labels: bug
