### ISSUE TITLE
vim.api.nvim_set_hl doesn't work with certain highlight groups if already started

### ISSUE THREAD

**Issue by frabjous** [neovim/neovim#18266] opened 2022-04-26 03:22 UTC
### Neovim version (nvim -v)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

ArchLinux 5.15.34-1-lts kernel

### Terminal name/version

kitty 0.25.0 

### $TERM environment variable

xterm-kitty

### Installation

Archlinux community repository / pacman

### How to reproduce the issue

```
$ nvim --clean
:set termguicolors
:set cursorline
:lua vim.api.nvim_set_hl(0,'CursorLine',{ bg='#ff0000' })
``` 

### Expected behavior

The line the cursor is on (CursorLine) should be red (color set by lua api command).

### Actual behavior

CursorLine remains gray.

(I don't actually want it red; I just picked that color because it's better to pick something noticeable when testing.)

Note that this command works fine if called in a start-up script, or with `--cmd "lua vim.api.nvim_set_hl(0,'CursorLine',{ bg='#ff0000' })"` as a startup option. It just doesn't work if nvim is already running. `:hi CursorLine guibg=#ff00000` (or the equivalent `vim.cmd` in lua) work fine. It's only if called through `vim.api` in lua that it doesn't work.

This is just one example. There are other highlight categories that also seem not to work with `vim.api.nvim_set_hl` once nvim is running; another such is `ColorColumn`.

**Comment by clason** [comment] 2022-04-26 07:04
Duplicate of #18160

**Closed by clason** 2022-04-26 07:04 UTC
Labels: bug, api, highlight
