### ISSUE TITLE
[Q] Sending '<ESC>' through nvim_feedkeys?

### ISSUE THREAD

**Issue by chentau** [neovim/neovim#12312] opened 2020-05-13 21:48 UTC
Hi, I'm a little bit confused about the behavior of `nvim_feedkeys` when escaping key presses like `<esc>`.

In particular, something like this works:

`:exe "lua vim.api.nvim_feedkeys('\<esc>oa', 'm', true)`,

but this does not:

`:lua vim.api.nvim_feedkeys('\<esc>oa', 'm', true)`.

It returns the error message `E5104: Error while creating lua chunk: [string "<VimL compiled string>"]:1: invalid escape sequence near '''`.

I'm guessing that the error message comes from `\<esc>` not being a valid escape sequence in lua strings, but this doesn't explain why the first example works. 
Is this expected behavior, and how can I make it so the second example works? Thanks a lot.

```
nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment] 2020-05-13 22:37
The same thing happens with other control sequences, by the way, such as `\<c-v>`. See also #12297

**Comment by chentau** [comment] 2020-05-13 22:49
Thanks for pointing that other issue out. Should I close this issue as a duplicate?

**Comment by erw7** [comment] 2020-05-27 08:50
In VimL's double-quoted strings, as described in the `:h string`, `\<xxx>` represents a special key.

So

```
:exe "lua vim.api.nvim_feedkeys('\<esc>oa', 'm', true)"
```

will actually run

```
lua vim.api.nvim_feedkeys('^[oa', 'm', true)
```

However, in a lua chunk, `\<xxx>` has no special meaning. If you want to treat `\<xxx>` as a special key in the lua chunk, you need to do the following:

```
:lua vim.api.nvim_feedkeys(vim.api.nvim_eval('"\\<esc>oa"'), 'm', ture)
```

**Comment by clason** [comment] 2020-05-27 09:42
Just to make sure I get this straight: to pass special keys through lua, you _need_ to
1. escape the backslash,
2. use double quotes inside the single-quoted string, and
3. wrap all this in an `vim.api.nvim_eval`?

Is that something that can be encapsulated, either by an (optional) argument to `feedkeys` or a convenience function (since such sequences are relevant in other contexts as well)?

**Comment by erw7** [comment] 2020-05-27 10:00
> Is that something that can be encapsulated, either by an (optional) argument to feedkeys or a convenience function (since such sequences are relevant in other contexts as well)?

Now I've looked into it and found `nvim_replace_termcodes()`. Why don't you give this a try?

**Comment by clason** [comment] 2020-05-27 10:05
So something like
```vim
:lua vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('ifoo\<cr>',true,false,true),'m',true)
```
? That throws an error, and `\\<cr>` inserts one backslash.

**Comment by erw7** [comment] 2020-05-27 10:18
I don't think it's necessary to have a backlash. It's only in VimL that `\<xxx>` is a special key.

**Comment by nhooyr** [comment] 2020-06-03 13:36
@tjdevries Can you close as a duplicate of https://github.com/neovim/neovim/issues/12297

**Comment by tjdevries** [comment] 2020-06-03 13:39
Duplicate of #11297

**Comment by tjdevries** [comment] 2020-06-03 13:40
(I'm not good at typing apparently :facepalm:)

**Closed by tjdevries** 2020-06-03 13:39 UTC
