### ISSUE TITLE
strftime %T has no effect

### ISSUE THREAD

**Issue by habamax** [neovim/neovim#9252] opened 2018-11-18 15:43 UTC
- `nvim --version`: 0.3.1
- Vim (version: 8.1) behaves differently? YES
- Operating system/version: Win10
- Terminal name/version: GUI vim and neovim-qt

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:echo strftime("%y%m%d %T")

```

### Actual behaviour
nothing is showed
### Expected behaviour
current datetime should be shown

Actually this `:echo strftime("%y%m%d %T")` I took from help `:h strftime`

If I remove `%T` -- I get the date. If I change it to `%H:%M` I get the time. So there is smth wrong with `%T` format.

Gvim echoes the same function call without a problem.

**Comment by justinmk** [comment] 2018-11-18 17:02
Duplicate of #6781. Read the full discussion there and explain why it doesn't apply.

**Closed by justinmk** 2018-11-18 17:02 UTC
