### ISSUE TITLE
!okular file.pdf& no longer works

### ISSUE THREAD

**Issue by orangenschalen** [neovim/neovim#6564] opened 2017-04-21 17:09 UTC
If I try to open a pdf-file from nvim with okular `!okular file_name.pdf&'  the call returns and nothing seems to happen.
Opening without the '&' works but blocks nvim as expected. The former version worked three month ago and it works with the current version with e.g. katarakt.

 I'm a bit lost without any obvious error messages.

- neovim-0.1.7ubuntu1+git201704191303+3344+23~ubuntu17.04.1
- Vim (8.0.95) behaves differently?
Yes
- Operating system/version:
Ubuntu 17.04
- Terminal name/version:
konsole, bash
- `$TERM`:
xterm-256color

### Actual behaviour
Okular no longer opens with the pdf, but returns immediatly(?). No error message is shown.

### Expected behaviour
Okular should open with the given file.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:cd in/a/dir/with/a/pdf
:!okular file_name.pdf&
```

**Comment by justinmk** [comment] 2017-04-21 17:38
> The former version worked three month ago and it works with the current version with e.g. katarakt.

A bisect to a specific commit would help quite a lot then.

I've no idea what okular does, perhaps you can compare some other more common command.

Also, what happens if you use `:terminal`?

    :te 
    okular foo.pdf &

**Comment by orangenschalen** [comment] 2017-04-22 18:54
Okay, I'll try to bisect it then.

Okular is a pdf viewer programm, it belongs to the KDE family of programms.

Starting with |:te| instead of |:!| shows the same behaviour. With a |&|
the terminal terminates happily but nothing visible ist done.
Without a |&| the terminal comes up, okular as well and the latter
blocks the former as expected.

Thanks for the workarround proposition. I'll head on to the build
instructions next.

**Comment by justinmk** [comment] 2017-04-22 19:41
FWIW, `:te okular foo.pdf` won't block nvim, only the shell it runs in. You can `<C-\><C-N>` to return to normal-mode.

**Comment by orangenschalen** [comment] 2017-04-22 21:11
Yes, I'm aware of the possibility to leave the terminal afterwards, but I'd like to get back the "fire and forget" possibility of |:!my_favority_pdf_viewer %:r.pdf&| to view pdfs corresponding to my current LaTeX or whatever file.

Anyway, it is more complicated. The change of behaviour has seemingly been triggered by okular. I've went back to V0.1.5 + the luacheck change from 44e6ee930fff5bf42178 to make it build, and the behaviour is still "not as vim" and "not as expected". But as that is back more than 3 month, it should have worked.

I'll edit the claim that it ever worked with neovim in the initial posting. Hopefully someone can give a hint were to look for traces what actually happens during the call to the shell and okular.

**Comment by justinmk** [comment] 2017-04-22 21:46
That makes more sense. But one thing we need to confirm: if you run `:terminal`, and then run the command with `&` inside the terminal, does it work? This is different than running `:te foo &`. Like this:

```
:te
foo &
```

If that works, you can script it like this (hideous, I know):

```vim
:command! -nargs=+ Pdf let a=expand(<q-args>)|sp|exe 'te'|call jobsend(b:terminal_job_id, "okular ".a." &\nexit\n")
:Pdf %:r.pdf
```

> Hopefully someone can give a hint were to look for traces what actually happens during the call to the shell and okular.

Perhaps okular changed its behavior for ttys vs pipes. If so, this is a duplicate of #1496.

https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes

**Comment by ZyX-I** [comment] 2017-04-22 21:50
@justinmk I do not see any sense in such complex scripting. Just use `call jobstart(['okular', 'file_name.pdf'])`.

**Comment by ZyX-I** [comment] 2017-04-22 21:54
Also okular has absolutely no reason to change its behaviour: it is a GUI application. I would rather ask whether SIGHUP is sent in these cases. @orangenschalen Does `:!nohup okular … >/dev/null &` change anything?

**Comment by ZyX-I** [comment] 2017-04-22 22:02
BTW, `:!okular ~/image.png&` works for me, and okular even does not exit after Neovim (0.1.7, from portage) exits.

**Comment by ZyX-I** [comment] 2017-04-22 22:03
Okular itself is

```
Qt: 4.8.6
KDE: 4.14.28
Okular: 0.26.1
```

**Comment by orangenschalen** [comment] 2017-04-22 22:16
`:!nohup okular … >/dev/null &` does not work as well.
Actually `:!nohup dolphin > /dev/null &` does neither.

`:!thunderbird&` works as expected, `:!akregator&` doesn't. It seems KDE-libs related.

The versions are:

Qt: 5.7.1
KDE: 5.31.0
Okular: 1.0.3
Dolphin: 16.12.3

All as provided by Ubuntu 17.04.

**Comment by ZyX-I** [comment] 2017-04-22 22:23
@orangenschalen Can you post the `/tmp/okular.strace` after `:!strace -o /tmp/okular.strace okular … &`, assuming it exits in this case?

**Comment by orangenschalen** [comment] 2017-04-22 22:27
@justinmk: Yes, started from the integrated terminal it works, and the scripting (in yours and ZyX-l's versions) offers a workarround.

@ZyX-l: Here's the trace: [okular.strace.txt](https://github.com/neovim/neovim/files/949345/okular.strace.txt)

**Comment by ZyX-I** [comment] 2017-04-22 22:34
@orangenschalen It tries writing something to stderr, but there is no stderr to write to, so it gets killed by SIGPIPE. Try using `!okular … &>/dev/null &`. And I would still suggest to use `jobstart()`, it is cleaner and no need to bother with escaping.

**Comment by orangenschalen** [comment] 2017-04-22 22:41
Yes, with redirecting stderr it works. So I'll find out about the error message in question, may be pester the okular developers and create an alias for my use in nvim.

Thanks a lot for the enlightening help!

As I don't know whether the current behaviour of nvim is correct or not I'll leave the issue open. Feel free to close it, if you judge it fine as it is.

**Comment by ZyX-I** [comment] 2017-04-22 22:42
@justinmk I do not think we want to keep the out/err pipes after `:!` finished (also, if I am not mistaking by the time shell should successfully exit, okular makes init a parent and thus we will not be getting any SIGCHILD to wait for, so the only indication would be EOF when reading from out/err). Vim connects processes to its tty when using `:!`, so it does not have the problem, but it would have the problem with okular stderr output messing up the screen.

**Closed by ZyX-I** 2017-04-22 22:42 UTC
Labels: job-control

**Comment by orangenschalen** [comment] 2017-04-22 22:46
@ZyX-I: Correct, vim shows some error messages from okular upon okular's start up. Then it refreshes the screen after a key is pressed.
