### ISSUE TITLE
Auto Indentation is too slow

### ISSUE THREAD

**Issue by zubairakram** [neovim/neovim#9670] opened 2019-03-03 21:08 UTC
auto indentation operation is  too slow.
I tried to auto indent an HTML file having 23k lines.
I used command sequence ""gg v G =''' it takes too much time to complete the process and uses only one processor at a time.

however same process was performed in VSCode in just one second.

(it's just for example)

**Comment by justinmk** [comment] 2019-03-03 21:33
Duplicate of #6052

[treesitter](https://github.com/neovim/neovim/pull/9219) integration may also help with this.

**Closed by justinmk** 2019-03-03 21:33 UTC
