### ISSUE TITLE
map É doesn’t work

### ISSUE THREAD

**Issue by sanpii** [neovim/neovim#22076] opened 2023-01-31 17:49 UTC
### Describe the bug

Map with `É` doesn’t work.

### Steps to reproduce

nvim --clean
:map É i
É

### Expected behavior

Entering in insert mode.

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

no, vim 9.0.1182

### Operating system/version

Archlinux

### Terminal name/version

wezterm, 20221119-145034-49b9839f

### $TERM environment variable

ansi-256color

### Installation

system package manager

**Comment by zeertzjq** [comment] 2023-01-31 23:20
Duplicate of #20190

**Closed by zeertzjq** 2023-01-31 23:20 UTC
Labels: bug
