### ISSUE TITLE
support set the column place of sign

### ISSUE THREAD

**Issue by Archdsenna** [neovim/neovim#29717] opened 2024-07-15 02:49 UTC
### Problem

Can nvim support setting the position of the symbol in the sign colnum, as shown in the following figure?
![image](https://github.com/user-attachments/assets/eda735f7-d43f-4cec-970c-c44b3d5c27c9)
I want to set a certain sign to appear in a fixed sign colnum. I learned that sign_place() doesn't seem to be able to do this.

### Expected behavior

The sign appears in the fixed sign colnum.

**Comment by Shougo** [comment] 2024-07-15 02:54
Unfortunately, it is not supported.
The sign feature does not support specify column.

**Comment by Archdsenna** [comment] 2024-07-15 03:10
Thanks. Is there any plan to introduce this feature in the future? Can I do this in other ways?Is it possible to set the position of all symbols in the current buffer through vim script function, using the following command:
:execute 'sign place 2 line=1 name=GitGutterLineAdded buffer=' . bufnr('%')

**Comment by Shougo** [comment] 2024-07-15 04:27
Hm...  Why this feature is really useful?

**Comment by Archdsenna** [comment] 2024-07-15 05:29
In the previous discussion( [#19719](https://github.com/neovim/neovim/pull/19719) and [#19737](https://github.com/neovim/neovim/pull/19737) ), I saw that it is now possible to reuse the same column by setting the priority of the same type of mark, this helps more important symbols stand out on the far left, as shown in the figure below:
![image](https://github.com/user-attachments/assets/b98b5b72-1d85-4e47-a54d-ce714e4dfc58)

But in a column of flags with the same priority (where there is no flag with a higher priority), the flags are drawn from left to right, which results in the following situation(red Marking):
![image](https://github.com/user-attachments/assets/f34f0a30-470c-4f6f-946e-2c64fdb81c53)

The 'x' sign is displayed on the far left, which is not aligned with the 'x' sign above, which looks very confusing. In fact, I have also seen similar discussions here: [#10106]，but there seems to be no valid conclusion(https://github.com/neovim/neovim/issues/10106)

If logos of the same type can be aligned in the same column, it will enhance the visual experience, so I am looking forward to this feature being supported, thanks!

**Comment by lewis6991** [comment] 2024-07-15 07:55
Duplicate of #10106

**Closed** 2024-07-15 07:56 UTC
Labels: enhancement, column
