### ISSUE TITLE
NeoVim behaves as if keys were pressed on refocusing terminal window in macOS

### ISSUE THREAD

**Issue by starteleport** [neovim/neovim#31305] opened 2024-11-22 10:05 UTC
### Problem

Is reproduced on latest stable (0.10.2_1): No
Is reproduced on master: Yes

Terminal: iTerm2 3.5.10, not reproducible in macOS built-in terminal

### Steps to reproduce

Steps to reproduce:
- Run `nvim --clean`
- cmd+tab away from the terminal window
- cmd+tab back to the terminal window

Actual result:
- 3650 is printed in the lower-right corner (aka key preview) as if the keys were actually pressed

### Expected behavior

Expected result:
- No keys are "pressed"

### Nvim version (nvim -v)

v0.11.0-dev-5721+g6e44a6a289-Homebrew

### Vim (not Nvim) behaves the same?

no

### Operating system/version

15.1.1 (24B91)

### Terminal name/version

iTerm2 3.5.10

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment] 2024-11-22 10:09
Duplicate of #31122

**Closed by zeertzjq** 2024-11-22 10:09 UTC
Labels: bug
