### ISSUE TITLE
<C-j> as `wildchar`

### ISSUE THREAD

**Issue by monkoose** [neovim/neovim#11042] opened 2019-09-17 11:10 UTC
- `nvim --version`: 0.4.2

### Actual behaviour
Right now you can't set `<C-j>` as wildchar and even after setting it, `C-j` press still acts like `return`. Is it possible to fix this? Terminal emulator limitation? Tested in different terminal emulators.
`set wildchar?` returns `wildchar=<NL>`
### Expected behaviour
`set wildchar=<C-j>`
in your config should acts like `tab` press in default config and popup menu should appear when you press `C-j` in command line.

**Comment by bfredl** [comment] 2019-09-17 11:16
We should make this work in terminals that uses the libtermkey encoding at least http://www.leonerd.org.uk/hacks/fixterms/

**Comment by monkoose** [comment] 2019-09-17 11:22
So you can cmap `<C-j>` easily, but can't make it as `wildchar`?
Sounds weird, are you sure it is because terminal emulator limitations?

**Comment by bfredl** [comment] 2019-09-17 11:38
> So you can cmap <C-j> easily, but can't make it as wildchar? Sounds weird, are you sure it is because of terminal emulator limitations?

What I said is just that we should fix it where it is possible to fix it.

**Comment by monkoose** [comment] 2019-09-17 12:51
Yes, sorry, language barrier.
So i should leave this open, right?

**Comment by bfredl** [comment] 2019-09-17 12:53
Yes.

**Comment by justinmk** [comment] 2019-09-18 04:30
duplicate of https://github.com/neovim/neovim/issues/5916 (which is about distinguishing all of these ambiguous keycodes, not only ctrl-j)

**Comment by bfredl** [comment] 2019-09-18 08:18
But it is not the same issue. Even in terminals where we already recognize `<c-j>` (and it works in a mapping), then `set wildchar=<c-j>` doesn't work.

**Comment by smackesey** [comment] 2020-05-17 16:47
Not sure if this is exactly the same issue but it seems related, so I'll leave it here. Setting `<M-c>` as wildchar produces an error message: `Invalid argument: wildchar=<M-c>`. This is a setting that works fine in Vim.

**Comment by zeertzjq** [comment] 2021-09-20 05:17
A hacky workaround:

```vim
:set wildcharm=<Tab>
:cnoremap <C-J> <Tab>
```

Or if you want to use `<Tab>` for something else:

```vim
:set wildchar=<Help> " Not sure if this is necessary
:set wildcharm=<Help>
:cnoremap <C-J> <Help>
```

**Comment by zeertzjq** [comment] 2021-09-20 05:56
Also this is completely unrelated to terminal. `<C-J>` [stops key processing](https://github.com/neovim/neovim/blob/490e09c6d81b9bf52eac7aa146e62b3da2d86579/src/nvim/ex_getln.c#L1344) before it is matched against `wildchar`. IDK whether this is intentional.

**Comment by zeertzjq** [comment] 2021-09-22 00:03
> Not sure if this is exactly the same issue but it seems related, so I'll leave it here. Setting `<M-c>` as wildchar produces an error message: `Invalid argument: wildchar=<M-c>`. This is a setting that works fine in Vim.

@smackesey That is a separate issue. Maybe you can open another issue for that.

**Comment by justinmk** [comment] 2021-09-22 13:12
This Vim limitation is now documented: https://github.com/neovim/neovim/pull/15753/files#diff-442131dbc53d601ff38edcc95c73c09272934f92f7cf6601738cc6ceaf8a1e48R6824

**Closed by justinmk** 2021-09-22 13:12 UTC
Labels: documentation, status:has-vim-patch, bug-vim, input, core

**Comment by zeertzjq** [comment] 2023-07-10 11:09
Mapping to `<C-Z>` also works in Nvim.
