### ISSUE TITLE
Add an option to specify soft-wrapping width

### ISSUE THREAD

**Issue by cbarrete** [neovim/neovim#25996] opened 2023-11-11 22:34 UTC
### Problem

There is currently no way to set the width at which text is wrapped when `'wrap'` is set: the text is wrapped when it hits the edge of the window, which can be impractical when dealing with wide windows.
Wrapping at a given column can be achieved by setting `'textwidth'`, but this is not always desirable/possible: there might be rules or convention in place for a document, and it makes edits much more annoying and noisy, especially when version control is involved.

### Expected behavior

I'd like to introduce a new option (name to be determined) or just re-purpose `'textwidth'` when `'wrap'` is enabled to allow soft-wrapping text at a given column/width.
If this feature is deemed acceptable, I'm happy to give implementing it a shot, but I'd appreciate some pointers on how to best implement it.

The behavior when the window is narrower than the wrapping width remains to be determined: I suggest not wrapping any trailing characters, as if `'wrap'` was disabled, but we could also wrap them like e.g. Neomutt does. The behavior could also be configurable (which would require more discussion of the name of the options to be introduced/repurposed, but this is just bikeshedding).

I don't know of other text editors that implement a similar feature, but Neomutt's  pager does something very similar via its `wrap` and `reflow_wrap` configuration variables.

**Comment by zeertzjq** [comment] 2023-11-11 23:31
Duplicate of #4386

**Closed by zeertzjq** 2023-11-11 23:31 UTC
Labels: enhancement

**Comment by tyalie** [comment] 2024-03-04 02:22
Okay but the duplicated issue has been closed, so that only collaborators can add something. I would suggest opening this one again

**Comment by tyalie** [comment] 2024-03-07 01:17
Just wanna chime in and point to the [rickhowe/wrapwidth][wrapwidth] plugin which uses new APIs introduced with vim 9 and neovim 10 to implement exactly this feature. See also the issue https://github.com/vim/vim/issues/1847

[wrapwidth]: https://github.com/rickhowe/wrapwidth
