### ISSUE TITLE
Open a file at line number

### ISSUE THREAD

**Issue by mattyw** [neovim/neovim#2174] opened 2015-03-17 19:32 UTC
vim supports opening a file at a certain line number:
```
vim +27 foobar.py
```

It's fairly common for programs to output file and line numbers as foobar.py:27

It would be nice if neovim supported this as a command line
```
nvim foobar.py:27
```

**Comment by Pyrohh** [comment] 2015-03-17 19:35
Looks like a dupe of #1281

**Closed** 2015-03-17 19:58 UTC
