### ISSUE TITLE
Neovim freezes when trying to edit macro with Ultisnips installed

### ISSUE THREAD

**Issue by medwatt** [neovim/neovim#12901] opened 2020-09-12 14:26 UTC
- `nvim --version`: 0.5.0-675
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Windows 10
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

- Make sure that Ultisnips plugin is installed
- Record a macro that has an internal keycode such as <80>kb for backspace
- Paste content of the register that contains the macro into an empty line so that the macro can be edit
- Position the cursor to the end of the keycode while in insert mode and press backspace to delete the keycode

### Actual behaviour

Doing the above steps will cause neovim to freeze. Disabling ultisnips will make the issue go away. So, this seems to be an issue with using the backspace inside neovim with ultisnips installed.

### Expected behaviour

This behaviour is not observed in vanilla vim. Vanilla vim doesn't freeze even with Ultisnips installed.

**Comment by erw7** [comment] 2020-09-12 19:10
Duplicate of #12293, #12386.

**Closed by erw7** 2020-09-12 19:10 UTC
Labels: bug, duplicate
