### ISSUE TITLE
crash in frame2win()

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#25364] opened 2023-09-25 15:05 UTC
### Problem

```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   nvim    0x10cdb07cc frame2win + 12 (window.c:3489)
1   nvim    0x10cda8758 winframe_remove + 152 (window.c:3287)
2   nvim    0x10cdb0dd0 win_free_mem + 112 (window.c:3197)
3   nvim    0x10cdb0308 win_close_othertab + 984 (window.c:3176)
4   nvim    0x10cdafed8 close_windows + 424 (window.c:2612)
5   nvim    0x10ca38ec4 do_buffer + 1924 (buffer.c:1356)
6   nvim    0x10ca3a27f do_bufdel + 255 (buffer.c:1064)
7   nvim    0x10cb29670 ex_bunload + 112 (ex_docmd.c:4303)
8   nvim    0x10cb22bc0 execute_cmd0 + 880 (ex_docmd.c:1634)
9   nvim    0x10cb22583 execute_cmd + 835 (ex_docmd.c:1712)
10  nvim    0x10c9da53e nvim_cmd + 5870 (command.c:659)
11  nvim    0x10c9ba3e8 nlua_api_nvim_cmd + 392 (lua_api_c_bindings.generated.c:1607)
12  nvim    0x10ce3a2c6 lj_BC_FUNCC + 68
```

### Steps to reproduce

Current minimal steps require "satellite" plugin + `foldlevelstart=99`:

1. `issue.lua` : 
   ```
   for name, info in pairs{
     plugin1 = { url= 'https://github.com/lewis6991/satellite.nvim', commit = '542e856b3a727ce4757250cc00e45332fe146690' },
   } do
     local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
     if vim.fn.isdirectory(install_path) == 0 then
       vim.fn.system { 'git', 'clone', info.url, install_path }
       vim.fn.system { 'git', 'reset', '--hard', info.commit }
     end
     vim.opt.runtimepath:append(install_path)
   end
   require('satellite').setup()
   vim.cmd'set foldlevelstart=99'
   ```
2. start Nvim with `issue.lua`
   ```
   ./build/bin/nvim --clean -u issue.lua +'che nvim' +'call nvim_input(":che lsp")'
   ```
3. hit enter to invoke `:che lsp`

### Expected behavior

no crash plz

### Neovim version (nvim -v)

b3be7b741386

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos

### Terminal name/version

Terminal.app

### $TERM environment variable

screen-256color (in tmux)

### Installation

source

**Comment by zeertzjq** [comment] 2023-09-25 15:08
I think this is a duplicate of an existing issue

**Comment by zeertzjq** [comment] 2023-09-25 15:09
Likely #21409

**Comment by zeertzjq** [comment] 2023-09-25 15:10
Duplicate of #21409

**Closed by zeertzjq** 2023-09-25 15:10 UTC
Labels: has:repro, bug-crash

**Comment by justinmk** [comment] 2023-09-25 15:13
Minimal repro: https://github.com/neovim/neovim/issues/21409#issuecomment-1351022340
