### ISSUE TITLE
vim / neovim - autocomplete stop working after seven repetitions

### ISSUE THREAD

**Issue by ardaij** [neovim/neovim#15067] opened 2021-07-12 11:35 UTC
I use vim / nvim as editor. The code to completion working.
But if something happens seven times in a program, this stopped working.

For example:

import cadquery as cq
part = (cq.Workplane("XY")
.circle(10)
.extrude(10)
.faces(">Z")
.circle(10)
.extrude(10)
.faces(">Z")
.circle(10)
.extrude(10)
.faces(">Z")
.circle(10)
.extrude(10)
.faces(">Z")
.circle(10)
.extrude(10)
.faces(">Z")
.circle(10)
.extrude(10)
.faces(">Z")
.circle(10)
)

After the seventh ".circle()", (or seventh .lineTo(), etc. ) the code completion stop working.
I tried this with several add-ons, always the same result.

"davidhalter/jedi-vim", "ncm2/ncm2-jedi"

I thought this was a cadquery bug, I reported this problem on the cadquery (CadQuery/cadquery#823).
I received this answer:

"This is not a CadQuery problem. You probably should report this to vim/nvim developers or to developers of whatever auto-completion plugin you are using with it."

Could this be a vim / neovim or ncm2-Jedi question?

**Comment by clason** [comment] 2021-07-12 11:39
"This is not a neovim problem. You probably should report this to the developers of ncm2-Jedi." ;)

Seriously, though, since you are not using neovim's built-in (manual, omni-)completion, the first point of contact is always the autocomplete plugin. You should also add _exact_ repeating steps (what is your exact -- minimal! -- config to reproduce this? which keys are you entering exactly?).

I'll close this for now, but feel free to reopen (after adding these steps) if(!) the ncm2 devs conclude that this is not in fact an issue with their plugin (or your config).

**Closed by clason** 2021-07-12 11:39 UTC
Labels: bug
