### ISSUE TITLE
Please consider adding support for the XDG Base Directory spec

### ISSUE THREAD

**Issue by mtglsk** [neovim/neovim#1904] opened 2015-01-28 14:03 UTC
Vim should source vimrc from the $XDG_CONFIG_HOME/vim, temp files in $XDG_CACHE_HOME, etc.

Please look at this: https://tlvince.com/vim-respect-xdg

Of course, it should gracefully fall-back to normal locations, but this check up wouldn't cost much for end users and is a good step for consolidating all the settings into the .config folder for easier migration and cross-compatibility.

**Comment by ZyX-I** [comment] 2015-01-28 14:24
Duplicate of #78. (Also: I do not think there is any reason to fallback.)

**Closed** 2015-01-28 14:24 UTC
Labels: duplicate
