### ISSUE TITLE
Problems with roxterm

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#3245] opened 2015-08-26 10:55 UTC
roxterm has some problem with understanding resizing control sequences (https://github.com/neovim/neovim/pull/3145#issuecomment-132250440, #3048), which causes a brief flickering when starting nvim. In qterminal's case, invoking `nvim` seems to completely break the output, even after nvim has been closed.

In the case of roxterm, this could be a regression, as the problem occurs on Arch Linux with roxterm 3.1.5, but not on an Ubuntu 14.04 system with roxterm 2.8.1. Also in qterminal's case, it would be great if this could be solved upstream. @fmoralesc is there a way to reproduce these problems without nvim, to make reporting this upstream easier? Also, are there other terminals that don't work atm? We should probably add this to https://github.com/neovim/neovim/wiki/Following-HEAD

*Edit:* FWIW, sakura seems like a nice alternative to roxterm. Switched to that for now to get rid of the flickering.

*Edit 2:* qterminal issues have reportedly been fixed.

**Comment by fmoralesc** [comment] 2015-08-26 11:32
To reproduce, just try something like
~~~ sh
$ printf '\e[8;40;100t'
~~~
Both terminals should ignore the control sequence if they don't know what to do with it. qterminal's behavior seems particularly bad, since it resizes the buffer but not the window, breaking all output.

Re: https://www.reddit.com/r/neovim/comments/3efxjf/why_can_i_use_neovim_in_xterm_but_not_in_qterminal/

**Comment by fmoralesc** [comment] 2015-08-26 12:38
Honestly, I would not trust anything that is not vte-based, except for urxvt or xterm itself.

**Comment by jleclanche** [comment] 2015-11-03 22:27
If anyone wants to work on this in qterminal please ping me and I can try help you get through the code, and I'll merge your PR.

https://github.com/qterminal/qtermwidget

**Comment by paulolieuthier** [comment] 2015-11-05 17:45
@fwalch the problem with QTerminal has been fixed. Now moving to neovim as well :smile:.

**Comment by fwalch** [comment] 2015-11-05 18:15
Awesome!

**Comment by justinmk** [comment] 2016-06-20 16:52
Seems like this is external, and mostly fixed. Can we close it?

**Closed** 2016-07-30 15:54 UTC
