### ISSUE TITLE
Stuck in insert mode after bracketed paste. Must kill from other term

### ISSUE THREAD

**Issue by themadsens** [neovim/neovim#12023] opened 2020-03-18 22:43 UTC
- `nvim --version`:
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/config -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/include

- `vim -u DEFAULTS` (version: ) behaves differently?
No

- Operating system/version:
macOS Mojave 10.14.6

- Terminal name/version:
iTerm2 3.1.2

- `$TERM`:
xterm-256color-italic:
```
$ cat xterm-italic.tic
xterm-256color-italic|xterm with 256 colors and italic,
  sitm=\E[3m, ritm=\E[23m,
  use=xterm-256color,
```
### Steps to reproduce using `nvim -u NORC`
Paste text from clipboard in insert mode with CMD-V (System paste shortcut)
Happens intermittently - Maybe 1 in 5

### Actual behaviour
Stuck in insert mode with ^[[201~ at end of pasted text. 
Nothing gets converted. Arrow keys, Function keys, ESC (^[). Everything is inserted literally 

### Expected behaviour
Being able to `<ESC>` out of insert mode ...

### Workaround
Use CTRL-V for paste (And CTRL-C for CTRL-V)
```
inoremap <C-V> <C-R>*
inoremap <C-C> <C-V>
```

**Comment by erw7** [comment] 2020-03-19 10:59
Duplicate of #11699.

**Comment by themadsens** [comment] 2020-03-19 13:06
Indeed it is. Spent quite some time google'ing, but missed this one. Should I close the issue then?

**Comment by erw7** [comment] 2020-03-20 05:21
There is no new information here. I think it is better to close this.

**Closed** 2020-03-20 06:43 UTC
Labels: bug
