### ISSUE TITLE
nvim_buf_delete has no effect when used against the buf showed under the currently focused float win

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#22276] opened 2023-02-16 02:02 UTC
### Describe the bug

when closing the buffer showed under the currently focused float win using vim.api.nvim_buf_delete, seems to be a no-op.

this behavior has not be mentioned in the doc of nvim_buf_delete, nor showed any explicit error messages.

### Steps to reproduce

* nvim --clean +'test.lua'

<details>
<summary>test.lua</summary>

```lua
local api = vim.api

assert(api.nvim_get_current_buf() == 1)

local bufnr = api.nvim_create_buf(false, true)
local winid = api.nvim_open_win(bufnr, true, { relative = "editor", row = 3, col = 3, width = 12, height = 3 })

assert(api.nvim_get_current_win() == winid)
api.nvim_buf_delete(1, {force = true})

assert(api.nvim_buf_is_valid(1))
```

</details>

### Expected behavior

the window was closed.

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

system package manager

**Comment by zeertzjq** [comment] 2023-02-16 02:17
Duplicate of #20315

**Closed by zeertzjq** 2023-02-16 02:17 UTC
Labels: bug
