### ISSUE TITLE
LSP popup overlapping

### ISSUE THREAD

**Issue by vanhtuan0409** [neovim/neovim#13957] opened 2021-02-17 03:36 UTC
- `nvim --version`: v0.5.0-dev+1089-gdc3ca16a9
- Operating system/version: Arch Linux

### Steps to reproduce using `nvim -u NORC`

- Set config
```
nnoremap <silent> K <cmd>lua vim.lsp.buf.hover()<CR>
autocmd CursorHold <buffer> lua vim.lsp.diagnostic.show_line_diagnostics()
```

- When pressing `K` on an error line, hover popup got overlapped by diagnostic popup

![](https://user-images.githubusercontent.com/8175932/106725909-70b65300-663c-11eb-9b4f-af4d14747ca1.png)

### Expected behaviour
- Only hover popup is visible, diagnostic popup should be cancelled

**Comment by mjlbach** [comment] 2021-03-06 18:05
Isn't this a duplicate of: https://github.com/neovim/neovim/issues/11508?

**Comment by vanhtuan0409** [comment] 2021-03-08 02:27
yeah I think it is duplicated. Can close this issue

**Comment by mjlbach** [comment] 2021-03-08 03:45
Cool, just want to make sure I'm triaging appropriately since I'm assigning myself to the other one. Thanks!

**Closed by mjlbach** 2021-03-08 03:45 UTC
Labels: bug, lsp
