### ISSUE TITLE
occassional crash when starting neovim from alacritty v 0.3.3-rc1

### ISSUE THREAD

**Issue by sanga** [neovim/neovim#10195] opened 2019-06-12 10:12 UTC
```nvim: /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/rbuffer.c:143: rbuffer_consumed: Assertion `count && count <= buf->size' failed.
                                                                                                                                             fish: “vim -u NORC” terminated by signal SIGABRT (Abort)```

- `nvim --version`:
- Vim (version: ) behaves differently?
- Operating system/version: ubuntu 19.04
- Terminal name/version: alacritty 0.3.3-rc1 (0b88b9f)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
Run `nvim -u NORC` from alacritty v 0.3.3-rc1 (0b88b9f). For me, it should crash, within 10-15 tries.

Neovim sometimes gets some garbage chars sent to it during startup. I suppose that may be related e.g. `:0/0/0^G`

**Comment by sanga** [comment] 2019-06-12 10:12
Probably related to https://github.com/neovim/neovim/issues/10131 but that doesn't mention any crashing

**Comment by sanga** [comment] 2019-06-12 10:32
Also repros with TERM=alacritty

**Comment by blueyed** [comment] 2019-06-12 12:32
Can you test this with master, please?

If it happens there still a backtrace would be useful (see https://github.com/neovim/neovim/wiki/Development-tips#debugging).

**Comment by HarmtH** [comment] 2019-06-12 12:55
> Probably related to #10131 but that doesn't mention any crashing

During my bisecting Neovim did crash sometimes on some commits of it, but never on master (even though I started it most times on master)

**Comment by blueyed** [comment] 2019-06-12 13:50
Thanks for the info, closing as duplicate of #10131.

**Closed by blueyed** 2019-06-12 13:50 UTC
Labels: bug-crash
