### ISSUE TITLE
Command-line completion attempt erases last status line

### ISSUE THREAD

**Issue by ds26gte** [neovim/neovim#8689] opened 2018-07-06 02:06 UTC
- `nvim --version`: v0.3.1-dev
- Vim (version: ) behaves differently? Yes, works fine in Vim 8.1.155
- Operating system/version: Ubuntu 18.04
- Terminal name/version: gnome-terminal 3.28.2
- `$TERM`: term-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set wim=list:longest,full
Edit some file(s) so as to have at least one populated status line 
:e<space><tab>
```

### Actual behaviour

The text on the last status line disappears, leaving only the status line's background-color. When the `:e` command is completed, the status line text is restored.

### Expected behaviour

There should be no erasure of text on the status lines ever.

**Comment by jamessan** [comment] 2018-07-06 10:49
Duplicate of #8611

**Closed by jamessan** 2018-07-06 10:49 UTC
