### ISSUE TITLE
snippet.jump doesnt stop when $0 is tight next to a placeholder/tabstop

### ISSUE THREAD

**Issue by Rishabh672003** [neovim/neovim#31152] opened 2024-11-10 06:03 UTC
### Problem

As can be seen in the screencast when the $0 is right next to the placeholder, same behaviour also happens with just tabstops

https://github.com/user-attachments/assets/4c154296-696c-490f-a673-e2df81ece38d

### Steps to reproduce

1. make a repro.lua
2. paste the following
```lua
vim.keymap.set({ 'i', 's' }, '<Tab>', function()
   if vim.snippet.active({ direction = 1 }) then
     return '<Cmd>lua vim.snippet.jump(1)<CR>'
   else
     return '<Tab>'
   end
end, { expr = true })

vim.keymap.set('i', '<C-;>', function ()
  vim.snippet.expand('var ${1:name} ${2:type}$0')
end)
vim.keymap.set('i', '<C-S-;>', function ()
  vim.snippet.expand('var ${1:name} ${2:type} $0')
end)
```
3. run with `nvim --clean -u random.lua random.lua`
4. press `<C-;>` and the keep press tabbing

### Expected behavior

After encountering $0, the snippet shouldn't be active and it should just tab

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1123+g0eae0bc804

### Vim (not Nvim) behaves the same?

no (doesnt have this functionality)

### Operating system/version

Arch Linux

### Terminal name/version

Ghostty 0.1.0-main+e7ccc60e

### $TERM environment variable

xterm-ghostty

### Installation

bob

**Comment by Rishabh672003** [comment] 2024-11-13 17:22
this also causes a weird bug in rare cases when if keep pressing tab, it inserts some text of the feedkey in the file 

https://github.com/user-attachments/assets/5ddd1620-34e6-47ed-997f-3a2c61dd1843

**Comment by MariaSolOs** [comment] 2024-11-16 22:54
Looks like a duplicate of https://github.com/neovim/neovim/issues/31028

**Closed** 2024-11-16 22:57 UTC
Labels: bug, snippet
