### ISSUE TITLE
shada.c has a memory leak

### ISSUE THREAD

**Issue by dundargoc** [neovim/neovim#17506] opened 2022-02-23 11:34 UTC
### Neovim version (nvim -v)

NVIM v0.7.0-dev

### Vim (not Nvim) behaves the same?

No

### Operating system/version

20.04.1-Ubuntu

### Terminal name/version

kitty

### $TERM environment variable

screen-256color

### Installation

Apt through PPA

### How to reproduce the issue

`valgrind nvim`

### Expected behavior

No memory leaks.

### Actual behavior

Memory leaks.

**Comment by jamessan** [comment] 2022-02-23 11:43
Why not attach the valgrind logs showing the issue you're hitting?

**Comment by dundargoc** [comment] 2022-02-23 11:45
```
==140385== 2,737 bytes in 73 blocks are definitely lost in loss record 498 of 581
==140385==    at 0x4A3A154: malloc (in /home/linuxbrew/.linuxbrew/Cellar/valgrind/3.18.1/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==140385==    by 0x351D9A: try_malloc (memory.c:73)
==140385==    by 0x351E15: xmalloc (memory.c:107)
==140385==    by 0x352030: xmallocz (memory.c:186)
==140385==    by 0x352068: xmemdupz (memory.c:204)
==140385==    by 0x42C4C7: shada_read_next_item (shada.c:3646)
==140385==    by 0x42692E: shada_read_when_writing (shada.c:2055)
==140385==    by 0x4289CB: shada_write (shada.c:2789)
==140385==    by 0x42A5DB: shada_write_file (shada.c:3045)
==140385==    by 0x327A2A: getout (main.c:668)
==140385==    by 0x2B80BB: ex_quit (ex_docmd.c:6639)
==140385==    by 0x2AD706: do_one_cmd (ex_docmd.c:1975)
```

**Comment by seandewar** [comment] 2022-02-23 12:17
the leak on exit is pretty well known #8223
is this the only leak you're hitting?

**Comment by dundargoc** [comment] 2022-02-23 12:37
Yes.

**Comment by seandewar** [comment] 2022-02-23 13:04
best to mark this as a duplicate of #8223 :+1:

**Closed by seandewar** 2022-02-23 13:04 UTC
Labels: bug
