### ISSUE TITLE
nvim_open_win behaves oddly when using bufpos outside the buffer text

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#23120] opened 2023-04-16 06:49 UTC
### Problem

When `bufpos` is set to a value outside the text of the buffer, the window is positioned oddly.

### Steps to reproduce

Save the following lua script, then open a clean Neovim and source it.
```
vim.api.nvim_open_win(vim.api.nvim_create_buf(false, true), 0, {
  relative = "win",
  width = 10,
  height = 5,
  bufpos = { 3, 3 },
  row = 0,
  col = 0,
  style = "minimal",
  border = "single"
})
```

### Expected behavior

Either an error because `bufpos` is out of range, or the window to appear in the top-left corner. Instead, the window appears in the bottom-left corner.

### Neovim version (nvim -v)

v0.10.0-dev-75+gc2e47e7be

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Rocky Linux 8.6

### Terminal name/version

xfce4-terminal 1.0.4

### $TERM environment variable

tmux-256color

### Installation

appimage

**Comment by zeertzjq** [comment] 2023-04-16 06:57
A ml_get error also happens when buffer has 3 lines and the last line is deleted.

**Comment by zeertzjq** [comment] 2023-08-19 22:51
I think it should behave as if bufpos is at last buffer line instead.

**Comment by glepnir** [comment] 2023-09-14 10:08
seems like fixed on master ? I can't reproduce this with clean -u

**Closed** 2024-04-22 11:31 UTC
Labels: bug, api, ui, float
