### ISSUE TITLE
Extra spacing around LSP Hover Buffer

### ISSUE THREAD

**Issue by Juhan280** [neovim/neovim#29459] opened 2024-06-23 10:58 UTC
### Problem

I have recently updated neovim from v0.9 to v0.10. Everything is fine except this one particular thing.

Whenever I call lsp hover, I see extra blank lines around the codeblock. I know that this isn't that big of a deal, but i like it being compact, especially because I also use neovim on my phone and those extra lines look ugly on the small screen.

Here is a screenshot from v0.10.0
![2024-06-23-163913_hyprshot](https://github.com/neovim/neovim/assets/92646057/7aca2141-3b16-4db5-9f31-cac2f91793f5)

I discovered that those extra lines come from the backtics of markdown codeblocks.
![2024-06-23-163919_hyprshot](https://github.com/neovim/neovim/assets/92646057/b132d13d-3e00-4ccd-a949-bfabb70bd0b2)
![2024-06-23-163925_hyprshot](https://github.com/neovim/neovim/assets/92646057/145010d2-ba54-4210-b9a4-0c00d73f8c97)

### Steps to reproduce

```lua
-- Run this file as `nvim --clean -u minimal.lua`

for name, url in pairs {
    lspconfig = "https://github.com/neovim/nvim-lspconfig",
    treesitter = "https://github.com/nvim-treesitter/nvim-treesitter"
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

vim.lsp.handlers["textDocument/hover"] = vim.lsp.with(vim.lsp.handlers.hover, {
    border = "rounded",
})

require("nvim-treesitter.configs").setup({
    ensure_installed = {"lua", "markdown"}
})
require("lspconfig").lua_ls.setup({})
```

### Expected behavior

Like neovim v0.9.x
A screenshot from v0.9.5:
![2024-06-23-163841_hyprshot](https://github.com/neovim/neovim/assets/92646057/f39f9936-e9ee-427f-8bf2-d9c973773dcc)

### Neovim version (nvim -v)

NVIM v0.10.0; Build type: Release; LuaJIT 2.1.1716656478

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

pacman -S neovim

**Comment by clason** [comment] 2024-06-23 10:59
Duplicate of https://github.com/neovim/neovim/issues/25718

**Closed by clason** 2024-06-23 10:59 UTC
Labels: bug, lsp
