### ISSUE TITLE
Crashes when pasting from clipboard

### ISSUE THREAD

**Issue by mick-io** [neovim/neovim#11505] opened 2019-12-02 19:39 UTC
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? Yes, I'm able to paste from the clipboard
- Operating system/version: macOS Catalina Version 10.15.1
- Terminal name/version: Iterm2 3.3.7
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
- Paste text with `command` + `p`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
- The following should appear near the pasted text: "Vim: Finished."
- The following should appear near the editor command-line: "E970: Failed to initialize lua interpreter"

### Expected behaviour
The text should be added to the current buffer without any issue.

<img width="652" alt="Screen Shot 2019-12-02 at 12 38 53 PM" src="https://user-images.githubusercontent.com/23181878/69989376-b7706080-1500-11ea-823a-61bb46a32418.png">

**Comment by justinmk** [comment] 2019-12-02 21:27
I can't reproduce this (of course). To get visibility into the actual error, please add the following to your init.vim (vimrc):

```
lua << EOF
vim.paste = (function(overridden)
  local tdots, tick, got_line1 = 0, 0, false
  return function(lines, phase)
    local call = vim.api.nvim_call_function
    local now = vim.loop.now()        
    local mode = call('mode', {}):sub(1,1)  
    if phase < 2 then  -- Reset flags.
      tdots, tick, got_line1 = now, 0, false
    elseif mode ~= 'c' then
      vim.api.nvim_command('undojoin')
    end
    if mode == 'c' and not got_line1 then  -- cmdline-mode: paste only 1 line.
      got_line1 = (#lines > 1)
      vim.api.nvim_set_option('paste', true)  -- For nvim_input().
      local line1 = lines[1]:gsub('<', '<lt>'):gsub('[\r\n\012\027]', ' ')  -- Scrub.
      vim.api.nvim_input(line1)
      vim.api.nvim_set_option('paste', false)
    elseif mode ~= 'c' then
      if phase < 2 and mode:find('^[vV\22sS\19]') then
        vim.api.nvim_command([[exe "normal! \<Del>"]])
        vim.api.nvim_put(lines, 'c', false, true)
      elseif phase < 2 and not mode:find('^[iRt]') then
        vim.api.nvim_put(lines, 'c', true, true)
        -- XXX: Normal-mode: workaround bad cursor-placement after first chunk.
        vim.api.nvim_command('normal! a')
      else
        vim.api.nvim_put(lines, 'c', false, true)
      end
    end
    if phase ~= -1 and (now - tdots >= 100) then
      local dots = ('.'):rep(tick % 4)
      tdots = now
      tick = tick + 1
      -- Use :echo because Lua print('') is a no-op, and we want to clear the
      -- message when there are zero dots.
      vim.api.nvim_command(('echo "%s"'):format(dots))
    end
    if phase == -1 or phase == 3 then
      vim.api.nvim_command('redraw'..(tick > 1 and '|echo ""' or ''))
    end
    return true  -- Paste will not continue if not returning `true`.
  end
end)(vim.paste)
EOF
```

Then restart Nvim and try pasting with cmd+v. Report the exact error here.

Also:

- How did you build or get Nvim, exactly?
- Can you check if the error is also present on the development version (0.5): The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. You don't need to install anything. Just download/unzip.

**Comment by ratmav** [comment] 2019-12-04 16:18
@justinmk i've run into this myself, but when i copy that snippet into my `init.vim` and restart, i get `E970: Failed to initialize lua interpreter`. i've been searching around the web, but i'm not finding a lot of information on how to correct or work around that error. is there some dependency i need to install with `brew` or something?

idk about the op, but i got nvim via homebrew. when i pull the nightly form the releases page, i don't get this error. so, it looks like it's a bug in the version homebrew is pulling. here's what i have for the homebrew version:

```shell
[user@host ~]$ nvim --version
NVIM v0.4.3
Build type: Release
/Users/user
Vim: Finished.
E970: Failed to initialize lua interpreter
```
note that this hangs, with that same E970 warning.

the nightly:
```shell
[user@host Downloads]$ ./nvim-osx64/bin/nvim --version
NVIM v0.5.0-226-gb1e4ec1c2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

since the nightly doesn't hang with the E970 warning, i suspect that the [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/neovim.rb) isn't building with the same lua support as the nightly builds.  actually, reading over it, it looks like the formula is building locally v. pulling the binaries from travis. perhaps it could be useful to change that behavior?

at any rate, since this isn't an issue in 0.5.0, i suspect it's just a matter of time until the formula is updated and this becomes a non issue. it's a pita right now, but i can work around it by using `p` in normal mode v. `Cmd+p` in insert mode. it may also be relevant that my setup also uses tmux and the [tmux-yank](https://github.com/tmux-plugins/tmux-yank) plugin*, so nvim, tmux, and macos are all touching the system clipboard (it may also be irrelevant, i'm just erring on the side of max detail because bug).

**Comment by mick-io** [comment] 2019-12-04 17:13
@justinmk I cleared out my _init.vim_ file and added the script you supplied. After making those changing, I launch Neovim and the follow **immediately** appeared:

```
ERROR detected while processing /Users/mick/.config/nvim/init.vim:
line   45:
E970: Failed to initialize lua interpreterVim: Finished.

Press ENTER or type command to continue
```

- I installed Neovim via _Homebrew_
- The nightly version (NVIM v0.5.0-226-gb1e4ec1c2) seems to have fixed the paste-and-crash problem. Do you have any idea how long it will be till the nightly version to become the stable?

**Comment by justinmk** [comment] 2019-12-05 07:29
> since this isn't an issue in 0.5.0, i suspect it's just a matter of time until the formula is updated and this becomes a non issue

It works in 0.4.3 for me.

I'm not convinced that 0.5 fixes the issue, we haven't found the root cause. Pleas try this smaller version:

```
lua << EOF
vim.paste = (function(overridden)
  return function(lines, phase)
    vim.api.nvim_put({'line1', 'line2', ''}, 'c', false, true)
    return true
  end
end)(vim.paste)
EOF
```

Then when you paste with cmd+c, it should insert the literal strings "line1" and "line2". Does that work?

**Comment by justinmk** [comment] 2019-12-05 07:34
> when i pull the nightly form the releases page, i don't get this error. so, it looks like it's a bug in the version homebrew is pulling

Does Lua work at all? What happens when you do this from Nvim cmdline:

    :lua print('hello\n')

> it looks like the formula is building locally v. pulling the binaries from travis. perhaps it could be useful to change that behavior?

It's better that homebrew builds rather than depending on us to build something on CI. And 0.4.3 from homebrew works for me on macOS, so this is not really the problem.

**Comment by bfredl** [comment] 2019-12-05 18:12
> Operating system/version: macOS Catalina Version 10.15.1

Catalina has been know to be a problem with earlier luajit builds. Is the 0.4.3 from homebrew patched to support Catalina?

**Comment by thomasbecker** [comment] 2019-12-09 11:18
> Does Lua work at all? What happens when you do this from Nvim cmdline:
> 
> ```
> :lua print('hello\n')
> ```
I'm having the same problem. neovim crashes when pasting any content from the clipboard on catalina. To answer the question: The simple lua print crashes neovim as well.

Let me know if I can provide any further info that will help resolving this.

**Comment by thomasbecker** [comment] 2019-12-09 15:22
It's already fixed in luajit. Simply do a `brew reinstall luajit` to fix it.

**Closed** 2019-12-09 18:00 UTC
Labels: bug, clipboard, platform:macos, revisit-at-release, waiting-for-repro, waiting-on-author
