### ISSUE TITLE
With vim-github-dashboard, after run GHD command, cursor position is wrong.

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#5085] opened 2016-07-18 16:43 UTC
- `nvim --version`: master
- Vim (version: ) behaves differently? yes
- Operating system/version: arch
- Terminal name/version: termite
- `$TERM`: xterm-termite

### Actual behaviour
in neovim, after run `:GHD! wsdjeg`,there is extra empty line at the begin of new tab, the cursor position is wrong. the cursor it at the end of the buffer, but in vim it is at the begining of the buffer.
### Expected behaviour
same as vim, the cursor position should be at the first line.

I have install neovim successfuny , and `:ruby puts 1` show `1` in cmdline, I think the ruby support has been install successfuly.

**Comment by justinmk** [comment] 2016-07-31 05:40
@alexgenco Does this seem like a problem with the ruby provider ? Or an nvim problem?

**Comment by alexgenco** [comment] 2016-07-31 23:34
I can't reproduce this exact issue... but when I tried on my version of nvim (v0.1.5-611-gdcbd1c7) it put the cursor on the last line (below `-- MORE --`), rather than at the top. It also introduced some strange redraw behavior when I hovered over "links" that is hard to describe, but seems to have to do with paren match highlighting (shown in gif).

I'll dig a little deeper later tonight.

![tty](https://cloud.githubusercontent.com/assets/566993/17280080/1401ef02-573c-11e6-9c51-d2aa38ea1aee.gif)

**Comment by alexgenco** [comment] 2016-08-01 03:22
Opened an issue for the redraw issue: https://github.com/neovim/neovim/issues/5149.

Still digging into the cause of the cursor going to the end of the buffer.

**Comment by alexgenco** [comment] 2016-08-02 03:38
I think I figured it out. Calling `Buffer#append` has different cursor behavior in nvim vs. vim. When you append a line _above_ the cursor, nvim moves the cursor down one line, while vim keeps it on the same line. If this is the intended behavior, adding a workaround to the gem won't be too bad. Otherwise, this will need to be fixed in nvim. @justinmk thoughts?

**Comment by justinmk** [comment] 2016-08-02 13:38
@bfredl does that seem plausible?

**Comment by bfredl** [comment] 2016-08-03 14:11
Not sure i follow. If you mean buffer_set_lines (buffer_insert is a deprecated alias ) increments the cursor line number so that the cursor stays on the _same_ line then then that it is the intended behavior of the set_lines api function, if not it is a bug. If the ruby vim interface behaves differently it  will need to adjust it. (I'm on a metered mobile connection now, but I can check this myself in 1-2 days when i'm back to my computer)

**Comment by alexgenco** [comment] 2016-08-03 17:12
@bfredl Yes, the cursor shifts down to accommodate the new line. Sounds like that's intended, so I'll figure out a workaround, probably this: https://github.com/alexgenco/neovim-ruby/pull/14.

**Comment by alexgenco** [comment] 2016-08-05 00:45
I just merged that PR. @wsdjeg do you want to try building neovim-ruby from master and see if it resolves the problem? You can just clone it down and run `rake install`. I'll push to RubyGems if things look good.

**Comment by wsdjeg** [comment] 2016-08-05 00:53
@lexgenco I will do it tonight, thanks for your help.

**Comment by wsdjeg** [comment] 2016-08-07 01:34
@alexgenco This patch works well for me.

**Closed** 2016-08-07 01:57 UTC
Labels: bug

**Comment by alexgenco** [comment] 2016-08-07 02:15
[v0.2.4 pushed to RubyGems](https://rubygems.org/gems/neovim/versions/0.2.4). Thanks all
