### ISSUE TITLE
relativenumber and cursorline slows down vim on zsh files

### ISSUE THREAD

**Issue by ii14** [neovim/neovim#14154] opened 2021-03-17 23:23 UTC
- `nvim --version`:
```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-nuv1vj/neovim-0.5.0+ubuntu2+git202103140419-314b222c2-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-nuv1vj/neovim-0.5.0+ubuntu2+git202103140419-314b222c2-d569569c9/build/config -I/build/neovim-nuv1vj/neovim-0.5.0+ubuntu2+git202103140419-314b222c2-d569569c9/src -I/build/neovim-nuv1vj/neovim-0.5.0+ubuntu2+git202103140419-314b222c2-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-nuv1vj/neovim-0.5.0+ubuntu2+git202103140419-314b222c2-d569569c9/build/src/nvim/auto -I/build/neovim-nuv1vj/neovim-0.5.0+ubuntu2+git202103140419-314b222c2-d569569c9/build/include
Compiled by buildd@lcy01-amd64-026

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 13 2020 15:49:09)
```
No. As far as I can tell, it's even worse on vim8.0. But it's before the 8.1.0372 patch, that was merged to neovim in #8986 and was supposed to fix the issue. I don't have any newer version of vim installed to check if it's fixed there.

- Operating system/version:
```
Linux 5.4.0-62-generic #70~18.04.1-Ubuntu SMP Tue Jan 12 17:18:00 UTC 2021 x86_64 x86_64 GNU/Linux
```

- Terminal name/version, `$TERM`:

`alacritty 0.8.0-dev (c566f78)` - `xterm-256color`
`st` - `st-256color`
`kitty 0.18.3` - `xterm-kitty`

### Steps to reproduce using `nvim -u NORC`

Create a `test.zsh` file:
```zsh
# vim: relativenumber cursorline
setopt list_packed              # lorem ipsum dolor sit amet
setopt auto_cd                  # lorem ipsum dolor sit amet
setopt notify                   # lorem ipsum dolor sit amet
setopt no_flow_control          # lorem ipsum dolor sit amet
setopt interactive_comments     # lorem ipsum dolor sit amet
setopt noclobber                # lorem ipsum dolor sit amet
setopt append_history		# lorem ipsum dolor sit amet
setopt share_history            # lorem ipsum dolor sit amet
setopt hist_ignore_all_dups     # lorem ipsum dolor sit amet
setopt hist_ignore_space        # lorem ipsum dolor sit amet
setopt auto_pushd               # lorem ipsum dolor sit amet
setopt pushd_minus              # lorem ipsum dolor sit amet
setopt pushd_silent             # lorem ipsum dolor sit amet
setopt pushd_to_home            # lorem ipsum dolor sit amet
setopt list_packed              # lorem ipsum dolor sit amet
setopt auto_cd                  # lorem ipsum dolor sit amet
setopt notify                   # lorem ipsum dolor sit amet
setopt no_flow_control          # lorem ipsum dolor sit amet
setopt interactive_comments     # lorem ipsum dolor sit amet
setopt noclobber                # lorem ipsum dolor sit amet
setopt append_history		# lorem ipsum dolor sit amet
setopt share_history            # lorem ipsum dolor sit amet
setopt hist_ignore_all_dups     # lorem ipsum dolor sit amet
setopt hist_ignore_space        # lorem ipsum dolor sit amet
setopt auto_pushd               # lorem ipsum dolor sit amet
setopt pushd_minus              # lorem ipsum dolor sit amet
setopt pushd_silent             # lorem ipsum dolor sit amet
setopt pushd_to_home            # lorem ipsum dolor sit amet
setopt list_packed              # lorem ipsum dolor sit amet
setopt auto_cd                  # lorem ipsum dolor sit amet
setopt notify                   # lorem ipsum dolor sit amet
setopt no_flow_control          # lorem ipsum dolor sit amet
setopt interactive_comments     # lorem ipsum dolor sit amet
setopt noclobber                # lorem ipsum dolor sit amet
setopt append_history		# lorem ipsum dolor sit amet
setopt share_history            # lorem ipsum dolor sit amet
setopt hist_ignore_all_dups     # lorem ipsum dolor sit amet
setopt hist_ignore_space        # lorem ipsum dolor sit amet
setopt auto_pushd               # lorem ipsum dolor sit amet
setopt pushd_minus              # lorem ipsum dolor sit amet
setopt pushd_silent             # lorem ipsum dolor sit amet
setopt pushd_to_home            # lorem ipsum dolor sit amet
```

Open with nvim:
```sh
nvim -u NORC --noplugin test.zsh
```

If modeline doesn't work for some reason:
```vim
:set relativenumber cursorline
```

...and try to type some text in insert mode.

### Actual behaviour
Enabling `relativenumber` or `cursorline` option on a zsh file with a lot of `setopt` statements makes everything really slow, particularly inserting text. Works just fine when these options are turned off. Having just `number` enabled also doesn't cause any issues.

### Expected behaviour
It should be fast.

**Comment by klooj** [comment] 2021-03-29 10:17
I play around with zsh way too much and was super skeptical of this issue, so I tried and was actually able to reproduce ... kinda. mixed bag of results:
1. with relativenumber & cursorline but no rc and no plugins, i cannot reproduce at all. 
2. BUT there is a heavy lag when opening the file with my normal  config. It seemed somewhat related to highlighting all occurrences of the word under the cursor, and setopt is the first word on every line... in other words a rendering bottleneck. 
3. BUT, the lag persists even when opening in a gui, which militates against the rendering bottleneck of a terminal emulator.  

Zsh is a little quirky with tree-sitter and bashls (known and documented somewhere), which I believe fully explains the lag on my end. But if you have the lag with no plugins and no rc, and you are certain neither treesitter nor lsp are attaching in that circumstance, then you may have a legit issue. good luck.

**Comment by ii14** [comment] 2021-03-29 11:38
Thanks a lot.
My initial tests were on a 2nd generation Intel i5, so a 10 years old CPU. Now I checked it on an "up-to-date" Ryzen CPU and it can handle it pretty well, no lag at all. But if I look at htop, nvim has ~20% CPU usage when I spam a random character in insert mode with relativenumber and cursorline. >25% if fill my entire screen with setopts, 78 lines. Compared to just ~2% without relativenumber or cursorline.

**Comment by 0qq** [comment] 2021-04-07 06:59
I had the same issue with zsh files and the problem was ```foldmethod=syntax```.

**Comment by justinmk** [comment] 2021-07-07 21:30
old, known vim issue. see https://github.com/neovim/neovim/issues/9984

duplicate of https://github.com/neovim/neovim/issues/4736

**Closed by justinmk** 2021-07-07 21:30 UTC
Labels: bug, duplicate, performance
