### ISSUE TITLE
Maximizing NVim with open tabs and tabline=1 partly hides the command area

### ISSUE THREAD

**Issue by the42** [neovim/neovim#11010] opened 2019-09-13 10:28 UTC
- `nvim --version`: v0.4.0-1554
- Operating system/version: Windows 10 64bit
- Terminal name/version: nvim-qt

### Actual behaviour
When I open a :tabnew and maximize nvim using window decoration controls, the increased space occupied by the tab decoration makes the command line partly vanish --> nvim maximizes "to much"

### Expected behaviour
All of nvim remains visible when maximizing with open tabs and set tabline=1

**Comment by bfredl** [comment] 2019-09-13 10:36
duplicate of https://github.com/equalsraf/neovim-qt/issues/523 ?

**Closed by bfredl** 2019-09-13 10:36 UTC
Labels: bug
