### ISSUE TITLE
Option to get rid of "Press ENTER or type command to continue"

### ISSUE THREAD

**Issue by drzhivago420** [neovim/neovim#28762] opened 2024-05-15 20:52 UTC
### Problem

If anyone has tried to update the treesitter parsers with a medium size terminal window, they'll understand the pain.
`:set cmdheight=2 ` is not a desirable solution obviously, if you are not fullscreening the terminal why would you want to get rid of screen real estate.

So yeah I think there's a real need for an option to just not read the whole message, I think most people don't want to have the message stuck in the window, specially with the increasing amount of things that spam like 20 messages at the same time.

### Expected behavior

Proposed solution: something like `:set impatientcmd` or whatever that allows users to opt out of that thing.

**Comment by clason** [comment] 2024-05-15 21:01
Duplicate of #22478

**Closed by clason** 2024-05-15 21:01 UTC
Labels: enhancement
