### ISSUE TITLE
Changing `comments` in ftplugin file does not work

### ISSUE THREAD

**Issue by TheBlob42** [neovim/neovim#24204] opened 2023-06-29 09:58 UTC
### Problem

Changes to the local `comments` option are not properly loaded when inside a `ftplugin` file.

This used to work at some point, but unfortunately I am not aware of the exact version when it changed :grimacing: 

Setting other options in the `ftplugin` file works fine  
(e.g. `vim.opt_local.complete:remove('w')`, `vim.opt_local.buflisted = false`, etc.)

Setting the `comments` option later on (e.g. `:lua vim.opt_local.comments:remove(':--')`) works fine as well

### Steps to reproduce

Create a nvim config with the following structure:
```
.config/nvim/
    └  ftplugin
        └  lua.lua
    └ init.lua
```

`ftplugin/lua.lua` contains:

```lua
print("TEST")
vim.opt_local.comments:remove(':--')
```

`init.lua` does not contain anything

### Expected behavior

- open a lua file with nvim `nvim ~/.config/nvim/init.lua`
- check `:messages` to see that "TEST" is being printed
    - therefore the custom ftplugin file for lua is being loaded
- write a comment then press enter

# Expected

The new line will not start with a comment (`--`)

# Actual

The next line starts with a comment

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Ubuntu

### Terminal name/version

GNOME Terminal 3.36.2

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by clason** [comment] 2023-06-29 10:01
That sounds like a duplicate of #24003. Can you test #24147?

**Comment by TheBlob42** [comment] 2023-06-29 21:24
@justinmk moving my custom ftplugins into `after/plugin/ftplugin` works, thanks for that workaround :slightly_smiling_face: 

I am just a little confused why it worked before in the "non-after" folder.  
Could it be that the comment option was changed in those built in ftplugin files in one of the latest releases?

@clason I am gonna check out the PR you suggested on the weekend and provide you with feedback as soon as I can

**Comment by zeertzjq** [comment] 2023-06-30 01:18
Hmm, this issue appears on v0.9.1, which doesn't contain #23801

**Comment by TheBlob42** [comment] 2023-06-30 08:45
| Version | Issue? |
| --- | --- |
| nightly | yes |
| 0.9.0 | no |
| 0.8.3 | no |

I could not test with #24147 yet but I'll try that as soon as I find the time for compiling it

**Comment by zeertzjq** [comment] 2023-06-30 10:21
The behavior you are expecting is wrong. See `:h ftplugin-overrule`.

**Closed by zeertzjq** 2023-06-30 10:21 UTC
Labels: bug, runtime, needs:response

**Comment by TheBlob42** [comment] 2023-06-30 12:03
Thanks for the clarification. I have indeed misunderstood it and it seems that the former behavior of my configuration was a "bug". Thank you for all the help :+1:
