### ISSUE TITLE
Prompt buffers

### ISSUE THREAD

**Issue by tbodt** [neovim/neovim#10431] opened 2019-07-05 16:29 UTC
Vim supports a type of buffer called a "prompt buffer" specialized for interactive input. Only the last line of the buffer is editable, and pressing enter triggers a callback. This is an important capability for vimspector's watch window, and would be very useful for any type of repl.

https://vimhelp.org/channel.txt.html#prompt-buffer

**Comment by justinmk** [comment] 2019-07-05 19:57
Duplicate of #8805.

see https://github.com/neovim/neovim/issues/8805#issuecomment-409940181

**Closed by justinmk** 2019-07-05 19:57 UTC
Labels: enhancement

**Comment by pianocomposer321** [comment] 2020-07-18 20:49
#8805 is locked, so I'll ask this question here: what would it take to implement this, either for neovim itself and then submit a pull request, or mimic the behavior so that it can be used only for the things that vimspector needs it for?

**Comment by tbodt** [comment] 2020-07-18 20:55
This might have been merged in from upstream vim in #10433

**Comment by pianocomposer321** [comment] 2020-07-18 21:04
@tbodt just notice that that PR was merged to master after the latest (0.4.3) release, so would I have to build from source to utilize this new feature?

**Comment by tbodt** [comment] 2020-07-18 21:04
Looks like it. I don't know when 0.5.0 is planned for.

**Comment by pianocomposer321** [comment] 2020-07-18 21:08
@tbodt ok. Building neovim looks _much_ better than some other projects I've seen, so it shouldn't be too much of an issue. Are there any problems I should be aware of that using the unstable release will cause (that you know of, of course)? I know there are always risks involved with using an unstable release, but if there aren't any problems that will directly affect me, I think I'll go ahead and do it, because the benefits outweigh the risks.

**Comment by pianocomposer321** [comment] 2020-07-18 21:42
@tbodt just built 0.5.0 from source and can confirm that the prompt buffer works (at least with vimspector, I don't see any reason why it wouldn't for anything else).

I'd also like to thank you guys at neovim for such a nicely put together application: not only the program but the simplicity of the build itself. It's so refreshing to be able to just run `make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=$HOME/.local/nvim install` and watch as the program is built in front of your eyes.
