### ISSUE TITLE
Need macOS package signing

### ISSUE THREAD

**Issue by psadi** [neovim/neovim#18887] opened 2022-06-07 05:05 UTC
### Neovim version (nvim -v)

NVIM v0.7.0 Latest

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MacOS Big Sur

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

github releases

### How to reproduce the issue

n/a

### Expected behavior

to open nvim as a binary

### Actual behavior

Unable to run nvim binary as it says developer cannot be verified

<img width="891" alt="Screenshot 2022-06-07 at 10 31 39 AM" src="https://user-images.githubusercontent.com/22428691/172300016-155ff205-7f81-44f8-85af-f3daf33972c1.png">

**Comment by zeertzjq** [comment] 2022-06-07 05:08
Duplicate of #11011

**Closed by zeertzjq** 2022-06-07 05:08 UTC
Labels: bug
