### ISSUE TITLE
lsp: incremental sync breaks with certain multibyte character operations 

### ISSUE THREAD

**Issue by octaltree** [neovim/neovim#14542] opened 2021-05-12 13:34 UTC
- `nvim --version`:
```
NVIM v0.5.0-dev+1318-g61aefaf29
Build type: RelWithDebInfo
LuaJIT 2.0.5
```
- language server name/version: rust-analyzer 9a431c26f 2021-05-12 dev
- Operating system/version: Linux coorie 5.10.34-1-MANJARO #1 SMP Sun May 2 11:29:56 UTC 2021 x86_64 GNU/Linux

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

```vim
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 1
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: tmux-256color

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: pyls: configuration checked.
  - INFO: texlab: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: clangd: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: tsserver: configuration checked.
```

</details>

<details>
<summary>lsp.log</summary>

before blank file
after attached lsp.log
[lsp.log](https://github.com/neovim/neovim/files/6466465/lsp.log)

</details>

### Steps to reproduce using nvim -u minimal_init.lua

<details>
<summary>minimal_init.vim</summary>

```
set runtimepath+=~/.config/nvim/dein/repos/github.com/neovim/nvim-lspconfig
lua require'lspconfig'.rust_analyzer.setup {}

lua vim.lsp.set_log_level('debug')

let g:signature = ''

function! s:fetch_cursor_signature_and_store() abort
  " Request without blocking and use the response next time.
  lua <<EOF
  do
    local cur = vim.lsp.util.make_position_params()
    vim.lsp.buf_request(0, "textDocument/signatureHelp", cur,
      function(err, _method, result, _client_id, _bufnr, _config)
        if type(result) ~= "table" or type(result.signatures) ~= "table" then
          return
        end
        local signature = result.signatures[1]
        if not signature then return end
        -- Discard signature.parameters
        vim.g['signature'] = signature.label
      end)
  end
EOF
endfunction

function! s:on_event() abort
  call s:fetch_cursor_signature_and_store()
  " use g:signature
endfunction

autocmd CursorMovedI * call s:on_event()

lua print(vim.lsp.get_log_path())
```

lspconfig HEAD is
```
*   commit 0a921bf2be74d293c8a8d6dd70122c1d01151a30 (HEAD -> master, origin/master, origin/HEAD): e808cea 7a3e0d1
| | Author: Michael Lingelbach <m.j.lbach@gmail.com>
| | Date:   Fri May 7 15:19:53 2021 -0700
```

</details>

1. Open file
```sh
cargo new hello
cd hello
sed 's/"Hello, world!"/"Hello, world! に対応"/' -i src/main.rs
nvim -u ../minimal_init.vim src/main.rs
```
2. Move cursor on 'に' \u306b
3. Type xcl to remove two chars and insert mode
4. IME On
5. Type "対応" \u5bfe\u5fdc. The line has string "Hello, World! 対応応".
6. I got the client-sided serialization error and was blocked with "Press ENTER or type command to continue"
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:394: Vim:E474: String "<af><be><e5>" contains byte that does not start any UTF-8 character
続けるにはENTERを押すかコマンドを入力してください
```
7. Enter
8. IME Off
9. Esc
10. :q

### Actual behaviour
When sending a signature request, the client tries to notify `textDocument/didChange` just before it. Then the error occurs asynchronously in json_encode and blocks the user interface.

### Expected behaviour
The file you are in the middle of editing is not necessarily valid utf-8. LSP can only send utf-8, but it is not desirable to block the user interface when an error occurs asynchronously and there is no way to catch it.

**Comment by dmitmel** [comment] 2021-07-27 12:34
Hi, I'm having an exact same problem, but have an even smaller reproduction method which does not involve IME:

1. minimal_init.vim
   ```vim
   set runtimepath+=~/nvim-lspconfig
   lua require('lspconfig').pyright.setup {}
   ```
2. something.py
   ```
   print('└─')
   ```
3. `nvim -u minimal_init.vim something.py`
4. Go to the character `└` (`8|`, `gg7l` etc), press `x`
5. Pressing `u` triggers the error.

I believe that neither the choice of a language server (Pyright) nor the HEAD of nvim-lspconfig (neovim/nvim-lspconfig@4f72377143fc0961391fb0e42e751b9f677fca4e) should matter. What's interesting though is that both of the characters in the string are 3-byte when UTF-8-encoded, and the error happens if you try undoing deletion of a 3-byte character followed by another 3-byte character. In other words, if you repeat the same sequence of steps, but with the character `─` at column 9, the bug doesn't occur.

**Comment by dmitmel** [comment] 2021-07-27 12:44
Also I believe that interface blocking is not the main aspect of this bug, as it occurs just because the error message is wrapped into two or more lines on a smaller screen. And I don't think it has something to do with invalid UTF-8 either. I found that disabling incremental text syncing (`setup {flags = {allow_incremental_sync = false}}`) prevents the bug from happening (technically a workaround, but I don't like it), so there must be bug in handling of multibyte characters in incremental syncs.

**Comment by dmitmel** [comment] 2021-07-27 12:54
I did some further digging: it definitely happens in my reproduction case, but not with every other multibyte character (though the repro should be reliable enough), but also the order of encoded bytes, displayed in the error message, is messed up: for Cyrillic characters it is reversed, for example, resulting in invalid UTF-8.

**Comment by dmitmel** [comment] 2021-07-27 16:30
Okay, I have an exact idea of what's wrong. The bug is in the following two functions:

https://github.com/neovim/neovim/blob/a5ac2f45ff84a688a09479f357a9909d5b914294/runtime/lua/vim/lsp/util.lua#L297-L369

The problem? They iterate UTF-8 encoded strings, received from the current buffer, byte-by-byte and not character-by-character. So indeed, the rest of the algorithm works as expected, but it finds sub-character differences, thus breaking UTF-8 encoding. I'm trying to figure out a solution and will submit a PR.

**Comment by clason** [comment] 2021-07-27 16:35
Getting proper multibyte UTF-8 handling (e.g., by exposing neovim's `mbyte.c`) into the Lua API is an urgent need -- otherwise we'll need to keep papering over these problems again and again...

**Comment by clason** [comment] 2021-07-27 16:39
Maybe vendoring https://github.com/meepen/Lua-5.1-UTF-8/blob/master/utf8.lua for the nonce can help until then?

**Comment by dmitmel** [comment] 2021-07-27 16:39
I actually have a few other patches (i.e. monkey-patches, nothing too serious) to LSP-related functions fixing handling of multibyte characters in my WIP configs. Those might be good sources of related PRs.

**Comment by dmitmel** [comment] 2021-07-27 16:41
About this PR in particular: `vim.str_byteindex` will suffice even though there is no function for iterating over characters of a string. Although I think #

**Comment by clason** [comment] 2021-07-27 16:49
> Although I think #14281 is more appropriate for such discussions.

Yes, and fixing incremental sync is high priority -- but any fix that goes towards ameliorating the general multi-byte mess in Lua is even more welcome.

(The big bonus of the `mbyte.c` exposure is that we are sure to have the same idea of length as vim core -- which might get dicey for composed characters and such... But maybe we need a short-term fix in the mean time.)

**Comment by dmitmel** [comment] 2021-07-27 16:52
Got it. Beware that I am a newcomer to the Nvim codebase. :sweat_smile:

**Comment by clason** [comment] 2021-07-27 16:55
You gotta start _somewhere_ ;)

**Comment by dmitmel** [comment] 2021-07-27 17:16
Wait, the heck? `vim.str_byteindex` and `vim.str_utfindex` stop at NULs? Does this mean that literally all LSP-related stuff is broken if the line contains a NUL byte?

**Comment by clason** [comment] 2021-07-27 17:33
It shouldn't (contain NUL); there's a translation layer that converts to `vim.NIL` where that occurs (and is not a terminator anyway). At least that's my understanding.

**Comment by dmitmel** [comment] 2021-07-27 17:36
```lua
print(vim.str_byteindex('привет', 4))  -- prints 8
print(vim.str_byteindex('пр\0ивет', 4))  -- errors with "index out of range"
```

**Comment by bfredl** [comment] 2021-07-27 17:40
> It shouldn't (contain NUL); there's a translation layer that converts to vim.NIL where that occurs (and is not a terminator anyway). At least that's my understanding.

No, that's for `null`, not `NUL`. We should fix `str_byteindex` (lua functions not interacting with internal vim state should be 8-bit safe, not 7.9943534 bit safe).

**Comment by clason** [comment] 2021-07-27 17:57
Silly mathematician, thinking that there's a unique null ;)

**Comment by dmitmel** [comment] 2021-07-27 18:24
Anyway, regarding this ticket: I made an interesting performance observation. So, I needed a way of iterating characters in a string, and I wrote these two functions:

```lua
function str_to_chars_1(str, utf16)
  -- vim.validate{
  --   str = {str, 'string'},
  --   utf16 = {utf16, 'boolean', true},
  -- }
  local chars = {}
  local char_idx = 1
  while true do
    local ok, char_len = true, 1
    if string.byte(str, 1) ~= 0 then
      ok, char_len = pcall(vim.str_byteindex, str, 1, utf16)
      if not ok then break end
    end
    chars[char_idx] = string.sub(str, 1, char_len)
    char_idx = char_idx + 1
    str = string.sub(str, char_len + 1)
  end
  return chars
end


function str_to_chars_2(str, utf16)
  -- vim.validate{
  --   str = {str, 'string'},
  --   utf16 = {utf16, 'boolean', true},
  -- }
  local chars = {}
  local char_idx = 1
  local byte_idx = 1
  while true do
    local ok, next_byte_idx = pcall(vim.str_byteindex, str, char_idx, utf16)
    if not ok then break end
    chars[char_idx] = string.sub(str, byte_idx, next_byte_idx)
    byte_idx = next_byte_idx + 1
    char_idx = char_idx + 1
  end
  return chars
end
```

Both do essentially the same thing, take a string and return a list with the characters. Now, you'd think that the second one would be slower because it essentially has to iterate the entire string over and over again to reach further characters (the complexity of this would be `O(n*(n+1)/2)`, I guess), and the first one jumps over just a single character on each step, but you'd be wrong. They actually have roughly the same speed, and the second one is a bit slower! (...on a dumb benchmark of running the function many times) Perhaps this is an indication of the fact that string slicing is not as fast in Lua as I expected it to be...

In any case, there is an important difference: the first function can be made to handle NUL bytes correctly (see the `if`), the second one depends on a patch to `vim.str_byteindex` for obvious reasons. _But, because the performance is effectively the same, we can go with either one._ I'd obviously say that we take the first one because handling NULs is better than not. Oh, and I'm not talking about the exact functions, but the methods of iteration for characters.

**Comment by bfredl** [comment] 2021-07-27 18:30
well, the cost of switching between c and lua contexts is much higher than iterating over a short string already in cache. if we want to speed this operation up, we want a c function that does more work before it returns (i e return an _array_ of byte indices where chars start).

**Comment by dmitmel** [comment] 2021-07-27 18:39
Oh, I also have to ask about handling of invalid UTF-8. Am I understanding it correctly: does Neovim convert files of all encodings to UTF-8 for usage in-memory, in Vimscript and through API (e.g. `nvim_buf_get_lines`)?

**Comment by bfredl** [comment] 2021-07-27 19:52
@dmitmel well, when you read a file, this is what happens by default: neovim attempts to detect the encoding, and convert it to valid UTF-8 internally. However there's no guarantee that the buffer actually contains valid UTF-8. you can add invalid utf-8 text using set_lines, by pasting it, etc, and then `set_lines` will give you the unmodified bytes back. You can ask neovim to read a file as `++binary` data, which will preserve invalid UTF-8 as such. In particular, NUL bytes are allowed as part of a buffer, but this causes all sort of weirdness with _vim script_ functions as vim script doesn't allow NUL in strings. 

However, as lua has no problem with NUL inside strings, our goal is that lua _should_ handle this situation without much extra heavy lifting (from the point of view of the the lua plugin, that is). As such, I would consider the existing behaviour of `str_byteindex` (which I wrote) as a bug, and changing it to handle NUL a bugfix.

**Comment by mjlbach** [comment] 2021-10-31 03:41
The bug is not fixed on master, you can test the above PR. The easy trigger is operations which delete a multibyte char.

**Comment by khokho** [comment] 2021-11-01 08:30
I actually can't trigger the bug on `neovim-git` but can do on 0.5.1 :man_shrugging:

**Comment by octaltree** [comment] 2021-11-01 09:26
I tried the first reproduction method with head.
```
NVIM v0.6.0-dev+544-g7ae86c1d4
Build type: RelWithDebInfo
LuaJIT 2.0.5
```
I don't get any error messages in nvim anymore, but according to the logs, the client is dead.
[lsp.log](https://github.com/neovim/neovim/files/7452109/lsp.log)

**Comment by mjlbach** [comment] 2021-11-01 09:27
There have been no fixes yet so I'm not surprised that's happening. You can try my linked PR

**Comment by octaltree** [comment] 2021-11-02 09:30
I tried with 1dbbaf89. Incremental sync is done without error.
[lsp.log](https://github.com/neovim/neovim/files/7459410/lsp.log)

**Comment by mjlbach** [comment] 2021-11-02 16:40
Ok, great! I'll try to get that merged next weekend. We found that even though rangeLength is deprecated, we still need to compute it for some servers (jdtls particularly)

**Comment by mjlbach** [comment] 2021-11-05 05:53
I went down a rabbit hole after filing that PR, there are some things that are broken in our current implementation are endline/multiline handling, some of the variable names are inscrutable/I didn't comment things well, etc. I'm rewriting everything in this repo:

https://github.com/mjlbach/incremental.nvim

Note, I've dramatically simplified some of the code, and improved performance (thanks to some tips from @dmitmel). I'm having a bit of trouble reliably getting end_range working, but hopefully will have some time to hack on it soon. I'm verifying the range changes with vscode, and set up a plenary testing suite against the current implementation (which, sadly, is wrong in many of these cases). If anyone here is interested on hacking on it together please file PRs (or help me fill out the tests!). 

Sorry this is taking so long I added some C utilities in core to help with the positioning, and I had to refamiliarize myself with the diffs, and there were several differences in vscode vim emulation notion of deletions/insertions that threw me off for a bit... I'm pretty sure at least start_range is now consistently correct :)

I am still confident this will get done by 0.6

**Comment by mjlbach** [comment] 2021-11-06 05:46
Can you all test #16252, I think this fixes everything...

**Closed** 2021-11-09 22:37 UTC
Labels: bug, lua, lsp, unicode  💩

**Comment by powerman** [comment] 2024-07-26 20:51
Please take a look at https://github.com/Feel-ix-343/markdown-oxide/issues/156 - I belive this is still an issue, just more racy and harder to trigger.

It happens for me while paste several dozens of Russian text lines: Neovim sends to LSP server JSON-RPC request which ends (in the middle of pasted lines) with "\xD0" byte instead of two bytes "\xD0\xB0" (which is https://unicodeplus.com/U+0430).

Because of race it's hard to reproduce, so I don't have a small `repro.lua` for this issue - I've tried to make one but without success so far.

```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
Run "nvim -V1 -v" for more info
```

**Comment by powerman** [comment] 2024-07-26 20:57
BTW, is this can happens because of OS clipboard manager? Any chance it sends pasted text to Neovim byte-by-byte and thus Neovim does not have complete UTF-8 at the moment of preparing LSP request?
Just in case I'm using Gentoo Linux with https://sourceforge.net/projects/parcellite/ 1.2.1 (just to sync PRIMARY and CLIPBOARD for Xorg).
