### ISSUE TITLE
Scrolling with `<C-d>` doesn't stop when EOF is visible at the bottom, only stopping when EOF is at the top

### ISSUE THREAD

**Issue by ChocolateOverflow** [neovim/neovim#28115] opened 2024-03-30 13:47 UTC
### Problem

When using `<C-d>` to scroll down, nvim would only stop once the last line of the file is at the top of the screen, not when the last line is visible at the bottom of the screen.

### Steps to reproduce

- no config needed
- Open a file (more than large enough for a full screen) & keep pressing `<C-d>` until it stops

### Expected behavior

When the last line has appeared on the screen (at the bottom), the cursor should move to that last line without letting that last line move up

### Neovim version (nvim -v)

v0.10.0-dev-2739+ge2224a793

### Vim (not Nvim) behaves the same?

no, vim 9.1

### Operating system/version

Arch Linux 6.8.2-arch2-1 x86_64 GNU/Linux

### Terminal name/version

alacritty 0.13.2 (bb8ea18e)

### $TERM environment variable

alacritty

### Installation

https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage

**Comment by clason** [comment] 2024-03-30 13:48
duplicate of #28106

**Comment by zeertzjq** [comment] 2024-03-30 13:54
No

**Comment by luukvbaal** [comment] 2024-03-30 14:23
Yes, both issues are also tracked here https://github.com/vim/vim/issues/14338.
I'm working on a fix to restore the previous behavior, although I think it is weird/inconvenient that the various scroll keys behaved differently.

**Comment by monkoose** [comment] 2024-04-06 16:12
I think it is the same PR that caused this, so I have not opened new issue, but <C-u> now also weirdly jumps between closed folds (in a file with a lot of closed folds (previously they just treated like 1 line to caclulate <C-u> jump, but now its behaviour is inconsistent). You can try it in file like this https://github.com/monkoose/neocodeium/blob/main/lua/neocodeium/server.lua

**Comment by luukvbaal** [comment] 2024-04-06 16:53
@monkoose I am attempting to fix any issues on top of the current patches so until proven fruitless I don't think we will revert. Sounds like a different problem indeed so if not a separate issue, clear reproduction steps would still be appreciated.

**Comment by monkoose** [comment] 2024-04-06 17:13
Ok, I will create new issue then.

**Closed** 2024-04-08 23:08 UTC
Labels: bug-regression
