### ISSUE TITLE
happen SIGABRT when jump invalid range

### ISSUE THREAD

**Issue by skanehira** [neovim/neovim#13453] opened 2020-12-05 06:06 UTC
- `nvim --version`: NVIM v0.5.0-834-g7c4f34966
- `vim -u DEFAULTS` (version: 8.2.2069) behaves differently?: Yes
- Operating system/version: Ubuntu 20.04 TLS
- Terminal name/version: gnome terminal
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
<C-r>=0/0<CR>
```

### Actual behaviour
happen SIGABRT
```
:-9223372036854775808fish: “nvim -u NORC” terminated by signal SIGABRT (Abort)
```
### Expected behaviour
display some error message
Vim will display error message `invalid range`

**Comment by glacambre** [comment] 2021-06-09 11:01
Can't reproduce on master, so I'll close this issue. Thanks for the report :).

**Closed by glacambre** 2021-06-09 11:01 UTC
