### ISSUE TITLE
Can't capitalize letters when using accents with wezterm and `enable_kitty_protocol`

### ISSUE THREAD

**Issue by igorlfs** [neovim/neovim#27380] opened 2024-02-08 00:40 UTC
### Problem

Using wezterm and setting [enable_kitty_protocol](https://wezfurlong.org/wezterm/config/lua/config/enable_kitty_keyboard.html) to true makes neovim not handle capitalized letters correctly, if they are to be inserted with accents. When trying to insert `É`, neovim outputs it as `é`. 

I understand this could be a limitation of either the kitty protocol or wezterm's implementation, but it works fine outside neovim. I suspect this can also happen with other keys that require combinations.

### Steps to reproduce

nvim --clean
i
É

### Expected behavior

Insert capitalized letters correctly, even with kitty protocol enabled.

### Neovim version (nvim -v)

v0.10.0-dev-2293+gc4417ae70c

### Vim (not Nvim) behaves the same?

yes, vim 9.1.80

### Operating system/version

Linux 6.7.3

### Terminal name/version

wezterm 20240128-202157-1e552d76

### $TERM environment variable

xterm-256color

### Installation

AUR

**Comment by zeertzjq** [comment] 2024-02-08 00:42
Duplicate of #21399

**Closed by zeertzjq** 2024-02-08 00:42 UTC
Labels: bug, tui
