### ISSUE TITLE
Does not run this BufNewFile autocmd

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [neovim/neovim#12597] opened 2020-07-05 11:38 UTC
- `nvim --version`: Tried 0.4.3 and 0.5.3
- `vim -u DEFAULTS` (version: ) vim 8.2 behaves appropriately
- Operating system/version: Arch Linux
- Terminal name/version: Konsole konsole 20.04.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u min.vim `

```viml
function! s:shellbang()
    let options  = [
        \ 'ash',
        \ 'bash',
        \ 'csh',
        \ 'dash',
        \ 'fish',
        \ 'ksh',
        \ 'ion',
        \ 'mksh',
        \ 'pdksh',
        \ 'sh',
        \ 'tcsh',
        \ 'zsh',
        \ 'none',
        \ ]

    let choice = inputlist([ 'Select your shell:' ]
        \ + map(copy(options), '"[".(v:key+1)."] ".v:val'))

    if choice >= 1 && choice <= (len(copy(options)) - 2)
        if choice == 5
            set ft=fish
        elseif choice == 7
            set ft=ion
        endif
        0put = '#!/usr/bin/env ' . (options)[choice - 1]
    endif
endfunction!

command! -bang -nargs=0 -bar ShellBang call <SID>shellbang()

autocmd BufNewFile *.sh      ShellBang
```

### Actual behaviour

Enters a new `.sh` file normally and nothing happens.

### Expected behaviour

Enters a new `.sh` file and prompts user for what shell they want to use and then inserts the appropriate shebang.

I have also  tested this on vim 8.2 and it does the expected behavior.

**Comment by monkoose** [comment] 2020-07-05 12:10
Can confirm this. 
Seems like inputlist() doesn't call.

`nvim -u NONE -c "set shortmess-=F" +"autocmd BufNewFile * call inputlist(['test1', 'test2'])"`

**Comment by erw7** [comment] 2020-07-05 21:37
Duplicate of #10116, #10008.

**Comment by erw7** [comment] 2020-07-06 09:26
@monkoose You will need to use `--cmd`. As described in `:h starting`, the commands given to `-c` and `+` are executed after the first file has been read.

**Comment by erw7** [comment] 2020-07-06 09:29
I've created a section on this in the FAQ as follows

https://github.com/neovim/neovim/wiki/FAQ#calling-inputlist-echomsg-etc-in-filetype-plugins-and-autocmd-does-not-work

**Closed by erw7** 2020-07-06 09:29 UTC
Labels: bug, duplicate
