### ISSUE TITLE
Slow netrw operation on 0.1.0 Neovim build

### ISSUE THREAD

**Issue by siphiuel** [neovim/neovim#3726] opened 2015-11-23 15:54 UTC
Hi all,

thanks for outstanding effort on Neovim.

I am getting weird slowdowns when navigating Netrw buffers, similar to [#1882](https://github.com/neovim/neovim/issues/1882), but on a scale of ~1sec. I've enabled Vim profiling with

    :profile start nvim.log
    :profile file *
    :profile func *

and jumped through folders a couple of times. At the end of `nvim.log` there is this:

    FUNCTIONS SORTED ON TOTAL TIME
    count  total (s)   self (s)  function
       88   3.065545   0.001285  provider#clipboard#Call()
       88   3.061784             <SNR>55_try_cmd()
       16   2.298749   0.001069  netrw#LocalBrowseCheck()
       15   2.292873   0.004757  <SNR>52_NetrwBrowse()
       44   1.562183   0.001182  14()
       43   1.537829             <SNR>52_NetrwOptionSave()
       44   1.502077   0.001294  15()
       59   1.501420   1.490751  <SNR>52_NetrwOptionRestore()
        8   1.264721   0.000582  <SNR>52_NetrwRefresh()
       15   1.206394   0.005489  <SNR>52_NetrwBrowseChgDir()
        4   0.958985   0.000779  <SNR>52_NetrwListStyle()
        4   0.950870   0.000742  <SNR>52_NetrwBannerCtrl()
       15   0.944636   0.030505  <SNR>52_NetrwGetBuffer()
       13   0.911636   0.006668  <SNR>52_NetrwEnew()
        5   0.811024   0.001338  <SNR>31_opendir()
       15   0.790094   0.004886  <SNR>52_PerformListing()
        3   0.713985   0.000407  <SNR>52_NetrwBrowseUpDir()
       30   0.166575   0.005739  <SNR>52_NetrwSafeOptions()
      138   0.104341             rainbow_parentheses#load()
       15   0.093563   0.000482  <SNR>37_LocalBrowse()

    FUNCTIONS SORTED ON SELF TIME
    count  total (s)   self (s)  function
       88              3.061784  <SNR>55_try_cmd()
       43              1.537829  <SNR>52_NetrwOptionSave()
       59   1.501420   1.490751  <SNR>52_NetrwOptionRestore()
      138              0.104341  rainbow_parentheses#load()
       15              0.070957  <SNR>52_NetrwWideListing()
       46   0.041482   0.041413  <SNR>8_LoadFTPlugin()
       15   0.944636   0.030505  <SNR>52_NetrwGetBuffer()
       46   0.048313   0.025996  <SNR>4_SynSet()
       15   0.021794   0.021681  <SNR>52_NetrwMaps()
      119              0.011041  netrw#RestorePosn()
       33              0.010608  <SNR>12_addtomrufs()
       46              0.009826  <SNR>21_define_commands()
       70   0.012067   0.008792  <SNR>52_NetrwGetWord()
       46   0.008676   0.008639  <SNR>9_LoadIndent()
       15   0.008892   0.007346  <SNR>52_LocalListing()
       13   0.911636   0.006668  <SNR>52_NetrwEnew()
       46   0.040078   0.006252  fugitive#detect()
       45              0.006136  <SNR>31_setup_vinegar()
       15              0.006057  <SNR>52_NetrwListHide()
       30   0.166575   0.005739  <SNR>52_NetrwSafeOptions()

Notes on environment i use: Neovim 0.1.0 (Homebrew build, Build type: RelWithDebInfo
), OS  X 10.11.1, Vim 7.4.922. Navigating in Vim is really fast with no slowdowns at all.

Maybe someone could point me to possible causes?

Thanks!

**Comment by justinmk** [comment] 2015-11-27 18:34
It's because of `'clipboard'`, though this was supposed to be fixed by https://github.com/neovim/neovim/pull/2809.

**Comment by siphiuel** [comment] 2015-11-28 19:10
I see, thanks. I don't have anything set for `'clipboard'` though.

**Comment by justinmk** [comment] 2015-11-28 22:50
That's weird. Looks like netrw doesn't care though. Not surprising.

**Comment by fatih** [comment] 2016-01-21 01:57
I've just discovered this too. I'm using the same config both for nvim and vim: https://github.com/fatih/dotfiles/blob/master/init.vim 

In Vim it's opening instantaneously, but Neovim lags when I open netrw.

**Comment by phinze** [comment] 2016-01-28 22:45
Hi folks! I'm experiencing this too. On OSX my `/var/log/system.log` fills up with lines like these during the lag:

```
Jan 28 16:43:41 [...] pbcopy[39944]: LaunchServices: Database mapping failed with result -10822, retrying
Jan 28 16:43:41 [...] pbcopy[39944]: LaunchServices: received XPC_ERROR_CONNECTION_INTERRUPTED trying to map database
```

**Comment by phinze** [comment] 2016-01-28 23:05
Hello again! Tracked my problem down to ye olde `tmux` / OSX clipboard madness that my config had somehow lost the workaround for.

Re-applied `reattach-to-user-namespace` ([per this article](https://robots.thoughtbot.com/how-to-copy-and-paste-with-tmux-on-mac-os-x)) and netrw performance is back to normal for me within `tmux`. :+1:

**Comment by siphiuel** [comment] 2016-01-29 10:40
Hmm. Weird. Nice catch. I do get the same error messages when navigating in Netrw Neovim. But usual Vim also produces these log entries, with a slight difference in that process name in `system.log` is not `pbcopy`/`pbpaste`, but `vim` itself.

**Comment by toadums** [comment] 2016-02-18 17:15
This just started happening to me, took about 1sec to open netrw, and 1 second if I changed directories. It started out of nowhere - just booted up iTerm this morning and started working. Didn't change anything in my vimrc, or elsewhere. It behaved the same inside and outside of tmux.

I restarted my computer, and the issue is gone now.

**Comment by entombedvirus** [comment] 2016-06-18 17:59
My netrw has also been showing ~1-2 sec delay when using neovim. As pointed out earlier in this thread, the cause is that netrw saves and restores the `@*` and `@+` registers. I verified this by turning on func and file profiling and 
[examining the logs](https://github.com/neovim/neovim/files/321890/nvim.log.txt).

Since I am using neovim over SSH, with X forwarding enabled, each time netrw saves or restores those registers, neovim invokes a shell command (one of `xclip,xsel`) and _that_ invocation takes about a second. I verified this by removing both `xclip,xsel` from my PATH, restarting the SSH session without X forwarding and observing that netrw in nvim is fast.

It's worth nothing that I do **not** have neovim `clipboard` options set to `unnamed` or `unamedplus,` but I still experience the slowness just by netrw's interaction with the two clipboard registers.

I am not entirely sure why netrw needs to save and restore the clipboard registers when browsing the fs.
As for a workaround, I think I am going to just switch to another file explorer plugin that does not have interaction with the clipboard registers.

**Comment by justinmk** [comment] 2016-08-26 00:55
Should be fixed on master. https://github.com/neovim/neovim/pull/5253

**Closed by justinmk** 2016-08-26 00:55 UTC
Labels: bug, clipboard

**Comment by zutsume** [comment] 2016-09-18 14:48
I'm currently using Vim 8 and I'm having this issue where the startup is really slow due to Vim connecting to the X-Server ( by passing it the `-X` flag it starts fast again ), as per this [stackoverflow question](http://stackoverflow.com/questions/14635295/vim-takes-a-very-long-time-to-start-up). 

I'm wondering if neovim handles the startup more efficiently? I'm going to install neovim after work later today.

**Comment by justinmk** [comment] 2016-09-18 19:56
@zutsume You won't run into that particular issue with nvim because nvim never connects directly to X. We also don't have any of these platform-specific arguments like `-X`.

**Comment by jrowlingson** [comment] 2018-10-14 19:49
I am also noticing a slight lag when opening netrw via `:Explore`. There is a similar amount of lag when switching between netrw buffers.

```
MacOS 10.14 (18A391)
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U
_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unu
meter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-str
agnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_
-DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180831-45030-1c6df1y/neovim-0.3.1/build/confi
/neovim-20180831-45030-1c6df1y/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/g
nclude -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Deve
Ks/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20180831-45030-1c6df1y/neovim-0.3.1/build/
/auto -I/tmp/neovim-20180831-45030-1c6df1y/neovim-0.3.1/build/include
Compiled by brew@Mojave.local
```

nvim:
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   0.252974   0.102575  netrw#Explore()
    9   0.228228   0.000274  provider#clipboard#Call()
    9   0.227705             <SNR>23_try_cmd()
    5   0.134464   0.000102  2()
    1   0.111724   0.000071  netrw#LocalBrowseCheck()
    1   0.111613   0.000426  <SNR>22_NetrwBrowse()
    4   0.093490   0.000146  3()
    3   0.082410             <SNR>22_NetrwOptionSave()
    2   0.078124   0.000616  <SNR>22_NetrwEnew()
    1   0.049829   0.000690  <SNR>22_NetrwGetBuffer()
    4   0.047820   0.046069  <SNR>22_NetrwOptionRestore()
    1   0.038307   0.000092  provider#clipboard#Executable()
    1   0.038215             <SNR>23_cmd_ok()
    1   0.031864   0.001874  <SNR>22_NetrwBookHistSave()
    1   0.029664   0.000437  <SNR>22_PerformListing()
   77   0.001854             <SNR>22_NetrwInit()
    1   0.001720   0.001350  <SNR>22_NetrwBookHistRead()
    1   0.001478   0.000147  <SNR>22_NetrwSafeOptions()
    2   0.001349   0.000605  <SNR>6_SynSet()
    1   0.001202   0.000633  <SNR>22_LocalListing()
```

vim (8.0.1283):
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   0.037577   0.013354  netrw#Explore()
    1   0.024223   0.000082  netrw#LocalBrowseCheck()
    1   0.024090   0.000562  <SNR>18_NetrwBrowse()
    1   0.010715   0.000710  <SNR>18_PerformListing()
    1   0.007728   0.001276  <SNR>18_NetrwGetBuffer()
    4   0.005391   0.003561  <SNR>18_NetrwOptionRestore()
    2   0.005323   0.000784  <SNR>18_NetrwEnew()
    1   0.004710   0.003329  <SNR>18_NetrwBookHistSave()
    1   0.003465   0.002941  <SNR>18_NetrwBookHistRead()
    1   0.002659   0.001508  <SNR>18_LocalListing()
    1   0.002569             <SNR>18_NetrwSetSort()
    2   0.002131   0.000887  <SNR>3_SynSet()
   77   0.002085             <SNR>18_NetrwInit()
    1   0.002066             <SNR>18_NetrwListSettings()
    1   0.001378   0.000208  <SNR>18_NetrwSafeOptions()
    3   0.001284             <SNR>18_NetrwOptionSave()
   21   0.001057             <SNR>18_NetrwFile()
    1   0.000809   0.000785  <SNR>18_NetrwMaps()
    2   0.000690   0.000484  <SNR>18_NetrwGlob()
    3   0.000624   0.000343  <SNR>18_NetrwHome()
```
