### ISSUE TITLE
Unable to print multiline string inside keymap callback function

### ISSUE THREAD

**Issue by Akmadan23** [neovim/neovim#23692] opened 2023-05-20 13:32 UTC
### Problem

When I attempt to print a string with multiple lines inside a keymap callback with `vim.print(table)` or `print(vim.inspect(table))` , only the last line gets printed, whereas `:lua vim.print(table)` actually prints the full table.

### Minimal code

`keymaps.lua`:
```lua
vim.keymap.set("n", "t", function()
  local t = { x = 1, y = 2, z = 3 }
  vim.print(t)
end)
```

### Steps:

1. nvim --clean -u keymaps.lua
2. t

### Output:
`}`

### Expected behavior

It should print the full table, in the example it would be
```
{
  x = 1,
  y = 2,
  z = 3
}
```

### Neovim version (nvim -v)

NVIM v0.9.0; Build type: Release; LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

unsupported

### Operating system/version

Linux arch 6.3.2-arch1-1

### Terminal name/version

alacritty 0.12.0

### $TERM environment variable

alacritty

### Installation

Arch standard repos

**Comment by clason** [comment] 2023-05-20 13:35
`:messages` will show the full output.

**Comment by zeertzjq** [comment] 2023-05-20 13:37
Will changing this behavior break plugins?

**Comment by zeertzjq** [comment] 2023-05-20 13:40
Duplicate of #22878

**Closed by zeertzjq** 2023-05-20 13:40 UTC

**Comment by Akmadan23** [comment] 2023-05-20 13:52
Ok, I can either use `nvim_echo` or `:messages` but if feels a bit hacky. The thing I don't get is why it works when called from cmd and doesn't when inside a lua callback...
