### ISSUE TITLE
Assertion error (bop_node_lvl != new_top_node_lvl) with expression register

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#12761] opened 2020-08-16 11:52 UTC
- `nvim --version`: NVIM v0.5.0-632-gc219d3eec
- `vim -u DEFAULTS` (version: 8.2.814) behaves differently? yes, no crash.
- Operating system/version: Arch Linux
- Terminal name/version: tmux/Kitty
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

1. enter insert mode (`i`)
2. start pasting from the expression register (`i_CTRL-R_=`)
3. type ` foo/bar b` (leading space), nvim will crash
```

### Actual behaviour

nvim crashes:
```
#0  0x00007f8f4173b355 in raise () from /usr/lib/libc.so.6
#1  0x00007f8f41724853 in abort () from /usr/lib/libc.so.6
#2  0x00007f8f41724727 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007f8f41733936 in __assert_fail () from /usr/lib/libc.so.6
#4  0x0000560368a682a9 in viml_pexpr_handle_bop (pstate=0x7ffedcc71b60, ast_stack=0x7ffedcc719c0, bop_node=0x5603699af720, want_node_p=0x7ffedcc70e44, ast_err=0x7ffedcc718a0)
    at ../src/nvim/viml/parser/expressions.c:1237
#5  0x0000560368a7d31e in viml_pexpr_parse (pstate=0x7ffedcc71b60, flags=2) at ../src/nvim/viml/parser/expressions.c:2725
#6  0x00005603688b7b76 in color_expr_cmdline (colored_ccline=0x560368bbb700 <ccline>, ret_ccline_colors=0x560368bbb760 <ccline+96>) at ../src/nvim/ex_getln.c:2570
#7  0x00005603688b83e2 in color_cmdline (colored_ccline=0x560368bbb700 <ccline>) at ../src/nvim/ex_getln.c:2686
#8  0x00005603688b8e46 in draw_cmdline (start=9, len=1) at ../src/nvim/ex_getln.c:2845
#9  0x00005603688ba6e3 in put_on_cmdline (str=0x560368bc0440 <IObuff> "b", len=1, redraw=1) at ../src/nvim/ex_getln.c:3217
#10 0x00005603688b6455 in command_line_handle_key (s=0x7ffedcc72440) at ../src/nvim/ex_getln.c:1781
#11 0x00005603688b41e1 in command_line_execute (state=0x7ffedcc72440, key=98) at ../src/nvim/ex_getln.c:1075
#12 0x0000560368a283c4 in state_enter (s=0x7ffedcc72440) at ../src/nvim/state.c:69
#13 0x00005603688b21c3 in command_line_enter (firstc=61, count=0, indent=0) at ../src/nvim/ex_getln.c:428
#14 0x00005603688b6c9f in getcmdline (firstc=61, count=0, indent=0, do_concat=true) at ../src/nvim/ex_getln.c:2031
#15 0x0000560368966300 in get_expr_register () at ../src/nvim/ops.c:706
#16 0x0000560368824060 in ins_reg () at ../src/nvim/edit.c:7526
#17 0x0000560368816cf6 in insert_handle_key (s=0x7ffedcc72830) at ../src/nvim/edit.c:915
#18 0x00005603688165b6 in insert_execute (state=0x7ffedcc72830, key=18) at ../src/nvim/edit.c:802
#19 0x0000560368a283c4 in state_enter (s=0x7ffedcc72830) at ../src/nvim/state.c:69
#20 0x0000560368815b5f in insert_enter (s=0x7ffedcc72830) at ../src/nvim/edit.c:484
#21 0x00005603688177ce in edit (cmdchar=105, startln=false, count=1) at ../src/nvim/edit.c:1413
#22 0x0000560368963be7 in invoke_edit (cap=0x7ffedcc72a18, repl=0, cmd=105, startln=0) at ../src/nvim/normal.c:7660
#23 0x0000560368963b7d in nv_edit (cap=0x7ffedcc72a18) at ../src/nvim/normal.c:7632
#24 0x000056036895511d in normal_execute (state=0x7ffedcc72990, key=105) at ../src/nvim/normal.c:1138
#25 0x0000560368a283c4 in state_enter (s=0x7ffedcc72990) at ../src/nvim/state.c:69
#26 0x00005603689533bf in normal_enter (cmdwin=false, noexmode=false) at ../src/nvim/normal.c:463
#27 0x000056036890f7d1 in main (argc=3, argv=0x7ffedcc72d28) at ../src/nvim/main.c:553

#4  0x0000560368a682a9 in viml_pexpr_handle_bop (pstate=0x7ffedcc71b60, ast_stack=0x7ffedcc719c0, bop_node=0x5603699af720, want_node_p=0x7ffedcc70e44, ast_err=0x7ffedcc718a0)
    at ../src/nvim/viml/parser/expressions.c:1237
1237	   assert(bop_node_lvl != new_top_node_lvl
(gdb) p bop_node_lvl
$1 = kEOpLvlMultiplication
(gdb) p new_top_node_lvl
$2 = kEOpLvlMultiplication
```

I have not checked if/how Vim's code differs in this regard.

**Comment by jamessan** [comment] 2020-08-16 23:56
Duplicate of #7889

**Closed by jamessan** 2020-08-16 23:56 UTC
Labels: bug, bug-crash
