### ISSUE TITLE
Some options are actually buffer-local option (not window-local)

### ISSUE THREAD

**Issue by boltlessengineer** [neovim/neovim#21789] opened 2023-01-14 06:59 UTC
### Describe the bug

Some window-local options like `'number'`, `'signcolumn'` behaves like buffer-local option.
But they are treated as window-local option. (User have to use `vim.wo` for them)

### Steps to reproduce

nvim --clean
:edit foo
:setlocal number
:edit bar

### Expected behavior

If `'number'` is really a window-local option, same window with buffer `bar` opened should have numberline.
But when buffer is changed from `foo` to `bar`, numberline turns off.

If `'number'` is buffer-local option, it should be treated from `vim.bo` not `vim.wo`

Other options like `'relativenumber'`, `'signcolumn'`, `'cursorline'` have same issue.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1826+g89232b8b4-dirty

### Vim (not Nvim) behaves the same?

yes, vim 9.0.639

### Operating system/version

macOS 13.1

### Terminal name/version

wezterm 20221122-154621-68c754b1

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment] 2023-01-14 07:04
Duplicate of #11525

**Closed by zeertzjq** 2023-01-14 07:04 UTC
Labels: bug
