### ISSUE TITLE
How to get scrolling (and xterm terminfo more specifically) to work on Windows

### ISSUE THREAD

**Issue by damca** [neovim/neovim#12289] opened 2020-05-09 22:00 UTC
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Windows
- Terminal name/version: Alacritty, Windows Terminal (Preview), Hyper.js, etc.
- `$TERM`: xterm-256color (technically $env:TERM)

### Actual behaviour

The main problem I have is scrolling with the mouse within neovim on any terminal on windows. Nvim-qt scrolls just fine.

With Alacritty (and many other terminals on Windows), the $env:TERM variable is set to xterm-256color (when using Powershell). However, after starting nvim, `echo &term` gives `builtin_xterm`.

I am assuming my scroll problems are with the terminfo used. On macOS with Alacritty (or Terminal.app) `echo &term` gives `xterm-256color`, and scrolling with mouse works just fine.

### Expected behaviour

That nvim would be able to scroll within terminals that support xterm-256color. Perhaps I need to add a specific terminfo somewhere? Not sure.

**Comment by erw7** [comment] 2020-05-10 04:53
Duplicate of #9514.

The cause of this problem is that TTY emulator of libuv does not send a sequence during mouse events. I've already created a PR (#11803) to fix it.

**Closed** 2020-05-10 07:15 UTC
Labels: bug, duplicate, platform:windows, tui
