### ISSUE TITLE
Issue with diagnostics when using julials and built-in LSP implementation

### ISSUE THREAD

**Issue by kdheepak** [neovim/neovim#12105] opened 2020-04-10 15:59 UTC
I'm able to use the built-in LSP implementation successfully with other language servers, but when using it with julials I'm having a few issue. Notably, I'm not able to get the diagnostics to show up and stay shown inline in the buffer.

I don't have this issue with vim-language-server and the built-in LSP implementation, and I don't have this issue with LanguageServer.jl and [autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim/). I don't know what it is about the built-in implementation and julials from nvim-lsp that causes this issue.

![neovimdiagnoistic mov](https://user-images.githubusercontent.com/1813121/79003926-e5019200-7b10-11ea-87f7-b866e0dc2ca5.gif)

You'll see in the gif, in the split on the right side, you'll see a flash of inline diagnostics and then it disappears. This issue does not happen with LanguageClient-neovim. I also ran `:lua vim.lsp.util.show_line_diagnostics()` and it doesn't do anything.

I've been trying to add print statements to the lua lsp file to try to figure out what is going on with no luck.

- `nvim --version`:

```
nvim --version
Alias tip: vi --version
NVIM v0.5.0-nightly-71-g1f56f9a4b
Build type: Release
LuaJIT 2.0.5
Compilation: /Users/USER/.local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200409-91602-1oi1s77/build/config -I/tmp/neovim-20200409-91602-1oi1s77/src -I/Users/USER/.local/include -I/tmp/neovim-20200409-91602-1oi1s77/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Users/USER/.local/opt/gettext/include -I/tmp/neovim-20200409-91602-1oi1s77/build/src/nvim/auto -I/tmp/neovim-20200409-91602-1oi1s77/build/include
Compiled by USER@USER

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/Users/USER/.local/Cellar/neovim/HEAD-1f56f9a/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?

I am using the following `MINRC` file, and running `vim -u MINRC tests/test.jl` using this [`tests/test.jl`](https://github.com/kdheepak/JuliaFormatter.vim/blob/55c3260ad2dee1b0f2d6be57655c67ca5522c616/tests/test.jl).

```
set nocompatible              " be iMproved, required
filetype off                  " required

if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
"
" Specify a directory for plugins
" - For Neovim:
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.local/share/nvim/plugged')

Plug 'JuliaEditorSupport/julia-vim'  | " julia support for vim
Plug '~/gitrepos/nvim-lsp'           | " collection of common configurations for the Nvim LSP client.

" Initialize plugin system
call plug#end()

let mapleader = " "

" use built in neovim lsp for autocomplete
autocmd Filetype c,cpp,python,julia,vim setlocal omnifunc=v:lua.vim.lsp.omnifunc

lua << EOF
    require'nvim_lsp'.nimls.setup{}
    require'nvim_lsp'.julials.setup{}
    require'nvim_lsp'.pyls.setup{}
    require'nvim_lsp'.vimls.setup{}
EOF

nnoremap 1gD           :lua vim.lsp.buf.type_definition()<CR>
nnoremap gr            :lua vim.lsp.buf.references()<CR>
nnoremap g0            :lua vim.lsp.buf.document_symbol()<CR>
nnoremap gD            :lua vim.lsp.buf.implementation()<CR>
nnoremap gd            :lua vim.lsp.buf.declaration()<CR>
nnoremap <c-]>         :lua vim.lsp.buf.definition()<CR>
nnoremap <leader>lk    :lua vim.lsp.buf.hover()<CR>
nnoremap <leader>ld    :lua vim.lsp.util.show_line_diagnostics()<CR>
nnoremap <leader>ls    :lua vim.lsp.buf.signature_help()<CR>
```

- Operating system/version: MacOS Catalina Version 10.15.3.
- Terminal name/version: ITerm2 3.3.9
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

This is an issue with nvim-lsp and julials, so I'm not able to reproduce it using NORC. However, I'm not experiencing this issue when using [autozimu's LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim/).

### Actual behaviour

The diagnostic messages flash in and out once, and don't ever appear after that.

### Expected behaviour

The diagnostic messages appear inline and stay inline.

**Comment by ms** [comment] 2020-05-01 19:12
I ran into disappearing diagnostics when multiple language servers were registered for the same buffer. Maybe your issue is similar.

If you go to `$VIMRUNTIME/lua/vim/lsp/callbacks.lua` and look for `M['textDocument/publishDiagnostics'] = function(_, _, result)`, you can add logging to see if the callback is being called repeatedly. If you comment out `  util.buf_clear_diagnostics(bufnr)`, things will probably work (although diagnostics will never be cleared)

If this is the issue, I think diagnostics will need to be cleared _per client ID_. I'm not very familiar with Lua or the LSP spec so it may take me a bit of time to try to fix this properly, I'd welcome help.

**Comment by c0r73x** [comment] 2020-06-09 08:24
This is because when it runs clear_diagnostics it clears all of it, so when having multiple lsp's for one language it will clear the first one when you get data from the second one. The way to solve this would be to save the results by source and clear that source when it updates.

**Comment by kdheepak** [comment] 2020-06-09 15:48
I'm not able to reproduce this issue anymore. Maybe some changes in commits in nightly releases since I made this issue fixed it? Is anyone experiencing this now? Should I just close this?

**Comment by tjdevries** [comment] 2020-11-13 03:55
I believe I have fixed this with https://github.com/neovim/neovim/commit/f75be5e9d510d5369c572cf98e78d9480df3b0bb . We now track diagnostics on a per client basis. So this should not be happening anymore. Closing unless we can reproduce (or you can open again if you have any concerns).

**Closed by tjdevries** 2020-11-13 03:55 UTC
Labels: bug, lsp

**Comment by kdheepak** [comment] 2020-11-13 05:00
Awesome!!!
