### ISSUE TITLE
Build for 0.2.2 fails at bad url

### ISSUE THREAD

**Issue by bit101** [neovim/neovim#8172] opened 2018-03-25 01:03 UTC
https://github.com/neovim/neovim/blob/6d2c30daf3b29b84b15b547ef956e165f5e9685d/third-party/cmake/BuildLuarocks.cmake#L150

Checked out tag 0.2.2. Got most of the way through the build process. Failed on this line.
It's looking for

`https://raw.githubusercontent.com/mpeterv/luacheck/master/luacheck-scm-1.rockspec`

That file no longer exists. I managed to find the updated version at:

`https://raw.githubusercontent.com/mpeterv/luacheck/master/luacheck-dev-1.rockspec`

with `scm` changed to `dev`, the build succeeded.

**Comment by jamessan** [comment] 2018-03-25 01:13
Duplicate of #8056

**Closed by jamessan** 2018-03-25 01:13 UTC
