### ISSUE TITLE
Assertion `!(handle->flags & (UV_CLOSING | UV_CLOSED))' failed.

### ISSUE THREAD

**Issue by qstrahl** [neovim/neovim#2499] opened 2015-04-24 18:06 UTC
Hey, I don't have steps to reproduce or anything, but nvim suddenly froze up as I was working and I had to kill it from another terminal. Only happened once, not a recurring bug as far as I know. When it exited, it produced this message:

```
vim: /build/buildd/neovim-0.0.0+git201504231825+1546+8+9~ubuntu14.10.1/.deps/build/src/libuv/src/unix/core.c:95: uv_close: Assertion `!(handle->flags & (UV_CLOSING | UV_CLOSED))' failed.
```

I figured someone might want to know about it. Please close this issue if it's not helpful.

**Comment by equalsraf** [comment] 2015-04-24 22:51
It would seem the assert is there to check if uv_close is called twice on the same handle

```C
void uv_close(uv_handle_t* handle, uv_close_cb close_cb) {
  assert(!(handle->flags & (UV_CLOSING | UV_CLOSED)));

  handle->flags |= UV_CLOSING;
  handle->close_cb = close_cb;

```

**Comment by justinmk** [comment] 2015-08-17 07:45
@oni-link made a couple recent commits in this area, so I'll close this since we don't have more information.

**Comment by akkartik** [comment] 2015-08-25 02:07
This is still happening. I'm running off version 201508211338 (commit c75d5010b742db83462fc4508cf6dba455f79ca7)

**Comment by tarruda** [comment] 2015-09-08 11:39
@akkartik can you provide me your vimrc? I'd like to try reproducing it locally

**Comment by akkartik** [comment] 2015-09-08 17:27
As it happens I just yesterday stumbled over a way to make the bug reliably manifest, at least on my laptop. Here's a fairly concise setup:

```shell
$ wget http://akkartik.name/neovim-issue-2499.tgz
$ tar zxf neovim-issue-2499.tgz 
$ cd neovim-issue-2499/scenario 
$ rm *.html; VIM=`pwd`/../vim nvim -u `pwd`/../vim/vimrc.vim -c "TOhtml |w | qa" tcc.c
zsh: no matches found: *.html
vim: /home/agaram/.local/share/src/neovim/.deps/build/src/libuv/src/unix/core.c:209: uv__finish_close: Assertion `handle->flags & UV_CLOSING' failed.
```

You should be able to run the last command over and over again with a reliable assertion failure. The necessary preconditions seem to be:

1. The https://github.com/mhinz/vim-signify plugin
2. Syntax highlighting enabled with all the frills (indent, plugins, etc.)
3. Writing to a non-existent file under a git repo. (The file doesn't have to actually be part of the repo.)
4. Quitting immediately after writing.

Beyond these preconditions my tarball is just one way to make the issue manifest more reliably. Though I found I needed at least one autocommand in my vimrc, even though it doesn't do anything.

Let me know if you're able to reproduce the issue. This one seems tough to track down given all the dependencies :/

**Comment by justinmk** [comment] 2015-09-08 19:21
https://github.com/neovim/neovim/issues/3000 also involves TOhtml.

**Comment by akkartik** [comment] 2015-09-08 19:47
I think `TOhtml` might not be directly implicated here. It's just having some side effect of processing or memory use or libio that makes the bug reproduce more easily. I originally found the problem while composing git commit messages, which are far tinier files and do far less processing. In that situation the bug is much more hard to deterministically trigger.

**Comment by tarruda** [comment] 2015-09-09 01:57
@akkartik thanks for the detailed steps, but even with it I'm unable to reproduce on master(I've tried like 30 times). Is it possible that you are running an outaded libuv version? If so, compiling after `rm -rf build .deps` should make sure it is updated.

**Comment by dnmario** [comment] 2015-09-09 01:57
Dear Thiago de Arruda,

The email sent to danielm@tinyhub.tk with subject
"Re: [neovim] Assertion `!(handle->flags & (UV_CLOSING | UV_CLOSED))'"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by tarruda** [comment] 2015-09-09 02:13
@dnmario There's something wrong with your mail server(it is posting comments on issues your'e tracking). I've blocked you for now, but when you fix the problem just send me a message on IRC or gitter and I will unblock.

**Comment by justinmk** [comment] 2015-09-09 02:21
@tarruda see https://github.com/neovim/neovim/pull/3273#issuecomment-136228679 for a similar case

**Comment by tarruda** [comment] 2015-09-09 02:51
@akkartik if updating libuv doesn't help, could you provide a backtrace of the core dump and information about your environment(OS, version, etc)?

**Comment by akkartik** [comment] 2015-09-09 03:01
@tarruda Thanks for trying my test. You're right, I just rebuilt from HEAD and the problem's gone. Just to make sure, I switched back to my previous head (c75d5010b742db83462fc4508cf6dba455f79ca7) and the problem is reliably present there, even after `rm -rf build .deps`. Can you reproduce at that commit, just for curiosity's sake?

According to `git bisect`, the commit that fixed the issue for me (and maybe actually fixed it :) is eb001a4abd2fbc740547c127807b2fc8367cc187. Hope this helps. I'll keep an eye out in case it recurs.

**Comment by dnmario** [comment] 2015-09-09 03:01
Dear Kartik Agaram,

The email sent to danielm@tinyhub.tk with subject
"Re: [neovim] Assertion `!(handle->flags & (UV_CLOSING | UV_CLOSED))'"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by tarruda** [comment] 2015-09-09 03:08
@akkartik yes, the abort happens on @c75d501

Closing since it's fixed on latest master

**Comment by akkartik** [comment] 2015-09-09 03:09
:+1:

**Closed by tarruda** 2015-09-09 03:08 UTC
Labels: bug

**Comment by XiaoPengYouCode** [comment] 2023-10-13 02:08
I find the problem when I try to writing an exist file under a git repo
