### ISSUE TITLE
Windows: TUI: messed up screen after resizing :terminal

### ISSUE THREAD

**Issue by symphony2014** [neovim/neovim#9016] opened 2018-09-19 02:34 UTC
- `nvim --version`:
- Vim (version: ) behaves differently?
- Operating system/version:
   windows 10
- Terminal name/version:
    nvim 0.3.1
- `$TERM`:

### Steps to reproduce using `nvim`

1.  Just start nvim from windows 10 cmd.
2.  start the :terminal mode.
3.  **npm start**.
4.   Win+upRow resize the nvim window.

### Actual behaviour
The window is weird  : 
![image](https://user-images.githubusercontent.com/6380601/45727738-8a83a680-bbf7-11e8-9b89-add9e22c6e6c.png)

### Expected behaviour

Should be normal window.

**Comment by justinmk** [comment] 2018-09-19 05:49
https://github.com/neovim/neovim/pull/8462 improves the Windows TUI.

**Comment by erw7** [comment] 2018-09-21 18:31
I think the cause of this issue is that `winpty` is unable to read the attributes that `libuv` wrote using the [`Console Virtual Terminal Sequence`](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences). Therefore #8462 does not solve this problem. 

I think it is necessary to fix `libuv` so that it does not use `Console Virtual Terminal Sequence` when it is executed under `winpty-agnet.exe` to fix this problem.

 In `Windows 10 October 2018 Update` or later, if `winpty` uses [`ConPTY`](https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/) (rprichard/winpty#152) or `neovim` uses `ConPTY` instead of `winpty`, I think that this problem will be fixed.

Although it is Japanese information(vim-jp/issues#1183), it seems that `vim` already tried implementation using `ConPTY` with terminal command.

**Comment by erw7** [comment] 2018-11-05 11:14
@symphony2014 I forgot to ask, can you check if the phenomenon is reproduced with vim?

**Comment by symphony2014** [comment] 2018-11-06 10:19
@erw7 ,  the vim is also messed up,  but seem like a little different . 
![image](https://user-images.githubusercontent.com/6380601/48058034-6f451880-e1f0-11e8-8ed5-427733d34bb8.png)

**Comment by erw7** [comment] 2018-11-07 09:53
@symphony2014 I think it is due to the difference between the `nvim` and `vim` `:termninal` commands. Try starting the terminal with the `:terminal ++curwin` command on vim and trying out the problematic operation.

**Closed** 2020-01-17 11:59 UTC
Labels: bug, display, platform:windows, tui
