### ISSUE TITLE
netrw scp bug in neovim v0.9.1 windows 

### ISSUE THREAD

**Issue by jamesdbrenton** [neovim/neovim#23962] opened 2023-06-08 22:22 UTC
### Problem

/C/Users/brento01/AppData/Local/Temp/nvim.0/4E3fd4/0.bashrc: No such file or directory

suggesting failure to create temporary file and temporary directory

### Steps to reproduce

nvim --clean scp://test/02_ssh.sh

where test is remote alias in .ssh\config and ssh-agent is running

scp test:.02_ssh.sh . 

works without problem 

Alternative rsa key without passkey reproduces same error (so not ssh problem)

No log entry corresponding to error message above

NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info

### Expected behavior

Identical commands work as remote editing in nvim 0.9.1 on linux

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

Don't have vim

### Operating system/version

windows 10

### Terminal name/version

terminal

### $TERM environment variable

Not applicable

### Installation

choco install neovim

**Comment by farnoy** [comment] 2024-01-14 17:11
Seeing this on `NVIM v0.10.0-dev-2080+g92c59c39c`

The problem is with the `scp` invocation, it looks like this on my end:

```
:!scp -q "user@host:file" "/C/Users/Kuba/AppData/Local/Temp/nvim.0/1ZaILY/7"
/C/Users/Kuba/AppData/Local/Temp/nvim.0/1ZaILY/7: No such file or directory                                                                                                                                                                                                                                                                                                           
```

If it was using `C:/Users/...` for the temporary path, it would have worked. This is why directory listings work on my end, but opening a file doesn't

**Comment by clason** [comment] 2024-01-14 17:13
Please test the latest Vim; we use exactly the same plugin as Vim, so these issues should be reported to the maintainer if it's not Neovim-specific.

**Comment by farnoy** [comment] 2024-01-14 17:21
Yeah, the same issue happens on Vim as well. Don't think it's getting fixed anytime soon

* https://github.com/vim/vim/issues/5199
* https://github.com/vim/vim/issues/3762

**Comment by clason** [comment] 2024-01-14 17:24
You need to contact the maintainer of this plugin, Charles E. Campbell. See http://www.drchip.org/astronaut/vim/index.html#NETRW (Unfortunately, you can contact him only via email under the address listed at the top of the netrw files.)

Any fixes he makes will be included in Vim, and we sync those changes. These are the **only** changes these files will ever get.

**Closed by clason** 2024-01-14 17:24 UTC
Labels: bug, platform:windows, netrw
