### ISSUE TITLE
inline virt_text which occupies virtual columns

### ISSUE THREAD

**Issue by resolritter** [neovim/neovim#16466] opened 2021-11-30 01:08 UTC
### Feature already in Vim?

No

### Feature description

# Problem

As described in https://github.com/neovim/neovim/pull/13952, with the relevant part for this feature highlighted in bold:

> This implements the first alternate display mode for virtual text: overlays. These can change the display of existing columns within a line, but **cannot insert/conceal columns** (the later affects quite a lot in the code, such as plines column calculation)

Here is a comparison of use-cases being covered by the current APIs:

![image](https://user-images.githubusercontent.com/17429390/143965722-5ba08725-e5d4-4824-a203-871781b64321.png)
_From https://jdhao.github.io/2021/09/09/nvim_use_virtual_text/_

It is currently not possible to have a mark which displaces text, i.e. occupies real columns, such as the decorations used for "parameter hints" in Visual Studio Code.

![image](https://user-images.githubusercontent.com/17429390/143965949-b8144cfe-4a35-4305-9c43-444edbcc0559.png)

# Solution

Create an API for arbitrary virtual text which occupies columns, just like "normal" text does

# Use-cases

- Inline type hints, as discussed in e.g. https://github.com/fannheyward/coc-rust-analyzer/issues/394#issuecomment-878238966

- Inline action items, such as a lightbulb for code actions

- Completion preview: instead of inserting the completion item's text, instead shown an inline preview using a virtual extmark

---

I am aware of https://github.com/neovim/neovim/issues/1767 but what is being requested in that issue is not clear. It's quite an old issue and, since then, virt_lines, overlays, EOL virtual text, etc. have all been implemented as "decorations", thus I think it could be closed in favor of more specific issues such as this one.

**Comment by mjlbach** [comment] 2021-11-30 01:11
I *feel* like this is a dupe, but I can't find the tracking issue. This is commonly called "anticonceal" and bfredl has been working on it in https://github.com/neovim/neovim/pull/9496

**Comment by zeertzjq** [comment] 2021-11-30 01:15
> It is currently not possible to have a mark which displaces text, i.e. occupies real columns, such as the decorations used for "parameter hints" in Visual Studio Code.

This is not a good example as this should be currently possible. Several plugins have this feature using normal text.

**Comment by resolritter** [comment] 2021-11-30 01:22
I agree with https://github.com/neovim/neovim/issues/16466#issuecomment-982187095, it seems like this request is related to https://github.com/neovim/neovim/pull/9496.

> This is not a good example as this should be currently possible. Several plugins have this feature using normal text.

Inline virtual text **which occupies columns** is not possible. It is possible to have virtual text which **overlays** existing columns, but it is not suitable for the use-cases being described in the OP.

**Comment by hrsh7th** [comment] 2021-11-30 01:24
Related https://github.com/neovim/neovim/issues/15291

**Comment by zeertzjq** [comment] 2021-11-30 01:24
I mean this can be implemented using normal text.

**Comment by zeertzjq** [comment] 2021-11-30 01:26
I mean your example doesn't necessary require virtual text. It can be implemented using normal text and extmarks.

**Comment by resolritter** [comment] 2021-11-30 01:34
> I mean your example doesn't necessary require virtual text. It can be implemented using normal text and extmarks.

Tampering with the buffer's characters for UI is not reasonable as shown extensively on EasyMotion e.g. https://github.com/easymotion/vim-easymotion/issues/402. This problem is grave enough that it prompted the creation of new plugins such as [hop.nvim](https://github.com/phaazon/hop.nvim#motivation) which uses virtual text instead of editing the buffer.

Yes, a plugin could insert useless space and use `virt_text_pos="overlay"` on top of that, but it would be worse for multiple reasons. It's not a reasonable alternative.

**Comment by resolritter** [comment] 2021-11-30 01:35
I think it would be fine to reopen https://github.com/neovim/neovim/issues/15291 or keep this one open. https://github.com/neovim/neovim/issues/15291#issuecomment-894308927 says

> Duplicate of #9496

#9496 is a PR, not a ticket. You don't put feature requests in a PR, so there's value in having at least one tracking issue open.

**Comment by mjlbach** [comment] 2021-11-30 01:36
I think everyone recognizes the need/value for anticonceal, it's more that bjorn is the only person who is likely to implement this in any reasonable timespan and he's already aware of the demand.

**Comment by resolritter** [comment] 2021-11-30 01:44
> I think everyone recognizes the need/value for anticonceal, it's more that bjorn is the only person who is likely to implement this in any reasonable timespan and he's already aware of the demand.

Understandable. Since https://github.com/neovim/neovim/issues/15291 has come up in the past, I suggest at least one of them is kept open for the sake of making it easier to find - https://github.com/neovim/neovim/pull/9496 is not since mostly only contributors are aware of that. Feature requests are put in issues, so one would search for duplicate open tickets here, not in the PRs.

**Comment by mjlbach** [comment] 2021-11-30 01:45
What about #15706?

**Comment by resolritter** [comment] 2021-11-30 01:52
https://github.com/neovim/neovim/issues/15706 says

> this feature request is about a mechanism to allow concealing of (e.g.) simple markup syntax when using treesitter highlighting. This would remove the need for a dual approach of TS-based highlighting in combination with the regex-based syntax-region definitions.

It's not explicitly asking for the same thing and it's harder to understand what the request is. The way this issue is worded assumes no knowledge of conceal in order to find it.

If this feature covers the use-case of https://github.com/neovim/neovim/issues/15706 then https://github.com/neovim/neovim/issues/15706 could be closed. I am not sure because it talks about tree-sitter and character concealing (as in [hiding characters](https://github.com/neovim/neovim/issues/15706#issuecomment-922253840)), which has nothing to do with this.

**Comment by bfredl** [comment] 2021-11-30 07:56
duplicate of #9496 . I agree the title was a bit obscure and hard to search for, so I updated it.

**Closed by bfredl** 2021-11-30 07:56 UTC
Labels: enhancement, display, extmarks
