### ISSUE TITLE
Intermittent coredump on window resize

### ISSUE THREAD

**Issue by leelavg** [neovim/neovim#16568] opened 2021-12-08 05:27 UTC
### Neovim version (nvim -v)

NVIM v0.6.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by runner@fv-az32-74  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

not using vim

### Operating system/version

Fedora 35

### Terminal name/version

tmux 3.2a

### $TERM environment variable

tmux-256color, all `OK` in `checkhealth`

### Installation

from github releases page

### How to reproduce the issue

- I suspect [this](https://github.com/leelavg/dotfiles/commit/3c2e6df469ab4b5ec581e5e7491e0370b9ac0f95) is the faulty commit in my rc file
- It already coredump'd twice with this commit and without that config it doesn't
- This is the first time I'm dealing with coredump so don't know my way to analyse the same

### Expected behavior

- No coredump

### Actual behavior

- Coredump'd
- [core.nvim.0.4d2d6a9339bd49a5a9cc92059bcc993a.346870.1638939664000000.zip](https://github.com/neovim/neovim/files/7673597/core.nvim.0.4d2d6a9339bd49a5a9cc92059bcc993a.346870.1638939664000000.zip)

**Comment by zeertzjq** [comment] 2021-12-08 06:49
You can try [these steps](https://github.com/neovim/neovim/wiki/FAQ#backtrace-linux) to obtain a backtrace.

**Comment by leelavg** [comment] 2021-12-08 06:58
@zeertzjq 

- thanks for quick reponse, attached backtrace
- [bt.txt](https://github.com/neovim/neovim/files/7673948/bt.txt)

let me know if more info is required,

**Comment by zeertzjq** [comment] 2021-12-08 07:14
What were you doing in Nvim when the crash happened?

**Comment by leelavg** [comment] 2021-12-08 07:37
- There were four windows in a single tab
- And each buffer in the window corresponds to four different files
- And each golang file (configured with lsp) corresponds to four different projects 😅 
- So, when I switched windows (after many times) nvim coredump'd
- I suspect [this](https://github.com/leelavg/dotfiles/commit/3c2e6df469ab4b5ec581e5e7491e0370b9ac0f95#diff-b1cda13c757b5610248eb21c1a8b3b8d9b9c64add71e2b60297c50e2fe065036R289) is too heavy 🤔

**Comment by zeertzjq** [comment] 2021-12-08 07:51
What autocommands does `:autocmd VimResized` list?

**Comment by leelavg** [comment] 2021-12-08 08:51
Below are related to resizes that I use

``` vim
nnoremap <silent> <leader>= :wincmd _<cr>:wincmd \|<cr>
nnoremap <silent> <leader>- :wincmd =<cr>
autocmd VimResized * :wincmd =
```

**Comment by zeertzjq** [comment] 2021-12-08 09:08
`CursorMoved` should be irrelevant here, as you didn't define the autocommand correctly: it is only triggered if the buffer name is "silent", and will cause an `E16: Invalid range` error if triggered.

**Comment by leelavg** [comment] 2021-12-08 09:16
> as you didn't define the autocommand correctly
- hehe, thanks for pointing that out 🥲

**Comment by erw7** [comment] 2021-12-08 10:09
May be duplicate of #13900.

**Comment by leelavg** [comment] 2021-12-13 02:58
- ack, I'm resizing the windows cautiously and didn't observe the coredump recently

**Comment by eyalk11** [comment] 2021-12-15 18:12
Probably duplicate of #16458

**Closed** 2022-04-23 16:31 UTC
Labels: tui, status:has-backtrace, bug-crash, closed:duplicate
