### ISSUE TITLE
Cursor column jumps when navigating in documentation

### ISSUE THREAD

**Issue by rpeshkov** [neovim/neovim#8713] opened 2018-07-09 21:57 UTC
- `nvim --version`: NVIM v0.3.0
- Vim (version: 8.0.1283) behaves differently? yes
- Operating system/version: MacOS 10.13.5
- Terminal name/version: iTerm2 Build 3.1.7, Terminal 2.8.2
- `$TERM`: xterm-256color, screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:h 'formatoptions'
3j " move down to letter 'i' in word 'which'
```

### Actual behaviour

Next movement down will change the cursor column. Cursor is placed on letter 'f' of 'fo-table' link. Next movement down will change the cursor column once again. Cursor will be placed on ' (apostrophe). Movement up works the same way. So, when cursor is placed on the link, its column changed. Also, try to move column when cursor is on link 'fo-table'. When you move left and reach 'f', you need to push `h` or `left` twice. Same with moving right - when you reach '.' you need to push `l` or `right` twice.

### Expected behaviour

When moving down and up through links in documentation, cursor column should not change. When moving left and right, there should not be places when you need to push the button double time.

**Comment by mhinz** [comment] 2018-07-09 22:20
It's the same for Vim.

The difference is that Nvim uses `filetype plugin on` by default and Vim does not. You can reproduce it with Vim: `vim -Nu NORC +"syntax on | filetype plugin on | h 'fo'"`

What it happens might be confusing at first, but it's not if you use `:set ft=` in the help buffer. The conceal feature merely _hides_ the `|` characters around "fo-table", but the characters are still there. Go over the `i` in `describes` and then go down and you'll notice it will be off by 2 now, since there are 2 hidden `|` in the line.

**Comment by mhinz** [comment] 2018-07-09 22:23
Since we share the runtime files with Vim (in this case: https://github.com/vim/vim/blob/6259e5769dd50d8a3b5b99f553bab34ff5c8a6ce/runtime/ftplugin/help.vim#L18) and the way the cursor addressing works won't change, I'm closing this.

**Closed by mhinz** 2018-07-09 22:23 UTC

**Comment by rpeshkov** [comment] 2018-07-09 22:32
> You can reproduce it with Vim: vim -Nu NORC +"syntax on | filetype plugin on | h 'fo'"

Nope, it's not reproducible on my machine. Launched what you provided, except that I used /usr/bin/vim to launch real vim (I have alias vim -> nvim) and I don't see this behaviour.

**Comment by mhinz** [comment] 2018-07-09 22:40
Because Apple ships a Vim has a few features not compiled in.

```
$ /usr/bin/vim --version | grep conceal
-conceal         +libcall         -profile         +visualextra
```

This should be `+conceal`, though.

That's why [this code](https://github.com/vim/vim/blob/6259e5769dd50d8a3b5b99f553bab34ff5c8a6ce/runtime/ftplugin/help.vim#L17-L19) never gets executed. But it's the `set conceallevel=2` that makes the difference that you see.
