### ISSUE TITLE
Multi-character emojis mess up cursor on the same line

### ISSUE THREAD

**Issue by WhyNotHugo** [neovim/neovim#18823] opened 2022-06-01 10:00 UTC
### Neovim version (nvim -v)

NVIM v0.7.0

### Vim (not Nvim) behaves the same?

no, vim misrenders multi-character emojis entirely

### Operating system/version

Linux 5.18.1-arch1-1 GNU/Linux

### Terminal name/version

foot, alacritty

### $TERM environment variable

foot, alacritty

### Installation

Official arch packages

### How to reproduce the issue

- Insert `🇳🇱 Netherlands`.
- Press `0w`. The cursor no displays in the middle of the second word.
- Press `ixx`. The line now renders `🇳🇱 Ne  Netherlands`.
- Save the file (`:w test`)
- Cat the file (`cat test`) The file reads `🇳🇱   Netherlands`

### Expected behavior

What neovim renders on screen should match the in-memory buffer and what's saved to disk.

### Actual behavior

Looks like neovim gets confused as to the position of the cursor and content and also renders content wrong on-screen.

**Comment by WhyNotHugo** [comment] 2022-06-01 10:01
Tested on `foot` and `alacritty`.  `helix` and `zsh` do not have this issue on the same terminals, so pretty I'm sure it's not a terminal issue.

**Comment by zeertzjq** [comment] 2022-06-01 10:14
Duplicate of #16447

**Closed by zeertzjq** 2022-06-01 10:14 UTC
Labels: bug
