### ISSUE TITLE
autowrite / autowriteall not functional for some events

### ISSUE THREAD

**Issue by alex-courtis** [neovim/neovim#17139] opened 2022-01-19 04:54 UTC
### Neovim version (nvim -v)

v0.6.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

linux 5.15.12-arch1-1

### Terminal name/version

alacritty 0.9.0 (fed349aa)

### $TERM environment variable

tmux-256color

### Installation

Arch User Repository

### How to reproduce the issue

nvim --clean file1 file2
`:set awa`
make a change in file1
`:n`
`:b#`
note that file1 has not been written

### Expected behavior

`autowrite` and `autowriteall` cause the buffer to be written when the documented events occur e.g. `:next`, `:quit`

### Actual behavior

The following `autowrite` events are not functioning:
* next
* previous
* rewind
* buffer

`autowriteall`:
* enew
* edit

first and last are functioning, but only if the active buffer is the first or last

**Comment by zeertzjq** [comment] 2022-01-19 04:57
Duplicate of #16470

**Comment by zeertzjq** [comment] 2022-01-19 04:57
```
	A buffer is not written if it becomes hidden, e.g. when 'bufhidden' is
	set to "hide" and `:next` is used.
```

**Closed by zeertzjq** 2022-01-19 04:57 UTC
Labels: bug

**Comment by alex-courtis** [comment] 2022-01-19 05:35
> This doc hasn't been backported to v0.6.1:
> 
> ```
> 	A buffer is not written if it becomes hidden, e.g. when 'bufhidden' is
> 	set to "hide" and `:next` is used.
> ```

Thanks for letting me know.
