### ISSUE TITLE
segfault with alpinelinux + neovim 0.8.1(no plugin) + term://fish

### ISSUE THREAD

**Issue by guijun** [neovim/neovim#21280] opened 2022-12-04 03:51 UTC
### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

alpine linux 3.16

### Terminal name/version

tmux 3.2

### $TERM environment variable

xterm-256color

### Installation

apk add neovim fish

### How to reproduce the issue

remove init.lua
apk add fish
# fish -v = 3.5.1
nvim
sp term://fish
crashed:
Segmentation fault.

can't reproduce with neovim v0.7.0

### Expected behavior

stable

### Actual behavior

crash

**Comment by clason** [comment] 2022-12-04 10:40
Can't reproduce on macOS with `master`.

**Comment by guijun** [comment] 2022-12-06 01:06
Can't reproduce on the same system with vim 8.2.5000

**Comment by felippemr** [comment] 2023-01-03 19:49
I'm having a similar issue while performing a "Live Grep" on a aarch64 OSX using neovim 0.9.0-dev.

**Comment by felippemr** [comment] 2023-01-03 19:52
Going back to neovim v0.8.2 solved the issue for me.

**Comment by guijun** [comment] 2023-01-14 09:16
reroduced again. after upgrade.
 but
 the issue gone if :
 apk del neovim
 apk add neovim

**Comment by justinmk** [comment] 2023-01-14 18:52
needs a repro or at least a backtrace

**Comment by dundargoc** [comment] 2023-01-14 19:06
Couldn't recreate it in docker with the following code:

```
FROM alpine:3.16

RUN apk add build-base cmake automake autoconf libtool pkgconf coreutils curl unzip gettext-tiny-dev git ninja fish
RUN git clone --depth=1 https://github.com/neovim/neovim.git home/neovim
WORKDIR home/neovim
RUN make install
```

**Comment by felippemr** [comment] 2023-01-26 20:00
The issue seems to be fixed on the latest master.

**Closed** 2023-02-21 15:44 UTC
Labels: platform:other, terminal, needs:response, bug-crash
