### ISSUE TITLE
Windows: pasting from clipboard adds a blank line

### ISSUE THREAD

**Issue by yoava333** [neovim/neovim#4706] opened 2016-05-03 22:48 UTC
- Neovim version: 1.5-dev
- Vim behaves differently? Vim version: 9.3+
- Operating system/version: Windows 10 x64
- Terminal name/version: nvim-qt
- `$TERM`: n/a
### Actual behaviour

pasting from the system clipboard adds a new line even if I copied characters

```
texttocopy
texttocopy
```
### Expected behaviour

pasted content pasted without the blank line

```
texttocopytexttocopy
```
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# starting from normal mode
i
texttocopy<esc>
"+yiw
"+yP
```

**Comment by equalsraf** [comment] 2016-05-04 08:22
Cheers @yoava333

I think @brcolow reported something similar a while back, but I think his example was harder. A few things to keep in mind

- Windows clipboard support is only present in #810 using [win32yank](https://github.com/equalsraf/win32yank)
- win32yank is replacing newline chars (https://github.com/neovim/neovim/pull/810/commits/1e7b889c78d64849cc8fa54646ad2111bf83981f) maybe that is the cause of the issue (on paste \r\n turns into \n and vice versa)

First thing to do is figure out whether its the yank operation that is placing the additional newline or if its the paste operation. @yoava333 what happens if you yank the text in Neovim and then paste it into another application like notepad of even gVim? And what happens if you copy a word off another app and then paste in Neovim?

PS: maybe change the title to `windows: pasting from clipboard adds a blank line` and add the platform tag

**Comment by yoava333** [comment] 2016-05-15 21:35
sorry for the delay in response.
copying a word from neovim to notepad (e.g. "+yiw) and paste in notepad I get the text without the new line.

**Comment by harila** [comment] 2016-07-19 05:29
Got this bug also. Very annoying, cannot really predict what pasting from windows clipboard will do. Almost have to use basic vim until this is resolved.

**Comment by equalsraf** [comment] 2016-07-19 09:57
Not on windows right now, can any one try replacing win32yank.exe with this binary and see if it fixes the issue?

https://ci.appveyor.com/project/equalsraf/win32yank/build/36/artifacts

**Comment by yoava333** [comment] 2016-07-19 11:09
@equalsraf still not working.

**Comment by gaving** [comment] 2016-07-19 12:14
@yoava333 @equalsraf seems to be fixed with that here!

**Comment by lazmol** [comment] 2017-01-09 12:34
Had the same problem on win7 with NVIM v0.1.6. Replaced win32yank.exe in the bin dir by the one given by @equalsraf and the yank-paste works without additional newline. Thanks!

**Comment by yoava333** [comment] 2017-01-11 08:35
works for me too, thanks!

**Comment by equalsraf** [comment] 2017-01-24 00:06
This should now be fixed in the master branch.

**Comment by harila** [comment] 2017-01-24 06:50
Nice, Ill start moving to neovim on day to day use. I'll report if there is more problems with copy pasting.

**Closed** 2017-01-24 07:13 UTC
Labels: platform:windows

**Comment by hanxi** [comment] 2017-08-28 07:47
fixed with this  https://github.com/extr0py/oni/issues/176#issuecomment-274275304
```
set clipboard=unnamed
```
