### ISSUE TITLE
conflict between :set nowrap and 3g$

### ISSUE THREAD

**Issue by icyhat** [neovim/neovim#10268] opened 2019-06-18 22:05 UTC
- `nvim --v0.3.7`:
- Operating system/version: Arch tty
- Terminal name/version:
- `$TMUX`:

### Steps to reproduce using `nvim -u NORC`
`3g$` => moving cursor to next 2 lines' last char
### Actual behaviour
`3g$` => moving cursor to current line's last char
### Expected behaviour
`3g$` => moving cursor to next 2 lines' last char

As I finally realize that I don't need `set nowrap` in `init.vim`, I delete this command in `init.vim`.And the world became perfect again.

But somehow, I'm happy to feedback the err information even it looks like low priority to fix.

: )

**Comment by blueyed** [comment] 2019-06-18 23:16
Is Vim behaving in the same way?

**Comment by icyhat** [comment] 2019-06-19 15:51
> Is Vim behaving in the same way?

Yes. 
1. I install vim => `3g$` works OK whther `.vimrc` exists.
2. `3g$` works ERR,  when I add `set nowrap` in `.vimrc`.

**Comment by blueyed** [comment] 2019-06-19 17:21
Please report an issue over there then: https://github.com/vim/vim/issues/new

**Comment by glacambre** [comment] 2021-06-06 07:35
Can't reproduce on master, must be fixed, closing :).

**Closed by glacambre** 2021-06-06 07:35 UTC
Labels: 0.kind: bug-vim, 2.status: upstreamed
