### ISSUE TITLE
cmdheight=0 doesn't show the recording macro.

### ISSUE THREAD

**Issue by ayoubelmhamdi** [neovim/neovim#27928] opened 2024-03-19 09:40 UTC
### Problem

when we use `set cmdheight=0`  we can not see the recording macro in the status line.

### Steps to reproduce

```vim
:set cmdheight=0
qq
```

### Expected behavior

i expected the same UI as vanilla vim that maybe use `cmdheight=1` and the `recording macro` is appeared in the status line.

![image](https://github.com/neovim/neovim/assets/34358145/7a513888-204b-455b-bff9-7399bf0153d2)

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

NVIM v0.9.5

### Operating system/version

void linux

### Terminal name/version

st

### $TERM environment variable

st-256color

### Installation

xbps

**Comment by zeertzjq** [comment] 2024-03-19 09:45
Duplicate of #19193

**Closed by zeertzjq** 2024-03-19 09:45 UTC
Labels: bug

**Comment by zeertzjq** [comment] 2024-03-19 09:49
If you want the same behavior as Vim you should set `cmdheight=1 laststatus=1` instead.
