### ISSUE TITLE
cursor skips lines on auto hide virtual lines

### ISSUE THREAD

**Issue by A-Lamia** [neovim/neovim#22705] opened 2023-03-17 12:14 UTC
### Problem

Not sure if this is a bug or just a side effect of 2 functionalities not interacting well, with the plugin virtual lines you can display LSP diagnostics as lines and make the visible only on the current line, an issue i have found is that when moving down lines are being skipped because the lines disappear.

I'm not sure if there is anything here to be fixed or if there is anything i can do to ensure the cursor goes where it should 

https://user-images.githubusercontent.com/6450181/225901318-d0834f46-28fd-42a9-9b9d-10723dc85639.mp4

The main developer (@WhyNotHugo) is also aware of this and has said it is a neovim issue https://todo.sr.ht/~whynothugo/lsp_lines.nvim/25,
i did look to check if a post was made here but couldn't find one.

### Steps to reproduce

installed lsp virtual lines and enabled only_current_lines, create an error on your current line then move down.

### Expected behavior

for the cursor to move down 1 line instead of the offset of how ever many errors there is.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1230+gd1e0f7454

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

Neovide

### $TERM environment variable

xterm-256color

### Installation

scoop

**Comment by justinmk** [comment] 2023-03-17 12:28
Need minimal steps to repro (without installing plugins).

**Comment by zeertzjq** [comment] 2023-03-17 12:35
Duplicate of #22704

**Closed by zeertzjq** 2023-03-17 12:35 UTC
Labels: bug, needs:response, needs:repro, extmarks
