### ISSUE TITLE
windows installer (msi) installs incorrect version

### ISSUE THREAD

**Issue by MoritzStw** [neovim/neovim#19269] opened 2022-07-07 13:35 UTC
### Neovim version (nvim -v)

0.7.2/0.6.1

### Vim (not Nvim) behaves the same?

No

### Operating system/version

windows

### Terminal name/version

powershell

### $TERM environment variable

not applicable

### Installation

Installed via nvim-win32.msi installer from github (https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-win64.msi)

### How to reproduce the issue

Download https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-win64.msi
Execute Installer
Navigate to installtion folder
Execute ./nvim.exe -v
Execute nvim-qt.exe
Run :version
Run :lua print(vim.keymap)

### Expected behavior

The MSI Installer installs version 0.7.2
./nvim.exe -v reports:

    NVIM v0.7.2
    Build type: RelWithDebInfo
    LuaJIT 2.1.0-beta3
    Übersetzt von runneradmin@fv-az276-503
    
    Features: -acl +iconv +tui
    See ":help feature-compile"
    
              System-vimrc-Datei: "$VIM\sysinit.vim"
         Voreinstellung für $VIM: "C:/Program Files/nvim/share/nvim"
    
    Run :checkhealth for more info

:version reports NVIM v0.7.2 [...]
:lua print(vim.keymap) prints table identifier

Remark: the nvim-win32.zip file contains the correct version of neovim

### Actual behavior

The MSI Installer installs version 0.6.1

./nvim.exe -v reports:

    NVIM v0.6.1
    Build type: RelWithDebInfo
    LuaJIT 2.1.0-beta3
    Übersetzt von runneradmin@fv-az152-430
    
    Features: -acl +iconv +tui
    See ":help feature-compile"
    
              System-vimrc-Datei: "$VIM\sysinit.vim"
         Voreinstellung für $VIM: "C:/Program Files/nvim/share/nvim"
    
    Run :checkhealth for more info

:version reports version NVIM v0.6.1  [...]
:lua print(vim.keymap) prints nil

Remark: the nvim-win32.zip file contains the correct version of neovim

**Comment by sitiom** [comment] 2022-07-24 12:35
I can't reproduce this. The MSI installer installs `0.7.2` correctly. Do you have Neovim installed through other means, like Chocolatey or Scoop (or adding Neovim manually to PATH)?

**Comment by MoritzStw** [comment] 2022-07-24 13:07
I had installed Neovim before 0.7.2 release either manually via the zip file or via winget.
Then arround 2022-07-07 i became aware of the lua vim.keymap feature and i wanted to try it.
I first tried to update Neovim via winget. It still reported the 0.6.1 version
Next I tried to install Neovim via the msi-installer (I did not remove any installed files before hand). It still reported 0.6.1
Last I installed manually via the zip installer. Now I had the correct version installed.
Then I wrote the ticket.

Today I uninstalled neovim via system controll and then manually deleting the folder (C:/Program Files/Neovim) and installed neovim fresh from the file i downloaded on the 7th. It installed the correct version.

Apparently the installer can install the correct version. What went wrong on the 7th I dont know.

**Comment by sitiom** [comment] 2022-07-24 13:12
Can you run `where nvim.exe` from the command prompt and report the output? It should look like this:
```console
> where nvim
C:\Program Files\Neovim\/bin\nvim.exe
```

**Comment by MoritzStw** [comment] 2022-07-24 13:17
Running from cmd:
`C:\Users\morit>where nvim
C:\Program Files\Neovim\bin\nvim.exe`

**Comment by sitiom** [comment] 2022-07-24 13:23
Weird, it seems like everything is working fine now. Inspecting the MSI from the releases, there is no trace of `Neovim 0.6.1` inside, so I don't know how this is possible in the first place.

You should close this issue now. Feel free to reopen it if you can reproduce it again.

**Closed** 2022-07-24 13:23 UTC
Labels: bug, platform:windows, distribution
