### ISSUE TITLE
windows: echo has('python3') always returns 0

### ISSUE THREAD

**Issue by prabirshrestha** [neovim/neovim#5360] opened 2016-09-19 00:44 UTC
- `nvim --version`: NVIM v0.1.6-119-g7b6786f (release build)
- nvim (version: ) behaves differently? NVIM 0.1.5-dev (release build)
- Operating system/version: windows 10 x64
- Terminal name/version: nvim-qt
- `$TERM`:
- Python 3.5.2
### Actual behaviour

0
### Expected behaviour

1
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:echo has('python3')
```

When I download the latest master nvim version seems like it always crashed. After trying out NORC I noticed that `:echo has('python3')` always returns 0.

**Comment by equalsraf** [comment] 2016-09-19 08:04
> nvim (version: ) behaves differently? NVIM 0.1.5-dev (release build)

Do you mean this was working ok in 0.1.5 from master? Or was it one of the other builds in appveyor? It would make sense if it was some build from #810.

@prabirshrestha out of the top of my head I suspect https://github.com/neovim/neovim/pull/5280 might fixe this, can you try it?

Also if you have both python 2 and 3 in your path, you might have to set `g:python3_host_prog` because of https://github.com/neovim/neovim/issues/5293

**Comment by prabirshrestha** [comment] 2016-09-20 05:41
By master I mean from appveyor mentioned in https://github.com/neovim/neovim/issues/5229
 https://ci.appveyor.com/api/projects/neovim/neovim/artifacts/build/Neovim.zip?branch=master&job=Configuration%3A%20MINGW_64 

I can't remember exactly where I got 0.1.5 build but I think it was from older #810 build. Tried the latest one and that didn't work out too. #5280 didn't work too.

I do have both python3 and python2 on my path. Python3 comes first. I tried setting `g:python3_host_prog` just the folder as well as with .exe and it didnt work.

```
let g:python3_host_prog = `C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python35\\python.exe`
```

**Comment by equalsraf** [comment] 2016-09-20 09:44
What about python2 does it work?

> I can't remember exactly where I got 0.1.5 build but I think it was from older #810 build.

Ok that makes sense.

> let g:python3_host_prog = `C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python35\\python.exe`

I don't think you need double slashes when using single quotes.

**Comment by justinmk** [comment] 2016-09-20 10:09
let g:python3_host_prog = `C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python35\\python.exe`

@prabirshrestha That code shows backticks. You must use single-quotes (`'`). And as @equalsraf mentioned escaping the slashes in single-quotes isn't needed.

**Comment by zovt** [comment] 2016-09-20 17:56
Just wanted to chime in saying that I'm experiencing the same thing. python, python2, and python3 are all valid bin names, with python pointing to python 3. 

nvim version
```
Compilation: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /O2 /Ob2 /D NDEBUG -DDISABLE_LOG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/deps64/usr/include -IC:/projects/neovim/deps64/usr/include -IC:/projects/neovim/deps64/usr/include/luajit-2.0 -IC:/projects/neovim/deps64/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor-vmppveyor@appveyor-vm
```

**Comment by equalsraf** [comment] 2016-09-20 18:22
@zovt  and does #5280 help with any of those?

**Comment by zovt** [comment] 2016-09-20 18:26
@equalsraf That did indeed! Everything is good now, thanks!

**Comment by equalsraf** [comment] 2016-09-20 18:28
@zovt, does it work for python2 and python3?

**Comment by zovt** [comment] 2016-09-20 20:53
@equalsraf yes sir, everything is up and running

**Comment by prabirshrestha** [comment] 2016-09-20 21:26
Fixed the quotes but it still doesn't work. This is the only line of code I have in my init.vim
```
let g:python3_host_prog = 'C:\Users\username\AppData\Local\Programs\Python\Python35\python.exe'
```

I'm downloading the neovim x64 binaries from https://ci.appveyor.com/project/neovim/neovim-1kmqj/build/8268 (This is the #5280) and Neovim-qt binaries from staging. https://github.com/equalsraf/neovim-qt/releases

@zovt where did u get the neovim binaries? Did you build it manually or from appveyor.

**Comment by zovt** [comment] 2016-09-20 21:29
I'm using neovim-qt staging and this build from appveyor: https://ci.appveyor.com/project/neovim/neovim-1kmqj/build/8268/job/cpda234xo49y7x3d/artifacts

**Comment by equalsraf** [comment] 2016-09-20 21:56
@prabirshrestha we can't rely on checkhealth just yet. Can you try a couple commands and see how it goes

- `echo system(['python', '-v'])`
- `echo system(['g:python3_host_prog', '-v'])`
- `echo system(['g:python3_host_prog', '-c', 'import neovim'])`

or likewise for python2 just in case

**Comment by prabirshrestha** [comment] 2016-09-21 04:15
`echo system(['python', '-v'])` This prints out bunch of text.

Did you mean `echo system(['python', '--version'])`? This prints `Python 3.5.2` whether I set `let g:python3_host_prog` or not.

`echo system(['g:python3_host_prog', '--version'])` doesn't seem to work. Says g:python3_host_prog is not executable. 
If I remove quotes `echo system([g:python3_host_prog, '--version'])` it says `Python 3.5.2`.

`echo system([g:python3_host_prog, '-c', 'import neovim'])` Nothing happens when I do this which means neovim module is imported correctly.

If I change it to `import bad` then it says `ImportError: no module named 'bad'`.

**Comment by equalsraf** [comment] 2016-09-21 09:51
> Did you mean echo system(['python', '--version'])?

Ups, yes I did, thanks.

> If I change it to import bad then it says ImportError: no module named 'bad'.

So far so good. I guess the next step is to run this function https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/pythonx.vim#L86

```viml
  let prog_ver = system([ 'python', '-c' ,
        \ 'import sys; ' .
        \ 'sys.path.remove(""); ' .
        \ 'sys.stdout.write(str(sys.version_info[0]) + "." + str(sys.version_info[1])); ' .
        \ 'import pkgutil; ' .
        \ 'exit(2*int(pkgutil.get_loader("neovim") is None))'
\ ])
```

**Comment by zovt** [comment] 2016-09-21 23:13
Quick Update, it seems that using the build you linked is breaking Vim Plug. I don't know if it's a Vim Plug issue, since it seems that using a build WITHOUT working python support allows it to work

**Comment by equalsraf** [comment] 2016-09-22 10:16
> since it seems that using a build WITHOUT working python support allows it to work

plug behaves differently when python is on and running Neovim. It would be useful to figure out if this happens because of system()/jobstart() or some other reason. Is there any error message?

> EDIT: I'm also getting the following error with the ruby integration:

I was expecting the ruby provider to be broken (https://github.com/neovim/neovim/pull/5280#issuecomment-244264396). Looking at ruby.vim, the exception handler tries to use channel_id, which might not be defined if jobstart fails, **so this is a bug**.

**Comment by zovt** [comment] 2016-09-22 16:11
Not sure how to enable debug messages in Plug, but I get a `Ruby interface is broken` message and under each plugin an error reading `The filename, directory name, or volume label syntax is incorrect.`

**Comment by prabirshrestha** [comment] 2016-09-23 05:54
This is the only thing I have in my init.vim

```viml
let g:prog_ver = system([ 'python', '-c' ,
        \ 'import sys; ' .
        \ 'sys.path.remove(""); ' .
        \ 'sys.stdout.write(str(sys.version_info[0]) + "." + str(sys.version_info[1])); ' .
        \ 'import pkgutil; ' .
        \ 'exit(2*int(pkgutil.get_loader("neovim") is None))'
\ ])

echom g:prog_ver
echom v:shell_error
```

I then ran `:messages` and here is what I see.

![image](https://cloud.githubusercontent.com/assets/287744/18775462/cbfaad84-8116-11e6-8e12-aefd0ae525b2.png)

My nvim is located at `c:\Users\username\Download\Neovim\bin\nvim.exe` I'm not sure why it is trying to load syntax.vim from Program Files directory.

(I don't have ruby installed)

**Comment by equalsraf** [comment] 2016-09-23 08:21
@prabirshrestha Neovim cannot find the runtime path. You need to either move it to that path, or set $VIMRUNTIME accordingly i.e. for the instalation to be portable we need https://github.com/neovim/neovim/pull/3303

The missing runtime would also explain the inability to setup python2/3, because python is spawned by the python provider in runtime/autoload/provider.

**Comment by prabirshrestha** [comment] 2016-09-25 01:47
Manually update the rtp using `let &rtp=d:/Neovim/share/nvim/runtime` didn't work.

![image](https://cloud.githubusercontent.com/assets/287744/18812355/ad9eecc6-8286-11e6-84f6-97218dcd951b.png)

`:help` is working without or without setting the rtp so I don't think the problem is actually to do with rtp.

**Comment by equalsraf** [comment] 2016-09-25 15:03
> Manually update the rtp using let &rtp=d:/Neovim/share/nvim/runtime didn't work.

I am unsure if it should work, at least for the python case. I believe the result is cached, so setting it manually will probably not work.

**Comment by wsdjeg** [comment] 2016-09-27 12:52
@equalsraf  I can not make neovim support python in win7, here is the test step:
I have only one line in my init.vim
`let g:python_host_prog = 'D:\Python27\python.exe'`
1. echo system(['python', '--version])
I get `Python 2.7.12`
2. echo system([g:python_host_prog', '--version'])
I get `Python 2.7.12`
3. echo system([g:python_host_prog, '-c', 'import neovim'])
I get 
![1](https://cloud.githubusercontent.com/assets/13142418/18873819/c0fb5538-84f3-11e6-92d6-3c639387d3d7.png)
4. echo provider#pythonx#Detect(2)
I get
![2](https://cloud.githubusercontent.com/assets/13142418/18873942/48e496bc-84f4-11e6-85a5-b40c81a8c1af.png)

**Comment by equalsraf** [comment] 2016-09-27 12:58
@wsdjeg are you testing in master or #5280?

**Comment by wsdjeg** [comment] 2016-09-27 13:00
I test it with master. and the zip file is download form https://github.com/neovim/neovim/wiki/Installing-Neovim

**Comment by equalsraf** [comment] 2016-09-27 13:01
Ah ok, the import issue should be fixed in #5280

**Comment by wsdjeg** [comment] 2016-09-27 13:03
thanks,  nice work.

**Comment by wsdjeg** [comment] 2016-09-27 14:08
@equalsraf I think the wiki need to be update, and the default runtime dir is `C:/Program Files (x86)/nvim/share/nvim` instead of `C:/Program Files (x86)/Neovim/share/nvim`.

so  by default we should `Unzip Neovim.zip in C:/Program Files (x86)/nvim/`

**Comment by equalsraf** [comment] 2016-09-30 08:57
@wsdjeg you are right, this changed in https://github.com/neovim/neovim/commit/1a15cf84c29c984d600f438122edc70be2ac91a1

**Comment by prabirshrestha** [comment] 2016-10-30 22:54
@equalsraf any updates on this?

**Comment by justinmk** [comment] 2017-01-09 02:06
Confirmed that #5910 (#5280) fixes this.

**Comment by justinmk** [comment] 2017-01-11 00:11
@prabirshrestha What's the output of:

```
:echo provider#pythonx#Detect(2)
:echo provider#pythonx#Detect(3)
```

**Closed** 2017-01-11 01:19 UTC
Labels: platform:windows
