### ISSUE TITLE
Syntax highlighting not working properly for bash (in master branch)

### ISSUE THREAD

**Issue by therealmaxmoon** [neovim/neovim#22133] opened 2023-02-05 18:41 UTC
### Describe the bug

I accidentally compiled the current master and while using NVIM v0.9.0-dev-869+g964ae205a I figured out that bash scripts look very ugly, like only the first line has nice colors and all other lines are in the same color. 

After checking out stable branch it worked.

### Steps to reproduce

git clone https://github.com/neovim/neovim.git
cd neovim
make CMAKE_BUILD_TYPE=Release
sudo make install
nvim ~/path/to/a/bash/script.sh

### Expected behavior

Colorful text => Correct syntax highlighting

### Neovim version (nvim -v)

v0.9.0-dev-869+g964ae205a

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MX Linux 21.3

### Terminal name/version

rxvt-unicode (urxvt) v9.22

### $TERM environment variable

rxvt-unicode-256color

### Installation

build from repo

**Comment by clason** [comment] 2023-02-05 18:43
can you share an example? bash scripts look fine for me.

(also, always make sure to test with `nvim --clean`)

**Comment by zeertzjq** [comment] 2023-02-05 23:39
Duplicate of https://github.com/vim/vim/issues/11937

**Closed by zeertzjq** 2023-02-05 23:39 UTC
Labels: bug, needs:response

**Comment by therealmaxmoon** [comment] 2023-02-06 00:22
> can you share an example? bash scripts look fine for me.

I completely forgot to create a screenshot before compiling the stable branch. But @zeertzjq posted a duplicate and it looks exactly like the screenshot there.
