### ISSUE TITLE
Opening files from fzf broken since neovim 3.0

### ISSUE THREAD

**Issue by aenda** [neovim/neovim#8560] opened 2018-06-15 14:06 UTC
(Note that this issue is not related to the fzf.vim plugin at all, but the behavior of fzf and neovim when run from the shell).

I have been using the following zsh widget for a while:
```
export FZF_DEFAULT_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || \
cat {} || tree -C {}) 2> /dev/null | head -200'"
# -l '.? ' will omit binary files
export FZF_DEFAULT_COMMAND="rg --files --hidden --smart-case --follow --glob \
\!.git/\* 2> /dev/null"

### Search a file with fzf and then open it in an editor ###
__fsel() {
  local cmd="${FZF_DEFAULT_COMMAND}"
  setopt localoptions pipefail 2> /dev/null
  eval "$cmd" | FZF_DEFAULT_OPTS="--height 70% --reverse $FZF_DEFAULT_OPTS" \
  $(echo "fzf") -m "$@" | while read item; do
    echo -n "${(q)item} "
  done
  local ret=$?
  echo
  return $ret
}
fzf_then_open_in_editor() {
    file="$(__fsel)"
    file_no_whitespace="$(echo -e "${file}" | tr -d '[:space:]')"
    if [ -n "$file_no_whitespace" ]; then
    # Use the default editor if it's defined, default nvim
        ${EDITOR:-nvim} "./${file_no_whitespace}"
    fi;
    zle accept-line
}
zle -N fzf_then_open_in_editor
bindkey "^O" fzf_then_open_in_editor
```
### Expected behavior:
open the selected file in neovim.
### Actual behavior:
open a blank new file in the current directory. (This also happens if I change the script to use `nvim -u NONE`).
I believe that it stopped working as of Neovim 3.0. If I `export EDITOR=vim` and open a file with Ctrl-O, it works fine (even if vim gives `Vim: Warning: Input is not from a terminal`). I read the following head page and saw the change about piping file names to nvim, but I don't think that should cause this issue because I don't pipe the `$file_no_whitespace` variable to nvim.
What is odd is that if I afterwards run `nvim $file_no_whitespace` it will open it just fine and perform the expected behavior.

- `nvim --version`:
```
> /usr/bin/nvim --version 
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconver
sion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pe
dantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector
-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build
/neovim/src/build/config -I/build/neovim/src/neovim-0.3.0/src -I/usr/include -I/build/neovim/src/build/src
/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently?
```
> vim --version
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 25 2018 00:52:08)
Included patches: 1-22
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    +tcl/dyn
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl/dyn          +vertsplit
-clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua/dyn           +ruby/dyn          -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -p
ipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector -rdynamic -Wl,-expo
rt-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relr
o,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl
   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
-fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.26/core_perl/CORE -lperl -lpthread -lnsl -ld
l -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
```

- Operating system/version: Arch Linux
- Terminal name/version: kitty 0.11.0
- `$TERM`: xterm-kitty

**Comment by jamessan** [comment] 2018-06-15 15:45
If you run `:ls` when nvim opens, do you see the file open as another buffer?

**Comment by aenda** [comment] 2018-06-15 22:00
Yep, don't know how I missed that. It opens the file and then one other empty buffer. Do you know the cause/how I could work around it?

**Comment by jamessan** [comment] 2018-06-15 22:48
Duplicate of #8561

**Closed by jamessan** 2018-06-15 22:48 UTC

**Comment by aenda** [comment] 2018-06-18 22:28
I see why `foo | xargs nvim` leads to the empty buffer, but why does `$EDITOR $(command)` (which I think is essentially what I am doing) lead to it? I don't really have a problem with the rationale expressed in https://github.com/neovim/neovim/pull/8576#issuecomment-398086294 for when a pipe is used, but this case seems kind of different to me.

**Comment by justinmk** [comment] 2018-06-19 08:57
> but why does `$EDITOR $(command)` (which I think is essentially what I am doing) lead to it? 

It doesn't, _unless_ you run that from a context where stdin is not a TTY. Can you provide a full example?

**Comment by aenda** [comment] 2018-06-19 18:23
I don't know that much about zsh internals, but I suppose that running that widget counts as "stdin not a TTY". I tested with the above commits from your fork and I have the previous behavior, where no empty buffer is opened (or I suppose it gets deleted before I can see it), which is perfect for me at least.
