### ISSUE TITLE
Accessing remote file through scp

### ISSUE THREAD

**Issue by RRethy** [neovim/neovim#8989] opened 2018-09-13 06:34 UTC
- `nvim --version`: NVIM v0.3.1
- VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  8 2018 13:02:33)

- Operating system/version: MacOS Sierra - Version 10.12.6
- Terminal name/version: Kitty 0.12.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC scp://[user@]machine//absolute/path/to/file.txt
```

### Actual behaviour

An empty buffer is opened without asking for my password.
Upon writing to the file I get the following:

```
:!scp -q '/var/folders/w3/dgzbbn0d1cddqp_f_fqtprtm0000gn/T/nvimSoGsX2/2' '[user@]machine//absolute/path/to/file.txt'
lost connection

shell returned 1
```

### Expected behaviour

If I run the same thing using Vim I am prompted for my password, then it opens up the file.
Upon writing to the file I am prompted for my password and the write works.

## Additional Notes

Very similar behaviour can be seen using `:Nread`.

**Comment by justinmk** [comment] 2018-09-13 07:39
Duplicate of https://github.com/neovim/neovim/issues/8982 , which is covered in the FAQ.

**Closed by justinmk** 2018-09-13 07:39 UTC

**Comment by neovim-discourse** [comment] 2021-11-12 03:35
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/using-nvim-scp-user-hostname-path-to-file-but-cant-connect-to-the-remote-machine/1396/1
