### ISSUE TITLE
Cannot move column block.

### ISSUE THREAD

**Issue by latiaoxia** [neovim/neovim#9973] opened 2019-05-06 08:01 UTC
- `nvim --version`:
```
NVIM v0.4.0-460-g2470c8829
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-f573cd9e-4434-46c9-bc92-b956a3dc6cca

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```

- Vim (version: 7.4) works ok.
- Operating system/version: ubuntu16.04
- Terminal name/version: 
- `$TERM`:

Hi, I want to do column block moving like below:
```
11 22 33
11 22 33
```
to
```
22 11 33
22 11 33
```

Operation:
crtl-v select 
```
11
11
```
`x`
ctrl-v select after
```
22
22
```
`p`

In neovim this will become mess, but on vim this works ok.

**Comment by latiaoxia** [comment] 2019-05-06 08:12
I found that this issue is caused by 
`set clipboard+=unnamedplus`

**Comment by justinmk** [comment] 2019-05-06 08:24
Works for me. Tested on `0.4.0-690` 6891d8aec. 

Did your steps start with `nvim -u NORC` ?

Also why `ctrl-v select` in the last step? Just `p`. In any case, Nvim results match Vim's.

> set clipboard+=unnamedplus

That's why it's important to stat with `nvim -u NORC`. 

Duplicate of #1822

**Closed by justinmk** 2019-05-06 08:24 UTC
