### ISSUE TITLE
coc.nvim signatureHelp / floating windows break Undo history

### ISSUE THREAD

**Issue by solstag** [neovim/neovim#11439] opened 2019-11-23 05:49 UTC
Ni! This is just to relay a bug that has been closed as a `neovim` bug over at `coc.nvim`:

https://github.com/neoclide/coc.nvim/issues/588

I am suffering from the same issue as the author, and I have at least once ended up with corrupt files after undoing multiple changes.

It appears he never reported the bug upstream, so I am relaying it. Sorry for not being more verbose but the original is quite complete.

Cheers

**Comment by justinmk** [comment] 2019-11-24 23:33
Thanks but there is no minimal repro provided in https://github.com/neoclide/coc.nvim/issues/588 . Also:

> could be avoided by send `<C-g>u` (in insert-mode) to break the undo chain.

does that "fix" the problem?

**Comment by solstag** [comment] 2019-11-26 15:12
Sorry for the silly question, but how would I use `<C-g>u` to "fix" the problem ? I don't see how breaking the undo chain would help, but I'm probably missing something.

Also, you're right it is not a minimal repro. I just didn't want to loose track because it happened to me as soon as I started using neovim with coc. If it happens again I will try harder to pin it. :-/ Thanks.

**Comment by solstag** [comment] 2019-11-26 15:20
And, to be clear, I did not reproduce the linked issue, I just had the same effect (some edit being "skipped" by undo, with thus some text leftover after undoing) on my system. So feel free to close this issue if there is no point in keeping it without further input.

**Comment by justinmk** [comment] 2019-11-28 06:37
> some edit being "skipped" by undo, with thus some text leftover after undoing

The reports are suffering from vagueness, so let's try to clarify. The linked report gives a screencast which tells me basically nothing. Also,

- at the end of the screencast it looks like virtual text is shown, and I wonder if that's being confused with "text" in the buffer
- just to make sure it's not a "redraw" issue, see if CTRL-L (or `:mode`) clears the "stuck" text

What's an example of text before/during/after?

> how would I use <C-g>u to "fix" the problem

 `ctrl-g u` (lowercase `u`) could force an undo point where it was otherwise apparently "skipped". Never heard of this issue, though...

**Comment by blueyed** [comment] 2019-11-29 11:07
JFI: I've seen some issue with undo history myself a while ago (where the buffer text was different, not just a skipped step).  Just sayin' that there might be bugs in this regard, but without a way to reproduce this we cannot do much there really.

**Comment by glacambre** [comment] 2021-06-06 14:36
It's been a long time and there are no reproducers, I doubt we'll ever be able to know whether this issue has been fixed. Let's close it (but if you encounter this bug again and find a way to reproduce it, please let us know and we'll re-open :) ).

**Comment by 3ernhard** [comment] 2021-06-13 12:17
I still encountered this issue.

**Comment by glacambre** [comment] 2021-06-13 12:22
@3ernhard are you using master/neovim nightly?

**Comment by 3ernhard** [comment] 2021-06-13 12:46
I tried both (nightly from copr repo), and the bug also appeared in both cases after some time.

**Comment by glacambre** [comment] 2021-06-13 13:30
Thanks for trying nightly :). Now we really need a way to reproduce this bug, otherwise we'll never be able to fix it.

**Comment by 3ernhard** [comment] 2021-06-23 16:52
I made this recording demonstrating the bug, I don't know if it helps in any way but I hope so, this was the first time I could somewhat repeat the bug:
https://user-images.githubusercontent.com/31304552/123135876-978dee00-d452-11eb-88fd-bc05caaf5854.mp4

When the three `return false;` popded up, I pressed undo only once. The more often I repeat this procedure/bug, the more `return false;` and `}` get inserted with a single undo.
Redo seems to work normal.



Build: NVIM v0.5.0-dev+1421-ga72dfec85

**Comment by resolritter** [comment] 2021-12-28 03:15
I noticed this behavior while I was calling some functions or executing `<C-R>=Function()<CR>` mappings in Insert mode. A simple experiment with `autocmd ModeChanged * Log(mode())` showed that sometimes the mode briefly changed to `"n"` or `"c"` while the UI still showed I am in Insert mode. The behavior of briefly-changing `mode()` also happens for Insert \<cmd> mappings. In any case, although ModeChanged was triggered multiple times while I was still typing, InsertLeave was only triggered when I actually left Insert mode.

I have not yet debugged the code, but the undo breakage might be connected to those mode changes.

**Comment by zeertzjq** [comment] 2021-12-28 03:36
> The behavior of briefly-changing mode() also happens for Insert <cmd> mappings.

Can you give an example?

**Comment by resolritter** [comment] 2021-12-28 04:03
re https://github.com/neovim/neovim/issues/11439#issuecomment-1001851567

```vim
let g:log = []
fun! Log(...)
  call extend(g:log, a:000)
endfun

autocmd ModeChanged * call Log(mode())

fun! InsertK()
endfun
inoremap k <cmd>call InsertK()<CR>

call feedkeys("akbc\<esc>:echo g:log\<cr>")
```

nvim -i NONE -u NONE -c 'source test.vim'

`g:log` will have multiple modes other than `"i"`. The same behavior can be observed with \<C-R> mappings.

**Comment by flaphoschi** [comment] 2022-01-09 23:12
I recorded the issue with LSP using clangd and nvim-cmp:

https://user-images.githubusercontent.com/3392113/148704635-330a5fa6-7443-4f73-8e21-b4eaa88c9b4f.mp4

1. Enter insert mode with `i`
2. Enter text up until `str.`
3. `Ctrl+n` and select `size`
4. Keep inserting, select `append` with `Ctrl+n` (doesn't matter if I enter this part manually or us completion) and finally switch to normal mode with `Esc`
5. Press `u` to undo twice
6. Buffer corrupted - `:w` stores what we see

**Comment by lyokha** [comment] 2022-01-19 16:34
> Kapture.2021-10-25.at.13.30.26.mp4

Interestingly, the bug is not reproduced when adding lines at the bottom of the buffer.

**Comment by lyokha** [comment] 2022-01-20 13:08
This small patch fixes the issue.

```diff
diff --git a/src/nvim/buffer.c b/src/nvim/buffer.c
index abd22fba2..cb27a4f26 100644
--- a/src/nvim/buffer.c
+++ b/src/nvim/buffer.c
@@ -1454,7 +1454,7 @@ void set_curbuf(buf_T *buf, int action)
     }
     if (bufref_valid(&prevbufref) && !aborting()) {
       win_T *previouswin = curwin;
-      if (prevbuf == curbuf) {
+      if (prevbuf == buf) {
         u_sync(false);
       }
       close_buffer(prevbuf == curwin->w_buffer ? curwin : NULL,
```

This code runs after opening a float window when setting its buffer. `u_sync()` stops updating undo buffer.

The original test looks really wrong because it shall always be true:

```c
  prevbuf = curbuf;
  bufref_T newbufref;
  bufref_T prevbufref;
  set_bufref(&prevbufref, prevbuf);
  set_bufref(&newbufref, buf);

  // Autocommands may delete the curren buffer and/or the buffer we want to go
  // to.  In those cases don't close the buffer.
  if (!apply_autocmds(EVENT_BUFLEAVE, NULL, NULL, false, curbuf)
      || (bufref_valid(&prevbufref) && bufref_valid(&newbufref)
          && !aborting())) {
    if (prevbuf == curwin->w_buffer) {
      reset_synblock(curwin);
    }
    if (unload) {
      close_windows(prevbuf, false);
    }
    if (bufref_valid(&prevbufref) && !aborting()) {
      win_T *previouswin = curwin;
      if (prevbuf == curbuf) {
        u_sync(false);
      }
```

At the beginning of the snippet ` prevbuf = curbuf;`, then nothing changes them until we finally test that they are equal! So, I figured out that the author meant the other test, `prevbuf == buf`. However I do not know the idea that actually lies behind the test.

**Comment by zeertzjq** [comment] 2022-01-20 13:30
This piece of code can be traced back to 16 years ago: <https://github.com/vim/vim/commit/607a95ed81973faab2e1c3d9c91822082694fdc3>.

**Comment by zeertzjq** [comment] 2022-01-20 13:35
The condition is not always true. Note that `BufLeave` autocommands can change `curbuf`.

**Comment by zeertzjq** [comment] 2022-01-20 14:23
Script to reproduce without floating windows:

```vim
new

let s:nextbuf = 2

function! s:switch() abort
  call win_execute(1001, 'buffer ' .. s:nextbuf)
  let s:nextbuf = 3 - s:nextbuf
endfunction

wincmd b

call timer_start(1000, { -> s:switch() }, { 'repeat': -1 })
```

This can also reproduce the bug in Vim.

**Comment by zeertzjq** [comment] 2022-01-20 14:49
More minimal repro:
```vim
new
buffer 1
wincmd w
call setline(1, ['test'])
autocmd InsertEnter * call timer_start(1000, { -> win_execute(1001, 'buffer 2') })
```

**Comment by flaphoschi** [comment] 2022-01-20 14:57
Shall we open an issue for VIM? Therefore we could nudge Moolenaar 😉

**Comment by zeertzjq** [comment] 2022-01-20 14:59
<https://github.com/vim/vim/issues/9575>

**Closed** 2022-01-27 07:48 UTC
Labels: bug, status:has-vim-patch, status:has-repro
