### ISSUE TITLE
LSP client window issues with rust_analyzer.

### ISSUE THREAD

**Issue by m-kru** [neovim/neovim#12543] opened 2020-06-26 08:21 UTC
First of all, I am not 100% sure if these issues should be reported in the nvim repository.

- `nvim --version`:
```
NVIM v0.5.0-575-g225f0bcd9
Build type: Debug
LuaJIT 2.1.0-beta3
```
- language server name/version: `rust_analyzer` used via https://github.com/neovim/nvim-lsp
- Operating system/version: `Linux arch 5.7.5-arch1-1 #1 SMP PREEMPT Mon, 22 Jun 2020 08:10:02 +0000 x86_64 GNU/Linux`

<details>
<summary>nvim -c ":checkhealth nvim nvim_lsp"</summary>

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - INFO: Build type: Debug
  - WARNING: Non-optimized (DEBUG) build. Nvim will be slower.
    - ADVICE:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6003'
  - INFO: $COLORTERM='truecolor'

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: rust_analyzer: configuration checked.

</details>

### Actual behaviour
1. Rendering font and background in the window created by the LSP client is weird.
![image](https://user-images.githubusercontent.com/26227737/85835308-22cb9980-b795-11ea-8a40-07bc507bf985.png)
a) In the background you can see boxes with the background color of the editor.
b) The font gets bold in weird place/style.

2. Colors in the editor and window created by LSP client are not coherent.
![image](https://user-images.githubusercontent.com/26227737/85835679-bf8e3700-b795-11ea-86c7-ed96ae908c77.png)
Look for example at the `fn` keyword.

### Expected behaviour
1. No boxes in the background. No bold/coherent bold?
2. Coherent colors. 

I could try to fix these issues, if someone point me what should be fixed and where.

**Comment by mklein994** [comment] 2020-06-27 18:58
The weird bold/italic style is because the syntax file for markdown doesn't understand `___` to mean `<hr>`, but interprets it instead as the start of a ___bold/italic___ (`___bold/italic___`) section.

It also doesn't understand headers that start with spaces before the first `#` symbol.

There was a recent change to rust-analyzer that changed the horizontal line from `---` to `___`: (see git blame for [446fd3f hover.rs](https://github.com/rust-analyzer/rust-analyzer/blame/446fd3f515177d044344580c4002c7647e728119/crates/ra_ide/src/hover.rs#L113/crates/ra_ide/src/hover.rs#L113)), and since syntax/markdown.vim doesn't understand it, it broke. This is [valid CommonMark syntax](https://spec.commonmark.org/0.29/#thematic-breaks) though, so that's probably why it didn't break VSCode when it was added.

I've fixed this for my [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) setup by adding this to `~/.config/nvim/after/syntax/markdown.vim` (adapted from [tpope/vim-markdown](https://github.com/tpope/vim-markdown)):

```vim
" Add underscores to <hr /> rule syntax
syn match markdownRule "^ \{,3}_ *_ *_[ _]*$"

" Allow headings to be indented by up to 3 spaces
syn region markdownH1 matchgroup=markdownHeadingDelimiter start="^ \{,3}##\@!"      end="#*\s*$" keepend oneline contains=@markdownInline,markdownAutomaticLink contained
syn region markdownH2 matchgroup=markdownHeadingDelimiter start="^ \{,3}###\@!"     end="#*\s*$" keepend oneline contains=@markdownInline,markdownAutomaticLink contained
syn region markdownH3 matchgroup=markdownHeadingDelimiter start="^ \{,3}####\@!"    end="#*\s*$" keepend oneline contains=@markdownInline,markdownAutomaticLink contained
syn region markdownH4 matchgroup=markdownHeadingDelimiter start="^ \{,3}#####\@!"   end="#*\s*$" keepend oneline contains=@markdownInline,markdownAutomaticLink contained
syn region markdownH5 matchgroup=markdownHeadingDelimiter start="^ \{,3}######\@!"  end="#*\s*$" keepend oneline contains=@markdownInline,markdownAutomaticLink contained
syn region markdownH6 matchgroup=markdownHeadingDelimiter start="^ \{,3}#######\@!" end="#*\s*$" keepend oneline contains=@markdownInline,markdownAutomaticLink contained
```

This probably isn't the best way to fix it, especially if Neovim's LSP client is adding a space the the start for padding, since that breaks code blocks created using 4 spaces. It works for me, but I haven't tested it with Neovim's LSP client.

**Comment by m-kru** [comment] 2020-06-28 09:05
@mklein994 what you propose is just a byway, not a fix :(.

**Comment by monkoose** [comment] 2020-07-01 19:25
First problem has nothing to do with neovim or lsp-client, it is your colorscheme that uses explicit set of background color for some highlight groups. As you can see it is the same as your main background color, you just don't see it because main background color match background color for this groups. But floating background color is different from your main background color.

Check what is the output of `:verbose highlight Normal`, for consistency it is rule to not set any guibg or ctermbg for Normal highlight group and inherit it from terminal background.

**Comment by m-kru** [comment] 2020-07-02 05:47
```vim
:verbose highlight Normal
Normal         xxx ctermfg=223 ctermbg=235 guifg=#ebdbb2 guibg=#282828
        Last set from ~/.config/nvim/plugged/gruvbox/colors/gruvbox.vim line 417
```

**Comment by monkoose** [comment] 2020-07-02 07:50
So what part of my answer you do not understand?

**Comment by m-kru** [comment] 2020-07-02 08:24
Correct me if I am wrong, both issues are related to the color scheme and they should be fixed there?

**Comment by SanchayanMaity** [comment] 2020-07-02 09:33
I see a similar odd issue while using nvim-lsp with rust analyzer or haskell language server. Have not much of an idea when it comes to syntax highlighting in vim, but, I noticed if I remove the `vim-markdown` plugin from `plasticboy` the floating windows do not show that high lighting which is off in color. So, I am just gonna remove that plugin, as I do not use markdown much anyway and consider it fixed. Alternatively, using tpope's vim-markdown plugin also does not show this problem but I guess that's also what is included by default.

**Comment by monkoose** [comment] 2020-07-02 10:35
@m-kru both issues related to syntax file for markdown or colorscheme itself (because you can change any highlight group in your colorscheme as you can see here https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L1328)

**Comment by m-kru** [comment] 2020-07-02 11:47
@mklein994 solution does not work in my case. https://github.com/morhetz/gruvbox os probably no longer maintained, looks like the owner is gone.

**Comment by mjlbach** [comment] 2021-03-06 17:55
This is (sort-of) a duplicate of https://github.com/neovim/neovim/issues/14032

We need to either strip or add syntax rules for rendering certain escaped markdown characters, and on top of that, you need to have a color scheme which supports it (I suggest embark or onedark)

**Closed by mjlbach** 2021-03-06 17:55 UTC
Labels: bug, lsp
