### ISSUE TITLE
"Unhandled Token" in neovim documentation search bar & headings

### ISSUE THREAD

**Issue by Benn-Lau** [neovim/neovim#29387] opened 2024-06-18 03:09 UTC
### Problem

# Bug Report ("=========") Unhandled Token
I got link to this git hub repo page to report this bug:

![Screenshot 2024-06-18 104011](https://github.com/neovim/neovim/assets/106262664/77fd04bc-84c1-4382-8839-de3bea6fc0fd)
![Screenshot 2024-06-18 104032](https://github.com/neovim/neovim/assets/106262664/bd4b1b99-099b-4281-85af-73c91aa61d58)

### Steps I took to attempt to solve this issue:

- I search in the repo issue and find no related information (maybe I am dumb)
- I tried refresh the page and no avail 

## Steps I took:
1. Visit: https://neovim.io/doc/user/lua.html#lua-intro
2. Use the search bar and type : "lua"
3. ![image](https://github.com/neovim/neovim/assets/106262664/da581344-ff77-43ea-b552-cdd7c8234509)
4. You should see "==============" (Unhandled token)
5. ![image](https://github.com/neovim/neovim/assets/106262664/52a75bde-3871-41a7-941b-26d279cd6701)
6. [lua.org](https://lua.org) connection timed out

### Expected behavior

No "unhandled token"

### Neovim version (nvim -v)

n

### Vim (not Nvim) behaves the same?

n

### Operating system/version

n

### Terminal name/version

n

### $TERM environment variable

n

### Installation

n

**Comment by Benn-Lau** [comment] 2024-06-18 03:15
I tried on _different browser_ and _disable plugins_ but the issue still persist 

**On Chrome:** 
![image](https://github.com/neovim/neovim/assets/106262664/17363e2e-9c5a-45e4-bae0-94e3426cafa5)

**On Firefox:**
![Screenshot 2024-06-18 105040](https://github.com/neovim/neovim/assets/106262664/6a593c1e-1aad-4e87-8dd0-6aee63f5f816)

**Comment by clason** [comment] 2024-06-18 06:51
Duplicate of #29277

**Closed by clason** 2024-06-18 06:51 UTC
Labels: bug
