### ISSUE TITLE
Error message for lack of neovim-python-client is not improved.

### ISSUE THREAD

**Issue by crocket** [neovim/neovim#9485] opened 2019-01-11 02:09 UTC
- `nvim --version`: https://github.com/neovim/neovim/commit/10f29f79f4e8240254b916160ae5bb17ff56d161
- Operating system/version: Gentoo
- Terminal name/version: Alacritty 0.2.5
- `$TERM`: alacritty

### Steps to reproduce

Download plug.vim into ~/.config/nvim/autoload

~/.config/nvim/init.vim

```
set shell=/bin/sh

call plug#begin('~/.config/nvim/plug')
Plug 'vimwiki/vimwiki'
Plug 'tbabej/taskwiki'
call plug#end()
```

Execute `nvim +PlugInstall`

~/vimwiki/index.wiki

```
* [[example|example]]
```

~/vimwiki/example.wiki

```
Example
```

Execute `nvim +VimwikiIndex`

Press `Enter` on `example`.
Press `Backspace`.

### Actual behaviour

![2019-01-11_fri_01 56 17](https://user-images.githubusercontent.com/748856/51008885-1055a400-1591-11e9-8ac7-40733da98ae8.png)

If I execute `nvim ~/vimwiki/index.wiki`, I see the following error messages.

```
line   36:
E117: Unknown function: provider#python3#Call
Error detected while processing BufEnter Autocommands for "*.wiki":
E319: No "python3" provider found. Run ":checkhealth provider"
Press ENTER or type command to continue
```

### Expected behaviour

It should print error messages introduced by https://github.com/neovim/neovim/pull/9344

**Comment by mhinz** [comment] 2019-01-11 10:52
https://github.com/tbabej/taskwiki/issues/200#issuecomment-453105640

Closing. :)

**Comment by crocket** [comment] 2019-01-11 10:58
This issue is separate from https://github.com/tbabej/taskwiki/issues/200#issuecomment-453105640

This issue is about esoteric error message that occurs whenever neovim-python-client is not compatible with neovim.

**Comment by mhinz** [comment] 2019-01-11 11:05
I can't reproduce that, though.

`<cr>` takes me to `~/vimwiki/example.wiki` and `<bs>` takes me back without issues, even when `pynvim`/`neovim` is deinstalled.

I tested with nvim 0.3.3 and nvim master.

**Comment by mhinz** [comment] 2019-01-11 11:09
Edit: vimwiki doesn't even use Python.

**Comment by crocket** [comment] 2019-01-11 11:16
Right, you have to add `Plug 'tbabej/taskwiki'`

**Comment by mhinz** [comment] 2019-01-11 11:24
Ah, there you go. Reproduced. I look into it.

taskwiki should change this code here anyway: https://github.com/tbabej/taskwiki/blob/f4f1fe2b2e62e1ec120b50c76cfe0e0e4adee16a/ftplugin/vimwiki/taskwiki.vim#L8-L20.

You can't just assume that Python is installed just because Nvim is used.

**Comment by mhinz** [comment] 2019-01-11 13:30
Yeah, I have a patch already, but I didn't want to make PR just before going out for shopping. ;-)

**Closed** 2019-01-11 23:52 UTC
Labels: provider
