### ISSUE TITLE
After starting nvim, a folder called '~' will be created in the current directory.

### ISSUE THREAD

**Issue by xuoutput** [neovim/neovim#11930] opened 2020-02-22 08:43 UTC
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: macOS Mojave 10.14.5 18F132 x86_64
- Terminal name/version: iterms2
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

```
brew uninstall neovim
brew install neovim
```
then
```
cd ~
nvim -u NORC
ls
```

There is no folder called ~ in the current directory. 

```
nvim -u NORC
ls
```

A folder called '~' was created in the current directory.

![image](https://user-images.githubusercontent.com/16385443/75089358-cbbd7a00-5592-11ea-8f26-4bf3fe1e34e7.png)

But if I start with `sudo nvim -u NORC`

![image](https://user-images.githubusercontent.com/16385443/75089381-1d660480-5593-11ea-81fa-c9dbd425eb5d.png)

A folder called 'swap' appears

### Expected behaviour

Don't create folders after startup

**Comment by xuoutput** [comment] 2020-02-22 14:41
coc.nvim

**Comment by xuoutput** [comment] 2020-02-29 06:50
Not a bug in coc.nvim

**Comment by xuoutput** [comment] 2020-02-29 07:07
nvim --version: NVIM v0.5.0-404-g49cd750d6
vim -u DEFAULTS (version: ) behaves differently? I do not install vim
Operating system/version: Linux VM_145_90_centos
Terminal name/version: zsh
$TERM: xterm

# Steps to reproduce using `nvim -u NORC`

# Actual behaviour

download [Linux (64)](https://github.com/neovim/neovim/releases)
1. Download nvim.appimage
2. Run chmod u+x nvim.appimage && ./nvim.appimage
3. `:checkhealth`
![image](https://user-images.githubusercontent.com/16385443/75602952-fbc1cb80-5b04-11ea-96c8-afac2b5c968b.png)

then
```
ls
```

A folder called '~' was created in the current directory.

**Comment by xuoutput** [comment] 2020-04-06 06:27
$HOME/.config/configstore/update-notifier-npm.json

**Comment by glacambre** [comment] 2021-06-07 04:52
Can't reproduce on master, even with an unreadabale shada, so I'll close this. @xuoutput let us know if you're still experiencing this issue on master/nightly and we'll re-open :).

**Closed by glacambre** 2021-06-07 04:52 UTC
Labels: invalid
