### ISSUE TITLE
extmarks regression: :substitute with "n" flag raises E21 in non-modifiable buffer

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#11381] opened 2019-11-12 17:12 UTC
- `nvim --version`: NVIM v0.5.0-156-gdb436d527
 - `vim -u DEFAULTS` (version:  8.1 Included patches: 1-2291) behaves differently? Yes
 - Operating system/version: Ubuntu 16.04.6 LTS
 - Terminal name/version: XTerm(322)
 - `$TERM`: xterm-256color

### Steps to reproduce

Run this shell command:

    nvim -Nu NONE +'setl noma|s/x/y/ne'

### Actual behaviour

`E21` is raised.

### Expected behaviour

`E21` is not raised, because no substitution is performed thanks to the `n` flag.

### Additional information

I bisected the issue to a9065a50518ef59351f9d0d32041a991a751653f.

**Comment by glacambre** [comment] 2021-06-06 11:13
I can't reproduce this on master, so it has most probably been fixed. Let's close this issue :).

**Closed by glacambre** 2021-06-06 11:13 UTC
Labels: bug-regression, has:bisected
