### ISSUE TITLE
Unexpected escape sequences due to deferred background query

### ISSUE THREAD

**Issue by dalizard** [neovim/neovim#11062] opened 2019-09-19 13:05 UTC
I am running nvim 0.4.2 on macOS 10.14.6 under iTerm2 3.3.4.

When executing:
```
nvim -u NORC --startuptime /dev/stdout +qall | less
```
I am seeing some escape sequences, which started to appear with version 0.4.2. Also when starting nvim (plugins are loaded), a cursor is running through the screen as if something is being rendered. I believe this is related. The `$TERM` environment variable is set to _xterm-256color_.

**Comment by justinmk** [comment] 2019-09-19 20:21
:help $TERM

**Comment by rafikdraoui** [comment] 2019-09-19 20:50
I get the same behavior in tty:

```
$ nvim -u NONE -c 'quit'
^[]11;rgb:0000/2b2b/3636^[\$ 11;rgb:0000/2b2b/3636
```

This is with Kitty and `$TERM=xterm-kitty` (which I realize is not one of the value listed in `:h $TERM`), on both Linux and macOS. This doesn't happen in Terminal.app (`$TERM=xterm-256color`) on macOS. This started happening with 0.4.

Interestingly, `nvim -u NONE -c 'echo "hello"' -c 'quit'` triggers the same issue, but `nvim -u NONE -c 'echom "hello"' -c 'quit'` does not.

I know Kitty does not support BCE, and there's a reference to "BCE" in the release notes, so maybe this is related to that (but that's just a wild guess, I'm not familiar with all this!)

**Comment by h-michael** [comment] 2019-09-20 01:21
@justinmk I heard the same issue on Twitter.
He said that he tried this comment https://github.com/neovim/neovim/issues/9991#issuecomment-490987661, then the issue resolved.

He use MacOS and the issue occured with iTerm, Terminal.app and Alacritty.

**Comment by justinmk** [comment] 2019-09-20 02:15
I use kitty with `$TERM=xterm-kitty` , all the time, with zero problems.

Duplicate of #9991

**Comment by blueyed** [comment] 2019-09-20 14:59
@justinmk 
I see this with plain kitty (not in tmux also):
```
$ build/bin/nvim -u NONE -c 'quit'
^[]11;rgb:fdfd/f6f6/e3e3^[\[prompt]$ 11;rgb:fdfd/f6f6/e3e3
```
(also with urxvt)

Bisected to 66f4e8a ("screen: initialize screen properly with early `set display-=msgsep`").

**Comment by blueyed** [comment] 2019-09-20 15:03
@justinmk 
Not sure this is a duplicate of #9991 really (which appears to be about not recognizing some format).

Here it appears to be more due to nvim sending the query, but then having quit already when the response arrives, no?

**Comment by justinmk** [comment] 2019-09-20 15:22
> Here it appears to be more due to nvim sending the query, but then having quit already when the response arrives, no?

Good point. There's not anything we can do about that though.

**Comment by blueyed** [comment] 2019-09-20 15:42
> There's not anything we can do about that though.

I think we can fix this, by not quitting until we've seen the response (or after some timeout of course).  See https://github.com/neovim/neovim/pull/11067.

Re-opening.

**Comment by blueyed** [comment] 2019-09-20 18:42
https://github.com/neovim/neovim/pull/11067 should fix this, if you want to give it at try.

**Comment by justinmk** [comment] 2019-09-22 01:12
> I think we can fix this, by not quitting until we've seen the response (or after some timeout of course). See #11067.

Adding a timeout just causes a different problem, e.g. if terminal never sends a response. That's not a good tradeoff to fix a cosmetic issue.

**Comment by blueyed** [comment] 2019-09-22 15:23
Flushing the buffer fixes it: https://github.com/neovim/neovim/pull/11074.

> Why are we trying to optimize `nvim -u NONE -c 'quit'`? That is a useless command.

We're not optimizing it, but it is a good test case for showing that terminal responses might leak out of nvim.

**Comment by blueyed** [comment] 2019-09-22 15:25
Can you please test if https://github.com/neovim/neovim/pull/11074 fixes it for you?
(worked for me with urxvt and kitty)

**Closed** 2019-09-22 19:51 UTC
Labels: bug
