### ISSUE TITLE
Treesitter kill nvim in astro file

### ISSUE THREAD

**Issue by seocamo** [neovim/neovim#28405] opened 2024-04-18 20:01 UTC
### Problem

With only nvim-treesitter install, nvim die with pointer error if you type o in normal mode in a .astro file
Do not happen on 0.9 from Arch Repo

### Steps to reproduce

With only treesitter enable.
Make a test.adtro file with 
<body>
</body>
Open file in nvim
Type o

### Expected behavior

Nvim add a new line

### Neovim version (nvim -v)

0.10 nightly 

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch linux

### Terminal name/version

kitty

### $TERM environment variable

kitty

### Installation

build from nightly

**Comment by clason** [comment] 2024-04-18 20:19
Needs exact and minimal config so we can reproduce. Please also provide a backtrace; these things are usually the parser crashing, not nvim.

**Comment by seocamo** [comment] 2024-04-19 04:17
Will do when i get home, how do i make the backtrace for you? I am trying my best give what you need

**Comment by zeertzjq** [comment] 2024-04-19 04:24
https://neovim.io/doc/user/dev_tools.html#dev-tools-backtrace

**Comment by sirjager** [comment] 2024-04-19 12:37
same thing happening with my neovim, nvim automatically getting killed in .astro files.

Arch 6.6.28-1-LTS
Hyprland

IDK how to get crash logs n all

**Comment by clason** [comment] 2024-04-19 12:41
Duplicate of https://github.com/virchau13/tree-sitter-astro/issues/26

Not a Neovim issue.

**Closed by clason** 2024-04-19 12:41 UTC
Labels: bug, needs:repro, treesitter
