### ISSUE TITLE
Segmentation fault on mac when edit a long line file

### ISSUE THREAD

**Issue by icefed** [neovim/neovim#12471] opened 2020-06-11 14:42 UTC
- `nvim --version`: 0.4.3
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/config -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"
```
- `vim -u DEFAULTS` (version: ) behaves differently? 
- Operating system/version: 10.14.6 (18G4032) and 10.15
- Terminal name/version: iTerm2 Build 3.3.10
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC` 

Sorry i can not reproduce using `nvim -u NORC`, because i only can reproduce with plugins(fzf or floaterm).
```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```

### Reproduce with `fzf` or https://github.com/voldikss/vim-floaterm

1. open a file which have a long line( > 2500)
2. `set nowrap`
3. `2500|` move cursor to 2500 column. ( important)
4. `:Buffers` (fzf command) or `:FloatermNew` (floaterm command), then neovim  `segmentation fault`. I tested on CentOS 7, no fault.

### core dump
```
Process:               nvim [19246]
Path:                  /usr/local/Cellar/neovim/0.4.3/bin/nvim
Identifier:            nvim
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        zsh [14257]
Responsible:           nvim [19246]
User ID:               501

Date/Time:             2020-06-11 19:57:29.349 +0800
OS Version:            Mac OS X 10.14.6 (18G4032)
Report Version:        12
Anonymous UUID:        02E9B3E4-B559-BBE0-3774-D508F9DF09F6

Sleep/Wake UUID:       E3BA60F0-9B44-40F7-A989-A3FB4DA49764

Time Awake Since Boot: 78000 seconds
Time Since Wake:       750 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007ffee95bc0a8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [19246]

VM Regions Near 0x7ffee95bc0a8:
    Stack                  00007ffee8da0000-00007ffee95a0000 [ 8192K] rw-/rwx SM=ALI  thread 0
--> 
    Submap                 00007fff00000000-00007fff80000000 [  2.0G] r--/rwx SM=SHM  machine-wide VM submap

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   nvim                          	0x00000001067f5495 win_line + 21667
1   nvim                          	0x00000001067eabeb win_update + 4629
2   nvim                          	0x00000001067e87bb update_screen + 1990
3   nvim                          	0x00000001068406af terminal_check.llvm.11210652137840887655 + 43
4   nvim                          	0x000000010682962c state_enter + 40
5   nvim                          	0x000000010683f5f1 terminal_enter + 311
6   nvim                          	0x00000001066b422e edit + 118
7   nvim                          	0x0000000106793ce1 normal_execute.llvm.15691625082451191132 + 2474
8   nvim                          	0x00000001068296c8 state_enter + 196
9   nvim                          	0x00000001067688f9 main + 10367
10  libdyld.dylib                 	0x00007fff6c6f13d5 start + 1

Thread 1:
0   libsystem_malloc.dylib        	0x00007fff6c89f9d8 tiny_free_list_add_ptr + 399

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007f96f7005000  rbx: 0x00007f96f5702a30  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x00007ffee95bc0a8  rbp: 0x00007ffee959ecb0  rsp: 0x00007ffee959d830
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x00007f96f586ca00  r13: 0x0000000000000000  r14: 0x0000000000000001  r15: 0x000000000000797a
  rip: 0x00000001067f5495  rfl: 0x0000000000010246  cr2: 0x00007ffee95bc0a8
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14


Binary Images:
       0x106660000 -        0x1068b5fff +nvim (0) <C13934C3-0AAF-3816-B046-4D6C2F8C4ED3> /usr/local/bin/nvim
       0x10695f000 -        0x106968fff +libintl.8.dylib (0) <F8AF848E-83C4-3DE7-9701-82A6C9A1614E> /usr/local/opt/gettext/lib/libintl.8.dylib
       0x106974000 -        0x10698efff +libuv.1.dylib (0) <71AF7354-C648-309C-8405-327BF7C73884> /usr/local/opt/libuv/lib/libuv.1.dylib
       0x10699f000 -        0x1069a3fff +libmsgpackc.2.dylib (0) <96F48F32-F34F-3103-A21E-D6D9E903F121> /usr/local/opt/msgpack/lib/libmsgpackc.2.dylib
       0x1069ad000 -        0x1069b6fff +libvterm.0.dylib (0) <2B983607-6B65-3AE4-A36F-7BA2E8321130> /usr/local/opt/libvterm/lib/libvterm.0.dylib
       0x1069bb000 -        0x1069c0ffb +libtermkey.1.dylib (0) <F4D448A7-58DF-3771-B560-3C6E5177A1F6> /usr/local/opt/libtermkey/lib/libtermkey.1.dylib
       0x1069cc000 -        0x1069d3fff +libunibilium.4.dylib (0) <696AD650-DAC4-3C62-A298-6A5D04EA3061> /usr/local/opt/unibilium/lib/libunibilium.4.dylib
       0x1069dc000 -        0x106a5dff7 +libluajit-5.1.2.dylib (0) <071439AC-F0B9-34C7-982A-950DC06765F6> /usr/local/opt/luajit/lib/libluajit-5.1.2.dylib
       0x10a980000 -        0x10a9ea70f  dyld (655.1.1) <C192CA31-D059-3770-9882-D864FEFA0C96> /usr/lib/dyld
    0x7fff40729000 -     0x7fff40b6efef  com.apple.CoreFoundation (6.9 - 1575.23) <91D1D63A-9417-376D-801A-9ABDE4879F48> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff69295000 -     0x7fff69296ffb  libDiagnosticMessagesClient.dylib (107) <A14D0819-0970-34CD-8680-80E4D7FE8C2C> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff696d5000 -     0x7fff696d6ffb  libSystem.B.dylib (1252.250.1) <71C12F94-14DC-379B-8D2A-0523D0A58245> /usr/lib/libSystem.B.dylib
    0x7fff6991a000 -     0x7fff6996dff7  libc++.1.dylib (400.9.4) <9A60A190-6C34-339F-BB3D-AACE942009A4> /usr/lib/libc++.1.dylib
    0x7fff6996e000 -     0x7fff69983ff7  libc++abi.dylib (400.17) <38C09CED-9090-3719-90F3-04A2749F5428> /usr/lib/libc++abi.dylib
    0x7fff69984000 -     0x7fff69984ff3  libcharset.1.dylib (51.200.6) <2A27E064-314C-359C-93FC-8A9B06206174> /usr/lib/libcharset.1.dylib
    0x7fff6a2d9000 -     0x7fff6a3c9fff  libiconv.2.dylib (51.200.6) <2047C9B7-3F74-3A95-810D-2ED8F0475A99> /usr/lib/libiconv.2.dylib
    0x7fff6a3ca000 -     0x7fff6a62bffb  libicucore.A.dylib (62141.0.1) <A0D63918-76E9-3C1B-B255-46F4C1DA7FE8> /usr/lib/libicucore.A.dylib
    0x7fff6af0e000 -     0x7fff6b693fdf  libobjc.A.dylib (756.2) <7C312627-43CB-3234-9324-4DEA92D59F50> /usr/lib/libobjc.A.dylib
    0x7fff6bc5b000 -     0x7fff6bc5eff7  libutil.dylib (51.200.4) <CE9B18C9-66ED-32D4-9D29-01F8FCB467B0> /usr/lib/libutil.dylib
    0x7fff6bd7e000 -     0x7fff6bd90ff7  libz.1.dylib (70.200.4) <B048FC1F-058F-3A08-A1FE-81D5308CB3E6> /usr/lib/libz.1.dylib
    0x7fff6c574000 -     0x7fff6c578ff3  libcache.dylib (81) <1987D1E1-DB11-3291-B12A-EBD55848E02D> /usr/lib/system/libcache.dylib
    0x7fff6c579000 -     0x7fff6c583ff3  libcommonCrypto.dylib (60118.250.2) <1765BB6E-6784-3653-B16B-CB839721DC9A> /usr/lib/system/libcommonCrypto.dylib
    0x7fff6c584000 -     0x7fff6c58bff7  libcompiler_rt.dylib (63.4) <5212BA7B-B7EA-37B4-AF6E-AC4F507EDFB8> /usr/lib/system/libcompiler_rt.dylib
    0x7fff6c58c000 -     0x7fff6c595ff7  libcopyfile.dylib (146.250.1) <98CD00CD-9B91-3B5C-A9DB-842638050FA8> /usr/lib/system/libcopyfile.dylib
    0x7fff6c596000 -     0x7fff6c61afc3  libcorecrypto.dylib (602.260.2) <01464D24-570C-3B83-9D18-467769E0FCDD> /usr/lib/system/libcorecrypto.dylib
    0x7fff6c6a1000 -     0x7fff6c6daff7  libdispatch.dylib (1008.270.1) <97273678-E94C-3C8C-89F6-2E2020F4B43B> /usr/lib/system/libdispatch.dylib
    0x7fff6c6db000 -     0x7fff6c707ff7  libdyld.dylib (655.1.1) <002418CC-AD11-3D10-865B-015591D24E6C> /usr/lib/system/libdyld.dylib
    0x7fff6c708000 -     0x7fff6c708ffb  libkeymgr.dylib (30) <0D0F9CA2-8D5A-3273-8723-59987B5827F2> /usr/lib/system/libkeymgr.dylib
    0x7fff6c716000 -     0x7fff6c716ff7  liblaunch.dylib (1336.261.4) <AEBAE502-D691-3D26-BFD9-CB41090C0360> /usr/lib/system/liblaunch.dylib
    0x7fff6c717000 -     0x7fff6c71cfff  libmacho.dylib (927.0.3) <A377D608-77AB-3F6E-90F0-B4F251A5C12F> /usr/lib/system/libmacho.dylib
    0x7fff6c71d000 -     0x7fff6c71fff7  libquarantine.dylib (86.270.1) <3F36A3D6-9606-3D90-B520-809BAEF981C3> /usr/lib/system/libquarantine.dylib
    0x7fff6c720000 -     0x7fff6c721ff7  libremovefile.dylib (45.200.2) <9FBEB2FF-EEBE-31BC-BCFC-C71F8D0E99B6> /usr/lib/system/libremovefile.dylib
    0x7fff6c722000 -     0x7fff6c739ff3  libsystem_asl.dylib (356.200.4) <A62A7249-38B8-33FA-9875-F1852590796C> /usr/lib/system/libsystem_asl.dylib
    0x7fff6c73a000 -     0x7fff6c73aff7  libsystem_blocks.dylib (73) <A453E8EE-860D-3CED-B5DC-BE54E9DB4348> /usr/lib/system/libsystem_blocks.dylib
    0x7fff6c73b000 -     0x7fff6c7c2fff  libsystem_c.dylib (1272.250.1) <7EDACF78-2FA3-35B8-B051-D70475A35117> /usr/lib/system/libsystem_c.dylib
    0x7fff6c7c3000 -     0x7fff6c7c6ffb  libsystem_configuration.dylib (963.270.3) <2B4A836D-68A4-33E6-8D48-CD4486B03387> /usr/lib/system/libsystem_configuration.dylib
    0x7fff6c7c7000 -     0x7fff6c7caff7  libsystem_coreservices.dylib (66) <719F75A4-74C5-3BA6-A09E-0C5A3E5889D7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff6c7cb000 -     0x7fff6c7d1fff  libsystem_darwin.dylib (1272.250.1) <EC9B39A5-9592-3577-8997-7DC721D20D8C> /usr/lib/system/libsystem_darwin.dylib
    0x7fff6c7d2000 -     0x7fff6c7d8ffb  libsystem_dnssd.dylib (878.270.3) <D5352ABD-0311-3327-8E64-93F29EB19BF1> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff6c7d9000 -     0x7fff6c824ffb  libsystem_info.dylib (517.200.9) <D09D5AE0-2FDC-3A6D-93EC-729F931B1457> /usr/lib/system/libsystem_info.dylib
    0x7fff6c825000 -     0x7fff6c84dff7  libsystem_kernel.dylib (4903.278.28) <5B6BB78A-7845-3A31-B87E-03E18DDE4D86> /usr/lib/system/libsystem_kernel.dylib
    0x7fff6c84e000 -     0x7fff6c899ff7  libsystem_m.dylib (3158.200.7) <F19B6DB7-014F-3820-831F-389CCDA06EF6> /usr/lib/system/libsystem_m.dylib
    0x7fff6c89a000 -     0x7fff6c8c4fff  libsystem_malloc.dylib (166.270.1) <011F3AD0-8E6A-3A89-AE64-6E5F6840F30A> /usr/lib/system/libsystem_malloc.dylib
    0x7fff6c8c5000 -     0x7fff6c8cfff7  libsystem_networkextension.dylib (767.250.2) <FF06F13A-AEFE-3A27-A073-910EF78AEA36> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff6c8d0000 -     0x7fff6c8d7fff  libsystem_notify.dylib (172.200.21) <145B5CFC-CF73-33CE-BD3D-E8DDE268FFDE> /usr/lib/system/libsystem_notify.dylib
    0x7fff6c8d8000 -     0x7fff6c8e1fef  libsystem_platform.dylib (177.270.1) <9D1FE5E4-EB7D-3B3F-A8D1-A96D9CF1348C> /usr/lib/system/libsystem_platform.dylib
    0x7fff6c8e2000 -     0x7fff6c8ecff7  libsystem_pthread.dylib (330.250.2) <2D5C08FF-484F-3D59-9132-CE1DCB3F76D7> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6c8ed000 -     0x7fff6c8f0ff7  libsystem_sandbox.dylib (851.270.1) <9494594B-5199-3186-82AB-5FF8BED6EE16> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff6c8f1000 -     0x7fff6c8f3ff3  libsystem_secinit.dylib (30.260.2) <EF1EA47B-7B22-35E8-BD9B-F7003DCB96AE> /usr/lib/system/libsystem_secinit.dylib
    0x7fff6c8f4000 -     0x7fff6c8fbff3  libsystem_symptoms.dylib (820.267.1) <03F1C2DD-0F5A-3D9D-88F6-B26C0F94EB52> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6c8fc000 -     0x7fff6c911ff7  libsystem_trace.dylib (906.260.2) <12C1B9A2-39D6-3428-AE60-2303BD201A57> /usr/lib/system/libsystem_trace.dylib
    0x7fff6c913000 -     0x7fff6c918ffb  libunwind.dylib (35.4) <24A97A67-F017-3CFC-B0D0-6BD0224B1336> /usr/lib/system/libunwind.dylib
    0x7fff6c919000 -     0x7fff6c948fff  libxpc.dylib (1336.261.4) <7A9D1BF7-F17F-3B87-9373-B0079544E8C5> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 792493
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=245.3M resident=0K(0%) swapped_out_or_unallocated=245.3M(100%)
Writable regions: Total=64.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=64.2M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                    8K        1 
MALLOC                            46.3M       24 
MALLOC guard page                   16K        4 
MALLOC_LARGE (reserved)            860K        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        2 
Stack                             16.0M        2 
VM_ALLOCATE                        576K        2 
__DATA                            4024K       57 
__LINKEDIT                       222.9M       10 
__TEXT                            22.4M       53 
__UNICODE                          564K        1 
shared memory                       12K        3 
===========                     =======  ======= 
TOTAL                            369.8M      161 
TOTAL, minus reserved VM space   369.0M      161 
```

**Comment by erw7** [comment] 2020-06-11 16:49
This seems to be a duplicate of #11548.

**Comment by icefed** [comment] 2020-06-12 01:48
> This seems to be a duplicate of #11548.

Yes, the backtrace looks same. I think it's a window issue, fzf and vim-floaterm(normal wintype) both open a preview window, terminal too.

**Closed** 2020-06-13 16:53 UTC
Labels: bug, bug-crash, duplicate
