### ISSUE TITLE
Neovim freezes when using it with tree-sitter

### ISSUE THREAD

**Issue by vigoux** [neovim/neovim#12131] opened 2020-04-16 15:29 UTC
- `nvim --version`: 
```
NVIM v0.5.0-437-g2e01c5955
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/thomas/src/neovim/build/config -I/home/thomas/src/neovim/src -I/home/thomas/src/neovim/.deps/usr/include -I/usr/include -I/home/thomas/src/neovim/build/src/nvim/auto -I/home/thomas/src/neovim/build/include
```
- Operating system/version: Void Linux
- Terminal name/version: st
- `$TERM`: st-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC [random file that treesitter can parse]

Do some editing...
```

### Actual behaviour

Neovim freezes, and memory spikes up slowly. CPU starts panicking and your computer burns.

### Expected behaviour

Everything works properly.

### Additionnal informations

I was able to get a backtrace when the bug happens. The thing it happends both randomly and repeatedly.

The backtrace:
```
#0  0x000056162fb8d465 in atomic_dec (p=0x561637769b30) at ../src/tree_sitter/./atomic.h:37
#1  0x000056162fb8fb62 in ts_subtree_release (pool=0x561630e793e8, self=...)
    at ../src/tree_sitter/subtree.c:530
#2  0x000056162fb8830a in stack_node_release (self=0x561637852550, pool=0x5616310066d0,
    subtree_pool=0x561630e793e8) at ../src/tree_sitter/stack.c:108
#3  0x000056162fb88b56 in stack_head_delete (self=0x561637800b20, pool=0x5616310066d0,
    subtree_pool=0x561630e793e8) at ../src/tree_sitter/stack.c:239
#4  0x000056162fb8c0e5 in ts_stack_remove_version (self=0x5616310066a0, version=0)
    at ../src/tree_sitter/stack.c:608
#5  0x000056162fb82647 in ts_parser__condense_stack (self=0x561630e78f30)
    at ../src/tree_sitter/parser.c:1569
#6  0x000056162fb836ab in ts_parser_parse (self=0x561630e78f30, old_tree=0x5616316dc780, input=...)
    at ../src/tree_sitter/parser.c:1828
#7  0x000056162f9eac45 in parser_parse_buf (L=0x4045d378) at ../src/nvim/lua/treesitter.c:303
#8  0x000056162fbf9c6b in lj_BC_FUNCC ()
#9  0x000056162fbe5d4a in lua_pcall (L=0x4045d378, nargs=<optimized out>, nresults=0,
    errfunc=<optimized out>) at lj_api.c:1129
#10 0x000056162f9e7a76 in nlua_schedule_event (argv=0x7fff7a919a38) at ../src/nvim/lua/executor.c:226
#11 0x000056162f95baab in multiqueue_process_events (this=0x561630aab3b0)
    at ../src/nvim/event/multiqueue.c:157
#12 0x000056162f8f75b1 in insert_handle_key (s=0x7fff7a919bc0) at ../src/nvim/edit.c:1021
#13 0x000056162f8f6c56 in insert_execute (state=0x7fff7a919bc0, key=-26365) at ../src/nvim/edit.c:801
#14 0x000056162fb04d71 in state_enter (s=0x7fff7a919bc0) at ../src/nvim/state.c:69
#15 0x000056162f8f6200 in insert_enter (s=0x7fff7a919bc0) at ../src/nvim/edit.c:483
#16 0x000056162f8f7e6e in edit (cmdchar=111, startln=true, count=1) at ../src/nvim/edit.c:1412
#17 0x000056162fa414bb in invoke_edit (cap=0x7fff7a919db8, repl=0, cmd=111, startln=1)
    at ../src/nvim/normal.c:7643
#18 0x000056162fa40347 in n_opencmd (cap=0x7fff7a919db8) at ../src/nvim/normal.c:7091
#19 0x000056162fa42072 in nv_open (cap=0x7fff7a919db8) at ../src/nvim/normal.c:7967
#20 0x000056162fa329c9 in normal_execute (state=0x7fff7a919d30, key=111) at ../src/nvim/normal.c:1136
#21 0x000056162fb04d71 in state_enter (s=0x7fff7a919d30) at ../src/nvim/state.c:69
#22 0x000056162fa30c80 in normal_enter (cmdwin=false, noexmode=false) at ../src/nvim/normal.c:463
#23 0x000056162f9ed9a9 in main (argc=2, argv=0x7fff7a91a0b8) at ../src/nvim/main.c:569
```

I tried updating the treesitter runtime to its latest version, but this did not fixed the bug.

**Comment by kyazdani42** [comment] 2020-04-18 09:43
Hello, i think this issue is a duplicate of #11944

**Closed** 2020-04-22 16:54 UTC
Labels: bug
