### ISSUE TITLE
Text selected in visual mode is not stored in "* register

### ISSUE THREAD

**Issue by illia-shkroba** [neovim/neovim#21236] opened 2022-11-29 17:38 UTC
### Neovim version (nvim -v)

v0.8.1

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Arch Linux 5.15.80-1-lts

### Terminal name/version

st

### $TERM environment variable

st-256color

### Installation

Arch Linux pacman package manager with `pacman -S neovim`

### How to reproduce the issue

nvim --clean
Aany-text
viW
o
"*p

### Expected behavior

I am not sure whether it is meant to work like this, but Vim's default behavior is to store selected text in visual mode in a `"*` register.

It is especially useful when substituting: a text that should be substituted can be yanked into a `""` register and a substitution text can be yanked into a `"*` register by visually selecting the text (or vice-versa).

### Actual behavior

I have checked that it is possible to store some text in a Vim's `"*` register by visually selecting the text and then to paste that text in NeoVim by using the `"*` register.

**Comment by gpanders** [comment] 2022-11-29 17:43
Vim does not automatically copy the visual selection into the `*` register. Do you perhaps have a plugin (or a distro specific config file) that enables this?

**Comment by illia-shkroba** [comment] 2022-11-29 18:02
> Vim does not automatically copy the visual selection into the `*` register. Do you perhaps have a plugin (or a distro specific config file) that enables this?

I have removed the ~/.vimrc file to check this behavior and I don't have any system-wide options that might be causing this.

It seems that `gvim` [package](https://archlinux.org/packages/extra/x86_64/gvim) with different Vim compile options causes this behavior.
I have tried using `vim` [package](https://archlinux.org/packages/extra/x86_64/vim) instead and with this package the "visual selection copy" feature doesn't work.

Do you know how to enable this feature in NeoVim?
If there is no way of enabling it, maybe I should make a feature request?

**Comment by zeertzjq** [comment] 2022-11-29 22:11
Duplicate of #2325

**Closed by zeertzjq** 2022-11-29 22:11 UTC
Labels: bug
