### ISSUE TITLE
`cmdheight = 2` not respected when sourcing a session file

### ISSUE THREAD

**Issue by olimorris** [neovim/neovim#22450] opened 2023-02-28 09:19 UTC
### Problem

We've recently come across an [issue](https://github.com/olimorris/persisted.nvim/issues/53) whereby a session which has many buffers and a single split (_"the session"_), causes the `cmdheight` to change when sourced.

In the example I outline below, the `minimal.lua` file has `vim.opt.cmdheight = 2` which we can check with `:verb set cmdheight`. However when sourcing the session, the cmdheight is automatically set to 1.

### Minimal.lua file

```lua
vim.opt.sessionoptions = { 'curdir', 'folds', 'tabpages', 'winpos' }
vim.opt.cmdheight = 2
```

## Creating the session file

1. `nvim --clean -u minimal.lua`
3. Open at least two buffers
4. `:vsplit`
5. `:mksession`

## Sourcing the session file

1. `nvim --clean -u minimal.lua`
2. `:verb set cmdheight` observe that `2` is the output
3. `:source Session.vim`
4. `:verb set cmdheight` observe that `1` is now the output

### Expected behavior

I would expect `:verb set cmdheight` to still be `2` after sourcing the session.

### Neovim version (nvim -v)

0.9.0-dev-a601d03

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.2.1 (22D68)

### Terminal name/version

Kitty 0.27.1

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by clason** [comment] 2023-02-28 09:20
Is that not the same as #22449?

**Comment by zeertzjq** [comment] 2023-02-28 09:30
Cannot reproduce

**Comment by zeertzjq** [comment] 2023-02-28 09:38
Duplicate of #22449

**Closed by zeertzjq** 2023-02-28 09:38 UTC
Labels: bug
