### ISSUE TITLE
inputlist() is ignored in BufNewFile

### ISSUE THREAD

**Issue by WGH-** [neovim/neovim#10116] opened 2019-06-04 11:19 UTC
- `nvim --version`: NVIM v0.4.0-dev (db415bd) and NVIM v0.3.4
- Vim (version: 8.1 1-648) behaves differently? **YES**
- Operating system/version: Gentoo Linux
- Terminal name/version: Alacritty
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

Assuming test.txt doesn't exist:
```
nvim -u NORC

:autocmd BufNewFile test.txt call inputlist([1,2,3])
:e test.txt
```

### Actual behaviour
New buffer opens as if no `BufNewFile` was set up.

### Expected behaviour
A menu appears before buffer opens (like it does in Vim).

**Comment by justinmk** [comment] 2019-06-04 11:48
:set shortmess-=F

Vim 8.1 has the same behavior with:

    :set shortmess+=F

This is an Nvim default, documented at `:h nvim-defaults`. 

Duplicate of #10008

**Closed by justinmk** 2019-06-04 11:48 UTC

**Comment by chrisbra** [comment] 2019-06-04 12:07
I come to think, that the shortmess flag `F` is really not working well. We have a similar issue https://github.com/vim/vim/issues/4379 and I have been wanting to look at fixing this issue correctly.
