### ISSUE TITLE
How to hide the cursor? 'guicursor' does not take effect.

### ISSUE THREAD

**Issue by Yggdroot** [neovim/neovim#6538] opened 2017-04-17 06:36 UTC
- `nvim --version`: NVIM v0.2.0-1305-g58d2ce9
- Vim (version: ) behaves differently? yes
- Operating system/version: linux
- Terminal name/version: all
- `$TERM`: xterm/ xterm-256color

### Actual behaviour
Can not hide cursor.

### Expected behaviour
For vim, `set t_ve=` and `set guicursor=a:xxx` can hide the cursor.
But for neovim,  `set guicursor=a:xxx` can not hide the cursor, and I can not any other way to hide the cursor.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by teto** [comment] 2017-04-17 08:53
Not possible yet. Duplicate of https://github.com/neovim/neovim/issues/3688.

I am working on it

**Closed** 2017-04-17 08:55 UTC
