### ISSUE TITLE
show_position_diagnostics doesn't display diagnostics for multiple servers

### ISSUE THREAD

**Issue by ranebrown** [neovim/neovim#15591] opened 2021-09-07 15:01 UTC
### Neovim version (nvim -v)

0.6.0-dev+3f526feeb

### Language server name/version

pyright 1.1.157 / null-ls 5b0e21625a920cf4a2d1ce1c516dd503b7a32ca9

### Operating system/version

macOS 11.5.2

### Steps to reproduce using "nvim -u minimal_init.lua"

[minimal_init.txt](https://github.com/neovim/neovim/files/7122371/minimal_init.txt)

1. Install flake8 and pyright
2. Rename attached file to have lua extension
4. `nvim -u minimal_init.lua test.py`
5. Copy below contents into file
5. `]d` repeatedly to jump through diagnostics
6. Popup is not displayed for null-ls diagnostics i.e. flake8 only pyright.

```py
#comment
import test

if __name__ == "__main__":
    main()

```

### Expected behavior

The popup displaying diagnostics should be shown for all servers. Looks like this stems from the changes in #14795. Maybe the `client_id` needs passed to the new `show_position_diagnostics` similar to what is done with `show_line_diagnostics`.

### Actual behavior

Cursor jumps to the position of each diagnostic but the popup with more information is only displayed for pyright.

**Comment by pohzipohzi** [comment] 2021-09-07 16:41
Hmm this looks like an issue with `flake8`. The diagnostic cache shows negative character numbers:

```
...
    }, {
      code = "F401",
      col = "1",
      message = "'test' imported but unused",
      range = {
        end = {
          character = -1,
          line = 1
        },
        start = {
          character = 0,
          line = 1
        }
      },
      row = "2",
      severity = 3,
      source = "flake8"
    }, {
...
```

According to LSP [docs](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#position), characters should be zero-based:

> Position in a text document expressed as zero-based line and zero-based character offset. A position is between two characters like an ‘insert’ cursor in an editor. Special values like for example -1 to denote the end of a line are not supported.

**Comment by ranebrown** [comment] 2021-09-07 20:00
That could be related but if I change [this line](https://github.com/neovim/neovim/blob/db695cc4cafa6c26eb71a183cc73a167b842731e/runtime/lua/vim/lsp/diagnostic.lua#L548) to `show_line_diagnostics` the popup is shown correctly.

**Comment by mjlbach** [comment] 2021-09-07 21:18
We could normalize the character ranges but I agree this should be fixed upstream.

**Comment by pohzipohzi** [comment] 2021-09-08 05:28
@mjlbach there was another issue that popped up while fixing this upstream (see [comment](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/164#issuecomment-914876418)).

On investigation this appears to be due to some special last line handling stemming from https://github.com/neovim/neovim/issues/13476. However I can't seem to reproduce #13476, while removing the additional handling fixes https://github.com/jose-elias-alvarez/null-ls.nvim/issues/164:

```diff
diff --git a/runtime/lua/vim/lsp/diagnostic.lua b/runtime/lua/vim/lsp/diagnostic.lua
index 41a62da52..909945985 100644
--- a/runtime/lua/vim/lsp/diagnostic.lua
+++ b/runtime/lua/vim/lsp/diagnostic.lua
@@ -269,20 +269,10 @@ local function set_diagnostic_cache(diagnostics, bufnr, client_id)
   -- The diagnostic's severity. Can be omitted. If omitted it is up to the
   -- client to interpret diagnostics as error, warning, info or hint.
   -- TODO: Replace this with server-specific heuristics to infer severity.
-  local buf_line_count = vim.api.nvim_buf_line_count(bufnr)
   for _, diagnostic in ipairs(diagnostics) do
     if diagnostic.severity == nil then
       diagnostic.severity = DiagnosticSeverity.Error
     end
-    -- Account for servers that place diagnostics on terminating newline
-    if buf_line_count > 0 then
-      diagnostic.range.start.line = math.max(math.min(
-        diagnostic.range.start.line, buf_line_count - 1
-      ), 0)
-      diagnostic.range["end"].line = math.max(math.min(
-        diagnostic.range["end"].line, buf_line_count - 1
-      ), 0)
-    end
   end
 
   diagnostic_cache[bufnr][client_id] = diagnostics
```

What do you think of this change?

**Comment by mjlbach** [comment] 2021-09-08 05:35
The above patch introduces a regression, try this exact file with/without the patch https://github.com/neovim/neovim/issues/13476#issuecomment-762664563

**Closed** 2021-09-20 18:32 UTC
Labels: bug, lsp
