### ISSUE TITLE
Vim's settings written in Lua doesn't work in some files

### ISSUE THREAD

**Issue by dadyarri** [neovim/neovim#14654] opened 2021-05-27 14:39 UTC
- `nvim --version`: NVIM v0.5.0-dev+1357-g192f89ea1 (nvim-nightly-bin from AUR)
- Operating system/version: Manjaro @ 5.10
- Terminal name/version: Konsole 21.04.0
- `$TERM`: xterm-256color
- Configuration: https://github.com/dadyarri/dotfiles/tree/master/.config/nvim

### Actual behaviour

![image](https://user-images.githubusercontent.com/51821039/119843507-4b619380-bf10-11eb-8161-5347d91098ff.png)
![image](https://user-images.githubusercontent.com/51821039/119843610-62a08100-bf10-11eb-85fc-546118db3023.png)

### Expected behaviour

Same behaviour (fetching config correctly) in any file

**Comment by dylanarmstrong** [comment] 2021-05-27 14:58
Hey @dadyarri , can you try adding to your workspace config:
```lua
workspace = {
  library = ...,
  preloadFileSize = 1000
}
```
to your config here:
https://github.com/dadyarri/dotfiles/blob/master/.config/nvim/lua/lsp/lua-ls.lua#L31

I noticed that error message being used with this variable in the lua-language-server:
https://github.com/sumneko/lua-language-server/blob/80d6de8603ac3097da092bed26224a0cfcf07669/script/config.lua#L158

**Comment by dadyarri** [comment] 2021-05-27 15:04
@dylanarmstrong, hi, thanks for the reply. No, this didn't work, though error with file size limit fixed

**Comment by fdioguardi** [comment] 2021-05-27 17:23
Hi! I think the problem is that you're trying to set every option with `vim.o`.
Use `vim.wo` for window-scoped settings (like `number`) , and `vim.bo` for the buffer-scoped ones (like `tabstop`).

For reference, this is exactly what https://github.com/neovim/neovim/pull/13479 is gonna solve, so you can wait until it gets merged to not have to worry about it :D

**Comment by dadyarri** [comment] 2021-05-27 17:32
@fdioguardi, thanks for the idea, i'll try it. how can i get exact info about each option's scope? (just started moving to vim)

**Closed** 2021-05-27 17:45 UTC
Labels: bug
