### ISSUE TITLE
Commit a99d33ad breaks bindings with meta(alt) key in xterm

### ISSUE THREAD

**Issue by glebtv** [neovim/neovim#1881] opened 2015-01-24 01:06 UTC
If I revert a99d33ad9a6a81400a04712f769180ef700787b4 meta keys are working again. No idea how this happens.

**Comment by glebtv** [comment] 2015-01-24 02:11
@justinmk Sorry, this commit shouldn't have been in that PR
Yes, reverting only this change fixes it

**Comment by Pyrohh** [comment] 2015-01-24 22:45
I can't seem to reproduce this. This might seem like a silly question, but are you running QNX and/or pterm?

**Comment by glebtv** [comment] 2015-01-27 00:59
No, arch linux and xterm

**Comment by glebtv** [comment] 2015-01-27 01:27
Update:

Not all meta bindings seem to break,

Following works ok:

    nmap <m-x> <C-w>q
    nmap <m-c> <C-w>q
    nmap <m-'> <C-w>v
    nmap <m-/> <C-w>s

And this ones do not:

    map <M-Right> <c-w>l
    map <M-Left> <c-w>h
    map <M-Up> <c-w>k
    map <M-Down> <c-w>j

Both worked okay before and both work after reverting this change
https://github.com/glebtv/neovim/commit/10bd2476f841a48c925ed983e2bb28d2cef79e2e
to p_ttym_values.

Arrow keys by themselves work.

nvim seems to be waiting for some mouse event after meta+right key - it is unresponsive for about 10 seconds or until I click somewhere with a mouse.

**Comment by justinmk** [comment] 2015-01-27 02:06
> nvim seems to be waiting for some mouse event after meta+right key

Looking at `didset_options() => opt_strings_flags()`, `ttym_flags` is ORed until a match is found. If it matches on "urxvt" or "sgr", the ordinal will not match TTYM_URXVT or TTYM_SGR respectively. @glebtv what does `:echo &term` report for you?

Regardless, we need to fix TTYM_URXVT and TTYM_SGR values, although I think they will eventually be obviated by the terminal work @tarruda is doing.

**Comment by glebtv** [comment] 2015-01-27 03:48
```:echo &term``` reports xterm (both broken & good versions)

**Comment by Pyrohh** [comment] 2015-02-17 05:45
@glebtv is this still an issue now that #1820 is merged?

**Comment by Pyrohh** [comment] 2015-04-20 22:00
The TTYM_* values look like dead code, and I can't reproduce the issues regarding `<M-[arrow key]` mappings mentioned above. Besides that, I'll close this as it's been inactive for a while.

**Closed by Pyrohh** 2015-04-20 22:00 UTC
Labels: bug, terminal
