### ISSUE TITLE
:Man ignores $MANWIDTH and $MANOPT

### ISSUE THREAD

**Issue by rumpelsepp** [neovim/neovim#9533] opened 2019-01-21 06:38 UTC
- `nvim --version`: 
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-flySZy/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-flySZy/neovim-0.3.4/build/config -I/build/neovim-flySZy/neovim-0.3.4/src -I/usr/include -I/build/neovim-flySZy/neovim-0.3.4/build/src/nvim/auto -I/build/neovim-flySZy/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Operating system/version: debian/buster
- Terminal name/version: 

```
gnome-terminal --version
# GNOME Terminal 3.30.2 using VTE 0.54.2 +GNUTLS
```

- `$TERM`:

```
echo $TERM
xterm-256color
```

### Steps to reproduce using `nvim -u NORC`

I use `nvim` as manpager using  

```
export MANWIDTH="80"
export MANOPT="--nj --nh"
export MANPAGER="nvim +Man!"
```

in my `~/.profile`. Invoking `nvim` using, e.g., `man 2 open`works as expected. When I use `K` to jump to a related manpage, `nvim` forgets `MANWIDTH` and appearently `MANOPT`.

Using this:

```
$ nvim -u NORC
:Man ls
```

completely ignores `MANWIDTH` (and `MANOPT`).

### Expected behaviour

Remember `MANWIDTH` and `MANOPT` when invoked as manpager and jumping between manpages.

**Comment by justinmk** [comment] 2019-01-21 09:03
MANWIDTH is intentionally not used, instead the text is wrapped using Vim's own soft-wrap plus 'breakindent'. This is a feature.

I've never heard of MANOPT, this is the first time anyone mentioned it. Send a pull request, otherwise it's `wontfix`.

See also https://github.com/neovim/neovim/issues/9271

**Closed by justinmk** 2019-01-21 09:03 UTC

**Comment by rumpelsepp** [comment] 2019-01-21 09:08
> MANWIDTH is intentionally not used, instead the text is wrapped using Vim's own soft-wrap plus 'breakindent'. This is a feature.

Why is it used when you invoke `nvim` as MANPAGER? this is really annoying:

https://asciinema.org/a/Bqc70HcQxvHvtyFmk1A8MYvZ5

**Comment by mhinz** [comment] 2019-02-07 22:25
@rumpelsepp 

When using `man` (the program), it always enforces a hard wrapping. If you don't set `$MANWIDTH`, it may use the whole width of the screen.

The problem is that some systems had problems with a hard wrapping etc. And using the current soft wrapping (internally we use `MANWIDTH=999` here) has the obvious advantage that it works for all window sizes and supports resizing.

If you really want the old behaviour, put this in your vimrc:

```vim
if has('nvim')
  function! s:do_man(args) abort
    let width = exists('$MANWIDTH') ? $MANWIDTH : 80
    let args = empty(a:args) ? expand('<cword>') : a:args
      
    " printf(2) -> 2 printf
    let matches = matchlist(args, '\v^(\w*)\((.*)\)$')
    if !empty(matches)
      let args = matches[2].' '.matches[1]
    endif

    let manpage = system('MANPAGER=cat MANWIDTH='.width.' man '.args)
    if v:shell_error
      echohl WarningMsg | echomsg 'NO SUCH MANPAGE: '. args | echohl NONE
      return
    endif

    enew
    silent put =manpage
    silent 1delete _
    set filetype=man
  endfunction

  autocmd VimEnter * command! -nargs=* Man call s:do_man(<q-args>)
  autocmd FileType man set bufhidden=wipe
endif
```

I did a bit of testing but might have missed some cases. Anyway, it's good enough for personal use. Feel free to add `$MANOPT` etc. to the `system()` call.

**Comment by rumpelsepp** [comment] 2019-02-08 06:47
Thanks for your answer! In the meanwhile, my fix was more pragmatic:

`~/.local/bin/man`
```
#!/bin/bash

# Why?
# https://github.com/neovim/neovim/commit/9081cad514d27ed67f0e348e9db56eddb296cc1d
MANWIDTH=80 exec /usr/bin/man $@
```
