### ISSUE TITLE
Neovim Nightly freezes after pressing <c-x> <c-z>

### ISSUE THREAD

**Issue by Pandademic** [neovim/neovim#17036] opened 2022-01-11 12:40 UTC
### Neovim version (nvim -v)

NVIM v0.7.0-dev+863-g8f27c4a04

### Vim (not Nvim) behaves the same?

I don't know

### Operating system/version

Windows 11 build 22000.376

### Terminal name/version

Windows terminal 1.11.3471.0

### $TERM environment variable

vtpcon

### Installation

scoop ( scoop install neovim-nightly)

### How to reproduce the issue

- Open neovim
- press  control x , right after press control z

### Expected behavior

Neovim is completely frozen and unresponsive

### Actual behavior

Neovim is completely frozen and unresponsive

**Comment by Pandademic** [comment] 2022-01-11 12:41
Originally reported here :

https://github.com/VonHeikemen/fine-cmdline.nvim/issues/21#issuecomment-1009517821

**Comment by zeertzjq** [comment] 2022-01-11 12:53
Is it working fine on v0.6.1?

**Comment by seandewar** [comment] 2022-01-11 12:56
Isn't this #6660?

**Comment by zeertzjq** [comment] 2022-01-11 13:01
@Pandademic Please try to provides steps to reproduce with `nvim --clean`. Especially, is the `<C-X><C-Z>` pressed in Insert mode?

**Comment by VonHeikemen** [comment] 2022-01-11 13:12
The issue was reported on my plugin. I was using this to cancel a failed completion.

```lua
  vim.api.nvim_feedkeys(
    vim.api.nvim_replace_termcodes('<C-x><C-z>', true, false, true),
    'i',
    true
  )
```

According to `:help compl-stop` it should stop completion without changing the text, but it was trying to suspend the process. It does work fine on 0.6.1.

I was able to reproduce this without an `init.lua` or `init.vim` (meaning I didn't have a config file), and just executed that piece of lua code.

In my case the OS was `windows 10` (don't know the exact build version), using [cmder](https://cmder.net/). I did the test in an old laptop. I don't have it right now so I can't give any more details at this time.

**Comment by zeertzjq** [comment] 2022-01-11 13:14
That snippet feeds `<C-X><C-Z>` in Normal mode, not Insert mode. `compl-stop` only applies to Insert mode.

**Comment by VonHeikemen** [comment] 2022-01-11 13:18
Fair enough.

The issue still happened in my plugin, it was triggered in a mapping while the user is in insert mode.

**Comment by Pandademic** [comment] 2022-01-11 13:33
@zeertzjq as soon as you enter neovim (in normal mode) press control x and then control z - In bug report it wouldn't show

**Comment by zeertzjq** [comment] 2022-01-11 13:35
What happens if you only press `<C-Z>`?

**Comment by seandewar** [comment] 2022-01-11 13:35
> > @Pandademic Please try to provides steps to reproduce with `nvim --clean`. Especially, is the `<C-X><C-Z>` pressed in Insert mode?
> 
> @zeertzjq as soon as you enter neovim (in normal mode) press control x and then control z - In bug report it wouldn't show that text

That's expected, as `<C-X><C-Z>` only applies in insert mode, otherwise it'll just suspend nvim with no way to resume on windows like #6660. The problem is if this is also happening in insert mode like @VonHeikemen points out.

**Comment by Pandademic** [comment] 2022-01-11 13:37
> Does the same thing happen if you only press `<C-Z>`?

Let me check

**Comment by Pandademic** [comment] 2022-01-11 13:38
@zeertzjq yes it does

**Comment by Pandademic** [comment] 2022-01-11 13:39
@seandewar nothing wrong happens in insert mode , I belive

**Comment by zeertzjq** [comment] 2022-01-11 13:45
> it was triggered in a mapping while the user is in insert mode.

@VonHeikemen Can you roughly describe what the mapping does?

**Comment by VonHeikemen** [comment] 2022-01-11 13:50
It tries to cancel a completion then closes a popup window.

**Comment by VonHeikemen** [comment] 2022-01-11 14:02
Could it be that the keycode is being send to the window that is below the popup?

**Comment by maple-leaf** [comment] 2022-04-28 04:50
I can reproduce freeze issue on Windows 10 after pressing <c-z> on CMD or PowerShell 7 and doesn't find a way to recover.

Neovim version: NVIM v0.8.0-dev+52-g89df042a8
Windows OS version:
Windows 10 Pro
Version	20H2
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0


![image](https://user-images.githubusercontent.com/3980995/165678485-8072e1a9-d461-409a-9410-be88c8ced728.png)

**Comment by zeertzjq** [comment] 2022-04-28 04:52
@maple-leaf Did you press it in Normal mode?

**Comment by zeertzjq** [comment] 2022-04-28 05:00
I don't think keeping this issue open will lead to any new conclusion. Closing as a duplicate of #6660.

**Closed by zeertzjq** 2022-04-28 05:00 UTC
Labels: bug, platform:windows, status:needs-repro
