### ISSUE TITLE
tui: cursor-shape sometimes gets stuck

### ISSUE THREAD

**Issue by mawaldne** [neovim/neovim#7667] opened 2017-12-01 19:18 UTC
- NVIM v0.2.2
- Vim (version: 8.0) behaves differently? Yes
- OS X 10.12.6
- iTerm2 3.1.5
- xterm-256color
- Tmux 2.6

### Steps to reproduce using `nvim -u NORC`
```
1. tmux
2. nvim -u NORC
3. Hit i to enter insert mode
4. Hit esc to exit insert mode
```
### Actual behaviour

The cursor changes to a vertical bar when entering insert mode, but doesn't change back to a block when hitting esc to exit insert mode. 

### Expected behaviour

The cursor should change to a vertical bar when entering insert mode and change to a block when exiting insert mode.

### Current workaround

This workaround makes the cursor work properly: 

```
au InsertEnter,InsertChange * silent redraw!
au VimEnter,InsertLeave * silent redraw!
```

**Comment by mawaldne** [comment] 2017-12-01 19:32
I should have mentioned, this seems to only happen on a blanks line. When I do this on a line that contains text it works.

**Comment by justinmk** [comment] 2017-12-01 23:57
can you try HEAD?

**Comment by mawaldne** [comment] 2017-12-02 02:40
@justinmk Installed head.
```
➜  ~ nvim --version
NVIM v0.2.3-70-g27f9b1c7b
```

Still the same issue unfortunately.

**Comment by justinmk** [comment] 2017-12-08 08:52
@mawaldne https://github.com/neovim/neovim/commit/a58c9094db0ece13ecfc1a5b328c46a72aa46f76 may have fixed this, could you try latest HEAD again? I can't reproduce this, so I can't test it.

**Comment by mawaldne-surge** [comment] 2017-12-08 15:16
@justinmk Installed:
```
NVIM v0.2.3-103-gafae4b514
```

Same issue. Im wondering if theres something in my tmux / iterm2 setup. I'll play around some more.

**Comment by stellarhoof** [comment] 2017-12-16 05:48
Same issue here:
- NVIM v0.2.3-281-g7afd26a6d
- OS X 10.13.1
- iTerm2 3.1.5
- tmux-256color
- Tmux 2.6

Doesn't happen whilst outside of Tmux.

**Comment by phodge** [comment] 2018-07-05 07:57
The bug can also happen on lines containing text - it seems to be any time that the cursor changes shape but not position, the new cursor shape won't be visible until you move the cursor using a subsequent command.

E.g., any time you enter insert mode using `i` you're somewhat likely to get this behaviour (under iTerm2/tmux), but I'd imagine most users wouldn't notice that the cursor hasn't changed shape because they'll immediately type whatever text they entered insert mode to type, and that will cause iTerm2 to show the correct cursor shape.

Likewise most of the time when you leave insert mode, as long as you're not on the first character of the line, neovim will change cursor shape and also shift the cursor back one character, and moving the cursor seems to cause iTerm2/tmux to show the cursor shape. So you can reproduce the bug somewhat reliably when leaving insert mode but only from the first character of the line.

I couldn't reproduce the bug using vim8, but neovim's code has substantially diverged due to the TUI separation, so it's hard to determine how they differ. It's likely that force-redrawing the cursor or character under the cursor would cause iTerm2/tmux to render the new cursor shape, but I'm not sure how to do that yet, and I'm not convinced it's the correct solution either.

**Comment by justinmk** [comment] 2019-05-16 15:51
https://github.com/neovim/neovim/issues/10013 provides clear repro steps:

> 1. nvim -u NORC
> 1. :h
> 1. press `c` and then use hjkl, you will find curosr keep `_` shape
> 1. you will find that cursor shape can't reset to block by `ESC`.

**Comment by shmerl** [comment] 2019-08-29 16:31
@justinmk: is it known what's the root cause for cursor not changing?

**Comment by zeertzjq** [comment] 2022-11-14 12:22
Is #10013 really a duplicate of this? The steps to reproduce looks completely different.

**Comment by zeertzjq** [comment] 2024-02-05 01:01
Closing as this issue is quite old and contains a lot of outdated information.

**Closed by zeertzjq** 2024-02-05 01:01 UTC
Labels: tui, needs:repro, bug-regression
