### ISSUE TITLE
cat'ing binary file causes abort

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#5442] opened 2016-10-06 23:39 UTC
This will crash nvim 0.1.6 (and probably much older):

    :!cat build/bin/nvim
    src/nvim/ui.c:507: ui_cursor_left: Assertion `new_col >= 0` failed

This isn't a super important problem given that the "normal" behavior is to trash the terminal, but fixing it may lead to insight. Actually https://github.com/neovim/neovim/pull/4376 should fix it.

**Comment by phanimahesh** [comment] 2016-10-07 08:40
This doesn't happen with vim. The terminal gets trashed, yes, but there's no crash.

**Comment by milsen** [comment] 2016-10-08 21:03
This looks like a duplicate of #4142.

**Closed** 2016-10-09 06:36 UTC
Labels: bug, bug-crash, duplicate
