### ISSUE TITLE
Async writes

### ISSUE THREAD

**Issue by TonyTomCat01** [neovim/neovim#18173] opened 2022-04-19 13:28 UTC
### Feature description

Hello. I have seen the other thread on Github requesting for async writes to filesystem. I am currently having arch on a portable usb which is slow to write. When I write a file in neovim it usually takes from 4 to 30 seconds on my machine. And I have to wait the entire time for neovim to write the file which makes the experience terrible. It would be nice if this feature is added to neovim. I don't know if this feature already exists in neovim. If it does, please tell me.

**Comment by dundargoc** [comment] 2022-04-19 18:19
Duplicate of https://github.com/neovim/neovim/issues/11005.

I'll close this if you don't mind, it's easier to keep track of issues if it's contained in one place.

**Closed by dundargoc** 2022-04-19 18:19 UTC
Labels: enhancement, io
