### ISSUE TITLE
Neovim did not start again due to the following error

### ISSUE THREAD

**Issue by duytrung** [neovim/neovim#7493] opened 2017-11-06 09:22 UTC
- `nvim --version`: 0.2.1 beta

- Operating system/version: Windows 10
- Terminal name/version: CMD
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour

```
> nvim
function rtags#InitPython[9]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):ch 1 was closed by the client
Traceback (most recent call last):^M
  File "<string>", line 1, in <module>^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\__init__.py", line 70, in start_host^M
    session = stdio_session()^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 37, in stdio_session^M
    return session('stdio')^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 18, in session^M
    loop = EventLoop(transport_type, *args, **kwargs)^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\msgpack_rpc\event_loop\base.py", line 88, in __init__^M
    getattr(self, '_connect_{}'.format(transport_type))(*args)^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\msgpack_rpc\event_loop\asyncio.py", line 93, in _connect_stdio^M
    self._loop.run_until_complete(coroutine)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\base_events.py", line 467, in run_until_complete^M
    return future.result()^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\base_events.py", line 1115, in connect_write_pipe^M
    transport = self._make_write_pipe_transport(pipe, protocol, waiter)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\proactor_events.py", line 424, in _make_write_pipe_transport^M
    sock, protocol, waiter, extra)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\proactor_events.py", line 317, in __init__^M
    self._read_fut = self._loop._proactor.recv(self._sock, 16)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\windows_events.py", line 430, in recv^M
    self._register_with_iocp(conn)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\windows_events.py", line 611, in _register_with_iocp^M
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)^M
OSError: [WinError 6] The handle is invalid^M
Exception ignored in: <bound method _ProactorBasePipeTransport.__del__ of <_ProactorWritePipeTransport closing fd=1>>^M
Traceback (most recent call last):^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\proactor_events.py", line 97, in __del__^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\proactor_events.py", line 84, in close^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\base_events.py", line 574, in call_soon^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\base_events.py", line 357, in _check_closed^M
RuntimeError: Event loop is closed^M
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
Press ENTER or type command to continue

```
Python 3.6.3 by Anaconda

**Comment by justinmk** [comment] 2017-11-06 10:21
Duplicate of https://github.com/neovim/neovim/issues/7326 .

In https://github.com/neovim/neovim/issues/7326 you said:

> nVim should run, with a message saying that the plugin has caused error and it will not be loaded.

So what's actually happening? Is nvim closing? Is it crashing (does Windows show the crash-report dialog)?

Does the problem always occur with the same plugin ("rtags")?

**Closed by justinmk** 2017-11-06 10:21 UTC

**Comment by gwerbin** [comment] 2017-12-12 16:38
@justinmk I have this exact same problem. You can start Neovim normally after the big error message. It doesn't crash and runs fine otherwise.

**Comment by shahla69** [comment] 2018-09-18 13:00
hi
Would you mind telling me where my problem is ?
I run a Python file, but it does not run full and ends in the middle of the run!!

C:\Users\Hatami\Desktop\test\AdaptiveTrafficSignalControl-master>python four_int
ersects.py
Traceback (most recent call last):
  File "four_intersects.py", line 403, in <module>
    main()
  File "four_intersects.py", line 395, in main
    fixed_control_run(10)
  File "four_intersects.py", line 168, in fixed_control_run
    game_env.reset()
  File "C:\Users\Hatami\AppData\Local\Programs\Python\Python36\lib\site-packages
\gym\wrappers\time_limit.py", line 44, in reset
    return self.env.reset()
  File "C:\Users\Hatami\AppData\Local\Programs\Python\Python36\lib\site-packages
\gym\envs\toy_text\four_intersects_env.py", line 121, in reset
    self.start_sumo()
  File "C:\Users\Hatami\AppData\Local\Programs\Python\Python36\lib\site-packages
\gym\envs\toy_text\four_intersects_env.py", line 108, in start_sumo
    traci.start(self.sumo_cmd)
  File "C:\Program Files (x86)\DLR\Sumo\tools\traci\__init__.py", line 82, in st
art
    sumoProcess = subprocess.Popen(cmd + ["--remote-port", str(port)])
  File "C:\Users\Hatami\AppData\Local\Programs\Python\Python36\lib\subprocess.py
", line 594, in __init__
    _cleanup()
  File "C:\Users\Hatami\AppData\Local\Programs\Python\Python36\lib\subprocess.py
", line 205, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "C:\Users\Hatami\AppData\Local\Programs\Python\Python36\lib\subprocess.py
", line 1027, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid

python3.6
windows 7
 please help me
