### ISSUE TITLE
:terminal buffer in multiple splits after loading session

### ISSUE THREAD

**Issue by candronikos** [neovim/neovim#5250] opened 2016-08-25 01:03 UTC
- `nvim --version`: `NVIM 0.1.5-dev`
- Operating system/version: `Ubuntu 14:04`
- Terminal name/version: `Bash`
- `$TERM`: `xterm-256color`
### Actual behaviour

When a terminal buffer is in viewed through multiple windows it works fine.
After the session is reloaded using the `-S session.vim` switch the two windows point to separate buffers
### Expected behaviour

I expected the different windows to point to the same `:terminal` buffer
### Steps to reproduce
1. Start nvim
2. `:terminal`
3. `:split`
4. `:mksession session.vim`
5. quit nvim
6. In bash prompt `nvim -S session.vim`
7. `:ls` will show two termial buffers

**Comment by waynr** [comment] 2017-02-09 05:12
I wasn't able to reproduce this with the steps given since I was unfamiliar with how to get back to normal mode from terminal mode. The documentation helped: https://neovim.io/doc/user/nvim_terminal_emulator.html#terminal-emulator-input

So the more explicit reproduction steps are as follows:

1. `nvim`
1. `:terminal`
1. `<C-\> <C-n>`
1. `:split`
1. `:mksession session.vim`
1. `; q <CR>`
1. `nvim -S session.vim`

**Comment by waynr** [comment] 2017-02-09 05:24
Here's the resulting `session.vim` script:

```

**Comment by waynr** [comment] 2017-02-09 06:05
Here's the resulting `session.vim` script:

```vimscript
let SessionLoad = 1
let s:so_save = &so | let s:siso_save = &siso | set so=0 siso=0
let v:this_session=expand("<sfile>:p")
silent only
cd ~/projects/neovim
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO
badd +0 term://.//24601:/bin/bash
argglobal
silent! argdel *
set splitbelow splitright
wincmd _ | wincmd |
split
1wincmd k
wincmd w
set nosplitbelow
set nosplitright
wincmd t
set winheight=1 winwidth=1
exe '1resize ' . ((&lines * 35 + 36) / 73)
exe '2resize ' . ((&lines * 35 + 36) / 73)
argglobal
edit term://.//24601:/bin/bash
setlocal fdm=syntax
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
let s:l = 98 - ((6 * winheight(0) + 17) / 35)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
98
normal! 0
wincmd w
argglobal
edit term://.//24601:/bin/bash
setlocal fdm=syntax
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
let s:l = 98 - ((34 * winheight(0) + 17) / 35)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
98
normal! 0
wincmd w
exe '1resize ' . ((&lines * 35 + 36) / 73)
exe '2resize ' . ((&lines * 35 + 36) / 73)
tabnext 1
if exists('s:wipebuf') && getbufvar(s:wipebuf, '&buftype') isnot# 'terminal'
  silent exe 'bwipe ' . s:wipebuf
endif
unlet! s:wipebuf
set winheight=1 winwidth=20 shortmess=filnxtToO
let s:sx = expand("<sfile>:p:r")."x.vim"
if file_readable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &so = s:so_save | let &siso = s:siso_save
doautoall SessionLoadPost
unlet SessionLoad
" vim: set ft=vim :
```

Here I see two occurrences of `edit term://.//24601:/bin/bash`. Looking at my process list while `nvim` is running with a terminal emulator I see that whatever number is in the position of `24601` shown here is the process ID of the shell embedded in the vim terminal. When I perform the following sequence of actions:

1. `nvim` inside a bash shell
1. `:edit term://.//24601:/bin/bash`

Instead of running a terminal buffer that has a bash shell with PID 24601 I end up with some random OS-assigned PID (of course) rather than exactly the PID I specified. If I run `:edit term://.//24601:/bin/bash` again immediately after escaping back to normal mode I end up with a second terminal buffer with different PID than the first. This seems like logical behavior and explains why the `session.vim` script shown above doesn't work--there is no bash shell with PID 24601 running in a terminal buffer known by the new nvim process.

On the other hand, if I perform the following sequence of actions:

1. `nvim` inside a bash shell
1. `:split`
1. `:term` <- say this runs a bash shell with PID 1234
1. `<C-\><C-n>` escape terminal mode
1. `<C-w>j` move to the non-terminal pane
1. `:edit term://.//1234:/bin/bash`

I end up with two panes showing the same terminal buffer with the same shell, which I believe is @candronikos' expected behavior from simply running `nvim -S session.vim` in the original problem statement. This was my way of confirming that using the PID of a bash shell running in an existing nvim terminal buffer would obtain the expected behavior.

So at this point it seems to me like the bug is in one of two different places:

1. The generation of the vimscript by `mksession`.
1. The interpretation of the vimscript by `nvim -S session.vim`.

I'm really not familiar enough with either the mksession nor the vimscript interpreter internals to suggest which of these makes more sense but would be happy to take direction from someone more experienced with this codebase in how to approach a fix for this issue.

**Closed** 2020-01-27 03:03 UTC
Labels: :terminal, bug, complexity:low
