### ISSUE TITLE
Change to Terminal mode when switching from split in Insert mode to terminal split

### ISSUE THREAD

**Issue by ayhon** [neovim/neovim#13980] opened 2021-02-20 18:59 UTC
[This](https://github.com/neovim/neovim/issues/7286) is the closest issue I could find, but it talks about `netrw`, not the emulated terminal. Also, I wouldn't count this as a bug, it works as expected, but I think changing its behavior would make it much better, as a QoL improvement.

- `nvim --version`: 
```bash
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstac
k-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE
_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -
Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototype
s -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_
GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/
build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/
include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/buil
d/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
It doesn't. It behaves the same way.
For the record, I have nvim aliased to vim (Done by the OS itself, since I dont have their `vim` package installed), so that may be why it behaves the same way. I just don't know how to reverse this without uninstalling `nvim`.
- Operating system/version:
Pop!_OS 20.10
- Terminal name/version: `gnome-terminal`, 3.36.2 
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`
```viml
nvim -u NORC
:set mouse=a
:sp term://bash
 " click out of terminal split "
i
 " click  in terminal split "
```
Basically, with `:set mouse=a`, create a terminal split and switch into it by clicking it with the mouse while in insert mode in another split

### Actual behaviour
Since the terminal buffer cannot be modified from insert mode, if you type anything, nvim gives an error about trying to modify a buffer with modifiable off
```
E21: Cannot make changes, 'modifiable' is off
```

### Expected behaviour
Since Insert mode in a terminal buffer is useless, make it so when you switch splits this way, you enter into the terminal mode where you can type commands to the shell. Supposedly, if you were in insert mode and switched to the terminal split, it's because you want to keep typing something, so having to dismiss the error messages, press `Esc` and then `i` again can be annoying.

![image](https://user-images.githubusercontent.com/43295942/108605611-81ddbe80-73b5-11eb-828a-0dc2021d3af0.png)
*Undesirable outcome*

---

![image](https://user-images.githubusercontent.com/43295942/108605614-902bda80-73b5-11eb-8cbe-59be80f9f917.png)
*Inside terminal in Insert mode*

---

![image](https://user-images.githubusercontent.com/43295942/108605768-9b333a80-73b6-11eb-971b-6352bfcc7a17.png)
*The Terminal mode, what I suggest is the desirable outcome*

**Comment by glacambre** [comment] 2021-02-24 10:31
If this suggestion is implemented, I think it would make sense to have `<Cmd>` behave in the same way, as I suggested in https://github.com/neovim/neovim/issues/12246#issuecomment-623326647 .

**Comment by glacambre** [comment] 2021-06-10 06:11
I think @mjlbach plans on making insert mode in terminal buffers usable, which would conflict with this enhancement request?

**Comment by ayhon** [comment] 2021-06-14 08:08
> I think @mjlbach plans on making insert mode in terminal buffers usable, which would conflict with this enhancement request?

What would insert mode in terminals do?

**Comment by mjlbach** [comment] 2021-06-14 08:12
I think @glacambre is referring to allowing insert mode to enter mid-prompt, currently entering insert mode doesn't respect the cursor position, and will instead place the cursor at prompt end.

**Comment by glacambre** [comment] 2021-06-14 17:59
>What would insert mode in terminals do?

Allow you to edit the content of the buffer as if it was a regular buffer :).

**Comment by ColinKennedy** [comment] 2024-01-20 07:45
Just came here to mention that I would love this feature, I miss it from Vim. For anyone who wants this immediately, somehow https://github.com/akinsho/toggleterm.nvim figured out how to add this feature in, which is what I now use for all of my terminal needs

**Comment by zeertzjq** [comment] 2024-01-20 08:06
Duplicate of #7164

**Closed by zeertzjq** 2024-01-20 08:06 UTC
Labels: enhancement, terminal
