### ISSUE TITLE
Can not map <C-m> anymore

### ISSUE THREAD

**Issue by 0b11stan** [neovim/neovim#18245] opened 2022-04-24 19:46 UTC
### Neovim version (nvim -v)

0.8.0 commit 843d9223a14c599fda1b2abf1e7072be738fb831

### Vim (not Nvim) behaves the same?

no, vim 8.2.4651

### Operating system/version

archlinux

### Terminal name/version

alacritty

### $TERM environment variable

xterm

### Installation

Tarball

### How to reproduce the issue

On a fresh install (`podman run -it --rm docker.io/archlinux`).

Download last version of neovim and run it :

```bash
curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
./nvim-linux64/bin/nvim
```

Inside nvim play the following commands:

```vim
:map <C-l> :echo "test l"<CR>
:map <C-m> :echo "test m"<CR>
```

Then, press `CTRL + L` or `CTRL + M` and compare the difference.

### Expected behavior

I should see on the bottom of my terminal :

* when pressing `CTRL + L` : `test l`
* when pressing `CTRL + M` : `test m`

### Actual behavior

The mapping does work for `CTRL + L` (I see the test message) but it don't work for `CTRL + M` (I don't see anything).

FYI, the result of `:nmap` : 
```vim
   <C-L>         :echo 'test l'<CR>
n  %             <Plug>(MatchitNormalForward)
n  Y           * y$
n  [%            <Plug>(MatchitNormalMultiBackward)
n  ]%            <Plug>(MatchitNormalMultiForward)
n  gx            <Plug>NetrwBrowseX
n  g%            <Plug>(MatchitNormalBackward)
   <C-M>         :echo 'test m'<CR>
n  <Plug>NetrwBrowseX * :call netrw#BrowseX(netrw#GX(),netrw#CheckIfRemote(netrw#GX()))<CR>
n  <Plug>(MatchitNormalMultiForward) * :<C-U>call matchit#MultiMatch("W",  "n")<CR>
n  <Plug>(MatchitNormalMultiBackward) * :<C-U>call matchit#MultiMatch("bW", "n")<CR>
n  <Plug>(MatchitNormalBackward) * :<C-U>call matchit#Match_wrapper('',0,'n')<CR>
n  <Plug>(MatchitNormalForward) * :<C-U>call matchit#Match_wrapper('',1,'n')<CR>
```

**Comment by gpanders** [comment] 2022-04-24 20:03
Duplicate of #17867

**Closed by gpanders** 2022-04-24 20:03 UTC
Labels: bug

**Comment by gpanders** [comment] 2022-04-24 20:04
By the way if you're using alacritty you can get around this by adding

```yaml
key_bindings:
  - { key: M, mods: Ctrl, chars: "\x1b[109;5u" }
```

**Comment by 0b11stan** [comment] 2022-04-24 21:56
Damn, sorry for the duplicate and thank you for your tips !!
