### ISSUE TITLE
setloclist incompatibility with Vim after 7.4.2200

### ISSUE THREAD

**Issue by still-dreaming-1** [neovim/neovim#5314] opened 2016-09-08 00:49 UTC
- `nvim --version`: 0.1.6-dev
- Vim (version: 7.4.2295) behaves differently? Yes
- Operating system/version: Linux Mint 17.3 64 bit Cinnamon Edition
- Terminal name/version: GNOME Terminal 3.6.2
- `$TERM`: xterm-256color
### Actual behaviour

When the Syntastic plugin is installed, upon opening a file in a buffer, the following error messages appear:

```
Error detected while processing function <SNR>80_BufEnterHook[9]..<SNR>80_UpdateErrors[41]..873:                                                                                              
line   10:                                                                                                                                                                                    
E731: using Dictionary as a String                                                                                                                                                            
Error detected while processing function <SNR>80_BufEnterHook[9]..<SNR>80_UpdateErrors:                                                                                                       
line   41:                                                                                                                                                                                    
E171: Missing :endif                                                                                                                                                                          
Error detected while processing function <SNR>80_BufEnterHook:                                                                                                                                
line    9:                                                                                                                                                                                    
E171: Missing :endif
```
### Expected behaviour

It should behave the same as Vim. It should be possible to open a file in a buffer without errors with Syntastic installed.

The Syntastic developer says they don't support Neovim, but it "should" work. The developer claims this error message does not make sense for Vim and they recommended reporting an issue with Neovim. [Here](https://github.com/scrooloose/syntastic/commit/557b52fb206e0151f057326f5a8b3574298ea43b) is the Syntastic commit that introduces the issue. [Here](https://github.com/scrooloose/syntastic/issues/1868) is an issue reported to Syntastic about this.

**Comment by justinmk** [comment] 2016-09-08 08:17
Probably because we still have sticky types, in which case syntastic doesn't support older Vim either.

**Comment by nhooyr** [comment] 2016-09-08 11:07
Just to let you know, there exists a syntastic alternative for neovim https://github.com/neomake/neomake

**Comment by justinmk** [comment] 2016-09-08 11:23
Can someone who uses syntastic, bisect to the related Neovim commit?

**Comment by duckpuppy** [comment] 2016-09-08 11:47
@justinmk There's a link to the offending commit in the issue report.

**Comment by justinmk** [comment] 2016-09-08 11:53
@duckpuppy We need the bisected neovim commit, not syntastic.

**Comment by jamessan** [comment] 2016-09-08 12:45
The issue is that we made a [change](https://github.com/neovim/neovim/commit/39c38426214c931b45a428f07213a896bd9c46a4) to setloclist to allow setting the title, based on patches that had been proposed on vim-dev.  When the functionality finally got merged in Vim, it was to accept a dictionary of values rather than just a string to set the title.

Syntastic checks for whether Vim supports the extra argument by running

```vim
        try
            " Vim 7.4.2200 or later
            call setloclist(0, [], 'r', { 'title': '' })
        catch /\m^Vim\%((\a\+)\)\=:E118/
            " do nothing
        endtry
```

That works in Vim because it's either too old and emits

> E118: Too many arguments for function: setloclist

or it is new enough and the argument is a dictionary, as expected.

When you do the same in Neovim, you get the error

> E731: using Dictionary as a String

because we aren't expecting a dictionary.

**Comment by jamessan** [comment] 2016-09-08 14:41
Syntastic should be fixed (for now) with https://github.com/scrooloose/syntastic/commit/998179747a5715114c5a9e9b94317d73f4fd4d3d.  However, we need to catch up on Vim patches to avoid other breaking as Syntastic takes advantage of other recent Vim functions.

**Closed** 2017-02-27 19:36 UTC
Labels: bug, compatibility
