### ISSUE TITLE
Neovim takes very long to open a file containing long lines

### ISSUE THREAD

**Issue by the42** [neovim/neovim#9379] opened 2018-12-19 18:58 UTC
- `nvim --version`:
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

- Operating system/version: Manjaro Linux, also tested with Emacs
- Terminal name/version: Plasma Konsole 

```
nvim -u NORC Editthelargefile.txt

```

### Actual behaviour
Loading takes ~3 Minutes, consumes 25% CPU (of four cores)

### Expected behaviour
Load at least as fast as Emacs (~3 seconds)

I can't disclose the text file (~700MB log data). The file attached contains the length of every line to get an idea about the line length distribution.
[len.txt](https://github.com/neovim/neovim/files/2696172/len.txt)

**Comment by justinmk** [comment] 2018-12-19 19:30
Known issue. Try `nvim -u NONE` instead of `NORC`. 

> Load at least as fast as Emacs (~3 seconds)

Depends on the major-mode , line wrap,  etc. See also https://github.com/neovim/neovim/issues/3508#issuecomment-187017835 . 

> emacs-devel had a [related discussion](https://lists.gnu.org/archive/html/emacs-devel/2015-12/msg00385.html) regarding macro performance. (See also [emacs bug 13675](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=13675).)

>> The main problem, in a nutshell, is that to get to the next visual
>> line, you need to traverse all the characters of the preceding line.
>> Going backward (which happens every time you type C-p, and also many
>> times behind the scenes, e.g., when Emacs needs to determine where to
>> set the window start for next redisplay) is even more problematic,
>> since Emacs can currently only do that by starting from the beginning
>> of the previous _physical_ line (there's an optimization in this
>> regard for preposterously long lines, but it loses accuracy -- it
>> could cause horizontal scrolling when you move point vertically).
>> 
>> ...
>> 
>> Repeating a keyboard macro without intervening other actions means that
>> the macro, after achieving its changes, has to progress to the next
>> position where executing it makes sense as its last part.

Going to consider this a duplicate of #3508 .

**Closed by justinmk** 2018-12-19 19:30 UTC
