### ISSUE TITLE
neovim reacts sloppishly to input, causing things to happen that shouldn't

### ISSUE THREAD

**Issue by fiesh** [neovim/neovim#7056] opened 2017-07-21 11:15 UTC
I raised an issue with YouCompleteMe (https://github.com/Valloric/YouCompleteMe/issues/2725).  Since it cannot be reproduced with Vim, I was told to report it here.

I suppose https://github.com/Valloric/YouCompleteMe/issues/2725#issuecomment-316970040 is the way to reproduce the problem?

Please let me know how I can help isolate the issue further.  Thanks!

**Comment by jamessan** [comment] 2017-07-21 11:52
Duplicate of #6166

**Closed by jamessan** 2017-07-21 11:52 UTC
