### ISSUE TITLE
Cannot (re-)install neovim on Kubuntu 15.04

### ISSUE THREAD

**Issue by JCavallo** [neovim/neovim#2966] opened 2015-07-06 08:46 UTC
Rebuild on current head (deab194413af1475f8f4d8657500c1250521059e) as I usually do once a week.

Everything went fine, until I "installed'' :

```
/usr/local/share/nvim/runtime/doc already exists
CMake Error at cmake/GenerateHelptags.cmake:38 (message):
  Generating helptags failed:
 $   ] Error 2rget 'install' failedts/Neovim/build'
```

Prompt ends up corrupted.

uname -a
Linux Gaia 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fwalch** [comment] 2015-07-06 09:44
Try removing `/usr/local/share/nvim` and then run `make install` again.

Btw, if you're on Kubuntu, maybe using the [PPA](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable) is more convenient for you.

**Comment by JCavallo** [comment] 2015-07-06 09:51
Removing the directory solved the case. Still, I never had to do it before, and the prompt corruption may be worth investigating.

**Comment by fwalch** [comment] 2015-07-06 11:13
I think the prompt corruption occurs because Neovim crashes and thus doesn't reset the terminal properly. The issue is caused by the previously existing tags file containing invalid tags (because documentation was changed/removed in the meantime). I think we could solve this by just deleting an existing tags file before generating the helptags.

**Comment by justinmk** [comment] 2015-07-06 11:16
We have another issue covering this, so closing this one.

**Closed by justinmk** 2015-07-06 11:16 UTC

**Comment by fwalch** [comment] 2015-07-06 11:22
(The other issue where is is mentioned is https://github.com/neovim/neovim/issues/2364#issuecomment-91845325).
