### ISSUE TITLE
Recovery mode hangs

### ISSUE THREAD

**Issue by toslunar** [neovim/neovim#12492] opened 2020-06-16 03:03 UTC
`nvim -r file` fails to start, while "`nvim file` then `r` (Recover)" works.

- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
Yes.  Vim 8.1 does not cause the issue in my environment.
- Operating system/version: macOS 10.15.4
- Terminal name/version: iTerm2 3.3.11
- `$TERM`: `xterm-256color`
  - I also tested with `TERM=ansi-256color` but it didn't help.

### Steps to reproduce using `nvim -u NORC`

1. Open a file and insert "a".
   ```
   LANG=en_US nvim -u NORC /foo.txt
   ia<Esc>
   ```
2. Kill the process and open the file path with `-r` from a new terminal.
   ```
   pgrep nvim | xargs kill
   LANG=en_US nvim -u NORC -r /foo.txt
   ```
3. (Ctrl-C and remove the second swap file (`rm ~/.local/share/nvim/swap//%foo.txt.swo`) to clean up the failure at Step 2.)

### Actual behaviour

Step 2. shows the following message and then hangs.
```
Using swap file "~/.local/share/nvim/swap//%foo.txt.swp"
Original file "/foo.txt"
"/foo.txt" [New File]
Recovery completed. You should check if everything is OK.
(You might want to write out this file under another name
and run diff with the original file to check for changes)
You may want to delete the .swp file now.

Press ENTER or type command to continue
```

### Expected behaviour

Selecting "(R)ecover" after starting nvim without `-r` works fine.

```
LANG=en_US nvim -u NORC /foo.txt
r
```

<details><summary>output</summary>

```
E325: ATTENTION
Found a swap file by the name "~/.local/share/nvim/swap//%foo.txt.swp"
          owned by: tos   dated: Tue Jun 16 11:09:14 2020
         file name: /foo.txt
          modified: YES
         user name: tos   host name: tospfn3.local
        process ID: 42416
While opening file "/foo.txt"
      CANNOT BE FOUND
(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r /foo.txt"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/Users/tos/.local/share/nvim/swap//%foo.txt.swp"
    to avoid this message.

Swap file "~/.local/share/nvim/swap//%foo.txt.swp" already exists!
[O]pen Read-Only, (E)dit anyway, (R)ecover, (D)elete it, (Q)uit, (A)bort:
```
```
Using swap file "~/.local/share/nvim/swap//%foo.txt.swp"
"/foo.txt" [New File]
Recovery completed. You should check if everything is OK.
(You might want to write out this file under another name
and run diff with the original file to check for changes)
You may want to delete the .swp file now.


Press ENTER or type command to continue
```

</details>

`LANG=en_US nvim -u NORC -r` correctly lists the swap file(s).

<details><summary>output</summary>

```
Swap files found:
   In directory ~/.local/share/nvim/swap//:
1.    %foo.txt.swp
          owned by: tos   dated: Tue Jun 16 11:09:14 2020
         file name: /foo.txt
          modified: YES
         user name: tos   host name: tospfn3.local
        process ID: 42416
```

</details>

**Comment by glacambre** [comment] 2020-06-16 03:49
This looks like a duplicate of 
https://github.com/neovim/neovim/issues/12025 and 
https://github.com/neovim/neovim/issues/11386 . Could you try nightly?

**Comment by toslunar** [comment] 2020-06-16 08:25
> This looks like a duplicate of #12025 and #11386 . Could you try nightly?

Thanks.  I tried nightly (e628a05) and the issue persisted.

```
NVIM v0.5.0-nightly
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200616-7872-18qprz9/build/config -I/tmp/neovim-20200616-7872-18qprz9/src -I/usr/local/include -I/tmp/neovim-20200616-7872-18qprz9/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200616-7872-18qprz9/build/src/nvim/auto -I/tmp/neovim-20200616-7872-18qprz9/build/include
Compiled by tos@MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-e628a05/share/nvim"

Run :checkhealth for more info
```
, which is from homebrew
```
brew install luarocks
brew install --HEAD neovim
```

**Closed** 2020-06-22 21:04 UTC
Labels: bug

**Comment by toslunar** [comment] 2020-06-23 08:33
Thanks!
