### ISSUE TITLE
Opening netrw spawns wl-paste hundreds of times

### ISSUE THREAD

**Issue by jaroslawr** [neovim/neovim#11965] opened 2020-02-29 11:37 UTC
I am using neovim 0.4.3, as shipping in debian testing right now, under wayland and gnome-terminal. When I open a directory in netrw, the gnome-terminal title bar starts to flicker and continues to do so for several seconds. It seems to happen because neovim executes `wl-paste` hundreds of time when opening netrw.

**Comment by bfredl** [comment] 2020-02-29 13:05
Fixed on 0.5 master https://github.com/neovim/neovim/commit/6c22c7ab97cca9f8dda6863ee7f1db1ce30a3451  #11616 

Candidate for 0.4.4? (not a 0.4 regression, but nvim specific bug due to different clibpoard semantics than vim).

**Comment by justinmk** [comment] 2020-03-01 02:35
backported https://github.com/neovim/neovim/commit/5e47cf27b4d82cb0ccfa7859beaa29afb0af4bed

**Closed by justinmk** 2020-03-01 02:35 UTC
Labels: bug, maintenance:backported
