### ISSUE TITLE
Can't open the same man page twice since #4449 got merged

### ISSUE THREAD

**Issue by george-b** [neovim/neovim#5172] opened 2016-08-05 12:27 UTC
- `nvim --version`: NVIM 0.1.5-dev
- Vim (version: ) behaves differently? N/A
- Operating system/version: SLES 11 SP3
- Terminal name/version: PuTTY
- `$TERM`: screen-256color

### Actual behaviour

A new split is opened with the buffer name "man://cd(n)" when trying to view the man page for `cd`.

### Expected behaviour

The man page to be displayed.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:Man cd
:q!
:Man cd
```

**Comment by KillTheMule** [comment] 2016-08-05 12:46
There are several new PRs about the newly merged man plugin, to improve some aspects. Did you check if those might include your problem?

**Comment by nhooyr** [comment] 2016-08-05 12:48
No, those PRs address other problems.

**Comment by nhooyr** [comment] 2016-08-05 17:20
This isn't a problem with the new man.vim. You discovered a bug in vim and neovim! @jamessan is working on a fix.

**Comment by george-b** [comment] 2016-08-05 17:49
Huh interesting. Sorry I marked "Vim (version: ) behaves differently?" as "N/A" because I thought this was exclusive to the new man.vim plugin (where I first hit that and have not seen such behavior before). Thanks for the heads up!

**Comment by jamessan** [comment] 2016-08-05 17:53
It is being triggered by @nhooyr's changes to the man plugin, but the behavior happens when using the plugin with Vim as well.  I've narrowed down the exact behavior and am putting together tests and a fix.

**Comment by jamessan** [comment] 2016-08-05 18:00
Hmm, except this causes one of Vim's tests to fail...

> " test abandoning changed buffer, should be unloaded even when 'hidden' set

It seems to be expected behavior, but I don't understand the reasoning behind that.  I'll being this up on vim_dev and see what comes of it.

**Comment by nhooyr** [comment] 2016-08-05 18:01
But the buffer isn't changed? `nomodified` is explicitly set.

**Comment by jamessan** [comment] 2016-08-05 18:04
Don't let the `'modified'` bit throw you off.  The key part is testing that a buffer is unloaded even if `'hidden'` is set.  Since the buffer isn't backed by a file, unloading it means that when it is refocused it needs to get re-read from disk ... where it doesn't exist.

**Comment by ZyX-I** [comment] 2016-08-06 06:05
@jamessan It does not need to be re-read *from disk*. Vim provides lots of autocommands, including `*Cmd` ones that help you deal with files that are not on disk. And when buffer gets loaded again `BufReadCmd` is correctly triggered again.

**Comment by jamessan** [comment] 2016-08-06 12:12
> *Cmd autocommands are what were designed to deal with files that are not on disk.

I agree that's a better way to deal with loading the contents of the man buffers, but I still disagree that it's acceptable for `:q!` to unload a hidden buffer.  The `!` should only be relevant when there is a need to abandon a buffer, which isn't the case when hidden is set.

**Comment by jamessan** [comment] 2016-08-06 17:06
@george-b I guess the prevailing sentiment is "If that hurts, don't do it."  That is, don't use ":q!" when you don't want to lose data.  @nhooyr's refactoring should avoid the issue, though.

**Comment by george-b** [comment] 2016-08-06 18:01
> @george-b I guess the prevailing sentiment is "If that hurts, don't do it." That is, don't use ":q!" when you don't want to lose data

Sure.

>  @nhooyr's refactoring should avoid the issue, though.

Looking forward to it.

**Closed** 2016-08-07 20:55 UTC
