### ISSUE TITLE
PCREs for search and replace

### ISSUE THREAD

**Issue by nyarly** [neovim/neovim#5413] opened 2016-09-30 21:20 UTC
### Actual behaviour

Vim and Neovim both use a very old format for search patterns. For instance, \< marks a beginning of word, where the rest of the world (thanks to Perl, and Posix EREs) uses \b as a word boundary. Lookahead is even worse.

The end result is that one unavoidably needs to keep in mind both formats in order to use these powerful features.

### Expected behaviour

It'd be nice to be able to selectively enable PCREs in specific contexts. I'd assume a global toggle would break scripts and plugins, but for example being able to toggle them for a particular script file or (the motivating case) for the editor command line.

The PCRE option would need to include Neovim specific variants (e.g. cursor position)

**Comment by brcolow** [comment] 2016-09-30 21:52
Looks like a duplicate of https://github.com/neovim/neovim/issues/3208.

**Closed** 2016-09-30 22:00 UTC
Labels: duplicate

**Comment by ZyX-I** [comment] 2016-09-30 22:05
BTW, what is worse in lookahead? Also rest of the world has fixed-length lookbehind (at most, a number of branches, each has fixed length), only Vim allows things like `\%(abc.*\)\@<=`.

**Comment by nyarly** [comment] 2016-09-30 22:20
Vim's lookaround *behavior* is excellent, including selecting DTFA when appropriate. The *syntax* is the complaint: in PCRE you'd have `(?<abc.*)` and variant syntax for such a powerful but uncommonly used feature is a tremendous blow to usability.

**Comment by kaiuri** [comment] 2022-02-10 23:45
@nyarly

I am currently working on that and have a prototype already packaged into an [app](https://github.com/kaiuri/vrex), which you can pass some PCRE compliant regex and get a regular expression that's compatible with Vim's new NFA Regex Engine, more tests are needed but it seems to work. Feel free to drop in and give insights or help out on it.
https://github.com/kaiuri/vrex
