### ISSUE TITLE
Weird Bracketed Paste Behaviour

### ISSUE THREAD

**Issue by Gee19** [neovim/neovim#17035] opened 2022-01-11 05:42 UTC
### Neovim version (nvim -v)

v0.6.0-dev+569-g2ecf0a4c6

### Vim (not Nvim) behaves the same?

no, 8.2.3458

### Operating system/version

Ubuntu 18

### Terminal name/version

Windows Terminal & Kitty

### $TERM environment variable

xterm-256color

### Installation

AppImage

### How to reproduce the issue

Copy the following text to system clipboard, although this happens with any text:
`return sep.join(args)`

```
nvim --clean
In normal mode, press Ctrl-Shift-V
```

### Expected behavior

The buffer contents should match the clipboard.

### Actual behavior

The following is the contents of my buffer, notice the o has been shifted to the end of the pasted text.
```
return sep.jin(args)o
```

I've generated a nvim_paste.log via gdb based on [this comment](
https://github.com/neovim/neovim/issues/13921#issuecomment-782811093)

[nvim_paste.log](https://github.com/neovim/neovim/files/7843944/nvim_paste.log)

**Comment by zeertzjq** [comment] 2022-01-11 05:49
Duplicate of #13431

**Closed by zeertzjq** 2022-01-11 05:49 UTC
Labels: bug
