### ISSUE TITLE
problem with :UpdateRemotePlugins

### ISSUE THREAD

**Issue by Ir1sh** [neovim/neovim#4691] opened 2016-05-02 00:18 UTC
- Neovim version: 0.1.5
- Operating system/version: osX 10.11.4
- Terminal name/version: zsh

### Actual behaviour

<img width="1920" alt="screen shot 2016-05-01 at 7 11 43 pm" src="https://cloud.githubusercontent.com/assets/5074813/14945185/c5f0e8b6-0fd0-11e6-97f0-27e70a083ad1.png">

please see my screenshot.  I have python2 and 3 installed aswell as neovim with both pip2 and pip3.  when I try to run :UpdateRemotePlugins (part of ensime-vim install) I get the error shown in the ss.  The first part I recognise is failed to load python3 host.  If I do echo has('python3') it returns 1.  If I do let g:python3_host_prog = '/path/to/python3' and then run :UpdateRemotePlugins command again I get this error instead:

<img width="960" alt="screen shot 2016-05-01 at 7 16 26 pm" src="https://cloud.githubusercontent.com/assets/5074813/14945195/39f25c4a-0fd1-11e6-8da7-2cac85f0c390.png">

but adding that line to my vimrc dosn't seem to make any difference when I restart vim and run : UpdateRemotePlugins I get the first error again.

Any ideas on how I can troubleshoot this further and get it working?

**Comment by Ir1sh** [comment] 2016-05-02 00:26
actually nevermind what I said about the python3_host_prog setting all I have to do is run :UpdateRemotePlugins twice and I get those two different error messages

**Comment by Shougo** [comment] 2016-05-03 03:33
@Ir1sh Your neovim is old.  neovim 0.14 is the latest version.

**Comment by Ir1sh** [comment] 2016-05-03 14:19
wuuuttt man I would be so happy if that is the issue, thanks a lot.  I could have sworn I updated before trying to install but I will get on that and see how it goes, thanks

**Comment by Ir1sh** [comment] 2016-05-03 14:24
Emm so I did brew upgrade -HEAD neovim and now it say version is 1.5-82-g490804e and I get the same two errors when I try :UpdateRemotePlugins

**Comment by bfredl** [comment] 2016-05-03 14:30
and python-client is the latest (0.1.7) ?

**Comment by Ir1sh** [comment] 2016-05-03 14:39
<img width="640" alt="screen shot 2016-05-03 at 9 38 25 am" src="https://cloud.githubusercontent.com/assets/5074813/14986771/da076e2c-1112-11e6-953e-542898441bf5.png">

Yeah and I uninstalled HEAD and installed neovim/neovim/neovim instead which i think is latest stable instead of dev build and same problem

**Comment by Shougo** [comment] 2016-05-04 02:25
Please test this.
https://github.com/tweekmonster/nvim-python-doctor

**Comment by Ir1sh** [comment] 2016-05-04 02:59
thanks @Shougo  here is the op
<img width="815" alt="screen shot 2016-05-03 at 9 58 39 pm" src="https://cloud.githubusercontent.com/assets/5074813/15004255/4d10dd56-117a-11e6-8907-c7881492ba87.png">

**Comment by Shougo** [comment] 2016-05-04 03:06
Hm.  It seems working.

> Emm so I did brew upgrade -HEAD neovim and now it say version is 0.1.5-82-g490804e and I get the same two errors when I try :UpdateRemotePlugins

What are the two errors?   Please upload the errors.
I think they are not the error messages.

**Comment by Ir1sh** [comment] 2016-05-04 03:53
Apologies I dont know what other error messages you mean, I tried starting nvim with NVIM_PYTHON_LOG_FILE set but the file is empty even after running the updateremoteplugins task again

**Comment by Shougo** [comment] 2016-05-04 04:07
@Ir1sh Please upload the `:UploadRemotePlugins` result.
Your if_python/if_python3 are works?
Please test it.

`:py print("hello")`
`:py3 print("hello")`

**Comment by Ir1sh** [comment] 2016-05-04 04:10
@Shougo those last two screenshots in my second last message are the results from running :UpdateRemotePlugins

**Comment by Ir1sh** [comment] 2016-05-04 04:23
so I uninstalled the plugin that told me to run the :UpdateRemotePlugins command and ran it again, same errors and I noticed the econd time that it mentions deoplete, I dont have deoplete in my vundle setup or bundles folder is this packaged with neovim?  I tried to run deoplete#enable() and got not an editor command error

**Comment by Shougo** [comment] 2016-05-04 04:53
It seems UltiSnips detection.
Please remove it from the runtimepath.

**Comment by Ir1sh** [comment] 2016-05-04 05:19
thank-you this seems to have resolved it, so ultisnips is not compatible?

**Comment by Shougo** [comment] 2016-05-04 05:22
It seem neovim-python bug.

@bfredl Ping.

**Comment by ranranking** [comment] 2016-05-04 17:13
@Shougo I don't use ultisnips, I use neosnippets and deoplete, and I still get the same problem. What can I do?

**Comment by Shougo** [comment] 2016-05-07 01:37
@ranranking I cannot reproduce your error.  It seems your neovim-python or neovim is old.
You should update them.

@Ir1sh I have reproduced the error.  I will create issue in neovim-python.

**Comment by ranranking** [comment] 2016-05-07 03:13
@Shougo Strange. My neovim version is v0.1.5-92-g490804e, and my pythong neovim version is 0.1.7. It was fine before, I didn't remember which update caused this problem.
Maybe you can use this rc file:

```vim

if &compatible
    set nocompatible endif
  endif

  set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim
  let bundleExists = 1

  if dein#load_state(expand('~/.vim/dein'))
    call dein#begin(expand('~/.vim/dein'))

    call dein#add('Shougo/dein.vim', {'rtp':''})

    call dein#add('Shougo/vimproc.vim', {
          \ 'build' : 'make -f make_mac.mak',
          \ 'on_source': 'unite.vim'})

    call dein#add('Shougo/neco-vim', {'on_source': 'deoplete.nvim'})
    call dein#add('ujihisa/neco-look', {'on_ft':['markdown', 'tex'], 'on_i': 1})
    call dein#add('Shougo/neosnippet.vim', {'on_i': 1})
    call dein#add('Shougo/neosnippet-snippets', {'on_i': 1})
    call dein#add('Shougo/deoplete.nvim', {'on_i': 1})

    call dein#end()

    call dein#save_state()
  endif

  let g:deoplete#enable_at_startup=1
  let g:deoplete#max_list=6
	inoremap <silent><expr> <Tab>
		\ pumvisible() ? "\<C-n>" :
		\ deoplete#mappings#manual_complete()
  let g:deoplete#enable_smart_case=1

  if !exists('g:deoplete#omni#input_patterns')
    let g:deoplete#omni#input_patterns = {}
  endif

  let g:deoplete#omni#input_patterns.tex =
        \ '\v\\%('
        \ . '\a*cite\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
        \ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|%(include%(only)?|input)\s*\{[^}]*'
        \ . ')'

  let g:neosnippet#enable_snipmate_compatibility = 1
  imap <m-q>     <Plug>(neosnippet_jump)
  smap <m-q>     <Plug>(neosnippet_jump)
  xmap <m-q>     <Plug>(neosnippet_expand_target)

  let g:neosnippet#snippets_directory='~/.vim/dein/repos/github.com/Shougo/neosnippet-snippets/neosnippets,
                                      \ ~/.vim/my_snippets'

  let g:neosnippet#expand_word_boundary = 1

  imap <expr><M-Tab> neosnippet#expandable_or_jumpable() ?
      \ "\<Plug>(neosnippet_expand_or_jump)"
      \: pumvisible() ? "\<C-n>" : "\<TAB>"
  smap <expr><m-tab> neosnippet#expandable_or_jumpable() ?
      \ "\<Plug>(neosnippet_expand_or_jump)"
      \: "\<TAB>"
```

I just can get my deoplete work. I type `:UpdateRemotePlugins`, I got this:
``` vim
function remote#host#UpdateRemotePlugins[6]..<SNR>25_RegistrationCommands[13]..remote#host#Require[13]..provider#pythonx#Require, line 15
Vim(if):Channel was closed by the client
function remote#host#UpdateRemotePlugins[6]..<SNR>25_RegistrationCommands[13]..remote#host#Require[13]..provider#pythonx#Require, line 22
Failed to load python3 host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a f
ile and opening the generated log file. Also, the host stderr will be available in Neovim log, so it may contain useful information. See also ~
/.nvimlog.
remote/host: generated the manifest file in "/Users/ranranking/.vim/.init.vim-rplugin~"
```
Do you think I need to reinstall python neovim?

**Comment by Shougo** [comment] 2016-05-07 03:16
Hm.  It seems the same error.  I think you have executed `:UpdateRemotePlugins` without deoplete loading.  `neovim-python` has the bug.

**Comment by bfredl** [comment] 2016-05-07 19:36
have you checked `.nvimlog` after running `:UpdateRemotePlugins` (look towards the end of the file) ?

**Comment by bfredl** [comment] 2016-05-07 19:45
as the problem is with `:UpdateRemotePlugins` ultisnips is completely unrelated (it uses the vim python interface which doesn't rely on URP, except for the deoplete integration which just adds a module to the deoplete search path and doesn't add any remote plugin)

**Comment by ranranking** [comment] 2016-05-07 19:48
@bfredl Yes, I wanted to check the log file. But for some reason I don't have that file in my ~ directory. How do I have this? Just `touch .nvimlog` ? Or there is other ways opening neovim can generate the file automatically

**Comment by bfredl** [comment] 2016-05-07 19:57
It might not be available in a release build, only a debug build. But we should fix `:UpdateRemotePlugins` so that stderr is sent to `:messages` on abnormal exit (or any unexpected channel closed by client) so looking the log file should not be necessary...

**Comment by ranranking** [comment] 2016-05-07 19:59
Great. I am looking forward to it. I will rebuild neovim with debug to check the log file for now.

**Comment by ranranking** [comment] 2016-05-07 20:08
@bfredl I used the debug build, and ran `:UpdateRemotePlugins`, I got this in my `.nvimlog` file:
```vim
2016/05/07 14:04:45 [info @ main:533] 39455 - Starting Neovim main loop.
2016/05/07 14:05:05 [info @ main:533] 39899 - Starting Neovim main loop.
2016/05/07 14:05:14 [error @ forward_stderr:333] 39899 - Channel 1 stderr: must specify at least one plugin as argument

2016/05/07 14:05:14 [error @ call_set_error:743] 39899 - msgpack-rpc: Channel was closed by the client
2016/05/07 14:05:40 [info @ main:533] 40683 - Starting Neovim main loop.
2016/05/07 14:07:23 [info @ main:533] 42802 - Starting Neovim main loop.
2016/05/07 14:07:47 [error @ forward_stderr:333] 42802 - Channel 1 stderr: must specify at least one plugin as argument

2016/05/07 14:07:47 [error @ call_set_error:743] 42802 - msgpack-rpc: Channel was closed by the client
2016/05/07 14:07:56 [info @ main:533] 43492 - Starting Neovim main loop.
```

**Comment by bfredl** [comment] 2016-05-07 20:11
Ok, I get it now. Since a while back nvim cannot tell what is a plugin or not, only python-client. Thus having no plugins should not be an error. I will fix this in the python client.

**Comment by bfredl** [comment] 2016-05-07 20:20
Please try python-client master. (install it for python3)

**Comment by ranranking** [comment] 2016-05-07 20:40
@bfredl I downloaded the client repo and ran `pip3 install .`, it seems the problem still exists. Is there anything wrong with what I have done?

**Comment by bfredl** [comment] 2016-05-07 20:42
you still get "Channel 1 stderr: must specify at least one plugin as argument" in the logs?

**Comment by ranranking** [comment] 2016-05-07 20:44
Yes, it seems so:
```vim
2016/05/07 14:38:58 [info @ main:533] 76634 - Starting Neovim main loop.
2016/05/07 14:39:07 [error @ forward_stderr:333] 76634 - Channel 1 stderr: must specify at least one plugin as argument

2016/05/07 14:39:07 [error @ call_set_error:743] 76634 - msgpack-rpc: Channel was closed by the client
2016/05/07 14:42:20 [info @ main:533] 80743 - Starting Neovim main loop.
2016/05/07 14:43:04 [info @ main:533] 81667 - Starting Neovim main loop.
2016/05/07 14:43:16 [error @ forward_stderr:333] 81667 - Channel 1 stderr: must specify at least one plugin as argument

2016/05/07 14:43:16 [error @ call_set_error:743] 81667 - msgpack-rpc: Channel was closed by the client
2016/05/07 14:43:25 [info @ main:533] 82135 - Starting Neovim main loop.
```

**Comment by bfredl** [comment] 2016-05-07 21:04
it is latest commit 96c721a ? In principle the same problem could be for python2, so try `pip2 install .` as well

**Comment by ranranking** [comment] 2016-05-07 21:09
Yes, I think so. I don't have 
```python
if not plugins:
       sys.exit('must specify at least one plugin as argument')
```
in the __init__.py I have downloaded. And I tried `pip2 install .` too. I am wondering whether the installation is being used or not. How do I check?

**Comment by bfredl** [comment] 2016-05-07 21:11
in a terminal:
```
python3
import neovim
print(neovim.__path__)
```

**Comment by ranranking** [comment] 2016-05-07 21:15
OK, I think it is being used.
```python
>>> print(neovim.__path__)
['/Users/ranranking/python-client/neovim']
```
Strange

**Comment by bfredl** [comment] 2016-05-07 21:16
sorry, you need to run that outside the `python-client` repo (otherwise python just imports from the current directory)

**Comment by ranranking** [comment] 2016-05-07 21:18
Oh. Can you tell me how to do this? I am sorry I am not familiar with these procedures

**Comment by bfredl** [comment] 2016-05-07 21:19
just run the above in any other directory, like your home folder, or in a newly started terminal.

**Comment by ranranking** [comment] 2016-05-07 21:28
I got this now:
```python
>>> print(neovim.__path__)
['/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/neovim']
```
I uninstalled python neovim first and reinstalled it in the repo, and than went to my home directory, imported neovim in python3. However, the `:UpdateRemotePlugins` problem still exists. Strange

**Comment by bfredl** [comment] 2016-05-07 21:30
I've never understood OS X paths. What happens if you simply delete the above path `/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/neovim` ?

**Comment by ranranking** [comment] 2016-05-07 21:39
It shows `ImportError: No module named 'neovim'`. So this means I have to define the directory of the module?

**Comment by bfredl** [comment] 2016-05-07 21:42
And if you do `pip install .` again in the repo?

**Comment by ranranking** [comment] 2016-05-07 21:43
Yeah, I did that. Nothing changes.

**Comment by bfredl** [comment] 2016-05-07 21:44
and if you do `pip3 install --user .` ?

**Comment by ranranking** [comment] 2016-05-07 21:47
@bfredl It worked! Finally! Thank you so much!

**Comment by bfredl** [comment] 2016-05-07 21:48
Not that I understood the problem but happy to help :)

**Comment by ranranking** [comment] 2016-05-07 21:51
Yes, it really helped. When I use --user to install, I got this for the neovim path:
```python
>>> print(neovim.__path__)
['/Users/ranranking/Library/Python/3.5/lib/python/site-packages/neovim']
```
I think there might be some thing messed up with osx python directories

**Comment by justinmk** [comment] 2016-05-22 15:51
If this can be reduced to a minimal set of deterministic steps, please create an new issue. 

Closing this because there is nothing actionable here. We have several issues already covering "general UpdateRemotePlugins grief".

**Closed by justinmk** 2016-05-22 15:51 UTC
