### ISSUE TITLE
Clipboard unnamedplus breaks block copy-pasting

### ISSUE THREAD

**Issue by eduardoarandah** [neovim/neovim#12615] opened 2020-07-09 19:24 UTC
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? NO
- Operating system/version: Description:    Ubuntu 18.04.4 LTS
- Terminal name/version: wsl 
- `$TERM`:  xterm-256color

### Steps to reproduce using `nvim -u NORC`

Set clipboard to unnamed plus and block pasting stops working

![ok](https://user-images.githubusercontent.com/4065733/87081900-b79bb180-c1ef-11ea-8c53-bbefcea940c2.gif)

### Actual behaviour

block pasting stops working

### Expected behaviour

block pasting work

**Comment by ovitente** [comment] 2020-07-09 19:47
Confirming. I have the same issue with.
The same nvim version on mac, Catalina 10.15.5

**Comment by hugomg** [comment] 2020-07-09 23:28
It works on me on Fedora 32 and the latest Nvim. Could this have to do with Wayland vs X? I am using Wayland and wl-copy/wl-paste.

**Comment by ovitente** [comment] 2020-07-10 12:31
_It works on me on Fedora 32 and the latest Nvim. Could this have to do with Wayland vs X? I am using Wayland and wl-copy/wl-paste._
It does not apply to any graphical system, this issue works on native console mod. And gif from eduardo shows that apparently he is using windows 10.

**Comment by eduardoarandah** [comment] 2020-07-10 14:57
Oh I'm so sorry, it may be important to note that this issue happened to me in ubuntu inside WSL2 in windows. 
(WSL clipboard doesn't have any interaction with windows that I know of)

https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux

**Comment by hugomg** [comment] 2020-07-11 14:57
@ovitente It has to do with the graphical system because unnamedplus interacts with the system clipboard.

In any case, I tested again using X.org and xclip and it also worked. Maybe it is a Linux vs non-Linux thing then?

**Comment by eduardoarandah** [comment] 2020-07-11 16:39
> @ovitente It has to do with the graphical system because unnamedplus interacts with the system clipboard.
> 
> In any case, I tested again using X.org and xclip and it also worked. Maybe it is a Linux vs non-Linux thing then?

Do you have any commands I can run to find out what’s The clipboard being used here?

**Comment by hugomg** [comment] 2020-07-11 16:56
I don't know if this is the best way but I think you can use 

    :echo provider#clipboard#Executable()

You can also find some documentation about clipboard providers on `:help provider-clipboard`,

**Comment by eduardoarandah** [comment] 2020-07-14 00:27
`nvim -u NONE`
`:echo provider#clipboard#Executable()`

Returns:
`win32yank` (why? if I started with -u NONE and this is an extra configuration)

`:version`

Returns:
```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-
prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build
/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build
/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"

```

**Comment by ovitente** [comment] 2020-07-15 11:33
```
:version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra
-pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protecto
r-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-201
91107-13403-1or2rj3/neovim-0.4.3/build/config -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-13403-1
or2rj3/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Develope
r/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.
4.3/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

```

`:echo provider#clipboard#Executable()`
returns
`pbcopy`
Mac os catalina.

**Comment by DArcMattr** [comment] 2020-07-24 01:50
I believe this is a duplicate of #1822

**Closed** 2020-08-30 06:44 UTC
Labels: bug
