### ISSUE TITLE
There is a problem with copying and pasting text containing Chinese characters

### ISSUE THREAD

**Issue by xingezhang** [neovim/neovim#9996] opened 2019-05-10 14:16 UTC
- `nvim --version`:0.3.5
- Vim (version: ) behaves differently? 8.1.1200 yes
- Operating system/version: macOS Mojave/10.14.4
- Terminal name/version: iTerm2 /3.2.9
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
open a file
Use the command {"+y} for a line. The text of this line is Chinese characters.
then register "" is correct, but return another application, example pages, Ctrl-v is failed.

if i set clipboard+=unnamed,
Use the command {yy} or {dd} for a line. The text of this line is Chinese characters.
then register "" is correct, 
then use command {p}, i get notice {E353: Nothing in register "}
return another application, example pages, Ctrl-v is failed too.

### Expected behaviour
"+y and yy or dd Can be used normally.

**Comment by justinmk** [comment] 2019-05-10 14:41
example of buffer contents/text?

**Comment by xingezhang** [comment] 2019-05-10 14:48
This is the test.
# 这是一个测试

**Comment by justinmk** [comment] 2019-05-10 15:09
works for me, with `0.4.0-690` 6891d8aec.

Duplicate of https://github.com/neovim/neovim/issues/5683 .

**Closed by justinmk** 2019-05-10 15:09 UTC

**Comment by xingezhang** [comment] 2019-05-10 15:31
Thank you very much, after adding lang en_US.UTF-8 to init.vim, the problem is solved.
