### ISSUE TITLE
terminal: ":debug norm i" hangs: 100% CPU for nvim and $SHELL

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#2494] opened 2015-04-23 22:47 UTC
I've tried to use `:debug norm i` in a `:terminal` window, and it hangs after the first `s` (step) command:

```
Entering Debug mode.  Type "cont" to continue.                                      
cmd: norm i                                                                         
>s               
```

Both the shell (zsh or bash) and nvim then consume 100% CPU.

**Comment by justinmk** [comment] 2015-08-17 07:47
Appears to be fixed on master.

**Comment by blueyed** [comment] 2015-08-17 19:21
@justinmk 
It's not fixed for me, and also happens with `nvim -u NONE`.

Where you able to reproduce it before, but cannot now anymore?

**Comment by justinmk** [comment] 2015-08-17 23:25
Now I *can* reproduce it. Hmm.

**Comment by fdinoff** [comment] 2015-08-18 01:27
Neovim is getting stuck in [this loop](https://github.com/neovim/neovim/blob/a94a68145b3c607d1e58f708ded8fe625c9973d5/src/nvim/terminal.c#L356) and `safe_getc` always returns 27 (escape).

**Comment by fmoralesc** [comment] 2017-02-18 14:36
This seems to be resolved, I can't reproduce at all it with `-u NONE`.

**Comment by justinmk** [comment] 2017-03-02 00:30
Can't reproduce. Probably fixed by the `force_restart_edit` hack.

**Closed by justinmk** 2017-03-02 00:30 UTC
Labels: bug
