### ISSUE TITLE
Add `noautocmd` option to `vim.lsp.util.open_floating_preview`

### ISSUE THREAD

**Issue by qRoC** [neovim/neovim#22758] opened 2023-03-23 06:52 UTC
### Problem

Now using this function always generates `BufEnter`/`BufLeave`, and it's impossible to control.

Related issue: https://github.com/ray-x/lsp_signature.nvim/issues/260

### Expected behavior

Open floating preview without `BufLeave` + `BufEnter `

**Comment by qRoC** [comment] 2023-03-25 19:11
Why another? Why special?

`vim.lsp.util.open_floating_preview` doc say:

> {opts} (table) with optional fields (additional keys are passed on to [nvim_open_win() (https://neovim.io/doc/user/api.html#nvim_open_win()))

`vim.api.nvim_open_win` doc say:

> noautocmd: If true then no buffer-related autocommand events such as [BufEnter](https://neovim.io/doc/user/autocmd.html#BufEnter), [BufLeave](https://neovim.io/doc/user/autocmd.html#BufLeave) or [BufWinEnter](https://neovim.io/doc/user/autocmd.html#BufWinEnter) may fire from calling this function.

So this is the standard flag.

> Need a clear, concise use-case with sample code. Linking to external issues isn't sufficient.

Auto buffer save / code fmt on BufferLeave, vim.lsp.util.open_floating_preview on hover.

**Comment by stasjok** [comment] 2023-08-19 13:42
There is already a PR for this: #15981. Related: #15300. I was also frustrated to stumble on a lot of unwanted `BufLeave` events, caused by `nvim_open_float` (when cursor itself isn't actually moving anywhere). But it should probably be fixed in `nvim_open_float` itself.

**Comment by glepnir** [comment] 2024-02-06 08:16
fixed by https://github.com/neovim/neovim/pull/25078

**Closed by glepnir** 2024-02-06 08:16 UTC
Labels: enhancement, lsp
