### ISSUE TITLE
Neovim Exits with Code 134 on System Call during Exit Sequence

### ISSUE THREAD

**Issue by rockydd** [neovim/neovim#27456] opened 2024-02-13 06:04 UTC
### Problem

I've encountered an issue where Neovim exits with a status code of 134, indicating an abort signal, when executing a function that makes a system call during the editor's exit sequence. This behavior occurs even with a minimal Neovim configuration, suggesting it is not related to any plugins or complex setup.

### Steps to reproduce

nvim --clean -c "autocmd VimLeavePre * call system('echo test')"

### Expected behavior

Neovim should exit cleanly without any error codes, even when performing system calls during the exit sequence.

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

No, vim 9.0.2136

### Operating system/version

macOS 14.3.1

### Terminal name/version

iterm 2 (3.4.23)

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment] 2024-02-13 06:11
Duplicate of #21856

**Closed by zeertzjq** 2024-02-13 06:11 UTC
Labels: bug
