### ISSUE TITLE
SIGSEGV after deleting buffers with a floating window in a different tab.

### ISSUE THREAD

**Issue by ayosec** [neovim/neovim#30425] opened 2024-09-19 20:11 UTC
### Problem

In both Neovim 0.10.1 and the latest nightly, when the command `%bd` is executed, and there is a floating window in a different tab, the process crashes with a SIGSEGV.

The problem can be reproduced with these commands:

```vim
:LspInfo
:tabnew
:%bd
```

### Steps to reproduce

1. Install Neovim nightly with the lspconfig plugin in an empty HOME.

    ```console
    $ HOME=$(mktemp -d)

    $ cd

    $ wget https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz

    $ tar xf nvim-linux64.tar.gz

    $ cd nvim-linux64

    $ bin/nvim --version
    NVIM v0.11.0-dev-789+g0ba388847
    Build type: RelWithDebInfo
    LuaJIT 2.1.1724512491

    $ git clone https://github.com/neovim/nvim-lspconfig ~/.config/nvim/pack/nvim/start/nvim-lspconfig

    $ bin/nvim
    ```

2. In Neovim, execute these Ex commands.

    ```vim
    :LspInfo
    :tabnew
    :%bd
    ```

After `:%bd`, the program crashes with a `SIGSEGV`.

### Expected behavior

Delete all buffers without crashing.

### Neovim version (nvim -v)

v0.11.0-dev-789+g0ba388847

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Debian 12

### Terminal name/version

Alacritty (git)

### $TERM environment variable

alacritty

### Installation

Prebuilt package and nixpkgs

**Comment by ayosec** [comment] 2024-09-19 20:11
### Address Sanitizer

I built Neovim with the address sanitizer. It throws this error after `:%bd`:

```
../neovim/src/nvim/window.c:3198:25: runtime error: null pointer passed as argument 1, which is declared to never be null
../neovim/build/include/window.h.generated.h:49:42: note: nonnull attribute specified here
    #0 0x55e228468e2f in winframe_find_altwin ../neovim/src/nvim/window.c:3198:15
    #1 0x55e228454e28 in winframe_remove ../neovim/src/nvim/window.c:3135:15
    #2 0x55e228465da5 in win_free_mem ../neovim/src/nvim/window.c:3059:10
    #3 0x55e228462b00 in win_close_othertab ../neovim/src/nvim/window.c:3037:3
    #4 0x55e2284612d2 in close_windows ../neovim/src/nvim/window.c:2497:11
    #5 0x55e226daa51e in do_buffer_ext ../neovim/src/nvim/buffer.c:1396:7
    #6 0x55e226db213c in do_buffer ../neovim/src/nvim/buffer.c:1577:10
    #7 0x55e226db192b in do_bufdel ../neovim/src/nvim/buffer.c:1095:18
    #8 0x55e2273c514e in ex_bunload ../neovim/src/nvim/ex_docmd.c:4494:17
    #9 0x55e22739d718 in execute_cmd0 ../neovim/src/nvim/ex_docmd.c:1714:7
    #10 0x55e227378f4a in do_one_cmd ../neovim/src/nvim/ex_docmd.c:2358:7
    #11 0x55e22736a223 in do_cmdline ../neovim/src/nvim/ex_docmd.c:667:20
    #12 0x55e227a6014f in nv_colon ../neovim/src/nvim/normal.c:3176:18
    #13 0x55e227a4b6f4 in normal_execute ../neovim/src/nvim/normal.c:1234:3
    #14 0x55e228047745 in state_enter ../neovim/src/nvim/state.c:100:26
    #15 0x55e227a28bf2 in normal_enter ../neovim/src/nvim/normal.c:520:3
    #16 0x55e22774214b in main ../neovim/src/nvim/main.c:660:3
    #17 0x7f9740fe91c9  (/lib/x86_64-linux-gnu/libc.so.6+0x271c9) (BuildId: 22d638056fb5a842787ab92b025c3ecdf4bef3ba)
    #18 0x7f9740fe9284 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x27284) (BuildId: 22d638056fb5a842787ab92b025c3ecdf4bef3ba)
    #19 0x55e226a4dfd0 in _start (/usr/local/bin/nvim+0xceffd0) (BuildId: 966beea3ccf05b0f49ed5abb32c2587606063e07)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../neovim/src/nvim/window.c:3198:25 in
```

**Comment by zeertzjq** [comment] 2024-09-19 23:09
Duplicate of #21409

**Closed by zeertzjq** 2024-09-19 23:09 UTC
Labels: has:backtrace, bug-crash, floatwin
