### ISSUE TITLE
`type(getchar())` return 1 for <

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#12487] opened 2020-06-13 12:45 UTC
- `nvim --version`: NVIM v0.5.0-345-g0b49cb67f
- `vim -u DEFAULTS` (version: ) behaves differently? yeah
- Operating system/version: win7
- Terminal name/version: NO
- `$TERM`: NO

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
:echo type(getchar())
press <

```

### Actual behaviour

it should print 0, but it is 1 in nvim

### Expected behaviour

this should same as vim

**Comment by glacambre** [comment] 2020-06-13 12:54
On 2020-06-13 14:45, Wang Shidong wrote:
>   * |nvim --version|: NVIM v0.5.0-345-g0b49cb67f

Could you try nightly?

>   * Terminal name/version: NO
>   * |$TERM|: NO

I think these might be important - I can't reproduce this on linux+kitty.

**Comment by mhinz** [comment] 2020-06-13 12:54
From Gitter:

`getchar()` and <kbd><</kbd> returns `60` on macOS, but in this case, `<80><fc>^B` on Windows.

**Comment by erw7** [comment] 2020-06-13 17:17
I checked and `nvim-qt` is sending `"<S-lt>"`. Therefore, I think this is a problem with `nvim-qt`, not `neovim`.

**Comment by justinmk** [comment] 2020-09-08 05:58
Looks like this was fixed in https://github.com/equalsraf/neovim-qt/issues/134 .

Test with neovim-qt v0.2.16.1 (or later) https://github.com/equalsraf/neovim-qt/releases/tag/v0.2.16.1

**Closed by justinmk** 2020-09-08 05:58 UTC
Labels: bug, platform:windows
