### ISSUE TITLE
Seg Fault with :terminal and :help

### ISSUE THREAD

**Issue by wilriker** [neovim/neovim#7554] opened 2017-11-14 09:13 UTC
- `nvim --version`:
```
NVIM v0.2.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.1/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: Arch Linux x86_64
- Terminal name/version: `st` or `st` + `tmux`
- `$TERM`: `st-256color` or `tmux-256color`

### Steps to reproduce using `nvim -u NORC`
```vim
nvim -u NORC
:terminal
"(go to normal mode if you are not already)
:help
ZQ "(with focus in help window)
```

### Actual behaviour
`“nvim” terminated by signal SIGSEGV (Address boundary error)`

### Expected behaviour
Help window should be closed

**Comment by KillTheMule** [comment] 2017-11-14 09:28
FWIW, I can't reproduce this on 0.2.0.

**Comment by wilriker** [comment] 2017-11-14 09:31
@KillTheMule Neither can I.
This is new in 0.2.1 - and I only found it by accident, this is not something I regularly use. ;-)

**Comment by justinmk** [comment] 2017-11-14 09:45
fixed by https://github.com/neovim/neovim/pull/7547

**Closed by justinmk** 2017-11-14 09:45 UTC
