### ISSUE TITLE
Random keys presses being sent to neovim when starting it on macos

### ISSUE THREAD

**Issue by bellini666** [neovim/neovim#26093] opened 2023-11-17 14:36 UTC
### Problem

Since last week some random key presses will be sent to neovim when starting it on macos.

This is from starting it on iterm2
![Screenshot 2023-11-17 at 11 23 48](https://github.com/neovim/neovim/assets/134025/ca99baf8-350e-4285-90a4-8ae674940a92)

This is from starting it on the default terminal
![Screenshot 2023-11-17 at 11 23 57](https://github.com/neovim/neovim/assets/134025/01de576f-7ac5-482c-af26-d1483f56af37)

If I open a file with text the keypresses will actually do some modifications on the text

I'm running `HEAD` version of neovim, installing with brew with `brew install --HEAD neovim` and upgrading it with `brew upgrade neovim --fetch-HEAD`.

The issue started around last week. I run `brew upgrade` for neovim on a daily basis and it was fine before.

I also tried to uninstall the `HEAD` version and install the latest stable version (0.9.4) and the issue was gone, so the issue is only present in the dev version.

Here is a screencast showing the issue as well:

https://github.com/neovim/neovim/assets/134025/53b6b403-7bae-4fc8-80bb-26b744362ba7

### Steps to reproduce

Just open nvim, directly or `nvim --clean` on macos

### Expected behavior

Neovim should open without random keypress events being sent to it

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1592+gad867fee2-Homebrew

### Vim (not Nvim) behaves the same?

no (neovim stable itself doesn't)

### Operating system/version

macOS Sonoma 14.1.1

### Terminal name/version

iTerm2 3.4.22

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by clason** [comment] 2023-11-17 14:37
> iTerm2 3.4.22

Try the latest iTerm2 3.5 beta; the releases are ancient and have problems with DCS sequences.

**Comment by bellini666** [comment] 2023-11-17 14:41
@clason oh, switching to beta fixed the issue

The issue still remains on the macos default terminal, which is not a big deal for me as I only use iterm2, but might be for others

**Comment by gpanders** [comment] 2023-11-17 14:41
Duplicate of https://github.com/neovim/neovim/issues/26038.

**Closed by gpanders** 2023-11-17 14:41 UTC
Labels: bug

**Comment by clason** [comment] 2023-11-17 14:43
> The issue still remains on the macos default terminal

Yeah, but that is a piece of garbage anyway. Do Not Use.

**Comment by justinmk** [comment] 2023-11-17 15:22
We should probably skip this for Terminal.app, by checking `$TERM_PROGRAM == Apple_Terminal`

**Comment by gpanders** [comment] 2023-11-17 15:29
No need, the issue is resolved now that [libtermkey has been updated](https://github.com/neovim/neovim/pull/26073).
