### ISSUE TITLE
Live substitution in visual block mode

### ISSUE THREAD

**Issue by hinell** [neovim/neovim#21392] opened 2022-12-12 21:10 UTC
### Feature already in Vim?

No - as of `NVIM v0.9.0-dev-3576776`

### Feature description

https://user-images.githubusercontent.com/8136158/207153244-45139bbc-ac8f-41b4-b592-413ecc919e93.mp4

I request to add  live [blockwise substituion](https://neovim.io/doc/user/visual.html#v_b_C). Currently it's implemented only for `:s/.../.../` command.

## Related
* This might be related to
** #7257
** #9421

**Comment by justinmk** [comment] 2024-12-17 14:28
Duplicate of https://github.com/neovim/neovim/issues/20329

**Closed by justinmk** 2024-12-17 14:28 UTC
Labels: enhancement, multicursor
