### ISSUE TITLE
Permission errors when running as root and sharing $HOME with regular user

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#12475] opened 2020-06-12 05:42 UTC
- `nvim --version`: `NVIM v0.5.0-558-g6d1404faf`
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: `Debian bullseye/sid`
- Terminal name/version: Terminal.app
- `$TERM`: `xterm-256color`
### Steps to reproduce using `nvim -u NORC`

```
MANPAGER='nvim -u NORC +Man!' sudo -E man printf
q
```

This command runs sudo with `-E` to preserve `$HOME`.

### Actual behaviour

<img width="920" alt="Screen Shot 2020-06-12 at 1 39 23 AM" src="https://user-images.githubusercontent.com/10180857/84468734-8ca05b00-ac4d-11ea-9f99-1d4c455bc52d.png">

> E886: System error while opening temporary ShaDa file /home/nhooyr/.local/share/nvim/shada/main.shada.tmp.a for writing: permission denied

### Expected behaviour

No errors on Debian as it works fine directly on macOS.

Also noticed that opening a terminal within the spawned neovim will throw stuff like this:

<img width="665" alt="Screen Shot 2020-06-12 at 1 40 16 AM" src="https://user-images.githubusercontent.com/10180857/84468794-acd01a00-ac4d-11ea-88a8-484c26204b9e.png">

**Comment by erw7** [comment] 2020-06-17 16:34
I think this may be a problem with `/etc/sudoers` on macOS. Is `env_reset` set and `env_keep` does not contain `HOME`? How about using `sudo -H -E man printf`?

**Comment by nhooyr** [comment] 2020-06-17 16:59
@erw7 Sorry I clarified that it works perfectly on macOS. Errors only popup with Debian.

**Comment by erw7** [comment] 2020-06-18 16:26
I don't think this is a bug in neovim after all, but a problem with `sudo` configuration and usage. First, I suggest you read `man sudo` (you may have already read that). If that doesn't solve the problem, I think it's better to ask the question on a UNIX-related forum.

Of course it is possible to implement it so that the path to shada is determined from `uid` instead of `$HOME`. But I don't think that's something we're going to implement.

**Comment by nhooyr** [comment] 2020-06-18 16:39
@erw7 I'm very familiar with sudo's configuration and usage. When running as `sudo`, `neovim` is unable to write into my previous user's `$HOME` which should just work. It works perfectly on macOS.

**Comment by nhooyr** [comment] 2020-06-18 16:39
i.e if I use a root shell to touch that file, things just work.

**Comment by nhooyr** [comment] 2020-06-18 16:40
And it only happens with `:Man`. There's definitely something funky going on here. Please reopen!

**Comment by erw7** [comment] 2020-06-18 16:51
I also tried it with Debian. If I use `sudo -H -E man printf`, it works fine.

```vim
sudo nvim -u NORC
:echo $HOME
/root
MANPAGER='nvim -u NORC +Man!' sudo -E man printf
:echo $HOME
/home/erw7 "For some reason, $HOME is not /root.
```

**Comment by nhooyr** [comment] 2020-06-18 16:53
> I also tried it with Debian. If I use sudo -H -E man printf, it works fine.

That makes sense but ideally I share my config between root and my normal user.

> /home/erw7 "For some reason, $HOME is not /root.

Yea, that's what the `-E` option does. If you pass `-H` on top of it, then `$HOME` is set to the target user's `$HOME`.

**Comment by erw7** [comment] 2020-06-18 17:16
I finally understand what you want to do. You might be able to do this if you use `posix acl` and set it up properly. But I don't think it's a neovim bug after all. I think it's a matter of using Linux permissions. Can I close it again?

**Comment by erw7** [comment] 2020-06-18 17:41
I granted `rwx` privileges to `~/.local/share/nvim/{shada,shada/main.shada}` to `root`. But the following error occurred. I think what you want to do is impossible on Linux.

```
E136: Failed setting uid and gid for file /home/erw7/.local/share/nvim/shada/main.shada.tmp.a: operation not permitted
E136: Do not for get to remove /home/erw7/.local/share/nvim/shada/main.shada.tmp.c or remae it manually to /home/erw7/.local/share/nvim/shada/main.sda.
```

**Comment by nhooyr** [comment] 2020-06-18 18:30
Yea but that doesn't make sense. Neovim is running as root, it should be free to change whatever it wants. And how come it only happens with `:Man`? `:wshada` succeeds if I open a file and write to it.

i.e
```
command sudo -E nvim -u NORC /tmp/meow
<insert some lines>
:x
```

Succeeds perfectly.

**Comment by erw7** [comment] 2020-06-18 19:14
Surely it's strange that `os_fchown` fails as a root user.

**Comment by erw7** [comment] 2020-06-18 19:42
When I tried, the following command works fine.

```
sudo -E nvim -u NORC +'set ft=man | call man#open_page(v:count, v:count1, "", "printf")'
sudo -E nvim -u NORC +'e test.txt'
```
```

**Comment by erw7** [comment] 2020-06-20 08:10
If `MANPAGER` is `less`, `chown` will also fail. Thus this is not a problem for neovim. I don't know if this behavior was intended. In the environment I have at hand, Debian(buster) and Ubuntu 18.04.4 LTS (Bionic Beaver), where the problem existed. This problem did not exist with openSUSE Tumbleweed. If this is the case with bullseye/sid, it would be better to report it to a Debian ML.
 
```
MANPAGER=less sudo -E man printf
!touch test.txt; chown erw7:users test.txt
chown: changing ownership of 'test.txt': Operation not permitted
!done   (press RETURN)
```

**Closed by erw7** 2020-06-20 08:10 UTC
Labels: bug

**Comment by jamessan** [comment] 2020-06-20 12:28
I think Debian has AppArmor policies setup by default, which may be restricting what child processes of `man` can do.

**Comment by erw7** [comment] 2020-06-21 08:52
@jamessan Thanks. Putting appamor in complain mode with the following command confirmed that the problem went away.

```
sudo aa-complain /etc/apparmor.d/usr.bin.man 
```

**Comment by nhooyr** [comment] 2020-06-21 20:02
Awesome can confirm!

```
sudo apt install -y apparmor-utils
sudo aa-disable /etc/apparmor.d/usr.bin.man
```

Fixes the issue.

**Comment by Ahwxorg** [comment] 2023-07-10 09:10
Maybe someone can help me. I recently switched to macOS, and I keep getting errors saying "Permission denied"
