### ISSUE TITLE
incsearch: highlight every match, not only first

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#4429] opened 2016-03-09 06:08 UTC
It would be really nice to have this built into neovim. I can't think of a single reason anyone would be against this.

**Comment by justinmk** [comment] 2016-03-09 06:30
> I can't think of a single reason anyone would be against this.

It requires redrawing potentially more lines. So, slower in the terminal, particularly on slow connections. 

That's the reason for Vim... but in our case we try to optimize for the common case (e.g. we set `'ttyfast'` by default now), so it makes sense to greedy-highlight incsearch by default, probably.

**Comment by SageEx** [comment] 2016-03-12 08:26
Another problem with this is during jumping by search, we are only interested in first search result, and highlighting all searches will distract us.
Like delete till some text
``d/<text>``
If all other searches are highlighted, it is a major distraction.

**Comment by justinmk** [comment] 2016-03-12 16:11
@SageEx That's solved by having a different highlight group for the first match (which already exists, in fact).

**Comment by SageEx** [comment] 2016-03-12 18:49
@justinmk Do colorschemes generally define a highlight group for first match ? Or, all colorschemes would need to be updated again :disappointed: (for uniform look) .
OTOH what are the benefits of highlighting all searches with incsearch ?

**Comment by justinmk** [comment] 2016-03-12 19:13
@SageEx I dont' know. Can you look?

**Comment by nhooyr** [comment] 2016-03-12 21:49
I agree with @justinmk. By highlight group for the first match, do you mean `IncSearch`? If so yes, I think most colorschemes include it. I just checked apprentice, solarized, and molokai. Either way, its not a very big change.

**Comment by SageEx** [comment] 2016-03-13 05:26
I checked in the repo vim-colorschemes. Most of the colorschemes (484/681) define it and they are indeed defined as separate colors. So we are good there.
@justinmk If this feature is implemented, could it be toggled as an option ?
@nhooyr Sure there are no downsides, but what are the benefits of this feature ?

**Comment by nhooyr** [comment] 2016-03-13 05:32
So that you can visually see everything being selected as you type. It's a nice touch.
Oh, I forgot to mention, it should apply to substitutions. So that you can visually see exactly what you're replacing. That would be immensely useful imo.

**Comment by fmoralesc** [comment] 2016-03-13 06:52
Can't this be deferred to a plugin, like https://github.com/haya14busa/incsearch.vim/? That works fine already, except for a visual glitch caused by https://github.com/neovim/neovim/issues/3688 

Other than that, the performance concern can be dismissed if this is made opt-in instead of opt-out.

**Comment by CallumHoward** [comment] 2016-11-12 04:53
Now that we have the wonderful inccommand, incsearch would seem to be a complimentary opt-in in the same way. Perhaps performance issues could be mitigated by only considering patterns visible on the current screen? (please excuse my ignorance)

**Comment by justinmk** [comment] 2016-11-12 10:25
vim_dev is pushing for this, so unless someone wants to work on this we're just going to wait. https://groups.google.com/d/msg/vim_dev/yEm6YZBfOVQ/qSDqIMlSBwAJ

**Comment by josephholsten** [comment] 2017-03-26 03:56
@justinmk has that got a finished impl yet? does anyone need poking?

**Comment by CallumHoward** [comment] 2017-10-30 10:18
This is now merged in to Vim 8.0.1238 [patch here](https://github.com/vim/vim/releases/tag/v8.0.1238)

**Comment by justinmk** [comment] 2018-03-21 02:04
https://github.com/neovim/neovim/pull/7463

**Closed by justinmk** 2018-03-21 02:04 UTC
Labels: enhancement
