### ISSUE TITLE
Poor performance typing with hlsearch enabled

### ISSUE THREAD

**Issue by ColinKennedy** [neovim/neovim#28112] opened 2024-03-30 04:30 UTC
### Problem

I noticed high latency when typing and thought it was treesitter. It turns out I can reproduce it with baseline neovim.

https://github.com/neovim/neovim/assets/10103049/b0e7ea84-352b-4050-96e7-54b31afbb63b

recording explanation
- The first Neovim run has no latency typing issues because it was opened with `nvim -u NONE`
- The second Neovim was opened with `nvim -u foo.lua`, an empty lua file. This run has the latency issue
    - (I forgot to show it in the recording but after running `:noh`, the latency issue is gone)

### Steps to reproduce

Using https://github.com/vim/vim/blob/620e85265ce04654053c64f8058914ecafe4eb38/src/testdir/test_winfixbuf.vim ...

1. `nvim -u NONE test_winfixbuf.vim`
2. Start typing `a` repeatedly
3. You should see no latency / typing speed issues

1. `touch foo.lua`
2. `nvim -u foo.lua test_winfixbuf.vim`
3. Start typing `a` repeatedly
4. You should see a lag on certain characters, like in the recording

### Expected behavior

Consistently responsive typing

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2515+g2cadccabf-dirty

### Vim (not Nvim) behaves the same?

No, even with `:set hlsearch` enabled - VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Mar 26 2024 23:41:57) Included patches: 1-211

### Operating system/version

CentOS Linux 7 (Core)

### Terminal name/version

gnome-terminal - # GNOME Terminal 3.28.2 using VTE 0.52.4 +GNUTLS

### $TERM environment variable

xterm-256color

### Installation

Compiled from source

**Comment by zeertzjq** [comment] 2024-03-30 04:45
Duplicate of #23590

**Closed by zeertzjq** 2024-03-30 04:45 UTC
Labels: bug

**Comment by ColinKennedy** [comment] 2024-03-30 05:20
I think the default Neovim colorscheme should be updated if that's the case, unless it already has been

**Comment by glepnir** [comment] 2024-03-30 05:33
@ColinKennedy  off topic which font you used (comment hide as off topic)

**Comment by ColinKennedy** [comment] 2024-03-30 05:35
@glepnir [DroidSansMono Nerd Font Regular](https://www.nerdfonts.com/font-downloads). It's my favorite font :)
