### ISSUE TITLE
extra space in signcolumn when using unicode character like ⚠

### ISSUE THREAD

**Issue by allan-simon** [neovim/neovim#9997] opened 2019-05-10 22:49 UTC
- `nvim --version`: NVIM v0.4.0-dev
- Vim (version: ) behaves differently? I don't know 
- Operating system/version:  Linux Ubuntu 18.04
- Terminal name/version: QTerminal 0.9.0
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC toto.txt
```
1. write "b"
2. execute `:sign define piet text=⚠ texthl=Search`
3. execute : `:exe ":sign place 2 line=1 name=piet file=" . expand("%:p")`
                                                                                                                                                                      
### Actual behaviour

The line in the terminal is now 3 characters long , the `⚠`  a space  and `b` , with `⚠` and the space highlighted
but the cursor can still move to only the space, if you it something like `ra` to replace the "space" by "a" by something else, it is replaced in the visual output of the terminal , and now you see "⚠ab" 
but if you save, the "b" is correctly replaced by "a"

### Expected behaviour

there should be no extra space

Note:
    * the bug is not triggered if i use ascii characters

**Comment by justinmk** [comment] 2019-05-11 09:26
does https://github.com/neovim/neovim/pull/9788 fix it?

**Comment by allan-simon** [comment] 2019-05-11 10:16
I will try to compile it and tell you

**Comment by allan-simon** [comment] 2019-05-11 11:15
I will try to post a screenshot but with that branch i get:

first if I just put the sign in the signcolumn, it works as it should 
but now if delete (with `x`) the character of my line,  visually it delete "one character" of column sign

**Comment by allan-simon** [comment] 2019-05-11 11:19
funny things: if i try to take a screenshot with shutter , then nvim is redraw correctly , preventing from posting a screenshot....

**Comment by allan-simon** [comment] 2019-05-11 11:23
but ! with the original issue i'm able to take screenshot of it : 
![Selection_003](https://user-images.githubusercontent.com/213167/57569020-cae69d80-73ef-11e9-8e10-be1f0c6d1138.png)

**Comment by mqudsi** [comment] 2019-05-12 17:33
This is probably an issue with `wcwidth` (or equivalent) returning a wrong value. neovim thinks it is two cells wide, draws subsequent text from at that offset accordingly. See https://github.com/fish-shell/fish-shell/issues/5583

**Comment by allan-simon** [comment] 2019-05-12 18:50
thanks for the pointer @mqudsi  , today I've been trying to recompile some old version of nvim to see if it was working before (because I think I remember this feature used to work, but i'm not sure if it was because the linter I was using was not yet using unicode character, or if it was because old version of nvim didn't have that bug)

**Comment by justinmk** [comment] 2019-05-12 19:13
see also https://github.com/neovim/neovim/issues/4976

**Comment by grifcj** [comment] 2019-05-15 05:18
A few observations while running on Ubuntu 19.04. No solutions here, just sharing where I got after some looking.

I was able to replicate the bug in qterminal. I also noticed that the 'warning sign' or \u26a0, along with other nearby emoji codes seemed to have render issues wherever they appeared, even just in the buffer. The xadvance on the warning symbol seems to be 1 even though the glyph is 2 wide. I did most of my stuff in gnome-terminal but I noticed rendering issues in qterminal as well. 

I also tried things in nvim-qt, but didn't notice any problems there. Realize that that's quite different from tui though.

I looked up wcwdith and it only seems to be called in src/nvim/mbyte.c:474 in utf_char2cells @fbf2c41. That invocation is guarded by USE_WCHAR_FUNCTIONS. In lieu of wcwidth, there are lookup tables for character width and seems like \u26a0 would be found in emoji_width and result in width of 2.

Was trying to come up with an idea for a test case that this should fail, but not sure if that's possible given actual buffer content isn't affected.

**Comment by inconvergent** [comment] 2019-06-04 09:27
i don't know if this is relevant. but i ended up here when debugging a similar error (double width unicode characters, eg. when typing norwegian ø). i found that my problem was that gnome terminal (3.28.2) was set to Ambiguous-width characters: Wide. setting it to Narrow fixed my issue. 

Note: the error was present outside of (neo)vim too, i just didn't notice that initially.

**Comment by justinmk** [comment] 2019-06-04 11:12
This can be considered a duplicate of #7151. See also #6313

**Closed by justinmk** 2019-06-04 11:12 UTC
Labels: bug, complexity:low, help wanted
