### ISSUE TITLE
Prompt after :make does not behave intuitively

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7285] opened 2017-09-18 16:28 UTC
After running `:make` resulting in errors parsed by `errorformat`, neovim displays `Press ENTER or type command to continue`

At this point, it seems that whatever you do still results in neovim jumping to the first error. I believe that the default action (load first error) should only be taken if ENTER were pressed. If a command is executed, that should supplant the default 'jump to first error' behavior.

Additionally, ctrl+c at this point should abort the `:make` command; instead, it too continues on to load the first error.

(this may seem trivial, but when the result of `:errorformat` points to a non-existent file it means that at this point there's no way to avoid clearing the buffer contents)

**Comment by jamessan** [comment] 2017-09-18 16:31
The `Press ENTER` prompt has nothing to do with `:make`.  It's a general prompt that happens when the displayed message is larger the `'cmdheight'` lines.

As as aside, you can use `:make!` to perform the build and populate the quickfix list but not immediately jump to the first entry.

**Comment by mqudsi** [comment] 2017-09-18 16:43
I didn't realize that it was always the same reason that makes that prompt appear. I'm familiar with `:make!`, but thought this was an opportunity to improve the experience when `:make` was inadvertently used instead.

Would the current behavior be considered "by design" if ctrl-c interrupts the message (thereby giving control back to `:make`)?

**Comment by justinmk** [comment] 2017-09-19 06:28
considering this a duplicate of #7291, see https://github.com/neovim/neovim/issues/7291#issuecomment-330440635 

Essentially the Press-Enter prompt should be eliminated. What that means is debatable, but it's the general solution.

**Closed by justinmk** 2017-09-19 06:28 UTC
