### ISSUE TITLE
Crash: assertion failed

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#2838] opened 2015-06-15 12:30 UTC
While doing some regular editing, Neovim crashed with the following output:

```
[200~ plines_win_nofold: Assertion `col <= 2147483647 && (int)col < 2147483647 - (width -1)' failed. execute 'keepjumps keeppatterns [201~
```

It looks like this is an overflow check that should only fail when dealing with extremely long lines; but at the time the crash occured, I was editing a file wrapped at 80 columns. I’m currently trying to reproduce the issue with little success.

**Comment by tarruda** [comment] 2015-06-15 12:58
any chance you saved a core dump from the crash?

**Comment by Grimy** [comment] 2015-06-15 12:59
I found a reproduction:

    printf "\t" | nvim -u NONE +'set ts=3000000000' -

consistently crashes with:
    nvim: /home/grimy/.nvim/src/src/nvim/misc1.c:1299: plines_win_nofold: Assertion `col <= 2147483647 && (int)col < 2147483647 - (width -1)' failed.

On the other hand,

    printf "\t" | nvim -u NONE +'set ts=2000000000' -

just hangs for ever with 100% CPU usage, which is even worse imo.

**Comment by Grimy** [comment] 2015-06-15 13:02
@tarruda : core dumps were disabled on my machine at the time the original crash occured.

**Comment by tarruda** [comment] 2015-06-15 13:04
ok your snippet enabled me to reproduce locally, investigating now

**Comment by Grimy** [comment] 2015-06-15 13:16
From my tests, it seems that this is [not in vim].

**Comment by tarruda** [comment] 2015-06-15 13:53
this seems to have been introduced in @2ceb1c74

The crash is caused by `win_linetabsize(wp, s, (colnr_T)MAXCOL)` returning more than INT_MAX which fails the assertion

**Comment by Grimy** [comment] 2015-06-15 14:23
The following patch fixes both the crash and the hangup; as a downside, lines longer than 32000 columns will be rendered incorrectly.

```
diff --git a/src/nvim/misc1.c b/src/nvim/misc1.c
index 0737cae..660fbb0 100644
--- a/src/nvim/misc1.c
+++ b/src/nvim/misc1.c
@@ -1290,7 +1290,7 @@ int plines_win_nofold(win_T *wp, linenr_T lnum)
    * Add column offset for 'number', 'relativenumber' and 'foldcolumn'.
    */
   width = wp->w_width - win_col_off(wp);
-  if (width <= 0)
+  if (width <= 0 || col > 32000)
     return 32000;
   if (col <= (unsigned int)width)
     return 1;
```

**Comment by tarruda** [comment] 2015-06-15 16:05
Thanks, I don't think there's any need to have lines longer than 32k(this
should only happen with binary files anyway). Can you send a PR?

**Comment by justinmk** [comment] 2015-06-15 17:08
Documentation will need to be updated as well.

**Comment by Grimy** [comment] 2015-06-16 13:16
The average length of a “line” in a binary file is 256 bytes; 32k lines should be exceedingly rare. OTOH, 32k lines commonly happen in non-pretty-printed XML or JSON.

I can send a PR, but I’m not sure what documentation updates to make. While I can see what the code I changed does, I don’t have enough familiarity with the codebase to understand all the impacts. I made a few tests using a single-line 90k XML file and my patch doesn’t seem to make a difference.

**Comment by justinmk** [comment] 2015-06-16 13:30
OK, don't worry about it.

**Comment by chrisbra** [comment] 2015-06-16 14:26
Am 2015-06-16 15:16, schrieb Victor Adam:
> OTOH, 32k lines commonly happen in non-pretty-printed XML or JSON.

Indeed, and there have been bug reports for Vim with very long lines
(e.g. issue 164 and 274). Check e.g. the file at
https://code.google.com/p/vim/issues/detail?id=164
for an example.

Honestly, I'd try to avoid such an arbitrary limit (however large it 
is),
this just asks for trouble later.

Best,
Christian

**Comment by Grimy** [comment] 2015-06-16 15:08
Issue 164 doesn’t actually have much to do with long lines; it’s a bug in the regex engine picker (the regex triggers worst-case performance in the NFA engine, so `set re=0` should pick the old engine).

Issue 274 cannot be reproduced with the default configuration. The reporter probably did something unthinkable like activating syntax highlighting. Syntax highlighting being terribly slow on long lines has been a known issue of Vim for 17 years.

We’re getting off topic: improving Nvim’s behavior with long lines is another issue. This crash/hangup only happens on *ludicrously* long lines (> 100,000,000 virtual columns).

**Comment by chrisbra** [comment] 2015-06-16 15:15
Am 2015-06-16 17:08, schrieb Victor Adam:
> Issue 164 doesn’t actually have much to do with long lines; it’s a
> bug in the regex engine picker (the regex triggers worst-case
> performance in the NFA engine, so set re=0 should pick the old
> engine).
> 
> Issue 274 cannot be reproduced with the default configuration. The
> reporter probably did something unthinkable like activating syntax
> highlighting. Syntax highlighting being terribly slow on long lines
> has been a known issue of Vim for 17 years.
> 
> We’re getting off topic: improving Nvim’s behavior with long lines
> is another issue. This crash/hangup only happens on _ludicrously_ long
> lines (> 100,000,000 virtual columns).

The thing is, people are working with files with that many columns.

**Comment by justinmk** [comment] 2015-06-16 15:19
@chrisbra Thanks.

@Grimy Can we limit to INT_MAX instead of 32000?

**Comment by Grimy** [comment] 2015-06-16 15:26
@chrisbra Yes, they are. That’s why Neovim shouldn’t crash or hangup in those cases. My patch fixes that. It doesn’t fix anything else though; Neovim will still have terrible performance in those cases.

@justinmk Limiting to INT_MAX fixes nothing. I picked 32000 because it was already there; the more correct solution would be to limit to $LINES * $COLUMNS. With my patch, lines longer than 32000 characters will we wrapped incorrectly on UIs that can render more than 32000 characters (e.g. the TUI with a very small font). This sounds like a minor problem, but I can work on it if wanted.

**Comment by justinmk** [comment] 2015-06-16 15:28
> Limiting to INT_MAX fixes nothing. 

Ok. That means the bug is in Vim as well then?

**Comment by Grimy** [comment] 2015-06-16 15:34
Somewhat. `printf "\t" | vim -u NONE +'set ts=2147483647' -` hangs forever with 100% CPU usage, like nvim does. `printf "\t" | vim -u NONE +'set ts=2147483648' -`, instead of crashing like nvim, messes the terminal pretty badly.

**Comment by justinmk** [comment] 2015-06-16 16:30
To be fair, nvim crashes because it's actually checking for sanity here ;)

**Comment by Grimy** [comment] 2015-06-16 18:40
Yup, that’s a step in the right direction. It would be better if sanity-checking in nvim didn’t cause data loss. Instead of using `<assert.h>`, Neovim could have its own set of macros that make a save/swap/backup before aborting.

**Comment by justinmk** [comment] 2015-06-16 18:50
We use asserts for situations which should never happen, they indicate bugs that should be fixed. If we tried to save swap we could end up losing the stacktrace which enables us to fix the bug in the first place...

**Closed** 2017-10-22 14:43 UTC
Labels: bug-vim
