### ISSUE TITLE
Neovim :reg often crashes

### ISSUE THREAD

**Issue by ecbrodie** [neovim/neovim#6972] opened 2017-07-06 15:29 UTC
- `nvim --version`: 0.2.0
- Vim (version: 8.0) behaves differently?
- Operating system/version: macOS 10.12.5
- Terminal name/version: iTerm v3.0.15
- `$TERM`: `xterm-256color`

### Actual behaviour

Running `:reg` to view the neovim registers often freezes (approx. 75% reproduction rate). I cannot press ENTER to quit the register window. Ctrl-c will not terminate the process, nor will ctrl-z suspend it. I am forced to quit the shell window to get out of the process and then I need to manually `kill -9` the zombie process.

Specifically, a number of registers (such as up to `"7`) will render in the neovim console output, then freeze. No prompt to "Press ENTER" will appear.

### Expected behaviour

`:reg` works without issue. I am able to press ENTER to leave the registers screen

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

The issue can still be reproduced, although the rate seems to decrease to 25%-50%.

**Comment by teto** [comment] 2017-07-06 15:32
could it be that you paste huge chunks ? I had something similar because I had yanked a 100Mb file.

**Comment by ecbrodie** [comment] 2017-07-06 15:49
@teto I do not recall having yanked a large chunk, but I'll be open to that being a possibility. What's the best way to check? Does neovim maintain a file similar to VIM's `~/.viminfo` where yanked chunks are maintained? Also, is there a neovim command for clearing out my registers?

**Comment by jamessan** [comment] 2017-07-06 15:56
Or is this another manifestation of the jemalloc issues on OSX?

**Comment by ZyX-I** [comment] 2017-07-06 15:57
@ecbrodie In Neovim viminfo was replaced with shada, there is appropriate help somewhere in `starting.txt` where viminfo help was previously located. To clear a register, do `killall -TERM nvim` (or anything like this to kill all Neovim sessions) then `nvim -i NONE ~/.local/share/nvim/shada/main.shada` (unless you moved the location), remove register and write.

Though, if possible (not under NDA or like this), we would like to see what exactly causes freezing, I would suggest to backup the whole file before attempting to remove anything.

**Comment by ZyX-I** [comment] 2017-07-06 16:00
By the way, if you really have “too large yank” problem, check out what is your `&shada` setting. By default it contains `s10`, limiting single ShaDa entry size (but not the whole ShaDa file size) to 10 KiB (see `:h shada-s`).

**Comment by ecbrodie** [comment] 2017-07-06 18:03
I really doubt this issue is due to a too-large-yank problem. The times
when :reg worked, I confirmed that none of the chunks were long.

**Comment by mhinz** [comment] 2017-07-06 21:12
I can reproduce this with nvim from homebrew.

When I build from the repo, everything works just fine (even when I use jemalloc 5.0.1).

**Comment by ecbrodie** [comment] 2017-07-06 21:45
Right! I should mention that too. I installed neovim from brew, not source.

I think this should be a part of the issue template, could be useful
information on general for debugging purposes. I'll likely make a PR
tonight for that.

**Comment by mhinz** [comment] 2017-07-06 21:51
@ecbrodie 

I guess it would be a good idea to close this issue and follow https://github.com/neovim/homebrew-neovim/issues/219 and/or https://github.com/neovim/neovim/issues/6950 instead.

**Comment by ecbrodie** [comment] 2017-07-06 22:17
FWIW, I followed @ZyX-I's approach for clearing the `nvim` registers. The problem on `:reg` still reproduced itself. Thus, I am going to treat the idea of chunks being too large as a *red herring*.

@mhinz I'll follow those issues closely. However, I don't believe I have enough information personally to close this ticket. I am treating the issue on homebrew/jemalloc as a good educated guess, but not sure 100% if that's the issue. I'll let someone more familiar with neovim to make that call.

**Comment by justinmk** [comment] 2017-07-08 13:33
Upgrading homebrew and neovim should fix this.

**Closed by justinmk** 2017-07-08 13:33 UTC

**Comment by ecbrodie** [comment] 2017-07-08 13:51
Confirmed fixed. Thank you!
