### ISSUE TITLE
OSC-8 Support

### ISSUE THREAD

**Issue by timsofteng** [neovim/neovim#18195] opened 2022-04-20 19:34 UTC
### Feature already in Vim?

No

### Feature description

I've faced up with issue which I describe here:
https://codeberg.org/dnkl/foot/issues/1031

So to parse url from neovim with terminal emulator neovim should support OSC-8 feature.

Is it possible to implement it somehow?

**Comment by gpanders** [comment] 2022-04-20 19:37
This is a work in progress https://github.com/neovim/neovim/pull/18130.

Duplicate of https://github.com/neovim/neovim/issues/11871.

**Comment by gpanders** [comment] 2022-04-20 19:48
Duplicate of #11871.

**Comment by gpanders** [comment] 2022-04-20 19:48
Duplicate of #11871

**Closed by gpanders** 2022-04-20 19:48 UTC
Labels: enhancement

**Comment by timsofteng** [comment] 2022-04-20 19:54
Got it 
Thanks
