### ISSUE TITLE
When using '*' to search visual selection '/' is not escaped

### ISSUE THREAD

**Issue by girishji** [neovim/neovim#22800] opened 2023-03-28 09:46 UTC
### Problem

When visual selection includes a slash, any text after it is ignored in pattern search using '*'.

### Steps to reproduce

nvim --clean
nvim foo

insert some text as follows
```
asdf/asddfd afsdf /sadf
asd
asdf/asdf asdf /sadf
asdf/asddfd afsdf /sadf
```
visually highlight ```asdf/asddfd```, press ```*```.
It does not escape ```/``` during search

### Expected behavior

It should search (highlight) ```asdf/asddfd``` from line 1 and 4.

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

does not support this feature

### Operating system/version

macos 12.6.3

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by zeertzjq** [comment] 2023-03-28 09:52
Duplicate of #21676

**Closed by zeertzjq** 2023-03-28 09:52 UTC
Labels: bug, defaults
