### ISSUE TITLE
nvim -d  <(hexdump -C any.big.zip) <(hexdump -C another.big.zip)

### ISSUE THREAD

**Issue by alardam** [neovim/neovim#18557] opened 2022-05-13 10:49 UTC
### Neovim version (nvim -v)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by runner@fv-az316-460  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32) Included patches: 1-2269, 3612, 3625, 3669, 3741

### Operating system/version

Ubuntu 20.04.4 LTS (Focal Fossa)

### Terminal name/version

Gnome terminal 3.36.2

### $TERM environment variable

xterm-256color

### Installation

Use system package manager (dpkg -i) to install from https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.deb

### How to reproduce the issue

nvim -d --clean <(hexdump -C any.big.zip) <(hexdump -C another.big.zip)
or
nvim -d --noplugin <(hexdump -C any.big.zip) <(hexdump -C another.big.zip)
where: zip ~3MB

### Expected behavior

It should show difference between files (as vimdiff does).
However, if one does:
hexdump -C any.big.zip > first.txt
hexdump -C another.big.zip > second.txt
nvim -d --noplugin first.txt second.txt 
everything works as expected.

### Actual behavior

It is showing the difference for just a moment (less then 0.2s) and then diffs is gone.
I love Neovim concepts and I hope this report helps you to make it perfect soon.

**Comment by zeertzjq** [comment] 2022-05-13 11:08
Duplicate of #17926, which is duplicate of #16809

**Closed by zeertzjq** 2022-05-13 11:08 UTC
Labels: bug
