### ISSUE TITLE
Take wraping into consideration when concealling markdown links

### ISSUE THREAD

**Issue by neo451** [neovim/neovim#30810] opened 2024-10-14 10:26 UTC
### Problem

If I have one line with two links, and the text is long, it looks like this in plain text, with wrap on:
![Image](https://github.com/user-attachments/assets/eb021f36-c243-4bf8-8329-d1bdef739510)

now if I turn on tree-sitter highlight, the wrapped text will not go on the same column:
![Image](https://github.com/user-attachments/assets/651c0b30-358f-49d8-8153-6cfd06ed32a9)

but if I turn off the wrap option, it works as expected:
![Image](https://github.com/user-attachments/assets/0f9466ef-bc1c-4b69-9dfb-418b9de13fdf)

however, it does not make sense to turn off wrap in markdown files, for other lines will be unreadable.

This readme from the 0.10 newsletter also showcase this problem, because the wiki link is too long so that the roadmap link is pushed to the next line and concealing just does not work.

![Image](https://github.com/user-attachments/assets/0de38fc4-cfb7-4527-b1b0-d4be893fbb4b)

If someone can point me to where in source code I will also be willing to go and try to improve this myself.

ps: This problem because I am working a [feed reader](https://github.com/neo451/feed.nvim), and new to render a bunch of markdown files that has many inline links, so I guess that is a good rationale to fix this and makes neovim a much better markdown viewer.

### Expected behavior

the concealing should work as if wrap is off, and move the unconcealed part into the right position.
![Image](https://github.com/user-attachments/assets/0fc6a8e4-8974-46df-a1bf-6c024ee6516c)

**Comment by clason** [comment] 2024-10-14 10:28
That's just how conceal works, I'm afraid. This cannot be fixed without a massive rework of the implementation inherited from Vim.

**Comment by clason** [comment] 2024-10-14 10:30
Duplicate of #18282

**Closed by clason** 2024-10-14 10:30 UTC
Labels: enhancement, conceal
