### ISSUE TITLE
Hide statusline completely forever: `laststatus=4`

### ISSUE THREAD

**Issue by santigo-zero** [neovim/neovim#20221] opened 2022-09-16 15:54 UTC
### Feature already in Vim?

No

### Feature description

Hello! Are there any possibilities of adding an option that hides the statusline completely and forever?
  
We already have `laststatus=3` which only shows one statusline at the bottom of the screen and it looks great, but I'm not a fan of a statuslines overall and I would like to hide them in all cases. So something like `laststatus=4` would be great, using the window separators just like with `laststatus=3` but also hiding the statusline at the bottom.
 
The obvious answer would be to use `laststatus=0` but it doesn't really help in this situation since it hides the statusline when you only have one window open, after you open splits/vsplits each window will have it's own statusline.
  
Anyhow I hope you guys were able to understand me, my English is pretty bad. Also [this issue](https://github.com/neovim/neovim/issues/9731) is somehow related to this.

**Comment by zeertzjq** [comment] 2022-09-16 15:57
Duplicate of #18965

**Closed by zeertzjq** 2022-09-16 15:57 UTC
Labels: enhancement
