### ISSUE TITLE
Swapping jump commands doesn't work (<C-i>, <C-o>)

### ISSUE THREAD

**Issue by Tauka** [neovim/neovim#19074] opened 2022-06-24 03:51 UTC
### Neovim version (nvim -v)

v0.7.0

### Vim (not Nvim) behaves the same?

no, vim 8.2.4113

### Operating system/version

macOS 12.3.1

### Terminal name/version

Terminal Version 2.12.5 (444)

### $TERM environment variable

screen

### Installation

homebrew

### How to reproduce the issue

`nvim --clean`
`:nnoremap <C-i> <C-o>`
`:nnoremap <C-o> <C-i>`

### Expected behavior

Jump commands get swapped. It used to work with older `neovim`

### Actual behavior

None of the jump commands work

**Comment by zeertzjq** [comment] 2022-06-24 03:56
Duplicate of #17867

**Closed by zeertzjq** 2022-06-24 03:56 UTC
Labels: bug
