### ISSUE TITLE
Suggestion: CBOR is the new msgpack

### ISSUE THREAD

**Issue by lifranc** [neovim/neovim#10246] opened 2019-06-17 04:02 UTC
Msgpack refused to break for the sake of fixing design mistakes. CBOR is the way new sane projects are going. I almost daily contemplate writing a nvim plugin but supporting msgpack in my framework only to use it with nvim is off-putting. I certainly can't be the only one.  Besides, there seems to be old msgpack code which was meant to be cleaned up (#5724) . Perhaps the cleanup in question can go towards a better RPC format. And if anyone by any chance is interested to port [bincode](https://github.com/servo/bincode) to c++, that would be the most awesome moonshot.

**Comment by justinmk** [comment] 2019-06-17 04:56
You mean "better RPC format" but CBOR just looks like a data encoding format. RPC protocol is different than the encoding. And you didn't provide any references to CBOR, nor an alternative RPC protocol, nor any reference of msgpack design mistakes.

In any case this is a duplicate of https://github.com/neovim/neovim/issues/5526. I guess it's a good thing we didn't start chasing capt'n proto since we would need to drop everything to chase the next  hot new encoding.

**Closed by justinmk** 2019-06-17 04:56 UTC

**Comment by bfredl** [comment] 2019-06-17 07:19
> Msgpack refused to break for the sake of fixing design mistakes.

When writing something like this, it would be good to give concrete examples of what design mistakes you are concerned of. For instance: that msgpack is not seekable is not an issue for us, as we only use it for one-pass encoding/decoding of messages. (and for 'shada', but no third-party is expected to read/write that).

**Comment by lifranc** [comment] 2019-06-17 07:43
@bfredl @justinmk, I replied in the other issue. https://github.com/neovim/neovim/issues/5526#issuecomment-502570154

@justinmk Thanks for pointing out my inexactness. RPC format -> format used by the RPC messages. Hopefully that's better, but Im a hermit dev so the linguo is a bit fuzzy sometimes.
