### ISSUE TITLE
termopen() inside nvimrc returns E315: ml_get: invalid lnum: 41

### ISSUE THREAD

**Issue by mtglsk** [neovim/neovim#2408] opened 2015-04-11 13:34 UTC
Adding to my .nvimrc:

    nnoremap <C-t> :new | call termopen('bash') | startinsert

Returns a bug:

    E315: ml_get: invalid lnum: 41
    E315: ml_get: invalid lnum: 41
    E315: ml_get: invalid lnum: 41

Works ok when run from the command line.

**Comment by noahfrederick** [comment] 2015-04-11 13:53
Do you mean

```vim
nnoremap <C-t> :new <Bar> call termopen('bash') <Bar> startinsert
```

?

**Comment by mtglsk** [comment] 2015-04-11 13:59
Ok that works, thanks :+1: 

I don't know if this still a bug with `|`, most nnoremaps work fine with them.

**Comment by tarruda** [comment] 2015-04-11 14:00
In any case, you should never see messages like `E315: ml_get: invalid lnum: 41`

**Comment by noahfrederick** [comment] 2015-04-11 14:05
@mtglsk

> I don't know if this still a bug with |, most (?) nnoremaps work fine with them.

You can't use `|` in a mapping, because it signals the end of the mapping. Your original example is equivalent to:

```vim
nnoremap <C-t> :new
call termopen('bash')
startinsert
```

I assume calling `termopen('bash')` directly in your vimrc, which is the result of the above is triggering a bug.

**Comment by mtglsk** [comment] 2015-04-11 14:10
My bad, thanks for the explanation.

**Comment by tarruda** [comment] 2015-04-11 14:12
@mtglsk can you update the title so it reflects the real bug?(`termopen` inside vimrc)

**Comment by splinterofchaos** [comment] 2015-04-12 17:13
This relates to the use of a static variable in `syntax.c`, `current_lnum`, which does not get updated when we open a terminal. This causes it to repeatedly attempt to call `ml_get_buf()` with a line number greater than the number of lines in the terminal buffer. 

This this does not happen when I call `termopen()`  in  `.nvimrc`, but does happen when I go to a file larger than my screen size and call `termopen()` when scrolled at least one screen down.

This patch seems to fix it for me, though I think I'm missing an edge case or two.
```patch
diff --git a/src/nvim/syntax.c b/src/nvim/syntax.c
index 7be7c26..d1de2ab 100644
--- a/src/nvim/syntax.c
+++ b/src/nvim/syntax.c
@@ -382,6 +382,9 @@ static int syn_time_on = FALSE;
  */
 void syntax_start(win_T *wp, linenr_T lnum)
 {
+  if (wp->w_buffer->terminal) {
+    return;
+  }
   synstate_T  *p;
   synstate_T  *last_valid = NULL;
   synstate_T  *last_min_valid = NULL;
```

@tarruda does the terminal buffer use `syntax.c` for highlighting or is it controlled just with libvterm?

**Comment by tarruda** [comment] 2015-04-12 18:14
> @tarruda does the terminal buffer use syntax.c for highlighting or is it controlled just with libvterm?

The attribute information is stored by libvterm. screen.c will ask the terminal module for the attributes directly: https://github.com/neovim/neovim/blob/fb6e9312684b0f1bd60822d7da04ba6901b1e48b/src/nvim/screen.c#L2599

I think your patch is correct, can you open a PR?

**Comment by splinterofchaos** [comment] 2015-04-12 22:03
Openned #2419. I thought I remembered another instance where this message would appear related to terminal buffers, but I just can't remember.

**Comment by lazywei** [comment] 2015-04-18 05:36
I got this when using with [fzf](junegunn/fzf).
![image](https://cloud.githubusercontent.com/assets/2840571/7214147/d5f4c0e2-e5cf-11e4-88c3-9e21596ee54a.png)

**Comment by jgkamat** [comment] 2015-04-23 23:28
I get the same issue with fzf, except my line number is 42.

**Comment by lazywei** [comment] 2015-04-30 02:23
Is there any on-going PR or fix for this? This makes FZF totally unusable :/

**Comment by Pyrohh** [comment] 2015-04-30 02:27
@lazywei AFICT, no. #2419 was closed recently, as it doesn't seem to be an optimal solution.

**Comment by lazywei** [comment] 2015-04-30 02:40
@Pyrohh yeah, i'm aware of the closing of #2419 ... I'm wondering if there is any even workaround? I just want to use FZF no matter if the solution is optimal or not :sob:

**Comment by Shougo** [comment] 2015-04-30 02:49
"ml_get :" error is bug of neovim.
So, it must be fixed.  I don't know workaround.

**Comment by splinterofchaos** [comment] 2015-04-30 15:27
If there's a consensus that a quick fix would be more desirable than being able to use arbitrary syntax highlighting in terminals (which seems atypical, at least to me) in the interim, than I think #2419 would suffice for now. But a caveat is that temporary solutions can often stick around longer than intended.

**Comment by edi9999** [comment] 2015-05-12 15:34
@lazywei for fzf to work correctly, you can follow this: 

https://github.com/junegunn/fzf/issues/197

**Comment by tarruda** [comment] 2015-09-08 11:35
@mtglsk can you test if this is still an issue?

**Comment by Pyrohh** [comment] 2015-09-08 16:35
I can't reproduce this anymore.

**Comment by cHoco** [comment] 2015-09-08 22:34
Still happening for me, reproduce it pretty consistently, 100% if using debug build with python plugins enabled (YouCompleteMe) trying to open any file from vim-startify intro screen using fzf

**Comment by dnmario** [comment] 2015-09-08 22:34
Dear Enrico Ghirardi,

The email sent to danielm@tinyhub.tk with subject
"Re: [neovim] termopen() inside nvimrc returns E315: ml_get: invalid"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by tarruda** [comment] 2015-10-01 13:59
@cHoco can you update to latest master and give me some step-by-step to reproduce?

**Comment by cHoco** [comment] 2015-10-01 15:26
Can't reproduce with latest master, fixed for me :+1:

**Closed** 2015-10-01 15:31 UTC
Labels: :term, bug
