### ISSUE TITLE
`:verbose map` reports wrong path for lua defined mappings

### ISSUE THREAD

**Issue by TheLeoP** [neovim/neovim#28783] opened 2024-05-16 17:48 UTC
### Problem

Using `:verbose map lhs` where `lhs` is the left hand side of any (lua defined?) mapping reports the wrong path. It seems to show a path relative to the directory where nvim was opened even for mappings defined elsewhere (i.e. `_defaults.lua` is shown as `~\AppData\Local\nvim\vim\_defaults.lua line 146` if `nvim` is opened in `stdpath('config')` and shown as `~/vim\_defaults.lua line 146` if opened in `~`)

May be related to #27125 (?), but that issue seemed like intended behaviour, so I think this one may be different (?).

### Steps to reproduce

1. `nvim --clean -V1` with the terminal `cwd` being `~\AppData\Local\nvim`
2. `:verbose map gc`
3. The path shown (on Windows) is `~\AppData\Local\nvim\vim\_defaults.lua line 146` (a path that doesn't even exist)

Notes: 

The keymap is really defined in

https://github.com/neovim/neovim/blob/a664246171569209698c0b17b1d7af831f6603d2/runtime/lua/vim/_defaults.lua#L129-L147

which, on my machine is located at `C:\Program Files\Neovim\share\nvim\runtime\lua\vim\_defaults.lua`. So, this seems to be different from #27125 because a wrapper for `vim.keymap.set` isn't being used here (and, again, the reported path doesn't even exist).

### Expected behavior

The correct path where the keymap is created should be shown

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

Doesn't apply

### Operating system/version

Windows 11 Pro 23H2

### Terminal name/version

Doesn't apply

### $TERM environment variable

Doesn't apply

### Installation

Stable release from Github

**Comment by zeertzjq** [comment] 2024-05-16 22:07
Duplicate of #28556

**Closed by zeertzjq** 2024-05-16 22:07 UTC
Labels: bug, lua, filesystem
