### ISSUE TITLE
:checkhealth crash in winframe_find_altwin

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#30646] opened 2024-10-03 17:13 UTC
### Problem

```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   nvim                          	       0x10fc7b169 winframe_find_altwin + 137
1   nvim                          	       0x10fc7884f winframe_remove + 47
2   nvim                          	       0x10fc7a55c win_close_othertab + 1132
3   nvim                          	       0x10fc7a095 close_windows + 565
4   nvim                          	       0x10f8df4b2 do_buffer_ext + 2082
5   nvim                          	       0x10f8e0f39 do_bufdel + 649
6   nvim                          	       0x10f9d72b9 ex_bunload + 57
7   nvim                          	       0x10f9d09bc execute_cmd0 + 220
8   nvim                          	       0x10f9d0612 execute_cmd + 802
9   nvim                          	       0x10f893d56 nvim_cmd + 8790
10  nvim                          	       0x10fa51728 nlua_api_nvim_cmd + 408
11  nvim                          	       0x10f7f6606 lj_BC_FUNCC + 68
```

### Steps to reproduce

This was tricky to narrow down. Currently requires satellite + an active lsp client.

```
nvim -u minimal.lua runtime/lua/man.lua +'call nvim_input(":che vim.lsp")'
nvim --clean -u minimal.lua runtime/lua/man.lua +'call nvim_input(":che vim.lsp")
[wait a second to allow LSP to initialize (this is important)]
<Enter>
:che lspconfig
[crash]
```

minimal.lua:

```lua
-- Run this file as `nvim --clean -u minimal.lua`
for name, url in pairs {
  'https://github.com/neovim/nvim-lspconfig',
  'https://github.com/lewis6991/satellite.nvim',
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require'satellite'.setup{}

require'lspconfig'.lua_ls.setup {
  cmd = {'lua-language-server'};
  -- on_attach = on_attach,
  settings = {
    Lua = {
      diagnostics = {
        -- Get the language server to recognize the `vim` global
        globals = {'vim'},
      },
      telemetry = {
        enable = false,
      },
    },
  },
}
```

### Expected behavior

no crasho

### Nvim version (nvim -v)

391c5084d118

### Vim (not Nvim) behaves the same?

no

### Operating system/version

mac

### Terminal name/version

kitty

### $TERM environment variable

kitty

### Installation

build

**Comment by zeertzjq** [comment] 2024-10-03 22:43
Duplicate of #21409

**Comment by zeertzjq** [comment] 2024-10-03 23:24
Duplicate of #21409

**Closed by zeertzjq** 2024-10-03 23:24 UTC
Labels: bug-crash
