### ISSUE TITLE
Folds are calculated before the tree-sitter tree is updated

### ISSUE THREAD

**Issue by Bekaboo** [neovim/neovim#25822] opened 2023-10-29 04:31 UTC
### Problem

Same as https://github.com/neovim/neovim/issues/14977.

If using treesitter as fold provider, foldcolumn can be out of sync after the buffer is changed.

### Steps to reproduce

1. Create the `minimal.lua` init file:

    ```lua
    local tmp = vim.env.TMPDIR
      or vim.env.TEMPDIR
      or vim.env.TMP
      or vim.env.TEMP
      or '/tmp'
    local data = tmp .. '/' .. (vim.env.NVIM_APPNAME or 'nvim')
    local packages_root = data .. '/site'
    local cloned_root = packages_root .. '/pack/packages/start'
    local cloned_path = cloned_root .. '/nvim-treesitter'
    local url = 'https://github.com/nvim-treesitter/nvim-treesitter.git'

    vim.fn.mkdir(cloned_root, 'p')
    vim.opt.pp:prepend(packages_root)
    vim.opt.rtp:prepend(packages_root)

    if not vim.loop.fs_stat(cloned_path) then
      vim.fn.system({ 'git', 'clone', url, cloned_path })
    end

    require('nvim-treesitter.configs').setup({
      ensure_installed = 'json',
      highlight = { enable = true },
    })

    vim.o.foldcolumn = '1'
    vim.o.foldmethod = 'expr'
    vim.o.foldexpr = 'nvim_treesitter#foldexpr()'
    vim.o.foldlevelstart = 99
    ```

2. Create the following json file `test.json` for testing:

    ```json
    {
      "glossary": {
        "title": "example glossary",
        "GlossDiv": {
          "title": "S",
          "GlossList": {
            "GlossEntry": {
              "ID": "SGML",
              "SortAs": "SGML",
              "GlossTerm": "Standard Generalized Markup Language",
              "Acronym": "SGML",
              "Abbrev": "ISO 8879:1986",
              "GlossDef": {
                "para": "A meta-markup language, used to create markup languages such as DocBook.",
                "GlossSeeAlso": [
                  "GML",
                  "XML"
                ]
              },
              "GlossSee": "markup"
            }
          }
        }
      }
    }
    ```

3. `nvim --clean -u minimal.lua test.json`
4. `zjzj` to jump to the first line of the second fold
5. `O` to insert a line above
6. Observe that the foldcolumn is out of sync

Screenshots:

- Step 3:

  ![image](https://github.com/neovim/neovim/assets/76579810/34db0d3f-d7fd-4671-ac43-aeb8ab519371)

- Step 4:

  ![image](https://github.com/neovim/neovim/assets/76579810/e111c91a-3dc6-46b8-a406-1be2f5514847)

- Step 5 (observe that foldcolumn not updated in time):

  ![image](https://github.com/neovim/neovim/assets/76579810/f2b79741-50e4-472e-832b-c3d4aa83a3c7)

### Expected behavior

Foldcolumn should always be in sync.
Foldcolumn should be re-calculated after treesitter updates folds.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1427+gac353e87aec

### Vim (not Nvim) behaves the same?

no, vim does not have treesitter

### Operating system/version

Linux 6.1.60-1-lts

### Terminal name/version

alacritty 0.12.3 (5efb0690) + tmux 3.3a

### $TERM environment variable

tmux-256color

### Installation

AUR

**Comment by lucario387** [comment] 2023-11-13 06:00
Only when using `o` or `O` the foldexpr is calculated incorrectly. If instead we use `A<CR>` it will be correct. If instead, we use `A<CR>` in autocmds then foldcolumn is also updated incorrectly.

**Comment by tomtomjhj** [comment] 2024-05-11 05:33
This might have been fixed by recent fixes in `vim.treesitter.foldexpr()` and extmark updates. Can you still reproduce on the latest version with `vim.treesitter.foldexpr()` instead of `nvim_treesitter#foldexpr()`?

**Comment by igorlfs** [comment] 2024-05-11 13:39
I can confirm I'm still having this issue with `NVIM v0.10.0-dev-3116+gc1396afa7c`

**Comment by tomtomjhj** [comment] 2024-05-11 15:55
@igorlfs  https://github.com/neovim/neovim/pull/28709 should fix the issue you're experiencing.

I can't reproduce the original issue Bekaboo described.

**Comment by igorlfs** [comment] 2024-05-12 02:02
Hey, thanks for the quick fix! I thought about reporting it, but I suspected it was just a side effect of this issue!

**Closed** 2024-05-12 09:03 UTC
Labels: bug, treesitter, folds
