### ISSUE TITLE
Random Assertion Fail in c_CTRL-R= (viml_pexpr_handle_bop)

### ISSUE THREAD

**Issue by LunarLambda** [neovim/neovim#9166] opened 2018-10-29 08:13 UTC
This happened two times (both randomly, can't reproduce) in the Ctrl-R= prompt

- `nvim --version`:
NVIM v0.3.0
Build type: RelWithDebInfo
- Vim (version: ) behaves differently? N/A
- Operating system/version: Ubuntu MATE 18.04.1
- Terminal name/version: GNOME Terminator 1.91
- `$TERM`: xterm-256color

![image](https://user-images.githubusercontent.com/38919842/47636967-73bb6280-db5a-11e8-8764-ec7d8db15d8e.png)

Output:
=echo strftimenvim: ../src/nvim/viml/parser/expression.c:1241: viml_pexpr_handle_bop: Assertion `bop_node_lvl != new_top_node_lvl || bop_node_ass == new_top_node_ass' failed.
zsh: abort (core dumped)  nvim

**Comment by justinmk** [comment] 2018-10-29 09:04
Duplicate of #7889

**Closed by justinmk** 2018-10-29 09:04 UTC
