### ISSUE TITLE
Lsp get references opens quickfix window even if result is empty

### ISSUE THREAD

**Issue by ulisses-cruz** [neovim/neovim#15050] opened 2021-07-10 23:53 UTC
### How to Reproduce

- Call `lua vim.lsp.buf.references()` with the cursor in an empty line.

### Expected result 

- Noting happens.

### What is happening

- A quickfix window is opened with no content.

### The problem

I believe that the problem is in this line here:

https://github.com/neovim/neovim/blob/7c61d9c3bfe201943de731e4cba62b559392e49a/runtime/lua/vim/lsp/handlers.lua#L196

### Sugestion

I believe that the intended code was:

```
if vim.tbl_isempty(result) then return end
```

**Comment by mjlbach** [comment] 2021-07-11 02:07
What server is this? Doesn't happen with sumneko. Regardless we can work around it.

**Comment by mfussenegger** [comment] 2021-07-11 08:28
I'm not sure if it would improve the UX if we simply do nothing on an empty result.

If a user wants to get the references and nothing happens, they get the impression that it didn't work and might try again - not knowing what's going on.

Especially if you're working on a bigger project and the language server takes some time to compute the result it is important to eventually get some kind of feedback.


I think we should go the opposite route and also print out a message if there was an error.

**Comment by mjlbach** [comment] 2021-07-11 08:31
I agree we should print a warning if no references were returned, but I don't think we should open the quickfix list if no results are returned (which is, as far as I can tell, the current behavior, I'm unable to reproduce the OPs issue)

**Comment by ulisses-cruz** [comment] 2021-07-11 09:51
> What server is this? Doesn't happen with sumneko. Regardless we can work around it.

The server I was configuring is tsserver

**Comment by mjlbach** [comment] 2021-07-11 10:07
This should be closed by  #15050

**Closed by mjlbach** 2021-07-11 10:07 UTC
Labels: lsp
