### ISSUE TITLE
LustyExplorer doesn't work properly

### ISSUE THREAD

**Issue by helicobacter9** [neovim/neovim#6548] opened 2017-04-19 07:36 UTC
- `nvim --version`: NVIM v0.2.0-1303-gdd391bf
- Vim (version: 8.0.562) behaves differently? Yes, no errors.
- Operating system/version: OSX 10.10
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### Actual behaviour
I'm using sjbach/lusty plugin and it's giving me an error when I try to select a file from a split window:

    Cannot find the correct window!
    assertion failure
    eval:276:in `assert'
    eval:657:in `cleanup'
    eval:1066:in `open_entry'
    eval:648:in `choose'
    eval:526:in `key_pressed'
    eval:888:in `key_pressed'
    eval:1:in `block in <main>'
    eval:262:in `profile'
    eval:1:in `<main>'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/ruby_provider.rb:32:in `eval'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/ruby_provider.rb:32:in `block (2 levels) in 
    __define_ruby_execute'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/ruby_provider.rb:97:in `block (4 levels) in __wrap_client'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/ruby_provider.rb:144:in `__with_exception_handling'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/ruby_provider.rb:96:in `block (3 levels) in __wrap_client'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/ruby_provider.rb:138:in `__with_redirect_streams'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/ruby_provider.rb:95:in `block (2 levels) in __wrap_client'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/ruby_provider.rb:121:in `__with_vim_constant'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/ruby_provider.rb:94:in `block in __wrap_client'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/ruby_provider.rb:115:in `__with_globals'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/ruby_provider.rb:93:in `__wrap_client'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/ruby_provider.rb:31:in `block in __define_ruby_execute'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/plugin/handler.rb:51:in `call'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/plugin/handler.rb:51:in `call'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/host.rb:96:in `block in wrap_plugin_handler'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/host.rb:55:in `call'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/host.rb:55:in `handle'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/host.rb:42:in `block in run'
    /Library/Ruby/Gems/2.0.0/gems/neovim-0.3.3/lib/neovim/session.rb:76:in `block (2 levels) in run'

The problem seems to be that global variable $curwin is wrong? I get no errors in VIM.

### Expected behaviour

It should not give me any errors when selecting a file.

### Steps to reproduce

Open any file with command :LustyFilesystemExplorer. Then create split window and go to that split window. Try to open any other file with command :LustyFilesystemExplorer and it should give an error when selecting a file with an enter key.

**Comment by Shougo** [comment] 2017-04-19 07:42
Please upload `CheckHealth` result.

**Comment by justinmk** [comment] 2017-04-19 10:05
cc @alexgenco

**Comment by helicobacter9** [comment] 2017-04-19 16:26
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - ERROR: key_backspace (kbs) entry is ^H (ASCII DELETE): key_backspace=^H,

    - SUGGESTIONS:
      - Set key_backspace to \177 (ASCII BACKSPACE). Run these commands:
          infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
          tic $TERM.ti
      - See https://github.com/neovim/neovim/wiki/FAQ

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider
  - INFO: Using: g:python_host_prog = "/usr/bin/python"
  - INFO: Executable: /usr/bin/python
  - INFO: Python2 version: 2.7.5
  - INFO: python-neovim version: 0.1.7
  - WARNING: Latest python-neovim is NOT installed: 0.1.13

## Python 3 provider
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.5.1
  - INFO: python3-neovim version: 0.1.8
  - WARNING: Latest python3-neovim is NOT installed: 0.1.13

## Ruby provider
  - SUCCESS: Found up-to-date neovim RubyGem
  - INFO: Ruby Version: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
  - INFO: Host Executable: /usr/bin/neovim-ruby-host
  - INFO: Host Version: 0.3.3

**Comment by alexgenco** [comment] 2017-04-22 16:04
Yup, definitely a bug, just reproduced. I'll take a crack at it.

**Comment by alexgenco** [comment] 2017-04-23 18:26
This is a weird one, alright. Haven't fixed yet but I've found a small repro case:

1. Add a `binding.remote_pry` here https://github.com/sjbach/lusty/blob/8b6a3434850baab234718029da158384bdf53a26/autoload/lustyexplorer.vim#L700
2. `nvim +"vs" +LustyFilesystemExplorer foo.rb`, select first option, UI pauses for debug.
3. Start a `pry-remote` debug console, run this command several times:
  - `Vim.command("wincmd w"); $curwin.index`

The current window index cycles between `1000, 1000, 1002, 1000, 1000, 1002, ...`, and never hits 1001, which is the target window Lusty is trying to switch back to.

What makes it extra weird, is that if you use `Vim.get_current_window.index` instead of `$curwin` ([which should be equivalent](https://github.com/alexgenco/neovim-ruby/blob/539e17f8dfe5b3871e6ad21ad210326c11b0a14f/lib/neovim/ruby_provider.rb#L113)), you get `1000, 1001, 1002, ...` as expected. Further, switching a couple `$curwin`s to `Vim.get_current_window` fixes the bug.

So somehow `$curwin` is getting cached 1/3 times. If this rings any bells to anyone let me know, otherwise I'll keep investigating.

**Comment by alexgenco** [comment] 2017-04-23 19:51
Ok, while I didn't exactly figure out the strange cycling above, I did figure out a fix, which I pushed to the `refresh_globals` neovim-ruby branch. @helicobacter9 can you try `rake install`ing from that branch and seeing if you have any issues?

Basically, the bug is that calling commands on the `Vim` module doesn't update the `$curwin` or `$curbuf` global variables; they're only updated between `:ruby...` commands. It's still a mystery to me how it gets updated at all in the lusty script, though.

The fix increases roundtrips between neovim-ruby and nvim during `Vim.method` invocations, but I don't really have any alternatives, since any command can implicitly alter the current buffer or window.

**Comment by alexgenco** [comment] 2017-05-01 01:21
I just release [neovim-ruby v0.4.0](https://rubygems.org/gems/neovim/versions/0.4.0), so you should be able to just `gem install neovim` now. This particular bug is fixed on my local setup, but let me know if you run into anything else.

**Closed** 2017-05-01 08:51 UTC
Labels: provider

**Comment by helicobacter9** [comment] 2017-05-03 06:41
Sorry, I didn't have any time to test this. I just installed neovim-ruby v0.4.0 and LustyExplorer seems to be working fine. I'll let you know if I find any bugs. Thank you.
