### ISSUE TITLE
Neovim terminal will exit early if the process outputs alot of ouput quickly

### ISSUE THREAD

**Issue by Naught00** [neovim/neovim#22817] opened 2023-03-29 21:25 UTC
### Problem

Overloading the neovim terminal with output will cause the terminal to exit.

Consider this C program:

```
#include <stdio.h>

 int main(void) {
         int i;
         for (i = 0; i <= 10000; i++) 
                 printf("%d\n", i);
 
         return 0;
 }
```

The expected output would be 1..10000. This is not what happens when ran in a neovim terminal. This is shown in the gif:

![neovimbugcropped](https://user-images.githubusercontent.com/42555851/228667094-fb347c3a-59ca-493a-b21b-abe98a22c5be.gif)

I tried this in regular vim and it outputs fine. The program has no problem outputting correctly in gnome-terminal or xterm. 

### Steps to reproduce

nvim --clean
:term ./a.out

./a.out being a program that outputs lots of numbers quickly.

### Expected behavior

1..10000 should be printed in full.

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

No, version 9.0.1337

### Operating system/version

Arch Linux, Linux 6.2.7-arch1-1 

### Terminal name/version

GNOME Terminal 3.46.8 using VTE 0.72.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

System package manager

**Comment by zeertzjq** [comment] 2023-03-30 02:52
Duplicate of #3030

**Closed by zeertzjq** 2023-03-30 02:52 UTC
Labels: bug, terminal
