### ISSUE TITLE
bug: strange codes when using emoji

### ISSUE THREAD

**Issue by wenfangdu** [neovim/neovim#26348] opened 2023-12-01 12:51 UTC
### Problem

Redirected from https://github.com/vscode-neovim/vscode-neovim/issues/1668#issuecomment-1835804204.

![image](https://github.com/neovim/neovim/assets/28700378/3e000ded-2e6a-4c47-8780-5b37762ce401)

### Steps to reproduce

Paste the following into a new file.

```
 🏁                🏃🏾‍♀️                                    🏃🏿‍♀️
 🏁                🏃🏽‍♀️                            🏃🏿‍♂️
 🏁                🏃🏼‍♂️                                                         🏃🏾‍♂️
 🏁                🏃🏻‍♀ ️             🏃🏽‍♂️
 🏁                🏃🏽‍♂️                     🏃🏻‍♂️
```

### Expected behavior

No strange code.

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

Vim doesn't support emoji by default.

### Operating system/version

macOS 14

### Terminal name/version

Terminal.app

### $TERM environment variable

xterm-256color

### Installation

Homebrew

**Comment by clason** [comment] 2023-12-01 12:57
Please provide reproducing steps with `nvim --clean`. (I don't see any issues.)

**Comment by wenfangdu** [comment] 2023-12-01 13:02
@clason Updated description.

**Comment by wenfangdu** [comment] 2023-12-01 13:04
@clason Updated description, `<200d>` shouldn't be displayed.

**Comment by wenfangdu** [comment] 2023-12-01 13:07
@clason From a paid course, is this a Neovim issue, or a terminal issue?

**Comment by clason** [comment] 2023-12-01 13:09
Vim behaves the same, fwiw.

**Comment by zeertzjq** [comment] 2023-12-01 13:10
Duplicate of #7151

**Closed by zeertzjq** 2023-12-01 13:10 UTC
Labels: bug, unicode  💩
