### ISSUE TITLE
Bug with `vim.fn.json_encode` in `lsp/rpc`

### ISSUE THREAD

**Issue by MunifTanjim** [neovim/neovim#15033] opened 2021-07-09 08:41 UTC
- `nvim --version`: `v0.6.0-dev+27-g27118c6eb`
- Operating system/version: `Ubuntu 20.04.2 LTS`
- Terminal name/version: `alacritty 0.9.0-dev (fa2fa39)`
- `$TERM`: `tmux-256color`

### Actual behaviour

![Peek 2021-07-09 14-17](https://user-images.githubusercontent.com/8050659/125049809-2e99ad80-e0c3-11eb-96c3-2ca40e65e285.gif)

Error:

```
Error executing vim.schedule lua callback: ...unt_vimTjkTHS/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:399: Vim:E474: String "<e2>" contains byte that does not start any UTF-8 character
```

File Content:

```
local test = { "╭","─","╮" }
return test
```

- With LSP for `lua` on
- Place the cursor after the `{`
- In INSERT mode, press `ENTER`

### Expected behaviour

Not causing any error.

**Comment by mjlbach** [comment] 2021-07-09 08:43
Dupe of https://github.com/neovim/neovim/issues/14542

**Closed by mjlbach** 2021-07-09 08:43 UTC
Labels: bug, lsp
