### ISSUE TITLE
Neovim v0.9.0 `uv_close: Assertion '!uv__is_closing(handle)' failed`

### ISSUE THREAD

**Issue by androidpcguy** [neovim/neovim#22998] opened 2023-04-10 15:49 UTC
### Problem

I upgraded to v0.9.0 couple days ago and started getting an error pop up below the statusbar when exiting neovim. It doesn't occur all the time but I've noticed that if I move my terminal window (I use i3wm) I can get the error to happen pretty consistently. Error goes away if I downgrade to v0.8.3.

`nvim: src/unix/core.c:116: uv_close: Assertion '!uv__is_closing(handle)' failed`

Neovim exits with code 134

This is my first time submitting a bug report, sorry if I'm not following best practices!

### Steps to reproduce

Moving the terminal window in i3wm? Not sure otherwise

### Expected behavior

It should exit with code 0, not 134

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

Dunno, I don't have vim installed

### Operating system/version

Arch Linux kernel 6.2.10-arch1-1

### Terminal name/version

alacritty 0.12.0

### $TERM environment variable

xterm-256color

### Installation

Official Arch repo

**Comment by martineausimon** [comment] 2023-04-10 17:19
I have the same issue. I think this message only appears when the VimLeave or VimLeavePre event is used

**Comment by zeertzjq** [comment] 2023-04-10 23:19
Duplicate of #21856

**Closed by zeertzjq** 2023-04-10 23:19 UTC
Labels: bug

**Comment by XiaoPengYouCode** [comment] 2023-10-13 02:21
same issue
