### ISSUE TITLE
Tried to undo, Assertion fail leads to crash, yesterday's nightly, windows. 

### ISSUE THREAD

**Issue by WillEhrendreich** [neovim/neovim#28967] opened 2024-05-24 14:06 UTC
### Problem

![image](https://github.com/neovim/neovim/assets/55286472/8af6cf50-37e1-4bc3-9b8a-da698a5909c2)

### Steps to reproduce

I was hitting undo, if that helps.. I'm really not sure what happened. I can't reliably repro

### Expected behavior

just undo.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-57+gcd48b72b6 Build type: RelWithDebInfo LuaJIT 2.1.1713484068

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Win 11

### Terminal name/version

windows terminal running pwsh

### $TERM environment variable

none

### Installation

bob

**Comment by luukvbaal** [comment] 2024-05-24 14:09
Duplicate of #28906

**Closed** 2024-05-24 14:09 UTC
Labels: bug
