### ISSUE TITLE
TUI/Windows: text draws over line numbers

### ISSUE THREAD

**Issue by saippua** [neovim/neovim#15734] opened 2021-09-20 14:36 UTC
### Neovim version (nvim -v)

0.5.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10 19044.1237 WSL2 Ubuntu 20.04

### Terminal name/version

Windows Terminal, Powershell, Command Prompt

### $TERM environment variable

xterm-256color

### Installation

0.5.0 appimage, also tried latest on apt-get which is 0.4.3

### How to reproduce the issue

nvim -u NONE
:e ~/.vimrc
:set nu
Enter VISUAL LINE mode
scroll down to highlight text

### Expected behavior

text should be highlighted and line number column should not glitch out like it does.

### Actual behavior

![image](https://user-images.githubusercontent.com/30152369/134020799-c0b50d39-41e7-42f9-aa14-e45259d9a233.png)
return to normal mode:
![image](https://user-images.githubusercontent.com/30152369/134020869-d5cf7d53-e206-4a35-b500-5f9ba64e57ce.png)

**Comment by erw7** [comment] 2021-09-22 08:55
May be duplicate of #14872? The same phenomenon can also be seen in #9461. AFAIK this happens when `LF` is converted to `CRLF`. If you change the `cud1` in terminfo from `\n` to `\E[B`, it may help. 

Due to the lack of information on whether your neovim is a native Windows binary, a linux binary, or whether you are running it from a WSL shell, I am unable to reproduce the phenomenon.

**Comment by saippua** [comment] 2021-09-22 10:20
> Due to the lack of information on whether your neovim is a native Windows binary, a linux binary, or whether you are running it from a WSL shell, I am unable to reproduce the phenomenon.

I'm running neovim inside WSL. I've tried with both an appimage of 0.5.0 downloaded from [here](https://github.com/neovim/neovim/releases/tag/v0.5.0) as well as the 0.4.3 that im mainly using that I got using `sudo apt-get install neovim` The bug exists on both.

I wasnt able to get that terminfo fix to work.. or maybe I just didnt do it right.
I created a `.terminfo` file in `$HOME` as per [this documentation](https://man7.org/linux/man-pages/man5/terminfo.5.html) (`$TERMINFO` is not set for whatever reason) and added `cud1=\E[B` to it. Problem still occurs

**Comment by justinmk** [comment] 2021-09-22 12:50
see also #10558 

If Windows Terminal doesn't work with `$TERM= xterm-256color` it means one of the following:

- TERM should be set to something else. What does Windows Terminal expect it to be (consult their docs)?
- Windows Terminal has a bug. It claims to emulate xterm but doesn't behave like xterm.

I'll keep this issue open to catch similar reports.

**Comment by saippua** [comment] 2021-10-08 08:41
I've recreated a fresh WSL instance and that made the issue go away. However, once I installed `texlive-full` the issue reappeared (I'm also using `vimtex`). Uninstalling `texlive-full` with `sudo apt remove --purge texlive-full` and `sudo apt autoremove` unfortunately didnt fix the issue.

I'm currently doing yet another WSL reinstall to see if I can reproduce the issue more accurately.

Note: I've also used vim with `vimtex` and `texlive-full` installed and the issue does not appear there.

**Comment by lervag** [comment] 2021-10-08 11:16
> and this (using `:term` instead of `:!` there) sounds like a reasonable and straightforward improvement.

Actually, I don't think so, because I now try to fully avoid `:!` alltogether.

**Comment by clason** [comment] 2021-10-08 11:19
(That's of course even better :))

**Comment by lervag** [comment] 2021-10-08 11:23
I just merged the mentioned PR, so you could try to update VimTeX to see if it resolved your issue?

**Comment by saippua** [comment] 2021-10-08 11:42
> I just merged the mentioned PR, so you could try to update VimTeX to see if it resolved your issue?

I did `:PlugUpdate` and ran the repro but it doesn't seem like it worked. nvim is still breaking when I compile the pdf.

Also for some reason `g:vimtex_view_auto = 0` isnt disabling the auto preview after compile. So far the only thing thats worked is `g:vimtex_view_general_viewer = ''` Going a bit off-topic for this repo though. I'll go ahead and make an issue on vimtex for this.

> > In either case, It seems to me that something in how nvim runs :! commands as opposed to :term commands that is causing this issue..
> 
> The question is not whether there is a difference, but whether there is a _bug_ in how these commands are run (in _Neovim_) -- and that is not clear to me from this issue...

We're already past the point where I understand what's going on. All I know is that the `xdg-open` command only breaks the terminal when its run in nvim using `:!`. And note: it breaks the *terminal* not the nvim instance, because quitting nvim and restarting it does not fix the problem. The the entire terminal must be closed and recreated to fix the issue.

**Comment by justinmk** [comment] 2021-10-09 00:13
> `xdg-open` command only breaks the terminal when its run in nvim using `:!`. And note: it breaks the _terminal_ not the nvim instance, because quitting nvim and restarting it does not fix the problem.

Can you try system(), e.g.

     :call system(['xdg-open', 'foo.pdf'])

**Comment by jorgerojas26** [comment] 2021-11-04 08:33
I'm having this exact issue, text is drawn over line numbers 
![image](https://user-images.githubusercontent.com/26725479/140282333-34742064-5e0f-4206-9b43-78e59a88aa85.png)

Any update on this?

**Comment by meijieru** [comment] 2023-01-11 23:34
It could be reproduced by `:lua vim.fn.jobstart "xdg-open http://github.com"`

**Closed** 2023-07-06 02:09 UTC
Labels: platform:windows, tui, needs:response, needs:repro
