### ISSUE TITLE
Option 'iminsert' isn't a local to buffer as it should be

### ISSUE THREAD

**Issue by dtcyganok** [neovim/neovim#7658] opened 2017-11-29 16:53 UTC
- `nvim --version`: v0.2.2
- Vim (version: ) behaves differently? This is a known [vim bug](https://groups.google.com/forum/#!msg/vim_dev/HpwZWJojl3E/4zCBH3qWQ5IJ)
- Operating system/version: Linux 4.13.12-1-ARCH
- Terminal name/version: sakura 3.3.4
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC any-file.txt
:setlocal imiminsert=1
:e another-file.txt
:setlocal imiminsert?
```

### Actual behaviour

'iminsert' option is global

### Expected behaviour

'iminsert' option should be local to buffer

**Comment by bfredl** [comment] 2017-11-29 18:31
it is local to the buffer, but when opening a new buffer the value gets copied from curbuf. Is this really a problem?

**Comment by dtcyganok** [comment] 2017-11-29 22:40
Yes. This is problem. It is not comfortable. If you use `iminsert`, then when you open a file in another language, you always need to switch the `iminsert` option before search or input of any text.

Imagine if the `spell` and `spelllang` options behaved similarly.

**Comment by justinmk** [comment] 2017-11-29 23:30
'iminsert' is buffer-local. 'spell' is window-local. This is in the help.

**Comment by dtcyganok** [comment] 2017-11-30 00:17
Why is it closed?

From `help 'iminsert'`
```text
'iminsert' 'imi'	number (default 0, 2 when an input method is supported)
			local to buffer
```
But value of `iminsert` gets copied from current buffer when opening new file.

**Comment by Shougo** [comment] 2017-11-30 01:22
@justinmk The documentation is buffer local, but the behavior is global.
I have reproduced the problem.

But another buffer local option like 'indentexpr', it does not have the problem.

I have tested it in Vim, it seems global, too.

**Comment by dtcyganok** [comment] 2017-11-30 01:35
Thank you for your attention to the problem.

Note: the behavior of the option is not entirely global. Already opened buffers have an old option value. The new option value applies only to new buffers.

Is it possible to reopen issue? Maybe create new?

**Comment by Shougo** [comment] 2017-11-30 01:38
Hm...
I have read the source code.
The scope is `buffer`.

I don't know why the behavior.

**Comment by Shougo** [comment] 2017-11-30 01:42
`setl iminsert` changes the global `iminsert` value.
I don't know why though.

You can check the behavior.

> Note: the behavior of the option is not entirely global. Already opened buffers have an old option value. The new option value applies only to new buffers.

Yes.
The global value is used for new buffer.  So the value is changed by `setlocal`.

Note: It is the same behavior in Vim.  It should be issued in Vim.

**Comment by dtcyganok** [comment] 2017-11-30 01:50
I created the issue in vim.

**Comment by bfredl** [comment] 2017-11-30 07:38
https://github.com/neovim/neovim/blob/10c3b206cbf394d7b67bff95242b7033a1ce1d63/src/nvim/option.c#L4185

I think is the offending line. as only b_p_iminsert is actually used, not p_iminsert it makes no sense, and can probably be deleted.

**Comment by chrisbra** [comment] 2017-11-30 07:47
That sounds familiar: https://groups.google.com/d/msg/vim_dev/HpwZWJojl3E/ndWKRSYaUXcJ

**Comment by bfredl** [comment] 2017-11-30 07:58
@chrisbra Am I right to not see any conclusion there? Someone mentioned back-wards compatibility, but not with what. From the time before buffer local behavior was established?

**Comment by chrisbra** [comment] 2017-11-30 08:09
correct. I think it should be fixed and consider it a bug (and it has come up a couple of times on either vim-use or vim-dev, which shows that the current behaviour is at least unexpected).

**Comment by chrisbra** [comment] 2017-11-30 08:10
I think there is also a todo list entry about it. At least there used to be one about it (but I didn't check the todo list recently).

**Comment by Shougo** [comment] 2017-11-30 08:50
It is already todo listed here.

> 'iminsert' global value set when using ":setlocal iminsert"? (Wu, 2012 Jun 23)

**Comment by glacambre** [comment] 2021-06-05 16:27
Can't reproduce on master, so I assume this has been fixed. I'll close this issue :).

**Closed by glacambre** 2021-06-05 16:27 UTC
Labels: +plan, 0.kind: bug-vim, help wanted

**Comment by dtcyganok** [comment] 2023-08-25 18:59
That wasn't fixed. I can still reproduce it easily.

**Comment by bfredl** [comment] 2023-08-25 19:46
I cannot reproduce given the original instructions. please provide instructions for the easily reproduce.

**Comment by dtcyganok** [comment] 2023-08-25 21:00
To reproduce:

`:e path/to/some_file`
Then press `i<C-^><Esc>`
`:e path/to/another_file`
`:setlocal iminsert?`

**Comment by bfredl** [comment] 2023-08-25 21:27
seems like a different issue. `i_CTRL-^` does not behave like documented, within a single buffer. not sure if behavior or docs are wrong, but regardless, better to open new issue than necro-post a tangentially related old one.
