### ISSUE TITLE
Type complete in clangd show an error position

### ISSUE THREAD

**Issue by TimerLinker** [neovim/neovim#23680] opened 2023-05-19 03:30 UTC
### Problem

NVIM v0.10.0-dev-295+g01f81ed89

![image](https://github.com/neovim/neovim/assets/48616483/699083eb-1577-4302-a2fd-843cf94a2b7c)

In vscode or vim 9.0

![image](https://github.com/neovim/neovim/assets/48616483/f62cadcb-2c62-4cad-b071-07b8681120d7)

Is there any options can fix this error ?

### Steps to reproduce

Open any c++ file can see it.

### Expected behavior

I wish the style of type complete in neovim will get the same effect like vscode.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-295+g01f81ed89

### Vim (not Nvim) behaves the same?

vim 9.0

### Operating system/version

centos 7

### Terminal name/version

iterm2 3.4.19

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by zeertzjq** [comment] 2023-05-19 03:33
Duplicate of #18086

**Closed by zeertzjq** 2023-05-19 03:33 UTC
Labels: bug
