### ISSUE TITLE
LSP: E565 with vim.lsp.omnifunc and custom server

### ISSUE THREAD

**Issue by oncomouse** [neovim/neovim#24369] opened 2023-07-16 14:18 UTC
### Problem

I'm trying to replace some of the completion sources I use with [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) due to its impending archiving. Specifically, I'm trying to write a number of completion sources that responded to `textDocument/completion` with completion items.

I've written a basic LSP server method that gets passed as the `cmd` key to `vim.lsp.start_client()`. But when I trigger omnicompletion (`<C-x><C-o>`), I get the following error in Neovim:

~~~
E5108: Error executing lua Vim:E565: Not allowed to change text or change window
stack traceback:
        [C]: in function 'complete'
        ...w/.local/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:2318: in functio
n 'handler'
        ...w/.local/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:1499: in functio
n 'done'
        /home/andrew/minimal.lua:10: in function </home/andrew/minimal.lua:9>
        /home/andrew/minimal.lua:20: in function 'request'
        ...w/.local/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:1491: in functio
n 'request'
        ...w/.local/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:2116: in functio
n 'buf_request'
        ...w/.local/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:2290: in functio
n <...w/.local/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:2263>
E5108: Error executing lua Vim:E565: Not allowed to change text or change window
stack traceback:
        [C]: in function 'complete'
        ...w/.local/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:2318: in functio
n 'handler'
        ...w/.local/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:1499: in functio
n 'done'
        /home/andrew/minimal.lua:10: in function </home/andrew/minimal.lua:9>
        /home/andrew/minimal.lua:20: in function 'request'
        ...w/.local/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:1491: in functio
n 'request'
        ...w/.local/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:2116: in functio
n 'buf_request'
        ...w/.local/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:2290: in functio
n <...w/.local/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:2263>
Press ENTER or type command to continue
~~~

The error happens twice each time. I think this is because `vim.lsp.omnifunc()` never gets to the line `return -2`, so completion continues.

The error is happen at the line `vim.fn.complete(startbyte + 1, items)` in [lsp.lua](https://github.com/neovim/neovim/blob/f660b794808ac809ee8cafe82ddd824840bc8e2c/runtime/lua/vim/lsp.lua#L2336).

As can be seen from the minimal-init.lua below, this happens regardless of the content returned by the handler for `textDocument/completion`.

I'm likely missing something here, but I can't figure it out nor can I figure out why E565 is being triggered.

### Steps to reproduce using "nvim -u minimal_init.lua"

Open any file with the following `minimal_init.lua` (`nvim -u minimal_init.lua`) and type `<C-x><C-o>` to trigger omnicompletion.

~~~lua
local handlers = {
  initialize = function(_, _, done)
    done(nil, {
      capabilities = {
        completionProvider = true,
      },
    })
  end,
  ["textDocument/completion"] = function(_, _, done)
    done(nil, {
      { label = "hello" },
    })
  end,
}
local server = function(dispatchers)
  local closing = false
  return {
    request = function(method, params, done)
      if type(handlers[method]) == "function" then
        handlers[method](method, params, done)
      else
        done()
      end
    end,
    notify = function(...) end,
    is_closing = function()
      return closing
    end,
    terminate = function()
      if not closing then
        closing = true
        dispatchers.on_exit(0, 0)
      end
    end,
  }
end
vim.api.nvim_create_autocmd({ "FileType" }, {
  callback = function()
    local bufnr = vim.api.nvim_get_current_buf()

    local id = vim.lsp.start_client({
      cmd = server,
      flags = { debounce_text_changes = 250 },
      on_attach = function()
        vim.bo.omnifunc = "v:lua.vim.lsp.omnifunc"
      end,
    })

    if not id then
      return
    end

    local did_attach = vim.lsp.buf_is_attached(bufnr, id) or vim.lsp.buf_attach_client(bufnr, id)
    if not did_attach then
      vim.print("Did not attach to buffer " .. bufnr)
    end
  end,
})
-- # vim:ts=2:sw=2:sts=2:expandtab
~~~

### Neovim version (nvim -v)

NVIM v0.10.0-dev-661+gef94fb69c

### Language server name/version

N/A

### Operating system/version

Linux

**Comment by justinmk** [comment] 2023-07-16 14:45
I don't see anything obvious. As you already surmised, the basic issue is that the completion popup is still active while something is trying to edit the buffer. For troubleshooting, try force-closing or canceling the completion popup before sending responses from your lsp server?

Does playing with `debounce_text_changes` make a difference?

**Comment by mfussenegger** [comment] 2023-07-16 14:58
The problem is that the omnifunc uses `lsp.buf_request` and triggers the handler _per_ client. So you have one `vim.fn.complete` call per client.

The solution is to change it to use `buf_request_all` and merge the results. (Or even better, loop over the clients to also generate the params per client with the right encoding, to fix the mixed encoding handling as well)

**Comment by oncomouse** [comment] 2023-07-16 16:07
I didn't entirely understand @mfussenegger's reply. I should be using a different `omnifunc` instead of the supplied one?

I apologize for following up on a closed issue, but that doesn't make sense as null-ls is using really similar code to mine ([call to `vim.lsp.start_client()`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/db09b6c691def0038c456551e4e2772186449f35/lua/null-ls/client.lua#L74-L98) and [the definition of the function passed to `cmd`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/db09b6c691def0038c456551e4e2772186449f35/lua/null-ls/rpc.lua#L58-L145), but doesn't trigger this error. Also, with the minimal init file I supplied, my code is the only LSP client attached, so I don't understand how triggering `lsp.buf_request` per client would cause this error? Also, in my full config file, I have lua-ls and null-ls running as completion sources at the same time in lua files and omnicompletion works. So could there be something else causing the problem here?

**Comment by zeertzjq** [comment] 2023-07-16 21:44
I don't see how this is solved without a PR to change the omnifunc.

**Comment by mfussenegger** [comment] 2023-07-17 17:35
With `nvim -u minimal_init.lua` it still triggers ftplugins,  so one might have multiple clients - that kinda led me down the wrong path.

It is indeed also a problem with a single client (`nvim --clean -u minimal_init-lua`)

I think the actual problem was that `vim.fn.complete` is triggered within a luv callback, not in the main thread.

Could you try with https://github.com/neovim/neovim/pull/24381 ?

**Comment by oncomouse** [comment] 2023-07-18 19:24
#24381 does fix the problem. Thanks!

And, thanks for the reminder about `vim.lsp.start()`.

**Closed** 2023-07-19 05:10 UTC
Labels: bug, complexity:low, has:repro, lsp
