### ISSUE TITLE
Support .editorconfig by default

### ISSUE THREAD

**Issue by rakin406** [neovim/neovim#14132] opened 2021-03-14 02:46 UTC
I think it's better to follow .editorconfig by default. I know there is a plugin for that but many vim users need to install it and it's kind of a hassle. Set the indentation based on .editorconfig file.

### Actual behaviour
.editorconfig file exists but neovim does not set the indentation based on it.
### Expected behaviour
Set the indentation levels, tabs or spaces, based on .editorconfig

**Comment by teto** [comment] 2021-03-14 14:53
duplicate of https://github.com/neovim/neovim/issues/3988 I dont think the opinion changed on this.

**Closed** 2021-03-15 04:18 UTC
Labels: duplicate, enhancement
