### ISSUE TITLE
nvim.exe seems to be blocked when the `echo` is used during initialization

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#9161] opened 2018-10-28 03:19 UTC
- `nvim --version`: v0.3.2-726-gf895b47d3
- Vim (version: ) behaves differently? yes
- Operating system/version: Windows10
- Terminal name/version: nvim.exe
- `$TERM`: 

### Steps to reproduce using `nvim -u NORC`

```
1. add `echo 'hello'` to init.vim
1. start `cmd`, run nvim.exe, it shows 
```
hello
Press ENTER or type command to continue
```
1. but hit ENTER cannot continue 
```

![image](https://user-images.githubusercontent.com/19503791/47611585-49f33480-daa3-11e8-8ccf-688dbe0380c8.png)

**Comment by justinmk** [comment] 2018-10-28 10:32
Duplicate of https://github.com/neovim/neovim/issues/7967

**Closed by justinmk** 2018-10-28 10:32 UTC
