### ISSUE TITLE
LSP: Undefined global "vim" when using lua-language-server with custom lua config file

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#21686] opened 2023-01-08 01:59 UTC
### Neovim version (nvim -v)

HEAD

### Language server name/version

lua-language-server 3.6.4

### Operating system/version

macOS 12.5.1

### Steps to reproduce using "nvim -u minimal_init.lua"

in ftplugin/lua.lua (following suggested place from lsp.txt docs):

```lua
vim.lsp.start({
  name = 'testservername',
  root_dir = vim.fs.dirname(vim.fs.find('luarc.lua', { upward = true, })[1]),
  cmd = { 'lua-language-server', '--configpath=luarc.lua' },
  settings = {
    Lua = {
      runtime = { version = 'LuaJIT' },
    },
  },
})
```

create a `~/.config/nvim/luarc.lua` file, following the [lua-language-server wiki for custom config files](https://github.com/sumneko/lua-language-server/wiki/Configuration-File#custom-config-file):

```lua
return {
  Lua = {
    workspace = {
      library = vim.api.nvim_get_runtime_file("", true),
    },
    diagnostics = {
      globals = {
        "vim"
      }
    },
  }
}
```

### Expected behavior

`Lua.diagnostics.globals` list should work in a custom lua config passed to lua-language-server via the `--configpath=` flag.

### Actual behavior

Open any old neovim lua file with a `vim.whatever` call. Diagnostics will give a warning about the `Undefined global 'vim'.` even though we have declared it in our config file as a known global. It also seems that the `vim.api.nvim_get_runtime_file()` call in `Lua.workspace.library` didn't work either.

I don't know that this is a LSP client error, or a lua-language-server error, or a bit of both, or neither. I'm thinking it may have something to do with loading order like this other issue: #21588 

### Log file

https://gist.github.com/craigmac/ea4d8d1032e5c175090d8a9adbcd2d98

**Comment by haolian9** [comment] 2023-01-08 11:01
So the lua-lang-server will evaluate `~/.config/nvim/luarc.lua` on its own.
Then obviously it knows nothing about `vim` in `vim.api.nvim_get_runtime_file("", true)`.

**Comment by craigmac** [comment] 2023-01-08 14:50
It doesn't that's true, but does this then it stops all processing of the `luarc.lua` at that point? I can't see that in the logs. It seems to have stopped processing the config at that point though, as the neovim rtp hasn't been added, and "vim" isn't a recognized global in any lua file after this. Can you think of any workaround to this? I can't use a `.luarc.json` because I'd have to hard-code every single rtp value in there and keep it in sync, rather have it built dynamically. Yes, I could add this in my `vim.lsp.start()` call but I don't want to add these rtp values globally (lua-language-server mentions it slows down the server if you do this globally).

**Comment by mfussenegger** [comment] 2023-01-09 19:06
> It doesn't that's true, but does this then it stops all processing of the luarc.lua at that point?

It's very likely that it stops evaluating it. 

> Yes, I could add this in my vim.lsp.start() call but I don't want to add these rtp values globally (lua-language-server mentions it slows down the server if you do this globally).

You could do it per project if you write your own code that looks for a luarc.lua, evaluates it and calls vim.lsp.start with the resulting settings

Closing this as it's not a bug in the lsp client

**Closed by mfussenegger** 2023-01-09 19:06 UTC
Labels: lsp

**Comment by craigmac** [comment] 2023-01-09 20:29
> You could do it per project if you write your own code that looks for a luarc.lua, evaluates it and calls vim.lsp.start with the resulting settings

Good idea, I'll do that, thanks!

**Comment by sureshsaragadam** [comment] 2023-08-15 18:12
i had the same Warning with lua_ls in neovim 
my nvim -v
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
![Screenshot from 2023-08-15 23-39-10](https://github.com/neovim/neovim/assets/47267790/f04694ee-ce52-4040-9b8e-51950382b522)

[](url)
