### ISSUE TITLE
Expression register crash

### ISSUE THREAD

**Issue by tricktux** [neovim/neovim#11574] opened 2019-12-18 21:24 UTC
- `nvim --version`:
	- `NVIM v0.5.0-132-g83b6d9f19`
	- `Build type: RelWithDebInfo`
- `vim -u DEFAULTS` (version: ) behaves differently?
	- Didn't test
- Operating system/version: `Arch`
- Terminal name/version: `termite`
- `$TERM`: `xterm-termite`

### Steps to reproduce using `nvim -u NORC`

1. `nvim -u NONE`
2. Go into insert mode: `i`
3. Type: `CTRL-R` + `=` + `echo 1024*1024`

### Actual behaviour

[coredump](https://send.firefox.com/download/e914cb4c4941386b/#I3vDL7rNNcC0-VP0ZUqwKA)
*It will be up for only 7 days

### Expected behaviour

I know this is not a valid expression, but it should not crash

**Comment by KillTheMule** [comment] 2019-12-18 21:53
Can confirm with NVIM v0.4.0-1139-g027ebb23d. Note that his already crashes when pressing the `*` with

> ../src/nvim/viml/parser/expressions.c:1241: viml_pexpr_handle_bop: Assertion `bop_node_lvl != new_top_node_lvl || bop_node_ass == new_top_node_ass' failed.
>            Aborted

**Comment by justinmk** [comment] 2019-12-19 06:08
Duplicate of https://github.com/neovim/neovim/issues/7889

Yes, it's an old bug. Someone needs to take https://github.com/neovim/neovim/pull/8421 to the finish line.

> 3\. Type: `CTRL-R` + `=` + `echo 1024*1024`

Didn't repro for me.

**Closed by justinmk** 2019-12-19 06:08 UTC
Labels: bug
