### ISSUE TITLE
Xterm not working like other terminals for autopair curly braces { }

### ISSUE THREAD

**Issue by Xemptuous** [neovim/neovim#22570] opened 2023-03-08 07:53 UTC
### Problem

When using xterm with the plugin `windwp/nvim-autopairs` the curly braces `{` do not auto-pair; but all others do incl. parentheses, brackets, single & double quotes, and backticks.

when using other terminal emulators (kitty and terminator), they work as expected using the same configs and nvim versions.

I am led to believe this is related to interactions between NeoVIm and xterm.

I also tested this behavior with NeoVim versions 0.8.3, and 0.9.0-dev-1028+gd422fc827 and had the same results.

### Steps to reproduce

install `nvim-autopairs` with package manager (e.g., lazy).
open neovim with xterm
type `{`versus `[` or `"` or `'` or `(` in any filetype buffer

### Expected behavior

curly braces should auto-pair or auto-complete as they do when being used with other terminal emulators.

### Neovim version (nvim -v)

0.9.0-dev-1166+g06aed7c17

### Vim (not Nvim) behaves the same?

not sure

### Operating system/version

Debian sid w/ i3-wm and Gnome

### Terminal name/version

xterm v379-1

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by zeertzjq** [comment] 2023-03-08 08:02
Duplicate of #20910

**Comment by zeertzjq** [comment] 2023-03-08 08:02
Duplicate of #20190

**Closed by zeertzjq** 2023-03-08 08:02 UTC
Labels: bug

**Comment by Xemptuous** [comment] 2023-03-10 08:11
This issue seems most closely related to #21399, as I am now noticing that the `nvim-surround` plugin also fails to respond to specifically the braces, which are not picked up in the codebases for solely braces
