### ISSUE TITLE
visual selection off-by-one when expanded backwards

### ISSUE THREAD

**Issue by nkgm** [neovim/neovim#8983] opened 2018-09-11 23:10 UTC
For example, `vb`:

![image](https://user-images.githubusercontent.com/5631881/45392445-14e46d00-b630-11e8-90d0-11c043850bee.png)

This is purely a visual issue as the underlying selection behaves as expected.

NVIM v0.2.1-867-gd2cbc31

**Comment by shmerl** [comment] 2019-01-02 19:52
Do you mean the missing highlighting of the first character in the visual selection when selecting from right to left? I also noticed this problem.

**Comment by justinmk** [comment] 2019-01-02 19:58
Happens in Vim 8.1.50 also. Probably intentional, therefore `wontfix`.

**Comment by shmerl** [comment] 2019-01-02 20:01
What is the intent behind it? It sounds like a bug, at least it's very non intuitive and looks inconsistent. If there is some use case for this, can there be some configuration which controls it, for those who prefer more consistently looking selection?

**Comment by shmerl** [comment] 2019-01-02 20:08
Can you reopen then, please?

**Comment by justinmk** [comment] 2019-01-02 22:53
This happens regardless of `selection`, but it's more noticeable with `selection=exclusive` because the default value of `guicursor` sets a vertical-bar cursor for `ve` (visual + `selection=exclusive`).

And I just confirmed that yes, Vim 8.1.50 does have the same behavior, regardless of `selection`.

**Comment by justinmk** [comment] 2019-01-02 23:13
@shmerl see https://github.com/neovim/neovim/pull/9446

**Comment by shmerl** [comment] 2019-01-03 00:05
> I think it's to avoid changing the foreground color of the text, which could be hard to read against a block cursor. Traditionally Vim's visual selection does "reverse mode".

I guess making it configurable (with option to turn it on and off) will cover all possibilities.

In my case I'm using a block cursor which does the inversion, but I also make it blinking. When the cursor goes off, the inversion is turned off as well. So it would be ideal to keep the color the same when cursor is active (as a block) and show selection colors when the cursor is off (blinked out).

**Comment by justinmk** [comment] 2019-01-03 00:14
> So it would be ideal to keep the color the same (i.e. inverted) when cursor is active, and show selection colors when the cursor is off (blinked out).

That's not possible, the blinking is controlled by the terminal. If you're using a GUI (not a terminal) then such a feature request nevertheless must be directed to the GUI, because Nvim still has no knowledge of the blink state.

So it sounds like you actually don't want the highlight, except sometimes, which means this is `wontfix`.

**Comment by justinmk** [comment] 2019-01-03 00:59
Pushed another approach to https://github.com/neovim/neovim/pull/9446

**Closed** 2019-01-04 00:53 UTC
Labels: compatibility, complexity:low, display, enhancement

**Comment by shmerl** [comment] 2019-01-07 21:44
I can confirm that selection is working for me now properly. Thanks for fixing!
