### ISSUE TITLE
mouse operation hangs neovim

### ISSUE THREAD

**Issue by bigeagle** [neovim/neovim#1935] opened 2015-02-03 03:47 UTC
Hi there,

I recently updated my neovim from git version 050c651 to 9023f62, then I found all my mouse operations (clicking, scrolling) seems to trigger some input to neovim, and the whole program hangs (runs very slowly). 

It's strange that if I run nvim inside tmux, this problem does not appear. 

Cheers,

**Comment by Pyrohh** [comment] 2015-02-03 06:25
Hello,

If you run `nvim -u NONE`, do you still experience the issue? If you built and installed from git, you may be running a debug build (`nvim --version` should tell you, under `Build Type`), which can be noticeably slower.

**Comment by bigeagle** [comment] 2015-02-03 06:30
Hi,

When running `nvim -u NONE` and `:set mouse=a`, the problem still exists. My nvim version is 
```
NVIM 0.0.0-alpha+201502021723 (compiled Feb  3 2015 11:35:01)
Commit: 7751cd21f5ae8952f578a0ccd892e32c95a4ae8a
Build type: Release
```
It seems nvim didn't recognize the input events are from mouse but processed it as press, since I got some strange characters in the input buffer.

Cheers,

**Comment by bigeagle** [comment] 2015-02-03 06:31
This version doesn't have this bug:
```
NVIM 0.0.0-alpha+201501060012 (compiled Jan  7 2015 16:26:47)
Commit: 050c6515f80b4964d7d9a7b66fa95146a4f38e4c
Build type: Release
```

**Comment by Pyrohh** [comment] 2015-02-03 06:53
This might have been caused by #1810. I can recall two different mouse related issues recently which don't happen on #1820. Could you give that branch a try?

**Comment by bigeagle** [comment] 2015-02-03 07:45
Yes the problem does not show in #1820.

**Comment by Pyrohh** [comment] 2015-02-03 19:33
@bigeagle would you like to keep this open? Or are your issues now resolved in #1820?

**Comment by tarruda** [comment] 2015-02-03 19:41
> @bigeagle would you like to keep this open? Or are your issues now resolved in #1820?

I have high hopes that #1820 will be merged on friday

**Comment by bigeagle** [comment] 2015-02-04 03:31
@Pyrohh I don't mind to close this issue, but I'd prefer closing it after #1820 merged.

**Comment by Pyrohh** [comment] 2015-02-04 03:38
Oh yeah, of course.

**Comment by Pyrohh** [comment] 2015-02-17 05:17
@bigeagle Now that #1820 is merged, would you mind closing this (assuming your issue is fixed of course)?

**Closed** 2015-02-17 05:21 UTC

**Comment by bigeagle** [comment] 2015-02-17 08:48
Sure :)
