### ISSUE TITLE
Where can I find `nvim-linux64.deb` for version 0.9?

### ISSUE THREAD

**Issue by LittleNewton** [neovim/neovim#22975] opened 2023-04-09 12:17 UTC
### Problem

I cannot find it in the release page. Would you mind provide this release package? Or explain why don't provide one.

### Expected behavior

I can find the deb package in 0.8 but 0.9

**Comment by zeertzjq** [comment] 2023-04-09 12:21
Duplicate of #22684

**Closed by zeertzjq** 2023-04-09 12:21 UTC
Labels: closed:duplicate

**Comment by aistellar** [comment] 2023-04-16 08:17
To build a Debian package
```
apt install ninja-build gettext cmake unzip curl git file
make CMAKE_BUILD_TYPE=Release
cmake --build build --target package
```
https://github.com/neovim/neovim/wiki/Building-Neovim#ubuntu--debian
