### ISSUE TITLE
inccommand=nosplit: segfault/hang when adding ":%s//" to the end of a extract-constant macro

### ISSUE THREAD

**Issue by TimoFreiberg** [neovim/neovim#12028] opened 2020-03-19 13:57 UTC
- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
no comparison to vim possible as `inccommand` doesn't exist in vim
- Operating system/version:
`Arch Linux (5.5.9 kernel)`
- Terminal name/version:
`GNOME Terminal 3.36.0.1 using VTE 0.60.0 +BIDI +GNUTLS +ICU +SYSTEMD`

- `$TERM`:
`screen-256color`

### Steps to reproduce using `nvim -u NORC`

See also attached file 
[segv.txt](https://github.com/neovim/neovim/files/4354934/segv.txt)
`nvim -u NONE segv.txt`
```
:set inccommand=nosplit

load the following macro:
di'ma?jumptarget^MoBAZ = ^[p`ai$BAZ^[/\v<BAZ>^Mzz:%s//
(note the `^M` and `^[`)

put the cursor on the 'bar' at the bottom of the buffer
run @m
type `a` (or some arbitrary text) (sometimes nvim freezes after this)
press <Esc>
press u
if it didn't segfault yet, redo/undo a few times

jumptarget

     vvv cursor on the bar here
foo('bar')
```

### Actual behaviour

nvim either freezes while entering text after the `:%s//` prompt or segfaults a few inputs later (apparently not deterministic!)

### Expected behaviour

nvim completes the macro (including opening the `:%s//` prompt) and continues working

**Comment by glacambre** [comment] 2021-06-05 08:37
@TimoFreiberg can you still reproduce this with [neovim nightly](https://github.com/neovim/neovim/releases)? I can't.

**Comment by TudbuT** [comment] 2022-05-13 16:55
> @TimoFreiberg can you still reproduce this with [neovim nightly](https://github.com/neovim/neovim/releases)? I can't.
yes, the issue is in nightly aswell, and it still happens.

**Comment by justinmk** [comment] 2022-06-26 10:07
Please try nightly again! Implementation of 'inccommand' changed with https://github.com/neovim/neovim/pull/18194 which was merged May 31.

**Comment by TimoFreiberg** [comment] 2022-06-26 10:21
I totally forgot the details of this, but I could follow my own instructions again so that's great.
I can't reproduce this on the current nightly!
the macro doesn't work properly, which might or might not be a bug, but I don't get segfaults/crashes even when undo/redoing the process tens of times.
I'm fine with closing this 👍

**Closed** 2022-06-26 10:23 UTC
Labels: status:needs-response, bug-crash

**Comment by justinmk** [comment] 2022-06-26 10:55
> the macro doesn't work properly, which might or might not be a bug

'inccommand' must not interfere or even activate during non-interactive usage (such as macros or mappings). This is covered by tests but if it is interfering with macros please do report it.
