### ISSUE TITLE
Remove Ex mode! 

### ISSUE THREAD

**Issue by fakeid30** [neovim/neovim#7166] opened 2017-08-15 14:00 UTC
Since Neovim is a refactor of legacy vim codebase, what is the real world usefulness of Ex mode? Can't it be removed? 

The only use I ever had of this mode was when my network was too slow and I had to ssh into a server, I used Ex mode to edit text on a file non interactively. Since the chance of a random server having neovim is low, and slow network which doesn't redraw text, is close to nil, what is the point of having a legacy system like Ex mode? 

This isn't a rant or anything, I am asking a legit question here. I could not find a single use of this mode.

**Comment by jamessan** [comment] 2017-08-15 14:07
Duplicate of #1089.

**Closed by jamessan** 2017-08-15 14:07 UTC

**Comment by ZyX-I** [comment] 2017-08-15 14:09
@jamessan That issue was locked by @justinmk, so it can’t be discussed.

**Comment by justinmk** [comment] 2017-08-15 18:56
Ex mode is used for `nvim -es` , I think. Which is important.
