### ISSUE TITLE
Neovim can't make backup file(s)

### ISSUE THREAD

**Issue by MakotoTheKnight** [neovim/neovim#3551] opened 2015-10-28 20:47 UTC
I'm getting this error when I attempt to write files out with Neovim:

```E510: Can't make backup file (add ! to override)```

I have full permissions into the directories that I'm writing to, and this particular issue didn't crop up the last time I used Neovim, which was less than a week ago (prior to this latest release).

Version info:

```
NVIM 0.0.0-alpha (compiled Oct 28 2015 08:52:58)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-lddVLo/neovim-0.0.0+git201510280208+1950+14~ubuntu15.04.1/build/config -I/build/neovim-lddVLo/neovim-0.0.0+git201510280208+1950+14~ubuntu15.04.1/src -I/build/neovim-lddVLo/neovim-0.0.0+git201510280208+1950+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-lddVLo/neovim-0.0.0+git201510280208+1950+14~ubuntu15.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-lddVLo/neovim-0.0.0+git201510280208+1950+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-lddVLo/neovim-0.0.0+git201510280208+1950+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-lddVLo/neovim-0.0.0+git201510280208+1950+14~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-lddVLo/neovim-0.0.0+git201510280208+1950+14~ubuntu15.04.1/build/src/nvim/auto -I/build/neovim-lddVLo/neovim-0.0.0+git201510280208+1950+14~ubuntu15.04.1/build/include
Compiled by buildd@lgw01-13
```

**Comment by Pyrohh** [comment] 2015-10-28 21:04
dupe of #3496, all backups are now stored in `~/.local/share/nvim/backup` by default (dictated by the `backupir` variable). However, the directory is, IIRC, not automatically created if it doesn't exist, so just do so manually to fix the warning.

**Closed by Pyrohh** 2015-10-28 21:04 UTC

**Comment by phcerdan** [comment] 2015-10-29 12:02
Shouldn't be the folder created automatically? or writebackup disabled by default? Not really user-friendly doing it manually.

**Comment by dani-h** [comment] 2015-10-29 12:32
@phcerdan :+1:

**Comment by HolgerPeters** [comment] 2015-10-29 12:48
Imho nvim should create that directory.

**Comment by Pyrohh** [comment] 2015-10-29 16:55
I agree, but this is already mentioned in #3496.
