### ISSUE TITLE
LSP[rust_analyzer] received `end` message with no corresponding `begin`

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/neovim#19158] opened 2022-06-29 20:54 UTC
### Neovim version (nvim -v)

NVIM v0.8.0-dev+1976-g6f6286e4f

### Language server name/version

rust-analyzer 0.0.0 (b74e96f50 2022-06-26)

### Operating system/version

macOS v12.4

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
vim.cmd('syntax off')
vim.cmd('filetype off')
vim.cmd('filetype plugin indent off')

local cache_dir = vim.env.HOME .. '/.cache'
local dein_dir = cache_dir .. '/dein'
local dein_repo_dir = dein_dir .. '/repos/github.com/Shougo/dein.vim'

if not string.match(vim.o.runtimepath, '/dein.vim') then
	if vim.fn.isdirectory(dein_repo_dir) ~= 1 then
		os.execute('git clone https://github.com/Shougo/dein.vim ' .. dein_repo_dir)
	end
	vim.o.runtimepath = dein_repo_dir .. ',' .. vim.o.runtimepath 
end

if vim.call('dein#min#load_state', dein_dir) ~= 1 then
    return
end

vim.call('dein#begin', dein_dir)

vim.call('dein#add', 'rust-lang/rust.vim')
vim.call('dein#add', 'neovim/nvim-lspconfig')
vim.call('dein#add', 'hrsh7th/nvim-cmp')
vim.call('dein#add', 'hrsh7th/cmp-nvim-lsp')

vim.call('dein#end')
vim.call('dein#save_state')


require'lspconfig'.rust_analyzer.setup {}

local cmp = require('cmp')

cmp.setup {

  mapping = {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({
      select = true,
    }),
  },

  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
  }),
}

vim.cmd('syntax on')
vim.cmd('filetype on')
vim.cmd('filetype plugin indent on')
```

### Expected behavior

a

### Actual behavior

a

**Comment by clason** [comment] 2022-06-29 20:57
Duplicate of #19157

**Closed by clason** 2022-06-29 20:57 UTC
Labels: bug, lsp
