### ISSUE TITLE
In vimscript, evaluating a global variable without prefixing g: will fail the first time.

### ISSUE THREAD

**Issue by btipling** [neovim/neovim#1606] opened 2014-12-03 17:40 UTC
You can verify by adding the following to a `.nvimrc` and running `:Foo` twice. 

```
let foo = 'bar'

function! FooInit()
  command! Foo echom foo
  Foo
endfunction

command! Foo call FooInit()
```

The first time calling `:Foo` will fail, the second time it will print `bar` to :messages. If `command! Foo echom foo` was changed to `command! Foo echom g:foo`, prefixing the variable with `g:` this problem doesn't happen.

This is also a problem for `vim.eval` in the python-client (neovim/python-client#69). This issue didn't used to exist for python-client before the remote-plugin system changes were merged in.

nvim version:

```
NVIM 0.0.0-alpha+201412021515 (compiled Dec  2 2014 14:30:32)
Commit: 81394c9d73a0dc579dd82d3bb83fd36711299ea1
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/Users/bjorn/apps/neovim/build/config -I/Users/bjorn/apps/neovim/src -I/Users/bjorn/apps/neovim/.deps/usr/include -I/Users/bjorn/apps/neovim/.deps/usr/include -I/Users/bjorn/apps/neovim/.deps/usr/include/luajit-2.0 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -I/Users/bjorn/apps/neovim/build/src/nvim/auto -I/Users/bjorn/apps/neovim/build/include
Compiled by root@achilles.local  Features included (+) or not (-):
+acl             +farsi           -mouse_gpm       -tag_any_white
+arabic          +file_in_path    +mouse_netterm   +terminfo
+autocmd         +find_in_path    +mouse_sgr       +termresponse
-browse          +float           -mouse_sysmouse  +textobjects
+byte_offset     +folding         +mouse_urxvt     +title
+cindent         -footer          +mouse_xterm     -toolbar
-clipboard       +fork()          +multi_byte      +user_commands
+cmdline_compl   +gettext         +multi_lang      +vertsplit
+cmdline_hist    +iconv           +path_extra      +virtualedit
+cmdline_info    +insert_expand   +persistent_undo +visual
+comments        +jumplist        +postscript      +visualextra
+conceal         +keymap          +printer         +viminfo
+cscope          +langmap         +profile         +vreplace
+cursorbind      +libcall         +quickfix        +wildignore
+cursorshape     +linebreak       +reltime         +wildmenu
+dialog_con      +lispindent      +rightleft       +windows
+diff            +listcmds        +scrollbind      +writebackup
+digraphs        +localmap        +signs           -X11
-dnd             +menu            +smartindent     -xfontset
-ebcdic          +mksession       +startuptime     -xsmp
-emacs_tags      +modify_fname    +statusline      -xterm_clipboard
+eval            +mouse           +syntax
+ex_extra        -mouseshape      +tag_binary
+extra_search    +mouse_dec       +tag_old_static
   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "$HOME/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/nvim"
```

Using OS X 10.10.

**Comment by justinmk** [comment] 2016-10-29 12:47
This is by design of VimL, so closing.

**Closed by justinmk** 2016-10-29 12:47 UTC
Labels: question, viml
