### ISSUE TITLE
clipboard: error: -2

### ISSUE THREAD

**Issue by subnut** [neovim/neovim#13509] opened 2020-12-11 04:43 UTC
- `nvim --version`:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? 
  Could not check. Issue not consistently reproducible.
- Operating system/version:
  Arch linux.
- Terminal name/version:
  kitty, latest version
- `$TERM`: 
  `xterm-kitty`

### Actual behaviour
Sometimes, when starting `nvim`, it gets stuck on a blank screen. If I press Ctrl-C, it immediately recovers and starts up correctly, but `:messages` shows this line on top (using `echohl WarningMsg`) -
```
clipboard: error: -2
```
I haven't been able to reproduce this issue reliably. It is very irregular. But it is frequent. It occurs atleast twice/thrice per week.

### Expected behaviour
Does not hang.
The above error message isn't shown

**Comment by glacambre** [comment] 2020-12-11 10:24
Sounds like an init.vim issue. Can you reproduce it when running `nvim -u NORC`?

**Comment by subnut** [comment] 2020-12-11 10:58
Umm.... actually, this issue is very irregular. In fact, just after it happens, even if I immediately open another neovim instance, it doesn't happen.

As it is unfeasible for me to always keep running on `nvim -u NORC`, so I am actually at a loss on how to reproduce it using `nvim -u NORC`

**Comment by glacambre** [comment] 2020-12-11 13:42
I guess you could try disabling these three plugins and seeing if it helps. If it doesn't, I'd recommend building neovim in debug mode and attaching to it with GDB when it hangs. You'll be able to get a backtrace and probably enough information to find out where the message is coming from :)

**Comment by subnut** [comment] 2020-12-11 17:15
Right now... I don't have enough time in hand to follow the steps mentioned above, and will not have for a few months.
@glacambre Should I close this issue till then?

**Comment by glacambre** [comment] 2020-12-12 09:39
Yeah, I think this should be closed as there is no easy way to reproduce for neovim developpers. Feel free to reopen once you have more information :)

**Closed by glacambre** 2020-12-12 09:39 UTC
Labels: bug

**Comment by evertonse** [comment] 2024-07-03 23:49
I had the symptons presented in this issue, although I was on the WSL2 using arch, the problem was that insider my WSL I had installed *win32yank-bin* by pacman. 

After uninstalling that, clipboard error -2 didn't occur anymore.

This problem were occurring even with "nvim -u NORC".
