### ISSUE TITLE
Incorrect display and treatment of multi-byte characters

### ISSUE THREAD

**Issue by frangio** [neovim/neovim#1672] opened 2014-12-15 00:46 UTC
Documents with multi-byte characters such as "ñ" or "こ" don't display correctly and act as if each byte was a character on its own.

Inserting a character "ñ" seems to be alright at first but: a) the cursor will behave as if two characters had been inserted, and b) after doing a line selection (```V```) two "replacement characters" (�) will be shown in place of the "ñ" and next to it.
After inserting a character "こ" it will immediately display as gibberish. Three garbage characters will be shown in its place, each can be selected and edited independently.
Inserting other multi-byte characters shows similar behaviour.

I'm running on OS X 10.10.1, and could reproduce this bug on iTerm (2.0.0.20141103) and Terminal.app.

This started happening after updating neovim about two weeks ago. Before that I think I was running an October release but I'm not sure. The current version displays the same bug.

```
:version
NVIM 0.0.0-alpha+201412141614 (compiled Dec 14 2014 21:18:27)
Commit: a5edc5f2572d6d63f7f7a32ae6ec7bcabe1472b6
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-cS36K
f/build/config -I/tmp/neovim-cS36Kf/src -I/tmp/neovim-cS36Kf/.deps/usr/include -I/tmp/neovim-cS36Kf/.deps/usr/include -I/tmp/neovim-cS36Kf/.deps/usr/include/luajit-2.0 -I/Library/Frameworks/R.framework/Headers -
I/usr/include -I/tmp/neovim-cS36Kf/build/src/nvim/auto -I/tmp/neovim-cS36Kf/build/include
Compiled by frangio  Features included (+) or not (-):
+acl             +cmdline_hist    +diff            +farsi           +iconv           +listcmds        -mouse_gpm       +path_extra      +scrollbind      -tag_any_white   +virtualedit     +writebackup
+arabic          +cmdline_info    +digraphs        +file_in_path    +insert_expand   +localmap        +mouse_netterm   +persistent_undo +signs           +terminfo        +visual          -X11
+autocmd         +comments        -dnd             +find_in_path    +jumplist        +menu            +mouse_sgr       +postscript      +smartindent     +termresponse    +visualextra     -xfontset
-browse          +conceal         -ebcdic          +float           +keymap          +mksession       -mouse_sysmouse  +printer         +startuptime     +textobjects     +viminfo         -xsmp
+byte_offset     +cscope          -emacs_tags      +folding         +langmap         +modify_fname    +mouse_urxvt     +profile         +statusline      +title           +vreplace        -xterm_clipboard
+cindent         +cursorbind      +eval            -footer          +libcall         +mouse           +mouse_xterm     +quickfix        +syntax          -toolbar         +wildignore
-clipboard       +cursorshape     +ex_extra        +fork()          +linebreak       -mouseshape      +multi_byte      +reltime         +tag_binary      +user_commands   +wildmenu
+cmdline_compl   +dialog_con      +extra_search    +gettext         +lispindent      +mouse_dec       +multi_lang      +rightleft       +tag_old_static  +vertsplit       +windows
   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "$HOME/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

**Comment by Breakster** [comment] 2015-01-15 12:16
I could actually reproduce this bug on a manual build. In fact, the test case test_listlbr_utf8 in the oldtest suite is failing and it seems to be related to this issue.

This issue pops up in both the neovim version installed with Homebrew as well as a manually built version:
NVIM 0.0.0-alpha+201501130938 (compiled Jan 14 2015 23:49:12)
Commit: 9b4f6fbd33ebd452d472b0333accfcb34e01173b

I'm using OSX 10.10.1, iTerm2 and zsh.

It is unlikely that the terminal or shell has anything to do with it though, because I see the same issue with Terminal.app and bash.

I don't have any ideas how to track down this issue, but maybe this info helps.

**Comment by Breakster** [comment] 2015-01-17 01:20
Looking into this issue a bit, I found the following. It seems the character encoding is not set properly when launching vim. When running `:set encoding=utf-8` after startup, utf-8 characters are displayed correctly.

I think the problem is in enc_locale(). The block of if statements in mbyte.c:3411 is supposed to return the locale of the shell (is this true?), but instead it is overwritten. Even though LC_CTYPE is set to "UTF-8" in the shell, the final char string is "US-ASCII". 

```c
# ifdef HAVE_NL_LANGINFO_CODESET
  if ((s = nl_langinfo(CODESET)) == NULL || *s == NUL)
# endif
#  if defined(HAVE_LOCALE_H) || defined(X_LOCALE)
    if ((s = setlocale(LC_CTYPE, NULL)) == NULL || *s == NUL)
#  endif
      if ((s = (char *)os_getenv("LC_ALL")) == NULL || *s == NUL)
        if ((s = (char *)os_getenv("LC_CTYPE")) == NULL || *s == NUL)
          s = (char *)os_getenv("LANG");
```

Commenting out the `nl_langinfo()` call and the `setlocale()` call gives the desired behaviour for me. Not sure if this will cause issues no other systems though.

**Comment by frangio** [comment] 2015-03-04 22:50
I would like to confirm this is still an issue for neovim built via Homebrew install. Like @Breakster said, running `:set encoding=utf-8` after startup works as an ad-hoc solution.

**Comment by Breakster** [comment] 2015-03-05 07:36
I think I have a fix for this issue. mb_init() is supposed to initialise multibyte support. However it is not called after the default for encoding has been set. This probably has to do with updating default values for neovim, and the initialisation was not updated accordingly.

I will try to make a proper fix for this in the coming days.

As I am new to this project, and actually open source development in general, what is the proper way to publish a fix?

**Comment by justinmk** [comment] 2015-03-05 14:52
@breakster that is very likely, and it may fix another bug I noticed. Thanks for investigating. See CONTRIBUTING.md.

**Comment by Breakster** [comment] 2015-03-06 22:22
I submitted a pull request for this.

https://github.com/neovim/neovim/pull/2106

**Comment by justinmk** [comment] 2015-03-06 22:45
@Breakster Thanks, there is something I need to look at though.

**Closed** 2015-03-07 23:01 UTC
Labels: bug, encoding, ui
