### ISSUE TITLE
OS X builds are faulty...

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#1972] opened 2015-02-10 11:28 UTC
I suspect this has more to do with Travis than us, but I keep getting messages about broken builds on OS X.  I'm running them locally with no issues on Yosemite.

Most of them appear to be hanging.  However, the latest one seems like LuaJIT is to blame:

```text
-- Output to stderr:
PANIC: unprotected error in call to Lua API (29)
```

I'd hate to disable the OS X builds, but we also need them to be reliable. :-(

**Comment by tarruda** [comment] 2015-02-10 11:34
Is it for gcc only? If so, this could be the cause: http://lua-users.org/lists/lua-l/2011-08/msg00803.html

We could try replacing luajit with plain lua for running tests(and use it only for the vimL translator later)

**Comment by jszakmeister** [comment] 2015-02-10 11:37
Sadly, no, it's not just gcc.  Clang has been hanging too.  This is the first time I've seen the panic issue.  I've been running the tests locally and have not seen any issues, so it smells like something has gone wrong (versus LuaJIT being broken).

**Comment by fwalch** [comment] 2015-02-10 11:50
As a first step, we could change the Busted output type to "TAP" to find out which test causes the PANIC.

**Comment by jszakmeister** [comment] 2015-02-10 11:55
I've only seen the PANIC once, so I'm not even sure it'll reproduce. :-(  I've been working on some TAP improvements for busted, but at the moment, the busted TAP output only prints the name of the test after it has passed or failed.  A PANIC is a pretty hard failure and I believe it'll just dump out at that point and not print the test name.  So, we just need to be cognizant that it's the next test after the one we see that has failed.

The other issue is that the TAP output has been... less useful than the plainTerminal or utfTerminal. :-(  But it's probably worth a try.

**Comment by elmart** [comment] 2015-02-10 11:57
FWIW, the "panic" error has happened to me several times this past week.

**Comment by tarruda** [comment] 2015-02-10 11:57
I think the best move here is to build luajit for debugging and run it with gdb, setting a break in the function that prints the 'unprotected error' message(which would be `panic` in src/lib_aux.c).

**Comment by tarruda** [comment] 2015-02-10 11:59
BTW, it seems to be possible to get a lua stack from luajit backtrace with this: https://github.com/openresty/nginx-gdb-utils#lbt (I haven't tested).

**Comment by jszakmeister** [comment] 2015-02-10 12:02
> Is it for gcc only? If so, this could be the cause: http://lua-users.org/lists/lua-l/2011-08/msg00803.html

D'oh, I didn't realize you were talking about the panic here.  That could very well be the issue.

**Comment by fwalch** [comment] 2015-02-10 12:17
The panic also occurred with Clang at some point: https://travis-ci.org/neovim/neovim/jobs/49841104

**Comment by tarruda** [comment] 2015-02-10 16:16
I've enabled a bunch of compilation flags to simplify debugging, and also enhanced the lua client with a custom panic function that should print the lua backtrace when the unprotected error is triggered.

The problem now seems to be downloading dependencies for OSX: https://travis-ci.org/neovim/neovim/jobs/50207759

Maybe these need to be included in the deps repository?

**Comment by Pyrohh** [comment] 2015-04-20 21:06
I'll close this I have not seen this issue in a while, but please reopen if I'm wrong.

**Closed by Pyrohh** 2015-04-20 21:06 UTC
