### ISSUE TITLE
Pythons logging module doesn't work

### ISSUE THREAD

**Issue by Drllap** [neovim/neovim#22462] opened 2023-03-01 00:25 UTC
### Problem

Logging with pythons logging module doesn't work

### Steps to reproduce

nvim --clean
py3 << EOF
import logging
logging.basicConfig(filename='some-log.log', level=logging.NOTSET)
logging.info("fle fle")
EOF

### Expected behavior

A file with the name `some-log.log` with the line `INFO:root:fle fle` should have been created

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal Version: 1.16.10261.0

### $TERM environment variable

vtpcon

### Installation

chocolatey

**Comment by zeertzjq** [comment] 2023-03-01 00:33
Duplicate of https://github.com/neovim/pynvim/issues/373

**Closed by zeertzjq** 2023-03-01 00:33 UTC
Labels: bug
