### ISSUE TITLE
env option doesn't work with termopen()

### ISSUE THREAD

**Issue by mg979** [neovim/neovim#12899] opened 2020-09-12 03:15 UTC
- `nvim --version`: NVIM v0.5.0-682-g997147e4b
- `vim -u DEFAULTS` (version: 8.1) behaves differently? similarly
- Operating system/version: MX Linux (debian buster)
- Terminal name/version: xfce4-terminal
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:call termopen('echo $TESTVAR', {'env': {'TESTVAR': 'test string'}})
```

### Actual behaviour

It prints nothing

### Expected behaviour

It should print `test string`

I can add that in vim it doesn't work either, doing:

    call term_start('echo $TESTVAR', {'env': {'TESTVAR': 'test string'}})

prints `$TESTVAR` and not `test string`.

I can also add that `env` works correctly for `jobstart()` (also in vim).

**Comment by erw7** [comment] 2020-09-12 19:12
Duplicate of #11751.

**Closed by erw7** 2020-09-12 19:12 UTC
Labels: bug, duplicate
