### ISSUE TITLE
Neovim stopped working with Vundle plugin

### ISSUE THREAD

**Issue by themightyoarfish** [neovim/neovim#5109] opened 2016-07-24 09:25 UTC
- `nvim --version`: 

```
NVIM v0.1.5-630-g291c3c6
Build type: Release
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/Volumes/Data/Downloads/Sources/neovim/build/config -I/Users/Rasmus/Downloads/Sources/neovim/src -I/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include -I/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include -I/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include -I/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include -I/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include -I/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include -I/opt/local/include -I/opt/local/include -I/Volumes/Data/Downloads/Sources/neovim/build/src/nvim/auto -I/Volumes/Data/Downloads/Sources/neovim/build/include
Compiled by Rasmus@rasmus-macbook-pro.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```
- Vim (version: 7.3) behaves differently? Yes
- Operating system/version: OSX 11.5.1
- Terminal name/version: iTerm 3.0.4
- `$TERM`: xterm-256color
### Actual behaviour

This is a minimal `.vimrc`:

```
" Init Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-commentary'

call vundle#end()
```

Previously `commentary.vim` used to work flawlessly. Now (without any change I can remember), the `gc` mapping is not defined anymore.
Running `:scriptnames` shows that `bundle/vim-commentary` scripts are not loaded (???).
### Expected behaviour

neovim loads plugin so mapping should be defined.
### Steps to reproduce using `nvim -u .myvimrc`
1. open `.myvimrc` with Vundle installed, run `:PluginInstall`
2. open file with nvim
3. `gcc` (current line should be commented out)
4. nothing is commented out

**Comment by mhinz** [comment] 2016-07-24 09:53
The Vundle README says that `filetype plugin indent on` is required at the end of your example vimrc. Does it make any difference? (commentary is no ftplugin, but I have no idea how Vundle works.)

(I assume Vundle got sourced correctly, otherwise you'd get errors with that vimrc.)

**Comment by themightyoarfish** [comment] 2016-07-24 10:00
Adding that to the minimal vimrc from above solves the issue. Trouble is, that line is in my real vimrc, but with that one it does not work. Will need to investigate further.

**Comment by fmoralesc** [comment] 2016-07-24 10:21
If the user has `filetype off`, the filetype stuff won't be enabled in nvim, perhaps vundle is interacting with that. Why would `filetype off` be required? In vanilla vim, it is never enabled before the init file is sourced, and in nvim `filetype` is set after it  is.

**Comment by Alok** [comment] 2016-07-24 21:29
@themightyoarfish Sorry if this sounds insulting, but when you say "my real vimrc", do you mean `~/.vimrc` or `~/.config/nvim/init.vim`? I don't think `nvim` sources the `~/.vim` folder by default, and it would explain your issue with `filetype plugin indent on`.

**Comment by themightyoarfish** [comment] 2016-07-25 06:12
Reasonable question; the init.vim is symlinked to .vimrc.

**Comment by mhinz** [comment] 2016-07-25 08:42
FWIW, I can't reproduce it with a similar vimrc as the one given above. `nvim -u rc` sources commentary just fine (just after `$VIMRUNTIME/filetype.vim`) and `gcc` works as well.

My steps:

```
$ cd /tmp
$ git clone https://github.com/VundleVim/Vundle.vim
$ nvim -u rc
:PluginInstall
:qa
$ nvim -u rc
iabc<esc>gcc
```

`rc`:

```
" Init Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=/tmp/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-commentary'

call vundle#end()
```

**Comment by justinmk** [comment] 2016-11-13 13:17
> The Vundle README says that filetype plugin indent on is required at the end of your example vimrc. Does it make any difference? 

Shouldn't be needed, nvim does this automatically.

And commentary.vim works for me. 

This seems like a configuration/usage issue, closing.

**Closed by justinmk** 2016-11-13 13:17 UTC
