### ISSUE TITLE
Pasting into ipython in a terminal buffer indents poorly

### ISSUE THREAD

**Issue by chrisrytting** [neovim/neovim#11928] opened 2020-02-21 21:49 UTC
This seems similar to #3476, but that issue was fixed back in 2016 so I don't think any of the workarounds there will do anything for me.

- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) gives me `E282: Cannot read from "DEFAULTS"`
- Operating system/version: MacOSX Mojave 10.14.6 
- Terminal name/version: Iterm2, Build 3.3.9
- `$TERM`: screen-256color: command not found

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```
Sorry, I'm not sure what this section expects from me. When I do `nvim -u NORC`, it just starts up nvim. Is it supposed to open a file or run a command or something? Sorry in advance if this is an obvious instruction...

### Actual behaviour
When I yank from one buffer and paste into ipython running inside a terminal buffer, the code is (a) indented weirdly and (b) every line is run before the next one is pasted.

For example:

Copying
```
def hello():
    hey = 'hello'
    print(hey)
```
from a .py file gives me
```
In [1]: def hello():
   ...:         hey = 'hello'
   ...:             print(hey)
```
in ipython in the terminal buffer.

This also happens on a different machine I use which is Ubuntu 18.04/nvim 0.2.2.
 
### Expected behaviour

When I yank from one buffer and paste into ipython running inside a terminal buffer, the code is pasted in a multi-line block that I can edit and run. 

Copying
```
def hello():
    hey = 'hello'
    print(hey)
```
from a .py file gives me
```
In [1]: def hello():
   ...:     hey = 'hello'
   ...:     print(hey)
```
in ipython in the terminal buffer.

### Attempted solutions

I have tried `:set paste` and `:set no autoindent`. This happens in any terminal I try it in, be it iterm, BYOBU on the linux machine I'm sshing into, or the native terminal on Mac.  I've tried copying and pasting using the system clipboard as well, and everytime I paste into a terminal buffer this behavior happens. 

I would really like to fix it so I can copy functions defined elsewhere into ipython and play around with them. Can you help me figure out how to fix this?

**Comment by justinmk** [comment] 2020-02-21 22:00
likely a duplicate of https://github.com/neovim/neovim/issues/11418

workaround is to paste into a buffer, then

    :%yank

then paste into the `:terminal`

**Closed by justinmk** 2020-02-21 22:00 UTC
Labels: bug, clipboard

**Comment by chrisrytting** [comment] 2020-02-21 22:25
@justinmk That doesn't work for me. The behavior is the same. The yanked text looks exactly the same in the register as it does when I copy a section of code from a .py file. 

Maybe I should clarify that I am copying from one buffer and pasting into another buffer (a terminal one) in the same vim session, so the yanked text is already in a vim register.

**Comment by justinmk** [comment] 2020-02-22 02:13
Instead of English descriptions it saves a lot of time to say exactly the keys you are typing at every step.

**Comment by bfredl** [comment] 2020-02-22 07:04
sounds like what is requested is bracketed paste support for nested  terminal.

**Comment by justinmk** [comment] 2020-02-22 21:18
In that case it's covered by https://github.com/neovim/neovim/issues/11418 as mentioned.

**Comment by chrisrytting** [comment] 2020-02-28 03:49
Sorry if I'm being unclear @justinmk. Is this better?

When I open a buffer using `:new`, press `p` in normal mode to paste the copied text into buffer as you instructed, resulting in

```
def hello():
    hey = 'hello'
    print(hey)
```
in said buffer. Then I type `:%yank` as you instructed. Then I switch to the `:terminal` and press `p` in normal mode using both `Ctrl` + `Shift` + `v` in insert mode and using `p` in normal mode, and in both cases, what is pasted is 

```
In [178]: def hello():
     ...:         hey = 'hello'
     ...:             print(hey)
```
i.e. the same thing happens as I first indicated in the first post in the issue.
