### ISSUE TITLE
Weird character issue in 0.2.2

### ISSUE THREAD

**Issue by superDuperCyberTechno** [neovim/neovim#7663] opened 2017-11-30 09:56 UTC
- `nvim --version`: 0.2.2
- Vim: Haven't tested.
- Operating system/version: Ubuntu 16.04.03
- Terminal name/version: gnome-terminal 3.18.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
No idea. Happens at random, apparently.

### Actual behaviour
Opening up Neovim (using an existing session) sometimes prints the following characters at seemingly random places in the code. This slows down machine considerably. If I scroll past the line with the offending characters, they disappear and Neovim returns to normal responsiveness.

![screenshot from 2017-11-30 10-42-54](https://user-images.githubusercontent.com/6486383/33424775-201097ca-d5bd-11e7-99ea-8ee87fe54f38.png)

### Expected behaviour
Do not screw up the characters.

![screenshot from 2017-11-30 10-44-27](https://user-images.githubusercontent.com/6486383/33424785-23928fc0-d5bd-11e7-978d-ee1d48f84407.png)

### Extras
I honestly do not know if this is actually related to Neovim or not, but I thought I'd let you know in case someone had the same issues. I just recently switched to Ubuntu, just as 0.2.2 was released, so I cannot tell you if this was a problem prior to this version.

In case it becomes relevant, here's a list of plugins I use:

```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'terryma/vim-multiple-cursors'
Plug 'Yggdroot/indentLine'
Plug 'tpope/vim-fugitive'
Plug 'junegunn/fzf.vim'
Plug 'mhinz/vim-signify'
Plug 'mattn/emmet-vim'
Plug 'w0rp/ale'
Plug 'jeetsukumaran/vim-filebeagle'
Plug 'jeetsukumaran/vim-indentwise'
Plug 'tpope/vim-eunuch'
Plug 'sheerun/vim-polyglot'
Plug 'thaerkh/vim-workspace'
Plug 'morhetz/gruvbox'
Plug 'ervandew/supertab'
Plug 'justinmk/vim-sneak'
Plug 'tomtom/tcomment_vim'
Plug 'alvan/vim-closetag'
Plug 'yuttie/comfortable-motion.vim'
Plug 'tpope/vim-surround'
Plug 'captbaritone/better-indent-support-for-php-with-html'
call plug#end()
```

**Comment by KillTheMule** [comment] 2017-11-30 10:02
Try `set guicursor=`.

**Comment by mschilli87** [comment] 2017-11-30 10:02
Note that the `":"` is not colored in the first case.
Is it always the case that if you see 'weird characters'(tm), they appear in front of an otherwise colored part of the code? If so, it could be some problem escaping the escape sequences (no pun intended).

**Comment by KillTheMule** [comment] 2017-11-30 10:07
Good thinking, see https://github.com/neovim/neovim/issues/6041#issuecomment-347872657.

**Comment by superDuperCyberTechno** [comment] 2017-11-30 10:09
The thing is, `set guicursor=` has always been a part of my init.vim.

**Comment by KillTheMule** [comment] 2017-11-30 10:17
Then you should check your `$TERM` setting, is that appropriate for `gnom-terminal`? Maybe try `gnome-256color`.

**Comment by superDuperCyberTechno** [comment] 2017-11-30 10:25
As far as I can tell from my research, gnome-terminal is supposed to be `xterm-256color`.

**Comment by KillTheMule** [comment] 2017-11-30 10:27
That might be the case, but that doesn't mean that's the correct choice afaik. Look in `/usr/share/terminfo/` for alternatives and try out (that's how I found `gnome-256color` on my machine).

**Comment by justinmk** [comment] 2017-11-30 11:30
This isn't related to 'guicursor' / cursor shaping. 

This is a duplicate of https://github.com/neovim/neovim/issues/7381

**Closed by justinmk** 2017-11-30 11:30 UTC

**Comment by KillTheMule** [comment] 2017-11-30 11:49
Ah, those "weird chars" issues confuse me. Sorry for that!
