### ISSUE TITLE
Add a option to merge the number column and sign column

### ISSUE THREAD

**Issue by toniz4** [neovim/neovim#12702] opened 2020-08-01 04:51 UTC
Vim has suport to this since the 8.1.1564 patch (https://github.com/vim/vim/releases/tag/v8.1.1564)
```
set signcolumn=number
```
In neovim the only options are: auto, yes, no

**Comment by erw7** [comment] 2020-08-01 14:28
Thanks for the request, but this is a duplicate of #12372. In addition, this feature has been ported by #12621 and is awaiting merge.

**Closed by erw7** 2020-08-01 14:28 UTC
Labels: duplicate, enhancement
