### ISSUE TITLE
Copy paste places text on different line instead of on current line

### ISSUE THREAD

**Issue by mangelozzi** [neovim/neovim#12703] opened 2020-08-01 11:17 UTC
- `nvim --version`:
```
:ver
NVIM v0.5.0-563-ge628a05b5
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict
-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto
-DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/b
uild/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/bu
ild/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/n
eovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-c5758e75-4445-4564-8946-810c98499a51
```
- Operating system/version: Windows 10 running WSL2 Ubuntu 20.04
- `$TERM`: xterm-256color

Using the win32yank.exe to handle the clipboard.

### Steps to reproduce using `nvim -u NORC`

1. `:set clipboard=unnamedplus`
2. Insert the text `one two three`
3. Press CTRL+v and select the word `two`, then press `y` to yank it.
4. Place the cursor before `two` and press `P`

### Actual behaviour
The word `two` is pasted on the line before.

### Expected behaviour
The word `two` is pasted on the current line.

### Compared to Vim
I tried the same thing in Vim, but don't understand whats going on.
`:h 'clipboard'` shows help on the clipboard option.
`:set clipboard=unnamedplus` doesnt echo an error.

However `:set clipboard` prints
`E519: Option not supported: clipboard`
and `echom &clipboard` prints blank.

So Vim behaves as expected with copy and pasting, but I suspect it might be because `clipboard` is not being set to `unnamedplus`.

**Comment by justinmk** [comment] 2020-08-30 06:44
> * Press CTRL+v and select the word `two`, then press `y` to yank it.

ctrl-v is block paste. Did you try `v` instead of ctrl-v ?

This seems like a duplicate of https://github.com/neovim/neovim/issues/1822

**Closed by justinmk** 2020-08-30 06:44 UTC
Labels: bug, needs-repro
