### ISSUE TITLE
run shell scripts in the background

### ISSUE THREAD

**Issue by mjacobus** [neovim/neovim#12060] opened 2020-03-27 15:14 UTC
Really great work guys with nvim! I am impressed on how nvim is moving fast and how I've been left behind by sticking to vim. There is only one thing up to this day preventing me from changing to nvim.

I like running my tests the way vim does, outside the editor, by basically putting the editor in background and using the terminal shell to run it. Why I like it? Because I can go back to the output with `CTRL+Z` and quickly bringing the editor back with `fg`.

Is there a way of currently doing this in nvim? Or what would be the equivalent of doing `CTRL+z` for checking the output again?

### Steps to reproduce using `nvim -u NORC`

```
1. nvim
2. `:! ls` or `:terminal ls`
3. <C+Z>
```

### Actual behaviour

No `ls` output in the terminal

### Expected behaviour

Files are listed just as if I had typed `ls` in the terminal by doing `<c-z>` `ls`.

-------

This [stackoverflow question](https://stackoverflow.com/questions/46097571/how-to-run-scripts-in-background-in-neovim) compare vim/nvim and what is the option I would love to have.

Can we please, please, pretty,  please have it? I know it is not much but I would be more than happy rewarding 100USD for whoever develops this retro-feature and gets it approved and shipped.

**Comment by bfredl** [comment] 2020-03-27 18:40
why not just use `<c-z>` also to run the command?

**Comment by mjacobus** [comment] 2020-03-27 19:10
Because the command I want to run is test files. `<leader>t` will run my test. That is super fast to type.

Doing it manually is very disruptive and renders plugins such as vim-test useless.

```
<C-Z>
./bin/rspec {hum, what is the file name again ?}... <enter>
```

**Comment by bfredl** [comment] 2020-03-27 19:13
right. but wouldn't `:terminal` cover your use case? the output ends up in a buffer so you can read it afterwards. with a bit of scripting you can send new commands to the same terminal instance.

**Comment by mjacobus** [comment] 2020-03-27 20:30
Both `:terminal` and `:!` are halfway there. I can see the output very clearly and a clean way.

```txt
 1 Run options: include {:locations=>{"./spec/koine/attributes/attributes_spec.rb"=>[83]}}                                                                                                                                                                                                                                     
 2 .                                                                                                                                                                                                                                                                                                                           
 3                                                                                                                                                                                                                                                                                                                             
 4 Finished in 0.00107 seconds (files took 0.07467 seconds to load)                                                                                                                                                                                                                                                            
 5 1 example, 0 failures                                                                                                                                                                                                                                                                                                       
 6                                                                                                                                                                                                                                                                                                                             
 7                                                                                                                                                                                                                                                                                                                             
 8 [Process exited 0]    
```

I don't need to run it in the same terminal. In fact, once I run a test I don't care about the previous test message. As you can see in the output, once I hit a key, the output is gone and I cannot quickly reopen it, so I can read it once again.

If there is a way of opening last terminal output in full screen and go back to my code with just an few key strokes as I do with `<c-z>` and `fg` I probably don't need this proposed feature.

**Comment by mjacobus** [comment] 2020-03-27 20:38
Related, I think: https://github.com/neovim/neovim/issues/2229

**Comment by mjacobus** [comment] 2020-03-27 21:04
Also, `:terminal` does not seem to be as efficient as terminal itself to interrupt processes.

**Comment by mjacobus** [comment] 2023-08-02 19:24
Another reason why the old vim behavior was powerful - being able to run a command in the terminal by putting the editor in the background - is seeing the output in full terminal size, regardless of how many splits.



![image](https://github.com/neovim/neovim/assets/226834/c382d873-1ad9-4f9c-8fa5-0927ee33152c)

![image](https://github.com/neovim/neovim/assets/226834/ecb8d076-3377-4798-90d4-fa88d17bc618)


The `:term` behaviour will make the output fit to the buffer size, and it does not handle line breaks very well...


![image](https://github.com/neovim/neovim/assets/226834/6a9c5c2a-7215-4ba5-8610-30e415238d07)




Copy and paste of the lines:

```
 _____________________________
____________ 
/ Hello nvim community, how ar
e you folks \
\ doing today?                
            /
 -----------------------------
------------ 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[Process exited 0]
```

**Comment by justinmk** [comment] 2023-08-02 20:40
This is a LOT of words to say what is essentially https://github.com/neovim/neovim/issues/1496 (duplicate of https://github.com/neovim/neovim/issues/1716 ) . 

But probably https://github.com/neovim/neovim/issues/3439 would address this.

**Closed by justinmk** 2023-08-02 20:40 UTC
Labels: enhancement
