### ISSUE TITLE
./runtime/lua/vim/lsp/sync.lua:66: index out of range when using v_g_CTRL-A

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#16280] opened 2021-11-11 02:39 UTC
### Neovim version (nvim -v)

0.6.0 commit 14def4d

### Language server name/version

texlab 3.3.0

### Operating system/version

Arch Linux

### :checkhealth

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: texlab: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: **/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - INFO: Build type: Debug
  - WARNING: Non-optimized (DEBUG) build. Nvim will be slower.
    - ADVICE:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'
```

### Steps to reproduce using "nvim -u minimal_init.lua"

This is `/tmp/minimal_init.lua`:
```lua
vim.lsp.set_log_level('trace')
require('vim.lsp.log').set_format_func(vim.inspect)
vim.cmd([[set rtp+=~/.local/share/nvim/site/pack/packer/start/nvim-lspconfig]])
require('lspconfig').texlab.setup({})
```

This is `/tmp/tmp.tex`:
```tex
\begin{document}
\section*{1}
\section*{1}
\section*{1}
\end{document}
```

1. Run `VIMRUNTIME=./runtime ./build/bin/nvim -u /tmp/minimal_init.lua /tmp/tmp.tex`
2. Press `3gg$h<C-V>jg<C-A>`

### Expected behavior

No errors.

### Actual behavior

```
Error executing lua callback: ./runtime/lua/vim/lsp/sync.lua:66: index out of range
stack traceback:
        [C]: in function 'str_utfindex'
        ./runtime/lua/vim/lsp/sync.lua:66: in function 'byte_to_utf'
        ./runtime/lua/vim/lsp/sync.lua:100: in function 'align_position'
        ./runtime/lua/vim/lsp/sync.lua:222: in function 'compute_end_range'
        ./runtime/lua/vim/lsp/sync.lua:351: in function 'compute_diff'
        ./runtime/lua/vim/lsp.lua:366: in function 'incremental_changes'
        ./runtime/lua/vim/lsp.lua:384: in function 'fn'
        ./runtime/lua/vim/lsp.lua:163: in function 'for_each_buffer_client'
        ./runtime/lua/vim/lsp.lua:1084: in function <./runtime/lua/vim/lsp.lua:1076>
```

### Log file

https://gist.github.com/zeertzjq/ca5d027a6c7486dd6c51a3afbfc1e70a

**Comment by mjlbach** [comment] 2021-11-11 02:43
Duplicate of https://github.com/neovim/neovim/issues/16274, please use the tracking issue.

**Closed by mjlbach** 2021-11-11 02:43 UTC
Labels: bug, bug-regression, lsp
