### ISSUE TITLE
inlay_hint: "Failed to delete autocmd" error when closing a buffer

### ISSUE THREAD

**Issue by MariaSolOs** [neovim/neovim#24456] opened 2023-07-23 22:35 UTC
### Problem

With the latest nightly release, I'm seeing the following error every time I close a buffer:

<img width="1192" alt="image" src="https://github.com/neovim/neovim/assets/62502207/9f0a1266-2ef7-4259-8acf-c24c32d363ce">

So far I've seen this happen with Lua and Rust files.

Note that this doesn't happen with NVIM v0.10.0-dev-692+g86ce3878d.

### Steps to reproduce

The only inlay-hint related setup I have is this pair of autocommands that toggles inlay hints:
```lua
    if buf_client.supports_method 'textDocument/inlayHint' then
        local inlay_hints_group = vim.api.nvim_create_augroup('ToggleInlayHints', { clear = false })

        -- Initial inlay hint display.
        local mode = vim.api.nvim_get_mode().mode
        vim.lsp.inlay_hint(bufnr, mode == 'n' or mode == 'v')

        vim.api.nvim_create_autocmd('InsertEnter', {
            group = inlay_hints_group,
            buffer = bufnr,
            callback = function()
                vim.lsp.inlay_hint(bufnr, false)
            end,
        })
        vim.api.nvim_create_autocmd('InsertLeave', {
            group = inlay_hints_group,
            buffer = bufnr,
            callback = function()
                vim.lsp.inlay_hint(bufnr, true)
            end,
        })
    end
```
The rest of my LSP configuration is [here](https://github.com/MariaSolOs/dotfiles/blob/d0c27368177b1ca78d79843824e9d54f565e94ba/.config/nvim/lua/helpers/lsp.lua).

### Expected behavior

For there to be no error.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-709+gce56ad2ba

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Mac Ventura 13.4.1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

bob

**Comment by MariaSolOs** [comment] 2023-07-23 22:44
This seems to have been caused by #24411. Moreover, I'm not the only one seeing this error, see https://github.com/DNLHC/glance.nvim/pull/57

**Comment by MariaSolOs** [comment] 2023-07-24 04:37
As extra information: I discovered that this happens with always happens when using `bwipeout`, but not with `bdelete` (at least I haven't seen it happen yet). This kind of explains the error since the former removes the buffer-local autocommands.

**Comment by justinmk** [comment] 2023-07-24 14:37
@catlee

**Comment by catlee** [comment] 2023-07-24 15:58
I'm having some problems reproducing this. It doesn't happen all the time, I wonder if there's something racing between `bwipeout` deleting buffer-local autocommands and the disable() function trying to delete the autocommands as well.

When trying to debug this, I discovered that we are calling `nvim_buf_attach` each time the inlay hints are enabled. This results in many callbacks being registered on the buffer, and so `disable` is called multiple times when closing the buffer.

This is a result of my previous PR which removed the `enabled` field from the internal inlay_hint state table.

I think we need to re-introduce that field, since there doesn't seem to be another way to track when we've registered buffer event handlers, nor is there a way to un-register them?

**Comment by justinmk** [comment] 2023-07-24 16:01
> since there doesn't seem to be another way to track when we've registered buffer event handlers, nor is there a way to un-register them?

To unregister a particular handler one would need to remember the id returned by `nvim_create_autocmd()`

**Comment by MariaSolOs** [comment] 2023-07-24 16:18
@catlee thank you for looking into it! If it helps, I could always reproduce it with this command [here](https://github.com/MariaSolOs/dotfiles/blob/d0c27368177b1ca78d79843824e9d54f565e94ba/.config/nvim/lua/plugins/bufferline.lua#L28).

**Comment by catlee** [comment] 2023-07-24 17:34
> > since there doesn't seem to be another way to track when we've registered buffer event handlers, nor is there a way to un-register them?
> 
> To unregister a particular handler one would need to remember the id returned by `nvim_create_autocmd()`

I'm referring to the buffer callbacks here: https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/inlay_hint.lua#L153.

After setting up `on_detach` / `on_reload` callbacks, there doesn't seem to be a way to un-register them.

**Comment by catlee** [comment] 2023-07-24 17:52
> @catlee thank you for looking into it! If it helps, I could always reproduce it with this command [here](https://github.com/MariaSolOs/dotfiles/blob/d0c27368177b1ca78d79843824e9d54f565e94ba/.config/nvim/lua/plugins/bufferline.lua#L28).

Thanks. It only reproduces for me when I have multiple buffers open.

**Comment by justinmk** [comment] 2023-07-24 17:54
`:help nvim_buf_detach()` mentions `:help api-lua-detach`: 

```
In-process Lua callbacks can detach by returning `true`. This will detach all
callbacks attached with the same |nvim_buf_attach()| call.
```

I almost missed that 😅

**Comment by catlee** [comment] 2023-07-24 19:08
> `:help nvim_buf_detach()` mentions `:help api-lua-detach`:
> 
> ```
> In-process Lua callbacks can detach by returning `true`. This will detach all
> callbacks attached with the same |nvim_buf_attach()| call.
> ```
> 
> I almost missed that 😅

Thanks, that's good to know. I'm not sure how I can use that in this case.

The current code ends up calling `nvim_buf_attach` every time inlay hints are enabled. If the user toggles hints on/off multiple times without triggering the `on_detach` or `on_reload` buffer events, then we end up registering the callbacks multiple times.

**Closed** 2023-08-01 12:13 UTC
Labels: bug, lsp
