### ISSUE TITLE
Emoji "⚠️" hides next character

### ISSUE THREAD

**Issue by bonsairobo** [neovim/neovim#24653] opened 2023-08-10 20:02 UTC
### Problem

When I paste the ⚠️ emoji into a buffer, the following character is always hidden/missing. I've tried pasting the same string into the shell in my terminal emulator (fish and kitty), and I cannot reproduce the issue, which leads me to believe it is not a font or terminal emulator issue, but an issue specific to neovim. I've also tried reproducing in VSCode, but it renders as expected.

### Steps to reproduce

```
nvim --clean
enter insert mode
"⚠️"
```

See that the 2nd quote is missing.

### Expected behavior

The 2nd quote should be rendered after the ⚠️.

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

yes, vim 9.0

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.29.2

### $TERM environment variable

xterm-kitty

### Installation

pacman (system package manager)

**Comment by bonsairobo** [comment] 2023-08-10 20:06
Might be a duplicate of #7151? I'm not knowledgeable enough about emojis/unicode to say.

**Comment by zeertzjq** [comment] 2023-08-10 21:09
Duplicate of #7151

**Closed by zeertzjq** 2023-08-10 21:09 UTC
Labels: bug
