### ISSUE TITLE
layout error

### ISSUE THREAD

**Issue by Liameternal** [neovim/neovim#17750] opened 2022-03-17 05:39 UTC
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

no, vim 8.2.3995

### Operating system/version

5.16.0-kali3-amd64

### Terminal name/version

xterm 371

### $TERM environment variable

screen-256color

### Installation

apt-get

### How to reproduce the issue

- step1: nvim --clean [ACL_file](https://raw.githubusercontent.com/Liameternal/ACL/main/ACL4SSR_Online_Full.ini)
- step2: :set nu, which will look normal
![normal](https://user-images.githubusercontent.com/25942745/158744132-ce811a56-81c4-4f51-b8cd-e98c7cc5a951.png)
- step3: strike key G and then gg, the bug will appear
![bugs](https://user-images.githubusercontent.com/25942745/158744146-c91f247f-e1c2-45c2-88df-2289f251dd21.png)
.

### Expected behavior

just as the normal pic shows

### Actual behavior

as the bugs pic shows

**Comment by zeertzjq** [comment] 2022-03-17 05:42
Duplicate of #7151

**Closed by zeertzjq** 2022-03-17 05:42 UTC
Labels: bug
