### ISSUE TITLE
Running `:botright copen` copies window shading in the created quickfix window (just `:copen` doesn't)

### ISSUE THREAD

**Issue by pianocomposer321** [neovim/neovim#24043] opened 2023-06-17 02:06 UTC
### Problem

When creating a new window, the shading (background color etc.) is copied from the current window. This is normal. However, this normally does not apply to the quickfix list (i.e., the window created by `:new` will have the same shading as the window it was called from, but the window created by `:copen` won't). However, when I instead do `:botright copen`, the created quickfix list does have the shading of the window that it was called from.

This seems unexpected to me... It makes sense to me for the quickfix list to never copy the shading of the window it was created from, and just always follow the colorscheme. But in any case, it doesn't make much sense (to me anyway) for this particular behavior to change when the command is called using `:botright`.

Note: I ran into this issue when using [toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim), so the window I created the quickfix list from was a toggleterm terminal. I haven't tested with another window with the background color changed, because I'm not sure how to do that :smile:. It's possible this is a toggleterm issue, but I don't think so.

### Steps to reproduce

1. Open neovim
2. Run :ToggleTerm
3. Run :copen

The quickfix list will be colored like normal.

1. Open neovim
2. Run :ToggleTerm
3. Run :botright copen

The quickfix list will be colored like the terminal window.

### Expected behavior

See above.

### Neovim version (nvim -v)

NVIM v0.8.2

### Vim (not Nvim) behaves the same?

I don't know, toggleterm doesn't run on vim

### Operating system/version

KDE Neon 5.27

### Terminal name/version

Kitty

### $TERM environment variable

screen

### Installation

Installed .deb from releases page

**Comment by zeertzjq** [comment] 2023-06-17 04:00
Duplicate of #18283

**Closed by zeertzjq** 2023-06-17 04:00 UTC
Labels: bug

**Comment by pianocomposer321** [comment] 2023-06-17 15:57
@zeertzjq Are you sure this is a duplicate? The differentiating factor in https://github.com/neovim/neovim/issues/18283 is that the original window is a floating window, but here it isn't. The thing that makes a difference is the use of `:botright`, which isn't mentioned at all in the other issue.

I wouldn't be surprised if the issues are related, but they aren't caused by the same thing as far as I can tell...
