### ISSUE TITLE
Tilde (~) behaves as empty string in substitution when inccomand=nosplit

### ISSUE THREAD

**Issue by saulaxel** [neovim/neovim#17193] opened 2022-01-25 05:41 UTC
### Neovim version (nvim -v)

NVIM v0.6.0

### Vim (not Nvim) behaves the same?

Vim 8.2.42.12 doesn't seem to have inccomand and it works fine. It also works fine in neovim if inccomand is set to empty

### Operating system/version

Kubuntu 20.04.1-Ubuntu Linux 5.11.0-46-generic x86_64 x86_64

### Terminal name/version

Konsole 19.12.3

### $TERM environment variable

xterm-256color

### Installation

Downloaded the appimage

### How to reproduce the issue

nvim --clean
ione two<Esc>
:s/one/changed
:s/two/~

### Expected behavior

The text "two" should be replaced by "changed" since "\~" is documented to mean "last given substitute string" in help /~. It works if I "set inccomand=".

### Actual behavior

"two" is replaced by an empty string

**Comment by zeertzjq** [comment] 2022-01-25 05:55
Duplicate of #12109

**Closed by zeertzjq** 2022-01-25 05:55 UTC
Labels: bug
