### ISSUE TITLE
Strange bug with neovim and urxvt: Seems like something is running "rg" on startup

### ISSUE THREAD

**Issue by lervag** [neovim/neovim#26295] opened 2023-11-29 08:04 UTC
### Problem

I regularly build neovim from Git (through the `neovim-git` package on Arch). Recently I've had a strange issue where it seems on startup that there's a rouge `rg` being issued.

I did a `git bisect` to find that the commit that introduces this problem for me is ab102f188e86bdbfce1d4de2ef633092a906e8fe (by @gpanders).

I can't reproduce this problem with `xterm`.

### Steps to reproduce

* Given a simple `test.txt` with only the word "ABCD" on the first line.
* I open `urxvt`
* I run `nvim --clean test.txt`
* I observe that the buffer contains "gBCD" and that it is changed (as shown in screenshot below)

![image](https://github.com/neovim/neovim/assets/998898/98debdfe-6ae4-407c-82a8-b6e7f062f68a)

### Expected behavior

Buffer is not changed on start.

### Neovim version (nvim -v)

0.10.0 ab102f188e86bdbfce1d4de2ef633092a906e8fe

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

urxvt v9.31

### $TERM environment variable

rxvt-256color

### Installation

build from repo

**Comment by zeertzjq** [comment] 2023-11-29 08:12
`neovim-git` package is not "build from repo" as it uses external dependencies. Try `neovim-nightly-bin`.

**Comment by lervag** [comment] 2023-11-29 08:14
Sorry; I use `neovim-git` for daily use, but I also built directly from source during `git bisect`.

**Comment by zeertzjq** [comment] 2023-11-29 08:23
Oh, I can reproduce this using Nvim built from source.

**Comment by zeertzjq** [comment] 2023-11-29 08:35
This will fix the problem if you build from source:
```diff
diff --git a/runtime/lua/vim/_defaults.lua b/runtime/lua/vim/_defaults.lua
index 09d6d43e7..e49ae3d49 100644
--- a/runtime/lua/vim/_defaults.lua
+++ b/runtime/lua/vim/_defaults.lua
@@ -280,7 +280,7 @@ do
       end,
     })
 
-    io.stdout:write('\027]11;?\027\\')
+    io.stdout:write('\027]11;?\a')
 
     timer:start(1000, 0, function()
       -- No response received. Delete the autocommand
```

But it will not fix the problem for `neovim-git` because it uses external dependencies.

**Comment by lervag** [comment] 2023-11-29 09:48
> This will fix the problem if you build from source:
> 
> …
> 
> But it will not fix the problem for `neovim-git` because it uses external dependencies.

Cool, thanks. Would you propose this as a fix for the current issue?

I don't quite understand why this would not fix the problem for [`neovim-git`](https://aur.archlinux.org/packages/neovim-git), though.

**Comment by gpanders** [comment] 2023-11-29 14:58
> This will fix the problem if you build from source:
> 
> ```diff
> diff --git a/runtime/lua/vim/_defaults.lua b/runtime/lua/vim/_defaults.lua
> index 09d6d43e7..e49ae3d49 100644
> --- a/runtime/lua/vim/_defaults.lua
> +++ b/runtime/lua/vim/_defaults.lua
> @@ -280,7 +280,7 @@ do
>        end,
>      })
>  
> -    io.stdout:write('\027]11;?\027\\')
> +    io.stdout:write('\027]11;?\a')
>  
>      timer:start(1000, 0, function()
>        -- No response received. Delete the autocommand
> ```
> 
> But it will not fix the problem for `neovim-git` because it uses external dependencies.

So this sounds like a urxvt bug that it only accepts BEL and not ST as a terminator?

If we apply this patch then we will see a lot more instances of https://github.com/neovim/neovim/issues/26038 happen, because now _all_ terminals will respond with the BEL terminator and anyone (regardless of terminal emulator) not using the updated/bundled libtermkey will have that problem.

**Comment by lervag** [comment] 2023-11-29 21:12
> @lervag That issue is the same as #26038. It is caused by a bug in one of our dependencies (libtermkey). The vendored/bundled version of libtermkey has been updated, but not "official" release has been made yet, so using the version from the package manager will still have that issue.

Ah, I see. And thanks for the explanation. It does bring a couple of questions though. First, do I understand correctly that, since I'm currently relying on the `neovim-git` version from Arch AUR, I will have to wait until an official release of libtermkey? Or is there some way of relying on a bundled and more up-to-date version of libtermkey?

> > This will fix the problem if you build from source:
> > ```diff
> > diff --git a/runtime/lua/vim/_defaults.lua b/runtime/lua/vim/_defaults.lua
> > index 09d6d43e7..e49ae3d49 100644
> > --- a/runtime/lua/vim/_defaults.lua
> > +++ b/runtime/lua/vim/_defaults.lua
> > @@ -280,7 +280,7 @@ do
> >        end,
> >      })
> >  
> > -    io.stdout:write('\027]11;?\027\\')
> > +    io.stdout:write('\027]11;?\a')
> >  
> >      timer:start(1000, 0, function()
> >        -- No response received. Delete the autocommand
> > ```
> > 
> > But it will not fix the problem for `neovim-git` because it uses external dependencies.
> 
> So this sounds like a urxvt bug that it only accepts BEL and not ST as a terminator?

:shrug: I don't know these things :)

**Comment by lervag** [comment] 2023-11-29 21:17
> My theory is that st is sending the OSC 11 response terminated with BEL (0x07) instead of ST (0x1b 0x5c) as it should be. We learned recently that libtermkey https://github.com/neovim/libtermkey/pull/4, so if my theory is correct what is likely happening is that st is sending us the OSC 11 response and it is not being interpreted correctly by termkey as an OSC sequence. Thus, it never gets sent in the TermResponse autocommand and is instead treated like regular terminal input, where it then appears in Nvim.

@gpanders If I understand correctly, you mean that your theory for `st` also holds for `urxvt`? If so, then I could attempt to verify this by following the steps you outlined.

**Comment by zeertzjq** [comment] 2023-11-29 21:52
No. `urxvt` has a different bug than `st`.

**Comment by gpanders** [comment] 2023-11-29 21:54
> > My theory is that st is sending the OSC 11 response terminated with BEL (0x07) instead of ST (0x1b 0x5c) as it should be. We learned recently that libtermkey [neovim/libtermkey#4](https://github.com/neovim/libtermkey/pull/4), so if my theory is correct what is likely happening is that st is sending us the OSC 11 response and it is not being interpreted correctly by termkey as an OSC sequence. Thus, it never gets sent in the TermResponse autocommand and is instead treated like regular terminal input, where it then appears in Nvim.
> 
> @gpanders If I understand correctly, you mean that your theory for `st` also holds for `urxvt`? If so, then I could attempt to verify this by following the steps you outlined.

No, urxvt seems to have a different problem altogether. I can't run urxvt locally to verify, so I'm only going off of what @zeertzjq suggested, but it _seems_ like urxvt doesn't recognize ST (`\e\\`) as a valid terminator, but it does accept BEL (`\a`).

You can very easily verify this yourself though. In urxvt enter `printf '\e]11;?\e\\'` in your shell and let me know what it spits back. Then do the same with but with `printf '\e]11;?\a'` (note the different terminator).

**Comment by zeertzjq** [comment] 2023-11-30 00:55
`urxvt`'s response is missing a backslash when query ends with ST.

**Comment by aikow** [comment] 2023-11-30 06:43
Not sure how helpful this is, but I'm getting a very similar issue when using tmux on a remote server via the ssh kitten. It doesn't happen when using kitty locally, or when using tmux in kitty locally, or when using regular ssh, or when just using the ssh kitten. This is using the latest nightly build.

**Comment by gpanders** [comment] 2023-11-30 12:54
@lervag Thanks. Your screenshot confirms what @zeertzjq also said, urxvt is not including the `\` character in its reply, so libtermkey is not interpreting the reply as an OSC sequence. Instead, the whole reply is treated as regular input. As in, Neovim thinks you are literally typing the keys `11;rgb`. The `rg` in that string is what’s responsible for that `g` character replacing the `A` in `ABCD`.

**Comment by gpanders** [comment] 2023-11-30 12:57
This is certainly a urxvt bug. Our choices are:

1. Do nothing and wait for urxvt to fix their bug
2. Change the terminator in our query to BEL, which will cause problems everywhere that isn’t using our patched version of libtermkey, until a new version is released and distros upgrade

**Comment by lervag** [comment] 2023-11-30 14:21
> This is certainly a urxvt bug. Our choices are:
> 
> 1. Do nothing and wait for urxvt to fix their bug

Does this imply that I (and other neovim + urxvt users) would be prevented from using any neovim version that includes the commit ab102f188e86bdbfce1d4de2ef633092a906e8fe until the bug is fixed in urxvt? Or would I somehow find the issue to be resolved after updates to libtermkey?

> 2. Change the terminator in our query to BEL, which will cause problems everywhere that isn’t using our patched version of libtermkey, until a new version is released and distros upgrade

This does not sound like a good choice.

I'm curious, though; this issue first appeared after ab102f188. So, that refactoring did break things for several users, me included. I wonder if it may be worth considering to revert this change? Or, alternatively, add someway to avoid the autocommand altogether?

**Comment by clason** [comment] 2023-11-30 14:24
Don't forget that the main issue here is that urxvt does not implement OSC correctly (while many others do), so I don't think reverting is really called for.

**Comment by gpanders** [comment] 2023-11-30 14:31
>So, that refactoring did break things for several users, me included. I wonder if it may be worth considering to revert this change? Or, alternatively, add someway to avoid the autocommand altogether?

Reverting is _an_ option, but not one that I am in favor of. Generally speaking, we (as in Neovim, the project) want to write our code in a way that is best for us (the maintainers) and our users. https://github.com/neovim/neovim/commit/ab102f188e86bdbfce1d4de2ef633092a906e8fe is undoubtedly a win from a maintenance and "code cleanliness" perspective. It _has_ caused issues for users, but all of these issues are bugs caused by the broader ecosystem, which https://github.com/neovim/neovim/commit/ab102f188e86bdbfce1d4de2ef633092a906e8fe has helped to uncover. The change itself is correct from Neovim's perspective.

Reverting https://github.com/neovim/neovim/commit/ab102f188e86bdbfce1d4de2ef633092a906e8fe allows those bugs to creep back into their dark holes and linger longer. Eventually, they will pop up again and bother someone else. The right course of action is to fix the bugs.

> > This is certainly a urxvt bug. Our choices are:
> > 
> > 1. Do nothing and wait for urxvt to fix their bug
> 
> Does this imply that I (and other neovim + urxvt users) would be prevented from using any neovim version that includes the commit [ab102f1](https://github.com/neovim/neovim/commit/ab102f188e86bdbfce1d4de2ef633092a906e8fe) until the bug is fixed in urxvt?

That's correct. This would of course be unpleasant for urxvt users, but I want to stress that **the unpleasantness comes from a urxvt bug, not a Neovim bug**.

> 
> > 2. Change the terminator in our query to BEL, which will cause problems everywhere that isn’t using our patched version of libtermkey, until a new version is released and distros upgrade
> 
> This does not sound like a good choice.

We will not release a new version of Neovim without some kind of plan to distribute these patches to libtermkey. Option 2 is most likely what we will end up doing.

**Comment by gpanders** [comment] 2023-11-30 17:42
There's nothing actionable here for Neovim, so I'm going to close. For future readers with the same problem, keep an eye out for a new urxvt release.

**Comment by lervag** [comment] 2023-11-30 17:54
I've reached out to the maintainer of rxvt-unicode and asked if it may be possible for him to make another release that includes the fix.

**Comment by zeertzjq** [comment] 2023-11-30 21:16
With #25870 merged this may be reconsidered.

**Comment by clason** [comment] 2023-11-30 21:28
No. Urxvt is still doing it wrong.

**Comment by bfredl** [comment] 2023-11-30 21:40
I don't think we should add workarounds in neotermkey for bugs in terminal emulatators which has been _fixed_. Is this known to be a bug anywhere else? otherwise recommend closed-as-fixed.

**Comment by zeertzjq** [comment] 2023-11-30 21:44
It's not a workaround and not in libtermkey. It's restoring old behavior.

**Comment by clason** [comment] 2023-11-30 21:46
You mean changing behavior to only use BEL is "restoring old behavior"? This is certainly some doublespeak I am not familiar with.

**Comment by gpanders** [comment] 2023-11-30 21:54
Yes, in the C implementation of requesting the background color we used BEL. Using BEL in the Lua implementation is fine. The argument against it earlier was the libtermkey bug, but now that that is vendored there isn't a reason not to do it.

**Comment by bfredl** [comment] 2023-11-30 21:55
yes, fixes in Nvim to behave correctly may expose bugs in other software. if urxvt would have _disagreed_ there was a bug on their end there might be a story here. but this sounds like a non-story.

**Comment by zeertzjq** [comment] 2023-11-30 21:58
There is nothing incorrect with the old v0.9 behavior.

**Closed** 2023-11-30 22:17 UTC
Labels: status:blocked-external, defaults, tui
