### ISSUE TITLE
Neovim becomes unresponsive with 100% CPU when pressing G on a large HTML file

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#14150] opened 2021-03-17 04:40 UTC
- `nvim --version`: `v0.5.0-dev+1152-gf5daf55c1`
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Ubuntu 20.04.2
- Terminal name/version: Konsole 19.12.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Download `plotly_graph.html` by clicking `DOWNLOAD HTML` at https://plotly.com/python/interactive-html-export/.

Attached here:
[plotly_graph.zip](https://github.com/neovim/neovim/files/6153772/plotly_graph.zip)

```
nvim -u NORC plotly_graph.html
```

Type `G` to go to the end of the document.

### Actual behaviour

Neovim becomes unresponsive with 100% CPU utilization.

### Expected behaviour

Neovim would move the cursor to the end of the document.

**Comment by matveyt** [comment] 2021-03-30 15:35
Syntax highlighting is known to be slow on large files. You're adviced to switch it off: `:e +set\ syntax=off plotly_graph.html`.

BTW. Original Vim seems to perform a little better, so `:e +setl\ synmaxcol=150 plotly_graph.html` is kind of tolerable. Still far from good.

**Comment by dstein64** [comment] 2021-03-30 16:31
> "BTW. Original Vim seems to perform a little better..."

I encounter a substantial time difference between Vim and Neovim in this scenario. Vim takes less than 2 seconds to move the cursor to the end of the document after pressing `G`, whereas Neovim takes 4 minutes and 50 seconds (followed by the message `'redrawtime' exceeded, syntax highlighting disabled`). I'm unable to cancel the operation with `<ctrl-c>`, and have to kill the process to avoid waiting.

**Comment by glacambre** [comment] 2021-06-10 17:22
@dstein64 are you using the appimage? If yes, could you try to compile neovim from source and see if it's still slow?

The reason I'm asking this is that I noticed that the appimage is super slow, but a neovim compiled from source isn't. I profiled both and it turns out that what's taking the majority of the time is memcpy - and the the reason the appimage is so much slower than the native version is that the the native version uses AVX instructions while the appimage doesn't (and this is because the appimage is supposed to be portable, so you can't use instructions that possibly don't exist on the user's computer). I'm quite blown away by this discovery.

**Comment by dstein64** [comment] 2021-06-11 04:32
Thanks for looking into this @glacambre!

I confirmed that compiling from source does not exhibit the problem reported here.

I extracted the contents of the appimage with `./nvim.appimage --appimage-extract`. Calling `ldd` on `squashfs-root/usr/bin/nvim` shows `libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6`, which matches what is output when I call `ldd` on the `nvim` binary I compiled. Calling `nm -g -C ./nvim  | grep memcpy` on each of the binaries also shows the same output for undefined symbols `__memcpy_chk@@GLIBC_2.3.4` and `memcpy@@GLIBC_2.14`.

My interpretation of this output is that both binaries are dynamically linked and use the same C standard library implementation, and would consequently use the same implementation of `memcpy`. How did you confirm that the appimage is using a different implementation of `memcpy`?

**Comment by glacambre** [comment] 2021-06-11 05:36
@dstein64 I looked at perf recordings - in the native case memcpy had multiple entries for avx-related instructions and it didn't for the appimage. It could just be missing symbols, but I'm not sure what else could cause memcpy to be orders of magnitude slower.

**Comment by dstein64** [comment] 2021-06-13 01:53
I noticed that the issue is not specifically related to appimages. That is, for the task reported in this ticket, the appimage for 0.4.4 works fine, and the non-appimage nightly release version, `nvim-linux64.tar.gz`, works slow.

I profiled the nightly release versus the version I compiled locally and found that the [call](https://github.com/neovim/neovim/blob/141647cfbb1f137e3eefe6ba8e658b475e902cac/src/nvim/memory.c#L369) to `strlen` in `memory.c::xstrlcpy` is the hot spot on the nightly release.

I believe the slow-down for the nightly release arises from an older version of gcc being used when compiling the nightly release. Ubuntu 18.04 used for the GitHub Actions task uses gcc-7 by default. For `gcc<10`, when `-Og` is used (which it is for the nightly releases), the call to `strlen` is compiled to `repnz scasb`, whereas `gcc>=10` compiles to `call strlen`, which would use a dynamically linked optimized version of that function (e.g., using AVX2 instructions) from the C standard library. I used a newer gcc locally, so I did not encounter the slowdown, although I did after attempting a build with gcc-9. I think the appimage release version of 0.4.4 would not have the slowdown since `-Og` was not used for the release build, and `repnz scasb` would not have been used for `strlen`.

If that's the correct explanation, a workaround for the issue reported in this ticket could be to switch from using gcc-7 to using gcc-10, gcc-11, or clang.

**Comment by glacambre** [comment] 2021-06-13 05:05
It looks like the appimage is built on ubutun 18.04:

https://github.com/neovim/neovim/blob/141647cfbb1f137e3eefe6ba8e658b475e902cac/.github/workflows/release.yml#L45-L47

And that version of ubuntu doesn't have GCC-10:

https://repology.org/project/gcc/versions

I believe we can't upgrade the machines building the appimages as appimages require old libcs in order to be portable. Perhaps passing `--fno-builtin-function` would be enough to prevent gcc from using its own strlen?

**Comment by dstein64** [comment] 2021-06-13 06:15
> "And that version of ubuntu doesn't have GCC-10:"

`apt-get install gcc-11` works for installing `gcc-11` on the GitHub Actions Ubuntu 18.04 virtual machines, which have the https://launchpad.net/~ubuntu-toolchain-r/+archive/test repository enabled by default. According to the [Ubuntu Wiki](https://wiki.ubuntu.com/ToolChain#PPA_packages), that PPA has updated toolchain packages.

> "Perhaps passing --fno-builtin-function would be enough to prevent gcc from using its own strlen?"

A quick test on [Compiler Explorer](https://godbolt.org/) suggests that `-fno-builtin-strlen` results in gcc-7 using an external `strlen` (`call strlen` instead of the `repnz scasb` version).

**Comment by jamessan** [comment] 2021-06-17 02:17
This should be fixed with the next nightly.

**Closed by jamessan** 2021-06-17 02:17 UTC
Labels: bug

**Comment by glacambre** [comment] 2021-06-17 05:32
I can confirm that this is fixed on nightly :).

**Comment by dstein64** [comment] 2021-06-17 05:41
I also just confirmed the reported problem is resolved when using either the nightly appimage (`nvim.appimage`) or the Linux archive (`nvim-linux64.tar.gz`).

Thanks again @glacambre!

**Comment by clason** [comment] 2022-08-09 16:05
@dstein64 @glacambre could you do me a favor and test the releases from https://github.com/clason/neovim/actions/runs/2826516457

(We have to update the GHA runners doing the release to Ubuntu-20.04 which ships with GCC 10.3.0, so I'm testing builds with that; if those don't run into this issue, we can avoid pulling in `gcc-11`.)

**Comment by glacambre** [comment] 2022-08-09 17:25
@clason Your appimage, the 0.7.0 appimage and the 0.7.0 non-appimage build all seem to take roughly ~12 seconds to open the file + scroll down using `G`. I can't remember what the original timings were unfortunately, but I'd be willing to assume the problem hasn't come back :)

**Comment by dstein64** [comment] 2022-08-09 17:44
GCC 10 did not have the issue in my initial experiments:
https://github.com/neovim/neovim/issues/14150#issuecomment-860138124

@glacambre, the original timing, assuming you're using the same file, was 4 minutes and 50 seconds:
https://github.com/neovim/neovim/issues/14150#issuecomment-810405305

**Comment by clason** [comment] 2022-08-09 19:18
Sounds like I did not introduce a regression, then. Thank you both!

**Comment by garyhellman** [comment] 2022-08-11 17:01
/lib64/libm.so.6: version `GLIBC_2.29' not found
was working fine yesterday --- now nightly does not work (on linux RHEL)
bummer

**Comment by clason** [comment] 2022-08-11 17:03
Yes, that is (now) explicitly documented (see "Following HEAD" and the pinned issue).

It's an unavoidable consequence of Github deprecating the Ubuntu 18.04 runner; nothing we can do about it. 

(_You_ can do something about it, though: build Neovim yourself from source.)

**Comment by garyhellman** [comment] 2022-08-11 17:05
ok - thanks - i'll try that :)
