### ISSUE TITLE
v:register incorrectly persists into the next command

### ISSUE THREAD

**Issue by svermeulen** [neovim/neovim#11202] opened 2019-10-11 06:22 UTC
- `nvim --version`: 0.4.2
- `vim -u DEFAULTS` (version: ) behaves differently?  No.  This issue exists in Vim too.
- Operating system/version: Mac OSX 10.14.6
- Terminal name/version: Mac Terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
:nnoremap <space>r :echom v:register<cr>

- Open a file with some contents
- Execute any delete operation and specify a register (eg. `"adw`)
- Execute `<space>r`
```

### Actual behaviour

The value for `v:register` given to the `<space>r` command is still whatever register was given to the previous command

### Expected behaviour

The value for `v:register` should be the default (`"`)

I reported this to bram many years ago and he confirmed it as a bug but argued that it was not worth fixing.

In case you're wondering what the use case is:
I'm seeing it because I have a custom paste operation that uses v:register and I also use the mapping `nnoremap d "_d`.  So I see this every time I do a paste (without specifying a register) immediately following a delete.

**Comment by bfredl** [comment] 2019-10-11 09:55
I think is the relevant code, the condition for resetting looks very strict:
```
  // If we didn't start or finish an operator, reset oap->regname, unless we
  // need it later.
  if (!finish_op
      && !s->oa.op_type
      && (s->idx < 0 || !(nv_cmds[s->idx].cmd_flags & NV_KEEPREG))) {
    clearop(&s->oa);
    set_reg_var(get_default_register_name());
  }
```

Though I wonder if the proper solution is to implement `v:register` dynamically, i e instead of trying to keep it in sync, we calculate the correct value from `normal_state->oa.regname` upon access.

**Comment by andymass** [comment] 2019-10-11 11:45
@svermeulen, can you further explain how your custom paste workflow is interrupted by the value of v:register?  I'm not sure changing this would fix your use case.

**Comment by svermeulen** [comment] 2019-10-11 23:43
@andymass Here's a small example of my use case:

```
function s:doCustomPaste()
    exec "normal! \"" . v:register . "p"
endfunction

nnoremap d "_d
nnoremap p :call <sid>doCustomPaste()<cr>
```

My actual use case is more complicated though of course.

If you use the above as your .vimrc, then yank something, than run `dwp` it will delete the word but will not paste anything, because it passes the black hole register to the custom paste method.  You can work around this by checking for the black hole register inside the doCustomPaste method, but that's not a great solution

**Comment by andymass** [comment] 2019-10-12 21:07
@svermeulen, thanks, yeah that's bad.  Should be fixed.

**Comment by ffanzhang** [comment] 2019-10-21 04:06
```
196   it('works in normal mode', function()                                                                                                                   
197     cmdmap('<F2>', 'let s = [mode(1), v:count, v:register]')                                                                                              
198                                                                                                                                                           
199     -- check v:count and v:register works                                                                                                                 
200     feed('<F2>')                                                                                                                                          
201     eq({'n', 0, '"'}, eval('s'))                                                                                                                          
202     feed('7<F2>')                                                                                                                                         
203     eq({'n', 7, '"'}, eval('s'))                                                                                                                          
204     feed('"e<F2>')                                                                                                                                        
205     eq({'n', 0, 'e'}, eval('s'))                                                                                                                          
206     feed('5"k<F2>')                                                                                                                                       
207     eq({'n', 5, 'k'}, eval('s'))                                                                                                                          
208     feed('"+2<F2>')                                                                                                                                       
209     eq({'n', 2, '+'}, eval('s'))                                                                                                                          
210                                    
```
Do we have to fix those functional tests in test/functional/ex_cmds/cmd_map_spec.lua if we were to fix this bug?

**Comment by justinmk** [comment] 2019-10-21 04:31
> Do we have to fix those functional tests in test/functional/ex_cmds/cmd_map_spec.lua if we were to fix this bug?

If the tests are wrong then they should be updated. (I haven't checked the actual issue here, fwiw)

**Comment by andymass** [comment] 2019-10-22 23:23
@svermeulen can you post that exact to a vim issue?  Bram may reevaluate if it has been many years.

**Comment by chrisbra** [comment] 2019-10-23 11:14
I agree with @andymass suggestion.

**Comment by amerlyq** [comment] 2021-03-20 14:34
Is this anywhere on roadmap?

I tried to create my own paste mappings, which would re-indented pasted block based on surrounding context and heuristics, and spent several months in frustration, until I understood the root cause and found this thread.

Together with `set unnamedplus` the detrimental effect from `v:register` is several magnitudes larger, 
as each time I switch to browser, copy something and try to paste into nvim -- it pastes some trash from previous register, whatever it was (or does nothing after `"_d"`).

**Comment by andymass** [comment] 2021-03-20 14:40
@amerlyq  This should already be fixed by patch 8.2.0929, which is included: https://github.com/neovim/neovim/commit/4e24e31a6b2c45e0bc2ab15059a51092b29ebaf5
Do you have an example showing the problem?

**Comment by amerlyq** [comment] 2021-03-20 16:06
@andymass I temporarily take back my claim above, until I can stably reproduce it with `nvim -u NONE`. 
When I did it just now, it seems probability to trigger the problem was significantly reduced -- and I start to suspect transient/timing-related problems somewhere in chain:
`qutebrowser -> xclip -> copyq -> xlip -> nvim`.
Previously I claimed the problem as related, because I pasted _previously_ copied/deleted text, but it may still be unrelated to v:register.
Sorry on bumping the issue.
So, if it's already fixed -- it can be safely closed, I suppose.

**Comment by amerlyq** [comment] 2021-03-20 16:25
Actually, I located one of my several corner case with misbehavior:
Case N1: 
* create new empty line (custom `go`) with proper automatic indent
* modify text from clipboard to add additional level of indent to each line
* keep in clipboard original text (i.e. don't modify register in-place)
```
nvim -u NONE
set clipboard=unnamedplus
nnoremap go  o<Space><Esc>^"_D
nnoremap <buffer><silent> p  :<C-u>call setreg('p', map(getreg(v:register,1,1), "'  '. v:val"), 'V') \| exe 'norm! "pp'<CR>
```
As you can assume, immediately after `go` -- we have `:echo v:register` showing `_` instead of nothing or `" / +`

**Comment by amerlyq** [comment] 2021-03-20 16:43
Argh, I tested it on archlinux Aug release 0.4.4, which was older than the Oct commit above (but when I checked the dates, I somehow looked into original vim repo commit which was in Jul, so I thought everything ok). 
Master from 0.5.0 don't have the problem.
Sorry again.

**Comment by glacambre** [comment] 2021-06-06 09:37
Yup, can't reproduce on master, let's close this :).

**Closed by glacambre** 2021-06-06 09:37 UTC
Labels: bug
