### ISSUE TITLE
The new default colorscheme breaks legacy vim colorscheme: workarounds and future steps?

### ISSUE THREAD

**Issue by wookayin** [neovim/neovim#26378] opened 2023-12-04 04:39 UTC
First of all, I appreciate the huge efforts and work done in the new default colorscheme #26334, it's a great feature and nice enhancement of neovim.

I hope this can be a follow-up thread as a part of the tracking issue #26369, about the awesome new default colorscheme introduced in #26334. Initiated from [my reddit comment](https://www.reddit.com/r/neovim/comments/189nw6r/comment/kbvd65x/?utm_source=reddit&utm_medium=web2x&context=3):

## Description of the problem

One issue I have is that the new default colorscheme to **break** many existing legacy colorschemes that are based on the plain "vim" colorscheme. Those legacy colorschemes --- including [those are "shipped with neovim"](https://github.com/neovim/neovim/tree/master/runtime/colors) and [community-maintained collections](https://github.com/flazz/vim-colorschemes) or [curations](https://vimcolorschemes.com/) --- are affected and now look quite different because they did not exhaustively define all the highlight group being used, i.e. because of their implicit dependency/assumptions on the default (vim) colorscheme.

Colorschemes usually have `hi clear` at the beginning of the script file, but this reverts all the highlight configs back to the new neovim default; so having some lines like `:colorscheme vim` or `:source colors/vim.vim early` in init.vim will have no effect. These lines must be put after `hi clear` in each of the colorscheme script.

For example, if a colorscheme does not explicitly define "String" as `:hi link String Constant` (which used to default to "Constant" -> "Red"), this will no longer have a highlight color same as "Constant" but "NvimLightGreen". This is a problem of a *legacy, outdated* colorscheme, so shouldn't be a major problem or blocker, but [we might have some decisions or suggested solutions for those legacy colorschemes](https://www.reddit.com/r/neovim/comments/189nw6r/comment/kbvssn9/?utm_source=reddit&utm_medium=web2x&context=3).

Also, the built-in colorschemes https://github.com/neovim/neovim/tree/master/runtime/colors would need an corresponding update or a removal.

## Workaround or solutions

On an end user's side:

- (1) Users should avoid using legacy vim colorschemes, and move to the modern, neovim-aware plugins that have a continued neovim support.

- (2) An user whose config is unfortunately based on an "old" vim colorscheme (say `base_legacy`) can *copy* (or "fork") `colors/base_legacy.vim` into their neovim config and add the `source colors/vim.vim` line after `hi clear`). Sorry, you can't use a plugin any longer unless it is still maintained.

- (3) Update your existing colorscheme or config to explicitly configure all the built-in highlight groups, that behave differently e.g. `WinSeparator`, `String`, `Function`, `MoreMsg`, `WarningMsg`, etc.

Community/plugin:

- (4) The maintainer of colorschemes should update their plugin to make it "aware of neovim 0.10" -- but I don't think is always possible; Many "legacy" colorschemes are no longer updated and maintained (https://github.com/flazz/vim-colorschemes). I don't expect all the (legacy) colorschemes in such a "collection" (even including [a fork](https://github.com/EvitanRelta/vim-colorschemes)) can be updated.

Neovim side:

- (5) Add a backward-compatibility option for `hi clear` to allow an user to explicitly opt out of the new default colorscheme; e.g. if some switch is turned on, `hi clear` will revert to (or source) the `vim` colorscheme. Or, if `:colorscheme vim` is ever called once in user's `init.vim` or `init.lua`, `hi clear` will revert to the `vim` colorscheme instead of the new neovim default.

  Since this is only to support an old vim legacy, I'm not sure if it is really worth doing to add a new flag or configuration point. But I don't see any other solutions that can make legacy vim colorschemes look exactly the same without changing the behavior of `hi clear`.

**Comment by wookayin** [comment] 2023-12-04 06:51
I'm fine with "breaking changes" because neovim's decision is to force users to actively move away from legacy colorschemes.

>  Or, if :colorscheme vim is ever called once in user's init.vim or init.lua, hi clear will revert to the vim colorscheme instead of the new neovim default.

One possible proposal is to make `:colorscheme vim` (more than `:source colors/vim.vim`) set some global variable (like `g:colors_name` set by `:colorscheme`), and `hi clear` be aware of this so that `:hi clear` work as if `:colorscheme vim` were done.

**Comment by clason** [comment] 2023-12-04 06:55
> I'm fine with "breaking changes" because neovim's decision is to force users to actively move away from legacy colorschemes.

This is false; nobody is moving anybody away from anything. We just don't consider spending effort on unmaintained external projects worthwhile.

> One possible proposal is to make :colorscheme vim (more than :source colors/vim.vim) set some global variable (like g:colors_name set by :colorscheme), and hi clear be aware of this so that :hi clear work as if :colorscheme vim were done.

No, we should strive for the minimally invasive fix for the bundled(!) colorschemes. We already need to modify the boilerplate at the top due to different `t_co` handling, so this is not a big step.


Also, can you please show some before/after screenshots showing bundled (habamax, retrobox, quiet, etc.) colorschemes? I haven't noticed anything from my (admittedly brief) testing.

**Comment by justinmk** [comment] 2023-12-04 20:28
# Resolution

To close this issue:

> We should fix the bundled colorschemes ... (e.g., by adding a `colorscheme vim` after the `hi clear`).

For externally-maintained plugins, there's nothing actionable (we already have documented the change).

**Comment by echasnovski** [comment] 2023-12-16 13:53
The compatibility issue with most probable cause and suggested solutions are now mentioned in the [breaking changes](https://github.com/neovim/neovim/blob/574519d9d68f7f28a868e95ef0d081cbae6ddec4/runtime/doc/news.txt#L106-L109) and [difference to Vim](https://github.com/neovim/neovim/blob/574519d9d68f7f28a868e95ef0d081cbae6ddec4/runtime/doc/vim_diff.txt#L33-L36).

**Comment by leet0rz** [comment] 2023-12-16 14:31
I will put this in here too:
[theme on stable](https://camo.githubusercontent.com/b3bcb4c26e2f26acee5265a9496b3856ec68faa856caf2cc0a7ee6c76ad3916f/68747470733a2f2f692e696d6775722e636f6d2f55306451476e7a2e706e67)
[theme on nightly](https://i.imgur.com/sX3fJG6.png)

This was fine until the nightly where the new default theme was released.

**Comment by leet0rz** [comment] 2023-12-16 22:57
This fixed the problem for me:

vim.cmd("highlight @variable.lua guifg=#38d5d5")
vim.cmd('highlight Identifier guifg=#38d5d5')

I just reverted these back to their original colors, maybe this is helpful for someone else too.

**Closed** 2024-01-25 17:22 UTC
Labels: enhancement, defaults, compatibility, highlight

**Comment by fionn** [comment] 2024-05-17 10:52
> (3) Update your existing colorscheme or config to explicitly configure all the built-in highlight groups, that behave differently e.g. `WinSeparator`, `String`, `Function`, `MoreMsg`, `WarningMsg`, etc.

Is there an exhaustive list somewhere?

**Comment by clason** [comment] 2024-05-17 10:57
* `:h group-name`
* `:h highlight-groups`
* `:h treesitter-highlight-groups`
* `:h diagnostic-highlights`
* `:h lsp-highlight`
* `:h lsp-semantic-highlight`

or check `src/nvim/highlight_group.c` directly.

**Comment by echasnovski** [comment] 2024-05-17 11:00
Plus [relevant part of 'news-0.10.txt'](https://github.com/neovim/neovim/blob/42aa69b076cb338e20b5b4656771f1873e8930d8/runtime/doc/news-0.10.txt#L25-L36).

**Comment by shmerl** [comment] 2024-05-17 18:39
> Is there an exhaustive list somewhere?

More in the same context, is there some example what uses all the values? I.e. I'd like to troubleshoot vim-gotham theme by comparing old and new look side by side. If someone made a comprehensive example with all the definitions used, that would expose all the regressions.

**Comment by clason** [comment] 2024-05-17 18:41
The help pages I linked actually use the corresponding highlight groups to color the group name, for that exact purpose.

**Comment by shmerl** [comment] 2024-05-17 18:48
Perfect, I'll use that to compare. It works at least for those ones which aren't new.

**Comment by shmerl** [comment] 2024-05-19 17:56
Slightly off-topic, but where is the definition of the new default color scheme? I.e. if I wanted to convert one from vimscript to lua, what can I look at as the stock example that defines all groups?

**Comment by clason** [comment] 2024-05-19 18:13
highlight_groups.c

**Comment by shmerl** [comment] 2024-05-19 18:28
Well, I want a lua example to make a theme. .c doesn't sound like it. So default theme isn't even defined in lua?

Is the fallback one a sufficient example? I.e. https://github.com/neovim/neovim/blob/master/runtime/colors/vim.lua

**Comment by clason** [comment] 2024-05-19 18:32
Yes, the default theme is not defined in Lua but in C. (That's how it is the default.)

Please ask usage questions in discussions or on Matrix.
