### ISSUE TITLE
Need more tests for visual features

### ISSUE THREAD

**Issue by tarruda** [neovim/neovim#1630] opened 2014-12-09 12:02 UTC
#1605 introduced a framework/DSL for writing screen tests/specs, which is something not covered by the old functional tests. I have added a few basic tests but we still need a lot more. If you make extensive use of a particular visual feature, consider contributing with some tests that verify it works on Neovim.

Those interested in helping will find enough documentation to get started in the files under test/functional/ui(especially screen.lua).

Here are some features that come to mind and could use some testing:

- Default highlight coloring(search matches, visual mode, ...)
- Concealing
- Anything window/tab related(buffer/window/tab navigation, status bars, ...)

I will give special attention to PRs that contribute with such tests.

**Comment by McKizzle** [comment] 2015-02-16 03:06
Hello, 

I've created a few tests that check the position of the cursor while searching and if search results are highlighted with `set hlsearch`. I don't want to to create any pointless pull requests. The tests seems to fall into the requirements stated above, but it feels better to verify to with you before hand. 

Cheers,

MrMcKizzle

**Comment by justinmk** [comment] 2015-02-16 03:14
@McKizzle why would it be pointless? Send a Pizzle Requizzle.

**Comment by McKizzle** [comment] 2015-02-16 03:39
Alrighty, I'm going to add some more related tests first and do that.

**Comment by justinmk** [comment] 2015-02-16 14:33
@McKizzle check out https://github.com/neovim/neovim/pull/1930 to make sure you aren't duplicating effort.

For future reference, check open PRs tagged with the "test" label:

https://github.com/neovim/neovim/pulls?q=is%3Aopen+is%3Apr+label%3Atests

**Comment by McKizzle** [comment] 2015-02-16 14:41
Thanks, that helps a lot.

**Comment by bfredl** [comment] 2015-02-16 14:54
@McKizzle I am testing basic hlsearch and incsearch in #1930, and I plan to also add test hlsearch:s interaction with matchadd/pos/ (as I've  looked into refactor this code) . But I'm sure there are more cases that could be tested here (the logic in `screen.c` that implements all these is pretty complex) , so your input would certainly be helpful.

**Comment by bfredl** [comment] 2015-02-16 14:57
Btw, is the rules for merging overlapping highlights from different sources (`:syntax`, spell, diff, hlsearch, incsearch, matchadd, visual, etc) documented somewhere? (ie what is prioritized over what, when there is a conflict) Otherwise I plan to write up something about this myself.

**Comment by McKizzle** [comment] 2015-02-16 15:12
@bfredl OK. I built a few basic highlighting tests yesterday. They provide the same tests you have. I'll go ahead and build a few concealing tests. If there are any additional higlighting and searching tests I'll add them to yours.

**Comment by McKizzle** [comment] 2015-02-22 23:28
A couple of tests for highlighting, searching, and concealing have been added. [https://github.com/neovim/neovim/pull/2044](https://github.com/neovim/neovim/pull/2044)

**Comment by bfredl** [comment] 2015-02-23 10:14
Perhaps it is just me, but I am always a little bit annoyed that the tests do not (and can not?) check the character under the cursor (I mean the `^` completely replaces the marked character, instead of annotating it like the highlight specs).

**Comment by tarruda** [comment] 2015-02-23 10:27
> Perhaps it is just me, but I am always a little bit annoyed that the tests do not (and can not?) check the character under the cursor (I mean the ^ completely replaces the marked character, instead of annotating it like the highlight specs).

For tests that need to verify cursor position(such as mouse drag/click), I think its more readable to display a marker in the screen rather than check `screen._cursor.{col,row}`. Though it would be easy to add an option that hides the `^` marker.

**Comment by bfredl** [comment] 2015-02-23 10:42
No, I meant that `^` could be prepended to the character under the cursor, rather than replacing it. (as is done with highlight markers), for instance in the searchhl test
`some {1:^ext}`
could be
`some {1:^text}`

**Comment by daynin** [comment] 2016-02-08 00:25
@tarruda hello! What about simple UI test for operations with text objects (like deleting, replacing, changing and etc). Can they be useful or not?

I ask this question because I see tests which check operations which mostly produce some text's highlighting or something like that.

**Comment by justinmk** [comment] 2016-02-08 00:49
@daynin Please check the legacy tests which cover many text-object cases already.

Actually, I think we can close this issue now: we have many tests and I am seeing confusion caused by the existence of this issue. We no longer need "any test you can think of". We need specific tests and the task is no longer entry-level.

**Closed by justinmk** 2016-02-08 00:49 UTC
Labels: entry-level, robustness, tests

**Comment by daynin** [comment] 2016-02-08 00:51
@justinmk , ok. Thank you!

**Comment by tarruda** [comment] 2016-02-08 12:09
@daynin Something we could use is more regression tests that reproduce bugs being reported. That is, if you see reported bugs in the issue tracker(or if you report a bug), try to reproduce it in a test and send a PR. These kind of tests are important because in a codebase as big as ours, the same bugs have a good chance of being reintroduced through different paths. Examples:

- https://github.com/neovim/neovim/blob/827e267800417b8fdd1340d54f5dc5fa9d81bb92/test/functional/eval/msgpack_functions_spec.lua#L18-L27
- https://github.com/neovim/neovim/blob/827e267800417b8fdd1340d54f5dc5fa9d81bb92/test/functional/ex_getln/history_spec.lua#L8-L36
- https://github.com/neovim/neovim/blob/827e267800417b8fdd1340d54f5dc5fa9d81bb92/test/functional/shada/merging_spec.lua#L180-L204

Notice the `Regression test:` marker(standardized by @ZyX-I?), helping to distinguish from normal feature tests.

**Comment by ZyX-I** [comment] 2016-02-08 13:59
I do not have all tests that cover bugs marked like this. This marker is usually placed by me when it seems that test case was already covered by another test or when test “looks strange”: i.e. I think it would be hard to determine what is tested without describing why this test is added.

If I think that bug happened to exist because test coverage is *not complete* and test has value on its own I usually do not add this marker.

In any case I never thought of this marker as a standard: it is a simple explanatory comment the only purpose of which is to explain why test exists.
