### ISSUE TITLE
SIGABORT with coc.nvim

### ISSUE THREAD

**Issue by liyinsg** [neovim/neovim#11107] opened 2019-09-27 12:42 UTC
- `nvim --version`: NVIM v0.5.0-67-g298da52fd
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version: Ubuntu 19.04
- Terminal name/version: gnome-terminal  3.32.1-1ubuntu1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim +PlugUpgrade +qall`

init.vim
```
set rtp+=/usr/local/etc/vim

if empty(glob("/usr/local/etc/vim/autoload/plug.vim"))
  silent !curl -fLo /usr/local/etc/vim/autoload/plug.vim --create-dirs
	\ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin("/usr/local/etc/vim/plugged")
Plug 'neoclide/coc.nvim', {'do': './install.sh nightly'}
call plug#end()	         " required
```

### Actual behaviour
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff73aa700 (LWP 7432)]
[Detaching after fork from child process 7433]
[Thread 0x7ffff73aa700 (LWP 7432) exited]

Thread 1 "nvim" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c42535 in __GI_abort () at abort.c:79
#2  0x000055555575f924 in rpc_set_client_info (id=0x3, info=...) at /home/ly/archive/neovim/src/nvim/msgpack_rpc/channel.c:688
#3  0x0000555555607cdd in nvim_set_client_info (channel_id=0x3, name=..., version=..., type=..., methods=..., attributes=..., err=0x7fffffffd1d0) at /home/ly/archive/neovim/src/nvim/api/vim.c:1678
#4  0x00005555555ed644 in handle_nvim_set_client_info (channel_id=0x3, args=..., error=0x7fffffffd1d0) at /home/ly/archive/neovim/build/src/nvim/auto/api/private/dispatch_wrappers.generated.h:4517
#5  0x000055555575e7da in request_event (argv=0x7fffffffd248) at /home/ly/archive/neovim/src/nvim/msgpack_rpc/channel.c:382
#6  0x0000555555699f81 in multiqueue_process_events (this=0x555555a72370) at /home/ly/archive/neovim/src/nvim/event/multiqueue.c:157
#7  0x0000555555725dde in event_teardown () at /home/ly/archive/neovim/src/nvim/main.c:171
#8  0x00005555557a2cc0 in mch_exit (r=0x0) at /home/ly/archive/neovim/src/nvim/os_unix.c:92
#9  0x0000555555726d80 in getout (exitval=0x0) at /home/ly/archive/neovim/src/nvim/main.c:678
#10 0x00005555556c415c in ex_quit_all (eap=0x7fffffffd470) at /home/ly/archive/neovim/src/nvim/ex_docmd.c:6178
#11 0x00005555556bb205 in do_one_cmd (cmdlinep=0x7fffffffd670, flags=0xa, cstack=0x7fffffffd790, fgetline=0x0, cookie=0x0) at /home/ly/archive/neovim/src/nvim/ex_docmd.c:2270
#12 0x00005555556b763e in do_cmdline (cmdline=0x7fffffffe31f "qall", fgetline=0x0, cookie=0x0, flags=0xa) at /home/ly/archive/neovim/src/nvim/ex_docmd.c:593
#13 0x00005555556b6c6a in do_cmdline_cmd (cmd=0x7fffffffe31f "qall") at /home/ly/archive/neovim/src/nvim/ex_docmd.c:270
#14 0x000055555572959d in exe_commands (parmp=0x7fffffffdd90) at /home/ly/archive/neovim/src/nvim/main.c:1697
#15 0x000055555572670a in main (argc=0x3, argv=0x7fffffffdf88) at /home/ly/archive/neovim/src/nvim/main.c:523
```
### Expected behaviour
No crash

### First commits in coc.nvim caused the crash
https://github.com/neoclide/coc.nvim/commit/0fe193e685282a0d9acb2de60c58e540cc7e3b48
```
function! coc#rpc#stop()
  return coc#client#stop(s:name)	  if empty(s:client)
    return
  endif
  try
    if s:is_vim
      call job_stop(ch_getjob(s:client['channel']), 'term')
    else
      call jobstop(s:client['chan_id'])
    endif
  catch /.*/
    " ignore
  endtry
endfunction	endfunction
```

**Comment by justinmk** [comment] 2019-09-29 22:15
Duplicate of #11052

**Closed** 2019-09-29 22:15 UTC
Labels: bug
