### ISSUE TITLE
'%' character dissapears when joining lines

### ISSUE THREAD

**Issue by minusf** [neovim/neovim#8841] opened 2018-08-10 10:43 UTC
- `nvim --version`: `NVIM v0.3.1`
- Vim (version: ) behaves differently? yes
- Operating system/version: macos
- Terminal name/version: iterm2
- `$TERM`: `screen-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
i{%<enter>%}<esc>kJ
```

### Actual behaviour

```
{%|}
```
(`|` = cursor)

### Expected behaviour

```
{%|%}
```
(`|` = cursor)

### also

The previous line must contain `%`, otherwise the behaviour is correct:

```
ia<enter>%<esc>kJ
```
Result:
```
a|%
```
(`|` = cursor)

**Comment by chrisbra** [comment] 2018-08-10 11:07
`:set formatoptions-=j` or remove the `%` from your comments setting.

**Comment by jamessan** [comment] 2018-08-10 11:13
Duplicate of #8655

**Closed by jamessan** 2018-08-10 11:13 UTC

**Comment by minusf** [comment] 2018-08-10 11:16
sorry for the noise.

i never realized `%` was part of `comments`, or more precisely filetype plugins not removing it where it is definitely not part of comments (e.g. `jinja`).

the different default for `formatoptions` in vim also did not help me doing my homework.

thanks for looking into this.
