### ISSUE TITLE
nvim-qt.exe cause E903 error

### ISSUE THREAD

**Issue by peter-lyr** [neovim/neovim#21642] opened 2023-01-04 10:55 UTC
### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

vim is ok

### Operating system/version

windows 10

### Terminal name/version

no terminal

### $TERM environment variable

no either.

### Installation

just download nvim-win64.zip and unzip somewhere.

### How to reproduce the issue

- double click nvim-qt.exe
- type `:terminal` and press enter

### Expected behavior

open terminal in current buffer.

### Actual behavior

cause an error e903.
![mmexport1672829002073](https://user-images.githubusercontent.com/55801796/210538158-fdf4912d-58b4-48b0-8154-aa7733a3d600.png)
it is OK in v0.6 and v0.7.
but not ok in v0.8.0, 0.8.1 and 0.8.2.
Error accures only in this version of windows. In another version of windows, all things are perfect.

**Comment by clason** [comment] 2023-01-04 11:21
Duplicate of #20458

**Closed by clason** 2023-01-04 11:21 UTC
Labels: bug, platform:windows

**Comment by justinmk** [comment] 2023-01-04 11:24
Windows 10 Version 1809 is required for :terminal

**Comment by peter-lyr** [comment] 2023-01-04 11:40
So how do we solve this problem? I can't change my Windows version now.

**Comment by dseeni** [comment] 2023-03-15 01:03
Sadly I'm experiencing this as well, but relating to fzf.vim 

Stuck on a windows 8.1 pc for work for the time being.

Are there any workarounds in terms of getting a plugin to launch? (fzf.vim)
I don't use terminal nvim...
