### ISSUE TITLE
hiding a floatwin can leave a spot

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#29844] opened 2024-07-24 13:19 UTC
### Problem

a spot like this:

![ceb6f12c-49bd-11ef-9e05-54b203702c9c](https://github.com/user-attachments/assets/76e5d6b0-6b36-4c8d-aa97-5c11f5bc5c63)

which will not remain long, yet `:redraw` and `:redraw!` can not clear it.

### Steps to reproduce

* test.lua
```
------
------

local api = vim.api

local text = "🅰️"

local bufnr = api.nvim_create_buf(false, true)
api.nvim_buf_set_lines(bufnr, 0, -1, false, { text })

local winid = api.nvim_open_win(bufnr, false, {
  relative = "editor",
  row = 1,
  col = 1,
  width = api.nvim_strwidth(text),
  height = 1,
})

vim.print("winid", winid)
vim.schedule(function() api.nvim_win_set_config(winid, { hide = true }) end)
```
* `$ nvim --clean -u NONE test.lua`
* `:so`
* see the white spot

### Expected behavior

nothing of a floatwin will be left when it's being hidden.

### Neovim version (nvim -v)

nvim 0.10

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9.2

### $TERM environment variable

st-256color

### Installation

pacman

**Comment by haolian9** [comment] 2024-07-24 13:22
i have also tried kitty, which is dark background by default, the above procedure will procedure a black spot.

i'm having trouble on uploading images, so please forgive me for the broken image link

**Comment by zeertzjq** [comment] 2024-07-24 13:42
Duplicate of #7151

**Closed by zeertzjq** 2024-07-24 13:42 UTC
Labels: bug, display, float

**Comment by haolian9** [comment] 2024-07-24 23:42
i actually found a workaround for this very problem: append a space to that text
