### ISSUE TITLE
Segfault when using the Expr-Register with invalid values

### ISSUE THREAD

**Issue by edi9999** [neovim/neovim#9074] opened 2018-10-01 12:39 UTC
- `nvim --version`:  

```
NVIM v0.3.2-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-tRG5jm/neovim-0.3.0~ubuntu1+git201809302032-3bdc34d-479a1d0=. -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-tRG5jm/neovim-0.3.0~ubuntu1+git201809302032-3bdc34d-479a1d0/build/config -I/build/neovim-tRG5jm/neovim-0.3.0~ubuntu1+git201809302032-3bdc34d-479a1d0/src -I/build/neovim-tRG5jm/neovim-0.3.0~ubuntu1+git201809302032-3bdc34d-479a1d0/.deps/usr/include -I/usr/include -I/build/neovim-tRG5jm/neovim-0.3.0~ubuntu1+git201809302032-3bdc34d-479a1d0/build/src/nvim/auto -I/build/neovim-tRG5jm/neovim-0.3.0~ubuntu1+git201809302032-3bdc34d-479a1d0/build/include
Compiled by buildd@lcy01-amd64-016

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently?  vim version works 
- Operating system/version:  Ubuntu 18.04.1 LTS
- Terminal name/version: xfce4-terminal xfce4-terminal 0.8.7.4 (Xfce 4.12)
- `$TERM`:  screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# go into insert mode
i
# Go into expr-register
C-R=
# Hit 1/2 3 (eg **1**, **/** , **2**, **<Space>**, **3**)
1/2 3
```

### Actual behaviour

=1/2 nvim: /build/neovim-tRG5jm/neovim-0.3.0~ubuntu1+git201809302032-3bdc34d-479a1d0/src/nvim/viml/parser/expressions.c:1241: viml_pexpr_handle_bop: Assertion `bop_node_lvl != new_top_node_lvl || bop_node_ass == new_top_node_ass' failed.
                                                                   Aborted (core dumped)

### Expected behaviour

Don't crash at least :-)

**Comment by KillTheMule** [comment] 2018-10-01 12:42
Could not reproduce with 0.3.0-1353-gb33d304.

**Comment by jamessan** [comment] 2018-10-01 13:13
I can reproduce this back in v0.3.0 -- `./build/bin/nvim -u NONE -i NONE -n -c 'call feedkeys(":\<C-r>=1/2 3\<CR>", "nx")`.  Cc @ZyX-I

**Comment by KillTheMule** [comment] 2018-10-01 13:17
```sh
=1/2 3
Error detected while processing command line:
E15: Invalid expression: 1/2 3
Press ENTER or type command to continue
```

That's what I get in 0.3.0. It's a release build, but that probably shouldn't matter.

**Comment by justinmk** [comment] 2018-10-01 13:47
Is this the same as https://github.com/neovim/neovim/issues/7889 ?

**Comment by jamessan** [comment] 2018-10-01 13:50
Yeah, looks like the same problem.

Duplicate of #7889

**Comment by jamessan** [comment] 2018-10-01 13:51
> It's a release build, but that probably shouldn't matter.

It does.  Release builds disable asserts.

**Closed by jamessan** 2018-10-01 13:50 UTC
