### ISSUE TITLE
Insert in the wrong pane when involving navigation between views

### ISSUE THREAD

**Issue by bohrshaw** [neovim/neovim#2733] opened 2015-05-24 14:16 UTC
With two panes side by side in the current window, cursor on the left one, issue command `startinsert | wincmd w`, surprisingly the right pane is now in insert mode. (Same if `startinsert` is replaced by `call feedkeys('i')`.)

This also happens within the context of an auto-command like `autocmd BufWinEnter,WinEnter term://* startinsert`, when a command like `wincmd w | wincmd W` is executed in a *proper* pane layout.

I encountered this issue when trying to put any terminal buffer in insert mode whenever I switch to it. And I'm unsure if this is the proper behavior of (n)vim and need help to solve my actual problem in a robust way.

PS: The newly-introduced terminal buffer(when used as a shell) seems to be an exception of vim's "normal mode as default mode", which is trouble-anticipated.

**Comment by Grimy** [comment] 2015-06-10 11:52
Why is this tagged [bug]? That sounds exactly like the expected behaviour to me: `startinsert` puts nvim in insert mode, then `wincmd w` focuses the right panel. Note that vim also behaves this way.

@bohrshaw, could you expand on why you find this beahvior surprising?

**Comment by bohrshaw** [comment] 2015-06-11 02:08
@Grimy, I expected insert-mode is local to the current pane or window. **But it turns out that the mode just follows the cursor**, which does make sense. I can confirm that this also applies to visual, select, replace mode. What do you think? @justinmk 

As for the terminal-insert-problem, thanks for the solution @Grimy! I have:

    autocmd BufWinEnter,WinEnter term://* startinsert
    autocmd BufLeave term://* stopinsert

**Comment by Grimy** [comment] 2015-06-11 06:32
I had forgotten about `stopinsert`, it’s more elegant than my `feedkeys` solution =)

> I expected insert-mode is local to the current pane or window.

Nope. Insert-mode, like all other modes, is global to (n)vim. You can easily test that by inputting `<C-O><C-W>w` in insert mode.

Since this is not, actually, a bug, I think we can close this issue. Maybe open an improvement request to make modes window-local instead. But that would be a pretty big effort for not much gain: it would only make a difference in edge-cases like this, since most window-switching occurs in normal mode. Plus, it would be an incompatible change that could break some scripts.

**Closed** 2015-06-11 13:25 UTC
Labels: bug
