### ISSUE TITLE
A feature that may be worth learning about cursorline highlight

### ISSUE THREAD

**Issue by 1478zhcy** [neovim/neovim#14136] opened 2021-03-14 11:58 UTC
- `nvim --version`: v0.5.0-dev+1148-g3c8583e43
- `vim -u DEFAULTS` (version: ) behaves differently.
- Operating system/version: Windows, Linux

As you see:
![image](https://user-images.githubusercontent.com/61115159/111067208-29a26400-84fe-11eb-9383-26ae63197c0b.png)
If I set 'cursorlineopt' to 'number' while I set cursorline on, only the line number will be highlighted. It would be useful in some color theme and some terminal emulator. I recently discovered this feature of Vim, but Neovim not support the option.

**Comment by teto** [comment] 2021-03-14 14:55
duplicate of https://github.com/neovim/neovim/issues/13356 .

**Closed by teto** 2021-03-14 14:55 UTC
Labels: enhancement
