### ISSUE TITLE
Setting `clipboard` to "unnamedplus" cannot be reverted in lua

### ISSUE THREAD

**Issue by helq** [neovim/neovim#29208] opened 2024-06-05 21:56 UTC
### Problem

The clipboard variable cannot be disabled once it has been enabled with a value of "unnamedplus" in lua. The error doesn't appear with a `init.vim` file, only `init.lua`.

The bug is not present in v0.9.0, but it is in v0.10.0 and current master.

### Steps to reproduce

Minimal configuration:

```lua
vim.opt.clipboard = "unnamedplus"
vim.opt.clipboard = nil
```

Steps:

1. Open neovim with minimal configuration
2. Type `:set clipboard`
3. Type `:lua vim.opt.clipboard = nil`
4. Type `:set clipboard`

### Expected behavior

Output: `clipboard=`
But instead it is: `clipboard=unnamedplus`

### Neovim version (nvim -v)

v0.11.0-dev-187+gd7651b27d5

### Vim (not Nvim) behaves the same?

no, 9.1

### Operating system/version

Archlinux

### Terminal name/version

Konsole 24.05.0

### $TERM environment variable

konsole-256color

### Installation

AUR (neovim-git)

**Comment by zeertzjq** [comment] 2024-06-05 22:08
Duplicate of #28992

**Closed by zeertzjq** 2024-06-05 22:08 UTC
Labels: bug
