### ISSUE TITLE
Allow clearing an augroup for the buffer only (lua API)

### ISSUE THREAD

**Issue by entropitor** [neovim/neovim#17576] opened 2022-03-02 13:53 UTC
### Feature already in Vim?

/

### Feature description

Currently it's only possible to clear all autocommands in an autogroup when using lua. However, the following is not supported: (Notice the `<buffer>` part)

```vim
    augroup LspClosing
      autocmd! * <buffer>
      autocmd BufDelete <buffer> lua DetachBufferFromClients(tonumber(vim.fn.expand("<abuf>")))
    augroup END
```

**Comment by clason** [comment] 2022-03-02 13:56
Duplicate of #17554

**Closed by clason** 2022-03-02 13:56 UTC
Labels: enhancement, api
