### ISSUE TITLE
lsp: select handlers/capabilities per server when using multiple language servers

### ISSUE THREAD

**Issue by ranjithshegde** [neovim/neovim#14101] opened 2021-03-09 16:47 UTC
- `nvim --version`: 0.5.0+dev+1129+gc12ea02e0-1
- nvim-lsp version(commit hash): e0e107044618bf06db2c1753fc154e7b68b6342c
- What language server : ccls + clangd
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): no
- Is the problem isolated to a particular language server: no
- Operating system/version: Arch linux, 5.11.4

### How to reproduce the problem from neovim startup
launch any cpp project/file, 

### Actual behaviour
defaults to Ccls

### Expected behaviour
choose ccls or clangd for specific issues, or prioritize a particular language

### Health check
<details>
<summary>Checkhealth result</summary>

health#scnvim#check
========================================================================
## scnvim
  - OK: SCNvim classes installed: /home/ranjith/.local/share/SuperCollider/Extensions/scide_scnvim
  - OK: has("timers") - success
  - INFO: sclang executable: /usr/bin/sclang
  - INFO: Could not find scdoc render program. See :help |scnvim-help-system| for more information.
    This is an optional dependency and only needed for SCDoc integration.

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#floaterm#check
========================================================================
## common
  - INFO: Platform: linux
  - INFO: Nvim: NVIM v0.5.0-dev+1129-gc12ea02e0
  - INFO: Plugin: 7b0eb92

## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available

health#vimtex#check
========================================================================
## VimTeX
  - OK: Vim version should have full support!
  - OK: General viewer should work properly!
  - OK: Compiler should work!

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.18.3(parser generator, used for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - bash           ✓ ✓ ✓ . 
  - java           ✓ ✓ . ✓ 
  - html           ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . 
  - devicetree     ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ 
  - supercollider  ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ 
 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         *) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: ccls: configuration checked.
] - INFO: texlab: configuration checked.
  - INFO: clangd: configuration checked.
  - INFO: sumneko_lua: configuration checked.

health#completion_nvim#check
========================================================================
## general
  - OK: neovim version is supported

## completion source
  - OK: all completion sources are valid

## snippet source
  - INFO: You haven't set up any snippet source

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.9.2
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v15.11.0
  - INFO: Nvim node.js host: /home/ranjith/.local/share/npm/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

</details>

### LSP log

<details>
<summary>Log file</summary>

</details>

Heart of the issue!
I have been using a combination of ccls and clangd until now, first with languageclient neovim, then with Coc and now with native nvim lsp
Ccls does all the work, the only reason for having clangd is because ccls cant parse doxygen markers, hence help(hover) is pretty terrible.
Is there a way to choose which language server is called when calling hover? in Coc somehow help defaulted to clangd, I just turned off any other feature of cland using config

**Comment by mjlbach** [comment] 2021-03-11 05:44
I took the liberty of moving this from nvim-lspconfig to core (yay! I can do that now). Right now we don't have a non-hacky way to do this.

**Comment by mfussenegger** [comment] 2021-03-11 16:25
If you don't mind some lua code you could build your own triggers by using the low-level client API (See `:help vim.lsp.client`)

For example something like this:


```lua
function M.hover()
  local name = 'language-server-name' -- this is probably 'clangd' in your case
  local clients = vim.tbl_filter(function(c) return c.name == name end,  vim.lsp.get_active_clients())
  local match, client = next(clients)
  assert(match, 'No active client found with name=' .. name)

  client.request('textDocument/hover', vim.lsp.util.make_position_params())
end
```

**Comment by ranjithshegde** [comment] 2021-03-11 18:39
@mfussenegger this is perfect! Thank you so much for the details on how you wrote it as well! I love this community

**Comment by ranjithshegde** [comment] 2021-03-16 08:17
@mfussenegger 
With your proposed function, I can hand over hover to clangd from ccls.
Is there a way to disable clangd autocomplete altogether? having both clangd & ccls populate the autocomplete source makes it a mess (not to mention clangd fails at snippets whereas ccls is rather graceful at that)

**Comment by mfussenegger** [comment] 2021-03-19 10:23
I don't think there is currently a way to do that other than basically re-implementing some of the completion functions.

What do you use for autocompletion? If it's omnifunc based you could for example copy the implementation below and adjust it with the clients pattern in the `hover` snippet I posted earlier:

https://github.com/neovim/neovim/blob/0f7b6b2efd4270545f2080ae91ad241189e00d67/runtime/lua/vim/lsp.lua#L1174-L1213

**Comment by alexaandru** [comment] 2021-04-01 09:52
FWIW, I'll add my use case in here as I'm in the same boat: I recently discovered efm lsp and it is absolutely amazing, I use it to "fill in the gaps" all over the place. Particularly, I use it for running `prettier` formatter on a bunch of files and I also use it for Go to run `golangci-lint` in the background.

The problem is: `efm` is only one single LSP with one single initialization section, so one single set of init_options. In order to get formatting to work, I need to set `document_formatting` to `true`, and then prettier formatter work as expected. However, in case of Go, I only want linting not formatting, but because formatting is set to true, efm is also asked to format stuff and things break in 50% of the cases or so.

Anyway, thank you @mfussenegger for the solution, I adapted it to formatting, will leave it here if anyone else runs into this:

```Lua
    local wait_ms = 1200                                                                                                                                                                                   
                                                                                                                                                                                                                     
    local function sync_format_with(name)                                                                                                                                                                            
      local clients = vim.tbl_filter(function(c)                                                                                                                                                                     
        return c.name == name                                                                                                                                                                                        
      end, vim.lsp.get_active_clients())                                                                                                                                                                             
      local match, client = next(clients)                                                                                                                                                                            
      assert(match, "No active client found with name=" .. name)                                                                                                                                                     
                                                                                                                                                                                                                     
      local completed = false                                                                                                                                                                                        
      local h = function(err, method, result, clientid)                                                                                                                                                              
        local _, _, _ = err, method, clientid                                                                                                                                                                        
        vim.lsp.util.apply_text_edits(result)                                                                                                                                                                        
        completed = true                                                                                                                                                                                             
      end                                                                                                                                                                                                            
                                                                                                                                                                                                                     
      client.request("textDocument/formatting", vim.lsp.util.make_formatting_params(), h)                                                                                                                            
                                                                                                                                                                                                                     
      vim.wait(wait_ms, function()                                                                                                                                                                         
        return completed                                                                                                                                                                                             
      end)                                                                                                                                                                                                           
    end                                                                                                                                                                                                              
                                                                                                                                                                                                                     
    function M.Format()                                                                                                                                                                                         
      local ft = vim.fn.getbufvar(vim.api.nvim_get_current_buf(), "&filetype")                                                                                                                                       
      if ft ~= "go" and ft ~= "tf" then                                                                                                                                                                              
        vim.lsp.buf.formatting_sync(nil, wait_ms)                                                                                                                                                    
      elseif ft == "go" then                                                                                                                                                                                         
        sync_format_with("gopls")                                                                                                                                                                                    
      elseif ft == "tf" then                                                                                                                                                                                         
        sync_format_with("terraformls")                                                                                                                                                                              
      end                                                                                                                                                                                                            
    end
```

So this will use whatever the LSP wants to use except for Go and Terraform, where it will lookup specific clients and ask those to perform formatting.

**Comment by ranjithshegde** [comment] 2021-04-01 10:14
> https://github.com/neovim/neovim/blob/0f7b6b2efd4270545f2080ae91ad241189e00d67/runtime/lua/vim/lsp.lua#L1174-L1213

Was a little hard for me to follow until I went through the lsp.txt (or whatver its called in helps system) and the protocol.lua in /usr/share/nvim*. And now I get it! Thank you @mfussenegger .
Also i found I could just disable completion for that server with an on attach function with custom capabilities.completion!

What is annoying however is diagnostics. if I disable publishDiagnostics in an on_attach function and assign it to only that language that needs to be disabled, it still globally disables;
example here
 ```
  Cattach = function(client)
        local caps = client.resolved_capabilities
        caps.document_formatting = false
        caps.document_highlight = false
        caps.rename = false
        caps.hover = false
        caps.completion = false
        caps.publishDiagnostics = false
        if caps.signatureHelpProvider then
            u.create_bufgroups(signHover)
        end
    end
```
Ccls has lsp extensions which can be enabled with [this](https://github.com/m-pilia/vim-ccls) plugin. For now thats the only reason I have ccls + clangd setup, where ccls gets the above attach function so that it only does these hierarchical navigation and references, clangd does the rest such as completion+lsp-snippets, hover, formatting, diagnostics etc

**Comment by alexaandru** [comment] 2021-04-01 18:07
After playing with this some more, I found a much more elegant solution - use the `on_attach` handler to alter the resolved capabilities as desired. In my case:

```Lua
local function on_attach(client, bufnr)
  local rc = client.resolved_capabilities
  if client.name == "efm" then
    local ft = vim.fn.getbufvar(bufnr, "&filetype")
    rc.document_formatting = can_format(cfg.efm.settings.languages[ft])
  end
end
```
where `cfg` holds my lspconfig settings. Now when I call `vim.lsp.buf.formatting_sync()` it seeds that only gopls supports formatting for go files and it only uses that. Conversely, where I have `formatCommand`s defined in efm for a language, then formatting is enabled for that client/buffer and `efm` gets called. Exactly as I want it to! :) 

For the OP, you can easily adapt this to your use case:

```Lua
local function on_attach(client, bufnr)
  if client.name == "ccls" then
    client.resolved_capabilities.hover = false
  elseif client.name == "clangd" then
    client.resolved_capabilities = {hover = true}
  end
end
```

Untested, but that should do it: `ccls` does all the work except hover and `clangd` only does hover and nothing else.

**Comment by mjlbach** [comment] 2021-04-01 18:17
Hmm can you not use on_init? This will run on every attach (not that big of deal, but still.

**Comment by alexaandru** [comment] 2021-04-01 18:31
That sounds even better, I'll have to give it a try :) Thanks!

**Comment by mjlbach** [comment] 2021-04-01 18:35
I'm going to close, since this seems like any additional API we could come up with would be more complicated than the suggestions mentioned.

@alexaandru another thing to try would be to override the list of default capabilities passed to the setup({}) call in lspconifg to disable the desired capabilities. You can get access to the default capabilities of neovim's language server client with (:lua require('vim.lsp.protocol').make_client_capabilities()), and then just manually disable the flags you don't want the server to respond to. Not sure if this will work, since the server just may ignore this.

If one of you could right a guide and put it in the lspconfig wiki, I would be grateful :) I don't use multiple language servers simultaneously.

**Closed by mjlbach** 2021-04-01 18:35 UTC

**Comment by alexaandru** [comment] 2021-04-01 18:54
Yeah, I'd rather go the route of altering capabilities coming from the server, since that is guaranteed to work no matter what the server does with the default capabilities.

And sure, after I try out the `on_init` change, happy to take a stab at it. I use ~16 LSPs and efm overlaps with about half of them :-) I even get fun stuff like for JavaScript, where organize imports comes from one LSP (tsserver) and formatting from another (efm, as I prefer `prettier` over `tssserver` for that) in which case I needed a bit of extra work to serialize them.

**Comment by alexaandru** [comment] 2021-04-01 19:06
Meh, cannot use `on_init`, as the capability that I want to override is filetype dependent and I do not have that information at that time. I do have it at attach time (bufnr). However, `on_init` might be a good choice for OP as his "capabilities filtering" is not filetype dependent. Good to know it exists though :) so thanks again!

**Comment by ranjithshegde** [comment] 2021-04-04 09:49
Thanks for all your help here. I have been experimenting with different configs inside lspconfig.LANG.setup, basically different configs for handlers, on_init, resolved capabilites etc.

Where I am stuck is disabling diagnostic from a particular server. since its not part of on_init(or on_attach, before_init) nor can I disable it with resolved capabilities (do I have this wrong).

@mjlbach Any suggestions on disabling diagnostics from a specific language server?

**Comment by mjlbach** [comment] 2021-04-04 09:50
Just override the handler for the server you want to silence diagnostics for. Alternatively disable capabilities for diagnostics for the client.

**Comment by ranjithshegde** [comment] 2021-04-04 09:51
Thanks. but as you had guessed, publishDiagnostics is ignored by LS.

And yes I will move this to discourse. Thanks

**Comment by neovim-discourse** [comment] 2021-04-04 15:51
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/multiple-parallel-langauge-servers/235/6

**Comment by WhyNotHugo** [comment] 2021-07-16 16:23
@alexaandru [Your suggestion above](https://github.com/neovim/neovim/issues/14101#issuecomment-812079871) is pretty close to what I'm trying to achieve, but I can't figure out what this `can_format` function is.

Where are you importing this from?

My scenario is very similar: for `ts`, both `tsserver` and `efm` report formatting capabilities, but I want to disable the former so the latter is always used.

**Comment by WhyNotHugo** [comment] 2021-07-16 16:24
Never mind, it was far simpler. [For posterity's sake](https://xkcd.com/979/):

```lua
  local rc = client.resolved_capabilities
  if client.name == "tsserver" then
    rc.document_formatting = false
  end
```

**Comment by alexaandru** [comment] 2021-07-16 18:13
Sorry about that @WhyNotHugo but you figured it out. Yes, it can be whatever can tell `efm` if it should do formatting for that language or not. In my case, since I used `efm` for a dozen+ languages, I needed a function, which for posterity sake, can be seen here: https://github.com/alexaandru/nvim-config/blob/v3.0.0/lsp.lua#L47-L50  I guess, I can just copy it in here:

```Lua
local function can_format(opts)
  for _, v in ipairs(opts) do if v.formatCommand then return true end end
  return false
end
```

Cheers!

**Comment by neovim-discourse** [comment] 2021-09-29 10:34
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/efm-tries-to-get-in-on-the-action-with-vim-lsp-buf-rename/1183/1
