### ISSUE TITLE
Windows version not reporting 'gui_running'

### ISSUE THREAD

**Issue by saltycraig** [neovim/neovim#7448] opened 2017-10-27 15:36 UTC
Windows 64-bit version running 'nvim-qt.exe' program does not report '1' when checking for 'gui_running' option, and it should as that people often use this to guard some GUI code.

- `nvim --version`: v0.2.1-25-g2e3b78d1
- Vim (version: not applicable)
- Operating system/version: Windows 7 64-bit
- Terminal name/version: not applicable
- `$TERM`: not applicable

### Actual behaviour
    :echo has("gui_running")
    0
    :echo has("win64")
    1
### Expected behaviour
    :echo has("gui_running")
    1
    :echo has("win64")
    1

**Comment by jamessan** [comment] 2017-10-27 15:44
Duplicate of #5220

**Closed by jamessan** 2017-10-27 15:44 UTC

**Comment by justinmk** [comment] 2023-02-28 11:28
`has('gui_running')` is now supported in Nvim 0.9 https://github.com/neovim/neovim/pull/22382
