### ISSUE TITLE
init/startup: some colorschemes break with True Color enabled

### ISSUE THREAD

**Issue by borring** [neovim/neovim#2953] opened 2015-07-03 17:48 UTC
One such colorscheme is [hybrid_material](https://raw.githubusercontent.com/kristijanhusak/vim-hybrid-material/master/colors/hybrid_material.vim).

if `NVIM_TUI_ENABLE_TRUE_COLOR=1` is set, the colorscheme will not load correctly from `.nvimrc`. It'll load correctly if you set it in the commandline or if nvim is launched without true color.

I also noticed that `has("gui_running")` returns 0 on launch. I checked by echoing it in my `.nvimrc` but returns 1 from the commandline after launch. That may have something to do with it.

**Comment by borring** [comment] 2015-07-18 21:54
If anyone's having the same problem, I'm getting around this issue by using the `VimEnter` autocmd event to set my colorscheme.

**Comment by mhinz** [comment] 2015-07-20 11:14
The problem is that there's no UI attached yet at the time the vimrc is read. Thus `has('gui_running')` always returns 0 at start.

I'm looking into it.

**Comment by addisonamiri** [comment] 2015-09-22 15:15
I can confirm this bug with the `solarized` colorscheme and gnome-terminal with vte .40. Setting the colorscheme after launch works for me as well but the colorscheme isn't loaded correctly (though it is loaded in some form because changing the colorscheme in my .nvimrc has an effect on the wrong colors that are shown).

**Comment by StanislavNikolov** [comment] 2015-09-29 18:07
I've tested the colorschemes ```solarized``` and ```oceanicnext```. They work only when called with ```:colorscheme```, but not when called from the .nvimrc.

**Comment by nicksloan** [comment] 2015-11-02 14:13
I added the following, which seems to have fixed it for me. Not sure if there might be unintended side-effects.

`au VimEnter * colorscheme solarized`

**Comment by justinmk** [comment] 2015-11-02 14:20
@nicksloan That's the recommended fix ATM. No side effects.

**Comment by mhinz** [comment] 2015-11-10 20:37
@justinmk Is anything speaking against simply checking if `--embed` was provided?

**Comment by mhinz** [comment] 2015-11-10 20:40
Is this actually an issue that needs to be fixed? Sure, people are used to it from Vim, but only because Vim works quite differently in that respect.

**Comment by addisonamiri** [comment] 2015-11-10 22:43
@mhinz From what I understand, the colorscheme isn't being correctly set when true color is enabled. I think because of that it makes sense for this to be labeled as a bug.

If this is too difficult to fix, then I think there needs to be some way to make it clear to users that this is expected behavior.

**Comment by mhinz** [comment] 2015-11-10 23:09
@addisonamiri He actually stated 2 problems.

The first is that init.vim gets processed before any GUI is attached, so `has('gui_running')` won't work, but `autocmd GUIEnter...` would.

The second it somehow related to `NVIM_TUI_ENABLE_TRUE_COLOR=1` and a colorscheme "not loaded correctly". Do you have more details about this?

**Comment by addisonamiri** [comment] 2015-11-11 22:17
@mhinz I wasn't aware of the first part and yes, that does seem like the way it should work.

For the colorschemes, whenever true color is enabled the colorscheme isn't set properly. It is set in some fashion (as can be seen by setting different colorschemes and launching neovim) but the colors are way off. Setting the colorscheme after launch, however fixes any display weirdness, hence the AutoCmd fixing it as it sets the colorscheme later in launch.

If that's not clear I apologize. I'm not too familiar with the init process so I may be wrong on a few assumptions but to my knowledge this is what happens.

**Comment by mhinz** [comment] 2015-11-11 22:48
@addisonamiri This will probably be easier to solve after: https://github.com/neovim/neovim/issues/3646#issuecomment-155732777

**Comment by Marenz** [comment] 2015-12-03 12:00
To be honest, doing 

```
au VimEnter * colorscheme solarized
```

Seems very ugly to me. There should be some way for the GUI to read the current colorscheme at the very least. Or you offer some kind of delayed notification for things deemed important to the GUI? In any case, labeling this as expected behavior seems very dirty to me and I vote strictly against that.

**Comment by ghostcow** [comment] 2016-01-29 11:45
screenshots of color difference:
![bug](https://cloud.githubusercontent.com/assets/5609841/12674734/aee27306-c68d-11e5-9dcb-f96af727dbb8.png)
molokai colorscheme, powerlineish airline scheme, latest build.


When I run nvim from a remote computer. The fix:
`au VimEnter * colorscheme molokai `
Doesn't fix the problem- it elicits the same color pallet with slightly different symbols in the airline.

**Comment by justinmk** [comment] 2016-02-04 06:49
`has("gui_running")` always returns 0 now. Colorschemes that check this are broken and should be fixed. This is a better option than asking _all other_ plugins to adjust their logic. See https://github.com/neovim/neovim/pull/4155 for more discussion.

**Closed by justinmk** 2016-02-04 06:49 UTC
Labels: bug
