### ISSUE TITLE
`BufEnter` autocmd and `vim.bo.buftype`

### ISSUE THREAD

**Issue by aidancz** [neovim/neovim#31457] opened 2024-12-05 07:15 UTC
### Problem

can't use `vim.bo.buftype` inside `BufEnter` autocmd callback

this autocmd not works:

```
vim.api.nvim_create_autocmd({'BufEnter'}, {callback = function() vim.print("(" .. vim.bo.buftype .. ")") end})
```

while this works:

```
vim.api.nvim_create_autocmd({'BufEnter'}, {callback = function() vim.print("(" .. vim.bo.filetype .. ")") end})
```

### Steps to reproduce

1. prepare file `minimal.lua`

```
vim.api.nvim_create_autocmd({'BufEnter'}, {callback = function() vim.print("(" .. vim.bo.buftype .. ")") end})
```

2. run `nvim --clean -u minimal.lua +terminal`

### Expected behavior

expected:
print text `(terminal)`

actual:
print text `()`

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1287+g8f84167c30

### Vim (not Nvim) behaves the same?

not sure

### Operating system/version

6.12.1-arch1-1

### Terminal name/version

st 0.8.5

### $TERM environment variable

st-256color

### Installation

AUR

**Comment by zeertzjq** [comment] 2024-12-05 07:25
Duplicate of #29419

**Closed by zeertzjq** 2024-12-05 07:25 UTC
Labels: bug
