### ISSUE TITLE
vim.opt_global:get() return a local option value.

### ISSUE THREAD

**Issue by uga-rosa** [neovim/neovim#22091] opened 2023-02-01 18:51 UTC
### Describe the bug

If both global and local values are set, the local value is returned even if opt_global is used.

### Steps to reproduce

nvim --clean
:set dictionary=foo
:setl dictionary=bar
:lua= vim.opt_global.dictionary:get()

### Expected behavior

Return a global value `{ "foo" }`.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-9ce44a7

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 20.04.5 LTS (WSL2)

### Terminal name/version

Windows terminal

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by clason** [comment] 2023-02-01 19:00
Out of interest, can you try before https://github.com/neovim/neovim/commit/679f3072f6c39be81da95261908f1998b6e3e643?

**Comment by clason** [comment] 2023-02-01 19:03
Just tested; this looks like a regression from https://github.com/neovim/neovim/pull/20103

@lewis6991

**Comment by clason** [comment] 2023-02-01 19:14
Oh, and duplicate of #21506.

**Closed by clason** 2023-02-01 19:14 UTC
Labels: lua, bug-regression, options
