### ISSUE TITLE
Brew upgrade neovim to 0.3.1 broken

### ISSUE THREAD

**Issue by chhschou** [neovim/neovim#9018] opened 2018-09-19 23:33 UTC
- `nvim --version`: 0.3
- Vim (version: ) behaves differently? no
- Operating system/version: osx high sierra
- Terminal name/version: mac terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

Run `brew upgrade neovim` to update neovim to 0.3.1

### Actual behaviour
luabitop-1.0.2-1.src.rock not found

below is excerpt from terminal:

==> Downloading https://github.com/neovim/neovim/archive/v0.3.1.tar.gz
Already downloaded: /Users/cchou/Library/Caches/Homebrew/downloads/48ed393e1b6719518a65822d4c024297a5f3a6f3f54fa27aba2a760c7e4feaad--neovim-0.3.1.tar.gz
==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.1-1.src.rock
Already downloaded: /Users/cchou/Library/Caches/Homebrew/downloads/8dfe80834670fa8af7d5264d07d66afc6fb5b4f253e772a06014f0a8b734eaf6--lpeg-1.0.1-1.src.rock
==> Downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.7/libmpack-lua-1.0.7.tar.gz
Already downloaded: /Users/cchou/Library/Caches/Homebrew/downloads/ad0f976ceb0dc87d6ce2195e0a405fc851ae85b558580477f1bac0c93c2a933a--libmpack-lua-1.0.7.tar.gz
==> Downloading https://luarocks.org/manifests/kikito/inspect-3.1.1-0.src.rock
Already downloaded: /Users/cchou/Library/Caches/Homebrew/downloads/ecc1fa84ce4c83c9406f6d1202d4a88c80ede4a0a2bfd8d8d2bd54fd042226bb--inspect-3.1.1-0.src.rock
==> Downloading https://luarocks.org/luabitop-1.0.2-1.src.rock

curl: (22) The requested URL returned error: 404 Not Found
/Users/cchou/.brew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
from /Users/cchou/.brew/Library/Homebrew/utils/fork.rb:49:in `puts
from /Users/cchou/.brew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
from /Users/cchou/.brew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
from /Users/cchou/.brew/Library/Homebrew/utils/fork.rb:30:in `fork'
from /Users/cchou/.brew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
from /Users/cchou/.brew/Library/Homebrew/utils/fork.rb:27:in `open'
from /Users/cchou/.brew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
from /Users/cchou/.brew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
from /Users/cchou/.brew/Library/Homebrew/formula_installer.rb:719:in `build'
from /Users/cchou/.brew/Library/Homebrew/formula_installer.rb:311:in `install'
from /Users/cchou/.brew/Library/Homebrew/cmd/upgrade.rb:162:in `upgrade_formula'
from /Users/cchou/.brew/Library/Homebrew/cmd/upgrade.rb:109:in `block in upgrade_formulae'
from /Users/cchou/.brew/Library/Homebrew/cmd/upgrade.rb:106:in `each'
from /Users/cchou/.brew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade_formulae'
from /Users/cchou/.brew/Library/Homebrew/cmd/upgrade.rb:84:in `upgrade'
from /Users/cchou/.brew/Library/Homebrew/brew.rb:89:in `<main>'

### Expected behaviour
neovim 0.3.1 dependencies are met

**Comment by justinmk** [comment] 2018-09-20 05:33
Duplicate of https://github.com/Homebrew/homebrew-core/issues/32144

**Closed by justinmk** 2018-09-20 05:33 UTC
