### ISSUE TITLE
Netrw "-" emits unnecessary space

### ISSUE THREAD

**Issue by westandskif** [neovim/neovim#13918] opened 2021-02-11 10:25 UTC
- `nvim --version`:
```NVIM v0.5.0-dev+1037-gd6d4e3d1a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az204-613
Features: +acl +iconv +tui
```

- `vim -u DEFAULTS` (version: ) behaves differently?
 no idea
- Operating system/version:
 `Linux westandskif 5.10.15-arch1-1 #1 SMP PREEMPT Wed, 10 Feb 2021 18:32:40 +0000 x86_64 GNU/Linux`
- Terminal name/version:
- `$TERM`:
 `alacritty 0.7.1 (a852eb85)`

### Steps to reproduce using `nvim -u NORC`
Run nvim, open netrw and press `-` to go a dir up.

### Actual behaviour
This emits unnecessary (or I just don't understand why) space in the end (e.g. this triggers whichkey plugin for me).

### Expected behaviour
No space is emitted here (see before pipe symbol):
https://github.com/neovim/neovim/blob/f6ac375604238c94d3dc3eeb9b82e67417460806/runtime/autoload/netrw.vim#L6300

**Comment by doubleloop** [comment] 2021-02-15 15:25
Duplicate of https://github.com/neovim/neovim/issues/11407 and there is also open PR with the fix: https://github.com/neovim/neovim/pull/12902 . Should it be merged? Or should this wait till whole https://github.com/vim/vim/commit/5ef1c6a4838a9629b793f3ae676f72a764171b00 is ported (it contains the same fix so there should be no merge conflict).
cc @janlazo

**Comment by janlazo** [comment] 2021-02-15 23:47
I'd say port all of the netrw files up to the Vim runtime commit that includes the fix but the open PR has a trivial fix. It's missing attribution to Vim so I will not merge it.

**Closed** 2021-02-16 14:24 UTC
Labels: 0.kind bug-netrw, bug
