### ISSUE TITLE
When the NeoVim window is resized, terminal text is truncated and lost

### ISSUE THREAD

**Issue by techfishio** [neovim/neovim#8924] opened 2018-08-27 18:34 UTC
- **`nvim --version`:**

```
nvim --version
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTI
FY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=g
nu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARA
TIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180820-47777-1t89t8z/n
eovim-0.3.1/build/config -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/src -I/usr/local/include -I/usr/loca
l/opt/gettext/include -I/usr/include -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/build/src/nvim/auto -I/t
mp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"
```

- **Vim (version: ) behaves differently?**
- **Operating system/version:** macOS High Sierra 10.13.6
- **Terminal name/version:** iTerm2 3.2.0
- **`$TERM`:** xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```
1. Make NeoVim full screen
2. Open a terminal buffer in a vertically split window
3. Change your screen size (e.g. put NeoVim on an external monitor, disconnect it)
4. Change it back (e.g. reconnect the external monitor)

### Actual behaviour

Terminal text is truncated to a single character (see screenshot):
![nvim-terminal-cutoff](https://user-images.githubusercontent.com/1899850/44678300-ef7b2080-a9ec-11e8-9eb6-3d14bcd36dd8.png)

### Expected behaviour

Terminal text is not truncated, and thus lost into the either, when the NeoVim window is resized.

**Comment by justinmk** [comment] 2018-08-28 06:52
Duplicate of #4997

**Closed by justinmk** 2018-08-28 06:52 UTC
