### ISSUE TITLE
Problems building & installing .deb

### ISSUE THREAD

**Issue by AprilArcus** [neovim/neovim#24815] opened 2023-08-21 05:15 UTC
### Problem

Note: I am building neovim from the 0.9.1 tag on a Debian-based x86-64 system.

1.) Wrong install directory

When I follow the instructions to build and install neovim on my Debian-based machine at https://github.com/neovim/neovim/wiki/Building-Neovim#quick-start, I end up with neovim installed to `/usr/bin/nvim`, `/usr/share/nvim/runtime/`, `/usr/share/nvim/man1/nvim.1`, `/usr/share/locale/`  `/usr/share/icons/hicolor/128x128`. However, because the default install location is `/usr/local`, nvim will resort to

`fall-back for $VIM: "/usr/local/share/nvim"`

and fail to find its support files.

In order to fix this, `-D CPACK_PACKAGING_INSTALL_PREFIX=/usr/local` must be passed to `cpack` when generating the `.deb` archive.

The install scripts should derive this and `-D CMAKE_INSTALL_PREFIX` from the same source of truth.

2.) Wrong permissions

The build scripts generate files into `./build` with permissions 750. When `dpkg` moves them to `/usr/` or `/usr/local/` (as the case may be), it retains those permissions but sets the owner and group to root. As a result, when invoked as a non-superuser, neovim cannot read its own support files. These files should be generated with permissions 755 instead.

It looks like this is set up correctly in https://github.com/neovim/neovim/blob/v0.9.1/cmake/InstallHelpers.cmake, so I wonder if I'm doing something wrong.

3.) Wrong runtime path

After passing `-D CPACK_PACKAGING_INSTALL_PREFIX=/usr/local` and running `chmod -R o+rx` on all the support directories, I have a working `nvim` in `/usr/local/bin/nvim`, but it is still searching for support files in `/usr/local/share/nvim`, not `/usr/local/share/nvim/runtime`. As a result, I see

`E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim`

because the file is actually at `/usr/local/share/nvim/runtime/syntax/syntax.vim`.

### Steps to reproduce

see above

### Expected behavior

see above

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian

### Terminal name/version

kitty 0.29.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo / dpkg

**Comment by AprilArcus** [comment] 2023-08-21 17:01
Is it possible to look at the script used to generate https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable ?

**Comment by AprilArcus** [comment] 2023-08-22 20:32
Setting `umask 022` before building resolves (2)

**Comment by justinmk** [comment] 2023-09-12 12:41
> Is it appropriate to reference https://git.launchpad.net/neovim-ppa/tree/local.mk?

yes. That is considered third-party and unsupported, but it's a good reference for debian building.

**Comment by justinmk** [comment] 2023-10-11 23:27
@jamessan any advice here ?

**Comment by jamessan** [comment] 2023-10-12 00:01
Not really.  I don't use cpack, so not really familiar with how it works.  The official Debian packaging is available for reference.  I'm now only waiting for one more dependency to get accepted into Debian and I'll be able to finally get Debian's package update past 0.7.2.

**Comment by Benczak** [comment] 2024-01-03 20:09
How is it going to update past 0.7.2? :(

**Comment by jamessan** [comment] 2024-01-03 20:32
The packages are uploaded, but the tests are [hanging on most platforms](https://buildd.debian.org/status/package.php?p=neovim&suite=experimental) and I can't reproduce it when running the build manually.  You should be able to build from that yourself, if you want.

I'm going to close this issue, since it's nothing relevant to the project.

**Closed by jamessan** 2024-01-03 20:32 UTC
Labels: bug, build, distribution
