### ISSUE TITLE
API for interpreting a command line, including side-effects, as if the user had typed it

### ISSUE THREAD

**Issue by resolritter** [neovim/neovim#16516] opened 2021-12-04 09:18 UTC
### Feature already in Vim?

No

### Feature description

# Problem

Plugins such as https://github.com/VonHeikemen/fine-cmdline.nvim provide an alternate UI for the command line. The problem is that, for instance, if you type `s/foo/bar` there, it does not benefit from `inccommand` and other features triggered from native command line input.

# Solution

Implement a `nvim_eval_cmdline(text)` API which plugins can use to evaluate arbitrary command lines programmatically. Evaluating the command line this way incurs the relevant side-effects (e.g. `inccommand`) as if the user had typed the text in the native UI.

A first implementation can be made to serve plugins which reimplement the command line and therefore do not interact with the native input directly. For instance, if it's difficult to reason about `nvim_eval_cmdline` while the command line is active, make it a no-op in that situation and follow suit for any other tricky scenarios which do not cater to the aforementioned plugins, with the limitations and shortcomings being documented.

For ease of use, the API could include an extra parameter, as in `nvim_eval_cmdline(text, [should_execute])`, where `should_execute` is a boolean flag through which the text can be executed immediately, i.e. the equivalent of `<CR>`.

# Context

The idea of `setcmdline` has been brought up before in https://github.com/neovim/neovim/pull/5384#issuecomment-253723586

**Comment by chentau** [comment] 2021-12-04 18:02
This can already be done in a slightly hacky way via vim.on_key and vim.cmd.

**Comment by resolritter** [comment] 2021-12-04 23:20
> This can already be done in a slightly hacky way via vim.on_key and vim.cmd.

Is this referring to something similar to what's done in https://github.com/chentau/live.nvim/blob/e59eaa30c6a33c613cc53bb2e985117d5a4f7645/lua/live/init.lua#L18-L25 ?

```lua
local function execute_cmd(cmdline)
  local tick = vim.b.changedtick

  pcall(vim.cmd, cmdline)

  -- update_screen() is not called when in 
  -- command line mode, so force a redraw
  -- then undo the change right after
  vim.cmd("silent redraw!")
  if tick ~= vim.b.changedtick then
    vim.cmd("silent undo")
  end
end
```

How would that work with `inccommand`?

The way the feature is described here is less about "execute something ahead of time" and more about "interpret this command line as if the user had typed it manually". I don't see it as a similar approach to that of live.nvim.

**Comment by justinmk** [comment] 2022-04-23 16:01
Duplicate of #7370

**Closed by justinmk** 2022-04-23 16:01 UTC
Labels: enhancement, api
