### ISSUE TITLE
Add terminal emulator as clipboard backend

### ISSUE THREAD

**Issue by 0guanhua0** [neovim/neovim#19081] opened 2022-06-25 00:03 UTC
### Feature already in Vim?

No

### Feature description

https://github.com/ojroques/vim-oscyank

can we integrate OSC52 to copy text to the system clipboard from anywhere?
copy through ssh is a pain and the current backends only consider shell utility. we should also consider termianal emulator

**Comment by zeertzjq** [comment] 2022-06-25 00:08
Duplicate of #3344

**Closed by zeertzjq** 2022-06-25 00:08 UTC
Labels: enhancement, provider
