### ISSUE TITLE
Nvim + tmux show colors code in command line

### ISSUE THREAD

**Issue by danielgatis** [neovim/neovim#14440] opened 2021-04-25 18:45 UTC
- `nvim --version`: NVIM v0.5.0-dev+bb7d3790b
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version: macOS Big Sur (11.2.3)
- Terminal name/version:  alacritty 0.7.2 (5ac8060) / tmux 3.2
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

Open tmux and start nvim.

### Actual behaviour
Show a strange color code in the command line.

### Expected behaviour

Show the command line empty.
<img width="1429" alt="Screen Shot 2021-04-25 at 15 35 04" src="https://user-images.githubusercontent.com/7380/116005405-214d4680-a5dd-11eb-9090-6a1c1b1fc76a.png">

**Comment by mhinz** [comment] 2021-05-01 18:02
I suspect you installed tmux and alacritty via homebrew and that the issue only happens within tmux. I can't reproduce it here.

1. Does it work when starting the tmux session without your config? (`tmux -f /dev/null`)
2. Does it happen with `export TERM=tmux-256color` (in tmux)?

**Comment by danielgatis** [comment] 2021-05-01 21:41
```
Does it work when starting the tmux session without your config? (tmux -f /dev/null)
```
No. I got the same issue.

```
Does it happen with export TERM=tmux-256color (in tmux)?
```
Nope.

But when I am using the combo iterm2+tmux it works fine.

**Comment by mhinz** [comment] 2021-05-01 21:49
Ok.. does it even happen with `nvim -u NONE` in alacritty started via `alacritty --config-file /dev/null`?

**Comment by danielgatis** [comment] 2021-05-01 22:14
with `nvim -u NONE` + `alacritty --config-file /dev/null` + `tmux -f /dev/null`
<img width="1552" alt="Screen Shot 2021-05-01 at 19 10 48" src="https://user-images.githubusercontent.com/7380/116796257-80193100-aab1-11eb-988d-4ad1f5bf0959.png">

**Comment by mhinz** [comment] 2021-05-01 22:42
I guess the tmux server was still running, because that's clearly not the default tmux statusline. :)

**Comment by danielgatis** [comment] 2021-05-01 23:28
first of all: `tmux kill-server`
and: nvim -u NONE + alacritty --config-file /dev/null + tmux -f /dev/null

<img width="1552" alt="Screen Shot 2021-05-01 at 20 27 20" src="https://user-images.githubusercontent.com/7380/116797394-c96e7e00-aabb-11eb-8614-8d5158e8af4c.png">

**Comment by mhinz** [comment] 2021-05-02 09:58
Can you install Nvim 0.4.4 (from repo or Homebrew) and see if it's also happening there? Did it ever work for you in alacritty?

Since I can't reproduce it and since we had no one else having the same issue so far, I tend to think that it's somehow related to your environment. I have no idea where the `0000/0000/0000` is coming from (that's not a typical escape sequence I would expect in such issues), but the `^G` suggests that something tries to "ring the bell" in the terminal.

**Comment by mhinz** [comment] 2021-05-02 10:47
Try this _outside_ of tmux:

```
$ brew install ncurses
$ export TERM=alacritty
$ infocmp $TERM | head -n1
#	Reconstructed via infocmp from file: /usr/local/Cellar/ncurses/6.2/share/terminfo/61/alacritty
$ nvim ~/.tmux.conf
...
set-option -g  default-terminal   'tmux-256color'
...
$ tmux
$ nvim
```

Same issue>

**Comment by danielgatis** [comment] 2021-05-02 19:50
yep :(

**Comment by mhinz** [comment] 2021-05-03 01:10
Then I'm out of ideas.

The version `NVIM v0.5.0-dev+bb7d3790b` suggests that you downloaded the nigthly release from GitHub, is that correct? Would be interesting to know if it works for you if you build from the repo:

https://github.com/neovim/neovim/wiki/Installing-Neovim#install-from-source

**Comment by danielgatis** [comment] 2021-05-03 02:28
@mhinz 

This issue is introduced in this commit: https://github.com/neovim/neovim/commit/8ed0a0d4dbe1575a0a3bca0f6e8034bfb380b1ef

Take a look at the screenshot before this commit, there are no strange codes.
<img width="1552" alt="Screen Shot 2021-05-02 at 23 23 26" src="https://user-images.githubusercontent.com/7380/116836734-1296fe80-ab9e-11eb-925a-a0e51b00c679.png">

**Comment by danielgatis** [comment] 2021-05-03 16:11
same error here: https://github.com/neovim/neovim/issues/14298

**Comment by mhinz** [comment] 2021-05-03 17:47
@erw7 Here's another `set_bg` issue with tmux. I guess this can be closed in favor of https://github.com/neovim/neovim/issues/14298, right?

**Comment by dylanarmstrong** [comment] 2021-05-28 04:38
I believe this issue #14652 is related to this one.

**Comment by danielgatis** [comment] 2021-06-15 16:22
https://github.com/neovim/neovim/issues/14298#issuecomment-852187077

**Closed** 2021-07-07 19:22 UTC
Labels: bug, tui
