### ISSUE TITLE
bracketed paste inserts characters into nvim session

### ISSUE THREAD

**Issue by chris-conklin** [neovim/neovim#13749] opened 2021-01-13 21:11 UTC
When pasting into NVIM v0.5.0-dev I there are additional characters **^[[201^[[200~** added which cause other command keys to be misinterpreted and output chars to the screen. The only way to right the session is to paste a second time. Once the second paste takes place I can switch modes and type normally.

Example of what occurs: [https://pastebin.com/c60L06HE](https://pastebin.com/c60L06HE)

This occurs while accessing my headless CentOS 7 workstation where the binary was built via ssh from an Ubuntu-20.04 host with gnome-terminal. I have tested pasting with the scroll wheel as well as r/c and paste - both produce the same result. The very same setup with nvim 0.4.4 does not have the issue. 

This is occurring on nvim 0.5 with defaults 

I have determined that this happens between these two commits

**978857e0c** Merge pull request #12592 from jamessan/fix-mod-keys - The issue is not present
**97ffa158a** Merge pull request #12004 from @erw7 erw7/fix-paste - The issue is present

**Comment by erw7** [comment] 2021-02-21 08:54
I am not able to reproduce the phenomenon in my environment. Can you show me the nvim_paste.log that you created when the problem occurred according to https://github.com/neovim/neovim/issues/13921#issuecomment-782811093.

**Comment by justinmk** [comment] 2022-08-02 11:48
https://github.com/neovim/neovim/pull/16585 was another followup.

Closing since there was no reply.

**Closed by justinmk** 2022-08-02 11:48 UTC
Labels: bug, status:needs-response, status:needs-repro
