### ISSUE TITLE
Nightly is missing `macos` builds

### ISSUE THREAD

**Issue by kdheepak** [neovim/neovim#13176] opened 2020-10-28 07:45 UTC
Nightly is currently missing `macos` builds

<img width="1000" alt="Screen Shot 2020-10-28 at 1 45 17 AM" src="https://user-images.githubusercontent.com/1813121/97406696-3e6bbb80-18bf-11eb-9cfc-4fd60faaaf3c.png">

I'm not sure why though, I see that the CI on travis is passing fine.

**Comment by clason** [comment] 2020-10-28 08:02
Duplicate of the (pinned) issue #13146

**Closed by clason** 2020-10-28 08:02 UTC
Labels: bug, ci, duplicate

**Comment by kdheepak** [comment] 2020-10-28 08:06
My bad, I even scanned for previous issues but missed that one.
