### ISSUE TITLE
expression parser crashes when executing visual mapping

### ISSUE THREAD

**Issue by latricewilgus** [neovim/neovim#11789] opened 2020-01-29 20:56 UTC
In the following scenario neovim crashes with
```
src/nvim/viml/parser/expressions.c:1240: viml_pexpr_handle_bop: Assertion `bop_node_lvl != new_top_node_lvl || bop_node_ass == new_top_node_ass' failed.
```

Steps to reproduce:
Create a file "crashes_nvim.vim" with the content:
```
function! s:getPattern()
	" does not matter can even be empty.
endfunction

" Does not crash if <CR> is added to the end
vnoremap * :<C-U>/<C-R>=<SID>getPattern()
```
Then run the following command
```
nvim -u NONE -c 'source crashes_nvim.vim' -c 'execute "normal iae\<ESC>0vll**"'
```
Note that "normal" and not "normal!" is used.

Affected versions are:

* nvim-0.4.3 (latest stable)
* 406464fa6e6dbacca82746412b24308bc58ddbc7 (current head as of writing)

Under any one of the following conditions no crash happens:

* vim-8.1
* neovim-0.2.2
* Adding <CR> at the end of the vnoremap command
* Using a global function GetPattern() instead of a script-local s:getPattern()
* Replacing the '*' in the map command to 't', 'tt', or '-'

**Comment by justinmk** [comment] 2020-01-30 04:45
Duplicate of https://github.com/neovim/neovim/issues/7889

Someone needs to give human attention to https://github.com/neovim/neovim/pull/8421

**Closed by justinmk** 2020-01-30 04:45 UTC
Labels: bug, duplicate
