### ISSUE TITLE
`Assertion to_scroll >= 0 failed` on `:intro` with `cmdheight=0`

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#26713] opened 2023-12-22 14:33 UTC
### Problem

As in title. I get 
```
nvim: .../src/nvim/message.c:2345: msg_scroll_flush: Assertion `to_scroll >= 0' failed.
```
bt:
```cpp
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007f5e5cdc415f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007f5e5cd76472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f5e5cd604b2 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007f5e5cd603d5 in __assert_fail_base (fmt=0x7f5e5ced4dc8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5603e3a98d56 "to_scroll >= 0", 
    file=file@entry=0x5603e3ab9dd8 ".../src/nvim/message.c", line=line@entry=2345, function=function@entry=0x5603e3a6c2e0 <__PRETTY_FUNCTION__.0.lto_priv.47> "msg_scroll_flush") at ./assert/assert.c:92
#5  0x00007f5e5cd6f3a2 in __assert_fail (assertion=assertion@entry=0x5603e3a98d56 "to_scroll >= 0", file=file@entry=0x5603e3ab9dd8 ".../src/nvim/message.c", line=line@entry=2345, 
    function=function@entry=0x5603e3a6c2e0 <__PRETTY_FUNCTION__.0.lto_priv.47> "msg_scroll_flush") at ./assert/assert.c:101
#6  0x00005603e383096a in msg_scroll_flush () at .../src/nvim/message.c:2345
#7  0x00005603e391390d in ui_flush () at .../src/nvim/ui.c:533
#8  0x00005603e37d458f in inchar (buf=0x5603e3b928fd <typebuf_init+61> "", maxlen=203, wait_time=-1) at .../src/nvim/getchar.c:2797
#9  0x00005603e37d5cd4 in vgetorpeek (advance=advance@entry=true) at .../src/nvim/getchar.c:2695
#10 0x00005603e37d6007 in vgetc () at .../src/nvim/getchar.c:1473
#11 0x00005603e37d655e in safe_vgetc () at .../src/nvim/getchar.c:1642
#12 0x00005603e3833bb0 in wait_return (redraw=0) at .../src/nvim/message.c:1202
#13 0x00005603e37ac394 in do_cmdline (cmdline=<optimized out>, fgetline=0x5603e37bcc2c <getexline>, cookie=0x0, flags=0) at .../src/nvim/ex_docmd.c:865
#14 0x00005603e384a46c in nv_colon (cap=0x7ffdfb3e3df0) at .../src/nvim/normal.c:3215
#15 0x00005603e3849c12 in normal_execute (state=0x7ffdfb3e3d80, key=<optimized out>) at .../src/nvim/normal.c:1219
#16 0x00005603e38e600f in state_enter (s=0x7ffdfb3e3d80) at .../src/nvim/state.c:98
#17 0x00005603e384358d in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at .../src/nvim/normal.c:508
#18 0x00005603e380bf8e in main (argc=5, argv=<optimized out>) at .../src/nvim/main.c:637
```

### Steps to reproduce

- run `nvim --clean --cmd 'set cmdheight=0' `
- run `intro` command inside

### Expected behavior

No crash

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1933+g2151e781e

### Vim (not Nvim) behaves the same?

- 

### Operating system/version

Debian Sid

### Terminal name/version

tmux 3.3a-5, kitty 0.31.0

### $TERM environment variable

tmux-256color

### Installation

from repo

**Comment by zeertzjq** [comment] 2023-12-22 14:51
Duplicate of #26505

**Closed by zeertzjq** 2023-12-22 14:51 UTC
Labels: bug
