### ISSUE TITLE
nvim -e  <f-args> reads beyond newline

### ISSUE THREAD

**Issue by ds26gte** [neovim/neovim#8581] opened 2018-06-18 06:19 UTC
- `nvim --version`: v0.3.1-dev
- Vim (version: ) behaves differently? Yes, Vim 8.1.66 produces expected behavior
- Operating system/version: Ubuntu 18.04
- Terminal name/version: gnome-terminal 3.28.1
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

Have a file `j.txt` with the following single line as content:

```
The quick brown fox jumped over the lazy dog
```

```
nvim -u NORC -e -s $1 <<"EOF"

func! Htmlentitiesf(...)
  for l:item in a:000
    for l:c in split(l:item, '\zs')
      exec 'sil! %s/' . l:c . '/' . printf('\&#x%x;', char2nr(l:c)) . '/g'
    endfor
  endfor
endfunc

com! -nargs=* Htmlentities call Htmlentitiesf(<f-args>)

Htmlentities ‘’
Htmlentities “”

x

EOF

```

### Actual behaviour

The contents of the file `j.txt` are changed to
```
&#x74;h&#x65; qu&#x69;ck brow&#x6&#x65;; fox ju&#x6d;p&#x73; ov&#x65;r &#x74;h&#x65; &#x6c;azy dog
```

It would appear that the first call to `Htmlentities` reads not just its line but the line following, so it's assuming 'Htmlentities' is an argument as well, so it seeks to transform the characters from `Htmlentities` as well. (The `n` in `brown` is especially mangled.)

### Expected behaviour

The contents of `j.txt` should be unaltered. Only the smart quotes are supposed to be changed to HTML entities, and the file has no smart quotes.

**Comment by justinmk** [comment] 2018-06-18 08:19
That's weird, we have tests using -es with viml input.

Does it work on Nvim 0.2.2 ?

**Comment by ds26gte** [comment] 2018-06-18 12:37
In reply to your question: Yes, it works fine in Nvim 0.2.2.  (This is just an artificially made minimal example of a larger program that I've been using for some time. It must have stopped working during one of my updates.)

**Comment by glacambre** [comment] 2021-06-05 19:38
I can't reproduce this bug on master, so it's probably fixed. Closing :).

**Closed by glacambre** 2021-06-05 19:38 UTC
Labels: bug-regression, input
