### ISSUE TITLE
lsp: outdated diagnostics show up, slowly,  after they have been fixed

### ISSUE THREAD

**Issue by mrnugget** [neovim/neovim#14161] opened 2021-03-19 08:38 UTC
- Using the nightly build installed through `apt`, updated daily.
- `nvim --version`:
```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-h0XGpv/neovim-0.5.0+ubuntu2+git202103170423-0ab88c2ea-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-h0XGpv/neovim-0.5.0+ubuntu2+git202103170423-0ab88c2ea-d569569c9/build/config -I/build/neovim-h0XGpv/neovim-0.5.0+ubuntu2+git202103170423-0ab88c2ea-d569569c9/src -I/build/neovim-h0XGpv/neovim-0.5.0+ubuntu2+git202103170423-0ab88c2ea-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-h0XGpv/neovim-0.5.0+ubuntu2+git202103170423-0ab88c2ea-d569569c9/build/src/nvim/auto -I/build/neovim-h0XGpv/neovim-0.5.0+ubuntu2+git202103170423-0ab88c2ea-d569569c9/build/include
Compiled by buildd@lcy01-amd64-021

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Ubuntu 20.10
- Terminal name/version: `kitty 0.18.3`
- `$TERM`: `screen-256color`

### LSP config

`~/.vim/lua/lsp.lua`:
```lua
local lspconfig = require('lspconfig')
local completion = require('completion')

local on_attach = function(client)
  completion.on_attach(client)
  client.config.flags.allow_incremental_sync = true
end

local servers = {
  gopls = {
    gopls = {
      completeUnimported = true,
      analyses = {
        unusedparams = false,
      },
    }
  },
}

for ls, settings in pairs(servers) do
  lspconfig[ls].setup {
    on_attach = on_attach,
    settings = settings,
  }
end

require('nlua.lsp.nvim').setup(lspconfig, {
  on_attach = on_attach
})

vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
  vim.lsp.diagnostic.on_publish_diagnostics, {
    virtual_text = true,
    signs = true,
    update_in_insert = true,
  }
)
```

`~/.vimrc`:

```viml
if has('nvim')
  " If we're using Neovim's builtin LSP support, let's disable a lot of the
  " auto-functionality in vim-go:
  let g:go_def_mapping_enabled = 0
  let g:go_term_enabled = 1
  let g:go_diagnostics_enabled = 0
  let g:go_code_completion_enabled = 0
  let g:go_fmt_autosave = 0
  let g:go_mod_fmt_autosave = 0
  let g:go_doc_keywordprg_enabled = 0
  let g:go_gopls_enabled = 0
  let g:go_diagnostics_enabled = 0

  " Configure LSP
  lua require("lsp")

  " Set updatetime for CursorHold
  " 300ms of no cursor movement to trigger CursorHold
  set updatetime=300
  " Show diagnostic popup on cursor hold
  autocmd CursorHold * lua vim.lsp.diagnostic.show_line_diagnostics()
  " have a fixed column for the diagnostics to appear in
  " this removes the jitter when warnings/errors flow in
  set signcolumn=yes
  " Enable type inlay hints
  autocmd CursorMoved,InsertLeave,BufEnter,BufWinEnter,TabEnter,BufWritePost *
  \ lua require'lsp_extensions'.inlay_hints{ prefix = '', highlight = "Whitespace", enabled = {"ChainingHint", "TypeHint", "ParameterHint"} }
endif

```
### Actual behaviour

Diagnostics show up slowly even after fixing the error that caused them. It seems like they're queued up somewhere:

https://user-images.githubusercontent.com/1185253/111753036-acc51080-8896-11eb-90b3-b14924b93044.mp4

https://user-images.githubusercontent.com/1185253/111753039-ad5da700-8896-11eb-8243-e414789def7b.mp4

### Expected behaviour

After changing the text I would expect old diagnostics to be ignored.

---

Let me know if you need more info.

I have a hunch that this is a newish problem, because it got worse in the past 1-2 weeks.

**Comment by mrnugget** [comment] 2021-03-19 08:40
I wonder whether it's related to https://github.com/neovim/neovim/pull/14119 and the change in https://github.com/neovim/neovim/commit/e4e51c69d740eb7dc4f3bf0479a92ac6442d979a.

**Comment by mjlbach** [comment] 2021-03-19 08:45
It's possible. The incremental sync shouldn't be sending changes to the server any more frequently than our prior implementation (which sent the full buffer on each document change). One option would be to try disabling it to see if the performance is any better. Using your config:


```lua
for ls, settings in pairs(servers) do
  lspconfig[ls].setup {
    on_attach = on_attach,
    on_init = function(client)
        client.config.flags = {
          allow_incremental_sync = false;
        }
     end;
    settings = settings,
  }
end
```

**Comment by mrnugget** [comment] 2021-03-19 09:04
That doesn't seem to help, no. 

https://user-images.githubusercontent.com/1185253/111756395-72f60900-889a-11eb-8ca4-f9f0d1469b24.mp4

**Comment by mjlbach** [comment] 2021-03-19 09:12
Do you have an example project I can reproduce this with, or can you reproduce this on any file? Is it only happening with gopls? I'll try to look into this on the weekend.

#14119 will definitely help, but I'm concerned about the possibility of a performance regression. With incremental sync disabled, nothing should have changed in the last couple weeks.

**Comment by mrnugget** [comment] 2021-03-19 09:20
So far I've only seen this happen with a large Go codebase and `gopls`. But you can see hints of this even in slightly smaller projects, such as https://github.com/sourcegraph/src-cli. If you open that, with `gopls v0.6.8`, and edit, for example, `internal/batches/executor.go` and add invalid things really fast you can see how diagnostics are trying to catch up:

https://user-images.githubusercontent.com/1185253/111758266-915d0400-889c-11eb-9a08-09a20ab39691.mp4

I've used the builtin LSP support the last few weeks in that `src-cli` repository and everything was _really fast_ and snappy as hell. It still is faster compared to working in github.com/sourcegraph/sourcegraph (which is where I recorded the videos above), but something feels off.

Let me know if I can help debug this more.

**Comment by mfussenegger** [comment] 2021-03-19 09:26
Maybe we've to use the `version` property that's part of the diagnostic response.
If it's there we could ignore the result if the diagnostics are for an outdated version.

I suspect something like this is happening:

- language server can't keep up with the diagnostic computation given the rate of changes
- language server does not interrupt previous diagnostic computations on new changes
- language server sends diagnostics per change
- client processes the diagnostics as they arrive.

**Comment by mjlbach** [comment] 2021-03-19 09:30
It doesn't seem quite as bad on my computer. Is completion-nvim adding some overhead?

https://user-images.githubusercontent.com/13316262/111759512-e710bc80-885a-11eb-9c68-1ce020636bd4.mov

@mfussenegger I agree we could be smarter about both delaying text updates (like your pending PR) and also debouncing diagnostics.

**Comment by mrnugget** [comment] 2021-03-19 09:36
> It doesn't seem quite as bad on my laptop (2014 mbp retina, so nvme drive but generally older). I'm on a slightly older gopls (v0.6.2). Is completion-nvim adding some overhead?

By disabling completion it got faster, I think. But it still feels off a bit.

You could try playing around with the `enterprise/internal/batches/store/changesets_test.go` file in github.com/sourcegraph/sourcegraph, which is a large Go codebase, but should work out of the box with the standard Go tooling.

> I suspect something like this is happening: [...]

That _feels_ true to me (someone who doesn't know the internals of what's happening here): outdated diagnostics hang around and are then slowly replaced.

**Comment by mjlbach** [comment] 2021-03-19 09:42
> Maybe we've to use the version property that's part of the diagnostic response.

The one concern I have with this approach is it will likely just indefinitely defer diagnostics while a user is typing. I'm wondering if just debouncing the text_document_did_change would be enough to address point 1. We should check what vscode does.

**Comment by mrnugget** [comment] 2021-03-19 10:13
Recorded another video that might make the behaviour more visible and thus easy to digest (and also give an impression of how this is not just "could be a bit faster" but rather "this is unusable for me right now")

https://user-images.githubusercontent.com/1185253/111764840-f5cf9180-88a3-11eb-8d5b-ce15bb32b6a0.mp4

**Comment by mjlbach** [comment] 2021-03-19 10:21
Thank you! I definitely want to address this. I haven't managed to reproduce yet on the sourcegraph codebase, but I'm working on it. 

If you have time you can try rolling back to an earlier commit like c12ea02e0b5d465e2c4b7d8bba028d069bdf7008 and see if the problem is gone for you. Otherwise, if it's not a regression, there are some optimizations we can start looking at.

**Comment by mrnugget** [comment] 2021-03-19 10:43
> If you have time you can try rolling back to an earlier commit like [c12ea02](https://github.com/neovim/neovim/commit/c12ea02e0b5d465e2c4b7d8bba028d069bdf7008) and see if the problem is gone for you. Otherwise, if it's not a regression, there are some optimizations we can start looking at.

Thanks! I'll try that if I find the time this weekend.

Regarding reproducing: my complete vim and lsp config is here: https://github.com/mrnugget/vimconfig/blob/master/lua/lsp.lua Note that the `lsp.lua` file in the repository is not what I used locally to debug this (where I've flipped incremental sync on/off, etc.)

**Comment by mjlbach** [comment] 2021-03-19 10:45
Oh interesting, another thing to try would be disabling lsp_extension's workspace diagnostic. I can try reproducing with your config as well.

**Comment by mrnugget** [comment] 2021-03-19 10:49
> Oh interesting, another thing to try would be disabling lsp_extension's workspace diagnostic.

I've disabled those locally when recording the videos here/trying to reproduce this. So it was more like the config in https://github.com/neovim/neovim/issues/14161#issue-835703027

**Comment by mjlbach** [comment] 2021-03-19 10:49
Got it! Sorry for the noise.

**Comment by mrnugget** [comment] 2021-03-20 16:48
Okay, here are my findings after checking out 2-3 older commits (going back max. 8 weeks) and editing the same file in the same repository as in the videos above: no difference. I also tried to see whether there was a regression in `neovim/nvim-lspconfig` and went back a few weeks in that plugin. Again: no difference.

**But** what I did find out is that my statement from above

> By disabling completion it got faster, I think. But it still feels off a bit.

contained a huge hint.

After having tested on multiple commits I've had the test workflow down and could reliably reproduce the behaviour of diagnostics text appearing super slow, character by character. With **completion disabled though** the character-by-character slowness is gone. There's still something glitchy, most likely what @mfussenegger described in https://github.com/neovim/neovim/issues/14161#issuecomment-802684054, and I think that should be fixed, but it seems that `nvim-lua/completion-nvim` is a bottleneck and slows processing of LSP messages down a lot.

**Comment by mjlbach** [comment] 2021-03-20 16:52
Thank you so much for digging into this, and I'm happy it's not a regression!

I believe the numerous completion requests sent by `nvim-lua/completion-nvim` will add quite a bit of overhead. I think we should go ahead and merge @mfussenegger's debounce PR as I think that is the most immediate solution.

As an aside, `hrsh7th/nvim-compe` is seeing a lot more development than `completion-nvim` and would generally recommend that. I believe they will trigger a comparable number of server requests, but I'm not positive.

**Comment by mrnugget** [comment] 2021-03-20 16:53
> I think we should go ahead and merge @mfussenegger's debounce PR as I think that is the most immediate solution.

Without knowing the details: I agree that debouncing (or cancelling outdated requests, etc.) seems like the correct choice.

> As an aside, `hrsh7th/nvim-compe` is seeing a lot more development than `completion-nvim` and would generally recommend that. I believe they will trigger a comparable number of server requests, but I'm not positive.

Haha, thank you! I was just thinking "okay, is there another completion plugin I can try?"

**Comment by mrnugget** [comment] 2021-03-20 17:22
(Sidenote update: `nvim-compe` feels a bit faster, although it's still possible that some outdated diagnostics hang around when completing, changing in and out of insert mode, etc.)

**Comment by bluz71** [comment] 2021-03-28 07:19
> Is completion.nvim adding some overhead?

In my experience, definitely yes. I switched over to [nvim-compe](https://github.com/hrsh7th/nvim-compe) and it is a much smoother less laggy experience (whilst doing the same job).

The performance issue of completion.nvim is [noted here](https://github.com/nvim-lua/completion-nvim/issues/203).

nvim-compe is the preferred auto-completion manager for Neovim LSP these days.

**Comment by copy** [comment] 2021-09-06 05:05
I think this is not only caused by auto-completion but also by neovim sending `textDocument/didChange` events while making changes in insert mode (rather than when leaving insert mode). I can't seem to find any way to disable this behaviour. `update_in_insert` turns off display of diagnostics in insert mode, but if you leave insert mode quickly after typing, neovim briefly shows an old diagnostic.

**Comment by mjlbach** [comment] 2021-09-06 05:06
flags.debounce_text_changes in the args to start_client is what you are looking for. See help start_client

**Comment by copy** [comment] 2021-09-06 05:24
@mjlbach Even with `debounce_text_changes` neovim sends `textDocument/didChange` in insert mode.

**Comment by mjlbach** [comment] 2021-09-06 05:25
It does, if you're using autocompletion plugins they will trigger flushing the cache (happens on each request), or after the debounce window

**Comment by copy** [comment] 2021-09-06 05:51
What I'm saying is that it shouldn't (or should be configurable to not do it), since it causes this issue. It should (be configurable to) send `textDocument/didChange` only when leaving text mode, so that users don't see stale diagnostics, as shown in this thread.

**Comment by mjlbach** [comment] 2021-09-06 06:00
Just to be more explicit, we have to flush the cached text changes when a `request` is made from the client to server (such as `signature_help`, `hover`, `completion`, `definition`) because otherwise the server response would have been derived from an out of date copy of the text document, and therefore be invalid. 

We could add an additional option like `debounce_text_changes`, that debounces text changes until leaving insert mode. Practically speaking , I don't think this will affect many users, as things like `lsp_signature.nvim` and `nvim-cmp` trigger requests extremely frequently.

**Comment by copy** [comment] 2021-09-08 04:10
> I'm curious why a high debounce_text_changes interval is not sufficient?

I see two reasons:

1. It basically doubles the latency of getting diagnostics. If my lsp takes 1 second to produce a diagnostic, I need to set `debounce_text_changes` to 1 second to avoid the effect of queued up diagnostics slowly playing back. Then the new (worst-case) latency is 2 seconds (1 second debounce and 1 second for the lsp to respond).
2. Most intermediate changes are false positive syntax/type errors anyway.

However, I'm starting to think that this could be fixed on the side of the lsp server. Do you think in this scenario (the client sending `textDocument/didChange` faster than the lsp server being able to compute diagnostic responses), the lsp server should handle `textDocument/didChange` in batches and send a single diagnostic? (that is, is it legal in the protocol or would it break any expectations from lsp clients?)

**Comment by mjlbach** [comment] 2021-09-08 04:21
> It basically doubles the latency of getting diagnostics. If my lsp takes 1 second to produce a diagnostic, I need to set debounce_text_changes to 1 second to avoid the effect of queued up diagnostics slowly playing back. Then the new (worst-case) latency is 2 seconds (1 second debounce and 1 second for the lsp to respond).

A little confused by this, as the same argument would apply if we debounced text changes until leaving insert mode. To clarify, there are no queued up diagnostics being played back. The diagnostic notifications are sent independently (but triggered) by when we sent textDocument/didChange notifications from client -> server. 

Some servers have poor runtime characteristics when they receive many updates, which is why we have the debounce option. It's also definitely the case that the issue varies by server. clangd/hls/pyright being on one end of the spectrum, the theia typescript language server

**Comment by copy** [comment] 2021-09-17 03:03
> A little confused by this, as the same argument would apply if we debounced text changes until leaving insert mode.

When debouncing with a timer of a second, the `didChange` event is sent to the lsp server one second after the last key is pressed (worst case). My proposal would send the `didChange` event immediately when insert mode is exited.

That said, I now think this is a lsp server issue (which are slow and/or queue up `didChange` events), and `debounce_text_changes` is good enough for dealing with such language servers.

**Comment by mjlbach** [comment] 2021-10-05 17:02
@mrnugget I've made additional performance improvements over the last month (most recently today) that should help with this issue. I would also ensure you are using a debounce of at least 150ms. Please let me know if you are still experiencing this, because I may have to dig into gopls :)

**Comment by mjlbach** [comment] 2021-10-06 06:01
@mrnugget The changes should be on master, so please let me know next time you rebuild! For now, I'm going to close the issue. There are some related tracking issues on various performance quirks but I *think* this one is fixed at least (although do feel free to reopen if otherwise!).

**Closed by mjlbach** 2021-10-06 06:01 UTC
Labels: bug, status:needs-response, lsp
