### ISSUE TITLE
tui_flush: Assertion `r.bot <= grid->height && r.right <= grid->width' failed.  (via redraw_custom_statusline)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#11951] opened 2020-02-26 19:08 UTC
> nvim: ../src/nvim/tui/tui.c:1186: tui_flush: Assertion `r.bot <= grid->height && r.right <= grid->width' failed.

```
(gdb) thread apply all bt

Thread 2 (Thread 0x7f28519b6780 (LWP 81095)):
#0  modifier_len (cmd=0x55c2a1dc2bf4 "let options = a:0 ? a:1 : {}") at ../src/nvim/ex_docmd.c:2804
#1  0x000055c2a06d755d in has_loop_cmd (p=0x55c2a1dc2bf4 "let options = a:0 ? a:1 : {}") at ../src/nvim/ex_eval.c:2041
#2  0x000055c2a06bf1ed in do_cmdline (cmdline=0x0, fgetline=0x55c2a066c932 <get_func_line>, cookie=0x55c2a1988410, flags=7) at ../src/nvim/ex_docmd.c:572
#3  0x000055c2a066bb05 in call_user_func (fp=0x55c2a17c8660, argcount=2, argvars=0x7ffcf664a310, rettv=0x7ffcf664a9e0, firstline=20, lastline=20, selfdict=0x0) at ../src/nvim/eval.c:12373
#4  0x000055c2a065ce8b in call_func (funcname=0x55c2a1084da0 "neomake#statusline#get", len=22, rettv=0x7ffcf664a9e0, argcount_in=2, argvars_in=0x7ffcf664a310, argv_func=0x0, firstline=20, lastline=20, doesrange=0x7ffcf664a4cc, evaluate=true, partial=0x0, selfdict_in=0x0) at ../src/nvim/eval.c:6389
#5  0x000055c2a065c508 in get_func_tv (name=0x55c2a1084da0 "neomake#statusline#get", len=22, rettv=0x7ffcf664a9e0, arg=0x7ffcf664a970, firstline=20, lastline=20, doesrange=0x7ffcf664a4cc, evaluate=1, partial=0x0, selfdict=0x0) at ../src/nvim/eval.c:6141
#6  0x000055c2a0657cd6 in eval7 (arg=0x7ffcf664a970, rettv=0x7ffcf664a9e0, evaluate=1, want_string=0) at ../src/nvim/eval.c:4321
#7  0x000055c2a065740f in eval6 (arg=0x7ffcf664a970, rettv=0x7ffcf664a9e0, evaluate=1, want_string=0) at ../src/nvim/eval.c:4031
#8  0x000055c2a0656ebf in eval5 (arg=0x7ffcf664a970, rettv=0x7ffcf664a9e0, evaluate=1) at ../src/nvim/eval.c:3879
#9  0x000055c2a0656119 in eval4 (arg=0x7ffcf664a970, rettv=0x7ffcf664a9e0, evaluate=1) at ../src/nvim/eval.c:3615
#10 0x000055c2a0655f44 in eval3 (arg=0x7ffcf664a970, rettv=0x7ffcf664a9e0, evaluate=1) at ../src/nvim/eval.c:3533
#11 0x000055c2a0655d9e in eval2 (arg=0x7ffcf664a970, rettv=0x7ffcf664a9e0, evaluate=1) at ../src/nvim/eval.c:3464
#12 0x000055c2a0655bbb in eval1 (arg=0x7ffcf664a970, rettv=0x7ffcf664a9e0, evaluate=1) at ../src/nvim/eval.c:3391
#13 0x000055c2a0655aed in eval0 (arg=0x55c2a1c1777d "neomake#statusline#get(bufnr, { 'format_running': '… ({{running_job_names}})', 'format_loclist_ok': (a:active ? '%#NeomakeStatusGood#' : '%#NeomakeStatusGoodNC#').'✓%#NeomakeStatusReset#', 'format"..., rettv=0x7ffcf664a9e0, nextcmd=0x7ffcf664aac8, evaluate=1) at ../src/nvim/eval.c:3351
#14 0x000055c2a065109a in ex_let_const (eap=0x7ffcf664aac0, is_const=false) at ../src/nvim/eval.c:1524
#15 0x000055c2a0650d13 in ex_let (eap=0x7ffcf664aac0) at ../src/nvim/eval.c:1452
#16 0x000055c2a06c316c in do_one_cmd (cmdlinep=0x7ffcf664ae00, flags=7, cstack=0x7ffcf664af20, fgetline=0x55c2a066c932 <get_func_line>, cookie=0x55c2a1adb950) at ../src/nvim/ex_docmd.c:2248
#17 0x000055c2a06bf34b in do_cmdline (cmdline=0x0, fgetline=0x55c2a066c932 <get_func_line>, cookie=0x55c2a1adb950, flags=7) at ../src/nvim/ex_docmd.c:614
#18 0x000055c2a066bb05 in call_user_func (fp=0x55c2a1107de0, argcount=2, argvars=0x7ffcf664bad0, rettv=0x7ffcf664c180, firstline=20, lastline=20, selfdict=0x0) at ../src/nvim/eval.c:12373
#19 0x000055c2a065ce8b in call_func (funcname=0x55c2a1dbcfb0 "MyStatusLine", len=12, rettv=0x7ffcf664c180, argcount_in=2, argvars_in=0x7ffcf664bad0, argv_func=0x0, firstline=20, lastline=20, doesrange=0x7ffcf664bc8c, evaluate=true, partial=0x0, selfdict_in=0x0) at ../src/nvim/eval.c:6389
#20 0x000055c2a065c508 in get_func_tv (name=0x55c2a1dbcfb0 "MyStatusLine", len=12, rettv=0x7ffcf664c180, arg=0x7ffcf664c130, firstline=20, lastline=20, doesrange=0x7ffcf664bc8c, evaluate=1, partial=0x0, selfdic--Type <RET> for more, q to quit, c to continue without paging--c
t=0x0) at ../src/nvim/eval.c:6141
#21 0x000055c2a0657cd6 in eval7 (arg=0x7ffcf664c130, rettv=0x7ffcf664c180, evaluate=1, want_string=0) at ../src/nvim/eval.c:4321
#22 0x000055c2a065740f in eval6 (arg=0x7ffcf664c130, rettv=0x7ffcf664c180, evaluate=1, want_string=0) at 
../src/nvim/eval.c:4031
#23 0x000055c2a0656ebf in eval5 (arg=0x7ffcf664c130, rettv=0x7ffcf664c180, evaluate=1) at ../src/nvim/eval.c:3879
#24 0x000055c2a0656119 in eval4 (arg=0x7ffcf664c130, rettv=0x7ffcf664c180, evaluate=1) at ../src/nvim/eval.c:3615
#25 0x000055c2a0655f44 in eval3 (arg=0x7ffcf664c130, rettv=0x7ffcf664c180, evaluate=1) at ../src/nvim/eval.c:3533
#26 0x000055c2a0655d9e in eval2 (arg=0x7ffcf664c130, rettv=0x7ffcf664c180, evaluate=1) at ../src/nvim/eval.c:3464
#27 0x000055c2a0655bbb in eval1 (arg=0x7ffcf664c130, rettv=0x7ffcf664c180, evaluate=1) at ../src/nvim/eval.c:3391
#28 0x000055c2a0655aed in eval0 (arg=0x55c2a1d60642 "MyStatusLine(4, 1)", rettv=0x7ffcf664c180, nextcmd=0x0, evaluate=1) at ../src/nvim/eval.c:3351
#29 0x000055c2a064fd9d in eval_to_string (arg=0x55c2a1d60642 "MyStatusLine(4, 1)", nextcmd=0x0, convert=0) at ../src/nvim/eval.c:933
#30 0x000055c2a064ff26 in eval_to_string_safe (arg=0x55c2a1d60642 "MyStatusLine(4, 1)", nextcmd=0x0, use_sandbox=0) at ../src/nvim/eval.c:972
#31 0x000055c2a061f091 in build_stl_str_hl (wp=0x55c2a18404f0, out=0x7ffcf664dea0 " ~/src/pdbpp/.venv/lib/python3.8/site-packages/pip/_internal/utils/setuptools_build.py   simpler-pth", ' ' <repeats 42 times>, "? 20: 1 [14.4]", outlen=4096, fmt=0x55c2a1d60640 "%!MyStatusLine(4, 1)", use_sandbox=0, fillchar=32 ' ', maxwidth=159, hltab=0x7ffcf664d220, tabtab=0x7ffcf664d720) at ../src/nvim/buffer.c:3387
#32 0x000055c2a07fc6b4 in win_redr_custom (wp=0x55c2a18404f0, draw_ruler=0) at ../src/nvim/screen.c:5326
#33 0x000055c2a07fc078 in redraw_custom_statusline (wp=0x55c2a18404f0) at ../src/nvim/screen.c:5143
#34 0x000055c2a0800fda in showruler (always=0) at ../src/nvim/screen.c:7125
#35 0x000055c2a0778f09 in normal_redraw (s=0x7ffcf664efb0) at ../src/nvim/normal.c:1280
#36 0x000055c2a0779022 in normal_check (state=0x7ffcf664efb0) at ../src/nvim/normal.c:1326
#37 0x000055c2a084a40b in state_enter (s=0x7ffcf664efb0) at ../src/nvim/state.c:28
#38 0x000055c2a0776d47 in normal_enter (cmdwin=false, noexmode=false) at ../src/nvim/normal.c:463
#39 0x000055c2a0733a7e in main (argc=2, argv=0x7ffcf664f348) at ../src/nvim/main.c:569

Thread 1 (Thread 0x7f2851578700 (LWP 81096)):
#0  0x00007f2851be9ce5 in raise () from /usr/lib/libc.so.6
#1  0x00007f2851bd3857 in abort () from /usr/lib/libc.so.6
#2  0x00007f2851bd3727 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007f2851be2426 in __assert_fail () from /usr/lib/libc.so.6
#4  0x000055c2a0872478 in tui_flush (ui=0x55c2a0db5040) at ../src/nvim/tui/tui.c:1186
#5  0x000055c2a087b048 in ui_bridge_flush_event (argv=0x7f2851577748) at src/nvim/auto/ui_events_bridge.generated.h:109
#6  0x000055c2a06a2398 in multiqueue_process_events (this=0x7f284c000d30) at ../src/nvim/event/multiqueue.c:157
#7  0x000055c2a06a172b in loop_poll_events (loop=0x7f2851577890, ms=-1) at ../src/nvim/event/loop.c:70
#8  0x000055c2a086fd14 in tui_main (bridge=0x55c2a0db5160, ui=0x55c2a0db5040) at ../src/nvim/tui/tui.c:442
#9  0x000055c2a087bd94 in ui_thread_run (data=0x55c2a0db5160) at ../src/nvim/ui_bridge.c:104
#10 0x00007f2851fb046f in start_thread () from /usr/lib/libpthread.so.0
#11 0x00007f2851cad3d3 in clone () from /usr/lib/libc.so.6
```

NVIM v0.5.0-396-gc036e24f3-dirty
Related: https://github.com/neovim/neovim/issues/8774
Maybe also related: https://github.com/neovim/neovim/issues/11240 (reminded me of that)

/cc @bfredl

**Comment by glacambre** [comment] 2021-06-07 04:57
@blueyed did you have a reproducer for these? Both #8774 and #11240 are closed so I'm tempted to close this issue.

**Comment by dundargoc** [comment] 2022-04-18 10:22
I gave in to glacambre's temptation. I assume this has been solved, can reopen if it turns out it hasn't.

**Closed by dundargoc** 2022-04-18 10:22 UTC
Labels: tui, bug-crash
