### ISSUE TITLE
vim/treesitter.lua:191: invalid end error rendered as virtual text

### ISSUE THREAD

**Issue by sanga** [neovim/neovim#12588] opened 2020-07-03 06:30 UTC
- `nvim --version`:
```
NVIM v0.5.0-577-g48ac77a14
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-926e4ea1-1710-4627-a936-0e46d2a8c227

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: linux/ubuntu 19.10
- Terminal name/version: alacritty 0.5.0-dev (8688e47)
- `$TERM`: alacritty

### Steps to reproduce using `nvim -u NORC`

I haven't tried yet to repro this in `NORC`-mode

### Actual behaviour

The following lua error gets dumped out into my editor i.e. inline with my code as virtual text I guess.

```
    5     @pytest.fixture(scope="class", autouse=True) Error executing lua: ..._vimEQiGjG/usr/share/nvim/runtime/lua/vim/treesitter.lua:191: invalid end
```

Sorry I don't have nice repro steps for this, it's appears sporadically whilst editing.

### Expected behaviour

No internal lua errors as virtual text.

**Comment by sanga** [comment] 2020-07-03 06:42
So this may perhaps be due to plugins and configuration I have. (Guessing a little but....) relevant plugins would be:

```
Plug 'neovim/nvim-lsp'
Plug 'haorenW1025/completion-nvim'
Plug 'haorenW1025/diagnostic-nvim'
Plug 'steelsojka/completion-buffers'
```

and some (semi-randomly chosen) config:

```
:lua << EOF
  on_attach_vim = function()
    require'completion'.on_attach()
    require'diagnostic'.on_attach()
  end
  local nvim_lsp = require('nvim_lsp')
  nvim_lsp.pyls_ms.setup{
    init_options = {
      interpreter = {
        properties = {
          InterpreterPath = "/usr/bin/python3.7",
          Version = "3.7"
        }
      }
    },
    root_dir = nvim_lsp.util.root_pattern('pylintrc'),
    on_attach=on_attach_vim
  }
  nvim_lsp.rust_analyzer.setup{}
  nvim_lsp.jsonls.setup{}
  nvim_lsp.dockerls.setup{}
  nvim_lsp.bashls.setup{}
  nvim_lsp.diagnosticls.setup{}
  nvim_lsp.terraformls.setup{}
  nvim_lsp.sumneko_lua.setup{}
EOF

nnoremap <silent> <Leader>dec <cmd>lua vim.lsp.buf.declaration()<CR>
nnoremap <silent> <Leader>def <cmd>lua vim.lsp.buf.definition()<CR>
nnoremap <silent> <Leader>hov <cmd>lua vim.lsp.buf.hover()<CR>
nnoremap <silent> <Leader>imp <cmd>lua vim.lsp.buf.implementation()<CR>
nnoremap <silent> <Leader>sig <cmd>lua vim.lsp.buf.signature_help()<CR>
nnoremap <silent> <Leader>ref <cmd>lua vim.lsp.buf.references()<CR>

" completions
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
set shortmess+=c
let g:completion_enable_fuzzy_match = 1
" let g:completion_matching_strategy_list = ['exact', 'substring', 'fuzzy']
let g:completion_matching_strategy_list = ['fuzzy']
let g:diagnostic_enable_virtual_text = 1
let g:completion_auto_change_source = 1
let g:completion_enable_auto_popup = 1
let g:completion_enable_auto_hover = 1
let g:completion_enable_auto_signature = 1
let g:completion_chain_complete_list = {
            \ 'default' : {
            \   'default': [
            \       {'complete_items': ['lsp', 'buffer']},
            \       {'mode': '<c-p>'},
            \       {'mode': '<c-n>'}],
            \   'comment': [],
            \   'string' : [
            \       {'complete_items': ['path']}]lua <<EOF
require'nvim-treesitter.configs'.setup {
    highlight = {
        enable = true,
    },
    incremental_selection = {
        enable = true,
        keymaps = {                       -- mappings for incremental selection (visual mappings)
          init_selection = 'gnn',         -- maps in normal mode to init the node/scope selection
          node_incremental = "grn",       -- increment to the upper named parent
          scope_incremental = "grc",      -- increment to the upper scope (as defined in locals.scm)
          node_decremental = "grm",      -- decrement to the previous node
        }
    },
}
EOF

highlight link TSError Normal
            \   }}

```

**Comment by vigoux** [comment] 2020-07-03 07:27
Hi thanks for reporting this ! You are actually facing a well known error with treesitter integration.
One thing that will help us in fixing that would be to have the actual edit that caused that error.
The previously reported edits are:
- `~`
- I think that we have `o` and `O` that can cause problem sometimes.

A thing you can do is try https://github.com/neovim/neovim/pull/12568 to see if that solves your issue.

**Comment by vigoux** [comment] 2020-07-03 07:28
And the problematic plugin here would be `nvim-treesitter` because you are using Treesitter-based highlighting.

**Comment by sanga** [comment] 2020-07-03 07:56
ha ha. I actually started out filing this bug against `nvim-treesitter` but then decided as the errors points to an internal nvim file that perhaps it would be better against nvim :)

OK. Thanks for the info and the speedy reply. I'll try to notice what keys trigger this. And possibly try that branch too if I find time. Cheers!

**Comment by tjdevries** [comment] 2020-07-13 21:50
@vigoux should we close this here (is it a `nvim-treesitter` problem?) or is it a `neovim/neovim` problem?

**Comment by vigoux** [comment] 2020-07-13 22:05
It is a `neovim/neovim` problem, caused by the tree and the buffer getting out of sync. I think that this issue will be more useful once we know the edit that caused this desync.

**Comment by mfussenegger** [comment] 2020-07-13 22:22
> It is a `neovim/neovim` problem, caused by the tree and the buffer getting out of sync. I think that this issue will be more useful once we know the edit that caused this desync.

Not sure if it helps, but I tend to get this error when I have a buffer inactive, then change the file outside of vim (e.g checkout a different branch with git), then change back to the buffer. But can't reliably reproduce it either - but doing that it happens fairly often for me.

**Comment by vigoux** [comment] 2020-08-03 14:33
It definitely helps, and this is an interesting note. I will have to check to see what causes this.
I want to note here too that calling `:change` causes an assertion failure within treesitter, and causes neovim to crash (badly).

**Comment by tjdevries** [comment] 2020-08-08 19:43
@vigoux Is there anything we have in progress to fix this / anything you need help on? i don't know if @norcalli is interested in this at all.

**Comment by vigoux** [comment] 2020-08-08 19:46
I guess that we made a fair bit of progress in an earlier pr (on invalid buffer updates). All of the bugs boil down to that same invalide buffer update problem. The problem we have is reproducing the errors.

So I guess we just need more reports with repros...

**Comment by tjdevries** [comment] 2020-08-08 19:48
I would suggest we just try and write one million tests for the feature in the PR (if you're still intereseted in doing that)

**Comment by tjdevries** [comment] 2020-08-08 19:48
(if possible, tailoring tests to something similar to bug reports we've had)

**Comment by KillTheMule** [comment] 2020-08-08 19:55
Maybe https://github.com/neovim/neovim/pull/12733 does help a bit?

**Comment by vigoux** [comment] 2020-08-08 21:35
Yeah looks like we are addressing the same issues.
I noticed that automatic comment continuation (I don't remember the name of the option) also breaks buffer updates.

**Comment by subsonik** [comment] 2020-08-27 06:26
I'm also experiencing this problem:

Error executing lua callback: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:148: invalid end

It occurs when typing **_.C_** and **_(_** in a Python file.

```
NVIM v0.5.0-638-g91109ffda
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/x/Documents/src/neovim/build/config -I/Users/x/Documents/src/neovim/src -I/Users/x/Documents/src/neovim/.deps/usr/include -I/opt/local/include -I/Users/x/Documents/src/neovim/build/src/nvim/auto -I/Users/x/Documents/src/neovim/build/include
Compiled by x@MacBook-Pro-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

Minimal config:

```
packadd! dracula
packadd! nvim-treesitter

if has('nvim') || has('termguicolors')
    set termguicolors
endif
syntax enable
colorscheme dracula

lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "python" },
  highlight = {
    enable = true,
    disable = { "c", "rust" },
  },
}
EOF
```

**Comment by subsonik** [comment] 2020-09-02 17:07
Since the latest commit, this seems to be fixed for me. I can no longer trigger the "invalid end" error.

**Comment by vigoux** [comment] 2020-09-02 17:10
Lastest `neovim` commit or latest `nvim-treesitter` commit ?

**Comment by pushqrdx** [comment] 2020-09-15 22:29
i have latest both with neovim `NVIM v0.5.0-695-gf34eeba2d` and i am getting (in c++) `invalid end` at `query.lua` lines 167

**Comment by Shougo** [comment] 2020-09-16 00:07
I get `invalid start` at `query.lua` lines 167.

**Comment by bfredl** [comment] 2020-09-16 08:00
probably remaining issues with bytetrack. Me and @vigoux will go through them.

**Comment by sanga** [comment] 2020-09-26 04:41
So I found a reliable way to repro this this morning by accident.

Create the following python file:

```python
def run(self, name):
    print(f'hi {name}')
```
Then run `:%s/self, /`. As soon as you hit the last `/` => error

![2020-09-26_07:34:03](https://user-images.githubusercontent.com/2088/94330197-e47b8b80-ffca-11ea-853e-c5878aa993ee.gif)

So this now seems very similar to #12967 . However I have `inccommand=split` so at least that's different - it seems from that bug that `inccommand=nosplit` is a requirement for the bug to trigger?

This is against `NVIM v0.5.0-709-g4f8d98e58` and nvim-treesitter `98c12ec23a6df2f2f505304b61c4b2eefc0a568f`

**Comment by vigoux** [comment] 2020-09-26 07:43
Very nice ! The repro will help a lot !

**Comment by akinsho** [comment] 2020-09-26 14:32
@sanga yeah I think this is the same error as I raised in #12967 tbh I didn't realize it also occurred with `inccommand=split`. I didn't know an issue already existed for it. I can close that out as a duplicate of this if it's already being tracked here.

**Comment by rafikdraoui** [comment] 2020-10-06 20:14
Here are some other ways to reproduce (some of them were already mentioned here and there across the few issues related to this)

With minimal vimrc `minrc.vim`:

```vim
set runtimepath+=/path/to/nvim-treesitter
set inccommand=nosplit
lua <<EOF
  require'nvim-treesitter.configs'.setup {
    ensure_installed = "python",
    highlight = { enable = true },
  }
EOF
```

and python file `f.py` (note the 3 blank lines between the imports and the function, to trigger a reformatting with `black`):

```python
import sys
import os



def parse_template():
    with open("hello.txt") as f:
        data = f.read()
    ...
```

Open the buffer with `nvim --clean -u minrc.vim f.py` and

1. Entering `:%s/open/` triggers the error (but it's fine if `inccommand` isn't set to anything)

2. Switching to another terminal and running `isort f.py` or `black f.py` triggers the error when neovim gets the focus again (`isort` and `black` are programs that format python files)

**Comment by vigoux** [comment] 2021-05-21 15:33
Hey there, it's been a while, but I think that we progressively fixed
all the issues mentionned here.

Could you confirm it's the case, and close this is issue accordingly ?

**Comment by akinsho** [comment] 2021-05-23 09:47
@vigoux are the `invalid_end` and the `end_col` issue in #12861 unrelated? if they are related then the frequency of the bug has gone down a lot for me but it does still happen i.e. specifically the `end_col` error but tbh I don't always track the exact message that is displayed.

If the two bugs are different then I definitely don't see any issues relating to `inccommand` anymore.

**Comment by rafikdraoui** [comment] 2021-05-23 15:37
@vigoux Indeed, I noticed that for the past weeks the issue doesn't happen as frequently. Thanks!

The error doesn't happen anymore with the steps described above in https://github.com/neovim/neovim/issues/12588#issuecomment-704527421.

But it still occurs once in a while. I haven't found a minimal reproducible case for it yet, but it seems to mostly happen when I move a whole section of code (for example, a function) by deleting it then pasting it somewhere else. But it is a very rare occurence now, in the order of once a week rather than once an hour like it used to be!

**Comment by vigoux** [comment] 2021-06-07 17:13
Great that it is partly fixed !
Feel free to post here if you find a reproduction for your bugs, we will gladly include that in our test base and work on the issue !

**Closed** 2023-02-27 09:42 UTC
Labels: bug, treesitter
