### ISSUE TITLE
mapping for c-[ not working after v0.6.0

### ISSUE THREAD

**Issue by kalloc** [neovim/neovim#19618] opened 2022-08-01 23:32 UTC
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

vim -u DEFAULTS affected, v0.6.0 not affected

### Operating system/version

Ubuntu, OS X

### Terminal name/version

Terminal.App, Kitty, Tmux

### $TERM environment variable

xterm-256color

### Installation

brew, binary from release

### How to reproduce the issue

cat /tmp/test.conf 
nnoremap <C-]> <C-i>
nnoremap <C-[> <C-o>

vim -u /tmp/test.conf

### Expected behavior

In v0.6.0 and previous versions, ctrl-[ works well

### Actual behavior

in v0.7.x, ctrl-o, ctrl-i, ctrl-] — work well, but ctrl-[ not

**Comment by zeertzjq** [comment] 2022-08-01 23:50
Duplicate of #17867

**Closed by zeertzjq** 2022-08-01 23:50 UTC
Labels: bug
