### ISSUE TITLE
File URI problema with Built-in LSP, nvim-compe and clangd

### ISSUE THREAD

**Issue by dantearaujo1** [neovim/neovim#15250] opened 2021-08-03 10:59 UTC
### Neovim Version

0.6 nightly build

### Operating system/version:

Windows 10

### Terminal name/version:

Cmder

### TERM environment variable

cygwin

### Installation

download binaries from github realease page

### Steps to reproduce

I Tried to move from COC to built-in lsp in neovim using nvim-lspconfig, downloading LLVM (using clangd), completion with compe. I configured everything and when i openned a buffer with a cpp file :LspInfo shows that clangd was found in the cand attached in the correct root directory of my project (with compile_commands.json in the root directory) but when i enter in insert mode it doesn't give me any LSP information for autocompletion. I already posted this in the clangd github, but it seems is a client problem and not a server side problem. You can check the clangd log  with --log=verbose there to help me out, thank you in advance.

[Issue here (with Log info)](https://github.com/clangd/clangd/issues/832) 

### Expected behavior

Recieve autocompletion from LSP with compe 

### Actual behavior

Not recieving autocompletion and log file tells that we have a problem with file URI scheme

**Comment by clason** [comment] 2021-08-03 11:04
Are you sure it's a neovim problem? Do you get the same errors when using omnifunc (`<c-x><c-o>`) manual completion with `:set omnifunc=v:lua.vim.lsp.omnifunc`?

(If not, this is an issue with `nvim-compe`, not neovim.)

**Comment by dantearaujo1** [comment] 2021-08-03 11:07
Yeap, i recieve buffers completion, snippets completions but none from LSP. i just tested now with <c-x><c-o> and had the same result.

**Comment by clason** [comment] 2021-08-03 11:11
That is strange, since all internal functions should use the same utility functions for constructing the URI, so it's not clear to me why some are right and some are wrong. 

Could you add a complete minimal example (based on the LSP issue template -- you are using the wrong template here) _without_ autocompletion and just manual LSP completion?

**Comment by dantearaujo1** [comment] 2021-08-03 16:51
Where do i find this LSP issue template so i can add a minimal example.. sorry, im new to this programming world.

**Comment by clason** [comment] 2021-08-03 16:54
If you click on "new issue", you get the choice of three templates; it's the third one.

**Comment by dantearaujo1** [comment] 2021-08-04 12:50
Already did another issue with all the information there @clason can you check it out, please? #15261

**Comment by clason** [comment] 2021-08-04 13:01
Thanks; I'm closing this as a duplicate of #15261 then.

**Closed by clason** 2021-08-04 13:01 UTC
Labels: bug, lsp, platform:cygwin
