### ISSUE TITLE
The background in WinBar is taken from `Normal` highlight

### ISSUE THREAD

**Issue by qRoC** [neovim/neovim#26037] opened 2023-11-14 10:30 UTC
### Problem

When setting a custom highlight in WinBar (using `%#..#`), the background is taken from `Normal` highlight

### Steps to reproduce

1) Define `Normal` and `WinBar` highlights with different `bg`.
2) 

```
vim.opt_local.winbar = 'hello'
```

Result - Ok, background is from `WinBar`

<img width="129" alt="1" src="https://github.com/neovim/neovim/assets/1789565/33c7c0f1-d090-4040-b537-6b9096c5cc37">

3) 

```
vim.opt_local.winbar = '%#TestBug#hello'
```

`TestBug` is no existing highlight.
Result - Ok, background is from `WinBar`

<img width="176" alt="2" src="https://github.com/neovim/neovim/assets/1789565/5df95f60-8323-4e0f-99a2-0ecd745c6069">

4)
Now define `TestBug`, but without `bg`.
Result - background is from `Normal`

<img width="140" alt="3_1" src="https://github.com/neovim/neovim/assets/1789565/87e4bcad-2310-48b7-b412-2dd2e0552d1a">

<img width="328" alt="3_2" src="https://github.com/neovim/neovim/assets/1789565/622b569a-5aac-4eb3-8f47-8ebb64800768">

### Expected behavior

Background is from `WinBar `

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1507+g267c346e2-Homebrew

### Vim (not Nvim) behaves the same?

dont know

### Operating system/version

macOS 14.1

### Terminal name/version

Alacritty fork

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by zeertzjq** [comment] 2023-11-14 10:46
I don't think this should be changed.

**Comment by Bekaboo** [comment] 2023-12-04 12:17
@zeertzjq Could you explain why shouldn't highlighted texts in winbar take `WinBar` as the default background? In most cases, if a user applies a highlight group to contents inside winbar, it is more natural to have the same background color as `WinBar`.

**Comment by zeertzjq** [comment] 2023-12-04 12:22
Because it's the current behavior.

**Comment by echasnovski** [comment] 2023-12-04 12:59
> @echasnovski

Not a default colorscheme issue. It is how 'statusline', 'tabline', 'winbar' (and probably 'statuscolumn') blend colors and is present in Neovim 0.9.4.

**Comment by Bekaboo** [comment] 2023-12-23 16:39
@zeertzjq Sorry for spamming, but could you let us know whether you see this change appropriate to be merged in `master` in future releases?

**Comment by zeertzjq** [comment] 2023-12-25 02:33
Hmm, actually the current behavior applies to 'statuscolumn' as well: the default 'statuscolumn' highlight group is `LineNr`, while custom highlights in 'statuscolumn' have their backgrounds taken from `Normal`. The expected behavior is less clear for 'statuscolumn' as it is a replace for multiple window columns.

Therefore, if 'statusline' and 'winbar' are changed to combine custom highlights with `StatusLine` and `WinBar` respectively, it's also necessary to consider the consistency of 'winbar', 'statusline' and 'statuscolumn', i.e, whether to also change 'statuscolumn' to combine custom highlights with `LineNr`.

@luukvbaal What do you think?

**Comment by zeertzjq** [comment] 2023-12-25 02:44
No, I don't think that desirable as it's not backward-compatible and there is no way to achieve the old behavior. Instead there should be a way to combine highlight groups in 'statusline'.

**Comment by Bekaboo** [comment] 2023-12-25 03:33
@zeertzjq Thanks for your reply!

> there is no way to achieve the old behavior

To achieve the old behavior one only needs to specify `bg` of the hlgroup to be the same as `Normal`'s.

> Instead there should be a way to combine highlight groups in 'statusline'.

That's a nice feature too, but it's solves a different problem. The problem in this issue is that it is hard to have highlighted text with bg that respects `WinBarNC`/`WinBar`/`StatuslineNc`/`Statusline`. Users will still have to use complicated unreliable autocmds and winhl/highlight ns tricks to achieve that when they are able to merge hlgroups.

**Comment by zeertzjq** [comment] 2023-12-25 03:47
Hmm right, but I just noticed that the patch above was not enough, because it will also cause user highlight group to be combined with other attributes in `StatusLine` like `bold`, which isn't desired. A more complicated solution is needed.

**Comment by Bekaboo** [comment] 2023-12-29 09:07
Also related to https://github.com/neovim/neovim/issues/26502

**Comment by echasnovski** [comment] 2023-12-29 09:14
> Also related to #26502

No, it is not related. See [this comment](https://github.com/neovim/neovim/issues/26037#issuecomment-1838584354).

**Comment by Bekaboo** [comment] 2023-12-29 10:08
@echasnovski Thanks for your response. I see what you mean. It's "sort of" related -- if winbar highlights are merged by default / there is an easy way to sync the background of highlighted chunks with `hl-WinBar` or `hl-WinBarNC` there will be no issues like #26502

**Comment by zeertzjq** [comment] 2024-02-20 22:13
Related #27555

**Comment by ribru17** [comment] 2024-08-03 22:27
> ```viml
> set winbar=%#WinBarHlTest#abcd%*
> ```

@zeertzjq Can I make a PR for this? I may be misunderstanding the original bug but it seems that no attributes in the WinBar highlights (or custom highlight groups used in the winbar) are inherited from the StatusLine highlights for me.

**Comment by zeertzjq** [comment] 2024-08-03 22:51
> Hmm right, but I just noticed that the patch above was not enough, because it will also cause custom highlight group to be combined with other attributes in `StatusLine` or `StatusLineNC` like `bold` and `italic`, which may be undesired and is hard to override. A more complicated solution is needed.

Oh, I forgot that `nocombine` can be used for that. In that case this change may be OK.

**Comment by ribru17** [comment] 2024-08-03 22:55
Awesome, give me one moment. Also FYI I was testing this even without nocombine and it was working perfectly

**Closed** 2024-10-12 17:57 UTC
Labels: highlight, statusline
