### ISSUE TITLE
Standard  structured config and plugin configuration

### ISSUE THREAD

**Issue by horga83** [neovim/neovim#27455] opened 2024-02-13 04:17 UTC
### Problem

I have been looking over Neovim configurations and to say that the plugin system is a mess would be an understatement.  It would be nice if there was a standard plugin file structure that EVERY plugin followed.  Just look at the hundreds of videos of people configuring Neovim.  Half the plugins have configuration examples that only serve to confuse the new user.  I think Neovim is a fine editor but it could be so much more and much more accessible for new users.  Yes I understand it is a huge task but I can't even count how many different directory structures and config file "examples" there are.  Maybe the goal for version 1.0 would be a better way.

### Expected behavior

Suggest a Neovim standard configuration folder structure that is recommended.  Provide complete examples to get many of the top 25 or 30 plugins running at least being able to run under say Lazy.vim.  Plugin authors would at least follow the "core" configuration to get a running system.  Yes custom stuff would still be available but at least a new user could follow some complete documentation with real world working example configuration files to get a plugin working and modify it from there.

Too much to ask?

**Comment by wookayin** [comment] 2024-02-13 04:32
Folder structure -- plugins should have the same layout as runtimepath, [:help `runtimepath`](https://neovim.io/doc/user/options.html#'runtimepath'), and it has never changed ever since the original vim.

- `lua/`
- `ftplugin/`
- `plugin/`
- `queries/`
- etc.

Do you have any example of (strange) plugins that do not follow this structure? I don't think I haven't seen anything peculiar directory structure.

**Comment by horga83** [comment] 2024-02-13 04:52
Just have a look at the many youtube videos

Some do everything in init.lua some have lua/core/{plugins, plugin_config, utils} some have lua{config, options, plugins} it's all over the place.  Some have init.lua sprinkled between folders, some do it all in one.  Makes it very confusing for new users.

Just look at nvim.autopairs for example, it's not clear how it all goes together, Lazyvim, Lunarvim mini.nvim nvchad all handle things differently.  Very difficult to get clear examples that actually work.

Many times one can follow a video but then have a super hard time getting a plugin to work because it doesn't provide a standard working example from options to setup() to require etc.

**Comment by zeertzjq** [comment] 2024-02-13 05:00
Duplicate of #22366

**Closed by zeertzjq** 2024-02-13 05:00 UTC
Labels: enhancement
