### ISSUE TITLE
OpenBSD Builds all failing

### ISSUE THREAD

**Issue by tjdevries** [neovim/neovim#12339] opened 2020-05-18 19:01 UTC
Basically as far as I can see, all the OpenBSD builds are failing with logs similar to this: https://builds.sr.ht/~jmk/job/212768

Wondering what needs to be done to fix it, since it would take a lot of cognitive load off for PRs to see green check marks :)

cc @blueyed @vext01 since you're the contributors to that file and I'm completely lost :)

**Comment by vext01** [comment] 2020-05-18 20:15
The manifest has hard-coded package names in. They've probably gone stale.

To find out what versions to use, SSH in to one of the failing builds and
do 'pkg_info -Q <X>' where <X> is a search term like 'autoconf' and you
should see the available versions.

When installing packages, you'd normally totally omit the package version
and: in the case that there's only one candidate, it'd install it; or if
there are many candidates (as there are with automake and autoconf),
pkg_add would ask you which version you want to install, but since the
builds are non-interactive, that's not going to be possible.

Hopefully that helps!

**Comment by glacambre** [comment] 2020-05-19 03:46
This is probably a duplicate of 
https://github.com/neovim/neovim/issues/12104

**Comment by tjdevries** [comment] 2020-05-19 16:11
I don't think it's a duplicate of those, but that does look like something else we might need to fix.

For the current build failures, it does not get past setup because of the failure to find the packages. Thanks for the tips @vext01 and @glacambre

**Comment by vext01** [comment] 2020-05-20 10:28
Sorry folks, I thought you were updating the OpenBSD version: this would cause packages to go stale. But this is not what's happening here. You are still using OpenBSD-6.5 (two releases old by the way, and unsupported).

> https://cdn.openbsd.org/pub/OpenBSD/6.5/packages/amd64/: no such dir

This looks like an intermittent network failure. That directory seems to work fine if i go there in my web browser.

I also pasted your manifest into a manually submitted sr.ht build and the packages installed fine:
https://builds.sr.ht/~vext01/job/214176

So are you still seeing this issue?

**Comment by vext01** [comment] 2020-05-20 10:32
> OpenBSD-6.5 (two releases old by the way, and unsupported)

About this, OpenBSD-6.7 was released yesterday. I'd wait for sr.ht to provide an image and update. There's little point in updating to 6.6.

https://man.sr.ht/builds.sr.ht/compatibility.md#openbsd

**Comment by tjdevries** [comment] 2020-05-22 21:40
Thanks for the info @vext01 . I guess we can just wait until they're supporting 6.7 . If anyone wants to fix this, that'd be helpful, since I'm not super familiar. Otherwise perhaps I'll try when I have some extra time.

**Comment by vext01** [comment] 2020-05-23 11:31
Sonia it still an issue? If it was an intermittent network issue, it'd
probably fix itself.

**Comment by h-michael** [comment] 2020-05-24 10:09
After this build https://builds.sr.ht/~jmk/job/217629, it works.
(The fact that the test is failing is another matter in itself.)

**Closed** 2020-05-25 02:25 UTC
Labels: bug, ci
