### ISSUE TITLE
Visual Block Mode's behavior might need to change to be more user friendly

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#20453] opened 2022-10-02 18:24 UTC
### Feature already in Vim?

No

### Feature description

When we're in the Visual-Block Mode:
```
|test  <----- Cursor Here
aaa
bbb
foo
bar
```
and we press `<C-v>` to get into the Visual-Block-Mode, then we press `j` to move down the cursor and select the beginning of each line `a` `b` `f` `b` and then we press `I` to go to the insert-mode

the cursor might need to be like this,  anything we have inserted in each line will show the result immediately so we don't need to press `<ESC>` to apply changes to the buffer.
```
|tes
|aaa
|bbb
|foo
|bar
```

instead of this
```
|test
aaa
bbb
foo
bar
```

I guess when multi-cursor in future will do it for us perfectly?

though it's just a small enhancement of visual-block mode, the original visual-block mode also works quite well.

**Comment by smjonas** [comment] 2022-10-02 18:55
Duplicate of #20329.

**Closed by smjonas** 2022-10-02 18:55 UTC
Labels: enhancement
