### ISSUE TITLE
"paste" option being set unintentional

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10966] opened 2019-09-08 12:24 UTC
I've noticed that I sometimes have set "paste", although not done this myself.

`:verb set paste?` says:

> Last set from Lua line 51

btw: can we have a more meaningful source location there?

I've not found a way to reproduce this yet, but it might be related to suspending Neovim (`ctrl-z`).

**Comment by justinmk** [comment] 2019-09-08 20:11
This suggests that the "stop paste" code is not being received, or else `phase=3` is not sent to `vim.paste`. https://github.com/neovim/neovim/pull/10974 is a workaround, so please check if it still happens after that.

> btw: can we have a more meaningful source location there?

That would be nice. See https://github.com/neovim/neovim/pull/8329#discussion_r185205891 .

**Comment by justinmk** [comment] 2019-09-08 21:59
Closed by https://github.com/neovim/neovim/pull/10974 . Assuming the root cause is covered by https://github.com/neovim/neovim/issues/10865 .

**Closed by justinmk** 2019-09-08 21:59 UTC
Labels: bug, clipboard
