### ISSUE TITLE
Cannot map <c-m>

### ISSUE THREAD

**Issue by litearc** [neovim/neovim#18667] opened 2022-05-21 00:06 UTC
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

yes, vim 8.2

### Operating system/version

Ubuntu 20.04

### Terminal name/version

kitty 0.20.2

### $TERM environment variable

xterm-256color

### Installation

linuxbrew

### How to reproduce the issue

```
nvim --clean file1 file2
:nnoremap <c-n> :bp<cr>
:nnoremap <c-m> :bn<cr>
```
Now, press `<c-n>` and `<c-m>`.

### Expected behavior

The expected behavior is:
- if I press `<c-n>`, it switches to the previous buffer (works)
- if I press `<c-m>`, it switches to the next buffer (does not work)

### Actual behavior

- When I press `<c-n>`, it switches to the previous buffer as expected
- When I press `<c-m>`, it just moves the cursor down one line

It seems `<c-m>` cannot be mapped. It worked in a previous version (I think 6.0) and works in vim (8.2).

**Comment by zeertzjq** [comment] 2022-05-21 00:12
Duplicate of #17867

**Closed by zeertzjq** 2022-05-21 00:12 UTC
Labels: bug
