### ISSUE TITLE
bad characters inserted occasionally immediately after <ESC>

### ISSUE THREAD

**Issue by aeruder** [neovim/neovim#2093] opened 2015-03-04 15:07 UTC
Finally found a pretty easy way to reproduce this.

* Run nvim -u NONE
* :set showmatch
* Type i(1**)\<ESC\>j**

The )\<ESC\>j needs to be typed pretty quickly.  For me I almost always end up with a ê character and I'm still in insert mode.  Set showmatch seems to make it happen almost every time but I'm guessing it is just as possible anytime a plugin or otherwise causes some lag and results in processing the \<ESC\>j really quickly.

**Comment by critechar** [comment] 2015-03-04 16:33
Which version are you using? With a recent update, there is no longer any lag (or timeout) for <kbd>ESC</kbd> to switch to normal mode. But <kbd>Alt</kbd>+<kbd>J</kbd> will give you `ê` character while in insert mode (see #2068)

**Comment by aeruder** [comment] 2015-03-04 16:48
The showmatch is what is creating the lag in this example.  0.0.0-alpha+201503040021

**Comment by acoffman** [comment] 2015-03-04 19:05
I also experience this!

**Comment by aeruder** [comment] 2015-03-04 22:17
I'm including here a transcript of a discussion between me and the author of libtermkey and friends just to get everyone on the same page.

       thegorn | anyone want to try reproducing something for me really
               | quick on their nvim? nvim -u NONE / :set showmatch /
               | Type 'i(1)<ESC>j'
       thegorn | the key here is to type the )<ESC>j pretty quickly so
               | the <ESC>j gets typed while it is still doing the
               | showmatch
       LeoNerd | Mmmm timing
       thegorn | yea, it happens way more often to me, system has a
               | little hiccup, the <ESC> gets lumped in with the j in
               | some weird terminal goodness
       LeoNerd | Yah
       thegorn | or maybe it is always just related to showmatch and with
               | writing C I tend to have lots of lines that end with
               | );<ESC>j
       LeoNerd | The long-term view of that (pardon the pun) is that the
               | terminal should eventually support nicer encodings
       LeoNerd | But until you're running a terminal that
               | neovim/libtermkey/etc... knows is going to do it safely,
               | it has to rely on timing
       thegorn | yea, i get very frustrated by the state of terminals in
               | 2014
       LeoNerd | Me too
       thegorn | er, 2015 now
       LeoNerd | Hence my mamoth effort to write a better set of
               | tools/libraries/etc...
       thegorn | LeoNerd: i'm assuming you saw the issue too?
       LeoNerd | I'm well aware of it, yes :)
       thegorn | ok, well, i made issue #2093 regarding it, i didn't see
               | it on the bug tracker yet but was pretty sure i've seen
               | it referenced somewhere
             * | LeoNerd the author of libtermkey (what neovim uses to
               | parse keys), libtickit (what it will sometime be using
               | to do the entire terminal UI), libvterm (what neovim
               | uses to embed a virtual terminal to implement :term ...;
               | what pangoterm uses; ...)
       thegorn | ah, ok
       LeoNerd | Soyeah, trust me :) I understand what the problem is
       thegorn | is it possible to rework things to retain some sort of
               | timing information on keyboard input? i understand that
               | most of this is just a giant hack to deal with terminal
               | sending special characters encoded with <ESC> key which
               | makes it a little tricky to determine <ESC> vs <special
               | key>
       LeoNerd | Yeah..
       LeoNerd | The real solution is an encoding that doesn't rely on
               | timing at all
       LeoNerd | What you do is put the terminal in S8C1T mode, so it
               | uses the real 8bit values instead of 7bit ESC-prefixed
               | versions for the C1 controls (i.e. CSI and SS3)
       thegorn | is that available on terminal emulators now? i know i've
               | seen references to 8-bit mode
       thegorn | ah, ok, is that not done now?
       LeoNerd | That then means the only times you'll ever see an ESC
               | byte are either the real Escape key, or an Alt+{letter}
               | prefix.
       LeoNerd | The latter can then be fixed by forcing CSIu encoding
               | (and CSI therefore using the real 8bit value of 0x9b)
       LeoNerd | Most terminals since the 1980s will support S8C1T; I
               | don't know of a single application even in 2015 that
               | enables the mode. :(
    BlackEdder | LeoNerd: does pangoterm do this (and does neovim then
               | pick that up automatically)
       LeoNerd | Hm?
       LeoNerd | pangoterm will support of all that yes; but it won't do
               | it *by default* because it doesn't know that the
               | application running inside will cope
       LeoNerd | It has to be asked to do that
    BlackEdder | Can we ask it to do it from inside neovim?
       LeoNerd | You could but again it wouldn't help on its own
       thegorn | need a thread in neovim blocking on tty input, attaching
               | timestamps to everything and then throwing it in a queue
               | for main thread to pick up
       thegorn | :)
       LeoNerd | thegorn: nono, timing is not the answer
       LeoNerd | Network delays can break timing. The answer is the
               | encoding that doesn't rely on timing information
       LeoNerd | BlackEdder: Sure you could send the sequences to enable
               | that, but that's insufficient. neovim's input parser
               | would have to then additionally be aware that *because*
               | these modes are in effect, it no longer needs to use
               | timing information.
       LeoNerd | There's currently no switch to do that
    BlackEdder | Ah, I had hoped that that came for free with libtermkey
               | :)
       LeoNerd | Nope
       LeoNerd | libtermkey just handles bytesof input from the terminal,
               | it doesn't talk ot the terminal. So it doesn't have a
               | way to ask for that mode in the first place
       LeoNerd | It's why I've declared libtermkey a basically
               | development dead-end; the code wants merging into
               | libtickit properly, where it can do such things
    BlackEdder | Hmm wouldn't it be worth it to make libtermkey and
               | libvterm aware of each other :)
    BlackEdder | Ah, libtickit does that :)
    BlackEdder | nevermind
       thegorn | libvterm is less related iiuc
       thegorn | (that handles the other side of the tty)
       LeoNerd | termkey is EOL, to be merged into tickit. Eventually
               | there'll just be two; tickit the library that
               | applications use to talk to the TTY; vterm the one that
               | terminal emulator programs use to implement the TTY
    BlackEdder | k
    BlackEdder | but neovim uses termkey, not tickit?
       thegorn | LeoNerd: so is nvim currently on curses + termkey?
       LeoNerd | I don't even think it's curses
       LeoNerd | I think it's currently using unibilium directly to query
               | the terminfo DB and output its own strings
       thegorn | oh, ok

**Comment by aidos** [comment] 2015-03-07 10:22
I tracked this down to the line `set ttimeoutlen=100` in vim-sensible as the cause in my case. To fix it I just added `set ttimeoutlen=0` the to my .nvimrc.

**Comment by Pyrohh** [comment] 2015-03-07 23:34
@aidos you might be able to set it in your nvimrc via [this method](https://github.com/tpope/vim-sensible/issues/88#issuecomment-67413355).

**Comment by aidos** [comment] 2015-03-09 13:08
@Pyrohh thanks. Worked perfectly, and is far nicer than hacking vim-sensible directly.

**Comment by aeruder** [comment] 2015-03-09 14:31
ttimeoutlen does not help with this problem.

**Comment by aidos** [comment] 2015-03-09 14:58
@aeruder sorry if I side-tracking things there. You're correct, it doesn't help in the showmatch case you outlined. I noticed the same behaviour you describe from having vim-sensible installed and this was the only discussion I could find on the issue.

It is a more general problem though (I guess the root cause is the same):

- run nvim -u NONE
- :set ttimeout
- :set ttimeoutlen=100
- Type `i<ESC>j`

I've now read through the im conversation and it sounds like a horrible issue to have to fix. Fortunately for me I can workaround it by changing ttimeoutlen, unfortunately that doesn't help you at all...

**Comment by kaldrenon** [comment] 2015-03-11 13:52
+1, this is happening for me as well. OSX/iTerm2, if that's relevant.

**Comment by kaldrenon** [comment] 2015-03-11 18:21
After a little more fiddling: This happens when I am in tmux, and does **not** happen when I am not in tmux.

**Comment by akkartik** [comment] 2015-03-11 18:24
:+1: to kaldrenon. I see the problem in tmux.

**Comment by aharris88** [comment] 2015-03-11 20:32
I also see the problem in tmux, but not when I'm not in tmux. This happens even if I run `nvim -u NONE` and even if I try setting:

    :set ttimeout
    :set ttimeoutlen=100

or

    :set ttimeout
    :set ttimeoutlen=0

**Comment by tarruda** [comment] 2015-03-11 20:41
Try putting this in your tmuxrc : `set -g escape-time 20`

**Comment by akkartik** [comment] 2015-03-11 20:45
@tarruda Yes, that fixed it for me. I assume this is a workaround that we'd ideally want to remove the need for (given infinite time, resources, etc., etc.)?

**Comment by aharris88** [comment] 2015-03-11 20:50
I get this error:

    E518: Unknown option: -g

**Comment by aharris88** [comment] 2015-03-11 20:55
@tarruda That fixed it for me after restarting tmux

**Comment by aeruder** [comment] 2015-03-11 21:22
Once again reiterating, this does not fix the core issue (and why it is still broken with showmatch even with tmux and escape-time, etc..).

**Comment by tarruda** [comment] 2015-03-11 22:27
> @tarruda Yes, that fixed it for me. I assume this is a workaround that we'd ideally want to remove the need for (given infinite time, resources, etc., etc.)?

Its just a problem with how terminals represent the alt modifier. With its default settings, tmux will wait 500 milliseconds after a escape byte is received to pass it forward. So if you press esc and after 200 milliseconds press j, tmux will send esc + j together which will be parsed as alt+j by neovim. Vim does not have this problem because by default it doesn't recognize the alt modifier in terminals, so esc + j are interpreted as two different key presses. There's nothing I can do about this without taking the ability to parse the alt modifier in arbitrary keys.

The problem reported by @aeruder is the same, but the reason it is not fixed by lowering the timeout is because `showmatch` uses a sleep function which causes a lag that results in esc+j arriving together in the input buffer.

The only idea I have for fixing this issue is to run the TUI in separate thread. Since it is something that will have to be done for the gtk UI, I will defer fixing this issue to a later time.

**Comment by akkartik** [comment] 2015-03-11 22:31
:+1:

Just thinking aloud: is this maybe reason to retreat to vim's non-support for alt modifiers?

**Comment by justinmk** [comment] 2015-03-11 22:43
@akkartik That is a big compromise just to avoid `set -g escape-time 20`. 

We have identified that `:sleep` will exacerbate the issue, and this affects showmatch and things like [vim-pulse](https://github.com/inside/vim-search-pulse).

@tarruda Could the problem be easily avoided by setting a timestamp before going into `:sleep`, and then comparing that before processing the typeahead?

**Comment by tarruda** [comment] 2015-03-11 23:14
> @tarruda Could the problem be easily avoided by setting a timestamp before going into :sleep, and then comparing that before processing the typeahead?

Thats a possibility, yes

**Comment by critechar** [comment] 2015-03-12 05:33
> So if you press esc and after 200 milliseconds press j, tmux will send esc + j together which will be parsed as alt+j by neovim. Vim does not have this problem because by default it doesn't recognize the alt modifier in terminals, so esc + j are interpreted as two different key presses.

Is it possible to provide a global option which, when set, always processes alt+j as esc+j in insert mode?

**Comment by feedthebayer** [comment] 2015-04-04 15:24
Fyi for anyone who adds the above recommended timeout settings and still has the issue, make sure you don't have anything like the below in your config file :)

```
if has('macunix') || has('mac')
  " Fix meta key for Mac
  let c='a'
  while c <= 'z'
    exec "set <A-".c.">=\e".c
    exec "imap \e".c." <A-".c.">"
    let c = nr2char(1+char2nr(c))
  endw
endif
```

**Comment by jzelinskie** [comment] 2015-04-09 03:14
I'm getting this on iTerm2/OSX/showmatch and no tmux. :crying_cat_face:

**Comment by justinmk** [comment] 2015-05-11 02:15
I did not see `set nottimeout` in any of the suggestions here. @aeruder can you confirm that `set ttimeout?` returns `nottimeout`? Or does `set nottimeout` fix the issue for you?

**Comment by aeruder** [comment] 2015-05-28 19:32
@justinmk doesn't matter.  There is no setting that is going to fix this problem as it is related to a.) how unicode characters are encoded b.) how escape is encoded and that there is no real way to distinguish between the two without 8-bit mode when the editor is blocking.

**Comment by justinmk** [comment] 2015-05-28 20:29
@aeruder So did you try it with `set nottimeout` or not?

**Comment by aeruder** [comment] 2015-05-28 20:37
Yes.

**Comment by krisleech** [comment] 2015-06-03 09:38
Same here, only with nvim in tmux do I get this issue. Pressing `Esc + j`, or `Esc + :w` quickly produces unicode characters and leaves me in insert mode. Non of the setting above fixed the issue. Putting this here so I can test an future fix.

**Comment by tarruda** [comment] 2015-06-11 02:36
@justinmk the only way to fix this is by running IO in a separate thread(#2371), which I'm already working on(and facing some challenges to implement)

**Comment by justinmk** [comment] 2015-08-17 06:45
@aeruder Are you able to reproduce this on latest master? Even with showmatch it seems fine to me.

**Comment by aeruder** [comment] 2015-08-17 12:58
NVIM 0.0.0-alpha+201508170110 (compiled Aug 17 2015 07:55:25)
    Commit: 14d2a90db984c1a0360727c4d9b8337a689fccec
    (1)ê

Still reproduced on Konsole with no tmux or screen.  The trick is that the )<esc>j has to be pressed pretty quick (while show match is still processing).

**Comment by tarruda** [comment] 2015-08-17 13:01
FWIW, the PR I'm working on now will fix this.

**Comment by aeruder** [comment] 2015-08-17 13:04
@tarruda agree until we start talking about laggy links (ssh, etc.) between the terminal and neovim.  It would be nice to fix this in a better way but that requires an upgrade to the entire ecosystem (terminals, multiplexers, and libtermkey/etc...).  I will be super happy to just not have ê all over my screen when using locally.

**Comment by khouli** [comment] 2015-08-28 02:52
Since this is a likely first google hit for folks experiencing this issue (including myself), would anyone knowledgeable mind explaining the current status of this issue?

All I know is that I often produce foreign characters when switching from insert to normal mode. Is there anything I can do at the moment to prevent this or just make it less likely?

Thanks.

**Comment by justinmk** [comment] 2015-08-28 03:02
Are you using tmux? This is addressed in the wiki and elsewhere.

**Comment by khouli** [comment] 2015-08-28 03:08
I should have mentioned this is without tmux. urxvt on arch.

**Comment by nagisa** [comment] 2015-08-28 08:47
@khouli [Try these 3 options](https://github.com/nagisa/sysconf/blob/1a542e8f671b90f1f6ef6a2d172c88ae6c6d5c5c/nagisa/vim/editor.vim#L46).

**Comment by tarruda** [comment] 2015-08-28 09:58
> Since this is a likely first google hit for folks experiencing this (including myself), would anyone knowledgeable mind explaining the current status of this issue?

Fixing this on #3246(not ready yet)

**Comment by tarruda** [comment] 2015-08-28 15:45
@khouli can you test if this bug is present on PR #3246?

**Comment by khouli** [comment] 2015-08-29 03:34
@tarruda Alright I just grabbed and built that branch and I'll start experimenting but I'm not sure how to reliably reproduce the issue. Any guesses about what I should try?

**Comment by khouli** [comment] 2015-08-29 03:45
@aeruder It sounds like you were able to reproduce this reliably? Do you have a trick or just fast fingers? Was it Esc then ) then j from insert mode that was causing this for you?

At the moment I just don't know exactly what keypresses cause this for me. I have a keylogger running that captures control characters. The next time I see this I'll check what I pressed.

**Comment by tarruda** [comment] 2015-09-01 13:24
> @tarruda Alright I just grabbed and built that branch and I'll start experimenting but I'm not sure how to reliably reproduce the issue. Any guesses about what I should try?

On master branch, I can reproduce reliably using @aeruder instructions. I can't reproduce on #3246

**Comment by aeruder** [comment] 2015-09-04 17:13
@tarruda Seems better with #3246

**Comment by tarruda** [comment] 2015-09-07 11:40
#3246 is merged, so closing this.

Just to be clear, #3246 is only meant to fix the `<esc>` lag caused by showmatch which is what @aeruder reported in this issue

**Closed by tarruda** 2015-09-07 11:40 UTC
Labels: bug, tui

**Comment by brightshine** [comment] 2015-09-30 03:14
Hi, I can reproduce this issue with NVIM 0.0.0-alpha+201509272033
( Commit: 622ec95c3f793a814b3e7c0ee697c959f5b77332 )
Does someone else getting bad characters with tmux now?

**Comment by justinmk** [comment] 2015-09-30 03:48
@brightshine tmux timing is not related to this issue. Notice that in Vim if you press escape in insert-mode it will pause for a few seconds.

Your tmux config controls the timing of escape. https://github.com/neovim/neovim/wiki/Troubleshooting#pressing-esc-when-running-nvim-in-tmux-or-gnu-screen-inserts-characters

**Comment by Rio** [comment] 2015-10-06 20:00
Same issue when running in tmux on Fedora 22. neovim version ```NVIM 0.0.0-alpha (compiled Jul 26 2015 15:55:24)``` from ```nvim -v``` or ```version 0.0.0 release 69.git7a6bf3f.fc22``` from ```dnf info neovim```

**Comment by tarruda** [comment] 2015-10-06 20:12
@Rio if it was compiled in July 26 then it didn't get the fix

**Comment by Rio** [comment] 2015-10-07 08:45
Yeah noticed that after reporting sorry. All the builds on Fedora Copr don't have it though, guess I'll just wait.

**Comment by bfredl** [comment] 2015-10-08 11:10
did something change on master recently? I always had

    set ttimeout
    set ttimeoutlen=10

in nvimrc working well, but after last recompile it seems like (`nvim -u NONE` and then) `set ttimeout ttimeoutlen=1` or anything greater than zero works like `ttimeout=infinity` i e after pressing ESC nothing happens before pressing ESC again. Seems to work well enough with `set nottimeout` or `ttimeoutlen=0`

**Comment by justinmk** [comment] 2015-10-08 17:02
@tarruda Is there a reason Neovim needs to support `ttimeout[len]` at all?

**Comment by tarruda** [comment] 2015-10-08 20:07
> did something change on master recently? 

Yes, it's a bug introduced by #3360. Can you confirm that this patch fixes the problem?

```diff
diff --git a/src/nvim/tui/input.c b/src/nvim/tui/input.c
index 32b3f15..654b857 100644
--- a/src/nvim/tui/input.c
+++ b/src/nvim/tui/input.c
@@ -249,6 +249,7 @@ static void tk_getkeys(TermInput *input, bool force)
 static void timer_cb(TimeWatcher *watcher, void *data)
 {
   tk_getkeys(data, true);
+  flush_input(data, true);
 }

 static bool handle_bracketed_paste(TermInput *input)
```

> @tarruda Is there a reason Neovim needs to support ttimeout[len] at all?

No more reason than any other terminal program that can be used over connections high latency. If we drop this option and nvim terminal UI is used over slow connections, there will be no way for the user to send keys such a <kbd>PageUp</kbd> or <kbd>Home</kbd>, which are represented by a leading esc byte.

Imagine this scenario: A xterm user presses <kbd>PageUp</kbd> which sends the bytes `\x1b`(esc), `[`, `[`, `5` and `~` but the first `[` arrives between 200-500ms after the `\x1b`. How should nvim interpret the esc byte: As a the esc key or as the beginning of an esc sequence? Welcome to one of the biggest problems caused by how terminals encode keys.

AFAIK there's no way to fix without changing the encoding (which is what @leonerd is trying to achieve in a backwards-compatible way). `ttimeoutlen` is a workaround to allow users to adapt the program to the speed of their connections.

**Comment by bfredl** [comment] 2015-10-09 09:22
@tarruda Works, thanks!

**Comment by leonerd** [comment] 2015-10-10 11:57
To add to what @tarruda says: there is a way to reduce that coupling of the <kbd>Escape</kbd> key, which involves requesting `S8C1T` from the terminal, because if it accepts that (which is fairly likely on most terminals), it will use the single 8bit byte encoding of CSI instead of the two-byte `ESC [` sequence. This reduces the occasions where a real `ESC` byte is seen.

Annoyingly, it is slightly insufficient because of the way most (legacy) terminals encode simple <kbd>Alt</kbd> modified printing characters, is also to prefix `ESC` on them. If those too are changed to use `CSI u` encoding, which itself uses the single 8bit value, then now the only time an `ESC` byte is ever seen comes from the real <kbd>Escape</kbd> key; at which point all those annoying timing issues disappear.

It's this latter part which requires more work and support from terminals.

**Comment by tarruda** [comment] 2015-10-10 23:39
> Annoyingly, it is slightly insufficient because of the way most (legacy) terminals encode simple Alt modified printing characters, is also to prefix ESC on them. If those too are changed to use CSI u encoding, which itself uses the single 8bit value, then now the only time an ESC byte is ever seen comes from the real Escape key; at which point all those annoying timing issues disappear.

It is important to mention that while `S8C1T` can remove the timing issue, it also removes support for utf-8 since the higher sequences require the first bit to be set.

**Comment by leonerd** [comment] 2015-10-11 11:31
@tarruda: Technically, yes. But in practice it all turns out fine. The

UTF-8 encoding for any valid Unicode character never *starts* with a C1 control byte. The way `libtermkey` interprets the input relies on this - a leading C1 byte is interpreted as a control, whereas a C1 byte appearing after a UTF-8 initial high byte is interpreted as UTF-8 continuation.
