### ISSUE TITLE
redundantly specifying `:syntax enable` while using tabs breaks syntax highlighting

### ISSUE THREAD

**Issue by michaelkirk** [neovim/neovim#1066] opened 2014-08-14 14:24 UTC
Steps to repeat:

```
When I open via `nvim file_1.rb`
And I run `:syntax enable`
Then I see that syntax is highlighted
When I run `:tabnew file_2.rb`
And I run `:syntax enable` again
And I switch back to my first tab ("file1_.rb")
Then I see syntax highlighting stops
When I run `:syntax enable` a third time 
Then syntax highlighting still doesn't turn n.
```

It works when not using tabs - for example:

```
When I open via `nvim file_1.rb`
And I run `:syntax enable`
And I run `:syntax enable` again
Then syntax highlighting is still enabled (as expected)
```

I'm running OSX Mavericks

I've just installed neovim 5c9db00e9e8b2361a57dfdc1ca2c0e3e9ee01efc via `brew install --HEAD https://raw.github.com/neovim/neovim/master/neovim.rb`

**Comment by fmoralesc** [comment] 2015-07-18 18:05
(Reviewing old issues) I can't reproduce this at all and I think it's safe to close this.

**Comment by fmoralesc** [comment] 2016-04-19 08:23
Closing this.

**Closed by fmoralesc** 2016-04-19 08:23 UTC
Labels: bug
