### ISSUE TITLE
"E444: Cannot close last window" when pressing 'q' in normal mode in a man:// file

### ISSUE THREAD

**Issue by Euro20179** [neovim/neovim#20625] opened 2022-10-12 20:48 UTC
### Neovim version (nvim -v)

v0.8.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch linux x86_64

### Terminal name/version

kitty 0.26.3

### $TERM environment variable

kitty (setting to xterm-256color does nothing)

### Installation

pacman

### How to reproduce the issue

`nvim -u /dev/null man://test`
press `q` in normal mode

### Expected behavior

Neovim should close.

### Actual behavior

E444: Cannot close last window error is printed.

**Comment by Euro20179** [comment] 2022-10-12 20:50
There's a good chance that it's one of my plugins, or that I'm doing something wrong here, but I uninstalled packer, and removed a bunch of files from packer in the runtime paths that were still influencing neovim, but the problem persisted.

**Comment by nacho-dz** [comment] 2023-02-17 16:25
I came across the same problem recently, and while I'm not sure what the root of the issue is, I patched it adding the following line to `~/.config/nvim/after/ftplugin/man.vim`:
```vim
nnoremap <buffer> q ZQ
```
or to `~/.config/nvim/after/ftplugin/man.lua`:
```lua
vim.keymap.set('n', 'q', 'ZQ', { buffer = true })
```
either one should work.

**Comment by Euro20179** [comment] 2023-02-17 20:20
Yep, works for me as well, I wonder why `q` doesn't force quit by default in man pages.

**Comment by justinmk** [comment] 2024-10-10 11:31
duplicate of https://github.com/neovim/neovim/issues/30743

**Closed by justinmk** 2024-10-10 11:31 UTC
Labels: bug, runtime
