### ISSUE TITLE
options not works fine when same buffer in float win and normal win

### ISSUE THREAD

**Issue by glepnir** [neovim/neovim#22004] opened 2023-01-26 07:13 UTC
### Describe the bug

when the buffer both in normal win and float win, the winbar will copied from the normal win to float win. custom winhl not work.

### Steps to reproduce

a min config , `nvim --clean -u min.lua min.lua`

```lua
vim.opt.termguicolors = true
vim.cmd.colorscheme('desert')
vim.cmd('syntax on')

local curbuf = vim.api.nvim_get_current_buf()

vim.api.nvim_set_hl(0, 'TestFloatNormal', {
  background = '#000000'
})

vim.api.nvim_set_hl(0, 'TestFloatBorder', {
  background = '#ffffff',
  foreground = '#442356'
})

local curwin = vim.api.nvim_get_current_win()
vim.wo[curwin].winbar = 'winbar in winid:' .. curwin

local bufnr = vim.api.nvim_create_buf(true, true)
local winid = vim.api.nvim_open_win(bufnr, true, {
  relative = 'editor',
  width = 40,
  height = 20,
  row = 5,
  col = 10,
  border = 'double'
})

vim.api.nvim_win_set_option(winid, 'winhl', 'Normal:TestFloatNormal,FloatBorder:TestFloatBorder')

vim.api.nvim_win_set_buf(winid, curbuf)
```

### Expected behavior

`winbar` is win option. it does not copied from the normal window. `winhl` not works like border color  is missing.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-2030+ga0a112515

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos 13.0.1

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

build frome source

**Comment by zeertzjq** [comment] 2023-01-26 07:19
Duplicate of #11525

**Closed by zeertzjq** 2023-01-26 07:19 UTC
Labels: bug, highlight, options

**Comment by lewis6991** [comment] 2023-01-26 09:32
You need to use setlocal. `vim.wo` is equivalent to `set`.

**Comment by glepnir** [comment] 2023-01-26 09:34
but i set `winid` for into `wo` not only use `vim.wo` .

**Comment by lewis6991** [comment] 2023-01-26 09:39
No `vim.wo[winid]` does not behave like `setlocal`. `vim.wo.opt` is the same as `vim.wo[curbuf].opt`.

**Comment by lewis6991** [comment] 2023-01-26 09:40
See `:help vim.wo`:

>  Note: this does not access |local-options| (`:setlocal`) instead use: >lua
>        nvim_get_option_value(OPTION, { scope = 'local', win = winid })
>        nvim_set_option_value(OPTION, VALUE, { scope = 'local', win = winid }

**Comment by glepnir** [comment] 2023-01-26 09:41
min config also use the `nvim_win_set_option` for winhl. it also not work

**Comment by lewis6991** [comment] 2023-01-26 09:44
`nvim_win_set_option` is the same as `vim.wo`.

Please read my comments! You need to use `nvim_set_option_value` with `scope = 'local'`.

**Comment by glepnir** [comment] 2023-01-26 09:46
guess so . I will read source code then . thx

**Comment by glepnir** [comment] 2023-01-26 10:16
i had tried the `setlocal` `nvim_set_option_value` it not work.  please try it  ?
