### ISSUE TITLE
normal mode command 'gx' (open url) does not work in terminal buffer. 

### ISSUE THREAD

**Issue by yzhuang** [neovim/neovim#4612] opened 2016-04-19 21:22 UTC
- Neovim version: 0.1.3
- [Yes - Vim does not have terminal buffers ] Vim behaves differently?  
- Operating system/version: OS X 10.11.4
- Terminal name/version: iterm2
- `$TERM`: xterm-256color
### Actual behaviour

In neovim terminal buffer, when cursor is placed on an URL, pressing 'gx' opens some garbage URL.
Error message from neovim is:

> Error detected while processing function netrw#BrowseXVis[5]..netrw#BrowseX[53]..netrw#NetRead[5]..<SNR>96_NetrwSafeOptions:
> line    9:
> E474: Invalid argument: bt=nofile
> "NetrwMessage"  --No lines in buffer--
### Expected behaviour

In vim and neovim, when cursor is placed on an URL in normal mode, pressing 'gx' opens the URL in a browser. This works fine for neovim in regular buffers.

**Comment by dm1try** [comment] 2016-06-01 12:29
btw, this is related to [`netrw#CheckIfRemote()`](https://github.com/neovim/neovim/blob/master/runtime/autoload/netrw.vim#L5193-L5195) which returns `true` for terminals because of the terminal buffer name `term://something...` 
If you rename the terminal buffer then all works fine.

**Comment by lingceng** [comment] 2018-01-02 07:12
I use a map to fix it. The Open function use 'open' command which is only available on mac.

```vimscript
function! Open(url)
  silent execute '!open ' . a:url
  redraw!
endfunction

autocmd BufEnter term://* nnoremap <buffer> gx viW"xy \| :call Open(@x)<CR>
```

**Comment by yzhuang** [comment] 2018-01-02 08:18
yea, I ended up remapping `gx` as well, using this:

```
Plug 'tyru/open-browser.vim' "{
  " Disable netrw gx mapping.
  let g:netrw_nogx = get(g:, 'netrw_nogx', 1)
  nmap gx <Plug>(openbrowser-open)
  vmap gx <Plug>(openbrowser-open)
"}
```

**Comment by justinmk** [comment] 2018-06-24 22:45
This seems to be fixed now, though netrw has other bugs.

**Closed by justinmk** 2018-06-24 22:45 UTC
Labels: bug

**Comment by dm1try** [comment] 2020-03-17 21:59
still reproducible on my side.
I ended up remapping `gx` as well 😐 :
```
nmap <silent> gx :!open <cWORD><cr>
```
