### ISSUE TITLE
[Feature Request]Show character before pumvisible items.

### ISSUE THREAD

**Issue by fgheng** [neovim/neovim#13213] opened 2020-11-03 11:49 UTC
- `nvim --version`: 0.5.0-789
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Arch Linux
- Terminal name/version: Alacritty
- `$TERM`: screen-256color

![image](https://user-images.githubusercontent.com/50551377/97981236-ebd55680-1e0c-11eb-9c44-e9ad6c37993a.png)
hello, could you add a column before pumvisible items?
I want to put the symbol in the red box in the green box.

**Comment by glacambre** [comment] 2021-06-09 05:41
I think this is a duplicate of https://github.com/neovim/neovim/issues/12320 , so I'll close this issue. @fgheng please subsribe to the other issue if you want to be notified once this is implemented :)

**Closed by glacambre** 2021-06-09 05:41 UTC
Labels: enhancement
