### ISSUE TITLE
`E5248: Invalid character in group name` when opening .tfvars file using terraform-ls

### ISSUE THREAD

**Issue by renzepost** [neovim/neovim#23717] opened 2023-05-22 10:09 UTC
### Problem

I'm using the `terraform-ls` LSP, and when opening a `.tfvars` file in my repository I get the error `E5248: Invalid character in group name`. This happens when I use Mason and lsp-config, but I have managed to reproduce the issue with the latest build of nvim without any plugins as well.

### Steps to reproduce

Ensure `terraform-ls` is installed [manually](https://github.com/hashicorp/terraform-ls/blob/main/docs/installation.md)
Clone this example TF repo: https://github.com/hashicorp/tfc-guide-example
`cd tfc-guide-example`
`nvim --clean variables.auto.tfvars`
`:lua =vim.lsp.start({name='terraform-ls',cmd={'terraform-ls', 'serve'},root_dir='/path/to/tfc-guide-example'})`
Keep note of the client ID that is returned by the above command
`lua =vim.lsp.buf_attach_client(0, <client ID>)`
Now, start inserting some text, like `region = "foo"`. The error will start appearing.

### Expected behavior

No error

### Neovim version (nvim -v)

NVIM v0.10.0-dev-370+gb7708eac2

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Ubuntu 20.04.6 WSL2

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment] 2023-05-22 10:16
Duplicate of #23184

**Closed by zeertzjq** 2023-05-22 10:16 UTC
Labels: bug, lsp
