### ISSUE TITLE
The term and nvim display icons differently

### ISSUE THREAD

**Issue by xaotag** [neovim/neovim#23780] opened 2023-05-27 03:23 UTC
### Problem

https://github.com/neovim/neovim/assets/40427877/65650d13-b6a5-4377-b2f7-8964e5cffdfa

### Steps to reproduce

.

### Expected behavior

The icons displayed in the terminal and nvim are consistent

### Neovim version (nvim -v)

NVIM v0.10.0-dev-383+gaa9d46b672

### Vim (not Nvim) behaves the same?

Vi IMproved 9.0,yes

### Operating system/version

Arch Linux x86_64

### Terminal name/version

WezTerm

### $TERM environment variable

xterm-256color

### Installation

arch paru -S neovim-git ,but cn aur

**Comment by xaotag** [comment] 2023-05-27 03:26
OK,but kitty term

https://github.com/neovim/neovim/assets/40427877/8c157803-5148-4bc4-a21c-0be34676f412

**Comment by zeertzjq** [comment] 2023-05-27 03:59
Duplicate of #22014

**Closed by zeertzjq** 2023-05-27 03:59 UTC
Labels: bug
