### ISSUE TITLE
Piping NodeJS output into Neovim makes the editor unusable

### ISSUE THREAD

**Issue by jeremija** [neovim/neovim#18470] opened 2022-05-07 18:57 UTC
### Neovim version (nvim -v)

```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 25 2022 22:13:25)

### Operating system/version

Arch Linux

### Terminal name/version

```
alacritty 0.10.1 (2844606d)
```

### $TERM environment variable

```
alacritty
```

### Installation

Arch Linux Repository (`sudo pacman -S neovim`)

### How to reproduce the issue

```
node -e 'console.log("test")' | nvim -u <(echo "let s:test = system('echo test')") -
```

### Expected behavior

I expect to be able to use the `hjkl` keys to move the cursor.

Using the following commands works fine:

- `node -e 'console.log("test")' | nvim -u <(echo '') -`
- `echo 'test' | nvim -u <(echo "let s:test = system('echo test')") -`
- `python -c 'print("test")'| nvim -u <(echo "let s:test = system('echo test')") -`

Also, piping the NodeJS output into vim also works:

- `node -e 'console.log("test")' | vim -u <(echo "let s:test = system('echo test')") -`

So there must be some weird thing happening when Neovim is trying to read from stdin from a NodeJS process, and when the `system` function is called in the config. The same thing happens if the config file contains a line like `silent execute !echo test`.

```
$ node --version
v18.1.0

$ echo $SHELL
/usr/bin/zsh

$ zsh --version
zsh 5.8.1 (x86_64-pc-linux-gnu)
```

Happens in bash too.

### Actual behavior

The cursor key letters just end up overwriting the editor content on the screen, and when I press CTRL+C it exits.

**Comment by justinmk** [comment] 2022-05-12 01:01
All of your examples work fine for me (macos, Nvim cf68f0a51202).

    node -e 'console.log("test")' | nvim -u <(echo "let s:test = system('echo test')") -

Maybe the `<(...)` file is where the trouble is, not stdin (`-`). What's the point of that anyway? Does it work if you use `-c` instead?

    node -e 'console.log("test")' | nvim -c "let g:test = system('echo test')" -

**Comment by jeremija** [comment] 2022-05-12 07:38
Yes I can reproduce it even with `node -e 'console.log("test")' | nvim -c 'let g:test = system("echo test")' -`.

I was not aware of the `-c` flag, and I used `<()` ([process substitution](https://tldp.org/LDP/abs/html/process-sub.html)) to write a config file on the fly.

I can also reproduce this on Termux for Android.

**Comment by jeremija** [comment] 2022-05-12 07:42
Sorry, I actually take that back, I cannot reproduce it with the `-c` flag. But can you please try putting `let s:test = system('echo test')` in a `nvimrc` file and starting neovim with `nvim -u nvimrc`.

For example:

**nvimrc**

```vimscript
let s:test = system('echo test')
```

Then run:

```
node -e 'console.log("test")' | nvim -u nvimrc -
```

**Comment by justinmk** [comment] 2022-05-12 12:19
As I said above, the `<()` form works for me, and so does the `-u nvimrc` form.

**Comment by jeremija** [comment] 2022-05-13 07:49
I see your point, but is it possible that it's only reproducible on Linux?

I've already tested it on the latest version (nvim 0.7.0) as you can see on my bug report.

But just to make sure it's not something specific on my local machine, I've created a `Dockerfile` that installs the latest version of Neovim and NodeJS and runs the same command:

```
FROM ubuntu:22.04

RUN  apt-get update \
  && apt-get install -y \
    wget \
    xz-utils \
  && rm -rf /var/lib/apt/lists/*


RUN wget https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.tar.gz
RUN wget https://nodejs.org/dist/v16.15.0/node-v16.15.0-linux-x64.tar.xz

RUN tar xzvf nvim-linux64.tar.gz
RUN tar xvf node-v16.15.0-linux-x64.tar.xz

RUN echo "let g:test = system(\"echo test\")" > nvimrc

CMD ["bash", "-c", "/node-v16.15.0-linux-x64/bin/node -e 'console.log(\"test\")' | /nvim-linux64/bin/nvim -u /nvimrc"]
```

and I can reproduce the issue by running:

```
docker build . --tag nvim-test
docker run --rm -it nvim-test
```

See the below video:

https://user-images.githubusercontent.com/1489493/168236389-83c6984c-f827-4316-9f7b-baaeaefd9c49.mp4

**Comment by zeertzjq** [comment] 2022-05-13 08:30
Both `node -e 'console.log("test")' | nvim -u <(echo "let s:test = system('echo test')") -` and `node -e 'console.log("test")' | nvim -u <(echo '') -` make Nvim unusable for me on Arch Linux with bash, so it is unrelated to `system()`.

**Comment by zeertzjq** [comment] 2022-05-13 08:36
The `<(...)` isn't needed either. I can reproduce with `-u` followed by an empty config.

**Comment by justinmk** [comment] 2022-05-13 12:58
Is this another case of https://github.com/neovim/neovim/issues/16809 ? I don't understand why https://github.com/neovim/neovim/pull/12531 was merged, it was not fully formed.

**Comment by jeremija** [comment] 2022-05-13 15:44
I tried adding a delay to stdin like `echo $(sleep 2; echo test) | nvim -u nvimrc -` and I was unble to reproduce the issue, so I'm not sure if it's related to the first issue you linked.

**Comment by erw7** [comment] 2022-05-14 04:27
This problem is caused by `node` changing the state of the `tty` on exit after call to `uv_tty_set_mode()` on neovim. In some cases, this may not happen due to race condition issues. However, you should be able to trigger this problem in almost any system by intentionally delaying the end of node as follows.

```sh
node -e "setTimeout(()=>{console.log('test')}, 1000)" | nvim -u NORC --cmd 'sleep 500m' -
node -e "setTimeout(()=>{console.log('test')}, 1000)" | nvim -u NORC --cmd "let g:test = system('echo test')" -
```

This issue should have been fixed by #13084. However, some commands and functions (`:sleep`, `system()` etc.) call `ui_flush()` internally, and this problem occurs because the first `tui_mode_change()` is called before the end of startup. Therefore, this problem will not occur if `ui_call_mode_change()` is not called when `starting` is `true`.

**Comment by KevinSJ** [comment] 2022-06-07 08:43
Hello @erw7 and @justinmk , I would like to work on this if you don't mind. After some digging, I found this boils down to changing this part of the file. 
https://github.com/neovim/neovim/blob/9e442c17eeffca934c1de3674b910458e04c989b/src/nvim/generators/gen_api_ui_events.lua#L196-L199
My thinking is to add a condition checking if ev.name is 'mode_change', if that's the case then the first true this code should be changing to something like `!((TUIData *)ui->data)->is_starting`. But it looks like that's not the correct way to do this, would you mind giving some hints? 
`write_signature(call_output, ev, '!((TUIData *)ui->data)->is_starting, '..ev.name..', ui', true)`

**Comment by justinmk** [comment] 2022-06-07 16:52
@KevinSJ sounds like a good direction, send a PR, can't do a code review in comments here.

**Comment by erw7** [comment] 2022-06-11 02:31
> I would like to work on this if you don't mind.

PR is welcome. Please create PR.

> But it looks like that's not the correct way to do this, would you mind giving some hints?

The condition used is `!starting`, not `!((TUIData *)ui->data)->is_starting.`.

https://github.com/neovim/neovim/blob/2b252430aa9ef52de7da733e2c0221c97111bce2/src/nvim/globals.h#L492-L493

**Comment by KevinSJ** [comment] 2022-06-12 04:07
@erw7 @justinmk Thanks for your reply. It looks like using !starting as condition would not fix the issue completely, I still created the PR here -- https://github.com/neovim/neovim/pull/18932
I have attached a screencast of what it looks like on mine local after changing that condition:

https://user-images.githubusercontent.com/7546654/173213959-ee6094a2-5022-4f2d-88f9-75b2248b37b1.mp4

**Comment by erw7** [comment] 2022-06-12 09:51
Very strange, but the next first patch solves this problem, but the second patch, which works similarly to your PR, does not solve the problem. The debug build log shows that in both cases the first call to `UI: mode_change` is delayed until the reading from `stdin` is finished (starting main loop), as intended.

```diff
diff --git a/src/nvim/ui.c b/src/nvim/ui.c
index d66e57b13..2f445b6a6 100644
--- a/src/nvim/ui.c
+++ b/src/nvim/ui.c
@@ -520,7 +520,7 @@ void ui_flush(void)
     api_free_array(style);
     pending_mode_info_update = false;
   }
-  if (pending_mode_update) {
+  if (pending_mode_update && !starting) {
     char *full_name = shape_table[ui_mode_idx].full_name;
     ui_call_mode_change(cstr_as_string(full_name), ui_mode_idx);
     pending_mode_update = false;
```

```diff
diff --git a/src/nvim/ui.c b/src/nvim/ui.c
index d66e57b13..02ae872df 100644
--- a/src/nvim/ui.c
+++ b/src/nvim/ui.c
@@ -521,8 +521,10 @@ void ui_flush(void)
     pending_mode_info_update = false;
   }
   if (pending_mode_update) {
-    char *full_name = shape_table[ui_mode_idx].full_name;
-    ui_call_mode_change(cstr_as_string(full_name), ui_mode_idx);
+    if (!starting) {
+      char *full_name = shape_table[ui_mode_idx].full_name;
+      ui_call_mode_change(cstr_as_string(full_name), ui_mode_idx);
+    }
     pending_mode_update = false;
   }
   if (pending_has_mouse != has_mouse) {
```

What is even more curious is that in the case of the second patch, the same problem occurs in the next step, even though this problem did not occur before the fix. It seems we need to consider this a little more.

```
node -e "setTimeout(()=>{console.log('test')}, 1000)" | nvim -u NORC +"sleep 500m" -
```

**Comment by KevinSJ** [comment] 2022-06-12 11:19
@erw7 I should have done it like either of the ways you pointed out. It is cleaner than what I have in my current PR. I will update it once we have a conclusion on whether the first one works correctly.

Looks like the problem is that `pending_mode_update` variable is set to false in the second scenario (and in my PR). I tend to think this `ui_flush` function is called more than once during the startup cycle and that variable should only be set to false if and only if actual mode change occurs (in the second scneario the mode is not changed, but the variable is changed to false)?

**Comment by erw7** [comment] 2022-06-12 14:56
@KevinSJ I thought it was a good idea because even though there are more calls to `ui_call_mode_change()`, if it is your PR change we don't have to change it again. However, your PR method does not seem to work because the first `tui_mode_change()` call is too late. It seems that changing mode with `i<CR>` or `:<CR>` will call  `tui_mode_change()` and `TTY` will change to RAW mode.

Sorry, can you please correct the PR?

**Comment by KevinSJ** [comment] 2022-06-13 08:16
@erw7 of course, I've updated the PR.

**Closed** 2022-06-19 15:22 UTC
Labels: bug, tui, io, complexity:low, status:has-plan, system, startup
