### ISSUE TITLE
Nightly - crash to prompt, decoration provider

### ISSUE THREAD

**Issue by grappas** [neovim/neovim#26181] opened 2023-11-23 21:57 UTC
### Problem

`nvim: /home/main-builder/pkgwork/src/neovim/src/nvim/decoration_provider.c:127: decor_providers_invoke_win: Assertion `kv_size(decor_state.active) == 0' failed. `

### Steps to reproduce

1. Install neovim nightly.
2. Install Lazyvim
3. Use live_grep in telescope and hit enter or start searching with flash.nvim
4. bug occurs

### Expected behavior

no bug

### Neovim version (nvim -v)

v0.10.0-dev-1627+g879617c9bb

### Vim (not Nvim) behaves the same?

0.9.4

### Operating system/version

Arch Linux/Hyprland

### Terminal name/version

Foot 1.16.2

### $TERM environment variable

foot

### Installation

AUR

**Comment by zeertzjq** [comment] 2023-11-23 22:00
Duplicate of #26171

**Closed by zeertzjq** 2023-11-23 22:00 UTC
Labels: bug
