### ISSUE TITLE
Neovim Lags and produces unwanted garbage characters on exit from insert mode.

### ISSUE THREAD

**Issue by jgkamat** [neovim/neovim#2100] opened 2015-03-05 16:12 UTC
As part of my workflow, I commonly press 'o' type something, quickly press esc, and move up and down (with j/k). When I press up/down after escaping from insert mode, I get garbage characters, and nvim doesn't actually switch to normal mode. 

It seems like there is a lot of lag when exiting insert mode, and when I press any keys during this lag, the switch doesn't take place.

This issue is present when I deleted my ~/.vim folder, and my nvimrc.

**Comment by acoffman** [comment] 2015-03-05 16:22
Is this a dupe of #2093?

**Comment by justinmk** [comment] 2015-03-05 16:41
see also:

https://github.com/neovim/neovim/issues/2017#issuecomment-75235455

https://github.com/neovim/neovim/issues/2017#issuecomment-75513139

**Closed by justinmk** 2015-03-05 16:41 UTC
Labels: duplicate
