### ISSUE TITLE
LSP refresh references highlighting without blinking

### ISSUE THREAD

**Issue by mitinarseny** [neovim/neovim#15306] opened 2021-08-07 22:53 UTC
### Feature description

Currently, new NeoVim 0.5.0 LSP Lua client has support of following functions:
```vim
highlight LspReferenceText cterm=underline
autocmd CursorMoved,CursorMovedI <buffer> lua vim.lsp.buf.clear_references()
autocmd CursorMoved,CursorMovedI <buffer> lua vim.lsp.buf.document_highlight()
```
But with these commands and `updatetime` set to `200` references highlighting is blinking every time I move cursor, even staying on the same variable name. It would be great is there is one function like `vim.lsp.buf.document_rehighlight()` which updates screen only once.

**Comment by justinmk** [comment] 2021-09-24 14:32
closing because:

1. cannot reproduce , NVIM v0.6.0-dev+339 bc570b006413
2. display flicker is a general UI performance issue, covered by other issues
3. this is too special-case

**Closed by justinmk** 2021-09-24 14:32 UTC
Labels: enhancement, lsp

**Comment by cblessing24** [comment] 2022-07-08 12:15
This works for me @mitinarseny:

```lua
local augroup = vim.api.nvim_create_augroup("LspDocumentHighlight", { clear = false })
vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
vim.api.nvim_create_autocmd({ "CursorMoved", "CursorMovedI" }, {
	group = augroup,
	buffer = bufnr,
	callback = function()
		vim.lsp.buf.clear_references()
		vim.lsp.buf.document_highlight()
	end,
})
```

**Comment by cblessing24** [comment] 2022-07-08 12:18
Nevermind I still get some flickering while moving over the same variable.

**Comment by williamhCode** [comment] 2023-02-07 21:21
I use CursorHold for the document highlight.
```lua
if client.server_capabilities.documentHighlightProvider then
    local group = vim.api.nvim_create_augroup("lsp_document_highlight", { clear = false })
    vim.api.nvim_clear_autocmds { buffer = bufnr, group = group }
    vim.api.nvim_create_autocmd("CursorHold", {
        callback = vim.lsp.buf.document_highlight,
        buffer = bufnr,
        group = group,
    })
    vim.api.nvim_create_autocmd("CursorMoved", {
        callback = vim.lsp.buf.clear_references,
        buffer = bufnr,
        group = group,
    })
end
```
If the `updatetime` is longer than how fast your keyboard repeat keys, there shouldn't be any flicker (except your keyboard repeat trigger time which may be longer, so it might flicker when you start moving). But I set my `updatetime=250`, and with macOS key repeat set to the lowest, I don't see any flickering
