### ISSUE TITLE
gco and gcO to insert a comment below and above and go into Insert mode

### ISSUE THREAD

**Issue by nikitarevenco** [neovim/neovim#30355] opened 2024-09-12 12:20 UTC
### Problem

Inserting a comment not on the current line, but rather on the line above or below is a very common task

### Expected behavior

It would be useful to have default keymap for `gco` and `gcO` which would insert a comment on the line below or above, respectively

### gco

Cursor: line 2
Mode: Normal
```lua

local random_number = 7

```

After pressing `gco`

Cursor: line 3, at `<cursor>`
Mode: Insert
```lua

local random_number = 7
-- <cursor>
```

### gcO

Cursor: line 1
Mode: Normal
```lua
local random_number = 7
```

After pressing `gcO`

Cursor: line 1, at `<cursor>`
Mode: Insert
```lua
-- <cursor>
local random_number = 7
```

**Comment by clason** [comment] 2024-09-12 12:22
Duplicate of #28979

**Closed by clason** 2024-09-12 12:22 UTC
Labels: enhancement
