### ISSUE TITLE
rxvt: After clicking on tabline, dragging in other parts of the UI doesn't work

### ISSUE THREAD

**Issue by pnloyd** [neovim/neovim#5400] opened 2016-09-28 16:21 UTC
- nvim: 0.1.6-dev
- OS: Linux mint 18
- Term: rxvt-unicode 9.22
- `$TERM`: rxvt-unicode-256color

After clicking anywhere on the tab like, any further attempts to "drag" other parts of the UI fail.

To reproduce in nvim -u NORC:
:tabe | split | vsplit
Click anywhere on the tab line.
Observe that clicking and dragging on separators or text moves tabs instead of moving splits or creating visual mode selections. 

After looking at code in [normal.c](https://github.com/neovim/neovim/blob/master/src/nvim/normal.c#L2476) I believe the problem is that after the mouse has been released the bool in_tab_line (indicating click originated in the tabline) doesn't get reset to false. I have a fix [(25578b)](https://github.com/pnloyd/neovim/commit/25578bd1a06f295d0c3237f0a04ab3119bef9852) for this, but the fact that that separators are using a completely different method of tracking whether they are dragging makes me doubt if it's the appropriate approach.

**Comment by justinmk** [comment] 2016-09-28 18:20
Thanks for investigating! Maybe @sach1t can help you.

**Comment by pnloyd** [comment] 2016-09-28 19:21
Thanks, the function that's handling click events is over 600 lines long, and is handling both the logic for the tabs/separators/visual mode. Looks like the parts dealing with "VIsual" mode and separators are tightly intertwined, while the logic for the tabs is mostly (completely?) separate.

I feel like if it was a goal to develop/extend UI components, the logic for what is being clicked or dragged should be separated from from how those UI components should react. Otherwise this function could head into a pretty messy direction. Possibly a sort of event driven system might improve this situation?

**Comment by justinmk** [comment] 2016-09-29 08:22
Visual mode isn't a UI component, it's part of the global editor state. 

Though no disagreement with your general thought.

**Comment by sach1t** [comment] 2016-10-01 17:30
This seems to be only impacting rxvt, as I cannot reproduce this on xterm or gnome-terminal. It may  have something to do with libtermkey, I remember someone commented about the release events not working on rxvt.

**Comment by justinmk** [comment] 2016-10-01 17:40
Thanks, marking as unplanned then. Patch definitely welcome, but rxvt is low-priority.

**Comment by pnloyd** [comment] 2016-10-01 19:54
Just as a note on this, I'm not able to test if is happening for me in
non-rxvt terminals (because I'm setting up a new machine ATM), but I do
remember that VIM did not have this problem with rxvt. I'll test more when
I'm able to.

**Comment by justinmk** [comment] 2016-10-01 22:16
> VIM did not have this problem with rxvt. 

Yes, Nvim regressed with respect to terminal support. But we gained (1) a decoupled UI (important for externalized UIs), and (2) better support for some terminal features such as bracketed paste. See also https://github.com/neovim/neovim/issues/5385#issuecomment-249440001

**Comment by KeithScheiwiller** [comment] 2017-04-24 15:02
Just a small (hopefully useful) addition to this: The reason I noticed it happening is that clicking and dragging a vsplit after having clicked somewhere in the tabbar causes the current tab to move instead (as if you were clicking and dragging on the tagbar). It seems to persist in this state until restart. Slightly frustrating but not the end of the world.

This is in urxvt. I don't know about other terminal emulators.

**Comment by KeithScheiwiller** [comment] 2017-07-17 13:29
Is this something that's still on the roadmap somewhere? It's quite frustrating when my tabs keep changing order as it messes up my keybindings to switch between them.

**Comment by justinmk** [comment] 2017-07-17 14:31
This is on the "unplanned" milestone. Milestones define the roadmap. rxvt support might improve with the recent work that is being done on the TUI, but other than that this is, again, a low priority. Patches always welcome, of course, but I personally don't care about rxvt and it seems like no one else does either.

**Comment by KillTheMule** [comment] 2017-07-18 07:36
As a side node, I can reproduce the problem in xterm. This system is ancient though...

**Comment by vsajko** [comment] 2017-09-27 22:33
it is reproducible on Debian Stretch on:
alacritty 0.1.0
qterminal 0.7.1 (probably konsole also)
urxvt 9.22

it is not reproducible on:
xterm 327
GNOME Terminal 3.22.2 Using VTE version 0.46.1 +GNUTLS
kitty 0.3.0
stterm

**Comment by justinmk** [comment] 2017-09-28 06:48
@vsajko please mention exact nvim version

**Comment by vsajko** [comment] 2017-09-28 07:34
@justinmk 
:version                                                                                                                                                                                                                                                                         
NVIM v0.2.1-906-g542ed5f5d

**Comment by justinmk** [comment] 2017-12-22 19:34
Most likely related to https://github.com/neovim/neovim/issues/3458

**Comment by bew** [comment] 2017-12-22 19:45
@justinmk how is it related to #3458 ?

**Closed** 2018-04-22 17:26 UTC
Labels: bug, tui
