### ISSUE TITLE
"*" does not add to jumplist if cursor line does not change

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#9874] opened 2019-04-09 14:21 UTC
- `nvim --version`:      NVIM v0.4.0-529-gfb555c689 Build type: RelWithDebInfo
 - Vim (version: 8.1-1119) behaves differently? Yes.
 - Operating system:     Ubuntu 16.04.6 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.9
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.7.1-dev-0 (x86_64-pc-linux-gnu)

### Steps to reproduce using `nvim -u NORC`

Consider this shell command:

    $ printf 'hello world' | nvim -Nu NONE +'norm! fr' -

### Actual behaviour

If I press `*` while the cursor is on the `r` of `hello world`, the cursor jumps to the start of the word `world`.

Now, if I press `C-o` to jump back to where I was (the `r` in `world`), it raises the error `E37`:

    E37: No write since last change (add ! to override)

![gif](https://user-images.githubusercontent.com/8505073/55807717-f7eb1c00-5ae2-11e9-827f-fe9eeaca4c3d.gif)

Neovim tries to jump to a location in another file, and it didn't add the original position to the jumplist.

Had there been two occurrences of the word `world`:

    $ printf 'hello world\nhello world' | nvim -Nu NONE +'norm! fr' -

Then the position would have been added.

In Vim, it doesn't matter whether the current word is present once or multiple times in the buffer. The current position is always added to the jumplist before a `*` motion.

![gif](https://user-images.githubusercontent.com/8505073/55807864-3ed91180-5ae3-11e9-8525-2fe96a4f7d83.gif)

I rely on this behavior in a plugin similar to [vim-slash](https://github.com/junegunn/vim-slash) to restore the position of the cursor after a `*` search (I just want the search register to be populated and all the occurrences to be highlighted).
In Vim it works consistently; in Neovim, it works only when the word under the cursor is present more than once in the current buffer.

### Expected behaviour

Before `*` jumps, I expected the current position to be added to the jumplist, like in Vim, regardless of the number of occurrences of the word under the cursor.

**Comment by justinmk** [comment] 2019-04-09 18:12
Bisected to 35362495c . Note that backtick-backtick still works.

> I rely on this behavior in a plugin similar to [vim-slash](https://github.com/junegunn/vim-slash) to restore the position of the cursor after a `*` search

Can you use backtick-backtick instead?

A patch that fixes this regression, without regressing 35362495c, is welcome.

**Comment by lacygoill** [comment] 2019-04-09 18:41
You're right, ``` `` ``` is a good replacement for C-o. Thank you very much for your answer.

**Comment by justinmk** [comment] 2019-08-21 12:07
backtick-backtick for return within a line is reasonable, so I am marking this `wontfix`.

**Closed by justinmk** 2019-08-21 12:07 UTC
Labels: +workaround, bug-regression, editor, help wanted

**Comment by haya14busa** [comment] 2020-02-03 16:34
<code>``</code> itself updates jumplist while `<C-o>` move the cursor to older position in jumplist, so it's not drop-in replacement.

Also it doesn't make sense to me at all that the behavior changes depending on the cursor position and it broke compatibility with Vim (including usage from existing Vim script) unnecessarily, IMO...

**Comment by commonquail** [comment] 2020-07-22 17:34
> it doesn't make sense to me at all that the behavior changes depending on the cursor position

I perceived it not as an intended change in behaviour but as a way to emulate that a particular event (record a jumplist entry) does not occur, only it uses incomplete (and insufficient) information.

This regression breaks one of my oldest mappings, and introduces an inconvenient exception to muscle memory for anyone that uses `*` (`#`) frequently without that mapping. It's bad enough that I'm not entirely convinced my slight improvement in #12607 is good enough for me. At the very least, I think this warrants a bigger mention in `vim-differences` than just

>   The jumplist avoids useless/phantom jumps.

**Comment by justinmk** [comment] 2023-07-12 17:54
Addressed by https://github.com/neovim/neovim/pull/21874

**Comment by stephenkraemer** [comment] 2023-07-26 12:24
Does that mean that * should be able to add multiple columns on the same line to the jump list? This isn't working for me at the moment (v0.9 and compiled from master). I tried to understand what is going on in #21874, but couldn't really see how it should affect this issue here. Thanks a lot for any info :)
