### ISSUE TITLE
diff_hlID() and hlID() are not compatible

### ISSUE THREAD

**Issue by rickhowe** [neovim/neovim#7314] opened 2017-09-24 04:24 UTC
I am using nvim v0.2.1-890 on Windows 7 and noticed that the return value of diff_hlID() is not equivalent with that of hlID().

I have opened two windows and make them diff mode. And when a cursor is on a 'DiffAdd' line,
`
diff_hlID(line('.'), col('.'))
`
returns 24 but 
`
hlID('DiffAdd')
`
returns 25. As a result,
`
synIDattr(diff_hlID(line('.'), col('.')), 'name')
`
returns 'FoldColumn', not 'DiffAdd'.
The same mismatch happens on 'DiffChange' and 'DiffText'

In nvim v0.2.1-25,
`
hlID('DiffAdd')
`
returns 24 so there was no mismatch.

Is that already reported in this issue?

**Comment by justinmk** [comment] 2017-09-24 14:55
Where does it say they should be the same? Does Vim have the same issue (please mention the exact Vim version you tested... as requested by the issue template)

**Comment by rickhowe** [comment] 2017-09-24 15:17
In Vim both ID have always been equivalent, as far as I know, since 7.3 and until even now 8.0.1142.

help diff_hlID says:
The highlight ID can be used with |synIDattr()| to obtain
syntax information about the highlighting.

help hlID says:
This can be used to retrieve information about the highlight
group.  For example, to get the background color of the
"Comment" group: >
	:echo synIDattr(synIDtrans(hlID("Comment")), "bg")

Both ID can be used for synIDattr() as well so they should be equivalent, I think.

**Comment by jamessan** [comment] 2017-09-26 17:50
I used the following to bisect when the change occurred.

```sh
$ printf '1\n2\n3\n' > ~/foo.txt
$ printf '1\n2\n4\n3\n' > ~/bar.txt
$ cat ~/repro.vim
edit ~/foo.txt
diffthis
split ~/bar.txt
diffthis
if synIDattr(diff_hlID(3, 1), 'name') == 'DiffAdd'
  qa
else
  quit
  cquit
endif
$ ./build/bin/nvim -u NONE -i NONE -S ~/repro.vim
```

The results point to 8d8b6224.

```
commit 8d8b6224d941567aeefc67beb471aea36b8bdc05
Author: Björn Linse <bjorn.linse@gmail.com>
Date:   Mon May 8 17:17:10 2017 +0200

    options: make 'highlight' read-only
```

Cc @bfredl

**Comment by glacambre** [comment] 2021-06-05 16:08
I can't reproduce this on master - I get `25` for both `diff_hlID(line('.'), col('.'))` and `hlID('DiffAdd')`, so I assume the bug is fixed. Closing this issue :).

**Closed by glacambre** 2021-06-05 16:08 UTC
Labels: bug, vimscript
