### ISSUE TITLE
Neovim overwrites user highlight groups

### ISSUE THREAD

**Issue by youginil** [neovim/neovim#23278] opened 2023-04-23 07:40 UTC
### Problem

I write some highlight groups in init.lua, it do not works as expected.

### Steps to reproduce

1. Save the following code to ~/.config/nvim/init.lua
```
vim.o.termguicolors = true
vim.g.colors_name = "hello"
vim.o.background = "light"

-- This is comment
vim.api.nvim_set_hl(0, "Comment", { fg = "#ff0000", italic = true })
```
2. Set Kitty theme `Github Light`
3. `nvim init.lua`
![Screen Shot 2023-04-23 at 3 23 03 PM](https://user-images.githubusercontent.com/11213808/233826186-301221d1-d75f-482f-9162-0ee090e48839.png)
`vim.sho_pos()` output
```
Syntax
  - luaComment links to Comment
```
```
:hi Comment
Comment        xxx ctermfg=4 guifg=Blue
```
4. Set Kitty theme `Gruvbox Dark`, it works fine
![Screen Shot 2023-04-23 at 3 25 31 PM](https://user-images.githubusercontent.com/11213808/233826178-3ec4bbd4-1e49-4d4f-8184-a45e9d37c40e.png)

### Expected behavior

User highlights should not be overwrited by neovim

### Neovim version (nvim -v)

NVIM v0.9.0 LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no check

### Operating system/version

macOS 10.15.7

### Terminal name/version

Kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

Github Release

**Comment by nullchilly** [comment] 2023-04-23 07:47
Can't reproduce with kitty 0.27.1

[Screencast from 2023-04-23 14-45-42.webm](https://user-images.githubusercontent.com/56817415/233826867-44a514b2-e6ee-49ae-823a-8003e5e81ace.webm)

**Comment by zeertzjq** [comment] 2023-04-23 08:22
Duplicate of #22614

**Closed by zeertzjq** 2023-04-23 08:22 UTC
Labels: bug

**Comment by youginil** [comment] 2023-05-02 03:39
I found a solution.

https://github.com/neovim/neovim/issues/22614#issuecomment-1530770510
