### ISSUE TITLE
Way to test neovim plugin on github CI / avoid hit enter to continue after message 

### ISSUE THREAD

**Issue by saidelike** [neovim/neovim#28886] opened 2024-05-21 07:52 UTC
### Problem

I would like to test a neovim plugin in github CI. The problem is that it seems to hang waiting for me to hit enter after a message is displayed. 

### Expected behavior

It would be nice to have a way to disable requiring to hit enter entirely for any message being displayed so it doesn't block in CI environment where no user interaction is possible.

I am aware of the "shortmess" option https://neovim.io/doc/user/options.html#%27shortmess%27 but it doesn't seem possible to disable them all for sure, at least it didn't seem to help me.

There is the noice plugin https://github.com/folke/noice.nvim that allows redirecting messages to notifications and it has the nice side effect of not requiring me to hit enter but it means installing an additional plugin just for that in CI to get a feature that could be nice to have in neovim itself.

**Comment by clason** [comment] 2024-05-21 07:58
Duplicate of #22478

**Closed by clason** 2024-05-21 07:58 UTC
Labels: enhancement

**Comment by saidelike** [comment] 2024-05-21 10:55
Hi,

Just thought I would come back here to let everyone know that I fixed the problem in my case. Indeed, my question was on github CI, not in a normal neovim use.

And so, using `--headless` (https://neovim.io/doc/user/starting.html#--headless) avoids that problem when executing on github CI and bypasses the "hit enter to continue" thing.
