### ISSUE TITLE
Auto-complete sometimes halts the program completely without any way to exit if you type too fast after opening the auto-complete menu.

### ISSUE THREAD

**Issue by AndyGozas** [neovim/neovim#15189] opened 2021-07-25 18:29 UTC
### Neovim Version

0.5.0

### Operating system/version:

Arch-linux 5.10.45-1-lts

### Terminal name/version:

st

### TERM environment variable

xterm

### Installation

Pacman

### Steps to reproduce

Add the following to your config, enable spellcheck, set g:autocompleteion to v:true and g:autocomplete_type to "buffer"

```
function! OpenCompletion()
    if pumvisible() && (g:autocompletion == v:true)
        if g:autocomplete_type == "buffer"
            call feedkeys("\<C-e>\<C-n>", "i")
        endif
        if g:autocomplete_type == "omni"
            call feedkeys("\<C-e>\<C-x>\<C-o>", "i")
        endif
        return
        redraw
    endif
    if ((v:char >= 'a' && v:char <= 'z') || (v:char >= 'A' && v:char <= 'Z')) && (g:autocompletion == v:true)
        if g:autocomplete_type == "buffer"
            call feedkeys("\<C-n>", "i")
        endif
        if g:autocomplete_type == "omni"
            call feedkeys("\<C-x>\<C-o>", "i")
        endif
        redraw
    endif
endfunction

autocmd InsertCharPre * noautocmd call OpenCompletion()
```

Then open neovim and type text very fast. It can be any text but it must be frequently space-separated. You can type some gibberish but it must be space separated every couple of keys for fastest bug reproduction

### 

- [ ] Please check the box if it's possible to reproduce the bug with `nvim --clean` as well

### Expected behavior

Such configuration should enable as-you-type auto-completion, closing and reopening auto-complete menu every time a character is pressed.

### Actual behavior

And it actually does that exact thing, but if you type too fast, it halts in an infinite loop. This works not only with my configuration but also with some existing as-you-type auto-complete plugins. There is no way to exit the program, no way to stop the infinite loop, you can only kill it from a different terminal.

**Comment by AndyGozas** [comment] 2021-07-25 18:34
I found the actual place where it halts -- in the file edit.c in function ins_compl_get_exp it checks if it has found all the matches by checking if the latest match position matches the first ever found match position. But if you type too fast, the first ever found match disappears and is never found again, so it just keeps going through the buffer over and over, never stopping, because that first match is the only thing that can stop it, and it does not exist anymore. I may have fixed it, but I`m not sure -- I have not fully tested the solution yet, but it does not halt anymore in my custom installation https://github.com/inceye/neovim.

**Comment by vigoux** [comment] 2021-07-27 17:25
Strangely enough I am not able to reproduce this bug...
Could you provide a simpler reproduction step ?

**Comment by AndyGozas** [comment] 2021-07-28 07:13
Maybe this config is outdated or i've forgotten to remove something. You can just use the complete config from here https://github.com/inceye/sali-nvim-build and turn on both autocomplete and spell check by pressing \`a and \`o (those are backticks, not quotes, I mean those that are on the same key as ~) in normal mode.

What you should see after that is that in insert mode, if you type anything normal like hello world, every time you type a letter the auto-complete menu should be visible and updated, and then just type some gibberish like spam "asfd afsd fdsa fasdf" WITH spaces in between, also I guess typing slightly different gibberish every time helps a little bit but it should still be similar. And it should be fast and it might take a few seconds. For me the halt happens almost always during the first 100 symbols, almost always on the third symbol in the word.
When it halts you'll just see a menu open with one option and there was some text on the bottom left that I don't remember. You will not be able to exit this state forever, you would not be able to type or change mode. And It will take an entire CPU core completely.

What happens in the code is it finds the first match right under the cursor, and then goes on to find other matches and probably in this moment either a new letter goes through or something else happens, I'm not entirely sure, but that first match is never found again, and since the condition to stop looking for matches is for the current match to have the same coordinates as the first match, it halts.

If even with all that you will not be able to reproduce the bug, I can record it on video for you to see.

**Comment by AndyGozas** [comment] 2021-07-30 13:11
I have just tested this again, and with my configuration that bug happens even in plain vim, without plugins without anything, just with the configuration from https://github.com/inceye/sali-nvim-build (general/settings.vim and keys/mappings.vim concateneted) and it also halts just like neovim does if you start typing too fast.

**Comment by Shougo** [comment] 2021-07-30 13:41
You should report it in Vim issues.

**Comment by AndyGozas** [comment] 2021-07-30 13:56
> You should report it in Vim issues.

I sure will, also I've found out that this state is in fact escapable, but only by pressing ^C (escape key does not work, only ^C does), and ^C must not be remapped to anything else (in vim it can be remapped and still allow you to escape this state when pressed). But even though this halt state is escapable, it's existence is still a bug, which I will report to vim issues, and which, in my opinion, should be fixed in neovim.

**Comment by Shougo** [comment] 2021-07-30 14:16
If it is fixed in Vim, neovim will be fixed by patch porting.

**Comment by AndyGozas** [comment] 2021-07-30 14:22
It is not fixed yet, and while the code is the same, it is located in a different file. I can port the patch from my pull-request to vim and submit it, but it just seems like it would be more work for you.

**Comment by clason** [comment] 2021-07-30 14:26
If it's just a different place, it would still be good to do that in order to avoid needless divergence that will make porting later patches harder. Having two different fixes for the same problem would be unwelcome.

**Comment by AndyGozas** [comment] 2021-07-30 14:29
Alright then, I will create a pull-request to vim and notify you when VIM guys reply.

**Comment by oberblastmeister** [comment] 2021-08-02 15:22
I am able to reproduce this issue. I have also faced this issue when working on some autocompletion plugins like rofl

**Comment by clason** [comment] 2021-08-02 15:28
https://github.com/vim/vim/pull/8672, for anyone wanting to follow along

**Comment by AndyGozas** [comment] 2021-08-06 07:31
Vim has patched the issue https://github.com/vim/vim/commit/6a230c6b32695393785ae64b440ce5f023a22382

**Comment by seandewar** [comment] 2021-09-17 17:55
Ported in #15364. Thanks for the patch.

**Closed by seandewar** 2021-09-17 17:55 UTC
Labels: status:has-vim-patch, bug-vim, completion
