### ISSUE TITLE
Support remote plugins/hosts over TCP

### ISSUE THREAD

**Issue by teto** [neovim/neovim#6543] opened 2017-04-17 20:40 UTC
In order to diagnose msgpack-rpc problems, I like using wireshark (www.wireshark.org) to see the msgpack messages rather than an ASCII dump of it. The plugin https://github.com/linear-rpc/msgpack-rpc-dissector/ though basic works with latest wireshark (2.3.0). Thus I wanted to use a TCP transport and thus start the remote plugins via TCP. It 

The main problem is for nvim to retrieve the channel id when creating the host since it's created on TCP establishement (More details available on https://github.com/neovim/python-client/issues/252).

I hacked a dirty solution for fun here https://github.com/teto/neovim/tree/on_accept which adds an OnNewSocket autocommand to let the vimscript providers retrieve the channel id (host discovery sleeps until the channel id is set).
It's a low priority issue and I don't intend to work on it further but I thought it could be helpful to document the problems I met.

**Comment by ZyX-I** [comment] 2017-04-18 09:16
TCP raises questions with security: if Neovim supports TCP it is expected to have some features for preventing unauthorized access because unlike UNIX domain sockets bound to filesystem and relevant unauthorised  access preventing capabilities TCP has no such own features. Why you just not use two domain sockets and a script passing data from one socket to another via TCP?

**Comment by ZyX-I** [comment] 2017-04-18 09:23
I think that this issue is essentially a duplicate of #4443: while they are not exactly the same, it is main part after which talking about TCP makes sense, and TCP access issues will most likely be fixed as a part of fixing #4443.

**Closed by ZyX-I** 2017-04-18 09:23 UTC
Labels: enhancement, rpc

**Comment by justinmk** [comment] 2017-04-18 09:25
Well, there are required changes to the runtime as discussed in https://github.com/neovim/python-client/issues/252
