### ISSUE TITLE
Statusline gets updated on every call from unrelated timer

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#14303] opened 2021-04-06 13:03 UTC
When there is a timer executing some function (unrelated to statusline), statusline gets updated on every call to timer function.

- `nvim --version`: NVIM v0.5.0-dev+1221-g9b2d4ff62
- `vim --version`: 8.0.1453
- Operating system/version: Ubuntu 18.04.2
- Terminal name/version: Gnome, 3.28.2-1ubuntu1~18.04.1
- `$TERM`: xterm-256color

### Steps to reproduce

I have written two config files: one uses Vimscript timer (`timer_start`) and the other uses Lua timer (`vim.loop.new_timer`). Both of them have statusline set to executable function which returns the number of times it has been called. In this setup number in statusline shows the number of times `statusline` option got evaluated since the start.

Steps:

- Run `nvim -u init_timer_vim.vim` and look at statusline.
- Run `nvim -u init_timer_lua.vim` and look at statusline.
- Run `vim -u init_timer_vim.vim` and look at statusline.

<details><summary>init_timer_vim.vim</summary>

```vim
" Set up global counter
let g:statusline_counter = 0

" Create statusline function
function MyStatusline()
  let g:statusline_counter = g:statusline_counter + 1
  return g:statusline_counter
endfunction

" Enable settings
set laststatus=2
set statusline=%!MyStatusline()

" Create timer which is unrelated to statusline settings
function MyHandler(timer)
endfunction

let timer = timer_start(200, 'MyHandler', {'repeat': 500})

" Results:
" - Neovim: just after opening, `g:statusline_counter` gets updated forever
"   every 200 ms, even though timer has nothing to do with statusline.
" - Vim: statusline `g:statusline_counter` isn't constantly updating.
```

</details>

<details><summary>init_timer_lua.vim</summary>

```vim
" Set up global counter
let g:statusline_counter = 0

" Create statusline function
function MyStatusline()
  let g:statusline_counter = g:statusline_counter + 1
  return g:statusline_counter
endfunction

" Enable settings
set laststatus=2
set statusline=%!MyStatusline()

" Create timer which is unrelated to statusline settings
lua << EOF
local timer = vim.loop.new_timer()
timer:start(200, 200, vim.schedule_wrap(function() end))
EOF

" Result: just after opening Neovim `g:statusline_counter` gets updated
" forever every 200 ms, even though timer has nothing to do with statusline.
```

</details>

### Actual behaviour

- Output of `nvim -u init_timer_vim.vim`:
<details><summary>Animation of Neovim with Vimscript timer</summary>

![neovim_statusline-issue_1](https://user-images.githubusercontent.com/24854248/113714255-e26c5500-96f0-11eb-8efc-efbafe645164.gif)

</details>

- Output of `nvim -u init_timer_lua.vim`:
<details><summary>Animation of Neovim with Lua timer</summary>

![neovim_statusline-issue_2](https://user-images.githubusercontent.com/24854248/113714451-121b5d00-96f1-11eb-8ff2-3a8259cf715c.gif)

NOTE:  in reality updates were smooth, every 200ms. Certain "lags" are because of recording.

</details>

- Output of `vim -u init_timer_vim.vim`:
<details><summary>Animation of Vim with Vimscript timer</summary>

![neovim_statusline-issue_3](https://user-images.githubusercontent.com/24854248/113714638-47c04600-96f1-11eb-86df-a228488b96f8.gif)

</details>

### Expected behaviour

Maybe this is by design, but my expectation is that statusline shouldn't update on every call to unrelated timer (like in Vim).

**Comment by seandewar** [comment] 2021-04-06 16:44
I've observed this too; probably related to/duplicate of #4847.

**Comment by echasnovski** [comment] 2021-04-06 18:15
Yeah, maybe they have the same cause. But there it is deduced that the most probable cause is "neovim-python API calls". Here it is definitely due to Vim's and Lua's timer calls.

**Comment by bfredl** [comment] 2021-04-06 18:25
The root cause could still be the same (both use the same event loop abstractions)

**Comment by echasnovski** [comment] 2021-04-08 14:28
I tried to look at source code and couldn't find even remotely how `timer_start` and `statusline` evaluation can be connected.

However, I noticed something that might be relevant: statusline for only current window is updated. Statusline for other windows and tabline are not updated.

Animation with 'init_timer_vim_2.vim' configuration:

![neovim_statusline-issue_4](https://user-images.githubusercontent.com/24854248/114044228-b509dd80-988f-11eb-80a4-1e60a795c251.gif)

<details><summary>init_timer_vim_2.vim</summary>

```vim
" Set up global counter
let g:statusline_counter = 0
let g:statuslineNC_counter = 0
let g:tabline_counter = 0

" Create statusline function
function MyStatusline()
  let g:statusline_counter = g:statusline_counter + 1
  return g:statusline_counter
endfunction

function MyStatuslineNC()
  let g:statuslineNC_counter = g:statuslineNC_counter + 1
  return g:statuslineNC_counter
endfunction

function MyTabline()
  let g:tabline_counter = g:tabline_counter + 1
  return g:tabline_counter
endfunction

" Enable settings
set laststatus=2
set showtabline=2
set tabline=%!MyTabline()

" Define statusline behavior
augroup Statusline
  au!
  au WinEnter,BufEnter * setlocal statusline=%!MyStatusline()
  au WinLeave,BufLeave * setlocal statusline=%!MyStatuslineNC()
augroup END

" Create timer which is unrelated to statusline settings
function MyHandler(timer)
endfunction

let timer = timer_start(200, 'MyHandler', {'repeat': 500})

" Results:
" - Neovim: just after opening, **only** `g:statusline_counter` gets updated
"   forever every 200 ms, even though timer has nothing to do with statusline.
" - Vim: nothing is updated.
```

</details>

**Comment by zeertzjq** [comment] 2022-03-12 13:15
A hacky fix I found:
```diff
diff --git a/src/nvim/normal.c b/src/nvim/normal.c
index 0e5e0ab40..742a69023 100644
--- a/src/nvim/normal.c
+++ b/src/nvim/normal.c
@@ -1345,7 +1345,9 @@ static void normal_redraw(NormalState *s)
   did_emsg = false;
   msg_didany = false;  // reset lines_left in msg_start()
   may_clear_sb_text();  // clear scroll-back text on next msg
-  showruler(false);
+  if (nv_cmds[s->idx].cmd_char != K_EVENT) {
+    showruler(false);
+  }
 
   setcursor();
 }
```

**Comment by lewis6991** [comment] 2022-04-06 10:52
Any chance we can get that hacky fix in?

**Comment by zeertzjq** [comment] 2022-04-06 10:59
Actually I think it is not really clear what the intended behavior should be, as it is possible for a timer or an RPC call to change some variable related to statusline.

**Comment by lewis6991** [comment] 2022-04-06 11:07
In such cases, shouldn't there be an explicit call to refresh the status bar? I feel the current behaviour is really undesirable.

**Comment by bfredl** [comment] 2022-04-13 07:40
We could try this early in the 0.8 and get some feedback. there is also the `:redrawstatus` command (though it might be too greedy, better with a command which marks it as redraw-later).

**Comment by zeertzjq** [comment] 2022-05-20 09:40
> A hacky fix I found:
> 
> ```diff
> diff --git a/src/nvim/normal.c b/src/nvim/normal.c
> index 0e5e0ab40..0985bc8da 100644
> --- a/src/nvim/normal.c
> +++ b/src/nvim/normal.c
> @@ -1345,7 +1345,9 @@ static void normal_redraw(NormalState *s)
>    did_emsg = false;
>    msg_didany = false;  // reset lines_left in msg_start()
>    may_clear_sb_text();  // clear scroll-back text on next msg
> -  showruler(false);
> +  if (s->idx < 0 || nv_cmds[s->idx].cmd_char != K_EVENT) {
> +    showruler(false);
> +  }
>  
>    setcursor();
>  }
> ```
> 
> `normal_redraw()` is called before `normal_execute()`, so this checks `s->idx` for the last normal mode command character (as `s->c` has already been cleared here).

Note: this fix only fixes the problem in Normal mode. In Insert mode another fix is needed.

**Comment by zeertzjq** [comment] 2022-08-05 02:47
Maybe there needs to be another less drastic way to redraw the statusline. Ref #19472

**Comment by msva** [comment] 2023-01-16 21:43
Hi there!
I'd like to highlight this issue (and #17937 too, by the way), as it makes NVim usage behaviour very annoying when using timers with low timeouts.

Also, this happens when using plugins like https://github.com/folke/noice.nvim or similar.
Well, even `nvim-notify` makes nvim eat significant amount of CPU time because of (or, at least, it looks very like this) this issues :cry:.

Unfortunately, my C-foo is not enough to handle such issues, so I can't make a PRs with fixes :cry: 

Although, I have feeling, that there is commits with "fixes" for lualine (unfortunately, I can't provide links on related PRs atm, but at least #19472 and links from it looks related) is in charge of current behaviour.

**Comment by luukvbaal** [comment] 2023-03-06 03:03
Another (naive) fix @zeertzjq: https://github.com/neovim/neovim/pull/22547

**Closed** 2023-03-09 10:06 UTC
Labels: bug, performance, event-loop
