### ISSUE TITLE
Screen corruption in diff mode

### ISSUE THREAD

**Issue by kevinoid** [neovim/neovim#16415] opened 2021-11-23 15:39 UTC
### Neovim version (nvim -v)

0.5.1 (also tested 0.5.0, 0.4.4, 0.3.2)

### Vim (not Nvim) behaves the same?

no, vim 8.2.3565

### Operating system/version

Debian bookworm/sid with Linux 5.15

### Terminal name/version

xfce4-terminal 0.8.10 or foot 1.6.4

### $TERM environment variable

xterm-256color or xterm

### Installation

Debian package or nvim-linux64.tar.gz from releases

### How to reproduce the issue

```sh
nvim --clean -d <(seq 1 200) <(seq 1 2 200)
```
Once opened, press <kbd>PageDown</kbd> (or <kbd>Ctrl</kbd>-<kbd>F</kbd>) to scroll down a page.

### Expected behavior

<img src="https://user-images.githubusercontent.com/336433/143054608-d3ead952-53f0-450e-a593-b94aecfb6e59.png" alt="nvim screenshot of valid/legible diff mode" width="800" height="427">

### Actual behavior

<img src="https://user-images.githubusercontent.com/336433/143054742-2204c9fe-a9ed-4ae0-a887-fd5aae7e6228.png" alt="nvim screenshot of valid/legible diff mode" width="800" height="427">

**Comment by kevinoid** [comment] 2021-11-23 15:42
This is a weird issue.  The reproduction is completely reliable, and I'm able to reproduce it with every version and environment I've tested (different terminals, different `$TERM`, Wayland/X11, older kernels).  Yet, I'm reasonably sure it started occurring recently, since it's severe enough that I think I would have noticed it before.  Any suggestions for how to troubleshoot further would be appreciated.

**Comment by kevinoid** [comment] 2021-11-23 15:44
Also, to clarify, the "Actual Behavior" screenshot is how the terminal appears immediately after pressing <kbd>PageDown</kbd>.  If I resize the window, it redraws like the "Expected Behavior" screenshot.

**Comment by zeertzjq** [comment] 2021-11-23 15:51
What's you ncurses version?

**Comment by kevinoid** [comment] 2021-11-23 15:53
@zeertzjq Good question!  I didn't realize neovim used ncurses.  Looks like I recently upgraded from 6.2+20201114-4 to 6.3-1.  I'll try downgrading and let you know.

**Comment by zeertzjq** [comment] 2021-11-23 15:54
Most likely a duplicate of #16238

**Closed by zeertzjq** 2021-11-23 15:54 UTC
Labels: bug, environment, tui

**Comment by kevinoid** [comment] 2021-11-23 16:10
Bingo!  Downgrading to 6.2 fixes the issue.  I agree.  Looks like a dup of #16238.  Sorry for the noise.  Thanks for the help @zeertzjq!
