### ISSUE TITLE
Keymap being ignored

### ISSUE THREAD

**Issue by miversen33** [neovim/neovim#18166] opened 2022-04-19 01:47 UTC
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

no 8.1.2018

### Operating system/version

Ubuntu 20.04/WSL (Ubuntu 20.04)

### Terminal name/version

Konsole/Microsoft Terminal

### $TERM environment variable

xterm-256color

### Installation

appimage (as well as dpkg)

### How to reproduce the issue

nvim --clean
:lua vim.api.nvim_set_keymap('n', '<C-i>', ':<C-w><C-k>', {})
:split

### Expected behavior

Using the above keymap, pressing Control + I should move you to the buffer above you, however it does not. Executing the shortcut <C-w><C-k> still moves you to the above buffer however.

### Actual behavior

Pressing `<C-i>` fails to do anything. I am not able to get this keymap to apply even using more traditional vim mapping
`:nmap <C-i> <C-w><C-k> noremap` from a buffer. 

I dont know what else I can provide here and I dont know how big this goes (I would be willing to accept I am doing it wrong, though I _haven't_ changed my keymapping in quite some time)

**Comment by miversen33** [comment] 2022-04-19 01:48
Probably worth calling out that this works on versions prior to the update to Neovim 0.7.0

**Comment by gpanders** [comment] 2022-04-19 01:52
Your reproduction text shows

```
:lua vim.api.nvim_set_keymap('n', '', ':', {})
```

I assume something got filtered out. Be sure to use backticks to escape any `<` characters, or GitHub will interpret them as (invalid) HTML.

**Comment by zeertzjq** [comment] 2022-04-19 01:53
Duplicate of #17867

**Closed by zeertzjq** 2022-04-19 01:53 UTC
Labels: bug
