### ISSUE TITLE
`set hlsearch` inside function doesn't highlight search

### ISSUE THREAD

**Issue by hauleth** [neovim/neovim#7409] opened 2017-10-18 16:06 UTC
- `nvim --version`:
```
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Skompilowany przez brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

       vimrc systemu: "$VIM/sysinit.vim"
   odwet dla $VIM-a: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"
```
- Vim (version: ) behaves differently? No, this bug is also present in Vim
- Operating system/version: macOS Sierra 10.12.6 (16G1031)
- Terminal name/version: iTerm2 Build 3.1.beta.5
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

Define function:

```
function! Highlight()
  let @/ = 'word'
  set hlsearch
endfunction
```

Have buffer with content:

```
word
```

Call `call Highlight()`

### Actual behaviour

`word` is not highlighted

### Expected behaviour

`word` to be highlighted

## Other

According to [Vim SE question](https://vi.stackexchange.com/q/8207/1259) it seems that in Vim setting `set compatible` makes it works, but in NeoVim this is hard error. It also seems that with

```
function! Highlight()
  let @/ = 'word'
  set hlsearch
  redraw
endfunction
```

It highlights becomes unpredictable. It seems to highlight only n+1 occurrence in text (at least when used in [sad.vim](https://github.com/hauleth/sad.vim)).

**Comment by jamessan** [comment] 2017-10-18 16:32
Contrary to `:help function-search-undo` and `:help @/`, the first definition of `Highlight()` does exactly what you want it to do, for me, in both vim (8.0.1144) and nvim (0.2.0).

**Comment by hauleth** [comment] 2017-10-18 16:57
`:help function-search-undo` tells only about `:hlsearch` not about `:set hlsearch`and these two are different from each other.

There is ASCIIcast that demonstrates the problem https://asciinema.org/a/cySU3m3WJcdjzMajJxMtYkA63

**Comment by jamessan** [comment] 2017-10-18 17:02
> these two are different from each other.

I know that.  See also `:help v:hlsearch`.

Here's my [ASCIIcast](https://asciinema.org/a/VVQcjh61wo12RPwMBujid0Jvu) showing it working.

**Comment by hauleth** [comment] 2017-10-18 17:09
@jamessan setting `set nohls` fixes the problem. When you use `:nohl` then it reappears https://asciinema.org/a/CMPHL6vYY41UIdLufCHwf7g5q

**Comment by jamessan** [comment] 2017-10-18 17:22
Ok, so the problem is nothing to do with setting `'hlsearch'`.  The problem is that you can't effect whether `v:hlsearch` is "true" inside the function, which is exactly what's described at `:help v:hlsearch`.

The typical way to work around this would be to have an `<expr>` mapping that causes `let v:hlsearch=1` to be directly called, instead of called inside a function.

```vim
function! Highlight()
    let @/ = 'word'
    set hlsearch
    return ":let v:hlsearch = v:true\<CR>"
endfunction

nnoremap <expr> <silent> <C-g> Highlight()
```

**Comment by hauleth** [comment] 2017-10-18 17:24
The temp fix can be by using:

```
:let v:hlsearch=1 | call Highlight()
```

However the problem is that I am using my function as `opfunc` and this causes ugly flash that show previous highlight.

**Comment by jamessan** [comment] 2017-10-18 17:33
> the problem is that I am using my function as opfunc and this causes ugly flash that show previous highlight.

Then `'hlsearch'` may not be the right tool for the job.  I wouldn't expect an opfunc to be blindly enabling `'hlsearch'` for me, especially if it's something I've intentionally disabled.

I'm not sure about the Vim side of things, but for nvim you may find `nvim_buf_{add,clear}_highlight` to be more useful.

Since this is documented behavior, I'm going to close the issue.

**Closed by jamessan** 2017-10-18 17:33 UTC

**Comment by justinmk** [comment] 2017-10-18 17:48
There's actually an existing issue for this.
