### ISSUE TITLE
Event on new mapping (autocmd)

### ISSUE THREAD

**Issue by eyalk5** [neovim/neovim#11274] opened 2019-10-22 21:24 UTC
Hi,

It would be useful to have an (autocmd) event that is triggered when a key sequence is mapped. 
A user function would allow it or reject it. 

I, for instance, don't want any plugin to map any sequence that begins with `\c`. But I know several plugins do this, not necessarily at a predictable time. Sometimes it is hard to control all the mapping of all the plugins. 

Another option would be an option to protect a mapping, such that a longer mapping couldn't be mapped. Or that it couldn't be replaced(a different thing).

Thanks

**Comment by justinmk** [comment] 2019-10-23 03:39
Duplicate of https://github.com/neovim/neovim/issues/11116 .

However, this particular use-case is not a strong motivation:

> don't want any plugin to map any sequence that begins with `\c`. But I know several plugins do this,

Users should very much file bug-reports on such plugins. The Vim ecosystem is made better when people insist on well-behaved plugins.  Fighting  plugins via config-tricks will make everything more complicated: for plugin-authors, users, and troubleshooting.

**Closed by justinmk** 2019-10-23 03:39 UTC
Labels: enhancement
