### ISSUE TITLE
gopls panics on 0.6.0

### ISSUE THREAD

**Issue by djdv** [neovim/neovim#15799] opened 2021-09-26 19:17 UTC
### Neovim version (nvim -v)

0.6.0-dev+344-gb3b02eb52

### Language server name/version

gopls ba6b94c735d2f7b74804e255e653a4292074ae76

### Operating system/version

Windows 11 (22463.1000)

### :checkhealth

```markdown
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: ? (not found)
  - INFO: key_dc (kdch1) terminfo entry: ? (not found)

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: gopls: configuration checked.
```

### Steps to reproduce using "nvim -u minimal_init.lua"

- Be on a Windows system using nvim 0.6.0+
- Setup `gopls` via `nvim_lsp.gopls.setup{}` with or without any custom setup options.
- Open a go project which causes nvim to start `gopls`
- Try to communicate with the LSP using something like `gd` to go to a definition

### Expected behavior

nvim goes to the definition, gopls does not panic.
This is the case in the release version of 0.5.0.

### Actual behavior

gopls panics, nvim isn't happy about it.
This is the case in the current commit for 0.6.0

Notice 0.5.0 is requesting `file:///C:/tmp/nvim-issue/main.go`
while 0.6.0 is requesting `C:\\\\tmp\\\\nvim-issue\\\\main.go`

Either the path delimiters are causing an issue, or more likely the omission of the `file:///` protocol prefix. Not sure.

### Log file

https://gist.github.com/djdv/cc76b8f9576021ab36d3fa8d92d3ac39

**Comment by mjlbach** [comment] 2021-09-26 19:29
Duplicate of #15261

**Closed by mjlbach** 2021-09-26 19:29 UTC
Labels: bug, lsp
