### ISSUE TITLE
Lag is noticeable within comment while the treesitter highlight is enabled.

### ISSUE THREAD

**Issue by towry** [neovim/neovim#25113] opened 2023-09-12 09:21 UTC
### Problem

This issue is a bit hard to reproduce without following exactly steps.

When typing `/**` comment in vue files, the input lag is noticeable.

### Steps to reproduce

put `slow-ts.lua` in `/tmp`:

```lua
vim.g.mapleader = " "
vim.g.maplocalleader = ","
vim.opt.number = true

for name, url in pairs({
	-- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
	-- some_plugin = 'https://github.com/author/plugin.nvim'
	treesitter = "https://github.com/nvim-treesitter/nvim-treesitter",
}) do
	local install_path = vim.fn.fnamemodify("slow_ts/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		if name == "treesitter" then
			vim.fn.system({ "git", "clone", "--branch", "main", "--depth=1", url, install_path })
		else
			vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
		end
	end
	vim.opt.runtimepath:append(install_path)
end

-- ===============

require("nvim-treesitter").setup({
	ensure_install = { "vue", "javascript", "typescript", "comment", "jsdoc" },
	auto_install = false,
	install_dir = vim.fn.fnamemodify("slow_ts/.site", ":p"),
})

local ftau = vim.api.nvim_create_augroup("option_ft", { clear = true })
vim.api.nvim_create_autocmd("FileType", {
	group = ftau,
	pattern = { "*" },
	callback = function(args)
		local buf = args.buf
		-- start highlighter.
		if not pcall(vim.treesitter.start, buf) then
			print("ERROR! highlight not started")
			return
		end
	end,
})

vim.cmd("colorscheme default")
```

Put a `test.vue` file along side with `slow-ts.lua`:

file content: https://gist.github.com/towry/74d6ff3312e18c6fd39367d1b4e477cf#file-test-vue

Steps to repro it:

1. `nvim --clean -u slow-ts.lua`, wait for the nvim-treesitter setup is done.
2. make sure `vue`, `comment` parsers is installed.
3. `nvim --clean -u slow-ts.lua test.vue`
4. (important) press `ctrl-d` multiple times to move cursor down and press `ctrl-u` to make sure line 26 is visible and move cursor to line 26 with `j/k`.
5. start insert comment with content `/***` above line 26.

Note: it seems if I press `:26` to directly move cursor to line 26, this bug will not be triggered.

A lag demo can be seen here: https://github.com/neovim/neovim/issues/25074#issuecomment-1713502035

### Expected behavior

No lag in comment.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1088+g6b5f44817

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos

### Terminal name/version

kitty + macos terminal

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by llllvvuu** [comment] 2023-09-12 09:21
Better way to get to line 26: `26ggzt`. C-d is a bit annoying since dependent on screen size.

`init.lua` can be shorted and still reproduces:
```lua
local install_path = vim.fn.fnamemodify("slow_ts/treesitter", ":p")
local url = "https://github.com/nvim-treesitter/nvim-treesitter"
vim.fn.system({ "git", "clone", "--branch", "main", "--depth=1", url, install_path })
if vim.fn.isdirectory(install_path) == 0 then
  vim.opt.runtimepath:append(install_path)
end

require("nvim-treesitter").setup({
  ensure_install = { "vue", "javascript", "typescript", "comment", "jsdoc" },
  auto_install = false,
  install_dir = vim.fn.fnamemodify("slow_ts/.site", ":p"),
})

-- ^ not core to repro; only for installing parsers --

vim.api.nvim_create_autocmd("FileType", {
  pattern = { "*" },
  callback = function() vim.treesitter.start() end,
})
```

**Comment by llllvvuu** [comment] 2023-09-12 09:25
BTW from a cursory look, the symptoms see the same as in #25088, just without needing `nvim-treesitter`'s indent to trigger. I'll add the print statements to make sure.

**Comment by lewis6991** [comment] 2023-09-12 09:27
I'm pretty sure this is because there is a nested injection that occupies most of the buffer. Every edit will destroy and recreate the tree without any incremental parsing.

**Comment by clason** [comment] 2023-09-12 10:33
Thousands of comment injections is a well-known pain point (that incremental injections were meant to solve -- and have solved for the vast majority of reported cases).

In the meantime, I consider "don't install the comment parser" a reasonable workaround, as its value is vanishingly small, compared to the headaches it creates.

**Comment by llllvvuu** [comment] 2023-09-12 10:39
Then we can probably close this and file it under https://github.com/nvim-treesitter/nvim-treesitter/issues/5057.

Although one thing I wonder about is why `on_line_impl` iterates to the `root_end_row` and not the window end row.

**Comment by clason** [comment] 2023-09-12 10:41
Just because the comment parser is a bad idea doesn't mean that there aren't performance issues worth fixing.

**Comment by lewis6991** [comment] 2023-09-12 10:42
> Although one thing I wonder about is why highlighter's on_line_impl iterates to the root_end_row and not the window end row.

It doesn't iterate the `root_end_row`, it creates an iterator that goes down to `root_end_row`. If a match exceeds line, then `on_line_imp` returns.

**Comment by lewis6991** [comment] 2023-09-12 10:56
> For one reason or another, iter() is getting called on matches on line 170 when I'm on line 26 and my viewport only goes up to line 74. Not that it's a huge deal, as it's only a 3x factor difference

From how I understand it works, `on_line_impl` will process up-to one match that after `line`, but will then return:

```lua
    while line >= state.next_row do
      ...
      if hl and end_row >= line and (not is_spell_nav or spell ~= nil) then
        ...
        api.nvim_buf_set_extmark(buf, ns, start_row, start_col, {
          end_line = end_row,
          end_col = end_col,
          ...
        })
      end
      if start_row > line then
        state.next_row = start_row
      end
    end

```

**Comment by llllvvuu** [comment] 2023-09-12 11:02
Right, got it, it won't help because the issue isn't the matches but the number of non-matches that are captured.

Actually I wonder if this is really held back by the comment parser being a "bad idea". I believe it for some files, but on this particular file, only the comment *query* seems to be a bad idea, in its current state. And I feel like the query could be improved? It looks like someone had luck removing some captures: https://github.com/nvim-treesitter/nvim-treesitter/issues/5057#issuecomment-1617833491

**Comment by clason** [comment] 2023-09-12 11:05
This is beside the point, though. The first order of business is to find out _what_ is slow here. If it's the languagetree/highlighter, that needs to be improved. If it's (just) the comment parser/queries, we're done here, and improvements need to be made elsewhere. 

> The kind of annoying thing is that I can't seem to get an :InspectTree up for comment filetype, so I can't improve it further

There _is_ no "comment" filetype. You can make `:InspectTree` show the injected nodes by pressing `I`, though.

**Comment by llllvvuu** [comment] 2023-09-12 11:15
> The first order of business is to find out what is slow here.

We figured it out earlier, it's `iter_captures` because there are too many captures. There are a few defensive programming options from the Neovim side:
* caching the HighlighterQuery result - this could speed things up if you're editing outside of the big comment block
* an config option to limit the number of captures processed

But unless there are more clever things `iter_captures` can do, I'm inclined to think that

> we're done here, and improvements need to be made elsewhere.

applies here, and "elsewhere" is specifically this file: https://github.com/nvim-treesitter/nvim-treesitter/blob/0ba881b7a2af0e24962e4522cf15ebd642261a90/queries/comment/highlights.scm. There's only so much Neovim can do if it receives a black box of 4000 captures which might be legitimate fresh matches.

**Comment by lewis6991** [comment] 2023-09-12 11:29
`(_) @spell` looks like something that could produce a lot of captures.

**Comment by tomtomjhj** [comment] 2023-09-12 14:42
> `(_) @spell`

This query doesn't seem to be necessary, because the parent language usually have something like `(comment) @comment @spell` already

**Comment by llllvvuu** [comment] 2023-09-12 19:16
> `(_) @spell`

Turns out this wasn't the only chatty query. Each of the following return 801 matches, for a total of 4005 matches.

```scm
("text" @text.todo @nospell
 (#any-of? @text.todo "TODO" "WIP"))

("text" @text.note @nospell
 (#any-of? @text.note "NOTE" "XXX" "INFO" "DOCS" "PERF" "TEST"))

("text" @text.warning @nospell
 (#any-of? @text.warning "HACK" "WARNING" "WARN" "FIX"))

("text" @number
 (#lua-match? @number "^#[0-9]+$"))
```

Possibly a precedence issue? The `#any-of` / `#lua-match` aren't filtering the captures

> You can make :InspectTree show the injected nodes (rather, their language) by pressing I, though.

Thanks for the tip. In this case, `style_element > raw_text` is expanded, so I can see the injected `scss` nodes, but `script_element > raw_text` is unexpanded, there is no `javascript` subtree. Maybe `:InspectTree` has its own `LanguageTree` that is more lazy than the highlighter?

**Comment by llllvvuu** [comment] 2023-09-12 19:41
> Note — Predicates are not handled directly by the Tree-sitter C library.

Ah this is indeed exactly what's happening:

https://github.com/neovim/neovim/blob/1f551e068f728ff38bd7fdcfa3a6daf362bab9da/runtime/lua/vim/treesitter/query.lua#L608

Predicates are happening on the Lua side, so even though there are no e.g. TODO comments, every word is checked on the Lua side for whether it is e.g. "TODO". 

Would it be faster if it were in C?

**Comment by lewis6991** [comment] 2023-09-12 19:44
> Would it be faster if it were in C

Most definitely but also quite non-trivial.

**Comment by clason** [comment] 2023-09-12 19:47
Not only not trivial, but also not desired -- predicates and directives are meant to be user customizable.

**Comment by lewis6991** [comment] 2023-09-12 19:57
> predicates and directives are meant to be user customizable.

I thought user-definable, not customizable?

I don't see why we couldn't implement some of the predicates directly in C.

**Comment by lewis6991** [comment] 2023-09-12 19:59
Either, we can avoid the need to do this by fixing (or killing) the comment parser. A lot of these queries should be parsed directly in the parser.

**Comment by llllvvuu** [comment] 2023-09-12 20:16
> I thought user-definable, not customizable?

There is some commentary (which I don't fully grok) under the `match_preds` implementation that suggests that maybe users want to hook into the implementation details?

https://github.com/neovim/neovim/blob/1f551e068f728ff38bd7fdcfa3a6daf362bab9da/runtime/lua/vim/treesitter/query.lua#L612-L615

> A lot of these queries should be parsed directly.

A non-TS comment highlighter might still need to be filtered by the TS language tree but would definitely be more efficient if can just check the changed text (it's not really a parser just an equality check)

> Either, we can avoid the need to do this by fixing (or killing) the comment parser.

Do we think the comment query will be the last time a query wants to evaluate predicates on a large number of nodes?

**Comment by llllvvuu** [comment] 2023-09-12 20:26
> Not only not trivial, but also not desired -- predicates and directives are meant to be user customizable.

I'm sure `_rawquery` could take a flag to optionally pre-filter matches, so that the user can take the faster pre-filter, or do custom filtering themselves

That being said, point understood re: doing it in C not being the answer right now.

**Comment by lewis6991** [comment] 2023-09-12 20:41
> Do we think the comment query will be the last time a query wants to evaluate predicates on a large number of nodes?

The comment parser is usually the reason for a lot of issues.

The issue here with the comment parser is that the queries are just too general, almost pointlessly so. What is the parser even parsing?

**Comment by llllvvuu** [comment] 2023-09-12 21:03
> The issue here with the comment parser is that the queries are just too general, almost pointlessly so. What is the parser even parsing?

The answer is nothing: https://github.com/stsewd/tree-sitter-comment/blob/master/src/grammar.json . It's just a glorified string split + one paren match. It could be replaced by `/(todo|fixme)\(([^()]*)\)/`

I suspect it's only there just because it's a convenient API. It should probably be deprecated from nvim-treesitter, regardless of async parsing.

The question is, does the alternative need a new API? Just to configure what goes into the `(todo|fixme)` part?

**Comment by clason** [comment] 2023-09-12 21:06
To be perfectly fair, nobody is forcing you to install it. And I've been _very_ vocal about just installing every parser under the sun getting you what you deserve.

**Comment by llllvvuu** [comment] 2023-09-12 21:15
> A lot of these queries should be parsed directly.

I think you could probably just do

```lua
edit_range = -- from some callback
for_each_tree(function(ts_tree, lang_tree)
  if tree:lang() == 'comment'
    -- update extmarks in overlap(edit_range, ts_tree) using user-configured/plugin-configured regex
  end
end)
```

I could try making a plugin for it although I'm very unfamiliar with the relevant APIs.

**Comment by clason** [comment] 2023-09-12 21:16
No. We will not add workarounds for ill-behaved parsers.

**Comment by llllvvuu** [comment] 2023-09-12 21:28
That's not what I'm saying - I'm agreeing that the parser shouldn't be installed and pointing out that highlighting can be solved in userspace (plugins). Anyway, I think this issue can be closed.

> I've been very vocal

Not key to this issue, but probably the signposting could be more than just GitHub issue comments. Some of the items in the README say "experimental, ", could we not put "slow, " next to this one?

**Closed** 2023-09-16 12:52 UTC
Labels: performance, treesitter
