### ISSUE TITLE
Neovim terminal emulation appears to be much more sluggish than vim

### ISSUE THREAD

**Issue by unphased** [neovim/neovim#20408] opened 2022-09-30 06:41 UTC
### Neovim version (nvim -v)

v0.8.0-dev+399-g58323b1fe

### Vim (not Nvim) behaves the same?

no, vim 8.2 patches 1-3227

### Operating system/version

Ubuntu 20.04

### Terminal name/version

alacritty. reproduces in other terminals also

### $TERM environment variable

xterm-256color

### Installation

from github releases

### How to reproduce the issue

Open a terminal on a very large screen and set the font to be reasonably small. Or on a small screen, set the font to be really really small. 

activate the fzf plugin: https://github.com/junegunn/fzf.vim 

It runs fzf inside of terminal inside vim. 

This is sluggish when the window is sufficiently big in nvim. It is not reproduceable in vim. This indicates that nvim has some inefficiency redrawing the terminal. 

### Expected behavior

not be slower than vim

### Actual behavior

sluggish terminal behavior but only apparent on large screens. this is not just a ridiculous thing, it actually is slow and chews up extra CPU when I maximize the terminal on my ultrawide monitor.

**Comment by justinmk** [comment] 2022-09-30 09:17
duplicate of https://github.com/neovim/neovim/issues/11090

**Closed by justinmk** 2022-09-30 09:17 UTC
Labels: bug, performance, terminal
