### ISSUE TITLE
:tag fails to find tag since Nvim 0.8

### ISSUE THREAD

**Issue by narcisse82** [neovim/neovim#24255] opened 2023-07-04 16:18 UTC
### Problem

With the revision 0.7.2, I had no issue when executing this command : 
:tag btauif

With the revision 0.9.1, nvim tells me that the btauif tag does not exist when executing the same command

Please find attached the .tags file which is used in my project...

I can provide you with the .tags file so that you can check the issue in your side...

### Steps to reproduce

:tag btauif

### Expected behavior

nvim should find the tag as it is present in the .tags file, and it works perfectly with the nvim version 0.7.2

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release

### Vim (not Nvim) behaves the same?

Not checked

### Operating system/version

CentOs 7.0

### Terminal name/version

NA

### $TERM environment variable

screen-256color

### Installation

appimage

**Comment by narcisse82** [comment] 2023-07-05 06:51
[tags_file_issue_24255.zip](https://github.com/neovim/neovim/files/11954712/tags_file_issue_24255.zip)

**Comment by narcisse82** [comment] 2023-07-05 06:52
In the .vimrc, I've got this setting:
set tags=~/.tags

**Comment by justinmk** [comment] 2023-07-05 07:55
can you bisect? building Nvim is very easy: https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites

**Comment by narcisse82** [comment] 2023-07-05 09:37
Hi 

I'm trying to compile nvim from sratch with : 
- git clone https://github.com/neovim/neovim
- cd neovim
- make CMAKE_BUILD_TYPE=RelWithDebInfo
Unfortunately, the compilation has issues with some dependencies (tar files to be downloaded, and that can't be found)
1:LIBUV_URL https://github.com/libuv/libuv/archive/v1.46.0.tar.gz
7:LUAJIT_URL https://github.com/LuaJIT/LuaJIT/archive/51fb2f2c3af778f03258fccee9092401ee4a0215.tar.gz
13:UNIBILIUM_URL https://github.com/neovim/unibilium/archive/d72c3598e7ac5d1ebf86ee268b8b4ed95c0fa628.tar.gz
22:LUV_URL https://github.com/luvit/luv/archive/1.45.0-0.tar.gz
28:LUA_COMPAT53_URL https://github.com/keplerproject/lua-compat-5.3/archive/v0.9.tar.gz
47:TREESITTER_C_URL https://github.com/tree-sitter/tree-sitter-c/archive/v0.20.2.tar.gz
49:TREESITTER_LUA_URL https://github.com/MunifTanjim/tree-sitter-lua/archive/v0.0.18.tar.gz
51:TREESITTER_VIM_URL https://github.com/neovim/tree-sitter-vim/archive/v0.3.0.tar.gz
53:TREESITTER_VIMDOC_URL https://github.com/neovim/tree-sitter-vimdoc/archive/v2.0.1.tar.gz
55:TREESITTER_QUERY_URL https://github.com/nvim-treesitter/tree-sitter-query/archive/v0.1.0.tar.gz
57:TREESITTER_PYTHON_URL https://github.com/tree-sitter/tree-sitter-python/archive/36f9e33d52b7572536ac1a8af8d7e78363ad52c3.tar.gz
59:TREESITTER_BASH_URL https://github.com/tree-sitter/tree-sitter-bash/archive/493646764e7ad61ce63ce3b8c59ebeb37f71b841.tar.gz
61:TREESITTER_MARKDOWN_URL https://github.com/MDeiml/tree-sitter-markdown/archive/936cc84289f6de83c263ae8e659fb342867ceb16.tar.gz
63:TREESITTER_URL https://github.com/tree-sitter/tree-sitter/archive/91e4d940169a0c0b024560632ef53c4f119117ca.tar.gz

Any idea ?

**Comment by justinmk** [comment] 2023-07-05 10:09
>  make CMAKE_BUILD_TYPE=RelWithDebInfo

just `make` will be faster (defaults to "debug" build type)

**Comment by narcisse82** [comment] 2023-07-05 10:17
Hi 
I've just test the stable releases (nvimapp images):
- 0.7.0 : OK
- 0.7.2 : OK
- 0.8.0 : can not execute on my CentOs 7.0 machine
./nvim.0.8.0/bin/nvim: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./nvim.0.8.0/bin/nvim)
./nvim.0.8.0/bin/nvim: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./nvim.0.8.0/bin/nvim)
- 0.8.1 : Fail
- After 0.8.1 : Fail

**Comment by justinmk** [comment] 2023-07-05 10:21
Please check with `vim` (as recent as possible). Don't want to spend time on this if it's a vim bug.

**Comment by zeertzjq** [comment] 2023-07-05 10:27
Vim patches that touch tag.c merged between v0.7.0 and v0.8.0 only contain cosmetic changes, so it is unlikely to come from Vim.

**Comment by narcisse82** [comment] 2023-07-05 11:39
I've compiled vim from sources and tried it. It is ok with vim

**Comment by mfussenegger** [comment] 2023-07-05 17:06
Also keep in mind that lsp sets tagfunc automatically, so it might not use the tags file. Minimal reproduction steps would help rule out stuff like that

**Comment by justinmk** [comment] 2023-07-05 17:40
Definitely. Did you repro it with `nvim --clean` ?

**Comment by narcisse82** [comment] 2023-07-05 20:16
Using nvim --clean makes no difference

**Comment by zeertzjq** [comment] 2023-07-06 21:51
Is it still not possible to bisect?

**Comment by narcisse82** [comment] 2023-07-07 06:56
Hi

What do you mean by "bisect" ? Is it a request for me or for Justin ?

**Comment by zeertzjq** [comment] 2023-07-07 07:01
See `git bisect --help`

**Comment by justinmk** [comment] 2023-07-07 19:28
@narcisse82 I am asking you to build nvim and find the commit that caused the issue, because this is a very specific issue to your tags file. No one else can do it for you.

**Comment by narcisse82** [comment] 2023-07-26 14:20
Hi Justin,

I've compiled nvim at different tags on my personal laptop, but I can't manage to reproduce the issue I have on my professional laptop.
For the time being, I can not investigate further.
I propose that you close this ticket...

Best regards,
Stephane

**Closed** 2023-08-26 01:45 UTC
Labels: needs:response, needs:repro, bug-regression
