### ISSUE TITLE
Error in python support.

### ISSUE THREAD

**Issue by Yggdroot** [neovim/neovim#6499] opened 2017-04-11 03:14 UTC
- `nvim --version`: latest
- Vim (version: ) behaves differently? yes
- Operating system/version: all
- Terminal name/version:
- `$TERM`:

### Actual behaviour
```python
py b = vim.current.buffer
py print b is vim.current.buffer
```
The result is: **False**

### Expected behaviour
The result is: **True**

Vim gives the correct result: **True**.
The result is also inconsistent with python syntax.

**Comment by justinmk** [comment] 2017-04-11 08:28
What about vim before bindeval was introduced?

**Comment by ZyX-I** [comment] 2017-04-11 08:32
Same on vim-7.0.112. Earlier versions do not have normally working Python support.

**Comment by ZyX-I** [comment] 2017-04-11 08:36
@Yggdroot I do not see how the result is inconsitent, especially inconsistent with *syntax*. You are checking whether objects are identical; in Vim vim.Buffer object is cached in buf_T structure, Neovim constantly creates new temporary objects, everything is consistent. The situation when `@property` implementation function returns always different objects is not unique, proper way to check such things is `==` and not `is`.

**Comment by bfredl** [comment] 2017-04-11 09:03
Closed as not a bug, `==` should be used for equality

**Closed by bfredl** 2017-04-11 09:03 UTC
