### ISSUE TITLE
LSP/Scala: buffer string included in completion list

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/neovim#11744] opened 2020-01-21 12:37 UTC
- `nvim --version`: NVIM v0.5.0-316-g8fe0635e7
- Operating system/version: Mac / 10.15.2
- Terminal name/version: iTerm / 3.3.7
- `$TERM`: screen-256color

### Plugins and settings
```toml
[[plugins]]
repo = 'neovim/nvim-lsp'
hook_add = '''
    command! Scratch lua require'lsp'.makeScratch()
'''
```

`.config/nvim/lua/lsp.lua`
```lua
local M = {}

function M.makeScratch()
    local nvim_lsp = require'nvim_lsp'
    local configs = require'nvim_lsp/skeleton'

    -- Scala
    if not nvim_lsp.scala_lsp then
        configs.scala_lsp = {
            default_config = {
                cmd = {'metals-vim'};
                filetypes = {'scala', 'sbt'};
                root_dir = nvim_lsp.util.root_pattern('build.sbt');
        };
      }
    end

    nvim_lsp.scala_lsp.setup{}
end

return M
```

`.sbt/1.0/plugins/plugins.sbt`
```scala
resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.3.4")
```

## How to reproduce the problem from neovim startup

1. `$ sbt new nabezokodaikon/scala-basic.g8`
2. `name [My Something Project]: = issue-scala`
3. `$ cd issue-scala`
4. `$ nvim`
5. `e: src/main/scala/com/github/nabezokodaikon/Main.scala`
6. Type appropriately

### Actual behaviour
A character string that is not related to completion will be entered in Scala.
<img width="265" alt="スクリーンショット 2020-01-18 16 28 43" src="https://user-images.githubusercontent.com/3197942/72662638-bea9ea00-3a2c-11ea-9bbd-290e10a1846a.png">

### Expected behaviour
I want to remove unnecessary string completion in Scala.

**Comment by nabezokodaikon** [comment] 2020-01-21 12:38
So that's it. It may be a problem of metals. However, VSCODE did not have this problem.

**Comment by justinmk** [comment] 2020-01-22 07:52
Thanks for the repro steps. The contents of `Main.scala` might be needed?

I don't use scala. If someone wants to look into this, perhaps it's related to the choice of cursor position / offset  that is sent to the server?

**Comment by nabezokodaikon** [comment] 2020-01-22 13:17
The minimal code to reproduce is:
```scala
package com.github.nabezokodaikon

object Main {

  def main(array: Array[String]): Unit = {
    val a: Int = 0 // Correct code
    val b: Int scala // Incorrect code
  }

}

```

The completion is displayed as follows.
<img width="707" alt="スクリーンショット 2020-01-22 22 14 36" src="https://user-images.githubusercontent.com/3197942/72897258-e36fcb80-3d64-11ea-98cd-3180d5cc7e3e.png">

**Comment by justinmk** [comment] 2020-01-22 21:13
Just to be clear,  you expect the same results, minus that single highlighted item?

The results are coming from the language server as indicated by `[LC]`. This might be a question of sending the right options/parameters to the language server, i.e. it's a question of configuration and should be sent as a PR to https://github.com/neovim/nvim-lsp

**Comment by nabezokodaikon** [comment] 2020-01-23 14:29
Sorry. I made a mistake in the screenshot.
In fact, if you do `c-x` and` c-o`, you will see the `E764: Option 'omnifunc' not set`.

**Comment by nabezokodaikon** [comment] 2020-01-23 15:10
If you look closely, the type of module is also wrong.
All displayed completions must be `Class`.

**Comment by justinmk** [comment] 2020-01-26 02:06
Can someone analyze https://github.com/prabirshrestha/vim-lsp/pull/688 and see if it makes sense to do something like that in Nvim `vim.lsp` module?

**Comment by nabezokodaikon** [comment] 2020-01-26 10:50
Hmm. At least not for me.

**Comment by ckipp01** [comment] 2020-03-21 18:47
I'm not extremely familiar with the LSP implementation of nvim, but it looks like you're grabbing the label of the completion rather than the `newText`. For example take the following image I tried to reproduce what you're experiencing.

<img width="816" alt="Screenshot 2020-03-21 at 19 43 37" src="https://user-images.githubusercontent.com/13974112/77234145-7df55b00-6bac-11ea-8aed-06bd30472094.png">

In this scenario you see that the first option `toCharArray(): Array[Char]` is the label, which is being inserted. Here is the actual completion item:

```json
    {
      "label": "toCharArray(): Array[Char]",
      "kind": 8,
      "detail": "(): Array[Char]",
      "preselect": true,
      "sortText": "00000",
      "filterText": "toCharArray",
      "insertTextFormat": 1,
      "textEdit": {
        "range": {
          "start": {
            "line": 7,
            "character": 7
          },
          "end": {
            "line": 7,
            "character": 9
          }
        },
        "newText": "toCharArray()"
      },
      "data": {
        "symbol": "java/lang/String#toCharArray().",
        "target": "file:/Users/ckipp/Documents/scala-workspace/test-project/example/?id\u003dexample"
      }
    },
```

I would expect the `newText` from the `textEdit` to be inserted.

**Comment by ckipp01** [comment] 2020-04-08 06:51
So I just looked at this a bit more. The problem seems to be here:

https://github.com/neovim/neovim/blob/5a5c2f0290b5cdb8ccc1a06cb41f248ab25fd792/runtime/lua/vim/lsp/util.lua#L196

Metals doesn't send `insertText`, but instead sends `textEdits` which is recommended in the spec.

```
* The `insertText` is subject to interpretation by the client side.
* Some tools might not take the string literally. For example
* VS Code when code complete is requested in this example `con<cursor position>`
* and a completion item with an `insertText` of `console` is provided it
* will only insert `sole`. Therefore it is recommended to use `textEdit` instead
* since it avoids additional client side interpretation.
```
I've never used lua before, but I may take a stab at fixing this. Is there a reason why `insertText` was chose here over `textEdit`?

**Comment by mfussenegger** [comment] 2020-04-09 16:52
I think this would be fixed with https://github.com/neovim/neovim/pull/11989

**Comment by ckipp01** [comment] 2020-04-09 18:23
Ah jeez, I didn't even see that. Thanks for pointing that out @mfussenegger!

**Comment by kvnflm** [comment] 2020-04-24 12:55
This indeed seems to have been fixed with https://github.com/neovim/neovim/pull/11989, Metals completion is working without any problems now

**Closed** 2020-04-26 17:04 UTC
Labels: +plan, complexity:non-trivial, help wanted, lsp
