### ISSUE TITLE
LSP: allow registering custom, client-side handlers per server

### ISSUE THREAD

**Issue by MagicDuck** [neovim/neovim#14258] opened 2021-03-30 22:43 UTC
### Version (using 0.5 nighttly)
```
NVIM v0.5.0-dev+1157-g0ab88c2ea
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1616045056542.local

Features: +acl +iconv +tui
```

### Background
Coming from Intellij Idea, I really liked the feature where the editor would offer you a code action to "suppress eslint rule X", by introducing a comment on the line above. Ex:
```js
    // eslint-disable-next-line no-param-reassign  <--- This line would be introduced by the code action to suppress no-param-reassign
    parentTriggerBlock.presentation = responseTriggerPresentation;
```

Switching to nvim + native LSP, there are offerings such as `diagnosticls` (https://github.com/iamcco/diagnostic-languageserver) to achieve linting/formatting, but it only supports capabilities such as `textDocument/formatting` & `textDocument/publishDiagnostics`.

#### First attempt (unsuccessful)
```lua
local handlers = require('stephan/lsp/handlers')

lspconfig.diagnosticls.setup {
...
  on_init = function(client)
    client.resolved_capabilities.document_formatting = true
    client.resolved_capabilities.code_action = true
    client.resolved_capabilities.execute_command = true
  end,
  handlers = {
    ["textDocument/codeAction"] = handlers.lintCodeAction
    ["workspace/executeCommand"] = handlers.workspaceExecuteCommand
  }
}
```
It looked like `client.request()` would be called to do the RPC, and have a successful return status, but `handlers.lintCodeAction` and `handlers.workspaceExecuteCommand` never got called :(.

#### Second attempt (successful)
```lua
local handlers = require('stephan/lsp/handlers')

lspconfig.diagnosticls.setup {
...
  on_init = function(client)
    client.resolved_capabilities.document_formatting = true
    client.resolved_capabilities.code_action = true
    client.resolved_capabilities.execute_command = true
    client.request = handlers.client_request(client);  -- hack time :)
  end,
  handlers = {
    ["textDocument/codeAction"] = {
      type = 'local_lsp',
      handler = handlers.lintCodeAction
    },
    ["workspace/executeCommand"] = {
      type = 'local_lsp',
      handler = handlers.workspaceExecuteCommand
    }
  }
}
```
where `'stephan/lsp/handlers.lua'` looks like:
```lua
local function resolve_handler(client, method)
  return client.handlers[method] or vim.lsp.handlers[method]
end

-- slightly tweaked implementation based on https://github.com/neovim/neovim/blob/db47cf81537f929812cd7aa3bc2b852a31cb48ae/runtime/lua/vim/lsp.lua#L719
-- allows for handlers of the form: {type: 'local_lsp', handler: <func>}
exports.client_request = function(client)
    local original_client_request = client.request;
    if client._request_override_applied then
      return original_client_request;
    end

    client._request_override_applied = true;
    return function(method, params, handler, bufnr)
      if not handler then
        handler = resolve_handler(client, method)
          or error(string.format("not found: %q request handler for client %q.", method, client.name))
      end

      if (type(handler) == 'table' and handler.type == 'local_lsp') then
        handler.handler(method, params, client.id, bufnr)
        return true, 1;
      else
        return original_client_request(method, params, handler, bufnr, client.config);
      end
  end
end

exports.lintCodeAction = function(method, params, client_id, bufnr, config)
  local actions = {}
  for _, diagnostic in pairs(params.context.diagnostics) do
    if (diagnostic.source == 'eslint') then
      local rule = string.match(diagnostic.message, "%[([^%]]*)%][ ]*$");
      table.insert(actions, {
        arguments = {
          newText = "// eslint-disable-next-line " .. rule,
          lineNum = diagnostic.range.start.line
        },
        command = "add_indented_new_line",
        title = "Suppress eslint rule " .. rule
      });
    end
  end

  return vim.lsp.handlers['textDocument/codeAction'](nil, method, actions, client_id, bufnr, config);
end

exports.workspaceExecuteCommand = function(method, params, client_id, bufnr, config)
  if params.command == "add_indented_new_line" then
    local lineNum = params.arguments.lineNum;
    local line = vim.fn.getbufline(bufnr, lineNum + 1)[1];
    local prefix = string.match(line, "^%s*")
    vim.fn.appendbufline(bufnr, lineNum, prefix .. params.arguments.newText);
  end
end
```

### Concluding remarks / Request
While in theory, that language server could be patched to support such a code action, it seemed a lot harder to me (especially achieving it in a generic fashion) than simply doing it on the client side (neovim lua config). Also, having a mechanism to do it from within neovim can have other applications, like:
- allowing people to have their own custom capabilities handlers that won't be accepted as PRs in a language server implementation.
- implementing handlers like this (as opposed to simply having keys bound to lua functions to do this stuff) allows one to hook into the existing LSP framework and take advantage of things like lsp-saga, etc... without extra work. 

Also, this can most likely be achieved in a more cleaner fashion that what I ended up doing... so that's why I am requesting an official mechanism to do this :). Let me know if I can clarify more...

**Comment by MagicDuck** [comment] 2021-03-30 22:49
Side note:
Btw, I stole & modified slightly this thing from tj's config and it was invaluable in debugging my lsp stuff:
```lua
P = function(v)
  print(vim.inspect(v))
  return v
end

if pcall(require, 'plenary') then
  RELOAD = require('plenary.reload').reload_module

  ReloadPackage = function(name)
    RELOAD(name)
    return require(name)
  end

  ReloadFunc = function(pname, funcName)
    return function(...)
      local package = ReloadPackage(pname);
      return package[funcName](...);
    end
  end
end
```

So what I would  do is change the handlers to:
```lua
  handlers = {
   ...
    ["workspace/executeCommand"] = {
      type = 'local_lsp',
      handler = ReloadFunc('stephan/lsp/handlers', 'workspaceExecuteCommand')
    }
  }
```
Which allows for the following dev loop without restarting nvim:
1. open a workspace buffer where your lsp server attaches
2. go to `stephan/lsp/handlers.lua`, make changes to `workspaceExecuteCommand` func + save
3. go back to workspace buffer, and `:e!`

I think it could be good to include a note about something like this in the docs somewhere, as it greatly improves the experience.

**Comment by mjlbach** [comment] 2021-03-30 23:33
I don't understand why you need to do all of the indirection, and implement a custom code-action. Couldn't you handle this all client side by querying the returned diagnostics from the language server and implementing your own function to disable the eslint line?

**Comment by MagicDuck** [comment] 2021-03-31 02:20
Like I mentioned above, it's because:
> implementing handlers like this (as opposed to simply having keys bound to lua functions to do this stuff) allows one to hook into the existing LSP framework and take advantage of things like lsp-saga, etc... without extra work.

**Comment by MagicDuck** [comment] 2021-03-31 03:01
Perhaps having some sort of `on_request` callback in the config could be enough?
For example, something like this:
```lua
lspconfig.diagnosticls.setup {
...
  on_init = function(client)
    client.resolved_capabilities.code_action = true
  end,
  on_request = function(client, handler, method, params, bufnr, config)
    if (method === "textDocument/codeAction") then
      my_codeaction_handler(...)
      return false -- prevent default RPC call action in client.request()
    end
  end
}
```

**Comment by mjlbach** [comment] 2021-03-31 03:03
Isn't it cleaner to just do as you currently have done(ish) and override the handler using the handlers key of setup, wrapping the original handler?

**Comment by MagicDuck** [comment] 2021-03-31 03:53
You mean like this?
```lua
lspconfig.diagnosticls.setup {
...
  on_init = function(client)
    client.resolved_capabilities.code_action = true
  end,
  on_request = function(client, handler, method, params, bufnr, config)
    if (method === "textDocument/codeAction") then
      handler(...)
    end
  end,
  handlers = {
    ["textDocument/codeAction"] = handlers.lintCodeAction
  }
}
```
Or do you mean what I had before? I suggested the `on_request` thing because it might have been easier to implement, but I am not sure. 
To me, for sure it would be cleanest without it if there was a way to differentiate between handlers that need to do RPC and handlers that don't.
Maybe something in the vein of the existing `lsp.with(handler, override_config)`, like `lsp.withLocalHandler(handler)` that returns a table which `client.request` can use to figure out if it needs to do RPC or just simply invoke the function?

**Comment by mjlbach** [comment] 2021-03-31 04:09
I still don't get what you're trying to achieve that couldn't be achieved overriding the 'textDocument/codeAction' handler, the `M.code_action` buf function in buf.lua, and on_publish_diagnostics.

**Comment by MagicDuck** [comment] 2021-03-31 04:15
Yes, I understand that the handler doesn't do RPC, but `client.request()` from https://github.com/neovim/neovim/blob/db47cf81537f929812cd7aa3bc2b852a31cb48ae/runtime/lua/vim/lsp.lua#L719 does it and then calls the handler with the result. And in my particular case, If I do what you suggest, it just gets stuck and never calls the handler. I don't understand why, but that's what happens... Possibly it keeps waiting for communication to continue, I am not sure 🤷‍♂️ . That's basically the first thing I attempted as I outlined initially...

**Comment by mjlbach** [comment] 2021-03-31 04:26
Here is the way it works:

1. You invoke vim.lsp.buf.code_action() [here](https://github.com/mjlbach/neovim/blob/0cadab14123a492f6a02f9580315596d604f9a9d/runtime/lua/vim/lsp/buf.lua#L344-L350) which sends a json-rpc request to the language server requesting a code action at the current location
2. The request is handled by the language server, which sends back a json-rpc request which is matched against the available handlers [here](https://github.com/mjlbach/neovim/blob/d41778c993e95c8b37b3d8e10dacc3060ae489da/runtime/lua/vim/lsp.lua#L524-L535) and then redirected to the appropriate handler, in this case [here](https://github.com/mjlbach/neovim/blob/0cadab14123a492f6a02f9580315596d604f9a9d/runtime/lua/vim/lsp/handlers.lua#L113-L144)
3. In this particular case, after prompting the user to choose a code action, a second buf_request is sent to the language server via the the buf_execute_requests helper [here](https://github.com/mjlbach/neovim/blob/0cadab14123a492f6a02f9580315596d604f9a9d/runtime/lua/vim/lsp/handlers.lua#L139-L142) which is implemented [here](https://github.com/mjlbach/neovim/blob/0cadab14123a492f6a02f9580315596d604f9a9d/runtime/lua/vim/lsp/buf.lua#L371-L377). 
4. This is what triggers the second json-rpc loop which is then handled by the handler [here](https://github.com/mjlbach/neovim/blob/0cadab14123a492f6a02f9580315596d604f9a9d/runtime/lua/vim/lsp/handlers.lua#L21-L25).

Any of the above handlers should be overridable. I still don't understand the exact behavior you want, but it should be implementable by overriding any of the above handlers.

**Comment by MagicDuck** [comment] 2021-03-31 04:34
Thanks for outlining how it works. The behaviour I want is:
`On step 2., the handler I have defined for "textDocument/codeAction" gets called.`
The handler never gets called though cause this callback here never executes when talking with diagnosticls:
https://github.com/neovim/neovim/blob/db47cf81537f929812cd7aa3bc2b852a31cb48ae/runtime/lua/vim/lsp.lua#L726

**Comment by MagicDuck** [comment] 2021-03-31 04:38
On the other hand, if I use `tsserver` instead as the language server, it works. My guess is because `tsserver` implements `textDocument/codeAction`, while `diagnosticls` doesn't.

**Comment by mjlbach** [comment] 2021-03-31 04:41
Right, you will never get a codeAction handler to be invoked for a server that doesn't support it without manually wrapping another handler which is called in order to pass the return params to your overridden handler. If that works, I don't see what the problem is?

**Comment by MagicDuck** [comment] 2021-03-31 04:49
Dude, I am close to giving up here, lol... it doesn't matter how much wrapping you do if the end result handler in `client.request()` doesn't get called on the callback by the rpc call.
I have said like 3 times that the end result handler doesn't execute when talking to a server that doesn't support the method.
Therefore, **there is no way for me to override the functionality through a handler.** 

I just want to have custom code actions even if the language server does not support this functionality. Don't know what else to say...

**Comment by mjlbach** [comment] 2021-03-31 04:55
What I'm saying, is that in your example above, there is nothing to stop you from writing a function (M.wrap_code_action()) that wraps M.code_action to directly call exports.lintCodeAction without overriding on_request.

**Comment by MagicDuck** [comment] 2021-03-31 05:04
I am not sure if that would work, because you can have multiple clients hooked up to the same buffer and code actions could be gathered from all of them....
Also, am guessing for lsp-saga to be invoked, I need to call the following in my wrapper, correct?
```lua
 vim.lsp.handlers['textDocument/codeAction'](nil, method, actions, client_id, bufnr, config);
```
I am not sure where I would get `client_id` & `config` args from.
Seems messy...

**Comment by mjlbach** [comment] 2021-03-31 05:09
If you define your overridden function in the on_attach handler for diagnosticls you'll have access to the client (from the args passed to on_attach) and config (from client). 

TBH injecting custom code actions, or providing the infrastructure for it, seems messier to me. I don't think this is a wide use-case, and I'd personally like the lsp client in core to stay as close to the spec as possible.

**Comment by MagicDuck** [comment] 2021-03-31 16:47
That soles part of it but still wouldn't fix the multiple client hooked to same buffer, each with their own code actions problem.

To each their own I suppose. I am not sure if I managed to get across the fundamental idea that is beyond my little example which is allowing people to wrap existing language servers in nvim and make it appear as if that language server provided additional capabilities. 

Sorry if things got a little heated. In any case, we've pretty much exhausted the subject. Maybe a different contributor has a different opinion. In any case I am perfectly happy to continue doing what I'm doing. Just thought this feature would help others...

**Comment by mjlbach** [comment] 2021-03-31 20:11
> Sorry if things got a little heated. 

There are ~3 active contributors to the language server client in core (me being one of them), any of whom need to understand exactly what you want, and why the current implementation does not work for your use case. 

I actually do understand what you want now, to summarize (for others):

When a server does not implement a capability (such as code actions), you would like to send a request (code actions) from neovim that then bypasses the json-rpc loop (which the server can't respond to, since it will ignore the request) and instead directly invokes a custom code_actions handler (essentially, neovim is acting as your 'language server').

The main reason you want to do this, is because you would like to use the unified interface of lspsaga so your custom code actions are injected into the same dialogue with the code actions from the server. This is mildly complicated by the fact that you could be running multiple servers, so you can't (easily) override M.code_actions to directly invoke the handler.

I would update your issue title to be "lsp: allow registering custom, client-side handlers per server".

**Comment by mfussenegger** [comment] 2021-03-31 22:19
Wouldn't it make more sense to add this "suppress lint rule" functionality into a language server itself?
That way other clients would also benefit from it.

I fully agree with @mjlbach on this. This seems like a too niche use case to justify changing things in core to have better designed first class support for this. 
Although it gets a bit ugly there are ways to accomplish what you want

**Comment by MagicDuck** [comment] 2021-03-31 22:28
@mfussenegger 
While in theory, that language server could be patched to support such a code action, it seemed a lot harder to me (especially achieving it in a generic fashion for all the linters that `diagnosticls` supports) than simply doing it on the client side (neovim lua config). This could just be a me problem, not willing to mess around with the internals of `diagnosticls`. On the other hand, having a mechanism to do it from within neovim can have other applications, like allowing people to enrich an existing language server with their own custom capabilities that won't be accepted as PRs in a language server implementation because they are just very specific to their workflow.

**Comment by mjlbach** [comment] 2021-03-31 22:48
I do listen 😆 

I'm torn because I see the value on one hand, but I also see the complexity/user ratio on the other.

The cleanest alternative (IMO) is to launch a dummy language server which just returns the correct packet in response to each request (with nils or whatever), we could even launch a second neovim instance. This seems more like a plugin thing than a core thing though.

**Comment by mjlbach** [comment] 2021-05-25 15:43
If anyone wants this feature, there now exists https://github.com/jose-elias-alvarez/null-ls.nvim which allows you to use the language server API with arbitrary nevoim code action etc. 

This should suffice until we can generalize the APIs around diagnostics/formatting.

**Comment by mjlbach** [comment] 2021-06-08 04:30
This is actually a dupe of https://github.com/neovim/neovim/issues/12326, for which we're probably going to merge a variant of https://github.com/neovim/neovim/issues/12326 which should be a relatively clean solution for this problem.

**Closed by mjlbach** 2021-06-08 04:30 UTC
Labels: enhancement, lsp
