### ISSUE TITLE
segmentation fault on reloading init.vim

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#3587] opened 2015-11-03 07:27 UTC
really weird bug. If I go

    set undofile
    set undodir=~/.dotfiles/nvim/undo

then 

    nmap <leader>r :so $MYVIMRC<CR>

and press <leader>r on the starting screen of neovim I get a segmentation fault

But if I change the undodir to a directory that doesn't exist

     set undodir=~/.dotfiles/nvim/undodir

it works fine, or if I unset the undofile option it works perfectly fine.

I am using the exact same configuration on linux, line by line, exact same directories and env variables but no segmentation faults there. I mean EXACT SAME. I literally copy and paste the directories/files onto my linux system without changing anything and it works perfectly.

It also only happens on the start screen, e.g. Startify or the default neovim welcome.

If I edit a file, go back to Startify and then press <leader>r it also segfaults. 

The file doesn't even necessarily have to be init.vim. it can be some random file on my desktop. But if I get rid of the undofile option or set undodir to some non existent directory it works perfectly fine. 

Here is a gist of a log file (nvim -V2000log) in which I open nvim, press <leader>r and it crashes with a segmentation fault.

https://gist.github.com/nhooyr/d916e03b8ffca75dd6bf

Neither does this happen with vim with the exact same configuration (copy and paste).

**Comment by nhooyr** [comment] 2015-11-03 07:47
Installed from source and it works perfectly, seems to be a problem with home-brew's neovim.

**Comment by yagebu** [comment] 2015-11-03 10:31
Not just a problem with the homebrew version, as I get this both on homebrew-compiled Neovim from master, as well as the Arch Linux 0.1 release package. Sourcing a file with

    set undofile

leads to a segfault if `undodir` already exists.

**Comment by fwalch** [comment] 2015-11-03 11:17
Confirmed. It seems to be related to optimizations. Building with `CFLAGS=-O1 make` doesn't crash, building with `CFLAGS=-O2 make` does. It also crashes with build type `RelWithDebInfo` (`-Og` on gcc).

**Comment by tarruda** [comment] 2015-11-05 14:19
@nhooyr can you determine when this bug was introduced with `git bisect`?

**Comment by nhooyr** [comment] 2015-11-06 00:32
@tarruda i can if you can give me a very brief primer on how to build neovim from source. I don't get any errors when i build with CFLAGS=-02 but I do with RelWithDebInfo. 

The way I am building is cloning the repo, then running CFLAGS=-02 make install. running it and then seeing if it Segfaults and it didn't for me. 

For RelWithDebInfo I couldn't get this to crash for me but thats probably because I built it wrong. Uh I cloned the repo again, went into third-party. Ran

    cmake .
    make install -B

Then I went up and ran 

    cmake -DDEPS_PREFIX=./third-party/usr -DCMAKE_BUILD_TYPE=RelWithDebInfo
    make install -B

But it never segfaults for me. Am I building it wrong?

**Comment by nhooyr** [comment] 2015-11-06 00:52
This doesn't crash for me.
    make CMAKE_BUILD_TYPE=RelWithDebInfo install

**Comment by fwalch** [comment] 2015-11-06 09:30
Actually, it seems to be fixed in current `master` (32a9022). It still crashed for me when I built from 4196d0b. So I think this can be closed.

**Closed by fwalch** 2015-11-06 09:30 UTC
Labels: bug
