### ISSUE TITLE
Take character width into account before wrapping

### ISSUE THREAD

**Issue by reportaman** [neovim/neovim#17917] opened 2022-03-30 04:24 UTC
### Feature already in Vim?

No

### Feature description

If a file contains certain characters that occupy more than one character width, and if such a character falls at the end of line, then the character overflows to the border of tmux (assuming there is a pane to right of nvim pane in tmux).

Add an option to disable this behavior, so such wide glyphs wrap before a character before line width. Put another way, such character should wrap if it doesn't get 2 characters space from the edge.

<img width="96" alt="Screen Shot 2022-03-29 at 9 22 20 PM" src="https://user-images.githubusercontent.com/71736629/160750854-b2244622-c873-4efb-b069-43b8e662144b.png">

**Comment by zeertzjq** [comment] 2022-03-30 04:36
Duplicate of #7151

**Closed by zeertzjq** 2022-03-30 04:36 UTC
Labels: enhancement
