### ISSUE TITLE
split() function is slow for large strings

### ISSUE THREAD

**Issue by skupr** [neovim/neovim#3486] opened 2015-10-22 12:26 UTC
Hi,

I've noted major performance degradation of CtrlP plugin comparing to vanilla vim.
Vim profiling showed that the bottleneck is split() function called on large string
This string is a list of files - in my case, it's about 40k.
In vim, the same split goes almost instantly.

**How to reproduce**
```bash
$ for ((i=0; i<40000; ++i)); do echo "---------------------------------------------------------------"; done > list
$ time nvim +'let l=split(system("cat list"), "\n")' +qall
real    0m29.763s
user    0m29.653s
sys     0m0.037s
$ time vim +'let l=split(system("cat list"), "\n")' +qall                                                                                             
real    0m0.156s
user    0m0.098s
sys     0m0.024s
```

**Some investigations**
Not sure if that will help, but still:

I've run valgrind's callgrind tool, however without debug info it did not show much.
I've built neovim manually from git (commit e38cbb93670272d0da15c60222a123b88ec55002), and suddenly it showed much better results:
```
time neovim/bin/nvim +'let l=split(system("cat list"), "\n")' +qall
real    0m1.679s
user    0m1.433s
sys     0m0.195s
```
But it still times more than original vim.

I've run valgrind's callgrind tool for this build, and it showed that the bottleneck is a strlen() that is called from find_match_text() function, file regexp_nfa.c
However I'm not sure that these results are applicable to original build, because in first callgrind's results, strlen() calling time was neglectible...

**Info**
OS: Linux Mint 17.2 Rafaela 64bit
neovim: 0.0.0+git201510192253+1938+14~ubuntu14.04.1
```
NVIM 0.0.0-alpha (compiled Oct 20 2015 14:37:34)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-eun6ek/neovim-0.0.0+git201510192253+1938+14~ubuntu14.04.1/build/config -I/build/neovim-eun6ek/neovim-0.0.0+git201510192253+1938+14~ubuntu14.04.1/src -I/build/neovim-eun6ek/neovim-0.0.0+git201510192253+1938+14~ubuntu14.04.1/.deps/usr/include -I/build/neovim-eun6ek/neovim-0.0.0+git201510192253+1938+14~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-eun6ek/neovim-0.0.0+git201510192253+1938+14~ubuntu14.04.1/.deps/usr/include -I/build/neovim-eun6ek/neovim-0.0.0+git201510192253+1938+14~ubuntu14.04.1/.deps/usr/include -I/build/neovim-eun6ek/neovim-0.0.0+git201510192253+1938+14~ubuntu14.04.1/.deps/usr/include -I/build/neovim-eun6ek/neovim-0.0.0+git201510192253+1938+14~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-eun6ek/neovim-0.0.0+git201510192253+1938+14~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-eun6ek/neovim-0.0.0+git201510192253+1938+14~ubuntu14.04.1/build/include
Compiled by buildd@lcy01-08

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/share/nvim"
```

Manual build of neovim:
```
NVIM 0.0.0-alpha+201510191853 (compiled Oct 22 2015 18:20:24)
Commit: e38cbb93670272d0da15c60222a123b88ec55002
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/stask/homeenv-pkg/neovim/build/config -I/home/stask/homeenv-pkg/neovim/src -I/home/stask/homeenv-pkg/neovim/.deps/usr/include -I/home/stask/homeenv-pkg/neovim/.deps/usr/include -I/home/stask/homeenv-pkg/neovim/.deps/usr/include/luajit-2.0 -I/home/stask/homeenv-pkg/neovim/.deps/usr/include -I/home/stask/homeenv-pkg/neovim/.deps/usr/include -I/home/stask/homeenv-pkg/neovim/.deps/usr/include -I/home/stask/homeenv-pkg/neovim/.deps/usr/include -I/usr/include -I/home/stask/homeenv-pkg/neovim/build/src/nvim/auto -I/home/stask/homeenv-pkg/neovim/build/include
Compiled by stask@stask-desktop

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/home/stask/neovim/share/nvim"
```
gcc version: 4:4.8.2-1ubuntu6

**Comment by justinmk** [comment] 2015-10-22 13:04
Nice report, thanks. What Vim version?

**Comment by skupr** [comment] 2015-10-22 13:31
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 20 2015 10:34:33)
Included patches: 1-898
Compiled by stask@stask-desktop
Big version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    +xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/stask/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions       
```

**Comment by oni-link** [comment] 2015-10-23 00:04
> I've run valgrind's callgrind tool for this build, and it showed that the bottleneck is a strlen() that is called from find_match_text() function, file regexp_nfa.c

That is the cause of the slowdown. This `strlen()` was added as an extra test with commit 0a116c828debc6192a6bfb6bceb8cf020e867db0:

```diff
diff --git a/src/nvim/regexp_nfa.c b/src/nvim/regexp_nfa.c
index 484dfe1..4cd4224 100644
--- a/src/nvim/regexp_nfa.c
+++ b/src/nvim/regexp_nfa.c
@@ -4781,6 +4781,7 @@ static long find_match_text(colnr_T startcol, int regstart, char_u *match_text)
     if (match
         /* check that no composing char follows */
         && !(enc_utf8
+             && STRLEN(regline) > (size_t)(col + len2)
              && utf_iscomposing(PTR2CHAR(regline + col + len2)))
         ) {
       cleanup_subexpr();
```
Commenting this extra test out brings the test time down to vim's time.

**Comment by justinmk** [comment] 2015-10-23 01:08
Maybe we could wrap `regline` in a getter/setter instead of accessing it directly, so that its length can be cached.

There was a similar case in the same PR: https://github.com/neovim/neovim/pull/3309#discussion_r39183283

**Comment by oni-link** [comment] 2015-11-11 00:12
Knowing the length of a byte sequence should not be necessary for moving to the next character, if invalid bytes would be handled correctly (jump only 1 byte instead of up to 4 (or even 6)). 

In #3150 the problem seems to be that we try to match `U+00ab` (`«`, UTF-8 encoded as `0xc2 0xab`) and the byte sequence `0xab 0x00`. The start of the match is successful, because `utf_ptr2char()` translates the (invalid) byte sequence `0xab 0x00` to character `U+00ab`. By skipping the character `U+00ab` (2 bytes) in the byte sequence, we end up after the byte sequence.

The following patch removes the slowdown and prevents #3150, but the invalid byte problem could also happen elsewhere. Using `utf_ptr2char()` and `utf_char2len()` in combination to determine the length of a character from an invalid byte sequence can lead to the wrong length.

```diff
diff --git a/src/nvim/regexp_nfa.c b/src/nvim/regexp_nfa.c
index 4cd4224..d0b2c16 100644
--- a/src/nvim/regexp_nfa.c
+++ b/src/nvim/regexp_nfa.c
@@ -4780,10 +4780,7 @@ static long find_match_text(colnr_T startcol, int regstart, char_u *match_text)
     }
     if (match
         /* check that no composing char follows */
-        && !(enc_utf8
-             && STRLEN(regline) > (size_t)(col + len2)
-             && utf_iscomposing(PTR2CHAR(regline + col + len2)))
-        ) {
+        && !(enc_utf8 && utf_iscomposing(PTR2CHAR(regline + col + len2)))) {
       cleanup_subexpr();
       if (REG_MULTI) {
         reg_startpos[0].lnum = reglnum;
@@ -6266,8 +6263,28 @@ nfa_regexec_both (
   if (prog->regstart != NUL) {
     /* Skip ahead until a character we know the match must start with.
      * When there is none there is no match. */
-    if (skip_to_start(prog->regstart, &col) == FAIL)
-      return 0L;
+
+    while (1) {
+      if (skip_to_start(prog->regstart, &col) == FAIL) {
+        return 0L;
+      }
+
+      // Check whether regline + col is really the start of UTF-8
+      // character prog->regstart. Could be wrong, because
+      // utf_ptr2char() returns U+00zz for invalid UTF-8 sequence
+      // starting with byte 0xzz.
+      if (!enc_utf8) {
+        break;
+      }
+      char_u *p = regline + col;
+      int c = prog->regstart;
+      if (c < 0x80 || c != *p || (c == 0xc3 && p[1] == 0x83)) {
+        // Match was correct.
+        break;
+      }
+      // Prepare to search after invalid byte
+      col++;
+    }
 
     /* If match_text is set it contains the full text that must match.
      * Nothing else to try. Doesn't handle combining chars well. */
```

**Comment by justinmk** [comment] 2016-01-27 04:26
Closed by https://github.com/neovim/neovim/pull/4093

**Closed by justinmk** 2016-01-27 04:26 UTC
Labels: bug, performance

**Comment by justinmk** [comment] 2016-01-27 04:29
@skupr Could you try CtrlP on latest master?

**Comment by skupr** [comment] 2016-01-27 04:42
@justinmk, it now works fine!
