### ISSUE TITLE
Errors in BufEnter autocmd swallowed when triggered by vim.cmd("buffer ...")

### ISSUE THREAD

**Issue by elihunter173** [neovim/neovim#13711] opened 2021-01-07 19:18 UTC
- `nvim --version`: NVIM v0.5.0-dev+1012-gfe1ebea33
- `vim -u DEFAULTS` (version: ) behaves differently? Vim doesn't have `vim.cmd` or `vim.api`.
- Operating system/version: N/A
- Terminal name/version: N/A
- `$TERM`: N/A

### Steps to reproduce using `nvim -u NORC`

Create the following `bug.lua` file.
```lua
function setup_bug()
  vim.cmd [[autocmd BufEnter * lua print(0); error("error swallowed"); print(1)]]
  -- vim.cmd [[autocmd BufEnter * throw 'error swallowed']]
end
function show_bug()
  local buf = vim.api.nvim_create_buf(true, false)
  vim.api.nvim_buf_set_lines(buf, 0, -1, true, {"some text"})
  vim.cmd("buffer " .. buf)
  -- vim.cmd("doautocmd BufEnter")
end
```

Then run this command.
```
nvim -u NORC -c 'luafile bug.lua' -c 'lua setup_bug(); show_bug()'
```

### Actual behaviour

A new unnamed buffer is created with the text "some text", 0 is printed, and then the new buffer is switched to.

If you comment out line 8 and uncomment line 9 (i.e. replace `buffer` with `doautocmd`), then the error is correctly displayed. `lua error("error swallowed")` and `throw 'error swallowed'` as the autocmd both have the same behavior.

### Expected behaviour

A new unnamed buffer is created with the text "some text" and the following is printed (or similar)

```
0
Error detected while processing command line:
E5108: Error executing lua bug.lua:8: Vim(lua):E5108: Error executing lua [string ":lua"]:1: error swallowed
```

**Comment by elihunter173** [comment] 2022-03-24 03:49
Duplicate: #13726

Funnily enough tamago324 and I noticed the same issue within 1 day of each other

**Comment by zeertzjq** [comment] 2022-03-25 02:25
#13726 is not a duplicate of this one. #13490 may be related though.

**Closed** 2022-08-30 22:13 UTC
Labels: bug, api, events
