### ISSUE TITLE
C: improper indent of structs within return

### ISSUE THREAD

**Issue by 44100hertz** [neovim/neovim#7269] opened 2017-09-14 17:25 UTC
An example:
```C
struct point point_zero() {
    return (struct point){
        0,
            0,
    };
}
```

It's just treating the `{` as the start of a statement and the `,` as a comma operator and getting confused. I think `return` needs to be treated like an lvalue.

**Comment by justinmk** [comment] 2017-09-14 18:41
Can you answer the fields in the issue template?

**Comment by hertz4** [comment] 2017-09-14 20:33
I can assure you this bug is not version, OS, or terminal-specific. If you insist, I will.

**Comment by justinmk** [comment] 2017-09-14 20:42
It's useful to know if Vim has the same behavior, and the exact version of vim that was tested.

**Comment by hertz4** [comment] 2017-09-14 20:48
I'm on v0.2.0.

Vim has this behavior. This is a very old bug, I've been using vim and nvim for some time and it's always been there. The bug is actually in many other editors, too.

**Comment by justinmk** [comment] 2017-09-14 21:17
This is more likely to get attention if report to Vim. Though if you want to send a patch with a test, it's welcome here.

**Comment by hertz4** [comment] 2017-09-14 21:18
Thanks, I'll be sure to bug them about it, too.

**Comment by justinmk** [comment] 2019-03-03 21:26
Duplicate of #3234

**Closed by justinmk** 2019-03-03 21:26 UTC
Labels: bug-vim, syntax
