### ISSUE TITLE
Win10 nightly version icon error

### ISSUE THREAD

**Issue by SheilaLundin** [neovim/neovim#13682] opened 2021-01-04 03:54 UTC
![Snipaste_2021-01-04_11-51-30](https://user-images.githubusercontent.com/20018517/103499547-74ab5580-4e83-11eb-8166-826e1db97646.png)

The stable version is OK.

**Comment by erw7** [comment] 2021-01-06 03:58
Thanks for reporting this, but this is a duplicate of #12928.

**Closed by erw7** 2021-01-06 03:58 UTC
Labels: bug
