### ISSUE TITLE
Empty $HOME results in `./~` being used instead

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#8614] opened 2018-06-21 14:59 UTC
When the environment variable `HOME` is empty, Neovim uses `./~/.local/share/nvim` as the data directory, as seen in https://www.reddit.com/r/neovim/comments/8spc2n/i_dont_want_this_shada_thing_in_my_project_how_do/. I can only confirm in linux.

What should happen instead is maybe up for debate, but at least using `./.local/share/nvim` (i.e. omitting creating `~` in the current directory) seems sensible.

**Comment by mhinz** [comment] 2018-06-21 15:52
Obviously it should use the _absolute_ path `~/.local/share` as default for [`$XDG_DATA_HOME`](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

If it's as easy as changing `$HOME/.local/share` to `~/.local/share`, we should change it, even though it's not a real bug in my opinion. `$HOME` being empty probably leads to a lot of issues with all kinds of software.

**Comment by jamessan** [comment] 2018-06-21 16:07
I think it's fairly common to fall-back to `getpwuid()`'s `pw_dir` field when `$HOME` isn't available.  I'm surprised Vim doesn't do that...

**Comment by jamessan** [comment] 2018-06-21 16:29
Hmm, it looks like [uv_os_homedir()](http://docs.libuv.org/en/v1.x/misc.html#c.uv_os_homedir) should be fairly easy to fit into `init_homedir()`.

**Comment by MorTD** [comment] 2018-07-13 20:37
Hello

Is this still ongoing? Or possible to grab and handle?

**Comment by janlazo** [comment] 2018-08-17 15:11
Related: 8.0.1231,8.1.0211,8.1.0217 and vim-patch PR  #8866

**Comment by mhinz** [comment] 2018-08-17 15:20
@MorTD Oops. Apparently we missed your comment. Yup, as long as this issue isn't closed, nobody took the time to implement it, so.. if you're still interested, please send a PR. :)

**Comment by jamessan** [comment] 2018-08-17 16:11
There are two other PRs that have already started working on it.  We just need to iron out the details on those.

**Comment by LambdaP** [comment] 2018-10-10 12:57
How’s progress on this ironing out?

**Comment by sfcgeorge** [comment] 2018-10-23 10:43
I'm on macOS and `echo $HOME` show it is set, but I still keep getting an empty folder called `~` being created with shada stuff in it.

**Comment by italomg** [comment] 2019-01-10 21:44
I believe that this issue could be closed as https://github.com/neovim/neovim/pull/8641 appears to have fixed it.

**Comment by Lattay** [comment] 2019-02-08 10:12
Hello, I think there is a confusion here ! It is the shell that expand ~ into home path, but other program does not recognize it as a path. To convince yourself try the following in bash :

    $ echo ~
    /home/user
    $ echo "~"
    ~
    $ python -c 'open("~/f", "w").write("hello")'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    FileNotFoundError: [Errno 2] No such file or directory: '~/f'

**Comment by blueyed** [comment] 2019-06-11 16:52
There is some WIP in https://github.com/neovim/neovim/pull/9745.

**Comment by blueyed** [comment] 2019-06-18 06:13
@sfcgeorge 
Your issue might be https://github.com/neovim/neovim/issues/9585 - but you also did not mention the actual value (i.e. `""` (empty) is also set, and having a tilde in there (after shell expansion/`echo`) would take it indeed literally).  Anyway, please follow up in #9585 I guess.

**Comment by acebby** [comment] 2019-09-29 07:23
Hi, newbie here.

> If it's as easy as changing `$HOME/.local/share` to `~/.local/share`, we should change it, even though it's not a real bug in my opinion. `$HOME` being empty probably leads to a lot of issues with all kinds of software.

I agree with mhinz here. $HOME shouldn't be empty for UNIX systems. So how about warning the user before entering nvim that their HOME is empty or whitespace?

If possible, I would like to take up this issue.

**Comment by prabhsuggal** [comment] 2020-10-01 11:45
I would like to contribute here.  I am new to open source development. 
Is this issue OS specific. or can it be reproduced in any OS?

**Closed** 2021-01-11 00:46 UTC
Labels: 0.kind: hacktoberfest, bug, complexity:low, editor, good first issue, phodge
