### ISSUE TITLE
cursor shape not reset when use operator 'c' with 'modifiable' is off

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#10013] opened 2019-05-16 01:35 UTC
- `nvim --version`:  v0.4.0-610-g773bdd41e
- Vim (version: ) behaves differently? Yes
- Operating system/version: linux
- Terminal name/version: lxterminal
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

1. nvim -u NORC
1. :h
1. press `c` and then use hjkl, you will find curosr keep `_` shape
1. you will find that cursor shape can't reset to block by `ESC`. 

### Expected behaviour
The cursor shape should be normal mode block.

**Comment by justinmk** [comment] 2019-05-16 15:51
thanks for the repro steps, added to https://github.com/neovim/neovim/issues/7667.

Duplicate of https://github.com/neovim/neovim/issues/7667

**Comment by zeertzjq** [comment] 2022-11-14 12:21
Is this really a duplicate of #7667? The steps to reproduce looks completely different.

**Comment by zeertzjq** [comment] 2022-11-14 13:22
https://github.com/vim/vim/pull/11545

**Closed** 2022-11-15 15:02 UTC
Labels: ui, bug-vim, complexity:low, has:repro
