### ISSUE TITLE
flickering highlight in vimrc

### ISSUE THREAD

**Issue by GopherJ** [neovim/neovim#13799] opened 2021-01-19 20:24 UTC
- `nvim --version`:  `
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: `Linux Mint v20`
- Terminal name/version: `alacritty@0.6.0`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

### Actual behaviour

![Peek 2021-01-19 21-20](https://user-images.githubusercontent.com/33961674/105088724-94a26200-5a9c-11eb-8634-95146cf191c9.gif)

### Expected behaviour

no flickering and color changes

**Comment by vigoux** [comment] 2021-01-20 09:15
Could you confirm that using `d` instead of `a` in your GIF doesn't trigger the issue ?
What you might see is just vim correctly highlighting text after the `:a` command.

**Comment by chrisbra** [comment] 2021-01-20 10:14
That is expected, because the syntax command parses the `a` as an append command. That is not a bug.

**Comment by GopherJ** [comment] 2021-01-20 10:22
@chrisbra but it's in insert mode

**Comment by GopherJ** [comment] 2021-01-20 10:23
> Could you confirm that using `d` instead of `a` in your GIF doesn't trigger the issue ?
> What you might see is just vim correctly highlighting text after the `:a` command.

yes, I can reproduce it by using `a` or `i` but not `d`

**Comment by chrisbra** [comment] 2021-01-20 10:33
> @chrisbra but it's in insert mode, even it's expected, I think it's still a very bad user experience

Well, the `a` starts an `append` command. the rest of the following code is seen as argument to `:append`, so it is not any more seen  as valid vimrc commands (more or less)

If you think you can improve this code, you might want to discuss concrete improvements with the vim syntax script maintainer Dr. Chip.

**Comment by chrisbra** [comment] 2021-01-20 10:52
so basically everything between an `:append` and a following leading `.` is parsed as literal content that will be `appended`. And since the `:` is optionally and the `append` can be abbreviated as `a` you see the swichting syntax highlighting.

```
:append
foobar
bar
.
```

that is just the way the language works.

**Comment by vigoux** [comment] 2021-01-20 14:54
As I expected, this is not an issue, but a feature.
When encountering weird issues with VimL, don't forget to search in the help files.
In your case, searching for `:h :a` would have helped, and actually, I'd suggest reading the user manual, and searching for things like these.

Closing, as this is normal behavior.

**Closed by vigoux** 2021-01-20 14:54 UTC
Labels: bug
