### ISSUE TITLE
Error executing lua: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:277: Query error at 224:4. Invalid node type "doc_comment":   (doc_comment)) @comment.documentation

### ISSUE THREAD

**Issue by alichtman** [neovim/neovim#27533] opened 2024-02-19 10:03 UTC
### Problem

Opening https://github.com/alichtman/gopro-chaptered-video-assembler/blob/main/src/cli.rs in `NVIM v0.10.0-dev-2397+ga9f578b7a` causes the following error to be spit out over and over.

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:277: Query error at 224:4. Invalid node type "doc_comment":
  (doc_comment)) @comment.documentation
   ^

stack traceback:
	[C]: in function '_ts_parse_query'
	/usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:277: in function 'fn'
	/usr/local/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'fn'
	/usr/local/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'get'
	...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
	...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
	...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:187: in function 'fn'
	...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:489: in function 'for_each_tree'
	...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:174: in function 'prepare_highlight_states'
	...al/share/nvim/runtime/lua/vim/
```

### Steps to reproduce

My dotfiles are here: https://github.com/alichtman/dotfiles/tree/main/.config/nvim-lazyvim and I didn't have time to repro this with the minimal repro template.

### Expected behavior

No errors dumped to screen.

### Neovim version (nvim -v)

v0.10.0-dev-2397+ga9f578b7a

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 23.10

### Terminal name/version

gnome-shell

### $TERM environment variable

xterm-256color

### Installation

build from git source

**Comment by clason** [comment] 2024-02-19 10:04
Duplicate of #3092

**Closed by clason** 2024-02-19 10:04 UTC
Labels: bug, treesitter

**Comment by clason** [comment] 2024-02-19 10:05
There's a reason we insist on minimal reproducing steps...

**Comment by alichtman** [comment] 2024-02-19 10:11
Running `:TSUpdate` fixed the problem. It would be great if the error message either told you this, or pointed you to the issue you linked.

**Comment by clason** [comment] 2024-02-19 10:13
Sorry, but we can't guard against someone using an external plugin incorrectly. The error message correctly points out the specific issue from the point of Neovim.
