### ISSUE TITLE
Stop neovim from changing terminal cursor

### ISSUE THREAD

**Issue by notwidow** [neovim/neovim#20477] opened 2022-10-04 11:31 UTC
### Neovim version (nvim -v)

latest v.0.8.0

### Vim (not Nvim) behaves the same?

not vim user

### Operating system/version

Artix Linux rolling

### Terminal name/version

Alacritty Latest

### $TERM environment variable

xterm-256color

### Installation

pacman

### How to reproduce the issue

set terminal cursor to underline and open and close neovim

### Expected behavior

Neovim should not change terminal cursor and cursor shape should be set to default terminal cursor after exit

### Actual behavior

Changes cursor

**Comment by zeertzjq** [comment] 2022-10-04 11:56
Duplicate of #4396

**Closed by zeertzjq** 2022-10-04 11:56 UTC
Labels: bug, tui
