### ISSUE TITLE
How to open file in new tab from command line on windows 10 by neovim-qt? 

### ISSUE THREAD

**Issue by woshichuanqilz** [neovim/neovim#11493] opened 2019-12-02 02:07 UTC
As the title said 

I googled that nvr can solve this problem but, nvr seems can't run on windows

And remote option seems not work on neovim-qt

**Comment by justinmk** [comment] 2019-12-02 02:22
Remote features will be addressed by https://github.com/neovim/neovim/pull/11326 .

**Closed by justinmk** 2019-12-02 02:22 UTC

**Comment by ashfinal** [comment] 2019-12-02 03:21
@woshichuanqilz Until then, you can use [this script](https://macplay.github.io/listings/nvim-qt/invr.au3.html) recently written by me to workaround this.

Actually nvr works on Windows except the `os.fork` part(there is also a workaround for this, but @mhinz felt not motivated enough to fix this as he was waiting this `--remote/connect` feature to be merged someday).

Anyway, to use my script... I assumpt you've already installed `nvr`? then you need to [autoit3](https://www.autoitscript.com/site/autoit/) to compile this script to `invr.exe`, then run `invr.exe` whenever you need `nvr`.

Oh, there's also a context menu [Edit with Neovim](https://macplay.github.io/others/Edit%20with%20Neovim.reg), so you can basically right-click a file/directory then open it in a new nvim-qt buffer.

**Comment by woshichuanqilz** [comment] 2019-12-02 09:41
![image](https://user-images.githubusercontent.com/11295355/69948463-a4728600-152a-11ea-9111-9ebf2a6b8579.png)
I compile your autoit script and still get error like this, how to fix it. 

can you give me a command line to open the file in neovim new tab on windows?

**Comment by woshichuanqilz** [comment] 2019-12-02 09:41
> @woshichuanqilz Until then, you can use [this script](https://macplay.github.io/listings/nvim-qt/invr.au3.html) recently written by me to workaround this.
> 
> Actually nvr works on Windows except the `os.fork` part(there is also a workaround for this, but @mhinz felt not motivated enough to fix this as he was waiting this `--remote/connect` feature to be merged someday).
> 
> Anyway, to use my script... I assumpt you've already installed `nvr`? then you need to [autoit3](https://www.autoitscript.com/site/autoit/) to compile this script to `invr.exe`, then run `invr.exe` whenever you need `nvr`.
> 
> Oh, there's also a context menu [Edit with Neovim](https://macplay.github.io/others/Edit%20with%20Neovim.reg), so you can basically right-click a file/directory then open it in a new nvim-qt buffer.

please check my last post tnx.

**Comment by mhinz** [comment] 2019-12-02 10:47
@ashfinal 

What is the workaround for `os.fork()`? If there's an easy way to do it, please create a PR for it. I can't implement it as I don't have access to Windows and I stopped using a VM for it, because it was a poor and time-consuming experience.

If someone feels motivated enough to look into it, I'll gladly add him as a contributor who can commit all Win-specific things on its own. Every now and then, I'll check the master branch for regressions on the Unix side and make a new release otherwise.

**Comment by ashfinal** [comment] 2019-12-02 14:18
@woshichuanqilz Strange, `invr myfile` should do the trick. What did you run?
Also, to open file in new tab, just type `invr --remote-tab myfile`.

@mhinz I believe `subprocess` is a more general solution for windows(and *nix?), though I need further investigation and test. The complexity is quite low and I'm 90% sure I can fix this without breaking anything. And there were other flaws: on windows I wanted `nvr` to help launch nvim-qt when I rightclicked something, but `nvr` would cause an ugly command line window flashing by whenever it runned. Maybe `nvr.exe` could be repacked so it didn't have to show this ugly window? Also, on windows passing command line parameters is quite different from on *nix, So the docs may need to update.

What I want to say is, this autoit script is just my quick solution, which was written three days ago. To contribute, I surely need more investigation ;) But rest assured, when I have time and feel confident enough, I will create PRs to commit windows specific things.
