### ISSUE TITLE
macOS Terminal breaks on displaying termguicolors

### ISSUE THREAD

**Issue by tbrodbeck** [neovim/neovim#11327] opened 2019-11-03 09:18 UTC
- `nvim --version`:
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5```
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local```
- Operating system/version: OSX 10.15.1 (19B88)
- Terminal name/version: Terminal Version 2.10 (433) and iTerm Build 3.3.6
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
Either command of those yields the same result
```
nvim -u NORC
env -i TERM=ansi-256color "$(which nvim)"
```
![Screenshot 2019-11-02 at 18 02 20](https://user-images.githubusercontent.com/24418160/68082251-b6251880-fe1a-11e9-8590-dba7f85df2ed.png)
```
:set termguicolors
```
### Expected behaviour (of iTerm and any linux Terminal) on the left side and actual behaviour on the right side
![Screenshot 2019-11-02 at 19 28 13](https://user-images.githubusercontent.com/24418160/68082252-bb826300-fe1a-11e9-90a3-13c413975c2c.png)

(also posted on SO: https://stackoverflow.com/questions/58674310/nvim-in-macos-terminal-breaks-on-displaying-termguicolors)

**Comment by justinmk** [comment] 2019-11-03 11:21
Confirmed. This has been a problem for awhile i think, but I always forget about it because it works in tmux, and I'm always in tmux.

**Comment by rgossiaux** [comment] 2020-10-17 06:35
termguicolors enables 24-bit colors, but the built-in Terminal.app on Mac does not support 24-bit colors, so I don't believe this is a bug.

**Comment by craigmac** [comment] 2021-12-13 19:30
Workaround is simply to guard termguicolors:

```
  if !$TERM_PROGRAM =~ "Apple_Terminal"
    set termguicolors
  endif
```

Terminal.app only supports 256 colours (in 2021...)

**Comment by adonespitogo** [comment] 2022-10-02 17:33
```
  if !$TERM_PROGRAM =~ "Apple_Terminal"
    set termguicolors
  endif
  ```
  
  How to write this in lua?

**Comment by clason** [comment] 2022-10-02 21:18
If you want to use 24bit colors (or generally a sane, modern terminal emulator) on macOS, use https://iterm2.com.

**Comment by justinmk** [comment] 2022-10-02 22:37
It shouldn't look _broken_ though. It works fine in tmux. Can we fallback to 256 colors in unsupported terminals like Terminal.app? I don't think there's a technical blocker here, just need a PR.

**Comment by craigmac** [comment] 2022-10-03 12:58
@justinmk I just tried this and you're right, it does seem to work... at least for default colorscheme, that's bizarre. This is with vanilla tmux and nvim --clean, then opening a file and setting termguicolors. However, if you set colorscheme to one that only defines guifg/guibg, I used macvim.vim for this test, and you set termguicolors, it won't work. There's so many layers here at work it's hard to tell where the issue is, but I think that the default colorscheme is just a special case?

**Comment by justinmk** [comment] 2022-10-03 19:16
> However, if you set colorscheme to one that _only defines guifg/guibg,_ I used macvim.vim for this test, and you set termguicolors, it won't work.

What do you expect? guifg/guibg are for RGB ("gui colors", 'termguicolors') UIs. If the colorscheme does not define ctermfg/ctermbg it can't work (except by interpolation, which is out of scope here).

What I suggested is that we just ignore 'termguicolors' for non-compatible terminals like Terminal.app. However, I'm reminded that this would add different problems: we would be overriding the explicit user setting based on terminal-sniffing, which causes the opposite problem when our terminal-sniffing is wrong...

**Closed by justinmk** 2022-10-03 19:16 UTC
Labels: bug, platform:macos, tui

**Comment by guohanli** [comment] 2022-10-07 15:36
> Workaround is simply to guard termguicolors:
> 
> ```
>   if !$TERM_PROGRAM =~ "Apple_Terminal"
>     set termguicolors
>   endif
> ```
> 
> Terminal.app only supports 256 colours (in 2021...)

A great solution! However, it just looks like the equal sign is wrong. The following script works for me.
```
if !$TERM_PROGRAM == "Apple_Terminal"
  set termguicolors
endif
```

**Comment by lancecontreras** [comment] 2023-09-23 19:41
> Confirmed. This has been a problem for awhile i think, but I always forget about it because it works in tmux, and I'm always in tmux.

I was pulling my hair on why I saw it looking good in my mac terminal. I thought that I broke something. But you're right it's tmux!
