### ISSUE TITLE
jobstop not killing 'make dev'

### ISSUE THREAD

**Issue by dithmer** [neovim/neovim#20236] opened 2022-09-17 21:47 UTC
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

Can't tell, api is different

### Operating system/version

Debian WSL in Windows 10

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

debian package from releases page

### How to reproduce the issue

```
  local api = vim.api
  local fn = vim.fn

  local function start_job(cmd, cwd)
      local buf, win = create_temp_window()
      local job = fn.termopen(cmd, {
          stdout_buffered = false,
          detached = false,
          cwd = cwd,
          on_exit = function(_, code, _)
              print("Job exited with code " .. code)
          end,
      })
      api.nvim_win_close(win, true)
      return buf, job
  end

  local buf, jobid = start_job("make dev", "backend")

  fn.jobstop(jobid)
```

The Makefile contains a single target `dev` which executes a golang binary with an gin-gonic app, which isn't closed, as seen per `ps aux`, after the `jobstop`-command was called.

### Expected behavior

The processes should be killed

### Actual behavior

The processes stay open:

```
dithmer  15643  0.2  0.0   5668  2516 ?        Ss   23:36   0:00 make dev
dithmer  15751  3.2  0.3 1316124 20976 ?       Sl   23:36   0:00 ./bin/gin-gonic-example-app
```

**Comment by justinmk** [comment] 2022-09-19 18:50
duplicate of https://github.com/neovim/neovim/issues/12974#issuecomment-698673003

**Closed by justinmk** 2022-09-19 18:50 UTC
Labels: bug, platform:windows, job-control
