### ISSUE TITLE
Text yanked to unnamed register is prefixed with extraneous newline

### ISSUE THREAD

**Issue by kstevens715** [neovim/neovim#13940] opened 2021-02-14 22:54 UTC
When you yank text to the unnamed clipboard and then try to paste into nvim or any other program the text will be pasted to the next line instead of to the current position of the cursor.

- `nvim --version`:
```
- NVIM v0.5.0-dev+dc3ca16

Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210214-12176-nx69ll/build/config -I/tmp/neovim-20210214-12176-nx69ll/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210214-12176-nx69ll/build/src/nvim/auto -I/tmp/neovim-20210214-12176-nx69ll/build/include
Compiled by kyle@Kyles-MBP

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-dc3ca16_1/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: macOS Big Sur
- Terminal name/version: iTerm2 3.4.4
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
1. nvim -u NORC
2. :set clipboard=unnamed
3. Open a file with some text.
4. Select text in the middle of a line.
5. Yank
6. Paste with `p` in the middle of the line.

```

### Actual behaviour
The yanked text is pasted onto the next line.

### Expected behaviour
The yanked text is pasted in the middle of the line, where your cursor is placed.

**Comment by kstevens715** [comment] 2021-02-14 23:37
Maybe this is already a known issue. It looks like using this plugin fixes the behavior: 
https://github.com/bfredl/nvim-miniyank

**Comment by glacambre** [comment] 2021-06-10 05:42
The behavior is exactly the same with and without `set clipboard=unnamed` for me on linux: the text gets inserted within the line rather than on a different line.

@kstevens715 are you still experiencing this issue on nightly/master? If yes it might be macos specific.

**Comment by kstevens715** [comment] 2021-06-18 15:35
> are you still experiencing this issue on nightly/master? 

I just updated to the latest nightly release and I still have the same issue.

**Comment by clason** [comment] 2021-06-18 16:36
By 

> Select text in the middle of a line.

do you mean `visual-block` selection? If so, this is a duplicate of #1822. You could try out #14848 and see if it fixes the problem for you.

**Closed** 2021-06-18 17:13 UTC
Labels: bug
