### ISSUE TITLE
Bind <C-Space> not working on Windows

### ISSUE THREAD

**Issue by ilya2207** [neovim/neovim#21213] opened 2022-11-28 08:29 UTC
### Neovim version (nvim -v)

v0.8.1

### Vim (not Nvim) behaves the same?

no, 7.4.2066

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal, pure powershell, not working in windows at all

### $TERM environment variable

idk

### Installation

choco install neovim

### How to reproduce the issue

Bind <C-Space> for smth
Try use this bind

### Expected behavior

This should work

### Actual behavior

Bind displayed in map, but nothing happened

**Comment by zeertzjq** [comment] 2022-11-28 08:57
Duplicate of #8435

**Closed by zeertzjq** 2022-11-28 08:57 UTC
Labels: bug
