### ISSUE TITLE
[Website] "Documentation" links return GitHub Pages 404

### ISSUE THREAD

**Issue by lnx-soul** [neovim/neovim#14475] opened 2021-05-02 01:33 UTC
### Actual behaviour

When clicking the "General" link from the "Documentation" dropdown on https://neovim.io/doc/general/, it links a 404 GitHub Pages page.

This is a screenshot of the button in question: https://imgur.com/gallery/xWsxsMV

### Expected behaviour

I expect it to link to the actual "General Documentation".

### Follow up

I'll check out where the documentation lives now and submit a PR.  It's probably a very simple fix.

EDIT: Actually, all of the "Documentation" links are broken.  I'll fix them as well.

**Comment by jamessan** [comment] 2021-05-02 02:48
Duplicate of #14466

**Closed by jamessan** 2021-05-02 02:48 UTC
Labels: bug
