### ISSUE TITLE
Running a command in an `autocmd BufWritePost` causes a crash on `:wq`

### ISSUE THREAD

**Issue by twpayne** [neovim/neovim#27499] opened 2024-02-16 21:05 UTC
### Problem

nvim exits with code 134, indicating that it self-terminated with a SIGABRT signal likely raise by calling `abort()` when a `autocmd BufWritePost` runs a command.

### Steps to reproduce

Put the following in `~/.config/nvim/init.vim`:

```vim
autocmd BufWritePost ~/.config/nvim/* ! sh -c 'echo ok'
```

Run `nvim ~/.config/nvim/init.vim` and immediately quit nvim with `:wq`.

Observe that nvim exits with code 134.

```console
$ echo "autocmd BufWritePost ~/.config/nvim/* ! sh -c 'echo ok'" >> ~/.config/nvim/init.vim
$ nvim ~/.config/nvim/init.vim   # then quit with :wq
$ echo $?                        # print exit code of last process
134
```

Note that this depends on the autocmd pattern:

```vim
autocmd BufWritePost ~/.config/nvim/* ! sh -c 'echo ok'  " triggers bug
autocmd BufWritePost ~/.some/dir/*    ! sh -c 'echo ok'  " triggers bug
autocmd BufWritePost *                ! sh -c 'echo ok'  " does not trigger bug
```

### Expected behavior

Neovim should exit with code 0, indicating success.

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

Not tested

### Operating system/version

macOS 14.2.1

### Terminal name/version

iTerm2 3.4.23

### $TERM environment variable

xterm-256color

### Installation

Homebrew

**Comment by terminalmage** [comment] 2024-02-16 21:35
I can confirm this bug in v0.9.5 on the following platforms:

- Arch Linux: (installed from [official Arch Linux repositories](https://archlinux.org/packages/extra/x86_64/neovim/))
- Ubuntu 20.04 (pre-built binary downloaded from [releases](https://github.com/neovim/neovim/releases/tag/v0.9.5) page).

**Comment by zeertzjq** [comment] 2024-02-16 21:43
Duplicate of #21856

**Closed by zeertzjq** 2024-02-16 21:43 UTC
Labels: bug
