### ISSUE TITLE
Linux: :!python [filename].py throws EOF error on input() function

### ISSUE THREAD

**Issue by IBRice101** [neovim/neovim#18599] opened 2022-05-17 01:12 UTC
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

no, vim 8.2.4827

### Operating system/version

Manjaro Linux 21.2.6

### Terminal name/version

alacritty 0.10.1 (2844606d)

### $TERM environment variable

alacritty

### Installation

Pacman Package Manager

### How to reproduce the issue

```sh
nvim test.py
```
```py
#!/usr/bin/python

x = input("Input a string")
```
```
:!python test.py
```

### Expected behavior

prints "Input a string" with space below for user to input text

### Actual behavior

error thrown
```
Input a stringTraceback (most recent call last):
    file "/home/user/path/to/file/test.py" line 3 in <module>
        x = input("Input a string")
EOFError: EOF when reading a line

Shell returned 1

Press ENTER or type command to continue
```

**Comment by zeertzjq** [comment] 2022-05-17 01:16
Duplicate of #1496

**Closed by zeertzjq** 2022-05-17 01:16 UTC
Labels: bug
