### ISSUE TITLE
lsp: tbl_get attempts to index a boolean value in supports_method

### ISSUE THREAD

**Issue by dimbleby** [neovim/neovim#18344] opened 2022-05-01 12:40 UTC
### Neovim version (nvim -v)

v0.8.0-dev+97-g65b4bf055

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

ubuntu 20.04

### Terminal name/version

xterm

### $TERM environment variable

tmux-256color

### Installation

compile from source

### How to reproduce the issue

attempt to rename a variable using the jedi-language-server

### Expected behavior

variable is renamed

### Actual behavior

```
E5108: Error executing lua vim/shared.lua:0: attempt to index a boolean value
stack traceback:
        vim/shared.lua: in function 'tbl_get'
        /home/dch/.local/nvim/share/nvim/runtime/lua/vim/lsp.lua:988: in function 'supports_method'
        /home/dch/.local/nvim/share/nvim/runtime/lua/vim/lsp.lua:1489: in function 'fn'
        /home/dch/.local/nvim/share/nvim/runtime/lua/vim/lsp.lua:164: in function 'for_each_buffer_client'
        /home/dch/.local/nvim/share/nvim/runtime/lua/vim/lsp.lua:1488: in function 'request'
        ...e/dch/.local/nvim/share/nvim/runtime/lua/vim/lsp/buf.lua:405: in function 'rename'
        [string ":lua"]:1: in main chunk
```
cf #18329

This time I think that the problem is [here](https://github.com/neovim/neovim/blob/65b4bf055f58eb622f59188c3bace2519cb777b1/runtime/lua/vim/lsp.lua#L45): renameProvider has type `boolean | RenameOptions`

**Comment by n3wborn** [comment] 2022-05-01 16:46
Same kind of error for code actions (NVIM v0.8.0-dev+97-g65b4bf055).

When I `:lua vim.lsp.buf.code_action()` 

![image](https://user-images.githubusercontent.com/10246722/166155750-7635494a-4310-46b9-b51c-c390f65f9cab.png)

**Comment by dimbleby** [comment] 2022-05-02 10:43
After #18337 I get a cleaner message instead of the stack trace - but renaming still isn't working where it previously did

```
method textDocument/prepareRename is not supported by any of the servers registered for the current buffer
```

**Comment by Gabrielbdd** [comment] 2022-05-02 14:36
> After #18337 I get a cleaner message instead of the stack trace - but renaming still isn't working where it previously did
> 
> ```
> method textDocument/prepareRename is not supported by any of the servers registered for the current buffer
> ```

I'm facing the same issue. I did some debbuging, and found out that [this PR](https://github.com/neovim/neovim/commit/c618b314c6a266806edf692122b16ba9ff7a8e10) introduced this behavior:
```diff
-  ['textDocument/prepareRename'] = 'rename';
+  ['textDocument/prepareRename'] = { 'renameProvider', 'prepareProvider'} ;
```

The problem is that many LSP servers does not support the "textDocument/prepareRename" request. Removing the "prepareProvider" item works, but it doesn't look like the right solution.

**Comment by hood** [comment] 2022-05-04 11:58
Same issue here, getting:
```
method textDocument/prepareRename is not supported by any of the servers registered for the current buffer
```

whenever trying to rename in buffers using `typescript-language-server`

**Comment by donus3** [comment] 2022-05-06 14:44
I use null-ls and tssever. When call the rename function, the error message is null-ls has no rename capability. Then apply this commit [fix(lsp): fix rename capability checks and multi client support](https://github.com/neovim/neovim/commit/55187de1157e05ea71c7c0404345dee0e27e963e) to filter out the null-ls as
```lua
    vim.keymap.set("n", "grn", function()
      vim.lsp.buf.rename(nil, {
        filter = function(clients)
          return vim.tbl_filter(function(client)
            return client.name ~= "null-ls"
          end, clients)
        end,
      })
    end, opts)
````
It's working!!

**Comment by mfussenegger** [comment] 2022-05-06 17:03
Should be fixed with https://github.com/neovim/neovim/pull/18441 & https://github.com/neovim/neovim/pull/18449

**Closed by mfussenegger** 2022-05-06 17:03 UTC
Labels: bug, lsp
