### ISSUE TITLE
Flaky test: shell/viml_system_spec.

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#2001] opened 2015-02-17 11:48 UTC
It seems shell/viml_system_spec.lua is flaky. Travis build failed with this output:
```
212 successes / 1 failure / 0 errors / 1 pending : 0.0 seconds
Pending → ...vis/build/neovim/neovim/test/functional/job/job_spec.lua @ 101
jobs will only emit the "exit" event after "stdout" and "stderr"
Failure → ...neovim/neovim/test/functional/shell/viml_system_spec.lua @ 80
system() executes shell function `yes` and is interrupted with CTRL-C
./test/functional/ui/screen.lua:234: Row 14 didnt match.
Expected: "Type  :quit<Enter>  to exit Vim                      "
Actual:   "                                                     "
stack traceback:
	./test/functional/ui/screen.lua:234: in function 'wait'
	./test/functional/ui/screen.lua:205: in function 'expect'
	...neovim/neovim/test/functional/shell/viml_system_spec.lua:83: in function <...neovim/neovim/test/functional/shell/viml_system_spec.lua:80>
-- Output to stderr:
CMake Error at /home/travis/build/neovim/neovim/cmake/RunTests.cmake:25 (message):
  Running functional tests failed with error: 1.
```
I resubmitted again and this time it passed.

**Comment by tarruda** [comment] 2015-02-17 21:48
My guess is that it is caused by the process not being killed within the screen test timeout. I tried to fix it by adding a check for the $CI_TARGET environment variable(it multiplies the default timeout by 3) but I'm not sure it worked as I expected.

**Comment by elmart** [comment] 2015-02-19 23:00
Happened again at https://travis-ci.org/neovim/neovim/jobs/51433888.

**Comment by tarruda** [comment] 2015-02-20 10:56
I think the cause may be the same as the one faced by @justinmk(https://github.com/neovim/neovim/pull/1802#issuecomment-74940079). The problem is that with this case, there's no reliable way to wait before calling `screen:expect()`.  After I'm done fixing the issues with the new TUI I will focus on this test

**Comment by tarruda** [comment] 2015-02-21 08:05
Now that #2032 is merged we'll have to watch for more of those failures and close this if it no longer happens.

**Comment by elmart** [comment] 2015-02-21 08:28
Great. I'll keep an eye on this, and close this if it doesn't reproduce anymore. It won't take too long to verify.

**Comment by Pyrohh** [comment] 2015-03-10 04:56
I have not encountered this bug for a while, anyone else?

**Comment by tarruda** [comment] 2015-03-10 09:45
I believe its safe to say its fixed now. If it appears again we'll reopen

**Closed by tarruda** 2015-03-10 09:45 UTC
