### ISSUE TITLE
Have terminal buffer lines not split with new lines

### ISSUE THREAD

**Issue by ilan-schemoul** [neovim/neovim#29503] opened 2024-06-27 20:15 UTC
### Problem

What's very problematic with buffer terminals is that there is line breaks at the end of every lines.
If I write a super long line in any regular buffer then it will be one line that will appear as multiple lines.
For example "a very long phrase, that will be cut" can appear on small screen
"a very long phrase"
", that will be cut"
It appears as two lines but I can search "phrase, that will be" and the search works because it really is one line.
If I have a terminal buffer and in the output there is a super long line it will appear as two lines.
What's very annoying is if I search for a word then I won't find it if it's cut in half. If I type yi" it won't work across lines that are split etc.

### Expected behavior

Not split lines

**Comment by zeertzjq** [comment] 2024-06-27 21:24
Duplicate of #2514

**Closed by zeertzjq** 2024-06-27 21:24 UTC
Labels: enhancement
