### ISSUE TITLE
rbuffer_consumed  crash

### ISSUE THREAD

**Issue by snowair** [neovim/neovim#22199] opened 2023-02-10 02:41 UTC
### Describe the bug

```
nvim: /home/snow/neovim-0.8.3/src/nvim/rbuffer.c:143: rbuffer_consumed: Assertion `count && count <= buf->size' failed.
Aborted (core dumped)
```

### Steps to reproduce

```
NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/snowzhu/??/neovim-0.8.3/build/cmake.config -I/home/snowzhu/??/neovim-0.8.3/src -I/home/snowzhu/??/neovim-0.8.3/.deps/usr/include -I/usr/include -I/home/snowzhu/??/neovim-0.8.3/build/src/nvim/auto -I/home/snowzhu/??/neovim-0.8.3/build/include
Compiled by root@VM-54-247-centos

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

```

### Expected behavior

no crash

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

centos 8.2

### Terminal name/version

bash

### $TERM environment variable

xterm-256color

### Installation

build from release source

**Comment by justinmk** [comment] 2023-02-15 10:22
duplicate of https://github.com/neovim/neovim/issues/21299 , can you try development build?

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.

**Comment by jorgen99** [comment] 2023-02-22 18:51
I got the exact same error message as snowair. 

Our team is using nvim 0.6.1 on Ubuntu 18.04 LTS. The error happens when we start a terminal inside nvim and then start a clojure program that communicates with nvim via sockets.

I'm a vim n00b so I might have gotten the sockets/api thing wrong, but I think that's what we're doing. Sending commands from one buffer to the clojure repl running in the buffer with the terminal.

I cloned the git repo. At first I tried the stable version. 0.8.3, then found this bugreport and tried the latest with sha 675826da6. The only difference is that the latest crashes out to bash without any error message.

I then ran a git bisect from our working version to pinpoint the commit where it starts crashing and it's the following one.

18:24 $ git bisect bad
d5f047bee04a42f40425c34061c84b39af846e1f is the first bad commit

Hope this helps in some way.

/Jörgen

**Closed** 2023-05-07 14:47 UTC
Labels: bug, needs:response, needs:repro, revisit-at-release, has:bisected
