### ISSUE TITLE
nvim.exe on Windows 10.1809 as git editor creates folder "~"with shada after git-commit

### ISSUE THREAD

**Issue by ThoAppelsin** [neovim/neovim#9585] opened 2019-02-07 10:46 UTC
- `nvim --version`: v0.3.4
- *NeoVim* (version: v0.3.1) behaves differently!
- Operating system/version: Windows 10.1809
- Terminal name/version: PowerShell Core
- `$TERM`: ?

### Steps to reproduce using `nvim -u NORC`

```
git config --global core.editor '"nvim -u NORC"'
mkdir test
cd test
git init
echo "asd" > asd.txt
git add .
git commit
:q
```

### Actual behaviour

`init.vim` is not loaded for the nvim, even without NORC.

There is now a folder named "~" in the git directory with a shada file in it. Following is the whole structure of the directory:

```
C:\<somewhere>\TEST
|   asd.txt
|
\---~
    \---AppData
        \---Local
            \---nvim-data
                +---shada
                |       main.shada
                |
                \---swap
```

### Expected behaviour

`init.vim` should be loaded when git-commit is used without NORC.

I did not expect to have that folder. This renders nvim unusable as the git editor.

**Comment by ThoAppelsin** [comment] 2019-02-07 11:32
As I tested this back and forth with v0.3.4, 3, 2, and 1, I noticed that the issue exists with v0.3.2 and onwards, but not on v0.3.1.

**Comment by KillTheMule** [comment] 2019-02-07 11:35
See https://github.com/neovim/neovim/issues/8614

**Comment by ThoAppelsin** [comment] 2019-02-07 11:39
Typing `echo $HOME` in my terminal prints my home directory: `C:\Users\<username>`

**Comment by KillTheMule** [comment] 2019-02-07 11:49
Per default, the shada files are written to `$XDG_DATA_HOME/nvim-data/shada`, which should default to `~/AppData/Local/nvim-data/shada`. Could you check it still has this value?

I'm unclear on things on windows, but this pretty much looks similar: `~` isn't resolved the way it should be.

**Comment by ThoAppelsin** [comment] 2019-02-07 12:05
Unlike `$HOME`, `$XDG_DATA_HOME` is not set in PowerShell.

I don't understand what exactly you want me to do when you ask me to "do it from inside nvim". I tried, `:terminal`, which opened a cmd.exe terminal, which had the value `%HOME%` set. I tried `!echo %HOME%` which gives me an error. `XDG_DATA_HOME` is nowhere to see so far.

Could you be more exact with what you mean. And also, you may want to note that v0.3.1 is issue-free in this particular aspect.

**Comment by KillTheMule** [comment] 2019-02-07 13:10
> I don't understand what exactly you want me to do when you ask me to "do it from inside nvim"

When you type `echo $HOME` in your shell,  you get the shell's value of it. It _should_ be passed to nvim as an environment variable, but to make sure of it, you can type `:echo $HOME` in nvim to see the variable in nvim's environment. Same for `XDG_DATA_HOME`, of course.

> And also, you may want to note that v0.3.1 is issue-free in this particular aspect.

Sure, I noted that, that's why I suggested you might bisect the issue.

> Unlike `$HOME`, `$XDG_DATA_HOME` is not set in PowerShell.

So nvim will probably use its default, which kinda fits the issue I was linking: The `~` isn't resolved.

**Comment by ThoAppelsin** [comment] 2019-02-07 13:36
`:echo $HOME` also does print home, but `:echo $XDG_DATA_HOME` does not.

However, if I first write `$env:XDG_DATA_HOME = $HOME` in PowerShell, and then after launch nvim, then I actually do get my home directory when I type `:echo $XDG_DATA_HOME`. Same thing is true when I set the environment variable to be equal to my current home directory via System Properties dialog.

However, neither `$HOME` nor `$XDG_DATA_HOME` gets printed when I run git-commit with nvim set as its editor. Moreover, `:echo $HOME` results in a crash of nvim.

**Comment by KillTheMule** [comment] 2019-02-07 13:50
> However, neither $HOME nor $XDG_DATA_HOME gets printed when I run git-commit with nvim set as its editor. 

Ok, that basically confirms my suspicion that it's the same as the linked issue: empty $HOME makes the problem you first reported.

> Moreover, :echo $HOME results in a crash of nvim in this case.

Now THAT is something else. I've no idea how to proceed, and if that's another issue or related. Need to bring in the cavalery, @janlazo @justinmk any comments?

**Comment by janlazo** [comment] 2019-02-08 01:28
If `$HOME` is empty, nvim will check `$USERPROFILE` to set `$HOME` internally. Windows sets  `HOMEDRIVE` and `HOMEPATH` instead of `HOME`. Does the bug happen before 1e06c235b81089a0127aea278643e8d236168002?

Related: https://github.com/neovim/neovim/issues/8614

**Comment by ThoAppelsin** [comment] 2019-02-08 20:19
Who knows... I am unable to help you out on that.

**Comment by janlazo** [comment] 2019-02-09 06:16
I can't replicate the issue on 0.3.2 by running the same steps, with or without `-u NORC`. `init.vim` is loaded for me when `core.editor` is set to `nvim`, without `-u NORC`. `init.vim` is loaded by checking the output of `:scriptnames`. Tested with nvim and nvim-qt. Used git from git-for-windows.

**Comment by ThoAppelsin** [comment] 2019-02-09 09:12
I've been able to replicate the issue on yet another Windows machine of mine. It used to have Neovim 0.3.1 that didn't have this issue. I then upgraded Neovim to 0.3.4 and got the issue along with it.

I have tried with Windows PowerShell and cmd.exe here. I had tried with Windows PowerShell and [PowerShell Core](https://github.com/PowerShell/PowerShell) there. It's all the same; 0.3.1 doesn't have the issue while 0.3.2 and beyond does.

I have uninstalled git, which I had installed via Chocolatey, and then installed through [git-scm website](https://git-scm.com/), just to make sure. I also removed [posh-git](https://github.com/dahlbyk/posh-git) along the way. Neither of them was of any help. Works on 0.3.1 but not 0.3.2+.

I want to emphasize this further:
- Issue happens with the switch from 0.3.1 to 0.3.2.
- Issue happens only with the `git-commit`, not when running nvim explicitly.

Finally, I also tried `:scriptnames` which provides me a longer list including my `init.vim` and scripts of my plugins, on 0.3.1. I only get the ones under `C:\tools\neovim\Neovim\share\nvim\runtime` with 0.3.2+.

**Comment by neillrobson** [comment] 2019-04-17 16:44
I am encountering the exact same issue. I have not tested on 0.3.1 or earlier, but on 0.3.4 it seems that neovim is not reading my `init.vim` file--or any user-specific configuration--when run via a `git commit` call. In addition, it creates an empty `~/` directory within the folder that contains the Git project. Running `nvim` on the PowerShell command line explicitly does not yield any of these issues.

The output of `:scriptnames` also matches @ThoAppelsin 's report.

**Comment by ThoAppelsin** [comment] 2019-04-17 16:47
My solution had been to use git's vim as my commit-message editor.

**Comment by lx4r** [comment] 2019-05-01 16:00
Can reproduce this issue on Windows 10 + PowerShell + Neovim 0.3.4 as stated by @neillrobson

**Comment by blueyed** [comment] 2019-06-18 05:40
> * Issue happens only with the `git-commit`, not when running nvim explicitly.

Maybe another nvim is used then, or it gets handled as Unix-line and not Windows, e.g. because it is invoked through bash?

Try comparing the output of `:!env` between nvim-via-git and nvim itself.
See also `:h stdpath()` for diagnosing further.

(Some XDG related commit between 0.3.1 and 0.3.2: 314f6ea)

**Comment by ThoAppelsin** [comment] 2019-06-26 13:52
Strangely, I realized that this issue is not present anymore. I still am using NeoVim v0.3.4, but I have upgraded to Windows 10.1903 on the way. It would be interesting if I had checked this right before the upgrade and after...

**Comment by lx4r** [comment] 2019-06-30 10:19
For me the issue persists with NeoVim version v0.3.7 and Windows version 10.1809.
@blueyed When should I execute `:!env`. I tried to run it when editing a file but that didn't work. Sorry for the noob question. 😇

**Comment by justinmk** [comment] 2019-10-07 05:07
Duplicate of #8614

**Closed by justinmk** 2019-10-07 05:07 UTC
Labels: bug, duplicate, platform:windows
