### ISSUE TITLE
cursor does not match cursorcolumn

### ISSUE THREAD

**Issue by jiajunhuang** [neovim/neovim#3794] opened 2015-12-06 15:57 UTC
steps to reproduce it:
:set cursorcolumn
:help intro
:421
wwwww

**Comment by mhinz** [comment] 2015-12-06 16:14
It happens because of concealed characters from the `help` filetype. It's the same in Vim.

I'll have a look.

**Comment by chrisbra** [comment] 2016-01-26 17:56
Hm, as far as I can see, the mentioned patch does not fix this issue. I think this is another one of the conceal bugs still open in Vim

**Comment by zeertzjq** [comment] 2024-03-15 00:51
Closing as there is no mention of what the expected behavior should be.

**Closed by zeertzjq** 2024-03-15 00:51 UTC
Labels: bug-vim
