### ISSUE TITLE
nvim terminal-mode cursor shape cant't change

### ISSUE THREAD

**Issue by TimKingNF** [neovim/neovim#11246] opened 2019-10-17 13:19 UTC
I try to type the following code in my terminal. `iterm.app`

```
tmux
nvim

# open terminal in nvim
:te

# type `zsh-f` in nvim terminal-mode
zsh -f
$ echo -ne '\e[5 q'
$ echo -ne '\e[1 q'
```
I expect the cursor shape would be changed.  But not. Somebody can tell me what to do is correct? 

thanks.

My Config like this:
```bash
# nvim version: v0.3.8

# a section in `.tmux.conf`
set-option -g default-shell /bin/zsh
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

#  a section in  `init.vim`
if $TERM_PROGRAM =~ "iTerm"
  if empty($TMUX)
      let &t_SI = "\<Esc>]50;CursorShape=1\x7"
      let &t_EI = "\<Esc>]50;CursorShape=0\x7"
      let &t_SR = "\<Esc>]50;CursorShape=2\x7"
  else
      let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
      let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
      let &t_SR = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=2\x7\<Esc>\\"
  endif
endif
```

**Comment by justinmk** [comment] 2019-10-18 05:17
Duplicate of https://github.com/neovim/neovim/issues/3681

**Closed by justinmk** 2019-10-18 05:17 UTC
