### ISSUE TITLE
Python3 ImportError: bad magic number in 'neovim'

### ISSUE THREAD

**Issue by rafi** [neovim/neovim#3085] opened 2015-07-22 21:14 UTC
This error happens if I have [`$PYTHONUSERBASE`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUSERBASE) environment variable set and run any **python3** code, _e.g._ `:python3 print('hello')`:
```
2015/07/23 00:08:33 [info @ main_loop:558] 91447 - Starting Neovim main loop.
2015/07/23 00:08:34 [error @ forward_stderr:333] 91447 - Channel 1 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: bad magic number in 'neovim': b'\x03\xf3\r\n'

2015/07/23 00:08:34 [error @ call_set_error:741] 91447 - msgpack-rpc: Channel was closed by the client
```

**Comment by torpak** [comment] 2015-07-25 06:51
you are not using the same minor version of python interpreter, the neovim python module was compiled with.
for example 3.3 vs. 3.4

**Comment by rafi** [comment] 2015-07-25 10:20
I deleted the python packages, re-compiled neovim, and then:
```sh
sudo pip-2.7 install neovim
sudo pip-3.4 install neovim
```
Configured:
```viml
let g:python_host_prog  = '/opt/local/bin/python2.7'
let g:python3_host_prog = '/opt/local/bin/python3.4'
```

And receiving the same error.
It works fine once I `unset PYTHONUSERBASE`.
Am I doing something wrong?

**Comment by fwalch** [comment] 2015-07-25 10:25
When PYTHONUSERBASE is set, what does [this](https://github.com/neovim/neovim/wiki/Troubleshooting#python-support-isnt-working) show?

**Comment by rafi** [comment] 2015-07-26 22:54
I've completely removed the `$PYTHONUSERBASE` directory, uninstalled every python package from my system, re-installed per my comment above, and still I'm getting same behavior, all the while that `$PYTHONUSERBASE` is set, I'm getting `ImportError: bad magic number in 'neovim': b'\x03\xf3\r\n'`
 
```viml
:let [interp, errors] = provider#pythonx#Detect(2)
:echo interp  " python2
:echo errors " (empty)
:let [interp, errors] = provider#pythonx#Detect(3)
:echo interp  " python3
:echo errors " (empty)
```

```sh
$ echo $PYTHONUSERBASE 
/Users/rafi/.local/lib/python

$ /opt/local/bin/python3.4 -c "import neovim"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: bad magic number in 'neovim': b'\x03\xf3\r\n'

$ unset PYTHONUSERBASE
$ /opt/local/bin/python3.4 -c "import neovim"
$ # empty output
```

**Comment by fwalch** [comment] 2015-07-26 23:03
Well, the last few lines don't involve `nvim` at all, so the problem is on the Python level. I can run `python3 -c "import neovim"` with `PYTHONUSERBASE=/home/florian/.local/lib/python` without problems. Sorry, but... are you sure that `~/.local/lib/python` does not contain a Neovim package?

I'm not sure what Python does internally if `PYTHONUSERBASE` is set, maybe it even looks in additional directories.

FWIW, Neovim detects `python3` (note to self: maybe absolute path would be good here) as Python, *not* `python3.4`. It might not necessarily be the same.

**Comment by fwalch** [comment] 2015-07-26 23:08
Maybe this will show which Neovim package it tries to load:

```
$ python -c "import pip; print([repr(x) for x in pip.get_installed_distributions() if x.key == 'neovim'][0])"
neovim 0.0.37 (/usr/lib/python3.4/site-packages)
```

**Comment by rafi** [comment] 2015-07-26 23:14
```sh
python -c "import pip; print([repr(x) for x in pip.get_installed_distributions() if x.key == 'neovim'][0])"
neovim 0.0.37 (/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages)
```

If I `mv ~/.local/lib/{python,python-tmp}` it works. Really weird, I only have a few packages there I've installed via `--user`.

**Comment by fwalch** [comment] 2015-07-26 23:17
In your case it would be `python3`, not `python`, to execute the command (`python` is Python 2 for you).

**Comment by rafi** [comment] 2015-07-26 23:19
```sh
python3 -c "import pip; print([repr(x) for x in pip.get_installed_distributions() if x.key == 'neovim'][0])"
neovim 0.0.37 (/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages)
```

**Comment by fwalch** [comment] 2015-07-26 23:20
If not Neovim itself, maybe one of its dependencies is installed in `~/.local/lib/python`, and Python tries to load it from there first before loading the globally installed package.

In any case, looks like this is a problem with your Python/packages installation, so I'm closing this.

**Closed by fwalch** 2015-07-26 23:20 UTC

**Comment by rafi** [comment] 2015-07-26 23:25
Running `find $PYTHONUSERBASE -name '*pyc' -delete` fixed the problem. Thanks for your help!
