### ISSUE TITLE
Wrong cursor position when undoing `undojoin`.

### ISSUE THREAD

**Issue by UrsaDK** [neovim/neovim#6276] opened 2017-03-14 15:00 UTC
- `nvim --version`: NVIM 0.2.0-dev
- Vim (version: 7.4 patch 898) behaves differently? no
- Operating system/version: macOS Sierra
- Terminal name/version: Terminal.app
- `$TERM`: xterm-256color

### Actual behaviour

Undoing a change after `undojoin` restores the cursor to the beginning of the buffer.

### Expected behaviour

The cursor should be restored to the location of the joined change.

### Steps to reproduce using `nvim -u NORC`

Save the following commands in a file, eg: `reproduce-err.vim`

```
normal ggiline one is bull of aaaa
set undolevels=10 " splits the change into separate undo blocks

normal Goline two is full of bbbb
set undolevels=10 

normal Goline three is full of cccc        
set undolevels=10

normal Goline four is full of aaaa's again
set undolevels=10

undojoin
keepjumps %s/aaaa/zzzz/
normal u
```
Source the file into an empty vim buffer
```
nvim -u NORC +"so reproduce-err.vim"
```

Also, if it's of any help, StackOverflow (http://stackoverflow.com/questions/31548025) includes a more verbose write up of the issue (with more examples), and some attempts at locating what's causing it.

**Comment by zhou13** [comment] 2017-03-29 20:03
workaround: `noremap <F3> ix<ESC>x:undojoin \| Autoformat<CR>`

**Comment by UmkaDK** [comment] 2017-03-30 11:53
@zhou13, that might do the trick (haven't tested it), but it relies on you noticing that the cursor was restored to the wrong place, which is not always obvious.

**Comment by zhou13** [comment] 2017-03-30 21:20
That's why this is called a "workaround".

**Comment by glacambre** [comment] 2021-06-05 14:53
This bug seems unrelated to undojoin to me - what's moving the cursor is the undoing of the substitution.

**Comment by justinmk** [comment] 2023-09-12 09:50
Duplicate of https://github.com/neovim/neovim/issues/5989

**Closed by justinmk** 2023-09-12 09:50 UTC
Labels: bug-vim
