### ISSUE TITLE
Jumplist deletes jumps on the current line

### ISSUE THREAD

**Issue by Tarmean** [neovim/neovim#10825] opened 2019-08-21 11:47 UTC
- `nvim --version`: NVIM v0.4.0-1760-g7ed212262
- `vim -u DEFAULTS` (version: 8.0) behaves differently? yes
- Operating system/version: WIndows 10
- Terminal name/version: nvim-qt

Using :jumps, calling getjumplist() or using ctrl-o when the topmost jumplist entry is on the current line deletes that jumplist entry.

### Steps to reproduce using `nvim -u NORC`

- Generate a file for testing, e.g. `100ia<esc>yy5p`

Reproduction:
- Create a jumplist entry with m'
- Move somewhere else on the same line
- use ctrl-o

### Actual behaviour
We delete the jumplist entry on the current line and jump to some previous jumplist entry.

### Expected behaviour
Jump back to the marked location on the current line. Create a jump point in the location we used ctrl-o at which will replace the jumplist entry since we can only have one jumplist entry per line.
(Whether this behavior is intuitive is debatable but it's what vim and older neovim versions do)

**Comment by justinmk** [comment] 2019-08-21 12:06
> use ctrl-o

Use backtick-backtick instead of ctrl-o.

This behavior is intentional. It avoids the (much more annoying) extra jump at line 1 when using ctrl-o to move between buffers.

- https://github.com/neovim/neovim/issues/9775
- https://github.com/neovim/neovim/issues/9874#issuecomment-481369640

Duplicate of #9874 , although I think this can be `wontfix`.

**Closed by justinmk** 2019-08-21 12:06 UTC
Labels: bug

**Comment by Tarmean** [comment] 2019-08-21 12:23
Not jumping in place seems fairly sensible for most cases.

I don't really understand why `:jumps` or `getjumplist()` should also delete the first jumplist entry if its on the same line, though.
