### ISSUE TITLE
Setting backupdir causes E506 when edit a symlink file.

### ISSUE THREAD

**Issue by szsdk** [neovim/neovim#16312] opened 2021-11-14 08:41 UTC
### Neovim version (nvim -v)

NVIM v0.6.0-dev+388-g23d13aa4c

### Vim (not Nvim) behaves the same?

Neovim and vim behave the same when setting through vimrc

### Operating system/version

macOS 12.0

### Terminal name/version

kitty 0.23.1 created by Kovid Goyal

### $TERM environment variable

xterm-256color

### Installation

extract from `nvim-macos.tar.gz`

### How to reproduce the issue

```
> cat init.lua

vim.opt.backupdir="~/tmp,/tmp"
-- vim.opt.backupdir={"~/tmp", "/tmp"} -- do not work either
```

```
> cat init_vimrc

set backupdir=~/tmp,/tmp
```

```
> touch t
> ln -s t l
```

```
> nvim -u init_vimrc l
```
In the neovim, `:w` works fine. But
```
> nvim -u init.lua l
```
raises E506

### Expected behavior

Setting through lua and vimrc should work the same.

### Actual behavior

Described in "How to reproduce the issue".

**Comment by zeertzjq** [comment] 2021-11-14 08:45
Does `vim.opt.backupdir = {vim.env.HOME .. '/tmp', 'tmp}` work for you?

**Comment by szsdk** [comment] 2021-11-14 08:47
Yes, that works.

**Comment by zeertzjq** [comment] 2021-11-14 08:48
Duplicate of #15720

**Closed by zeertzjq** 2021-11-14 08:48 UTC
Labels: bug
