### ISSUE TITLE
vim.diagnostic.setqflist clamps diagnostics based on current buffer

### ISSUE THREAD

**Issue by jose-elias-alvarez** [neovim/neovim#16429] opened 2021-11-24 22:41 UTC
### Neovim version (nvim -v)

NVIM v0.6.0-dev+624-ga2e5c2f7c

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.0.1

### Terminal name/version

iTerm2 Build 3.5.0beta2

### $TERM environment variable

xterm-256color / tmux-256color

### Installation

Build from source

### How to reproduce the issue

Prepare two files, `test.lua` and `test-2.lua`:

```lua
-- test.lua
print("hello")
print("hello")
print("hello")
```

```lua
-- test-2.lua
vim.diagnostic.set( vim.api.nvim_create_namespace("test"), vim.fn.bufadd("test.lua"), { { lnum = 1, end_lnum = 2, col = 0, end_col = 0, message = "test diagnostic" } })
```

Note that for the reproduction to succeed, `test-2.lua` should contain only one line.

In the directory containing the two files, run the following command:

```sh
nvim --clean +"edit test-2.lua" +"source test-2.lua" +"lua vim.diagnostic.setqflist()"
```

### Expected behavior

The quickfix list shows the following entry:

```
test.lua|2-3 col 1 error| test diagnostic
```

This is the correct position and reflects what you see if you run the following command, which opens `test.lua` before opening the quickfix list:

```sh
 nvim --clean +"edit test.lua" +"source test-2.lua" +"lua vim.diagnostic.setqflist()"
```

### Actual behavior

The quickfix list shows the following entry, which has an incorrect position:

```
test.lua|1 col 1 error| test diagnostic
```

The issue seems to stem from [this line in `set_list`](https://github.com/neovim/neovim/blob/a2e5c2f7c8ec2b236a0c33cf9fc3cbab17c6cfcd/runtime/lua/vim/diagnostic.lua#L434), which results in diagnostics getting clamped to the current buffer's dimensions. Making the 3rd argument to `get_diagnostics` falsy fixes the issue and seems reasonable, but I don't know if there was a reason for the original behavior that this fix overlooks.

**Comment by gpanders** [comment] 2021-11-25 02:31
Thanks for the issue report and for the repro case. I can indeed reproduce this and your analysis of the problem is 100% correct.

@mjlbach and I decided to clamp line numbers in the quickfix list in https://github.com/neovim/neovim/pull/16370; however, there are two problems here:

1. `get_diagnostics` clamps line numbers for the given `bufnr`, but `setqflist()` includes diagnostics from many different buffers. So `get_diagnostics` needs to be updated to handle the case where it retrieves diagnostics from multiple buffers. This is an easy fix.
2. Diagnostic producers can theoretically (as your reproduction example does) include diagnostics for buffers that are not loaded. This means that we cannot clamp line numbers since we cannot get the number of lines in the buffer.

(1) needs to be resolved in any case, but the question remains: what do we do for diagnostics for unloaded buffers? We can leave those "unclamped" (i.e. just use the "raw" line numbers as sent from the producer), but then we have a mix of clamped and unclamped line numbers. Or we can just leave line numbers in the quickfix list always unclamped (i.e. revert https://github.com/neovim/neovim/pull/16370/commits/5b0d8f85fdb705b07143fc4019189a9dcfe3c108). I'm in favor of the latter. @mjlbach what do you think?

**Comment by mjlbach** [comment] 2021-11-25 02:41
Fine by me
________________________________

**Closed** 2021-11-25 12:28 UTC
Labels: bug, diagnostic
