### ISSUE TITLE
Multiple Cursors like helix

### ISSUE THREAD

**Issue by otavioschwanck** [neovim/neovim#22521] opened 2023-03-04 13:45 UTC
### Problem

2023 and neovim still doesn't have a viable option for multi cursors.

### Expected behavior

https://docs.helix-editor.com/keymap.html#selection-manipulation

**Comment by lewis6991** [comment] 2023-03-04 13:49
Duplicate of #7257

Please look for existing issues before raising new ones.

**Closed by lewis6991** 2023-03-04 13:49 UTC
Labels: enhancement
