### ISSUE TITLE
BUG: [test] about 008_autocommands_spec.lua

### ISSUE THREAD

**Issue by zhaozg** [neovim/neovim#7911] opened 2018-01-24 09:32 UTC
I can't give solution.

```
[  FAILED  ] .../neovim/test/functional\legacy\008_autocommands_spec.lua @ 56: autocommands that delete and unload buffers: BufUnload, VimLeave
.../neovim/test/functional\legacy\008_autocommands_spec.lua:88: Expected objects to be the same.
Passed in:
(string) 'Test A:
  - file name displayed: test://bar.txt
  - quickfix claims that the file name displayed is: test://bar.txt
Test B:
  - number of window open: 2
Test C:
  - 'buftype' of the location list window: quickfix
  - buffer displayed in the 2nd window: test://quux.txt
VimLeave done'
Expected:
(string) 'VimLeave done'

stack traceback:
        .../neovim/test/functional\legacy\008_autocommands_spec.lua:88: in function <.../neovim/test/functional\legacy\008_autocommands_spec.lua:56>
```

**Comment by janlazo** [comment] 2018-01-24 20:40
Check test/functional/legacy/096_location_list_spec.lua and src/nvim/testdir/test_quickfix.vim
If the issue is deleting `test.out`, check the other legacy tests that use it as a tempfile.

**Comment by zhaozg** [comment] 2018-01-30 13:14
@janlazo thanks, and I do some test on your advice, and get two conclusions.

1)   If call os.remove('test.out') in 008_autocommands_spec.lua  setup function, test will pass.
2)  096_location_list_spec.lua call os.remove('test.out') in teardown function, but not remove test.out really, why?

**Comment by zhaozg** [comment] 2018-01-30 13:32
And after test, In addition to test.out, there are other files, including Xtest-functional-eval-buf_functions.d
XTEST feature-ex_cmds-mksession_spec.d XTEST feature-ex_cmds-mkview_spec.d 558 Xtest-functional-plugin-shada.shada.tst need to remove.

**Comment by justinmk** [comment] 2018-02-01 00:06
Just a guess, on Windows if a process is still running, another process can't delete a file opened in the first process. Can work around this by using unique file names in the test files. 

Maybe the actual problem is that `io.open()` is used without closing the file handle. I fixed that by using `helpers.read_file()` instead.

> Xtest-functional-eval-buf_functions.d
> XTEST feature-ex_cmds-mksession_spec.d
> XTEST feature-ex_cmds-mkview_spec.d

Those cases should be fixed by using `helpers.rmdir()`. Should never use `lfs.rmdir()`, it is fragile.

Does https://github.com/neovim/neovim/pull/7950 fix the issues for you?

**Closed** 2018-02-01 02:12 UTC
Labels: platform:windows, tests

**Comment by zhaozg** [comment] 2018-02-01 02:42
Thanks, works fine.
