### ISSUE TITLE
E:484

### ISSUE THREAD

**Issue by Dmitryi** [neovim/neovim#12412] opened 2020-05-31 12:00 UTC
1. I open the diary.md file and create a new .md file.
In the file diary.md I press Enter on the new file and try to open it, but it does not work. In the folder diary a new file is not created. 

2. I am writing tasks for the day.
- [ ] Task one
- [ ] Task Two

Previously, when i press Enter, the cursor would go to the next line and the dash itself would appear, I only added square brackets and wrote text. Now this not work.

3. I press the zg key and this error appears.
E484: Unable to open the file /home/f32/.config/nvim/spell/en.utf-8.add

VimwikiShowVersion - Stable version: 2.5
NVIM v0.4.3
Fedora 32
Xterm(351)

**Comment by glacambre** [comment] 2020-05-31 12:20
This is not a minimal reproducer and it doesn't make clear that this is 
a Neovim bug. I'd recommend asking for help to build a minimal 
reproducer in VimWiki's repository.

**Comment by teto** [comment] 2020-05-31 23:08
does the path exist and do you have write access to it ? /home/f32/.config/nvim/spell/en.utf-8.add

**Comment by Dmitryi** [comment] 2020-06-01 07:26
Yes, in the file init.vim contains the path to the files

`set spellfile=~/.config/nvim/spell/ru.utf-8.add`
`set spellfile=~/.config/nvim/spell/en.utf-8.add`

The directory and files made writable, but no changes have been made.

`sudo chmod 777 -R spell`

**Comment by mhinz** [comment] 2020-06-13 19:23
- I created `~/.config/nvim/spell` and copied `runtime/spell/en-utf8.spl` from this repo to it.
- Then I created a file `test.vim` with these lines:

    ```vim
    set spellfile=~/.config/nvim/spell/en.utf-8.add
    set spell
    ```
- `nvim -u test.vim`
- insert "i rock"
- `i` is highlighted red; use `zg` on it (`en.utf-8.add` and `en.utf-8.add.spl` get created containing only the entry for `i`)


The above works as expected for me. Adding more entries works as well. When I `chmod 444` the add files and then use `zg`, I also get `E484` as expected.

So, double check that the files below `~/.config/nvim/spell` belong to the correct user and have the proper permissions.

I'm closing this in the meanwhile, since there's nothing we can act on. Please just reopen this issue if you think that's wrong and maybe come up with a way to reproduce this with `nvim -u NORC` or a minimal init file.

**Closed by mhinz** 2020-06-13 19:23 UTC
Labels: bug
