### ISSUE TITLE
HOME key works in vim but not neovim in rxvt-unicode

### ISSUE THREAD

**Issue by emilcarr** [neovim/neovim#14257] opened 2021-03-30 21:13 UTC
The HOME key works in vim but not neovim when I am using rxvt-unicode. However, both keys work in another term such as xterm. The END key works fine.

```
$ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: 8.2.2653)
- Operating system/version: Arch Linux
- Terminal name/version: rxvt-unicode 
- `$TERM`: rxvt-unicode-256color
- `$TERM`: rxvt-unicode

### Steps to reproduce using `nvim -u NORC`

```
:map <ESC>[1~ <Home>
:map <ESC>[4~ <End>
:imap <ESC>[1~ <Home>
:imap <ESC>[4~ <End>
```

### Actual behaviour

- Type something
- Press HOME. Observe no movement in cursor position.
- Move cursor and press END. Observe that cursor jumps to end of line.

### Expected behaviour

- Type something
- Press HOME. Observe that cursor jumps to start of line.
- Press END. Observe that cursor jumps to end of line.

**Comment by erw7** [comment] 2021-04-02 06:21
I can't reproduce it. Doesn't the Home key work with `nvim -u NORC`? Normally, the Home key should work without the map setting. What is the result of executing the following command?

```
infocmp rxvt-unicode | egrep 'khome|kend'
infocmp rxvt-unicode-256color | egrep 'khome|kend'
cat -v -
" Press <Home> key. End with ^C.
nvim -u NORC
i^V<Home>
```

**Comment by mhinz** [comment] 2021-04-09 10:23
I'm pretty sure this is a configuration issue.

Do the steps @erw7 mentioned. Harcoding escape sequences like that is bound to fail when switching between different terminal emulators.

I'm closing this, since it's nothing we can act on, but feel free to ask further questions in here, if you need help figuring out terminal issues. Or better use our new https://neovim.discourse.group :)

**Closed by mhinz** 2021-04-09 10:23 UTC
Labels: bug
