### ISSUE TITLE
Pasting register in powershell terminal reverses lines

### ISSUE THREAD

**Issue by peterdhansen** [neovim/neovim#11205] opened 2019-10-11 16:14 UTC
- `nvim --version`: NVIM v0.4.2
- Operating system/version: Windows 10
- Terminal name/version: cmd

### Steps to reproduce using `nvim -u NORC`
make three lines like:
```
1
2
3
```
copy all lines: `Vkky`
Paste lines into terminal buffer
```
:new 
:terminal powershell
<C-\><C\-N>
p
```
### Actual behaviour
lines are pasted as 
```
PS C:\Windows\> 3
>> 2
>> 1
```
### Expected behaviour
correct order
```
PS C:\Windows\> 1
>> 2
>> 3
```

**Comment by Liberatys** [comment] 2019-10-27 17:10
Hey there :D 

I would like to work on this issue if its okay ?

**Comment by justinmk** [comment] 2019-10-27 20:03
@Liberatys feel free, don't need to ask.

**Comment by erw7** [comment] 2019-10-31 05:38
@Liberatys Have you made any progress? The cause of this problem seems to be a line feed code.

```
:terminal powershell
:call jobsend(b:terminal_job_id, "1\n2\n3")
 => PS C:\Windows\> 3
    >> 2
    >> 1
:call jobsend(b:terminal_job_id, "1\r2\r3")
 => PS C:\Windows\> 1
    1
    PS C:\Windows\> 2
    2
    PS C:\Windows\> 3
```

If you paste in the terminal, I think you can fix it by sending a `CR` (`\r`) instead of a `LF` (`\n`).

**Comment by Liberatys** [comment] 2019-10-31 09:28
@erw7 yea I think I have an idea how to resolve the issue... but with the latest version of neovim, my dear system is not longer compiling it ... But I will work on it this evening and will submit the pull if everything works out.

**Comment by blueyed** [comment] 2019-12-21 11:36
See https://github.com/neovim/neovim/pull/11348 for WIP to address/fix this.

**Comment by dundargoc** [comment] 2022-05-23 20:09
Can you try [this](https://github.com/neovim/neovim/pull/18723) and see if it fixes the issue?

**Comment by 3N4N** [comment] 2023-03-08 04:26
Closing because this particular bug seems to have transformed into a different bug, #14621.  Presumably after PR #19315 was merged.  Now, pasting in terminal buffer doesn't reverse the order of the lines -- it strips away the line feeds.

Tested on:

```
OS: Windows 22H2
Terminal emulator: Windows Terminal v1.17.1023
$TERM: xterm-256colors
Shell: cmd.exe

NVIM v0.9.0-dev-854+g8258345c6d48-dirty
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/apps/nvim/share/nvim"

Run :checkhealth for more info
```

**Closed by 3N4N** 2023-03-08 04:26 UTC
Labels: bug, platform:windows, terminal

**Comment by justinmk** [comment] 2023-03-09 01:16
> this particular bug seems to have transformed into a different bug, #14621. Presumably after PR #19315 was merged. Now, pasting in terminal buffer doesn't reverse the order of the lines -- it strips away the line feeds.

#14621 was reported before #19315 , so perhaps it's not a regression but just further work yet to be done :)
