### ISSUE TITLE
Window opened with `enter` and `focusable` false on startup is getting focused

### ISSUE THREAD

**Issue by gregorias** [neovim/neovim#31766] opened 2024-12-29 09:38 UTC
### Problem

Running `vim.api.nvim_open_win` on startup still makes Neovim always enter and focus the leftmost window (it also generates a `BufEnter` event), which is confusing.

This is problematic for me, because [I’m creating empty buffers for padding](https://github.com/shortcuts/no-neck-pain.nvim/blob/5d91f31a2d583a367df97a4654be028fbe13f2d2/lua/no-neck-pain/ui.lua#L129) during startup and I don’t want them to have focus. It would be brittle to try to refocus on `BufEnter` events that are getting generated.

### Steps to reproduce

```lua
-- init.lua
local side_buffer = vim.api.nvim_create_buf(--[[listed]] false,--[[scratch]] false)
local side_win = vim.api.nvim_open_win(side_buffer, false, { split = "left", focusable = false })
```

1. Run:

```shell
nvim --clean -u init.lua init.lua
```

You’ll see that the unnamed buffer (window) on the left has focus.

### Expected behavior

Focus should be on the init.lua.

Alternatively, there should be a way to specify which window should receive focus on startup. 
Naive `set_current_win` on startup doesn’t work. Deferring `set_current_win` after startup is not good, because it causes a flash of moving cursor from the padding buffer.

### Nvim version (nvim -v)

0.10.3

### Vim (not Nvim) behaves the same?

Not relevant, it’s a Lua API issue.

### Operating system/version

macOS 15.1.1 (24B91)

### Terminal name/version

Kitty 0.38.1

### $TERM environment variable

xterm-kitty

### Installation

Homebrew

**Comment by glepnir** [comment] 2024-12-29 10:22
seesm like firstwin is changed .. workaround is use defer_fn move to next event loop

``lua
vim.defer_fn(function()
  vim.api.nvim_open_win(side_buffer, false, { split = 'left', focusable = false })
end, 0)
```

**Comment by zeertzjq** [comment] 2024-12-29 13:34
Duplicate of #29365

**Closed** 2024-12-29 13:35 UTC
Labels: closed:duplicate
