### ISSUE TITLE
:lmap does not trigger for some keys (I've observed `@` and `^`)

### ISSUE THREAD

**Issue by mmalcomson** [neovim/neovim#19042] opened 2022-06-21 16:32 UTC
### Neovim version (nvim -v)

NVIM v0.7.0 and NVIM v0.8.0-dev+423-g2f2022773

### Vim (not Nvim) behaves the same?

No, system vim VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32) Included patches: 1-2269, 3612, 3625, 3669, 3741

### Operating system/version

Ubuntu 20.04

### Terminal name/version

`xterm -v` == XTerm(353)

### $TERM environment variable

xterm-256color

### Installation

Build from source

### How to reproduce the issue

```
nvim --clean
:lmap @ 2<enter>
i<C-^>@
```

### Expected behavior

Should have inserted `2` having applied the lmap

### Actual behavior

Inserts `@` having not applied the lmap.

Other observables are:
- This problem does not trigger inside `tmux`, only in a bare xterm.
- This only happens for some keys -- trying the same with `!` works just fine.  Other keys I've noticed have this problem are `^` and `_`.
- N.b. I had a little check in the debugger, it seems that the `typebuf` is getting K_SPECIAL, KS_MODIFIER, MOD_MASK_SHIFT, @ in it for the `@` key, but for other keys (like the `!`) we simply get the `!` in the typebuffer.

It's the whole special/modifier/shift thing that means the mapping is not triggered -- because there's no mapping for shift-@ there's just a mapping for `@`.

**Comment by clason** [comment] 2022-06-21 16:36
See https://github.com/neovim/neovim/issues/14090#issuecomment-1094483292 and https://github.com/neovim/neovim/issues/14090#issuecomment-1113090354

**Comment by mmalcomson** [comment] 2022-06-21 16:40
Sorry -- I don't quite follow.
I'm talking about the plain `@` and `^` keys, those comments seem to be talking about the`<C-^>` versions.

**Comment by clason** [comment] 2022-06-21 16:44
The issue is that the handling of these `<c-^>` mappings changed, and some terminals are very sensitive to such changes. (For example, I cannot reproduce this issue in iTerm2 on macOS.)

**Comment by zeertzjq** [comment] 2022-06-21 22:55
I found a way to work around this:
```vim
autocmd InsertEnter * call chansend(v:stderr, "\x1b[>4;0m")
autocmd InsertLeave * call chansend(v:stderr, "\x1b[>4;2m")
```

**Comment by mmalcomson** [comment] 2022-06-23 09:56
Thanks!  I appreciate it!
Just for my own curiosity, would you mind telling me what those autocommands do?
I assume the control characters are setting some terminal option somewhere, but my knowledge of terminal control characters is not that large.

**Comment by zeertzjq** [comment] 2022-06-23 09:59
The `InsertEnter` autocommand disables modifyOtherKeys, and the `InsertLeave` autocommand enables modifyOtherKeys.

**Comment by meribold** [comment] 2023-02-10 08:45
I just tried the workaround and it's ineffective here. Details of my setup are in #21944.

**Comment by zeertzjq** [comment] 2023-03-08 08:05
Closing in favor of #20190

**Closed by zeertzjq** 2023-03-08 08:05 UTC
Labels: bug, tui, input, mappings
