### ISSUE TITLE
extmarks are not always rendered when `end_line` is far from the start `line`

### ISSUE THREAD

**Issue by folke** [neovim/neovim#14625] opened 2021-05-23 16:21 UTC
Something I noticed when working on a new plugin. Not blocking for me at all.

1. open a document that is at least two heights of the editor
2. create an extmark from line 1 to the end of the document with hl group to something like `Comment`
3. go to the top of the buffer
4. you'll see the Comment group applied correctly
5. go to the bottom

### Actual behaviour

The extmark will not be rendered.

### Expected behaviour

the text at the bottom should also be with the `Comment` hl.

--- 

If you then slowly scroll up, all of the sudden the extmark will render completely.

There's probably some kind of optimization that checks if the extmark should be rendered, but it only takes the start line into account?

**Comment by bfredl** [comment] 2021-05-25 10:30
We don't have the code for proper intersections yet, this will be fixed in #13243 for 0.6

**Comment by zeertzjq** [comment] 2023-09-15 13:49
I cannot reproduce this even in v0.5.1.

**Closed** 2023-10-16 01:48 UTC
Labels: bug, needs:response, needs:repro, extmarks
