### ISSUE TITLE
LeftRelease is not triggered when double clicking

### ISSUE THREAD

**Issue by hobarrera** [neovim/neovim#7013] opened 2017-07-13 00:02 UTC
I'm trying to properly configure mouse to copy into the PRIMARY xorg selection. I've followed the instructions from [the wiki](https://github.com/neovim/neovim/wiki/FAQ#copying-to-x11-primary-selection-with-the-mouse-doesnt-work)

I would seem that mouse selection copies the selection, but these only seem to work for click-dragging (arbitrary selection), but not for double-clicking (word selection), nor triple-clicking (line selection).

NVIM v0.2.0, on Xorg 1.19.3, using termite.  
Vim behaves differently for any recent version, since this all works out-of-the-box.

**Comment by justinmk** [comment] 2017-07-13 07:22
@sach1t does this sound right?

**Comment by sach1t** [comment] 2017-07-15 22:18
When double or triple clicking there are multiple `<LeftMouse><LeftRelease>` events occurring, so the release is happening. I think the issue is with the interaction between the selection that is happening  (and the jumping into visual mode) and the mapped keys.

**Comment by sach1t** [comment] 2017-07-15 22:49
It might also be worth noting that trying something like `:vnoremap <LeftRelease> "+ygv` (to avoid vim's autoselect) to copy into the clipboard does not work when double or triple clicking in either vim or nvim. So I think it is safe to say that the suggested workaround doesn't fully work in vim either, and so this is not a newly introduced issue.

**Comment by hobarrera** [comment] 2017-07-16 05:08
On `vim`, with it's clipboard-selection integration, double/triple clicking automatically copies to clipboard (just enable `set mouse=a`). No extra mapping is required.

> something like :vnoremap <LeftRelease> "+ygv (to avoid vim's autoselect)

I don't quite follow this -- this only reason I set this mapping is because nvim it won't mouse-copy otherwise.

**Comment by justinmk** [comment] 2017-07-16 10:58
Thanks @sach1t . Then this is a duplicate of https://github.com/neovim/neovim/issues/2325

**Closed by justinmk** 2017-07-16 10:58 UTC
Labels: mouse, tui

**Comment by hobarrera** [comment] 2017-07-16 14:01
This isn't a dupe of that issue. I'm saying that mouse release isn't triggering properly when double clicking, so mouse selection doesn't work _even when following the instructions on the wiki_.

What I'm doing is following nvim docs (and the suggestion on other issues), not merely doing a vim vs nvim mouse comparison.

**Comment by justinmk** [comment] 2017-07-16 14:19
I've updated the wiki (as anyone is free to do): https://github.com/neovim/neovim/wiki/FAQ#copying-to-x11-primary-selection-with-the-mouse-doesnt-work

I'm not sure we can change the semantics of double-click/triple-click to be different from Vim without breaking plugins. Though, if this is really a useful feature then it might be worth breaking, since it's pretty obscure.

If the only reason for this request is to work around the autoselect issue, then, yes, we're back to #2325.

**Comment by jberryman** [comment] 2023-12-05 16:37
@indivisible thanks! mostly works, but strangely for me the `gv` does nothing (no text is selected after the double or triple-click)
