### ISSUE TITLE
:!clear is seemingly broken, not consistent with vim

### ISSUE THREAD

**Issue by kevr** [neovim/neovim#19142] opened 2022-06-28 20:40 UTC
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

Arch Linux 5.18.7-arch1-1

### Terminal name/version

Alacritty 0.10.1-2

### $TERM environment variable

alacritty, also tried with screen-256color

### Installation

Arch Linux community repository

### How to reproduce the issue

1. Launch `nvim`
2. Type `:!clear` and press Enter
3. Problematic escape output is displayed, nothing is cleared, image below

![wtf](https://user-images.githubusercontent.com/1672189/176281881-b854250e-c9eb-46c1-9282-2c538eaa917e.png)

### Expected behavior

1. Launch `vim`
2. Type `:!clear` and press Enter
3. A cleared terminal buffer is displayed properly

![fix](https://user-images.githubusercontent.com/1672189/176282439-552c8627-405f-4daa-b1e7-f7300958e129.png)

### Actual behavior

1. Launch `nvim`
2. Type `:!clear` and press Enter
3. Problematic escape output is displayed, nothing is cleared, image below

![wtf](https://user-images.githubusercontent.com/1672189/176281881-b854250e-c9eb-46c1-9282-2c538eaa917e.png)

**Comment by bfredl** [comment] 2022-06-28 20:44
duplicate of #1496

**Closed by bfredl** 2022-06-28 20:44 UTC

**Comment by kevr** [comment] 2022-06-28 21:03
For other users, I'll leave the solution in case others run into the same issue. Personally, seems a bit odd to me that neovim attempts to support vim's ! for some reason, but doesn't completely support it. Why not just replace `:!` with `:terminal` completely?

Anyway, for users wanting to spawn a clean shell command within neovim, use the `:terminal` command, as suggested by @clason on IRC. The `:terminal` command does not need a clear involved and can be combined with layout pipes to control where it spawns, like `:belowright split | terminal echo hi`.
