### ISSUE TITLE
Clipboard (win32yank) error when opening netrw

### ISSUE THREAD

**Issue by Exisar** [neovim/neovim#10537] opened 2019-07-18 09:26 UTC
- `nvim --version`: NVIM v0.3.8
- Operating system/version: Windows 10 64 bit
- Terminal name/version: nvim-qt, powershell, command prompt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

1. open nvim-qt.exe or open program in a terminal
2. type :Explore

The bin directory is in the PATH environment variable.

### Actual behaviour

program displays the following error:
`clipboard: error invoking win32yank.exe'

![win32yank exe error](https://user-images.githubusercontent.com/50517143/61445954-a8708380-a94e-11e9-9a94-c70894bf4034.PNG)

### Expected behaviour

no error and uses clipboard tool properly

**Comment by justinmk** [comment] 2019-07-18 18:30
Thanks for the report. Try the development version, available from the [Releases](https://github.com/neovim/neovim/releases) page.

Duplicate of https://github.com/neovim/neovim/issues/6695

**Closed by justinmk** 2019-07-18 18:30 UTC
Labels: bug, platform:windows
