### ISSUE TITLE
The status bar (lualine) flickers when using the vim.opt.cmdheight = 0 parameter

### ISSUE THREAD

**Issue by test-github-account-for-me** [neovim/neovim#26875] opened 2024-01-03 19:23 UTC
### Problem

Hello! I found that when using the ```vim.opt.cmdheight = 0``` parameter, the lualine status bar starts flickering when using nvim-cmp. I was looking for a similar error there and found it. It stated that this particular command was the problem, as it was experimental. Please fix this problem! Here is a link to that discussion: https://github.com/hrsh7th/nvim-cmp/issues/1218

### Steps to reproduce

Add the standard settings for lualine, nvim-cmc to your configuration, set the parameter ```vim.opt.cmdheight = 0``` and set any lsp to receive auto-completion. For example, pyrigt.

### Expected behavior

The ```vim.opt.cmdheight = 0``` parameter should hide the command line so that there is no flicker on the status bar (lualine)

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1702233742

### Vim (not Nvim) behaves the same?

most likely, this is specific only to neovim

### Operating system/version

Arch Linux stable

### Terminal name/version

konsole 23.08.4

### $TERM environment variable

xterm-256color

### Installation

the official arch repository

**Comment by wookayin** [comment] 2024-01-03 19:43
Duplicate of #20644

**Closed by wookayin** 2024-01-03 19:43 UTC
Labels: bug
