### ISSUE TITLE
A version can make emoji and mouse work in Windows!

### ISSUE THREAD

**Issue by geekjam** [neovim/neovim#12580] opened 2020-07-01 10:19 UTC
Preview:

![test](https://user-images.githubusercontent.com/5414233/86232719-f36ac180-bbc6-11ea-88d7-7bd8186c3a78.gif)

Requirements:
Windows Terminal

Why?
Current release version: Mouse not works!
Current nightly version: Emoji not works!

Build from this commit:
https://github.com/neovim/neovim/commit/29f1e1995da1c3e6fb94a5f939c43481df3a500d

You can download my build:
https://ci.appveyor.com/project/geekjam/neovim/builds/33822054

**Comment by jamessan** [comment] 2020-07-01 14:12
What's the issue?  Are you saying that commit 29f1e19 fixes the mouse and emoji support?  If so, great.  That PR has been merged already and will be part of our next release.  You can also use a nightly build.

**Comment by geekjam** [comment] 2020-07-01 14:31
@jamessan 
This commit far from the nightly version, I think can't not easy to do that. The better way, maybe somebody to check why we lose emoji support in the future. 🙃

**Comment by jamessan** [comment] 2020-07-01 14:34
@erw7, do you understand what the problem is here?

**Comment by geekjam** [comment] 2020-07-01 14:39
@jamessan I don't know this programming language, just lucky to try 😂

**Comment by clason** [comment] 2020-07-01 16:03
I think they're saying that a later commit _broke_ the support, and that it was still working at 29f1e19, i.e., reporting a regression?

**Comment by erw7** [comment] 2020-07-01 17:51
As @clason said, the emoji don't seem to display correctly after https://github.com/neovim/neovim/commit/29f1e1995da1c3e6fb94a5f939c43481df3a500d as shown below.

- `nvim --version`:  Since v0.5.0-530-g618e9a769
- `vim -u DEFAULTS` (version: ) behaves differently? Yes (8.2.1024)
- Operating system/version: Windows 10
- Terminal name/version: Windows Terminal
- `$TERM`: N/A

### Steps to reproduce using `nvim -u NORC`

emoji.txt
```
💔💑💗
```

```
nvim -u NORC emoji.txt
```

### Actual behaviour
![NG](https://user-images.githubusercontent.com/11682285/86275139-c8579080-bc0d-11ea-9b07-ab6ca66c553f.png)

### Expected behaviour
![OK](https://user-images.githubusercontent.com/11682285/86275155-cf7e9e80-bc0d-11ea-8071-301b5d8fe979.png)

The problem seems to be caused by updating libuv to 1.34.2 (I reverted to 1.32.0 and the problem stopped).

@geekjam Please be sure to respect the issue template when you create the next issue.

**Comment by geekjam** [comment] 2020-07-01 18:09
* nvim --version: v0.5.0-530-g29f1e1995
  You can download: https://ci.appveyor.com/project/geekjam/neovim/builds/33822054/job/dkwe1i4o0jdhop40/artifacts
* Operating system/version: Windows 10
   Version: 18363.900
* Windows Terminal
  Version: 1.0.1401.0
  Config:

```json
// This file was initially generated by Windows Terminal 0.11.1191.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",

    // You can add more global application settings here.
    // To learn more about global settings, visit https://aka.ms/terminal-global-settings

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": false,

    // If enabled, formatted data is also copied to your clipboard
    "copyFormatting": false,

    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
			"fontFace": "Cascadia Code",
			"fontSize": 12
        },
        "list":
        [
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
	        "hidden": false,
		"colorScheme": "One Half Dark"
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "CMD",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },

    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": [],

    // Add custom keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
    "keybindings":
    [
        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },

        // Press Ctrl+Shift+F to open the search box
        { "command": "find", "keys": "ctrl+shift+f" },

        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+n" }
    ]
}
```

* Test File: 
[emoji.txt](https://github.com/neovim/neovim/files/4859630/emoji.txt)

Preview:
![test](https://user-images.githubusercontent.com/5414233/86277328-17e78d80-bc09-11ea-8bbb-95d8279f1f65.gif)

**Comment by erw7** [comment] 2020-07-01 19:18
@geekjam I don't know what the problem is with your Preview, Preview2. Please write the actual and expected behavior in a way that others can understand.

**Comment by erw7** [comment] 2020-07-01 20:42
@geekjam I understand. So you've created a neovim that can take a mouse and emoji on Windows. If possible, create a pull request in such a case. Note that the problem of #11061 recurs in the neovim you created. Therefore, I don't think they will incorporate your changes.

#12583 should allow you to use both the mouse and the emoji on Windows.

**Closed by erw7** 2020-07-01 20:42 UTC
Labels: bug, invalid, platform:windows, tui

**Comment by geekjam** [comment] 2020-07-06 12:23
@erw7 I don't make a private build, I just told you the old commit version can make this works.
