### ISSUE TITLE
Wrong version in download link

### ISSUE THREAD

**Issue by cemsbr** [neovim/neovim#7693] opened 2017-12-05 12:40 UTC
Downloading release [v0.2.2](https://github.com/neovim/neovim/releases/download/v0.2.2/nvim.appimage) appimage gives me the pre-release v0.2.3.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC --version
```

### Actual behaviour
```
NVIM v0.2.3-1-gd6f9d1df0
(...)
```

### Expected behaviour
```
NVIM v0.2.2...
```

**Comment by jamessan** [comment] 2017-12-05 13:02
Duplicate of #7645

**Closed by jamessan** 2017-12-05 13:02 UTC
