### ISSUE TITLE
Neovim terminal text vanishes.

### ISSUE THREAD

**Issue by akashdiphazra** [neovim/neovim#29409] opened 2024-06-19 08:51 UTC
### Problem

https://github.com/neovim/neovim/assets/61003681/30501313-be3e-49f8-84e7-7cc79821b5cf

### Steps to reproduce

Just open nvim use tabbed terminal. i am using toggleterm but it uses the term only. This issue also appears while toggling fullscreen mode also or resizing.

### Expected behavior

terminal should maintain its text.

### Neovim version (nvim -v)

nvim v0.10.0 stable

### Vim (not Nvim) behaves the same?

no info

### Operating system/version

fedora 40

### Terminal name/version

kitty teminal

### $TERM environment variable

xterm-256color

### Installation

build from source using git.

**Comment by zeertzjq** [comment] 2024-06-19 08:57
Duplicate of #4997

**Closed by zeertzjq** 2024-06-19 08:57 UTC
Labels: bug
