### ISSUE TITLE
NVIM could not run properly due to unprotected error in call to lua api

### ISSUE THREAD

**Issue by oscarchuaweiwen-fsd** [neovim/neovim#16704] opened 2021-12-18 13:21 UTC
### Neovim version (nvim -v)

NVIM v0.7.0-dev+737-g818ae74ea

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOs Monterey

### Terminal name/version

iterm2

### $TERM environment variable

iterm2

### Installation

homebrew

### How to reproduce the issue

nvim

someone please help, this problem occur when nvim is run in terminal

### Expected behavior

should be able to run nvim in normal

### Actual behavior

<img width="658" alt="Screenshot 2021-12-18 at 9 21 06 PM" src="https://user-images.githubusercontent.com/81850353/146642507-b189d32e-aaa9-40c3-a115-0133788bb432.png">

**Comment by zeertzjq** [comment] 2021-12-18 13:23
Duplicate of #16688

**Closed by zeertzjq** 2021-12-18 13:23 UTC
Labels: bug

**Comment by gpanders** [comment] 2021-12-19 03:59
Should be fixed by #16714.
