### ISSUE TITLE
[BUG] set langmap breaks % bracket matching.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#3271] opened 2015-08-30 19:34 UTC
I've verified that if the only thing I have in `~/.nvimrc` is

``` viml
set langmap=hHjkKi;iIhjJk
```

, when I navigate to some brackets/parens/brances in a file, for example the `{` in

``` js
if (true) {
  console.log(true)
}
```

, pressing `%` to jump to the matching brakcet/paren/brace causes the entire block to move to the very top of the view. As you can imagine, it is disorienting. 

This has been happening for months, but I've finally reached a point where I can't take it any more. :laughing:

**Comment by fdinoff** [comment] 2015-08-30 19:42
It appears to be a bug in the matchit plugin. I can reproduce in vim after enabling the matchit plugin. Can you contact the maintainer. (I believe its @benjifisher)

**Comment by trusktr** [comment] 2015-08-30 21:23
@fdinoff How do I disable the the matchit plugin? The only line I have in nvimrc is `set langmap=hHjkKi;iIhjJk`.

**Comment by fdinoff** [comment] 2015-08-30 21:25
In vim its one of the default plugins after https://github.com/neovim/neovim/pull/2723, From `:help matchit`

```
You can avoid loading this plugin by setting the "loaded_matchit" variable
in your vimrc file:
        :let loaded_matchit = 1
```

**Comment by trusktr** [comment] 2015-08-31 03:01
@benjifisher If you could fix this, that'd be great! :]

**Comment by docwhat** [comment] 2017-02-04 21:28
Isn't this a bug in `langmap`? If I read the docs correct for `:normal!` it should ignore mappings:

> If the [!] is given, mappings will not be used. Without it, when this command is called from a			non-remappable mapping (`:noremap`), the argument can be mapped anyway.

**Comment by kopischke** [comment] 2017-02-05 11:43
>Isn't this a bug in `langmap`? If I read the docs correct for `:normal!` it should ignore mappings:

That is only true for then `:map` family of commands, `:langmap`s are another beast entirely whose remapping behaviour is controlled by the `(no)langremap` setting [introduced in Vim 7.4.502](https://github.com/vim/vim/commit/4391cf98ec3b94f33dfd053cab25ed56c787bea9) (called `langnoremap` [until patch 7.4.2236](https://github.com/vim/vim/commit/4391cf98ec3b94f33dfd053cab25ed56c787bea9)). [Starting with patch 7.4.1649](https://github.com/vim/vim/commit/aedfcbe1e6c7df6edcd6756d7601bfdec7dd2087), Vim sets that option when loading the _matchit_ plugin.

**Comment by mhinz** [comment] 2021-05-05 10:19
Seems to be fixed on master.

**Closed by mhinz** 2021-05-05 10:19 UTC
Labels: 0.kind: bug-vim, runtime
