### ISSUE TITLE
Provide a way to send a message directly to message history without displaying on screen

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#22880] opened 2023-04-04 02:02 UTC
It would be helpful to have a way to silently send messages to the message history. For example, you could use this to display an on-screen error message and follow it with a backtrace (or some other useful context) sent silently to message history so when the user runs `:messages` they see the error with the context but when they are notified that an error happened they just see the main error text without noise.

**Comment by Shougo** [comment] 2023-04-04 04:12
Hm.  It should be requested to Vim in the first.

**Comment by ddickstein** [comment] 2023-04-04 04:48
Is requesting features from vim and then waiting for a patch a requirement? Per https://github.com/neovim/neovim/issues/2514#issuecomment-580135150, I thought this wasn't needed. I think Neovim feature development would be unlocked somewhat if it could implement features independently and let Vim pull them in after the fact instead of only pulling from Vim.

**Comment by bfredl** [comment] 2023-04-04 08:11
Correct. We like to coordinate potential sharing of new features/API:s with vim but it is not something which needs to happen _upfront_. it is fine to prototype things solely in the neovim repo first.

also related: #22478

**Comment by Shougo** [comment] 2023-04-11 16:23
I have implemented the feature.

https://github.com/vim/vim/pull/12249

**Comment by zeertzjq** [comment] 2023-04-13 06:26
I don't think adding to message history is the best way to solve the original problem mentioned. There is a hard coded limit to the number of messages in message history. Why can't the extra information be stored into a variable and shown by a custom command?

**Comment by clason** [comment] 2023-04-13 06:34
I don't think this is the way we want to address the underlying issue here; the goal is rather to enrich our Neovim API for messages with metadata so users can despatch them however they wish, see https://github.com/neovim/neovim/issues/22478 (which I'm closing this one as duplicate of, since it should cover this use case as well.)

**Closed by clason** 2023-04-13 06:34 UTC
Labels: enhancement, needs:discussion

**Comment by justinmk** [comment] 2023-07-16 12:10
:help histadd()
