### ISSUE TITLE
"nvim -r" (recovery mode) not working

### ISSUE THREAD

**Issue by sam-lunt** [neovim/neovim#11181] opened 2019-10-08 12:48 UTC
The command `nvim -r` fails to display any text or outputs junk console codes, depending on the term setting. When run in tmux (with `TERM=tmux-256color` or `TERM=xterm-kitty`), it outputs nothing. When run in kitty without a tmux session, it outputs the sequence `^[]11;rgb:3f3f/3f3f/3f3f^[\` and displays `execute: 3f3f/3f3f/3f3f` below the new prompt. I installed a few other terminal emulators and had similar problems.

- `nvim --version`:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
I installed vim and did not see the same behavior.

- Operating system/version:
Arch Linux, kernel 5.3.5, libvterm is version 0.1.git5.4a5fa43-1

- Terminal name/version:
kitty version 0.14.6-1, but similar behavior with xterm and urxvt

- `$TERM`:
`tmux-256color` and `xterm-kitty`, as mentioned above.

### Steps to reproduce using `nvim -u NORC`
From a kitty terminal window (with or without tmux), run `nvim -u NORC -r`. No output will be displayed in the tmux case, and a junk control sequence will be displayed when no tmux session is used.

Running `TERM=ansi-256color nvim -u NORC -r` produces the correct output in the tmux case, but without tmux, the code `^[]11;rgb:3f3f/3f3f/3f3f^[\` and `execute` message are both still displayed (along with the correct output).

**Comment by blueyed** [comment] 2019-10-08 17:15
> When run in kitty without a tmux session, it outputs the sequence `^[]11;rgb:3f3f/3f3f/3f3f^[\` and displays `execute: 3f3f/3f3f/3f3f` below the new prompt. I installed a few other terminal emulators and had similar problems.

That's due to the terminal background response.

Do you get other output / the list with `-r`?

(I cannot reproduce it with 0.4.2 myself in kitty - i.e. it lists swapfiles there)

But `nvim -u NORC -cq` outputs those codes.

That's fixed in master (8a4ae3d, f96d1e6).

Should have those for 0.4.3 probably also.

Can you try the nightly?

**Comment by blueyed** [comment] 2019-10-08 17:19
JFI: Cherry-picked 3626d21 to the release-0.4 branch.

**Comment by sam-lunt** [comment] 2019-10-09 00:18
Thanks for the follow up. No, I'm not seeing the swap files listed in either case. I am able to see it when I run something like `nvim -Vfoo -r`, in which case the list of swap files are at the end of the `foo` file.

I tried building master (using the `neovim-git` aur package) as well as `release-0.4`, but neither worked. The effect was different (my entire terminal now flickers for a moment), but there is still no list of swap files. (That was the same for both master and release-0.4)

Let me know if there's anything else I should try, I appreciate the help. (and obviously this is not a pressing issue on my end)

**Comment by blueyed** [comment] 2019-10-09 00:58
I see now.
The flickering is due to the terminal screen to be changed to an alternate screen (and back), and you do not see the swapfiles (unless you have many, which I had initially - then the more-prompt is used).

You can see what's happening by piping it to `cat -A`:
```
^[[?1049h^[[22;0;0t^[[?1h^[=^[[H^[[J^[]11;?^G^[[?2004h^[[m^O^[[H^[[J^[[23BSwap files found:^[[K^[[16;24r^[[16;1H^[[8M^[[1;24r^[[15;1H                          >
$
   In directory ~/.local/share/nvim/swap//:^[[K^M$
1.    %tmp%1.swp^[[K^M$
          owned by: user   dated: Wed Oct  9 02:31:20 2019^[[K^M$
         file name: /tmp/1^[[K^M$
          modified: YES^[[K^M$
         user name: user   host name: a.example.com^[[K^M$
        process ID: 588053 (STILL RUNNING)^[[K^M$
^[[J^[[1 q^[[1 q^[[23;43H^[[34h^[[?25h^[[?25l^[[1 q^[[m^O^[[34h^[[?25h^[[?1l^[>^[[?1049l^[[23;0;0t^[[?2004l^[[?1004l^[[34h^[[?25h
```

So the issue here is also that it should not enter the alternate screen in the first place (and also not clear it etc).

**Comment by blueyed** [comment] 2019-10-09 01:04
It works better with https://github.com/neovim/neovim/pull/11187, but clears the whole screen still (to use the grid there then).

**Comment by blueyed** [comment] 2019-10-09 01:22
Using headless mode fixes it.
I.e. as a workaround you can use `nvim -r --headless`.

**Comment by sam-lunt** [comment] 2019-10-09 10:54
Yup, it works perfectly with `--headless`. Thanks!

**Closed** 2019-10-11 17:17 UTC
Labels: bug
