### ISSUE TITLE
Treesitter query:iter_captures does not give results when omitting a capture name

### ISSUE THREAD

**Issue by jvgrootveld** [neovim/neovim#13759] opened 2021-01-15 07:36 UTC
**Update**: I wrongfully added this issue on the nvim-treesitter [issue 854](https://github.com/nvim-treesitter/nvim-treesitter/issues/854) repository. I moved it to here. Oeps.

**Note**
I am not sure this is a bug or intentional but noteworthy for (new) users nonetheless. Even if this was intentional, I think the documentation can be updated to clarify. I asked a question [on reddit](https://www.reddit.com/r/neovim/comments/kx1ceh/need_a_little_help_with_tree_sitter_query_matching/) first for why this was not working.

**Describe the bug**
The [`query:iter_captures`](https://neovim.io/doc/user/treesitter.html#query:iter_captures()) and [`query:iter_matches`](https://neovim.io/doc/user/treesitter.html#query:iter_matches()) are not returning matches when omitting a capture name in the query.

**To Reproduce**
1. Run this gist :-)
```lua
local ts = vim.treesitter
local ts_utils = require 'nvim-treesitter.ts_utils'

local query_no_name = ts.parse_query("lua", "(function (function_name))")
local query_with_name = ts.parse_query("lua", "(function (function_name)) @item")

function invoke_query(name, query)
    print("--------- " .. name .. " ---------")
    local parser = ts.get_parser(0, "lua")
    local root = parser:parse()[1]:root()
    local start_row, _, end_row, _ = root:range()

    for id, node in query:iter_captures(root, 0, start_row, end_row) do
        local name = query.captures[id]
        print("- capture name: " .. name)
        print_node(string.format("  capture node id(%s)", id), node)
    end
end

function print_node(title, node)
    print(string.format("%s: type '%s' text '%s'", title, node:type(), ts_utils.get_node_text(node, 0)[1]))
end

invoke_query("Query no name - expect results", query_no_name)
invoke_query("Query with name - gives results", query_with_name)
```

Output:
```
--------- Query no name - expect results ---------
--------- Query with name - gives results ---------
- capture name: item
  capture node id(1): type 'function' text 'function invoke_query(name, query)'
- capture name: item
  capture node id(1): type 'function' text 'function print_node(title, node)'
```

**Expected behavior**
I expect the capture `iter_captures` function to return matching nodes regarding of given a capture name. 

**Output of `nvim --version`**
```
NVIM v0.5.0-dev+1016-g0af5a56e4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1610344040703.local
```

**Comment by vigoux** [comment] 2021-01-15 08:26
I think this is expected behavior, because the match you would get would actually be empty.
We _must_ capture node in a match for it to appear, and if you want to get the whole match you can always capture it as a whole as you did.

I am not even sure if that's not `tree-sitter` default behavior rather than an addition we did.

**Comment by jvgrootveld** [comment] 2021-01-15 08:55
@vigoux Thats weird because the Tree-sitter [documentation](https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries) shows a lot of examples without capture names.

The [Query syntax - Capturing Nodes](https://tree-sitter.github.io/tree-sitter/using-parsers#query-syntax) documentation even states the pattern is optional:

> When matching patterns, **you** may want to process specific nodes within the pattern.

It is just something I did not expect to happen.

**Comment by vigoux** [comment] 2021-01-15 10:25
But you are saying you are iterating over the captures, right ?
So if you are omitting the capture in a match, there is no reason to retrieve it !

If you want to iterate over _matches_ there is `iter_matches` for that purpose.

**Comment by theHamsta** [comment] 2021-01-15 10:30
But how is `iter_captures` supposed to work without captures (the captures are actually the names with `@`). Don't you mean to use `:iter_matches` because I would expect this to work even for matches without any captures. Since you wrote that it doesn't it's maybe a bug? Because then `:iter_matches` should actually return an empty table and the id of the match.

**Comment by jvgrootveld** [comment] 2021-01-15 20:07
Not sure, I am pretty new to this so I could be wrong.

When trying with `iter_matches`:
```lua
for pattern, match, metadata in query:iter_matches(root, 0, start_row, end_row) do
    print(inspect(match))
end
```

I get only node matches with the added name.
```
--------- Query no name - expect results ---------
{}
{}
--------- Query with name - gives results ---------
{ <userdata 1> }
{ <userdata 1> }
```

**Comment by vigoux** [comment] 2021-05-21 15:38
So, this is not an issue, this is just how tree-sitter works.

In order to capture nodes you have to ... capture them.
Thus running `iter_matches` without captures will not yield anything,
because you _did not captured them_.

I am closing this now as this is just _not a bug but a
misunderstanding of how tree-sitter works_.

**Closed** 2021-05-21 15:38 UTC
Labels: bug
