### ISSUE TITLE
configuration in vim.opts get disabled when searching 

### ISSUE THREAD

**Issue by tsjazil** [neovim/neovim#18054] opened 2022-04-09 11:41 UTC
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Archlinux

### Terminal name/version

st 0.8.4

### $TERM environment variable

st-256color

### Installation

pacman 

### How to reproduce the issue

Search something in nvim by using '/'

### Expected behavior

and all the options in config get disabled mainly colorscheme and related stuffs

### Actual behavior

![beforesearch](https://user-images.githubusercontent.com/45793120/162572807-63301cdf-2333-436d-bfba-08c1b1a853e6.jpg)

![aftersearch](https://user-images.githubusercontent.com/45793120/162572799-47cade42-fd4f-4f28-ad5d-f33a2b8317fd.jpg)

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by zeertzjq** [comment] 2022-04-09 11:43
Please provide minimal steps to reproduce with `nvim --clean`

**Comment by clason** [comment] 2022-04-09 11:44
And describe _exactly_ what you mean by "all the options in config gets disabled".

**Comment by tsjazil** [comment] 2022-04-09 11:50
> And describe _exactly_ what you mean by "all the options in config gets disabled".

ig the picture describes it

**Comment by clason** [comment] 2022-04-09 11:54
So highlighting gets disabled. Needless to say, I cannot reproduce this. Please add _minimal_ and complete step for anybody else to reproduce this issue on their system.

**Comment by tsjazil** [comment] 2022-04-09 11:59
willl trying neovim 0.7 appimage causes this problem

**Comment by clason** [comment] 2022-04-09 15:49
No. Really, if we don't have the exact steps to reproduce this, there's nothing we can do. I'm closing this issue, but will reopen it when the information is provided.

**Closed by clason** 2022-04-09 15:49 UTC
Labels: bug, status:needs-repro, highlight

**Comment by tsjazil** [comment] 2022-04-10 06:26
Okay, so here you go with the exact steps to reproduce this issue:

- Open any file in  neovim 
- Search for something using /
- See the error i.e, the formatting gets broken

Here are my neovim config files ([link](https://github.com/tsjazil/dotfiles/tree/main/.config/nvim)) & here are my whole [dotfiles](https://github.com/tsjazil/dotfiles/)

Please let me know if there's any more details that I can provide to help the team fix this issue. Or am I doing anything wrong for this to happen?

Thanks! :)

**Comment by clason** [comment] 2022-04-10 08:15
It looks like you are using a "framework" (`alpha-nvim`), which is almost certainly the root of the problem and not something Neovim supports. Unless you can reproduce the issue with `nvim --clean`, it's an issue that should be reported with whatever framework(s) you use.

**Comment by tsjazil** [comment] 2022-04-10 08:53
I disabled alpha-nvim and still these persist
Thanks BTW :)

**Comment by clason** [comment] 2022-04-10 08:54
Again, you have to provide a minimal config (or use `nvim --clean`), otherwise there's nothing we can do here.

**Comment by tsjazil** [comment] 2022-04-10 09:07
Ok thanks

**Comment by tsjazil** [comment] 2022-04-10 09:19
Its another plugin thats causing its thanks for your time
