### ISSUE TITLE
netrw freezes in tree style when pressing `-` on a symbolic link

### ISSUE THREAD

**Issue by bvdmitri** [neovim/neovim#21542] opened 2022-12-26 14:58 UTC
### Neovim version (nvim -v)

v0.8.1

### Vim (not Nvim) behaves the same?

I don't know

### Operating system/version

macOS 13.0.1

### Terminal name/version

iTerm2 3.4.18

### $TERM environment variable

xterm-256color

### Installation

brew install neovim

### How to reproduce the issue

Put the following settings in the init script:
```
-- Use "tree" listing style
vim.g.netrw_liststyle = 3
```

Prepare the "test" setup, create a test (can be empty) folder and make a symbolic link:
```bash
cd /tmp
mkdir testfolder
ln -s testfolder testlink
nvim .
```

Open neovim, put cursor exactly on the symbolic link and press `-` (`go up dir` command).

 

### Expected behavior

NeoVim goes a directory up.

### Actual behavior

NeoVim freezes and uses about 90%. NeoVim cannot be used anymore and must be force closed.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/6557701/209560742-c52c04b1-2c63-40da-a140-14c94b6b6d26.png">

**Comment by zeertzjq** [comment] 2022-12-26 22:05
Cannot reproduce.

**Comment by bvdmitri** [comment] 2022-12-27 08:07
@zeertzjq  Hm, I tried to reproduce the same bug this morning and It worked (with the `--clean` flag), but I had to open another file first, in contrast with the original text 
- use something like `neovim --clean test.txt`
- Execute `:lua vim.g.netrw_liststyle=3`
- Execute `:E`
- Press `-` on a symbolic link

There is a small video recording, you can see that at some point `neovim` uses 90% of CPU (infinite for loop?) and I cannot longer type any commands.

https://user-images.githubusercontent.com/6557701/209633382-c35dbce1-0e3c-40a9-9d3b-2f0e9d0a7ae5.mov

**Comment by BozeBro** [comment] 2023-04-25 21:46
I was able to replicate the issue on my macOS device. I found a workaround by sending a SIGINT (C-c), and then the function will finish and it goes up a directory as expected. You should also find that nvim will stop eating resources afterward. I'll try looking into the issue and finding a proper fix.

**Comment by BozeBro** [comment] 2023-08-02 09:20
The seems to be reproducible on my vim as well if you have the netrw_liststyle=3 in your .vimrc. A current workaround that I found that works for both neovim and vim is to press Ctrl-c (SIGINT) which will stop whatever is pausing us and we will go up a directory. Currently, the error is 
`Error detected while processing function <SNR>16_NetrwBrowseUpDir:
line   40:`
I'll have to see what this means and locate the file. This seems to be a vim issue though

**Comment by rpuhalovich** [comment] 2023-08-26 08:24
Hope it's okay, but I've taken a look at this issue and have opened a PR for a fix for it.

**Comment by justinmk** [comment] 2023-09-11 23:56
https://github.com/vim/vim/pull/12922#issuecomment-1698229697

**Comment by justinmk** [comment] 2024-02-07 20:56
Closing as duplicate of https://github.com/neovim/neovim/issues/27301

**Closed by justinmk** 2024-02-07 20:56 UTC
Labels: bug, plugin, runtime, has:vim-patch, complexity:low, vim-patch, netrw

**Comment by bvdmitri** [comment] 2024-02-08 09:32
Thanks for working on this! But how is this can be a duplicate if it has been opened before 😀 (it also has more discussion and relevant links)

**Comment by ni554n** [comment] 2025-02-27 00:02
On Windows, `vim.g.netrw_liststyle = 3` hangs like this every time upon pressing `-`, but not with `..`
