### ISSUE TITLE
Allow scrolling without moving the cursor.

### ISSUE THREAD

**Issue by urandom** [neovim/neovim#14250] opened 2021-03-30 09:14 UTC
Hi,

The current behavior of neovim (and vim) is for the cursor to always be visible on the screen. This works great all the time, with one exception: when paired with `autocmd CursorHold <buffer> lua vim.lsp.buf.document_highlight()`. When viewing a long piece of code (or using a small window), you can't really see all highlighted references without breaking the highlight. That's because when the window scrolls, the cursor will eventually move in order to stay in view.

Perhaps there can be an option to enable scrolling without ever moving the cursor itself, even if it goes out of view?

**Comment by whitebyte** [comment] 2021-03-30 13:13
Possibly duplicate of https://github.com/neovim/neovim/issues/989

**Comment by urandom** [comment] 2021-03-30 13:46
That looks like it's a duplicate. Should I add a comment with a use-case for it's implementation?

**Comment by teto** [comment] 2021-03-31 13:55
nope it's something we want, just need someone to implement it. Not trivial since it is a fundamental change.

**Closed by teto** 2021-03-31 13:55 UTC
Labels: duplicate, enhancement
