### ISSUE TITLE
[WinBar bug?] CmdlineEnter winbar + Gitsigns navigation + tabnew =  E315: ml_get: invalid lnum

### ISSUE THREAD

**Issue by bluz71** [neovim/neovim#19576] opened 2022-07-30 03:31 UTC
### Neovim version (nvim -v)

NVIM v0.8.0-dev-nightly-2-gea13dce3b

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Linux Mint 20

### Terminal name/version

Alacritty 0.9.0

### $TERM environment variable

alacritty

### Installation

Prebuilt nightly from repo

### How to reproduce the issue

**init.vim**

```viml
call plug#begin('~/.vim/plugged')
Plug 'lewis6991/gitsigns.nvim'
call plug#end()

lua << END
require("gitsigns").setup({
  keymaps = {
    buffer = true,
    ["n ]g"] = '<cmd>lua require"gitsigns".next_hunk({wrap = true})<CR>zz',
  },
})
END

augroup Events
    autocmd!
    autocmd CmdlineEnter * setlocal winbar=%f
augroup END
```

1. Start nvim on any Git-repo file with unstaged changes
2. Navigate to the change using the Gitsigns mappings of `]g`
3. Create a new tab `:$tabnew`

### Expected behavior

A tab should be created without issue.

### Actual behavior

Many `E315: ml_get: invalid lnum` will result:

![Error](https://user-images.githubusercontent.com/11382509/181870746-686e530a-0987-41d5-b96e-5b8dbac180b7.png)

Note, version `NVIM v0.8.0-dev+555-gd07a39c54` does not produce the error. Somewhere between `gd07a39c54` - `gea13dce3b` produces this issue involving `winbar` / `Gitsigns` and `tabnew`.

**Comment by zeertzjq** [comment] 2022-07-30 03:35
Duplicate of #19458

**Closed by zeertzjq** 2022-07-30 03:35 UTC
Labels: bug

**Comment by bluz71** [comment] 2022-07-30 03:42
Apologies, my search skills were poor today.
