### ISSUE TITLE
Flatpak installations cannot read user config

### ISSUE THREAD

**Issue by alexkalderimis** [neovim/neovim#12294] opened 2020-05-10 14:18 UTC
Flatpak overrides values for `XDG_CONFIG_HOME`, and there is no way for users to override this. The host value `HOST_XDG_CONFIG_HOME` is made available instead, which can be controlled by users. This prevents users maintaining configuration in standard directories and using flatpak.

Note:

this situation is not caused by nvim, but by flatpak's understanding of the XDG specification (https://github.com/flatpak/flatpak.github.io/issues/191)

- `nvim --version`:

 ```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/run/build/neovim/_flatpak_build/config -I/run/build/neovim/src -I/app/include -I/usr/include -I/run/build/neovim/_flatpak_build/src/nvim/auto -I/run/build/neovim/_flatpak_build/include
Compiled by buildbot@cncf-x86-1.flathub.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/app/share/nvim"
```
- `vim -u DEFAULTS` (version: ) behaves differently?
   no
- Operating system/version:
   independent - flatpak
- Terminal name/version:
  independent, but I'm using kitty
- `$TERM`: `screen-256color'

### Actual behaviour

User configuration should be read from `$HOME/.config/nvim`

### Expected behaviour

No configuration is found

**Comment by deisi** [comment] 2021-05-11 10:44
So what I do to deal with this is, that I symlink $HOME/.config/nvim with $HOME/.var/app/app-id/config/nvim


That way configuration works as expected.  

Fixing this on the flatpak or nvim side is not a good idea, as this is the way flatpaks are supposed to work. 

The rather more troublesome issue is that the flatpak app has no access to /bin/ or /urs/bin and thus things like `:terminal` wont work.

**Comment by glacambre** [comment] 2021-06-08 07:06
@alexkalderimis What do you want neovim to do here? I'm not sure neovim can do anything about flatpak not adhering to standards.

**Comment by deisi** [comment] 2021-06-08 16:44
>  I'm not sure neovim can do anything about flatpak not adhering to standards.

Well fratpak ist adhering to the XDG standards here. In fact, some of the people who wrote the XDG standard in the first place, are part of the development team responsible for how flatpak handles config files of sandboxes applications. There was a lengthy discussion about this over at flatpak, but lets just summaries this as legit. 

So personally I see now way of fixing this, as it is not really an issue, but intended behavior. Just not what people expect.

**Comment by glacambre** [comment] 2021-06-08 16:47
>Well fratpak ist adhering to the XDG standards here.

>In fact, some of the people who wrote the XDG standard in the first place, are part of the development team responsible for how flatpak handles config files of sandboxes applications.

These are two very different things :). But I agree actually, flatpak adheres to the standards and twist them in a user-unfriendly way.

>So personally I see now way of fixing this, as it is not really an issue, but intended behavior. Just not what people expect.

I agree, let's close this issue then :).

**Closed by glacambre** 2021-06-08 16:47 UTC
Labels: bug
