### ISSUE TITLE
Expanding snippet makes custom `<Tab>` and `<S-Tab>` mappings unusable during active snippet session

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#30198] opened 2024-08-30 18:15 UTC
### Problem

Expanding snippet with `vim.snippet.expand()` makes user keymaps `<Tab>` and `<S-Tab>` unusable during snippet session without (straightforward) way to opt-out of this behavior.

### Steps to reproduce

1. Create the following 'init.lua' file:
    ```lua
    vim.keymap.set('i', '<Tab>',   [[pumvisible() ? "\<C-n>" : "\<Tab>"]],   { expr = true })
    vim.keymap.set('i', '<S-Tab>', [[pumvisible() ? "\<C-p>" : "\<S-Tab>"]], { expr = true })

    local go_right = function()
      if vim.snippet.active({ direction = 1 }) then return vim.snippet.jump(1) end
      local snippet = 'for k, v in pairs($1) do\n\t$0\nend'
      vim.snippet.expand(snippet)
    end
    vim.keymap.set({ 'i', 's' }, '<C-l>', go_right)
    ```
2. `nvim --clean -u init.lua`
3. Start Insert mode and press `<C-l>` to expand snippet.
4. Press `<C-n>` to show completion popup.
5. Press `<Tab>`. Currently it moves to the next tabstop. When not inside active snippet session, it select next completion item.

------

This seems to be the result of #27339 inside which I didn't find the discussion about the motivation to not recognize user's global `<Tab>` and `<S-Tab>` mappings.

### Expected behavior

`vim.snippet.expand()` keeps custom `<Tab>` / `<S-Tab>` mappings usable. Either by default or by some configurable mechanism. Here are several suggestions:

- Set default snippet navigation keymaps only if it doesn't conflict with what user has already created (either global or buffer-local). This is how I'd expect it to work. For example, default LSP mappings behave the same way: [explicitly with `K`](https://github.com/neovim/neovim/blob/5f95f1249f464e4f0ceed468ec5a1ba6e810da14/runtime/lua/vim/lsp.lua#L365) and [implicitly with other defaults](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/_defaults.lua) (because they are created early and globally while user can override them inside config).
- Allow `opts` in `vim.snippet.expand()` with fields `lhs_jump_forward` and `lhs_jump_backward` to customize which keys are used as default for navigating left and right. Preferably with an ability to supply empty string to not create any.
- Provide a `SnippetEnter` event (as suggested in #26449) to trigger after mappings are already created. Users then can delete buffer-local mappings inside an autocommand.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-680+g4353996d0

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.10.6-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

**Comment by justinmk** [comment] 2024-08-30 22:18
> This seems to be the result of #27339 inside which I didn't find the discussion about the motivation to not recognize user's global `<Tab>` and `<S-Tab>` mappings.

Because we need reasonable defaults, and users can set different mappings if they want.

> Set default snippet navigation keymaps only if it doesn't conflict with what user has already created (either global or buffer-local). 

I have Tab/S-Tab global mappings, they're irrelevant during snippet editing.



> default LSP mappings [`K`](https://github.com/neovim/neovim/blob/5f95f1249f464e4f0ceed468ec5a1ba6e810da14/runtime/lua/vim/lsp.lua#L365) and [other defaults](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/_defaults.lua) ... are created early and globally while user can override them inside config.

That would be possible if we had a true snippet "mode", but we don't have that. 



> Provide a `SnippetEnter` event (as suggested in [Add `SnippetEnter` and `SnippetLeave` events #26449](https://github.com/neovim/neovim/issues/26449)) to trigger after mappings are already created

I also [mentioned](https://github.com/neovim/neovim/issues/26449#issuecomment-1845145737) in that issue that "mode" is needed.

So this issue is basically a duplicate of that issue?

**Closed by justinmk** 2024-08-30 22:18 UTC
Labels: bug, snippet

**Comment by echasnovski** [comment] 2024-08-31 06:33
> > This seems to be the result of #27339 inside which I didn't find the discussion about the motivation to not recognize user's global `<Tab>` and `<S-Tab>` mappings.
> 
> Because we need reasonable defaults, and users can set different mappings if they want.

@justinmk, I wholeheartedly agree about reasonable *defaults*, which among other things means that they can be customized. This is *not* the case here. Exactly `<Tab>` and `<S-Tab>` are [temporarily forced after session is created](https://github.com/neovim/neovim/blob/53af02adbad049f5fc24540cc0f38fa4f9aadf58/runtime/lua/vim/snippet.lua#L242-L251) and user can do *nothing* to prevent that. Making them customizable will solve this issue.

> > Set default snippet navigation keymaps only if it doesn't conflict with what user has already created (either global or buffer-local).
> 
> I have Tab/S-Tab global mappings, they're irrelevant during snippet editing.

That certainly is possible. Same as the opposite of them being relevant. Having `<Tab>`/`<S-Tab>` navigating through completion list (be it built-in pop-up or nvim-cmp) is definitely not uncommon. With current snippet expansion behavior using it this way is impossible (without hacks that try to delete buffer-local `<Tab>`/`<S-Tab>` Insert mode mappings).

**Comment by echasnovski** [comment] 2024-08-31 06:50
Even the hack of wrapping `vim.snippet.expand()` to later delete buffer-local mappings doesn't work, because [later delete of those temporary mappings](https://github.com/neovim/neovim/blob/53af02adbad049f5fc24540cc0f38fa4f9aadf58/runtime/lua/vim/snippet.lua#L264) throws an error of `E31: No such mapping`.

Here is the reference (makes `<Tab>`/`<S-Tab>` work but later indefinitely throws a mentioned error):
```lua
local my_expand = function(snippet)
  vim.snippet.expand(snippet)
  vim.schedule(function()
    pcall(vim.keymap.del, { 'i', 's' }, '<Tab>', { buffer = 0 })
    pcall(vim.keymap.del, { 'i', 's' }, '<S-Tab>', { buffer = 0 })
  end)
end
```

**Comment by mfussenegger** [comment] 2024-08-31 07:50
How about we setup the tab/s-tab snippet keymaps generally in `_defaults` instead of temporary during snippet expansion?

```lua
local function try_jump(direction, key)
  if vim.snippet.active({direction = direction}) then
    return string.format("<cmd>lua vim.snippet.jump(%d)<cr>", direction)
  end
  return key
end
vim.keymap.set({"i", "s"}, "<Tab>", function() return try_jump(1, "<Tab>") end, { expr = true })
vim.keymap.set({"i", "s"}, "<S-Tab>", function() return try_jump(-1, "<S-Tab>") end, { expr = true })
```

Then users can still override tab, and if they no longer define any keymap to jump between snippets that's their own fault

**Comment by echasnovski** [comment] 2024-08-31 07:56
> How about we setup the tab/s-tab snippet keymaps generally in `_defaults` instead of temporary during snippet expansion?

To me this sounds at least better than the current non-configurable approach. Allowing `opts` in `vim.snippet.expand()` feels cleaner but indeed introduces more configuration which might not be in the spirit of `vim.snippet`.

Probably it is also a good idea to document somewhere inside `:h vim.snippet` that `<Tab>` / `<S-Tab>` are used as default for jumping forward/backward

**Comment by clason** [comment] 2024-08-31 08:44
> How about we setup the tab/s-tab snippet keymaps generally in _defaults instead of temporary during snippet expansion?

But this will break users of other snippet (library) plugins. The current setup is chosen for a reason. 

I agree that lack of configuration is an issue we need to tackle, but what's still unclear is the "how". I disagree with Justin (as in the linked issue) wholeheartedly about the mode requirement; this wouldn't solve the issue here, either, since the problem (right now) involves distinguishing between LSP snippet context and generic snippet context (and others, e.g., completion). So unless we replace the current event-oriented structure with a plethora of modes (not just snippet but also completion etc.), this would not buy us anything.

So the big question right now is whether we can tackle this in a future-proof way without also deciding the strategy for other plugins to leverage the snippet infrastructure (which was a design goal, I recall, that we also punted on.) This will determine whether that should be configurable on the event/mode level or the LSP autocompletion level.

**Comment by mfussenegger** [comment] 2024-08-31 09:01
> But this will break users of other snippet (library) plugins

Only in that it would require some adaptation in the keymap. E.g. if you use luasnip you need a custom keymap anyway, and there you could check if `vim.snippet` is active, or if luasnip is active - or am I missing something?

Adding a `opts` with keymap configuration to `vim.snippet.expand` would afaik deviate from usual patterns - I don't think core uses that anywhere else yet?

And if snippet library plugins used `vim.snippet.expand` under the hood they'd also have to pass-through the options to expose it to users. Doesn't seem ideal to me

**Comment by echasnovski** [comment] 2024-08-31 09:08
> Adding a `opts` with keymap configuration to `vim.snippet.expand` would afaik deviate from usual patterns - I don't think core uses that anywhere else yet?

I also don't recall anything similar. But the reason might be that there is no functionality that implements "temporary mode". Snippets do.

> And if snippet library plugins used `vim.snippet.expand` under the hood they'd also have to pass-through the options to expose it to users. Doesn't seem ideal to me

I'd find this at least OK.

**Comment by clason** [comment] 2024-08-31 09:09
> Only in that it would require some adaptation in the keymap.

Yes, and all I'm saying is that this is something that should be considered when deciding the final shape of the API. (We added something minimal but working with the plan of deciding the "real" API after release; I'm saying we should take our time and do that properly instead of simply slapping another opt-in-or-out on it. Otherwise adding an option to `lsp.completion.enable` to skip setting up the default mapping seems the least work to scratch this particular itch.)

(It also has some implications to on-demand loading of -- potentially very heavy -- snippet engines, but I agree that that should not be a primary concern for core, even though it is very much a concern for me.)

> E.g. if you use luasnip you need a custom keymap anyway, and there you could check if vim.snippet is active, or if luasnip is active - or am I missing something?
> And if snippet library plugins used vim.snippet.expand under the hood they'd also have to pass-through the options to expose it to users. Doesn't seem ideal to me

Yes. That's why I'm saying that you can't really separate these questions and need to decide them together.

**Comment by echasnovski** [comment] 2024-08-31 10:00
> ... We added something minimal but working with the plan of deciding the "real" API after release ...

Just to clarify, after 0.11 release? I'd ask to resolve this sooner because the current non-configurable approach *does* break a lot of configs.

**Comment by justinmk** [comment] 2024-08-31 15:31
> I disagree about the mode requirement ... since the problem (right now) involves distinguishing between LSP snippet context and generic snippet context (and others, e.g., completion). So unless we replace the current event-oriented structure with a plethora of modes (not just snippet but also completion etc.), this would not buy us anything.

Maybe we don't need new modes but rather a "stack" of scopes, similar to `v:event.cmdlevel` in `CmdlineEnter`. So instead of `SnippetEnter`/`SnippetLeave`, introduce a `ModeEnter`/`ModeLeave` which increments a `level`. This would be a way for plugins to model arbitrary sub-modes.

**Comment by echasnovski** [comment] 2024-09-03 09:43
A note for possible future people who have `<Tab>` and `<S-Tab>` Insert mode mappings which conflict with this not configurable `vim.snippet.expand()` side effect. Until/if this is resolved, here is a monkey-patch solution which (at the time of writing this) works for `<Tab>` / `<S-Tab>` mappings from the [original post](https://github.com/neovim/neovim/issues/30198#issue-2497927721):

```lua
if vim.fn.has('nvim-0.11') == 1 then
  -- Ensure that forced and not configurable `<Tab>` and `<S-Tab>`
  -- buffer-local mappings don't override already present ones
  local expand_orig = vim.snippet.expand
  vim.snippet.expand = function(...)
    local tab_map = vim.fn.maparg('<Tab>', 'i', false, true)
    local stab_map = vim.fn.maparg('<S-Tab>', 'i', false, true)
    expand_orig(...)
    vim.schedule(function()
      tab_map.buffer, stab_map.buffer = 1, 1
      -- Override temporarily forced buffer-local mappings
      vim.fn.mapset('i', false, tab_map)
      vim.fn.mapset('i', false, stab_map)
    end)
  end
end
```

**Comment by mfussenegger** [comment] 2024-09-08 07:41
I wonder if it would be an option to get the popular snippet plugins to check for `vim.snippet.active` in their own equivalent functions, and use `vim.snippet.jump` if it is active instead of their own.
Then we could remap `tab`/`s-tab` globally by default. If users overrode it to use luasnip or similar it would continue working with lsp completion (or soon [snippet text edits](https://github.com/neovim/neovim/pull/30287)) if the plugins are aware of `vim.snippet`.


The `opts` parameter is imho not an option, because you've N callsites, often with some indirection (e.g. snippet text edit linked above is triggered via code-action).

That only leaves either the global keymap or the autocmd/custom mode as option as far as I can see(?)

**Comment by echasnovski** [comment] 2024-09-08 09:32
I still don't quite understand why there is a difference in decisions about making global mappings for LSP related features (`gr`, `<C-s>`) and making global mappings for snippets jumps. Both are relevant only under certain conditions. If user overrides it, it is their fault.

> That only leaves either the global keymap or the autocmd/custom mode as option as far as I can see(?)

Another approach that came to my mind recently was to add `vim.snippet.config()`, similar to `vim.diagnostic.config()`. As far as I can tell, the latter serves its purpose well, so can a `vim.snippet.config()`. This would avoid the "N callsites" problem because user can configure snippet behavior in one place to be effective for all other `vim.snippet.expand()` usages.

**Comment by clason** [comment] 2024-09-08 09:39
> I still don't quite understand why there is a difference in decisions about making global mappings for LSP related features (gr, <C-s>) and making global mappings for snippets jumps. 

The difference is the state of the API: LSP is a public, relatively stable, API; snippets are a black-box feature _without_ a public API -- that was intentionally deferred to later. My point is not that there should not be configurability; my point is that we should not forestall the API design discussion by adding individual "hot fixes" that will bite us later (as they so often have).

`vim.snippet.config` is one possible API design, but it needs to cover _all_ the possibilities we wish to support (a list we haven't even begun to collect yet). I don't see why now would not be a good time to have this general(!) discussion -- feel free to open an issue, and please tag the other snippet engine developers there.

**Comment by echasnovski** [comment] 2024-09-08 09:45
> `vim.snippet.config` is one possible API design, but it needs to cover _all_ the possibilities we wish to support

Not sure what it means. `vim.snippet.config(opts)` is a future compatible design which can be expanded without needing to have an extensive discussion about all possible config options to support. This can be separated into discussions:
- Whether or not `vim.snippet.config(opts)` is a good idea.
- *Separate* discussions on whether certain behavior being configured is a good idea.

**Comment by clason** [comment] 2024-09-08 09:48
> Separate discussions on whether certain behavior being configured is a good idea.

But that's not a discussion we need to have; nobody disagreed that this (mappings) is something that should be configurable. So the _only_ question is how, and that needs to tie in with _other_ things that should be configurable (which we don't have a full idea of yet -- and some of _those_ things might require something different from `vim.snippet.config`). So this also ties into the discussion how snippet plugins should be able to leverage `vim.snippet`, which has always been a part of the (long-term) design goal.

**Comment by mfussenegger** [comment] 2024-09-08 10:02
> Another approach that came to my mind recently was to add vim.snippet.config(), similar to vim.diagnostic.config(). As far as I can tell, the latter serves its purpose well, so can a vim.snippet.config(). This would avoid the "N callsites" problem because user can configure snippet behavior in one place to be effective for all other vim.snippet.expand() usages.

It crossed my mind too, but it goes a bit against the advise to avoid keymap DSLs which popped up in some Lua plugin guideline PRs.
So far we have either `vim.keymap.set` as default, or set due some action (`lsp.start`) and a way to override them again (`LspAttach`). I so far don't see compelling arguments that would require the introduction a third concept.

And one reason `vim.diagnostic.config` became a thing was the requirement to be able to configure namespaces separately. That wouldn't apply for `vim.snippet` as far as I can see(?)

> The difference is the state of the API: LSP is a public, relatively stable, API; snippets are a black-box feature without a public API -- that was intentionally deferred to later.

`vim.snippet.expand` is public. I thought what we deferred on was a `parse` (which implies making the AST public, and documenting/freezing it), and potentially something to format the AST. Or do I miss other use-cases?

---

So far my understanding is that we have to consider two use-cases here: Direct use of `vim.snippet.expand`, and indirect use via another mechanism (currently completion, soon LSP workspace edits triggered indirectly via something like code-actions), and of course any plugins making use of it. 
E.g I leverage it in [nvim-snippasta](https://github.com/mfussenegger/nvim-snippasta) 

 
To me it is still not clear if having made the keymaps ad-hoc on use justified the trouble with the customization. As far as I understand it only made co-use with other snippet plugins slightly easier in that it doesn't require users to update their keymaps. Or is there another aspect?
If there isn't, how about we change the mapping to be a always-on default, with a news.txt/breaking changes entry that includes a example to create a keymap that works for both vim.snippet and luasnip? (And given it is nightly/dev, we can still revisit depending on the feedback we get)

**Comment by clason** [comment] 2024-09-08 10:05
>  Or do I miss other use-cases?

Well, I was talking more about the API to be as minimal as possible for the current MVP -- this includes `lsp.completion.attach`, which I still consider the best place for scratching _this_ particular itch.

**Comment by echasnovski** [comment] 2024-09-08 10:12
> `vim.snippet.config` is one possible API design, but it needs to cover _all_ the possibilities we wish to support (a list we haven't even begun to collect yet). I don't see why now would not be a good time to have this general(!) discussion -- feel free to open an issue, and please tag the other snippet engine developers there.

#30306
