### ISSUE TITLE
Scroll wheel still scrolls after remapping

### ISSUE THREAD

**Issue by pianohacker** [neovim/neovim#6211] opened 2017-03-04 08:18 UTC
This blocks proper implementation of the alt-text of https://xkcd.com/1806/ (along with other, possibly more useful things).

- `nvim --version`:NVIM v0.2.0-752-gaf63f321
- Works correctly in Vim 8.0.197
- OS: Debian sid (unstable)
- Terminal name/version: urxvt-256color v9.22
- `$TERM`:rxvt-unicode-256color

After doing the following mappings:

    :noremap <ScrollWheelUp> u
    :noremap <ScrollWheelDown> ^R

### Actual behaviour

When scrolling, the window scrolls and the undo/redo is performed.

### Expected behaviour

Only the undo/remove is performed.

**Comment by justinmk** [comment] 2017-03-04 10:31
Depends on 'mouse' setting

**Comment by pianohacker** [comment] 2017-03-04 21:40
In what way? If the mouse is not turned on in normal mode (`set mouse=ivc` or `set mouse=`), then the mouse wheel doesn't scroll Neovim, but the mouse events aren't passed to Neovim at all. Either the terminal scrolls (if possible), or Neovim just doesn't get the events.

**Comment by justinmk** [comment] 2017-03-05 09:18
I see now you're saying it works, but also scrolls. Can you try a different terminal, e.g. xterm?

**Comment by pianohacker** [comment] 2017-03-07 02:26
When scrolling, after the above mappings and `set mouse=ivc` (or `set mouse=`):

* urxvt: the terminal scrolls (through the scrollback)
* xterm: nothing happens

**Comment by lheckemann** [comment] 2018-02-16 12:56
Still occurs in 0.2.2 and current master (09b51bbf87b16af9a186cea750ada748d89aa259). Vanilla vim behaves as expected. 

<details>
<summary>tested 0.2.2 version info</summary>

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /nix/store/nj7mw0lyx80g7lrxcxy5v9vmnpif5950-gcc-wrapper-6.4.0/bin/gcc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/source/build/config -I/build/source/src -I/nix/store/9qddqr79hv7ykyrb64j4481jni02yhbb-libuv-1.19.1/include -I/nix/store/s53aj0lq3j98bg6pc7qz1a4s76my55ab-libmsgpack-2.1.5/include -I/nix/store/4qh0qqlnzbc528g0wkwbh85sn3qcn941-unibilium-2.0.0/include -I/nix/store/0yfnw4yal81yw7v9slrgcfd627yyjqj9-libtermkey-0.19/include -I/nix/store/d0y9rvqz6kz6fnkzbiir4bs8flghkcb8-neovim-libvterm-2017-11-05/include -I/nix/store/q7nmpfhsg23pvibpcyac0lbnnhc80pm3-jemalloc-5.0.1/include -I/nix/store/apr1rfqacnmd7yqawqf1lv9dnnaalyqp-glibc-2.26-131-dev/include -I/build/source/build/src/nvim/auto -I/build/source/build/include
Compiled by nixbld

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/845wvvzp9n3mkc3hb2s18918g16h7jf2-neovim-unwrapped-0.2.2/share/nvim"
```
</details>

<details>
<summary>tested master version info</summary>

```
NVIM v0.2.3-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /nix/store/nj7mw0lyx80g7lrxcxy5v9vmnpif5950-gcc-wrapper-6.4.0/bin/gcc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/source/build/config -I/build/source/src -I/nix/store/9qddqr79hv7ykyrb64j4481jni02yhbb-libuv-1.19.1/include -I/nix/store/s53aj0lq3j98bg6pc7qz1a4s76my55ab-libmsgpack-2.1.5/include -I/nix/store/4qh0qqlnzbc528g0wkwbh85sn3qcn941-unibilium-2.0.0/include -I/nix/store/0yfnw4yal81yw7v9slrgcfd627yyjqj9-libtermkey-0.19/include -I/nix/store/d0y9rvqz6kz6fnkzbiir4bs8flghkcb8-neovim-libvterm-2017-11-05/include -I/nix/store/q7nmpfhsg23pvibpcyac0lbnnhc80pm3-jemalloc-5.0.1/include -I/nix/store/apr1rfqacnmd7yqawqf1lv9dnnaalyqp-glibc-2.26-131-dev/include -I/build/source/build/src/nvim/auto -I/build/source/build/include
Compiled by nixbld

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/x6g00bmbd9cym7vi0ss5sl0c1ham603f-neovim-unwrapped-0.2.3/share/nvim"
```
</details>
<details><summary>vim version info</summary>

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  1 1970 00:00:01)
Included patches: 1-1257
Compiled by nixbld
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     +gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
-clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        -perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "
/nix/store/mk9x723wg3zwzq627afxlzzryj60kfmn-vim-8.0.1257/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -ldl     
```</details>

**Comment by ndrewtl** [comment] 2018-05-17 08:03
Any reason why this issue was closed? I'm on 0.2.2 and still experiencing this. Would like to reopen if possible.

**Comment by ndrewtl** [comment] 2018-05-17 08:04
Any progress on this?

**Comment by dylan-chong** [comment] 2018-09-01 05:46
This still happens on the latest 0.3.1 release. I can confirm this happens inside and outside of Tmux, whereas the vanilla vim works properly

**Comment by justinmk** [comment] 2018-09-01 09:12
That's why this issue is still open. And it can be closed as soon as someone spends the time to work on it. So far that person hasn't materialized.

**Comment by laggardkernel** [comment] 2019-02-23 08:22
The problem still exists in NVIM v0.3.1 with `set mouse=a`. While the same mappings works well on classic VIM.

**Comment by hlpr98** [comment] 2019-03-06 05:49
The reason for this is,

The ScroolWheelUp input from the mouse is treated as `<Up>` and The ScrollWheelDown input from the mouse is treated as `<Down>`. Similar behaviour is seen for other mouse inputs too.

The proper expected behaviour can be observed upon
```
:noremap <Up> u
:noremap <Down> ^R
```
I'll try and correct this problem.

I would like to claim this issue

**Comment by hlpr98** [comment] 2019-03-10 11:06
This is a problem which is terminal specific. For instance, I'm running `Gnome-terminal` and I can reproduce this problem, because for some reason, in the new "screen" which runs in the terminal, the mouse scroll inputs are interpreted as Up/Down arrow keys. 

A similar problem has been discussed in 
https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1688528
https://bugs.launchpad.net/ubuntu/+source/screen/+bug/106995

And I'm pretty sure by now that this is not a bug or problem due to NVIM.

**Comment by b-r-o-c-k** [comment] 2019-03-14 21:49
The double, triple, and quadruple scroll wheel events need to be mapped in order to make it work:
```
:noremap <ScrollWheelUp>     u
:noremap <2-ScrollWheelUp>   u
:noremap <3-ScrollWheelUp>   u
:noremap <4-ScrollWheelUp>   u
:noremap <ScrollWheelDown>   ^R
:noremap <2-ScrollWheelDown> ^R
:noremap <3-ScrollWheelDown> ^R
:noremap <4-ScrollWheelDown> ^R
```
I don't know if this is intentional. If not, `check_multiclick()` in `os/input.c` looks like the right function to fix.

**Comment by publik-void** [comment] 2019-03-16 19:36
> The reason for this is,
> 
> The ScroolWheelUp input from the mouse is treated as `<Up>` and The ScrollWheelDown input from the mouse is treated as `<Down>`. Similar behaviour is seen for other mouse inputs too.

I'm pretty sure it's not related to this. Try `set mouse=a` and `map <up> <nop>`, `map <down> <nop>`, so that you can be sure the arrow keys shouldn't do anything and mouse mode is enabled. Then try to reproduce the original issue. You can even do the following:

```
map <ScrollWheelup> <nop>
map <s-ScrollWheelup> <nop>
map <c-ScrollWheelup> <nop>
map <ScrollWheeldown> <nop>
map <s-ScrollWheeldown> <nop>
map <c-ScrollWheeldown> <nop>
map <ScrollWheelleft> <nop>
map <s-ScrollWheelleft> <nop>
map <c-ScrollWheelleft> <nop>
map <ScrollWheelright> <nop>
map <s-ScrollWheelright> <nop>
map <c-ScrollWheelright> <nop>
```

The result that I get from this in iTerm2 and Konsole both with or without tmux is that Neovim will still scroll when using the mouse wheel, even though the arrow keys don't perform any action.

**Comment by publik-void** [comment] 2019-03-16 19:54
> The double, triple, and quadruple scroll wheel events need to be mapped in order to make it work:
> 
> ```
> :noremap <ScrollWheelUp>     u
> :noremap <2-ScrollWheelUp>   u
> :noremap <3-ScrollWheelUp>   u
> :noremap <4-ScrollWheelUp>   u
> :noremap <ScrollWheelDown>   ^R
> :noremap <2-ScrollWheelDown> ^R
> :noremap <3-ScrollWheelDown> ^R
> :noremap <4-ScrollWheelDown> ^R
> ```
> I don't know if this is intentional. If not, `check_multiclick()` in `os/input.c` looks like the right function to fix.

I can confirm this. Doing

```
map <ScrollWheelUp> <c-y>
map <s-ScrollWheelUp> <c-y>
map <c-ScrollWheelUp> <c-y>
map <ScrollWheelDown> <c-e>
map <s-ScrollWheelDown> <c-e>
map <c-ScrollWheelDown> <c-e>
map <ScrollWheelLeft> <nop>
map <s-ScrollWheelLeft> <nop>
map <c-ScrollWheelLeft> <nop>
map <ScrollWheelRight> <nop>
map <s-ScrollWheelRight> <nop>
map <c-ScrollWheelRight> <nop>
map <2-ScrollWheelUp> <c-y><c-y>
map <s-2-ScrollWheelUp> <c-y><c-y>
map <c-2-ScrollWheelUp> <c-y><c-y>
map <2-ScrollWheelDown> <c-e><c-e>
map <s-2-ScrollWheelDown> <c-e><c-e>
map <c-2-ScrollWheelDown> <c-e><c-e>
map <2-ScrollWheelLeft> <nop>
map <s-2-ScrollWheelLeft> <nop>
map <c-2-ScrollWheelLeft> <nop>
map <2-ScrollWheelRight> <nop>
map <s-2-ScrollWheelRight> <nop>
map <c-2-ScrollWheelRight> <nop>
map <3-ScrollWheelUp> <c-y><c-y><c-y>
map <s-3-ScrollWheelUp> <c-y><c-y><c-y>
map <c-3-ScrollWheelUp> <c-y><c-y><c-y>
map <3-ScrollWheelDown> <c-e><c-e><c-e>
map <s-3-ScrollWheelDown> <c-e><c-e><c-e>
map <c-3-ScrollWheelDown> <c-e><c-e><c-e>
map <3-ScrollWheelLeft> <nop>
map <s-3-ScrollWheelLeft> <nop>
map <c-3-ScrollWheelLeft> <nop>
map <3-ScrollWheelRight> <nop>
map <s-3-ScrollWheelRight> <nop>
map <c-3-ScrollWheelRight> <nop>
map <4-ScrollWheelUp> <c-y><c-y><c-y><c-y>
map <s-4-ScrollWheelUp> <c-y><c-y><c-y><c-y>
map <c-4-ScrollWheelUp> <c-y><c-y><c-y><c-y>
map <4-ScrollWheelDown> <c-e><c-e><c-e><c-e>
map <s-4-ScrollWheelDown> <c-e><c-e><c-e><c-e>
map <c-4-ScrollWheelDown> <c-e><c-e><c-e><c-e>
map <4-ScrollWheelLeft> <nop>
map <s-4-ScrollWheelLeft> <nop>
map <c-4-ScrollWheelLeft> <nop>
map <4-ScrollWheelRight> <nop>
map <s-4-ScrollWheelRight> <nop>
map <c-4-ScrollWheelRight> <nop>
```

"fixes" scrolling, although the inertia feels a bit jerky.

**Comment by hlpr98** [comment] 2019-03-16 22:37
Thankyou @publik-void and @b-r-o-c-k for your feedback. I will look into this issue again.

And nothing other than "ScrollWheelRight", "ScrollWheelLeft", "ScrollWheelUp" and "ScrollWheelDown" is a valid key_name as per `src/nvim/keymap.c` so I'm not sure why or how all these arbitrary mapping really making any difference. I'll try to find that out.

**Comment by hlpr98** [comment] 2019-03-17 13:12
> > The reason for this is,
> > The ScroolWheelUp input from the mouse is treated as `<Up>` and The ScrollWheelDown input from the mouse is treated as `<Down>`. Similar behaviour is seen for other mouse inputs too.
> 
> I'm pretty sure it's not related to this. Try `set mouse=a` and `map <up> <nop>`, `map <down> <nop>`, so that you can be sure the arrow keys shouldn't do anything and mouse mode is enabled. Then try to reproduce the original issue. You can even do the following:
> 
> ```
> map <ScrollWheelup> <nop>
> map <s-ScrollWheelup> <nop>
> map <c-ScrollWheelup> <nop>
> map <ScrollWheeldown> <nop>
> map <s-ScrollWheeldown> <nop>
> map <c-ScrollWheeldown> <nop>
> map <ScrollWheelleft> <nop>
> map <s-ScrollWheelleft> <nop>
> map <c-ScrollWheelleft> <nop>
> map <ScrollWheelright> <nop>
> map <s-ScrollWheelright> <nop>
> map <c-ScrollWheelright> <nop>
> ```
> The result that I get from this in iTerm2 and Konsole both with or without tmux is that Neovim will still scroll when using the mouse wheel, even though the arrow keys don't perform any action. Wether I enable or disable the setting `Scroll wheel sends arrow keys when in alternate screen mode.` in iTerm2 doesn't affect the outcome either.

@publik-void were you getting this issue even after after you toggled `Scroll wheel sends arrow keys when in alternate screen mode` to `no` and restarting the iTerm2 ??

**Comment by publik-void** [comment] 2019-03-17 19:07
> @publik-void were you getting this issue even after after you toggled `Scroll wheel sends arrow keys when in alternate screen mode` to `no` and restarting the iTerm2 ??
> 
> And also please tell about about the behaviour of Vim in the same situation

Yes, after configuring Neovim the way I mentioned, setting `Scroll wheel sends arrow keys when in alternate screen mode.` to `No` and subsequently restarting iTerm2, Neovim still scrolls in response to the mouse wheel or trackpad. Vim in the same situation does not.

**Comment by hlpr98** [comment] 2019-03-17 20:56
> > @publik-void were you getting this issue even after after you toggled `Scroll wheel sends arrow keys when in alternate screen mode` to `no` and restarting the iTerm2 ??
> > And also please tell about about the behaviour of Vim in the same situation
> 
> Yes, after configuring Neovim the way I mentioned, setting `Scroll wheel sends arrow keys when in alternate screen mode.` to `No` and subsequently restarting iTerm2, Neovim still scrolls in response to the mouse wheel or trackpad. Vim in the same situation does not.

@publik-void Try doing the following:
1. open NVIM to edit a file
2. `:set mouse=a`
3. `:noremap <ScrollWheelUp> u`
4. scroll the mouse wheel up (it should cause undo)

for nvim, only `ScrollWheelUp`, `ScrollWheelDown`, `ScrollWheelLeft` and `ScrollWheelRight` are defined key_names (as per `src/nvim/keymap.c`) hence all the other mapings you have given should not really cause any difference. 

use `:noremap` instead `:map` because `:map` lets recursive search for functionality of an input.

**Comment by publik-void** [comment] 2019-03-18 02:23
> for nvim, only `ScrollWheelUp`, `ScrollWheelDown`, `ScrollWheelLeft` and `ScrollWheelRight` are defined key_names (as per `src/nvim/keymap.c`) hence all the other mapings you have given should not really cause any difference.

But they do, as @b-r-o-c-k and I both mentioned. You can try it out for yourself. The mappings in my previous comment which use shift and control obviously aren't necessary for testing this and they might not even exist, I just use them in my `init.vim` to be sure I get the same behavior regardless of whether I have any modifier keys pressed or not.

> use :noremap instead :map because :map lets recursive search for functionality of an input.

Again, this should not make any difference for testing the behavior we're talking about.

> The reason I'm so confident that this issue is not a bug in NVIM and rather is terminal specific is because, the above steps of action helped to resolve the issue in Gnome-Terminal, Powershell and xTerm (with extremely basic config) that I use. The reason for my confidence is because I have degubbed extensively using GDB (which confirmed that the input that NVIM received was not <ScrollWheelUp> but rather <Up>), and the nvim_input() API (which confirms that mapping is actually registered).

You're using terminal emulators that translate mouse wheel events to arrow keys. Unless I got this all completely wrong, this issue is about making mouse wheel events work properly **using Neovim's mouse mode** and using terminal emulators that **do not send arrow key events** in response to mouse wheel events.
If your terminal emulator sends `<Up>` and `<Down>` when you turn the mouse wheel you can easily use those to scroll, yes. And you can easily disable scrolling. But there may be various reasons why one might not want to (or be able to) have the terminal emulator send arrow keys using the mouse. In that case you need to use the mouse mode in vim. You can enable it by setting `mouse=a`. This should (probably) be considered the "proper" way to enable scrolling anyway.

So to reiterate, the issue here is that Neovim does not disable mouse scrolling when mapping the `<ScrollWheelUp>` and `<ScrollWheelUp>` key_names to something else than buffer scrolling. However, it *does* disable the scrolling when the double, triple, and quadruple scrolling key_names are mapped to something else too. So now the question is:
* Is this the intended behavior?
* If it is, are there good reasons to keep it this way? Can we perhaps improve the documentation to more obviously mention the `<2-ScrollWheelUp>` etc. events?
* If it is not, how to change it?

**Comment by qstrahl** [comment] 2019-09-05 20:32
> So to reiterate, the issue here is that Neovim does not disable mouse scrolling when mapping the <ScrollWheelUp> and <ScrollWheelUp> key_names to something else than buffer scrolling.

It's not really an issue of Neovim "disabling" scrolling. The default behaviour for these keys is magical, and if you map over them, as you've observed, you don't get the default behaviour. The only real issue is the confusion caused by the fact that mapping `<ScrollWheelUp>` does not at all influence the behaviour of '<2-ScrollWheelUp>` and so on.

> Is this the intended behavior?

Yes.

> If it is, are there good reasons to keep it this way?

Yes; it gives users more options, taking nothing away.

> Can we perhaps improve the documentation to more obviously mention the `<2-ScrollWheelUp>` etc. events?

That would be great. The documentation is definitely confusing and a bit misleading. Somewhat related: #10954

**Comment by justinmk** [comment] 2019-09-05 21:13
Can someone send a doc update? It needs to be written by one of you who groks this :)

**Comment by qstrahl** [comment] 2019-09-05 23:18
The first step would be to determine under what conditions the numbered `ScrollWheel` events occur. I think it's safe to assume they definitely don't occur in those terminals which send `<Down>` and `<Up>` instead. Apart from that, does the terminal play a role in making that happen, or does Neovim construct those variants all on its own whenever it sees scroll events close together?

**Comment by b-r-o-c-k** [comment] 2019-09-06 02:10
The numbered mouse events occur when multiple mouse inputs are received within the time duration specified by the `mousetime` option.  The docs say that the option only controls click events, but it also applies to scroll events and possibly others.

**Comment by m3at** [comment] 2019-10-02 05:40
So to answer the original question and summarize previous commands, scrolling through time (undo/redo) while disabling the scrolling through space can be done with:
```
set mousetime=1
noremap <ScrollWheelUp> u
noremap <ScrollWheelDown> <C-R>
noremap <2-ScrollWheelUp> <Nop>
noremap <3-ScrollWheelUp> <Nop>
noremap <4-ScrollWheelUp> <Nop>
noremap <2-ScrollWheelDown> <Nop>
noremap <3-ScrollWheelDown> <Nop>
noremap <4-ScrollWheelDown> <Nop>
```

The documentation is unclear but there is no bug, and it's not neovim-specific. I feel like we can close this issue as the original problem is resolved.
Next step would be to improve upstream's doc

**Comment by ollpu** [comment] 2020-07-15 22:06
@m3at The `<n-ScrollWheelX>` maps don't seem to do anything in upstream VIM (if that's what you meant). Maybe the behavior has changed at some point.

I think this could be made a lot more usable by introducing `<1-ScrollWheelX>`, and these numbered versions would do whatever `<ScrollWheelX>` does unless specifically overridden.
This way, for a normal use-case, you could just rebind `<ScrollWheelX>` and have it work like expected.
This wouldn't even break current configurations that set the numbered versions, because `<1-ScrollWheelX>` would just cause `<ScrollWheelX>`, which is what would be configured currently.

**Comment by kuuote** [comment] 2022-02-27 07:50
I had troubled unexpected behavior of scroll wheel mapping and solved by comment of this issue. (https://github.com/neovim/neovim/issues/6211#issuecomment-473078631)
Is it simply undocumented it?  or has other problems?

**Comment by zeertzjq** [comment] 2022-03-02 04:40
The current implementation dates back to <https://github.com/neovim/neovim/commit/e0e41b30c61922e099a067ac5c137e745699a1aa>, and the old implementation was removed in <https://github.com/neovim/neovim/commit/e0e41b30c61922e099a067ac5c137e745699a1aa>. I cannot find a mention about the current behavior being intended.

**Closed** 2022-04-02 10:47 UTC
Labels: bug, input, complexity:low, status:has-workaround, mouse
