### ISSUE TITLE
API: Visual mode entered/left/changed autocmd

### ISSUE THREAD

**Issue by asvetliakov** [neovim/neovim#11590] opened 2019-12-21 22:52 UTC
I'd be good if neovim will provide `VisualEnter`/`VisualLeave`/`VisualChange` (although i'm only interested in enter/change events for now) autocmd events. I'm not sure though should i create feature request here or in original vim

**Comment by justinmk** [comment] 2019-12-22 03:36
Definitely would like this, though it requires some delicate choices to avoid spam.

Duplicate of https://github.com/neovim/neovim/issues/4399

**Closed by justinmk** 2019-12-22 03:36 UTC
Labels: enhancement

**Comment by theol0403** [comment] 2022-08-04 16:45
Could this please be re-opened?

While https://github.com/neovim/neovim/issues/4399 has been closed because `ModeChanged` was added, we still don't have `VisualChange`. 

This is crucial for vscode-neovim, because for nvim visual selections to be synced with vscode, we need to know the start/end range of the visual selection without hacks.

https://github.com/vscode-neovim/vscode-neovim/issues/172
https://github.com/vscode-neovim/vscode-neovim/issues/778

Currently, the only possible available API is to parse the Visual highlight group sent by nvim. However, this does not work for text outside of the neovim viewport, resulting in incorrect visual selections. 

I could also create a new issue specifically for `VisualChange`.

**Comment by clason** [comment] 2022-08-04 17:25
Can you explain more precisely what is missing from `ModeChanged`?

**Comment by clason** [comment] 2022-08-04 20:34
I think a new issue with a detailed description of the desired events would be good then.

(But do look through other issues whether some of them wouldn't do the job for you, say, a `vim.visual_selection` Lua API.)

**Comment by theol0403** [comment] 2022-08-04 22:24
Thanks, will do soon. 

A visual selection api would be useful to get the visual selection, but I can already do that with `getpos('v')`. What I need is an event that notifies when the visual selection changes.
