### ISSUE TITLE
In the old version of glibc and O2 is enabled, replacing the strncmp argument with a macro will cause the compilation to fail

### ISSUE THREAD

**Issue by hardboydu** [neovim/neovim#29291] opened 2024-06-12 02:24 UTC
### Problem

```
neovim-nightly/src/nvim/autocmd.c:1248:43: error: macro "strncmp" requires 3 arguments, but only 2 given
 1248 |   if (strncmp(*argp, S_LEN("<nomodeline>")) == 0) {
      |                                           ^
In file included from /usr/include/string.h:633,
                 from neovim-nightly/src/nvim/autocmd.c:8:
/usr/include/bits/string2.h:919: note: macro "strncmp" defined here
  919 | # define strncmp(s1, s2, n)                                                   \
      |
neovim-nightly/src/nvim/autocmd.c:2362:54: error: macro "strncmp" requires 3 arguments, but only 2 given
 2362 |   return patlen >= 8 && strncmp(pat, S_LEN("<buffer")) == 0 && (pat)[patlen - 1] == '>';
      |                                                      ^
/usr/include/bits/string2.h:919: note: macro "strncmp" defined here
  919 | # define strncmp(s1, s2, n)                                                   \
      |
make[2]: *** [src/nvim/auto/autocmd.c.generated.h] Error 1
```

### Steps to reproduce
```
cmake ../neovim-nightly \
		-DCMAKE_INSTALL_PREFIX=/opt/neovim \
		-DCMAKE_BUILD_TYPE=Release
```

### Expected behavior

Compilation succeeded

### Neovim version (nvim -v)

commit 66a1e028e6edfc26e9546f1c68f3e4bdf159511e

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

CentOS 7.9

### Terminal name/version

windows terminal

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by dundargoc** [comment] 2024-06-12 09:42
Which version of glibc are you using?

**Comment by hardboydu** [comment] 2024-06-12 10:11
> Which version of glibc are you using?

GNU C Library (GNU libc) stable release version 2.17

**Comment by dundargoc** [comment] 2024-06-12 11:28
Maybe the minimum glibc version has been increased. That would in that case be a documentation issue. I'll need to check.

**Comment by hardboydu** [comment] 2024-06-13 00:20
> Maybe the minimum glibc version has been increased. That would in that case be a documentation issue and this would be a wontfix. I'll need to check.
> 
> TODO: if this turns out to be the case, look into adding a minimum glibc check in build.yml if it's simple to do so.

CentOS 7.x is so widely used as a production system that I don't think it's time to give up on supporting it

**Comment by clason** [comment] 2024-06-13 08:07
> CentOS 7.x is so widely used as a production system that I don't think it's time to give up on supporting it

So is Neovim 0.9. If you run a legacy version of an OS, you should expect to have to run legacy versions of applications as well. We don't drop support at a whim; we try to keep things running on as many platforms as possible. But at the same time, we will _not_ refrain from making necessary or useful changes just for the sake of legacy platforms. (Again, you can keep using older versions; it's not like they are removed from the internet...)

In this specific case, we are talking about a nightly build for a version that will be released in months -- long after CentOS 7's end of life (June 30, 2024).

**Comment by dundargoc** [comment] 2024-06-13 11:13
This discussion is premature. I have no idea yet if the problem is in fact that minimum glibc has been increased. I probably shouldn't have brought up the possibility of "wontfix" before confirming it.

@hardboydu can you bisect the commit where building breaks for you? `make distclean` may help here in case the build breaks for unrelated reasons.

**Comment by moonstruckmoth** [comment] 2024-06-13 11:24
I'm facing the same issue and I've tracked down the commit from where it started failing to compile.

The commit is as below

commit c37695a5d5f2e8914fff86f3581bed70b4c85d3c (HEAD)
Author: James <89495599+IAKOBVS@users.noreply.github.com>
Date:   Tue Jun 11 22:40:24 2024 +0700

    refactor: use S_LEN(s) instead of s, n (#29219)

**Comment by dundargoc** [comment] 2024-06-13 11:37
@IAKOBVS

**Comment by IAKOBVS** [comment] 2024-06-13 11:47
> @IAKOBVS 

S_LEN macro doesn't work when passed as an argument to another macro. That's why I didn't use it for the STRICMP macros, only functions.

**Comment by clason** [comment] 2024-06-13 14:11
Yes, obviously. Can you fix this so it works on all supported platforms, or should we revert that commit?

**Comment by IAKOBVS** [comment] 2024-06-13 14:35
Just revert.

**Comment by IAKOBVS** [comment] 2024-06-13 14:35
> Yes, obviously. Can you fix this so it works on all supported platforms, or should we revert that commit?

Just revert it.

**Comment by gpanders** [comment] 2024-06-13 19:55
Is this something we can test for in CI? Otherwise how we will know if _any_ use of `S_LEN` is safe? (Unless we make a rule: "never use S_LEN in stdlib functions because those could secretly be macros").

**Comment by clason** [comment] 2024-06-13 19:59
Not without containers. (But I believe this sort of "macro wrappers for gcc" in glibc can be researched; It will take some effort, though.)

**Closed** 2024-06-13 21:20 UTC
Labels: bug, build, has:bisected

**Comment by dundargoc** [comment] 2024-06-14 12:19
> Is this something we can test for in CI? Otherwise how we will know if _any_ use of `S_LEN` is safe? (Unless we make a rule: "never use S_LEN in stdlib functions because those could secretly be macros").

I don't see how we could. Even if we start testing centos specifically it won't account for other distros. We could start testing a slew of popular distros (centos, debian, fedora, arch, manjaro, etc etc) but that is going to be expensive CI-wise.
