### ISSUE TITLE
Nvim not working also when i set up environment variables on windows

### ISSUE THREAD

**Issue by gGameDevelop** [neovim/neovim#30126] opened 2024-08-23 17:22 UTC
### Problem

After writing nvim on cmd it shows $qm and exit

### Steps to reproduce

nvim
nvim -u NONE
nvim --nopluggin

### Expected behavior

Opening nvim

### Neovim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

no, vim 9.000, vim works correctly without this issue

### Operating system/version

Windows 10 64bit

### Terminal name/version

CMD windows 1511

### $TERM environment variable

C:\Program Files\Neovim\bin

### Installation

MSI installer file, and the zip archive

**Comment by clason** [comment] 2024-08-23 17:30
Duplicate of #30125 

Please open duplicate issues. If you need help setting up Neovim, ask on Matrix.

**Closed by clason** 2024-08-23 17:30 UTC
Labels: bug

**Comment by gGameDevelop** [comment] 2024-08-23 19:55
Sorry. But please help me

**Comment by gGameDevelop** [comment] 2024-08-23 19:59
Or if you can, please tell me the correct steps to follow.

**Comment by gGameDevelop** [comment] 2024-08-24 17:33
Please, answer 🙏
