### ISSUE TITLE
Neovim segfaults when using Rg/fzf and probably vim-matchup

### ISSUE THREAD

**Issue by aerosol** [neovim/neovim#12596] opened 2020-07-04 22:59 UTC
- `nvim --version`:
```
NVIM v0.5.0-581-g267bc57d2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/hq1/.cache/yay/neovim-git/src/neovim-git/build/config -I/home/hq1/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/hq1/.cache/yay/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/hq1/.cache/yay/neovim-git/src/neovim-git/build/include
Compiled by hq1@carb

Features: +acl +iconv +tui
```
- `vim -u DEFAULTS` (version: ) behaves differently? - the plugins I'm using are neovim specfic, and this is clearly related to plugins
- Operating system/version: `Arch / Linux carb 5.7.6-arch1-1 #1 SMP PREEMPT Thu, 25 Jun 2020 00:14:47 +0000 x86_64 GNU/Linux`
- Terminal name/version: kitty 0.18.1 
- `$TERM`: `screen`

### Steps to reproduce using `nvim -u NORC`

N/A

### Actual behaviour

I cannot reproduce it reliably. Pieces of info that might be valuable:
  - happens every once in a while when using ripgrep fzf search window 
  - The command I'm using when segfault happens is https://github.com/aerosol/dotfiles/blob/develop/silos/nvim/.config/nvim/plugin/01-commands.vim#L1-L4 (it uses `bat` to generate previews)
  - Core dump: https://gist.github.com/aerosol/d9372194b510c986232172742b3dd653

### Expected behaviour

Neovim should not segfault.

**Comment by erw7** [comment] 2020-07-05 04:12
@aerosol Thanks for the reporte, but as far as the backtrace goes, this is a duplicate of #11548. So I'm closing this.

**Closed by erw7** 2020-07-05 04:12 UTC
Labels: +backtrace, bug, bug-crash

**Comment by aerosol** [comment] 2020-07-05 05:57
Awesome. Thank you @erw7
