### ISSUE TITLE
Wrong placement of nvim_buf_set_extmark() for vim help files

### ISSUE THREAD

**Issue by monkoose** [neovim/neovim#14860] opened 2021-06-19 14:04 UTC
- `nvim --version`: v0.5.0-dev+1403-g141647cfb
- Operating system/version: ArchLinux
- Terminal name/version: kitty
- `$TERM`: xterm-kitty

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:help getpos()
:set nowrap
:let hello = nvim_create_namespace('')
:call nvim_buf_set_extmark(0, hello, line('.') - 1, col('.') - 1, { 'virt_text': [[ "we are here", "Error" ]], 'virt_text_pos': 'overlay' })
8zl
```

### Actual behaviour
extmark shifted to left screen
![](https://i.imgur.com/PDfDx7D.png)

### Expected behaviour
stay on the position
![](https://i.imgur.com/JbFanJV.png)

**Comment by zeertzjq** [comment] 2023-05-24 08:25
Duplicate of #14050

**Closed by zeertzjq** 2023-05-24 08:25 UTC
Labels: bug, extmarks
