### ISSUE TITLE
some issues about + register

### ISSUE THREAD

**Issue by thinker3** [neovim/neovim#2217] opened 2015-03-21 23:27 UTC
I mapped ctrl-v to paste the content of + register

:reg not showing + register but the symbol |, even though it works as well in insert mode

but in command mode, I can not use ctrl-v to paste text from command-c

I have to paste once in insert mode, then I can paste in command mode

osx 10.10.2

**Comment by LeonB** [comment] 2015-03-30 12:06
I thnk this is a duplicate of #1860

**Comment by bfredl** [comment] 2015-03-30 12:17
#2244 might fix both issues.

**Comment by bfredl** [comment] 2015-04-01 13:52
Closed as duplicate of #1860 and #1908

**Closed by bfredl** 2015-04-01 13:52 UTC
