### ISSUE TITLE
Some Emoji mangles decorations by ASCII Escape Characters

### ISSUE THREAD

**Issue by kyoh86** [neovim/neovim#14436] opened 2021-04-25 09:24 UTC
`nvim --version`:
```
NVIM v0.5.0-dev+1231-g48e805728
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az36-521

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
yes.

- Operating system/version: Arch Linux
- Terminal name/version: GNOME terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Run `nvim -u NORC`.
2. Call `:terminal`.
3. Execute `echo $'\U1f589 \e[90m2000\e[0m'` in there
4. Execute `echo $'\U1f58a \e[90m2000\e[0m'` in there

### Actual behaviour

Ascii Escape Characters will be applied in wrong range.
`200` be colored gray, but `0` at tail is default color.

![image](https://user-images.githubusercontent.com/5582459/115987846-d38f0900-a5f1-11eb-8d3b-e168c775845a.png)

### Expected behaviour

`2000` is colored gray

as executed on GNOME terminal directly:
![image](https://user-images.githubusercontent.com/5582459/115988130-3c2ab580-a5f3-11eb-8ba3-f00d17d98596.png)

**Comment by plaxi0s** [comment] 2021-04-26 12:40
Can reproduce 
`nvim --version`:

    NVIM v0.5.0-dev+1280-gbb7d3790b
    Build type: RelWithDebInfo
    LuaJIT 2.1.0-beta3
    Compilation: /usr/local/bin/clang -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/revv/git/neovim/build/config -I/home/revv/git/neovim/src -I/home/revv/git/neovim/.deps/usr/include -I/usr/include -I/home/revv/git/neovim/build/src/nvim/auto -I/home/revv/git/neovim/build/include
    Compiled by revv@revv
    
    Features: +acl +iconv +tui
    See ":help feature-compile"
    
       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/local/share/nvim"
    
    Run :checkhealth for more info

**Comment by zeertzjq** [comment] 2022-01-17 04:08
Does this bug still exist?

**Comment by kyoh86** [comment] 2022-01-18 16:22
@zeertzjq yes.

![image](https://user-images.githubusercontent.com/5582459/149976860-95143249-97d0-4e10-be3f-eb348f93e943.png)

```
:version
NVIM v0.7.0-dev+nightly
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/tmp/tmp.EQyJU4f6C0/neovim/build/config -I/tmp/tmp.EQyJU4f6C0/neovim/src -I/tmp/tmp.EQyJU4f6C0/neovim/.deps/usr/include -I/usr/include -I/tmp/tmp.EQyJU4f6C0/neovim/build/src/nvim/auto -I/tmp/tmp.EQyJU4f6C0/neovim/build/include
Compiled by kyoh86

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by erw7** [comment] 2022-04-03 04:18
duplicate of #13036.

**Closed by erw7** 2022-04-03 04:18 UTC
Labels: bug, terminal
