### ISSUE TITLE
Support extensive loading of lua files in folders such as ftdetect, ftplugin, plugin, colors, autoload in addition to init.lua support

### ISSUE THREAD

**Issue by kutsan** [neovim/neovim#13469] opened 2020-12-06 19:24 UTC

**Comment by clason** [comment] 2020-12-07 08:19
Duplicate of https://github.com/neovim/neovim/issues/12670 ?

**Comment by bfredl** [comment] 2020-12-07 08:45
`autoload/` is not needed as `lua/` is already autoload for lua. Lets discuss the others in #12670.

**Closed by bfredl** 2020-12-07 08:45 UTC
Labels: enhancement, lua
