### ISSUE TITLE
`vim.o`/`vim.opt` attempt to index field o/opt (a nil value)

### ISSUE THREAD

**Issue by yzia2000** [neovim/neovim#14704] opened 2021-06-02 05:00 UTC
- `nvim --version`:
NVIM v0.5.0-dev+1372-g056c464e8
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/yushi/core/neovim/build/config -I/home/yushi/core/neovim/src -I/home/yushi/core/neovim/.deps/usr/include -I/usr/include -I/home/yushi/core/neovim/build/src/nvim/auto -I/home/yushi/core/neovim/build/include
Compiled by $USER

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

- Operating system/version: Linux 5.12.8-arch1-1 x86_64
- Terminal name/version: st-0.8.4
- `$TERM`: st-256color

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:lua print(vim.o.lines) # any vim.o.*
:lua print(vim.opt.lines) # any vim.opt.*
```

### Actual behaviour
attempt to index field o/opt (a nil value)

### Expected behaviour
show lines or output of the variable

I am sorry if this is duplicate. I tried to check. Its causing a lot of my plugins to break. Have I missed out on some option?

**Comment by clason** [comment] 2021-06-02 06:56
Duplicate of #14697

(Runtime file mismatch: You need to 1. regenerate the CMake cache files (`make cmake` or `make distclean`) before building and 2. install the updated runtime files (`make install` or adjusting the `VIMRUNTIME` environment variable.)

**Closed by clason** 2021-06-02 06:56 UTC
Labels: bug

**Comment by yzia2000** [comment] 2021-06-02 17:01
Thanks, the distclean worked!

**Comment by alvarotroya** [comment] 2021-07-10 22:24
Hi everyone! 

I am also facing this issue but unfortunately the proposed solution isn't working for me. 

I have tried all of the possible combinations below 
1. `make cmake` / `make distclean`
2. `make -j4` / `make CMAKE_BUILD_TYPE=Release`
3. `sudo make install`

The VIMRUNTIME variable is not set but running `nvim --cmd 'echo $VIMRUNTIME'` yields `/tmp/.mount_nvimhR0P5x/usr/share/nvim/runtime` and the cryptic part before `/usr/...` changes every time I close and open neovim. I am missing the directory `/usr/share/nvim` so there is definitely something wrong with the installation but I can't figure out what, specially since I have been following the steps in 'Building from source'.

Does anyone have any idea of what I am missing here?

**Comment by clason** [comment] 2021-07-10 22:27
You should ask such questions on Discourse or (better) Gitter rather than on old closed issues. (I suspect that you have a stale appimage lying around and aren't actually running the newly-built version.)

**Comment by alvarotroya** [comment] 2021-07-10 22:31
Thanks for the quick response, I just figured this out! You are right, for some reason, the default installation path was ~/.local/bin and ~/.local/share in my case, thanks for the hint about the Discord and Gitter, will keep that in mind for the next time! Hope the comment helps anyone with the same issue next time
