### ISSUE TITLE
tests: flaky: "TermClose event triggers when long-running terminal job gets stopped"

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10182] opened 2019-06-11 11:46 UTC
```
[----------] Running tests from /Users/travis/build/neovim/neovim/test/functional/autocmd/termclose_spec.lua
[ RUN      ] TermClose event triggers when long-running terminal job gets stopped: -- Output to stderr:
Vim: Caught deadly signal 'SIGHUP'
Vim: Finished.
CMake Error at /Users/travis/build/neovim/neovim/cmake/RunTests.cmake:56 (message):
  functional tests failed with error: 1
FAILED: CMakeFiles/functionaltest 
cd /Users/travis/build/neovim/neovim/build && /usr/local/Cellar/cmake/3.12.3/bin/cmake -DBUSTED_PRG=/Users/travis/nvim-deps/usr/bin/busted -DLUA_PRG=/Users/travis/nvim-deps/usr/bin/luajit -DNVIM_PRG=/Users/travis/build/neovim/neovim/build/bin/nvim -DWORKING_DIR=/Users/travis/build/neovim/neovim -DBUSTED_OUTPUT_TYPE=nvim -DTEST_DIR=/Users/travis/build/neovim/neovim/test -DBUILD_DIR=/Users/travis/build/neovim/neovim/build -DTEST_TYPE=functional -DSYSTEM_NAME=Darwin -P /Users/travis/build/neovim/neovim/cmake/RunTests.cmake
ninja: build stopped: subcommand failed.
```

https://travis-ci.org/neovim/neovim/jobs/543806289#L3113 (via https://github.com/neovim/neovim/pull/10163, worked when restarted / triggered a new build)

**Comment by justinmk** [comment] 2019-06-11 11:49
Known/old issue (though maybe not tracked in a ticket). Ignoring it until I get a chance to revisit the event loop / libuv details.

**Comment by justinmk** [comment] 2019-06-30 22:46
Related test:

```
[  ERROR   ] ...im/neovim/test/functional/autocmd/termclose_spec.lua @ 20: TermClose event triggers when fast-exiting terminal job stops
test/functional/helpers.lua:96: Vim(call):E900: Invalid channel id

stack traceback:
	test/functional/helpers.lua:96: in function 'request'
	test/functional/helpers.lua:254: in function 'command'
	...im/neovim/test/functional/autocmd/termclose_spec.lua:23: in function <...im/neovim/test/functional/autocmd/termclose_spec.lua:20>
```

**Comment by blueyed** [comment] 2019-07-24 02:07
What's interesting here is that there is no "Global test environment teardown", i.e. busted appears to get killed here maybe even?

The test is rather concise: https://github.com/neovim/neovim/blob/8fc93241d680f7c73e3013d679adb70c09cb3d57/test/functional/autocmd/termclose_spec.lua#L28-L34

It might be due to a problem in https://github.com/neovim/neovim/blob/8fc93241d680f7c73e3013d679adb70c09cb3d57/src/nvim/os/process.c#L89-L107.

@justinmk 
I remember you showing me a patch for this function - where is it?

(most recent build log: https://travis-ci.org/neovim/neovim/jobs/562822071#L2050)

**Comment by justinmk** [comment] 2019-07-24 10:06
> I remember you showing me a patch for this function - where is it?

https://github.com/neovim/neovim/issues/9704

**Comment by blueyed** [comment] 2019-08-14 16:50
Happened in https://travis-ci.org/neovim/neovim/jobs/571901939#L2042 (osx), with log now:
```
[----------] Running tests from test/functional/autocmd/termclose_spec.lua
[ RUN      ] TermClose event triggers when fast-exiting terminal job stops: 23.66 ms OK
[ RUN      ] TermClose event triggers when long-running terminal job gets stopped: -- Tests exited non-zero: SIGPIPE
-- Output to stderr:
Vim: Caught deadly signal 'SIGHUP'
Vim: Finished.
-- $NVIM_LOG_FILE: /Users/travis/build/neovim/neovim/build/.nvimlog
ERROR 2019-08-14T16:44:05.988 46077 loop_close:133: uv_loop_close() hang?
[--I] signal   0x107dc7218
[-AI] async    0x107dc6fc0
[R--] signal   0x107dc2060
CMake Error at /Users/travis/build/neovim/neovim/cmake/RunTests.cmake:85 (message):
  functional tests failed with error: SIGPIPE
```

**Comment by justinmk** [comment] 2019-08-14 16:59
We could change `loop_close` to exit 0 in CI, to avoid noise. It's a known issue and the key to solving it may be the discussion in https://github.com/neovim/neovim/issues/7376

**Comment by blueyed** [comment] 2019-09-25 10:22
One more data point from Travis (macos clang, https://travis-ci.org/neovim/neovim/jobs/589353802#L2103):
```
[ RUN      ] autocmd TermClose triggers when long-running terminal job gets stopped: -- Tests exited non-zero: SIGPIPE
-- Output to stderr:
Vim: Caught deadly signal 'SIGHUP'
Vim: Finished.
-- $NVIM_LOG_FILE: /Users/travis/build/neovim/neovim/build/.nvimlog
ERROR 2019-09-25T09:50:55.799 9881  loop_close:137: uv_loop_close() hang?
[--I] signal   0x10cbc6188
[-AI] async    0x10cbc5f30
[R--] signal   0x10cbc1100
```

**Comment by justinmk** [comment] 2020-02-19 04:39
> We could change `loop_close` to exit 0 in CI, to avoid noise. It's a known issue and the key to solving it may be the discussion in #7376

 https://github.com/neovim/neovim/pull/11887 doesn't really solve the root cause, but may avoid the non-zero exit. (To fix root cause, see comment in `loop_close` discussing `uv_walk`: we need to do a better job of closing all handles before closing loop)

**Comment by justinmk** [comment] 2020-02-20 01:43
https://travis-ci.org/neovim/neovim/jobs/652621733

**Comment by justinmk** [comment] 2022-07-04 12:37
Not observed in a long time, and potentially fixed by https://github.com/neovim/neovim/pull/19082 anyway.

**Closed by justinmk** 2022-07-04 12:37 UTC
Labels: test, terminal, event-loop
