### ISSUE TITLE
t_Co contains wrong value(255), for terms such as xterm, linux, or any other 8 color term

### ISSUE THREAD

**Issue by Ketrel** [neovim/neovim#11883] opened 2020-02-16 21:23 UTC
- `nvim --version`:
NVIM v0.5.0-275-g34a59242a

- `vim -u DEFAULTS` (version: ) behaves differently?  
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
Behaves differently in that it correctly reports 8 or 256 for t_o

- Operating system/version:  
KDE Neon

- Terminal name/version: 
- `$TERM`:
Have tried with the straight TTY on a multi-user login ($TERM name `linux`), xterm with $TERM name `xterm`, qterminal with $TERM `xterm`, all of the above with $TERM name `screen`

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```
Actually use, or set $TERM to a value that indicates 8 color support, such as `linux`, `xterm`, `screen`, etc.

Open Neovim, and `:echo &t_Co`

### Actual behaviour
Neovim echos: 256

### Expected behaviour
Neovim echos: 8

**Comment by justinmk** [comment] 2020-02-16 21:32
Most terminals, including linux vt console, support 256 colors these days, so this is not worth fixing.  


Duplicate of https://github.com/neovim/neovim/issues/5538

**Closed by justinmk** 2020-02-16 21:32 UTC
Labels: bug

**Comment by bfredl** [comment] 2020-02-16 21:39
> Actually use, or set $TERM to a value that indicates 8 color support, such as linux, xterm, screen, etc.

This does not indicate 8 color support. The actual number of colors is stored in the terminfo database which is looked up by the `$TERM` name. None of my terminals use the weird "-256color" prefix in `$TERM`.

**Comment by Ketrel** [comment] 2020-02-16 21:54
Neither Debian nor any of the Ubuntus support 256 colors in thr vtys.  Additionally in all the cases I mentioned above `tput colors` returns 8.

**Comment by Ketrel** [comment] 2020-02-16 21:58
Additionally, I see no indication that getty supports 256 colors in any version.

**Comment by justinmk** [comment] 2020-02-16 22:12
> Neither Debian nor any of the Ubuntus support 256 colors in their vtys.

"debian" and "ubuntu" are things that change with time, so the version is relevant, not to mention the kernel version...

**Comment by bfredl** [comment] 2020-02-16 22:26
`tput colors` seems unreliable, it returns "8" even in xterm with full truecolor support. 

How many colors kernel TTY:s can rendrer depends on the driver (VGA text mode vs framebuffer console etc), so the terminfo cannot be definite there.
