### ISSUE TITLE
`vim.cmd` fails to get marks inside `vim.keymap.set` callback

### ISSUE THREAD

**Issue by schardev** [neovim/neovim#27459] opened 2024-02-13 10:09 UTC
### Problem

Calling `vim.cmd` inside `vim.keymap.set` callback fails to get marks and hangs up neovim.

### Steps to reproduce

add a visual remap like the below:

```lua
-- apply macro to visual selection
vim.keymap.set("x", "@", function()
  vim.ui.input({ prompt = "Macro Register: " }, function(reg)
      vim.cmd([['<,'>normal @]] .. reg)
  end)
end, { silent = false })
```

record a macro and try to invoke it on a visual selection. On first attempt it'll error out with:

```
E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2(): Vim(normal):E20: Mark not set: '<,'>normal @q
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /home/saurabh/.config/nvim/lua/core/mappings.lua:118: in function </home/saurabh/.config/nvim/lua/core/mappings.lua:116>
```

on second attempt it'll hang up neovim

### Expected behavior

It should apply the macro to visual selection.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2331+g170c890dc

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux x86_64

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

wezterm 20240203-110809-5046fc22

### Installation

AUR and Pacman

**Comment by zeertzjq** [comment] 2024-02-13 10:14
Duplicate of #18340

**Comment by schardev** [comment] 2024-02-13 10:15
Do note that calling it from cmdline works as expected.

**Closed by zeertzjq** 2024-02-13 10:14 UTC
Labels: bug
