### ISSUE TITLE
FocusLost with xterm

### ISSUE THREAD

**Issue by glebtv** [neovim/neovim#2302] opened 2015-03-30 15:59 UTC
Previously (before #1820 as it seems), it was possible to get FocusLost/FocusGain behavior in xterm like this:

    if &term =~ "xterm.*"
      let &t_ti = &t_ti . "\e[?1004h"
      let &t_te = "\e[?1004l" . &t_te
      nnoremap <silent> <ESC>[O <ESC><ESC>:wall<cr>
      nnoremap <silent> <ESC>[I <ESC>
    endif

Is there some way to get behavior like this this now?

**Comment by glebtv** [comment] 2015-03-31 22:48
This codes seems to also be supported on iterm2
https://code.google.com/p/iterm2/issues/detail?id=1324

And there was a vim patch for this:
https://groups.google.com/forum/#!topic/vim_dev/ASn8QqQqVe0

I tried adding it to tui.c but I don't know enough C to do it properly (thus should be very easy, no?)

**Comment by houshuang** [comment] 2015-04-28 02:07
This would be incredibly useful. Rather than save, I want it to go to normal mode whenever I come back to Vim - I never remember which mode I was in, and often start issuing commands while in insert mode.

**Comment by glebtv** [comment] 2015-04-28 16:25
Saving was just my hack/example,
I think it should trigger FocusLost/FocusGained autocmd like it was in gui vim https://github.com/neovim/neovim/blob/9a363ca7a3174d8e278dee29bb8984909eeda693/runtime/doc/autocmd.txt#L678
so users can choose what they want to do

**Comment by houshuang** [comment] 2015-04-28 16:34
Oh absolutely, I didn't mean to imply anything about neovim default functionality - with FocusLost/Gained, users can do what they want.

**Comment by justinmk** [comment] 2015-04-28 16:41
The vim_dev link is useful, I definitely would like to see this.

**Comment by justinmk** [comment] 2015-08-17 06:34
Marking this as a bug since it actually is a regression from Vim:

https://github.com/tmux-plugins/vim-tmux-focus-events/issues/1

Also added to 0.2 milestone, shouldn't be difficult to include the vim_dev patch.

**Closed** 2015-11-18 12:43 UTC
Labels: bug, tui
