### ISSUE TITLE
hang with netrw or "set clipboard+=unnamedplus"

### ISSUE THREAD

**Issue by skywind3000** [neovim/neovim#6695] opened 2017-05-06 18:09 UTC
- `nvim --version`: NVIM v0.2.1-25-g2e3b78d1
- Vim (version: ) behaves differently? yes
- Operating system/version: Windows 7 64bits
- Terminal name/version: nvim-qt
- `$TERM`:

### Actual behaviour
NeoVim stuck for 10 seconds after ":q!" 

### Expected behaviour
exit immediately

### Steps to reproduce using `nvim -u NORC`
1. start nvim-qt on Windows
2. type: ":Ex" to open netrw
3. type: ":q!" to exit neovim

After ":q!", NeoVim's cpu usage exceeded 25% (100% of a single core), 
I noticed that NeoVim was trying to execute "win32yank.exe" repeatly at that time.

Here is the profiling detail:

```

FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   68   4.413280   0.327599  <SNR>23_NetrwBookHistSave()
   76   4.301969   0.001095  provider#clipboard#Call()
   72   4.199791   0.001516  2()
   71   4.198275             <SNR>24_try_cmd()
   70   4.100859             <SNR>23_NetrwOptionSave()
   69   4.087352   0.021727  <SNR>23_NetrwEnew()
    1   0.345549   0.182587  netrw#Explore()
    1   0.151548   0.000176  netrw#LocalBrowseCheck()
    1   0.151225   0.000751  <SNR>23_NetrwBrowse()
    4   0.101083             3()
    1   0.059860   0.001093  <SNR>23_PerformListing()
   71   0.045861   0.042259  <SNR>23_NetrwOptionRestore()
    1   0.027196   0.002741  <SNR>23_NetrwGetBuffer()
    1   0.024307   0.011506  <SNR>23_LocalListing()
   69   0.021558   0.010264  <SNR>23_NetrwHome()
  123   0.020575   0.009251  <SNR>23_NetrwFile()
  125   0.011653             <SNR>23_ComposePath()
    1   0.011128             provider#clipboard#Executable()
    2   0.005376   0.001861  <SNR>6_SynSet()
    1   0.004659   0.000404  <SNR>23_NetrwSafeOptions()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
   71              4.198275  <SNR>24_try_cmd()
   70              4.100859  <SNR>23_NetrwOptionSave()
   68   4.413280   0.327599  <SNR>23_NetrwBookHistSave()
    1   0.345549   0.182587  netrw#Explore()
    4              0.101083  3()
   71   0.045861   0.042259  <SNR>23_NetrwOptionRestore()
   69   4.087352   0.021727  <SNR>23_NetrwEnew()
  125              0.011653  <SNR>23_ComposePath()
    1   0.024307   0.011506  <SNR>23_LocalListing()
    1              0.011128  provider#clipboard#Executable()
   69   0.021558   0.010264  <SNR>23_NetrwHome()
  123   0.020575   0.009251  <SNR>23_NetrwFile()
    2   0.004263   0.003871  <SNR>23_NetrwGlob()
    1              0.002842  <SNR>23_NetrwSetSort()
    1   0.027196   0.002741  <SNR>23_NetrwGetBuffer()
   68              0.002685  GuiClose()
   75              0.002244  <SNR>23_NetrwInit()
    1   0.002128   0.002079  <SNR>23_NetrwMaps()
    2              0.001937  <SNR>3_LoadFTPlugin()
    2   0.005376   0.001861  <SNR>6_SynSet()
```

**Comment by justinmk** [comment] 2017-05-08 11:43
Easy to reproduce. You can get out of the "deadlock" with CTRL-C.

2e3b78d1 is before 34c3f03013375817d3d089e685793290eded553a so this isn't a regression by 
https://github.com/neovim/neovim/pull/6644#issuecomment-299215794.

Related change: c826ebd3de7f73d360a8032127ed9d9db0543d8a

**Comment by skywind3000** [comment] 2017-05-09 20:38
Thanks for the constantly bug fixing, NeoVim is becoming better on Windows now, I'd like to switch from GVim to nvim-qt sooner or later, because nvim-qt will NOT FLICKER while scrolling, it's cool.

**Comment by justinmk** [comment] 2017-08-22 19:16
This still happens after https://github.com/neovim/neovim/commit/85f3084e21e112a34d891d90cfaf37a7de726866 :frowning_face:

**Comment by partounian** [comment] 2017-08-28 23:39
There is a workaround tag/label, so what is the workaround for this issue?

**Comment by jamessan** [comment] 2017-08-29 14:57
> You can get out of the "deadlock" with CTRL-C.

You can also not use NetRW.  Try dirvish or NERDTree.

**Comment by nadya-p** [comment] 2018-05-02 14:55
CTRL-C workaround doesn't work for me.

**Comment by janlazo** [comment] 2018-05-05 16:10
Tested with nightly and `nvim-qt -- -u NORC`.

> type: ":Ex" to open netrw

clipboard: error invoking win32yank:

> type: ":q!" to exit neovim

CPU usage went up to around 17% (was still increasing).
Before it finally closed, I got spammed with `Press to continue` message until nvim.exe terminated.
If I do the same steps with my [vimrc](https://github.com/janlazo/dotvim8/blob/master/shared.vim) (which uses vim-dirvish), this doesn't happen. I didn't disable netrw in my vimrc. @justinmk Any ideas?

How does netrw invoke win32yank on neovim since the buffer is set to readonly?

**Comment by justinmk** [comment] 2018-05-05 16:28
@janlazo unless you have `:set clipboard=unnamed` I have no idea.

**Comment by nadya-p** [comment] 2018-07-18 07:46
The issue occurs as well with the default

    :set clipboard=

**Comment by nadya-p** [comment] 2018-07-18 07:55
Yet another workaround is to open Windows Explorer with focus on the current file using

      nnoremap <silent> <leader>e :execute<Space>'!explorer'<Space>'/select,'.expand('%:p')<CR>

I admit that netrw is much more powerful then NERDTree or Windows Explorer, so a real fix would be very useful.

**Comment by frangio** [comment] 2019-09-21 17:25
I am seeing this with the default `set clipboard=` too. It renders netrw unusable on Wayland with wl-copy/wl-paste.

Is there any indication as to what can be causing this?

**Comment by blueyed** [comment] 2019-09-21 20:04
@frangio 
Is this a regression for you from 0.3.x?  If so, can you git-bisect it, please?

**Comment by justinmk** [comment] 2019-09-21 20:29
@frangio this may be (partly) a wayland (wl-copy) bug, see https://github.com/neovim/neovim/issues/9806#issuecomment-480827573 and later comments which suggest that it can be fixed by "installing wl-copy from git" (they haven't done a release yet).

**Comment by justinmk** [comment] 2019-12-10 08:47
Maybe this is avoided by https://github.com/neovim/neovim/commit/6c22c7ab97cca9f8dda6863ee7f1db1ce30a3451 ?

**Comment by fmoralesc** [comment] 2019-12-19 23:36
From #11571: I seem to still have this issue with default `&clipboard` even after updating my version of wl-clipboard. Still not sure what is causing it.

**Comment by djsavvy** [comment] 2020-02-16 03:53
I was having the same problem, also referenced in [#9806](https://github.com/neovim/neovim/issues/9806 )

I discovered the following workaround (to be put in `nvim.init`): 
`
" Enable system clipboard integration
set clipboard+=unnamedplus
" Workaround for neovim wl-clipboard and netrw interaction hang 
" (see: https://github.com/neovim/neovim/issues/6695 and
" https://github.com/neovim/neovim/issues/9806) 
let g:clipboard = {
      \   'name': 'myClipboard',
      \   'copy': {
      \      '+': 'wl-copy',
      \      '*': 'wl-copy',
      \    },
      \   'paste': {
      \      '+': 'wl-paste -o',
      \      '*': 'wl-paste -o',
      \   },
      \   'cache_enabled': 0,
      \ }

`

**Comment by justinmk** [comment] 2020-02-16 05:09
## Resolution/Summary

- assuming this was fixed by https://github.com/neovim/neovim/commit/6c22c7ab97cca9f8dda6863ee7f1db1ce30a3451
- clipboard performance is  tracked in https://github.com/neovim/neovim/issues/11804
- wayland-related problems tracked in https://github.com/neovim/neovim/issues/9806 

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._

**Closed by justinmk** 2020-02-16 05:09 UTC
Labels: +workaround, bug, clipboard, job-control, platform:windows
