### ISSUE TITLE
screen: artifacts after scroll

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#8768] opened 2018-07-23 00:43 UTC
(This is most likely related to #8221. cc @bfredl )

- `nvim --version`: `v0.3.2-dev`
- Vim (version: ) behaves differently? Yes
- Operating system/version: macOS
- Terminal name/version: Terminal.app
- `$TERM`: screen-256color (terminfo from SSH'd ubuntu system)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC +'e README.md' +'vsplit' +'windo set cursorline' +'call feedkeys("\<PageDown>")'
:tab split
```

- The `:tab split` must be done manually, after the screen has done a draw/scroll.
- The `<PageDown>` is to provoke a scroll.

### Actual behaviour

The new tabpage shows artifacts from the previous tabpage.

### Expected behaviour

The new tabpage should show correctly.

**Comment by bfredl** [comment] 2018-07-23 08:57
Does it fail the same in xterm or libvterm (pangoterm, :term in stable nvim)?

AFK now but will investigate later today or tomorrow (but not on macos)

**Comment by bfredl** [comment] 2018-07-23 19:13
I can reproduce in python-gui, so seems to be screen.c bug

**Comment by bfredl** [comment] 2018-07-24 09:40
I think I found the issue. The inital version of the UI protocol (before there was any documentation, only python-gui and TUI reference implementations), had the intention to allow clearing only a subset of the screen by having "clear" be affected by the scrolling region. This was never used, and never specified in the documentation, but some clients and TUI code assume this. api/ui.c should be made compatible with these clients again, and TUI code should just be changed (as the new protocol doesn't have persistent regions, this code can just be deleted), I'l push a fix very soon.

**Comment by bfredl** [comment] 2018-07-24 09:45
Also a lot of usages of CLEAR should just be changed to NOT_VALID in window.c, for instance when switching tabs, as new grid_line event can easily clear the rest of an already changed line, unlike old put (which required dense transmission of cleared region).

**Comment by bfredl** [comment] 2018-07-24 11:14
#8771 might be fixing this now.

**Comment by Fetz** [comment] 2018-07-24 15:07
@bfredl I'm having similar issues when running neovim (using spacevim) in TMUX

**Comment by bfredl** [comment] 2018-07-24 15:46
@Fetz I just merged a change, please try latest master.

**Closed** 2018-07-24 15:46 UTC
Labels: bug-regression, design, discuss, display

**Comment by Fetz** [comment] 2018-07-25 09:00
Hi @bfredl, thanks a lot most of the issues that I was having neovim on tmux with scroll etc was fixed.

I have only small glitches char not rendering correctly in the powerline when moving it up and down, I will try to see if I can recreate it with `nvim -u NORC` and if yes I will create another issue.

Again thanks a lot
