### ISSUE TITLE
Concealed text should not wrap

### ISSUE THREAD

**Issue by w1475963** [neovim/neovim#30909] opened 2024-10-23 05:51 UTC
### Problem

Take concealed text into account when checking if a line should wrap or not.
Otherwise, some preview plug-ins (such as markdown tables) will display strange line breaks.

![Image](https://github.com/user-attachments/assets/37623a22-9953-4c36-9b7e-8908719273c6)

### Steps to reproduce

```vim
:set wrap
```

### Expected behavior

Concealed text should be ignored.
I set:
```vim
:set nowrap
```
than it looks like this.

![Image](https://github.com/user-attachments/assets/e2892070-5403-4642-b347-4f0ebae799ea)

### Nvim version (nvim -v)

NVIM v0.10.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos

### Terminal name/version

xterm

### $TERM environment variable

xterm-256color

### Installation

aur

**Comment by zeertzjq** [comment] 2024-10-23 06:19
Duplicate of #14409

**Closed by zeertzjq** 2024-10-23 06:19 UTC
Labels: bug
