### ISSUE TITLE
scheduled :redrawstatus in operator pending mode triggers mode change

### ISSUE THREAD

**Issue by MunifTanjim** [neovim/neovim#23284] opened 2023-04-23 09:53 UTC
### Problem

Calling `:redrawstatus` inside `vim.schedule` from `no` mode keeps changing the mode back and forth between `n` and `no`.

### Steps to reproduce

**repro.lua**

```lua
vim.o.statusline = "%{v:lua.vim.api.nvim_get_mode().mode}"

vim.api.nvim_create_autocmd("ModeChanged", {
  callback = function()
    vim.schedule(function()
      vim.cmd("redrawstatus")
    end)
  end,
})
```

```sh
nvim -u repro.lua
```

- Press `d` or `y` (to enter operator pending mode)
- Statusline keeps changing between `n` and `no`

### Expected behavior

Statusline should show `no`, should not change to `n`.

### Neovim version (nvim -v)

v0.9.0-dev-1095+gb0b4c3109-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.3.2

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by zeertzjq** [comment] 2023-04-23 09:58
Duplicate of #22263

**Closed by zeertzjq** 2023-04-23 09:58 UTC
Labels: bug
