### ISSUE TITLE
signcolumn: toggle alignment of signs

### ISSUE THREAD

**Issue by cohml** [neovim/neovim#31322] opened 2024-11-23 15:18 UTC
### Problem

By default, signs in the signcolumn appear to be left justified. In other words, the first sign shows up on the far left, with additional signs added to the right of that, up to the maximum allowed.

However, when the signcolumn is wide, this can lead to significant visual separation between the sign and the line numbers/text when there aren't many signs on a line. For example, considering the lonely `W` at the top left, notice the big space between it and the line number:

![Image](https://github.com/user-attachments/assets/ed2c00fe-f67d-42f9-a340-3447489f9d41)

### Expected behavior

It would be nice if this could be configured. For example, `signalign = "left" | "right"`, where `"left"` equals the current default behavior (left-alignment, new signs added to the right) and `"right"` would beget right-alignment with new signs added to the left.

**Comment by zeertzjq** [comment] 2024-11-23 23:10
Related #16632

**Comment by justinmk** [comment] 2024-11-24 15:49
Duplicate of https://github.com/neovim/neovim/issues/11212

**Comment by cohml** [comment] 2024-11-24 16:54
> Duplicate of https://github.com/neovim/neovim/issues/11212

Reviewing that thread, #11212 does not sound like a duplicate of this issue. It proposes something completely different and vastly grander in scope. From the thread:

> I would like to have a second signcolumn. This means there would be one on the left and one on the right.

That is not my proposal at all.

My proposal is simply to allow the order of signs in the (left) signcolumn to be flipped. That is, the first sign will be on the far right, with subsequent signs added to the left.

Can we reopen this?

**Comment by zeertzjq** [comment] 2024-11-24 22:54
Maybe this can already be achieved using `'statuscolumn'`?

**Comment by luukvbaal** [comment] 2024-11-24 23:04
Anything you can think of to put into `'statuscolumn'`, you can. So yes it's possible, but not as easy for the user as a builtin options obviously. 

IDK if the official stance for the project in regards to column customization is: use `'statuscolumn'`, yet.

**Comment by justinmk** [comment] 2024-11-25 11:42
Yes, anything that can be achieved with 'statuscolumn' is not something we're going to bake-into core.

**Comment by cohml** [comment] 2024-11-25 13:32
If what I'm proposing is already possible, that's the best-case scenario!

In that case, simply clarifying how to do it (I guess via the documentation) would be perfectly sufficient.

Sadly I won't be able to volunteer, but perhaps we could re-open this so that later someone else might?

**Closed** 2024-11-25 13:33 UTC
Labels: enhancement, column, closed:duplicate

**Comment by tinkerrring** [comment] 2025-11-27 22:00
(never committed to an open source project, so I hope this doesn't waste time of anyone reading this... )


I think the following does right-align the statuscolumn?

```
:set statuscolumn=%=%s
```
The first   %=   does the trick. As there is nothing before   %=   it means: Right-align the content that follows. 


If correct, should I try to add this as an example in the documentation here? 

[Link to statuscolumn in options.txt](https://github.com/neovim/neovim/blob/a6ea446c7e68b29d65b65a4dd086d12c615e22f9/runtime/doc/options.txt#L6253)

(Thank you for Neovim!)

**Comment by barrettruth** [comment] 2026-07-04 04:19
Sorry for the necropost (backlog be gone!) The above example is not sufficient for nvim 0.13+. Thoughts on this @luukvbaal? maybe an option? (maybe not...)

**Comment by luukvbaal** [comment] 2026-07-07 11:15
I don't think the situation has changed; `%=%s` works to right-align the sign column w.r.t. the rest of the statuscolumn content, but not the signs itself inside a partially filled sign segment (if its width > 1.). It's trivial to support that in a custom 'statuscolumn' sign function/plugin, but not really something that can be documented I think.

**Comment by barrettruth** [comment] 2026-07-07 17:10
I've created a right-aligned signcolumn script. It works by allocating space with signcolumn and rendering with statuscolumn. This is just one way to do it.

It looks like this:

<img width="861" height="527" alt="Image" src="https://github.com/user-attachments/assets/c1574768-3169-468e-beb9-688c994ee754" />

I'm going to close this for now since the workaround is fine and @luukvbaal seems ok with this approach also.

```
local function rsc()
  local res = vim.api.nvim_eval_statusline('%s', {
    winid = vim.g.statusline_winid,
    use_statuscol_lnum = vim.v.lnum,
    highlights = true,
  })
  local signs, hls = {}, res.highlights or {}
  local char, byte, hi = 0, 0, 1
  local chars = vim.fn.strchars(res.str)
  while char < chars do
    while hls[hi + 1] and hls[hi + 1].start <= byte do
      hi = hi + 1
    end
    local text, width = '', 0
    while char < chars and width < 2 do
      local ch = vim.fn.strcharpart(res.str, char, 1)
      text = text .. ch
      width = width + vim.fn.strdisplaywidth(ch)
      byte = byte + #ch
      char = char + 1
    end
    if text ~= '  ' then
      signs[#signs + 1] = { text, hls[hi] and hls[hi].group }
    end
  end
  local out = { '%#SignColumn#' .. ('  '):rep(math.max(res.width / 2 - #signs, 0)) }
  local group = 'SignColumn'
  for _, sign in ipairs(signs) do
    if sign[2] and sign[2] ~= group then
      out[#out + 1] = '%#' .. sign[2] .. '#'
      group = sign[2]
    end
    out[#out + 1] = sign[1]:gsub('%%', '%%%%')
  end
  return table.concat(out) .. '%*%=' .. (vim.v.virtnum == 0 and vim.v.lnum or '') .. ' '
end
_G.rsc = rsc
vim.o.signcolumn = 'yes:4'
vim.o.statuscolumn = '%!v:lua.rsc()'
```
