### ISSUE TITLE
0.6.1 breaks syntax highlighting in checkhealth buffer

### ISSUE THREAD

**Issue by PatrBal** [neovim/neovim#16867] opened 2022-01-01 13:45 UTC
### Neovim version (nvim -v)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no checkhealth in Vim

### Operating system/version

macOS 12.1

### Terminal name/version

iTerm2 Build 3.4.15

### $TERM environment variable

xterm-256color

### Installation

Compiled by brew@Monterey  Features: +acl +iconv +tui

### How to reproduce the issue

nvim --clean
:checkhealth

### Expected behavior

Syntax highlighing of the output of the command 
:checkhealth
The following snapshot is obtained with nvim 0.6.0

<img width="1677" alt="0 6 0" src="https://user-images.githubusercontent.com/44707588/147851949-0ebee51e-308d-4fcc-9e5c-f0b4a912746d.png">

### Actual behavior

No syntax highlighting of the output of the command
:checkhealth
in nvim 0.6.1

<img width="1677" alt="0 6 1" src="https://user-images.githubusercontent.com/44707588/147851986-ab5ea19f-317d-43bd-b2f9-0f26241bd37d.png">

**Comment by clason** [comment] 2022-01-01 13:48
The filetype for the `checkhealth` buffer has changed: https://github.com/neovim/neovim/pull/16708 

Make sure your colorscheme handles this appropriately.

**Comment by zeertzjq** [comment] 2022-01-01 13:59
OP isn't using any plugins.

**Comment by clason** [comment] 2022-01-01 14:02
I'd be surprised if that were the case ;)

This report uses `nvim --clean`,  where the behavior is expected. (The hardcoded color names were removed in favor of deriving from Markdown syntax highlighting, so this is particular report is not a bug.)

**Comment by zeertzjq** [comment] 2022-01-01 14:03
Oh wait...

**Comment by zeertzjq** [comment] 2022-01-01 14:14
Oh, one now needs to run `:syntax on` before running `:checkhealth` to have `:checkhealth` show colors with `nvim --clean`. It is not clear what the intended behavior should be.

**Comment by clason** [comment] 2022-01-01 14:17
Right now, the `checkhealth` behaves like any other filetype -- no syntax highlighting with `--clean`. That consistency strikes me as more useful than having some colors even with "factory defaults".

@gpanders

**Comment by gpanders** [comment] 2022-01-01 19:04
It's not really a bug then since the syntax isn't "broken", it's just that `--clean` doesn't enable syntax highlighting by default. I guess this could be considered a (minor) regression in that `--clean` had syntax highlighting before and now it doesn't. Though I agree with @clason that the consistency of having `checkhealth` be "just another filetype" is better.

`:checkhealth` syntax highlighting still works as expected under "normal" uses (i.e. not with `--clean`), and as far as I know the main use case of using `:checkhealth` with `--clean` is for bug reports, where we don't care about syntax highlighting. So I'm fine with calling this a "wontfix".

**Closed** 2022-01-01 20:17 UTC
Labels: bug, runtime, status:needs-discussion, bug-regression

**Comment by zeertzjq** [comment] 2022-03-16 09:18
Fixed by #17566
