### ISSUE TITLE
Floating window can be not focused after `nvim_input_mouse()`

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#25643] opened 2023-10-14 14:34 UTC
### Problem

Calling `nvim_input_mouse()` right after `nvim_open_win()` with coordinates inside new floating window does not focus the floating window.

### Steps to reproduce

1. Create config file with the following content:
```lua
_G.test_mouse = function()
  local buf_id = vim.api.nvim_create_buf(false, true)
  local config = { relative = 'editor', row = 1, col = 1, height = 10, width = 10 }
  vim.api.nvim_open_win(buf_id, false, config)

  vim.api.nvim_input_mouse('left', 'press', '', 0, 5, 5)
end
```
2. Open `nvim` with that config.
3. Execute `:lua _G.test_mouse()`. Floating window is not focused, although it was "clicked" on.

### Expected behavior

Floating window should be focused, as it is on `ebe489d` commit.

------

The #25629 seems to be the reason. Applying the following patch fixes this issue:

```patch
diff --git a/src/nvim/getchar.c b/src/nvim/getchar.c
index 5f3b14399..46a786c1d 100644
--- a/src/nvim/getchar.c
+++ b/src/nvim/getchar.c
@@ -2862,9 +2862,7 @@ int inchar(uint8_t *buf, int maxlen, long wait_time)

     // Always flush the output characters when getting input characters
     // from the user and not just peeking.
-    if (wait_time == -1L || wait_time > 10L) {
-      ui_flush();
-    }
+    ui_flush();

     // Fill up to a third of the buffer, because each character may be
     // tripled below.
```

### Neovim version (nvim -v)

NVIM v0.10.0-dev-bf70a33

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.5.6-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

**Comment by zeertzjq** [comment] 2023-10-15 12:21
Not a bug. Clicking before redrawing isn't guaranteed to work. (e.g. it doesn't work for 'foldcolumn' or concealed text either)

**Comment by zeertzjq** [comment] 2023-10-15 12:36
Actually there does seem to be a problem: if event are always available, UI is never flushed, even if input is processed. In Vim there is a `redraw_after_callback()` that calls `out_flush()`, but it doesn't seem ideal to flush UI after each event in Nvim either.

**Comment by zeertzjq** [comment] 2023-10-20 13:32
Closing in favor of #25727

**Closed by zeertzjq** 2023-10-20 13:32 UTC
Labels: event-loop
