### ISSUE TITLE
Statusline bleed-over with vim-airline and vsplit

### ISSUE THREAD

**Issue by ugopozo** [neovim/neovim#4147] opened 2016-02-01 15:46 UTC
Hi,

I'm not sure whether this is issue #858 coming back to life, or if it something completely unrelated, however, in version 0.1.1-2 (the one currently on Arch's stable repo), I get the same weird behavior from that issue.

![Airline bleedover](https://cloud.githubusercontent.com/assets/529125/12721981/b0f1b0ae-c8e9-11e5-8d08-956afebd95d0.png)

If you look on the bottom, you can clearly see the contents of the statusline repeated twice, the first one in the correct position but without colors, the second one with the correct colors but bleeding over the right window's statusline.

Also, the right window has the minimum configuration I could reproduce the bug with:

```vimscript
set ruler
set laststatus=2
set mouse=a

syntax on
filetype off

call plug#begin('~/.config/nvim/test_plugged')

Plug 'vim-airline/vim-airline'

call plug#end()
```

**Comment by justinmk** [comment] 2016-02-01 16:29
Does CTRL-L fix it?

**Comment by ugopozo** [comment] 2016-02-01 16:37
@justinmk No, it doesn't. It seems to be related to the size of the statusline. As in, the most items airline is supposed to show, and the smaller the window is horizontally, greater is the possibility of it bleeding over. In the basic configuration above I had to shrink the left window an awful lot for the behavior to appear, but in a real world system, with git, venv, and syntastic blocks showing on the statusline, it's fairly easy to reproduce:

![Real world bleeding](https://cloud.githubusercontent.com/assets/529125/12723601/36f02698-c8f1-11e5-985c-ca9b64f22e02.png)

**Comment by justinmk** [comment] 2016-02-01 16:43
>  In the basic configuration above I had to shrink the left window an awful lot for the behavior to appear,

Can you list those steps precisely? That will make it easy to write a test.

**Comment by Fluctos** [comment] 2016-02-01 16:47
I believe that recent changes in vim-airline/vim-airline repository fixed that problem.

**Comment by chrisbra** [comment] 2016-02-01 16:50
On Mo, 01 Feb 2016, Fluctos wrote:

> I believe that recent changes in vim-airline/vim-airline repository
> fixed that problem.

Not completly, I am afraid, it still seems to happen fairly often with 
neovim:
https://github.com/vim-airline/vim-airline/issues/964

Best,
Christian
-- 
Wenn ich Käse esse, lasse ich die Made links liegen.
		-- Heinz Erhardt

**Comment by ugopozo** [comment] 2016-02-01 17:04
@justinmk The init.vim I listed on the first post requires vim-plug to be installed. Without vim-plug, you can reproduce this with these steps:

* In a clean ~/.config/nvim, create init.vim with the following contents:

```
set ruler
set laststatus=2
set mouse=a

syntax on
filetype off
```

* In the same folder, clone vim-airline master branch from https://github.com/vim-airline/vim-airline.git .

* Symlink autoload, plugins and docs (for good measure) from vim-airline/* into ~/.config/nvim.

* Open any file (such as init.vim itself) with neovim, :vsp, and then resize the window so that the leftmost window gets smaller. Once it hits a certain threshold, the bleed-over will apear.

![Bleeding on a clear ~/.config/nvim](https://cloud.githubusercontent.com/assets/529125/12724404/ff56c5da-c8f4-11e5-9535-fbc2163999e5.png)

**Comment by wsdjeg** [comment] 2016-02-01 17:30
maybe it is due to airline it self,can you try with old version airline,for example 
https://github.com/vim-airline/vim-airline/commit/d7f4fbf5298f9d941a9a1464c5f08c32cf759d34

**Comment by ugopozo** [comment] 2016-02-01 17:48
@wsdjeg Just tried with that revision, problem still persists.

**Comment by ugopozo** [comment] 2016-02-01 17:57
I don't know if it helps, but I just tried with regular vim (version 7.4, patches 1-1190, from Arch's stable repo), following exactly the same procedure (just substituting ~/.config/nvim for ~/.vim, and ~/.config/nvim/init.vim for ~/.vimrc), and the problem does **not** appear. The statusline is correctly shrunk with no bleedover:

![airline-bleed4](https://cloud.githubusercontent.com/assets/529125/12725935/30d24b50-c8fc-11e5-900a-0237a6fbb05e.png)

**Comment by ZyX-I** [comment] 2016-02-01 18:04
@ugopozo Can you show `&statusline` and `eval(&statusline[2:])` contents when problem appears, evaluated in the window which has the problem?

**Comment by ZyX-I** [comment] 2016-02-01 18:06
Also all windows’ sizes at the time you did the test.

**Comment by ugopozo** [comment] 2016-02-01 18:14
@ZyX-I Sure.

`&statusline`:

![airline-statusline](https://cloud.githubusercontent.com/assets/529125/12726414/97c8ee66-c8fe-11e5-9c55-187fac1af77c.png)

`eval(&statusline[2:])`:

![airline-eval-statusline](https://cloud.githubusercontent.com/assets/529125/12726422/a3486fd2-c8fe-11e5-9e97-b4ff565c9cb9.png)

Leftmost window width is 31, rightmost is 59. However, the bleed-over only happens when the leftmost window is selected, so when I switch to the rightmost one to run `:echo winwidth(0)` there is no bleed-over.

**Comment by ZyX-I** [comment] 2016-02-01 18:40
@ugopozo ***No screenshots***. This is needed for reproducing the problem locally, so provide *text*.

**Comment by ZyX-I** [comment] 2016-02-01 18:41
(Locally and without airline.)

**Comment by ugopozo** [comment] 2016-02-01 18:44
@ZyX-I Hey, I'm sorry, I didn't know about that. Anyway, as text:

`&statusline`:
```
%!airline#statusline(1)
```

`eval(&statusline[2:])`:
```
%{airline#check_mode(1)}%#airline_a#%( %#airline_a_bold#%{airline#util#wrap(airline#parts#mode(),0)}%#airline_a#%{airline#util#append(airline#parts#crypt(),0)}%{airline#util#append(airline#parts#paste(),0)}%{airline#util#append("",0)}%{airline#util#append(airline#parts#iminsert(),0)} %)%#airline_a_to_airline_b#>%#airline_b#%#airline_b_to_airline_c#>%#airline_c#%( %<%f%m %#airline_c_red#%{airline#util#wrap(airline#parts#readonly(),0)}%#airline_c# %)%=%#airline_c_to_airline_x#<%#airline_x#%#airline_x_to_airline_y#<%#airline_y#%#airline_y_to_airline_z#<%#airline_z#%( %3p%% %#airline_z_bold#%{g:airline_symbols.linenr}%#airline_z_bold#%4l%#airline_z#%#airline_z#:%3v  %)%(%#airline_z_to_airline_error#<%#airline_error#%( %{airline#util#wrap(airline#extensions#ycm#get_error_count(),0)} %)%)%(<%( %{airline#util#wrap(airline#extensions#ycm#get_warning_count(),0)}%{airline#util#wrap(airline#extensions#whitespace#check(),0)} %)%)
```

**Comment by ZyX-I** [comment] 2016-02-01 18:59
Though it would be harder then I thought: powerline in such case returns text that (except for highlight groups) can be used directly without powerline.

---

Screenshots are used for detecting visual problems and are useless or hard to use for anything else, so if you are asked for any text it is safer to assume that you are asked for *text* then to assume you were asked for screenshot.

---

By the way, what’s the point for `<` and `>`? Powerline full triangles at least look nice (if you were able to setup fonts), these occupy space and look like a poor man’s replacement for rich man’s powerline characters. Better to have “no” and “vertical line” separators like ![](http://img-fotki.yandex.ru/get/64820/9151298.6/0_bae75_4107c06d_orig.png), which looks fine even if vertical line is `|` (U+007C VERTICAL LINE from ASCII, on the screenshot it is U+2502 BOX DRAWING LIGHT VERTICAL).

**Comment by ZyX-I** [comment] 2016-02-01 19:06
> Leftmost window width is 31, rightmost is 59. However, the bleed-over only happens when the leftmost window is selected, so when I switch to the rightmost one to run :echo winwidth(0) there is no bleed-over.

You can use `winwidth(1)` and `winwidth(2)` without switching. Though I do not think this should yield different numbers, would be very surprising if it did.

**Comment by ZyX-I** [comment] 2016-02-01 19:13
@ugopozo I am unable to reproduce this even with airline installed and provided &statusline (and also with default &statusline in place of your `eval(&statusline[2:])`). Can you also show `eval(getwinvar(2, '&statusline')[2:])` while being inside window with bug?

**Comment by ugopozo** [comment] 2016-02-01 19:19
@ZyX-I Lesson learned, will provide text unless asked for screenshot explicitly.

And yes, `winwidth(1|2)` do yield the same values.

I think Airline's appeal over Powerline is that, although it doesn't work in as many different environments, it does work in (Neo)vim and it doesn't require you to mess with your system fonts to simply work. In fact, Powerline's [own repository](https://github.com/powerline/powerline) points to Airline as a lightweight option for people who, like me, don't need/want all the bells and whistles that Powerline provides.

Also, `eval(getwinvar(2, '&statusline')[2:])`:

```
%{airline#check_mode(2)}%#airline_c1_inactive#%( %<%f%m %{airline#util#wrap(airline#parts#readonly(),0)} %)%=%#airline_c1_to_airline_x_inactive#<%#airline_x_inactive#%#airline_x_to_airline_y_inactive#<%#airline_y_inactive#%#airline_y_to_airline_z_inactive#<%#airline_z_inactive#%( %3p%% %{g:airline_symbols.linenr}%4l:%3v  %)
```

I also verified, it is actually different from `eval(&statusline[2:])`, which is the same value I posted before.

**Comment by cHoco** [comment] 2016-02-01 19:40
Just wanted to chime in and confirm that I'm also affected by the same bug.
Here's minimal conf:
``` vim
call plug#begin('~/.vim/plugged')
Plug 'bling/vim-airline'
call plug#end()
let g:airline#extensions#ycm#enabled = 1
```
To reproduce:

```
nvim -u testrc testrc +vs
```
And the overflowing should be there. By resizing the left window the effect should be even more visible.

**Comment by ZyX-I** [comment] 2016-02-01 19:43
@ugopozo Powerline does not *require* you to mess with your system fonts, there is a setting for using only characters from ascii, or only standard unicode characters (or even only unicode characters present in terminus font) (“only” here though means things like symbols before branch or line number and separators, if you e.g. edit file which has powerline triangle in its name, it will be shown as-is). My screenshot shows powerline.

Though it does not work in Neovim yet.

---

Still no luck. Are you able to reproduce this issue when running

```Shell
STL1='%{airline#check_mode(1)}%#airline_a#%( %#airline_a_bold#%{airline#util#wrap(airline#parts#mode(),0)}%#airline_a#%{airline#util#append(airline#parts#crypt(),0)}%{airline#util#append(airline#parts#paste(),0)}%{airline#util#append("",0)}%{airline#util#append(airline#parts#iminsert(),0)} %)%#airline_a_to_airline_b#>%#airline_b#%#airline_b_to_airline_c#>%#airline_c#%( %<%f%m %#airline_c_red#%{airline#util#wrap(airline#parts#readonly(),0)}%#airline_c# %)%=%#airline_c_to_airline_x#<%#airline_x#%#airline_x_to_airline_y#<%#airline_y#%#airline_y_to_airline_z#<%#airline_z#%( %3p%% %#airline_z_bold#%{g:airline_symbols.linenr}%#airline_z_bold#%4l%#airline_z#%#airline_z#:%3v  %)%(%#airline_z_to_airline_error#<%#airline_error#%( %{airline#util#wrap(airline#extensions#ycm#get_error_count(),0)} %)%)%(<%( %{airline#util#wrap(airline#extensions#ycm#get_warning_count(),0)}%{airline#util#wrap(airline#extensions#whitespace#check(),0)} %)%)' STL2='%{airline#check_mode(2)}%#airline_c1_inactive#%( %<%f%m %{airline#util#wrap(airline#parts#readonly(),0)} %)%=%#airline_c1_to_airline_x_inactive#<%#airline_x_inactive#%#airline_x_to_airline_y_inactive#<%#airline_y_inactive#%#airline_y_to_airline_z_inactive#<%#airline_z_inactive#%( %3p%% %{g:airline_symbols.linenr}%4l:%3v  %)' bin/nvim -u NONE -i NONE -N --cmd vsplit --cmd 'vertical resize 31' --cmd 'set rtp+=~/.vam/vim-airline' --cmd 'runtime plugin/airline.vim' -c 'call setwinvar(1, "&stl", $STL1)' -c 'call setwinvar(2, "&stl", $STL2)'
```

(replace `~/.vam/vim-airline` with actual path)? On my system this shows only ![](http://img-fotki.yandex.ru/get/64354/9151298.6/0_bae76_32be7f04_orig.png).

---

@cHoco And without vim-plug and g:airline#extensions#ycm#enabled setting? Specifically with only

```Vim
set runtimepath=/path/to/airline
```

in testrc (this should disable all plugins, except airline, even built-in ones)? Same, but with g:airline#… setting?

**Comment by ugopozo** [comment] 2016-02-01 19:54
@ZyX-I You almost had me convinced to try Powerline again, but if it doesn't in Neovim yet, no dice. I have been thoroughly spoiled by deoplete, `:term` and vim-plug to switch back to vim.

Also, I actually *can* reproduce the issue with that command. Only changes I had to make are `bin/nvim` to `/usr/bin/nvim` and `~/.vam/vim-airline` to `~/.config/nvim-test/vim-airline`, and yes, I get the bug. Should I include an screenshot?

**Comment by cHoco** [comment] 2016-02-01 19:55
@ZyX-I  I can reproduce it with `runtimepath` AND the `g:airline#extensions#ycm#enabled` setting enabled. In my case that option is essential to reproduce the issue.

**Comment by ugopozo** [comment] 2016-02-01 20:00
@ZyX-I @cHoco What I gather is that in order to reproduce the bug the current window width must be smaller than a certain threshold that seems to depend on the total width of the statusline that airline is trying to show.

Maybe @cHoco needs to enable YCM in order to see the issue so that it increases the amount of text airline is trying to show and then trigger the bug.

**Comment by ZyX-I** [comment] 2016-02-01 20:20
@ugopozo I do not think it is *total width* that is responsible, without YCM (runtimepath setting does not contain it) there is no text to show. But airline adds `%…` items to the statusline even they evaluate to nothing.

**Comment by ugopozo** [comment] 2016-02-02 13:59
@ZyX-I I tested again in my home computer and couldn't reproduce the bleed-over using your command. I try to keep my home and work computers mostly in sync (same OS, DE, general software, config sync using git etc.), and I can consistently reproduce the bleed-over on my work computer, while consistently not reproduce it on my home computer.

Main difference between them is hardware. My work computer has 4 GB of RAM and is almost always working from swap, home computer has 16 GB of RAM which is almost always free. I may be going out on a limb here, but it seems the bleed-over is most easily reproduced in memory-constrained situations (my terrible work PC, when I enable all my plugins on my home PC).

I can try later to overload my home PC's memory and see if the bleed-over appears, but as of right now I'm at work.

**Comment by ZyX-I** [comment] 2016-02-02 14:21
@ugopozo On my PC I have 16 GiB RAM (completely consumed by browsers, virtualbox and other software) plus 30GB (meant to be 32GiB AFAIR) SSD swap, so I usually have free memory, though it is free usually in swap.

I suspected some issue with $TERM handling, but still cannot reproduce inside tmux with TERM=xterm-256color, TERM=screen-256color and TERM=konsole-256color and AFAIK you should have either first or second. (And with TERM=xterm I have no colors even if I set `t_Co` to 256, though issue still does not show up.)

**Comment by ugopozo** [comment] 2016-02-02 15:17
@ZyX-I I have TERM=xterm-256color, and I'm using neovim with true colors enabled.

I have been doing some digging, and I've found this. [Here](https://github.com/neovim/neovim/blob/master/src/nvim/screen.c#L5111) the statusline drawing function starts looping on the `hltab` `stl_hrec` array, and it goes on until it finds a struct where `.start` is null. So, I downloaded the master branch and set up a breakpoint to this line, and this is what I get on the struct, when I run your command (and trigger the bug):

```
$31 = {{start = 0x7ffc79098620 " NORMAL >> [No Name]        <<<", userhl = -82}, {
    start = 0x7ffc79098621 "NORMAL >> [No Name]        <<<", userhl = -83}, {
    start = 0x7ffc79098627 " >> [No Name]        <<<", userhl = -82}, {
    start = 0x7ffc79098628 ">> [No Name]        <<<", userhl = -97}, {
    start = 0x7ffc79098629 "> [No Name]        <<<", userhl = -85}, {
    start = 0x7ffc79098629 "> [No Name]        <<<", userhl = -98}, {
    start = 0x7ffc7909862a " [No Name]        <<<", userhl = -88}, {
    start = 0x7ffc79098635 "       <<<", userhl = -90}, {
    start = 0x7ffc79098635 "       <<<", userhl = -88}, {start = 0x7ffc7909863c "<<<", 
    userhl = -99}, {start = 0x7ffc7909863d "<<", userhl = -70}, {
    start = 0x7ffc7909863d "<<", userhl = -95}, {start = 0x7ffc7909863e "<", 
    userhl = -73}, {start = 0x7ffc7909863e "<", userhl = -96}, {
    start = 0x7ffc7909863f "", userhl = -76}, {start = 0x7ffc7909863f "", userhl = -100}, 
  {start = 0x7ffc79098640 "ne#util#wrap(airline#extensions#whitespace#check(),0)", 
    userhl = -79}, {start = 0x7ffc7909863f "", userhl = -101}, {
    start = 0x7ffc79098640 "ne#util#wrap(airline#extensions#whitespace#check(),0)", 
    userhl = -91}, {start = 0x0, userhl = 0},  (.... goes on for a while, but this is the first null)
```

So it seems the problem is coming from somewhere else, in the filling of the `hltab` array. I'll keep looking and checking against Vim's source to find out what is being done differently.

**Comment by wsdjeg** [comment] 2016-02-02 15:20
also encount this issue, happened when switch from vimfiler buffer to file buffer.
![2016-02-02 23-19-10](https://cloud.githubusercontent.com/assets/13142418/12753801/8726bf74-ca03-11e5-95d4-128615eb93ea.png)

**Comment by wsdjeg** [comment] 2016-02-02 15:26
fixed by `git reset --hard HEAD~30` in vim-airline repo

**Comment by wsdjeg** [comment] 2016-02-03 02:18
thanks for your work
@chrisbra

**Comment by nicdumz** [comment] 2016-03-08 10:07
In my opinion #4195 is very similar.

See my latest update for status/questions there: https://github.com/neovim/neovim/issues/4195#issuecomment-193700966

**Comment by nicdumz** [comment] 2016-03-10 12:02
Merged, so I believe we can close this now.

**Comment by mhinz** [comment] 2016-03-10 12:06
@ugopozo This should be fixed by https://github.com/neovim/neovim/pull/4427. Please reopen if that's not the case.

**Closed by mhinz** 2016-03-10 12:06 UTC
Labels: bug-vim
