### ISSUE TITLE
Garbage typed when starting Neovim in Alacritty

### ISSUE THREAD

**Issue by HarmtH** [neovim/neovim#10131] opened 2019-06-06 12:43 UTC
- `nvim --version`: master, 8e8c7d7544129c2bf859adf8eb6eda5b19e8040b
- Vim (version: ) behaves differently? 8.1.1476, YES
- Operating system/version:
- Terminal name/version: Alacritty, master, 3931fb6fbce728c33b4ae2d1e604f181a7246fe0
- `$TERM`: alacritty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

### Actual behaviour
Garbage typed after start

### Expected behaviour
No garbage typed after start

### Explanation
I've bisected first wrong commit to 298608f88c463705cfd6ee47035c049dbb1d9fa0 (background detection)

Termite's response to ```\x1b]11;?\x07``` (WORKS):
```
^[]11;rgb:fbfb/f1f1/c7c7^G
```

Alacritty's response to ```\x1b]11;?\x07``` (BROKEN):
```
^[]11;rgb:fb/f1/c7^G
```

Both are correct responses afaik.

Vim also has an implementation of background detection, which seems to work fine.

**Comment by HarmtH** [comment] 2019-06-06 12:59
I've figured out that on some startups this if statement https://github.com/neovim/neovim/blob/master/src/nvim/tui/input.c#L406 is entered and sometimes it isn't.

**Comment by justinmk** [comment] 2019-06-06 13:11
> Vim also has an implementation of background detection, which seems to work fine.

alacritty decided to do it a different way. Vim patch: https://github.com/vim/vim/commit/32e1977012912cd5d7bc762dd41197bc3f1a1370

Patch welcome.

cc @joshtriplett

**Comment by HarmtH** [comment] 2019-06-06 13:33
That still doesn't explain why https://github.com/neovim/neovim/blob/master/src/nvim/tui/input.c#L406 is sometimes entered and sometimes it isn't.

I've wrote a small C program that checked how many characters were ```read()``` on one invocation (the return value of ```read()```).

Where termite (libvte) always returned 24 characters (```^[]11;rgb:fbfb/f1f1/c7c7^G```),

Alacritty returned different results. Sometimes 18 chars (```^[]11;rgb:fb/f1/c7^G```), but sometimes it's split. I've seen (17,1), (2,16), (5,2,3,4)...

**Comment by HarmtH** [comment] 2019-06-06 13:43
> > Vim also has an implementation of background detection, which seems to work fine.
> 
> alacritty decided to do it a different way. Vim patches:
> 
>     * [vim/vim@32e1977](https://github.com/vim/vim/commit/32e1977012912cd5d7bc762dd41197bc3f1a1370)
> 
>     * [vim/vim@12e71eb](https://github.com/vim/vim/commit/12e71eb8a89bdfe1def5854fd7478e8899801b44)
> 
> 
> Patch welcome.
> 
> cc @joshtriplett

This comment https://github.com/neovim/neovim/blob/master/src/nvim/tui/input.c#L387 and if I'm reading the code correct suggests different lengths of RGB are parsed correctly.

I think https://github.com/neovim/neovim/issues/10131#issuecomment-499495419 is the real issue here. I haven't dug into the Vim source code, but I assume it will just sit and wait for a complete response to ```\x1b]11;?\x07```?

**Comment by blueyed** [comment] 2019-06-12 13:53
https://github.com/neovim/neovim/issues/10195 mentions this might crash even.
Can you please provide a stacktrace for this?  (see https://github.com/neovim/neovim/wiki/Development-tips#debugging)
(might be as easy as `coredumpctl gdb`, and then `bt`)

**Comment by sanga** [comment] 2019-06-13 05:19
Master (v0.4.0-1016-g6f27f5ef9) doesn't seem to crash anymore for me, btw (or it hasn't crashed so far in 5mins of trying to crash it). Anecdotally, it seems like master is a lot less likely to get garbage chars at startup also

**Comment by sanga** [comment] 2019-06-13 06:31
I stand corrected. It also crashes on v0.4.0-1016-g6f27f5ef9 but it seems a lot less frequent. Same error as I mentioned in #10195 and I don't have symbols in this build so that stack is basically useless (sorry).

**Comment by blueyed** [comment] 2019-06-13 12:16
@HarmtH 
Is this related to / fixed by https://github.com/neovim/neovim/pull/10205 ?

**Comment by HarmtH** [comment] 2019-06-13 13:03
> @HarmtH
> Is this related to / fixed by #10205 ?

No, different problems unfortunately.

The issue here is that, unlike other terminals, Alacritty's response is not always contained in ```read()``` call. (I'm not enough of a kernel expert to know whether it's guaranteed that the responses from other terminals will be contained in one ```read()``` call, but it happens to be the case.)

Neovim will crash when only ```^[]11;rgb:``` is in the rbuffer.
The loop will be entered https://github.com/neovim/neovim/blob/master/src/nvim/tui/input.c#L411
But there is nothing left to read https://github.com/neovim/neovim/blob/master/src/nvim/tui/input.c#L422
So ```count``` will stay ```0```
And the assertion ````count && count <= buf->size```` inside https://github.com/neovim/neovim/blob/master/src/nvim/tui/input.c#L445 will trigger.

**Comment by HarmtH** [comment] 2019-06-13 13:14
So fixing the crash is as easy as wrapping https://github.com/neovim/neovim/blob/master/src/nvim/tui/input.c#L445 in a ```if (count) {}```.

Fixing the garbage typing will be a bit more difficult.

**Comment by blueyed** [comment] 2019-06-13 13:27
From a quick look it seems like `tinput_read_cb` should be responsible for handling / passing on only complete/finished escape sequences from responses?

**Comment by HarmtH** [comment] 2019-06-13 14:03
> From a quick look it seems like `tinput_read_cb` should be responsible for handling / passing on only complete/finished escape sequences from responses?

It seems to me that it cuts the input stream so the escape character doesn't appear in the middle, but always at the start. But it doesn't seem that it will wait for a complete sequence when it's already at the start?

> Ok, rather `handle_background_color` should postpone the handling if not complete (yet) maybe?

That sounds like an idea, but therefore ```tinput_read_cb``` first needs to be able to wait for complete sequences, probably with a time-out so it won't wait forever.

**Comment by chrisduerr** [comment] 2019-06-15 15:30
This has just been reported to me in https://github.com/jwilm/alacritty/issues/2543.

While looking into it, I came to the same conclusion that this must be because the output is not written in a single go and I'll see if I can patch this in Alacritty.

Regarding the format, this is planned to change to the more common rgb:ffff/0000/ffff format, however it should probably be noted that even #fff000fff is a valid format. Full info about allowed color formats can be found in `man XParseColor`.

**Comment by craigbarnes** [comment] 2019-07-14 20:13
Split reads/writes are not a bug, but an explicit result of the termios settings used by neovim.

As noted in the `termios(3)` man page, there are almost no guarantees about the result of a `read`:

> In noncanonical mode input is available immediately (without the user having to type a line-delimiter character),  no  input  processing  is performed, and line editing is disabled.  The read buffer will only accept 4095 chars; this provides the necessary space for a newline char if  the  input  mode  is switched to canonical.  The settings of `MIN` (`c_cc[VMIN]`) and `TIME` (`c_cc[VTIME]`) determine the circumstances in which a `read`(2) completes; there are four distinct cases:
>
> `MIN > 0`, `TIME == 0` (blocking read)  
> `read` blocks until `MIN` bytes are available, and returns **up to** the number of bytes requested.
>

Applications shouldn't be relying on the terminal to never split writes/flushes, they should either be waiting for the sequence terminator or detecting truncation -> re-reading -> re-parsing. Most apps that handle it at all do the latter (e.g. [1][], [2][]), due to strict state machine parsing falling down when having to deal with real world implementations.

[1]:https://github.com/tmux/tmux/blob/c9216493cfa3b62b6edc9dae11892a071e56fa5c/xterm-keys.c#L181-L182
[2]:https://github.com/craigbarnes/dte/blob/master/src/terminal/input.c#L89-L104

**Comment by mohamadLy** [comment] 2019-11-11 18:07
I was thinking taking this if nobody is on it

**Comment by justinmk** [comment] 2019-11-12 06:36
@mohamadLy please do.

**Comment by BodilessSleeper** [comment] 2021-04-23 12:24
This seems not to be an issue anymore

**Comment by lockejan** [comment] 2021-08-01 12:18
I tested this as well. Can't reproduce it under:
- alacritty 0.8.0
- NVIM v0.6.0-dev+15698eb5a
- MacOs 11.5.1 

Also the referenced alacritty issue has been closed in the meantime as well: https://github.com/alacritty/alacritty/issues/2543

Can be closed IMO.

**Comment by marcelarie** [comment] 2021-08-01 15:24
This is happening to me now.
I use ArcoLinux `5.13.6-arch1-1`
NVIM `v0.6.0-dev+99-g51251e1dc`
kitty `0.22.1`

Nvim slows down a lot and this characters appear everywhere. 

```
health#mkdp#check                                                                                                                       
========================================================================                                                                
  - INFO: Platform: linux                                                                                                               
  - INFO: Nvim Version: ^[]4;0;rgb:28/28/28^[\^[]4;1;rgb:fb/49/34^[\^[]4;2;rgb:b8/bb/26^[\^[]4;3;rgb:fa/bd/2f^[\^[]4;4;rgb:83/a5/         98^[\^[]4;5;rgb:d3/86/9b^[\^[]4;6;rgb:8e/c0/7c^[\^[]4;7;rgb:d5/c4/a1^[\^[]4;8;rgb:66/5c/54^[\^[]4;9;rgb:fb/49/34^[\^[]4;10;rgb:b8/bb/   26^[\^[]4;11;rgb:fa/bd/2f^[\^[]4;12;rgb:83/a5/98^[\^[]4;13;rgb:d3/86/9b^[\^[]4;14;rgb:8e/c0/7c^[\^[]4;15;rgb:fb/f1/c7^[\^[]4;16;rgb:    fe/80/19^[\^[]4;17;rgb:d6/5d/0e^[\^[]4;18;rgb:3c/38/36^[\^[]4;19;rgb:50/49/45^[\^[]4;20;rgb:bd/ae/93^[\^[]4;21;rgb:eb/db/b2^[\^[]10;    rgb:d5/c4/a1^[\^[]11;rgb:28/28/28^[\^[]12;7^[\NVIM v0.6.0-dev+99-g51251e1dc                                                           
  - INFO: Node version: ^[]4;0;rgb:28/28/28^[\^[]4;1;rgb:fb/49/34^[\^[]4;2;rgb:b8/bb/26^[\^[]4;3;rgb:fa/bd/2f^[\^[]4;4;rgb:83/a5/         98^[\^[]4;5;rgb:d3/86/9b^[\^[]4;6;rgb:8e/c0/7c^[\^[]4;7;rgb:d5/c4/a1^[\^[]4;8;rgb:66/5c/54^[\^[]4;9;rgb:fb/49/34^[\^[]4;10;rgb:b8/bb/   26^[\^[]4;11;rgb:fa/bd/2f^[\^[]4;12;rgb:83/a5/98^[\^[]4;13;rgb:d3/86/9b^[\^[]4;14;rgb:8e/c0/7c^[\^[]4;15;rgb:fb/f1/c7^[\^[]4;16;rgb@@@
  - ```

**Comment by justinmk** [comment] 2021-09-24 14:24
> Also the referenced alacritty issue has been closed in the meantime: [alacritty/alacritty#2543](https://github.com/alacritty/alacritty/issues/2543)

Thanks for that reference @lockejan . Details from https://github.com/alacritty/alacritty/pull/2544 :

> The dynamic color escape response would answer to requests with
> rgb:0/0/0 when the color was completely black, instead of properly
> responding with double-digit hex colors. This has been changed so that
> Alacritty now alwaysy properly responds with the same number of hex
> digits for all colors.
> 
> The number of digits has also been changed from two to four digits per
> color, since that is the more commonly used format.

**Closed by justinmk** 2021-09-24 14:24 UTC
Labels: bug, good-first-issue, tui, status:has-plan

**Comment by downhiller** [comment] 2025-01-28 10:27
I seem to be experiencing this in v0.10.2

About 5% of the time when I open a file, `rgb:1e1e/1e1e/1e1e` is input.  I've not logged the keys in any way, but a character gets overwritten with `g` and then the cursor moves back to the start of the word.  So I've deduced `rgb`.  If I then type `:` and hit up to see the last command I see `:1e1e/1e1e/1e1e`

I'm using Windows Terminal on Windows 11, connecting to a Centos Stream 9 server.  $TERM is `xterm-256color` (though I can't find where this is set - nothing in `/etc` or `~`?

Any help appreciated.  When I notice its happened it's no big deal (`u` happily undoes it), but when I don't notice, eurgh, infuriating!

**Comment by clason** [comment] 2025-01-28 10:30
Please test the latest nightly, and open a new issue with full details if it still happens.
