### ISSUE TITLE
Make vim modal editing an opt-in feature?

### ISSUE THREAD

**Issue by Bhanukamax** [neovim/neovim#20028] opened 2022-08-31 16:36 UTC
### Feature description

I know this might sound absurd to ask, but I thought why not?

I'm not sure whether this is possible or even considerable. But is it possible to decouple vim motions/modes/etc from neovim?

## Motivation for asking this:
I've seen the new developments/improvements in neovim with all the lua integrations, that's it's becoming more and more powerful, I believe that's the true power of neovim, but to get all that power one has to buy into using vim modal editing.

## Vim Modes
I have seen projects like [hydra](https://github.com/anuvyklack/hydra.nvim) which try to give more power to the users by introducing a way to implement new modes.

But what if that's something built into defining new modes also, and what if the vim modes (like insert, normal, visual, etc) are also just modes defined in Lua, and users can maybe control how those modes work, etc?

So if one wants they can, not use these modes but define their own modes or use a combination of things from what's built-in and what they define. To be more clear I'm talking about something like minor modes in emacs.

## Vim Motions
Do I dislike vim motions? no. 

But I think it would be beneficial if one can write his own way of using them with lua.

**for example:**
If someone wants to change their keyboard layout (eg: qwerty to dvorak), they have to rewire their vim muscle memory after they even learn how to type on dvorak.
But if the vim motions are not bound to letters like `w - "word", b - "beginning of the word"`, etc.
And if a user has the ability to write some Lua to implement their own modal editing way which uses some other mechanics with the left-hand right-hand work distribution (eg [Xah-fly-keys](https://github.com/xahlee/xah-fly-keys)) they can make it work for whatever keyboard layout similarly.
## This is my personal problem why should neovim care:
Yes this is a personal thing. After all, that's what software is all about, fixing our problems.
 I'm proposing this because I feel this could make neovim more extensibility.

**Comment by clason** [comment] 2022-08-31 16:44
I'm sorry, but this is just not an actionable request. Neovim is a fork of Vim, so the modal editing is "in its DNA" -- removing that doesn't give you a version of Neovim, it gives you something completely different:

> I've seen the new developments/improvements in neovim with all the lua integrations, that's it's becoming more and more powerful, I believe that's the true power of neovim, but to get all that power one has to buy into using vim modal editing.

I think most users and all maintainers will violently disagree with that statement -- rather it's the other way around: using Lua to bring the power of a modal editor into the Century of the Fruitbat.

> So if one wants they can, not use these modes but define their own modes or use a combination of things from what's built-in and what they define. To be more clear I'm talking about something like minor modes in emacs.

This specifically is a duplicate of https://github.com/neovim/neovim/issues/16313. (Note that even if that is implemented in Lua, it makes no sense to remove the builtin modes.)

I am going to close this issue since there is no need to track this and an issue tracker is not a discussion forum. If you want feedback on your idea, post it on r/neovim or https://neovim.discourse.group.

**Closed by clason** 2022-08-31 16:44 UTC
Labels: enhancement

**Comment by Bhanukamax** [comment] 2022-08-31 16:54
cool, I totally understand. Thanks for your feedback.
