### ISSUE TITLE
HOME key doesn't work in nvim which is run in FreeBSD screen/tmux

### ISSUE THREAD

**Issue by sp55aa** [neovim/neovim#31293] opened 2024-11-21 20:22 UTC
### Problem

HOME key doesn't work in nvim which is run in FreeBSD screen/tmux

screen --version: 4.09.01
tmux -V: 3.3a

btw, HOME key works in nvim without screen/tmux

### Steps to reproduce

nvim --clean

### Expected behavior

HOME key should work in nvim which is run in FreeBSD screen/tmux

### Nvim version (nvim -v)

v0.10.2

### Vim (not Nvim) behaves the same?

no, vim 9.1.764

### Operating system/version

FreeBSD 14.1 amd64

### Terminal name/version

tabby 1.0.187 (running in Windows 10)

### $TERM environment variable

screen-256color

### Installation

system package manager

**Comment by zeertzjq** [comment] 2024-11-21 22:26
Duplicate of #13292

**Closed by zeertzjq** 2024-11-21 22:26 UTC
Labels: bug
