### ISSUE TITLE
Trouble setting `background=light` after #14771

### ISSUE THREAD

**Issue by VVKot** [neovim/neovim#15176] opened 2021-07-24 10:40 UTC
- `nvim --version`:
```
NVIM v0.6.0-dev+64-g754ac5a83
Build type: Debug
LuaJIT 2.1.0-beta3
```
- Operating system/version: MacOS Big Sur 11.4
- Terminal name/version: iTerm2 3.4.8
- `$TERM`: xterm-256color

Also see logs here: https://github.com/neovim/neovim/pull/14771#issuecomment-886029977

You have 3 files:

1. test.vim: `set background=light`
2. test.lua: `vim.cmd [[set background=light]]`
3. test2.vim: `lua require "test.lua"`

Sourcing them results in background being set to light only for test2.vim (`nvim -u test2.vim`). Please note that I am talking about actually visual result on the screen, `set background?` returns `light` for all three cases.

### Actual behaviour

Background is set to dark in some cases

### Expected behaviour

Background is set to light in all cases

**Comment by clason** [comment] 2021-07-24 10:43
What happens with using `test.lua` as `init.lua`? (I.e., is the difference the fact that it's Lua or that it's a separate file that is `required`(!) manually?)

**Comment by clason** [comment] 2021-07-24 10:44
As already mentioned on the merged PR, the issue is likely that now `syncolor.vim` is sourced before `init.vim` so the manually set `background` is not available for the check in
https://github.com/neovim/neovim/blob/ea35584bac6f33d4cb4fd59f5dcd0113e568c5a1/runtime/syntax/syncolor.vim#L35

**Comment by VVKot** [comment] 2021-07-24 10:48
Yes, removing my `init.vim`, adding `init.lua` with `vim.cmd [[set background=light]]` and typing `nvim` works correctly. However, `nvim -u test.lua` does not.

**Closed** 2021-07-25 13:36 UTC
Labels: bug
