### ISSUE TITLE
Startup time increase significantly with function call style change in autocmd

### ISSUE THREAD

**Issue by roxma** [neovim/neovim#6239] opened 2017-03-09 11:00 UTC
- `nvim --version`:
```
NVIM v0.1.7-437-g0542baa
Build type: Release
Compilation: /usr/bin/cc -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/data/roxma/.local_software/tmp/neovim/build/config -I/data/roxma/.local_software/tmp/neovim/src -I/data/roxma/.local_software/tmp/neovim/.deps/usr/include -I/data/roxma/.local_software/tmp/neovim/.deps/usr/include -I/data/roxma/.local_software/tmp/neovim/.deps/usr/include -I/data/roxma/.local_software/tmp/neovim/.deps/usr/include -I/data/roxma/.local_software/tmp/neovim/.deps/usr/include -I/data/roxma/.local_software/tmp/neovim/.deps/usr/include -I/usr/include -I/data/roxma/.local_software/tmp/neovim/build/src/nvim/auto -I/data/roxma/.local_software/tmp/neovim/build/include
Compiled by roxma@VM_67_229_centos

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/data/roxma/.local_software/neovim/share/nvim"

```

- Operating system/version:
Linux VM_67_229_centos 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Code structure:
```
.
├── autoload
│   └── foo.vim
├── min.vim
├── plugin
    └── bar.vim
```

min.vim
```vim
set nocompatible
syntax on
filetype plugin indent on
set encoding=utf-8 fileencodings=ucs-bom,utf-8,gbk,gb18030,latin1 termencoding=utf-8

set rtp+=.
```

## normal version:

autoload/foo.vim
```vim

fun foo#bar()
    " do nothing
endf

func foo#foo()
    call foo#bar()
endfunc
```

plugin/bar.vim

```vim
au BufWinEnter * call foo#foo()
```

## slow version:

autoload/foo.vim
```vim
fun foo#bar()
    " do nothing
endf
```

plugin/bar.vim
```vim
func s:foo()
    call foo#bar()
endfunc

au BufWinEnter * call s:foo()
```

## Normal startup time:
nvim -u min.vim --startuptime normal.log
```
times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.013  000.013: --- NVIM STARTING ---
000.289  000.276: locale set
000.850  000.561: inits 1
000.861  000.012: window checked
001.140  000.279: parsing arguments
001.145  000.005: expanding arguments
001.207  000.062: inits 2
001.340  000.132: init highlight
002.140  000.329  000.329: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/syntax/syncolor.vim
002.359  000.720  000.391: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/syntax/synload.vim
018.640  016.176  016.176: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/filetype.vim
018.724  017.233  000.336: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/syntax/syntax.vim
018.834  000.013  000.013: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/filetype.vim
018.947  000.041  000.041: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/ftplugin.vim
019.073  000.050  000.050: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/indent.vim
019.135  017.709  000.372: sourcing min.vim
019.144  000.095: sourcing vimrc file(s)
020.008  000.378  000.378: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/gzip.vim
020.077  000.022  000.022: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/health.vim
020.187  000.073  000.073: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/man.vim
021.117  000.891  000.891: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/matchit.vim
021.460  000.291  000.291: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/matchparen.vim
022.281  000.769  000.769: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/netrwPlugin.vim
022.426  000.080  000.080: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/rplugin.vim
022.513  000.024  000.024: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/rrhelper.vim
022.706  000.146  000.146: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/shada.vim
022.845  000.057  000.057: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/spellfile.vim
023.124  000.226  000.226: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/tarPlugin.vim
023.327  000.147  000.147: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/tohtml.vim
023.413  000.033  000.033: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/tutor.vim
023.697  000.232  000.232: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/vimballPlugin.vim
024.080  000.285  000.285: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/zipPlugin.vim
024.346  000.016  000.016: sourcing ./plugin/bar.vim
024.362  001.547: loading plugins
024.666  000.304: loading packages
024.688  000.022: inits 3
033.411  008.723: reading ShaDa
034.533  001.121: clearing screen
035.182  000.040  000.040: sourcing ./autoload/foo.vim
035.227  000.654: opening buffers
035.289  000.062: BufEnter autocommands
035.298  000.008: editing files in windows
035.498  000.200: VimEnter autocommands
035.503  000.005: before starting main loop
039.308  003.805: first screen update
039.320  000.012: --- NVIM STARTED ---
```

## slow startup time
nvim -u min.vim --startuptime slow.log
```
times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.016  000.016: --- NVIM STARTING ---                                                        
000.355  000.339: locale set                                                                   
001.155  000.800: inits 1                                                                      
001.169  000.015: window checked                                                               
001.465  000.296: parsing arguments                                                            
001.470  000.005: expanding arguments                                                          
001.543  000.073: inits 2                                                                      
001.722  000.178: init highlight                                                               
002.531  000.314  000.314: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/syntax/syncolor.vim
002.756  000.669  000.354: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/syntax/synload.vim
023.950  021.068  021.068: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/filetype.vim
024.082  022.165  000.428: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/syntax/syntax.vim
024.217  000.018  000.018: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/filetype.vim
024.401  000.063  000.063: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/ftplugin.vim
024.576  000.053  000.053: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/indent.vim
024.654  022.796  000.496: sourcing min.vim                                                    
024.664  000.146: sourcing vimrc file(s)                                                       
025.648  000.316  000.316: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/gzip.vim
025.715  000.022  000.022: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/health.vim
025.849  000.099  000.099: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/man.vim
026.861  000.965  000.965: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/matchit.vim
027.277  000.317  000.317: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/matchparen.vim
028.131  000.807  000.807: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/netrwPlugin.vim
028.283  000.083  000.083: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/rplugin.vim
028.365  000.025  000.025: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/rrhelper.vim
028.568  000.154  000.154: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/shada.vim
028.693  000.065  000.065: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/spellfile.vim
029.048  000.292  000.292: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/tarPlugin.vim
029.310  000.143  000.143: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/tohtml.vim
029.398  000.033  000.033: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/tutor.vim
029.667  000.222  000.222: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/vimballPlugin.vim
030.045  000.292  000.292: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/plugin/zipPlugin.vim
030.328  000.028  000.028: sourcing ./plugin/bar.vim                                           
030.344  001.816: loading plugins                                                              
030.615  000.272: loading packages                                                             
030.647  000.032: inits 3                                                                      
039.561  008.914: reading ShaDa                                                                
040.724  001.163: clearing screen                                                              
041.808  000.446  000.446: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/autoload/remote/host.vim
042.953  000.330  000.330: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/autoload/remote/define.vim
046.861  004.657  004.326: sourcing /data/roxma/.local/share/nvim/rplugin.vim                  
047.152  000.026  000.026: sourcing ./autoload/foo.vim                                         
047.235  001.383: opening buffers                                                              
047.290  000.055: BufEnter autocommands                                                        
047.302  000.012: editing files in windows                                       
047.448  000.146: VimEnter autocommands
047.453  000.005: before starting main loop
048.051  000.241  000.241: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/autoload/provider/pythonx.vim
100.376  052.150  052.150: sourcing /data/roxma/.local_software/neovim/share/nvim/runtime/autoload/provider/python3.vim
253.546  153.703: first screen update
253.558  000.012: --- NVIM STARTED ---
```

**Comment by justinmk** [comment] 2017-03-09 11:12
That's how autoload works. Calling an autoload'd function (`call foo#...`) searches the runtimepath.

**Comment by roxma** [comment] 2017-03-09 11:14
Thw wierd part is that the two version both call autoload function.

**Comment by justinmk** [comment] 2017-03-09 11:15
au BufWinEnter * call s:foo()

That shouldn't work, `<SID>` is needed in an autocmd.

    au BufWinEnter * call <SID>foo()

**Comment by roxma** [comment] 2017-03-09 11:35
It's still very slow. I've even tried `g:Foo` version.

**Comment by jamessan** [comment] 2017-03-09 12:11
Both the normal and slow versions are basically the same up until the `clearing screen` log.  Then the slow one decides to load `remote/host.vim`, `remote/define.vim`, `rplugin.vim` and eventually the python host.

That's the significant difference, because that adds the startup time of Python itself into the mix.  Why is that happening in the slow case?

**Comment by justinmk** [comment] 2017-03-09 12:22
Most likely the FuncUndefined handler at `runtime/autoload/remote/define.vim:133`.

**Comment by tweekmonster** [comment] 2017-03-10 04:31
@roxma Have you tried this with master?  I'm not able to reproduce this.  Here's my log: https://gist.github.com/tweekmonster/e6bc9b096d66caf1f66dfea8a1772fb4

> That shouldn't work, <SID> is needed in an autocmd.

This has never been in the case for me.  From my understanding it's required in `:map` because you might want `s:` to be literal in `{rhs}`.  `autocmd` isn't interpreted as keystrokes so it shouldn't care.  What I think is actually broken about `<SID>` is that I can't use `<SNR>123` as a way to access script variables (as readonly, of course) which would help runtime debugging a ton.

**Comment by roxma** [comment] 2017-03-10 08:55
@tweekmonster 

I can reproduce this with master

```
NVIM v0.2.0-1218-g59ea30a
Build type: Release
Compilation: /usr/bin/cc -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/data/roxma/.local_software/tmp/neovim/build/config -I/data/roxma/.local_software/tmp/neovim/src -I/data/roxma/.local_software/tmp/neovim/.deps/usr/include -I/data/roxma/.local_software/tmp/neovim/.deps/usr/include -I/data/roxma/.local_software/tmp/neovim/.deps/usr/include -I/data/roxma/.local_software/tmp/neovim/.deps/usr/include -I/data/roxma/.local_software/tmp/neovim/.deps/usr/include -I/data/roxma/.local_software/tmp/neovim/.deps/usr/include -I/usr/include -I/data/roxma/.local_software/tmp/neovim/build/src/nvim/auto -I/data/roxma/.local_software/tmp/neovim/build/include
Compiled by roxma@VM_67_229_centos

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/data/roxma/.local_software/neovim_master/share/nvim"
```

This issue was found in ncm issue https://github.com/roxma/nvim-completion-manager/issues/48

@fannheyward could also confirm the effect of the change.

**Comment by wsdjeg** [comment] 2017-03-10 09:07
does it happend in vim? I also can not reproduce it.

**Comment by ZyX-I** [comment] 2017-03-10 12:16
> That shouldn't work, <SID> is needed in an autocmd.

`<SID>` is only needed in a mapping because keys put into input queue do not have script ID data attached to them and thus it is needed to expand `s:` at the mapping definition time (or, at most, before feeding rhs into input queue) and exactly `s:` may not be expanded in a mapping because it may mean something other then `<SID>`. This is not the case for autocommands.

**Comment by ZyX-I** [comment] 2017-03-10 12:21
Can you post a profile? Startuptime provides only an overview. E.g. run nvim with

    nvim --cmd 'profile start /tmp/profile.log' --cmd 'profile file *' --cmd 'profile func *'

, after you quit nvim profile will be in /tmp/profile.log.

**Comment by roxma** [comment] 2017-03-10 12:34
Here's the profile: http://pastebin.com/qGzH365Q

**Comment by justinmk** [comment] 2017-03-10 12:50
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    3   0.241226   0.000424  remote#define#AutocmdBootstrap()
    3   0.240231   0.000257  remote#host#Require()
    1   0.239823   0.193428  provider#pythonx#Require()
...
 
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1   0.239823   0.193428  provider#pythonx#Require()
    1              0.045727  <SNR>28_check_interpreter()
    3   0.004739   0.001965  remote#host#RegisterPlugin()
...
```

Is this the same issue as #5728 ?

**Comment by justinmk** [comment] 2017-04-26 10:25
No reply, assuming this is covered by https://github.com/neovim/neovim/issues/5728

**Closed by justinmk** 2017-04-26 10:25 UTC
Labels: performance, provider, runtime
