### ISSUE TITLE
Can not add data to a vim.g list using vim.fn.add.

### ISSUE THREAD

**Issue by fcying** [neovim/neovim#22799] opened 2023-03-28 02:11 UTC
### Problem

use `table.insert` `vim.fn.add` can not add data to a vim.g list.
use vim.cmd([[ call add() ]]) work fine.

t.lua
```
vim.cmd(' let g:test = {} ')
vim.cmd(' let g:test.a = [] ')

vim.pretty_print(vim.g.test)

table.insert(vim.g.test.a, 'aaa')
vim.pretty_print(vim.g.test)

vim.fn.add(vim.g.test.a, 'bbb')
vim.pretty_print(vim.g.test)

vim.cmd([[ call add(g:test.a, 'ccc') ]])
vim.pretty_print(vim.g.test) 
```

result:
![image](https://user-images.githubusercontent.com/106934/228108147-aead7055-e3e2-4bbd-be9d-f1d2da2a1078.png)

### Steps to reproduce

nvim -u  t.lua

### Expected behavior

add data to a vim.g list

### Neovim version (nvim -v)

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

debian 11

### Terminal name/version

xfce4-terminal 0.8

### $TERM environment variable

xterm 

### Installation

appimage

**Comment by zeertzjq** [comment] 2023-03-28 02:31
Duplicate of #12544

**Closed by zeertzjq** 2023-03-28 02:31 UTC
Labels: bug
