### ISSUE TITLE
Visual Block enhancement/fix

### ISSUE THREAD

**Issue by LamprosPitsillos** [neovim/neovim#16351] opened 2021-11-17 21:06 UTC
### Feature description

Visual block mode doesn’t actually behave as expected in this case. For example if I want to select a column of words and add to them I can’t just select and then press `w` to select each word separately and add to it (`A`). This is possible however if the words are at the end of the line and I press the `$` which indicates that it is possible for block mode to 'break' out of block and actually conform to a selection.

```shell
|Bear cub
|Dodecahedron dice
|Table cloth
|Jacksonville town

**Expected
Bear |cub
Dodecahedron |dice
Table |cloth
Jacksonville |town

**Actually, if cursor at first line
Bear |cub
Dodec|ahedron dice
Table| cloth
Jacks|onville town
```

I mean in which case would someone need to select the column words and select just until the end of the current word ? I just don’t see a reason why this is still in Neovim.
Is there a reason that I’m failing to see or is it just legacy “feature” ?
Either way i am curious to see what others think of this.

**Comment by clason** [comment] 2021-11-17 23:04
> Either way i am curious to see what others think of this.

This makes it much more appropriate for Discourse ([where you have already posted it](https://neovim.discourse.group/t/visual-block-mode-anti-feature-word-movement/1429)). Since there's no clear bug or new feature (that isn't a duplicate of the frequent "multi-cursor" request), I'm closing this one.

**Closed by clason** 2021-11-17 23:04 UTC
Labels: enhancement

**Comment by LamprosPitsillos** [comment] 2021-11-17 23:14
Maybe it was wrong of me to say the discussion part here..
Indeed in the Discourse i will get opinions , but I doubt any change is gonna come out of the discussion as even if someone notices it it's gonna get buried in a week.
I believe that "fixing" this , without multiple cursors that is, is considered a feature (and a very logical one at that).

**Comment by clason** [comment] 2021-11-17 23:18
You don't have a lot of patience, do you...

In any case, it's called a *block* selection for a reason -- what you apparently want (your issue didn't make it very clear) is something else and not a simple "fix". Still, PR for a new "jagged selection mode" welcome!

**Comment by LamprosPitsillos** [comment] 2021-11-17 23:22
> You don't have a lot of patience, do you...
Why would you say that ? And why the irony?
All i did was try and make my point more clear...
Anyway forget it, Thanks
