### ISSUE TITLE
range for visual selection

### ISSUE THREAD

**Issue by stumash** [neovim/neovim#16115] opened 2021-10-21 20:03 UTC
### Feature already in Vim?

no

### Feature description

let's say I have a text file

```
here's a line of text.
then another.
and finally a third line.
```

let's say I go to visual mode and select some text (selection indicated by upper case letters)

```
here's a line OF TEXT.
THEN ANOther.
and finally a third line.
```

while the text is visually selected, when I hit `:` I go to command mode with a line range

```
:'<,'>
```

and let's say I end up doing 

```
:'<,'>s/t/ZZ/g
```

that would leave the file like this

```
here's a line of ZZexZZ.
ZZhen anoZZher.
and finally a third line.
```

THE PROBLEM IS: I didn't select the **whole first two lines**, I only selected `of text.\nthen ano`

I don't want every single `t` **_in the lines that include my visual selection_** to be replaced, I only want the `t`s **_that are within the selection itself_** to be replaced. That last `ZZ` shouldn't have happened becase that `t` was outside my selection.

Is there anyway to do this?
Can we add a syntax (I propose ```:`<,`>```) for when we want comands to operate _only the selection itself_, _not all the lines that contain it_.

**Comment by gpanders** [comment] 2021-10-21 20:32
> can we not just beat them to it here in neovim?

Sure, PRs welcome. Or even better, send one to Vim and we can port it here so everyone benefits.

**Comment by 616b2f** [comment] 2023-07-31 17:58
can we close this as duplicate of https://github.com/neovim/neovim/issues/22297

**Closed** 2023-07-31 18:04 UTC
Labels: enhancement
