### ISSUE TITLE
The file field in callback arguments of the TabClosed event is expanded to an absolute path

### ISSUE THREAD

**Issue by NGPONG** [neovim/neovim#23941] opened 2023-06-06 16:26 UTC
### Problem

I tried to register two TabClosed events, and it looks like this (I only kept the following code in my init.lua)

```lua
local logger = require 'utils.log'

vim.api.nvim_create_autocmd("TabClosed", {
  group = vim.api.nvim_create_augroup('a', { clear = true, }),
  pattern = '*',
  callback = function(state)
    vim.fn.expand('<afile>')
    logger.info(state)
  end,
})

vim.api.nvim_create_autocmd("TabClosed", {
  group = vim.api.nvim_create_augroup('b', { clear = true, }),
  pattern = '*',
  callback = function(state)
    logger.info(state)
  end,
})
```

When I close a newly opened tabpage, the `file` field of the `state` output from `'a'` correctly feeds the tabpage number that is currently being closed, but the `file` field output from `'b'` is expanded to an absolute path, and the real output log looks like this

```
[INFO  Tue Jun  6 02:07:16 2023] _:9: {
  buf = 3,
  event = "TabClosed",
  file = "3", 
  group = 5,
  id = 3,
  match = "3"
}
[INFO  Tue Jun  6 02:07:16 2023] _:17: {
  buf = 3,
  event = "TabClosed",
  file = "/home/ngpong/neovim/3", <----------------
  group = 6,
  id = 4,
  match = "3"
}
```

The reason for this is that I called `vim.fn.expand('<afile>')` in the context of `'a'`'s callback function, and when I commented it out, everything worked fine.

I'm not quite sure if this is the expected behavior, because looking at the autocmd documentation in the section on TabClosed  explains:

> After closing a tab page. <afile> expands to the tab page number.

So I think that whether or not `vim.fn.expand('<afile>')` is used in the prior event's callback doesn't affect the file field of the current callback function.

### Steps to reproduce

1. nvim --clean -u my_issue.lua
2. :tabnew
3. :tabclose

```lua
for name, url in pairs {
  
} do
    local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
    if vim.fn.isdirectory(install_path) == 0 then
        vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
    end
    vim.opt.runtimepath:append(install_path)
end

local logger = require 'log'

vim.api.nvim_create_autocmd("TabClosed", {
  group = vim.api.nvim_create_augroup('a', { clear = true, }),
  pattern = '*',
  callback = function(state)
    vim.fn.expand('<afile>')
    logger.info(state)
  end,
})

vim.api.nvim_create_autocmd("TabClosed", {
  group = vim.api.nvim_create_augroup('b', { clear = true, }),
  pattern = '*',
  callback = function(state)
    logger.info(state)
  end,
})
```

### Expected behavior

Get the correct field value in the TabClosed event callback.

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Vim (not Nvim) behaves the same?

not sure

### Operating system/version

ubuntu22.04

### Terminal name/version

Windows terimal

### $TERM environment variable

xterm-256color

### Installation

ubuntu apt

**Comment by zeertzjq** [comment] 2023-06-07 00:31
Duplicate of #18964

**Closed by zeertzjq** 2023-06-07 00:31 UTC
Labels: closed:duplicate
