### ISSUE TITLE
sync

### ISSUE THREAD

**Issue by aloispichler** [neovim/neovim#23473] opened 2023-05-04 11:19 UTC
### Problem

I was writing LaTeX with nvim so far, it allowed syncing from the pdf to the source in nvim.
However, this is broken in the new release.

### Steps to reproduce

N/A

### Expected behavior

sync from the position in the pdf to the file in nvim.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch

### Terminal name/version

alacritty

### $TERM environment variable

xterm

### Installation

Arch

**Comment by bfredl** [comment] 2023-05-04 11:22
> I was writing LaTeX with nvim so far, it allowed syncing from the pdf to the source in nvim.

what plugin? what did you do? and what error message do you get now?

**Comment by clason** [comment] 2023-05-04 11:47
Probably a duplicate of https://github.com/lervag/vimtex/issues/2692.

**Closed by clason** 2023-05-04 11:47 UTC
Labels: bug, needs:response, needs:repro

**Comment by clason** [comment] 2023-05-04 11:50
This issue is not salvageable. If you use VimTeX -- as I suspect you do -- please open an issue (with _all_ the necessary details!) there first.

Needless to say, sync works fine for me.
