### ISSUE TITLE
`loadview` in a non-term buffer does weird things to a nearby term buffer

### ISSUE THREAD

**Issue by Soares** [neovim/neovim#5667] opened 2016-11-25 18:26 UTC
- `nvim --version`:

        NVIM 0.1.6

        Build type: RelWithDebInfo
        Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/build/config -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/src -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/build/src/nvim/auto -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/build/include
        Compiled by nate@Athena

        Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
        For differences from Vim, see :help vim-differences

           system vimrc file: "$VIM/sysinit.vim"
          fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.6/share/nvim"

- Vim (version: N/A) behaves differently? N/A
- Operating system/version: Mac OSX Yosemite 10.10.5
- Terminal name/version: iTerm2
- `$TERM`: `xterm-256color`

### Actual behaviour

Let's say I have a `test.txt` file and a `:term` buffer. If I `:loadview` on the `test.txt` file, it alters the term buffer such that the bottom line of the term buffer is halfway up the screen.

### Expected behaviour

Loading a view in `test.txt` should not affect the terminals in other buffers.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC test.txt
:mkview
:terminal
<C-^>
:loadview
<C-^>
```

**Comment by glacambre** [comment] 2021-06-05 11:54
I can't reproduce this on master so I'll close this issue. @Soares if you can still reproduce this bug, please let me know and I'll reopen :).

**Closed by glacambre** 2021-06-05 11:54 UTC
Labels: bug, topic: :terminal
