### ISSUE TITLE
Improper highlighting of some keywords in C comments

### ISSUE THREAD

**Issue by K4LCIFER** [neovim/neovim#16968] opened 2022-01-07 05:39 UTC
### Neovim version (nvim -v)

v0.7.0-dev+844-gb43575545

### Vim (not Nvim) behaves the same?

no, 8.2 (2019 Dec 12, compiled Dec 25 2021 11:17:40)

### Operating system/version

Arch Linux

### Terminal name/version

gnome-terminal 3.42.2

### $TERM environment variable

xterm-256color

### Installation

AUR

### How to reproduce the issue

1. Open a C file
2. Start a comment
3. Type any all caps word followed by a colon and observe that it gets highlighted incorrectly

### Expected behavior

I would only expect certain keywords like TODO or NOTE to be highlighted within a comment.

### Actual behavior

Any all caps word in a comment is highlighted if it is followed by a colon.
![image](https://user-images.githubusercontent.com/7829231/148497308-6e5f8058-b9b4-4c9a-b3b2-e11ff0f96088.png)
![image](https://user-images.githubusercontent.com/7829231/148497333-fd873596-010a-48b0-bd48-57680925800f.png)
![image](https://user-images.githubusercontent.com/7829231/148497351-19c3f8ec-c862-40e0-a719-da5d4427eea9.png)
![image](https://user-images.githubusercontent.com/7829231/148497378-900af72c-2079-4c52-8e46-0c9f446047af.png)
![image](https://user-images.githubusercontent.com/7829231/148497397-09b63292-d514-4347-af2c-0727f6551562.png)
![image](https://user-images.githubusercontent.com/7829231/148497466-ca7003b1-928a-4d2e-870b-cb43084abbdd.png)

ASIDE: I have also observed the same strange behaviour with other languages as well.

**Comment by zeertzjq** [comment] 2022-01-07 05:43
I cannot reproduce this. Please produce *minimal* steps to reproduce.

**Comment by K4LCIFER** [comment] 2022-01-07 05:57
I have also found that I have the same effect with other files as well: tried it with a `.vim` file and typed `" TEST:` and I observed the same effect. I think I have a broken syntax somewhere in my settings but I cannot locate it. Its not in my `init.vim`.

**Comment by K4LCIFER** [comment] 2022-01-07 06:11
> In this case Nvim should be run with `nvim --clean --cmd 'syntax on' foo.c`

Okay so I tried that with my `init.vim` file and got the same issue
![image](https://user-images.githubusercontent.com/7829231/148499992-243f289f-6cd9-43ee-a5b0-2de6d98aead9.png)
![image](https://user-images.githubusercontent.com/7829231/148500023-6a49f883-4f5f-4b03-abfa-5e344183a363.png)
![image](https://user-images.githubusercontent.com/7829231/148500038-d1377d06-f946-4dc7-a489-f197840f009f.png)
with one difference
![image](https://user-images.githubusercontent.com/7829231/148500066-a40c7bb1-7781-4fd5-91ba-bcb681d05ece.png)
BUT with a random `foo.c` I did not experience the same issue. So somehow that fixed C files but the issue persistes with vimscript...?

**Comment by zeertzjq** [comment] 2022-01-07 06:20
> but the issue persistes with vimscript...?

That's `vimCommentTitle`.

**Comment by zeertzjq** [comment] 2022-01-07 06:22
With your original `init.vim`, you can try installing <https://github.com/tpope/vim-scriptease> and pressing `zS` on the `TEST:` in a C file to see its syntax group.

**Comment by K4LCIFER** [comment] 2022-01-07 06:43
> With your original `init.vim`, you can try installing https://github.com/tpope/vim-scriptease and pressing `zS` on the `TEST:` in a C file to see its syntax group.

Alright I installed that, went to `TEST:` int the C file and hit `zS` but nothing happened.

**Comment by zeertzjq** [comment] 2022-01-07 06:49
What does `:echo getmatches()` print in a C file then?

**Comment by K4LCIFER** [comment] 2022-01-07 07:07
> What does `:echo getmatches()` print in a C file then?

It prints `[]`

**Comment by seandewar** [comment] 2022-01-07 10:20
I'm pretty certain this is from nvim-treesitter's highlight module. Can you confirm that `:TSBufDisable highlight` fixes this?

**Comment by seandewar** [comment] 2022-01-07 11:17
Just confirmed locally that this seems to be the case, so I'm closing this.
If you don't like this behaviour, consider sending an issue report to https://github.com/nvim-treesitter/nvim-treesitter.

**Closed by seandewar** 2022-01-07 11:17 UTC
Labels: bug, status:needs-response, status:needs-repro

**Comment by theHamsta** [comment] 2022-01-07 11:48
@K4LCIFER use `:TSUninstall comment`
