### ISSUE TITLE
seg fault because of tree-sitter-lua v0.0.13

### ISSUE THREAD

**Issue by seocamo** [neovim/neovim#20223] opened 2022-09-16 18:32 UTC
### Neovim version (nvim -v)

v0.8.0-dev-1098-gb616458af

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Manjaro

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

build the newest neovim, the problem start with [build(deps): bump tree-sitter-lua to v0.0.13](https://github.com/neovim/neovim/commit/279c7b11fb89776f89789ee7e0c4f2624a10d156)
you get seg fault

fish: Job 1, 'nvim' terminated by signal SIGSEGV (Address boundary error)
zsh: segmentation fault (core dumped)  nvim

if you git checkout the commit before
[docs(autocmds): re-add buffer param to docstring](https://github.com/neovim/neovim/commit/0f93aa12fdb07fd452706da8d13c590c86ce21de)
and it work 

### Expected behavior

it work

### Actual behavior

you get seg fault

fish: Job 1, 'nvim' terminated by signal SIGSEGV (Address boundary error)
zsh: segmentation fault (core dumped)  nvim

**Comment by seocamo** [comment] 2022-09-16 18:47
nvim start up with nvim --clean, and if the nvim-treesitter plugin is delete it start

**Comment by clason** [comment] 2022-09-16 18:50
We need exact reproduction steps with `nvim --clean` and the specific buffer it crashes with.

(Needless to say, it has been working fine for me and many others.)

**Comment by clason** [comment] 2022-09-16 18:51
Then it's not a Neovim problem?

**Comment by seocamo** [comment] 2022-09-16 20:25
well it can be some that neovim depend on, but i can build the commit before the tree-sitter-lua v0.0.13 amd it work fine but after that commit and neovim seg fault, i do need to have the nvim-treesitter plugin install for it to seg fault, but this plugin work fine with the old commit and a plugin should not make seg fault and die ?

**Comment by clason** [comment] 2022-09-16 20:28
First, nvim-treesitter replaces the parser. And if it is the parser that crashes (yet to be established), there is nothing Neovim can do to fix it).

**Comment by seocamo** [comment] 2022-09-16 20:31
ok, how can i get more info for you i am unsure? because it do work before that commit

**Comment by clason** [comment] 2022-09-17 08:38
I need complete reproducing steps: a _minimal_
1. `init.lua`  (not using nvim-treesitter)
2. `test.lua`

that I can run with `nvim --clean -u init.lua test.lua` to observe the crash.

**Comment by seocamo** [comment] 2022-09-18 13:44
you are right the bug is not in neovim it self, but it look like it is a error in MunifTanjim's tree-sitter-lua v 0.0.13 that is not in v 0.0.12
right now i can reproduces this with kyazdani42's nvim-tree.lua plugin and when calling the setup function(require"nvim-tree".setup{})

with packer.nvim to install them of course, i am still trying to see if i can find a few lines of the plugin that i can copy to a lua file that work with --clean

if anyone else has problems with nvim-tree.lua and the newest nightly like me, i just want add what i found.

ps. after removing all the plugins and only add 1 plugin at the time, i found that it do work with nvim-treesitter plugin, when this was missing it call require and it die, and i think that prevented it from calling autocmd/after code in the nvim-tree plugin.

**Comment by clason** [comment] 2023-11-29 14:02
Closing this since we've had no reports of this with later versions (current is v0.0.19). Feel free to open a new issue (with full reproduction steps, including the file!) if you observe it again with the current releases.

**Closed by clason** 2023-11-29 14:02 UTC
Labels: needs:repro, bug-crash, dependencies, treesitter
