### ISSUE TITLE
`compute_diff` doc has missing closing paren

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#23357] opened 2023-04-27 20:08 UTC
### Problem

Missing closing paren: https://github.com/neovim/neovim/blob/1cb60405548e79f1ec63921540e1c3ebb3ddcc01/runtime/doc/lsp.txt#L2137

**Comment by dundargoc** [comment] 2023-04-27 20:25
@ddickstein I can fix this, but for minor documentation issues like this don't hesitate to just send a quick PR instead 👍

**Comment by mfussenegger** [comment] 2023-04-28 18:26
I'm not sure why that method is even documented. Afaik the whole sync module was intended as internal

**Comment by clason** [comment] 2023-04-29 09:30
Seems intentional: https://github.com/neovim/neovim/pull/16285, but that decision can be revisited. Could even mark the function as internal (`_compute_diff`); it's only used in one place in the code.

@gpanders ?

**Comment by dundargoc** [comment] 2023-05-01 09:04
Closed by https://github.com/neovim/neovim/pull/23416

**Closed by dundargoc** 2023-05-01 09:04 UTC
Labels: documentation, typo
