### ISSUE TITLE
visual block commands not working with zero command height

### ISSUE THREAD

**Issue by robbienohra** [neovim/neovim#19044] opened 2022-06-22 00:39 UTC
### Neovim version (nvim -v)

v0.8.0-dev 6d52a29c3

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

macOS 12.4

### Terminal name/version

alacritty 10.1

### $TERM environment variable

alacritty

### Installation

from source (against nightly tag)

### How to reproduce the issue

- Set `cmdheight` to `0` 
- Select a visual block
- Enter `:`

### Expected behavior

Command prompt should become visible dynamically (as per recent feature merged [here](https://github.com/neovim/neovim/pull/16251)).

### Actual behavior

Mode is switched to command mode but command is not visible.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/28514482/174919023-a505d95b-00a1-4261-a0fb-8d56947021dc.png">

**Comment by zeertzjq** [comment] 2022-06-22 01:04
Duplicate of #18955

**Closed by zeertzjq** 2022-06-22 01:04 UTC
Labels: bug

**Comment by robbienohra** [comment] 2022-06-22 02:46
Thanks, @zeertzjq !
