### ISSUE TITLE
vim.cmd.close(2) does not work as vim.cmd.close{count=2}

### ISSUE THREAD

**Issue by pullant** [neovim/neovim#28015] opened 2024-03-24 20:08 UTC
### Problem

vim.cmd.close(2) does not work as vim.cmd.close{count=2}

from :help nvim_cmd()

    The first argument may also be used instead of count for commands that
    support it in order to make their usage simpler with |vim.cmd()|. For
    example, instead of `vim.cmd.bdelete{ count = 2 }`, you may do
    `vim.cmd.bdelete(2)`.

When using :lua vim.cmd.close(2) I get this error

    E5108: Error executing lua [string ":lua"]:1: Wrong number of arguments
    stack traceback:
        [C]: in function 'close'
        [string ":lua"]:1: in main chunk

### Steps to reproduce

    $ nvim --clean

Open two windows, close the second one with

    :lua vim.cmd.close(2)

### Expected behavior

vim.cmd.close() being able to take a count directly as vim.cmd.bdelete()

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1692716794

### Vim (not Nvim) behaves the same?

 Neovim behavior.

### Operating system/version

 Linux Mint 21.3

### Terminal name/version

Gnome Terminal 3.44.0

### $TERM environment variable

 xterm-256color

### Installation

built binary from repo

**Comment by zeertzjq** [comment] 2024-03-24 22:18
Duplicate of #23121

**Closed by zeertzjq** 2024-03-24 22:18 UTC
Labels: bug

**Comment by pullant** [comment] 2024-03-24 23:18
Oh, I see, it also happens in other commands and you are working on it. Sorry I could not find that related issue and pr before. Thank you zeertzjq!
