### ISSUE TITLE
Set terminal background to current scheme's when `termguicolors = true`

### ISSUE THREAD

**Issue by lbonn** [neovim/neovim#27173] opened 2024-01-24 09:26 UTC
### Problem

Now that neovim has a new default color scheme and that `termguicolors` is enabled by default, terminal users who did not use `termguicolors` are likely to see wrongly colored padding on the terminal borders when updating.

For example, see this alacritty issue https://github.com/alacritty/alacritty/issues/3746

### Expected behavior

There is a plugin that sends the correct escape sequence to fix this: https://github.com/typicode/bg.nvim.

But as the defaults have changed, it would make sense to do this in the stock configuration.

**Comment by zeertzjq** [comment] 2024-01-24 09:28
Duplicate of #16572

**Closed by zeertzjq** 2024-01-24 09:28 UTC
Labels: enhancement
