### ISSUE TITLE
Clicking with mouse incorrectly sets the cursor

### ISSUE THREAD

**Issue by kurkale6ka** [neovim/neovim#5801] opened 2016-12-20 13:55 UTC
- `nvim --version`: `NVIM v0.2.0-150-g33319b1bf`
- Vim (version: ) behaves differently? no
- Operating system/version: Arch Linux
- Terminal name/version: Sakura
- `$TERM`: `xterm-256color`

### Actual behaviour
clicking with mouse doesn't set the cursor where the arrow points

### Expected behaviour
clicking with mouse should set the cursor where the arrow points

### Steps to reproduce using `nvim -u NONE`

```
filetype plugin on
syntax on
help :map
```
Now clicking with the mouse doesn't set the cursor where the arrow points. Tested on the line with `mapmode-nvo`

**Comment by jamessan** [comment] 2016-12-20 14:09
I think this is a known issue with cursor placement when conceal is enabled.  Does it work properly if you `:set ft=` in the help buffer?

**Comment by jamessan** [comment] 2016-12-20 14:10
Hmm, although the issue I was thinking of (#5087) was supposed to have been fixed already by @tweekmonster.

**Comment by jamessan** [comment] 2016-12-20 14:11
Ah, this is likely a duplicate of #5341.

**Comment by kurkale6ka** [comment] 2016-12-20 14:16
it does work with `:set ft=` and sorry about the duplicate

**Comment by mhinz** [comment] 2016-12-20 14:51
Closing as duplicate of #5341.

**Closed by mhinz** 2016-12-20 14:51 UTC
