### ISSUE TITLE
Generates .nvimlog everywhere

### ISSUE THREAD

**Issue by NoahELE** [neovim/neovim#14806] opened 2021-06-14 04:58 UTC
- `nvim --version`: NVIM v0.5.0-dev+1386-gfd7e77b22
- Operating system/version: win 10
- Terminal name/version: windows terminal 1.8.1521.0
- `$TERM`: vtpcon

### Actual behaviour
Whenever I open nvim from a directory, it generates an empty .nvimlog file in that directory. I tried to create log folder in ~/.cache/nvim and ~\AppData\Local\nvim. But nvim does not generate any file in it. It always leave an empty .nvimlog file in the working directory.

### Expected behaviour
It should generate log file in a fixed place instead of generate empty log files everywhere.

My init.vim:

<details>

```
let $LANG='en'  " set message language
set langmenu=en   " set menu's language of gvim. no spaces beside '='

" use win shortcuts
source $VIMRUNTIME/mswin.vim
behave mswin

" vim-plug
call plug#begin('$VIM/plugged')
Plug 'mhinz/vim-startify'
Plug 'nlknguyen/papercolor-theme'
Plug 'morhetz/gruvbox'
Plug 'nanotech/jellybeans.vim'
Plug 'rakr/vim-one'
Plug 'yuttie/inkstained-vim'
Plug 'preservim/nerdtree'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'itchyny/lightline.vim'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-surround'
Plug 'scrooloose/nerdcommenter'
Plug 'raimondi/delimitmate'
Plug 'luochen1990/rainbow'
Plug 'easymotion/vim-easymotion'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'liuchengxu/vim-which-key'
call plug#end()
let g:ctrlp_map='<c-p>'
let g:ctrlp_cmd='CtrlP'
let g:ctrlp_working_path_mode='ra'
let g:lightline={'colorscheme':'deus'}
let g:rainbow_active=1

" font & colorscheme
set guifont=Source\ Code\ Pro:h12
set guifontwide=Sarasa\ Mono\ SC:h12
syntax on
set background=dark
colorscheme PaperColor

" personal configurations
set showmode
set showcmd
set guioptions=
set mouse=a
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,gbk,big5
set termencoding=utf-8
filetype plugin indent on
set autoindent
set expandtab
set smarttab
set number
set relativenumber
set cursorline
set ruler
set laststatus=2
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set visualbell
set nobackup
set noswapfile
set autoread
set autowrite
set wildmenu
set wildmode=list:longest,full
set wildignorecase
set timeoutlen=500 

" keymappings
let mapleader="\<Space>"
" which-key
nnoremap <silent> <leader> :WhichKey '<Space>'<CR>
" nerdtree
nnoremap <leader>nt :NERDTreeToggle<CR>
nnoremap <leader>nf :NERDTreeFind<CR>
nnoremap <leader>nc :NERDTreeCWD<CR>
" ctrlp
nnoremap <leader>p :CtrlP<CR>
" quit
noremap <leader>qq :q<CR>
noremap <leader>qQ :q!<CR>
noremap <leader>qs :wq<CR>
noremap <leader>qS :wqa<CR>
" files
noremap <leader>fs :w<CR>
noremap <leader>fS :wa<CR>
noremap <leader>ff :e 
" buffers
noremap <leader>bb :buffers<CR>
noremap <leader>bh :Startify<CR>
noremap <leader>bd :bdelete<CR>
noremap <leader>bn :bnext<CR>
noremap <leader>bp :bprevious<CR>
noremap <leader>bf :bfirst<CR>
noremap <leader>bl :blast<CR>
noremap <leader>b1 :b 1<CR>
noremap <leader>b2 :b 2<CR>
noremap <leader>b3 :b 3<CR>
noremap <leader>b4 :b 4<CR>
noremap <leader>b5 :b 5<CR>
noremap <leader>b6 :b 6<CR>
noremap <leader>b7 :b 7<CR>
noremap <leader>b8 :b 8<CR>
noremap <leader>b9 :b 9<CR>
" tabs
noremap <leader>tt :tabs<CR>
noremap <leader>te :tabe<CR>
noremap <leader>td :tabclose<CR>
noremap <leader>tn :tabnext<CR>
noremap <leader>tp :tabprevious<CR>
noremap <leader>t1 :tab 1<CR>
noremap <leader>t2 :tab 2<CR>
noremap <leader>t3 :tab 3<CR>
noremap <leader>t4 :tab 4<CR>
noremap <leader>t5 :tab 5<CR>
noremap <leader>t6 :tab 6<CR>
noremap <leader>t7 :tab 7<CR>
noremap <leader>t8 :tab 8<CR>
noremap <leader>t9 :tab 9<CR>
" windows
noremap <leader>ww <C-w>w
noremap <leader>wh <C-w>h
noremap <leader>wl <C-w>l
noremap <leader>wj <C-w>j
noremap <leader>wk <C-w>k
noremap <leader>wd <C-w>c
noremap <leader>ws <C-w>s
noremap <leader>wv <C-w>v
noremap <leader>w= <C-w>=
noremap <leader>wK <C-w>5-
noremap <leader>wJ <C-w>5+
noremap <leader>wH <C-w>5<
noremap <leader>wL <C-w>5>
" git
nnoremap <Leader>gg :Git<CR>
nnoremap <Leader>gd :Gdiffsplit<CR>
nnoremap <Leader>gc :Git commit<CR>
nnoremap <Leader>gb :Git blame<CR>
nnoremap <Leader>gl :Gclog<CR>
nnoremap <Leader>gp :Git push<CR>
nnoremap <Leader>gr :Gread<CR>
nnoremap <Leader>gw :Gwrite<CR>
nnoremap <Leader>ge :Gedit<CR>
nnoremap <Leader>ga :Git add .<CR>
nnoremap <Leader>gi :Git add -p %<CR>

```

</details>

**Comment by mjlbach** [comment] 2021-06-14 05:00
Dupe of https://github.com/neovim/neovim/issues/13753 you probably opened neovim as root the first time you started which wrote the first logfile as root, see https://github.com/neovim/neovim/pull/13758 for detailed debugging instructions

**Comment by ktrysmt** [comment] 2021-07-19 09:44
I encounted this bug too.

* Installed by homebrew `brew install neovim`
* Version: v0.5.0

I avoided this problem to down grading that `0.4.4`.
I had not launch nvim as admin (like using sudo), as far as I know..

**Comment by mjlbach** [comment] 2021-07-19 15:44
Hi,

Did you follow the instructions in #13578? Every time this has happened, it has been due to a permission issue with ~/.cache or ~/.cache/nvim or ~/.cache/nvim/log

See:
https://github.com/neovim/neovim/pull/13758#issuecomment-762462267

**Comment by justinmk** [comment] 2021-08-29 21:36
@NoahELE @ktrysmt what are the contents of the `.nvimlog` file? it should show a warning like this: https://github.com/neovim/neovim/blob/b35de6c525e7c8ad9d64d42f57f348dff608b9e5/src/nvim/log.c#L95-L96

else, what does `:echo $NVIM_LOG_FILE` report when you are running Nvim?

**Closed by justinmk** 2021-08-29 21:36 UTC
Labels: enhancement, ux, log

**Comment by NoahELE** [comment] 2021-08-30 01:13
@justinmk Nope, the nvimlog is empty. And I am using Windows, so there should not be a writing permission issue. I tried delete and recreate .nvmlog many times, but nvim does not write anything either in the file I created or the file it generates itself.

**Comment by justinmk** [comment] 2021-08-30 12:33
> what does `:echo $NVIM_LOG_FILE` report when you are running Nvim?

**Comment by NoahELE** [comment] 2021-08-30 12:34
![image](https://user-images.githubusercontent.com/49080986/131339668-1ce85053-397c-4423-a646-abca86c11033.png)

![image](https://user-images.githubusercontent.com/49080986/131339581-933692c5-90ac-4cc5-bf4a-2b2777fc2fab.png)

**Comment by kuremu** [comment] 2022-01-24 02:09
> > So, have anyone solve the problem? To avoid it, I went back to use Version 0.4.4. However, in Version 0.4.4, there are some problems with Backspace too.
> 
> This has always ended up being a permissions issue on the users systems. I provided links to detailed debugging steps in [#14806 (comment)](https://github.com/neovim/neovim/issues/14806#issuecomment-882654384)
> 
> but usually `sudo rm -rf ~/.cache/nvim` is sufficient. I also gave detailed instructions on how to use the debugger to identify exactly why the default log location is failing starting with this comment: [#13758 (comment)](https://github.com/neovim/neovim/pull/13758#issuecomment-762434477)

`sudo chown -R <user>:<user> /home/<user>/.cache/nvim`

worked for me.

**Comment by We-unite** [comment] 2023-03-02 15:43
Sorry to bother, I've met the same problem today, While opening a file in nvim-qt, there's a .vimlog built in current directory. Some times it's empty, sometimes it encounters an error and not empty. So do you know how to deal with it forever? I don't want a log in any occasion. Thanks!

**Comment by zeertzjq** [comment] 2023-06-30 13:33
That sounds like a permission issue in `~/.local/state/`

**Comment by clason** [comment] 2023-06-30 13:35
No, that analysis is not correct. I'm on macOS Ventura as well, don't have these values set, and the logs are written to `~/.local/state/nvim` just fine. As @zeertzjq writes (and the earlier comments explain), a permission issue somewhere in this directory chain is the most likely cause.
