### ISSUE TITLE
buftype variable not cleared for tab drop when splitright is true

### ISSUE THREAD

**Issue by ilovehans10** [neovim/neovim#27758] opened 2024-03-06 22:35 UTC
### Problem

My workflow is having a buffer open with my project in it, and in a vsplit buffer next to it having a term://zsh buffer to manually run commands in. I also have a normal mode mapping for ```<Space>ev``` to edit my init.lua in a new tab (using tab drop as to not create unnecessary tabs). Currently, when I have my workspace open and go to edit my vimrc with my mapping it will open the tab as expected, but it starts me out in insert mode.

This has been bothering me for months, and I finally decided to do some digging to see what might be causing it, and it seems to only happen in somewhat specific circumstances.

### Steps to reproduce

1. Open a file (doesn't work with an empty buffer) using the minimal init.lua attached below.
2. Use ```<Space>t``` to open a terminal in a vertical split to the right of the main buffer.
3. Use ```<C-h>``` to return to normal mode and move to the text buffer.
4. Type ```<Space>ev``` to be brought to a new tab with the nvim config, just to find that it is in insert mode instead of normal mode.

```
vim.g.mapleader = " "

vim.opt.splitright = true

local keyset = vim.keymap.set
keyset("n", "<leader>t", ":vsplit term://zsh<CR>")
keyset("n", "<leader>ev", (":tab drop ~/.config/nvim/init.lua<CR>"))
keyset("t", "<C-h>", "<C-\\><C-N><C-w>h")

vim.api.nvim_create_augroup("myterm", {})
vim.api.nvim_create_autocmd("BufEnter", { group = "myterm", command = "if &buftype ==# 'terminal' | startinsert | endif" })
```

### Expected behavior

What I expect is for my init.lua to open in a new tab and be in normal mode. From my testing it appears that when ```splitright``` is enabled and a terminal is opened, ```BufEnter``` autocommands run on the new tab will act as if their ```buftype``` is "terminal".

This works as expected if any of the following is true:
```splitright``` is set to false
```tab new``` is used in place of ```tab drop``` on line 8 of the vimrc
you manually type ```:tab drop ~/.config/nvim/init2.lua<CR>``` instead of using the mapping

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2191+g4e59422e1-Homebrew

### Vim (not Nvim) behaves the same?

no, vim 9.0.2018 (vim can't use lua configuration)

### Operating system/version

macOS 14.2.1

### Terminal name/version

iTerm2 3.4.20

### $TERM environment variable

xterm-256color

### Installation

Homebrew

**Comment by zeertzjq** [comment] 2024-03-07 00:01
As mentioned in https://github.com/vim/vim/issues/12087#issuecomment-1509735990 this is the intended behavior:

> What happens is that Vim goes over
all the windows and might close some, those that are not in the updated
argument list.

> However, if we would leave out the autocommands in this
specific situation, and still trigger them for the "tab all" command, it
gets inconsistent.

**Comment by zeertzjq** [comment] 2024-03-07 00:02
And this can be considered a duplicate of #14567

**Closed by zeertzjq** 2024-03-07 00:01 UTC
Labels: bug
