### ISSUE TITLE
Loading python is slow when first start neovim

### ISSUE THREAD

**Issue by lazywei** [neovim/neovim#2437] opened 2015-04-16 01:49 UTC
Hi,

I notice that there is a notable delay when open neovim first time. That is, if I quit neovim and re-start neovim, the delay is gone. And if I don't use neovim for a while (maybe half of hour) and start neovim again, the delay will appear again.
### First time startuptime

```
000.014  000.014: --- NVIM STARTING ---
000.734  000.720: locale set
002.408  001.675: inits 1
002.429  000.021: window checked
002.435  000.006: parsing arguments
002.437  000.002: expanding arguments
003.401  000.964: inits 2
003.575  000.174: init highlight
009.639  000.940  000.940: sourcing /Users/lazywei/Projects/neovim/runtime/autoload/remote/host.vim
2994.097  2986.094  2985.154: sourcing /Users/lazywei/Projects/neovim/runtime/autoload/provider/python.vim
```
### Second time startuptime

```
000.134  000.134: --- NVIM STARTING ---
000.769  000.635: locale set
001.420  000.651: inits 1
001.438  000.018: window checked
001.443  000.005: parsing arguments
001.445  000.002: expanding arguments
001.887  000.442: inits 2
002.030  000.143: init highlight
003.247  000.388  000.388: sourcing /Users/lazywei/Projects/neovim/runtime/autoload/remote/host.vim
104.763  102.032  101.643: sourcing /Users/lazywei/Projects/neovim/runtime/autoload/provider/python.vim
```

The loading time of `python.vim` is very difference between the above two.

**Comment by Shougo** [comment] 2015-04-16 01:51
I think it is python loading overhead.

Please test https://github.com/neovim/neovim/pull/2208.

**Comment by Shougo** [comment] 2015-04-16 01:52
> And if I don't use neovim for a while (maybe half of hour) and start neovim again, the delay will appear again.

It is (disk?) cache behavior.  It is not neovim related problem.

**Comment by tarruda** [comment] 2015-04-16 02:12
> It is (disk?) cache behavior. It is not neovim related problem.

:+1: 

I also notice this, whenever I reboot the machine it takes a little extra time to load

**Comment by Shougo** [comment] 2015-04-16 02:19
I improved the python loading in #2208.   And you can skip the check by `g:python_host_skip_check` variable.  If enabled it, the overhead is almost same with Vim.

**Comment by lazywei** [comment] 2015-04-16 02:21
OK, got it. How is #2208 going then? Would it be merged soon?

**Comment by Shougo** [comment] 2015-04-16 02:29
The code changes are done and it works.  I must rebase the codes though.
If #2208 is merged, it is closable.

**Comment by lazywei** [comment] 2015-04-24 09:53
I think this issue is solved :+1: 
Thanks @Shougo for the great efforts!

**Comment by lazywei** [comment] 2015-05-28 11:53
@Shougo it looks like python again causes the slow startuptime -- although not that significant this time

```
120.449  000.081  000.081: sourcing /Users/lazywei/Projects/neovim/runtime/autoload/provider/pythonx.vim
427.915  308.630  308.549: sourcing /Users/lazywei/Projects/neovim/runtime/autoload/provider/python3.vim
627.945  001.046  001.046: sourcing /Users/lazywei/Projects/neovim/runtime/autoload/remote/host.vim
628.224  198.926  197.880: sourcing /Users/lazywei/Projects/neovim/runtime/autoload/provider/python.vim
```

any idea why is that? or 3xx ms is kind of acceptable?
Thanks

**Comment by Shougo** [comment] 2015-05-29 01:14
@lazywei You can disable the check by `let g:python_host_skip_check = 1` and `let g:python3_host_skip_check = 1`.

**Comment by Shougo** [comment] 2015-05-29 01:15
@lazywei I think your plugins use `:python` automatically.  You should disable it or lazy loading.

**Comment by lazywei** [comment] 2015-05-29 02:04
Disable the host check raise weird errors.

I found the reason is that ultisnips loads python automatically, after switching to neosnippet, everything works fine. There is no slow python loading anymore.

Thanks

**Comment by Shougo** [comment] 2015-05-29 02:16
> Disable the host check raise weird errors.

Really?  Please create new issue for it.  I will check it.

**Comment by lazywei** [comment] 2015-05-29 02:28
Oh, it turns out it is fake alarm. The error comes from ultisnips. After removing it, disabling python host check works fine.
Thanks

**Comment by liujoey** [comment] 2015-12-03 16:00
I'm experience the same issue on my new Mac book pro 15". It's annoying. The first load time on my Mac is 10x times slower than my 4 years old Linux laptop with the same configuration.
@lazywei Would you please let me know how to generate the time report as you did? I want to measure the time differences.

The other thing is my Mac has FileVault enabled and Antivirus software (Sophos) installed -- due to company policy -- don't know how much impact caused by these two.

**Comment by liujoey** [comment] 2015-12-03 16:57
[1stStart.txt](https://github.com/neovim/neovim/files/51073/1stStart.txt)
[2ndStart.txt](https://github.com/neovim/neovim/files/51074/2ndStart.txt)

Added two log files. It looks really is the file caching mechanism issue. But I just don't understand why it is that much slower than a Linux. So I will try the configure on a Mac without FileVault and Antivirus.

**Comment by justinmk** [comment] 2015-12-03 17:00
@liujoey So 1stStart is "cold" start and 2ndStart is "warm" (i.e. you ran it again without any configuration changes, immediately after 1stStart)?

**Comment by liujoey** [comment] 2015-12-03 17:38
Yes, it is correct.

If I put the system in idle about ~2 hours, then the system become "cold" again. Never experience this in Linux before, so I'm very curious about how OS X handle IO caching.

**Comment by justinmk** [comment] 2015-12-05 20:59
Yes, 4s is quite bad for SSD, seems more like a Neovim issue.

**Comment by liujoey** [comment] 2015-12-11 04:39
@justinmk It is because YouCompleteMe. When I change to deoplete, no more slow down.

**Comment by Shougo** [comment] 2015-12-11 11:58
@liujoey I think it should be closed.

**Comment by liujoey** [comment] 2015-12-18 13:45
@justinmk @Shougo 

It seems the issue is related to a function call to `rpcrequest`. I have profiled the startup time, two functions `provider#python#Call()` and `<SNR>32_RequirePythonHost()` are very slow and both of them uses `rpcrequest`, any clue?

By the way, this is Mac Book pro 2015 with El Capitan, hard disk is SSD. 

```
FUNCTION  provider#python#Call()
Called 4 times
Total time:   4.669450
 Self time:   2.472237

count  total (s)   self (s)
    4              0.000017   if s:err != ''
                                return
                              endif
    4              0.000014   if !exists('s:host')
    1              0.000004     let s:rpcrequest = function('rpcrequest')
                            
                                " Ensure that we can load the Python host before bootstrapping
    1              0.000002     try
    1   2.197229   0.000016       let s:host = remote#host#Require('legacy-python-provider')
    1              0.000001     catch
                                  let s:err = v:exception
                                  echohl WarningMsg
                                  echomsg v:exception
                                  echohl None
                                  return
                                endtry
    1              0.000001   endif
    4              2.472098   return call(s:rpcrequest, insert(insert(a:args, 'python_'.a:method), s:host))
```

```
FUNCTION  <SNR>32_RequirePythonHost()
Called 1 time
Total time:   2.197154
 Self time:   2.197146

count  total (s)   self (s)
    1              0.000002   let ver = (a:host.orig_name ==# 'python') ? 2 : 3
                            
                              " Python host arguments
    1              0.000002   let args = ['-c', 'import sys; sys.path.remove(""); import neovim; neovim.start_host()']
                            
                              " Collect registered Python plugins into args
    1   0.000012   0.000005   let python_plugins = remote#host#PluginsForHost(a:host.name)
    2              0.000003   for plugin in python_plugins
    1              0.000010     call add(args, plugin.path)
    1              0.000001   endfor
                            
    1              0.000001   try
    1   0.034266   0.034265     let channel_id = rpcstart((ver == '2' ? provider#python#Prog() : provider#python3#Prog()), args)
    1              2.162823     if rpcrequest(channel_id, 'poll') == 'ok'
    1              0.000013       return channel_id
                                endif
                              catch
                                echomsg v:exception
                              endtry
                              throw 'Failed to load Python host. You can try to see what happened '. 'by starting Neovim with the environment variable '. '$NVIM_PYTHON_LOG_FILE set to a file and opening '. 'the generated log file. Also, the host stderr will be available '. 'in Neovim log, so it may contain useful information. '. 'See also ~/.nvimlog.'
```

**Comment by mhinz** [comment] 2015-12-18 15:22
Examing the second sample first: I expect a delay when `provider#python#...` is called for the first time, although 2 seconds is twice as long than it takes on my early 2014 MBA.

First sample: 2.5s for 4 calls to `rpcrequest()` is definitely too long, IMHO. Hmm..

**Comment by Shougo** [comment] 2015-12-18 23:24
I think @tarruda knows the reason...

**Comment by liujoey** [comment] 2016-02-26 20:00
I don't know what happened recently, I've just upgraded to 0.1.2 and this issue was gone. Rebooted my OS X to confirm, the first time when i launch nvim, the speed looks normal now.

**Comment by wsdjeg** [comment] 2016-02-27 01:34
I do not know if it is same as https://github.com/wsdjeg/DotFiles/issues/22

**Comment by liujoey** [comment] 2016-10-24 03:47
I believe I found my problem, it is because the Anti-Virus software. I don't know how does it affect the Python performance, but as soon as I removed the Sophos for Mac, the issue I described just gone. Since the Anti-Virus software was installed by Corp. Security policy, I'm sure it will be reinstalled after next security scan, but as for now I can sleep in peace.

**Comment by justinmk** [comment] 2016-10-24 08:59
@liujoey Thanks for the followup, that makes sense. In my experience, corporate AV on Windows caused a 3x slowdown for many `git` operations. Is `git` faster for you after disabling the AV? 

AV "realtime inspection" inserts itself on every process start, so programs like `git` which often spawn  child-processes will be slower, and that would also be the case for `nvim` spawning `python` processes. Are you able to request exceptions for e.g. python?

Note also that setting `g:python_host_prog` and/or `g:python3_host_prog` should help (see `:help g:python_host_prog`).

**Comment by sassanh** [comment] 2016-11-27 03:17
With
```
    let g:loaded_python_provider = 1
    let g:loaded_python3_provider = 1
```

command `vim --cmd 'au VimEnter * :q' takes .5s both for vim and nvim,  with
```
    let g:loaded_python3_provider = 1
```
nvim takes .65s and without any python disablers at all nvim takes .85s. Is it related to this thread or should I create another issue or aren't we going to take care of it at all?

(I do have
```
    let g:python_host_skip_check = 1
    let g:python3_host_skip_check = 1
```
for all above tests)

**Comment by nongiach** [comment] 2017-06-09 10:37
One solution that I found is to add this to my ~/.xinitrc
`nvim -c quit &`
There will always be an overhead the first time, let's embrace it, it's for the better good after all.
After that my startup time is 243ms with a lot of plugins installed.

**Comment by drozdowsky** [comment] 2019-06-27 20:04
I do not have `python_host_skip_check` in 0.3.7.
Problem with slow start is still persistent, it is a bit better on second launch.

**Comment by p10q** [comment] 2019-08-17 13:26
I know this is not optimal. But if I hardcode this:
```
" Returns array: [was_success, error_message] 
function! provider#pythonx#CheckForModule(prog, module, major_version) abort                            │
  return [0, '3.6']
```
I see a significant speedup in starting time (as a user of spacevim). Fwiw I tried setting `g:python_host_skip_check=1` and `g:python3_host_skip_check=1`, but couldn't quite get that to work.

**Comment by Shougo** [comment] 2019-08-17 13:29
`g:python_host_skip_check` and `g:python3_host_skip_check` is not used.
Because this is old issue.

You must set `g:python_host_prog` and `g:python3_host_prog` instead.

```vim
let g:python_host_prog  = '/usr/bin/python2'
let g:python3_host_prog = '/usr/bin/python3'
```

**Comment by p10q** [comment] 2019-08-17 13:38
Thanks for the fast response! Right, I had tried setting that too (I just experimented with that again by setting that in `~/.SpaceVim.d/autoload/myspacevim.vim` and `~/.SpaceVim/config/init.vim`). And for some reason that's not taking effect for me. That is, it does show the correct version when I do `:checkhealth plugin`. But somehow it's not preventing the `/usr/local/share/nvim/runtime/autoload/provider/pythonx.vim` from running as far as I can tell. Will keep checking why though (maybe something else is unique with my setup). Thanks again.

**Comment by p10q** [comment] 2019-08-17 14:08
Finally figured out the root cause for me is that Python loading happens much earlier in SpaceVim than I thought. For others reference I needed to set the above above two lines (for `python_host_prog` and `python3_host_prog`) in `~/.SpaceVim/config/main.vim` at the top and then it worked. Thanks again.

**Comment by Shougo** [comment] 2022-10-06 07:09
Unfortunately, the slow is neovim feature.
You can set `g:python3_host_prog` and you should not call Python interface on startup.

**Comment by notwidow** [comment] 2022-10-06 12:41
> Unfortunately, the slow is neovim feature. You can set `g:python3_host_prog` and you should not call Python interface on startup.

yeah i set it and still a bit slow. they need to fix it.

**Comment by Shougo** [comment] 2022-10-06 22:29
Vim is faster loading than neovim, but you cannot avoid slowness.

**Comment by notwidow** [comment] 2022-10-09 17:28
> Vim is faster loading than neovim, but you cannot avoid slowness.
> 
> And who is the they?

ahm what? did not get your point

**Comment by justinmk** [comment] 2024-02-15 13:11
> Note also that setting `g:python_host_prog` and/or `g:python3_host_prog` should help (see `:help g:python_host_prog`).

Duplicate of https://github.com/neovim/neovim/issues/7063

**Closed by justinmk** 2024-02-15 13:11 UTC
Labels: performance, provider, startup, remote, closed:duplicate
