### ISSUE TITLE
LSP: vim.lsp.diagnostic.show_line_diagnostics : `expected table, got nil` with latest nightly

### ISSUE THREAD

**Issue by getreu** [neovim/neovim#15773] opened 2021-09-24 05:54 UTC
### Neovim version (nvim -v)

NVIM v0.6.0-dev+331-gaba397991

### Vim (not Nvim) behaves the same?

don't know
Edit: BTW, Neovim 0.5 stable does not have this issue

### Operating system/version

Debian 11

### Terminal name/version

XTerm(366)

### $TERM environment variable

xterm-256color

### Installation

neovim.appimage

### How to reproduce the issue

Update: 1. and 3. are not necessary. The error occurs also when I open a regular Markdown file.

1. install the latest nightly version of `rust-analyzer`
2. open a Rust source code file
3. wait a bit that`Rust-analyzer` processes the project
4. observe the error message in the undermost line
    ```
    Error detected while processing CursorHold Autocommands for "*":
    E5108: Error executing lua vim/shared.lua:199: Expected table, got nil
    ```

I am following _Rust-analyzer_'s  and _Neovim_'s almost on a daily bases. Therefore I suppose that the bug was introduced within the last week.

### Expected behavior

No error message.

### Actual behavior

The above error message

**Comment by mjlbach** [comment] 2021-09-24 06:48
I assume you have a custom CursorHold auto command calling a handler with the old style signature. Can you show that requisite line from your init.lua?

**Comment by getreu** [comment] 2021-09-24 09:15
I found a `CursorHold auto command` in `init.vim`: 

```vim
autocmd CursorHold * lua vim.lsp.diagnostic.show_line_diagnostics()
```

**Comment by justinmk** [comment] 2021-09-24 09:40
so can you try `:lua vim.lsp.diagnostic.show_line_diagnostics()` manually, does it work, if not, try to narrow down where it fails exactly.

**Comment by getreu** [comment] 2021-09-24 14:30
@justinmk I had to quickly switch back to v0.5.0 to start working. Unfortunately I did not keep the latest `nvim.appimage` so I can not do your suggested test now. I will wait for the next nightly and give you feedback then. So far I can tell that the error does not show up with v0.5.0.

**Comment by gpanders** [comment] 2021-09-24 15:41
I can't reproduce this with a simple test file:

```rust
fn main() {
    println!("Hello world!");
}
```

Are you absolutely sure you're using the latest master version? We *just* fixed some bugs in `show_line_diagnostics()` yesterday. If so, then can you send me a file that you're able to reproduce the issue in?

**Comment by getreu** [comment] 2021-09-24 17:03
I first observed this when I started working this morning. This is why I thought it was related to `rust-analyzer` or Rust in general. Later I opened a simple Markdown file and the error showed up also.

> Are you absolutely sure you're using the latest master version? We _just_ fixed some bugs in `show_line_diagnostics()` yesterday. If so, then can you send me a file that you're able to reproduce the issue in?

Absolutely. I tested `NVIM v0.6.0-dev+331-gaba397991`.

**Comment by justinmk** [comment] 2021-09-24 19:20
> Absolutely. I tested `NVIM v0.6.0-dev+331-gaba397991`.

https://github.com/neovim/neovim/commit/aba397991 is from 2 days ago. Bugs were fixed yesterday.

**Comment by getreu** [comment] 2021-09-24 19:26
Then I will try with tomorrows nightly again. Thank you.

BTW: I found an older version `NVIM v0.6.0-dev+284-gc2a65921d` approx. one week old, which  does not have this problem.

**Comment by mjlbach** [comment] 2021-09-24 19:27
Thanks! Almost certain it will fix your issue, there have been a ton of changes recently around the diagnostics module so it is expected older commits will not have the same issues as master, but your particular bug should be fixed.

**Closed** 2021-09-24 21:05 UTC
Labels: bug, status:needs-response, status:needs-repro, lsp

**Comment by getreu** [comment] 2021-09-26 09:29
I tested today's nightly and can confirm that the issue fixed. Thank you for your fast reply and help.
