### ISSUE TITLE
Ansi escape code to change cursor shape cannot work in neovim's :terminal

### ISSUE THREAD

**Issue by Freed-Wu** [neovim/neovim#30671] opened 2024-10-05 14:12 UTC
### Problem

https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797?permalink_comment_id=5165100#gistcomment-5165100

printf "\e[3 q" should change the cursor shape. However, in neovim's `:terminal` cannot work.

### Steps to reproduce

1. `:terminal`
2. `printf "\e[3 q"

### Expected behavior

Cursor shape has changed

### Nvim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

haven't tested

### Operating system/version

NixOS unstable

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

xterm-256color

### Installation

nix

**Comment by zeertzjq** [comment] 2024-10-05 14:25
Duplicate of #3681

**Closed by zeertzjq** 2024-10-05 14:25 UTC
Labels: bug
