### ISSUE TITLE
Show workspace diagnostics in qflist instead of loclist

### ISSUE THREAD

**Issue by MrcJkb** [neovim/neovim#14830] opened 2021-06-16 11:32 UTC
### Actual behaviour

Currently,  `vim.lsp.diagnostic` exposes a function `set_loclist`, which by default adds diagnostics for the current buffer to the location list, and can be configured to add all workspace diagnostics (via `opts.workspace`).

### Expected behaviour

I find it irritating to have to use the loclist for workspace-wide diagnostics. Wouldn't the quickfix list make more sense in this case?

**Comment by MrcJkb** [comment] 2021-06-16 11:35
I have added a PR with a rough example.

**Comment by clason** [comment] 2021-06-16 12:03
Duplicate of https://github.com/neovim/neovim/issues/14481, I think.

**Comment by MrcJkb** [comment] 2021-06-16 13:32
Agreed.
I guess my main issue with the current implementation is inconsistency. There are many LSP handlers that populate the quickfix list (e.g. `textDocument/references`, `textDocument/documentSymbol`, ...).
And then there's a convenience function for populating the location list with diagnostics (that is well-documented), but not for populating the quickfix list.

Come to think of it, wouldn't it be better if you could configure which list to populate for each handler or diagnostics convenience function, respectively? I can think of many use cases in which the location list would be more suitable for references and document symbols than the quickfix list.

**Comment by clason** [comment] 2021-06-16 13:36
The _real_ fix here is to get away from the rigid single `qflist` and `loclist`s and introduce a generic (namespaced) `list` API that functions can use to avoid clobbering each other (and neovim). But not for 0.5 :)

**Comment by mjlbach** [comment] 2021-06-16 16:56
> Come to think of it, wouldn't it be better if you could configure which list to populate for each handler or diagnostics convenience function, respectively?

You can, with an override :) 

> And then there's a convenience function for populating the location list with diagnostics (that is well-documented), but not for populating the quickfix list.

This is about a 5 minute fix. Do people want two separate functions with shared logic, or an option to toggle between qf/loclist

**Comment by MrcJkb** [comment] 2021-06-17 10:16
> > Come to think of it, wouldn't it be better if you could configure which list to populate for each handler or diagnostics convenience function, respectively?
> 
> You can, with an override :)

Good point.

> This is about a 5 minute fix. Do people want two separate functions with shared logic, or an option to toggle between qf/loclist

Of course a toggle option would be better in this case. The reason I didn't choose that option in my PR is because it would require a rename of the existing `set_loclist` function.

**Comment by mjlbach** [comment] 2021-09-28 22:07
With the diagnostic changes, we're deprecating these internal lsp utilities in favor of the diagnostic ones, and it's fairly easy with the diagnostic API to customize how you add things to the qf/location list anyways cc @gpanders @neovim/lsp

**Closed by mjlbach** 2021-09-28 22:07 UTC
Labels: enhancement, lua, lsp
