### ISSUE TITLE
nvim hangs at start and/or exit when fstab has NFS mount

### ISSUE THREAD

**Issue by laur89** [neovim/neovim#12808] opened 2020-08-29 18:11 UTC
- `nvim --version`:

```NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-eK2ojg/neovim-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-eK2ojg/neovim-0.4.4/build/config -I/build/neovim-eK2ojg/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-eK2ojg/neovim-0.4.4/build/src/nvim/auto -I/build/neovim-eK2ojg/neovim-0.4.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
Nope, still same; also tried `nvim -u NONE`

- Operating system/version:
Debian testing (currently bullseye)
`Linux WH5005264 5.7.0-2-amd64 #1 SMP Debian 5.7.10-1 (2020-07-26) x86_64 GNU/Linux`
- Terminal name/version: `rxvt-unicode-256color`, 9.22-8
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

I'ts sometimes intermittent, but whenever nfs has mount definition in /etc/fstab and computer is restarted, then nvim starts acting up; mostly it's hanging when exiting (doesn't matter whether it's q, q!, qa, qa! et al), but sometimes hanging also happens when nvim is launched.

Note I'm not trying to open a file on the mount; reproduces by just opening an existing local file or a nonexisting one eg on `/tmp`.

/etc/fstab entry:
```
192.168.0.2:/mnt/on/remote /mnt/local nfs noauto,x-systemd.automount,x-systemd.mount-timeout=10,_netdev,x-systemd.device-timeout=10,timeo=14,rsize=8192,wsize=8192 0 0
```

Issues disappear once fstab entry is removed and system is rebooted.

**Comment by KillTheMule** [comment] 2020-08-29 18:56
This probably needs a bit more reproduceability. I am using nvim at work on a machine with a real lot of NFS mounts, but I've not observed any issues on startup/exit.

**Comment by laur89** [comment] 2020-08-29 19:07
Could you paste your fstab entry?

**Comment by KillTheMule** [comment] 2020-08-29 19:24
There are 2 entries like this:

```
--path1--  --target1--        nfs rw,bg,hard,intr,proto=tcp,nfsvers=3 0 0`
```
There are quite some more nfs mounts present, quite some of which have type `autofs` (not sure  what that really means, I assumed that those are nfs as well), but I have no idea where they're coming from.

**Comment by laur89** [comment] 2020-08-29 20:15
Cheers, I'll read up on the params again and give it a go. Fyi afaik `intr` is not supported by later kernels.

**Comment by justinmk** [comment] 2020-08-30 02:31
> mostly it's hanging when exiting

sounds related to 'fsync' . you might try `:set nofsync` though that is the default, but maybe your config or a plugin is setting 'fsync' ?

**Comment by laur89** [comment] 2020-08-30 12:09
Cheers, will try `:set nofsync`

> maybe your config or a plugin is setting 'fsync' ?
I also reproduced this via `nvim -u NONE`, that opens nvim in a stock setup right?

**Comment by justinmk** [comment] 2020-08-30 17:21
> I also reproduced this via `nvim -u NONE`, that opens nvim in a stock setup right?

yes

**Comment by justinmk** [comment] 2020-09-01 08:02
sounds like https://github.com/neovim/neovim/issues/12075 .  Closing in favor of that since it has repro steps

I wonder what changed, that we have two similar reports like this? Never heard of this since 2014...

**Closed by justinmk** 2020-09-01 08:02 UTC
Labels: bug, io, needs-repro, system
