### ISSUE TITLE
Buffer hides after executing ```:terminal ls```

### ISSUE THREAD

**Issue by max-0406** [neovim/neovim#18061] opened 2022-04-09 22:48 UTC
### Neovim version (nvim -v)

0.7.0-dev+1385-g6786b6afa

### Vim (not Nvim) behaves the same?

no, vim 8.2.4651

### Operating system/version

ArchLinux

### Terminal name/version

rxvt-unicode 9.26

### $TERM environment variable

rxvt-unicode-256color

### Installation

build from repo

### How to reproduce the issue

nvim --clean
:edit a.txt
:vsplit b.txt
:terminal ls
```i```
```<Enter>```

### Expected behavior

Two buffers display side by sdie. 

![2022-04-10_06:43:44](https://user-images.githubusercontent.com/74842863/162593915-edbcae3d-048a-4c1d-8df0-42d48624889c.jpg)

### Actual behavior

The buffer with b.txt becomes hidden.

![2022-04-10_06:44:37](https://user-images.githubusercontent.com/74842863/162594011-7aed7f6f-246d-415a-9cf7-3a2f0ec82dcd.jpg)

**Comment by zeertzjq** [comment] 2022-04-09 23:03
Duplicate of #5176

**Closed by zeertzjq** 2022-04-09 23:03 UTC
Labels: bug
