### ISSUE TITLE
Glitch for a Long Line with Trailing Spaces

### ISSUE THREAD

**Issue by e-kwsm** [neovim/neovim#24955] opened 2023-08-30 23:22 UTC
### Problem

Visual glitch occurs when a line has any non-space characters whose columns are less than or equal to the terminal width, and so many trailing spaces that the line length is greater than twice of the terminal width.

![long](https://github.com/neovim/neovim/assets/11627708/a9df737a-ac11-4ff0-b677-7997a2b3ff71)

### Steps to reproduce

Set the terminal width to 80.

Download [a.txt](https://github.com/neovim/neovim/files/12480777/a.txt) and open it. The line length of the first line is 161.
Move the cursor.

Redraw fixes the glitch.

### Expected behavior

No visual glitch.

### Neovim version (nvim -v)

v0.10.0-dev-995+gb2c3e9c72

### Vim (not Nvim) behaves the same?

no, vim 9.0.1736

### Operating system/version

EndeavourOS

### Terminal name/version

GNOME Terminal 3.48.2 using VTE 0.72.2 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment] 2023-08-30 23:36
Seem to be caused by #23891

**Comment by zeertzjq** [comment] 2023-08-31 04:03
This unconditional final column wrap doesn't look correct:
https://github.com/neovim/neovim/blob/ee56daebb6468075e743db0d605cb3f2a1699419/src/nvim/tui/tui.c#L1479

If the next call to `tui_raw_line()` wants to clear the next screen line, it doesn't print any characters, so in most terminals cursor hasn't advanced to the next screen line yet, and the cursor row on the grid is wrong.

I think this call should be removed, as `print_cell()` already calls `final_column_wrap()` when appropriate.

@rickyz @bfredl Any ideas?

**Comment by bfredl** [comment] 2023-08-31 08:14
> I think this call should be removed, as print_cell() already calls final_column_wrap() when appropriate.

Not in order to implement the wrapping line behavior of `kLineFlagWrap`. for the vast majority of terminals, `print_cell()` does _not_ call `final_column_wrap()` after printing the last char of the line.

> If the next call to tui_raw_line() wants to clear the next screen line, it doesn't print any characters, 

This looks like the real problem which should be fixed as such. after the change to use the grid_line event, TUI code might use clearing by accident even though nvim intended real spaces to be written. I think the fix is simple though: remember if _last_ line immediately did `kLineFlagWrap`, then a real char must always be printed, even if it is just a dummy space before clearing the rest of the line.

**Comment by zeertzjq** [comment] 2023-08-31 08:24
Ah yes, clearing the line seems to be the actual problem here, as the user should need to copy the spaces.

**Closed** 2023-09-02 10:50 UTC
Labels: tui, bug-regression, has:bisected
