### ISSUE TITLE
STL_MAX_ITEM is too small (80) for complex tabline plugins

### ISSUE THREAD

**Issue by zefei** [neovim/neovim#7459] opened 2017-10-29 21:51 UTC
I use the neovim `%@Func@` feature in my tabline plugin (https://github.com/zefei/vim-wintabs, https://github.com/zefei/vim-wintabs-powerline). I noticed that since I changed the plugin to render more complex tabline (a lot of higroups and function flags), tabline sometimes show `E541` at the end. The issue seems to be `#define STL_MAX_ITEM 80` which is too small for complex tabline rendering.

I'm not sure if the number can be increased safely. If it can, I'd suggest something like 1000 to accommodate possible new flags in the future.

### Steps to reproduce using `nvim -u NORC`

Make sure terminal window is wide enough to show the error message. Any long enough tabline can repro the issue, the repro below is just the current tabline I have.

```
nvim -u NORC
function! SetTabline()
  return "%1@wintabs#element#buffer_click@%#TabLineSel# .bash_profile %##%X%#WintabsPowerlineActiveBufferSepBuffer#%##%2@wintabs#element#buffer_click@
       %#TabLine# .bashr c %##%X%#TabLine#%##%3@wintabs#element#buffer_click@%#TabLine# .tmux.conf %##%X%#TabLine#%##%4@wintabs#element#buffer_click@
       %#TabLine# .gemrc %##%X%#TabLine #%##%5@wintabs#element#buffer_click@%#TabLine# .arcrc %##%X%#TabLine#%##%6@wintabs#element#buffer_click@%#TabLine# .
       babel.json %##%X%#TabLine#%##%7@wintabs #element#buffer_click@%#TabLine# .zshrc %##%X%#TabLine#%##%8@wintabs#element#buffer_click@%#TabLine# .vimrc
       %##%X%#TabLine#%##%9@wintabs#element#buffer_clic k@%#TabLine# .fzf.bash %##%X%#TabLine#%##%10@wintabs#element#buffer_click@%#TabLine# .lesshst
       %##%X%#TabLine#%##%11@wintabs#element#buffer_click@%#TabLine# .hgrc
       %##%X%#WintabsPowerlineBufferSepEmpty#%##%=|%#WintabsPowerlineActiveTabSepEmpty#%##%1@wintabs#element#tab_click@%#TabLineSel#1
       %##%X%#WintabsPowerline TabSepActiveTab#%##%2@wintabs#element#tab_click@%#TabLine# 2  %##%X%#TabLine#%##%3@wintabs#element#tab_click@%#TabLine# 3
       %##%X"
endfunction
set showtabline=2
set tabline=%!SetTabline()

```

### Actual behaviour

Nvim shows E541 in tabline.

### Expected behaviour

Nvim shows whole returned value in tabline.

**Comment by ZyX-I** [comment] 2017-10-29 22:12
This is one of the reasons for powerline not only not attempting to use Vim built-in atoms, but even once performing an optimization “when highlighting of next segment is the same to the highlighting of the previous segment, do not add highlight atom”: I managed to see the issue even though I am not using built-in atoms, on the other hand airline *does* use them and I am not sure how they cope.

**Comment by dundargoc** [comment] 2022-04-17 12:19
I believe this has been fixed as of https://github.com/neovim/neovim/pull/13167. I certainly couldn't reproduce this at least.

**Closed by dundargoc** 2022-04-17 12:20 UTC
Labels: enhancement
