### ISSUE TITLE
Possible bug: Lua API behavior diverges from vimscript behavior

### ISSUE THREAD

**Issue by danielyli** [neovim/neovim#15139] opened 2021-07-20 01:24 UTC
- `nvim --version`: NVIM v0.5.0
- Operating system/version: macOS 11.4
- Terminal name/version: iTerm 3.4.8
- `$TERM`: xterm-256color

## Description of Problem

Setting local window options via Lua diverges from expected VimScript behavior.

### Expected behaviour (VimScript)

In a fresh instance launched via `nvim -u NORC`, execute the following VimScript to enable line numbers _in the current window only_, and then open a new tab. Notice that the new tab does _not_ have line numbers, which is the correct behavior (as documented in `:help local-options`) because only the local window option was set:

```
$ nvim -u NORC
:setlocal number
:tabe
```

[![asciicast](https://asciinema.org/a/m74PO1fIMhcm4OpfHsdCwl3hJ.svg)](https://asciinema.org/a/m74PO1fIMhcm4OpfHsdCwl3hJ)

### Actual behaviour (Lua)

Repeat the above using Lua, and observe that the new tab has line numbers. This diverges from the expected behavior as documented in `:help vim.opt`:

```
$ nvim -u NORC
:lua vim.api.nvim_win_set_option(0, 'number', true)
:tabe
```

[![asciicast](https://asciinema.org/a/sYtfIDQKk6dphpq100rw6zgfQ.svg)](https://asciinema.org/a/sYtfIDQKk6dphpq100rw6zgfQ)

## Appendix

`:help vim.opt` says the following:

```
  The behavior of vim.o, vim.bo, vim.wo, and vim.go is designed to
  follow that of :set, :setlocal, and :setglobal which can be seen in the
  table below:

      lua            command      global_value       local_value
  vim.o           :set                set                set
  vim.bo/vim.wo   :setlocal            -                 set
  vim.go          :setglobal          set                 -
```

**Comment by seandewar** [comment] 2021-07-20 10:26
I think this relates to #14670.
[There's still some work to do on the window options API](https://github.com/neovim/neovim/issues/14670#issuecomment-859741648).

**Comment by gpanders** [comment] 2021-09-23 01:17
Closing as duplicate of #14670.

**Closed by gpanders** 2021-09-23 01:17 UTC
Labels: bug
