### ISSUE TITLE
error when editorconfig contains a comment

### ISSUE THREAD

**Issue by symphorien** [neovim/neovim#27630] opened 2024-02-25 21:22 UTC
### Problem

When running neovim in a folder that contains a file `.editorconfig` with inline comments the following error is shown:
```
Error detected while processing BufNewFile Autocommands for "*":
Error executing lua callback: root must be either "true" or "false"
stack traceback:
        [C]: in function 'error'
        ...-unwrapped-dirty/share/nvim/runtime/lua/editorconfig.lua:14: in function 'assert'
        ...-unwrapped-dirty/share/nvim/runtime/lua/editorconfig.lua:206: in function 'parse'
        ...-unwrapped-dirty/share/nvim/runtime/lua/editorconfig.lua:236: in function 'config'
        ...wrapped-dirty/share/nvim/runtime/plugin/editorconfig.lua:11: in function <...wrapped-dirty/share/nvim/runtime/plugin/editorconfig.lua:4>
Press ENTER or type command to continue
```
Such editorconfig files exist in the wild: https://gitlab.com/sane-project/backends/-/blob/release-1.3.0/.editorconfig?ref_type=heads#L9

This was initially reported as https://github.com/neovim/neovim/issues/23554 but without respecting the template.

### Steps to reproduce

```
mkdir tmp
echo 'root=true ; a comment' > tmp/.editorconfig
LANG=C result/bin/nvim --clean tmp/foo
```
Results in:
```
Error detected while processing BufNewFile Autocommands for "*":
Error executing lua callback: root must be either "true" or "false"
stack traceback:
        [C]: in function 'error'
        ...-unwrapped-dirty/share/nvim/runtime/lua/editorconfig.lua:14: in function 'assert'
        ...-unwrapped-dirty/share/nvim/runtime/lua/editorconfig.lua:206: in function 'parse'
        ...-unwrapped-dirty/share/nvim/runtime/lua/editorconfig.lua:236: in function 'config'
        ...wrapped-dirty/share/nvim/runtime/plugin/editorconfig.lua:11: in function <...wrapped-dirty/share/nvim/runtime/plugin/editorconfig.lua:4>
Press ENTER or type command to continue
```
Replacing the content of `tmp/.editorconfig` by `root=true` works fine.

### Expected behavior

Inline comment is ignored instead of creating an error

### Neovim version (nvim -v)

0fcbda59871ebc5fc91cac7fa430a4a93f6698c2 (today's master)

### Vim (not Nvim) behaves the same?

no, vim-9.0.2116

### Operating system/version

NixOS 23.11

### Terminal name/version

xfce4-terminal 1.1.1

### $TERM environment variable

xterm-256color

### Installation

flake in contrib folder

**Comment by zeertzjq** [comment] 2024-02-25 21:53
Duplicate of #25372

**Closed by zeertzjq** 2024-02-25 21:53 UTC
Labels: bug

**Comment by lewis6991** [comment] 2024-02-26 08:17
I really don't think editorconfig should be erroring with a stack trace on off-spec input. We should raise a less intrusive error/warning.
