### ISSUE TITLE
ml_get: invalid lnum when using treesitter

### ISSUE THREAD

**Issue by doubleloop** [neovim/neovim#12867] opened 2020-09-07 22:02 UTC
- `nvim --version`: NVIM v0.5.0-672-gd8e6a0396 (current master)
- nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter/commit/8d6c40ce24be2b8eb8dbcafd4e62fda47fdd1191 (current master)
- Terminal name/version: alacritty 0.6.0-dev (3688b5c)
- `$TERM`: screen-256color

### Steps to reproduce

test.py
```python
class Foo:
    def bar():
        if True:
            print("test")
            print(
```

testrc.vim

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
call plug#end()

lua << EOF
require('nvim-treesitter.configs').setup {
    highlight = {
        enable = true
    },
}
EOF
```
```
$VIMRUNTIME=$PWD/runtime build/bin/nvim -u testrc.vim test.py
```

### Actual behaviour
```
Error detected while processing FileType Autocommands for "python":
E315: ml_get: invalid lnum: 8
Press ENTER or type command to continue
```

### Expected behaviour
no error

**Comment by doubleloop** [comment] 2020-09-07 22:13
seems like the issue was 1832d18083446255aa04d63fac033aea08a65ed0

test.sh
```sh
make -j`nproc`
VIMRUNTIME=$PWD/runtime build/bin/nvim -u testrc.vim test.py +"redir @a | messages | redir END | if matchstr(@a, 'ml_get') == 'ml_get'| cq | else| q | endif"
```

```
$ git bisect start master 3acfefb63
$ git bisect run ./test.sh
...
1832d18083446255aa04d63fac033aea08a65ed0 is the first bad commit
commit 1832d18083446255aa04d63fac033aea08a65ed0
Author: Thomas Vigouroux <tomvig38@gmail.com>
Date:   Mon Aug 31 11:54:24 2020 +0200

    treesitter: update to use buf_set_extmark

 runtime/lua/vim/treesitter/highlighter.lua | 11 ++++++-----
 1 file changed, 6 insertions(+), 5 deletions(-)
bisect run success

```

**Comment by ruifm** [comment] 2020-09-08 06:28
I am getting exactly the same misbehavior and the bissect points to the same commit.

**Comment by bfredl** [comment] 2020-09-08 06:47
- Let's do luahl and bytetrack first and see if it helps.

**Comment by vigoux** [comment] 2020-09-08 08:28
Hi, and thanks for the bissect. The issue is kind of known, and repro are always useful.

As @bfredl said, this is on our roadmap to fix, through some prs.

**Comment by ruifm** [comment] 2020-09-08 10:06
> Hi, and thanks for the bissect. The issue is kind of known, and repro are always useful.
> 
> As @bfredl said, this is on our roadmap to fix, through some prs.

Can you reference the relevant PRs that would address this issue so that I can subscribe them?

Thanks to your (and @bfredl ) amazing work, I became ultra dependent on treesitter highlighting for my work in c++ and now I have to go back to legacy highlighting like a caveman. I guess those are the perks of using unreleased features :smile:

**Comment by vigoux** [comment] 2020-09-08 11:06
You should look at the `treesitter` project that this issue is linked too first, as this contains all the work and issues we follow.

As we have a fix repro for that, I will try to push a fix soon-ish.

And thanks for the kind words, but you are now part of it man :wink:

**Comment by vigoux** [comment] 2020-09-08 12:05
I am digging into that and found the following.

The tree generated by this file is 
```
(ERROR [0, 0] - [5, 0]
  (identifier [0, 6] - [0, 9])
  (identifier [1, 8] - [1, 11])
  (parameters [1, 11] - [1, 13])
  (true [2, 11] - [2, 15])
  (expression_statement [3, 12] - [3, 25]
    (call [3, 12] - [3, 25]
      function: (identifier [3, 12] - [3, 17])
      arguments: (argument_list [3, 17] - [3, 25]
        (string [3, 18] - [3, 24]))))
  (identifier [4, 12] - [4, 17]))
```

The problem is the `ERROR` node spanning past the end of the file, and that might be where the error comes from.

**Comment by ruifm** [comment] 2020-09-18 06:48
This issue seems to be fixed for me in the latest master after https://github.com/neovim/neovim/pull/12872

**Comment by vigoux** [comment] 2020-09-18 06:51
Yep, it should be okay now hopefully.

**Comment by jemag** [comment] 2020-10-22 14:52
Still getting a similar error in java, despite the fixes. So far it is incredibly intermittent, so it's really hard for me to replicate, especially since it will crash my nvim:
![image](https://user-images.githubusercontent.com/7985687/96889414-8ff5ef80-1454-11eb-9352-e5c830a1690f.png)

**Comment by vigoux** [comment] 2021-02-07 14:41
I think this issue is fixed now ? Could you confirm @jemag ?

**Comment by jemag** [comment] 2021-02-07 14:59
I believe so, I haven't seen it happen in quite some time now

**Closed** 2021-02-14 23:45 UTC
Labels: bug, treesitter
