### ISSUE TITLE
Buffer lags when you try to go EOL where line is bigger than terminal width 

### ISSUE THREAD

**Issue by spitfire-hash** [neovim/neovim#14968] opened 2021-07-03 10:41 UTC
- `nvim --version`: NVIM v0.5.0
- Operating system/version: Archlinux
- Terminal name/version: alacritty 0.8.0
- `$TERM`: alacritty

### Steps to reproduce using `nvim -u NORC`
Try to edit a markdown file whose line width is greater than terminal width. (in my case[this file](https://git.sr.ht/~tardypad/dotfiles/tree/master/item/doc/PACKAGES.md))
```
nvim -u NORC PACKAGES.md
```
Do `:set nowrap` for not wrapping lines. Come down to table and press and hold `l` (or `w`).

### Actual behaviour
The buffer lags, cursor goes some crazy parts of screen and it just becomes mess till you release the key
### Expected behaviour
It moves the cursor normal

This does not happen when filetype is not markdown. e.g. try to `cp PACKAGES.md PACKAGES` and do the same thing for the new file. it just does fine.

(btw this is not neovim specific, same thing happens with `vim -u DEFAULTS PACKAGES.md`

**Comment by justinmk** [comment] 2021-07-03 13:45
is this not a known vim syntax performance issue? duplicate of https://github.com/neovim/neovim/issues/4736 https://github.com/neovim/neovim/issues/650

**Closed by justinmk** 2021-07-03 13:45 UTC
Labels: bug
