### ISSUE TITLE
nvim_win_close should not be able to close cmdline-window

### ISSUE THREAD

**Issue by gelguy** [neovim/neovim#9767] opened 2019-03-21 10:21 UTC
- `nvim --version`:  `v0.4.0-401-g5c836d2ef`
- Operating system/version: `Windows 10 WSL Ubuntu`
- Terminal name/version: `wsltty`
- `$TERM`: `xterm`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
q:
:<C-R>=nvim_win_close(0, 1)<CR>
```

### Actual behaviour
Cmdline-window closes and leaves Nvim in an invalid state. Buffer cannot be quit, modifying the buffer leads to `ml_get` errors and sometimes seg-faults.

### Expected behaviour
`:close` when the cmdline-window is open will close the cmdline-window before closing the target window. `nvim_win_close` can have a similar behaviour.

Alternatively, `nvim_win_close` can have an error when attempting to close the cmdline-window.

**Comment by bfredl** [comment] 2019-03-21 11:23
Probably only closing the cmdline window itself should be allowed (and work like `:close`, i e Ctrl-C), and closing some other should be an error.

**Comment by bfredl** [comment] 2019-03-21 11:40
Somewhat related: perhaps cmdline window should be indicated in `nvim_get_mode()` as a separate field. Because even if nvim behaves like normal/insert mode for the cmdline window itself,  async co-processes could want to be careful with mutating state outside of that, because the state can be nested inside any other context.

**Comment by rasimon22** [comment] 2019-05-30 08:28
If the issue is still open, I've created a WIP pr. I'm very new to the codebase (cloned it for the first time this morning) so a second set of eyes to help point me in a good direction would be appreciated, particularly regarding the global state of all of the different windows (as far as I was able to tell today global `State` is more about the modality) Cheers!

**Comment by justinmk** [comment] 2019-08-10 11:45
closed by #10087

**Closed by justinmk** 2019-08-10 11:45 UTC
Labels: api, bug, good first issue
