### ISSUE TITLE
[idea] ctrl+n completion in command mode.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#3013] opened 2015-07-15 05:43 UTC
It'd be cool to press ctrl_n (ins-completion) while in command mode to bring up the same completion menus as when editing text files in INSERT mode.

**Comment by borring** [comment] 2015-07-15 13:48
In the meantime, you can already achieve something close to this.

While in the commandline, <c-f> will dump your cmdline history into a buffer where you can edit your commands. Vim has completion for vimL using `<c-x><c-v>` in INSERT mode. Then, when you're done typing your command, put your cursor over the command in NORMAL mode and press enter.

If you're not already in the command line, `q:` from normal mode will bring up the buffer mentioned earlier.

**Comment by trusktr** [comment] 2015-07-16 20:58
@borring Aaah, that's cool, a sort of workaround. Would be awesome for that popup to appear directly in the command mode.

This sort of gets closer: `nnoremap : q::startinsert<cr>`. The downside is command editing isn't exactly the same (backspace when there's no more characters on the current command doesn't exit back to normal mode, the window takes more space than wanted, etc). The cool thing is `tab` brings up the popup menu for completion, and `ctrl+n` completes like I was wanting.

It'd be cool to have the popup menus right in the actual command mode.

**Comment by trusktr** [comment] 2015-07-16 20:59
Interestingly, the command window seems to have a different height in different tabs, (depending on the layout in that tab?).

**Comment by trusktr** [comment] 2015-07-16 22:09
@borring Ran into a small problem: I tried typing `e %:p:h` while in the command window, and when I pressed tab it completed to the current working directory instead of the path to where the file I was editing is located. So not all behavior is as expected. If this could be fixed I might be tempted to live with the command window over adding the popup feature to the regular command line.

**Comment by borring** [comment] 2015-07-17 04:10
I would consider that expected behavior. I consulted the help files and found
this:

		Modifiers:
			:p		expand to full path
			:h		head (last path component removed)
			:t		tail (last path component only)
			:r		root (one extension removed)
			:e		extension only

If you want the full path to the file, remove the :h and just have `%:p`

**Comment by trusktr** [comment] 2015-07-17 06:20
@borring True, I knew that. What I mean is that the result in the command window isn't the same as the result you get in the real command line. The result in the window is always the cwd (not as expected), and the result in the real command line is the head path to a file (as expected).

**Comment by borring** [comment] 2015-07-17 18:14
Ah.. I see what you mean. That's unfortunate. It's probably because the window is a new buffer. You can try to rename the buffer after entering it. I already tried (unsuccessfully).

**Comment by justinmk** [comment] 2015-10-04 18:06
Closing in favor of https://github.com/neovim/neovim/issues/3423

**Comment by ZyX-I** [comment] 2015-10-04 18:23
@justinmk ? This issue does not seem to be related: it is about having NeoVim completion in terminal mode (which I closed because such idea has way too much issues). Popup menu in command mode does not have such big list of issues.

**Comment by purpleP** [comment] 2016-11-14 16:12
@justinmk Where can I ask questions about ex_getln.c and have other discussions about this feature?

**Comment by justinmk** [comment] 2016-11-14 16:32
@purpleP gitter or IRC

**Comment by justinmk** [comment] 2019-04-08 23:20
Resolved by https://github.com/neovim/neovim/pull/9607

```
if has('nvim-0.4')
  set wildoptions+=pum
endif
```

**Closed by justinmk** 2019-04-08 23:20 UTC
Labels: enhancement
