### ISSUE TITLE
neovim do not delete swap file after run `:q` in normal mode of the terminal buffer.

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#4699] opened 2016-05-03 13:10 UTC
- Neovim version:
- [x] Vim behaves differently? Vim version:
- Operating system/version:archlinux
- Terminal name/version:termite
- `$TERM`:xterm-termite
### Actual behaviour

do not delete swap file after close neovim in terminal buffer normal mode
### Expected behaviour

auto delete swap file
### Steps to reproduce using `nvim -u NORC`

```
nvim README.md
:te
type <C-\><C-n>
:q<cr>
nvim README.md
```

**Comment by azbshiri** [comment] 2016-05-13 18:01
In which version does this happen?

**Comment by satriyo796** [comment] 2016-06-16 02:44
Same case happened to me, my current installation is:

**Comment by SephVelut** [comment] 2016-09-04 14:06
Had something similar happen with the omnicomplete scratchpad. Not sure if actual issue. Spammed <C-o> and somehow a swap for the scratchpad was created at share/nvim/swap. Couldn't omnicomplete until I deleted the swap.

NVIM 0.1.5
Vanilla

**Comment by glacambre** [comment] 2021-06-05 09:49
@wsdjeg Does this still happen to you? I can't reproduce on master with `nvim -u NORC`.

**Comment by hsgg** [comment] 2023-01-24 19:41
This problem is happening for me with multiple tabs. To reproduce, first, open two files, and close one of them:
```
nvim -u NORC -p a.md b.md
:q<cr>
```
So this instance has only `b.md` still open.
In a second terminal, opening `a.md` finds a swap file:
```
nvim -u NORC a.md
```
Swapfile found! Need to completely stop the first `nvim` process to delete the swap for the already closed file.

Version:
```
% nvim --version
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"
```

**Comment by glacambre** [comment] 2023-01-24 19:45
@hsgg `:q` does not close the file you opened, it only closes the window (and quits neovim if it was the last window). `:bw` "closes" the file.

**Comment by glacambre** [comment] 2023-01-24 19:50
It's been a year and a half since I tried to reproduce the problem and couldn't, let's close this issue. We'll re-open if people find a way to reproduce it :).

**Closed by glacambre** 2023-01-24 19:50 UTC
Labels: bug, terminal
