### ISSUE TITLE
Error when editing russian language characters

### ISSUE THREAD

**Issue by shagohead** [neovim/neovim#16304] opened 2021-11-13 21:19 UTC
### Neovim version (nvim -v)

0.5.1 (build type: release)

### Vim (not Nvim) behaves the same?

No, because it nvim related issue

### Operating system/version

macOS 11.6

### Terminal name/version

Alacritty cf35a2019162 commit

### $TERM environment variable

alacritty

### Installation

homebrew

### How to reproduce the issue

Requires attached LSP client. Write some two russian language characters like `ее`. Then exit in normal mode, go into middle of the characters. Write some new characters, like: `еавы`. And you should get an error message, that will be echo'ed on every type:

```
Error executing vim.schedule lua callback: ...llar/neovim/0.5.1/share/nvim/runtime/lua/vim/lsp/rpc.lua:399: Vim:E474: String "<b2><d0>" contains byte that does not start any UTF-8 character
```

The String may be differ, depending on the entered character.

### Expected behavior

No error messages in these cases.

### Actual behavior

Nvim echo'ed error message in the middle of editing docstring/comments and other stuff.

**Comment by mjlbach** [comment] 2021-11-13 21:20
Duplicate of #14542, try neovim 0.6

**Closed by mjlbach** 2021-11-13 21:20 UTC
Labels: bug
