### ISSUE TITLE
fillchars: stlnc does not handle UTF-8 char

### ISSUE THREAD

**Issue by m1027** [neovim/neovim#12057] opened 2020-03-27 09:26 UTC
I use

>
> set fillchars=vert:│,fold:\ ,diff:·,stl:-,stlnc:-
>

This line is for completeness only. The critical part I refer to is the last
part: stlnc:-

When I replace the final dash (a standard dash) with a UTF-8 character, like a
prettier horizontal dash, and then :vsp and :sp the window, then the fillchars
are printed as two bytes instead of a single UTF-8 character. This overwrites
content in other windows.

BTW: Thanks for this fantastic app.

**Comment by bfredl** [comment] 2020-03-27 11:13
The issue is probably that the char you choose is displayed doublewidth by the terminal. The char has to be singlewidth (or ambiwith if 'ambiwidth' option is set to single, but it requires also that the terminal actually behaves in this way).

**Comment by zeertzjq** [comment] 2021-12-31 04:21
I think this can be closed in favor of #15993

**Closed by zeertzjq** 2021-12-31 04:21 UTC
