### ISSUE TITLE
[BUG] lag

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#3328] opened 2015-09-10 21:26 UTC
Lately, in Linux, the render of Neovim is always one move behind my actual movements, and there's what seems like a timeout before the cursor (and the result of many other actions) catches up to my last inputs. As you might imagine, it's incredibly bothersome.

I tried toggling things in my vimrc to find the culprit, but eventually I ended disabling everything, I even running `nvim -u NONE`, but still the problem persists. This hints at the possibility that something changed in neovim itself.

**Comment by trusktr** [comment] 2015-09-10 21:29
It doesn't always happen right away. Usually I've gotta move around, navigate around, do things, then after a little while it starts happening. I haven't been able to pinpoint what (if any) actions triggers it.

**Comment by fmoralesc** [comment] 2015-09-10 21:44
Does this happen in every filetype? Only thing that I can imagine might be causing slowdowns is the matchit plugin, which neovim enables by default.

**Comment by trusktr** [comment] 2015-09-10 23:44
@fmoralesc multiple file types, yes. I've got the matchit plugin disabled but it still happens

**Comment by fmoralesc** [comment] 2015-09-11 02:13
Does it still happen when you disable the syntax highlighting? Is auto-formatting enabled in any way? Also, any plugin that hooks into `CursorMoved` can cause slowdowns in vim, perhaps this is pessimized in neovim somehow. There are many moving parts that might be causing slowdowns.

**Comment by tarruda** [comment] 2015-09-11 11:52
@trusktr what's the output of `nvim --version` and your linux distro/terminal/version? Can you try rebuilding nvim and all dependencies from the scratch to see if the problem persists?(Just clone nvim into a new directory and build from there).

If you are 100% everything is up to date, can you use `git bisect` to determine which commit introduced this lag?

**Comment by mseeber** [comment] 2015-09-11 19:05
The issues is old, I had it even months ago in some cases and it drove me to build neovim as release version, since the performance is noticeable better that way.

I did some preliminary testing of the current master and this occurs with syntax highlighting on.
It disappears with syntax highlighting off.

It is especially bad for me with a certain set of very long and badly written php files. (very long lines with very deep nesting of braces inside the lines)

The lag in these files appears very local at some places when scrolling over them and it seems to require some "warmup" before it gets realy bad.
The cursor position in the line, while scrolling also seems to have some impact, but I am not sure there. (in the beginning less lag, when near the end of the line, more lag)

**Comment by weaksauce** [comment] 2015-09-11 19:11
does it still happen when you run it without your custom nvimrc and plugins?

**Comment by mseeber** [comment] 2015-09-11 19:11
I did some sampling with perf record, just to get an impression, here the first entrys:

    # Overhead  Command  Shared Object       Symbol
    # ........  .......  ..................  .......................................
    #
        39.33%  nvim     nvim                [.] in_id_list
        14.48%  nvim     nvim                [.] syn_current_attr
        10.76%  nvim     nvim                [.] nfa_regmatch
         6.46%  nvim     nvim                [.] addstate
         4.91%  nvim     nvim                [.] arena_chunk_dirty_insert

I obtain the samples by starting nvim, loading the file, warming up, starting perf record and start scrolling aroud one of the hotspots in the php code.

**Comment by mseeber** [comment] 2015-09-11 19:24
@weaksauce I moved away my .nvimrc and my .nvim folder and started neovim with:

    nvim -u NONE

Result:
No notable Lag, even when i enable syntax with `:syntax on`

So it is in my case probably caused by the custom php.vim and my nvimrc settings

**Comment by weaksauce** [comment] 2015-09-11 19:28
@mseeber if you can pin down exactly what is causing it by enabling one thing at a time then you can help get it resolved.

**Comment by mseeber** [comment] 2015-09-11 19:42
ok... I removed all custom plugins but kept my .nvimrc and it still occurs. I continue searching.

Also I confirmed, that it only happens, when the cursor is near the end of the line.
It does not occur, if the cursor is running over whitespace from the indentation of the php code.

**Comment by mseeber** [comment] 2015-09-11 20:43
I think my problem is very much related to the custom plugins, as performace is much better without the plugins. Sorry for the noise.

**Comment by tarruda** [comment] 2015-09-15 11:31
@mseeber thanks for the report. Would you say that the lag experienced in Neovim is significantly greater than in Vim?

**Comment by trusktr** [comment] 2015-09-15 17:57
@fmoralesc @weaksauce 

> Does it still happen when you disable the syntax highlighting? Is auto-formatting enabled in any way?

It seems to happen even with `nvim -u NONE`, so my case is different than @mseeber's. TO be specific, this is what happens: suppose I scroll or paste lots of code, then the first half of the screen (approximately, not always exactly half) updates fast all the time, then the second half updates after the lag.

@tarruda 

```
> nvim --version                                       
NVIM 0.0.0-alpha+201509100208 (compiled Sep 10 2015 13:44:19)                             
Commit: aea3f702371bd71439318513235368baf12aed00                                          
Build type: RelWithDebInfo                                                                
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter
 -Wstrict-prototypes -std=gnu99 -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/pacman/cache/pkg/neovim-git1788/neovim-git/src/neovim-git/build/config -I/home/pacman/cache/pkg/neovim-git1788/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/pacman/cache/pkg/neovim-git1788/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/pacman/cache/pkg/neovim-git1788/neovim-git/src/neovim-git/build/include                                                      
Compiled by trusktr@starlancer                                                            
                                                                                          
Optional features included (+) or not (-): +acl   +iconv    +jemalloc                     
For differences from Vim, see :help vim-differences                                       
                                                                                          
   system vimrc file: "$VIM/nvimrc"                                                       
     user vimrc file: "~/.nvimrc"                                                         
 2nd user vimrc file: "~/.nvim/nvimrc"                                                    
      user exrc file: "~/.exrc"                                                           
  fall-back for $VIM: "/usr/share/nvim
```

I'm on Arch Linux, building neovim-git from AUR, which pulls the latest neovim. My terminal is Gnome Terminal (3.16.2, Using VTE version 0.40.2 +GNUTLS).

**Comment by trusktr** [comment] 2015-09-15 18:11
It seems like it might happen where there's more CPU usage in the system. Whenever my fan starts running, movements in nvim are fast (becaue rendering nvim doesn't really take that much CPU) but the only thing is the lag for the last update. Basically, I can hold down `j` to move downwards, and it'll be speedy, but when I let go, it'll stop at one line before the one I meant to stop on, and after the lag (which seems sort of like a timeout) it'll move one more line downward.

**Comment by trusktr** [comment] 2015-09-15 18:13
Sometimes it happens when no there's no CPU usage. Right now, it was fine, then when I pressed `p` to paste, it pasted, and everything starting from two lines below the cursor (which includes the pasted content) updated normally, then the lines below that updates after the lag.

**Comment by trusktr** [comment] 2015-09-15 18:16
Could it be that anything that involves enough CPU triggers the behavior (perhaps the `p`aste used enough CPU)? It seems that if I leave nvim alone for a while, it goes back to normal. Then, if I start editing text fast, pasting, changing, etc, just consistently, then it'll start to have the problem.

**Comment by mseeber** [comment] 2015-09-15 23:08
@tarruda I'd say it's about the same without any plugins, an empty *rc and syntax highlighting turned on, so no worrys in my case. The case @trusktr describes here seems to be a different one so I back out here.

**Comment by justinmk** [comment] 2015-09-16 02:28
Moving this to 0.2, there is nothing we can act upon here.

**Comment by tarruda** [comment] 2015-09-16 06:06
@trusktr can you test if this lag happens before #3246? You can use @f39ac6982418 which is the parent commit.

**Comment by justinmk** [comment] 2016-02-01 05:21
No reply, and no way to reproduce.

**Closed by justinmk** 2016-02-01 05:21 UTC
