### ISSUE TITLE
reltime() might use negative numbers as second return value (different from Vim)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#2567] opened 2015-05-02 12:03 UTC
I've noticed that Neovim might use a negative number with the list returned by `reltime()`, which is different from Vim:

    let s = reltime() | while 1 | echom string(reltime(s)) | endwhile

    [0, 10812]
    [0, 91084]
    [0, 172501]
    [...]
    [0, 1986232653]
    [0, 1986427063]
    [0, -1934584780]
    [0, -1934368068]

This caused an issue with Syntastic, which relied on this for comparison (https://github.com/scrooloose/syntastic/pull/1406).
While the fix is to use `reltimestr()` for comparison, Neovim should probably not behave different here.

While `reltimestr()` appears to be correct in Neovim, it seems like Vim uses the first number of `reltime()` for the number of seconds - which is not the case in Neovim - probably given that it uses a wider range for the second number.

**Comment by splinterofchaos** [comment] 2015-05-02 15:07
Please check out #2568 and let me know if that fixes it for you.

**Comment by blueyed** [comment] 2015-05-02 20:15
Does not work for me..

Using `vi -c 'let s = reltime() | while 1 | echom string(reltime(s)) | echom reltimestr(reltime(s)) | endwhile'` it starts with:

[-107064, 10356]
18446284237.331051
[-107064, 202204]
18446284237.331242

`uname -m`: x86_64

**Comment by JCavallo** [comment] 2015-05-12 10:10
I have the same problem (sort of) with https://github.com/rhysd/accelerated-jk which also use reltime for comparison purposes. I tried your pull request, but though it does remove the negatives, the values are rather different than those from vanilla vim :

vim -c 'let s = reltime() | while 1 | echom string(reltime(s)) | endwhile'

[0, 5]
[0, 53]
[0, 72]
[0, 96]
[0, 113]
[0, 129]


nvim -c 'let s = reltime() | while 1 | echom string(reltime(s)) | endwhile'

[0, 5555]
[0, 53479]
[0, 81180]
[0, 180852]
[0, 239623]
[0, 297192]

**Comment by aktau** [comment] 2015-05-12 17:49
I don't see why we would have to change Neovim in this roundabout way for plugins that are obviously not using the reltime() function as documented:

```
reltime([{start} [, {end}]])                reltime()                                
        Return an item that represents a time value.  The format of                  
        the item depends on the system.  It can be passed to                                                                                 
        reltimestr() to convert it to a string.                                      
        Without an argument it returns the current time.                             
        With one argument is returns the time passed since the time                  
        specified in the argument.                                                   
        With two arguments it returns the time passed between {start}                
        and {end}.                                                                   
        The {start} and {end} arguments must be values returned by                   
        reltime().                                                                   
        {only available when compiled with the +reltime feature}
```

This is from the vanilla Vim docs by the way. The plugins need to be corrected to use `reltimestr()` (processing that if need be). 

Or am I missing something and is there a good reason why the plugins use something like `string(reltime(s))` and not `reltimestr(reltime(s))`?

**Comment by aktau** [comment] 2015-05-12 17:53
So [this](https://github.com/rhysd/accelerated-jk/blob/master/autoload/accelerated/time_driven.vim#L66-L67) is the relevant part of the accelerated-jk plugin:

```vim
    let current_timestamp = reltime()
    let [sec, microsec] = reltime(previous_timestamp, current_timestamp)
```

The documentation never states that `reltime()` returns seconds and microseconds. One can use `reltimestr()` to get such a value though. It will most likely not represent a value of seconds and microseconds since some fixed epoch. OS'es actively randomize these timers to prevent people from relying on that.

**Comment by aktau** [comment] 2015-05-12 18:04
Though I would consider it a dirty hack, it would in fact be possible to make Neovim behave mostly like Vim without going to bit-twiddling:

1. When Neovim starts up, save one value obtained from `profile_start()`, name it `base_time`.
2. When `reltime()` is called, always offset the resulting `proftime_T` with `base_time`, so that we get a "time since start up" value, which it seems like Vim does.
3. Don't do the union type-punning trick but instead creating the high and low values manually by extracting seconds and microseconds from the nanoseconds `proftime_T`: (in `profile.c`)

```c
struct vim_timeval {
  uint32_t seconds;
  uint32_t microseconds;
};

struct vim_timeval profile_compat(proftime_T tm) {
  uint32_t sec =  (uint32_t) (tm / 1000000000ULL);
  return (struct vim_timeval) {
    .seconds = sec,
    .microseconds = (uint32_t) ((tm - (sec * 1000000000ULL)) / 1000ULL)
  };
}
```

And then basically adding the two values in that struct to the list. I believe this is ugly and I probably made a mistake in my time calculations there even...

**Comment by JCavallo** [comment] 2015-05-12 18:59
@aktau Agreed that neovim should not try to fix plugins bugs, I just meant to say that I noticed the problem by using this plugin; then noticed the difference of behaviour of `reltime()` between vim and nvim with the proposed fix

**Comment by Shougo** [comment] 2015-05-13 01:15
> @aktau Agreed that neovim should not try to fix plugins bugs, I just meant to say that I noticed the problem by using this plugin; then noticed the difference of behaviour of reltime() between vim and nvim with the proposed fix

Well, you should report the problem to the plugin author(@rhysd).

**Comment by ZyX-I** [comment] 2015-05-13 19:26
@JCavallo This issue and the associated PR are about fixing other plugins’ bugs. I would actually close both with a resolution NOTABUG.

**Comment by JCavallo** [comment] 2015-05-13 21:14
@ZyX-I The original issue was not created by me, and there is a bug in the current version (reltime` returning negative values). The PR appears because I referenced the neovim issue from the plugin one.

**Comment by ZyX-I** [comment] 2015-05-13 21:18
@JCavallo Why do you think that this is a bug? `reltime()` returning negative values is *not* a bug because documentation explicitly defines `reltime()` result as platform-dependent, so the only valid way of using it is passing through `reltimestr()`. `reltime()` output does not even have to be a list.

It *would be* a bug if `reltimestr()` returned negative values or did not conform `{seconds}.{microseconds}` format, but this is not the case.

**Comment by ZyX-I** [comment] 2015-05-13 21:22
@JCavallo And I ment PR by @splinterofchaos (#2568).

**Comment by JCavallo** [comment] 2015-05-13 22:00
@ZyX-I You got a point. Though negative values smells of overflow, if `reltimestr` properly parse it, it is indeed not a bug.

**Comment by aktau** [comment] 2015-05-13 23:12
> @ZyX-I You got a point. Though negative values smells of overflow, if reltimestr properly parse it, it is indeed not a bug.

It's not overflow, it's just that Neovim internally represents time as a single unsigned 64-bit number in nanosecond units. To "expose" this to VimL, it is split up (in the middle) in 2 32-bit signed integers. Of course, it is quite likely that at least one of the resulting numbers will be negative. Since reltimestr() by design does the reverse transformation, it does not lose information.

**Comment by splinterofchaos** [comment] 2015-05-20 18:07
I'm going to go ahead and close this since no one has presented a convincing argument that this is really a bug. Please comment if you feel this is a mistake.

**Closed by splinterofchaos** 2015-05-20 18:07 UTC
