### ISSUE TITLE
LSP: Enhacement ideas

### ISSUE THREAD

**Issue by pwntester** [neovim/neovim#11630] opened 2019-12-29 14:50 UTC
Im sharing some enhacements I implemented on top of the current LSP client as suggested by @justinmk [here](https://github.com/neovim/nvim-lsp/issues/45#issuecomment-559611520)

Please let me know if any of these enhacements would make sense for the core client and if so I will send PR for them. The main enhacements are:

#### add signs to sign column for diagnostics
Shows signs for each line containing one or more diagnostics
<img width="801" alt="imagen" src="https://user-images.githubusercontent.com/125701/71558208-e53dbc00-2a50-11ea-93c0-8027bef4e1c5.png">

#### statusline integration
Expose diagnostic counts and server readiness with a global function so they can be showed in the status line. see screenshot above.

#### right align virtual text to the right of the screen
<img width="1070" alt="imagen" src="https://user-images.githubusercontent.com/125701/71558238-1fa75900-2a51-11ea-8110-6861efc9024d.png">

I feel this is the right place to show virtual text but its not ready for integration into core client since virtual text placement depends on window's size so if the same buffer is shown in more than one window, only one will have the virtual text shown in the right place. I cant think of any workaround for this. @justinmk any ideas?

#### remove highlights from diagnostics details popup window
<img width="469" alt="imagen" src="https://user-images.githubusercontent.com/125701/71558267-757c0100-2a51-11ea-8955-224dcc7baf7f.png">

Without this, each line would be in the highlight group for their severity. Also, applied NormalFloat to winhighlight for the popup window

#### codeactions support
<img width="1081" alt="imagen" src="https://user-images.githubusercontent.com/125701/71558328-4023e300-2a52-11ea-859f-9d2eeb408720.png">

My implementation uses FZF, but I saw a PR implementing the menu on a float window so I guess that is a better approach, although I would miss the fuzzy finding

#### use NormalFloat for hover popup window
This should be the default for any float windows

#### expose local functions as global ones
When overriding the default callbacks (eg: override the diagnostics callback), its normally a good idea to reuse helper functions such as `all_buffer_diagnostics`, `buf_diagnostics_save_positions`, `highlight_range`, `trim_empty_lines`, etc. however these are defined as local functions, so I found myself having to copy and manatain them. @norcalli  would it be possible to expose them? 

Here is my [LSP config](https://github.com/pwntester/dotfiles/blob/master/config/nvim/lua/lsp-config.lua) and [here](https://github.com/pwntester/dotfiles/blob/master/config/nvim/lua/nvim-lsp.lua) are all the functions and variables I had to copy to my local config since they were not exposed

**Comment by justinmk** [comment] 2019-12-30 07:01
> virtual text placement depends on window's size so if the same buffer is shown in more than one window, only one will have the virtual text shown in the right place

use the narrowest window as the benchmark. Or just don't worry about it :)

>  use NormalFloat for hover popup window
> This should be the default for any float windows

agreed

> codeactions support

until Nvim has better menu support I'd say this should use `:help inputlist()`. It's ugly but it's usable.

> expose local functions as global ones
> When overriding the default callbacks (eg: override the diagnostics callback), its normally a good idea to reuse helper functions such as `all_buffer_diagnostics`

Makes sense. The problem is they need to be documented and then the name/API can't change.

**Comment by bfredl** [comment] 2019-12-30 08:23
>  Also, applied NormalFloat to winhighlight for the popup window. use NormalFloat for hover popup window. This should be the default for any float windows

But `NormalFloat` is already the default for any popup window. This highlight group was specifically added so you do not need to use winhl option for every floating window (and if you do, you can simply use `winhl=Normal:xx` like for any window, as NormalFloat is just for the default).

> remove highlights from diagnostics details popup window

But why? I like the visual connection.

**Comment by bfredl** [comment] 2019-12-30 08:35
> right align virtual text to the right of the screen. I feel this is the right place to show virtual text but its not ready for integration into core client since virtual text placement depends on window's size so if the same buffer is shown in more than one window, only one will have the virtual text shown in the right place.

I think we should implement this natively in screen.c. I'm currently working on refactoring the implementation, after that we should add new display modes for virtual text.

**Comment by pwntester** [comment] 2019-12-30 13:36
> But NormalFloat is already the default for any popup window. This highlight group was specifically added so you do not need to use winhl option for every floating window (and if you do, you can simply use winhl=Normal:xx like for any window, as NormalFloat is just for the default).

My fault, I have an autocommand to change winhighlight that is also affecting floating windows

> But why? I like the visual connection.

This is probably a personal choice, but in my case, perhaps because I used colored underline and sign, its too much coloring, eg:

<img width="1277" alt="imagen" src="https://user-images.githubusercontent.com/125701/71584096-77a59480-2b11-11ea-9837-917808e1128f.png">

(it gets worst when mixing warnings (orange) and errors (red) in the same line)

> I think we should implement this natively in screen.c. I'm currently working on refactoring the implementation, after that we should add new display modes for virtual text.

I think this is definitly the way to go

**Comment by pwntester** [comment] 2019-12-30 13:45
Summing up:

- add signs to sign column for diagnostics
Will send PR
- statusline integration
Will send PR
- right align virtual text to the right of the screen
To be supported natively. Filed https://github.com/neovim/neovim/issues/11634
- remove highlights from diagnostics details popup window
Personal choice so wont send PR
- codeactions support
Lets stick to existing PR for now (https://github.com/neovim/neovim/pull/11607)
- use NormalFloat for hover popup window
Already implemented
- expose local functions as global ones
wait for @norcalli  response

**Comment by pwntester** [comment] 2019-12-30 13:54
Also, forgot I implemented reference highlight on cursorhold:

<img width="464" alt="imagen" src="https://user-images.githubusercontent.com/125701/71584719-47abc080-2b14-11ea-9ea0-ce0fe6aae095.png">

Will send PR for this as well

**Comment by dex157** [comment] 2020-02-17 05:32
Emacs has the [lsp-ui](https://github.com/emacs-lsp/lsp-ui#lsp-ui-sideline) package to output information from the language server protocol. The output is on the right side of the screen.

I think this is a very good working model for virtual text:
![](https://raw.githubusercontent.com/emacs-lsp/lsp-ui/master/images/lsp-line.gif)

**Comment by XVilka** [comment] 2020-03-03 03:33
Since all mentioned pull requests were merged, maybe this one can be marked as done?

**Closed** 2020-03-06 09:05 UTC
Labels: enhancement, lsp
