### ISSUE TITLE
crashes in tmux on pane resize

### ISSUE THREAD

**Issue by macovsky** [neovim/neovim#12500] opened 2020-06-17 22:35 UTC
Approximately once a day neovim crashes when some pane is being resized in tmux (say goes to/from fullscreen or I just increase/decrease size).

Couldn't try nightly release because of https://github.com/neovim/neovim/issues/12430.

- `nvim --version`: NVIM v0.4.3 
- `vim -u DEFAULTS` (version: ) behaves differently? I can't reproduce it anywhere actually.
- Operating system/version: `Linux 5.7.2-arch1-1 x86_64 GNU/Linux` (but it was also crashing the same way on macos)
- Terminal name/version: `st` (was also crashing in `alacritty` on macos)
- `$TERM`: `screen-256color` (`xterm-256color` on macos)

`tmux 3.1b`

### Steps to reproduce using `nvim -u NORC`

The problem is that I can't reproduce it even with my current configuration.

### Actual behaviour

Crashes on pane resize in tmux.

coredump:

```
           PID: 1285264 (nvim)
           UID: 1000 (macovsky)
           GID: 998 (wheel)
        Signal: 6 (ABRT)
     Timestamp: Wed 2020-06-17 14:30:09 PDT (22min ago)
  Command Line: nvim .
    Executable: /usr/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (macovsky)
       Boot ID: 12a3dd20d08f476b90ae61af9c211321
    Machine ID: 3391aaff91df48c58e79d8287a60a74f
      Hostname: arc
       Storage: /var/lib/systemd/coredump/core.nvim.1000.12a3dd20d08f476b90ae61af9c211321.1285264.1592429409000000000000.lz4
       Message: Process 1285264 (nvim) of user 1000 dumped core.
                
                Stack trace of thread 1285265:
                #0  0x00007f44e8bba355 raise (libc.so.6 + 0x3c355)
                #1  0x00007f44e8ba3853 abort (libc.so.6 + 0x25853)
                #2  0x00007f44e8bfd878 __libc_message (libc.so.6 + 0x7f878)
                #3  0x00007f44e8c04d3a malloc_printerr (libc.so.6 + 0x86d3a)
                #4  0x00007f44e8c05a86 unlink_chunk.constprop.0 (libc.so.6 + 0x87a86)
                #5  0x00007f44e8c0625b _int_free (libc.so.6 + 0x8825b)
                #6  0x0000557ce90e2c7a n/a (nvim + 0x95c7a)
                #7  0x0000557ce90ee1f4 ugrid_resize (nvim + 0xa11f4)
                #8  0x0000557ce90ee289 n/a (nvim + 0xa1289)
                #9  0x0000557ce92473c9 multiqueue_process_events (nvim + 0x1fa3c9)
                #10 0x0000557ce92475fa loop_poll_events (nvim + 0x1fa5fa)
                #11 0x0000557ce90fc67e n/a (nvim + 0xaf67e)
                #12 0x00007f44e8b0c422 start_thread (libpthread.so.0 + 0x9422)
                #13 0x00007f44e8c7dbf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 1285264:
                #0  0x0000557ce9172390 profile_passed_limit (nvim + 0x125390)
                #1  0x0000557ce9157419 n/a (nvim + 0x10a419)
                #2  0x0000557ce9159bf6 n/a (nvim + 0x10cbf6)
                #3  0x0000557ce915a73f n/a (nvim + 0x10d73f)
                #4  0x0000557ce915abad n/a (nvim + 0x10dbad)
                #5  0x0000557ce9156ab2 vim_regexec_multi (nvim + 0x109ab2)
                #6  0x0000557ce9105280 n/a (nvim + 0xb8280)
                #7  0x0000557ce91098f1 n/a (nvim + 0xbc8f1)
                #8  0x0000557ce910a068 get_syntax_attr (nvim + 0xbd068)
                #9  0x0000557ce9150267 n/a (nvim + 0x103267)
                #10 0x0000557ce9153c7a n/a (nvim + 0x106c7a)
                #11 0x0000557ce914b1e5 n/a (nvim + 0xfe1e5)
                #12 0x0000557ce914b8ee screen_resize (nvim + 0xfe8ee)
                #13 0x0000557ce90f06f7 ui_refresh (nvim + 0xa36f7)
                #14 0x0000557ce92473c9 multiqueue_process_events (nvim + 0x1fa3c9)
                #15 0x0000557ce91a45d3 n/a (nvim + 0x1575d3)
                #16 0x0000557ce91b20cf n/a (nvim + 0x1650cf)
                #17 0x0000557ce910e2e1 state_enter (nvim + 0xc12e1)
                #18 0x0000557ce91b388c normal_enter (nvim + 0x16688c)
                #19 0x0000557ce90b4d37 main (nvim + 0x67d37)
                #20 0x00007f44e8ba5002 __libc_start_main (libc.so.6 + 0x27002)
                #21 0x0000557ce90b5dce _start (nvim + 0x68dce)
```

Current plugins are:

```
Plug '/usr/local/opt/fzf'
Plug 'Raimondi/delimitMate'
Plug 'SirVer/ultisnips'
Plug 'airblade/vim-rooter'
Plug 'ap/vim-css-color'
Plug 'baskerville/vim-sxhkdrc'
Plug 'cakebaker/scss-syntax.vim'
Plug 'chr4/nginx.vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'digitaltoad/vim-pug'
Plug 'duff/vim-bufonly'
Plug 'elixir-editors/vim-elixir'
Plug 'gh:macovsky/flattened'
Plug 'godlygeek/tabular'
Plug 'guns/vim-clojure-static', { 'for': 'clojure' }
Plug 'guns/vim-sexp', { 'for': 'clojure' }
Plug 'hashivim/vim-terraform'
Plug 'haya14busa/vim-asterisk'
Plug 'jez/vim-superman'
Plug 'jpalardy/vim-slime'
Plug 'junegunn/fzf.vim'
Plug 'justinmk/vim-dirvish'
Plug 'kchmck/vim-coffee-script'
Plug 'machakann/vim-highlightedyank'
Plug 'macovsky/vim-indent-object'
Plug 'macovsky/vim-mutt-aliases'
Plug 'mattn/gist-vim'
Plug 'mattn/webapi-vim'
Plug 'mileszs/ack.vim'
Plug 'moll/vim-bbye'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'neomutt/neomutt.vim'
Plug 'pangloss/vim-javascript'
Plug 'pearofducks/ansible-vim'
Plug 'roxma/vim-tmux-clipboard'
Plug 'shumphrey/fugitive-gitlab.vim'
Plug 'slim-template/vim-slim'
Plug 'thoughtbot/vim-rspec'
Plug 'tmux-plugins/vim-tmux-focus-events'
Plug 'tomtom/tcomment_vim'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-classpath', { 'for': 'clojure' }
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-git'
Plug 'tpope/vim-haml'
Plug 'tpope/vim-markdown'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-ragtag'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-rsi'
Plug 'tpope/vim-sexp-mappings-for-regular-people', { 'for': 'clojure' }
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-ruby/vim-ruby'
Plug 'vimwiki/vimwiki'
```

### Expected behaviour

Not to crash.

**Comment by mnrce** [comment] 2020-06-19 16:47
I can confirm this also happens in nightly.

I'm using `NVIM v0.5.0-563-ge628a05b5` and also got crashed recently with `tmux 3.1b` when resizing the panes.

I can't reproduce, either. It just happens when I randomly resize the panes and neovim's pane got too small and then neovim just crashed.

**Comment by tmpm697** [comment] 2020-06-22 02:30
Current use with `tmux next-3.2` and `NVIM v0.4.3`, I don't observe the issue.

**Comment by mnrce** [comment] 2020-06-22 09:33
Related: https://github.com/liuchengxu/vim-clap/issues/466.

**Comment by macovsky** [comment] 2020-07-01 17:43
now I've seen this message if that helps: `free(): invalid next size (normal)`

**Comment by glacambre** [comment] 2021-06-08 17:19
@macovsky Are you still experiencing these crashes? If yes, could you try to reduce the list of plugins you use until you find the one causing the crashes?

**Comment by macovsky** [comment] 2021-06-08 20:54
I haven't had these crashes in a while actually and I wasn't updating neovim either, only `tmux` went to `3.2` from `3.1b` 🤷🏻‍♂️

**Comment by glacambre** [comment] 2021-06-08 22:44
@macovsky Great, thanks. Since we don't have a reproducer the best thing to do here is probably to close this issue, feel free to re-open/open a new one if the problem comes back :).

**Closed by glacambre** 2021-06-08 22:44 UTC
Labels: 9.needs:repro, bug, bug-crash, tui
