### ISSUE TITLE
paste with clipboard provider in Windows works, but copy doesn't

### ISSUE THREAD

**Issue by ntcong** [neovim/neovim#11570] opened 2019-12-18 04:09 UTC
I'm using Neovim in WSL/Ubuntu 19.04 
`:checkhealth` reports clipboard provider works (all command run with nvim -u NORC)
```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - OK: escape-time: 1ms
  - INFO: $TERM: screen-256color
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. 'termguicolors' won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank
```

Pasting works with clipboard content from Windows, but coping in nvim doesn't put content in clipboard

win32yank can run manually without problem
```
echo "hello" | win32yank.exe -i --crlf
win32yank.exe -o --lf         
hello                                                                                                                                             
```
yanking yield (pasting does not)
```
clipboard: error invoking win32yank.exe:
```

**Comment by justinmk** [comment] 2019-12-18 07:41
Duplicate of https://github.com/neovim/neovim/issues/7021

**Closed** 2019-12-18 07:41 UTC
