### ISSUE TITLE
ScrollWheel events not ignored when mapped

### ISSUE THREAD

**Issue by lheckemann** [neovim/neovim#8012] opened 2018-02-15 11:58 UTC
- `nvim --version`:
```
NVIM v0.2.0
Build type: Release
Compilation: /nix/store/5l6b97jscljkvsq9y9amg71v5jfzddm4-gcc-wrapper-6.4.0/bin/gcc -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-v0.2.0-src/build/config -I/build/neovim-v0.2.0-src/src -I/nix/store/3q601pxyblbsllndsvjk5rb9m2g0qwpx-libuv-1.14.1/include -I/nix/store/wab2jyy4r3i79hqwwpqwg2pnbw161h5f-libmsgpack-2.0.0/include -I/nix/store/xfsbrzqjcbfzhscin998rqd4apvc7dh3-unibilium-1.2.0/include -I/nix/store/miz6idffbhw6i8x2abp9076j3xdrzy5w-libtermkey-0.19/include -I/nix/store/wm7i165cxx5zayjkl9mgpkrhpcggf46k-neovim-libvterm-2016-10-07/include -I/nix/store/3i2llfv140xak9dibxrjq888brhv1g3k-jemalloc-4.5.0/include -I/nix/store/j4q18y05wpnjin423wf69nfb7r7q0ml9-glibc-2.25-123-dev/include -I/build/neovim-v0.2.0-src/build/src/nvim/auto -I/build/neovim-v0.2.0-src/build/include
Compiled by nixbld

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/b230l4g299mcjk5grf80jsshbrbrydyn-neovim-0.2.0/share/nvim"
```
- Vim
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  1 1970 00:00:01)
Included patches: 1-1257
Compiled by nixbld
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     +gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
-clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        -perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "
/nix/store/mk9x723wg3zwzq627afxlzzryj60kfmn-vim-8.0.1257/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -ldl           
```
- Operating system/version: NixOS 17.09.2987.59890bb1351
- Terminal name/version: tmux 2.6
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:read !hexdump /dev/urandom | head -n 200
:set mouse=a
:noremap <ScrollWheelUp> <C-y>
:noremap <ScrollWheelDown> <C-e>
```
Then scroll up and down.

### Actual behaviour
Scrolls jump around — it seems that in *addition* to the user mapping, the standard behaviour is being triggered, resulting in rather confusing scrolling behaviour.

### Expected behaviour
Each scrollwheel tick scrolls a single line. This is the behaviour observed in vanilla vim.

**Comment by justinmk** [comment] 2018-02-15 13:44
Looks like a duplicate of https://github.com/neovim/neovim/issues/6211 . But that also was before 0.2.2 was released, please check that as @mhinz mentioned.

**Closed by justinmk** 2018-02-15 13:44 UTC
