### ISSUE TITLE
node.sj: Missing "neovim" npm package even though package is installed

### ISSUE THREAD

**Issue by jkehler** [neovim/neovim#8552] opened 2018-06-14 12:42 UTC
`nvim --version`:
```
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.0/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: 0.2.2) behaves differently?
- Operating system/version: antergos/arch Linux
- Terminal name/version: WSL Terminal (Windows SSH session)
- `$TERM`: xterm

### Actual behaviour
When running :checkhealth the Node.js provider reports that the neovim npm package is not installed.

```
 ## Node.js provider (optional)
- INFO: Node.js: v10.4.1
- WARNING: Missing "neovim" npm package.
   - ADVICE:
      - Run in shell: npm install -g neovim
      - Is the npm bin directory in $PATH?
```

I have confirmed that the npm neovim package is indeed installed via `npm install -g neovim`. I have also confirmed that I can load the neovim package using `require('neovim')` in node console.

Running `:UpdateRemotePlugins` does not resolve the issue.

The neovim package is currently installed under `/usr/lib/node_modules/neovim/` in my system.

I have looked at the `runtime/autoload/provider/node.vim` file and tried to troubleshoot the issue via Ex Mode (I dont know anything about vimscript so I might be doing all of this wrong)

The command `let global_modules_dir = get(split(system(cmd), "\n"), 0, '')` returns `/usr/lib/node_modules`

When I try executing the following `let entry_path = glob(global_modules_dir . '/neovim/bin/cli.js')` I get no output into that variable. So I believe the package check is failing here. I can confirm that the full path `/usr/lib/node_modules/neovim/bin/cli.js` does exist on my system.

Downgrading to Neovim 0.2.2 fixes my problem completely.

Some output when executing the following commands in Ex mode.

```
:echo glob('/usr/lib/node_modules/neovim/bin/cli.js')
:echo filereadable('/usr/lib/node_modules/neovim/bin/cli.js')
1
:echo glob('/usr/lib/node_modules')
/usr/lib/node_modules
:echo glob('/usr/lib/node_modules/neovim')
:echo glob('/usr/lib/node_modules/npm')
:
```

`filereadable` can read the file just fine. It is only the `glob` function that doesn't return any output for any of the folders inside of the `node_modules` folder. I tried various other packages that are in my `node_modules` folder and `glob` returns nothing for all of them.

I tried doing a complete `rm -rf /usr/lib/node_modules` folder and reinstalled Node completely. It didn't make any difference.

**Comment by janlazo** [comment] 2018-06-14 13:07
If this is about https://github.com/neovim/neovim/pull/8528, then it's not merged so end users shouldn't use it yet. If `glob()` or `filereadable` fail, then nvim cannot access or read it.

**Comment by jkehler** [comment] 2018-06-14 13:29
I dont believe my problem is related to #8528 since I'm using the version of neovim that is in the official Arch linux repositories not a custom build. Also the error output of that PR has changed to include the word yarn and my error output does not have that.

Is there any reason that nvim cannot read or access it? Again if I downgrade to 0.2.2 it works fine. I've tried completely removing the package and reinstalling it as well.

The permissions of the `/usr/lib/node_modules/neovim/bin/cli.js` file and related directories is `0755` which is readable by all users on the system. Again Node can read it as well as Neovim 0.2.2.

**Comment by jkehler** [comment] 2018-06-14 14:10
Some output when executing the following commands in Ex mode.

```
:echo glob('/usr/lib/node_modules/neovim/bin/cli.js')
:echo filereadable('/usr/lib/node_modules/neovim/bin/cli.js')
1
```

**Comment by janlazo** [comment] 2018-06-14 15:27
In `:h glob`, it's configurable with some options so you may have included `node_modules/` in one of them. That said, `filereadable` is enough to check if the file exists and is readable. Thanks for the report.

**Comment by jkehler** [comment] 2018-06-14 16:14
Ah thanks for the hint. I did have /node_modules/ set in my wildignore option. If i remove this then the check passes. Also if I pass TRUE into `{nosuf}` argument `glob('/usr/lib/node_modules/neovim/bin/cli.js', 1)` it returns the path successfully.

**Closed** 2018-06-17 11:08 UTC
Labels: provider, runtime

**Comment by isAarons** [comment] 2023-04-14 11:21
```
- ERROR **npm**: not available
- OK **node**: v18.15.0
```

**Comment by dundargoc** [comment] 2023-04-14 11:28
@isAarons open a new issue please, the problem is probably different
