### ISSUE TITLE
Treesitter conceal broken 

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#27853] opened 2024-03-14 09:41 UTC
### Problem

With the commit https://github.com/neovim/neovim/commit/cb46f6e467268edf917cc3617b4c024a66b256de the way treesitter-conceal was handled changed and broke treesitter conceal matching.
For example, if you use `queries/vimdoc/highlights.scm` with the content:
```lua
(tag
  "*" @label
  (#set! conceal "")
  text: (_) @label)
```
Then in vimdoc the tag conceal will be broken, as in instead of `*foo*` showing nothing it shows `*`

### Steps to reproduce

`nvim --clean`

`:help`

While using the `queries/vimdoc/highlights.scm` file:
```lua
(tag
  "*" @label
  (#set! conceal "")
  text: (_) @label)
```

### Expected behavior

Show the correct text when concealing

### Neovim version (nvim -v)

0.10.0-dev-00c4962

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

linux 6.7.9-arch1-1

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by clason** [comment] 2024-03-14 10:00
If you can't replicate it with `nvim --clean`, it's not a Neovim issue.

(In this case, it's a regression in the vimdoc parser.)

**Comment by altermo** [comment] 2024-03-14 10:15
I singled out https://github.com/neovim/neovim/commit/cb46f6e467268edf917cc3617b4c024a66b256de which changed the way conceal is handled, and also updated the bug report to not use nvim-treesitter.

**Comment by clason** [comment] 2024-03-14 10:35
Ok, the issue is that the PR changed how `#set!` behaves. This is documented but the commit was not marked as "breaking", so it slipped by me. This means the queries have to be adapted in nvim-treesitter. I know the fix but it will take some time (it's a big change).

**Comment by clason** [comment] 2024-03-14 10:51
Fixed downstream by changing the patterns broken by this: https://github.com/nvim-treesitter/nvim-treesitter/pull/6292.

Is it a bug if it's documented? Closing for now and letting @gpanders decide how to handle this.

**Closed by clason** 2024-03-14 10:51 UTC
Labels: bug, treesitter
