### ISSUE TITLE
Keeping cursor position while scrolling

### ISSUE THREAD

**Issue by ignamartinoli** [neovim/neovim#18938] opened 2022-06-12 19:28 UTC
### Feature already in Vim?

No

### Feature description

It would be cool if there was the possibility to live the cursor where it is while scolling to check some code real quick

**Comment by justinmk** [comment] 2022-06-12 20:27
duplicate of https://github.com/neovim/neovim/issues/989

I renamed it to make it easier to find

**Closed by justinmk** 2022-06-12 20:27 UTC
Labels: enhancement
