### ISSUE TITLE
spurious error highlight of curly brace on C compound literal

### ISSUE THREAD

**Issue by K4LCIFER** [neovim/neovim#14980] opened 2021-07-04 03:39 UTC
- `nvim --version`: NVIM v0.6.0-dev+1-g62d67de59
- Operating system/version: Arch Linux
- Terminal name/version: Alacritty
- `$TERM`: ?

### Actual behaviour
As you can see in the following screenshot (the code snippet is C), there is unneeded red highlighting of these curly braces; the braces are properly paired, but neovim thinks that they are not:
![image](https://user-images.githubusercontent.com/7829231/124372455-ac326900-dc3e-11eb-8756-ca57710dbb48.png)

### Expected behaviour
I would expect that the curly brace in the previous screenshot would not be highlighted red.

**Comment by justinmk** [comment] 2021-07-04 06:24
same issue in vim 8.2.2029 (please verify this next time, as requested by the issue template)

essentially a duplicate of https://github.com/neovim/neovim/issues/3234 , though that one doesn't mention highlighting specifically, it's the same root cause: Vim's builtin C syntax parser doesn't support [compound literals](https://en.cppreference.com/w/c/language/compound_literal).

**Closed by justinmk** 2021-07-04 06:24 UTC
Labels: 0.kind: bug-vim, bug, duplicate, syntax
