### ISSUE TITLE
Writing a Netrw compatiple explorer in lua to replace Netrw

### ISSUE THREAD

**Issue by saccarosium** [neovim/neovim#31554] opened 2024-12-11 20:31 UTC
### Problem

Netrw has a lot of problems:
- It is monolithic and tries to do too many things
- Is really difficult to modify / extend by plugins
- It is hard to fix and triage bugs since it is a thousand more lines of plugin written in legacy vimscript with like 1 space indentation
- Has some really poor UX decisions (multifile operations, alternate file is buggy, ...)

Having said that, Netrw is something that a lot of users, including myself, and it is probably a bad idea to replace it with an entirely different plugin.

### My solution

I was thinking for a while to write a Netrw compatible file explorer written in lua that address the issues mentioned above. I've worked on some patches wile developing for vim and I've studied the code a lot so I think I can do this.

I wanna to ask if is it something that the maintainers would be interested in. If so, I would love to working in on myself. Firstly I would probably do a standalone plugin and that as it matures maybe merge it into neovim.

**Comment by clason** [comment] 2024-12-11 20:38
Duplicate (will link and close when I am back at keyboard).

**Comment by clason** [comment] 2024-12-11 20:39
(The label should give you some indication where the maintainers stand on this...)

**Comment by justinmk** [comment] 2024-12-11 22:41
duplicate of https://github.com/neovim/neovim/issues/4378

> It is monolithic and tries to do too many things

related: 
- https://github.com/neovim/neovim/issues/23232
- https://github.com/neovim/neovim/issues/23231

**Closed** 2024-12-12 05:42 UTC
Labels: enhancement, netrw
