### ISSUE TITLE
No errors reported when `sp` is missing when calling `nvim_set_hl` but `underline/undercurl/etc` are set

### ISSUE THREAD

**Issue by MariaSolOs** [neovim/neovim#30081] opened 2024-08-18 03:54 UTC
### Problem

This is a bug/feature request, but recently I encountered a [strange bug](https://github.com/ibhagwan/fzf-lua/issues/1361) with a highlight mysteriously changing because I had set `underline = true` but didn't include `sp` when calling `nvim_set_hl`.

### Expected behavior

For an error/warning to be shown to the user when `sp` should be set.

### Neovim version (nvim -v)

v0.11.0-dev-610+g32d17cb6d

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 14.6.1

### Terminal name/version

fish

### $TERM environment variable

wezterm

### Installation

From source

**Comment by glepnir** [comment] 2024-08-18 04:03
Why  need throw an error here  If sp is not set, will use the default fg.

**Comment by MariaSolOs** [comment] 2024-08-18 04:05
> Why need throw an error here If sp is not set, will use the default fg.

Because it can cause the highlight to interact strangely when combined with things like backdrops. See [this comment](https://github.com/ibhagwan/fzf-lua/issues/1361#issuecomment-2254662014) for an example.

**Comment by zeertzjq** [comment] 2024-08-18 04:10
Duplicate of #14453

**Closed by zeertzjq** 2024-08-18 04:10 UTC
Labels: closed:duplicate
