### ISSUE TITLE
nvim: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by nvim)

### ISSUE THREAD

**Issue by nippyin** [neovim/neovim#21261] opened 2022-12-02 00:36 UTC
### Neovim version (nvim -v)

Latest release

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Operating System: Red Hat Enterprise Linux 8.4 (Ootpa)

### Terminal name/version

Solarwind Putty

### $TERM environment variable

xterm-256

### Installation

tar file

### How to reproduce the issue

>untar the tar file and move it in `/usr/bin/nvim`
>run nvim on the terminal and getting following output instead of editor

[user@aser1]~% nvim
`nvim: /lib64/libm.so.6: version GLIBC_2.29 not found (required by nvim)`

```
   Static hostname: aser1
         Icon name: computer-vm
           Chassis: vm
        Machine ID: a869311b25bb46a1be50f74b6ac7f4b9
           Boot ID: de14aefafe7c47379b7c93ac813b0df7
    Virtualization: microsoft
  Operating System: Red Hat Enterprise Linux 8.4 (Ootpa)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:8.4:GA
            Kernel: Linux 4.18.0-372.26.1.el8_6.x86_64
      Architecture: x86-64
```

### Expected behavior

No error.

### Actual behavior

```
nvim: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by nvim)
```

**Comment by zeertzjq** [comment] 2022-12-02 00:40
Did you use the v0.8.1 appimage and still get this error?

**Comment by nippyin** [comment] 2022-12-02 01:30
Yes


________________________________

**Comment by clason** [comment] 2022-12-02 12:54
Does it work if you just run the appimage without extracting it?

**Comment by nippyin** [comment] 2022-12-02 13:12
> Does it work if you just run the appimage without extracting it?

Its a tar file and I extract it under ~/.config directory.
Then I create a symbolic link to /usr/bin/nvim

**Comment by justinmk** [comment] 2023-01-08 22:45
duplicate of https://github.com/neovim/neovim/issues/20581



> Installation
> tar file

wait... why are we providing a tar file? of course that won't work except on systems that closely match whatever CI job was used to build the tar file.

**Comment by nippyin** [comment] 2023-01-09 00:22
> duplicate of #20581
> 
> > Installation
> > tar file
> 
> wait... why are we providing a tar file? of course that won't work except on systems that closely match whatever CI job was used to build the tar file.

Could you please guide how should i install nvim without tar file on RHEL 8.5?

**Comment by justinmk** [comment] 2023-01-09 01:49
> Could you please guide how should i install nvim without tar file on RHEL 8.5?

use the appimage listed at https://github.com/neovim/neovim/releases . follow the instructions there.

**Comment by kabouzeid** [comment] 2023-01-31 13:08
`bat` "fixed" it like this https://github.com/sharkdp/bat/pull/2194

**Comment by dundargoc** [comment] 2023-02-04 17:59
I don't think crosscompiling against older versions or whatever bat did is feasible for us. I think some form of vittualization is the way to go unfortunately.

**Comment by dundargoc** [comment] 2023-02-04 18:00
Actually, justin has a point: why are we providing tar/deb files lol? I'll create a pr to remove it.

**Comment by dundargoc** [comment] 2023-02-06 18:44
Reopening as this isn't solved. Either we need to

1. remove the tar from releases.
2. make the tar work on this version of glibc
3. Explicitly mention in the release notes minimum version of glibc we're willing to support.

**Comment by kabouzeid** [comment] 2023-02-07 14:55
the tar is imo still useful because it includes the `man` dir for example.

**Comment by dundargoc** [comment] 2023-02-07 23:29
The manpages doesn't look super useful tbh since it's already described in `:h cli-arguments`. Unsure about what the `nvim.desktop` is good for.

**Comment by kabouzeid** [comment] 2023-02-08 10:32
this is for proper installing on a linux system as a package manger would. the `.desktop` file makes it discoverable by application launchers.

**Comment by justinmk** [comment] 2023-02-09 12:40
>  remove the tar from releases.

That would be my preference. I don't want to maintain multiple different linux install packages. If AppImage isn't good enough, user needs to build from source or use a package manager (e.g. linuxbrew if you want HEAD).

**Comment by jamessan** [comment] 2023-02-09 14:14
> Was there some other reason for introducing the tar artifact? @jamessan 

I believe we started with that and never stopped providing it when we added the appimage.

**Comment by dundargoc** [comment] 2023-03-27 07:36
https://github.com/neovim/neovim/issues/22684

**Comment by hanshanglin** [comment] 2023-05-04 03:36
hi all, is there any alternative way to run nvim under this issues?

**Comment by zeertzjq** [comment] 2023-05-04 03:57
Use appimage

**Comment by dundargoc** [comment] 2023-05-04 07:06
Why would appimage work but not tar.gz? They are built in the same container.

**Comment by clason** [comment] 2023-05-04 07:15
_Now_ they are. This issue comes from a time when they weren't (which is one of the reasons we wanted to drop the tar.gz).

**Comment by dundargoc** [comment] 2023-05-04 07:20
> This issue comes from a time

It was reopened 3 hours ago, but whatever.

This should have been fixed on master. We can close this. Wait for a 0.9.1 release.

**Closed** 2023-05-04 07:20 UTC
Labels: bug, needs:discussion
