### ISSUE TITLE
Neovim cannot execute external commands if started from Git-Bash

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#14605] opened 2021-05-21 09:25 UTC
- `nvim --version`:
```
NVIM v0.5.0-dev+1339-g5d9c56012
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/T
ools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2
/Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32
-D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT3
2 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config
-ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovi
m/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-612

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
```
Installed from Chocolatey in `c:\tools\neovim\Neovim\bin\`
- Operating system/version: Windows 10 20H2
- Terminal name/version: mintty 3.4.7
- `$TERM`: xterm

- [x] `vim -u DEFAULTS` (version: 8.2.2840 ) behaves differently

### Steps to reproduce using `nvim -u NORC`
Launch Git-Bash, then
```
winpty nvim -u NORC
:!ls
# alternatively, execute a program natively compiled for Windows, for example
:!youtube-dl --version
```

### Actual behaviour
Neovim returns
```
/usr/bin/bash: /s: No such file or directory 

shell returned 127
```

### Expected behaviour
Neovim should successfully run `ls`  or `youtube-dl --version` like Vim does when launched from Git-Bash (note: I'm talking about native Vim for Windows, not Vim bundled with the Git-for-Windows distribution).

**Comment by matveyt** [comment] 2021-05-21 16:50
I believe you should get the same result with Vim for Windows. The point is that `$SHELL` is wrong (non-Windows path). Therefore you have to execute it with `SHELL= winpty nvim` instead.

**Comment by bob-marcus** [comment] 2021-05-21 21:07
@matveyt Thanks for your reply. If I do `:echo $SHELL` in both Neovim and Vim for Windows, the shell path is the same `C:\Program Files\Git\usr\bin\bash.exe`.
However, if I execute `:!ls` from inside Vim for Windows launched from Git Bash, the first line that appears in the popup `vimrun.exe` window is `"C:\Program Files\Git\usr\bin\bash.exe" -c "ls"`.
About your third point, do you mean that I should put the line `let SHELL="winpty nvim"` in my `init.vim`?

**Comment by janlazo** [comment] 2021-05-21 23:48
This is valid longstanding bug because Vim adjusts the shell-related options for Windows if the tail of the filepath for  `shell` option contains `sh`. It likely was removed in the initial commit of Neovim and not restored by 0.2.0 release.

Problem is that Vim relies on `vimrun.exe` to run system and `:!` bangs while Neovim executes it directly so restoring the Vim code to auto-adjust the shell-related options will not be a 1-1 port.

Adding this to 0.5.1 milestone unless a hero can submit a correct patch by 0.5.
Shell-related options are difficult to correctly set.
It's an ongoing process for me in my own config, https://github.com/janlazo/dotvim8/blob/16b897a7a30c3f1d2f34b90e95dedc477da3d3cb/shared.vim#L195

**Comment by kaabus** [comment] 2021-07-01 07:28
Can I take up this issue ??

**Comment by janlazo** [comment] 2021-07-01 15:48
Yes.

**Comment by Adnn** [comment] 2022-07-27 10:12
Are there current recommendations on how to get Neovim to execute external commands when it is launched from git-bash?

**Comment by matveyt** [comment] 2022-07-27 10:43
@Adnn 

```VimL
if &shell =~? 'sh\.exe$'
    set shellcmdflag=-c
endif
```

**Comment by evesdropper** [comment] 2022-08-02 19:21
> Are there current recommendations on how to get Neovim to execute external commands when it is launched from git-bash?

I believe @janlazo's shell config works for me (i.e. `:! ls` works now.

However, since we're on this topic, it appears that while terminal commands work, I do not have such luck when it comes to plugins - the given shell does not work with Vim-Plug and Vimtex returns the same `/usr/bin/bash: /s: No such file or directory`. Is there a way to configure the shell so that it works for certain plugins?

**Comment by justinmk** [comment] 2022-08-03 15:28
> Is there a way to configure the shell so that it works for certain plugins?

? That's the plugin's responsibility.

If 'shell' is misconfigured and the request here is to improve the defaults for git-bash, please open a new issue with complete details about Nvim version, 'shell' and shell-related settings, and exact steps to reproduce the issue.

Closing this issue because it has almost no useful information, with followup comments that don't mention Nvim version.

**Closed by justinmk** 2022-08-03 15:28 UTC
Labels: bug, platform:windows, complexity:non-trivial

**Comment by Grave18** [comment] 2023-02-05 11:28
As a workaround on nvim 0.8.2 I use this in my init.vim :let &shell = '"C:\WINDOWS\system32\cmd.exe"'

**Comment by kaminskypavel** [comment] 2023-03-20 09:10
for a quickfix I'd suggest setting the shell to be cmd.exe

in `init.lua` add:
**`vim.opt.shell = 'cmd.exe'`**
