### ISSUE TITLE
Setting 'v' register type doesn't work while clipboard=unnamed.

### ISSUE THREAD

**Issue by Teeheey** [neovim/neovim#11098] opened 2019-09-25 18:21 UTC
- NVIM v0.4.2
- Build type: Release
- OS X 10.14.7
- Iterm2
- $TERM - xterm-256color

Hi there!
I noticed, that when set clipboard=unnamed I can't change register type from linewise(```V```) to characterwise(```v```).
There is no problem with changing from ```v``` to ```V```by the way.

# Steps done with `nvim -u NORC`
1) yank whole line to get register with linewise type (```dd / yy```)
2) check type of rigester via  ```:echom getregtype(v:register)```
it is ```V``` now
4) change register type by ```:call setreg(v:register, getreg(v:register), 'v')```
5) check type of rigester via  ```:echom getregtype(v:register)```
it is ```v``` now

# Add :set clipboard=unnamed
1) yank whole line to get register with linewise type (```dd / yy```)
2) check type of rigester via  ```:echom getregtype(v:register)```
it is ```V``` now
4) change register type by ```:call setreg(v:register, getreg(v:register), 'v')```
5) check type of rigester via  ```:echom getregtype(v:register)```
### Expected behaviour
Should be ```v``` now

### Fact
It is still ```V```

**Comment by marcotrosi** [comment] 2019-09-25 18:23
I tried here and I can confirm your discovery. thx.

**Comment by Findas** [comment] 2019-10-08 07:53
I wanted to contribute to this issue as my first issue, but I can't reproduce that on Ubuntu LTS 18.04 with the 0.4.2 release nor the nightly am I doing something wrong or is this OS X specific?

**Comment by bfredl** [comment] 2019-10-09 06:44
The entire issue is OS-specific. On X11 we have a hack to keep register type of clipboard at least within the same instance (but not across instances). On OS X neither works.

Duplicate of https://github.com/neovim/neovim/issues/1822 (it mentions "block", but the same issue exists for a "char" clipboard ending with `\n`)

**Closed** 2019-10-10 08:32 UTC
Labels: Hacktoberfest, bug, clipboard, complexity:low, good first issue, help wanted

**Comment by marcotrosi** [comment] 2019-10-15 14:12
@bfredl if the issue is OS specific why doesn’t this issue exist for Vim on the same OS?
Only NeoVim seems to have this problem but not Vim

**Comment by chrisbra** [comment] 2019-10-15 14:15
because it uses the clipboard provider (because you have `set clipboard=unnamed`), which is an external program that is executed depending on your platform. Might try a different provider in this case.

**Comment by Teeheey** [comment] 2019-10-15 14:17
@chrisbra could u provide more info, how can I make it?
are there any another workarounds ?

**Comment by bfredl** [comment] 2019-10-15 14:22
@marcotrosi because clipboard is an os specific feature. I am not sure where the assumption comes from that nvim and vim somehow only would differ in platform unspecific code.

**Comment by chrisbra** [comment] 2019-10-15 14:31
Vim doesn't use the clipboard provider infrastructure but has (platform) specific clipboard interface built in. That is one of the differences between Vim and Neovim (which always delegates the clipboard specific code to the clipboard provider).

**Comment by marcotrosi** [comment] 2019-10-15 14:35
Thank you @chrisbra

**Comment by bfredl** [comment] 2019-10-15 15:26
@marcotrosi Someone could indeed port the vim implementation https://github.com/vim/vim/blob/master/src/os_macosx.m to a nvim provider. There is no reason really other than no one has stepped in yet and done the work. (I haven't tried it myself, as I don't have a mac).
