### ISSUE TITLE
Add `SearchStart` and `SearchStop` events

### ISSUE THREAD

**Issue by uwla** [neovim/neovim#30062] opened 2024-08-15 14:02 UTC
### Description

Add an event before search starts with `/`, `*`, `?` and after it stops.

This can be useful for plugins that would set/unset options and enable/disable keymaps before and after the search.

A basic usage would be to toggle the scrolloff`autocmd SearchStart set scrolloff=999`, `autocmd SearchStop set scrolloff=0` so when we are searching the text is always in the middle (sometimes it is put on the bottom and is hard to see the next lines)

A more advanced usage would be a plugin that enables keymappings available only during search such as `i` to toggle insensitive search, `p` to toggle a side panel with all avaiable search results, using `w` to toggle search on all visible `windows`, `t` to toggle search on all tabs, `r` to toggle regex search.

I am not aware if such plugin exists, but I am just giving an example of what could be accomplished: customization and more powerful search behavior.

### Expected behavior

Two new events `SearchStart` and `SearchStop` just like `BufEnter`, `WinNew`, etc ...

**Comment by justinmk** [comment] 2024-08-15 14:22
> This can be useful for plugins that would set/unset options and enable/disable keymaps before and after the search.

Describe an exact scenario showing exact steps.

Is this for incremental search while typing in the `/` prompt? That can already be achieved via `CmdlineEnter`/`CmdlineLeave`.

**Comment by zeertzjq** [comment] 2024-08-15 22:55
There is no such thing as "stopping" a search.

**Comment by justinmk** [comment] 2024-08-16 15:34
> when we are searching ... only during search

What does this *mean*? I asked for exact steps. I assume you mean:

- when `n` is pressed to go to a search result
- while search results are highlighted (until `:nohlsearch`)

Thus this is a duplicate of https://github.com/neovim/neovim/issues/18879

**Closed by justinmk** 2024-08-16 15:34 UTC
Labels: enhancement, events
