### ISSUE TITLE
Semantic Highlighting, Folding

### ISSUE THREAD

**Issue by stellarhoof** [neovim/neovim#719] opened 2014-05-14 15:38 UTC
Hi guys. I was wondering how hard would it be to implement syntax highlighting / folding which are aware of the semantics of the program given an AST. This AST could be built from any external tool and output in a format recognized by nvim.

**Comment by myitcv** [comment] 2015-10-03 15:18
As a brief update on this thread, given that #1107 has been merged `matchaddpos` is available in `neovim`. 

[`neogo`](https://github.com/myitcv/neogo) is the updated plugin I mentioned above. It is a Go MSGPACK plugin written using the [`neovim`](https://godoc.org/github.com/myitcv/neovim) package to read the contents of the buffer being edited, parse using [`go/parser`](https://godoc.org/go/parser) into an AST, then [spit out byte offset-based syntax highlighting commands using `matchaddpos`](https://github.com/myitcv/neogo/blob/cdd00c4c2ef8e2be53eadfdbda2a30951ce3a582/neogo.go#L168) and [`matchdelete`](https://github.com/myitcv/neogo/blob/cdd00c4c2ef8e2be53eadfdbda2a30951ce3a582/neogo.go#L182)

Thanks for @fmoralesc for #1107

**Comment by fmoralesc** [comment] 2015-10-03 15:27
Great demo, @myitcv! It's also very nice to see that you've been making progress on the go host.

**Comment by justinmk** [comment] 2015-10-03 15:29
@myitcv That's awesome. How does it feel on large files? If user edits in the middle of some function, does the parser have enough state to tell the go code "only `matchdelete()` these nodes, and `matchaddpos()` these other specific nodes", or is it rebuilding the entire buffer on each keypress?

**Comment by myitcv** [comment] 2015-10-03 15:51
@justinmk the current implementation is extremely inefficient for two reasons:

* The conversation in #1114
* `neogo` spits out `matchaddpos`/`matchdelete` commands for the entire buffer. This could easily by optimised to only spit out commands for the current view port (i.e. the user is currently looking at the contents from byte offset `X` to `Y`, hence only spit out highlighting commands that affect that region)

Even with a solution from #1114, the `go/parser` package will ultimately be reparsing the entire buffer each time. The package is extremely fast (takes ~35ms to parse a 20k file) so I don't expect this to be an issue most of the time, but still, this is another area where things could be improved.

**Comment by fmoralesc** [comment] 2015-10-03 15:58
@myitcv On your second point, I guess you could *cache* the matchaddpos commands for highlighting outside of the viewport. You would probably need to delete/update all the matchaddpos commands for matches after it (because inserts could make them invalid), though, and that might be complicated.

**Comment by myitcv** [comment] 2015-10-03 16:07
@fmoralesc this is what I was thinking:

* maintain an AST of the current buffer contents - easy
* when the contents of the buffer update, update the AST - easy, but not efficient for a couple of reasons as discussed above)
* only output `matchaddpos` commands for the current viewport (calculated from the current AST, which gives byte offsets of each token)
* maintain a set of current `matchaddpos` commands sent to neovim
* when the viewport changes, call `matchaddpos`/`matchdelete` as required based on the current `matchaddpos` commands

This all assumes I can ask neovim "what is the current view port in terms of byte offsets"... can I do that?

**Comment by justinmk** [comment] 2015-10-03 16:21
> "what is the current view port in terms of byte offsets"... can I do that?

The vimscript `winsaveview()` function combined with `winheight('%')` and `winwidth('%')` can give you the viewport, though of course in the future we will look to add first-class properties to the API.

**Comment by fmoralesc** [comment] 2015-10-03 16:25
@justinmk That means we would need to notify viewport changes. Not sure how that would work along the UI infraestructure and @tarruda's proposed smart UI mechanism.

**Comment by justinmk** [comment] 2015-10-03 16:38
Just to be clear, by "first class properties" I do not be properties that are "bound" (I think that would be a bad idea). I just mean API calls that do not require vimscript strings.

**Comment by bfredl** [comment] 2015-10-03 17:03
@myitcv If you like you could test to use #1817 which intends to have better semantics and performance that matchaddpos for these kinds of usages. (e.g should scale better for lots of added highlights, allows batch deletions of lineranges of highlights). Though realistically it won't be finished/merged in the timeframe of 0.1, but I think its eligible for 0.2.
The documentation is currently missing, but hopefully https://github.com/neovim/neovim/pull/1817#issuecomment-72335766 is explaning the basic API, as well as the unit test.

**Comment by myitcv** [comment] 2015-10-03 17:05
@bfredl - certainly will add it to the list. The optimisations I've described above will, however, probably get us 90% of the way there.

**Comment by bfredl** [comment] 2015-10-03 18:23
True, the point of #1817 is to make it _simpler_ for highlighting plugins to give a smooth and performant experience, especially when 1) switching between buffers in a window and 2) deleting or inserting lines in the beginning (or before) or middle of the current viewport (which would make matchaddpos items misaligned immediately)

**Comment by myitcv** [comment] 2015-10-04 07:24
@bfredl 

> but matches tied to a specific buffer and not the current window.

This shows how little I have tested my prototype! Sounds eminently sensible to be tying these highlights to buffers.

One thought on the API (apologies if I have missed discussion elsewhere):

I think the API should be a byte-offset based approach. Parsers will in all likelihood work with byte offsets under the covers, as does neovim (unless I am mistaken). And so this will be the most efficient means of generating and using syntax highlighting commands. At the moment I'm translating between byte offsets and line/col references, but only in order to call `matchaddpos`.

> It should respond to removing/inserting lines before, and deleting highlighting lines (though not undoing deletes)

Can you explain this a bit more? Surely we can't make any guarantees about a highlight still being valid when a line gets inserted/deleted? Only the parser can know that.

**Comment by bfredl** [comment] 2015-10-04 08:21
AFAIK neovim mostly works with line/col numbers ( and there is lots of "stuff that happens" when lines are renumbered: marks, signs, folds etc are updated, but less so when shifting chars within a line..)
But won't most parsers emit line/col pairs as well, I mean for human-readable syntax errors anyway? (as a data point clang cindex API has full support for both). In the long run it might be good to gain a byte-based buffer API but I think it's out of scope for #1817 .

>  Surely we can't make any guarantees about a highlight still being valid when a line gets inserted/deleted? Only the parser can know that.

True, the question is what happens the split second before the parser had time to rerun. Instead of immediately clearing all highlight below, just letting the old highlights follow along will probably give a smoother transition. (consider the case where a blank line is deleted or inserted, the user won't even notice that an update was needed)

**Comment by myitcv** [comment] 2015-10-04 09:34
> AFAIK neovim mostly works with line/col numbers

I am mistaken therefore :+1: 

> But won't most parsers emit line/col pairs as well

Yes they will. But I think the [minimum representation](https://github.com/golang/go/blob/2adc4e892704bb99f2d16c0c09777987cb6bed35/src/go/token/position.go#L71) needed in a parser is the byte offset; the line, col etc is always derivable. Perhaps I was trying to prematurely optimise....

Either way, the goal behind my comment was to have the most efficient implementation for what is a very sensitive part of the code base, especially when it comes to large files (as @justinmk alluded to earlier). If however neovim currently works by line/col references, then this efficiency goal is somewhat subsumed by the complexity of the changes that would be required for `v0.1`. 

So practically speaking, if neovim works with line/col references then it probably makes sense for `v0.1` of the API you're proposing to also be line/col based, I agree.

**Comment by myitcv** [comment] 2015-10-04 10:27
@justinmk - incidentally, for me to start using `winsaveview()` I need #1250 to have landed (just commented there because I've seen the milestone slip to `0.2`)

**Comment by bfredl** [comment] 2015-10-04 11:03
How is #1250 related, ain't `winsaveview()` just a dict of numerical values ?

**Comment by myitcv** [comment] 2015-10-04 11:29
It's a dict yes; and dicts have string keys (can they be anything else, not sure). But right now the string keys are encoded as MSGPACK `BIN`. 

To be fair in the meantime I could use multiple calls to `eval winsaveview()['leftcol']` etc.. 

But as I mention in #1250, the proposal we have agreed upon is a breaking change for the writers of plugin hosts so should be in `0.1`

**Comment by bfredl** [comment] 2015-10-04 11:41
can't you just assume BIN keys are valid ASCII/UTF-8 in the meanwhile? or maybe is limitation with the msgpack library you're using? Anyway #1250 in 0.1 would be good, but is it really breaking? Mean a plugin host could just hande both incoming BIN and STR correctly already, and would not be affected when neovim switches to STR per defaullt.

**Comment by myitcv** [comment] 2015-10-04 11:47
I wouldn't describe it as a limitation :)

There would be relatively significant changes needed to the library, yes. And the same would be the case for all other typed language MSGPACK libraries. So my point is really that this can be more easily fixed at source.

And yes it is breaking because the encoding of the API `String` is part of the API definition.

**Comment by bfredl** [comment] 2015-10-04 12:18
>  And the same would be the case for all other typed language MSGPACK libraries. 

Not true. You could just allow a static type to match both STR and BIN, as the haskell msgpack library allows for instance (by the same mechanism, say, it matches a msgpack int when a Float is expected), and nvim-hs does, if I understand it correctly. But sorry for the nitpick, I agree #1250 sooner than later would make life easier for new hosts :)

**Comment by myitcv** [comment] 2015-10-04 12:23
@bfredl - sorry, yes. That was a rather broad sweeping statement that is easily proved wrong :+1:

**Comment by jeaye** [comment] 2015-10-11 12:57
Vanilla vim works quite well with https://github.com/jeaye/color_coded if we exclude the lack of an asynchronous API. I'm certainly interested in supporting neovim in color_coded and I'd welcome any help.

**Comment by bfredl** [comment] 2015-10-11 13:19
@jeaye I used color_coded a while back to test drive #1817 though it is presently only a ugly hack that doesn't integrate well with the rest of the codebase and uses the python-client/cffi as a "bridge" to communicate with neovim. What I indented to do was to then use `msgpack.cpp` to directly communicate with neovim without any bridge, but unfortunately I haven't had time to work on it yet. FWIW my fork is [here](https://github.com/bfredl/color_coded/tree/nvim_bufhl)

**Comment by jeaye** [comment] 2015-10-11 13:33
@bfredl That's very exciting to see! color_coded has changed a lot since then, unfortunately, but it's excellent that you were able to test drive it. I'm still very new to neovim and its asynchronous API, but neovim support has been on my mind for a while.

A big issue with the marriage of vim and libclang, right now, is that every libclang plugin wrangles the AST manually. This means that, if I have 5 plugins using libclang to do *something*, my code will be compiled at least 5 times. I've spoken with @oblitum, a YCM collaborator, about this. Before much work goes into bringing more libclang-based plugins (like color_coded) to neovim, I think this is something that should be thoroughly considered.

**Comment by purpleKarrot** [comment] 2015-11-05 08:40
FYI: http://thread.gmane.org/gmane.comp.compilers.clang.devel/21780

**Comment by teto** [comment] 2015-11-05 14:05
@purpleKarrot  Look(ed) promising but the mails are from 2012, was any substantial code produced from that ? https://github.com/crange/crange is from ~2014 but it's not the same (not a server but a static db apparently)

**Comment by torpak** [comment] 2015-11-18 10:34
@jeaye maybe it would help to define an api that is language agnostic and includes most usecases:
* type analysis semantic coloring and maybe context sensitive doc display
* positional completion
* error and warning information (short and long messages, positions and related positions for warnings and errors)
* other usecases?

Then plugins using this api could be language agnostic and use backends for any language.

**Comment by justinmk** [comment] 2017-12-23 14:27
[tree-sitter](https://github.com/tree-sitter) (see also [video](https://youtu.be/a1rC79DHpmY)) looks like a viable option.

- C lib with minimal dependencies
- more momentum (and more grammars) than scintillua just by association with Atom editor
- advanced features like incremental parsing and error recovery (not sure if scintillua has those)

**Comment by stellarhoof** [comment] 2017-12-23 17:13
@justinmk Looks very promising. It looks like christmas came early.

**Comment by justinmk** [comment] 2018-03-23 17:21
Discussion above is mostly outdated.  
Closing this as duplicate of https://github.com/neovim/neovim/issues/1767.

**Closed by justinmk** 2018-03-23 17:21 UTC
Labels: enhancement, syntax

**Comment by trusktr** [comment] 2018-04-17 22:28
We need this badly, f.e. here's why: https://github.com/posva/vim-vue/issues/95

**Comment by trusktr** [comment] 2018-04-17 22:28
We need this badly, f.e. here's why: https://github.com/posva/vim-vue/issues/95
