### ISSUE TITLE
Copy text auto append `\n` in the end

### ISSUE THREAD

**Issue by ciknight** [neovim/neovim#9177] opened 2018-10-31 03:44 UTC
- `nvim --version`:
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/build/config -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/build/include
Compiled by brew@Sierra-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

     system vimrc file: "$VIM/sysinit.vim"
   fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently? **8.1.150**
- Operating system/version: **macOS 10.13.5**

- Terminal name/version: **ITerm2 Build 3.1.6**
- `$TERM`: **xterm-256color**

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set clipboard+=unnamedplus
i
this is text
<esc>
<C-v>byp
```

### Actual behaviour

Copy `text` auto append `\n` in the end

```
this is text
text
```

### Expected behaviour
```
this is ttextext
```

This is the behavior exhibited when using vim 8 via vim -u NORC

**Comment by justinmk** [comment] 2018-10-31 09:38
Duplicate of #1822

(I found the issue by using the "clipboard" label)

**Closed by justinmk** 2018-10-31 09:38 UTC
Labels: duplicate
