### ISSUE TITLE
"hi clear" statements not working at init.

### ISSUE THREAD

**Issue by karoliskoncevicius** [neovim/neovim#22973] opened 2023-04-09 08:25 UTC
### Problem

Setting colorscheme from init.vim broke after updating to NeoVim v0.9.0.

I have a custom colorscheme in ./config/nvim/colors/colors.vim
In my config file at ./config/nvim/init.vim I set the colorscheme with `colorscheme colors`

But yesterday after NeoVim update this stopped working.
Now for it to work I have to call `:colorscheme colors` manually after starting NeoVim.

Seems like only `hi clear` statements are affected.

### Steps to reproduce

Have this as `./config/nvim/init.vim`:

    filetype plugin indent on

    syntax enable
    colorscheme colors

Have this as `./config/nvim/colors/colors.vim`:

    hi clear

    if exists('syntax_on')
      syntax reset
    endif

    syntax enable
    set background=dark

    hi clear Number
    hi clear Character
    hi clear Statement
    hi clear Type
    hi clear Function
    hi clear PreProc
    hi clear Special
    hi clear Identifier
    hi clear Constant
    hi clear Boolean
    hi clear String
    hi clear Delimiter
    hi clear Conceal
    hi clear Directory

### Expected behavior

`hi clear` statements are applied after starting NeoVim, without the need to call the colorscheme manually.

Seems like the was the behaviour in the previous version of NeoVim.

### Neovim version (nvim -v)

0.9.0 Release

### Vim (not Nvim) behaves the same?

no, vim 9.0.270

### Operating system/version

macOS 13.3

### Terminal name/version

Apple terminal 2.13; GNU screen 4.09.00

### $TERM environment variable

screen-256color

### Installation

macports

**Comment by zeertzjq** [comment] 2023-04-09 08:50
What is the version you are previously on?

**Comment by karoliskoncevicius** [comment] 2023-04-09 08:53
v0.8.3 (also installed with MacPorts).

**Comment by zeertzjq** [comment] 2023-04-14 02:41
Maybe this is duplicate of #22614?

**Comment by zeertzjq** [comment] 2023-05-23 07:13
Duplicate of #22614

**Closed by zeertzjq** 2023-05-23 07:13 UTC
Labels: bug-regression, highlight
