### ISSUE TITLE
synmaxcol interferes with "%" operator

### ISSUE THREAD

**Issue by edi9999** [neovim/neovim#30934] opened 2024-10-24 15:23 UTC
# synmaxcol Setting Interferes with `%` Bracket Matching Position

## Bug Description

When `set synmaxcol=400` is set, the `%` motion (bracket matching) incorrectly identifies the matching closing bracket, jumping to the wrong position in the file.

## Steps to Reproduce
1. Create a test file with the following content:
```javascript
describe("FOOBAR", function () {
    it("FOOBAR", function () {
        name = "style-text-tag.docx";
        expectedName = "expected-style-align.docx";
        data = {
            loop: [
                {
                    style:
                        "text-justify Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                },
            ],
        };
        this.loadAndRender();
    });
});
```

2. Set `synmaxcol=400` in your Neovim configuration
3. Go to line 2 (the line containing `it("FOOBAR", function () {`)
4. Move to the end of the line using `$`
5. Press `%`

## Expected Behavior
The cursor should jump to the matching closing brace on the line before the last line (the line containing just `    });`).

## Actual Behavior
The cursor incorrectly jumps to the last line of the file (the line containing just `});`), matching with the wrong closing brace.

## Environment
- Neovim version: NVIM v0.10.2 Build type: RelWithDebInfo LuaJIT 2.1.1713484068
- Operating System: Ubuntu 22.04.5 LTS \n \l

## Additional Information
- The issue can be temporarily resolved by removing the  `synmaxcol` setting.
- This appears to be an unexpected interaction between syntax highlighting limits and bracket matching functionality
- The issue specifically occurs when there's a long line (>400 characters) within the function block

**Comment by clason** [comment] 2024-10-24 15:25
That is how it's supposed to work; `matchit` relies on syntax to find matches.

**Comment by edi9999** [comment] 2024-10-24 15:26
Other note : standard vim does not behave like that : 

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep  4 2024 22:39:45)
Included patches: 1-576
```

**Comment by clason** [comment] 2024-10-24 15:27
Please try the latest version 9.1.0813.

**Comment by clason** [comment] 2024-10-24 15:30
And to make sure, this is with `nvim --clean`? And legacy syntax highlighting is actually enabled (Lua files use tree-sitter highlighting by default instead, which means that `matchit` -- which _does_ rely on legacy syntax -- won't work fully.)

**Comment by edi9999** [comment] 2024-10-24 16:19
I have tried with treesitter but still have got the same issue.

Also I've recorded the issue : 

![Image](https://github.com/user-attachments/assets/6defb818-2075-41c4-b24f-1d050f8f8454)

**Comment by clason** [comment] 2024-10-24 16:26
> I have tried with treesitter but still have got the same issue.

I meant the json highlighting with long lines; of course matchit will have the same issue.

**Comment by justinmk** [comment] 2024-10-24 16:38
duplicate of:

- https://github.com/neovim/neovim/issues/15462

**Closed by justinmk** 2024-10-24 16:38 UTC
Labels: plugin, runtime, syntax, treesitter
