### ISSUE TITLE
document of termopen should update or a bug of termopen.

### ISSUE THREAD

**Issue by kevinhwang91** [neovim/neovim#11829] opened 2020-02-07 13:18 UTC
```vim
termopen({cmd}[, {opts}])			*termopen()*
		Spawns {cmd} in a new pseudo-terminal session connected
		to the current buffer.  {cmd} is the same as the one passed to
		|jobstart()|.  This function fails if the current buffer is
		modified (all buffer contents are destroyed).

		The {opts} dict is similar to the one passed to |jobstart()|,
		but the `pty`, `width`, `height`, and `TERM` fields are
		ignored: `height`/`width` are taken from the current window
		and `$TERM` is set to "xterm-256color".
		Returns the same values as |jobstart()|.

		See |terminal| for more information.
```
but I saw code about `static void f_termopen(typval_T *argvars, typval_T *rettv, FunPtr fptr)`, which ignored not only `pty`, `width`, `height`, and `TERM` fields, but also `env` which I expect to pass into the terminal.

**Comment by justinmk** [comment] 2020-02-08 08:42
looks like duplicate of https://github.com/neovim/neovim/issues/11751

**Closed by justinmk** 2020-02-08 08:42 UTC
Labels: bug
