### ISSUE TITLE
nightly version crash after opened a file

### ISSUE THREAD

**Issue by jheroy** [neovim/neovim#28451] opened 2024-04-22 01:26 UTC
### Problem

           PID: 1539133 (nvim)
           UID: 1000 (*)
           GID: 1000 (*)
        Signal: 11 (SEGV)
     Timestamp: Mon 2024-04-22 09:13:08 CST (2s ago)
  Command Line: nvim --embed init.lua
    Executable: /usr/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (*)
       Boot ID: c9e76f59bef1477eb2954aba1a3233ca
    Machine ID: 7de618f5a96249eaa30802cbf5a1be86
      Hostname: archlinux
       Storage: /var/lib/systemd/coredump/core.nvim.1000.c9e76f59bef1477eb2954aba1a3233ca.1539133.1713748388000000.zst (present)
  Size on Disk: 7.3M
       Message: Process 1539133 (nvim) of user 1000 dumped core.
                
                Stack trace of thread 1539133:
                #0  0x000059e132cfc8f8 changed_window_setting (nvim + 0x1d28f8)
                #1  0x0000731065b37359 n/a (libluajit-5.1.so.2 + 0xc359)
                #2  0x0000731065b5ce74 n/a (libluajit-5.1.so.2 + 0x31e74)
                #3  0x0000731065b97595 n/a (libluajit-5.1.so.2 + 0x6c595)
                #4  0x0000731065b34ef6 n/a (libluajit-5.1.so.2 + 0x9ef6)
                #5  0x0000731065b47cb3 lua_pcall (libluajit-5.1.so.2 + 0x1ccb3)
                #6  0x000059e132cae4cd nlua_pcall (nvim + 0x1844cd)
                #7  0x000059e132cb7020 nlua_schedule_event (nvim + 0x18d020)
                #8  0x000059e132db3104 state_handle_k_event (nvim + 0x289104)
                #9  0x000059e132d0d792 nv_event (nvim + 0x1e3792)
                #10 0x000059e132d060f1 normal_execute (nvim + 0x1dc0f1)
                #11 0x000059e132db2f78 state_enter (nvim + 0x288f78)
                #12 0x000059e132d04a55 normal_enter (nvim + 0x1daa55)
                #13 0x000059e132ccb0cd main (nvim + 0x1a10cd)
                #14 0x000073106584ecd0 n/a (libc.so.6 + 0x25cd0)
                #15 0x000073106584ed8a __libc_start_main (libc.so.6 + 0x25d8a)
                #16 0x000059e132b73045 _start (nvim + 0x49045)
                
                Stack trace of thread 1539161:
                #0  0x00007310658b0ebe n/a (libc.so.6 + 0x87ebe)
                #1  0x00007310658b3750 pthread_cond_wait (libc.so.6 + 0x8a750)
                #2  0x0000731065a2ae7e uv_cond_wait (libuv.so.1 + 0x1fe7e)
                #3  0x0000731065a1dacf n/a (libuv.so.1 + 0x12acf)
                #4  0x00007310658b455a n/a (libc.so.6 + 0x8b55a)
                #5  0x0000731065931a3c n/a (libc.so.6 + 0x108a3c)
                
                Stack trace of thread 1539160:
                #0  0x00007310658b0ebe n/a (libc.so.6 + 0x87ebe)
                #1  0x00007310658b3750 pthread_cond_wait (libc.so.6 + 0x8a750)
                #2  0x0000731065a2ae7e uv_cond_wait (libuv.so.1 + 0x1fe7e)
                #3  0x0000731065a1dacf n/a (libuv.so.1 + 0x12acf)
                #4  0x00007310658b455a n/a (libc.so.6 + 0x8b55a)
                #5  0x0000731065931a3c n/a (libc.so.6 + 0x108a3c)
                
                Stack trace of thread 1539162:
                #0  0x00007310658b0ebe n/a (libc.so.6 + 0x87ebe)
                #1  0x00007310658b3750 pthread_cond_wait (libc.so.6 + 0x8a750)
                #2  0x0000731065a2ae7e uv_cond_wait (libuv.so.1 + 0x1fe7e)
                #3  0x0000731065a1dacf n/a (libuv.so.1 + 0x12acf)
                #4  0x00007310658b455a n/a (libc.so.6 + 0x8b55a)
                #5  0x0000731065931a3c n/a (libc.so.6 + 0x108a3c)
                
                Stack trace of thread 1539134:
                #0  0x0000000000000000 n/a (n/a + 0x0)
                ELF object binary architecture: AMD x86-64

### Steps to reproduce

nvim init.lua
wait 3 seconds
nvim crashed

### Expected behavior

keep running 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2968+g344906a08f Build type: RelWithDebInfo LuaJIT 2.1.1702233742

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux x86_64  6.8.1-arch1-1 

### Terminal name/version

kitty 0.33.0

### $TERM environment variable

xterm-256color

### Installation

6.8.1-arch1-1

**Comment by zeertzjq** [comment] 2024-04-22 01:33
Duplicate of #27906

**Closed by zeertzjq** 2024-04-22 01:33 UTC
Labels: bug
