### ISSUE TITLE
ctrl-c closes cmdline-window if ":term" is present

### ISSUE THREAD

**Issue by bohrshaw** [neovim/neovim#3494] opened 2015-10-25 09:17 UTC
Here's how to reproduce:
1. Run `nvim -Nu NORC +term`
2. Press `<C-\><C-n>q:k<C-c>`

Then the command prompt is hidden until another character is typed.

Edit: And sometimes, when there's a terminal buffer displayed in the current tab page, `q:<C-c>` also closes the cmdline-window.

**Comment by justinmk** [comment] 2017-01-20 00:51
Seems to be fixed.

**Comment by BohrShaw** [comment] 2017-01-20 01:19
Seems not for me. And it could be a different issue. @justinmk 
Execute command `nvim -u NORC +term +stopinsert` and type `q:k<C-c>`, the command-window is abnormally closed.

**Comment by agcosmin** [comment] 2019-06-24 18:31
Hello everyone,
(My name is Cosmin. I'm new to opensource and neovim but i like the project and would like to help as much as I can, hence I'm looking at the "good first issue" and "complexity:low".)
Regarding this issue: I cannot reproduce (:terminal buffer behaves like normal buffer) this on master HEAD (8c7e41f59) nor at the nightly (9ce34050e) tag but it is present at the v0.3.7 tag. I would consider this as fixed only that I don't know what's the relation between the release-0.3 branch and the master branch since their latest common ancestors is a commit from january. Because this situation (i.e. tested as fixed but reappeard later) seems to have happend in the past it leads me to think that there might be somthing related to the release build but I don't know how to test that since I'm not familiar with that procedure.
Any thoughts?

**Comment by bfredl** [comment] 2019-06-24 20:47
This might have been fixed by #9883 . We consider this a refactor (i e it might cause additional bugs, though so far there has been none) and not just a bugfix, so we don't include it in bugfix releases (v0.3.x)

**Comment by justinmk** [comment] 2019-06-24 21:04
Works on 8c7e41f596e6

**Closed by justinmk** 2019-06-24 21:04 UTC
Labels: :terminal, bug, complexity:low, good first issue
