### ISSUE TITLE
word-level diff

### ISSUE THREAD

**Issue by qstrahl** [neovim/neovim#3433] opened 2015-10-07 17:19 UTC
It would be nice if we could get word-level diff support -- a feature whose absence from vim has pained me for far too long. Right now, the following two lines would be diff-highlighted like so:

>the **quick brown fox jumps over the lazy** dog
>the **lazy brown fox jumps over the quick** dog

The actual change is much smaller than this leads one to believe. Ideally, we should have the option of highlighting the diff at word-level, like so:

>the **quick** brown fox jumps over the **lazy** dog
>the **lazy** brown fox jumps over the **quick** dog

Plenty of tools exist to generate these word-level diffs (git, wdiff, dwdiff...) -- nvim just has to digest and render them.

**Comment by ZyX-I** [comment] 2015-10-07 22:01
Duplicate of #1007.

**Closed by ZyX-I** 2015-10-07 22:01 UTC
Labels: duplicate

**Comment by qstrahl** [comment] 2019-09-02 22:02
@ZyX-I #1007 was closed without addressing this issue; is it time to re-open this?

**Comment by justinmk** [comment] 2019-09-02 22:35
xdiff was integrated, does it not support this? It is the same library used by git.

**Comment by qstrahl** [comment] 2019-09-03 03:26
I suppose it must! But to my knowledge, the diff highlighting does not make
use of it to highlight changes per-word rather than per-line.

**Comment by justinmk** [comment] 2019-09-03 11:15
@chrisbra do you recall any discussion about this?

**Comment by chrisbra** [comment] 2019-09-03 11:28
Nope, I don't think this was discussed in the past. I had a quick look at the git source and if I am not completely wrong, it seems, git splits the files by word boundaries, creating basically a diff of lines containing single words and joins them then together. 
Supporting this from within Vim would need some work and we cannot simply use `git diff --word-diff` as a `diffexpr`, since the output is not a unified diff.

**Comment by chrisbra** [comment] 2019-09-03 11:31
I am wondering however what is wrong with using https://github.com/rickhowe/diffchar.vim, doesn't that already do what you want?

**Comment by qstrahl** [comment] 2019-09-03 15:41
Nothing's wrong with it, per se - not to downplay @rickhowe's amazing work
with the plugin, but the lack of native support leads to some
inefficiencies and behavioural quirks that I don't think a plugin could
reasonably solve. The fact that a plugin author is effectively
re-implementing diff algorithms to adjust for the editor's highlighting I
think speaks to the need for the editor to behave differently.

**Comment by justinmk** [comment] 2019-09-03 15:57
In any case I am not in favor of reopening this because:

- #1007 was open for many years and no one took ownership of it.
- xdiff was dumped into the Vim codebase and complicates diverging from upstream Vim.

@chrisbra is the subject-matter expert here, it would make more sense for this request to be handled upstream.

**Comment by qstrahl** [comment] 2019-09-03 16:35
Fair enough! I'm inclined to agree, for what it's worth.

**Comment by ychin** [comment] 2025-03-26 23:30
See vim/vim#16881.
