### ISSUE TITLE
Custom margin between line numbers and text

### ISSUE THREAD

**Issue by malyutinegor** [neovim/neovim#9410] opened 2018-12-29 17:52 UTC
Can I customize space between line numbers and code?

**Comment by justinmk** [comment] 2018-12-29 17:58
Duplicate of https://github.com/neovim/neovim/issues/6092 

(to find that issue I searched for "margin" : https://github.com/neovim/neovim/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+margin )

**Closed by justinmk** 2018-12-29 17:58 UTC

**Comment by malyutinegor** [comment] 2018-12-29 17:59
It has not been updated since 2017
