### ISSUE TITLE
With `cmdheight=0 laststatus=3`, statusline is not shown when leaving insert mode

### ISSUE THREAD

**Issue by tomtomjhj** [neovim/neovim#23946] opened 2023-06-07 10:18 UTC
### Problem

With `cmdheight=0 laststatus=3`, the statusline disappears after entering and leaving the insert mode. 

### Steps to reproduce

1. `nvim --clean -c 'set cmdheight=0 laststatus=3'`
2. `i`
3. `<Esc>`. The statusline is gone.

### Expected behavior

Should show the statusline. For example, leaving the cmdline mode correctly displays the statusline.

### Neovim version (nvim -v)

0.8, a217675a67233ca2032cd668e919858d2aed92e7

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

ubuntu 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

tmux-256color

### Installation

appimage

**Comment by zeertzjq** [comment] 2023-06-07 10:22
Duplicate of #20667

**Closed by zeertzjq** 2023-06-07 10:22 UTC
Labels: bug
