### ISSUE TITLE
Undefined variable: a:1 (in autoload/vunde/scripts.vim)

### ISSUE THREAD

**Issue by GreenRaccoon23** [neovim/neovim#2477] opened 2015-04-21 20:11 UTC
I'm running Linux (64 bit Arch Linux). When running `:PluginUpdate`, I get this error:

    Error detected while processing function vundle#installer#new:
    line    1:
    E121: Undefined variable: a:1
    E15: Invalid expression: (a:1 == '') ? g:bundles : map(copy(a:000), 'vundle#conf
    ig#bundle(v:val, {})')
    Press ENTER or type command to continue

The error is in `~/.vim/Vundle.vim/autoload/vundle/scripts.vim`. I thought that it might have been messed up somehow or that I'd missed a Vundle update, so I manually git cloned this repo and overwrote the files in `~/.vim/Vundle.vim/`. This didn't fix it unfortunately.

This is the "Vundle" section of my .vimrc file:

	set nocompatible               " be iMproved
	filetype off                   " required!
	" set the runtime path to include Vundle and initialize
	set rtp+=~/.vim/bundle/Vundle.vim
	call vundle#begin()
	" alternatively, pass a path where Vundle should install plugins
	"call vundle#begin('~/some/path/here')

	" let Vundle manage Vundle, required
	Plugin 'gmarik/Vundle.vim'

	" The following are examples of different formats supported.
	" Keep Plugin commands between vundle#begin/end.
	" plugin on GitHub repo
	"Plugin 'tpope/vim-fugitive'
	" plugin from http://vim-scripts.org/vim/scripts.html
	"Plugin 'L9'
	" Git plugin not hosted on GitHub
	"Plugin 'git://git.wincent.com/command-t.git'
	" git repos on your local machine (i.e. when working on your own plugin)
	"Plugin 'file:///home/gmarik/path/to/plugin'
	" The sparkup vim script is in a subdirectory of this repo called vim.
	" Pass the path to set the runtimepath properly.
	"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
	" Avoid a name conflict with L9
	"Plugin 'user/L9', {'name': 'newL9'}
	" ...
	Plugin 'nsf/gocode', {'rtp': 'vim/'}
	Plugin 'fatih/vim-go'
	Plugin 'scrooloose/syntastic'
	Plugin 'majutsushi/tagbar'
	Plugin 'rjohnsondev/vim-compiler-go'
	Plugin 'dgryski/vim-godef'
	Plugin 'vim-jp/vim-go-extra'
	" All of your Plugins must be added before the following line
	call vundle#end()            " required
	filetype plugin indent on     " required! 
	" To ignore plugin indent changes, instead use:
	"filetype plugin on
	"
	" Brief help
	" :PluginList       - lists configured plugins
	" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
	" :PluginSearch foo - searches for foo; append `!` to refresh local cache
	" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
	"
	" see :h vundle for more details or wiki for FAQ
	" Put your non-Plugin stuff after this line

It used to work great. I haven't run `:PluginUpdate` in a while though. I'm not sure why it's acting up all of a sudden.

**Comment by glts** [comment] 2015-04-21 20:43
I don't see anything specifically about Neovim in your report. Unless I'm missing something, I think this is better suited for the [Vundle.vim bugtracker](https://github.com/gmarik/Vundle.vim/issues).

**Comment by Pyrohh** [comment] 2015-04-21 21:22
> I thought that it might have been messed up somehow or that I'd missed a Vundle update, so I manually git cloned this repo and overwrote the files in ~/.vim/Vundle.vim/. This didn't fix it unfortunately.

Did you remove `~/.vim/Vundle` before cloning again?

I can't reproduce this given the sample of the `.vimrc` you gave us (I assume you have it symlinked to `~/.nvimrc`?), and besides that I'm not sure how this is related to nvim, so I'll close this for now.

**Closed by Pyrohh** 2015-04-21 21:22 UTC
