### ISSUE TITLE
Lua: Unexpected behaviour using arrays/maps in vim.b

### ISSUE THREAD

**Issue by jbyuki** [neovim/neovim#12845] opened 2020-09-03 18:33 UTC
- `nvim --version`: v0.5.0-635-g8c49e3d50-dirty
- Operating system/version: Windows 10 64-bit

In a lua script, I'm executing this piece of code:

```lua
vim.b.list = {}
table.insert(vim.b.list, 3)
print(vim.inspect(vim.b.list))
```

### Actual behaviour

The 3 is not added to the list and an empty list is returned.
```
{}
```

### Expected behaviour

Should return the array with the 3.
```
{ 3 }
```

I tested the equivalent code in vimscript and it works. Is that caused by the list type? Other data types (numbers,...) work as expected.

**Comment by justinmk** [comment] 2020-09-05 20:30
The Lua-Vimscript bridge copies structures to/from Lua/Vimscript. There are no reference semantics.

Duplicate of https://github.com/neovim/neovim/issues/1898

**Closed by justinmk** 2020-09-05 20:30 UTC
Labels: bug

**Comment by bfredl** [comment] 2020-09-06 08:24
I think we do want `vim.lb[bufnr]` already (lua private map, erased on `bwipe`). @norcalli might has the code somewhere.
