### ISSUE TITLE
MacOS download missing on nightly release page

### ISSUE THREAD

**Issue by rockerBOO** [neovim/neovim#13022] opened 2020-10-01 13:51 UTC
On the https://github.com/neovim/neovim/releases/tag/nightly page, there is a note about a MacOS download. Seeing the assets list shows no `nvim-macos.tar.gz`.

![Screenshot_2020-10-01 Release NVIM 0 5 0 · neovim neovim](https://user-images.githubusercontent.com/15027/94817968-994ae980-03cb-11eb-900d-a770c1c70b0e.png)

I was responding to [this message on Reddit](https://www.reddit.com/r/neovim/comments/j38ook/neovim_050_on_mac/). They couldn't find the MacOS nightly release.

**Comment by jamessan** [comment] 2020-10-01 14:09
Duplicate of #13021

**Closed by jamessan** 2020-10-01 14:09 UTC
Labels: bug
