### ISSUE TITLE
Compilation fails on arm64 windows on gettext.

### ISSUE THREAD

**Issue by yashamon** [neovim/neovim#29534] opened 2024-07-01 23:50 UTC
### Problem 
The procedure to build on arm windows is more or less clear now. Open arm 64 native tools command prompt (search in Start). (Afterwards, execute pwsh or nu if you have it, to have a more comfortable interactive shell.)

Execute the building commands as described in the instructions: https://github.com/neovim/neovim/blob/master/BUILD.md

However:
Compilation fails on building gettext, compiling this directly also fails. 

### Steps to reproduce

The build procedure is standard and described above.

### Expected behavior

Compilation does not fail.

### Neovim version (nvim -v)

head

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows

### Terminal name/version

NA

### $TERM environment variable

NA

### Installation

NA

**Comment by dundargoc** [comment] 2024-07-02 11:12
Isn't this the same issue as https://github.com/neovim/neovim/issues/29416?

**Comment by clason** [comment] 2024-07-02 11:14
Duplicate of #29416

**Closed by clason** 2024-07-02 11:14 UTC
Labels: bug, build, platform:windows

**Comment by yashamon** [comment] 2024-07-02 15:19
I suggest that the other issue is closed and this reopened. As the former issue was asking for compiling instructions, and this issue states that this is actual bug.

**Comment by dundargoc** [comment] 2024-07-02 15:26
Can you not change the title of the other issue?

**Comment by clason** [comment] 2024-07-02 15:27
>  and this issue states that there is an actual bug.

This has not been confirmed yet; it could also be that the instructions need to be different on WARM.
