### ISSUE TITLE
When using `CTRL-R` mapping in command mode, a '"' + content after cursor will appear at the end

### ISSUE THREAD

**Issue by mars90226** [neovim/neovim#9932] opened 2019-04-22 11:35 UTC
- `nvim --version`: NVIM v0.4.0-614-g43356a43d
- Vim (version: ) behaves differently? yes
- Operating system/version: Ubuntu 18.04 Linux 4.18.20-041820-generic
- Terminal name/version: MobaXterm v11.1
- `$TERM`: xterm-256color. But in neovim, $TERM is screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:123<C-B><C-R>0
```

### Actual behaviour
The command line becomes `:123"123`

### Expected behaviour
The command line should be `:123`

And moving cursor to the left after using `CTRL-R` mapping will update the '"' to the location after cursor.
```
nvim -u NORC
:123<C-B><C-R>0<Right><Left>
```
### Actual behaviour
The command line becomes `:1"12323`

### Expected behaviour
The command line should be `:123`

And I've use git bisect to find that [this commit](https://github.com/neovim/neovim/commit/3b7a4f233bd53eb901904992227be3fffe5e621a) is the reason.
I should note that these additional texts are all virtual. It will not actually modified the command line text.
And using any mapping starting with `CTRL-R` will work.

**Comment by zgpio** [comment] 2019-04-22 12:11
# I tried these steps
```
nvim -u NORC
let @0 = 123
:<C-R>0
then use <left> to move cursor, I find cmdline render issue.
```

**Comment by justinmk** [comment] 2019-04-23 10:35
Duplicate of https://github.com/neovim/neovim/issues/9917

**Closed by justinmk** 2019-04-23 10:35 UTC

**Comment by mars90226** [comment] 2019-04-23 11:49
Yes, sorry for the duplicate issue.
