### ISSUE TITLE
After using `tcd`, tabs created after temporarily also use that working directory

### ISSUE THREAD

**Issue by drifkin** [neovim/neovim#5082] opened 2016-07-17 20:54 UTC
- `nvim --version`: 
```
NVIM 0.1.4
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160611-52187-1w1qv7r/neovim-0.1.4/build/config -I/tmp/neovim-20160611-52187-1w1qv7r/neovim-0.1.4/src -I/tmp/neovim-20160611-52187-1w1qv7r/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160611-52187-1w1qv7r/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160611-52187-1w1qv7r/neovim-0.1.4/deps-build/usr/include/luajit-2.0 -I/tmp/neovim-20160611-52187-1w1qv7r/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160611-52187-1w1qv7r/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160611-52187-1w1qv7r/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160611-52187-1w1qv7r/neovim-0.1.4/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160611-52187-1w1qv7r/neovim-0.1.4/build/src/nvim/auto -I/tmp/neovim-20160611-52187-1w1qv7r/neovim-0.1.4/build/include
Compiled by devon@local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.4/share/nvim"
```

- Vim (version: ) behaves differently?: n/a: the `tcd` command doesn't exist in vim

- Operating system/version: 10.11.5
- Terminal name/version: iTerm2 Build 2.9.20160510
- `$TERM`: `xterm-256color`

### Actual behaviour

Suppose the current working directory is some dir X. A new tab is created using `:tabnew`, and then `tcd` is used to change its working directory to a different one, say dir Y. `:tabnew` is used again to create another tab. The new tab will have a working directory of dir Y. Switching away and then back to this tab will then have it switch to its expected working directory of dir X.

Note that this isn't just a a bug with the `:pwd` command, the actual working directory appears to be incorrect (when testing with `:edit`, for example).

### Expected behaviour

When creating a new tab, its working directory should be the global working directory (in this case, dir X).

It is also expected that leaving a tab and then coming back to it does not change its working directory.

### Steps to reproduce using `nvim -u NORC`

1. `mkdir -p /tmp/dir-x`
2. `mkdir -p /tmp/dir-y`
3. `cd /tmp/dir-x`
4. `nvim -u NORC`
5. `:pwd` will produce "/tmp/dir-x", as expected
6. `:tabnew`
7. `:tcd /tmp/dir-y`
8. `:pwd` will produce "/tmp/dir-y", as expected
9. `:tabnew`
10. `:pwd` will produce "/tmp/dir-y", which is **not** expected
11. `gT`
12. `gt`
13. `:pwd` will produce "/tmp/dir-x", which is what we originally expected to happen, but this is confusing that it switched to this

**Comment by ZyX-I** [comment] 2016-07-17 21:47
I would say that “leaving a tab and then coming back” should not alter working directory (obviously, unless autocommands are created that alter this behaviour). But I would not agree with using global directory for new tab if it is created from the tab that has tab-local directory: when creating a new window window-local directory is inherited from the current window, if any.

**Comment by drifkin** [comment] 2016-07-17 22:57
What you're saying does seem reasonable to me (that the actual bug is that the new tab ever switches to the global working directory). It does make me wonder what should happen in this situation with "nesting": create a new tab, use `:tcd`, then create a new window within the tab, use `:lcd` with a different directory and then create a new tab with `:tabnew`. What should the working directory of the new tab be? Should it depend on which window we had active before we used `:tabnew`? Or should it always be the directory we specified with `:tcd`?

I just tried it out and it looks like the current behavior is to inherit the directory specified with `:lcd`, if that was the active window upon tab creation. Otherwise, it follows the same behavior in my original post.

**Comment by ZyX-I** [comment] 2016-07-17 23:01
I actually think that it would be logical if new window (you cannot create a new tab without creating a new window) inherits from the window (in Vim it already does), new tab inherits from the tab. So basically you will see that current directory is from the window, but both tab-local and window-local directories are actually set which can be checked with `getcwd()` if needed (e.g. in tests).

**Comment by drifkin** [comment] 2016-07-17 23:08
The behavior you're describing sounds good to me.

**Comment by justinmk** [comment] 2016-08-10 00:04
@hiphish Any chance you could look at this?

**Comment by HiPhish** [comment] 2016-08-10 22:45
I won't have time for the next few days, I'm attending this year's GUADEC, but I can look into it later. My beef with Vim is that there is not much encapsulation going on, you have global variables all over the place, resulting in an ugly spaghetti of "check these variable to find out if something is, then check that variable of there and so on". I did not change anything about it because that would have been a more invasive procedure than I dared at that point.

**Comment by HiPhish** [comment] 2016-08-15 21:51
I tried it and I can confirm the bug. The first question is what behaviour should we settle on? Should a new tab inherit the working directory of the current tab or that of the editor?

Here is how I see it: when creating a new window we can either use `new` or `split`. The former creates a new blank window while the latter creates a new window with the same buffer as the window the command was called from. It's obvious that in the case of `split` the window should inherit the local working directory. The use of `new` is similar to that of `tabnew`, so we should replicate the behaviour of `new` for the sake of consistency, which is to inherit the local working directory.

Personally I think that's the wrong thing to do. When I request a *new* window I expect the window to be pristine, not carry the baggage of another window with it. Worse, this kind of baggage is invisible to the user until they try to run a command and wonder why it isn't working properly. Sadly the choice has already been made by Bram and we can decide to either follow suit or break compatibility with Vim by "fixing" `new`. However, whether we change or keep `new`, `tabnew` has to mimic its behaviour for the least surprise.

**Comment by justinmk** [comment] 2016-08-15 23:24
tabnew should inherit the CWD.

In either case a mapping can change the behavior, so the choice seems arbitrary; and as you say consistency is paramount in absence of any strong reason for inconsistency.

**Comment by justinmk** [comment] 2016-08-15 23:27
But note the finer details in https://github.com/neovim/neovim/issues/5082#issuecomment-233209382. I agree with that comment.

**Comment by HiPhish** [comment] 2016-08-16 09:45
I think I fixed it, it was just a one-line fix. I'll run tests and lint, then I'll file a PR.

**Comment by HiPhish** [comment] 2016-08-16 11:11
PR is up at #5227

**Comment by hkupty** [comment] 2016-09-01 19:08
Is this PR going to be merged? I'm having issues with wrong `pwd` after `tcd`. It's a slightly different use scenario, but I think it might be solved by the same PR.

**Comment by HiPhish** [comment] 2016-09-01 19:46
I just rebased the PR on the current upstream/master, so as far as I'm concerned everything is good to go.

**Closed** 2016-09-04 01:40 UTC
Labels: bug, ux
