### ISSUE TITLE
Faster way to close long messages.

### ISSUE THREAD

**Issue by shadmansaleh** [neovim/neovim#14108] opened 2021-03-11 17:44 UTC
### Idea
Adding a simple map to close messages without scrolling. currently `<space>` and `q` scroll by page in message window. What I would like to propose is to add a keymap similar to these that quits the message window and get to editor instently. `q` / `<esc>` seems like a good candidate  to me.

### Reasoning
I use `vim.inspect` with `print` quite often . It make it really easy to see the contents of table to debug or to understand the table structure. But it also makes it  very easy to get stuck in long messages. Alot of times I will use `print(vim.inspect())` on tables without having any idea  about their depth . Deep tables especially class implementations in lua can generate really long  message output with `inspect`. After that only way to get out of messages is long scrolling . It's really annoying when it happens and I'm sure I'm not the only one who has faced it . So adding an instant way to exit messages will be very useful. This can also happen if message log just got really long over long use period.

### Steps to reproduce
```vim
:lua print(vim.inspect(vim))
```

**Comment by saadparwaiz1** [comment] 2021-03-11 18:08
Can't you just use G?

**Comment by shadmansaleh** [comment] 2021-03-11 18:18
> Can't you just use G?

Thanks. I didn't know that map worked in messages . I assumed it didn't . Though it will still probably be nice if their was some hint for that.

Though the guide that appears at messages:
> -- More -- SPACE/d/j: screen/page/line down, b/u/k: up, q: quit

says `q` quits but it scrolls 😅

**Comment by andymass** [comment] 2021-03-11 18:24
There is a difference between:

    lua print(vim.inspect(vim))

and:

    echo luaeval('vim.inspect(vim)')

In the latter, q quits in the former it scrolls.

**Comment by shadmansaleh** [comment] 2021-03-11 18:27
> In the latter, q quits in the former it scrolls.

Shouldn't they act the same ?
It seems
```vim
echom luaeval('vim.inspect(vim)')
```
scrolls too/

**Comment by devbhansingh** [comment] 2021-04-16 07:17
I'd like to work on this issue.

**Comment by glacambre** [comment] 2021-06-10 15:53
Closing as duplicate of https://github.com/neovim/neovim/issues/11224 , which links to a PR that would implement this :).

**Closed by glacambre** 2021-06-10 15:53 UTC
Labels: enhancement

**Comment by shadmansaleh** [comment] 2021-06-10 17:33
@glacambre thanks for finding the previous issue :) . I thought of working on think but then started using `G` and forgot all about this :P
