### ISSUE TITLE
`++p` for `:write` doesn't work with `vim.cmd`

### ISSUE THREAD

**Issue by musjj** [neovim/neovim#23949] opened 2023-06-07 17:50 UTC
### Problem

Running `vim.cmd.write("++p")` (which is supposed to be the equivalent of `:write ++p`), will write into a file called `++p` instead of saving the current file.

I've also tried double checking with `vim.api.nvim_parse_cmd(":write ++p", {})` and it seems that the argument structure is supposed to be correct.

### Steps to reproduce
```shell
nvim --clean some/file
:lua vim.cmd.write("++p")
```

### Expected behavior

Save the current file while ensuring that the parent directories are created.

### Neovim version (nvim -v)

v0.10.0-dev-411+g9dd48f783

### Vim (not Nvim) behaves the same?

`vim.cmd` is not available in vim

### Operating system/version

Linux

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

bob

**Comment by zeertzjq** [comment] 2023-06-07 21:56
Duplicate of #21687

**Closed by zeertzjq** 2023-06-07 21:56 UTC
Labels: bug
