### ISSUE TITLE
seems `vim.api.nvim_buf_set_extmark` is based on window default

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#25218] opened 2023-09-17 14:47 UTC
### Problem

seems `vim.api.nvim_buf_set_extmark` is based on window default

### Steps to reproduce

![Screenshot from 2023-09-17 22-39-53](https://github.com/neovim/neovim/assets/97107165/2978d60d-c12c-4a5b-85a3-7fc28fcd4a6f)
:so<CR>
![Screenshot from 2023-09-17 22-41-12](https://github.com/neovim/neovim/assets/97107165/34bd9c2f-3b30-4b5b-b914-db59aa78bd36)
move the cursor to line-end
![Screenshot from 2023-09-17 22-41-57](https://github.com/neovim/neovim/assets/97107165/1c2a671b-8480-4d57-a703-2196cfc9cfb8)
as you can see, the `virt text` is moving while the cursor moving to the end.

`virt text` should be based on buffer. not window(as you can see, i didn't set the virt_text_win_col)          
 • virt_text_win_col : position the virtual text at a fixed
                    window column (starting from the first text column of the
                    screen line) instead of "virt_text_pos".

### Expected behavior

virt text not moving

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1134+g677df72e4 Build type: Release LuaJIT 2.1.1694940244 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

guess no.

### Operating system/version

Linux

### Terminal name/version

Kitty

### $TERM environment variable

xterm256

### Installation

Compiled manually

**Comment by zeertzjq** [comment] 2023-09-17 22:48
Duplicate of #14050

**Closed by zeertzjq** 2023-09-17 22:48 UTC
Labels: bug
