### ISSUE TITLE
macOS: build failure `passing 'VTermStringFragment' to parameter of incompatible type 'char *'`

### ISSUE THREAD

**Issue by dhruvmanila** [neovim/neovim#17253] opened 2022-01-31 04:27 UTC
### Neovim version (nvim -v)

0.7.0 commit 2870311a37314135b73e0ee54b41da86c9540a39 (latest master)

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.1

### Terminal name/version

kitty 0.24.1 created by Kovid Goyal

### $TERM environment variable

xterm-kitty

### Installation

build from repo / homebrew

### How to reproduce the issue

Build from repo
1. `git clone https://github.com/neovim/neovim`
2. `make distclean`
3. `make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=~/neovim" install`

Homebrew
1. `brew install --HEAD neovim`

### Expected behavior

It should build without any compile errors.

### Actual behavior

```
[309/348] Building C object src/nvim/CMakeFiles/nvim.dir/terminal.c.o
FAILED: src/nvim/CMakeFiles/nvim.dir/terminal.c.o 
/Library/Developer/CommandLineTools/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -Dnvim_EXPORTS -I/Users/dhruv/contributing/neovim/build/config -I/Users/dhruv/contributing/neovim/src -I/Users/dhruv/contributing/neovim/build/src/nvim/auto -I/Users/dhruv/contributing/neovim/build/include -I/Users/dhruv/contributing/neovim/.deps/usr/include/luajit-2.1 -isystem /Users/dhruv/contributing/neovim/.deps/usr/include -isystem /usr/local/opt/gettext/include -I/usr/local/include -I/usr/local/opt/openssl@3/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -DNDEBUG -flto=thin -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -MD -MT src/nvim/CMakeFiles/nvim.dir/terminal.c.o -MF src/nvim/CMakeFiles/nvim.dir/terminal.c.o.d -o src/nvim/CMakeFiles/nvim.dir/terminal.c.o -c /Users/dhruv/contributing/neovim/src/nvim/terminal.c
/Users/dhruv/contributing/neovim/src/nvim/terminal.c:850:29: error: passing 'VTermStringFragment' to parameter of incompatible type 'char *'
    buf_set_term_title(buf, val->string);
                            ^~~~~~~~~~~
/Users/dhruv/contributing/neovim/src/nvim/terminal.c:821:50: note: passing argument to parameter 'title' here
static void buf_set_term_title(buf_T *buf, char *title)
                                                 ^
1 error generated.
[318/348] Building C object src/nvim/CMakeFiles/nvim.dir/regexp.c.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:92: nvim] Error 1
```

**Comment by zeertzjq** [comment] 2022-01-31 04:30
Duplicate of #16217

**Closed by zeertzjq** 2022-01-31 04:30 UTC
Labels: bug
