### ISSUE TITLE
Using <C-c> to abort a vim.fn.input() prompt causes E5108 error instead of returning 0

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#23067] opened 2023-04-13 18:22 UTC
### Problem

Docs for `:h confirm()` says:

```
		If the user aborts the dialog by pressing <Esc>, CTRL-C,
		or another valid interrupt key, confirm() returns 0.

```

But it instead throws an error when used via `vim.fn.input()`

Related: https://github.com/neovim/neovim/issues/18144

This behaviour is mentioned there, but according to the docs this is not the correct behaviour (throwing an error). I see some code in the runtime secure.lua file that looks to have been written with this behaviour in mind. Are the docs wrong? Searched issues but only found that one issue that seemed relevent.

### Steps to reproduce

nvim --clean
:lua print(vim.fn.confirm('yes or no?', '&yes\n&no', 1))

try out hitting enter, should print 1, try it out with 'y' and 'n' keys to get 1 and 2 as expected, cancel the prompt with Esc, you get 0 printed as expected, now try <C-c> and an error will throw:

```
E5108: Error executing lua Keyboard interrupt
stack traceback:
        [C]: in function 'confirm'
        [string ":lua"]:1: in main chunk
```

### Expected behavior

0 is printed

### Neovim version (nvim -v)

0.10.0 commit gf4136c9d4

### Vim (not Nvim) behaves the same?

maybe

### Operating system/version

macOS 12.6.3

### Terminal name/version

Wezterm

### $TERM environment variable

wezterm

### Installation

build from repo

**Comment by Mike325** [comment] 2023-04-14 11:17
it's not the same behavior at least for Vim `8.1.4599` the prompt can be dismissed with both `<C-c>` and `<ESC>`

**Comment by zeertzjq** [comment] 2023-04-14 11:32
Duplicate of #16416

**Closed by zeertzjq** 2023-04-14 11:32 UTC
Labels: bug, lua
