### ISSUE TITLE
`stty: stdin isn't a terminal source` when pasting text when clipboard=unnamed

### ISSUE THREAD

**Issue by firedev** [neovim/neovim#2662] opened 2015-05-15 08:02 UTC
Hi, 

Just tried neovim after a while, glad to see the system clipboard is working. However I have 
`set clipboard=unnamed` in `.vimrc` and every time I copy and paste text inside nvim I see the following line appended on top:
```
stty: stdin isn't a terminal
```
Unsetting clipboard fixes this but maybe there is a better way?

PS. In fact every shell comand seem to prefix itself with stty warning.
```
:!ls
stty: stdin isn't a terminal
Press ENTER or type command to continue
```

**Comment by tarruda** [comment] 2015-05-15 10:39
Any chance your shell tries to set terminal attributes with stty? Nvim uses pipes to execute shell commands.

**Comment by bfredl** [comment] 2015-05-15 15:31
Now that `system()` takes an argv we could just stop using the shell on clipboard actions. I should revive #2077 ...

**Comment by firedev** [comment] 2015-05-16 01:08
Shell commands do work and the message is not affecting anything. But I can't copy and paste in NeoVim. Clipboard looks like this:
```
"*   stty: stdin isn't a terminal^Jtest^J
"+   stty: stdin isn't a terminal^Jtest^J
".   test^@
```

I had this in my .zsh to be able to use Ctrl-S in Vim:
```
# Disable flow control commands (keeps C-s from freezing everything)
stty start undef
stty stop undef
```
But even after commenting it out, nothing changed. Where else can I look? Vim is not affected.

**Comment by firedev** [comment] 2015-05-16 03:49
Another suspect was `rettach-to-user-namespace` in `.tmux.conf` but this one is commented out as well:
```
# set-option -g default-command "reattach-to-user-namespace -l zsh"
```

**Comment by bfredl** [comment] 2015-05-16 08:54
`.zshrc` should only affect affect an interactive shell (not `:!` or `system()`), do you have an `.zshenv` ?

**Comment by tarruda** [comment] 2015-05-18 08:36
> But even after commenting it out, nothing changed. Where else can I look? Vim is not affected.

I suggest to use "binary search" in your zshrc to find the problem. First confirm that the problem is indeed in your shell initialization files by starting it with `zsh -d -f`, then keep commenting sections of your zshrc/zprofile until you isolate the problem.

**Comment by firedev** [comment] 2015-05-19 01:13
Thanks @bfredl, forgot about `.zshenv` I had `stty -ixon` in there. Removing that fixed the issue. But it is up to you to decide if this ticked should be closed or not.

**Comment by bfredl** [comment] 2015-05-19 13:27
@firedev if you want you could try #2703 which should work even with the line in `.zshenv`. (disregard any `DEBUG:` message)

**Comment by frdeso** [comment] 2015-06-02 17:35
I have a similar issue with Fish shell. I run Archey in my config.fish file to print system usage when I open a terminal and whenever I try to paste a line I just yanked I get the Archey output followed by the yanked line. This issue is also triggered when I run a command like <pre>!pwd</pre> example output: http://i.imgur.com/DyP3z2M.png

This happens when I <pre>set clipboard=unnamed</pre> Trying the changes suggested in [#2703](https://github.com/neovim/neovim/pull/2703) and it fixes the pasting issue but not the "!" commands issue.

**Comment by firedev** [comment] 2015-06-04 04:47
Thanks @bfredl however I am not 100% sure how to install nvim manually, I am just enjoying `brew install --HEAD` so I'll wait till it's merged in master.

**Comment by firedev** [comment] 2015-06-09 05:44
I have reinstalled from --HEAD and it's working fine now. Switched exclusively to neovim now. The only thing that doesn't work still is cursor shape change, but that is irrelevant.

**Comment by justinmk** [comment] 2015-08-17 07:43
fixed by https://github.com/neovim/neovim/pull/2703

**Closed by justinmk** 2015-08-17 07:43 UTC
Labels: clipboard
