### ISSUE TITLE
Single line scrolling for wrapped lines

### ISSUE THREAD

**Issue by unclechu** [neovim/neovim#12801] opened 2020-08-28 01:36 UTC
It has always been an anti-feature of Vim for me that when you `set wrap` and try to scroll line by line (e.g. by pressing `CTRL-E`/`CTRL-Y`) the screen sometimes jumps with huge pace (few *visible* lines at once). This happens when a wrapped line reaches the top of the screen. So both Vim and Noevim are scrolling by *real lines* whilst I want to scroll by virtual, *visible* lines, which would be a lot more intuitive to me.

It’s probably some historical decision, maybe it has something to do with backward compatibility. But maybe it’s possible to implement it these days in Neovim? Since Neovim is supposed to be the modern and more flexible Vim. Maybe it’s at least possible by implementing some GUI? Maybe such GUI exists?

**Comment by justinmk** [comment] 2020-08-30 06:57
- duplicate of https://github.com/neovim/neovim/issues/8715
- significant work was done in https://github.com/neovim/neovim/pull/11014

**Closed by justinmk** 2020-08-30 06:57 UTC
Labels: enhancement
