### ISSUE TITLE
Syntax highlighting for code in the help text.

### ISSUE THREAD

**Issue by dundargoc** [neovim/neovim#17855] opened 2022-03-25 17:36 UTC
### Feature already in Vim?

No

### Feature description

Code in the documentation doesn't have syntax highlighting, which makes it a bit tough for me to follow. Usually this is fine, but in some extreme cases it's pretty unwieldy. The workaround I currently do is to copy the text to a new file and enable syntax highlighting that way. As workarounds go this is pretty solid, but I still think it'd be a Nice Idea ™ if this was built in.

**Comment by dundargoc** [comment] 2022-03-25 17:41
I couldn't find a plugin that did this (not sure if it's even possible without changes to core). Let me know if there is something out there.

**Comment by clason** [comment] 2022-03-25 17:45
Tree-sitter? (vimdoc parser plus whatever languages you want to highlight?)

**Comment by dundargoc** [comment] 2022-03-25 17:50
Doesn't that require knowledge of tree-sitter, nvim-treesitter, neovim, scheme and probably something else I don't know yet?

**Comment by clason** [comment] 2022-03-25 17:52
Well, yes, but I don't know what else to tell you. You know as well as I that the help syntax files themselves are maintained by upstream, so adding code block support is an issue you'd have to raise at vim/vim.

**Comment by mjlbach** [comment] 2022-03-25 17:55
Semi-related: https://github.com/neovim/neovim/issues/329

**Comment by dundargoc** [comment] 2022-03-25 18:05
> help syntax files themselves are maintained by upstream,

I know, I was just unsure if I should post there since this seemed suited to treesitter.

**Comment by clason** [comment] 2022-03-25 18:09
It is, but Work Is Needed. There is a parser (https://github.com/vigoux/tree-sitter-vimdoc), but I don't think it has injections yet. @vigoux ?

**Comment by clason** [comment] 2022-03-25 18:17
The big problem, however, is that there is no way to tell what the language of a code block is (or whether it is a proper language, at all). So in the end, the only robust solution would be to switch to a new "nvimdoc" format that is based on a light Markdown or RST flavor (with a proper specification).

**Comment by dundargoc** [comment] 2022-03-25 18:41
It's difficult for me to gauge at which point the usefulness of using a more modern/used documentation format outweighs the hassle of converting from vimdoc to said format. I know there was talk of a vimdoc to markdown converter, but I'm not sure of the current status yet.

**Comment by dundargoc** [comment] 2022-03-25 18:46
Yes, you're right.

I'm unsure as to what to do with this issue. If this isn't actionable/useful then I wouldn't mind closing it down.

**Comment by clason** [comment] 2022-03-25 18:56
I'd say your desire is widely shared, but a more useful issue would focus on one potential remedy -- three come to mind (treesitter support for vimdoc, codeblock highlighting in the syntax file, switching to our own help file format), only one of which (new file format) is properly actionable for Neovim. But this would go beyond what you asked for and should probably be opened as a dedicated issue. (I don't think it's a duplicate of #329, though.)

Personally, I'd like to wait with opening such a suggestion until I have a clearer idea of its rough shape, to avoid a needless free-for-all bikeshedding frenzy...

**Comment by clason** [comment] 2022-03-26 17:53
> Doesn't that require knowledge of tree-sitter, nvim-treesitter, neovim, scheme and probably something else I don't know yet?

Not anymore -- you can test it out with https://github.com/nvim-treesitter/nvim-treesitter/pull/2679

**Comment by dundargoc** [comment] 2022-03-26 21:09
O_O

SHIPIT!

**Comment by dundargoc** [comment] 2022-03-26 21:11
Works shockingly well for a first draft. I'd consider this issue resolved if that were merged.

**Comment by clason** [comment] 2022-03-26 21:14
Well, this hardcodes ALL cod blocks as Lua, with predictably catastrophic results for Vimscript and other code....

**Comment by dundargoc** [comment] 2022-03-26 21:15
Oh. I might have jumped the gun in that case then since I only looked at the lua code :)

**Comment by clason** [comment] 2022-03-26 21:18
I thought you would, which is why I didn't hard code it as Vimscript ;)

**Comment by justinmk** [comment] 2022-09-23 15:24
Tracked in https://github.com/vigoux/tree-sitter-vimdoc/issues/2

**Closed by justinmk** 2022-09-23 15:24 UTC
Labels: enhancement
