### ISSUE TITLE
arab on :terminal segfaults nvim

### ISSUE THREAD

**Issue by Al-Caveman** [neovim/neovim#12061] opened 2020-03-27 18:22 UTC
- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```
- `vim -u DEFAULTS` (version: ) behaves differently?  why is `vim` related? ya sure `vim` behaves differently.  jeez what's wrong with u..   or do u mean `nvim -u NONE`?  then this bug still exists (there is segfault).  *update: vim doesn't segfault.  just looks uglier (has a window split).*
- Operating system/version: `Linux getac 5.5.11-arch1-1 #1 SMP PREEMPT Sun, 22 Mar 2020 16:33:15 +0000 x86_64 GNU/`
- Terminal name/version: `alacritty 0.4.1`
- `$TERM`: `alacritty`

### Steps to reproduce

1. run nvim, 
2. `:terminal`,
3.  `i`, 
4. htop `<ENTER>`, 
5. c-\ c-n, 
6. `:set arab`,
7. profit!

### Actual behaviour
`fish: 'nvim' terminated by signal SIGSEGV (Address boundary error)`

### Expected behaviour
happy _arab_ mode.

**Comment by bfredl** [comment] 2020-03-27 18:36
likely this is duplicate of https://github.com/neovim/neovim/issues/11438. Fixed on master and release-0.4 (for future 0.4.4 release) in https://github.com/neovim/neovim/pull/11460.

**Closed by bfredl** 2020-03-27 18:36 UTC
Labels: bug

**Comment by lacygoill** [comment] 2020-03-27 19:19
Can reproduce on master with:

    nvim -u NONE --cmd 'set scl=yes:1 rtp-=~/.vim rtp-=~/.vim/after | syn enable' +'term htop' +'set arab'

But only with a `Release` build type; which gives a [backtrace](https://github.com/neovim/neovim/files/4395478/backtrace.txt) with not much info.

**Comment by bfredl** [comment] 2020-03-27 20:22
@lacygoill the reproduce there is quite different. Please open a new issue.
