### ISSUE TITLE
Errors from running `git commit` inside Neovim terminal

### ISSUE THREAD

**Issue by ajhynes7** [neovim/neovim#16504] opened 2021-12-02 22:08 UTC
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.0.1

### Terminal name/version

iterm2/3.4.14

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

```sh
$ nvim --clean
```

In Neovim:
```
:terminal
```

```sh
# Inside Neovim terminal
$ git commit
```

### Expected behavior

This should open a vi editor so you can write a commit message.

### Actual behavior

After running `git commit`, the following errors appear:

```
E10: \ should be followed by /, ? or &
Error detected while processing /usr/local/Cellar/neovim/0.6.0/share/nvim/runtime/plugin/rplugin.vim[65]..function <SNR>10_LoadRemotePlugins[1]..<SNR>10_GetManifest[1]..<SNR>10_GetManifestPath:
line    7:
E117: Unknown function: stdpath
--- Autocommands ---
Error detected while processing /usr/local/Cellar/neovim/0.6.0/share/nvim/runtime/plugin/shada.vim:
line    9:
E10: \ should be followed by /, ? or &
line   10:
E10: \ should be followed by /, ? or &
line   11:
E10: \ should be followed by /, ? or &
```

It continues on like that for more lines.

**Comment by zeertzjq** [comment] 2021-12-02 22:25
Duplicate of #6764

**Closed by zeertzjq** 2021-12-02 22:25 UTC
Labels: bug

**Comment by zeertzjq** [comment] 2021-12-02 22:30
You can alias `git` as `VIMRUNTIME= command git` in your shell as a workaround.

**Comment by jamessan** [comment] 2021-12-03 01:52
> You can alias `git` as `VIMRUNTIME= command git` in your shell as a workaround.

Setting `EDITOR=nvim` sounds like a more general fix.
