### ISSUE TITLE
Clipboard error on unnamedplus

### ISSUE THREAD

**Issue by w3bdev1** [neovim/neovim#14967] opened 2021-07-03 07:58 UTC
- `nvim --version`: v0.5.0
- Operating system/version: Void Linux

### Steps to reproduce
- Open a fresh terminal
- Create a config file with clipboard set to unnamedplus : `echo "set clipboard=unnamedplus" > /tmp/init.vim`
- Now open nvim with this config : `nvim -u /tmp/init.vim`
- Check `:registers`

### Actual behaviour
- Following error pops up
```
clipboard: error: Error: target STRING not available
Error detected while processing function provider#clipboard#Call[6]..2:
E691: Can only compare List with List
E15: Invalid expression: match(&clipboard, '\v(unnamed|unnamedplus)') >= 0 && get(s:selections[a:reg].data, 0, []) == clipboard_data
clipboard: provider returned invalid data
Error detected while processing function provider#clipboard#Call[6]..2:
E691: Can only compare List with List
E15: Invalid expression: match(&clipboard, '\v(unnamed|unnamedplus)') >= 0 && get(s:selections[a:reg].data, 0, []) == clipboard_data
clipboard: provider returned invalid data
```

### Expected behaviour
- No error should appear.

**Comment by clason** [comment] 2021-07-03 08:50
Can you try with latest master? That could be fixed by https://github.com/neovim/neovim/pull/14962.

@shadmansaleh

**Comment by shadmansaleh** [comment] 2021-07-03 08:53
I can't reproduce it . @clason @bfredl can you see if this happens for you?

@w3bdev1 what clipboard provider do you have `xcel`/`xclip` or something else?

**Comment by clason** [comment] 2021-07-03 09:01
I can't reproduce either (I'm on macOS with `pbcopy`/`pbpaste`.)

**Comment by w3bdev1** [comment] 2021-07-03 09:14
I have `xclip`. @shadmansaleh

**Comment by bfredl** [comment] 2021-07-03 09:14
> clipboard: error: Error: target STRING not available

sounds like an actual error from your clipboard provider tool

> Error detected while processing function provider#clipboard#Call[6]..2:
E691: Can only compare List with List
E15: Invalid expression: match(&clipboard, '\v(unnamed|unnamedplus)') >= 0 && get(s:selections[a:reg].data, 0, []) == clipboard_data

seems like subsequently caused error by not properly handling the first, which we should avoid.

**Comment by w3bdev1** [comment] 2021-07-03 09:58
It is happening when my device is freshly booted, i.e., system clipboard is completely empty. 
But when I copy from other window to clipboard, those gets stored into `*` and `+` registers and those error are not present.

Clipboard provider: xclip
Clipboard manager: clipmenu

**Comment by shadmansaleh** [comment] 2021-07-03 10:03
Ok I got it I think . Your clipboard is empty that's why xclip is throwing error when you try to retrive it.

This function
https://github.com/neovim/neovim/blob/d791274a9d9b87dec5bd024904424e1ce21de5a6/runtime/autoload/provider/clipboard.vim#L37-L49 returns 0 for error . That's why the comparism is failing .

@w3bdev1  can you try changing line 46 of `$VIMRUNTME/autoload/provider/clipboard_provider.vim` like following and see if it works then

```diff
- return 0
+ return []
```

@bfredl will it not be better to return  same type from `try_cmd` for error_code too ?

**Comment by w3bdev1** [comment] 2021-07-03 10:24
After changing the return statement the large chunk of error is gone, regarding the list comparison.
Only one line remians: `clipboard: error: Error: target STRING not available`
@shadmansaleh

**Comment by shadmansaleh** [comment] 2021-07-03 10:28
That one will remain . As it's emited by xclip . We are just forwarding it .

**Comment by shadmansaleh** [comment] 2021-07-04 14:35
Fixed in #14984.

@w3bdev1 you can try that branch .

**Comment by w3bdev1** [comment] 2021-07-04 14:47
Thanks.

**Comment by shadmansaleh** [comment] 2021-07-04 15:06
Did you try it ?

You probably should have waited till the pr got merged before closing this :D

**Closed** 2021-07-11 13:19 UTC
Labels: bug, topic: clipboard
